### ISSUE TITLE
Give Fields access to the Form and the Model

### ISSUE THREAD

**Issue by axyr** [z-song/laravel-admin#10]
I will come up with better PR's soon, but I need a crashcourse for that first.

I have some extended form fields, where I want to do more with a Model then only write a value to the column. like setting other values based upon the submission, and this needs to be done before a value is set on a model.

There is a lot of flexiblilty if we could have access to the Form and Model in the Form Fields and can be done pretty easy to add this to the forms:

- Make model public : 
```php
    /**
     * @return Model
     */
    public function model()
    {
        return $this->model;
    }
```
- pass the Form object to the form fields : 

```php
    /**
     * @param Field $field
     *
     * @return $this
     */
    public function pushField(Field $field)
    {
        $field->setForm($this);

        $this->builder->fields()->push($field);

        return $this;
    }
```
and change the line in __call()

```php
$this->builder->fields()->push($element);
```
to this : 

```php
$this->pushField($element);
```

**Comment by lyd600lty** [comment]
@axyr It doesn't work...

**Comment by axyr** [comment]
@lyd600lty could be.. this suggestion is a year old...
