### ISSUE TITLE
from表單裏有wang editor，刪除圖片時報錯

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#1004]
![qq 20170720172352](https://user-images.githubusercontent.com/9032762/28411060-3e975b1a-6d72-11e7-95ac-472cf84272c2.png)
請問是什麼問題？

**Comment by chenlixin93** [comment]
很明显你是编辑器js 引用出错了呗。只需要在自定义的组件里面引用就行了，然后注意你项目里面的命名空间之间的关系不要出错，最好把console 打开看看还出现什么问题，因为貌似我也有提示这个，不过都好像是隐藏在console里面，前端的东西稍微不注意可能就冲突了。
![image](https://user-images.githubusercontent.com/22536294/28511010-b9a77714-707d-11e7-83a8-f04ae013398b.png)

**Comment by akazhuk** [comment]
@chenlixin93  我也是這樣引用的啊。。按照文檔來搞的

**Comment by chenlixin93** [comment]
https://github.com/z-song/laravel-admin/pull/584/commits/03ef3c3ac37a324ef4a7de08a2a1ce990ef25164
一开始接入是有很多错误的，我当时是按照这个去修改上传，最终才没出现问题的，你可以参考下，是不是哪里没改好
