### ISSUE TITLE
有三个需求请教一下

### ISSUE THREAD

**Issue by wonderful60** [z-song/laravel-admin#1005]
![qq20170720-174725](https://user-images.githubusercontent.com/2291007/28414469-5e7fafe8-6d7e-11e7-99c9-fc6dd546c7fa.png)
1. grid是否有办法支持二级column标题，如上图这样

2. grid的数据来源如果是api获取，不知道如何编写？

3. grid export导出能否根据界面呈现的结果导出，而不需要重新查询一下数据库

**Comment by z-song** [comment]
1  你可以在display回调里面return一个table来实现这个效果
2 参考 http://120.26.143.106/admin/movies/in-theaters
3 暂时不能

**Comment by wonderful60** [comment]
非常感谢
