### ISSUE TITLE
中文文档发现两处问题

### ISSUE THREAD

**Issue by yogihwang** [z-song/laravel-admin#1007]
http://z-song.github.io/laravel-admin/#/zh/model-grid
1、
对应的数据模型为App\Models\Movie，下面的代码可以生成users的数据表格：
应该是：
对应的数据模型为App\Models\Movie，下面的代码可以生成movies的数据表格：
2、
// sql: ... WHERE `article.author_id` = $id;
    $filter->is('author_id', 'Author')->select(User::all()->pluck('name', 'id'));
这个连贯操作的说明不准确把？

**Comment by z-song** [comment]
已经修改，多谢指出
