### ISSUE TITLE
Function getForm is missing in NestedForm

### ISSUE THREAD

**Issue by SpinyMan** [z-song/laravel-admin#1008]
It's highly recommended to add getters for all public setters!
If we have public function setForm, setModel, setWhatEverElse we need to get them back!
Please add missing getForm function to NestedForm.php
```
/**
 * Get Form.
 *
 * @return $this->form
 */
public function getForm()
{
	return $this->form;
}
```
Thanx!

**Comment by SpinyMan** [comment]
Is there the chance to see at least this function?

**Comment by SpinyMan** [comment]
Still waiting...

**Comment by z-song** [comment]
Fixed now, upgrade to `1.5.x-dev`

ps: pull request are welcome;)

**Comment by SpinyMan** [comment]
Thank you very much!

**Comment by SpinyMan** [comment]
Sorry, but only now I understood that brunch 1.5.x is not for my laravel 5.4... Could u pls upgrade 1.4 brunch with that function?
Thanx!
