### ISSUE TITLE
Insert custom css file mainly to change the default adminlte, but also add other tweaks

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#1011]
I thought that I could insert a custom css file using `Admin::css('css/custom.css')` to change a few things in the interface, but I see that in the view `vendor/encore/laravel-admin/views/index.blade.php` it gets inserted before many css files, such as `AdminLTE.min.css`.

This mean some of my changes to the original adminlte will be overriden... Same thing with javascript (although its not as problematic by nature).

From what I understand, these functions are used to insert assets that are internally necessary and any form of field requirement. I'm guessing `AdminLTE.min.css` is added after to skin the fields and forms.

To insert a custom, my only option is to override that index view. Is there any other way?
I would have thought there would be a partial view to do so.

**Comment by Brenokx** [comment]
I have the same issue, someone can answer?

**Comment by Prateik2710** [comment]
I was also having the same issue but for now I have resolve that issue with `!important` it will not be applicable everywhere. I am also looking for better option.

**Comment by yesyo** [comment]
As a workaround, I just copied 

> vendor/encore/laravel-admin/resources/views/index.blade.php

 to 

> resources/views/vendor/admin/index.blade.php

 and added one line `<link rel="stylesheet" href="{{ url('path/to/your/css') }}">` after `{!! Admin::css() !!}` to override styles.

**Comment by nhannt-itech** [comment]
i have this problem too

**Comment by alexoleynik0** [comment]
This is how I handled similar issue myself: 

```php
// in `app/Admin/bootstrap.php` 
$baseCss = Admin::baseCss(); // this returns array to all baseCss paths if called without arguments.
$baseCss[] = 'path-to-your.css'; // add, reorder, delete, have fun.
Admin::baseCss($baseCss); // set it back.
```

Works for `Admin::baseJs()` too.

**Comment by gomes2191** [comment]
Do you have to add it to the public folder?

**Comment by gomes2191** [comment]
use Encore\Admin\Facades\Admin;
Admin::css('/custom/css/skin-black.min.css');


This solution of yours is the result of the same result.

**Comment by alexoleynik0** [comment]
@gomes2191 the result is not the same if you need to remove some css, or replace it, or simply put after the default ones to make overriding easier. 
Admin::css puts your asset before other, my method allows to put it after.
