### ISSUE TITLE
Helper Idea: Settings

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#1012]
A page where you can edit predefined settings (not create or delete them)

The settings could be defined in the `config/admin.php` file
```
'settings' => [
    'fieldname' => [
        'default value'
    ]
]
'settings_form' => App\My\Settings\Form::class, // for custom fields
```

A generic migration would generate the settings table, being a simple unique(varchar(name)) and text(value) ..perhaps more

When retrieving, if entry is not in the table, default value in the config is used

**Comment by z-song** [comment]
see https://github.com/laravel-admin-extensions/config
