### ISSUE TITLE
搜索的时候怎么根据 副表里的字段 搜索

### ISSUE THREAD

**Issue by wanggfyy** [z-song/laravel-admin#1013]
$filter->orderloan()->between('created_at', '时间')->datetime();这样报错

orderloan是连接的表
```php
 public function orderloan()
    {
        return $this->belongsTo(Yjfloan::class,'orderno','externalOrderNo');
    }
```

**Comment by wanggfyy** [comment]
@z-song

**Comment by z-song** [comment]
试试：```
$filter->between('orderloan.created_at', '时间')->datetime();
```

**Comment by wanggfyy** [comment]
@z-song    谢谢大佬

**Comment by feivorid** [comment]
@z-song 请问要是三个表关联怎么写 ？   
![image](https://user-images.githubusercontent.com/5013223/40896102-bd9e85f0-67e5-11e8-925e-a07de18325a9.png)
我这些直接报错了  报找不到readRecords这个字段，  请问这个怎么解决 ？
