### ISSUE TITLE
BUG:文件上传了，无法删除

### ISSUE THREAD

**Issue by mrchenzifan** [z-song/laravel-admin#1018]
laravel 5.4版本，文件上传了，无法删除

**Comment by uu-myheart** [comment]
ConvertEmptyStringsToNull中间件注释掉试试

**Comment by piaolingshagua** [comment]
ConvertEmptyStringsToNull 5.3也有用啊，但是5.3是可以删除图片和文件的啊，5.4不行啊。虽然注释掉有用，但是感觉不是这个问题。

**Comment by piaolingshagua** [comment]
那这个到底是什么原因呢？？？

**Comment by kangkang66** [comment]
注释掉也删除不了~
