### ISSUE TITLE
咨询个问题，本地发开完成后代码上传到服务器，admin表不会自动创建

### ISSUE THREAD

**Issue by libybai** [z-song/laravel-admin#1020]
执行`php artisan migrate`命令后没有创建admin表，
执行`php artisan admin:install`命令后会创建admin表，但是会有个错误提示
`/Users/libai/project/enterprise-server/app/Admin directory already exists !`
虽然不会产生什么影响，我想知道我的操作是不是不对呢？
需不需要单独执行`php artisan admin:install`命令

**Comment by z-song** [comment]
https://github.com/z-song/laravel-admin/issues/361#issuecomment-275304373 参考这里
