### ISSUE TITLE
关联模型的排序bug

### ISSUE THREAD

**Issue by zjalen** [z-song/laravel-admin#1026]
发现一个问题，在关联模型的显示时候，点击排序，会影响原本表格的字段内容，比如
`$grid->column('name','小区名')->sortable();
 $grid->column('project.name','所属项目')->sortable();`
点击所属项目的排序，直接导致原本的$grid->column('name','小区名')  里面name全部变成project的name了，还有id也是一样。另外在某些情况下还会出现原本有值的字段变空值，编辑还会报错
![image](https://user-images.githubusercontent.com/23429274/28701623-076d25d8-731d-11e7-9fce-6d354a06e64b.png)
![image](https://user-images.githubusercontent.com/23429274/28701633-1206ae88-731d-11e7-85cf-ec8ba8389d7a.png)
![image](https://user-images.githubusercontent.com/23429274/28701641-1a54e9c4-731d-11e7-8556-4130912acece.png)
![image](https://user-images.githubusercontent.com/23429274/28701650-20263d3a-731d-11e7-98eb-3094088222b3.png)

**Comment by tracking** [comment]
我也遇到了相同的问题, ID被关联模型里的ID覆盖了

**Comment by tracking** [comment]
查了下, 发现是Laravel的一个坑
见https://github.com/laravel/framework/issues/4962

解决方法就是通过select手动指定你需要的关联表字段:
```php
$grid->model()->select([
    '主表.*',
    'project.name',
]);
```
