### ISSUE TITLE
$form->hasMany should allow label to be specified like other field types

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#1028]
I'm not sure why I should always use the relation name as the label (especially with a bug currently not letting me use camel case). And there is no method for setting the label, only `->label()` method to retrieve the label. Other fields allow the label to be set, it should the same for hasMany.

**Comment by Nicksxs** [comment]
have not you solve this problem, i faced this recently， could you give me some advise

**Comment by isometriq** [comment]
Generally the same story: override the blade view (if possible and sufficient)
OR 
You should be able to extend the HasMany field to do more customization and maybe pass a custom title/label. You know how to extend a field?

**Comment by z-song** [comment]
@isometriq @Nicksxs The `hasMany` method has third optional parameter to specific the label name:
```php
$form->hasMany($relation, function () {
    //
}, $labelName);
```

**Comment by Nicksxs** [comment]
@z-song my laravel-admin version is 1.4.2
![image](https://user-images.githubusercontent.com/7351669/29767654-dd9a99b8-8c15-11e7-9a6e-1813e0cf556b.png)
than i add the thrid parameter, then i see this problem
![image](https://user-images.githubusercontent.com/7351669/29767709-12f3f5e6-8c16-11e7-93cf-61cb5c254845.png)
this is my usage 
![image](https://user-images.githubusercontent.com/7351669/29767742-2d5e4e5e-8c16-11e7-96e9-839e211b4831.png)
did i need to upgrade laravel-admin version

**Comment by Nicksxs** [comment]
@z-song my laravel version is 5.4.35
![image](https://user-images.githubusercontent.com/7351669/29767840-87fb7558-8c16-11e7-9bc3-43312dbfc07f.png)

**Comment by z-song** [comment]
写错了 是下面这样:
```php
$form->hasMany('relation', function () {

});

// or

$form->hasMany('relation', '关系', function () {

});
```

**Comment by Nicksxs** [comment]
@z-song 感谢！可以了

**Comment by isometriq** [comment]
@z-song Yes works fine, thanks for pointing that out. Maybe we should indicate in the docs.
