### ISSUE TITLE
一个一对多关系的问题!

### ISSUE THREAD

**Issue by caicaizi251** [z-song/laravel-admin#1031]
[http://120.26.143.106/admin/demo/painters/26/edit](http://120.26.143.106/admin/demo/painters/26/edit)就拿这个页面举个例子吧，这个painter有很多画作，然后我现在想对这个画家做个画作列表出来，并且可以对画作进行编辑，求实现的方法，，，感谢！！！

**Comment by MissMyCat** [comment]
老铁，这个部分直接有实现的代码，复制粘贴就行。

**Comment by caicaizi251** [comment]
老铁，这个部分并没有我说的列表效果！！！他是在整个表单里面把所有画作进行表单列出来，，然后让画家和所有画作一起修改，，，这样操作不方便，我需要的是下面这个操作
登录地址：http://app.tinali.cn/admin 用户名:guest 密码：123456
登录以后看那个楼层列表的操作中有个小眼睛，点那个小眼睛可以看到属于这个楼层中的商品列表，现在这个效果我搞出来了，但是现在有个问题就是当我编辑楼层的商品的时候，它update的id是floor_id
比如试着修改这个信息：http://app.tinali.cn/admin/floor/3/products/20/edit
但是你实际修改的却是：http://app.tinali.cn/admin/floor/1/products/3/edit
这个信息
