### ISSUE TITLE
问一个关于admin域名的问题，比如使用admin.domain.com访问

### ISSUE THREAD

**Issue by Witype** [z-song/laravel-admin#1032]
现在使用的地址是  domain.com/admin，可否使用   admin.domain.com的方式进行访问，谢谢

**Comment by z-song** [comment]
`config/admin.php`的`prefix`设置为空字符串即可

**Comment by ooking** [comment]
刚试了不行，其实配置说明也说了
If you want to access through the root path, just set the prefix to empty string.
把 prefix 留空的话也只是可以通过根路径访问，例如
原来 http://lv.com/admin 变成 http://lv.com
当然我可以创建一个 http://admin.lv.com 指向主机也可以达到同样的效果，可是实际上我把 prefix 留空后 
用 http://www.lv.com 访问最终是访问到了 route/web.php 这里的路由

实际我想达到的效果是有三个独立的域名：
http://api.lv.com 接口域名，已经用 dingo api 实现
http://admin.lv.com 访问 laravel-admin
http://www.lv.com 官网
 
我
laravel 使用的版本是:5.7.13
laravel-admin 1.6.7

**Comment by shinnlu** [comment]
只要2個步驟

route.php 裡面加
`'domain'=> env('APP_DOMAIN'),`

.env 裡面加
```
APP_DOMAIN =admin.laravel6.site
ADMIN_ROUTE_PREFIX=''
```

就可以了, prefix 不要移除，移除反而會有些問題
