### ISSUE TITLE
form表单对展示值的预处理功能如何实现

### ISSUE THREAD

**Issue by MissMyCat** [z-song/laravel-admin#1033]
我在保存表单的时候将某个字段的值，由字符串转换成数组，以Json格式保存了。
`$form->saving(function (Form $form) {
//process
});`

同时，form由于有edit功能，如果直接展示：
`$form->text('column name','lable')`
这种方式，就会直接给出一个json，我希望能对数据进行处理后，再展示……

**Comment by MissMyCat** [comment]
哦，已经尝试了一种黑科技解决这个问题了。

**Comment by zhaomengqiao** [comment]
什么黑科技，是内嵌功能吗

**Comment by MissMyCat** [comment]
@zhaomengqiao 并不是。我采取的方式是，加载form的时候再加载一个自己写的页面，用js把数据重新渲染了一次。

**Comment by z-song** [comment]
可以在模型里面设置字段的修改器来实现
