### ISSUE TITLE
grid默认排序为什么没有用降序，文档好像没有看到修改grid默认排序的参数

### ISSUE THREAD

**Issue by imlida** [z-song/laravel-admin#104]
grid默认排序采用降序体验更好，新增记录时可以知道新增成功了，但是文档好像没有找到修改默认排序的地方

**Comment by z-song** [comment]
@imlida 
https://github.com/z-song/laravel-admin/blob/master/docs/en/model-grid.md#modify-the-source-data
用`Grid::model()`方法修改Eloquent 查询，包括排序

**Comment by imlida** [comment]
知道了谢谢

**Comment by imlida** [comment]
建议把//cdn.ckeditor.com/4.5.10/standard/ckeditor.js  这个文件弄到本地来，国内的网络加载这个js非常慢，导致后台出现卡死的情况
