### ISSUE TITLE
Unable to set custom attributes to form

### ISSUE THREAD

**Issue by SpinyMan** [z-song/laravel-admin#1042]
`\Encore\Admin\Form\Builder\open($options = [])` accepts only `method` & `class` attributes. How to set `id` or `data-param` attribute?

**Comment by miadz** [comment]
also set attribute form controller when define field.
custom view can't solve everything.

**Comment by DanielDanaee** [comment]
@miadz Bebin man custom attribute ro nemitonam be field Select bezanam. Makhsosan baraye field e name, vaghti mikham custom name bezaram baraye field e select, attribute() name to taghir nemide

**Comment by miadz** [comment]
https://github.com/z-song/laravel-admin/blob/4fd32e48d8aeb574685a5b502816657844bb405c/resources/views/form/select.blade.php#L11
**** 
   <select class="form-control {{$class}}" style="width: 100%;" name="{{$name}}" {!! $attributes !!} >
******
@DanielDanaee dalilesh ine attribute  name  ro az un method nemitoni tarif koni chon az tariq $name tarif mishe,

 zemnan che dalili dare injori tarif konid ? ->attribute('name', "price[timeCapacity][$i]")-
mitonid az in estafde konid, shayed karet rah oftad $form->html('inja tarif konid html ro ')->plain();
