### ISSUE TITLE
form()方法如何拿到正在编辑的数据？

### ISSUE THREAD

**Issue by xlkit456852** [z-song/laravel-admin#1043]
因为想在进入编辑页面之前根据当前编辑数据的某个字段而决定另一个字段使用text/textarea/radio来填写。利用Form $form则不行，是空的。比如说：
```
if($data['type']==0){
    $form->text('config_name', '设置名称');
}else{
    $form->textarea('config_name', '设置内容');
}
```

**Comment by uu-myheart** [comment]
df

**Comment by SpinyMan** [comment]
There is no possibility to resolve it directly, because form filling goes right after form initialization. 
For new records you can use request GET params like this:
```
if(request('type') == 0){
    $form->text('config_name', '设置名称');
}
else{
    $form->textarea('config_name', '设置内容');
}
```

for update like this:
```
$model = SomeModel::find($id);
if($model->type == 0){
    $form->text('config_name', '设置名称');
}
else{
    $form->textarea('config_name', '设置内容');
}
```

**Comment by shencm** [comment]
request('type') 这样的取值是空， $model = SomeModel::find($id);这个$id 哪里来

**Comment by example3** [comment]
I use another function... it works.
public function edit($id)
{
   return Admin::content(function (Content $content) use ($id) { 
      $content->body($this->editform($id)->edit($id));
   }
}
protected function editform($id)
{
   return Admin::form(SomeModel::class, function (Form $form) use ($id){
      $model = SomeModel::find($id);
      if($model->type == 0){
          $form->text('config_name', '设置名称');
      }
      else{
          $form->textarea('config_name', '设置内容');
      }
   }
}

**Comment by maokuan** [comment]
在form表单中，点击提交会提示：Method [store] does not exist.
我要定义一个srore路由和方法来接收保存表单里面的参数吗？
