### ISSUE TITLE
Can't see related model data

### ISSUE THREAD

**Issue by vladyslavstartsev** [z-song/laravel-admin#1047]
Having issue with getting data from model relation in admin panel.
What I mean is 
I have `BoilersController`, there we have `form` method.
I've put there the code and it looks like this now
```
    protected function form()
    {
        return Admin::form(Boiler::class, function (Form $form) {

            $form->display('id', 'ID');

            $form->display('created_at', 'Created At');
            $form->display('updated_at', 'Updated At');
            $form->display('boilerType.name', 'Boiler type');
        });
    }
```

the problem is that when I'm on the page, I can't see `Boiler type`. 
I thought there is some problem with my `Boiler` and `BoilerType` models, but I haven't found it there.
Here they are.
`Boiler`
```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Boiler extends Model
{
    protected $fillable = [
        'boiler_type_id',
    ];

    protected $visible = [
        'boiler_type_id',
    ];

    public function boilerType()
    {
        return $this->belongsTo(BoilerType::class);
    }
}
```
`BoilerType`

```
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class BoilerType extends Model
{
    protected $fillable = [
        'name'
    ];

    protected $visible = [
        'id',
        'name'
    ];
}
```

How to show boiler type? Any ideas?

**Comment by z-song** [comment]
Yes these's some issue with getting data from model relation, the current solution is use lower case relation name instead.

```php
public function boilertype()
    {
        return $this->belongsTo(BoilerType::class);
    }

...

$form->display('boilertype.name', 'Boiler type');

```

**Comment by vladyslavstartsev** [comment]
@z-song checked, still the same result. can't see id

**Comment by vladyslavstartsev** [comment]
Also if it needs to be mentioned, on the other model relation (`User` and `Boiler` everything works perfect, but there I have `hasOne` in `User`s `boiler()` method)

**Comment by z-song** [comment]
Can't see `Boiler type` or `id` ?  I'm a little confused

**Comment by vladyslavstartsev** [comment]
Sorry, I pressed wrong key there 'id' -> 'it'. Nothing changed 
![image](https://user-images.githubusercontent.com/17382248/29151836-6c801a74-7d8c-11e7-9f31-cb7eae29cd2e.png)

**Comment by z-song** [comment]
I have tried myself and everything works fine,  are you sure there has BoilerType data related to Boiler with id 15?

**Comment by vladyslavstartsev** [comment]
Yes, that's how `boilers` table looks like 
![screenshot from 2017-08-10 13 15 58](https://user-images.githubusercontent.com/17382248/29166227-3484d2da-7dce-11e7-9dcc-6bb04d2a230b.png)
and `boiler_types` table looks like
![screenshot from 2017-08-10 13 18 02](https://user-images.githubusercontent.com/17382248/29166283-6c8a17bc-7dce-11e7-91eb-c7d90d7c0868.png)

Also if that helps if I do `dd(Boiler::find(15)->boilertype);` I can see `"Gas"`.

That's how my updated code looks like
```
       $form->display('boilertype.name', 'Boiler type');

       public function boilertype()
       {
           return $this->belongsTo(BoilerType::class , 'boiler_type_id');
       }
```
If I don't put second parameter on the `boilertype()` I will get `null` on `dd(Boiler::find(15)->boilertype);`

**Comment by vladyslavstartsev** [comment]
Maybe I did mistake in other part of the code? But I have no idea where it is.

**Comment by vladyslavstartsev** [comment]
I made it work like this

```
    protected function form($id = null)
    {
        return Admin::form(Boiler::class, function (Form $form) use ($id){
            $form->display('id', 'ID');

            $form->display('created_at', 'Created At');
            $form->display('updated_at', 'Updated At');
            if ($id !== null) {
                $boilerTypeName = Boiler::find($id)->boilertype->name;
                $form->display('boilertype.name', 'Boiler type')->setDefault($boilerTypeName);
            }
        });
    }
```

but this workaround really sucks

**Comment by z-song** [comment]
You must pass `boiler_type_id` as the second parameter for `belongsTo` method,  otherwise the Boiler  model can not find the Boiler type.

**Comment by vladyslavstartsev** [comment]
I did, still the same thing.

**Comment by z-song** [comment]
I have no idea about this, check this demo page http://120.26.143.106/admin/demo/users

This also has related model in edit form.  you can find all codes in the page.
