### ISSUE TITLE
Have provider any function like RESTFUL API interface?

### ISSUE THREAD

**Issue by vanloc0301** [z-song/laravel-admin#105]
I need RESTFUL API to create frontend page.

Or you have any document to create the landing page(passing data from back-end to front-end) with `laravel-admin`?

**Comment by z-song** [comment]
It's not supported currently.

**Comment by vanloc0301** [comment]
Will you support in future?

Have you any idea to do this?

Thanks @z-song .

**Comment by z-song** [comment]
@vanloc0301 
`laravel-admin` is admin panel builder， if you want to built RESTFUL APIs, packages like [dingo/api](https://github.com/dingo/api) is a better choice i think.

**Comment by vanloc0301** [comment]
@z-song . Thanks for your link providers.
