### ISSUE TITLE
Widget无法拓展的问题！

### ISSUE THREAD

**Issue by caicaizi251** [z-song/laravel-admin#1052]
不想使用laravel-admin自带的chartjs，，，个人想用百度的echarts应该怎么做？http://echarts.baidu.com/

**Comment by z-song** [comment]
下载echarts到public目录下，在app/Admin/bootstrap.php中引入js和css：
```php
Admin::css('/packages/xxx.css');
Admin::js('/packages/xxx.js');
```
路径自己调整好

就能在你的页面里面使用了，参考https://gist.github.com/z-song/15078827726bfae34dcda5935b02697a
