### ISSUE TITLE
自定义form 扩展引入 wangEditor 3.0.7 的报错问题

### ISSUE THREAD

**Issue by mygrows** [z-song/laravel-admin#1053]
引入 wangEditor 3.0.7  报错
![wangeditor](https://user-images.githubusercontent.com/23335187/29239576-98f4cdd0-7f84-11e7-9804-21fb15819fb7.png)，

测试
1、我本地单独测试，就单独的 html 页面引入 wangEditor.js 是可以正常引入编辑器的 
2、在线上 如果是用的是 wangEditor 2.1.22  是可以正常显示 wangEditor 编辑器的
3、form组件，是不是还没加载完dom，就渲染了？ 排查是不是还没有加载完 dom，就渲染了 wangEditor 了？
盼回复，谢谢 :)

**Comment by z-song** [comment]
试了一下，wangEditor 3.0.7使用方法有点变化，下面是我的代码：

扩展类`app/Admin/Extensions/WangEditor.php`:
```php
<?php

namespace App\Admin\Extensions;

use Encore\Admin\Form\Field;

class WangEditor extends Field
{
    protected $view = 'admin.wang-editor';

    protected static $css = [
        '/vendor/wangEditor-3.0.8/release/wangEditor.min.css',
    ];

    protected static $js = [
        '/vendor/wangEditor-3.0.8/release/wangEditor.min.js',
    ];

    public function render()
    {
        $this->script = <<<EOT

var E = window.wangEditor
var editor2 = new E('#{$this->id}');
editor2.create()


EOT;
        return parent::render();
    }
}

```

视图文件`resources/views/admin/wang-editor.blade.php`
```php
<div class="{{$viewClass['form-group']}} {!! !$errors->has($label) ?: 'has-error' !!}">

    <label for="{{$id}}" class="col-sm-2 control-label">{{$label}}</label>

    <div class="col-sm-6">

        @include('admin::form.error')

        <div id="{{$id}}">
            <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
        </div>

    </div>
</div>
```

**Comment by mygrows** [comment]
@z-song 非常感谢您的回复，用您提供的的方法，我这能成功引入 wangEditor 3.0.8 了，在这个过程中遇到
 了一点问题如图，
![wangeditor2](https://user-images.githubusercontent.com/23335187/29245467-066e243c-800d-11e7-870d-725da72b9fba.png)
最终我的视图文件代码修改如下：
<div class="form-group {!! !$errors->has($errorKey) ?: 'has-error' !!}">

   {{-- <label for="{{$id}}" class="col-sm-{{$width['label']}} control-label">{{$label}}</label>--}}

    <div class="col-sm-12">

        @include('admin::form.error')

        <div id="{{$id}}">
            <p>欢迎使用 <b>wangEditor</b> 富文本编辑器</p>
        </div>
        @include('admin::form.help-block')
    </div>
</div>

成功引入 wangEditor 3.0.8， 对了我使用的是 laravel-admin 1.4.*  
谢谢@z-song

**Comment by mygrows** [comment]
@z-song 编辑器能成功引入了，可是填写的内容提交不到控制器中，导致处理不了，入库

**Comment by z-song** [comment]
这个问题你到wangEditor的issue下面去搜就能找到答案了  https://github.com/wangfupeng1988/wangEditor/issues/886

下面是我这边修改过的代码

扩展类`app/Admin/Extensions/WangEditor.php`:
```php
<?php

namespace App\Admin\Extensions;

use Encore\Admin\Form\Field;

class WangEditor extends Field
{
    protected $view = 'admin.wang-editor';

    protected static $css = [
        '/vendor/wangEditor-3.0.8/release/wangEditor.min.css',
    ];

    protected static $js = [
        '/vendor/wangEditor-3.0.8/release/wangEditor.min.js',
    ];

    public function render()
    {
        $name = $this->formatName($this->column);

        $this->script = <<<EOT

var E = window.wangEditor
var editor = new E('#{$this->id}');
editor.customConfig.onchange = function (html) {
    $('input[name=$name]').val(html);
}
editor.create()


EOT;
        return parent::render();
    }
}

```
视图文件`resources/views/admin/wang-editor.blade.php`
```php
<div class="{{$viewClass['form-group']}} {!! !$errors->has($label) ?: 'has-error' !!}">

    <label for="{{$id}}" class="col-sm-2 control-label">{{$label}}</label>

    <div class="col-sm-6">

        @include('admin::form.error')

        <div id="{{$id}}">
            <p>{!! old($column, $value) !!}</p>
        </div>

        <input type="hidden" name="{{$name}}" value="{{ old($column, $value) }}" />

    </div>
</div>
```

**Comment by mygrows** [comment]
@z-song 感谢

**Comment by weir008** [comment]
@z-song 我按照您这边说的解决方案，始终无法成功引入编辑器。出现跟上面那位同学一样的报错信息：
 FatalErrorException
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined variable: viewClass (View: D:\laragon\www\l54-shop\resources\views\admin\views\wang-editor.blade.php)
问题出在哪里呢？

**Comment by z-song** [comment]
报错都已经告诉你哪里出了问题了`Undefined variable: viewClass`

改一下模板文件，去掉`viewClass `变量：
```php
<div class="form-group {!! !$errors->has($label) ?: 'has-error' !!}">

    <label for="{{$id}}" class="col-sm-2 control-label">{{$label}}</label>

    <div class="col-sm-6">

        @include('admin::form.error')

        <div id="{{$id}}">
            <p>{!! old($column, $value) !!}</p>
        </div>

        <input type="hidden" name="{{$name}}" value="{{ old($column, $value) }}" />

    </div>
</div>
```
