### ISSUE TITLE
请教grid方法报错

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#1054]
![default](https://user-images.githubusercontent.com/9032762/29250846-5d668120-807c-11e7-81e0-907e30809374.png)

**Comment by z-song** [comment]
贴代码。。

**Comment by akazhuk** [comment]
@z-song 就是简单的$this->gird(); 这个调用，tree和from都没有问题。不知道是不是因为我的docker更新了？

**Comment by akazhuk** [comment]
找到解决办法了
![default](https://user-images.githubusercontent.com/9032762/29262583-c72cc548-8107-11e7-920e-65ee9f4c5a26.png)
