### ISSUE TITLE
Column::extend

### ISSUE THREAD

**Issue by abufalbo** [z-song/laravel-admin#1056]
Hi, 
when I want to use `Column::extend` variable `$value` is `null` instead of value of column

```
$grid->title('Subscriber')->is_subscriber()->sortable();

Column::extend('is_subscriber', function ($value) {
	dump($value);
});
```
I use the version 1.4.x-dev

Do I make some mistake?
Thanks.

**Comment by z-song** [comment]
It works fine for me.

Are you put the extend definition in `app/Admin/bootstrap.php`?

**Comment by abufalbo** [comment]
Yes of course extend definition is in `app/Admin/bootstrap.php`

When I add variable to extend definition 
```
Column::extend('is_subscriber', function ($value, $var) {
	dump($value);
        dump($var);
});
```
`$grid->title('Subscriber')->is_subscriber('some content')->sortable();`

$var return `'some content'`
$value `null`

I have done `Form::extend` class and it work fine, but `Column::extend` not. 
I tried also version 1.5, but result was same.

**Comment by NickCoolii** [comment]
@abufalbo show us your code in app/Admin/bootstrap.php

I had same issue when I typed next:

```
use Encore\Admin\Grid\Column;
use app\Admin\Extensions\SelectState;
Column::extend('selectState', SelectState::class);
```

and in Column::$displayers I had next row:
"selectState" => "app\Admin\Extensions\SelectState"

So I fixed it in `app/Admin/bootstrap.php` with:
Column::extend('selectState', 'App\Admin\Extensions\SelectState');

But when i changed
