### ISSUE TITLE
我的laravel-admin所有规则验证都没有提示信息，直接返回刷新当前页面

### ISSUE THREAD

**Issue by zhengwenle** [z-song/laravel-admin#1057]
$form->text('name', '类目名称')->rules('required');
像这样的验证，包括登陆的时候也是没有错误信息提示，直接返回刷新当前页面，请大神帮忙解决一下，谢谢。

**Comment by z-song** [comment]
没遇到过这个问题，你看看有没有异常日志，看看浏览器控制台有没有错误吧

**Comment by upupli** [comment]
我其中一个页面也遇到了这个问题!

**Comment by gystone** [comment]
我也遇到了1.4的时候，出现了这个问题，然后以为是版本的问题，就升级到了1.5，现在1.5又出现这个问题了@z-song 这个问题现在如何能解决？

**Comment by jaredwu** [comment]
我也出现了这个问题 @zhengwenle 你解决了吗

**Comment by zhengwenle** [comment]
18339205162

**Comment by xinqiankb** [comment]
> 我知道啥问题了 index.balde.php 你是不是有修改过，这个地方出问题了，我重置了这个文件，就好了。哈哈，加个微信好友，之后交流交流

大佬，我也遇到这个问题，没修改过index.blade.php，尴尬
