### ISSUE TITLE
表格删除问题

### ISSUE THREAD

**Issue by sindey1982** [z-song/laravel-admin#106]
点击表格中的单条数据删除按钮，能成功删除，但是紧接着会调用一个url
http://washbasin_v2.dev/admin/config?_pjax=%23pjax-container
目前都是报错，页面无法刷新，是否需要配置什么,？
我如果直接输入浏览器地址栏，是可以访问的。

**Comment by sindey1982** [comment]
应该和我的开发服务器有关系，我的wamp环境 如果连续调用url，会出现报错。应该和这个有关系，可以关闭了。

**Comment by z-song** [comment]
这是pjax需要传递的参数
