### ISSUE TITLE
为什么注入一段js需要刷新才能使用?

### ISSUE THREAD

**Issue by tiandaye** [z-song/laravel-admin#1060]
我在 `laravel-admin` 里面的 `index.blade.php` 里面加了 `@yield('custom_js_yield')` 这段代码。我在其他blade里面写了
```
@section('custom_js_yield')
    <script type="text/javascript">
        $('#thc').on('click', function (e) {
            e.preventDefault();
            alert('thc');
        });
    </script>
@endsection。
```
但是我要刷新才能使用。是 `pjax` 造成的吗？  有可以不需要刷新我就使用。

**Comment by z-song** [comment]
刷新的时候，浏览器会执行所有的js文件和嵌在html里面的js代码，这个时候你注入的js就会执行。

你点击页面链接跳转的时候，可以打开控制台看看网络请求，整个页面只加载了页面的一部分内容，这个时候只会运行加载的这一部分内容里面的js代码

所以你引入的这段js，在每次点击页面的时候，是不会运行的。

解决的办法是在控制器里面用`Admin::script('xxx');`注入js代码，用`Admin::script('xxx');`注入的代码会在每次点击的时候随后端html一起返回，所以会被执行。

**Comment by tiandaye** [comment]
谢谢! 理解了。
