### ISSUE TITLE
为什么在grid中的filter无法过滤 0 的记录

### ISSUE THREAD

**Issue by yangji1979** [z-song/laravel-admin#1061]
为什么把 0 作为全选的过滤条件，而不是空，导致数据为0的记录无法查询！

**Comment by luck-token** [comment]
我暂时在 grid() 第一行添加

```
if (\request('channel_id') == 0) {
   app('request')->merge(['channel_id' => '']);
}
```

来过滤

**Comment by WuYeYouMing** [comment]
Encore\Admin\Grid\Filter\Field\Where.php中的第65行中的empty($value)导致的问题，我是改成用正则判断参数是否为空字符的，你可以参考下
