### ISSUE TITLE
laravel5.5还不能用这个包吗？

### ISSUE THREAD

**Issue by DamonSnow** [z-song/laravel-admin#1062]
在laravel5.5中使用，由于包自动发现的功能，如果添加ServiceProvider反而会报错。无法进行下一步publish，直接用vendor publish选择服务后，登录全部提示permission deny

**Comment by z-song** [comment]
不用手动添加ServiceProvider

**Comment by DamonSnow** [comment]
就是没添加serviceProvider,然后运行vendor publish，然后install，可是登录的时候会显示permission deny

**Comment by z-song** [comment]
是安装时的填充数据有点问题，修改好了，重新安装试试看
