### ISSUE TITLE
form如何隐藏按钮？

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#1063]
return Admin::content(function (Content $content) {
            $form = new Form($array);
            $form->display('id','id');
            $form->display('name','name');
            $content->row(new Box('资料详情', $form));
        });

用的是这种方式输出的form表单，好像用不了$form->disableReset(); $form->disableSubmit(); 这2种方法，因为是在Encore\Admin\Form里的，而我上面那种是用的Encore\Admin\Widgets\Form

**Comment by akazhuk** [comment]
没人有这个需求？

**Comment by xiaobailc** [comment]
如果所有的from小组件都不需要按钮，可以把视图文件拷贝到项目里面，然后修改视图文件。

**Comment by wslsq** [comment]
楼主找到解决方法了吗？

**Comment by yang5664** [comment]
"admin::widgets.form"的 submit、reset是寫死的。
