### ISSUE TITLE
MultipleImage()

### ISSUE THREAD

**Issue by lukaskris** [z-song/laravel-admin#1066]
i use $form->image('pictures')->multiple();
but cant select multiple, just single image...
i read documentation and use 

$form->multipleImage('images','Images');
but in save array to string

and i allready add

```
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $table = 'Item';

    public function category()
    {
        return $this->belongsTo(Category::class);
    }

    public function subitems()
    {
        return $this->hasMany(SubItem::class, 'subitem_id');
    }

    public function setPicturesAttribute($pictures)
    {
        if (is_array($pictures)) {
            $this->attributes['images'] = json_encode($pictures);
        }
    }

    public function getPicturesAttribute($pictures)
    {
        return json_decode($pictures, true);
    }
}

```

and then cant save cause array to string problem

please help ✌️ 
i confuse read documentation
and in demo online not found multiple image with this method

**Comment by z-song** [comment]
use `$form->image()->multiple()`

Select multiple images by keep press `ctrl` key.

**Comment by lukaskris** [comment]
i use $form->multipleImage('pictures')
cant use $form->image()->multiple...
now it's work
but if in edit or in grid, image not show...
can you help me why image didn't show?
