### ISSUE TITLE
构建的表单可以增加返回按钮吗？

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#1069]
Encore\Admin\Widgets\Form用的这个类来构建的表单
可以增加返回按钮吗？ 
![default](https://user-images.githubusercontent.com/9032762/29522922-b241e9f4-86bd-11e7-812a-b6ea0c41b62c.png)

**Comment by xiaobailc** [comment]
自定义视图，参见 http://laravel-admin.org/docs/#/zh/qa?id=%e5%85%b3%e4%ba%8e%e8%87%aa%e5%ae%9a%e4%b9%89%e8%a7%86%e5%9b%be
然后自己修改 form 组件的前端模板就可以了

**Comment by akazhuk** [comment]
@xiaobailc  好的，谢谢朋友，我向这个方向研究下
