### ISSUE TITLE
LA自带的图片上传很耗浏览器资源，整合webuploader发现初始化异常，需每次刷新

### ISSUE THREAD

**Issue by rainforyou** [z-song/laravel-admin#1070]
翻阅了众多issues，有写着封装成方法后 Admin::script('initupload()');调用的，但是没成功

var initupload = function(){
window.webuploader = {config:{thumbWidth: 220, thumbHeight: 220, wrapId: "uploader", },	uploadUrl: "./fileupload.php",	updateUrl: "./fileupdate.php",	removeUrl: "./filedel.php",	initUrl: "./fileinit.php"	}

}

**Comment by rainforyou** [comment]
整合用的Extensions  ，如果把window.webuploader 这段写入到扩展的render里可以初始化，就是需要刷新才行

**Comment by z-song** [comment]
完整的代码帖一下

**Comment by rainforyou** [comment]
`class Webuploader extends Field
{
    protected $view = 'admin.ext.webuploader';

    protected static $css = [
        '//cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css',
        '/packages/admin/webuploader/webuploader.css',
    ];

    protected static $js = [
        '/packages/admin/webuploader/webuploader.js',
        '/packages/admin/webuploader/extend-webuploader.js',
    ];

    public function render()
    {
        $this->script = <<<EOT
window.webuploader = {config:{thumbWidth: 220, thumbHeight: 220, wrapId: "uploader", },	uploadUrl: "./fileupload.php",	updateUrl: "./fileupdate.php",	removeUrl: "./filedel.php",	initUrl: "./fileinit.php"	}
EOT;
        return parent::render();

    }
}`

用上述代码需刷新才会初始化

**Comment by rainforyou** [comment]
在控制器里用下面这种方法不行，或者说我封装的不对

`$form->webuploader('thumb1');
Admin::script('initwebupload()');`
