### ISSUE TITLE
关于form  saving 回调问题

### ISSUE THREAD

**Issue by pal301x** [z-song/laravel-admin#1071]
小弟现在遇到一个场景。需要在新增或修改form 字段的时候，根据他提交的字段后台选择存储或修改什么样值。现在的回调只能看，不能改。有什么解决办法没？

也有考虑过在保存后回调哪里操作，但是考虑到后台操作有可能失败，就放弃了，
想和form 一起执行。

**Comment by rainforyou** [comment]
model里去set  get

**Comment by z-song** [comment]
https://laravel.com/docs/5.4/eloquent-mutators
