### ISSUE TITLE
如何让$form的radio button是横排显示而非竖排

### ISSUE THREAD

**Issue by alexli0707** [z-song/laravel-admin#1072]
首先感谢这么优秀的开源库,有个问题如何让$form的radio button是横排显示而非竖排.

**Comment by rainforyou** [comment]
你自己加个custom.css

`.radio {
    float: left;
}`

**Comment by zeen828** [comment]
$form->checkbox($column[, $label])->options([1 => 'foo', 2 => 'bar', 'val' => 'Option name']);

// 竖排
$form->checkbox($column[, $label])->options([1 => 'foo', 2 => 'bar', 'val' => 'Option name'])->stacked();
