### ISSUE TITLE
$form->file('filename','安装包');浏览器无响应问题

### ISSUE THREAD

**Issue by alexli0707** [z-song/laravel-admin#1078]
请教一下直接
 $form->file('filename','安装包');在上传安装包的时候直接导致浏览器无响应这个问题大家有遇到吗?或者有什么好的解决方式.
PS: laravel 5.4版本, 小文件一切正常,MB级别的文件就无响应了.

**Comment by alexli0707** [comment]
PS:在firefox下正常,在google下不行

**Comment by z-song** [comment]
laravel-admin集成的上传组件是`file-input`,  你出现的这个问题是`file-input`产生的，猜测是预览加载大文件的时候导致浏览器crash了，你可以到这个项目下面去提issue

或者参考[这里](http://z-song.github.io/laravel-admin/#/zh/model-form-field-management?id=%e6%89%a9%e5%b1%95%e8%87%aa%e5%ae%9a%e4%b9%89%e7%bb%84%e4%bb%b6)实现一个最基本的input上传组件，这样就不会有问题了

**Comment by alexli0707** [comment]
感谢回复,希望能早日修复这个问题,我先想办法解决,如果有好的解决方案也会申请commit
