### ISSUE TITLE
tab 内输出多个 $grid 点击连接地址总是跑到第一个去

### ISSUE THREAD

**Issue by lianke** [z-song/laravel-admin#1079]
![1120170824142820](https://user-images.githubusercontent.com/8402274/29652590-b7d72d94-88d8-11e7-9d62-d0f2157db318.png)
![2220170824142832](https://user-images.githubusercontent.com/8402274/29652593-bc17b7e8-88d8-11e7-8a19-50a59400104f.png)

**Comment by z-song** [comment]
点击哪里的链接？

**Comment by lianke** [comment]
就是tab没 是多个grid
比如点击第二个 tab  in stock的时候  然后在点击里面的排序 就有问题

**Comment by h2ero** [comment]
这里是因为刷新了整个tab，而不是tab里面的content。建议再加一个参数 Tab::add($title, $content, $active)

**Comment by lianke** [comment]
@h2ero 请老中医 能帮忙写一个我看下吗 小弟实在没头绪

**Comment by uu6744** [comment]
![_20170928141207](https://user-images.githubusercontent.com/27410921/30951967-3c8334c6-a458-11e7-8317-8368127099ef.png)
能不能给我一下那个tab的源码，谢谢

**Comment by ajiader** [comment]
我也遇到这个问题
