### ISSUE TITLE
Javascript Injection Security flaw

### ISSUE THREAD

**Issue by akizor** [z-song/laravel-admin#108]
Go anywhere in administration forms and add <script>alert(2);</script> to any input.
Confirmed on demo and local. Long live eval. :)
Really, this is a serious security flaw in case of viewing info added from frontend.

https://github.com/z-song/laravel-admin/search?utf8=%E2%9C%93&q=globalEval

**Comment by z-song** [comment]
Thank you for point out the serious  problem，I fix it by convert all applicable characters in grid to html entities .

**Comment by akizor** [comment]
The fix will not solve the core problem. This means the eval function. **I strongly recommend removing it or use alternatives.** It can cause very serious problems. This could lead to session hijacking, keyloggers and so on.
In the case i'll use my custom view inside your controller and show db data, I know laravel will escape values, but your module won't and will execute them.  Your package already has 822 downloads (at the time of this writing), this means 822 extremely vulnerable projects.

**Comment by z-song** [comment]
The eval function in `pjax.js` is use to execute javascript code in script tag respond by pjax request, and it's same as refresh the page manually.

I think the way to avoid js injection is validate or filter data added from frontend.
