### ISSUE TITLE
多图上传报错，我看官方demo也报错

### ISSUE THREAD

**Issue by zhaomengqiao** [z-song/laravel-admin#1081]
http://120.26.143.106/admin/demo/multiple-images
我们自己弄了报这个错误
Array to string conversion (SQL: insert into `demo_multiple_images` (`title`, `pictures`, `updated_at`, `created_at`) values (21312312312, image/bf176b7e77b7f457397b8d1cfdf21844.png, 2017-08-24 09:56:15, 2017-08-24 09:56:15))

想按官方demo改下，测试也是报这个错误

**Comment by zhaomengqiao** [comment]
多图上传后 拖动切换图片顺序 这个会加入吗 哈哈

**Comment by z-song** [comment]
因为你上传多图的时候，后端pictures字段接收到的数据是数组，数组存数据库就出现你上面的问题了，解决办法，在模型里面设置这个字段的修改器和访问器，比如用json格式存储图片地址的话：

```php
public function setPicturesAttribute($pictures)
{
    if (is_array($pictures)) {
        $this->attributes['pictures'] = json_encode($pictures);
    }
}

public function getPicturesAttribute($pictures)
{
    return json_decode($pictures, true);
}
```

ps  这个问题已经有人提过issue了，下次问之前建议先搜一下
