### ISSUE TITLE
How to use load and return result to another select field

### ISSUE THREAD

**Issue by lukaskris** [z-song/laravel-admin#1084]
my problem is the result not show in next select
![1](https://user-images.githubusercontent.com/15793303/29671113-dd4cf1dc-8912-11e7-88be-e9d7a2da3026.jpg)

in subitem not showing text

and there is options($id) in subitem model

   ```
 public static function options($id)
    {
    	if (! $self = static::find($id)) {
            return [];
        }

        return $self->pluck('size', 'id');
    }
```

and there is my controller

```
$form->select('item_id')->options(
                Item::all()->pluck('name','id')
            )->load('sub_item','/admin/api/subitem');

            $form->select('sub_item')->options(function ($id) {
               
               return SubItem::options($id);
            });
```

and then this is result of api
[{"id":1,"size":"M","color":"Biru"},{"id":2,"size":"L","color":"Merah"},{"id":3,"size":"L","color":"Hitam"}]

i confuse about options in result...
please help me thanks

**Comment by z-song** [comment]
The response format of your api should be like :
```json
[
    {
        "id" : 1,
        "text": "xxx"
    },
    ...
]
```
try：
```php
public function subitem(Request $request)
 {
     $q = $request->get('q');

     return SubItem::where('item_id', $q)->paginate(null, ['id', 'size as text']);
 }
```

**Comment by lukaskris** [comment]
thanks 👍

**Comment by lukaskris** [comment]
i wanna ask... 
my select option was show item
but if i want save
the id not save and show this is problem

SQLSTATE[HY000]: General error: 1364 Field 'sub_item' doesn't have a default value (SQL: insert into `restock` (`item_id`, `quantity`, `updated_at`, `created_at`) values (5, 1, 2017-08-25 15:02:23, 2017-08-25 15:02:23))

i think in SubItem::Options($id); in my problem

   ```
 public static function options($id)
    {
        if (! $self = static::find($id)) {
            return [];
        }
        return $self->pluck('text','id');
    }
```

thanks :)
