### ISSUE TITLE
composer问题

### ISSUE THREAD

**Issue by lizuoqiang** [z-song/laravel-admin#1085]
我怎么才能将你1.4的分支给composer 进我项目

**Comment by F4NNIU** [comment]
没看明白问题。
我的理解是执行以下命令后就已经在项目里了呀。
composer require encore/laravel-admin "1.4.*"

**Comment by lizuoqiang** [comment]
如果直接composer require encore/laravel-admin "1.4.*"的话报错：
Your requirements could not be resolved to an installable set of packages.

**Comment by F4NNIU** [comment]
你用的什么版本的 laravel?

**Comment by lizuoqiang** [comment]
之前是5.2  我正在新建一个5.4的

**Comment by lizuoqiang** [comment]
看来是可以了 好的 thank you
