### ISSUE TITLE
引入 wangEditor 3.0.8 出现报错

### ISSUE THREAD

**Issue by weir008** [z-song/laravel-admin#1086]
https://github.com/z-song/laravel-admin/issues/1053
@z-song 我按照您在上面这个issue里面的方案，无法成功引入wangEditor 3.0.8（2.1.23版本可以正常引入）。出现跟上面那位同学一样的报错信息：
FatalErrorException
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Undefined variable: viewClass (View: D:\laragon\www\l54-shop\resources\views\admin\views\wang-editor.blade.php)
问题出在哪里呢？

**Comment by z-song** [comment]
报错都已经告诉你哪里出了问题了`Undefined variable: viewClass`

改一下模板文件，去掉`viewClass `变量：
```php
<div class="form-group {!! !$errors->has($label) ?: 'has-error' !!}">

    <label for="{{$id}}" class="col-sm-2 control-label">{{$label}}</label>

    <div class="col-sm-6">

        @include('admin::form.error')

        <div id="{{$id}}">
            <p>{!! old($column, $value) !!}</p>
        </div>

        <input type="hidden" name="{{$name}}" value="{{ old($column, $value) }}" />

    </div>
</div>
```

**Comment by weir008** [comment]
汗！刚发现修改的是自己之前放到 vendor 目录下的 wang-editor.blade.php ，怪不得改了没反应。。。
对不起，我的粗心浪费了您的时间。
