### ISSUE TITLE
关于在admin，路径的问题

### ISSUE THREAD

**Issue by ibmsoft** [z-song/laravel-admin#109]
现在有一个项目，跑在nginx上，我配置了项目的工程 路径为 http://xxdomain.com/site001
这个时候，http://xxdomain.com/site001/admin 可以跳转到 管理登录页面，但是这个时候登录页面的login
action 路径还是 /admin/auth/login,理论上这应该变成  /site001/admin/auth/login
这里的路径，需要根据上下文来获取，这里好像是写死了（不是指admin，admin 可以在config 里配置前缀）

需要调整login里的
`    <form action="{{url(Admin::url('auth/login') )}}" method="post">`

**Comment by z-song** [comment]
@ibmsoft 你的前缀是配置成`site001/admin`还是`admin`呢？

**Comment by ibmsoft** [comment]
前缀是 admin

**Comment by z-song** [comment]
设置成site001/admin试试看呢
抱歉 我还没有测试过多级目录的情况

**Comment by ibmsoft** [comment]
好的，我现在就是修改源码，我也是才发现这个问题，希望下个版本修复吧

**Comment by Muhammadinaam** [comment]
Please solve this problem

**Comment by Haogood** [comment]
@ibmsoft 我也遇到一樣的情形，雖然調整了login form的action路徑後可以順利登入，但登入後的CRUD按鈕都是使用'/'絕對路徑，也要手動去修正CRUD的路徑嗎 還是有更好的解決方法呢

**Comment by cunluyuxia** [comment]
我想问一下，我跑在阿里云的nginx上，页面显示空白，在后面添加路径也没有任何反应， 你那里配置有问题吗

**Comment by moore0903** [comment]
1.在Admin.php中把url()方法的返回前面加上url('/');
2.在Authenticate中间件里面把重定向和下面方法中的数组相应的改一下;

这样貌似可以,但是不知道有什么问题没,就是有个问题,就是composer更新

**Comment by moore0903** [comment]
如果非根目录的情况下,建议使用多端口访问吧
试了好多种方法,不是改动太大了就是composer update还原了.要不然后就弄成自己的包
