### ISSUE TITLE
删除已上传成功的图片报错，排查是因为控制器里saved内进行foreach

### ISSUE THREAD

**Issue by zhaomengqiao** [z-song/laravel-admin#1090]
在saved内进行foreach 会影响删除图片报错
注释foreach 就可以正常删除图片
不涉及删除图片的话，本身saved也正常
 
![qq 20170825115813](https://user-images.githubusercontent.com/23172646/29699290-28aa9668-898e-11e7-9e09-0f33b7a9255c.png)

![qq 20170825120901](https://user-images.githubusercontent.com/23172646/29699295-36cc70f4-898e-11e7-8911-81ac7d388515.png)

**Comment by xiaobailc** [comment]
没试过在 from 的保存回调里面做逻辑，我建议你试试 用laravel框架提供的 Eloquent 模型事件来处理。而且这样应该更符合逻辑。https://laravel.com/docs/5.5/eloquent#events
