### ISSUE TITLE
Laravel5.5版本输入了php artisan vendor:publish --tag=laravel-admin后没生成admin.php

### ISSUE THREAD

**Issue by Share-Man** [z-song/laravel-admin#1095]
RT

**Comment by z-song** [comment]
tag修改过了，所以不能用`laravel-admin`这个tag了

你可以这样操作
先 `php artisan vendor:publish`
然后在下面出现的列表里里面选择`AdminServiceProvider`

文档还没完善，等laravel 5.5正式发布之后，再补充文档
