### ISSUE TITLE
在编辑页value()设置为什么无效

### ISSUE THREAD

**Issue by nomants** [z-song/laravel-admin#1096]
$form->password('password', '密码')->value('')->rules('required');

**Comment by xinhaonaner** [comment]
编辑页的value，我也不行，默默的关注下

**Comment by zhaomengqiao** [comment]
求解，有什么变通的方法

**Comment by zhaomengqiao** [comment]
$form->text('title')->value('text...');
设置保存值

$form->text('title')->default('text...');
设置默认值

搞定了，一个是默认一个是保存。一个是看的一个是保存的。
简单一点的就是，其实所有的全用default就都ok了，不要用value
