### ISSUE TITLE
列设置style依然会报错

### ISSUE THREAD

**Issue by alexli0707** [z-song/laravel-admin#1101]
`$grid->column('title')->style('width:100px;');`

提示方法不存在,但是实际Row中包含了style的方法.
版本:
`"encore/laravel-admin": "1.4.*",`

**Comment by z-song** [comment]
按理说应该没有问题的

dd一下`$grid->column('title')` 看看是不是`Encore\Admin\Grid\Column`对象

**Comment by alexli0707** [comment]
断点之后的确是这个对象.不方便截图我就不上传了

**Comment by z-song** [comment]
那能把错误贴出来最好

**Comment by alexli0707** [comment]
你好,这是完整的错误:

```
 BadMethodCallException In Macroable.php line 52 :

Method style does not exist.
```

**Comment by z-song** [comment]
看下Encore\Admin\Grid\Column类里面有没有style方法

**Comment by alexli0707** [comment]
并没有,Row里有

**Comment by z-song** [comment]
Row是用来控制行的，和列没有关系

更新到`1.4.x-dev`
```shell
composer require encore/laravel-admin 1.4.x-dev
```
