### ISSUE TITLE
编辑用户信息时头像的url不是之前配置里面的public/upload而是storage目录

### ISSUE THREAD

**Issue by DamonSnow** [z-song/laravel-admin#1103]
1.5.x-dev版本中，admin配置文件中upload已正确配置包括host，但是在编辑旧用户信息时显示的avatar头像url错误，url地址变成了storage。

**Comment by LynHuang** [comment]
请问upload不包含host是怎么解决的

**Comment by DamonSnow** [comment]
之前的问题描述的不清楚，再描述一下。首先使用的laravel版本5.5，laravel-admin版本1.5.x-dev，添加一个用户后进行修改操作进入edit页面是如下，头像
![20170830162706](https://user-images.githubusercontent.com/18485833/29862805-26d8cc7c-8da0-11e7-80e3-902653f96de5.png)
而在config/admin.php中配置upload如下
`'upload'  => [

        'disk' => 'admin',

        'directory'  => [
            'image'  => 'image',
            'file'   => 'file',
        ],

        'host' => 'http://mysite/upload/',
    ],`
conifg/filesystems.php中已完成配置。这里就不贴上去了，请问是什么原因？

**Comment by z-song** [comment]
这里的配置有些变化，1.5之后的版本不在admin.php中配置host，要在`filesystem.php`中对应的disk设置`url`
config/filesystem.php
```
'admin' => [
        'driver' => 'local',
        'root' => public_path('uploads'),
        'url' => env('APP_URL').'/uploads', // 配置这一行
        'visibility' => 'public',
],
```

**Comment by DamonSnow** [comment]
嗯，解决了，谢谢
