### ISSUE TITLE
migrating loss table administrators while executing php artisan admin:install

### ISSUE THREAD

**Issue by yiivon** [z-song/laravel-admin#1109]
/**
     * Create tables and seed it.
     *
     * @return void
     */
    public function initDatabase()
    {
        $this->call('migrate');
        /* **after migrating, there isn't administrators table in current database, fatal occur 
              Base table or view not found: 1146 Table 'xxxx.administrators' doesn't exist (SQL: select count(*) as aggregate from `administrators`)**
        */
        if (Administrator::count() == 0) {
            $this->call('db:seed', ['--class' => \Encore\Admin\Auth\Database\AdminTablesSeeder::class]);
        }
    }

**Comment by xiaobailc** [comment]
run  php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider"  first, have a try.
