### ISSUE TITLE
$form  select 中placeholder无效果

### ISSUE THREAD

**Issue by alexli0707** [z-song/laravel-admin#1111]
` $form->select('info_id','关联文章')->placeholder('输入文章id或者名称查找')`

**Comment by xiaobailc** [comment]
不支持，因为select 不是input 元素，底层调用的方法不一样，可以看下底层代码，实际上用的是 jQuery 的 select2 插件实现的。

**Comment by xiaobailc** [comment]
http://select2.github.io/examples.html#placeholders  可以看下select2 的相关设置，自己实现。

**Comment by manzhouya** [comment]
like this:
`$form->select('info_id','关联文章')->config('placeholder', '输入文章id或者名称查找')`
