### ISSUE TITLE
为grid 的列设置style无效

### ISSUE THREAD

**Issue by alexli0707** [z-song/laravel-admin#1112]
` $grid->title('标题')->style('width:50px;');`
还是那么长...导致后面列以及操作按钮都被推后

<img width="1119" alt="4db5abc6-5ffc-487e-bed1-d1be37e9016a" src="https://user-images.githubusercontent.com/2542172/29952179-5108e53a-8efa-11e7-8279-97f7efd2f79b.png">

**Comment by xiaobailc** [comment]
你用的css不对，应该用 word-break:break-all; 可以自己百度下强制换行。

**Comment by z-song** [comment]
行内容太长了应该限制长度`$grid->title('标题')->limit(20);`
