### ISSUE TITLE
请教 form 一对多自定义 relationName 在表单中的显示名称问题和内嵌文本输入框的高度问题

### ISSUE THREAD

**Issue by weir008** [z-song/laravel-admin#1113]
`$form->hasMany('properties', function (Form\NestedForm $form) {
                $form->text('name', '属性名称');
                $form->text('content', '属性内容');
            });`

![snipaste_20170901_103747](https://user-images.githubusercontent.com/21098755/29953495-456726de-8f03-11e7-8bd0-87078b2bbe6c.jpg)
如图，如何自定义 Properties 这个名称呢？
还有，第二个text的高度是咋回事呢？

**Comment by xiaobailc** [comment]
$form->hasMany('properties',  '你需要展示的名字',  function (Form\NestedForm $form) {
.....

**Comment by z-song** [comment]
高度的问题是一个bug, `content`使用了adminLte的css样式，暂时的解决办法是给content的text input添加一个样式
```php
$form->text('content', '属性内容')->attribute('style', 'min-height:10px !important;')
```
