### ISSUE TITLE
how to change Image name in multipleImage()

### ISSUE THREAD

**Issue by lukaskris** [z-song/laravel-admin#1116]
this is my code 
`$form->multipleImage('images','Images');`

i want rename file name base name item,
ex: 
"Item A" and file name is  "Item A_1.jpg", "Item A_2.jpg" ....

**Comment by LynHuang** [comment]
$form->multipleImage('post', '封面')->name(function ($file) {
       return md5(date('ymdhis') . $file->getClientOriginalName()) . '.' . $file->getClientOriginalExtension();
});

**Comment by LynHuang** [comment]
$form->multipleImage('filed', 'label')->name(function ($file) {
    return md5(date('ymdhis') . $file->getClientOriginalName()) . '.' . $file->getClientOriginalExtension();
});
use the name method return the new name;

**Comment by lukaskris** [comment]
thanks, work well..
but now i upload to cloud storage...
in database just save path not full url how to add Url for show picture.

**Comment by LynHuang** [comment]
I have this problem, too。Almost made me give up laravel-admin。
I use a hidden field to send the id , then use the saved method to change the value in database;
$form->hidden('author.user_id');
 $form->saved(function (Form $form) {
              $user = User::find($form->author['user_id']);
                $author= $user->author;
                if (!starts_with($author->avatar, config('admin.upload.host'))) {
                    $author->avatar = config('admin.upload.host') . "/{$author->avatar}";
                    $author->save();
                }
            });

**Comment by LynHuang** [comment]
But that has a problem is too slow.

**Comment by z-song** [comment]
Why to store full url in database for uploaded pictures??

**Comment by lukaskris** [comment]
cause in item grid didn't show image if the url not full :v 
how to append url to grid

**Comment by lukaskris** [comment]
the problem is display image in edit mode.
in grid show normal, but in edit form, how to append url like in grid?

**Comment by z-song** [comment]
@lukaskris Which version do you installed?

**Comment by lordjack** [comment]
> the problem is display image in edit mode.
> in grid show normal, but in edit form, how to append url like in grid?
> 
> ![image](https://user-images.githubusercontent.com/15793303/30003970-c49eb888-90f0-11e7-917f-bd7096761e42.png)

> the problem is display image in edit mode.
> in grid show normal, but in edit form, how to append url like in grid?
> 
> ![image](https://user-images.githubusercontent.com/15793303/30003970-c49eb888-90f0-11e7-917f-bd7096761e42.png)

I have the same problem when I edit the image or file. Could someone give a hint how to solve?
