### ISSUE TITLE
5.5版本的图表组件是永久去掉了还是打算改成扩展形式？

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#1117]
旧版本图表组件能够更新说明文档就更好不过了

**Comment by z-song** [comment]
永久去掉了
之前的图表组件用PHP封装图表js代码，限制太多，还不如直接用js来实现图表

**Comment by z-song** [comment]
自定义图表文档 参考http://laravel-admin.org/docs/#/zh/custom-chart

**Comment by windpursuer** [comment]
Perfect!
