### ISSUE TITLE
Grid进行分组统计，sql_mode导致报错

### ISSUE THREAD

**Issue by chenzi2015** [z-song/laravel-admin#1118]
我想分组后进行显示每一条数据，但是报错了。
$grid->model()->groupBy('member_id');

![image](https://user-images.githubusercontent.com/12816465/29960681-35cdb982-8f2f-11e7-987b-50ce0211c927.png)

**Comment by z-song** [comment]
打开`config/database.php`  把数据库配置中的`strict`设置成`false`试试看
