### ISSUE TITLE
請問有考慮將Nested Form納入功能嗎?

### ISSUE THREAD

**Issue by yang5664** [z-song/laravel-admin#112]
謝謝大大的努力，我在1.3加了NestedForm的功能，類似rails的https://github.com/nathanvda/cocoon，
不過實現的不是很好，想說大大是否有機會將這個功能實現?
````ruby
   public function form()
    {
        return Admin::form(Product::class,
          function (Form $form) {
            $form->text('name', '品名')->rules("required");
            $form->datetimeRange('start_at', 'end_at', '開放日期')->rules("required");
            $form->text('memo', '標語')->rules("required");
            $form->editor('spec', '說明');
            $form->hidden('thumb', '縮圖');
            $form->hidden('image', '代表圖');
            $form->hasManyForm('details', function (NestedForm $sub) {
                $sub->text('memo', '適用對象');
                $sub->text('memo2', '備註');
                $sub->currency('price', '價格')->symbol('NT');
                $sub->number('qty', '可售數量');
                $sub->editor('spec', '說明');
            });
        });
    }
````

**Comment by z-song** [comment]
@yang5664 请问是one to many的关系吗？或者方便展示一下效果截图吗？

**Comment by yang5664** [comment]
我做了擷圖
https://www.dropbox.com/s/rl5ur8z1vicerxh/2016-11-19_19-34-56.png?dl=0
點了"新增"，明細會產生一樣的表單。

**Comment by z-song** [comment]
其实已经开发了类似的功能，但是还有部分问题没有很好的解决，所以就没有开放出来，以后应该会实现这个功能的。

**Comment by yang5664** [comment]
謝謝耶，非常期待這項功能的發佈。

**Comment by edwinhuish** [comment]
@yang5664 能上传图片看看你的效果吗？你的两个链接都失效了。

**Comment by yang5664** [comment]
@edwinhuish 我修復擷圖了

**Comment by taimaiduc** [comment]
Will this function is coming soon sir ? 👍

**Comment by z-song** [comment]
@yang5664 @edwinhuish @taimaiduc This was implemented in version v1.3.1

docs https://github.com/z-song/laravel-admin/blob/master/docs/zh/model-form-fields.md#hasmany

demo http://120.26.143.106/admin/demo/painters

**Comment by edwinhuish** [comment]
@z-song 其实如果可以像 @yang5664 那样，有一个折叠按钮就完美了。

**Comment by edwinhuish** [comment]
@z-song 下面这个NestedForm 跟Form有什么区别么？我按照你之前在群里的写法，直接 function ($form)  效果是一样的。
```
$form->hasMany('paintings', function (Form\NestedForm $form) {
    $form->text('title');
    $form->image('body');
    $form->datetime('completed_at');
});
```

**Comment by edwinhuish** [comment]
@yang5664 请问你的这个效果是做成通用插件么？能共享一下代码？赶紧你这种界面更直观，好用。

**Comment by yang5664** [comment]
@edwinhuish 是根據Admin-Lte實現的，是通用插件，不過當前使用的HasMany是使用自己寫的，所以代碼可能不適合目前的laravel-admin使用。

**Comment by edwinhuish** [comment]
@yang5664 我后来自己改了laravel-admin 的 HasMany.blade.php，然后达到了跟你的类似的效果。
