### ISSUE TITLE
1.5权限问题

### ISSUE THREAD

**Issue by longyuan** [z-song/laravel-admin#1120]
```php
$path = trim(config('admin.route.prefix'), '/').trim($path, '/');
```
Permission.php文件的68行 是不是应该不需要第二个trim这个函数，否则会导致非管理员用户的所有权限失效

**Comment by kevincobain2000** [comment]
- Upgraded to 1.5. and ``/admin`` routes throws a 404
- also ``admin/auth/login`` on successful login it says permission denied

**Comment by pal301x** [comment]
确实出现这个问题了。折腾了半天。希望赶紧修复.

**Comment by z-song** [comment]
已经修复了 更新到 v1.5.1
