### ISSUE TITLE
saving时，怎样对数据处理后，再入库

### ISSUE THREAD

**Issue by xinhaonaner** [z-song/laravel-admin#1127]
![image](https://user-images.githubusercontent.com/24741621/30014988-6a9be158-9181-11e7-963d-a760a7bfbfee.png)
后台添加会员时，可以有推荐人（手机号唯一），表单提交时为手机号，表中需要存储 user_id，想知道，怎样在 insert 的时候，拿到表单数据，处理后，再存入数据库。
参考这个童鞋提问，还是解决不了：https://github.com/z-song/laravel-admin/issues/724
![image](https://user-images.githubusercontent.com/24741621/30015260-7aaf5f92-9182-11e7-853a-e98cfa6366c6.png)
我想知道，saving或者store怎样 处理数据，再入库

**Comment by xinhaonaner** [comment]
![image](https://user-images.githubusercontent.com/24741621/30017188-c7d931a0-918a-11e7-951a-cee1f7ee3c67.png)

我现在 暂时，在模型里面加了个 修改器，但是这样，使用 还是不太方便，因为 我还需要 对推荐人，做数据处理

**Comment by z-song** [comment]
你上面写错了
```php
$form-saving(function ($form) {
    $mobile = $form->recommender;
    
    $form->recommender = `用$mobile处理之后得到的id`;
});
```

**Comment by xinhaonaner** [comment]
song 兄，编辑的时候，该怎样通过recommender获取 推荐人的手机号呢？通过模型ma ?

**Comment by xinhaonaner** [comment]
song 兄，编辑的时候，该怎样通过recommender获取 推荐人的手机号呢？通过模型吗 ?
有好多人提issue ，感觉 你回答都来不及，xixi， 我也尽量 去回答一些问题吧 (*^__^*) @z-song
