### ISSUE TITLE
1.5  Grid switch 无法正常显示

### ISSUE THREAD

**Issue by pal301x** [z-song/laravel-admin#1128]
Encore\Admin\Grid\Displayers\SwitchDisplay 

我吧$this->value 打印出来不是值竟然是一个开关标签。

**Comment by z-song** [comment]
贴代码

**Comment by pal301x** [comment]
万分抱歉，是我自己大意的原因。已经解决了。！

**Comment by xinhaonaner** [comment]
我是1.4，但问题 同你一样
列表里使用switch,页面显示 有效果，但是数据库的值 没有变化！
![image](https://user-images.githubusercontent.com/24741621/30214362-c0a6beaa-94de-11e7-87c8-91784c6fbef4.png)
该怎样解决的呢？@pal301x @z-song ，谢谢了！！
![image](https://user-images.githubusercontent.com/24741621/30214233-38f77d96-94de-11e7-95be-f4e47bc9b094.png)
输出一直都是 ``on`` ``off``，但是表字段是`status`

**Comment by tiderjian** [comment]
![image](https://user-images.githubusercontent.com/1665649/50590673-dddbe500-0ec6-11e9-977a-ab61c61c8ed0.png)
我将这段修改了下就解决了
