### ISSUE TITLE
[ASK] Image upload alway get /storage/image/

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1129]
I got a problem on laravel admin 1.5. I have been changed location disk to upload folder.

[![https://gyazo.com/27b97af93d206c9bb2ae6bdd47843911](https://i.gyazo.com/27b97af93d206c9bb2ae6bdd47843911.png)](https://gyazo.com/27b97af93d206c9bb2ae6bdd47843911)

[![https://gyazo.com/72d8261d469723d5cc4be214d6100f29](https://i.gyazo.com/72d8261d469723d5cc4be214d6100f29.png)](https://gyazo.com/72d8261d469723d5cc4be214d6100f29)

[![https://gyazo.com/6a36a9ec090dee16db8adae170437801](https://i.gyazo.com/6a36a9ec090dee16db8adae170437801.png)](https://gyazo.com/6a36a9ec090dee16db8adae170437801)

**Comment by z-song** [comment]
The configuration of upload files has changed in 1.5 version

I just updated the docs http://laravel-admin.org/docs/#/en/model-form-upload?id=upload-to-local
