### ISSUE TITLE
缺少slimScroll JS插件的问题

### ISSUE THREAD

**Issue by springleng** [z-song/laravel-admin#113]
重现步骤：
1、在config/admin.php里将layout修改为：
'layout'  => ['fixed', 'sidebar-mini'],

2、在使用后台的过程中，chrome 的 console窗口报错如下：
<img width="808" alt="b9b07f85-2e2c-492b-a0ca-4b7b15f53da0" src="https://cloud.githubusercontent.com/assets/1900972/20452792/073bad72-ae4d-11e6-9529-1b7591c1a0a2.png">

之前在qq群里反馈过这个问题，但由于之前不知道跟我修改layout有关系。

js插件地址：
https://github.com/almasaeed2010/AdminLTE/tree/master/plugins/slimScroll

**Comment by z-song** [comment]
@springleng 确实有这个问题存在，将会在接下来的版本修复

谢谢提醒！

**Comment by springleng** [comment]
@z-song thanks
