### ISSUE TITLE
Role check error

### ISSUE THREAD

**Issue by orazz** [z-song/laravel-admin#1133]
Issue appeared after composer update
```
Admin::user()->isRole(['moderator']);
```
![screen shot 2017-09-04 at 9 57 50 pm](https://user-images.githubusercontent.com/8214953/30034649-2197f650-91bc-11e7-9ffe-22c90f31a286.png)

**Comment by z-song** [comment]
```php
Admin::user()->isRole('moderator');

//or
Admin::user()->inRoles(['moderator']);
```
