### ISSUE TITLE
1.5 BatchAction 组件问题

### ISSUE THREAD

**Issue by jxlwqq** [z-song/laravel-admin#1134]
BatchAction 类的$resource 属性值问题。
1.3 版本是完整的URL`https://www.xxx.com/admin`，1.5 版本则变成了相对路径`admin`。这导致ajax的url值会报错。
```
Request URL:https://admin/articles/post_to_weibo
```

**Comment by z-song** [comment]
我修改了一下文档  在拼接ajax请求url的时候

`url: '/{$this->resource}/release',`修改为`url: '{$this->resource}/release',`

http://laravel-admin.org/docs/#/zh/model-grid-custom-tools?id=%e6%89%b9%e9%87%8f%e6%93%8d%e4%bd%9c
