### ISSUE TITLE
表单中怎么在文件上传之后获取回调,同时做后续操作

### ISSUE THREAD

**Issue by alexli0707** [z-song/laravel-admin#1136]
如图:在上传后我需要用excel库去解析里面的兑换码,能如何实现上传到服务器的回调而不是在提交时才获取
![image](https://user-images.githubusercontent.com/2542172/30050382-de9a0254-9250-11e7-9e7a-d2ac0a08990a.png)

**Comment by z-song** [comment]
这个功能要你自己扩展了，已有的组件满足不了这个需求
