### ISSUE TITLE
form中的rules不通过时，并且后面的embeds中有multipleSelect或checkbox时，报错

### ISSUE THREAD

**Issue by fhqfkeeq** [z-song/laravel-admin#1139]
版本：1.4
代码如下：
```php
return Admin::form(A::class, function (Form $form) {
    $form->text('title', '标题')->rules('required|max:30');
    $form->embeds('config', '', function ($form) {
        $form->multipleSelect('yyy', 'yyy')->options(['a' => 'a', 'b' => 'b']);
        $form->checkbox('xxx', 'xxx')->options(['a' => 'a', 'b' => 'b']);
    });
});
```

如果不填写title字段，直接提交，会报

 ErrorException In MultipleSelect.php line 38 :

Column of this field must be a `BelongsToMany` relation. (View: /xxx/vendor/encore/laravel-admin/views/form.blade.php)

这是不是说我在使用上有些问题？

**Comment by yiivon** [comment]
instanceof 是返回 false 的。

**Comment by yiivon** [comment]
Column of this field must be a `BelongsToMany` relation.
new 到的 BelongsToMany 对象，instanceof 为false。

**Comment by fhqfkeeq** [comment]
因为config字段是一个以JSON格式存在mysql中的字段。所以embeds里面的yyy已经不是一个数据库字段，也有没关联关系了。我不知道怎么能绕过这个限制
