### ISSUE TITLE
 文档中没有提到如何保存model

### ISSUE THREAD

**Issue by fuacici** [z-song/laravel-admin#114]
文档中没有提到如何保存Form（model）， 是直接在列表 post的处理方法中， 挨个把属性取出来存吗？  还是有已经实现的更便捷的方法？   感谢！

**Comment by z-song** [comment]
@fuacici 构建好了model-form之后，数据的更新好保存就已经实现了，不需要自己处理提交的数据

**Comment by z-song** [comment]
@fuacici 按照 [快速开始](https://github.com/z-song/laravel-admin/blob/master/docs/zh/README.md#快速开始)这里的步骤来操作，就能生成对一个资源的CURD操作界面

**Comment by fuacici** [comment]
感谢 ！ 但是按步骤操作来的， 也创建了form， 然后提交报错， 405，

**Comment by z-song** [comment]
按照步骤来应该配置下面的路由啊
```php
$router->resource('products', ProductController::class);
```

**Comment by fuacici** [comment]
哦 看漏了 不好意思， 感谢！

**Comment by xxxone** [comment]
laravel5.3只需这样配置路由$router->resource('products', 'ProductController');

**Comment by Caosuhui** [comment]
不需要显性的save，现在form里面配好了，没有插入到数据库。code返回200，不报错插入数据库不成功，也不知道是什么原因？求教
