### ISSUE TITLE
Route post Admin/routes.php error

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1142]
I create route post on Admin/routes.php and using ajax call route and got  an isses.

Route get is ok.

[![https://gyazo.com/f56bcffccaa84116bceab680394c8bbf](https://i.gyazo.com/f56bcffccaa84116bceab680394c8bbf.png)](https://gyazo.com/f56bcffccaa84116bceab680394c8bbf)

[![https://gyazo.com/c1b71d0a6c050bc34d1a8a3f532892bd](https://i.gyazo.com/c1b71d0a6c050bc34d1a8a3f532892bd.png)](https://gyazo.com/c1b71d0a6c050bc34d1a8a3f532892bd)

[![https://gyazo.com/b2cceacb3f4898f343e5699d012d8418](https://i.gyazo.com/b2cceacb3f4898f343e5699d012d8418.png)](https://gyazo.com/b2cceacb3f4898f343e5699d012d8418)

**Comment by z-song** [comment]
I have no idea about this.
