### ISSUE TITLE
Can't delete admin image

### ISSUE THREAD

**Issue by Mike-Savin** [z-song/laravel-admin#1143]
Have an error when trying to remove administrator image in demo panel
![screenshot from 2017-09-07 18-34-25](https://user-images.githubusercontent.com/8523446/30171741-748dd550-93fb-11e7-9928-fea8e8d61e4f.png)

**Comment by z-song** [comment]
The delete button in user setting page will be removed at next release.

**Comment by z-song** [comment]
The delete button is removed now

**Comment by Mike-Savin** [comment]
Thank you

**Comment by amun1303** [comment]
![image](https://user-images.githubusercontent.com/7189244/91005326-ce139600-e600-11ea-8834-6cb6504fcca2.png)
Until now the delete button still exists.

**Comment by amun1303** [comment]
How can I remove this button?
