### ISSUE TITLE
Method value does not exist.

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1147]
Localhost PHP 7.0
I use funtion value and get error

[![https://gyazo.com/f33a018a6f2b032bac2e4922618159bd](https://i.gyazo.com/f33a018a6f2b032bac2e4922618159bd.png)](https://gyazo.com/f33a018a6f2b032bac2e4922618159bd)

[![https://gyazo.com/76daa3dfe0be800580d6488877e39bea](https://i.gyazo.com/76daa3dfe0be800580d6488877e39bea.png)](https://gyazo.com/76daa3dfe0be800580d6488877e39bea)

Function display is ok
[![https://gyazo.com/9a871247cb4d7a9cac703d56c9b178e0](https://i.gyazo.com/9a871247cb4d7a9cac703d56c9b178e0.png)](https://gyazo.com/9a871247cb4d7a9cac703d56c9b178e0)

**Comment by z-song** [comment]
Method `value()` is removed at version `1.5`
