### ISSUE TITLE
Encore\Admim\Form下面什么用？实在看不明白

### ISSUE THREAD

**Issue by lxy1151** [z-song/laravel-admin#1151]
下面这句什么用？
$hasDot = $relation instanceof \Illuminate\Database\Eloquent\Relations\HasOne
                || $relation instanceof \Illuminate\Database\Eloquent\Relations\MorphOne;

**Comment by z-song** [comment]
一对一关联的字段的form表单中用`.`连接 eg：
```php
$form->text('author.name');
```

**Comment by lxy1151** [comment]
请问有实际用处吗？我看了源码，除了在invalidColumn检查了下并没发现用到的地方？
并且如果是一对一关系，对应的关系表不会新增记录，就是因为加了.name使得提交的数据无法获取到？
如果把$hasDot 直接设置成false 对应的关系表是可以新增记录的！

**Comment by lxy1151** [comment]
我的关系设置如下：（如果将finance.living_id改为finance，数据是可以存储的，否则无法存储）
           $form->embeds('finance.living_id','财务信息',function(Form\EmbeddedForm $form){
                $form->currency('contract_fee','订单金额')->default(0.00)->rules('required');
                $form->hidden('record_type')->default(2)->rules('required');
            })->rules('required');

模型中关系设置：
    public function finance(){//财务单据关系
        return $this->hasOne(LivingFinance::class,'living_id')->where('record_type','=','2');
    }
