### ISSUE TITLE
checkbox 添加多个数据提示报错

### ISSUE THREAD

**Issue by yangzhipeng** [z-song/laravel-admin#1155]
QueryException In Connection.php line 664 :

Array to string conversion (SQL: insert into `foods` (`name`, `is_sale`, `category_id`, `updated_at`, `created_at`) values (wss, 1, 1, 2017-09-09 17:58:49, 2017-09-09 17:58:49))

我的代码：　　$form->checkbox('category_id', '菜品分类')->options($cate)->rules('required');

**Comment by yangzhipeng** [comment]
已解决

**Comment by kelvenchi** [comment]
怎么解决的丫？
