### ISSUE TITLE
Quick edit grid error.

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1167]
Quick edit got error 
![1854cae7812035eca2ce8f4ecb77fe14](https://user-images.githubusercontent.com/10907980/30264084-9003eab4-9701-11e7-9743-8a7af7ccfb62.png)

**Comment by z-song** [comment]
Fixed in version `v1.5.4`

**Comment by taimaiduc** [comment]
@z-song Still got issus :(.

**Comment by z-song** [comment]
run `php artisan vendor:publish --tag=laravel-admin-assets --force`

**Comment by taimaiduc** [comment]
👍
