### ISSUE TITLE
Delete an image on edit mode then save (not update new image) not working.

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1169]
Delete an image on edit mode then save not working. I am not update new image. Remove then give it empty

**Comment by qcol** [comment]
+1 - no trash icon in edit mode (in demo page too) 
http://laravel-admin.org/demo/multiple-images/3/edit

**Comment by qcol** [comment]
OK, I found in DOC... it needs ->removable() option... Should this not be the default?

**Comment by elinxer** [comment]
right!

**Comment by taimaiduc** [comment]
@z-song Take a look if you have time 👍

**Comment by z-song** [comment]
Update to `v1.5.x-dev` and try again.

**Comment by taimaiduc** [comment]
@z-song  run `composer update`  ?

**Comment by z-song** [comment]
`composer require encore/laravel-admin v1.5.x-dev`

**Comment by taimaiduc** [comment]
@z-song 
No icon remove image 
I also run ` php artisan vendor:publish --tag=laravel-admin-assets --force`

[![https://gyazo.com/4b267ec2c123f89248ef4c87fc6c6085](https://i.gyazo.com/4b267ec2c123f89248ef4c87fc6c6085.png)](https://gyazo.com/4b267ec2c123f89248ef4c87fc6c6085)

**Comment by z-song** [comment]
`$form->image(...)->removable();`

**Comment by taimaiduc** [comment]
@z-song Thank you so much.
If you have time can you add validation requice image? 💯
