### ISSUE TITLE
hasMany 中因 col-md-col-sm-2 造成样式错误，见图

### ISSUE THREAD

**Issue by smartymoon** [z-song/laravel-admin#1170]
![_20170912092321](https://user-images.githubusercontent.com/12489528/30303746-86031a30-979c-11e7-89ed-0482e5d16a92.png)
![_20170912092637](https://user-images.githubusercontent.com/12489528/30303747-86087822-979c-11e7-9e6e-b81079af7adb.png)

**Comment by z-song** [comment]
60244cb35f63740152029a64055ba475e3168d52 已经修复

更新到`v1.5.4`

**Comment by smartymoon** [comment]
@z-song 好奇怪，我已经更新到 1.5.4 ，但依然没有解决问题，通过composer看到的 1.5.4 的 commit 值要落后于 github  上最新的  commit 。

![_20170912175127](https://user-images.githubusercontent.com/12489528/30319822-814bd012-97e3-11e7-8bdc-4096253a5e84.png)

**Comment by z-song** [comment]
@smartymoon  这个修复还没有发布  等下周吧，或者更新到`1.5.x-dev`
