### ISSUE TITLE
Select2 in hasMany relation

### ISSUE THREAD

**Issue by gio00** [z-song/laravel-admin#1172]
Hi,

is there a way to add an option to the select2 that could open a modal for create a new item and select it.

For example I'm creating a new order that belongs to a new user, I can't find it in the list (select2 input) and so I will create it just there. 

Of course a could create the user first but I would like to have this feature too.

Thanks! :)

**Comment by z-song** [comment]
I'll consider adding this feature.

**Comment by xiaohuilam** [comment]
Now you can try https://github.com/xiaohuilam/laravel-admin-select2
