### ISSUE TITLE
多图控件(multipleImage)更新不了关联模型的字段的属性

### ISSUE THREAD

**Issue by a648132694** [z-song/laravel-admin#1173]
laravel版本 : 5.5
laravel-admin版本 : 1.5

**控制器代码:**
`$form->multipleImage('extend.pictures', '附属图片')->removable();`

**模型代码:**

```
    public function setPicturesAttribute($pictures)
    {
        if (is_array($pictures)) {
            $this->attributes['pictures'] = json_encode($pictures);
        }
    }

    public function getPicturesAttribute($pictures)
    {
        return json_decode($pictures, true);
    }

    public function extend(){
        return $this->hasOne(Pictures::class);
    }
```

但是单图或者其他类型,如文本,都是可以的,就是多图没办法修改值,可是图片也上传了

**Comment by z-song** [comment]
```php
public function setPicturesAttribute($pictures)
    {
        if (is_array($pictures)) {
            $this->attributes['pictures'] = json_encode($pictures);
        }
    }

    public function getPicturesAttribute($pictures)
    {
        return json_decode($pictures, true);
    }
```

这两个方法不是应该放在`Pictures`模型里面么？

**Comment by a648132694** [comment]
不好意思,我代码贴得不谨慎,是放在Pictures模型里的.
现在的问题是,都是同一个字段的情况下,都是指向Pictures模型的pictures属性
我用单图的控件,可以执行到Pictures模型的setPicturesAttribute和getPicturesAttribute方法,但是一换到多图之后,就没有执行这两个方法了

**Comment by z-song** [comment]
确实有问题 待我修复

**Comment by z-song** [comment]
修复了，更新到`v1.5.x-dev`

**Comment by a648132694** [comment]
@z-song 好,我更新试试,辛苦了

**Comment by a648132694** [comment]
关系模型的多图增加和更新都没问题了,但是删除关系模型的多图里的图片还是删除不了

**Comment by z-song** [comment]
提交了修复  稍后再更新一下 `v1.5.x-dev`

**Comment by a648132694** [comment]
下载更新试了下,可以了,辛苦了

**Comment by xuchuyuan** [comment]
![image](https://user-images.githubusercontent.com/2909307/34998193-5dc005d4-fb19-11e7-84d4-43b3929d4cd7.png)
你好 我现在上传图片成功，但是图片更新不到关联表的字段里，我的主表是newhome,关联表newhomeimages,在newhome中已经定义了homeImages(){hasmany()},类似于上图的调用，无法插入关联表，是不是哪里用法有问题？
