### ISSUE TITLE
qiniu云存储方式在5.5 不支持

### ISSUE THREAD

**Issue by Share-Man** [z-song/laravel-admin#1174]
多次检查，发现仍然不行。

>  InvalidArgumentException In FilesystemManager.php line 124 :
> Driver [qiniu] is not supported.

**Comment by elinxer** [comment]
`composer require zgldh/qiniu-laravel-storage`
然后再config/app.php 下provider加
// 七牛包
zgldh\QiniuStorage\QiniuFilesystemServiceProvider::class

**Comment by a648132694** [comment]
安装对应的云存储包就好,阿里云的oss也一样

**Comment by Share-Man** [comment]
之前就是这样操作的奥 还是不行

**Comment by Share-Man** [comment]
仍然提示Driver [qiniu] is not supported.

**Comment by a648132694** [comment]
你这个qiniu有配到了config里面去吗?我这边oss配完直接可以用了

**Comment by elinxer** [comment]
我这边多类型服务器都可以，你的情况或者有点特殊，或者某些配置没做好
![image](https://user-images.githubusercontent.com/7327251/30362663-a4ebd3ee-988f-11e7-9005-7441de3434b2.png)
![image](https://user-images.githubusercontent.com/7327251/30362680-be893760-988f-11e7-86fc-3de504b9e14d.png)

**Comment by Share-Man** [comment]
配置进去了的奥
![qq 20170913143305](https://user-images.githubusercontent.com/4065724/30362891-96a1a9d4-9890-11e7-960e-e6c55d071971.jpg)
![qq 20170913143319](https://user-images.githubusercontent.com/4065724/30362890-969d9948-9890-11e7-90da-e667c7e907a3.jpg)
![qq 20170913143341](https://user-images.githubusercontent.com/4065724/30362892-96d65094-9890-11e7-855c-4e9ef1320ffa.jpg)

**Comment by Share-Man** [comment]
重装了一次之后可以了！谢谢！

**Comment by z-song** [comment]
`Driver [qiniu] is not supported.`  明显是驱动没装好
