### ISSUE TITLE
1.5版本将代码拷贝到另一台电脑后 访问admin报404错误 

### ISSUE THREAD

**Issue by leeib** [z-song/laravel-admin#1175]
原电脑能正常访问，新电脑报404，两台电脑环境应该没区别  都是用的同一个版本的phpStudy；
http://www.laraveldemo.com/ 能正常访问laravel的主页；
http://www.laraveldemo.com/admin 报404；
执行php artisan route:list 没有发现admin路由；  
安装的是1.5.3版本；

**Comment by z-song** [comment]
run `php artisan package:discover`

**Comment by leeib** [comment]
已解决，3Q！
