### ISSUE TITLE
上传文件如果检测同名文件生成的新文件名后缀名会错误

### ISSUE THREAD

**Issue by a648132694** [z-song/laravel-admin#1176]
laravel版本 : 5.5
laravel-admin版本 : 1.5-dev

在所有上传控件中,有个检测是否同名的方法,里面调用了
encore\laravel-admin\src\Form\Field\UploadField.php里的generateUniqueName方法
```php
    protected function generateUniqueName(UploadedFile $file)
    {
        return md5(uniqid()).'.'.$file->guessExtension();
    }
```
但是这个`$file->guessExtension();`方法对部分格式生成的后缀名会错误,比如.mp3生成.bin,导致上传后文件的类型就不对了
我现在用
`$file->getClientOriginalExtension();`
这个方法暂时替代了下,希望看下这个问题

**Comment by z-song** [comment]
修复了   稍后更新到`1.5.x-dev`

**Comment by a648132694** [comment]
好,辛苦了
