### ISSUE TITLE
支持阿里云OSS吗？

### ISSUE THREAD

**Issue by DreamboyA** [z-song/laravel-admin#1178]
Laravel 版本 5.5.3
laravel-admin 版本 1.5.4

**Comment by a648132694** [comment]
支持,直接下oss的laravel相关的包,配置好就可以用了

**Comment by DreamboyA** [comment]
安装的这个扩展包，是不是不对？
https://github.com/johnlui/AliyunOSS

**Comment by DreamboyA** [comment]
需要在config/filesystems.php怎么配置？

**Comment by DreamboyA** [comment]
@a648132694 非常感谢

**Comment by shencm** [comment]
@mushishixian 我用你说的这个包 报错
ErrorException In FilesystemAdapter.php line 389 :
This driver does not support retrieving URLs. (View: D:\hycf\hycfServer\vendor\encore\laravel-admin\resources\views\form.blade.php)

**Comment by l269798518** [comment]
> <img alt="image" width="1258" src="https://user-images.githubusercontent.com/34508080/50332512-4cbb5480-053d-11e9-811b-1c892fca743e.png">
> 
> 我的配置jacobcyl的扩展之后，打开后台出现这个错误，请问这个怎么解决啊？

这个错大部分情况是指定访问的 oss 路径没有指定文件，访问 oss 上的文件时会检测是否存在，不存在就是报这个错。
