### ISSUE TITLE
grid 多个 expand 怎么操作。

### ISSUE THREAD

**Issue by xtcuiyd** [z-song/laravel-admin#1179]
grid 多个 expand 怎么操作。
后面的会把前面的expand值覆盖掉。

**Comment by z-song** [comment]
自己研究一下expand扩展的源码吧，遇到问题去熟悉一下bootstrap和jquery，毕竟这不是laravel-admin的内置功能。

**Comment by RobinHoo1973** [comment]
源代码在哪里,找不到啊
