### ISSUE TITLE
order 默认值没有生成，建议使用sort_id作为排序字段

### ISSUE THREAD

**Issue by xqbumu** [z-song/laravel-admin#118]
版本：1.3

uri：admin/auth/menu

提交请求体：
```
------WebKitFormBoundaryAK9bJ6kY8imsJKiN
Content-Disposition: form-data; name="parent_id"

0
------WebKitFormBoundaryAK9bJ6kY8imsJKiN
Content-Disposition: form-data; name="title"

User
------WebKitFormBoundaryAK9bJ6kY8imsJKiN
Content-Disposition: form-data; name="icon"

fa-users
------WebKitFormBoundaryAK9bJ6kY8imsJKiN
Content-Disposition: form-data; name="uri"

user
------WebKitFormBoundaryAK9bJ6kY8imsJKiN
Content-Disposition: form-data; name="roles[]"


------WebKitFormBoundaryAK9bJ6kY8imsJKiN
Content-Disposition: form-data; name="_token"

ROkusbRr6hrsdjg29pPpApCB07hl7ObDpGQQL9OU
------WebKitFormBoundaryAK9bJ6kY8imsJKiN--
```

报错：
"SQLSTATE[HY000]: General error: 1364 Field 'order' doesn't have a default value (SQL: insert into `admin_menu` (`parent_id`, `title`, `icon`, `uri`, `updated_at`, `created_at`) values (0, User, fa-users, user, 2016-11-21 09:47:02, 2016-11-21 09:47:02))"

代码还没太看懂，正在研究中，无从下手，早晨form的fsubmit看了一天不知道从哪看，回头一看，你已经解决了，就pull了，完美。

**Comment by z-song** [comment]
@xqbumu https://github.com/z-song/laravel-admin/blob/1.3/migrations/2016_01_04_173148_create_admin_tables.php#L41 1.3 里面的menu表的order字段有默认值，你可能需要修改一下这个字段，添加默认值
```sql

ALTER TABLE `admin_menu` MODIFY COLUMN `order` int(11) NOT NULL DEFAULT '0';

```

**Comment by xqbumu** [comment]
完美解决,感觉是我migrations的版本问题，thx
