### ISSUE TITLE
全新安装laravel-admin 1.5.4，laravel版本5.5.3

### ISSUE THREAD

**Issue by chensongah** [z-song/laravel-admin#1180]
我的安装步骤如下：
`# php artisan --version`
> Laravel Framework 5.5.3

`# composer require encore/laravel-admin "1.5.*"`
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Package operations: 2 installs, 0 updates, 0 removals
>   - Installing symfony/dom-crawler (v3.1.10): Loading from cache
>   - Installing encore/laravel-admin (v1.5.4): Loading from cache
> encore/laravel-admin suggests installing intervention/image (Required to handling and manipulation uplo
> encore/laravel-admin suggests installing spatie/eloquent-sortable (Required to built orderable gird.)
> Writing lock file
> Generating optimized autoload files
> > Illuminate\Foundation\ComposerScripts::postAutoloadDump
> > @php artisan package:discover
> Discovered Package: fideloper/proxy
> Discovered Package: laravel/tinker
> Discovered Package: encore/laravel-admin
> Package manifest generated successfully.

`# composer require intervention/image`
`# composer require spatie/eloquent-sortable`
`# php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider"`
> Copied Directory [/vendor/encore/laravel-admin/config] To [/config]
> Copied Directory [/vendor/encore/laravel-admin/resources/lang] To [/resources/lang]
> Copied Directory [/vendor/encore/laravel-admin/database/migrations] To [/database/migrations]
> Copied Directory [/vendor/encore/laravel-admin/resources/assets] To [/public/vendor/laravel-admin]
> Publishing complete.

`# php artisan admin:install`

> Nothing to migrate.
>   [Illuminate\Database\QueryException]                                                                
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ahphp.admin_users' doesn't exist (SQL:   
>   select count(*) as aggregate from `admin_users`)                                                    
>                                                                                                
>   [PDOException]                                                                               
>   SQLSTATE[42S02]: Base table or view not found: 1146 Table 'ahphp.admin_users' doesn't exist 

当执行 admin:install时，没有写如数据表，而且sql报错。数据表是哪个步骤安装的？谢谢

**Comment by z-song** [comment]
数据表的migrate是包含在`admin:install`命令里面的，奇怪的是你这边显示`Nothing to migrate.`

**Comment by chensongah** [comment]
你好，大神。我本地的php版本为：
> PHP 7.1.5 (cli) (built: May 28 2017 19:21:41) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies

运行 php artisan migrate 之后提示的是：Nothing to migrate. 大神有没有其他的建议？

**Comment by z-song** [comment]
去数据库检查下数据表有没有migrate

**Comment by chensongah** [comment]
数据库没有迁移文件，没有数据表；
vendor/encore/laravel-admin/migrations/2016_04_173148_create_admin_tables.php里有迁移数据的：

> Schema::connection($connection)->create(config('admin.database.users_table'), function (Blueprint $table) {
>             $table->increments('id');
>             $table->string('username', 190)->unique();
>             $table->string('password', 60);
>             $table->string('name');
>             $table->string('avatar')->nullable();
>             $table->string('remember_token', 100)->nullable();
>             $table->timestamps();
>         });
composer.json文件如下：
> {
>     "name": "laravel/laravel",
>     "description": "The Laravel Framework.",
>     "keywords": ["framework", "laravel"],
>     "license": "MIT",
>     "type": "project",
>     "require": {
>         "php": ">=7.0.0",
>         "encore/laravel-admin": "1.5.*",
>         "fideloper/proxy": "~3.3",
>         "intervention/image": "^2.4",
>         "laravel/framework": "5.5.*",
>         "laravel/tinker": "~1.0",
>         "spatie/eloquent-sortable": "^3.4"
>     },
>     "require-dev": {
>         "filp/whoops": "~2.0",
>         "fzaninotto/faker": "~1.4",
>         "mockery/mockery": "0.9.*",
>         "phpunit/phpunit": "~6.0"
>     },
>     "autoload": {
>         "classmap": [
>             "database/seeds",
>             "database/factories"
>         ],
>         "psr-4": {
>             "App\\": "app/"
>         }
>     },
>     "autoload-dev": {
>         "psr-4": {
>             "Tests\\": "tests/"
>         }
>     },
>     "extra": {
>         "laravel": {
>             "dont-discover": [
>             ]
>         }
>     },
>     "scripts": {
>         "post-root-package-install": [
>             "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
>         ],
>         "post-create-project-cmd": [
>             "@php artisan key:generate"
>         ],
>         "post-autoload-dump": [
>             "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
>             "@php artisan package:discover"
>         ]
>     },
>     "config": {
>         "preferred-install": "dist",
>         "sort-packages": true,
>         "optimize-autoloader": true
>     }
> }

**Comment by z-song** [comment]
`database/migrations`目录下有没有`2016_04_173148_create_admin_tables.php`??

没有的话`php artisan vendor:publish --tag=laravel-admin-migrations`, 再migrate

**Comment by chensongah** [comment]
果然是没有这个迁移文件，我自检下哈，谢谢
