### ISSUE TITLE
多图编辑不显示

### ISSUE THREAD

**Issue by gystone** [z-song/laravel-admin#1181]
多图 上传 没问题，但是编辑的时候多图不显示图片
![image](https://user-images.githubusercontent.com/13912882/30407836-6ca13f26-992d-11e7-8af3-14f44bd7b257.png)  
单图没有问题，代码是这样写的
![image](https://user-images.githubusercontent.com/13912882/30407849-820141ae-992d-11e7-9ec0-f6ad6e464263.png)
多图刚开始做的时候是没有问题的，我是在昨天下午的时候更新了一下composer，然后再看多图 就没有图片了，我看这里有人说是要把vendor/encore/laravel-admin/assets 文件拷贝到 public/packages中,经尝试后，无变化。

控制器get  set 的Attribute 也写了
![image](https://user-images.githubusercontent.com/13912882/30407911-00855736-992e-11e7-8f8c-4fc812a4ffdb.png)
请问，还有什么办法能解决这个问题么？

**Comment by z-song** [comment]
版本？？

**Comment by gystone** [comment]
我的版本是1.4的。 好的，我现在就去一个一个试看看

**Comment by gystone** [comment]
@z-song
 控制台报错了 
GET http://web.tjadmin.com/packages/clipboard/dist/clipboard.min.js 404 (Not Found)

clipboard.min.js 这个文件，我在项目中并没有搜到

**Comment by z-song** [comment]
@gystone 没有重现你的问题，建议升级到laravel 5.5+ laravel-admin 1.5， 1.4后面就慢慢不维护了
@yangzhipeng 一次多选几张图

**Comment by yangzhipeng** [comment]
@z-song   厉害　谢谢！！

**Comment by gystone** [comment]
@z-song 我把代码放另一台机器上运行了一下，可以显示图片，是没有问题的，那台电脑并没有更新composer，可能是我更新composer的问题。升级laravel5.5 php环境也要升级到7.0，是个不小的工程。谢谢啦。

**Comment by kelvenchi** [comment]
求教， 我也遇到类似问题， 请问您是怎么解决的也是1.4的版本。

**Comment by Mrkaula** [comment]
@z-song 有个问题卡了我许久，我上网查了没解决。想请您帮忙有空解答，谢谢

提问：单图和多图上传没问题，但是编辑的时候不显示图片

版本交代：PHP 7.2.19  +  Laravel 5.8.8  + laravel-admin 1.6 +mysql5.6

尝试：清代码缓存 php artisan cache:clear，清浏览器缓存

代码和图片如下：
页面显示
![image](https://user-images.githubusercontent.com/17514042/62039373-29226000-b22a-11e9-9dca-9d5ded9c7dc9.png)


model类
![image](https://user-images.githubusercontent.com/17514042/62039149-af8a7200-b229-11e9-9419-e6e5d4001572.png)

controller
![image](https://user-images.githubusercontent.com/17514042/62039207-cf219a80-b229-11e9-9341-7df6dd65b2c4.png)

数据库mysql（字段picture_description，类型varchar）
![image](https://user-images.githubusercontent.com/17514042/62039294-05f7b080-b22a-11e9-8ba0-3839e1c783b1.png)

**Comment by z-song** [comment]
@Mrkaula 这个问题和缓存根本没有关系

图片不显示，那肯定是url错了，那你就找出错误的url，去找到哪里配置错了。

**Comment by Mrkaula** [comment]
首先非常谢谢您能回复我，我很开心！！！也很意外！


您说的url问题，我也考虑过。但好像不是这个问题，下面是我的排查步骤123。能再麻烦您帮我看一下么




1.文件保存地址，我设置了config目录下的两个文件: filesystems.php 和admin.php 如下图





2.保存后，本地的相应目录里有成功上传图片





3.页面dubeg看到img标签的地址加载出来了







------------------ 原始邮件 ------------------
发件人: "Song"<notifications@github.com>;
发送时间: 2019年7月29日(星期一) 晚上6:30
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>;
抄送: "Kaula"<2673657594@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [z-song/laravel-admin] 多图编辑不显示 (#1181)




@Mrkaula 这个问题和缓存根本没有关系
 
图片不显示，那肯定是url错了，那你就找出错误的url，去找到哪里配置错了。

**Comment by z-song** [comment]
看不到图

**Comment by z-song** [comment]
你网站的url是什么？

**Comment by Mrkaula** [comment]
服务器本地调试界面：![image](https://user-images.githubusercontent.com/17514042/62043741-b61de700-b233-11e9-8d80-f193b033c689.png)

另外还有个对外访问的公网IP和端口。

**Comment by z-song** [comment]
你没发现图片的url没带端口58089吗？？？

**Comment by Mrkaula** [comment]
谢谢您，好了。对不起，我浪费了您的时间，我是个新手不太懂，谢谢^_^

**Comment by Mrkaula** [comment]
@z-song 您好。请问，多图上传，模型详情页如何读取？

参考：官网文档http://laravel-admin.org/docs/zh/model-show-fields，

报错如下：
![image](https://user-images.githubusercontent.com/17514042/62051421-ed958f00-b245-11e9-8377-ce47b3d9b374.png)

代码：
![image](https://user-images.githubusercontent.com/17514042/62051521-259cd200-b246-11e9-933f-40c54549daad.png)

数据库存储：
![image](https://user-images.githubusercontent.com/17514042/62051665-6ac10400-b246-11e9-92d5-ba96511b5e1f.png)

说明：单图正常上传编辑详情页都正常
