### ISSUE TITLE
wangEditor引入后点击编辑出现报错

### ISSUE THREAD

**Issue by elinxer** [z-song/laravel-admin#1182]
如图：
![image](https://user-images.githubusercontent.com/7327251/30413109-d1d11abc-994e-11e7-802e-b636d2568915.png)
引用
![image](https://user-images.githubusercontent.com/7327251/30413136-f181c1a4-994e-11e7-97f8-76e60460e7e5.png)
这是一个hasOne模型关联

laravel5.5
laravel-admin1.5.*

**Comment by z-song** [comment]
`$('input[name="description[description]"]')`
