### ISSUE TITLE
Javascript errors on each page

### ISSUE THREAD

**Issue by iparrabb** [z-song/laravel-admin#1183]
Hey there,

I have errors on each page when it change, for example, when clicked the link for navigate to users or roles page.

I have installed the package in a new and clean project.

https://i.imgur.com/bXHA9oP.png

**Comment by z-song** [comment]
Looks like exception of app.min.js, this is not imported by laravel-admin, maybe you should check this file

**Comment by iparrabb** [comment]
This seems compatibility problem, I only installed this package in a Laravel 5.5 empty project.
