### ISSUE TITLE
怎么修改默认语言

### ISSUE THREAD

**Issue by DreamboyA** [z-song/laravel-admin#1187]
config/app.php改为    'locale' => 'zh_cn', 了，但是界面上还是英文，还有哪需要配置吗？

**Comment by z-song** [comment]
看`resources/lang`目录下有什么语言

**Comment by a648132694** [comment]
@z-song 我记得现在lang目录的是zh-CN,和文档说的zh_CN有点出入

**Comment by z-song** [comment]
修改了一下文档

**Comment by fan153693** [comment]
![image](https://user-images.githubusercontent.com/7405726/42753805-a1bb1032-8924-11e8-9ea2-ff91860d8eea.png)

http://laravel-admin.org/docs/#/zh/qa?id=%E8%AE%BE%E7%BD%AE%E8%AF%AD%E8%A8%80
