### ISSUE TITLE
Form opened two times 

### ISSUE THREAD

**Issue by gio00** [z-song/laravel-admin#1191]
Hi, 

I'm not 100% sure if this is correct use of this functions. 

Anyway I wanted a box outside the tabbed form that I have in the form function, so I did this.

```   
public function create()
{
    return Admin::content(function (Content $content) {
         $content->row($this->box());
         $content->body($this->form());
    });
}
```

the problem is that doing this the form is opened two times( two <form ....> in the html source). I mean everything works anyway but it shouldn't happen.

PHP 7.1.8, Laravel 5.5.4, Laravel-admin 1.5.4

**Comment by z-song** [comment]
So what the method `box` looks like?

**Comment by kilimall** [comment]
@z-song I have a big issue after upgraded from 5.4 to 5.4, every time i post the form, there will make request twice, then will create two datas even i submit a time.

**Comment by gio00** [comment]
@z-song The method box it's nothing complicated, it's just a widget box
```
    public function box(){
        return new Box('Total', '<input disabled type=number id="total"> ');
    }
```

**Comment by kilimall** [comment]
I comment out these codes, it ok now:

`/*
    $(document).on('submit', 'form[pjax-container]', function(event) {
        $.pjax.submit(event, '#pjax-container')
    });
    */`

**Comment by z-song** [comment]
I have no idea about this, what if comment out `$content->row($this->box());`?

**Comment by gio00** [comment]
@z-song yes, if I comment out that line the form opens only once

**Comment by z-song** [comment]
Fixed now
