### ISSUE TITLE
Grid的Switch控件在处理关系模型字段时显示错误

### ISSUE THREAD

**Issue by mushishixian** [z-song/laravel-admin#1194]
laravel版本 : 5.5
laravel-admin版本 : 1.5-dev

**控制器代码:**

` $grid->column('child_pics.status','子状态')->switch();`

其中extend.status是一对一的关联模型字段,加载页面后,会报js错误

![image](https://user-images.githubusercontent.com/13271701/30509737-0aae15aa-9aea-11e7-9c60-488d998b251e.png)

此时js出现了语法错误
同时,bootstrapSwitch也挂载不到样式,原因是因为$('.child_pics.status')这样的jquery语法找不到正确位置的元素

也没办法用switch直接更新关系模型的字段,因为提交的字段名没有对应到关系模型里去,要以child_pics[status]这样的形式才能正确更新

**Comment by z-song** [comment]
没有考虑到这种关联关系，后面会修复

**Comment by woshihaiyong168** [comment]
遇到同样问题是否修复
