### ISSUE TITLE
checkbox 提交的时候提示：Array to string conversion

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1195]
checkbox 提交的时候提示：Array to string conversion
> $form->checkbox('facilities', '卫浴')->options($tmp);

对应字段类型为 varchar(255) 。
请问这问题是怎么解决的丫？

额， 忘记说了， 我用的是1.4的版本

**Comment by kelvenchi** [comment]
找到原因了

> $form->checkbox('facilities', '卫浴')->options($tmp);

改成

> $form->checkbox('facilities[]', '卫浴')->options($tmp);

就可以了

**Comment by kelvenchi** [comment]
`DB::transaction(function () {
            $updates = $this->prepareUpdate($this->updates);

            foreach ($updates as $column => $value) {
                /* @var Model $this->model */
                if (is_array($value)) $value = implode(',', $value); // 解决 checkbox 提交的报错“array to string 的bug”
                $this->model->setAttribute($column, $value);
            }

            $this->model->save();

            $this->updateRelation($this->relations);
        });`

From.php 里面我加了这样一行来解决的。这个应该是bug吧

**Comment by z-song** [comment]
文档上注明了
> 将选项数组存储到单字段中，如果字段是字符串类型，那就需要在模型里面为该字段定义[访问器和修改器](https://laravel.com/docs/5.5/eloquent-mutators)来存储和读取了。

**Comment by Guogb** [comment]
写了修改器，转换成字符串，提交后 save返回true 但是数据库没有更新。演示站点也是这样
