### ISSUE TITLE
1.5版的不能在列表中修改字段

### ISSUE THREAD

**Issue by qiumzh** [z-song/laravel-admin#1200]
![image](https://user-images.githubusercontent.com/12442026/30529551-1a2f8210-9c71-11e7-8c0d-d784dd900988.png)

![image](https://user-images.githubusercontent.com/12442026/30529561-35493c12-9c71-11e7-8e28-872437956eed.png)
![image](https://user-images.githubusercontent.com/12442026/30529577-487d3306-9c71-11e7-8ff4-cb35017bd10a.png)

**Comment by Share-Man** [comment]
I met the same problem .

**Comment by z-song** [comment]
@qiumzh @Share-Man see #1167

upgrade to `v1.5.4`, then run command `php artisan vendor:publish --tag=laravel-admin-assets --force`

**Comment by Share-Man** [comment]
@z-song Thanks !

**Comment by qiumzh** [comment]
还是不可以。
已经运行了php artisan vendor:publish --tag=laravel-admin-assets --force
![image](https://user-images.githubusercontent.com/12442026/30530842-a9bc4e76-9c7c-11e7-8d00-b911388e3777.png)

**Comment by z-song** [comment]
浏览器缓存清一下

**Comment by qiumzh** [comment]
浏览器缓存也清了，还是不可以，还是同样的错误
![image](https://user-images.githubusercontent.com/12442026/30531391-a1f879c2-9c80-11e7-8106-fcf1cceefa7c.png)

**Comment by z-song** [comment]
打开`public/vendor/laravel-admin/laravel-admin/laravel-admin.js`, 看开头是不是
```js
$.fn.editable.defaults.params = function (params) {
    params._token = LA.token;   //  看这一行
    params._editable = 1;
    params._method = 'PUT';
    return params;
};
```

**Comment by qiumzh** [comment]
![image](https://user-images.githubusercontent.com/12442026/30531501-59759db4-9c81-11e7-8e84-6e75fae45371.png)
这行是最新的。旧版本的是'{{csrf_token()}}'

**Comment by z-song** [comment]
那就是浏览器缓存没清空

**Comment by qiumzh** [comment]
@z-song 果然是的，我应该早点换个浏览器来试一下的。非常感谢。
