### ISSUE TITLE
$form->image和$form->multipleImage上传的图片的预览图，一片空白。

### ISSUE THREAD

**Issue by magicdiven** [z-song/laravel-admin#1206]
这是什么情况？

**Comment by gfd6th** [comment]
```
'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',

```

**Comment by magicdiven** [comment]
@gfd6th 我是按照手册上配的，在public/uploads/目录，我把img的src提出来，单独在浏览器上打开，图片是可以显示的。

**Comment by magicdiven** [comment]
@gfd6th  我发现是标签问题，默认用的是<images>标签，我在浏览器控制台改成了img就可以显示了。这意味着我要去改源码吗？

**Comment by magicdiven** [comment]
@z-song 麻烦解决下，或者说是我哪里配错了？上传的图片，系统默认都用了images标签，所以无法展示。我在浏览器改成img标签就ok了

**Comment by z-song** [comment]
@magicdiven 参考 #687

**Comment by magicdiven** [comment]
@z-song 按照你说的，已经解决，多谢，么么哒

**Comment by z-song** [comment]
1.4 以后会慢慢不维护了，建议能升级到laravel 5.5
