### ISSUE TITLE
多图上传之后再次编辑预览框出不来， console也没报错

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1208]
`$form->multipleImage('images','图片');`

数据模型里面有：

```php
    public function setImagesAttribute($pictures)
    {
        if (is_array($pictures)) {
            $this->attributes['images'] = json_encode($pictures);
        }
    }

    public function getImagesAttribute($pictures)
    {
        return json_decode($pictures, true);
    }
```
再次编辑就是看不到预览框

![img](https://www.perlface.net/wp-content/uploads/2017/09/QQ图片20170918172231.png)

额， 我的这个表格是放到tab里面了， 这应该没啥影响吧。

**Comment by z-song** [comment]
不放tab里面能正常？？

**Comment by kelvenchi** [comment]
额， 刚才试了下， 也不能显示出来。 卡这儿了。

**Comment by z-song** [comment]
版本？？

**Comment by kelvenchi** [comment]
1.4

**Comment by z-song** [comment]
复制`vendor/encore/laravel-admin/assets/bootstrap-fileinput`，覆盖掉`public/packages`下的同名目录, 清空浏览器

**Comment by kelvenchi** [comment]
没变化丫，还是那样

**Comment by magicdiven** [comment]
@z-song  我刚才按你说的，在正常窗口好了，但是在隐身窗口依然不可以，这是什么原因呢？

**Comment by z-song** [comment]
那我也没有办法了，没遇到过这个问题，重新安装一个，迁移过去吧

**Comment by kelvenchi** [comment]
重装了还是一样 @z-song

**Comment by Shijf** [comment]
@kelvenchi 模型里面我也写了这个，还是显示Array to string conversion，是怎么回事呀

**Comment by kelvenchi** [comment]
你好， 我更新到1.5 就没有这个问题了。 我原来的方法是：

[image: 内嵌图片 1]

把 那行 注释取消掉就可以， 但是这样破坏了， 不更改框架源码的初衷， 所以我还是选择升级了。

2017-09-25 16:08 GMT+08:00 Shijf <notifications@github.com>:

**Comment by niofeng** [comment]
1.7.14编辑时无预览.
