### ISSUE TITLE
[NEED HELP] Admin::JS can not load script with pjax.

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1211]
I using Admin::js('link') to load script. When going to another page then come back js **can not** load.
**NOT REFRESH PAGE** using js pjax in your lib.
1. Dashboard link is ok 
2. User link is ok 
3. Dashboard link comback is get error js

Can you help me ? :(.

Can we have a config to disable pjax ?

**Comment by z-song** [comment]
Open `public/vendor/laravel-admin/laravel-admin/laravel-admin.js` , comment out the rows associated with pjax

**Comment by taimaiduc** [comment]
@z-song can we have another solution?

**Comment by alihastam** [comment]
hello
**for laravel_admin with version #1.5**

1-Change AdminServiceProvider in vendor/encore/laravel-admin/src
`$this->loadViewsFrom(__DIR__.'/../resources/views', 'admin');`
to
       ` $this->loadViewsFrom(resource_path('views/admin'),'admin');`

2.Copy all views from  vendor/encore/laravel-admin/resources to your resources/view
3-Add your script in the end of `content.blade.php` before the `@endsection` tag is closed
