### ISSUE TITLE
图片能新增，删除，但是不能修改

### ISSUE THREAD

**Issue by xiuhuai** [z-song/laravel-admin#1212]
参考文档http://laravel-admin.org/docs/#/zh/model-form-upload
按照这个方法设置好后，

图片能新增，删除，但是不能修改，权限没有问题，都能删除哦，麻烦指导，谢谢

![6](https://user-images.githubusercontent.com/25577285/30571055-b11765c0-9d17-11e7-9d9b-a41c663958ff.png)
 修改后变成了 C:\Windows\Temp\php5521.tmp
 新增的时候是images/9055928775f7899353ade0c36fece644.jpeg

**Comment by xiuhuai** [comment]
修改后变成了 C:\Windows\Temp\php5521.tmp

**Comment by z-song** [comment]
版本？？

你的图片上传组件的显示有问题，贴代码

**Comment by xiuhuai** [comment]
admin1.5 版本
laravel5.5的
 浏览器是360，手机里就正常，但是图还是修改不了
只能增加

**Comment by xiuhuai** [comment]
<div class="col-sm-8">
--
  |  
  |  
  | <input type="file" class="product_picture" name="product_picture" data-initial-preview="http://localhost/uploads/C:\Windows\php8864.tmp" />
  |  
  |  
  | </div>
  | </div>
  |  
  | <div class="form-group ">
  | <label class="col-sm-2 control-label">logo地址</label>
  | <div class="col-sm-8">
  | <div class="box box-solid box-default no-margin">
  | 
  | <div class="box-body">
  | C:\Windows\php8864.tmp&nbsp;
  | </div>
  | </div>

**Comment by xiuhuai** [comment]
`

<div class="col-sm-8">
--
  |  
  |  
  | <input type="file" class="product_picture" name="product_picture" data-initial-preview="http://localhost/uploads/C:\Windows\php8864.tmp" />
  |  
  |  
  | </div>
  | </div>
  |  
  | <div class="form-group ">
  | <label class="col-sm-2 control-label">logo地址</label>
  | <div class="col-sm-8">
  | <div class="box box-solid box-default no-margin">
  | 
  | <div class="box-body">
  | C:\Windows\php8864.tmp&nbsp;
  | </div>
  | </div>

`

**Comment by xiuhuai** [comment]
`

<div class="col-sm-8">
--
  |  
  |  
  | <input type="file" class="product_picture" name="product_picture" data-initial-preview="http://localhost/uploads/C:\Windows\php8864.tmp" />
  |  
  |  
  | </div>
  | </div>
  |  
  | <div class="form-group ">
  | <label class="col-sm-2 control-label">logo地址</label>
  | <div class="col-sm-8">
  | <div class="box box-solid box-default no-margin">
  | 
  | <div class="box-body">
  | C:\Windows\php8864.tmp&nbsp;
  | </div>
  | </div>

`

**Comment by xiuhuai** [comment]
`<input type="file" class="product_picture" name="product_picture" data-initial-preview="http://localhost/uploads/C:\Windows\php8864.tmp" />`

**Comment by xiuhuai** [comment]
感谢你song 原来是 根目录放在public上一级导致的，谢谢
