### ISSUE TITLE
数据来自复杂SQL查询，grid查询条件问题

### ISSUE THREAD

**Issue by chenzi2015** [z-song/laravel-admin#1214]
如果覆盖model的paginate方法，然后自定义sql。 只能使用日期查询， 添加其他字段报错。

**Comment by z-song** [comment]
model-grid是基于eloquent模型，想要使用模型的什么功能，就去覆盖掉模型的对应方法，文档的实例只是告诉你取出数据是要覆盖paginate方法，你要举一反三

**Comment by chenzi2015** [comment]
是这样的， 我加了查询条件，点击查询后url里面就有查询条件， 但是框架没有去调用model的paginate方法。  还需要覆盖哪个方法才行呢？

**Comment by chenzi2015** [comment]
我想能不能把查询条件直接带到paginate里面去，我自己拼装。 这样最好！

**Comment by z-song** [comment]
没有去调用model的paginate方法??  那是调了哪个方法，或者有什么报错？？

**Comment by chenzi2015** [comment]
我选择时间后点击查询就会报这个错误： 
QueryException In Connection.php line 647 :
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'transfer' doesn't exist (SQL: select count(*) as aggregate from `transfer` where `created_at` between 2017-09-19 00:00:00 and 2017-09-19 00:00:00)
报错后执行不到model的paginate方法了。

**Comment by chenzi2015** [comment]
应该是直接去查询表去了， 没有去调用model的paginate方法。

**Comment by z-song** [comment]
调用了model的`whereBetween`方法，需要去覆盖model的`whereBetween`方法
```php
public function whereBetween()
{
    ...

    return $this;
}
```
在方法中用func_get_args()获取接收的参数和传值，然后记录下来，到paginate方法中去拼接sql语句查询

**Comment by chenzi2015** [comment]
哦哦， 好的， 我试试看， 谢谢！

**Comment by chenzi2015** [comment]
@z-song 重写了whereBetween方法后也调用不到paginate， 最好是点击查询后直接到paginate方法里面，然后拼接sql。

**Comment by chenzi2015** [comment]
最后用视图完美搞定了
