### ISSUE TITLE
关于图片上传问题

### ISSUE THREAD

**Issue by zhfin** [z-song/laravel-admin#1219]
![image](https://user-images.githubusercontent.com/30734994/30591752-a984f340-9d76-11e7-91a9-5fa36fe44452.png)

这是config/admin.php的配置
![image](https://user-images.githubusercontent.com/30734994/30591791-d15cec6a-9d76-11e7-984d-0d3443dcf078.png)

这是config/filesystems.php的配置
![image](https://user-images.githubusercontent.com/30734994/30591816-edac52d4-9d76-11e7-81cc-ad428b130d42.png)

这是public文件夹结构
![image](https://user-images.githubusercontent.com/30734994/30591842-0246bef0-9d77-11e7-95cf-a1dd006da177.png)

提出两个问题
1.如图1显示  图片文件地址为/uploads/uploads/... 是哪里出了问题
2.如下图所示  在上传user资料中的图片时  报了500错误
![image](https://user-images.githubusercontent.com/30734994/30592047-e35e9a34-9d77-11e7-917a-d0f96f4626ee.png)

希望对这两个问题给予答复，谢谢。

**Comment by yang5664** [comment]
你的設定有點不太一樣
<img width="399" alt="screen shot 2017-09-19 at 9 30 11 pm" src="https://user-images.githubusercontent.com/5953010/30594770-ce626ab6-9d81-11e7-92fe-d5d563e66a82.png">
<img width="457" alt="screen shot 2017-09-19 at 9 30 23 pm" src="https://user-images.githubusercontent.com/5953010/30594779-d95f053c-9d81-11e7-935a-50ff6f48538c.png">

**Comment by zhfin** [comment]
根据截图所修改了配置后  还是报了500错误  无法上传图片  权限777 (laravel-admin 1.4版本) 且原来能显示的图片也都直接指向了public/image

**Comment by z-song** [comment]
第一个问题，host配置修改为你的访问url，比如`http://localhost/`
第二个问题，打开500的页面看下报的什么错误

**Comment by zhfin** [comment]
@yang5664 @z-song 修改为laravel5.5+la1.5解决了问题
