### ISSUE TITLE
laravel/framework 从5.5.3更新到5.5.7报错

### ISSUE THREAD

**Issue by zhaoyang017** [z-song/laravel-admin#1226]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.x-dev

### Description:
执行`composer update`将`laravel/framework`从5.5.3更新到5.5.7，报下面的错误，版本回退，错误消失，麻烦帮忙看一下
```
ModelNotFoundException In Builder.php line 329 :

No query results for model [App\Models\Project] create
```
![image](https://user-images.githubusercontent.com/18034112/30639163-5c992bf4-9e30-11e7-84a0-08d7a76ca6dd.png)

**Comment by z-song** [comment]
这是laravel的bug   https://github.com/laravel/framework/issues/21272

等待官方发布修复版本

**Comment by guoweibo** [comment]
框架问题：https://github.com/laravel/framework/issues/21265
