### ISSUE TITLE
form select组件 再次编辑时 数据无法复现的问题

### ISSUE THREAD

**Issue by leeib** [z-song/laravel-admin#1229]
- Laravel Version: 5.5.3
- PHP Version:7.0.12
- Laravel-admin: 1..5.4

1、这样写数据无法复现，每次编辑都都会默认选中'/admin/api/express_companies'接口返回的第一个公司：
`$form->select('express_company_id','快递公司')->options('/admin/api/express_companies');`

2、这样写能正常复现数据，但不想要搜索，而是直接列出所有快递公司供选择：
```
$form->select('express_company_id','快递公司')->options(function ($id) {
                $expressCompany = ExpressCompany::find($id);
                
                if ($expressCompany) {
                    return [
                        $expressCompany->id => $expressCompany->name
                    ];
                }
            })->ajax(config('app.url','').'/admin/api/express_companies');
```

3、目前暂时用的如下方法：
```
$form->select('express_company_id','快递公司')->options($array);
//$array由数据库查出后转换成select所需格式的数组；
```

> **第1点中所说是存在这样一个bug，还是我使用不当呢？**

**Comment by lxy1151** [comment]
按照1这样做了，就是动态加载数据，Select组件源码js如下
`$.ajax($ajaxOptions).done(function(data) {
  $("{$this->getElementClassSelector()}").select2({data: data});
});`，看到了吗，直接加载你返回的data了，所以要想选中，必须在data中做处理，如{text:"1111",id:"11",selected:true}，就会选中了；根据格式返回自己处理结果数据，需要选中加属性selected=>true

**Comment by royisme** [comment]
public function editForm(){            
$form->select('province_id','省或直辖市')->options(function($id){
//这个block里面传递的$id是null，从哪里能获得model的值呢？
});
}

**Comment by leeib** [comment]
$id 就是你当前数据行的'province_id'的值，为null表示'province_id'为空。

**Comment by zbyjm6969** [comment]
如果当前数据有值，通过options加载后，不能显示当前数据啊？
