### ISSUE TITLE
Form表单创建多个tab添加数据成功，但编辑时报错。

### ISSUE THREAD

**Issue by qiumzh** [z-song/laravel-admin#1230]
- Laravel Version: 5.5.3
- PHP Version: 7.1.2
- Laravel-admin: 1.5.4

### Description:
用Form->tab()组建表单，其中有一对一关系，也有一对多关系。数据添加成功，但是编辑的时候所有的关联关系数据回显失败。多对多的直接报错。打印出来，返回的数据都为null

这个是一对一关系编辑时打印出来的截图：
![image](https://user-images.githubusercontent.com/12442026/30689721-650a134c-9ef4-11e7-9a91-92fda3acb08b.png)

这个是多对多关系编辑时打印出来的截图：
![image](https://user-images.githubusercontent.com/12442026/30689760-7d41f6fa-9ef4-11e7-9a8c-187adc9c7dc1.png)
多对多的PHP代码截图：
![image](https://user-images.githubusercontent.com/12442026/30689793-987a206e-9ef4-11e7-8663-952dd0e09894.png)
模型关联截图：
![image](https://user-images.githubusercontent.com/12442026/30689812-aabfca3a-9ef4-11e7-833c-18b078d82e4f.png)
![image](https://user-images.githubusercontent.com/12442026/30689825-b80f07f0-9ef4-11e7-9296-489179c9afa6.png)
 请问是一个什么情况？我该怎样可以解决，谢谢。

**Comment by z-song** [comment]
更新到`1.5.x-dev`或者等下一个小版本发布

**Comment by qiumzh** [comment]
@z-song 还有一个小问题就是，多图上传时，如果是创建时是无效的，只有编辑时多图上传的功能才有效。这个很奇怪。

**Comment by qiumzh** [comment]
$form->image('img', '商品主图')->rules('required');
$form->multipleImage('slideshow', '轮播图')->removable();
 
创建：
![image](https://user-images.githubusercontent.com/12442026/30732550-b1e916f2-9fa5-11e7-8620-0113821b2c30.png)

编辑：
![image](https://user-images.githubusercontent.com/12442026/30732577-d53cc4b4-9fa5-11e7-9803-72aaaa95156a.png)

**Comment by z-song** [comment]
不明白你的意思，不能按住ctrl多选几张图？？

**Comment by qiumzh** [comment]
我的意思是创建（新增）数据时多图上传功能不生效。

**Comment by qiumzh** [comment]
我搞明白了。☺ @z-song

**Comment by z-song** [comment]
http://laravel-admin.org/demo/multiple-images  创建功能不正常吗？
