### ISSUE TITLE
一个神奇的问题，请求大神

### ISSUE THREAD

**Issue by lxy1151** [z-song/laravel-admin#1233]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#
        $model = new LivingActive();
        $form = new \Encore\Admin\Form($model,function(Form $form){});
        $form->input('stream_id','tttttttttttttttt');
        var_dump($form->stream_id);//输出是有值的，值为tttttttttttttttt
        $rst = empty($form->stream_id);
        var_dump($rst);
**为啥$rst会返回true？？？**

**Comment by z-song** [comment]
`$form`对象里面并没有属性`stream_id `, `$form->stream_id`是通过`$form`的`__get`方法取到的

**Comment by lxy1151** [comment]
帅哥，上面我描述的很清楚了，是有输出结果的，值就在上面；$form->input('stream_id','tttttttttttttttt');已经设置了值了。

**Comment by z-song** [comment]
我也说的很清楚了 ,`$form->stream_id`是通过`__get`方法取到的

```php
<?php

class Foo
{
	public function __get($_)
	{
		return "hello";
	}
}

$foo = new Foo();

//  有值
var_dump($foo->bar);

// true
var_dump(empty($foo->bar));
```

**Comment by lxy1151** [comment]
有值不是应该返回false吗？为啥返回true。模型类中也是魔术方法获取字段值，如果有值就会返回false

**Comment by z-song** [comment]
这里找到了答案 http://php.net/manual/zh/function.empty.php#93117

```php
class Foo
{
    public function __get($_)
    {
        return "hello";
    }

    public function __isset($_)
    {
        // return false;
        return true;
    }
}

$foo = new Foo();

//  有值
var_dump($foo->bar);

// 这里会根据类的__isset()方法的返回值判断
var_dump(empty($foo->bar));
```

**Comment by lxy1151** [comment]
明白了，谢谢！
