### ISSUE TITLE
删除按钮如何添加回调？

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1234]
- Laravel Version: 5.4
- PHP Version:5.6
- Laravel-admin: 1.4.3

### Description:
两个表不是用外键链接的，但是子表有主表的id， 删除主表数据的时候我想删除子表数据。 这个如何实现呢？

### Steps To Reproduce:
目前好像只能删除数据模型对应的表的数据

**Comment by z-song** [comment]
在模型的删除事件回调里面实现这个吧
