### ISSUE TITLE
一对一关系  子表字段值页面上更新但是数据库没有更新

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1235]
- Laravel Version: 5.4
- PHP Version: 5.6
- Laravel-admin: 1.4.3

### Description:
editable() 可以调用， 值在页面上也会更新， 但是数据没有更新到数据库

```php
public function userMoney()
{
    return $this->hasOne('App\Models\UserMoney');
}
```
已经定义了， 页面上grid页显示了子表的字段值， 但是editable 不能更新值到数据库

### Steps To Reproduce:
定义一对一的关系， 在grid中添加editable方法

**Comment by z-song** [comment]
form里面有定义这个字段的field么 ？

**Comment by kelvenchi** [comment]
```php
$form->text('userMoney.money', '资金');
```

这样定义的

**Comment by z-song** [comment]
在1.4的版本里面有关系名称驼峰命名的问题，解决办法是用小写方法名,  把你的`userMoney`换成`usermoney`
