### ISSUE TITLE
图片删除功能不存在

### ISSUE THREAD

**Issue by PickApig** [z-song/laravel-admin#1236]
- Laravel Version: 5.5.12
- PHP Version: 7.1.9
- Laravel-admin: 1.5

### Description:

![qq 20170923170857](https://user-images.githubusercontent.com/10396827/30771808-28e4e498-a082-11e7-86ec-323a2b39ddd9.png)

请问如何放出删除和编辑图片的功能？

**Comment by tobeychen** [comment]
要加removable()
例如：
      $form->multipleImage('x', 'x')->removable();

**Comment by PickApig** [comment]
@tobeychen 原来如此，刚才加错地方了，非常感谢~

**Comment by Breadem** [comment]
@PickApig   我加了还是没有删除按钮
