### ISSUE TITLE
报告老大，访问器不支持下划线的字段！

### ISSUE THREAD

**Issue by yangzhipeng** [z-song/laravel-admin#1237]
报告老大，发现一个Bug
之前的还可以，更新了就不可以了。
 ErrorException In /home/halo/working/meals/vendor/encore/laravel-admin/src/Form/Field/MultipleFile.php line 167 : 
array_map(): Argument #2 should be an array (View: /home/halo/working/meals/resources/views/admin/form.blade.php)

**Comment by z-song** [comment]
你先暂时回退一下版本吧

**Comment by z-song** [comment]
先更新到`1.5.x-dev`
