### ISSUE TITLE
建议增加<meta name="csrf-token" content="{{ csrf_token() }}" />在模版头部

### ISSUE THREAD

**Issue by Share-Man** [z-song/laravel-admin#1238]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.*

### Description:
增加拓展插件 带有图片文件上传的时候 的时候会用得上，以前我是手动添加，但每次更新之后就得重新添加。

**Comment by z-song** [comment]
在js里面拿到token可以直接用`LA.token`
