### ISSUE TITLE
能否直接编辑图片路径？

### ISSUE THREAD

**Issue by PickApig** [z-song/laravel-admin#1240]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

![image](https://user-images.githubusercontent.com/10396827/30779233-b0b7a0ae-a11d-11e7-98be-959b1182a1de.png)
能否直接在预览框中，不上传图片，直接输入图片路径

**Comment by PickApig** [comment]
应该是设置fileinput属性的问题

**Comment by z-song** [comment]
没有这种操作

**Comment by PickApig** [comment]
@z-song 然而有这种需求- -。
比如有10个地方需要传banner图片，如果最后五张都是一样的
最后四张能否不上传，只输入文件名保存路径就行？
或者有没有什么好的其他替代方案，解决这个问题？
一是不需要上传那么多图片到服务器，二是不用每次都进行上传操作，直接输入图片名称（即路径）

**Comment by PickApig** [comment]
@z-song http://plugins.krajee.com/file-plugin-methods-demo#manipulation-methods 就类似这个操作的。

**Comment by z-song** [comment]
在原来的上传组件上面实现不太容易，我尝试了一个折中的办法，假设的图片字段名是`image`

form中
```php
 $form->image('image', '上传图片');

$form->text('image_url', '或者直接输入图片url')->default(function ($form) {
    return $form->model()->image;
});

$form->ignore('image_url');
```

在模型中加上：
```php
    public static function boot()
    {
        parent::boot();

        $callback =  function (Model $model) {
            if ($model->image == $model->getOriginal('image') &&
                $url = request('image_url'))
            {
                $model->image = $url;
            }
        };

        static::creating($callback);
        static::saving($callback);
    }
```

这样可以选择上传图片  也能在下面的text直接输入图片url

**Comment by PickApig** [comment]
@z-song 非常感谢！很好的解决了我的问题
