### ISSUE TITLE
关于验证类不提示错误，只是刷新页面的问题

### ISSUE THREAD

**Issue by gystone** [z-song/laravel-admin#1241]
- Laravel Version: 5.5
- PHP Version7.1
- Laravel-admin: 1.5

### Description:
表单一提交，已经设置了rule，什么也不填写 提交，应该提示错误，但是目前只是刷新了当前页面，并没有显示错误提示

### Steps To Reproduce:

经过回顾之前修改的东西，发现我在用session的时候在kernel.php里加入了
![image](https://user-images.githubusercontent.com/13912882/30779861-56b036d6-a12f-11e7-87bf-0b23906c5c8d.png)
然后所有的表单就都不提示错误了，把这两行去掉 就会显示，问一下大佬，这个我应该怎么解决，session 我也是需要的

**Comment by z-song** [comment]
没有能重现你的问题，我的laravel也打开了这两个中间件

**Comment by gystone** [comment]
@z-song 弄的我也没办法了，直接用cookie了放弃这两个中间件了

**Comment by z-song** [comment]
- Laravel Version: 5.5
- PHP Version7.1
- Laravel-admin: 1.5

上面的小版本也提供一下，方便重现问题

**Comment by gystone** [comment]
@z-song laravel-admin 我看 是1.5.x-dev，php是7.1.8，laravel 是5.5.1

**Comment by z-song** [comment]
你更新一下laravel吧， 我看最新的版本里面那两个中间件都是默认打开的

**Comment by gystone** [comment]
@z-song 好的

**Comment by sunxiyuan** [comment]
我页遇到了这个问题，一筹莫展中。。。
