### ISSUE TITLE
通过点击管理员头像进入管理员设置表单， 删除默认头像报404错误

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1242]
- Laravel Version: 5.4
- PHP Version:5.6
- Laravel-admin: 1.4.3

### Description:
通过点击管理员头像进入管理员设置表单， 删除默认头像报404错误。 另外点击“列表”按钮也会报错

### Steps To Reproduce:
点击右上角管理员图标进入设置页面， 点击页面上的删除按钮。

**Comment by z-song** [comment]
修复了，更新到`v1.4.4`

去掉了头像的删除按钮，在别的页面，如果你的图片上传需要有删除功能：
```php
$form->file('docs')->removable();
```
