### ISSUE TITLE
能否以model-form-tab的形式，每个tab都是一个单独的表单，可以单独提交？

### ISSUE THREAD

**Issue by taurusu28** [z-song/laravel-admin#1245]
- Laravel Version: 5.5.4
- PHP Version:
- Laravel-admin: 1.5

### Description:
刚接触不久，想看看能否把原后台管理系统移植过来。原系统的界面是这样：在编辑一个用户信息的时候，也是类似model-form-tab的标签形式，但是每个tab都是一个独立的提交表单，不知道在Laravel-admin如何实现？

**Comment by gzanthony** [comment]
我觉得你还不如自定义一个 view 模板用好些。
Form 可以用 $form->setView('admin.form.novel_form'); 指定自己的模板

**Comment by taurusu28** [comment]
对对，刚用这个思维有点固化了，总想着用这个实现所有功能，我去试试，感谢！

**Comment by z-song** [comment]
其实用`Encore\Admin\Widgets\Tab`可以实现这个：
```php
$tab = new \Encore\Admin\Widgets\Tab;

$tab->add('tab1', $this->form1());
$tab->add('tab2', $this->form2());
$tab->add('tab3', $this->form3());

$content->body($tab);

```

**Comment by taurusu28** [comment]
嗯，我都试试

**Comment by uu6744** [comment]
请问 form1表单里面具体内容应该怎么写

**Comment by uu6744** [comment]
BadMethodCallException In Controller.php line 68 :

Method [form] does not exist on [App\Admin\Controllers\BannerController].

这是我出现的错误

**Comment by Baiyongjian** [comment]
> 用其实`Encore\Admin\Widgets\Tab`可以实现这个：
> 
> ```
> $ tab  =  new  \ Encore \ Admin \ Widgets \ Tab ;
> 
> $ tab - > add（' tab1 '，$ this - > form1（））; 
> $ tab - > add（' tab2 '，$ this - > form2（））; 
> $ tab - > add（' tab3 '，$ this - > form3（））;
> 
> $ content - > body（$ tab）;
> ```
通过这种方式，您可以单独提交每个表单的数据，但是如何更改它呢？
