### ISSUE TITLE
[REQUEST] Can we support add image on select2 form 

### ISSUE THREAD

**Issue by t-perm** [z-song/laravel-admin#1247]
Can you support add an image on select option like that?
[![https://gyazo.com/76083baf0dfb8618610b49bcaef2ddea](https://i.gyazo.com/76083baf0dfb8618610b49bcaef2ddea.png)](https://gyazo.com/76083baf0dfb8618610b49bcaef2ddea)

I have changed by extent select field **but not working on pjax** :(. Just show image only
[![https://gyazo.com/c7c71d465d4d9c599b1bfe24f81b8534](https://i.gyazo.com/c7c71d465d4d9c599b1bfe24f81b8534.png)](https://gyazo.com/c7c71d465d4d9c599b1bfe24f81b8534)
```
use Encore\Admin\Form\Field\Select;

$("{$this->getElementClassSelector()}").select2({
    // allowClear: true,
    templateResult: formatData,
    templateSelection: formatData,
    placeholder: "{$this->label}"
});
function formatData (data) {
  var string = data.text.split('||||');
  return $('<img width="50px" src="/upload/' + string[0]  + '" /><span>' + string[1] + '</span>');
};
```

**Comment by z-song** [comment]
This can be support, wait for next version

**Comment by taimaiduc** [comment]
@z-song Thank you

**Comment by taimaiduc** [comment]
@z-song can you create new laravel-admin-extensions for this ?
