### ISSUE TITLE
需求！可以增加类似创建按钮那样的自定义的按钮么？

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1249]
- Laravel Version: 5.4
- PHP Version:5.6
- Laravel-admin: 1.4.3

### Description:
现有的方式可能是自定义一个工具去解决这个问题， 但是现在我想要的只是一个可以跳转的按钮。点击这个按钮跳转到我想要去的链接（链接可以在路由里面定义）。

### Steps To Reproduce:
None

**Comment by z-song** [comment]
看文档http://laravel-admin.org/docs/#/zh/model-grid-custom-tools

**Comment by aen516954023** [comment]
具体如何解决的
