### ISSUE TITLE
多图上传rules('required') 方法无效

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1250]
- Laravel Version: 5.4
- PHP Version:5.6
- Laravel-admin: 1.4.3
### Description:
多图上传， ->rules('required') 方法无效， 并没有验证是否选择至少一张图片。

### Steps To Reproduce:

```php
$form->mulitiImages('field')->rules('required');
```

**Comment by z-song** [comment]
已修复，更新到`1.5.x-dev`或者等下一个小版本发布
