### ISSUE TITLE
如果字段名称为content的情况下，表单的class中含有content,以至可能让表单变形，建议对表单的class进行前缀处理

### ISSUE THREAD

**Issue by sherry24love** [z-song/laravel-admin#1255]
- Laravel Version: 5.5.13
- PHP Version:7.0
- Laravel-admin: 1.5.*

### Description:
如果字段名称为content的情况下，表单的class中含有content,以至可能让表单变形，建议对表单的class进行前缀处理

**Comment by xs47968224** [comment]
可以自定义样式：
$form->textarea('content', 'Content')->setElementClass('my_content')；
如果要添加样式：
$form->textarea('content', 'Content')->addElementClass('other_content')；
