### ISSUE TITLE
关于大型Excel的数据导出问题

### ISSUE THREAD

**Issue by CoderPoet** [z-song/laravel-admin#1257]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5 dev

### Description: 关于超过五万条的Excel文件的导出问题

情景：自定义导出类的时候，需要获取grid的data，例如$this->getData()，这个方法对于小型数据是OK的，但是在大型数据的情景下，内存消耗很大。

求助：请问是不是可以使用游标或者yield的方式来获取数据写入Excel，而非一次性获取大量的数据到内存中？

另外，withScope()是否可以获取指定页码的数据?我看参数接收到了page只会把usePaginate设为TRUE，而没有去获取指定页码的数据，不知道这个是不是有别的方式解决？如果能够获取指定页码的数据，其实也能够实现我上面说的 通过yield生成器的方式来节省内存。

或者说对于这种导出大型Excel的需求，已经有更好的解决方案啦？

**Comment by z-song** [comment]
这里确实要优化   你是按照http://laravel-admin.org/docs/#/zh/model-grid-export 这里的自定义导出吗？

**Comment by CoderPoet** [comment]
@z-song 
嗯，起初我是用的你说的这个（laravel-excel）
但是那个消耗资源也太大了，于是只好放弃，使用了原生的fputcsv，刷新Buffer的方式实现导出，效率高了不少。

现在主要的问题就是从grid拉取数据的资源消耗有点大，如果能够实现读一条数据 写一条数据，然后定行刷新buffer ，相信大型Excel的导出应该不是什么问题了。
目前框架还未实现之前，我暂时提高内存的限制，还是能够导出的，十万条数据的量大概耗时51.79S，其中取grid数据耗时47.22S
![image](https://user-images.githubusercontent.com/19374680/30853168-94ea2bd4-a2e0-11e7-8811-a5e8dea46f9f.png)
![image](https://user-images.githubusercontent.com/19374680/30853180-9d46d228-a2e0-11e7-8a95-39d5a69951bf.png)

**Comment by CoderPoet** [comment]
我感觉快速解决方案就是提供一个方法： 能够获取指定页码的数据

**Comment by z-song** [comment]
现在不是可以选择导出当前页吗

**Comment by elinxer** [comment]
选择导出当前应该很多时候是不符合需求的，大数据导出还是建议csv格式，配合回调+异步接口获取数据，可以实现与下载相同的功能。

**Comment by z-song** [comment]
@CoderPoet @elinxer 提交了优化 5902ca5551334fb86a3d4c13bf08ca230836dff1

使用了模型的chunk方法和stream response来避免内存问题，你们可以试试看

**Comment by CoderPoet** [comment]
@z-song 嗯 我使用laravel原生的Eloquent的游标 配合 fputcsv直接输出csv的方式，读取一条数据就输出一条，解决了内存的问题，目前导出十万条的内存消耗可以稳定在10MB左右，响应速度大概稳定在2-3S。

不过还是建议框架方面可以优化getData()，可以提供个一个每次只从grid获取一条数据的方法，避免大数据直接写入内存带来的消耗与时耗。

**Comment by CoderPoet** [comment]
@elinxer 嗯 对于百万级别的数据量的话 异步也是很有必要的

**Comment by never615** [comment]
@CoderPoet  你弄个一千万数据测试一下,使用Eloquent的游标内存占用稳定吗?
我测试是每次chunk都会增加一点没有释放的内存,数据量大的时候还是有问题.
这是我之前测试的:http://www.jianshu.com/p/fe52b287ef05
使用DB的写法内存就不会存在未释放....
[laravel 5.4]

**Comment by lePig** [comment]
@langeuh 请教下这个PR要如何来使用？
