### ISSUE TITLE
1.5.5 版本的 form switch 组件问题

### ISSUE THREAD

**Issue by jxlwqq** [z-song/laravel-admin#1258]
- Laravel Version: 5.5.13
- PHP Version:7.1.7
- Laravel-admin: 1.5.5

### Description:
1.5.5 版本的 form switch 组件对enum('0', '1')类型的字段不支持。
1.5.3 版本无此问题，升级后报上述错误。

### Steps To Reproduce:
无。

**Comment by z-song** [comment]
没修改过switch相关代码逻辑，猜测是laravel的更新导致的问题

修改为value用字符串
```php
$form->switch('released')->states([
        'on'  => ['value' => '1'],
        'off' => ['value' => '0'],
    ]);
```

**Comment by huyouheng** [comment]
我的也是获取到on或off，版本是1.5的
`$form->switch('isAddPer','是否加入到权限')->states([
					'on'  => ['value' => '1'],
					'off' => ['value' => '0'],
				]);`
`info(\request('isAddPer'));`

[2018-03-28 14:20:42] local.INFO: on 

请问是怎么回事呢？
