### ISSUE TITLE
Question: How can I disable Admin-Authentification

### ISSUE THREAD

**Issue by AntoninSlejska** [z-song/laravel-admin#1259]
My application runs in an private network and all users are authentificated with Gitlab-Authentification.

I would like to use the existing authentification also for Admin. Is it possible?

**Comment by z-song** [comment]
Yes, it's possible.

First you need to define a user provider according to [adding-custom-user-providers](https://laravel.com/docs/5.5/authentication#adding-custom-user-providers),  then change the auth config:

```php
// config/admin.php

    'auth' => [
        'guards' => [
            'admin' => [
                'driver' => 'session',
                'provider' => 'admin',
            ]
        ],

        'providers' => [
            'admin' => [
                'driver' => 'custom', // specify the custom provider you defined
            ]
        ],
    ],

```

**Comment by z-song** [comment]
Added a document [custom-authentication](http://laravel-admin.org/docs/#/en/custom-authentication)
