### ISSUE TITLE
export功能中文乱码

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#126]
![image](https://cloud.githubusercontent.com/assets/7192860/20584576/e7808256-b22e-11e6-88f1-30ad19af7fef.png)
![image](https://cloud.githubusercontent.com/assets/7192860/20584579/f3197b7c-b22e-11e6-9a44-d1197bca8da3.png)
点击 export导出的文件中中文乱码

**Comment by z-song** [comment]
@xyz8772232 导出utf-8编码输出的csv文件，你需要修改excel的阅读编码

**Comment by xyz8772232** [comment]
好的，多谢，项目越来越强大，👍👍👍
