### ISSUE TITLE
直接在表格中进行数据更改或单选操作，如何触发保存回调？

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#1261]
测试直接在表格中进行数据更改或单选操作时发现保存回调没有生效

**Comment by z-song** [comment]
没重现你的问题，我这边saving和saved回调都触发了

注意表格中修改的字段，在form中也要有相应的field

**Comment by windpursuer** [comment]
请问switch有尝试否？我这边没法触发，clone了最新版本

**Comment by z-song** [comment]
就是测试的switch，你在回调里面打个断点看看

**Comment by windpursuer** [comment]
不好意思，是我搞错了。。能触发，我的问题是获取不到表单数据id，所以下一步没有执行。那么问题应该是保存回调里在表格中操作数据时，保存回调时如何获取表单数据对应的id？（在编辑页面是可以用$form->id获取的，但在表格中操作的话就不清楚怎么获取了,文档貌似没有提到）

**Comment by z-song** [comment]
用`$form->id`获取不到吗？那用`$form->model()->id`试试看

**Comment by windpursuer** [comment]
完美解决！实测$form->model()->id可用，感谢大大的耐心解答~

**Comment by fan153693** [comment]
能触发保存回调但是报错信息为什么不能弹出，，不管更新是否成功都提示更新成功
