### ISSUE TITLE
请问前台使用默认的User表，如何使用admin的权限规则？

### ISSUE THREAD

**Issue by kenfu** [z-song/laravel-admin#1269]
使用的都是最新版。

laravel admin 后台有权限和自己的user表。

请问laravel默认的user表能使用admin的权限管理吗，就是前台是否可以使用后台的权限管理？

**Comment by z-song** [comment]
最好不要使用admin的权限管理的吧   不然会产生混乱，如果有需求的话建议参考后台的权限系统再实现一个

**Comment by kenfu** [comment]
多谢！
