### ISSUE TITLE
Role / Permission Question

### ISSUE THREAD

**Issue by vlavius** [z-song/laravel-admin#1271]
- Laravel Version: 5.5.13
- PHP Version: 7.1.9
- Laravel-admin: 1.5.5

### Description:
Can i use the Role/Permission System for the Frontend of the Application or must implement a other?

Because you can only create / admin / routes under permissions.

**Comment by igor-chepurnoi** [comment]
I have the same question

**Comment by z-song** [comment]
The builtin permission module is just designed for the admin,  I suggest you use other permission packages for front-end such as entrust
