### ISSUE TITLE
Permission without route

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1272]
I can you add permission without route URL.
Some case user can go that URL but cannot do some action or cannot load some fields like the previous version Laravel Amin. 
Thank you.

**Comment by z-song** [comment]
For example, add a permission with slug `delete-image`，and assign it to some roles, then in your grid:
```php
$grid->actions(function ($actions) {
    if (!Admin::user()->can('delete-image')) {
        $actions->disableDelete();
    }
});
``` 
The roles with this permission will not able to see the delete button in actions column.

**Comment by z-song** [comment]
You need to modify the table `admin_permissions` to allow column `http_path` nullable:
```shell
alter table `admin_permissions` modify `http_path` text COLLATE utf8mb4_unicode_ci;
```
