### ISSUE TITLE
本地可以删除图片，服务器上不显示删除图标

### ISSUE THREAD

**Issue by cong5** [z-song/laravel-admin#1274]
在本地的时候是显示删除图标的：
![0](https://user-images.githubusercontent.com/5463514/30958506-01399784-a403-11e7-922d-50fc6efe5c8a.png)
但是在服务器上就不显示了
![1](https://user-images.githubusercontent.com/5463514/30958507-0184fc1a-a403-11e7-8149-73a9f7f11dc6.png)
请问这个是什么问题。

**Comment by cong5** [comment]
找到原因了，是`->removable();`的问题。

**Comment by Breadem** [comment]
请问具体怎么解决的？
我的出不来删除按钮，就像你的第二张图片

**Comment by cong5** [comment]
好像是这两点：
1、给生成表单的字段添加`->removable();` 标识允许删除
2、数据库里面的字段不能是`not null`
