### ISSUE TITLE
hasMany with 'required' image input can't be edited

### ISSUE THREAD

**Issue by mathcale** [z-song/laravel-admin#1276]
@z-song

- Laravel Version: 5.5.0
- PHP Version: 7.1.9
- Laravel-admin: 1.5.5

### Description:
I have a form which haves an image input with the 'required' rule (`$form->image('image')->rules('required')`) inside a `$form->hasMany('my_relation', ...)`. Creating a new record works fine, but when I try to edit a record the validation message "The my_relation.2.image field is required" shows up. It only works if I send the image again.

Also tried the `editable()` method on the input with the rule but got the validation error anyway.

**Comment by beniaminorossini** [comment]
up!
Any news about that?

**Comment by kratosvn** [comment]
@z-song do you have a solution for this problem?
thank you.

**Comment by kratosvn** [comment]
@z-song do you have a solution to this problem?
thank you.

**Comment by mendizalea** [comment]
Hi, I have the same problem. If I try to edit a record but I do not want to modify the photo it tells me that it is obligatory to select a photo
