### ISSUE TITLE
http://120.26.143.106/admin down forever?

### ISSUE THREAD

**Issue by vlavius** [z-song/laravel-admin#1277]
Hi,
 is this page down forever? 
It was for me the bedder demo page, with code expamples. 

Best regards.

**Comment by mathcale** [comment]
@vlavius The new Demo link is this one: http://laravel-admin.org/demo

**Comment by vlavius** [comment]
Yes, but without code tabs by the examples.

**Comment by z-song** [comment]
I'll release the demo repo lately

**Comment by vlavius** [comment]
Thank you.

**Comment by Astraeux** [comment]
希望尽早放出demo的下载，谢谢 @z-song

**Comment by z-song** [comment]
@vlavius @Astraeux @mathcale https://github.com/z-song/laravel-admin.org
