### ISSUE TITLE
请问下。pjax 如何单个DOM禁用呢？

### ISSUE THREAD

**Issue by 11373450** [z-song/laravel-admin#1278]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

**Comment by z-song** [comment]
为何要禁用

**Comment by 11373450** [comment]
我有个路由会有多层跳转，加判断，但是return 出来的时候，我不希望用pjax来接收跳转。
然后在admin里面 a标签有了pjax 就把return 出来的结果当html内容显示了。

我的是logout 先退出操作。然后操作成功后会跳转到index 。
但是在index页面的时候会判断未登录状态是否可以进index，判断的时候，还判断是否ajax来访问的。
ajax访问又要return msg 出去，
a 标签点击的时候 ，herf 就成了pjax 就直接当AJAX来判断，把msg当HTML显示在了pjax容器里面了。

我就想说把这个A标签不使用pjax去跳转就行了。

**Comment by z-song** [comment]
`public/vendor/laravel-admin/laravel-admin/laravel-admin.js` 这个文件的17行是用来给页面链接设置pjax请求，你修改一下这个文件的选择器就好了

比如修改为
```js
$(document).pjax('a:not(a[target="_blank"],a[no-pjax])', {
    container: '#pjax-container'
});
```
然后所有带有`no-pjax`属性的a链接都不会用pjax加载
```php
<a href='xxx' no-pjax>链接</a>
```

**Comment by 11373450** [comment]
OK。谢谢
