### ISSUE TITLE
grid搜索中 自定义sql 如果做时间范围的搜索

### ISSUE THREAD

**Issue by kriestian** [z-song/laravel-admin#128]
1：自定义 
```php              
 $filter->where(function ($query){
    $input = $this->input;
    dd($input);

    $query->whereHas('order', function ($query) use ($input) {
        $query->where('shipingdate', "$input");
    });
}, '制单日期')->dateTime();
```
这样是可以显示一个日期控件，但是如何做出范围？between()->dateTime();无效

**Comment by z-song** [comment]
目前还不支持这种类型的filter，以后考虑加上这个类型的filter

**Comment by kriestian** [comment]
非常感谢这个框架和作者，现在在用这个框架做信息化系统，业务上有这样的需求，请教下有什么零时的方案处理吗？谢谢

**Comment by z-song** [comment]
可以把需求稍微描述详细一点吗？

**Comment by kriestian** [comment]
好的，有个Task Model对应 Task表 关联了  Order 表  
现在在需要在 TaskController 的 Grid的 Filter里 添加一个搜索 order 表的 创建时间 范围。
这样描述能明白吗？

**Comment by kriestian** [comment]
然后我看到您在回复中有写到 多对多关联使用的是$filter->where(function ($query)  但是 这个只能接收一个参数的传递吗？有什么办法可以接收两个或者多个input的参数

**Comment by z-song** [comment]
两个模型是多对多关联？

**Comment by kriestian** [comment]
是一对多关系  Order对应多个Task

**Comment by z-song** [comment]
@kriestian 现在已经可以支持了

```php
$grid->filter(function ($filter) {
    $filter->between('order.created_at')->datetime();
});
```
`order`是关联方法

**Comment by kriestian** [comment]
好的，谢谢
