### ISSUE TITLE
数据表单中如何实现左右两列布局？

### ISSUE THREAD

**Issue by kenfu** [z-song/laravel-admin#1280]
目前laravel、laravel admin都是最新版本。

### Description:
文档中指引参考HomeController.php来布局，这是一个很好的方法。请问版主，在编辑数据的时候，也就是数据表单中$content->body($this->form()->edit($id)); 内部是如何实现布局呢，就像wordpress的文章发布页面一样。
多谢版主提点。

**Comment by z-song** [comment]
暂未实现

**Comment by tianxionglu** [comment]
希望这个功能能尽快上线啊，因为不是所有表单都需要占一整行的

**Comment by z-song** [comment]
@tianxionglu @kenfu 参考一下这里的布局吧 https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Controllers/PostController.php#L155-L188
