### ISSUE TITLE
[Need help ] Custom form

### ISSUE THREAD

**Issue by abdou1236** [z-song/laravel-admin#1286]
- Laravel Version: 5.4.*
- PHP Version: >=5.6.4
- Laravel-admin: 1.4.#

### Description:
Hi,
I want to create multiple random codes on one sumbit click so i changed the view of the form like this : 
![create](https://user-images.githubusercontent.com/8183194/31202554-5f7ad5a0-a963-11e7-83c3-06706d79fa81.png)
for example when i choose a number value equal to 5 i will use  $form->saving() to get this value before saving and  generate 5 random codes to store in the DB and it works perfectly.

![crebtn](https://user-images.githubusercontent.com/8183194/31203012-6ceccaca-a965-11e7-8b17-6a6c4de74abd.png)

![formedit](https://user-images.githubusercontent.com/8183194/31203043-8a0de846-a965-11e7-9873-9c968de3eefd.png)

![edit](https://user-images.githubusercontent.com/8183194/31203039-85b471e8-a965-11e7-9551-a40cba0ee160.png)

The problem is when i want to edit a row the the function formEditRow keep pointing to $form->saving of form() function and fail ! 
please can you help me with this ?

**Comment by z-song** [comment]
Do you see the `use ModelForm` statement in your controller, you need to override the  update method in your controller like this:

```php
    public function update($id)
    {
        return $this-> formEditRow()->update($id);
    }
```

**Comment by abdou1236** [comment]
Thank you sir for your clear response ,it worked like a charm :+1:
