### ISSUE TITLE
请问左侧的菜单如何 默认就不收缩起来.

### ISSUE THREAD

**Issue by wl496928838** [z-song/laravel-admin#1292]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:

请问左侧的菜单如何 默认就不收缩起来.

**Comment by tobeychen** [comment]
vendor/encore/laravel-admin/config/admin.php

把'layout'  => ['sidebar-collapse'],

改成'layout'  => ['sidebar-mini'],
