### ISSUE TITLE
get ID after save

### ISSUE THREAD

**Issue by myzpolice** [z-song/laravel-admin#1299]
- Laravel Version: 5.5
- PHP Version: 7
- Laravel-admin: 1.5

### Description:

I want to return ID after save, i usually using 
`
$user->save();
$insertedId = $user->id();
`
How can i achieve that in laravel admin?

**Comment by z-song** [comment]
```php
$form->saved(function (Form $form) {

    $form->model()->id;

});
```

**Comment by myzpolice** [comment]
thanks mate, work like a charm.
