### ISSUE TITLE
关于过滤查询的时候关联条件的疑惑

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#130]
![Uploading image.png…]()
看源码，看到这里，有点疑惑
    $grid->country()
用grid关联其他表，
    $this->queries
集合里面我dd()出来的都是数组，可是这个是判断后面的一个匿名函数是否在集合中。
后面的匿名函数是在什么时候加入到query里面的呢？
Grid/Model.php 230-233

**Comment by xyz8772232** [comment]
![image](https://cloud.githubusercontent.com/assets/7192860/20595479/fc645b52-b274-11e6-96aa-490213f2e6b6.png)

**Comment by xyz8772232** [comment]
感觉是多写了 $key?

**Comment by z-song** [comment]
你没理解contains方法的用法，举个例子
```php
$collection = collect([1, 2, 3, 4, 5, 6, 7]);

if ($collection->contains(function ($key, $value) {
    return $value > 5;
})) {
    echo '集合里有大于5的数字';
}
```

**Comment by xyz8772232** [comment]
好的
