### ISSUE TITLE
表单控件 textarea  当为空值时，无法保存！必须有值才能保存

### ISSUE THREAD

**Issue by 1027836596** [z-song/laravel-admin#1304]
- Laravel Version: 5.5.#
- PHP Version:7.1.6
- Laravel-admin: 1.5.#

### Description:
表单控件 textarea  当为空值时，无法保存！必须有值才能保存

**Comment by 1027836596** [comment]
Text 控件也是一样，将有内容清空时，发现数据库无法更新， 在调试 $model->attributes 发现Text 控件传过来的数据没变化，是原来的。

**Comment by z-song** [comment]
没有重现你的问题，数据库字段需要设置为允许null

**Comment by 1027836596** [comment]
但是我数据库字段已经是设置Null；现在的问题是提交表单时 在模型 saving 方法里打印出来的内容没有改变。按正常来说我清空组件后，提交过去的字段在未进数据库应该为空的；很奇怪，如果将内容改变是可以正常的。

**Comment by z-song** [comment]
不太清楚你的问题，将laravel-admin更新一下看看

**Comment by Witype** [comment]
- Laravel Version: 5.4.36.#
- PHP Version:7.1.6
- Laravel-admin: 1.4.#
也遇到同样的问题，

sql
~~~
#2017-10-25
CREATE TABLE `admin_boxs_menu`(
  `id` INT(10) UNSIGNED AUTO_INCREMENT,
  `title` VARCHAR(32) NOT NULL COMMENT '标题',
  `type` VARCHAR(32) NOT NULL COMMENT '菜单类型',
  `level` TINYINT DEFAULT 0 COMMENT '排序',
  `path` VARCHAR(128) DEFAULT NULL COMMENT '访问路径',
  `full` VARCHAR(128) DEFAULT NULL  COMMENT '全部路径',
  `params` VARCHAR(128) DEFAULT NULL  COMMENT '访问参数',
  `createAt` TIMESTAMP COMMENT '创建时间',
  `updateAt` TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (id)
)ENGINE = InnoDB DEFAULT CHARSET = utf8;
~~~

只要是空值就不会保存，但是我用phpmyadmin和phpstorm都可以设置空值，谢谢

**Comment by 1027836596** [comment]
不是数据表是否空值问题，主要是提交表单后，在 模型 static::saved()  保存方法中打印不到提交过来的字段。因为空值所以字段好像自动被去掉了。我这边现在采用方法是：在模型saving()方法 用\Request::all() 通过这个来提取出值更新就可以保存了。

**Comment by z-song** [comment]
打开`app/Http/Kernel.php`， 注释掉`ConvertEmptyStringsToNull`这个middleware试试看

**Comment by Witype** [comment]
注释掉ConvertEmptyStringsToNull就可以了，谢谢

**Comment by 1027836596** [comment]
谢谢，问题已解决了。
