### ISSUE TITLE
我的表单发现多了一个form ，我暂时注释了FORM.模板 多余信息

### ISSUE THREAD

**Issue by 1027836596** [z-song/laravel-admin#1305]
- Laravel Version: 5.5.#
- PHP Version:7.1.6
- Laravel-admin: 1.5.#

### Description:
 
    <form action="/admin/ad" method="post" accept-charset="UTF-8" class="form-horizontal" pjax-container>
       
我暂时注释了FORM.模板 多余信息
 
    {!! $form->open(['class' => "form-horizontal"]) !!}

**Comment by z-song** [comment]
开发分支已经解决了这个问题了 谢谢
