### ISSUE TITLE
列表页怎么使用grid展示每行的缩略图

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#1309]
- Laravel Version: 5.4
- PHP Version:7.1
- Laravel-admin: 1.4

### Description:
列表页怎么使用grid展示每行的缩略图
![tim 20171012160026](https://user-images.githubusercontent.com/17559363/31485562-dc63309a-af66-11e7-8819-fd886367d568.png)

**Comment by king52311** [comment]
接口文档里有，下面是我的例子
`$grid->logo('LOGO')->image(config('admin.upload.host'), 100, 100);;`
