### ISSUE TITLE
Report Bug

### ISSUE THREAD

**Issue by thickas** [z-song/laravel-admin#131]
\vendor\encore\laravel-admin\views\filter\modal.blade.php
line2 : 
&nbsp;&nbsp;Filter    ==>   &nbsp;&nbsp; {{ trans('admin::lang.filter') }}

\vendor\encore\laravel-admin\views\grid\table.blade.php
line 11
&nbsp;&nbsp;Export   ==>   &nbsp;&nbsp;{{ trans('admin::lang.export') }}

**Comment by z-song** [comment]
@thickas thank you for report this!
