### ISSUE TITLE
Call to undefined method Illuminate\Database\Query\Builder::addEagerConstraints()

### ISSUE THREAD

**Issue by JoanVt** [z-song/laravel-admin#1312]
Laravel 5.5
Last laravel-admin version
php 7.1

Just this:
$qualities  = ProjectQualities::pluck('name','id')->toArray(); -> [ 1 => 'something', 2 => 'etc...]
$form->checkbox('qualities','Qualities')->options($qualities);

returns that error.

**Comment by JoanVt** [comment]
Soz, was caché I guess, It is working now :<

**Comment by jxlwqq** [comment]
@JoanVt how did you fix the error?

**Comment by JoanVt** [comment]
@jxlwqq Yes! 
I made badly one call to a model function and was cached for a while for some reason.
php artisan cache:clear was the solution.
