### ISSUE TITLE
如何在一个项目里面创建两个Admin，最佳实践是什么

### ISSUE THREAD

**Issue by kilimall** [z-song/laravel-admin#1320]
- Laravel Version: 5.5.0
- PHP Version: 7.0
- Laravel-admin: 5.5

### Description:
我们想在一个Laravel里面创建两个后台，一个是运营后台，一个是卖家后台，如何做是最佳实践。

当前我们的想法是：
运营后台使用 Composer laravel-admin
卖家后台使用常规路由，再装载 Admin.php，但问题是不支持类似 config/admin.php,  app/Admin/bootstrap.php等设置，同时还要重装 view 和 其它 class，几乎相当于把 encore/laravel-admin/src 的文件都要复制过来，等于没有使用 composer 了！

要如何做才能在一个项目下配置两个 Admin  @实例呢？@z-song

**Comment by z-song** [comment]
暂不支持，要不就开两个项目

**Comment by kilimall** [comment]
我们已经解决了，laravel-admin  很好用，谢谢你！

**Comment by zhaomengqiao** [comment]
有什么好方法？ @kilimall

**Comment by Astraeux** [comment]
@kilimall 请问怎么解决的？

**Comment by hellowords** [comment]
@kilimall 是开两个项目解决的吗？

**Comment by xiaozha87** [comment]
@kilimall 我现在也遇到这个问题，能不能分享下你的解决方法，多谢！

**Comment by terranc** [comment]
有人实现出来了吗？
