### ISSUE TITLE
一些类的方法声明了 void 的返回类型导致php7.0的兼容问题

### ISSUE THREAD

**Issue by RunnerLee** [z-song/laravel-admin#1321]
- Laravel Version: 5.5.0
- PHP Version:7.0.6
- Laravel-admin: 1.5.5

### Description:
`Encore\Admin\Grid\Filter\Presenter\DateTime`, `Encore\Admin\Grid\Filter\Presenter\Radio`, `Encore\Admin\Grid\Filter\Presenter\Checkbox` 这三个类中, 有部分方法声明了 `void` 的返回类型.

而 `void` 是从 php 7.1.0 开始才支持的, 这会导致在用到这几个 Presenter 的时候发生异常
![image](https://user-images.githubusercontent.com/7436388/31543196-aa958dc4-b047-11e7-84a6-b2afa13965eb.png)

### Steps To Reproduce:
```
            $grid->filter(function (Grid\Filter $filter) {
                $filter->gt('created_at')->datetime();
            });
```

### Suggestion:
1. 不兼容php7.0, 在依赖中声明需要 php 7.1.0
2. 兼容php7.0, 移除这几个方法的返回类型的声明

**Comment by z-song** [comment]
已经在dev版本里面修复了这个问题

**Comment by RunnerLee** [comment]
好的。感谢
