### ISSUE TITLE
route does not work it give wrong path..?

### ISSUE THREAD

**Issue by Lalitpatadiya12** [z-song/laravel-admin#1324]
- Laravel Version: 5.2.*
- PHP Version: 5.6
- Laravel-admin:

**Comment by dcezario** [comment]
By default, the route for login points to "/laravel-admin-install-dir/auth/login". So, if you not using a vhost (Apache Server), you'll get this error.

**/vendor/encore/laravel-admin/resources/views/login.blade.php:**

```
<form action="{{ admin_base_path('auth/login') }}" method="post">
```

To solve it, you can overwrite the login view and set your own path to action.

Reference:  #856

**Comment by tinonetic** [comment]
> 
> 
> By default, the route for login points to "/laravel-admin-install-dir/auth/login". So, if you not using a vhost (Apache Server), you'll get this error.
> 
> **/vendor/encore/laravel-admin/resources/views/login.blade.php:**
> 
> ```
> <form action="{{ admin_base_path('auth/login') }}" method="post">
> ```
> 
> To solve it, you can overwrite the login view and set your own path to action.
> 
> Reference: #856

Hi, 

I have the same situation.

Just to be clear, I edit the **login.blade.php** file in the path **vendor\encore\laravel-admin\resources\views** ?

When you say overwrite? Is that what you mean?

I tried to follow what is being said in #856 and I cannot get where I copy from and to where to achieve the overwrite.

Thanks in advance!
