### ISSUE TITLE
新建用户，登陆后无法注销，无法回到登录界面

### ISSUE THREAD

**Issue by lazybat** [z-song/laravel-admin#1326]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin:  1.5.x-dev 

### Description:
新建一个用户，user1，指定了一个新建的权限，登陆后，提示成功登陆。
这是选择右上角用户登出，无法登出。
直接访问/admin，还是提示成功登陆，没办法用admin登陆了。

**Comment by lazybat** [comment]
只能删除/storage/framework/sessions/ 目录下文件，才能正常登陆。
admin用户没有问题

**Comment by lazybat** [comment]
发现给个login的权限，就正常了，只是没给login权限，应该无法登陆才对。

**Comment by tiandaye** [comment]
要是无法登陆，就拿不到用户信息啊。

**Comment by Lexluth0r** [comment]
为什么没有给login的权限 用户也能进行登录呢

**Comment by ericliu000** [comment]
同问 admin也无法登出

**Comment by teslia** [comment]
@z-song  你好，我也遇到这个问题了，当管理员没有login权限的时候，也能login成功，是否能在AutuController中判断登录的地方加一个权限判断的代码呢？
