### ISSUE TITLE
Disk [admin] not configured, please add a disk config in `config/filesystems.php`.

### ISSUE THREAD

**Issue by pratik007kumar** [z-song/laravel-admin#1327]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: ^1.5

### Description:
Disk [admin] not configured, please add a disk config in `config/filesystems.php`.

**Comment by abdou1236** [comment]
Hi,
Open 'filesystems.php' file under config folder and add this to the disk array :
 ` 'admin'  => [
            'driver' => 'local',
            'root'   => storage_path('app'),
        ]`

**Comment by z-song** [comment]
see http://laravel-admin.org/docs/#/en/model-form-upload?id=upload-to-local

**Comment by pratik007kumar** [comment]
thanks it working now

**Comment by Davion-xiao** [comment]
or edit admin.php under config directory, change the disk in upload array.

**Comment by itanea** [comment]
For me it works with adding this in 'config/filesystems.php' :

`        'admin' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_URL').'/storage',
            'visibility' => 'public',
        ],`

Check also if your storage link is ok with artisan's command : 

`php artisan storage:link`

Hope it helps ;-)

**Comment by saber13812002** [comment]
on windows 2012 when laravel hosted on IIS 

i config all of above but after restart the website it doest applied 

i cant restart iis because all other websites stopped and i didnt want to restart them.

please help me

**Comment by SlaraMk** [comment]
hi ,I followed the steps but still have the same problem

**Comment by SlaraMk** [comment]
> see http://laravel-admin.org/docs/#/en/model-form-upload?id=upload-to-local

I have another issues can you help me please ?

**Comment by phantomsom** [comment]
I tried @abdouTurki's solution and @happytodev's solution, same result when editing database data on my Laravel admin

I also tried this solution, https://blog.csdn.net/guaiguaiknl/article/details/80332337, same error
 
<img width="657" alt="Screen Shot 2021-04-15 at 6 59 00 PM" src="https://user-images.githubusercontent.com/19833754/114858932-aafe5680-9e1c-11eb-9bd3-f8b9332fb006.png">

Laravel Version: 8.36.2
PHP Version:7.4.16
Laravel-admin: v1.8.11


Disk [admin] not configured, please add a disk config in config/filesystems.php.

**Comment by phantomsom** [comment]
Fixed, needed to call php artisan cache:clear and config:clear
