### ISSUE TITLE
怎么修改自带删除的删除链接？

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#1328]
- Laravel Version: 5.4
- PHP Version:7.1
- Laravel-admin: 1.4

### Description:

如下图，怎么修改这个删除按钮的删除链接，在不新增按钮的情况下
### Steps To Reproduce:
![_20171016175556](https://user-images.githubusercontent.com/17559363/31606332-60c72efe-b29b-11e7-9f80-f7bab4ce63c8.png)

**Comment by z-song** [comment]
http://laravel-admin.org/docs/#/zh/model-grid-actions?id=%e6%a8%a1%e5%9e%8b%e8%a1%a8%e6%a0%bc%e8%a1%8c%e6%93%8d%e4%bd%9c

去掉默认的删除链接，  在加一个自定义的
