### ISSUE TITLE
关于上传图片的问题

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#133]
[2016-11-25 15:29:23] local.ERROR: exception 'League\Flysystem\FileNotFoundException' with message 'File not found at path: ' in E:\www\git\laravel-admin\vendor\league\flysystem\src\Filesystem.php:385
Stack trace:
#0 E:\www\git\laravel-admin\vendor\league\flysystem\src\Filesystem.php(234): League\Flysystem\Filesystem->assertPresent('')
#1 E:\www\git\laravel-admin\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php(155): League\Flysystem\Filesystem->delete('')
#2 E:\www\git\laravel-admin\vendor\encore\laravel-admin\src\Form\Field\File.php(179): Illuminate\Filesystem\FilesystemAdapter->delete('')
#3 E:\www\git\laravel-admin\vendor\encore\laravel-admin\src\Form\Field\File.php(89): Encore\Admin\Form\Field\File->destroy()
#4 E:\www\git\laravel-admin\vendor\encore\laravel-admin\src\Form\Field\Image.php(33): Encore\Admin\Form\Field\File->uploadAndDeleteOriginal(Object(Symfony\Component\HttpFoundation\File\UploadedFile))
#5 E:\www\git\laravel-admin\vendor\encore\laravel-admin\src\Form.php(449): Encore\Admin\Form\Field\Image->prepare(Object(Symfony\Component\HttpFoundation\File\UploadedFile))
#6 E:\www\git\laravel-admin\vendor\encore\laravel-admin\src\Form.php(363): Encore\Admin\Form->prepareUpdate(Array)
#7 E:\www\git\laravel-admin\vendor\laravel\framework\src\Illuminate\Database\Connection.php(476): Encore\Admin\Form->Encore\Admin\{closure}(Object(Illuminate\Database\MySqlConnection))

**Comment by iianpan** [comment]
'admin' => [
            'driver' => 'local',
            'root' => public_path('upload'),
            'visibility' => 'public',
        ],

**Comment by iianpan** [comment]
config/admin.php

....
'upload'  => [

        'disk' => 'admin',

        'directory'  => [
            'image'  => 'image',
            'file'   => 'file',
        ],

        'host' => 'http://laraveladmin.app/upload/',
    ],
....

**Comment by iianpan** [comment]
vendor/encore/laravel-admin/src/Form/Field/File.php:173

public function destroy()
{
    if ($this->original){
        $this->storage->delete($this->original);
    }
}

**Comment by xqbumu** [comment]
用的哪个laravel-admin版本，你用的版本的Form/Field/File.php和我的1.3版本不一样诶，最好使用最新版本的哦

**Comment by iianpan** [comment]
非常感谢你的回复，问题找到了，不知为何，我的原图为空，所以删除的时候找不到图片，建议加个判断

**Comment by z-song** [comment]
好的 谢谢反馈！

**Comment by iianpan** [comment]
#
