### ISSUE TITLE
multipleImage

### ISSUE THREAD

**Issue by ruziyi** [z-song/laravel-admin#1333]
- Laravel Version: 5.6
- PHP Version: 7.17
- Laravel-admin: v1.5.5

### 多图上传问题
ErrorException In MultipleFile.php line 167 :

array_map(): Argument #2 should be an array (View: \resources\views\admin\form.blade.php)
![image](https://user-images.githubusercontent.com/7804644/31698294-65a6c75e-b3ef-11e7-8090-69e31770e192.png)

**Comment by z-song** [comment]
到修改器和访问器两个方法里面断点，看看有没有走进去

**Comment by ruziyi** [comment]
![image](https://user-images.githubusercontent.com/7804644/31709066-7a201bde-b423-11e7-8dc6-4b957e38265a.png)
发现这个函数导致的， 不明白什么用意

**Comment by z-song** [comment]
更新`laravel-admin`到版本`v1.5.x-dev`

**Comment by xcaptain** [comment]
https://github.com/z-song/laravel-admin/commit/fe6e8f72ee3bfb753ba421f32a13ebf0f17b90b7#comments

@z-song  我给你的这个commit评论了但是你没回复我，打个新的标签这样composer update的时候就自动修复了

**Comment by kelvenchi** [comment]
我也遇到这种问题， 有没有临时的解决方案？

**Comment by xcaptain** [comment]
@kelvenchi 这个问题直接composer update一下就解决了
