### ISSUE TITLE
后台grid 如果要默认按创建时间倒序排序是怎么修改?

### ISSUE THREAD

**Issue by 1027836596** [z-song/laravel-admin#1334]
- Laravel Version: 5.5.0
- PHP Version: 7.0+
- Laravel-admin: 1.5.0

### Description:
后台grid 如果要默认按创建时间倒序排序是怎么修改?

**Comment by z-song** [comment]
http://laravel-admin.org/docs/#/zh/model-grid-data

**Comment by 1027836596** [comment]
谢谢，已看到
