### ISSUE TITLE
How can I set the id as a primary key manual

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#1336]
- Laravel Version: 5.4.*
- PHP Version: >= 5.6.4
- Laravel-admin: 1.4.*

### Description:
How can I set the id as a primary key manual? In the other hand, I don't want to use Auto Increment for this primary key.

### Steps To Reproduce:
1- My database
MyTable
id - int --> auto increment <-- I don't want to use it.
data - text

I want to insert to this table using Form and I want to set the value of id as the value as I want.

**Comment by z-song** [comment]
In mysql remove AUTO_INCREMENT from column id

In form use `$form->text('id');`

**Comment by mfvodka107** [comment]
I have followed exactly steps but when go to create page the Primary key field do not show up.

**Comment by z-song** [comment]
@mfvodka107 Try following code

```php
protected function form($creating = false)
{
    ....
    if ($creating) {
        $form->text('gid', 'ID');
    }

    $form->saving(function ($form) {
        $form->input('id', request()->get('gid'));
    });   
}
```
And in create method of controller 
```php
    public function create(Content $content)
    {
        return $content
            ->header('Header')
            ->description('description')
            ->body($this->form(true));
    }
```

**Comment by RikiSptraaa** [comment]
Make your id increment in models file to false, it will make the form showed up
