### ISSUE TITLE
mysql5.6安装失败,Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes

### ISSUE THREAD

**Issue by xiaotianhu** [z-song/laravel-admin#1337]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
mysql5.6(阿里云RDS环境) laravel默认mysql配置('charset' => 'utf8mb4')会安装失败,报

  [Illuminate\Database\QueryException]
  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 767 bytes (SQL: alter table `users` add uni
  que `users_email_unique`(`email`))

**Comment by xiaotianhu** [comment]
把laravel的database配置,utf8mb4改为utf8就可以了.
可以参考https://stackoverflow.com/questions/34716683/specified-key-was-too-long-max-key-length-is-767-bytes这个回复.

**Comment by momosc** [comment]
ok的

**Comment by callmez** [comment]
不可以兼容么?这个问题
