### ISSUE TITLE
使用子域名而非添加前缀的方式使用 Laravel-Admin 时会导致路径 "/" 的权限无效

### ISSUE THREAD

**Issue by chestnut-framework** [z-song/laravel-admin#1338]
Laravel Version: 5.5
PHP Version: 7.1.8
Laravel-admin: 1.5

### 描述:
使用子域名而非添加前缀的方式使用 Laravel-Admin 时会导致路径 "/" 的权限无效

### 原因：
Laravel $request->is() 方法不能处理空字符串， 在不使用前缀的情况下，trim($match['path'], '/') 会返回一个空的字符串，导致不能正确识别路径跟权限，在用户登录进入时首页就会显示无权访问

### Fix:
文件路径: vendor\encore\laravel-admin\src\Auth\Database\Permission.php: line 93

```php
protected function matchRequest(array $match, Request $request): bool {
	if (!$request->is(trim($match['path'], '/'))) {
	
		return false;
	}
```
改为以下代码可解决
```php
protected function matchRequest(array $match, Request $request): bool {
	$path = trim($match['path'], '/');

	if (!$request->is($path == '' ? '/' : $path)) {
		return false;
	}
```

**Comment by arunfung** [comment]
您好，我想问下，您是如何配置子域名的，我通过laravel官方提供的在web中可以实现子域名，但在admin/routes.php中不起作用

**Comment by garyvv** [comment]
我也是使用独立域名，同发现这个问题，没处理这个issue不知道作者是否内置了其他方法处理？
