### ISSUE TITLE
Rules for limit file ext not work in file upload

### ISSUE THREAD

**Issue by lukaskris** [z-song/laravel-admin#1341]
- Laravel Version: 5.4
- PHP Version: 5.6
- Laravel-admin: 1.4

### Description:

$form->file("src", "Choose Video File")->rules('mimes:doc,docx,xlsx');
i use this from documentation,
but mimes doesn't work.. all format can upload

**Comment by lukaskris** [comment]
Done...
but not filter ext in file open

**Comment by yurik94** [comment]
Did you resolved? How?

**Comment by yurik94** [comment]
Hey @lukaskris 
Digging in bootstrap input I finally resolved!

```
$form->file('apk', 'APK')
            ->rules('mimes:apk')
            ->options([
                'allowedFileExtensions' => ['apk']
            ])
            ->attribute('accept', '.apk')
            ->required();
```

@z-song Can you please include in docs?
