### ISSUE TITLE
[Request] Request add * form label with rules required

### ISSUE THREAD

**Issue by t-perm** [z-song/laravel-admin#1342]
Can you support add required * form label ? Make user easy to know what field need to fill in ?

$form->text($column, [$label])->rules('required|min:10');

![screenshot-laravel-admin org-2017-10-23-12-58-21-741](https://user-images.githubusercontent.com/10907980/31874143-ed14d8e2-b7f1-11e7-8cf9-de9b3f8d2b5c.png)

**Comment by z-song** [comment]
Not supported yet.

But you can add a help block under the text field:
`$form->text($column, [$label])->rules('required|min:10')->help('Required !');`

**Comment by azinkey** [comment]
add required method 
$form->text('name', 'Name')->rules('required|min:3')->required(true);

in laravel-admin.css

.asterisk:after {
    position: absolute;
    content: '*';
    right: 0px;
    color: red;
}
