### ISSUE TITLE
Form\NestedForm $form->hasmany  switch bug

### ISSUE THREAD

**Issue by Jone-qiao** [z-song/laravel-admin#1345]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5.x-dev
<img width="1035" alt="wx20171024-122021 2x" src="https://user-images.githubusercontent.com/29858391/31924674-c2d1aad6-b848-11e7-898f-97548509fded.png">

Form\NestedForm $form->hasmany 关系中 switch 字段名相同的情况下 修改其中一个会影响到其他记录该相同字段的值

**Comment by Jone-qiao** [comment]
@z-song   表单提交的值和选择的值不同，求帮助！

**Comment by z-song** [comment]
提交了修复，更新一下
