### ISSUE TITLE
编辑时清空表单某个选填项后点击保存不会执行update

### ISSUE THREAD

**Issue by alexli0707** [z-song/laravel-admin#1346]
- Laravel Version: 5.4
- PHP Version:7.1
- Laravel-admin: 1.4.dev

### Description:
$form->text('ios_download_url', 'ios下载地址')->placeholder('输入ios的下载地址,选填')->default(''); 之前有保留该下载地址,点击编辑,清空该地址再点击保存,没有执行update语句

**Comment by z-song** [comment]
参考 https://laracasts.com/discuss/channels/laravel/laravel-54-auto-convert-empty-text-input-to-null

**Comment by alexli0707** [comment]
注释Http\Kernal 中的
`//        \Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,`
可以了,感谢
