### ISSUE TITLE
[Help] Get mode create or edit of form

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#1348]
- Laravel Version: 5.4.*
- PHP Version: >= 5.6.4
- Laravel-admin: 1.4.*

### Description:
I want to know the mode of form "create" or "edit"
I try to use these code in my controller
```
if ($form->builder()->isMode('create') ){ --> always return TRUE means always create mode
          // Do business for create mode
} else {
          // Do something else
}
```

but $form->builder()->isMode('create') always return TRUE. Why?

**Comment by NickCoolii** [comment]
Laravel Version: 5.5.*
    PHP Version: >= 7
    Laravel-admin: 1.5.*

Same thing. Even when I'm setup in controller's edit()
`    public function edit($id)
    {
        return Admin::content(function (Content $content) use ($id) {
            $content->header(self::$header);
            $content->description(trans('admin.edit'));

            $content->body($this->form()->edit($id));

            $this->form()->builder()->setMode('edit');
            dd($this->form()->builder()->isMode('create')); // return TRUE
        });
    }`

**Comment by NickCoolii** [comment]
@amun1303 same thing with laravel admin 1.5 version.

Trick which I'm using in $form->saving(); and $form->saved():
```
if (is_numeric(basename(request()->path()))) {
// edit mode
} else {
// create mode
}
```

Hope this will help you and push in right direction.

**Comment by amun1303** [comment]
Nice tips, thanks @NickCoolii
