### ISSUE TITLE
从1.5.3升级到v1.5.5，已上传到七牛的图片无法删除

### ISSUE THREAD

**Issue by clock1129** [z-song/laravel-admin#1349]
- Laravel Version: 5.5
- PHP Version: 7.0.22
- Laravel-admin: 1.5.5

### Description:
从1.5.3升级到v1.5.5，已上传到七牛的图片无法删除，但是能正常显示。
在1.5.3时候会显示一个垃圾桶的小图标，点击可以正常删除；
而在1.5.5的图片右上角会出现一个x图标，但点击无任何反应。
(chrome console和network无任何错误)
code:
          $form->image('bg_image', '背景图片')->uniqueName()
            ->resize(800, null, function ($constraint) {
                $constraint->aspectRatio();
            });

**Comment by z-song** [comment]
`$form->image('bg_image', '背景图片')->removable();`
