### ISSUE TITLE
[RFC] select2 multiselect disable auto sort by default

### ISSUE THREAD

**Issue by xcaptain** [z-song/laravel-admin#1351]
- Laravel Version: 5.5.14
- PHP Version: php7.1
- Laravel-admin: 1.5.5-dev

### Description:
When using multiselect, select2 will do some auto sort by default, as discussed in https://github.com/select2/select2/issues/3106, I don't like this behavior, I want selected options order corresponding to user input.

https://github.com/select2/select2/issues/3106#issuecomment-255492815 can solve the problem at some distant, Is this a feature that can be merged into master?

**Comment by z-song** [comment]
这个问题好像问的是选择一个option之后，这个option就会在下拉列表里面消失，和排序没有关系吧

**Comment by xcaptain** [comment]
不是的，这个问题说的是select2会自动把用户的输入排序之后提交，比如用户选择的是3,2,1，选完之后select2会自动把数据排序变为1,2,3提交。上面那个人的解法可以部分解决这个问题。

**Comment by xcaptain** [comment]
@z-song 我自己实现了一下这个功能，请review一下我的代码 https://github.com/z-song/laravel-admin/pull/1362

改动包括:
1. 当使用multiselect时按已经保存的顺序展示选项
2. 提交multiselect时把提交顺序写入到一个自定义的排序字段 `$this->orderField`里面

这个pr主要是为了解决select2插件诡异的排序问题，当多选的时候插件会重排选项之后再提交，这个改动让数据库中存的顺序和用户提交的顺序保持一致

**Comment by xcaptain** [comment]
有没有人关注一下这个issue啊，帮忙review一下代码，或者给个approve也可以 :cry:

**Comment by xcaptain** [comment]
@z-song 我又在优化后台了，这个问题能关注下吗，挺有用的功能，用户手动控制select选项的顺序而不是选择之后自动重排。

**Comment by linganmin** [comment]
@z-song 同样遇到这问题，多选的时候会按照id自动重排，和用户选择的顺序不一致

**Comment by xcaptain** [comment]
@linganmin  老的pr一直没有合并而且已经和主干偏差太大，我又开了一个新的，欢迎使用并测试我的补丁
 https://github.com/z-song/laravel-admin/pull/2092

@z-song 这次写的更详细了能review下代码吗

**Comment by pandakon** [comment]
能不能合并到master？我也很需要这个功能！
