### ISSUE TITLE
列表页面怎么修改checkbox里的值，默认为ID，我想用其他的字段

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#1352]
- Laravel Version: 5.4
- PHP Version:7.1
- Laravel-admin: 1.4

### Description:

如题
### Steps To Reproduce:
`$actions->prepend('<a href="' . $actions->getResource() . '/view/' . $actions->getKey() . '"><i class="fa fa-eye"></i></a>');`
自定义按钮里的`$actions->getKey()`得到的是主键，我想换成其他字段，怎么使用呢？

**Comment by z-song** [comment]
其它字段直接写字段名

**Comment by lePig** [comment]
我的数据库主键是`aid`，好像得`$actions->row->aid`这样写吧。

作者说直接写字段名，难道是这样`$actions->aid`？  我这里这样报错
