### ISSUE TITLE
[BUG] $form dateRange always show time

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1355]
I am using $form->dateRange() but render show with time.
```
$form->dateRange('beginDate', 'endDate', 'Time')->rules('required');
```
[![https://gyazo.com/fd8a4326659e6c93e51f871839a87781](https://i.gyazo.com/fd8a4326659e6c93e51f871839a87781.png)](https://gyazo.com/fd8a4326659e6c93e51f871839a87781)

**Comment by z-song** [comment]
Which version do you use?  It works fine for me

**Comment by taimaiduc** [comment]
Just update to 1.5.x-dev 2332ee3 and it work fine.
