### ISSUE TITLE
查询过滤器疑问

### ISSUE THREAD

**Issue by phplife** [z-song/laravel-admin#1356]
- Laravel Version: 5.4
- PHP Version:7.1
- Laravel-admin:1.4

### Description:
已经关闭了查询过滤器的主键查询，也就是调用了disableIdFilter()方法，但是即使如此在查询的时候还是会有对主键的where操作，经过打印所有的过滤方法得到结果
![image](https://user-images.githubusercontent.com/15216030/32041222-f2f1db6c-b9f8-11e7-8ece-3ebecafc4c82.png)
![image](https://user-images.githubusercontent.com/15216030/32041299-2c3fcb04-b9f9-11e7-8e57-98d7bd14f1c4.png)

如果其他操作中没有对主键的查询是没有问题的，但是如果其他的查询有对主键的查询那么这个方法就会把其他方法对主键查询的值匹配过来，因为是根据查询字段来匹配值的。

我加了一个对主键between的方法，最后打印出匹配成功后查询条件。
![image](https://user-images.githubusercontent.com/15216030/32041465-bb98d75a-b9f9-11e7-930c-a8db4e008b26.png)
![image](https://user-images.githubusercontent.com/15216030/32041528-f60f0f26-b9f9-11e7-83e4-73dad3976a73.png)

也就是说自定义的主键查询都会多一个默认的对主键的where查询，这样就无法得到正常的结果。
不知道是不是我的使用方法有问题，还请不吝赐教。

**Comment by z-song** [comment]
最重要的代码没贴出来🤣

**Comment by phplife** [comment]
![image](https://user-images.githubusercontent.com/15216030/32042069-02db5e56-b9fc-11e7-9e18-dbb22b2fd5c9.png)
这是控制器的代码🙏

**Comment by z-song** [comment]
这里确实有问题，待我提交修复

**Comment by phplife** [comment]
辛苦了

**Comment by z-song** [comment]
提交了修复  更新到`1.4.x-dev`

ps 建议迁移版本到1.5, 版本1.4已经没时间维护了

**Comment by phplife** [comment]
好的

**Comment by langeuh** [comment]
Can this be reopened?

The fix causes strange behaviour:
make sure you have multiple filters and disable the id filter
- surf to an overview => all ok
- click in the menu to another page causing pjax to work
- click back to the overview with filters (triggering pjax) => first filter is gone
- refresh the page => first filter is back

somehow removeIDFilterIfNeeded() gets called two times when using pjax
