### ISSUE TITLE
可以将laravel-admin的登录方式改为passport吗？

### ISSUE THREAD

**Issue by tiandaye** [z-song/laravel-admin#1359]
- Laravel Version: 5.5.*
- PHP Version:
- Laravel-admin: 1.5.*

### Description:
可以将laravel-admin的登录方式改为passport吗？但是想保留rbac

**Comment by z-song** [comment]
http://laravel-admin.org/docs/#/zh/custom-authentication  看看这个能否有用

**Comment by tiandaye** [comment]
3q
