### ISSUE TITLE
editable 修改报错

### ISSUE THREAD

**Issue by leeib** [z-song/laravel-admin#1363]
- Laravel Version: 5.5
- PHP Version:7.0.12
- Laravel-admin: 1.5.5

代码：
`
$grid->searchable('是否可搜索')
                ->display(function ($value) {
                return ConstantsHelper::textForSearchable($value);
            })
                ->editable('select', [
                '1' => '是',
                '2' => '否'
            ]);
`

初始是没有值的
![image](https://user-images.githubusercontent.com/5858278/32140141-c61ce8bc-bc90-11e7-8559-196b4f8dd257.png)

![image](https://user-images.githubusercontent.com/5858278/32140144-e6f04c28-bc90-11e7-909e-c07a1548fe91.png)

选择【是】后报错
![image](https://user-images.githubusercontent.com/5858278/32140147-f5f5a75e-bc90-11e7-820a-a27b0d627db0.png)

**Comment by z-song** [comment]
display和editable不能一起用

在浏览器的network看看具体的异常

**Comment by leeib** [comment]
代码：
`$grid->state('状态')->editable('select',[1=>'待审核',2=>'审核通过']);`
浏览器的异常：
![image](https://user-images.githubusercontent.com/5858278/32167067-c23c2bb4-bda2-11e7-974d-4f04ed0e0ce6.png)

**Comment by z-song** [comment]
要看具体的异常信息

**Comment by leeib** [comment]
![image](https://user-images.githubusercontent.com/5858278/32222987-74f017e2-be76-11e7-9bd6-df1573769f5a.png)
![image](https://user-images.githubusercontent.com/5858278/32223015-977f0d54-be76-11e7-8d84-bb5e7c584f08.png)
没有更具体的了 laravel.log里也未见异常日志

**Comment by z-song** [comment]
把出错的链接点开看啊
![image](https://user-images.githubusercontent.com/5858278/32167067-c23c2bb4-bda2-11e7-974d-4f04ed0e0ce6.png)

**Comment by leeib** [comment]
419目测是ajax请求缺少token，网站内是这样，admin里就不知道了，点进去就是js代码飘红，你说的是不是这个？web小白，暂时无力分析，做个人网站，在详情页修改也一样，暂时先搁置了，非常感谢！
