### ISSUE TITLE
La关于form组件switch的使用问题

### ISSUE THREAD

**Issue by zhfin** [z-song/laravel-admin#1366]
- Laravel Version: 5.5
- PHP Version:7.1.7
- Laravel-admin: 1.5

### Description:

使用form组件 开关选择switch 时, 提交后sql语句中并没有使用states指定的value, 而是使用了states中的'on'和'off'

上传报错截图(字段类型为tinyint)
![qq20171030-160733](https://user-images.githubusercontent.com/30734994/32160709-e30fba5e-bd20-11e7-9e30-ac283fffdd73.png)

Model
![qq20171030-160801](https://user-images.githubusercontent.com/30734994/32160728-f9870864-bd20-11e7-8731-4796ab98adcf.png)

代码段
![qq20171030-161851](https://user-images.githubusercontent.com/30734994/32160774-3a40ba30-bd21-11e7-9969-b4c0f6a74443.png)

**Comment by z-song** [comment]
你自己写的保存逻辑还是 LA得保存逻辑？

**Comment by zhfin** [comment]
@z-song 没有复写save方法  用的都是默认的  提交时就变成了on而不是1了

**Comment by zhfin** [comment]
@z-song 如果要复写方法的话  定义的value就没什么意义了呀:)

**Comment by zhfin** [comment]
@z-song 
![image](https://user-images.githubusercontent.com/30734994/32215758-dd1f22e4-bdf0-11e7-9d6d-9a391650762c.png)
不改变代码的情况下 grid的switch组件就能成功的更改数据。

**Comment by z-song** [comment]
不太清楚你的问题，因为grid就是使用form来保存数据的

模型不需要定义`$fillable`, 另外你试试字段名改成小写下划线试试看

**Comment by Lweiis** [comment]
同样遇到了这个问题
1. User 表中使用 Switch 组件, 完全相同的 option, 不会报错
2. 换个表就会报错, 提示在 update 字段时不能使用 "off" 或 "of"
3. 简单讲就是在提交字段修改的时候没有使用 value 而是强制使用 "on", "off" 字符
