### ISSUE TITLE
Using hasMany with a NestedForm

### ISSUE THREAD

**Issue by rm-aplicativa** [z-song/laravel-admin#1367]
- Laravel Version: 5.4.x
- PHP Version: 5.6.x
- Laravel-admin: 1.4

### Description:
I am wondering if there is any chance to use hasMany to create a nested form inside a nested form. I have a complex domain model and I am trying to avoid different forms for each model but instead use only form with nested forms. I hope the code make this more clear.

### Steps To Reproduce:
```php
            $form->display('id', 'ID');

            $form->text('name', 'Name')->placeholder('Name');
            $form->textarea('description', 'Description')->placeholder('Description');

            $form->hasMany('sections', function (Form\NestedForm $seccion_form) {
                $section_form->text('title');
                $section_form->textarea('description');
                $section_form->hasMany('entries', function(Form\NestedForm $entry_form) {
                   $entry_form->text('title');
                   $entry_form->textarea('description');
                });
            });

            $form->display('created_at', 'Created At');
            $form->display('updated_at', 'Updated At');
```

The variable naming is a bit unfortunate but I hope it gets clear. With the current code it throws an exception

```
 ErrorException In Builder.php line 2445 :

Call to undefined method Illuminate\Database\Query\Builder::entries() (View: /Users/ricardo/PhpstormProjects/ConapeAdmin/vendor/encore/laravel-admin/views/form.blade.php)
```

My section model defines the entries() method has follows:
```php
    public function entries() {
        return $this->hasMany('App\Models\RequirementEntry', 'requirementSectionId');
    }
```

**Comment by z-song** [comment]
This is not supported，

**Comment by rm-aplicativa** [comment]
Understood. Thank you
The documentation should probably be updated to specify this https://github.com/z-song/laravel-admin/blob/04a6d10485a49d1988f8b4c252ad24f836beba29/src/Form/NestedForm.php#L40

**Comment by fhferreira** [comment]
+1

**Comment by batmaster** [comment]
Still waiting for this...

**Comment by ferryhinardi** [comment]
Any alternative solution for this case?

**Comment by jpinagonzalez** [comment]
Any alternative solution for this case?

**Comment by meqabayt** [comment]
Any alternative solution for this case?

**Comment by blackcolt** [comment]
+1

**Comment by WarGen4ik** [comment]
+1

**Comment by SkubaBogdan** [comment]
Will be solution for this issue? It would be cool!

**Comment by lazerg** [comment]
what about now?

**Comment by igovet** [comment]
@z-song Still no solution?

**Comment by soufianoxx** [comment]
@z-song  no solution ?
