### ISSUE TITLE
[Suggestion] To avoid misuse, menu/action/button/link should be hidden with permissions

### ISSUE THREAD

**Issue by martinym28** [z-song/laravel-admin#1368]
- Laravel Version: 5.5
- PHP Version: 7.0
- Laravel-admin: 1.5

**Comment by z-song** [comment]
Can you describe it clearly?

**Comment by martinym28** [comment]
all the menu/action/button/link are displaying when the user login with [login, dashboard] of the permissions.
Then user got any notice as [deny] during tried to click any menu/action/button/link. User be confused which one is his permission.

**Comment by z-song** [comment]
You have to control the displaying of buttons/links manually, for example, you defined a permission `create-post` which is for authorize user to create new post.

Then in the definition of grid, for the users who don't have the `create-post` permission:
```
if (Admin::user()->cannot('create-post')) {
    $grid->disableCreation();
}
```
