### ISSUE TITLE
升级1.5.6的一个问题

### ISSUE THREAD

**Issue by qiumzh** [z-song/laravel-admin#1370]
- Laravel Version: 5.5.19
- PHP Version:7.1.7
- Laravel-admin:1.5.6

### Description:
升级1.5.6后出现了1.5.4出现的问题：
![image](https://user-images.githubusercontent.com/12442026/32233682-edf34640-be95-11e7-8fb3-82cae32f1daa.png)
然而我用1.5.5版本的时候是没问题的，今天升级了1.5.6就报错了。

PHP代码段：
![image](https://user-images.githubusercontent.com/12442026/32233786-316c72d4-be96-11e7-916e-d418959e2a32.png)

模型代码段：
![image](https://user-images.githubusercontent.com/12442026/32233775-242ec324-be96-11e7-866e-f9fe158177e3.png)

有必要说明的是，1.5.5版本是没问题的。。。

**Comment by qiumzh** [comment]
@@还有一点就是：添加是问题的。编辑的时候才报错。

**Comment by qiumzh** [comment]
ps：添加数据是没问题的。但 编辑数据的时候就报错了。

**Comment by tiandaye** [comment]
关联关系的名称改为小写试试
