### ISSUE TITLE
Permit each person to perform crud for his entities not others...

### ISSUE THREAD

**Issue by v01061374** [z-song/laravel-admin#1371]
- Laravel Version: 5.5.19
- PHP Version: 7.1
- Laravel-admin: last version

### Description:
hi. Thank you for your awesome package. I want to implement an online store which provides access to different stores to upload and sell their products. 
Logically, each person should only have access to his own products and not to other's...
How can I achieve this through roles and permission with your package?

**Comment by v01061374** [comment]
By person, I mean sellers...

**Comment by z-song** [comment]
Add a `user_id` column to the products table, the column is related to the `id` column in `admin_users` table

Then in your products grid definition, add:
```php
$grid->model()->where('user_id', Admin::user()->id);
```
Then all products listed in the gird are all belongs to the current login user.

Before update/delete products, check if the products are belongs to the login user.

**Comment by v01061374** [comment]
Thank you very much.
As a side note, when I follow your approach , the user can only see the products I want, is there any need to check again?(as you mentioned in your last sentence)

**Comment by z-song** [comment]
It is needed I think, to avoid people forgery the update/delete requests.
