### ISSUE TITLE
How can I reuse [Laravel Auth] to replace [laravel-admin's login]... etc?

### ISSUE THREAD

**Issue by martinym28** [z-song/laravel-admin#1372]
- Laravel Version: 5.5.#
- PHP Version: 7.1
- Laravel-admin: 1.5.6

### Description: continue to use [Laravel Auth] with table: users that is easy way for Authority and extension.
 [laravel-admin's login] have 3 tables: [admin_users], [demo_users] and [users] there are difficult to rang Authority and extension.

**Comment by z-song** [comment]
[laravel-admin's login] only uses `admin_users`, it has nothing to do with the other two tables

**Comment by martinym28** [comment]
How can How can I reuse [Laravel Auth]  with one table [users] for back-end and front-end?

**Comment by z-song** [comment]
Open `config/admin.php` find configuration `database.users_table`, modify it to `users`，

Then you need to modify the `users` table by adding two columns, `avatar` and `username` refer to the table structure of `admin_user`.

**Comment by martinym28** [comment]
Thanks for help, hope laravel-admin continue to use [Laravel Auth] directly.

**Comment by martinym28** [comment]
The most downloaded Expansion Package is, Packages keep and carry on **[Laravel Auth]**
