### ISSUE TITLE
Grid 如何获得当前行在结果集中的序号呢

### ISSUE THREAD

**Issue by Iceux** [z-song/laravel-admin#1374]
- Laravel Version: 5.5.#
- PHP Version:7.1.7
- Laravel-admin: 1.5.6

### Description:
Grid 在有查询过滤的情况下如何获得当前行在结果集中的序号呢，比如常见的显示列表需要显示一个序号（从0开始，非数据库主键）

**Comment by z-song** [comment]
先添加一个虚拟列：
```php
$grid->number('序号');
```
然后把序号设置给这一列：
```php
$grid->rows(function ($row, $number) {
    $row->column('number', $number);
});
```

**Comment by Iceux** [comment]
谢谢，很方便的添加了序列号

**Comment by yuange** [comment]
如果是取当前一条数据在数据库中的主键，该如何获取？

**Comment by z-song** [comment]
$grid->rows(function ($row, $number) {
    //主键
    $row->getKey();
});
