### ISSUE TITLE
可以将表格行操作中编辑改为模态框而不是切换到一个页面吗，应该怎么实现

### ISSUE THREAD

**Issue by xiaolony** [z-song/laravel-admin#1377]
- Laravel Version:  5.5.19
- PHP Version: 7.1.4
- Laravel-admin:  1.5.x-dev

### Description:
![image](https://user-images.githubusercontent.com/18529307/32360065-72619d98-c08d-11e7-944b-8049eeeb1272.png)

**Comment by z-song** [comment]
要自己实现了，参考自定义行操作

**Comment by Nicksxs** [comment]
@z-song 行内编辑可以支持多个字段编辑后再提交么
