### ISSUE TITLE
图片上传裁剪处理

### ISSUE THREAD

**Issue by xinhaonaner** [z-song/laravel-admin#1379]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5.x

### Description:
图片上传时，显示 Image source not readable
"intervention/image": "^2.4", 包已安装 
具体配置 贴出：
### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/24741621/32387763-7b28b2a4-c100-11e7-94e3-97fa1211a830.png)
![image](https://user-images.githubusercontent.com/24741621/32387835-9fe52906-c100-11e7-980b-c51d28a67bd6.png)

请问是什么原因呢？

**Comment by z-song** [comment]
insert方法是用来插入水印的，你的使用方法貌似有问题吧

**Comment by xinhaonaner** [comment]
![image](https://user-images.githubusercontent.com/24741621/32487093-9d896826-c3e3-11e7-8b68-e9bc0368f40e.png)
我按手册上的方法 好像不可以，http://laravel-admin.org/docs/#/zh/model-form-fields?id=%e5%9b%be%e7%89%87%e4%b8%8a%e4%bc%a0

**Comment by z-song** [comment]
`laravel-admin`的图片处理基于[Intervention](https://github.com/Intervention/image),  你这个问题是windows环境和Intervention的不兼容问题导致的

https://github.com/Intervention/image/issues/231

我的建议是不要用windows开发

**Comment by xinhaonaner** [comment]
根据 你的思路，找到了临时解决办法

**Comment by haipersist** [comment]
在Ubuntu同样遇到这个问题了，提示Image source not readable 。也按照上面哥们的加法，还是出错啊，还请大神帮忙解答。
