### ISSUE TITLE
使用gird->model()->orderBy()添加排序条件后，会和点击排序时添加的排序条件冲突

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#138]
$grid->model()->orderBy('id', 'desc');
代码中使用这个。
然后点击图中的
![image](https://cloud.githubusercontent.com/assets/7192860/20628210/a0ff292c-b35f-11e6-9b54-a9860c383392.png)
排序按钮，查询中的排序的条件会有两个
![image](https://cloud.githubusercontent.com/assets/7192860/20628230/bb16833c-b35f-11e6-81ee-44aaf439ac29.png)

**Comment by z-song** [comment]
已修复 谢谢反馈！
