### ISSUE TITLE
自己的js文件，里面的事件不触发，重新刷新后可以触发

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#1380]
- Laravel Version: 5.4
- PHP Version:7.1
- Laravel-admin: 1.4

### Description:
如题，可能是pjax的原因，跳转到一个新页面时，自己写的js事件不触发，强制刷新页面后可以触发，请问是什么问题？

**Comment by tobeychen** [comment]
要在Controller里用Admin::script('my_own_js();')叫自定义function,写在return之前。

my_own_js.js:
     function my_own_js(){
           alert('my own js');
    }

Controller.php:
     public function index(){
           Admin::script('my_own_js();');
           return Admin::content(function (Content $content) {
          }
     }

**Comment by rainforyou** [comment]
@tobeychen 我这样操作的还是不行

**Comment by codesve** [comment]
> @tobeychen 我这样操作的还是不行

我这边遇到同样的问题，使用上面的方法是可以的。

有可能会在其他地方出错，提示一下：
1. 按[文档](https://laravel-admin.org/docs/zh/frontend)说明，需要在`app/Admin/bootstrap.php`下添加`Admin::js('/your/javascript/path/js.js');`来引用自己的js代码；
2. 如果前端需要事件监听，如click/change，需要在tobeychen例子中的`my_own_js()`中添加监听。
