### ISSUE TITLE
Mongodb support

### ISSUE THREAD

**Issue by TheJoin95** [z-song/laravel-admin#1381]
- Laravel Version: 5.5.13
- Version PHP: 7.1.11
- Laravel admin: 1.5-dev

### Description:
Hi, is there any way to implement mongodb?
Or it is a task for the future release?

I read about this [repo](https://github.com/jenssegers/laravel-mongodb), that is the only one (good) for implement mongodb like db in Laravel.

**Comment by z-song** [comment]
Mongodb  is already supported

**Comment by sd2595101** [comment]
@z-song 有关于使用MongoDB的相关文档资料吗？

**Comment by devenpateldp** [comment]
Laravel Version: 5.7
PHP Version:7.1
Laravel-admin: latest

After first installing
https://github.com/jenssegers/laravel-mongodb

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function prepare() on null

Symfony\Component\Debug\Exception\FatalThrowableError
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php326

vendor/laravel/framework/src/Illuminate/Database/Connection.php

any solution?
