### ISSUE TITLE
How to change ext and save file byte encrypt in file upload request

### ISSUE THREAD

**Issue by lukaskris** [z-song/laravel-admin#1385]
- Laravel Version: 5.4
- PHP Version: 5.5
- Laravel-admin: 1.4

### Description:
how to change ext and change file data byte before upload file?
i'm using master detail, in detail has many file upload (ex: video)
i want encrypt this video first, and change .mp4 format to .abcd
there is my code

```

$form->saving(function($form){
                $thumbnail_path   = public_path().'upload/images';
                           
                $sub_lessons = request()->sub_lessons;
                
                foreach ($sub_lessons as $sub_lesson) {
                    $tdes = new TripleDES("keyencrypt");
                    $data = file_get_contents($sub_lesson["src"]->getRealPath());
                    $bytes = $tdes->encrypt($data);
                    $name = $sub_lesson["src"]->getClientOriginalName() . ".abcd";
                    
                    // how to save my $bytes using name file $name
                }
                
            });
```

**Comment by z-song** [comment]
Try to use `file_put_contents();` to save `$bytes` to the file temp path

**Comment by lukaskris** [comment]
How to save in ftp? Not in temp folder?

**Comment by lukaskris** [comment]
How to save in ftp? Not in temp folder?

**Comment by lukaskris** [comment]
@z-song how to upload to cloud? maybe FTP or S3
what should i do?
file_put_contents() to save in temp path, but i want upload to cloud

**Comment by lukaskris** [comment]
@z-song how to upload to cloud? maybe FTP or S3
what should i do?
file_put_contents() to save in temp path, but i want upload to cloud

**Comment by z-song** [comment]
You need a ftp or S3 filesystem driver to upload files to cloud

ref https://laravel.com/docs/5.5/filesystem#driver-prerequisites
