### ISSUE TITLE
权限校验是通过限制路由完成， 可以让某部分路由不需要权限校验吗？

### ISSUE THREAD

**Issue by tiandaye** [z-song/laravel-admin#1386]
- Laravel Version: 5.5.*
- PHP Version:7.0.12
- Laravel-admin: 1.5.*

### Description:
权限校验是通过限制路由完成， 可以让某部分路由不需要权限校验吗？

**Comment by z-song** [comment]
没有设置权限的路由，访问的时候就不会验证权限

**Comment by tiandaye** [comment]
3q
