### ISSUE TITLE
Role类中的role_id跟user_id是不是反了？

### ISSUE THREAD

**Issue by sqw00453579** [z-song/laravel-admin#1387]
- Laravel Version: 5.5
- PHP Version: 7
- Laravel-admin: 1.5.x-dev

### Description:
laravel-admin/blob/master/src/Auth/Database/Role.php 中的administrators方法里：
role_id跟user_id是不是反了？

**Comment by z-song** [comment]
没有反

**Comment by sqw00453579** [comment]
那怎么根据role_id来获取角色中的用户列表呢？

**Comment by z-song** [comment]
`Role::find($id)->administrators`

**Comment by sqw00453579** [comment]
我就是用这个去获取，然后就发现是反的，才来反馈一下，如果我把
laravel-admin/blob/master/src/Auth/Database/Role.php 中的administrators方法里的关联
`return $this->belongsToMany($relatedModel, $pivotTable, 'user_id','role_id');`
改成：
`return $this->belongsToMany($relatedModel, $pivotTable, 'role_id','user_id');`
就正常了

**Comment by z-song** [comment]
https://github.com/z-song/laravel-admin/blob/master/src/Auth/Database/Role.php#L39

你的代码是从哪里弄来的？
