### ISSUE TITLE
升级1.5.6后带有tag组件的模型新建出错

### ISSUE THREAD

**Issue by Share-Man** [z-song/laravel-admin#1388]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 5.1.6

### Description:
![image](https://user-images.githubusercontent.com/4065724/32502548-001e6856-c416-11e7-9685-9260689aa6cb.png)
Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: Invalid argument supplied for foreach() (View: /www/wwwroot/XXXXXXX/vendor/encore/laravel-admin/resources/views/form/tags.blade.php)

### Steps To Reproduce:
修改是没问题的，新建就出错
已经重新发布过资源也不行

**Comment by z-song** [comment]
确实有点问题，你先用`$form->tags(xxx)->default([]);`修复一下吧

**Comment by z-song** [comment]
已修复
