### ISSUE TITLE
关于editable('select'）的问题

### ISSUE THREAD

**Issue by gystone** [z-song/laravel-admin#1389]
`$grid->status('订单状态')->editable('select', [0 => '待审核', 1 => '审核通过，待付款', 2 => '待发货',3=>'已发货',4=>'已完成',5=>'已取消'])->sortable();`

例如我现在选择的是3：待发货，数据库中记录的状态也是3
请问一下，有没有方法能让，再此选择的时候只能选择4或者5，前面012都是不能选择的状态

**Comment by z-song** [comment]
无法实现
