### ISSUE TITLE
请问能修改option的属性值吗

### ISSUE THREAD

**Issue by wslsq** [z-song/laravel-admin#1390]
- Laravel Version: 5.5
- PHP Version:7.1.5
- Laravel-admin: 1.5

### Description:
项目需要，要给select的options加一个data-price值，请问有方法实现吗，谢谢

**Comment by z-song** [comment]
有办法，要自定义一个Select对象和视图来实现

```php
class CustomSelect extends \Encore\Admin\Form\Field\Select
{
    protected $view = '你自定义的视图';

    public function render()
    {
        $vars = []; // 这里给视图传入变量，你的data-price
        return parent::render()->with($vars);
    }
}
```

新建视图文件参考 https://github.com/z-song/laravel-admin/blob/master/resources/views/form/select.blade.php

用传进来的变量，修改option的属性

最后打开app/Admin/bootstrap.php注册这个组件
```php
<?php

use App\Admin\Extensions\CustomSelect;
use Encore\Admin\Form;

Form::extend('select', CustomSelect::class);
```
就能用了

**Comment by wslsq** [comment]
感谢回复
