### ISSUE TITLE
升级到1.5后筛选出问题

### ISSUE THREAD

**Issue by nashlibby** [z-song/laravel-admin#1391]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5.6

### Description:

升级到1.5.6后发现筛选项第一个不见了，然后重新刷新下页面点筛选才会出来。。。

**Comment by nashlibby** [comment]
我发现开启了disableIdFilter()后就会出现这个问题

**Comment by z-song** [comment]
这个bug已经修复了，更新到`1.5.x-dev`解决

**Comment by nashlibby** [comment]
谢谢，啥时候发

**Comment by arunfung** [comment]
撤销按钮也无效
