### ISSUE TITLE
异步返回，页面提示框如何操作？

### ISSUE THREAD

**Issue by qiumzh** [z-song/laravel-admin#1394]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
当前自定义异步处理成功返回时，我应该如何操作页面显示提示框呢？类型这样的提示？
![image](https://user-images.githubusercontent.com/12442026/32613793-c2cf39e8-c5a6-11e7-8645-932e5097f2f6.png)

**Comment by z-song** [comment]
```js
toastr.info('刷新成功！')
```
ref https://github.com/CodeSeven/toastr
