### ISSUE TITLE
文件上传插件预览ZIP乱码的问题

### ISSUE THREAD

**Issue by SammyLee666** [z-song/laravel-admin#1395]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
我现在想关闭file上传插件的预览，因为在ZIP格式下回乱码，请问应该怎么办

**Comment by xs47968224** [comment]
``` 
$form->file('zip', '上传zip')->options([
                'showPreview' => false, // 如果只需要关闭预览功能，设置这句即可
                'allowedFileExtensions'=>['zip']             
])
```

更多参考：[https://github.com/z-song/laravel-admin/issues/1403](url)
