### ISSUE TITLE
Grid Expand Row id Data

### ISSUE THREAD

**Issue by chinajuns** [z-song/laravel-admin#1396]
- Laravel Version: 5.5.*
- PHP Version:7.1
- Laravel-admin: 1.5.*

### Description:
$grid->column('expand')->expand(function ()use ($grid){
                
                $data =  $grid->model()->where('id','=',$id);//如何获取这个ID
               $header = ['用户名','邮箱','QQ','手机号',......];
               $rows = [[]];//拿到数据填充到row
                return new Table($header,$rows);
            });

**Comment by z-song** [comment]
`$this->id`

当前行的数据都可以通过`$this`取到，不要用model去查询

**Comment by chinajuns** [comment]
谢谢，

**Comment by akazhuk** [comment]
朋友，Grid 的这个Expand 要怎么扩展出来？
