### ISSUE TITLE
tree view can't load custom query

### ISSUE THREAD

**Issue by ajaxangular** [z-song/laravel-admin#1397]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5.*

### Description:
I tried to get tree-view works with custom query but $tree->query is never hit. On the contrary, $tree->branch hit with default query (show all data). What's wrong with my code below... Help me, thanks

### Steps To Reproduce:
This is my code

`

    public function index()
    {
        return Admin::content(function (Content $content) {
            $content->header('Menu');

            $body = Menu::tree(function ($tree) {
                $tree->query(function ($model) {
                    dd('hit query');
                    return $model->where('type', 1);
                });

                $tree->branch(function ($branch) {

                    $payload = "<i class='fa {$branch['icon']}'></i>&nbsp;<strong>{$branch['title']}</strong>";

                    if (!isset($branch['children'])) {
                        if (url()->isValidUrl($branch['uri'])) {
                            $uri = $branch['uri'];
                        } else {
                            $uri = admin_base_path($branch['uri']);
                        }

                        $payload .= "&nbsp;&nbsp;&nbsp;<a href=\"$uri\" class=\"dd-nodrag\">$uri</a>";
                    }
                    return $payload;
                });
            });

            $content->body($body);
        });
    }
`

**Comment by lonycn** [comment]
get the same problem.
did you fix it?

**Comment by JayGajjar** [comment]
Hi, @z-song @ajaxangular i am also facing same problem, if you have found solution kindly update issue with answer.

**Comment by komarove** [comment]
$tree = $tree->query(function ($model) use ($role) {
            return $model->where('role', $role);
        });
