### ISSUE TITLE
grid的openMap方法没有显示 

### ISSUE THREAD

**Issue by huangda2100** [z-song/laravel-admin#1399]
- Laravel Version: 5.5.1
- PHP Version:7.1.8
- Laravel-admin: 1.5.x

### Description:
  @z-song 我照着demo网站源码中的Demos中Users的grid的写法，根据经纬度显示地图上的位置，但是显示出来的是null并且不可点击。而且demo网站中的这个功能也无法显示地图及位置。

**Comment by z-song** [comment]
参考demo文件`app/Admin/bootstrap.php`
