### ISSUE TITLE
form组件的multipleImage能否拖动排序图片？

### ISSUE THREAD

**Issue by xlkit456852** [z-song/laravel-admin#1400]
- Laravel Version: 5.6.4
- PHP Version:7
- Laravel-admin: 1.3.*

### Description:
multipleImage组件显示的图片有个左下角有个图标，鼠标以上会出现手掌样式，这个是能拖动排序的吗？但是我无论怎么拖也无反应。不知道现在是否有拖动（或其他方式）排序的功能？

**Comment by z-song** [comment]
不支持

**Comment by qdladoooo** [comment]
我也需要这个功能。
要不我们找时间实现一下吧

**Comment by kanakawaken** [comment]
希望能有这个功能
