### ISSUE TITLE
Problem with filtering data from 2 tables on 2 connections, they were joined and they have the same column name

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#1401]
- Laravel Version: 5.4.*
- PHP Version: >= 5.6.4
- Laravel-admin: 1.4.*

### Description:
I met a problem with filtering data from 2 tables on 2 connections, they were joined and they have the same column name

### Steps To Reproduce:
Table 1 on connection 1:
**CHAPTER table**
```
id -> int
chapter_id -> int
book_id -> int
chapter_name -> text
```

Table 2 on connection 2:
**ASSIGNED table**
```
id -> int
fromAdminId -> int
toAdminId -> int
book_id -> int
chapter_id ->
status -> tinyint
```

I need to display the list of chapters have assigned to specify adminUser.
First I set the model base on userAdmin has logged.
```
if ( Admin::user()->inRoles( [ 'employee' ] ) ) {
     $grid->model()->join( databaseName on connection 2 . '.ASSIGNED', function ( $join ) {
          $join->on( 'CHAPTER.chapter_id', '=', 'ASSIGNED.chapter_id' )
               ->where( 'ASSIGNED.to_id', '=', Admin::user()->id )
               ->select()
               ->where( [ [ 'status', '=', 0 ], ] );
          } );
}
```

Everything up to now is ok
I tried to filter this list by book_id but I met error because I have the same book_id name on both tables.
`$filter->is( 'book_id', 'BOOK_ID' );`

> SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'book_id' in where clause is ambiguous

Please help me to solve this problem!

**Comment by z-song** [comment]
try ：
```php
$filter->where(function ($query) {
    return $query->where('tablename.book_id', $this->input);
}, 'Book id');
```

**Comment by amun1303** [comment]
It's worked, Thanks @z-song so much
