### ISSUE TITLE
grid > form >switch

### ISSUE THREAD

**Issue by dky3344** [z-song/laravel-admin#1402]
- Laravel Version: 5.5.*
- PHP Version:7.1
- Laravel-admin: 1.5.*

### Description:
 $is_pass = [
                'on'  => ['value' => '1', 'text' => '不通过', 'color' => 'danger'],
                'off' => ['value' => '2', 'text' => '通过', 'color' => 'primary'],
            ];
            $grid->column('is_pass','审核')->switch($is_pass);

### Steps To Reproduce:
  $form->saving(function ($form) {
          ??//当开关按钮操作时候，获取不到update提交过来的数据  saved   也不行。 
            });

**Comment by xs47968224** [comment]
```
$form->saving(function ($form) {
 dd($form->is_pass)
});

$form->saved(function ($form) {
 dd($form->model()->is_pass)
});

应该是以上的区别，注意使用时的区别
```

**Comment by xs47968224** [comment]
```
$form->saving(function ($form) {
 dd($form->is_pass)
});

$form->saved(function ($form) {
 dd($form->model()->is_pass)
});

应该是以上的区别，注意使用时的区别
```
