### ISSUE TITLE
有没有方法可以对grid数据根据非model字段进行排序？

### ISSUE THREAD

**Issue by ianmay139** [z-song/laravel-admin#1406]
- Laravel Version: 5.5
- PHP Version:
- Laravel-admin: 1.5.5

### Description:
就是Grid 中有些通过关联表格等计算得到的（列）数据，客户希望根据这些数据（列）排序，然而定义的字段不再model中，请问有没有什么好办法可以直接根据这些数据排序呢？

**Comment by z-song** [comment]
只能根据表字段排序，你的需求无法实现

**Comment by luoxulx** [comment]
![image](https://user-images.githubusercontent.com/35016570/41573736-b7875134-73b0-11e8-83f9-fa91c369095d.png)
@z-song 我也需要使用外部api数据源时，对表格进行排序，横线处能做个判断更新下否？重写了太多了
