### ISSUE TITLE
路由配置上结合权限中间件来控制路由的权限后，方法中获取登录用户id报错

### ISSUE THREAD

**Issue by DamonSnow** [z-song/laravel-admin#1407]
- Laravel Version: 5.5.13
- PHP Version:7.1.1
- Laravel-admin: 1.5.x-dev

### Description:
描述如题，
![issue_x](https://user-images.githubusercontent.com/18485833/32778143-b7579ed6-c973-11e7-99f5-d918806d5699.png)
路由配置如下图
![issue_x1](https://user-images.githubusercontent.com/18485833/32778182-debf5d74-c973-11e7-8a77-04dc27400fce.png)

**Comment by z-song** [comment]
默认的中间件`config('admin.route.middleware')`，不能去掉

**Comment by DamonSnow** [comment]
如果加入默认的中间件，里面的路由全部显示无权限。这样就不能实现允许某个角色访问group里的路由了，是我写得有问题吗？比如我想让角色为user的用户可以直接访问该group的路由，以下写法无法实现。
![admin_bug](https://user-images.githubusercontent.com/18485833/32827805-518be99e-ca28-11e7-8f23-70aafd500ea6.png)

**Comment by z-song** [comment]
你要实现后台值允许两个角色访问，那在后台只添加这两个角色就好了

**Comment by DamonSnow** [comment]
我上面的代码不是在后台只添加这两个角色吗？能给个范例吗？

**Comment by z-song** [comment]
填加角色要到后台角色管理页面手动填写添加

**Comment by DamonSnow** [comment]
角色在后台已经添加了，但是以上写法不行啊。
![admin](https://user-images.githubusercontent.com/18485833/32925152-6a0573f6-cb7b-11e7-953d-6490663b1d77.png)
路由还是以上那样，该group中有/user的路由，现在一个用户角色为user的登陆后进入该路由结果是无权访问。如下图：
![adminallow](https://user-images.githubusercontent.com/18485833/32925465-07ff2240-cb7d-11e7-9577-00d3c51c9f47.png)

**Comment by z-song** [comment]
你先建了角色，有给这个角色赋这个页面的访问权限么

**Comment by DamonSnow** [comment]
没有，可是我想达到的目的就是某个路由群组不用判断权限啊，也就是公开的
