### ISSUE TITLE
正在做画册的图片管理功能，laravel-admin有相应插件吗？

### ISSUE THREAD

**Issue by xlkit456852** [z-song/laravel-admin#1414]
- Laravel Version: 5.3.*
- PHP Version:5.6.4
- Laravel-admin: 1.3.*

### Description:
正在做画册的图片管理功能，就是一本画册对多张图片，后台对图片能进行增删查改，排序等，laravel-admin有相应的插件吗？或者有什么其他的laravel插件可以推荐？辛苦了，谢谢！

**Comment by z-song** [comment]
一般不会有这种比较个性化需求的插件，公共插件都只是满足公共需求的。
