### ISSUE TITLE
wangediter and select are not match

### ISSUE THREAD

**Issue by zhenggg** [z-song/laravel-admin#1416]
- Laravel Version: 5.5.21
- PHP Version: 7.0.12
- Laravel-admin: 1.5.6

### Description:
wangediter 层级太高影响下拉框

### Steps To Reproduce:
表单中 一个下拉框 紧接着 一个 wangediter，下拉框的选项会的选择会被wangediter  干扰

**Comment by z-song** [comment]
下次遇到wangEditor的问题可以去https://github.com/wangfupeng1988/wangEditor/issues 找答案，
毕竟在这个编辑器在laravel-admin里面只是一个扩展示例，不属于内置功能，遇到问题还是要自己去解决。

相关问题：
https://github.com/wangfupeng1988/wangEditor/issues/776

解决办法，给编辑器添加一项配置：
```js
editor.customConfig.zIndex = 0;
```
