### ISSUE TITLE
Edit form not loading checkbox value

### ISSUE THREAD

**Issue by lucaydaniel** [z-song/laravel-admin#1417]
- Laravel Version: 5.5.20
- PHP Version: 7.1.10
- Laravel-admin: 1.5

### Description:

First of all thank you for this amazing library. I got a kickass admin panel up and running in a matter of minutes :heart_eyes:.

Regarding the issue that I am facing. I have a column which stores a boolean value (`published`). If it's `true` it means that the administrator has approved the News.

Everything works fine inside the `grid()` method, it's showing the correct value from the database but for some reason while editing the resource the checkbox is not checked even if the value in the database is true.

Most probably is my fault can anyone please help me? Many thanks!

Code in `NewsController.php` that renders the checkbox:

`$form->checkbox('published', 'Published')->options(['published' => 'Yes']);`

Mutator that converts array type into string:

```
public function setPublishedAttribute($value)
{
   if(in_array('published', $value))
     $this->attributes['published'] = true;
   else
     $this->attributes['published'] = false;
}
```

**Comment by xs47968224** [comment]
Use Switch function without setAttribute
```
$states = [
    'on'  => ['value' => 1, 'text' => 'Published', 'color' => 'success'],
    'off' => ['value' => 0, 'text' => 'Draft', 'color' => 'danger'],
];

$form->switch($column[, $label])->states($states);
```

**Comment by leandroeidi** [comment]
Use accessors. Mutators to save data to the database, acessors to retrieve data from database.

public function getPublishedAttribute($value)
{
    return $value == true ? 'published' : '';
}
