### ISSUE TITLE
无限分类，模型树 编辑的时候，URL有误

### ISSUE THREAD

**Issue by xinhaonaner** [z-song/laravel-admin#1419]
- Laravel Version: 5.5
- PHP Version:7.0.12
- Laravel-admin: 1.5.*

### Description:
无限分类，使用模型树。
在 编辑的时候，除了第一级，其他子类URL都不对，删除正常。

异常
![image](https://user-images.githubusercontent.com/24741621/32981674-9e8b2cfe-ccb3-11e7-98e1-e207bf027766.png)
正常
![image](https://user-images.githubusercontent.com/24741621/32981688-d301c5d8-ccb3-11e7-9c92-a422c2e02da7.png)

可能是 什么原因，或者 给个思路去哪里 查看，谢谢

**Comment by xinhaonaner** [comment]
原因找到了，是category表里有个 `path` 字段。那这是 为什么呢？

**Comment by z-song** [comment]
哪里的`category`表？

**Comment by xinhaonaner** [comment]
![image](https://user-images.githubusercontent.com/24741621/33053242-86a7f2d8-cead-11e7-96a5-7c64b4c975d7.png)

用的是 mysql，现在我把``path``字段改成 route 就好了,你可以本地测试下，在模型树 对应表中加个 path字段，再 看看 第几级以后 的编辑URL 是不是 和我一样

**Comment by never615** [comment]
库(grid和tree)里面用到关键字path了,model如果也有path命名的列就会有问题.
建议基础库的名字起得特别些,或者文档说明这些关键字数据库字段不能使用..
@z-song
