### ISSUE TITLE
Laravel-admin with Entrust? 

### ISSUE THREAD

**Issue by chimmel** [z-song/laravel-admin#1420]
- Laravel Version: 5.5
- PHP Version: 7
- Laravel-admin: ^1.5

### Description:
I already have a users table `users`, as well as `roles` and `permissions` via Entrust. I tried changing the config/admin.php values for users_table, users_model, roles_table, roles_model, etc., to what I have, and it threw an error that those tables already exist. 

How do I use my existing tables and models? 

### PS:
When I try logging in to http://discuss.laravel-admin.org with GitHub I get an error:
```
League \ OAuth2 \ Client \ Provider \ Exception \ GithubIdentityProviderException (200)
bad_verification_code
```

**Comment by chimmel** [comment]
By the way when I try logging in to discuss.laravel-admin.org with GitHub I get an error

**Comment by chimmel** [comment]
So there is no way to integrate the admin users and regular users? Like on the frontend of the site, if I want something displayed only for logged in users, I have to account for both separately each time?

**Comment by chimmel** [comment]
The [Quickstart](http://laravel-admin.org/docs/#/en/quick-start) states that this uses the default User model and corresponding table. . . . ?

**Comment by chimmel** [comment]
Please help

**Comment by z-song** [comment]
Sorry, I haven't experienced Entrust before, I'll try to integrate `laravel-admin` and Entrust, and release a doc if it works

**Comment by chimmel** [comment]
Thank you

**Comment by noogen** [comment]
I'm guessing you can take a look at config/admin.php 'database' section if you want to use other tables.  You may need to add/transform if it doesn't have similar field/columns.

I actually like the separation between internal/backend users and external/frontend users.  It does get a little confusing sometime with both type of users on the same app.

**Comment by chimmel** [comment]
Yeah I feel the opposite. I tried changing the values in there to match
mine to no avail. Could be that I didn't try hard enough.

On Nov 27, 2017 13:51, "Tom Noogen" <notifications@github.com> wrote:

I'm guessing you can take a look at config/admin.php 'database' section if
you want to use other tables. You may need to add/transform if it doesn't
have similar field/columns.

I actually like the separation between internal/backend users and
external/frontend users. It does get a little confusing sometime with both
type of users on the same app.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/z-song/laravel-admin/issues/1420#issuecomment-347285335>,
or mute the thread

**Comment by chimmel** [comment]
Sorry for the above. Z-song is this a major undertaking or do you think you'll have it available sometime soon?
