### ISSUE TITLE
请问怎么更改图片后而不删除源图片

### ISSUE THREAD

**Issue by raykaye** [z-song/laravel-admin#1424]
### Description:
请问怎么更改图片后不删除源图片, 因为有一个默认图片, 被多个引用.
而我现在想在Contorlller中, $from->saving(function() { ..... }) 实现.
尽可能不改变\encore\laravel-admin下的文件, 方便后面的升级维护.

**Comment by z-song** [comment]
参考demo的管理员编辑页面的头像设计

**Comment by raykaye** [comment]
好的  谢谢大牛提供的思路

**Comment by raykaye** [comment]
@z-song 我根据您的回答, 去看了头像设计相关代码, 还是没能实现相关功能, 好笨啊自己....
我主要看了\laravel-admin\src\Controllers\UserController.php, 发现主要不同是Administrator.php使用了trait, 
唯一一个有关头像的是trait AdminPermission 的 getAvatarAttribute()设置默认头像
还望您能多指导一点

**Comment by z-song** [comment]
参考`getAvatarAttribute`方法给你的字段也增加一个访问器就好了

**Comment by raykaye** [comment]
嗯 我再试试

**Comment by raykaye** [comment]
@z-song 可以了, 已经实现了想要的功能  谢谢大佬的框架和指导
