### ISSUE TITLE
无法上传图片

### ISSUE THREAD

**Issue by liyingxuan** [z-song/laravel-admin#1425]
- Laravel Version: 5.5.*
- PHP Version: 7.1.6
- Laravel-admin: 1.5.*

### Description:
已经根据文档配置好了wangeditor，能正常上传文字。但是无法上传图片。
有什么特殊配置么。

网页内报错：
QueryException In Connection.php line 664 :

SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'input' at row 1 

浏览器Console报错：
Failed to load resource: the server responded with a status of 403 (Forbidden)

**Comment by xs47968224** [comment]
报的是数据库存储错误，你要直接存储图片？如果直接存储图片，好像可以用blob, 通常的做法是先把文件保存到服务器，然后再保存文件路径到数据库

**Comment by liyingxuan** [comment]
根据文档配置是直接blob的，数据库字段用longtext也存不进。

现在换百度的uEditor，图片上传好使了，不过有新的小问题。
