### ISSUE TITLE
show morphMany Relation in the grid

### ISSUE THREAD

**Issue by joernroeder** [z-song/laravel-admin#1427]
- Laravel Version: 5.5.21
- PHP Version:
- Laravel-admin: 1.5.6

### Description:
I'm having a model with a `morphMany` relation which works well in my controllers.

```php
public function profileImages()
{
    return $this->morphMany('App\Image', 'imaginable');
}
```

In the grid i'd like to show a badge with a counter `$grid->profileImages()->count()->badge();` but the column stays empty. I've also tried to loop over the images via `->display(function ($images) {})` but i'm always getting `null` as the result. 
I couldn't find any code regarding grid and morpMany relationships https://github.com/z-song/laravel-admin/search?utf8=%E2%9C%93&q=morphMany&type= are i'm missing something or is this unsupported at the moment?

Thanks in advance!

**Comment by joernroeder** [comment]
could be related to #946

**Comment by z-song** [comment]
Try
```php
$grid->model()->with('profileImages');

$grid->column('profile_images')->count()->badge();

```

**Comment by joernroeder** [comment]
@z-song yes that works! Thanks
