### ISSUE TITLE
filter 里面的select没有调用api, 求正确姿势

### ISSUE THREAD

**Issue by kelvenchi** [z-song/laravel-admin#1432]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.4

### Description:
filter 里面的select并没有调用api

### Steps To Reproduce:

```php
$filter->where(function ($query) {
    $input = $this->input;
    $query->whereHas('project_type', function($query) use($input) {
        $query->where('name', $input);
    });
}, '标的类型')->select('admin/api/get_types');
```

**Comment by xinhaonaner** [comment]
我也是 过来看看，加载搜索框时，没有 请求
![image](https://user-images.githubusercontent.com/24741621/33545939-9e751e14-d91a-11e7-99eb-61ff24c473e2.png)

**Comment by z-song** [comment]
提交了修复 更新到`1.5.x-dev`

**Comment by xinhaonaner** [comment]
![image](https://user-images.githubusercontent.com/24741621/33592763-74d76ee2-d9c7-11e7-8b97-c60f13f57d17.png)
请求有了，但是 数据没有赋值到select框  ^_^

**Comment by rainforyou** [comment]
@xinhaonaner    好像还没解决，你的可以搜索吗？

**Comment by xinhaonaner** [comment]
不行

**Comment by z-song** [comment]
@rainforyou @xinhaonaner 下面这样用
`$filter->equal('author_id')->select()->ajax('/demo/api/users');`

**Comment by rainforyou** [comment]
@z-song   现在select  和multipleSelect  使用方法变了吗

**Comment by Wfengling** [comment]
1.5还是存在select api不能填充数据的情形

**Comment by zhangyangchen** [comment]
> @rainforyou @xinhaonaner 下面这样用
> 
> `$filter->equal('author_id')->select()->ajax('/demo/api/users');`

问题还在

**Comment by synard1** [comment]
same for me, if it got the correct result, then it show the result could not be loaded.

without ajax, i can get the result, but looks like blank value
