### ISSUE TITLE
集成wangEditor-3.0.14 可以显示但是不能编辑。

### ISSUE THREAD

**Issue by Alucardmini** [z-song/laravel-admin#1433]

**Comment by Alucardmini** [comment]
刚试了3.0.8提示这个错误
![image](https://user-images.githubusercontent.com/8130720/33177710-913e2684-d09e-11e7-8e32-1de67b2ae5bf.png)

**Comment by z-song** [comment]
wangEditor的问题请去https://github.com/wangfupeng1988/wangEditor/issues提问
