### ISSUE TITLE
options can't be overwritten with the UploadFile trait

### ISSUE THREAD

**Issue by lynrin** [z-song/laravel-admin#1436]
- Laravel Version: 5.5.21
- PHP Version: 7.1.11
- Laravel-admin: 1.5.6

### Description:
In the Image field(also File field), it is rendered as "false" even though the overwriteInitial option is set to "true".
It seems to be caused by arguments of the array_merge function is reversed in the options method of the UploadFile trait.

src/Form/Field/UploadField.php
```diff
    public function options($options = [])
    {
-        $this->options = array_merge($options, $this->options);
+        $this->options = array_merge($this->options, $options);

        return $this;
    }
```

**Comment by z-song** [comment]
Please fell free to send a pull request :)
