### ISSUE TITLE
grid中如何显示数据？

### ISSUE THREAD

**Issue by heimasi** [z-song/laravel-admin#1439]
-Laravel Version: 5.5
-PHP Version: 7.1.0
-Laravel-admin: 1.5

### Description:
grid中的actions有编辑和删除，如何优雅的显示数据？用于查看一些不想在表格行中显示的数据。

**Comment by z-song** [comment]
描述清楚一些

**Comment by heimasi** [comment]
@z-song 不好意思没有描述清楚！
就是显示一个类似于编辑数据的表单，但是只用来查看数据，比如有些比较长的文本不希望显示在grid里，通过查看来显示的。是不是都用$form->display()即可？放在哪个函数里面？

**Comment by z-song** [comment]
餐卡 http://laravel-admin.org/demo/users  profile按钮的展开，demo代码在https://github.com/z-song/laravel-admin.org
