### ISSUE TITLE
how to use forceDelete?

### ISSUE THREAD

**Issue by SpinyMan** [z-song/laravel-admin#1440]
- Laravel Version: 5.4
- Laravel-admin: 1.4

### Description:
How to implement trash page and get ability to remove softdeleted records?

**Comment by z-song** [comment]
In your controller, override the `destroy` method from `ModelForm` trait, and use `forceDelete` to remove softdeleted records in `destroy` method.

**Comment by SpinyMan** [comment]
Thanx)
