### ISSUE TITLE
How to access admin after truncating all tables? cannot log out 

### ISSUE THREAD

**Issue by chimmel** [z-song/laravel-admin#1441]
- Laravel Version: 5.5
- PHP Version: 7
- Laravel-admin: ^1.5

### Description:
I reset all migrations and seeded my database but now I need admin role(s) and user(s). I tried making a user with 'administrator' role, then changed its slug to 'admin', but that didn't work; I was able to sign in, but it says 'Permission denied' in the main content area, doesn't show anything and won't even log me out.

**Comment by z-song** [comment]
http://laravel-admin.org/demo/auth/permissions

You should add a permission of all routes (see first row), and assign it to the role which can access all routes.

**Comment by noogen** [comment]
I just started using this and it's pretty simple to reset.  I do it all the time with:

```shell
php artisan migrate:refresh
php artisan db:seed
```

And if you have any other package and you didn't make any modification, you can just do:
```shell
php artisan admin:import helpers

php artisan admin:import media-manager

php artisan admin:import api-tester

php artisan admin:import config

php artisan admin:import scheduling
```

That should repopulate all the routes for all those other packages, run specific one - depending on what you have.

**Comment by chimmel** [comment]
Aw thanks guys, I should've known. I'm sure that'll work.

**Comment by chimmel** [comment]
Hey sorry for the belated reply but this absolutely is not working for me. I try `php artisan admin:import ` anything, I get: 

`[LogicException]
Choice question must have at least 1 choice available.`

This means what...?

**Comment by chimmel** [comment]
And I had already run `migrate:refresh --seed` when I originally opened this issue, that didn't seed any of the admin database tables. How do I do so?

**Comment by chimmel** [comment]
Ok I didn't try hard enough at all so I now found the AdminTablesSeeder, but when I try `db:seed --class=AdminTablesSeeder` I get does not exist. Namespace in the command doesn't fly, tried that, also tried duplicating the file in my seeds directory and running that, as well as renaming said duplicate (class and file name). Nothing has worked.

**Comment by chimmel** [comment]
Sorry I'm slow I see now why the namespacing wouldn't work probably trying to run the package-included seeder: I had to double backslash. Wow \\
