### ISSUE TITLE
SELECT 选择地区的三级联动编辑遇到问题  

### ISSUE THREAD

**Issue by meitesi** [z-song/laravel-admin#1449]
- Laravel Version: 5.5.*
- PHP Version: 7.1.8
- Laravel-admin: 1.5.6

### Description:
创建会员时选择地区是可以创建的，但是在编辑的时候 地区没有默认值。
不知道是怎么回事 你给看一下吗？

### Steps To Reproduce:
```php

   $province=$this->province();
   $form->select('province','省份/直辖市')->options($province)->load('city', '/api/city');
   $form->select('city','市/县')->load('town','/api/town');
   $form->select('town','镇/区');

   public function province()
    {
        return Region::where('type',1)->get()->pluck('name','id')->toArray();
    }
```

**Comment by z-song** [comment]
https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Controllers/UserController.php#L169-L181 

用options方法添加默认选项
