### ISSUE TITLE
请问，一对一对多的关系，是怎么确定关联字段的呢

### ISSUE THREAD

**Issue by magicdiven** [z-song/laravel-admin#1451]
- Laravel Version: 5.5.1
- PHP Version: 7.0
- Laravel-admin: 1.5.*

### Description:
模型关系是怎么确定按按个字段进行关联的呢？这个不了解，用起来不顺手。
@z-song

**Comment by z-song** [comment]
仔细过一遍文档 https://d.laravel-china.org/docs/5.5/eloquent-relationships#defining-relationships
