### ISSUE TITLE
无权限的操作自动隐藏

### ISSUE THREAD

**Issue by songlipeng2003** [z-song/laravel-admin#1453]
### Description:
建议左边的导航和默认的CRUD操作，如果没有权限可以做到自动隐藏，这样可以更好减少不必要点击。

**Comment by rainforyou** [comment]
菜单里不是可以设置吗

**Comment by songlipeng2003** [comment]
菜单是可以的，我是知道的，我是说的更加细颗粒度的，例如有些人可以查看，不能创建，目前创建按钮还是在那里，点了会提示权限不足，最好是直接不显示

**Comment by lxin87** [comment]
文档里有写
http://laravel-admin.org/docs/#/zh/permission?id=%e8%b7%af%e7%94%b1%e6%8e%a7%e5%88%b6

看下场景2  是否符合

**Comment by space-blank** [comment]
请问菜单怎么根据权限隐藏？
