### ISSUE TITLE
NestedForm能否去掉删除和新增btn

### ISSUE THREAD

**Issue by tycallen** [z-song/laravel-admin#1462]
- Laravel Version: 5.5.18
- PHP Version:7.1
- Laravel-admin: up-to-date

### Description:
内嵌的一对多的NestedForm在每条后有删除按钮，整个form后有新增按钮，能否去除，多谢！
![qq 20171202125608](https://user-images.githubusercontent.com/3022000/33511932-3cf77cc4-d760-11e7-976f-1cf736358b47.png)

**Comment by shencm** [comment]
同问，还有能显示成列表方式么

**Comment by pei-lun** [comment]
Duplicate of #1027
