### ISSUE TITLE
How to get the auto-created file name to admin controller? (If file exists)

### ISSUE THREAD

**Issue by Haogood** [z-song/laravel-admin#1465]
- Laravel Version: 5.5.22
- PHP Version: 7.1.9
- Laravel-admin: 1.5.6

### Description:
- How to get the auto-created(unique) name when uploading file?

### Steps To Reproduce:
1. If image file is already existed. (same file name)
2. Laravel-admin will create a new unique file name.
3. In Admin Controller `form()`, I use `getClientOriginalName()`, but still get the original file name, not unique.
4. How to get this unique name and save it to db column when uploading?

Here is code:
```php
    protected function form()
    {
        return Admin::form(Header::class, function (Form $form) {

            $form->image('img', 'PHOTO')->move('path/to/image/');
            $form->hidden('img_small');
            $form->saving(function($form) {
                if ($form->img) {
                    $form->img_small = 'path/to/image/small/' . $form->img->getClientOriginalName();
                    
                    // then save small image
                }
            }

        });
    }
```

**Comment by manren** [comment]
$form->image('img_main', trans('app.img_main'))
                ->move('image/' . date('Ymd'))->uniqueName();
when save this set auto get a unique name   ;don`t need edit saving
Good luck to you.

**Comment by Haogood** [comment]
@manren Thanks for your solution 🤓

But which I want to ask is:
1. First time, upload the image , file name is "photo.jpg"
2. Second time, upload the image, file name is "photo.jpg",  when uploading, the file name is transformed into `path/5exivbsi49ekduq9diwfjwisjdu.jpg` (No need to use `uniqueName()`)
3. I hope to get this return value `path/5exivbsi49ekduq9diwfjwisjdu.jpg`
4. Is this achievable? 😂

**Comment by manren** [comment]
@Haogood why?Talk about the needs？chinese?

**Comment by Haogood** [comment]
@manren 
因為想使上傳的圖片維持原有的檔名，存檔的時候產生縮圖，給縮圖和原圖一樣的檔名
發現上傳相同檔名的圖片會自動產生新檔名，還能將路徑保存到DB
想問問看能不能調回這個"新產生"的檔名，可能太過鑽牛角尖了😂
目前用你提供的方法解決這個問題，謝謝🤓
