### ISSUE TITLE
 Integrity constraint violation: 1048 Column 'url' cannot be null (SQL: update `t_source` set `url` = , `updated_at` = 2017-12-05 04:06:29 where `id` = 1)

### ISSUE THREAD

**Issue by xiaobona0626** [z-song/laravel-admin#1467]
- Laravel Version: 5.5.#
- PHP Version: 7.1.10
- Laravel-admin: 1.5.#

### Description:

数据库设置url 字段不能为空
alter table `table_name`  add column `url` varchar(255) NOT NULL DEFAULT '' COMMENT '网址',

**Comment by manren** [comment]
form code?

**Comment by yang5664** [comment]
alter table table_name add column url varchar(255) NOT NULL DEFAULT '' COMMENT '网址',
```
alter table table_name add column url varchar(255)  NULL DEFAULT '' COMMENT '网址',
```
