### ISSUE TITLE
能否添加一个Admin::view()?

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#1469]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
我想要有个`admin::view()`的功能，以便插入html到页面，因为经常要用到bootstrap的modal功能。
如果已经有了，请提醒一下我怎么使用，谢谢

**Comment by manren** [comment]
`return Admin::content(function (Content $content) {

            $content->header('测试聊天');

            $content->body(view('admin.chat'));
        });`
那些容器本身就是可以传入view('index')这种原生模板的，另外，在表单中是可以使用html()来插入HTML的，在表格中也可以用display来实现HTML的插入；

**Comment by iianpan** [comment]
好的，经过你的提醒，我发现可以插入两个view。
```
return Admin::content(function (Content $content) {

            $content->header('测试聊天');

            $content->body(view('admin.chat'));

            $content->body(view('admin.list'));
});
```

**Comment by manren** [comment]
这里面还可以放容器呢
像这样
```
$content->row(function(Row $row) {
    $row->column(4, 'foo');
    $row->column(8, 'bar');
});
----------------------------------
|foo       |bar                  |
|          |                     |
|          |                     |
|          |                     |
|          |                     |
|          |                     |
----------------------------------
```
