### ISSUE TITLE
表单 密码没有加密，

### ISSUE THREAD

**Issue by jourdon** [z-song/laravel-admin#1471]
- Laravel Version: 5.5.22
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
$form->password('password','密码')->rules('required|confirmed');
 $form->password('password_confirmation','确认密码');
只用一个密码时，提交后密码没有加密，加了确认密码后，确认密码也会入库。会报错数据库没有password_confirmation

**Comment by z-song** [comment]
参考  https://github.com/z-song/laravel-admin/blob/master/src/Controllers/UserController.php#L98-L123
