### ISSUE TITLE
laravel download response not working

### ISSUE THREAD

**Issue by abdou1236** [z-song/laravel-admin#1472]
Hi,
when i use `response()->download($pathToFile, $newName, $headers);` i got this 

![bb](https://user-images.githubusercontent.com/8183194/33796687-f0128094-dcf9-11e7-8b9f-d988eca4fd93.png)

any help please?

**Comment by z-song** [comment]
Use `<a href="path/to/download" target="_blank" >Download</a>` or `<a href="path/to/download" no-pjax>Download</a>`

**Comment by abdou1236** [comment]
Hi sir,
thank you for your response 
I already tried target="_blank"  and it works perfectly .
thanks.
