### ISSUE TITLE
Use of setView on Grid and Form

### ISSUE THREAD

**Issue by amaurycid** [z-song/laravel-admin#1473]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
Proper use of setView is not on the documentation. Could somebody please show me how to properly use this method?

Thanks in advance.

### Steps To Reproduce:
Copied vendor package views to resources/views folder, but using this path on setView method trigers a not found exepcion.

**Comment by z-song** [comment]
Please ref to https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Controllers/ImageController.php#L73

**Comment by amaurycid** [comment]
Thanks, got it working!
