### ISSUE TITLE
disableRefreshButton not working!

### ISSUE THREAD

**Issue by amaurycid** [z-song/laravel-admin#1476]
- Laravel Version: 5.5.24
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
When apply $grid->disableRowSelector() to clear box head and apply a box-tittle, refresh button stays. If I use  $grid->disableRefreshButton(), it doesn't work.

**Comment by yang5664** [comment]
```
            // tools
            $grid->tools(function ($tools) {
                $tools->disableRefreshButton();
            });
```
