### ISSUE TITLE
如何设置rowselector列的宽度？

### ISSUE THREAD

**Issue by heimasi** [z-song/laravel-admin#1481]
- Laravel Version: 5.5.*
- PHP Version: 7.0
- Laravel-admin: 1.5.*

### Description:
如何设置rowselector的宽度？

![rowselector](https://user-images.githubusercontent.com/5692245/33868401-bb167b02-df3d-11e7-9f6f-e6c9b977353f.png)

**Comment by z-song** [comment]
不能设置
