### ISSUE TITLE
The project logo is in COMIC SANS

### ISSUE THREAD

**Issue by Cookizza** [z-song/laravel-admin#1483]
- Laravel Version: 5.5.0
- PHP Version: 7.2
- Laravel-admin: ALL

### Description:
The Laravel-Admin.org logo is written in Comic Sans and that's totally not ok.

### Steps To Reproduce:
Go to Laravel-Admin.org

**Comment by z-song** [comment]
I just googled that this font is totally deprecated

Do you have any recommended fonts?
