### ISSUE TITLE
构造函数内获取当前用户ID失败

### ISSUE THREAD

**Issue by mayday526** [z-song/laravel-admin#1484]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
`
public function __construct()
    {
        parent::__construct();
        dd(Admin::user()->id);
    }
`
错误信息：
"Trying to get property of non-object"

附：
我把`dd(Admin::user()->id);`放到其他方法里是可以成功获取到的

**Comment by z-song** [comment]
https://laravel.com/docs/5.3/upgrade#5.3-session-in-constructors

laravel 5.3之后就不能在constructor里面获取session了, 因为根据Laravel的运行流程，控制器的初始化在 路由应用session中间件之前

你可以这样用
```php
public function __construct()
{
    parent::__construct(); 

    $this->middleware(function ($request, $next) {
        dd(Admin::user()->id);
    });
}
```
