### ISSUE TITLE
The filter button and reset button of a grid are invisible when disabling ID filter

### ISSUE THREAD

**Issue by putuariepra** [z-song/laravel-admin#1486]
- Laravel Version: 5.5.25
- PHP Version: 7.1.11
- Laravel-admin: 1.5

Hey, I use filter on grid as describe here : http://laravel-admin.org/docs/#/en/model-grid-filters
However, when I disable the ID filter and use other fields filter e.g select on category_id. After filtering, the grid runs well but the filter button and reset button on right-top are invisible. 

I have tried not to disable the id filter, then the filter button and reset button are visible. Therefore I conclude that when I disable the id filter, filter button and reset button won't show.
Is that a bug? Or is there something wrong with my code?

Below is my code for the grid:

```
return Admin::grid(Icon::class, function (Grid $grid) {            
            $grid->path("Location);
            $grid->filter(function($filter){
              $filter->disableIdFilter();
              $filter->equal('category_id', "Category")->select(Category::get()->pluck("name", "id")->toArray());
            });
        });
```

**Comment by z-song** [comment]
It's a bug, already fixed in dev branch, update to `1.5.x-dev`

**Comment by putuariepra** [comment]
Ok then, thanks. I'll close this

**Comment by richin13** [comment]
@z-song isn't `1.5.x` compatible only with PHP7+?
