### ISSUE TITLE
使用了多图组件，在删除图片时候，会存在一种假象。

### ISSUE THREAD

**Issue by AaronChengHao** [z-song/laravel-admin#1487]
- Laravel Version: 5.5.*
- PHP Version: php7.1
- Laravel-admin: 1.5.x-dev

### Description:
后台使用了多图上传组件，工作人员在删除图片的时候。如果点击过快，前台显示图片已经删除成功，但是重新刷新页面，就会有几张图片还没删除。 但是如果慢一点删除，两秒删除一张，就不会有这样的情况发生。

**Comment by gystone** [comment]
我也遇到了您说的这个问题，请问您解决了吗？

**Comment by AaronChengHao** [comment]
@gystone  没有。 这个问题很奇怪

**Comment by AaronChengHao** [comment]
没有人回答这个问题么

**Comment by yang5664** [comment]
試著修改 /vendor/encore/laravel-admin/src/Form/Field/MultipleFile.php

<img width="1099" alt="screenshot at dec 20 14-37-31" src="https://user-images.githubusercontent.com/5953010/34194354-5a42cef0-e593-11e7-8162-d991e5887124.png">
