### ISSUE TITLE
挂件的form对象没有saving方法吗？

### ISSUE THREAD

**Issue by AaronChengHao** [z-song/laravel-admin#1488]
- Laravel Version: 5.5.*
- PHP Version:7.1
- Laravel-admin: 1.5.x-dev

### Description:
今天使用了挂件form对象。在业务场景中，需要在保存的时候，提前做一些操作，这时发现挂件的form对象没有saving方法，请问下z-song，有没有可变通的方式实现这样的场景？

**Comment by z-song** [comment]
Widgets只能用来构建前端展示，不处理后端逻辑

你用Widgets/Form，肯定要设置提交的路由，在路由里面做你想做得操作，在保存就好了
