### ISSUE TITLE
Filter and reset button of grid are invisible 

### ISSUE THREAD

**Issue by amaurycid** [z-song/laravel-admin#1489]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5.x-dev

### Description:
Read on a resolved issue that this was a bug, that you already fixed. But, I have latest version and have this bug! Noticed that when I refresh the grid, it shows again.

**Comment by z-song** [comment]
Can you please show your filter code?

**Comment by amaurycid** [comment]
In controller:
            $grid->filter(function($filter){
                $filter->disableIdFilter();
                $filter->like('name', 'Name');
            });
