### ISSUE TITLE
关于修改用户信息 但包含密码的问题

### ISSUE THREAD

**Issue by UpGod** [z-song/laravel-admin#1491]
- Laravel Version: #.#.#
- PHP Version: 7.1
- Laravel-admin: #.#.#

### Description:
[https://github.com/z-song/laravel-admin/blob/master/src/Controllers/UserController.php#L106:1](https://github.com/z-song/laravel-admin/blob/master/src/Controllers/UserController.php#L106:1)
有密码的用户 password是空的 , 但是 确认密码 不为空但是是哈希之后的.
也就是说修改用户信息必须修改密码;
怎么做 才能使当  密码输入不为空时修改密码, 为空时不修改密码?可以不要确认密码项 !

**Comment by jourdon** [comment]
我也遇到这个问题，本来想的是通过编辑时传入的id来判断是否是编辑状态，这样就可以在密码那里选择是否显示，不过感觉比较麻烦，而且获取不到表单提交的数据，也就不能unset掉密码或者其他提交的数据，所以简单的方法就编辑的时候直接把密码显示出来，不改就直接提交，还是原来的密码，改的得话就直接改密码。

**Comment by amaurycid** [comment]
On user model class

From;
   protected $hidden = [
       'password', 'remember_token'
   ];

Change to:
   protected $hidden = [
       'remember_token',
   ];

**Comment by UpGod** [comment]
@jourdon  可是有哈希的啊,你又不知道原始密码,怎么可能显现

**Comment by jourdon** [comment]
@UpGod [看例子吧](https://github.com/z-song/laravel-admin/blob/master/src/Controllers/UserController.php#L98)
