### ISSUE TITLE
如何使用back返回错误信息？

### ISSUE THREAD

**Issue by jianfengye** [z-song/laravel-admin#1492]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
在controller里面back()->withError("这是错误");

在页面上没有显示这个提示，看了下源码，好像错误的模版在vendor/encore/laravel-admin/resources/views/partials/error.blade.php，但是Admin怎么使用上这个模版？

这里back回去的controller就是一个grid的页面

**Comment by jianfengye** [comment]
laravel这边的withError是session中设置errors，而我们这边error.blade.php里面是根据session中error进行显示，我觉得这里有点奇怪啊，这两个为什么不打通？我感觉可以把error.blade.php里面的error修改为errors，然后foreach显示。

**Comment by z-song** [comment]
```php
$error = new MessageBag([
    'title'   => 'title...',
    'message' => 'message....',
]);

return back()->with(compact('error'));
```
admin的error和laravel的error有不一样的结构

**Comment by jianfengye** [comment]
我理解，但是如果我们在controller不是参数错误，是逻辑错误：
`
return Redirect::back()->withInput()->withErrors('城市已经在重跑列表中了');
`
那么这个错误就不会显示出来了。(因为这个错误没有form的key)

我总觉得如果设计form的话，倒不如把form的错误也展示在error的上面，这样能把laravel中的错误信息都统一了

**Comment by z-song** [comment]
当时没考虑到和laravel的错误一起集中处理，只能在以后的版本考虑兼容一下吧

**Comment by wangwenfan** [comment]
怎么自定义跳转呢
