### ISSUE TITLE
文章管理  create 和 edit 页面某些字段显示和隐藏问题

### ISSUE THREAD

**Issue by UpGod** [z-song/laravel-admin#1493]
- Laravel Version: #.#.#
- PHP Version: 7.1
- Laravel-admin: #.#.#

### Description:
 文章有一个作者,
在创建时 , 作者字段不显示,在编辑时显示;
类似ID字段一样,但是我用display时在创建时一样显示;

问题: 怎么让作者字段如同ID一样的存在?创建时不显示,编辑时显示

**Comment by jourdon** [comment]
在 ediit 中给form传入id.
这样的话如果是编辑状态，form里可以接受到id,通过id判断，就可以做你接下来的事情了
