### ISSUE TITLE
php artisan admin:install

### ISSUE THREAD

**Issue by NightravenJames** [z-song/laravel-admin#1496]
`
`

`$ php artisan admin:install

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `username` varchar(190)
  not null, `password` varchar(60) not null, `name` varchar(191) not null, `avatar` varchar(191) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` tim
  estamp null) default character set utf8mb4 collate utf8mb4_unicode_ci)

In Connection.php line 452:

  SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''

`

**Comment by z-song** [comment]
Do you run `php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider"` before admin:install??

**Comment by NightravenJames** [comment]
Yup

**Comment by NightravenJames** [comment]
Repeated the process again works now ... must have been something I missed

**Comment by NightravenJames** [comment]
Run `php artisan config:cache`  to cache the new admin configuration files other wise some variables will turn up empty

**Comment by jayantsr83** [comment]
I have tried all the things but not working in my case. Still showing same error again and again, Do i need to do changes on config/admin.php or it will work without it
