### ISSUE TITLE
Cannot use Illuminate\Database\Eloquent\Model as Model because the name is already in use

### ISSUE THREAD

**Issue by iatanasov77** [z-song/laravel-admin#1497]
- Laravel Version: 5.5.25
- PHP Version: 7.0.7
- Laravel-admin: 1.5.6

### Description:
Cannot use Illuminate\Database\Eloquent\Model as Model because the name is already in use in /vagrant/vendor/encore/laravel-admin/src/Grid/Column.php

**Comment by z-song** [comment]
Show me you code ?

**Comment by ZhangJiaBa** [comment]
我也是这个问题
