### ISSUE TITLE
How to create permission free routes?

### ISSUE THREAD

**Issue by langeuh** [z-song/laravel-admin#1498]
- Laravel Version: 5.5
- PHP Version: 7
- Laravel-admin: 1.5.x

### Description:
Permissions always check url, whilst I thought you had to specify the permision middleware
```php
 $router->group(
            ['middleware' => 'admin.permission:check,xxx'],
            function () use ($router) {
                $router->resource('xxx', 'Controller@action'));
            }
        );

$router->any('xxx/permission-free-url', 'Controler@otherAction')
```

surfing to 'xxx/permission-free-url' still gives me a 'permission denied' warning.

Looking at `Encore\Admin\Middleware\Permission` looks like any route is check for the correct rights, even if there is no middleware linked to it.

I do not want to create a permission for 'xxx/permission-free-url' as this would make no sense, since it's free for every user to use.

Any thoughts? Otherwise there is no point in even attaching `admin.permission:check,xxx` to my routes.

**Comment by amaurycid** [comment]
You should try Route::any() out of scope of $router. Other option would be to declare that route on routes/web.php

**Comment by z-song** [comment]
I just pushed a commit to fix this.

Now you can use this to avoid check url permission: 
```php
 $router->group(
    ['middleware' => 'admin.permission:free'],
    function () use ($router) {
        $router->resource('xxx', 'Controller@action'));
    }
);

//or

$router->get('permission-free-url', 'Controler@otherAction')->middleware('admin.permission:free');
```

Thanks for your advice!

**Comment by z-song** [comment]
The `$permission->shouldPassThrough($request)` logic will be skipped only if the route has a manually assigned middleware

**Comment by langeuh** [comment]
route:
```php
$router->group(
            ['middleware' => 'admin.permission:check,products'],
            function () use ($router) {
                $router->resource('products', 'ProductController'));
        );
```
Permission in db with name `products` and http_path `/produdcts*`


before the change you had to have a permission (name didn't matter) with the http_path `/produdcts*` to make it work.

After this commit you *need* a permission with name `products` which is correct. But changing the http_path to eg `/produdcts-whatever-qsdf*` should give me an acces denied error since the path doesn't match anymore. Yet still it is accessible
