### ISSUE TITLE
找到一个很好地文件上传插件

### ISSUE THREAD

**Issue by ilessy** [z-song/laravel-admin#15]
https://github.com/kartik-v/bootstrap-fileinput
看看如何,或者这个:
http://www.dropzonejs.com/

**Comment by z-song** [comment]
嗯 都蛮好的  我去看看

**Comment by z-song** [comment]
@ilessy 已经把 [bootstrap-fileinput](https://github.com/kartik-v/bootstrap-fileinput)集成进去了
谢谢！

**Comment by ilessy** [comment]
恩太好了
