### ISSUE TITLE
增加人性化的说明

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#150]
vendor/encore/laravel-admin/src/Form/Field.php
···

    protected $help = '';
    public function help($help)
    {
        $this->help = $help;
    }

    protected function variables()
    {
        $this->variables['id'] = $this->id;
        $this->variables['name'] = $this->formatName($this->column);
        $this->variables['value'] = $this->value();
        $this->variables['help'] = $this->help;
        $this->variables['label'] = $this->label;
        $this->variables['column'] = $this->column;
        $this->variables['attributes'] = $this->formatAttributes();

        return $this->variables;
    }
···

vendor/encore/laravel-admin/views/form/text.blade.php:13
···
@if ($help)
增加 bootstrap help block
@endif
···

**Comment by z-song** [comment]
谢谢， 我先看下效果，如果可以的话，可以给所有的field加上这个

**Comment by z-song** [comment]
现在已经给每一个form组件加上了help方法了，谢谢你的idea
