### ISSUE TITLE
关于\Encore\Admin\Widgets\Form的问题

### ISSUE THREAD

**Issue by manren** [z-song/laravel-admin#1502]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.6

### Description:
![image](https://user-images.githubusercontent.com/19370655/34076973-23067a18-e331-11e7-80dd-de7ffcab5545.png)

```
$form = new \Encore\Admin\Widgets\Form();

        $form->action('example');
        $form->color('color');
        $form->date('date');
        $form->select('user','会计师');
        $form->multipleSelect('suborder','子订单');
        return  $form;
```

### Steps To Reproduce:
用这个方法在一个部局中使用了Form组件，不知道为什么多选会在顶部多出来一个
我删掉，表单中和顶部的都会消失

**Comment by z-song** [comment]
放到一个box里面试试看呢
```php
return  new Box('title', $form);
```

**Comment by manren** [comment]
![image](https://user-images.githubusercontent.com/19370655/34078115-a6d4c418-e34e-11e7-9114-6dd14674514c.png)
还是一样的
```
$form = new \Encore\Admin\Widgets\Form();

        $form->action('example');
        $form->color('color');
        $form->date('date');
        $form->select('user','会计师');
        $form->multipleSelect('subooo','子订单');
        return new Box('订单信息', $form);
```
@z-song

**Comment by z-song** [comment]
重现了你的问题，右上角有个元素的class也是user，所以渲染出了两个select，你可以暂时换一下名称：
```
$form->select('user_name','会计师');
```

**Comment by manren** [comment]
多谢~
