### ISSUE TITLE
表单控件的问题

### ISSUE THREAD

**Issue by manren** [z-song/laravel-admin#1503]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.6

### Description:
![image](https://user-images.githubusercontent.com/19370655/34080150-67064bb0-e374-11e7-99e5-4a2f99489942.png)

### Steps To Reproduce:
后台收到的是Array ( [0] => 1 [1] => 2 [2] => )多了一个空白的，这个有办法统一处理掉嘛

**Comment by mtgnorton** [comment]
在encore\laravel-admin\src\Form.php中的prepare函数中过滤一下$this->inputs,
```
function filterNull($arr, $values = [null,'']) {
    foreach ($arr as $k => $v) {
        if (is_array($v) && count($v)>0) {
            $arr[$k] = filterNull($v, $values);
        }
        foreach ($values as $value) {
          if ($value == $v)
             unset($arr[$k]);
        }
    }
    return $arr;
}
```

**Comment by z-song** [comment]
你先在模型里面用修改器处理一下吧

**Comment by mtgnorton** [comment]
@z-song 在encore\laravel-admin\src\Form.php的prepare函数里增加对$this->inputs过滤可以么
```
function filterNull($arr ) {
    foreach ($arr as $k => $v) {
        if (is_array($v) && count($v)>1 ) {

            $arr[$k] = array_filter($v);
        }
    }
    return $arr;
}
```

**Comment by z-song** [comment]
修改Form.php不确定会不会影响到其它的组件，所以保险起见，还是建议在model里面对这个字段设置修改器，来过滤掉空白字符

**Comment by manren** [comment]
@z-song OK,多谢，先这么处理
