### ISSUE TITLE
列标题的样式

### ISSUE THREAD

**Issue by Dianwoung** [z-song/laravel-admin#1504]
- Laravel Version: 5.3.#
- PHP Version: 7.0
- Laravel-admin: 1.3.#

### Description:
Grid的列标题样式无法修改,只能修改列内容的样式,尝试使用了如下方式，发现被自动转义了：
$grid->column('winner',“<span class=\'label label-danger\'>胜利者<\/span>”);

**Comment by z-song** [comment]
没有这个feature(修改列标题的样式)

ps : 如果可以的话建议升级到`Laravel-admin 1.5.*`,  早期的版本已经不维护了
