### ISSUE TITLE
online users

### ISSUE THREAD

**Issue by abdou1236** [z-song/laravel-admin#1505]
Hi sir ,
i want t know who is connected to my laravel-admin (online and offline users ).
how can i do it ? 

thank you

**Comment by z-song** [comment]
Write a script to report their online status by request backend api periodically , and then you know which users are online

Import this script into admin in `app/Admin/bootstrap.php` by add `Admin::js('path/to/your/script.js')`

**Comment by abdou1236** [comment]
ok i will try it thank you sir
