### ISSUE TITLE
$filter->disableIdFilter()有问题

### ISSUE THREAD

**Issue by hongbaotong** [z-song/laravel-admin#1506]
- Laravel Version: 5.5.19
- PHP Version: 7.1.12
- Laravel-admin: 1.5.x-dev

### Description:
`$filter->disableIdFilter();` 会删除掉第一个自定义的过滤字段

### Steps To Reproduce:
```
$filter->disableIdFilter();
$filter->equal('id', '代理商编号');
$filter->like('realname', '真实姓名');
```
屏蔽掉默认ID过滤字段，`$filter->equal('id', '代理商编号');`这个筛选字段也会被屏蔽

**Comment by z-song** [comment]
这个问题已经修复 更新一下版本

**Comment by hongbaotong** [comment]
谢谢
