### ISSUE TITLE
[CI] Route not found

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1507]
I got this error run run CI can you help me a bit 
PHP Fatal error:  Uncaught Error: Class 'Admin' not found in /builds/taimaiduc/cxxxx/app/Admin/routes.php:10
[![https://gyazo.com/788a95f20312b23d548e48b8fff6fb94](https://i.gyazo.com/788a95f20312b23d548e48b8fff6fb94.png)](https://gyazo.com/788a95f20312b23d548e48b8fff6fb94)

**Comment by rap2hpoutre** [comment]
@taimaiduc Did you found a workaround for your problem?

**Comment by geekstek** [comment]
I have the same issue

**Comment by geekstek** [comment]
@taimaiduc @rap2hpoutre OK, Problem Found
I was change the default phpunit.xml and added following code 
```
<logging>
        <log type="coverage-html" target="./tests/_output/coverage" charset="UTF-8"
                                                           yui="true" highlight="true"
                                                           lowUpperBound="50" highLowerBound="80" />
        <log type="testdox-html" target="./tests/_output/testdox.html" charset="UTF-8"
             yui="true" highlight="true"
             lowUpperBound="50" highLowerBound="80" />
    </logging>
```
remove this, problem gone!

**Comment by taimaiduc** [comment]
Just exclude it file LOL
```
<filter>
        <whitelist processUncoveredFilesFromWhitelist="true">
            <exclude>
                <file>./app/Admin/routes.php</file>
            </exclude>
            <directory suffix=".php">./app</directory>
        </whitelist>
    </filter>
```
