### ISSUE TITLE
模型中创建的getFooAttribute方法无法被Laravel-admin调用。

### ISSUE THREAD

**Issue by OranTing** [z-song/laravel-admin#1508]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5.dev

### Description:

User模型里定义了 getPhotoCountAttribute 方法。

在 laravel-admin 里 使用 $grid->column('photo_count','照片数量'); 无法获得对应的数据。

这个应该如何解决呢？

**Comment by z-song** [comment]
模型里面加上：
```php
protected $appends = ['photo_count'];
```
试试看

**Comment by OranTing** [comment]
非常感谢，laravel的基本功没有学扎实。已经搞定，附上laravel的文档
![snip20171219_31](https://user-images.githubusercontent.com/13476576/34163666-4f84696e-e512-11e7-931f-ae35cc02854e.png)
