### ISSUE TITLE
grid一行中如何获取主键ID的值？

### ISSUE THREAD

**Issue by OranTing** [z-song/laravel-admin#1509]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.x

### Description:

![snip20171219_19](https://user-images.githubusercontent.com/13476576/34140382-3ca769de-e4b5-11e7-965a-5e3eda78006b.png)

如图：我想在这个grid的红框处加上链接。
```
$grid->photo('照片')->display(function ($photo) {
                $count = count($photo);
                return "<a href='/admin/photos?user_id=这个主键应该如何获取？'><span class='label label-warning'>{$count}</span></a>";
            });
```

A标签里的user_id应该是这条记录中的主键ID。应该如何获取呢？

### Steps To Reproduce:

**Comment by OranTing** [comment]
如下方法可以解决。

![55c8018c9f68ff4150da7ce6ac091652](https://user-images.githubusercontent.com/13476576/34142241-f1ab7ebe-e4c0-11e7-9092-c1df47f4df1b.jpg)

**Comment by zhangjihan** [comment]
太感谢了，刚好解决问题！
