### ISSUE TITLE
能控制左侧菜单menu吗？

### ISSUE THREAD

**Issue by gantoday** [z-song/laravel-admin#1511]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
希望自己加点逻辑控制左侧菜单的显示，比如我要用户满足某种条件才显示一些选项。请问要怎么操作呢？能控制这个吗？

**Comment by gantoday** [comment]
![image](https://user-images.githubusercontent.com/7780154/34165443-44e6d104-e517-11e7-8ec9-5ef4a48bf841.png)
另外icon表单类型，有些图标不显示，是空白状态。laravel和laravel-admin都是最新版。

**Comment by gantoday** [comment]
再另外，发现所谓的上传到oss是先上传到disk，然后再上传到第三方云存储里。建议加上浏览器端直传第三方云存储的。oss和七牛之类的都支持这种途径。就是先获取上传凭证，然后直接把文件传到第三方，不需要自己服务器中转。如此返回一个地址，保存地址就行了。

很棒的扩展，还在研究学习中。

**Comment by z-song** [comment]
1.menu不能加逻辑控制
2.应该是这个icon三方组件漏了图表
3.你要去找一个使用这种方式上传的laravel adapter

**Comment by gantoday** [comment]
@z-song 这么晚了还有回复，谢谢。
客户端直传，按我理解laravel adapter是不能实现的。

**Comment by z-song** [comment]
那就需要扩展一个前端form组件了

**Comment by gantoday** [comment]
等我学习下自己扩展个。
