### ISSUE TITLE
$filter->between出错

### ISSUE THREAD

**Issue by Lihuzi** [z-song/laravel-admin#1515]
求助：

filter代码如下：

$filter->between('updated_at')->datetime();

筛选时出现如下错误：

 ErrorException In Builder.php line 1060 :
Undefined offset: 0

通过代码查看发现以下问题：

$column => [
    '$gte' => $values[0],
    '$lte' => $values[1],
]

$values的内容实际上是'start'和'end'下标，而并不是0，1；

暂时修改后再次查询但是无法查询到在时间内的结果；
使用的是mongo数据库：
"jenssegers/mongodb": "^3.2"

**Comment by z-song** [comment]
写一个filter继承`Encore\Admin\Grid\Filter\Between`, 然后复写相应的方法，来修改下标，下面是个例子：





类 app/Admin/Extensions/Filter/MongodbBetween.php
```php
<?php

namespace App\Admin\Extensions\Filter;

use Encore\Admin\Grid\Filter\Between;

class MongodbBetween extends Between
{
    public function condition($input)
    {
        if (array_has($input, $this->column)) {
            //用array_values去掉start和end下标
            $this->value = array_values($input[$this->column]);
        }

        return $this->buildCondition($this->column, $this->value);
    }
}
```

然后在grid中使用：
```php
$filter->addFilter(new MongodbBetween('updated_at', '更新时间'))->datetime();
```

**Comment by Lihuzi** [comment]
感谢回复，已按例子方法解决。

**Comment by teg1c** [comment]
最新版本用这种解决办法不可行。

**Comment by bihantan** [comment]
新版本用`$filter->use(new YourFilter)`
