### ISSUE TITLE
如何创建关系查询

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1516]
- Laravel Version: 4.5
- PHP Version:
- Laravel-admin: 1.4

### Description:
$grid->filter(function($filter){}中如何创建关联表的LIKE查询，已对应好关系

### Steps To Reproduce:
```php
$filter->where(function ($query) {
    $query->whereHas('profile', function ($query) {
        $query->where('address', 'like', "%{$this->input}%")->orWhere('email', 'like', "%{$this->input}%");
    });
}, '地址或手机号');
```
上面是官方1.5文档的写法，我照着写报错，我在1.4的文档中好像没有看到，是因为1.4没有嘛？

**Comment by z-song** [comment]
报什么错？

**Comment by imekkk** [comment]
已解决，是我自己写错了，where的第二个参数放错地方了。。。。一层一层的方法。。
