### ISSUE TITLE
表单字段default值报错

### ISSUE THREAD

**Issue by jxlwqq** [z-song/laravel-admin#1517]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.7

### Description:
表单字段问题。
这是我表单中的一个字段，设置了默认值：
```php
$form->text('mobile', '手机')->default('');
```
对应的mysql字段的数字类型是这样的：
```mysql
  mobile VARCHAR(255) DEFAULT '' NOT NULL COMMENT '手机',
```
当提交表单时，会报以下错误：
```myqsl
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'mobile' cannot be null (SQL: update `team` set `position` = dede, `mobile` = , `updated_at` = 2017-12-21 13:18:23 where `id` = 1)
```
这个字段我已经设置了default值了，为啥还是会报错？？

**Comment by jxlwqq** [comment]
源码是不是用了 ==null，而不是 ===null 做判断了？

**Comment by z-song** [comment]
在`app/Http/Kernel.php` 里面有个中间件`ConvertEmptyStringsToNull` 会把request中所有的空字符串转换成null，要么去掉这个中间件，要么修改数据库
