### ISSUE TITLE
菜单问题

### ISSUE THREAD

**Issue by RealZark** [z-song/laravel-admin#1518]
- Laravel Version: 5.5.25
- PHP Version: 7.1.7
- Laravel-admin: 1.5.7

Description:
 后台创建菜单之后再删除的话，`admin_menu` 数据表中的记录删除了，但是 `admin_role_menu` 数据表未同步删除记录。

**Comment by z-song** [comment]
是的，其它几张表也存在这个问题，谢谢指出，晚点时候修复

**Comment by z-song** [comment]
已修复
