### ISSUE TITLE
请问一下 grid里面的switch操作 是否更新到数据库 如果更新到数据库 应该注意什么

### ISSUE THREAD

**Issue by CherishNA** [z-song/laravel-admin#1519]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
请问一下 grid里面的switch操作 是否更新到数据库 如果更新到数据库 应该注意什么
我现在在列上使用了switch方法 但是数据并不会更新到数据库

**Comment by CherishNA** [comment]
Laravel Version: 5.5
PHP Version:7+
Laravel-admin: 5.5

**Comment by CherishNA** [comment]
`  $form->switch('sign_status')->states($states);`
`   $grid->sign_status('签到状态')->display(function ($pay_status) {
                return $pay_status == 0 ? '未签到' : '已签到';
            })->switch($states);`

**Comment by CherishNA** [comment]
请问我想在grid里面更新我的签到状态 并不是在form里更新  请问是不是不在form里面更新 grid就不更新？

**Comment by z-song** [comment]
grid上面的更新，都是通过form里面设置的相关组件来实现的

**Comment by CherishNA** [comment]
好的 谢谢提醒 我自己弄一下

**Comment by CherishNA** [comment]
已解决 谢谢大佬
