### ISSUE TITLE
GRIDl里的编辑和删除按钮如何根据该行记录的某个字段状态 显示或隐藏呢？

### ISSUE THREAD

**Issue by cashhaha** [z-song/laravel-admin#1522]
- Laravel Version: 5.4
- PHP Version:7.0.2
- Laravel-admin: 1.4

Description:

想实现一个根据GRIDl里的每行记录的一个状态字段的值，隐藏或者显示 actions里的编辑和删除按钮
请教各位大大

**Comment by z-song** [comment]
http://laravel-admin.org/docs/#/zh/model-grid-actions
