### ISSUE TITLE
Is there a way to hide navigations which user don't have permissions for?

### ISSUE THREAD

**Issue by mhetreramesh** [z-song/laravel-admin#1523]
Instead of showing all navigation on the left side, do we have any way to hide navigations which user don't have permissions for?

**Comment by z-song** [comment]
You can assign roles to menus so that only the user with those roles can see the menu on the left side.

http://laravel-admin.org/demo/auth/menu

**Comment by mhetreramesh** [comment]
Wow! Worked like this. Amazing. Thanks 👍  😄
