### ISSUE TITLE
Is it slow for everyone?

### ISSUE THREAD

**Issue by mhetreramesh** [z-song/laravel-admin#1524]
It works like a charm, a very neat, clean way to write code.

I feel like it is a bit slow, not sure whether it is only for me. I'm using different docker containers for nginx, PHP & Mysql. Just wanted to check if someone already facing the same thing?

Thanks

**Comment by wslsq** [comment]
in no shape  : )

**Comment by mhetreramesh** [comment]
Okay, may be something from my end. I'll check! Thanks.

**Comment by harrett** [comment]
For the benefit of anyone else that stumbles on this question via Google, Docker for Mac now supports user guided caching for volumes.

Different applications require different levels of consistency. Full consistency is sometimes essential, and remains the default. However, to support cases where temporary inconsistency is an acceptable price to pay for improved performance, Docker 17.04 CE Edge includes new flags for the -v option:

consistent: Full consistency. The container runtime and the host maintain an identical view of the mount at all times. This is the default, as described above.
cached: The host’s view of the mount is authoritative. There may be delays before updates made on the host are visible within a container.
Enabling cached mode for my Laravel app was as simple as updating the volume references in docker-compose.yml.

Before:

    volumes:
        - ./:/var/www
After:

    volumes:
        - ./:/var/www:cached
Having made that change and recreated my containers I’m seeing performance that much more closely matches what I’d expect from non-virtualised local server. Previously a simple request was taking 1.3s to complete and that’s dropped to 0.35s. Despite the warning that host changes may not immediately be visible in the container I’ve yet to notice any issues with propagation.

There’s also an ongoing GH issue about Docker Mac FS performance with some useful notes.

[https://stackoverflow.com/questions/35305230/slow-response-times-laravel-5-2-in-docker-container](url)

**Comment by harrett** [comment]
Another optimization method:

[https://www.jianshu.com/p/b7c12a824044?from=groupmessage](url)
