### ISSUE TITLE
alert的特效 如何显示？

### ISSUE THREAD

**Issue by cashhaha** [z-song/laravel-admin#1525]
- Laravel Version: 5.4
- PHP Version:7.0.2
- Laravel-admin: 1.5

### Description:
![image](https://user-images.githubusercontent.com/4607725/34288333-9c93029e-e727-11e7-86b3-00e69e667e84.png)

这种如何实现

**Comment by z-song** [comment]
http://laravel-admin.org/docs/#/zh/content-layout

把上面的alert下写在blade视图里, 然后用`$content->body(view('xxx'));`引用
