### ISSUE TITLE
Filter 冲突问题

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1526]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:
我的表中有个发票的字段invoice，当我写筛选的时候，好像跟自带的css冲突了，然后我的样式就整个就改变掉了

### Steps To Reproduce:
$filter->is('invoice','发票')->select([0=>'未送达',1=>'已送达']);//不知道有没有什么方法可以处理一下，还我必须要改字段名？
$filter->is('settle','结算')->select([0=>'未结算',1=>'已结算']);
$filter->useModal();

**Comment by z-song** [comment]
打开`vendor/laravel-admin/laravel-admin/laravel-admin.css`给这个select加个样式 覆盖掉系统的样式
