### ISSUE TITLE
filter的select有默认空值,但不能选择空值

### ISSUE THREAD

**Issue by carlclone** [z-song/laravel-admin#1530]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.6

### Description:
filter/select.blade.php
select组件会把`<option></option>`和`<option value=""></option>`从选项中过滤 , 改为` <option value=" "></option>`即可 ,  前面那个在选项中不显眼,加个内容`<option value=" ">Empty</option>`

给作者的改进建议, 辛苦了

**Comment by wslsq** [comment]
![qq 20171225180250](https://user-images.githubusercontent.com/12254744/34337856-fe75d752-e99d-11e7-8a9d-75eecc69f07a.png)
同问如何选择空值（全部选项），目前空值不会显示出来，谢谢
