### ISSUE TITLE
Laravel原生页面JS初始化问题

### ISSUE THREAD

**Issue by manren** [z-song/laravel-admin#1531]
- Laravel Version: 5.5.#
- PHP Version:7.1
- Laravel-admin: 1.5.6

### Description:
```
<script src="/backend/chat/admin/chat.js"></script>
<script data-exec-on-popstate>
    $(function(){
        adminchat.init();
    });
</script>
```

### Steps To Reproduce:
这里面adminchat是在chat里弄的，但是下边的并不会等chat.js里面加载完了才运行的感觉，这样点击菜单跳到这个页的时候就会报adminchat找不到，刷新是没问题的，有没有比较优雅的方法解决这个问题

**Comment by z-song** [comment]
js引用在`app/Admin/bootstrap.php`中

初始化脚本用`Admin::script('adminchat.init();')`, 加在当前的页面里

**Comment by manren** [comment]
@z-song 好的，多谢~~
