### ISSUE TITLE
Password is not secured in v1.5.* working fine in v1.4.*

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#1532]
- Laravel Version: 5.5
- PHP Version: 7
- Laravel-admin: 1.5.7

### Description:
Password saving is working fine in v1.4.* if password is empty no change:
![password_1 4](https://user-images.githubusercontent.com/24757934/34329744-fc8d392c-e8d9-11e7-8a9d-fbacb0fc1e79.png)

But it's not working in the same way in v1.5.* we have to add password in the value which is not secure anyone can see the password in the view source.
![password_1 5](https://user-images.githubusercontent.com/24757934/34329760-556c8d68-e8da-11e7-9d68-05f725a9f36a.png)

**Comment by pcfjojo** [comment]
I also have the same problem
