### ISSUE TITLE
关于API验证用户的问题

### ISSUE THREAD

**Issue by kingsollyu** [z-song/laravel-admin#1535]
- Laravel Version: 1.5
- PHP Version: 7.1
- Laravel-admin: 1.5.dev

### Description:
我在`routes/api.php`里添加里一个API接口
```
Route::middleware('auth:api')->get('/upload/package', 'Api\Upload@package');
```
我想知道这个请求API的URL路径应该是一个怎么样的？我测试里很多都没有办法正确的访问，看demo代码也没有看出来个所以然，请大佬解答，麻烦了。

**Comment by z-song** [comment]
用命令`php artisan route:list`来找到这个路由的访问url

**Comment by kingsollyu** [comment]
刚才看了一下，是不是laravel-admin不支持使用api方式进行登陆？这个`Route::middleware('auth:api')`是larvael中的功能？

**Comment by z-song** [comment]
没明白你的意思

**Comment by kingsollyu** [comment]
其实我想实现的功能很简单，就是有一个`'domain.com/api/upload/package'`接口，这个接口是有登陆验证的。

**Comment by kingsollyu** [comment]
或者说我怎么样通过这个session来验证登陆？
![7_46e5z yd483is _yd1 ya](https://user-images.githubusercontent.com/5027735/34348222-1b53cc70-ea44-11e7-96db-03882f3d4a3f.jpg)
