### ISSUE TITLE
form如何嵌入一个table

### ISSUE THREAD

**Issue by cashhaha** [z-song/laravel-admin#1536]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:

![image](https://user-images.githubusercontent.com/4607725/34346912-f8c3957a-ea37-11e7-9e6e-2759baa74ccb.png)

想在form里面嵌入一个table，请问如何实现

**Comment by z-song** [comment]
`$form->html('<table>xxxx</table>');`

**Comment by cashhaha** [comment]
Widgets里的table

**Comment by z-song** [comment]
一样的啊
`$form->html(new \Encore\Admin\Widgets\Table());`

**Comment by cashhaha** [comment]
万分感谢
