### ISSUE TITLE
session中保存的payload的内容求解

### ISSUE THREAD

**Issue by kingsollyu** [z-song/laravel-admin#1538]
- Laravel Version: 1.5
- PHP Version:7.1
- Laravel-admin: 1.5.dev

### Description:
我想问一下session中保存的payload的内容，我这里查看如下：
```
        "payload": {
            "_token": "De2PyBrpuu7g05eu7RL9PQmCmaqvsxrFNdEfNIEQ",
            "url": [],
            "_previous": {
                "url": "http://appenv.sollyu.com"
            },
            "_flash": {
                "old": [],
                "new": []
            },
            "login_admin_59ba36addc2b2f9401580f014c7f58ea4e30989d": 1
        }
```
我想问一下其中的`login_admin_59ba36addc2b2f9401580f014c7f58ea4e30989d`是怎么生成的？
以及`_token`是怎么样对应的`UserId`的。

**Comment by z-song** [comment]
你想做什么？

**Comment by kingsollyu** [comment]
真的很简单啊，就是一个api接口，返回json的那种，里面有登陆验证，获取调用这个接口的用户信息。就这样。

**Comment by z-song** [comment]
你的路由应用这个中间件 `admin.auth`

**Comment by kingsollyu** [comment]
```
Route::middleware('admin:auth')->get('/upload/package', 'Api\AppEnv@uploadPackage');
```
这句话是写在`routes/api.php`还是写在`app/Admin/routes.php`里？

**Comment by kingsollyu** [comment]
@z-song 对不起，我智障了，直接在`app/Admin/Controllers`写正常的function就行了，我智障了。
