### ISSUE TITLE
文件和图片上传的文件名能不能自定义，或者采用md5_file的方式命名

### ISSUE THREAD

**Issue by imlida** [z-song/laravel-admin#154]
文件和图片上传保存的文件名能不能自定义，或者采用md5_file的方式命名？建议优化一下

**Comment by z-song** [comment]
@imlida 
```php

$form->image('picture')->move(null, 'xxxxx.jpg');

```

**Comment by imlida** [comment]
厉害了，谢谢，我试试

**Comment by imlida** [comment]
$form->image('picture')->move(null, 'xxxxx.jpg'); 这个如何知道原始上传文件的后缀？

**Comment by imlida** [comment]
是否可以这样用？$form->image('picture')->move(null, function($原始路径){
      return md5_file($原始路径).get_extension($原始路径) ;
});

**Comment by z-song** [comment]
目前还不支持这样，等我修改好了再通知你

**Comment by imlida** [comment]
好的，谢谢

**Comment by z-song** [comment]
代码提交了，使用：
```php
// 直接 md5()
$form->image('picture')->uniqueName();

// or
$form->image('picture')->name(function ($file) {
    return 'test.'.$file->guessExtension();
});
```

**Comment by cokyhe** [comment]
所有图片都叫test明显不现实，$form->image('picture')->name(function ($file) {
    return $newName.'.'.$file->guessExtension();
});
这里的$newName变量，无法传递啊

**Comment by hldh214** [comment]
> 所有图片都叫test明显不现实，$form->image('picture')->name(function ($file) {
> return $newName.'.'.$file->guessExtension();
> });
> 这里的$newName变量，无法传递啊

`use ($newName)`
