### ISSUE TITLE
数据库创建特殊字符过长问题

### ISSUE THREAD

**Issue by StringKe** [z-song/laravel-admin#1541]
laravel 5.4 改变了默认的数据库字符集，现在utf8mb4包括存储emojis支持。如果你运行MySQL v5.7.7或者更高版本，则不需要做任何事情。

当你试着在一些MariaDB或者一些老版本的的MySQL上运行 migrations 命令时，你可能会碰到下面这个错误：

```shell
D:\wwwroot\www.test.com>php artisan admin:install
Migration table created successfully.

In Connection.php line 664:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes (S
  QL: alter table `users` add unique `users_email_unique`(`email`))


In Connection.php line 458:

  SQLSTATE[42000]: Syntax error or access violation: 1071 Specified key was too long; max key length is 1000 bytes
```
在app\Providers\AppServiceProvider.php添加默认值
```php
<?php

namespace App\Providers;

use Illuminate\Support\ServiceProvider;
use Illuminate\Support\Facades\Schema; //add fixed sql

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Schema::defaultStringLength(191); //add fixed sql
    }

    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }
}

```

**Comment by jianfengye** [comment]
这个问题是laravel的问题，我建议在这个组件的wiki文档里面也带上这么个说明，能让第一次安装的人避开这个问题

**Comment by zjairing** [comment]
遇到这个问题，根据这个帖子的方法操作后，然后需要删除已经生成的两张数据表，才能php artisan admin:install重新进行

**Comment by zhangpeng233** [comment]
Illuminate\Database\QueryException  : SQLSTATE[HY000] [2002] Connection refused (SQL: select * from information_schema.tables where table_schema = mysql and table_name = migrations and table_type = 'BASE TABLE')

  at /wwwroot/weixin1905/vendor/laravel/framework/src/Illuminate/Database/Connection.php:665
    661|         // If an exception occurs when attempting to run a query, we'll format the error
    662|         // message to include the bindings with SQL, which will make this exception a
    663|         // lot more helpful to the developer instead of just the database's errors.
    664|         catch (Exception $e) {
  > 665|             throw new QueryException(
    666|                 $query, $this->prepareBindings($bindings), $e
    667|             );
    668|         }
    669| 

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /wwwroot/weixin1905/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:31

  2   PDOException::("SQLSTATE[HY000] [2002] Connection refused")
      /wwwroot/weixin1905/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:27

  Please use the argument -v to see more details.

**Comment by zhangpeng233** [comment]
asdads

**Comment by 1349859051** [comment]
有生成表吗？库吗？没看见啊

**Comment by xin6841414** [comment]
> 有生成表吗？库吗？没看见啊

有 migrate表已经生成，user表也有了，

**Comment by Liuck** [comment]
按照教程，正解

**Comment by GitCZH** [comment]
或者指定mysql数据库引擎默认为InnoDB。

**Comment by wangerzi** [comment]
踩到这个坑里了，不过 email 设置为 255 的长度加上唯一索引，其索引效率是不是不太高，比如单个数据分页、redo日志页存放的数据数量，Buffer缓冲区可存放的页之类的都有些影响，我这边是暂时改为 100 解决掉了。

**Comment by woshixiaobaitv** [comment]
如果楼主介绍的方法还不行可以尝试使用如下两个方法
一，在laravel配置文件中
`
//  config/database.php
'mysql' => [
		...
		'engine' => 'InnoDB',
		...
]

`
二，在 mysql配置文件 my.ini中（注意存盘重启）
`
//在mysql的配置文件my.ini中设置
default-storage-engine=InnoDB
innodb-default-row-format=dynamic
//restart
`

**Comment by zjairing** [comment]
本人被信砸到...俺会抓紧时间砸回去的．　　
 
 
　恩．．．．thank  you  for your letter ~恩哼　．．．

**Comment by sl138** [comment]
en.... thank you for your letter ~en ...

**Comment by zjairing** [comment]
本人被信砸到...俺会抓紧时间砸回去的．　　
 
 
　恩．．．．thank  you  for your letter ~恩哼　．．．
