### ISSUE TITLE
Form编辑表单内 如何获取字段的值？

### ISSUE THREAD

**Issue by cashhaha** [z-song/laravel-admin#1542]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:

如何在编辑表单里获取到id，现通过 request()->route()->parameters() 获取，不知道还有更便捷的方式，另外还想获取这条ID对应记录的其他值，除了用id再取一次，还有其他方法吗，请大大不吝指教下！万分感谢

**Comment by yang5664** [comment]
有試過？
```
request()->input('你的欄位名')  
```

**Comment by z-song** [comment]
从update方法里面把id传进来

**Comment by sdauma** [comment]
@z-song @yang5664  request()->input('你的欄位名') 不行，$form->model()->id也不行。 “update方法里面把id传进来”不明白啊，能给举个例子吗？

**Comment by yang5664** [comment]
提供我使用的案例給你參考
![screen shot 2018-01-14 at 11 05 54 am](https://user-images.githubusercontent.com/5953010/34912408-cab96b80-f91b-11e7-8c53-bdfcf2ce236e.png)

**Comment by sdauma** [comment]
@yang5664 谢谢！

**Comment by xialamp** [comment]
我试了，没成功,不知道什么原因

**Comment by xialamp** [comment]
request()->route()->parameters() 这种方式有没有办法获取其他字段值?
