### ISSUE TITLE
新增html页面文章,操作日志保存不下,报错!

### ISSUE THREAD

**Issue by UpGod** [z-song/laravel-admin#1544]
- Laravel Version: #.#.#
- PHP Version: 7.1 
- Laravel-admin: #.#.# 最新

### Description:
 字段过长,操作日志表保存不下.
 如何屏蔽部分操作不保存入日志?

**Comment by Zero0719** [comment]
同问，我也刚好遇到这个问题。
我是在编辑器中上传了图片，操作日志就报错

**Comment by z-song** [comment]
打开`config/admin.php` 找到operation_log.except, 照注释 去掉不需要记录log的路由

**Comment by UpGod** [comment]
那如何解决editor的图片上传,转码的数据太大的问题呢? @z-song
