### ISSUE TITLE
API tester 没有显示在 api.php 文件中添加的 api 信息

### ISSUE THREAD

**Issue by Zero0719** [z-song/laravel-admin#1546]
- Laravel Version: 5.5.26
- PHP Version:7.1
- Laravel-admin: 1.5

Description:
按照文档 API tester 章节的内容去操作，但是在 api-tester 页面上并没有看到我在 api.php 文件中添加的api 地址，是我哪里操作少了吗？
![image](https://user-images.githubusercontent.com/23370253/34399424-50e6dc4a-ebc2-11e7-9d16-68d5b061f1d8.png)

![image](https://user-images.githubusercontent.com/23370253/34399432-61c45ff6-ebc2-11e7-9406-4384e8428d3c.png)

**Comment by z-song** [comment]
你这些api的访问url是什么？

**Comment by Zero0719** [comment]
@z-song 
![image](https://user-images.githubusercontent.com/23370253/34432981-f6955b40-ecb6-11e7-8057-fab92c89ac7c.png)
这个 api 我访问的是 http://happycoding.local/api/test ， 可以正常访问拿到 hello world，但是就是那个API tester 页面没有出来这个 api

**Comment by diy3344** [comment]
config/admin.php里加
 'extensions' => [
        'api-tester' => [
            // route prefix for APIs
            'prefix' => 'api',
            // auth guard for api
            'guard'  => 'api',
            // If you are not using the default user model as the authentication model, set it up
            'user_retriever' => function ($id) {
                return \App\User::find($id);
            },
        ]
    ],

**Comment by SoulMate94** [comment]
我也是遇到了这个问题,加了配置还是报404错误,求解??

**Comment by bthiban** [comment]
Please add this to the main documentation for API TESTER.

Config/admin.php Riga

 'extensions' => [
        'api-tester' => [
            // route prefix for APIs
            'prefix' => 'api',
            // auth guard for api
            'guard'  => 'api',
            // If you are not using the default user model as the authentication model, set it up
            'user_retriever' => function ($id) {
                return \App\User::find($id);
            },
        ]
    ],
