### ISSUE TITLE
always Permission denied 1.5

### ISSUE THREAD

**Issue by kevincobain2000** [z-song/laravel-admin#1547]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5.7

### Description:

I am trying to upgrade from 1.5.4 to 1.5.5. (as I have updated Laravel version from 5.4 -> 5.5
It always comes up with Permission denied after logging in to admin.

**Comment by z-song** [comment]
Check your login user role's permissions

Or try  a fresh install

**Comment by kevincobain2000** [comment]
worked thanks
