### ISSUE TITLE
a链接是否可以多一个选择不使用pjax？

### ISSUE THREAD

**Issue by jianfengye** [z-song/laravel-admin#1549]
- Laravel Version: 5.3
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
z-song 大：

讨论一个问题

我现在想在某个页面引入vue组件来实现一些功能。

发现所有的a链接都使用了pjax，很多时候一些js就必须写在blade里面，甚至只希望某个页面引用的外部链接，或者希望引入vue来实现某个组件也变得很麻烦了。

感觉应该在a标签的地方做个口子，比如包含有pjax="disable"的标记的链接不使用pjax。
然后在menu的数据库加一个选择项，是否重新加载整个页面，默认不重新加载整个页面。

这种方式是我找到某个链接不使用pjax最好的方法了，不知道是不是还有其他方法能引入vue组件。
是不是还有其他实现方式？如果没有的话，我就这样修改了，然后提交一个pull request。

**Comment by z-song** [comment]
用这个 `<a href='xxxx' no-pjax>link</a>`

**Comment by jianfengye** [comment]
谢谢哈，那如果是sidebar的link要使用no-pjax如何做呢

**Comment by z-song** [comment]
你就填完整的url

**Comment by jianfengye** [comment]
尝试了：
1 给a标签增加no-pjax没有效果
2 填写完整的url，就会打开一个新的页面

**Comment by ChitaGideon** [comment]
#1278 

禁用单个
