### ISSUE TITLE
Back end panel is not responsive or mobile friendly? AdminLTE is responsive

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#1552]
AdminLTE original theme is mobile friendly:
https://adminlte.io/themes/AdminLTE/pages/tables/data.html

laravel-admin is is not responsive specially grid view:
![2017-12-29_0145](https://user-images.githubusercontent.com/24757934/34431108-0e1d9124-ec3a-11e7-978b-ed338de2dc5e.png)

**Comment by NickCoolii** [comment]
@smuzammilali what do you mean?
In laravel-admin we have scroll bar, and in AdminLTE I'm don't see it at all (with data info loss):
![default](https://user-images.githubusercontent.com/16125559/35009035-872923ba-fb0f-11e7-8f04-b928b6778a73.png)

![default](https://user-images.githubusercontent.com/16125559/35009063-9c973980-fb0f-11e7-8002-349a9afd4bc9.png)
