### ISSUE TITLE
[solved] PUT from grid: changing all phones values to empty string

### ISSUE THREAD

**Issue by NickCoolii** [z-song/laravel-admin#1555]
- Laravel Version: 5.5.26
- PHP Version: 7.0.21
- Laravel-admin: 1.5.7

### Description:
When i'm updating any value from grid (through editable) all phones (phone_1, phone_2, phone_3) updates to empty string, if they are not empty already.
request:
![request](https://user-images.githubusercontent.com/16125559/34442808-bb2a7008-ecd5-11e7-96c1-c7d9b8949473.png)
queries 1:
![queries](https://user-images.githubusercontent.com/16125559/34442811-c41dc8f4-ecd5-11e7-9a5a-7c4a2b8993df.png)
queries 2:
![queries 2](https://user-images.githubusercontent.com/16125559/34442820-ccc75ccc-ecd5-11e7-8feb-66b51902d7c8.png)
db schema:
![blueprint](https://user-images.githubusercontent.com/16125559/34442826-d934c224-ecd5-11e7-8783-ff10c4f511d0.png)
grid:
![grid](https://user-images.githubusercontent.com/16125559/34442828-dfa46664-ecd5-11e7-92e4-5b97e7f128d7.png)

Also tried change in db scheme replace "default('')" with "nullable()". No effect.

Any suggestions?
Thanks in advance.

UPD:
found source of my problem.
That's was my $form->saving() effect from form() function in this controller:
![laravel-5 5_laravel_admin-1 5 - d__work_php_mydev_laravel_laravel-5 5_laravel_admin-1 5 - _app_admin_controllers_recordcontroller php - phpstorm 2016 2 1 2017-12-29 20 38 16](https://user-images.githubusercontent.com/16125559/34443374-65548efe-ecd8-11e7-8495-d70ab6432cd0.png)

P.S.:
Is it a good solution?
![laravel-5 5_laravel_admin-1 5 - d__work_php_mydev_laravel_laravel-5 5_laravel_admin-1 5 - _app_admin_controllers_recordcontroller php - phpstorm 2016 2 1 2017-12-29 20 42 46](https://user-images.githubusercontent.com/16125559/34443541-ee09266a-ecd8-11e7-949a-eff44e0bd858.png)

**Comment by LanKing** [comment]
Hi!
How to get ID in saving function?

**Comment by LanKing** [comment]
@NickCoolii, Привет! Напиши плз свой контакт в целях обмена опытом )
