### ISSUE TITLE
不同角色顯示不同菜單的問題

### ISSUE THREAD

**Issue by geekstek** [z-song/laravel-admin#1557]
- Laravel Version: 5.5.28
- PHP Version: 7.1
- Laravel-admin: 1.5.*

### Description:
有沒有可能讓不同角色的人群顯示不同的菜單
比如： 我的Laravel-admin 安裝了laravel backup 和 helpers, import 後菜單會有顯示，但我不想會員看到這些菜單，可以怎樣做呢？謝謝

**Comment by z-song** [comment]
编辑菜单 选择可以看见这个菜单的role即可
