### ISSUE TITLE
自定义js问题

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1558]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:
根据文档，Admin::css('path/to/your/js'); 这样可以导入自己的js，不过这样好像是所有页面都有的，如果我需要在单个页面使用js，是我自己在页面中导入一下嘛？

**Comment by z-song** [comment]
全局导入css
`Admin::css('path/to/your/css');`

全局导入js
`Admin::css('path/to/your/js');`

 单页面导入js，在当前页面加入
`Admin::script('console.log("xxxx");');
