### ISSUE TITLE
想直接用本包的用户权限系统作为前端API的鉴权

### ISSUE THREAD

**Issue by felixjing** [z-song/laravel-admin#1559]
- Laravel Version: 5.5
- PHP Version:7
- Laravel-admin:1.5.x

### Description:
一个前后端分离项目，不想用laravel默认的用户模型新建RABC，想直接用本包的用户权限系统作为前端API的用户登录，权限管理等，不知道支不支持。

**Comment by z-song** [comment]
后台的权限中间件是`admin:auth` => `vendor/encore/laravel-admin/src/Middleware/Authenticate.php`

你的api使用这个中间件，就能共用后台的权限系统
