### ISSUE TITLE
请问选择条数的这部分，有提供不让它显示的方法吗

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#156]
![image](https://cloud.githubusercontent.com/assets/7192860/20780724/389f6114-b7b8-11e6-9139-b67d4dd9f37c.png)

现在不想使用着一块，有去除的方法吗

**Comment by z-song** [comment]
这个和分页一样是列表的默认功能，不能去掉，使用上有什么问题吗？

**Comment by xyz8772232** [comment]
我在自定义一些页面，关闭了pjax，这一块和pjax有关联，所以暂时不想展示出来

**Comment by z-song** [comment]
@xyz8772232 
```php
$grid->perPages([]);
```
这个办法能避免你的问题，但是不能去掉显示。

**Comment by xyz8772232** [comment]
好的，谢谢
