### ISSUE TITLE
How can I select value from URL query

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#1560]
- Laravel Version: 5.4.*
- PHP Version: >= 5.6.4
- Laravel-admin: 1.4.*
### Description:
I have a list options like this:
$opt = [1=> 'foo', 2=>'bar', 3=>'something']

I tried to used in form:
$form->select( 'type', 'Type' )->options( [1=> 'foo', 2=>'bar', 3=>'something'] );

When I call http://localhost:8000/admin/book/create?type=2 <== type: 1 | 2 | 3, 
I got the value from URL selectedOption = request()->get('type) ==> 2
I need the select input has chosen number 2 value after the form is loaded.

**Comment by z-song** [comment]
try:
```php
$form->select( 'type', 'Type' )->options( [1=> 'foo', 2=>'bar', 3=>'something'] )->default(request()->get('type));
```
