### ISSUE TITLE
左侧菜单栏怎么默认展开?

### ISSUE THREAD

**Issue by UpGod** [z-song/laravel-admin#1561]
左侧菜单栏怎么默认展开?就是宽的那个模式,现在是默认小图标模式.

**Comment by z-song** [comment]
打开`config/admin.php`，修改`layout`,  去掉`sidebar-mini`

**Comment by UpGod** [comment]
@z-song 去掉直接就完全隐藏了,只有点击才显示

**Comment by UpGod** [comment]
我用的1.5.x-dev版本,然后去掉后,菜单栏完全没有

**Comment by z-song** [comment]
说错了，去掉`sidebar-collapse`,留下`sidebar-mini`

**Comment by 469346971** [comment]
3q！
