### ISSUE TITLE
跟着官方文档一步步走 在php artisan admin:install命令的时候，提示 There are no commands defined in the "admin" namespace.

### ISSUE THREAD

**Issue by dogelin** [z-song/laravel-admin#1564]
Laravel Version: 5.5
PHP Version:7.0
Laravel-admin: 1.5.*
Description:
跟着官方文档一步步走
在php artisan admin:install命令的时候，提示我
There are no commands defined in the "admin" namespace.
不知道为什么，百度搜了没找到相同的问题，求大神指导

Steps To Reproduce:
第一步：composer require encore/laravel-admin "1.5.*"正确
第二步：php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider" 正确Publishing complete.
第三步：php artisan admin:install 错误提示There are no commands defined in the "admin" namespace.
 

不好意思打扰了

**Comment by xinhaonaner** [comment]
截图 看看 你的　`php artisan`　有没有admin

**Comment by dogelin** [comment]
@xinhaonaner php artisan命令里面并没有admin的命令

**Comment by z-song** [comment]
那就是没安装成功

**Comment by dogelin** [comment]
@z-song 我也知道是没安装成功，可我不知道是哪个步骤错误了，望大神指导

**Comment by dogelin** [comment]
谢谢，虽然不知道原因，重新创建了个laravel项目，然后一样的步骤成功安装，可能是之前的项目composer有冲突或者有什么文件错误吧，谢谢打扰了

**Comment by fg607** [comment]
@dogelin 我运行composer update后就可以了

**Comment by mohitpawar10** [comment]
Yes. There is issue with repository not with the package. I encountered the same issue.
