### ISSUE TITLE
$grid->disableCreation() still allows create through URL

### ISSUE THREAD

**Issue by Romerski** [z-song/laravel-admin#1565]
- Laravel Version: 5.5
- PHP Version: 7.0
- Laravel-admin: Last

### Description:
I want to disable creation on specific model. I just tried with `$grid->disableCreation()` and it removes create button from crud. But if I go through example.com/admin/model/create I can access to creation form of that model, so creation is not disabled.

Thanks.

**Comment by z-song** [comment]
Yes, method `disableCreation` only remove the create page link on grid.

If you want to disable creation on specific model, just remove the `create` action from the controller

**Comment by Romerski** [comment]
I mean, if I want to disable `create` action for a specific rol, I need to do through permissions with their routes, right? I can't check if a user has specific role/permission and disable `create` action for that user on the controller.

**Comment by z-song** [comment]
> I can't check if a user has specific role/permission and disable create action for that user on the controller

For example, create a role with name `editor`, and assign it to users, then check the role in create action in controller:

```php
use Encore\Admin\Auth\Permission;

class PostController extends Controller
{
    public function create()
    {
        // Only users who with role `editor` can pass this check
        Permission::allow('editor');
    }
}
```

**Comment by Romerski** [comment]
That's it! Thanks!

**Comment by NickCoolii** [comment]
@z-song maybe it would be better if use naming as in $form->tools(): disableBackButton(), disableListButton().
For less misunderstanding add method to Grid [disableCreationButton() or disableCreateButton()] and make disableCreation() as alias for new method for backward compatibility.

**Comment by z-song** [comment]
@NickCoolii Yes, `disableCreateButton` is more clearly, renamed in commit 757062b, Thanks

**Comment by Romerski** [comment]
@z-song @NickCoolii It wouldn't be better if `disableCreation()` also would throw an access denied exception if you try to go through `example.com/admin/model/create`? Because why will you disable create button if not to prevent creation of that model?

**Comment by NickCoolii** [comment]
@Romerski my use case:
I want to disable standard creation button, but still need creation function for my custom button with some get parameters which I wanna pass to form.

Update:
changed my solution: just used URL::previous() in creation form.

**Comment by ebsinori** [comment]
@NickCoolii I also have such use case. Could you tell me where to add this code?

**Comment by NickCoolii** [comment]
@ebsinori maybe this can help you:
http://take.ms/puKDM

**Comment by ebsinori** [comment]
@NickCoolii Thanks!
