### ISSUE TITLE
后台分不同部门或者平台

### ISSUE THREAD

**Issue by AaronChengHao** [z-song/laravel-admin#1566]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 

### Description:
你好，z-song，我这不是提问题，而是向您请教一个问题。我们后台要实现一个平台后台和商户后台的逻辑。平台后台属于最顶层的人，可以查看，修改所有数据，而商户后台只能查看和修改属于自己的数据，请问一下，面对这样的业务，我们的admin可以完成吗？如果可以，谢谢z-song能提供一点思路。谢谢

**Comment by z-song** [comment]
给平台后台分配最高权限

商户后台只展示他们自己的数据就好了
