### ISSUE TITLE
Fresh install with helpers. Cannot save form created using admin scaffold

### ISSUE THREAD

**Issue by azaman2204** [z-song/laravel-admin#1567]
Laravel-admin: 1.5
PHP version | PHP/7.1.7
Laravel version | 5.5.28

### Description:
Cannot save when create new record from form.

### Steps To Reproduce:
0. New fresh install as per laravel-admin webpage
1. create new table, model and controller using admin-helper
2. add the fields in the grid and form
```php
 protected function grid()
    {
        return Admin::grid(Announcement::class, function (Grid $grid) {

            $grid->id('ID')->sortable();
                        
            $grid->title('Title')->sortable();
            $grid->message('Message');
            $grid->startdate('Start')->sortable();
            $grid->enddate('Ends')->sortable();
            $grid->createdby('Created By')->sortable();

            $grid->created_at();
            $grid->updated_at();
        });
    }
]

```
```php
 protected function form()
    {
        return Admin::form(Announcement::class, function (Form $form) {

            $form->display('id', 'ID');
            
            $form->text('title','Title');
            $form->text('message','Message');
            $form->date('startdate','Start');
            $form->date('enddate','Ends');
            //$form->number('createdby','Created By');
            $form->hidden('createdby');
                    $form->saving(function (Form $form) {
                        $form->createdby = Admin::user()->id;
                    });
                    
            $form->display('created_at', 'Created At');
            $form->display('updated_at', 'Updated At');
            
            $form->saving(function () {
                  \Log::info(request()->getMethod());
                   
            });
        });
    }
```
3. create a menu entry and route to admin/announcement in app/Admin/route.php
```php
    $router->get('/announcement', '\\App\\Admin\\Controllers\\AnnouncementController@index');
    $router->get('/announcement/create', '\\App\\Admin\\Controllers\\AnnouncementController@create');
```

4. Grid display OK
5. Select new record button, new form displayed. Enter data ok. Press SUBMIT nothing happen, no record/data saved altho saw progress icon 

<img width="1013" alt="screen shot 2018-01-03 at 12 56 29 am" src="https://user-images.githubusercontent.com/790857/34492112-239a121c-f021-11e7-8347-ca5e7f1ffe1f.png">
<img width="990" alt="screen shot 2018-01-03 at 12 57 03 am" src="https://user-images.githubusercontent.com/790857/34492114-28a2c808-f021-11e7-80de-98fe3cd7f68f.png">

**Comment by z-song** [comment]
Replace your routes with following:
```php
$router->resource('/announcement', '\\App\\Admin\\Controllers\\AnnouncementController');
```

**Comment by azaman2204** [comment]
Thanks it works. My bad. I was using 
` $router->get('/announcement', '\\App\\Admin\\Controllers\\AnnouncementController@index');`
