### ISSUE TITLE
在 Admin::grid 如何使用 groupBy?

### ISSUE THREAD

**Issue by 1027836596** [z-song/laravel-admin#1569]
- Laravel Version: 5.5.#
- PHP Version:7.1
- Laravel-admin: 1.5.#

### Description:

在 Admin::grid 如何使用 groupBy?

我试了这样 $grid->model()->groupBy('title'); 不行。

因为要汇总统计

**Comment by zxk7516** [comment]
$grid->model()->groupBy()

**Comment by nidhisony24** [comment]
$grid->model()->groupBy() not work for me.

**Comment by z-song** [comment]
@1027836596 参考https://github.com/z-song/laravel-admin/issues/2466#issuecomment-419967748
