### ISSUE TITLE
删除的noty交互字段不一致？

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#157]
![image](https://cloud.githubusercontent.com/assets/7192860/20781325/f2d712f8-b7bc-11e6-9341-0099dc96fca4.png)
![image](https://cloud.githubusercontent.com/assets/7192860/20781335/01c6f260-b7bd-11e6-9f53-493f6695b654.png)
通知的时候，看代码，需要的返回值是status和message，但是默认的方法中只返回了一个msg

**Comment by z-song** [comment]
你说的是`vendor/encore/laravel-admin/src/Controllers/AdminController.php`这个文件吗，这个文件已经废弃了，为了兼容老版本才保留下来的。

现在使用`vendor/encore/laravel-admin/src/Controllers/ModelForm.php`这个来代替。

**Comment by xyz8772232** [comment]
好的
