### ISSUE TITLE
批量保存问题

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1571]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:
我想做一个表单保存一些信息，然后有按钮可以控制新增一条或者删除一条，最后一次性批量保存这些信息（相当于多次插入同一张表），不知道有没有案例或者代码可以参考一下

**Comment by oopsoop** [comment]
sdsds

**Comment by lePig** [comment]
我也想弄这样的，不知道老铁你是如何实现的？
