### ISSUE TITLE
editable('select',[]) 选项是否可以动态变化

### ISSUE THREAD

**Issue by gystone** [z-song/laravel-admin#1572]
- Laravel Version: 1.5
- PHP Version:7
- Laravel-admin: 1.5

### Description:

![image](https://user-images.githubusercontent.com/13912882/34550158-7caf5c1c-f149-11e7-9840-259230970573.png)
 请问
1、画红框的数组是否可以动态的变化，现知道display 和 editable 不能一起使用。
2、如问题1，不能动态变化，这样只能写死一个数组的话，那我想在蓝色框的位置出取出当前行的一些值，这样我也可以组一个动态的数组赋值给红色框，请问，如何在蓝色区域获取当前行的值？

**Comment by z-song** [comment]
无法满足你的需求~
