### ISSUE TITLE
列表页面无法操作-删除 报js错误

### ISSUE THREAD

**Issue by gilbertho-dd01** [z-song/laravel-admin#1575]
- Laravel Version: 5.5#.#.#
- PHP Version:PHP 7.1.12
- Laravel-admin: 1.5.x-dev

### Description:
![image](https://user-images.githubusercontent.com/34530493/34561767-87e554be-f186-11e7-9b05-0ccbfe5f2aca.png)

**Comment by gilbertho-dd01** [comment]
Controller 方法引用下面完美解决
Admin::js('/vendor/laravel-admin/AdminLTE/plugins/iCheck/icheck.min.js');

**Comment by gilberthedd01** [comment]
其实这里没加载到也是 路由中间件缺少admin，导致admin/bootstrap.php 没加载。
