### ISSUE TITLE
请问 登入页面的提示 username 必填. 如何改为中文

### ISSUE THREAD

**Issue by lianke** [z-song/laravel-admin#1577]
请问 登入页面的提示 username 必填. 如何改为中文的提示.

**Comment by lianke** [comment]
我这里好像传不了图片 
我改了中文之后 发现 提示 还是
 username 必填.
 password 必填.

我想改为 用户名 必填,请问怎么修改.

**Comment by z-song** [comment]
去google `laravel 汉化`

https://laravel-china.org/topics/570/laravel-more-than-and-5-language-package-to-you-the-52-mandarin-words-at-random-overtruelaravel-lang

**Comment by lianke** [comment]
AuthController.php 修改为如下就可以了,指定用户名和密码的错误提示信息
if ($validator->fails()) {
           // return Redirect::back()->withInput()->withErrors($validator);
			return Redirect::back()->withInput()->withErrors(['username' => trans('auth.username') , 'password' => trans('auth.password')]);
        }
