### ISSUE TITLE
form动态增加input输入框

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1578]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:
laravel-admin 能动态增加Input 输入框嘛？

**Comment by z-song** [comment]
http://laravel-admin.org/docs/#/zh/model-form-fields?id=%e4%b8%80%e5%af%b9%e5%a4%9a

用`$form->hasMany()`

**Comment by feistiny** [comment]
关于这个需求，我用了一个替代性的方式来实现，感觉效果不错，有此类需求的可以参考一下
可以在一个页面里方便的操作，json类型的字段或者hasMany关联，希望可以给@z-song一点灵感，只恨我现在还没有能力PR
![image](https://user-images.githubusercontent.com/13468753/46062334-0c497600-c19c-11e8-8b4f-8bbc811830b5.png)
![image](https://user-images.githubusercontent.com/13468753/46062307-f63bb580-c19b-11e8-9c77-6f7a844c5c60.png)
