### ISSUE TITLE
Grid不分页的问题

### ISSUE THREAD

**Issue by thickas** [z-song/laravel-admin#158]
比如在LogController中设置不分页显示，在Index中  $content->body($grid);之前添加如下语句
 $grid->model()->usePaginate(false);
运行时会出错，原因是encore\laravel-admin\views\grid\table.blade.php中下面两段代码没有添加判断
 <select class="form-control input-xs per-page" name="per-page">
                {!! $grid->perPageOptions() !!}
 </select>

  {!! $grid->paginator() !!}

如果直接删除这两段代码就正常可用了。

没去认真跟踪代码，建议或者是在Grid的两个函数中添加判断，或者是在table.blade.php添加判断，修复此问题。

**Comment by z-song** [comment]
这里确实有问题，谢谢反馈！

**Comment by z-song** [comment]
问题修复，添加了`Grid::disablePagination();`来关闭分页，谢谢反馈！
