### ISSUE TITLE
editable不能修改字段并报错

### ISSUE THREAD

**Issue by dogelin** [z-song/laravel-admin#1581]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5.7

### Description:
使用editable修改状态，报错
这是代码：
![aiq60 jl3 0o0dx_pqbbm w](https://user-images.githubusercontent.com/17040400/34601550-6ae26fb2-f237-11e7-9f07-8cb4eb46c8a6.png)

![pxo tqmk0a zx5 ew vfr](https://user-images.githubusercontent.com/17040400/34601255-198290f8-f236-11e7-956b-b31c4882ac43.png)

然后出现报错信息

![7oigezr5rl_axhscd_gvz d](https://user-images.githubusercontent.com/17040400/34601291-41f39190-f236-11e7-8cad-d3169c425eda.png)

![u ez4 2uc s 4 0hi1j](https://user-images.githubusercontent.com/17040400/34601318-5cf0846c-f236-11e7-9d58-80075059b84a.png)

![r za7smv 6vywbd 1 l 7](https://user-images.githubusercontent.com/17040400/34601342-7cc1e83a-f236-11e7-85a6-ece1d5c51544.png)

![pi_ep0ml8 oa k vuwaj](https://user-images.githubusercontent.com/17040400/34601396-c236f72a-f236-11e7-90a0-27818c34de95.png)

然后这些操作也弄了，都不行
![xmtf9tc1 lt so z_ c1 3](https://user-images.githubusercontent.com/17040400/34601484-26f6be0c-f237-11e7-9e32-3b60c2dd61c8.png)

请问是什么原因呢，哦，版主给的示例demo也有同样的错误，是源码本身就有这个bug吗

**Comment by z-song** [comment]
demo的代码更新一下就好了

你的form怎么写的？

**Comment by dogelin** [comment]
@z-song 
这样写的
![image](https://user-images.githubusercontent.com/17040400/34656482-c8fea64a-f455-11e7-8eab-c4711a516156.png)

**Comment by z-song** [comment]
form怎么写的?  form

**Comment by dogelin** [comment]
@z-song 
没改过什么form，安装后默认的

**Comment by dogelin** [comment]
@z-song 
![hywvy0 3 35gxdws0c9q v](https://user-images.githubusercontent.com/17040400/34658010-5f67deca-f466-11e7-81c4-bd896a3cae59.png)

**Comment by dogelin** [comment]
@z-song 
![_q 8di0io h8 sley eyh](https://user-images.githubusercontent.com/17040400/34658065-cc624646-f466-11e7-8ef5-917ec0cfddf6.png)

**Comment by z-song** [comment]
用：
```php
return Admin::form(User::class, function (Form $form) {
    //...
});
```

如果要使用`User::form()`，需要在模型里注入AdminBuilder
```php
use Encore\Admin\Traits\AdminBuilder;

class User extends Model
{
    use AdminBuilder;
}
```

**Comment by dogelin** [comment]
嗯嗯，谢谢，刚刚发现，打扰了
