### ISSUE TITLE
文件上传不存在文件

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1582]
- Laravel Version:5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:
配置好存储设置后，表单提交Excel，文件上传到了服务器，我跳转到了自己定义的方法中，如何把读取Excel的数据并进行处理？

**Comment by z-song** [comment]
文件上传上去了吗

**Comment by imekkk** [comment]
array:1 [▼
  "file" => UploadedFile {#321 ▼
    -test: false
    -originalName: "test.xlsx"
    -mimeType: "application/octet-stream"
    -size: 9464
    -error: 0
    #hashName: null
    path: "D:\xampp\tmp"
    filename: "php71D7.tmp"
    basename: "php71D7.tmp"
    pathname: "D:\xampp\tmp\php71D7.tmp"
    extension: "tmp"
    realPath: "D:\xampp\tmp\php71D7.tmp"
    aTime: 2018-01-08 08:45:24
    mTime: 2018-01-08 08:45:24
    cTime: 2018-01-08 08:45:24
    inode: 0
    size: 9464
    perms: 0100666
    owner: 0
    group: 0
    type: "file"
    writable: true
    readable: true
    executable: false
    file: true
    dir: false
    link: false
    linkTarget: "D:\xampp\tmp\php71D7.tmp"
  }
]
打印出来是这样的，应该再服务器上了吧？
