### ISSUE TITLE
是否可以考虑将开发这个项目的整个过程整理成一个教程出售?

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#1587]
如题.
对此类项目非常感兴趣,但是限于个人能力,曾经写过很多个项目,最后都放弃维护了.

是否可以将laravel-admin这个开源项目作为产品,整理一份分析和构建过程的教程.个人愿意付费得到这样一份思路.对个人的提高应该非常有帮助,以后web开发这里决定就用laravel系了.

我目前的项目用的vue的ivew

**Comment by z-song** [comment]
内容太多了，几乎覆盖了Laravel的视图、模型的所有内容

现在维护这个项目的时候都不太够，所以整理教程就更有心无力了

**Comment by faydanube** [comment]
好吧,谢谢回复.
作者辛苦了.

后续如果有开发这个项目的思路或者大纲之类的东西可以通知我.非常感谢.
