### ISSUE TITLE
menu里面的reset用的是submit

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#159]
![image](https://cloud.githubusercontent.com/assets/7192860/20782590/18fc5866-b7c8-11e6-9756-1a15a186d4e7.png)

![image](https://cloud.githubusercontent.com/assets/7192860/20782598/347de88e-b7c8-11e6-9fd4-b339d24b2c3b.png)

**Comment by z-song** [comment]
多谢指出，已经修复。
