### ISSUE TITLE
在laravel-admin中如何换成mongodb数据库

### ISSUE THREAD

**Issue by 529834149** [z-song/laravel-admin#1592]
- Laravel Version: #.#.# 5.4
- PHP Version: 7.1
- Laravel-admin: #.#.# 

### Description:

   "jenssegers/mongodb": "^3.0",
config/app中都已经配置好了，在执行php artisan admin:install时，没有生成admin文件夹，并且提示
![image](https://user-images.githubusercontent.com/22534117/34665411-06bccc60-f49b-11e7-8725-bf704961bf71.png)
 求大神指点

**Comment by 529834149** [comment]
在mongodb中生成的表结构
![image](https://user-images.githubusercontent.com/22534117/34665453-2546b556-f49b-11e7-8f86-e685947bf696.png)，但是没有数据

**Comment by 529834149** [comment]
应该是在mongodb中，所有的字段都不存在导致的----猜测正在尝试

**Comment by z-song** [comment]
没测试过mongodb的安装，你试着手动写入数据看看吧

**Comment by 529834149** [comment]
嗯好的我试一下

**Comment by 529834149** [comment]
mongdb时，根本不声称admin后台文件夹，我是直接复制文件过去，在登录时
，提交帐号密码提示 
![image](https://user-images.githubusercontent.com/22534117/34703573-993aa790-f52e-11e7-913b-17fc077cd273.png)，我看下代码
![image](https://user-images.githubusercontent.com/22534117/34703591-ab1de7b0-f52e-11e7-9707-fe6d5ddf4356.png)

**Comment by 529834149** [comment]
在点击后台登录提交时，一直提示Call to a member function prepare() on null，我看了下登录方法:
   /**
     * @param Request $request
     *
     * @return mixed
     */
    public function postLogin(Request $request)
    {
        $credentials = $request->only(['username', 'password']);
        $validator = Validator::make($credentials, [
            'username' => 'required', 'password' => 'required',
        ]);

        if ($validator->fails()) {
            return Redirect::back()->withInput()->withErrors($validator);
        }
**`// dump(Auth::guard('admin')->attempt($credentials));`**  这里一直提示错误Call to a member function prepare() on null ，但是  credentials是一个数组，我看参数都没问题
        if (Auth::guard('admin')->attempt($credentials)) {
            admin_toastr(trans('admin::lang.login_successful'));

            return redirect()->intended(config('admin.prefix'));
        }

        return Redirect::back()->withInput()->withErrors(['username' => $this->getFailedLoginMessage()]);
    }

**Comment by z-song** [comment]
你要把完整的异常trace信息给出来分析

**Comment by Adger01** [comment]
请问这个问题有解决吗？遇到同样的问题Call to a member function prepare() on null

**Comment by sd2595101** [comment]
里面好像被采用类似PDO接口的东西，不知道怎么解决，持续关注中

**Comment by sd2595101** [comment]
我尝试了一下，因为MongoDB跟其他数据库有些不同，不太好兼容。
(尝试的时候MongoDB用的是jenssegers/laravel-mongodb)

1. transaction ： MongoDB没有这个功能
2. 主键：MongoDB没有自增的数字SEQ供你使用，默认的_id是英数字。所以AdminTablesSeeder需要重新考虑一下。
3. 表关联的部分，不明原因：有些关联字段显示不出来。
