### ISSUE TITLE
列表数据expand内获取不到$this?

### ISSUE THREAD

**Issue by felixjing** [z-song/laravel-admin#1593]
```php
$grid->column('订单详情')->expand(function () {
    //dd($this->id);
    $profile = array_only($this->toArray(), ['category_id', 'amount', 'price', 'total_price', 'address']);
    return new Table([], $profile);
}, '详情'); 
```
想将列表行内的一部分内容隐藏然后点开显示
打印$this 获取不到，display可以。

**Comment by z-song** [comment]
是按照demo的expand扩展写的吗？

**Comment by felixjing** [comment]
@z-song 参开了 https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Controllers/UserController.php  
但demo里的是定义了一对一关系的
` $grid->column('expand')->expand(function () {
                $profile = array_only($this->profile, ['homepage', 'gender', 'birthday', 'address', 'last_login_at', 'last_login_ip', 'lat', 'lng']);
                return new Table([], $profile);
            }, 'Profile');`

`public function profile()
    {
        return $this->hasOne(Profile::class);
    }`

我是想用$this->toArray(),取到当前模型的数据，display(function(){dd($this->toArray()); })可以取到,但expand里$this是空的
