### ISSUE TITLE
select 如何设置默认值

### ISSUE THREAD

**Issue by sdauma** [z-song/laravel-admin#1594]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.5.x-dev

### Description:
$form->select('appauthtoken_id','商户授权码')->options('/admin/ShowAppAuthToken');
怎么设置默认选中值？

**Comment by z-song** [comment]
试试
```php
$form->select('appauthtoken_id','商户授权码')->options('/admin/ShowAppAuthToken')->default('xx');```

**Comment by xinhaonaner** [comment]
设置default不行，可以使用options
![image](https://user-images.githubusercontent.com/24741621/34810211-d73a04b2-f6d4-11e7-90d5-3d417b5d01e6.png)
效果：
![image](https://user-images.githubusercontent.com/24741621/34810189-b925dc76-f6d4-11e7-9be4-2e8c11d385cf.png)

现在修改的时候，没有数据显示，但是库里是有值的，请问如何在编辑时，获取数据呢？
![image](https://user-images.githubusercontent.com/24741621/34810109-5973c360-f6d4-11e7-9005-6fa6028a1f64.png)
![image](https://user-images.githubusercontent.com/24741621/34810119-693d7be2-f6d4-11e7-922c-20117bc37aa4.png)

**Comment by sdauma** [comment]
谢谢。->options(...)->options(...)可以。

**Comment by feivorid** [comment]
这个问题没解决啊    我也遇到也这个问题   select后面跟default 不好用    再跟一个options 也不好用啊  最主要编辑的时候还没有回填    请问boss 这个怎么解决 ？ @z-song

**Comment by ilevitate** [comment]
编辑的时候没有回填啊 请问怎么解决 ？ @z-song

**Comment by Suckbiao** [comment]
根据源码，default 函数无效，需要使用闭包。

`$form->select( $column [, $label] )->options( function ($default) {
        return  $default;
} )`
// 之后就会发现默认值已经选上了；
// 注意，默认值必须是在下拉选项中已经存在的值；

**Comment by shunhua** [comment]
@z-song   现在解决没这个问题

**Comment by RobinVSRose** [comment]
@sdauma @z-song  可以尝试忽略该字段，这样就不会在form->edit($id)的时候把default的值覆盖了
$form->ignore('appauthtoken_id')->select('appauthtoken_id','商户授权码')->options('/admin/ShowAppAuthToken')->default("ABCD0001");

**Comment by dynamohuang** [comment]
mark

**Comment by mycherish** [comment]
@RobinVSRose 忽略掉是可以显示了，但是不能保存

**Comment by lePig** [comment]
+1

**Comment by stone009** [comment]
+1 试了各种办法
```config``` ```options``` ```default``` 方法都不行。

**Comment by fplun** [comment]
![image](https://user-images.githubusercontent.com/38807395/46652065-846c5e80-cbd4-11e8-94f1-2e66a1f71d1c.png)
试试这样

**Comment by isalone** [comment]
谁能给个比较合理的解决方案，还是同样的问题，

**Comment by isalone** [comment]
找到解决方案了，我的laravel-admin 是1.5x版本的。
![image](https://user-images.githubusercontent.com/25174075/47262822-10f81480-d525-11e8-8253-076fb12fa6ca.png)
![image](https://user-images.githubusercontent.com/25174075/47262824-1fdec700-d525-11e8-8af4-16c5e8723f64.png)
上述是通过select 异步加载。这里catalog_id为关联表的主键。
