### ISSUE TITLE
是否登录判断

### ISSUE THREAD

**Issue by gilberthedd01** [z-song/laravel-admin#1595]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.x

### Description:
登录后台长时间不使用，再次访问出现错误信息。
中间件有这个逻辑处理吗
不知道是不是我的代码改动影响了

![image](https://user-images.githubusercontent.com/34530493/34702784-a66178a8-f52a-11e7-93a4-cea08451d94c.png)

**Comment by z-song** [comment]
应该会跳转到登陆页面的吧

**Comment by gilbertho-dd01** [comment]
不会跳， 长时间不活动页面。都直接报错误！

**Comment by sdauma** [comment]
我的可以跳转到登陆页面

**Comment by gilberthedd01** [comment]
已定位到问题。 还是路由确少admin中间件。
谢谢！
