### ISSUE TITLE
三级联动在编辑的时候, 回填数据只回填了第一项。

### ISSUE THREAD

**Issue by tiandaye** [z-song/laravel-admin#1596]
- Laravel Version: 5.5.*
- PHP Version:7.1.11
- Laravel-admin: 1.5.*

### Description:
三级联动过滤在编辑的时候, 回填数据只回填了第一项, 应该是没有触发它的 `change` 事件, 请问有解决方案吗？

**Comment by z-song** [comment]
二三级的数据你可以自己手动填上

**Comment by feivorid** [comment]
@tiandaye   请问这个问题 你是怎么解决的 ？   搞定了吗 ？

**Comment by dev-kang** [comment]
这个数据应该怎么自己手动添加上？ @z-song

**Comment by zenghuang19** [comment]
这个问题解决了吗？
