### ISSUE TITLE
列的拓展使用

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1597]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:
文档中说的可以直接在界面上修改列的值 $grid->column('sku')->editable('text'); 这个功能会直接修改数据库嘛？我一刷新就又回到原来的值上去了，如果可以直接修改还需要哪些条件？

**Comment by imekkk** [comment]
form 要把所有的字段都列出来嘛？

**Comment by imekkk** [comment]
form()要把所有的字段写出来嘛？提示是更新成功了，但是数据库没修改成功

**Comment by z-song** [comment]
在form中也要有该字段的field才可以

**Comment by imekkk** [comment]
我已经成功了，谢谢

**Comment by mycherish** [comment]
@imekkk 你怎么写的在form（）里，我这里有个bug， 就是修改了值，然后旁边两个的字段值在数据库里没有了
