### ISSUE TITLE
[idea] Remove csrf_token from GET request at Widgets\Form

### ISSUE THREAD

**Issue by NickCoolii** [z-song/laravel-admin#1599]
- Laravel Version: 5.5
- Laravel-admin: 1.5

### Description:
I'm using Widgets\Form for search through Grid's filters (GET method) and csrf_token is unnecessary and uglify url (as "where" filter also do).

I workaround this by adding 1 variable passing to view and 1 additional check in the view file.
@z-song 
On which branch better to make push: master or 1.5?

**Comment by z-song** [comment]
Thanks, push to branch 1.5 is ok.

**Comment by z-song** [comment]
Merged, Thanks!

**Comment by NickCoolii** [comment]
After this changes I have csrf_token problem when creating new menu element from /admin/auth/menu.
Will investigate.
