### ISSUE TITLE
也许还可以改造为一个可供游客访问的系统

### ISSUE THREAD

**Issue by thickas** [z-song/laravel-admin#160]
虽然名为后台系统，我觉得也可尝试改造为一个可以用于游客访问的系统，来访者自动创建以IP地址为用户名的用户，赋予guest角色，并自动登录。需要时再以后台管理员身份重新登录。

1、增加guest角色，修改Encore\Admin\Auth\Database\AdminTablesSeeder，增加下面的代码
Role::create([
            'name'  => '游客',
            'slug'  => 'guest',
        ]);

2、修改认证中间件，Encore\Admin\Middleware\Authenticate，实现自动获取IP地址作为用户名和密码，新建用户，并赋予guest角色，自动登录

    public function handle($request, Closure $next) {
        if (Auth::guard('admin')->guest() && !$this->shouldPassThrough($request)) {      
        
	 $username = $request->getClientIp();
            if (!User::where('username', $username)->count()) {
                $user = User::create([
                            'username' => $username,
                            'password' => bcrypt($username),
                            'name' => sprintf("游客%06d", User::count()),    //这里可以用随机字符串
                ]);
                $user->roles()->attach(Role::where('slug', 'guest')->get());
            }

            Auth::guard('admin')->attempt(['username' => $username, 'password' => $username]);
          //  return redirect()->guest(Admin::url('auth/login'));
        }
        return $next($request);
    }

3、修改Encore\Admin\Controllers\AuthController，

public function getLogin() {      
        if (!Auth::guard('admin')->guest()) {
           // return redirect(config('admin.prefix'));
            //注销当前用户，然后再登录
            Auth::guard('admin')->logout();
        }

        return view('admin::login');
    }

4、修改视图模板vendor\encore\laravel-admin\views\partials\header.blade.php

   @if (!Admin::user()->isRole('guest'))
                <li class="dropdown user user-menu">
		......
                </li>
                @else
                <li>
                <a href="{{ Admin::url('auth/login') }}">管理员从这里{{ trans('admin::lang.login') }}</a> 
                </li>
                @endif

**Comment by edwinhuish** [comment]
这样操作还不如直接改为不登陆能够进入系统，不过一些功能操作需要登陆。

**Comment by z-song** [comment]
这个属于自定义需求了，如果需要实现可以自己fork一个分支出来开发

如果访客多的话，会创建比较多的用户ip

或者可以提前建好访客的用户和角色，配置好权限，在登陆页面加一个`访客登陆`的按钮，访客点击按钮的时候就让他用建好的访客用户登陆。
