### ISSUE TITLE
dateRange如何设置默认值

### ISSUE THREAD

**Issue by RJustice** [z-song/laravel-admin#1602]
- Laravel Version: 5.4
- PHP Version: 7.1
- Laravel-admin: 1.4.3

### Description:

如何设置dateRange的默认值,  使用value方法或者prepare 都无法设置value值

**Comment by z-song** [comment]
```php
$form->dateRange('start_date', 'end_date', 'Date range')
    ->default(['start' => '2018-01-11', 'end' => '2018-01-12']);
```

**Comment by msassa** [comment]
This is not working for me. Any idea why?

`$form->dateRange('start_date', 'end_date', 'Dates')->default(['start' => '2018-01-11', 'end' => '2018-01-12']);`

**Comment by msassa** [comment]
it works like this:

`$form->dateRange('start_date', 'end_date', 'Dates')->options(['defaultDate' => date('Y-m-d')]);`

**Comment by xx10n31y** [comment]
> ```
> $form->dateRange('start_date', 'end_date', 'Date range')
>     ->default(['start' => '2018-01-11', 'end' => '2018-01-12']);
> ```

实测无效

**Comment by ftc-tonywang** [comment]
```
$form->dateRange('start_date', 'end_date', 'Date range')
    ->default(['start' => '2018-01-11', 'end' => '2018-01-12']);
```
1.7 is work , but upgrade to 1.8 not work

**Comment by toproplus** [comment]
```php
$model = new YourModel();
$model->start_date_field = '2025-12-19 00:00:00';
$model->end_date_field= '2025-12-20 00:00:00';
// 给数据表单，设置模型
$form = new Form($model);
$form->dateTimeRange('start_date_field', 'end_date_field', 'dateTimeRange');
```
