### ISSUE TITLE
hasMany动态添加多组数据，并保存在一个字段中

### ISSUE THREAD

**Issue by echoo212** [z-song/laravel-admin#1603]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.x-dev

### Description:
我有一个这样的需求：
给一个用户添加家庭成员信息（姓名、年龄、职业等），两个需求：
1.家庭成员需要动态添加
2.所有家庭成员信息用json存储，放到一个字段中
格式：
{
"mother":{"age":30,"edu":"\u672c\u79d1","job":"\u6559\u5e08"},
"father":{"age":30,"edu":"\u672c\u79d1","job":"\u6559\u5e08"},
"children":{"age":"5\u4e2a\u6708","edu":"\u5b66\u9f84\u524d","job":"\u65e0"}
}

请问咱们的框架能解决这个需求吗？非常感谢

**Comment by ajiader** [comment]
好像不能动态添加input
