### ISSUE TITLE
关于使用Redis存Session

### ISSUE THREAD

**Issue by morix-gao** [z-song/laravel-admin#1604]
- Laravel Version: 5.4
- PHP Version:5.6
- Laravel-admin: 1.4

### Description:
我打算用redis来存储auth的session（针对laravel-admin的auth系统）。
请教如何启动redis呢？

### Steps To Reproduce:
看到admin里有auth的配置：
    'auth' => [
        'driver'   => 'session',
        'provider' => '',
        'model'    => Encore\Admin\Auth\Database\Administrator::class,
    ],
我把provider配置成redis，删掉了session的对应文件，刷新页面重新登录，发现session还是文件模式。

**Comment by z-song** [comment]
在`config/session.php`里面配置

**Comment by morix-gao** [comment]
已搞定，Thank U！
