### ISSUE TITLE
三表关联查不到数据

### ISSUE THREAD

**Issue by echoo212** [z-song/laravel-admin#1605]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.x-dev

### Description:
三张表：user、user_detail、admin_users
user、user_detail通过uid关联
user_dtail、admin_users通过operator关联

现在想在user列表显示operator的name,但是就是取不到，麻烦帮忙看看是哪里的问题，非常感谢

### Steps To Reproduce:
`UserModel`
public function detail()
    {
        return $this->hasOne(UserDetail::class,'uid');
    }

`UserDetailModel`
public function adminOperator()
    {
        return $this->belongsTo(Administrator::class,'operator');
    }

`UserController`
 $grid->model()->with('detail.adminOperator')；
$grid->detail()->adminOperator('操作人')->display(function($adminOperator){
               return $adminOperator['name'];
            });

**Comment by z-song** [comment]
`adminOperator`换成小写试试看

**Comment by echoo212** [comment]
@z-song 换成小写好了，非常感谢！

**Comment by echoo212** [comment]
@z-song 改成小写好了，非常感谢！但是两表联查时方法名可以用驼峰命名

**Comment by cnxfire** [comment]
我也试过了 $gird()->model 里面要小写，连起来查询也要小写，都要小写

**Comment by cnxfire** [comment]
三表关联查询后,filter失效了
