### ISSUE TITLE
请问怎样修改Listbox的大小？

### ISSUE THREAD

**Issue by raykaye** [z-song/laravel-admin#1607]
- Laravel Version: 5.5.28
- PHP Version: 7.0.10
- Laravel-admin: 1.5.x-dev

### Description:
我在配置角色权限时，由于权限比较多，而角色权限配置页面`Listbox`高为`102px`，自己尝试一下修改还是改不了。

**Comment by z-song** [comment]
通过settings方法设置listbox，用`selectorMinimalHeight`设置最小高度：
```php
$form->listbox(...)->options(...)->settings(['selectorMinimalHeight' => 200]);
```
更多设置参考 https://github.com/istvan-ujjmeszaros/bootstrap-duallistbox#initialization-parameters-object

**Comment by raykaye** [comment]
可以了  谢谢大佬
