### ISSUE TITLE
/app/Admin/bootstrap.php 加载问题

### ISSUE THREAD

**Issue by gilberthedd01** [z-song/laravel-admin#1608]
- Laravel Version: 5.5#.#.#
- PHP Version: 7.0
- Laravel-admin: 1.5.x-dev

### Description:
在/app/Admin/bootstrap.php  添加代码
`Admin::navbar(function (\Encore\Admin\Widgets\Navbar $navbar) {
    $navbar->left('html...');
    $navbar->right('html...');
});
`
发现只有在
http://xxx.com/admin/  执行 bootstrap.php 
http://xxx.com/admin/xxx  不执行 bootstrap.php 

请问这跟路由设置有问题， 还是哪里出错。

**Comment by z-song** [comment]
不清楚你的问题

参考 demo站的代码 https://github.com/z-song/laravel-admin.org

同样设置了navbar,所有的页面都生效

**Comment by gilberthedd01** [comment]
已定位到， 还是路由配置中间件的问题。确少admin。
