### ISSUE TITLE
SQL Syntax error Postgres

### ISSUE THREAD

**Issue by SZEth8** [z-song/laravel-admin#161]
Have this problem whith postgres Driver: 

select * from "admin_menu" order by `order` = 0,`order` 

Caused by method "orderByRaw"

**Comment by z-song** [comment]
Sorry i didn't test postgres before，I'll checkout this out.

**Comment by hayeah** [comment]
Postgres uses the double quote for identifiers (`order`), MySQL uses the backtick.

The problem is at Menu::toTree

```php
 public static function toTree(array $elements = [], $parentId = 0)
    {
        $branch = [];
        if (empty($elements)) {
            $elements = static::with('roles')->orderByRaw('`order` = 0,`order`')->get()->toArray();
        }
...
```

This works on postgres:

```php
orderByRaw('"order" = 0,"order"')
```

https://github.com/z-song/laravel-admin/blob/e95eb30e87bb91c59db47b38fad72a205baf89e9/src/Auth/Database/Menu.php#L69

**Comment by z-song** [comment]
Thanks to @hayeah for fix this issue.
