### ISSUE TITLE
checkbox怎么在编辑的时候出现选中状态

### ISSUE THREAD

**Issue by mayday526** [z-song/laravel-admin#1614]

**Comment by z-song** [comment]
编辑的时候会根据这个字段的值选中相应的值

**Comment by z-song** [comment]
如果是想要在创建页面给checkbox设置默认选中：
```php
默认选中值为1，2的两个选项
$form->checkbox('xxx')->default([1, 2])
```

**Comment by z-song** [comment]
am和pm是两个虚拟字段？ 那你设置am和pm的访问器来输出am和pm两个字段的值吧

**Comment by mayday526** [comment]
对的，我换种问法，怎么用访问器来让checkbox的一个值处于选中状态

**Comment by z-song** [comment]
```php
public function getAmAttribute($value)
{
    return ['monday_am', 'tuesday_am'];
}
```
类似这样不行吗？

**Comment by mayday526** [comment]
不行哎

**Comment by mayday526** [comment]
选中monday_am和wednesday_am
![qq 20180113222737](https://user-images.githubusercontent.com/18496055/34906884-18c51a6a-f8b1-11e7-8f94-749c29bad6a9.png)

这是提交的post信息
![qq 20180113222621](https://user-images.githubusercontent.com/18496055/34906892-3353aa7c-f8b1-11e7-9324-a432f7b9f07e.png)

**Comment by z-song** [comment]
访问器里面用逗号`,`隔开选项输出：
```php
public function getAmAttribute($value)
{
    return join(',', ['monday_am', 'tuesday_am']);
}
```

**Comment by z-song** [comment]
am和pm两个字段放到了模型的appends里面么？
```php
protected $appends = ['am', 'pm'];
```

**Comment by mayday526** [comment]
对的，没错，TAT,谢谢大神，怪我文档不好好看，给自己两耳光!!!!
