### ISSUE TITLE
select的onchange时如何执行多个load

### ISSUE THREAD

**Issue by sdauma** [z-song/laravel-admin#1617]
- Laravel Version: 5.5.28
- PHP Version:7.2
- Laravel-admin: 1.5.x-dev

### Description:
                $form->select('address.province_id')->options(
                    ChinaArea::province()->pluck('name', 'id')
                )
                    ->load('address.city_id', '/demo/api/china/city')
                    ->load('test', '/demo/api/china/city');
我看着例子里面有这种写法，但我的程序select的onchange时只执行最后一个load，怎么做才可以select的onchange时执行两个或者多个load？谢谢！

**Comment by z-song** [comment]
`vendor/encore/laravel-admin/src/Form/Field/Select.php`的`load`方法, 会解除第一个change绑定事件, 你可以在设置了一个load之后，再用`Admin::script()`给当前页面嵌入一段js来达到第二个load效果：
```php
        $script = <<<EOT
$(document).on('change', ". address", function () {
    var target = $(this).closest('.fields-group').find(".test");
    $.get("/demo/api/china/city?q="+this.value, function (data) {
        target.find("option").remove();
        $(target).select2({
            data: $.map(data, function (d) {
                d.id = d.id;
                d.text = d.text;
                return d;
            })
        }).trigger('change');
    });
});
EOT;

Admin::script($script);
```

**Comment by sdauma** [comment]
太感谢了. @z-song  laravel-admin 很强大！
