### ISSUE TITLE
grid 构建列表视图，CheckBox不出现

### ISSUE THREAD

**Issue by gilberthedd01** [z-song/laravel-admin#1618]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5.7

### Description:
![image](https://user-images.githubusercontent.com/34530493/34917595-77a0791c-f983-11e7-9619-28949dc8ae6a.png)
如上图，代码按 http://laravel-admin.org/demo/users 一样书写

请问CheckBox 跟哪里的设置有关系。
表是单表设计，无外键关联。

谢谢！

**Comment by z-song** [comment]
代码没有问题，看看console有没有错误吧

**Comment by gilberthedd01** [comment]
![image](https://user-images.githubusercontent.com/34530493/34930541-df412f22-fa04-11e7-8eb2-9ee74313afd9.png)

通过dui'bi对比发现问题出现在 routes.php中
'middleware'    => ['web','admin'],
增加admin 中间件。

**Comment by z-song** [comment]
`Encore\Admin\AdminServiceProvider`
