### ISSUE TITLE
select 聯動問題

### ISSUE THREAD

**Issue by we820731** [z-song/laravel-admin#1619]
- Laravel Version: 5.4.36
- PHP Version:5.6.32
- Laravel-admin: 1.4

使用select聯動 城市與地區在不同table 抓不到所有地區?
![image](https://user-images.githubusercontent.com/31517223/34918038-1f15e322-f988-11e7-84be-fddd4f6d1477.png)

`                $form->select('city_id', trans('admin::lang.city_id'))->options(
                    Location::pluck('city_name', 'city_id')
                )->load('district_id', '/admin/api/tw/district')->rules('required');
`

`                
                $form->select('district_id', trans('admin::lang.district_id'))->options(function ($id) {
                    return WebArea::options($id);
                })->rules('required');
`

`    public function district(Request $request)
    {
        $cityId = $request->get('q');
        return   DB::connection('mysql2')->table('district')->where('city_id',$cityId)->get(['district_id', DB::raw('district_name as text')]);
    }`

**Comment by yang5664** [comment]
要什麼資料，應該是自己要處理吧，應該跟laravel-admin無關吧
