### ISSUE TITLE
表单multipleSelect保存时出错

### ISSUE THREAD

**Issue by dogelin** [z-song/laravel-admin#1621]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5.7

### Description:
用$form->multipleSelect('keywords','标签')->options(Tag::all()->pluck('name', 'id'))->setWidth(6);
获取的keywords是个数组
![image](https://user-images.githubusercontent.com/17040400/34925263-3afe4a2e-f9e3-11e7-8f11-3df7984e6ad5.png)

所以在saving里面弄成了字符串
![xsmiv_b3ed24727 i3c1m](https://user-images.githubusercontent.com/17040400/34925317-9f665f2e-f9e3-11e7-9922-f4e48b1cd75e.png)
结果保存的时候报错
![default](https://user-images.githubusercontent.com/17040400/34925354-c6e29afe-f9e3-11e7-8b52-6e013126926b.png)
将sql语句单独在数据库里面执行也报错
![zjskb19qpb2 aze shegh](https://user-images.githubusercontent.com/17040400/34925484-8a7e889c-f9e4-11e7-9225-6c9d73d58cc9.png)

我的字段属性是这个
![vauenf e g5xr6j ykun8](https://user-images.githubusercontent.com/17040400/34925482-85631b16-f9e4-11e7-876b-ef112077aa6d.png)

### Steps To Reproduce:
无论我处不处理keywords都是报的Array to string conversion 错误，keywords尝试了各种字符串样式都不行，请问大佬是哪方面错了呢

**Comment by dogelin** [comment]
已解决，定义修改器

**Comment by stillAnd** [comment]
我也碰到类似错误了,可以分享一下怎么解决的 吗

**Comment by dogelin** [comment]
> 我也碰到类似错误了,可以分享一下怎么解决的 吗

public function getKeywordsAttribute($keywords)
	{
		return explode('-',$keywords);
	}
	public function setKeywordsAttribute($keywords)
	{
		$this->attributes['keywords'] = implode('-',$keywords);
	}

变量需要改动属性的时候,在model里面写修改器
