### ISSUE TITLE
saved修改model的数据出错

### ISSUE THREAD

**Issue by sdauma** [z-song/laravel-admin#1622]
- Laravel Version: 5.5.28
- PHP Version:7.2
- Laravel-admin: 1.5.x-dev

### Description:
			$form->saved(function (Form $form) {
				$form->model()->request_id = date('YmdHis').str_pad($form->model()->id,6,'0',STR_PAD_LEFT);
				$form->model()->save();
				throw new \Exception($form->model()->id." ".$form->model()->request_id);
				$this->AlipayMarketingCardTemplateCreate($form->model());
			});

**Comment by dogelin** [comment]
保存前修改的话应该是saving方法吧

**Comment by sdauma** [comment]
提交了空数据到了数据库，而字段不允许null。字段->nullable(true) 就好了。

**Comment by sdauma** [comment]
网友给了正确的解决办法。
![select](https://user-images.githubusercontent.com/35126877/34940559-f3f6aa48-fa2a-11e7-8a2e-b10f202a2602.png)
