### ISSUE TITLE
过滤问题请教

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1623]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin:1.4

### Description:
项目中，发票未到为0，到了则输入发票号，我在过滤筛选的时候能实现这个嘛。未送达可以查到，查所有不为0的，该如何实现
$filter->is('invoiced','发票号(输入0查询未送达发票)');
$filter->useModal();

**Comment by yang5664** [comment]
ref to [http://laravel-admin.org/docs/#/zh/model-grid-filters?id=%e6%9f%a5%e8%af%a2%e7%b1%bb%e5%9e%8b](url)
