### ISSUE TITLE
grid 显示字段过多，有滚动条么？

### ISSUE THREAD

**Issue by cashhaha** [z-song/laravel-admin#1626]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4

### Description:
由于grid里面显示的字段非常多，大概20多个，显示的长度已经超过当前屏，现在默认是自动挤在一个界面内，样式很难看，请问有滚动条的设置么？

**Comment by z-song** [comment]
没有横向滚动条

不过你可以参考 http://laravel-admin.org/demo/users 的第二列的展开效果

demo代码 https://github.com/z-song/laravel-admin.org

**Comment by cashhaha** [comment]
OK
