### ISSUE TITLE
Seems like the route "banners" makes something goes wrong inside the admin

### ISSUE THREAD

**Issue by woliveirac** [z-song/laravel-admin#1627]
- Laravel Version: 5.5
- PHP Version: 7.0
- Laravel-admin: 1.5

### Description: I've created a basic module called "Banners" where you can simple upload an image, a description and a title. When i create the menu and put the URI as "banners" when i'm gonna create/edit or delete i've got an error.

The error is an ajax "create?_pajax=%23pajax-container" failed. (i'm gonna upload an screenshot showing this).

(I'm using CKeditor in this) 

I can't edit nor delete with this error happening.

The thing is, when i change my route to something else as "teste" and point out to the same controller, everything seems to work.

### Steps To Reproduce:

1- Create a model called banner with "image" and "description" fields
2 - Then create a Router Resource called "banners" using BannerController as resource
3 - Create the BannerController and test it. 

(I'm gonna attach all the necessary files.) 

![screenshot_4](https://user-images.githubusercontent.com/7048196/34946209-18fdeaa6-f9ed-11e7-8561-c1f3842ef3c3.png)
![screenshot_5](https://user-images.githubusercontent.com/7048196/34946253-52cf0ab2-f9ed-11e7-872b-f5be3138291a.png)

[githubissue.zip](https://github.com/z-song/laravel-admin/files/1631879/githubissue.zip)

Thank you, hopefully, i'm doing something wrong.

**Comment by z-song** [comment]
Works fine with other route name but `banners`?

If you have adblock installed in your browser, try to disable it for you site.
