### ISSUE TITLE
How to get model value in Form?

### ISSUE THREAD

**Issue by zinmyotun-gic** [z-song/laravel-admin#1629]
I want database column value within Form.
I search and try many way but there is no way to get database column value in Form.

e.g I want to get value of User(table) id 
$user->id but no way to get the value.

**Comment by yang5664** [comment]
how about this？
```
$form->model()->colum_name;
```

**Comment by zinmyotun-gic** [comment]
`$form->model()->colum_name;`

I already tried but no vlaue can retrieve.
I do a little research and found.
Form is not same as Grid and before return the Form there is no value from database is retrieve.

**Comment by z-song** [comment]
```php

class UserController extends Controller
{
        public function edit($id)
        {
              ....
              $content->body($this->form($id)->edit($id));
              ....
        }

        public function form($id = null)
        {
                // Get database value here
                if ($id) {
                    $user = User::find($id);
                }

                .....
        }
}
```

**Comment by simonpeters** [comment]
@z-song this returns null for me

**Comment by zinmyotun-gic** [comment]
@simonpeters
you need to pass (id) like this.

$this->form($request->id);

**Comment by lambae96** [comment]
@z-song i have a same proplem with @zinmyotun-gic 
my code:
protected function form()
    {
        return Admin::form(Stock::class, function (Form $form) {
              $form->model()->id;
        }
}
and this return null
pls help me

**Comment by wamilomarov** [comment]
I tried to access the model value, but it is only accessing the model, not the real object. So, I made it as follows:
1. Get the ID of model from the route as follows:
`$id = request()->route()->parameter('<route_param_name>');`
Here, "route_param_name" is the binding key, which can be found by just dumping `var_dump(request()->route()->parameters());`
@lambae96  in your case it will be 'stock'
2. Get the object by ID:
`model = $form->model()->find($id);`

So, the final code of mine was:
`if ($form->isEditing())
        {
            $id = request()->route()->parameter('config');
            $model = $form->model()->find($id);
        }`

**Comment by mintzhao** [comment]
overwirte the following code:
```
    public function edit($id, Content $content)
    {
        return $content
            ->title($this->title())
            ->description($this->description['edit'] ?? trans('admin.edit'))
            ->body($this->form($id)->edit($id));
    }
```

**Comment by xx10n31y** [comment]
> I tried to access the model value, but it is only accessing the model, not the real object. So, I made it as follows:
> 
> 1. Get the ID of model from the route as follows:
>    `$id = request()->route()->parameter('<route_param_name>');`
>    Here, "route_param_name" is the binding key, which can be found by just dumping `var_dump(request()->route()->parameters());`
>    @lambae96  in your case it will be 'stock'
> 2. Get the object by ID:
>    `model = $form->model()->find($id);`
> 
> So, the final code of mine was:
> `if ($form->isEditing()) { $id = request()->route()->parameter('config'); $model = $form->model()->find($id); }`

thanks a lot dude, works for me

**Comment by ohmydevops** [comment]
> I tried to access the model value, but it is only accessing the model, not the real object. So, I made it as follows:
> 
> 1. Get the ID of model from the route as follows:
>    `$id = request()->route()->parameter('<route_param_name>');`
>    Here, "route_param_name" is the binding key, which can be found by just dumping `var_dump(request()->route()->parameters());`
>    @lambae96  in your case it will be 'stock'
> 2. Get the object by ID:
>    `model = $form->model()->find($id);`
> 
> So, the final code of mine was: `if ($form->isEditing()) { $id = request()->route()->parameter('config'); $model = $form->model()->find($id); }`

works for me and save my day

**Comment by optiktr** [comment]
You can use this for get ID.

`          $string = URL::current();
          $explode = explode('/article/', $string);
          $explode = explode('/edit', end($explode));
          $last = $explode[0];
          dd($last);
`
