### ISSUE TITLE
edit与create的mode属性都为“create”，setmode方法并未起作用  

### ISSUE THREAD

**Issue by lvtu0316** [z-song/laravel-admin#1631]
- Laravel Version: 5.5.28
- PHP Version:7.0.22
- Laravel-admin:  1.5.x-dev

### Description:
当使用ismode方法判断form是“create”还是“edit”方法时，发现一直是“create”，查看源码发现，在form-》edit方法中，设置了mode为“edit”，但是似乎并未生效。
 /**
     * Generate a edit form.
     *
     * @param $id
     *
     * @return $this
     */
    public function edit($id)
    {
        $this->builder->setMode(Builder::MODE_EDIT);
        $this->builder->setResourceId($id);

        $this->setFieldValue($id);

        return $this;
    }

**Comment by NickCoolii** [comment]
@lvtu0316 sorry, I can't understand correctly, but maybe this hint will be useful:
https://github.com/z-song/laravel-admin/issues/1348

**Comment by lvtu0316** [comment]
When you submit a form, how to judge whether the execution is create or edit？
How to use the ismode method？
The value of this method is always create。

**Comment by NickCoolii** [comment]
@lvtu0316 look at link provided above.
![default](https://user-images.githubusercontent.com/16125559/35434837-9ea851f0-0299-11e8-9629-bf0d7e67269c.png)

**Comment by lvtu0316** [comment]
If the primary key is not a number, but string?
I'm using in determine whether the request method is patch or post

**Comment by NickCoolii** [comment]
@lvtu0316 maybe this would help you:
http://laravel-admin.org/docs/#/en/model-form-validation?id=form-validation
```
    // If it is not an edit state, add field unique verification
    if (!$id = $form->model()->id) {
        return 'unique:users,email_address';
    }
```
