### ISSUE TITLE
求助   如何在编辑form时获取数据表中的指定字段

### ISSUE THREAD

**Issue by TerryDaDa** [z-song/laravel-admin#1632]
- Laravel Version: 最新
- PHP Version:最新
- Laravel-admin:最新

比如说数据表有个字段叫status，我想在它为1时 运行$form->disableSubmit();

代码应该是这样写的吧：

if(不知道怎么获取这个status)
    $form->disableSubmit();

求教 这个status要怎么写才能得到它呢？谢谢。

**Comment by yang5664** [comment]
假如這樣的話？
```
$form->model()->status;
```

**Comment by dogelin** [comment]
楼主应该是想在编辑未提交的时候就获取到编辑的数据并判断吧，铜球方法，怎么写ajax啊

**Comment by z-song** [comment]
@TerryDaDa @dogelin 参考#1629
