### ISSUE TITLE
强制启用 https  修改admin.php未生效

### ISSUE THREAD

**Issue by iyueshang** [z-song/laravel-admin#1635]
- Laravel Version: #.#.#5.5
- PHP Version:7.`
- Laravel-admin: #.#.#1.5

### Description:
我强制启动https以后。导致admin 资源文件跨域，我讲admin.php 中secure修改为true，但是配置未生效

**Comment by iyueshang** [comment]
谢谢大佬

**Comment by yang5664** [comment]
試試 
```
php artisan config:clear 
php artisan config:cache
```
