### ISSUE TITLE
如何把筛选按钮去掉，所有筛选放放到页面上，不用弹出那种样式的 ？

### ISSUE THREAD

**Issue by changPHP** [z-song/laravel-admin#1638]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

**Comment by luck-token** [comment]
把前端模板复制一份

通过

```
app('view')->prependNamespace('admin', resource_path('views/admin'));
```

加载自定义模板

https://github.com/z-song/laravel-admin/issues/943

**Comment by changPHP** [comment]
1.5的版本需要手动修改了吗？我记得1.4好像可以更改吧

**Comment by L-xiaoxi** [comment]
请问你怎么改的
