### ISSUE TITLE
某个字段设置了editable，修改并保存后，我想刷新一下页面，该如何设置？

### ISSUE THREAD

**Issue by wjctim** [z-song/laravel-admin#1639]
- Laravel Version: 5.5.28
- PHP Version: 7.0.1
- Laravel-admin: 1.0

### Description:
某个字段设置了editable，如：$grid->sort()->editable('select', [0,1,2,3])。修改并保存后，我想刷新一下页面，该如何设置？

### Steps To Reproduce:
现在是只能局部刷新单条记录的数据

**Comment by dogelin** [comment]
哥们，你是怎么解决的，我不想要局部刷新，想全局刷新

**Comment by laraCai** [comment]
哥们解决了吗？能给个提示吗

**Comment by chenjiabin** [comment]
$script = <<<JS
$('.class').on('save', function(e, params) {
   $.pjax.reload('#pjax-container');
});
JS;
        Admin::script($script);

**Comment by faydanube** [comment]
> * Laravel Version: 5.5.28
> * PHP Version: 7.0.1
> * Laravel-admin: 1.0
> 
> ### Description:
> 某个字段设置了editable，如：$grid->sort()->editable('select', [0,1,2,3])。修改并保存后，我想刷新一下页面，该如何设置？
> 
> ### Steps To Reproduce:
> 现在是只能局部刷新单条记录的数据

@wjctim 

兄台，怎麽刷新頁面啊。

**Comment by wjctim** [comment]
> > * Laravel Version: 5.5.28
> > * PHP Version: 7.0.1
> > * Laravel-admin: 1.0
> > 
> > ### Description:
> > 某个字段设置了editable，如：$grid->sort()->editable('select', [0,1,2,3])。修改并保存后，我想刷新一下页面，该如何设置？
> > ### Steps To Reproduce:
> > 现在是只能局部刷新单条记录的数据
> 
> @wjctim
> 
> 兄台，怎麽刷新頁面啊。

没有好的方式刷新

**Comment by wjctim** [comment]
> 哥们，你是怎么解决的，我不想要局部刷新，想全局刷新

没有解决

**Comment by wjctim** [comment]
> 哥们解决了吗？能给个提示吗

没有解决
