### ISSUE TITLE
【BUG Report】特定情况下在表格页面点击筛选后会出现阴影遮蔽层无法恢复的情况

### ISSUE THREAD

**Issue by kong36088** [z-song/laravel-admin#1640]
![image](https://user-images.githubusercontent.com/11497913/35051247-c24b3822-fbdf-11e7-869b-b5c8880e54d7.png)

表格页面——筛选——输入筛选并提交——点击一个项目进行编辑（页面这时进行了跳转）——使用浏览器返回键返回到上一个页面（或者用js代码实现history.back()返回到上一页）——再次更改筛选条件并提交——bug出现：页面内容无法点击，阴影遮蔽层不消失

**Comment by yang5664** [comment]
這個問題發生的原因是在按下“撤銷”馬上按下“篩選”就會發生。
我自己的作法是，在“撤銷”動作還沒有完成時“篩選”按鈕會先隱藏，等到完成後按鈕會自己出現。
```
$('body').on('click', '.btn-group > .btn-reset', function(){
    $('.btn-group > .btn-filter').css('display', 'none');
});

```

**Comment by kong36088** [comment]
@yang5664 但是我的操作并不是点击撤销后立即点击筛选时发生的。而是跳转到另一个页面后返回当前页面后点击筛选时发生的

**Comment by yang5664** [comment]
其實你可以看到highlight的那一段
<img width="1132" alt="screen shot 2018-01-24 at 12 21 55 am" src="https://user-images.githubusercontent.com/5953010/35287117-9c9bb266-009c-11e8-842d-03bda765376c.png">
只要當前的程序還在loading，這時候”有機會“按下“篩選”的按鈕，都會造成這個問題。

**Comment by kong36088** [comment]
@yang5664 貌似确实是因为loading的原因。但是我当前页面其实已经loading完毕了，是不是状态标记时有点错误了？我唯一能想到的一个比较暴力的解决办法是点击“筛选”按钮后，主动把 "in"这个控制遮蔽层的class给去掉。
不知道还有没有更有效的解决办法，还请不吝赐教！

**Comment by yang5664** [comment]
我目前唯一想到的是利用pjax的complete
<img width="900" alt="screen shot 2018-01-24 at 12 30 51 am" src="https://user-images.githubusercontent.com/5953010/35287721-03bec1b2-009e-11e8-9c5d-2c20578b6b16.png">

**Comment by kong36088** [comment]
@yang5664 十分感谢你的分享！

**Comment by never615** [comment]
+1 ,基础库看能修复一下么

**Comment by MoonLiu666** [comment]
我也遇到同样的问题

**Comment by ikerlin** [comment]
请问这个问题修复了吗？，如何修复？当前使用版本：v1.5.14
