### ISSUE TITLE
开启https后，唯独font-awesome跨域

### ISSUE THREAD

**Issue by hjlarry** [z-song/laravel-admin#1642]
- Laravel Version: 5.5.28
- PHP Version:7.1.13
- Laravel-admin: 1.5.x-dev

### Description:
目前config里配的app的url是https的、配的admin的secure也是true。
无论使用http或者https访问页面总体都是正常的，唯独在使用http访问时，图标是没有的，页面提示是：
Access to Font at 'https://aaa.com/vendor/laravel-admin/font-awesome/fonts/fontawesome-webfont.woff2?v=4.5.0' from origin 'http://aaa.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://aaa.com' is therefore not allowed access.

**Comment by hjlarry** [comment]
some reason for cache

**Comment by lePig** [comment]
我开启了secure=true也出现字体文件访问出错。请问下 你怎么解决的？
