### ISSUE TITLE
列表页面js报错，会刷新两次

### ISSUE THREAD

**Issue by dogelin** [z-song/laravel-admin#1643]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin:1.5.7

### Description:
起因是我在操作列弄了个预览操作，点击会跳出一个模态框
![lm86 2 zc ac3a2e 4nw wv](https://user-images.githubusercontent.com/17040400/35090922-2deb7eac-fc76-11e7-99bc-75f22f8b506e.png)

因为尽量不改vender里面的数据原因，我是在CheckRow类里面通过点击预览的标签时将模态框的html插入到tabel.blade.php文件里面
![z g2jz5wd4897x udhp ui](https://user-images.githubusercontent.com/17040400/35091247-fed1cb8e-fc76-11e7-9dd7-2ee1af13fce1.png)
后面的操作一切顺利，预览效果也做出来了
但是后面我发现当修改完某些操作刷新的时候，或者点击左侧的导航进入到这个页面的时候，它会刷新完后再刷新一次，然后这次刷新就一直保持正在刷新的状态不能做其他操作，然后我发现js报错
![nf7 j3_0xc33jjgp9m ogu](https://user-images.githubusercontent.com/17040400/35091356-6118bdf2-fc77-11e7-9e12-682761fbb408.png)
![au yo z1g5lk zurl _7af](https://user-images.githubusercontent.com/17040400/35091423-9b475c5e-fc77-11e7-99b5-e7789877b7f0.png)

![qa32t hl y5 gpqx1royi](https://user-images.githubusercontent.com/17040400/35091549-e3df0d04-fc77-11e7-9e27-06e7d6580965.png)

这些错误在我点击浏览器的刷新的时候变正常，js也不报错，刷新也只刷新一次，但是在我做其他操作然后自动刷新后又会js报错，所以我只能在它出错保持刷新的状态时手动点击浏览器刷新。
### Steps To Reproduce:
所以是哪个方面出错了呢，难道不能插入html语句到table.balde.php里面嘛

**Comment by yang5664** [comment]
這個部分是 js的問題，你可以試試看單純一點的html code再試試看，
$('.box-header').append  換成 $('.box-header').html("<div>hello</div>")   // 改用 html

**Comment by dogelin** [comment]
@yang5664 直接把模态框放进blade里面不用append插入的话是不会报错的，但是vender里面的代码不是尽量不用改吗，所以我才采用append插进去代码的，这样vender里面的table.blade.php代码就不会有变化，所以html（）也是 不可取的，因为会把table.blade.php本来的html代码覆盖

**Comment by dogelin** [comment]
因为是js问题，所以close了
