### ISSUE TITLE
config secure 只开启了asset的https 但是忽视了route

### ISSUE THREAD

**Issue by kslr** [z-song/laravel-admin#1644]
- Laravel Version: #.#.# 
5.5
- PHP Version:
7.2
- Laravel-admin: #.#.#
1.5
### Description:
路由没有开启https 如果强制开启会导致post表单时丢失请求

### Steps To Reproduce:
开启后台https 开启主站https
后台导出以及from action地址都是http

**Comment by yang5664** [comment]
會跟 .env 有關係嗎？
```
APP_NAME=Laravel
APP_ENV=local
APP_KEY=base64:mptAo06gxfbuv7X4wujcp6whxQli0IqEfaD+XQEk/7U=
APP_DEBUG=true
APP_LOG_LEVEL=debug
APP_URL=http://localhost    <============ 這一行

```
記得 php artisan config:clear  &&  php artisan config:cache

**Comment by kslr** [comment]
@yang5664 app url和admin secure都是確定的

**Comment by kslr** [comment]
我使用cloudflure的重定向到https理論上是不會有影响的。
但是部分form url是http 这就导致了我在提交的时候数据丢失。

**Comment by z-song** [comment]
form的action是通过`request()->getScheme()`获取scheme来拼接的完整url，

你试试用dd一下request()->getScheme()看打印的是什么？

**Comment by kslr** [comment]
@z-song
```php
request()->getScheme()   https
dd(env('APP_URL'))   https
dd(config('admin.secure'));  true
```
值得一提的是，我在app/Providers/AppServiceProvider.php的boot强制全部使用https
```php
if (env('APP_ENV') === 'production') {
    URL::forceScheme('https');
 }
```

**Comment by ahu** [comment]
我觉得此问题依旧有价值。建议开启secret为true 后，route 也启用https。

应用场景是这样的：阿里云负载均衡https 请求，监听的后端是 http——这是官方推荐的设置模式，折腾过前443后443貌似不行，还设置过nginx 的80强制跳转443，结果在负载均衡那无限循环了...所以，最终只能是前443后80——也即laravel-admin 的 nginx vhost 是监听在80

结果访问laravel-admin 登录后 URL 从https 跌回http... 此时页面部分元素无法正常加载。查看 Chrome（版本 67.0.3396.30（正式版本）beta （64 位）） console 提示：

Access to Font at 'https://xxx.com/vendor/laravel-admin/google-fonts/fonts/Source-Sans-Pro-Bold.ttf' from origin 'http://xxx.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://xxx.com' is therefore not allowed access.

然而，https 是阿里云负载均衡控制的，无法设置Access-Control-Allow-Origin，在 nginx 设置是无用的。

所以，只有一条路：那就是表单提交也 https 才行了，相当于laravel-admin最好也是强制 https。

说来奇怪，我和@kslr 一样在lavaral 设置了URL::forceScheme('https')，但没毛用，貌似被laravel-admin直接忽略或绕过了,23333333...

**Comment by kslr** [comment]
@ahu 我翻到一个有意思的issue
https://github.com/laravel/framework/issues/4208

**Comment by lePig** [comment]
@ahu 我设置了`URL::forceScheme('https')`同样没用。

**Comment by kslr** [comment]
@ahu 跨域只有全部上https可解
@lePig 你给的资料太少了

**Comment by lePig** [comment]
@kslr 我后来调试了一下发现和 @ahu 说的情况一只。
`config/admin.php`中的secure为true只是对admin_url()这些后台函数有用。并不会对route()有用

而URL::forceScheme('https')是对route()有用。

**Comment by heimasi** [comment]
@ahu 我也使用了阿里云负载均衡https，后端http，larave-admin登录时要等很久，但是其实已经登录成功了，这时直接刷新页面就能进到登录后的页面，但是如果不手动刷新要等好久还会报错。这是什么情况，你那边是这样的吗？如何解决的？多谢
