### ISSUE TITLE
提供一个创建管理员用户的 console 命令

### ISSUE THREAD

**Issue by bestony** [z-song/laravel-admin#1646]
- Laravel Version: 5.5.*
- PHP Version:7.0
- Laravel-admin: 1.5.* 

### Description:
在项目通过 git 部署到 server 端时，没有了管理员用户。需要一个命令来创建超级管理员。

**Comment by z-song** [comment]
安装完成之后默认就有一个admin/admin用户，用这个用户登录就可以创建其它用户

**Comment by bestony** [comment]
@z-song  在进行 Git 管理后，迁移到生产环境后，migrate 是无法生成新的用户的。不可能在生产环境现场配置安装本框架。

**Comment by z-song** [comment]
你可以自己写一个command，逻辑也比较简单  就是往admin_users表里面插一条数据

**Comment by ljf1172361058** [comment]
use Illuminate\Support\Facades\DB;
        use Carbon\Carbon;
        
        // 创建管理员用户
        DB::table('admin_users')->insert([
            'username' => 'admin',
            'password' => '$2y$10$8ZC4GvYWkM9VYERg/jbMIui7OXfSWJUTLrqT9YP4oUXQgMLsEz/kK', // admin
            'name' => 'Administrator',
            'created_at' => Carbon::NOW(),
            'updated_at' => Carbon::NOW(),
        ]);

在填充数据类里面加上这段增加管理员账号的代码, 这就是安装完成之后的admin用户

**Comment by maojindao55** [comment]
vi database/seeds/DatabaseSeeder.php
```
<?php

use Illuminate\Database\Seeder;

class DatabaseSeeder extends Seeder
{
    /**
     * Seed the application's database.
     *
     * @return void
     */
    public function run()
    {
        // $this->call(UsersTableSeeder::class);
         $this->call(\Encore\Admin\Auth\Database\AdminTablesSeeder::class);// add the code

    }
}
```
php artisan db:seed
