### ISSUE TITLE
Split one form into two boxes / fieldsets

### ISSUE THREAD

**Issue by avifatal** [z-song/laravel-admin#1647]
Hi,
I have a need to split one form into two horizental fieldsets.
im not taling about 2 fielfd in a row, im talking about real fieldset.
Something like:

https://i.imgur.com/wk2lbZ6.png
Is it possible?
Thanks

**Comment by NickCoolii** [comment]
Hi @avifatal 
Are you searching something like this?
![default](https://user-images.githubusercontent.com/16125559/35186472-f1d877b0-fe25-11e7-9a57-1545001ccfd8.png)

Then check this:
https://github.com/z-song/laravel-admin/issues/872#issuecomment-336665176

**Comment by avifatal** [comment]
Thanks. But now. This is column per field.
I need fieldset. Or box.
See my image
