### ISSUE TITLE
419 unknown statu

### ISSUE THREAD

**Issue by conlin** [z-song/laravel-admin#1651]
- Laravel Version: 5.5.32
- PHP Version: 7.1.10
- Laravel-admin: 1.5.8

### Description:
新建菜单的，点击提交以后无法创建成功，Headers 返回：

Status Code: 419 unknown statu

**Comment by zhsb190101** [comment]
暫時可以在VerifyCsrfToken裡面except掉'admin/auth/menu'解決。

**Comment by samfrm** [comment]
Open this file : vendor/encore/laravel-admin/src/Controllers/MenuController.php
in `index()` method after this line `$form->action(admin_base_path('auth/menu'));`
add this : 
`$form->hidden('_token')->default(csrf_token());`
Refresh the page, it will work.

**Comment by lianke** [comment]
修改composer.json,将 laravel-admin 的版本限制为 1.5.5，然后更新
发现 v1.5.8 是有这个问题,
我不建议去修改框架,一旦框架更新 ,你的代码就会被覆盖,先回滚旧版本,等待老大更新.

**Comment by z-song** [comment]
@conlin @zhsb190101 @lianke @samfrm Update to latest version (v1.5.9)

**Comment by conlin** [comment]
OK

**Comment by Ladel** [comment]
This correction was not necessary. just need to fix the previous error.
#1612 
uncorrect `@if( ! $method == 'GET' )`
correct `@if( $method != 'GET' )`

**Comment by PerfectLive** [comment]
百度编辑器,上传图片时提示419,laravel-admin版本为1.6
