### ISSUE TITLE
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

### ISSUE THREAD

**Issue by cnbattle** [z-song/laravel-admin#1652]
- Laravel Version: 5.5.32
- PHP Version: 7.2.0
- Laravel-admin: 1.5.8

### Description:
在创建和编辑时,点击保存报500 , 查询代码 显示
Parse error: syntax error, unexpected '?', expecting variable (T_VARIABLE)

但是数据更新成功了

### Steps To Reproduce:
可留个邮箱,我发网址登录账号和密码

**Comment by cnbattle** [comment]
新情况:原来是php7.0, 现在换成7.2了 ,没有上述报错

**Comment by pcfjojo** [comment]
Superb thanks a lot.. i also had the same issue, and resolved by switching php version

**Comment by priyeshwar-AGL** [comment]
how to switch 7.2 to 7.0 in php

**Comment by EJellyfish** [comment]
同样的问题，我是在使用邮件发送的时候报的错，提高php版本就好了……不知道为什么
