### ISSUE TITLE
multipleSelect录入时和编辑时取值不同

### ISSUE THREAD

**Issue by sdauma** [z-song/laravel-admin#1654]
- Laravel Version: 5.5.32
- PHP Version:7.2
- Laravel-admin: 1.5.x-dev

### Description:

![tim 20180123090201](https://user-images.githubusercontent.com/35126877/35253302-a1b2d27a-001f-11e8-8848-e9cb935b2998.png)

multipleSelect  ，action=store（录入）时，获取的是title的，如‘消费送黄金,推荐送现金,进店增大礼’。action=update（编辑）时是id如'1,2,3'

**Comment by z-song** [comment]
dump一下录入和编辑时传入的`$appauthtoken_id`是否相同

**Comment by sdauma** [comment]
![4](https://user-images.githubusercontent.com/35126877/35254333-b636d96c-0024-11e8-8a12-a51cab5fcf33.png)
![3](https://user-images.githubusercontent.com/35126877/35254631-09c39f06-0026-11e8-9616-38965bd422d2.png)

@z-song  $template_benefit_info=array(1=>'消费送黄金',2=>'推荐送现金',3=>'进店增大礼');如果store时存入‘消费送黄金,推荐送现金,进店增大礼’,如果update存入'1,2,3'。

**Comment by sdauma** [comment]
我自己的解决办法是，store时根据‘消费送黄金,推荐送现金,进店增大礼’获取到'1,2,3'。update时不用处理。
