### ISSUE TITLE
上传图片样式设置问题

### ISSUE THREAD

**Issue by dogelin** [z-song/laravel-admin#1656]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5.7

### Description:
图片上传的功能是没有问题的，但是每次修改上传的时候并排两个图片
![default](https://user-images.githubusercontent.com/17040400/35262737-d3e41d18-0050-11e8-9d1d-430ab8ba8e66.png)

下面还有两小图标，本来我以为没什么，是设计本来就是这样，官网demo样式也是这样，但是昨天发现另外个人的上传图片样式不一样
![tim 20180123100730](https://user-images.githubusercontent.com/17040400/35262746-dc99488e-0050-11e8-9a2e-b5e738f4566c.png)

修改图片会替换掉之前的，而且下面图标和功能不一样，但是那个人说他根本没做什么操作，本来就长这样，所以请教作者，这个图片上传的样式还能设置吗，怎么设置。万分感谢

**Comment by wangxiaohui0312** [comment]
这个解决没
