### ISSUE TITLE
关于Form的多列显示

### ISSUE THREAD

**Issue by morix-gao** [z-song/laravel-admin#1657]
Laravel Version: 5.4
PHP Version:5.6
Laravel-admin: 1.4
Description:
如果一个表单的输入项较多，Tab页内还想分组（列），或者一个form下想多列显示的话，该怎么处理呢？必须要自定义吗？
我尝试了html（）方法，但是它在formgroup内，无法将多个formgroup框定在2个html（<> xxx </>）段内。

**Comment by morix-gao** [comment]
同时要赞一个，这个项目很棒！

**Comment by dogelin** [comment]
可以使用tab解决
参考http://laravel-admin.org/docs/#/zh/model-form-fields?id=model-form-tab

**Comment by morix-gao** [comment]
Tab也不够用，Tab里边还能再嵌套吗？我没试成功

**Comment by z-song** [comment]
1.4 不支持这个feature
