### ISSUE TITLE
關於客製化或微調encore/laravel-admin下的views

### ISSUE THREAD

**Issue by yang5664** [z-song/laravel-admin#166]
請問有考慮將encore/laravel-admin下的views，publish到resources/views/encore/laravel-admin，
這樣子若有微調view可以不直接動vendor下的原始碼。
```ruby
// 客製化視圖 laravel-admin
$this->loadViewsFrom(resource_path('views/vendor/encore/laravel-admin'), 'admin');
$this->loadTranslationsFrom(resource_path('lang/vendor/laravel-admin'), 'admin');

// publish views & lang
$this->publishes([
    'vendor/encore/laravel-admin/views' => resource_path('views/vendor/encore/laravel-admin'),
    'vendor/encore/laravel-admin/lang' => resource_path('lang/vendor/laravel-admin')
], 'laravel-admin');
```
參考：https://laravel.com/docs/5.3/packages#views
Overriding Package Views && Publishing Views

**Comment by z-song** [comment]
可以把`vendor/encore/laravel-admin/views`下的文件，copy到`resources/views/laravel-admin`下，然后新加一个`ServiceProvider`,用`$this->loadViewsFrom(resource_path('views/laravel-admin'), 'admin');`覆盖掉`laravel-admin`的views.

**Comment by dev-kang** [comment]
在1.5版本下，重新定义一个ServiceProvider无法覆盖原来的views命名空间定义。

**Comment by dev-kang** [comment]
针对1.5版本可以定义一个新的ServiceProvider，可以使用下面的方法
` $this->app['view']->replaceNamespace('admin', resource_path('views/store'));` 
进行实现覆盖。
