### ISSUE TITLE
n+1问题

### ISSUE THREAD

**Issue by AaronChengHao** [z-song/laravel-admin#1663]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5.x-dev

### Description:
hi，z-song，请问下，在后台读取列表的时候，这么解决模型一对一的问题呢？ 每一行数据都会查询关联的表，   同时我使用了with方法，提前调用，也没效果。

**Comment by z-song** [comment]
我这边不用with也不会产生n+1问题，贴代码吧

**Comment by AaronChengHao** [comment]
![image](https://user-images.githubusercontent.com/20119217/35430220-4c0f20b8-02b2-11e8-8c14-3c67956da34a.png)
这就是scenic模型 一对一的方法

**Comment by z-song** [comment]
已修复
