### ISSUE TITLE
我在提交图片的时候遇到一个问题，以下是我的配置信息和报错信息

### ISSUE THREAD

**Issue by changPHP** [z-song/laravel-admin#1664]
![image](https://user-images.githubusercontent.com/26112014/35316536-266b8794-010d-11e8-9ba7-c74c1d49416e.png)

![image](https://user-images.githubusercontent.com/26112014/35316551-3c6979e8-010d-11e8-8305-3ba0eb3be25c.png)

正常选择文件上传后

![image](https://user-images.githubusercontent.com/26112014/35316576-5faae50e-010d-11e8-9986-f6588099ed29.png)

点击提交时页面未跳转，图片地址在数据库中也没有更换掉，后台返回错误 422

![image](https://user-images.githubusercontent.com/26112014/35316619-9f6804e2-010d-11e8-9244-3cf2eece5b74.png)

![image](https://user-images.githubusercontent.com/26112014/35316653-cf04e454-010d-11e8-94c2-cadddb1645ca.png)

还望各位帮忙解答，谢谢！

**Comment by z-song** [comment]
根据第三张图的exception trace，错误是中间件`spite/laravel-pjax`抛出的, 你把这个中间件从后台的路由中去掉

**Comment by changPHP** [comment]
谢谢~
