### ISSUE TITLE
Multi-database Admin::grid model

### ISSUE THREAD

**Issue by jan-obtam** [z-song/laravel-admin#1668]
- Laravel Version: 5.5.32
- PHP Version: 7.1.12
- Laravel-admin: 1.5.x-dev

### Description:
Is it possible to implement a multiple database connection for `Admin::grid( Model::class, function(){} );`? Like maybe provide a pre-determined model connection like so:

```

$users = new User::connection('test-db');

return Admin::grid( $users, function(){});
```

**Comment by z-song** [comment]
Set database connection in your model like :
```php
class User extends Model 
{
    protected $connection = 'test-db';
}
```

**Comment by jan-obtam** [comment]
Hmmm. Not really my use case. Basically, what I want to achieve is to allow multiple app deployments with the same database schema be accessible using the same models.

So deployment A, with Database A, and deployment B with Database B can still be accessed by the same model, for example, Employee:: model. What we want to achieve is to have multiple app deployments being monitored by the same application. (Multiple database connections) Another point we want to achieve hotswapping/fast additions of deployments by simply defining a config file. In this way, I can easily use this [class](https://lukevers.com/2015/03/25/on-the-fly-database-connections-with-laravel-5).

**Comment by jan-obtam** [comment]
I think I can achieve this by instead of just having a Model instance on the first parameter, allow a Builder object also, because the OTF class returns a builder object.
