### ISSUE TITLE
筛选的类名和数据库字段相同,导致输入框变形!!

### ISSUE THREAD

**Issue by UpGod** [z-song/laravel-admin#1669]
```
$grid->filter(function ($filter){
                $filter->like('content', '内容');
            });
```
`content` 会给input加`content`类,结果变高

**Comment by z-song** [comment]
打开 `public/vendor/laravel-admin/laravel-admin/laravel-admin.css`，写样式覆盖掉AdminLte的样式

参考 https://github.com/z-song/laravel-admin/blob/master/resources/assets/laravel-admin/laravel-admin.css
