### ISSUE TITLE
select()->load() can't select database result

### ISSUE THREAD

**Issue by zinmyotun-gic** [z-song/laravel-admin#1670]
When in edit mode,
select()->load() is not select upon on database result
it always show top option.

For e.g.
if DB result for test 1 => 'id' : 1, test2_id = '1'

test2_id - options data ['0' => 'Option1', '1'=>'Option2', '3'=>'Option3']

```
$form->select('test1')->options(Test::all()->pluck('name', 'id'))->load('test2_id', '/admin/api/test2', 'id', 'name')->rules('required');

$form->select('test2_id')->options(Test2::all()->pluck('name', 'id'))->rules('required');
```
expected result is Test2 select box should be select Option2
instead it always select Option1

**Comment by orazz** [comment]
i have same problem, did you resolve this problem?
