### ISSUE TITLE
一对多关联模型 multipleImage 上传图片上传不了

### ISSUE THREAD

**Issue by zhonghaibin** [z-song/laravel-admin#1675]
- Laravel Version: 5.5.32
- PHP Version:PHP/7.1.9
- Laravel-admin: 1.5.x-dev

### Description:
一对多关联模型 用多图上传组件上传图片提示必须是一张图片。导致提交不了

### Steps To Reproduce:
![qq 20180125173713](https://user-images.githubusercontent.com/22255693/35381467-583f1340-01f7-11e8-8a34-fb7806c2693d.jpg)
![qq 20180125174635](https://user-images.githubusercontent.com/22255693/35381498-7496ae36-01f7-11e8-8d99-b5d127584665.jpg)

**Comment by bing8u** [comment]
这个hasMany特别多问题（比如：一对多的多个图片，后面所有图片只会显示第一组的），hasMany中多图不支持。用多文件代替。

**Comment by zhonghaibin** [comment]
@bing8u 添加 在一对多的中用image()->removable(),也删除不了已经上传的文件。

**Comment by bing8u** [comment]
我也是有这个删除文件的问题没有解决。
不妨圈作者并将此问题反馈，告知hasMany中的一系列错误。
