### ISSUE TITLE
使用扩展自定义组件，加入的组件或者编辑器，需要刷新页面才能使用

### ISSUE THREAD

**Issue by boomyanzi** [z-song/laravel-admin#1679]
- Laravel Version: 5.5.#
- PHP Version: 7.0
- Laravel-admin: 1.5.5

### Description:
有特殊需求需要加入组件或者更换编辑器
发现直接在当前页上打开，js就无效，必须刷新后才能使用
有谁知道怎么解决吗，我准备把按钮都改成在新页面打开

**Comment by maojindao55** [comment]
也遇到了，解决了吗？
