### ISSUE TITLE
Model Grid filter on joined table

### ISSUE THREAD

**Issue by samfrm** [z-song/laravel-admin#1681]
How to make filter on column came from another(join) table? 
Example : 

```
$grid->user('User')->display(function() {
return  DB::table('users')->where('id', $this->user_id)
                    ->pluck('name')->first();
            })->sortable();
```
I want to make filter for column `name` which is on my Users Table.

**Comment by BrandOriented** [comment]
Try something like this:
`
                $filter->where(function ($query) {
                    $input = $this->input;
                    $query->whereHas('users', function ($query) use ($input) {
                        $query->whereIn('id', $input);
                    });
                }, 'Users')->multipleSelect(User::all()->pluck('name', 'id'));
`
