### ISSUE TITLE
select联动 js报错：Uncaught TypeError: Cannot use 'in' operator to search for 'length' in

### ISSUE THREAD

**Issue by citywill** [z-song/laravel-admin#1684]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5.9

### Description:
select联动出错

### Steps To Reproduce:
变更第一个select后报错

### 修复方法：
/src/Form/Field/Select.php
https://github.com/z-song/laravel-admin/blob/4fd32e48d8aeb574685a5b502816657844bb405c/src/Form/Field/Select.php#L118

替换成
data: $.map(JSON.parse(data), function (d) {

**Comment by z-song** [comment]
你接口的content-type要是json, 就会自动解析成js对象不需要用JSON.parse解析一遍
