### ISSUE TITLE
能否通过hidden属性来修改值

### ISSUE THREAD

**Issue by gilberthedd01** [z-song/laravel-admin#1690]
有个编辑id属性，需要记录最后操作用户uid
$uid = 2;
$form->hidden('uid','')->value($uid);
我在构建表单的时候尝试这样设置隐藏域。
新增操作正常，当edit的时候 uid隐藏域还是会将上次获取的值返回。无法进行修改。

当然重写update 方法是可以实现。

想问下有没更好的方法来实现？

**Comment by gilberthedd01** [comment]
目前不想重写，而又达到效果的方法是。
在edit页面加载时，用js去替换掉隐藏域的值。

**Comment by z-song** [comment]
给模型加上保存钩子来实现：

```php
class MyModel extends Model 
{
    protected static function boot()
    {
        parent::boot();

        // 修改记录的时候触发
        static::c(function($model) {
            $model->uid = Admin::user()->id;
        });
    }   
}
```
