### ISSUE TITLE
Between and DateTime filters

### ISSUE THREAD

**Issue by mitris** [z-song/laravel-admin#17]
fix JS
now you use 

    protected $js = [
        **'moment/min/moment.min.js',**
        'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js'
    ];

change to 

    protected $js = [
        'moment/min/moment-with-locales.min.js',
        'eonasdan-bootstrap-datetimepicker/build/js/bootstrap-datetimepicker.min.js'
    ];

and remove 
$js[] = "moment/locale/{$options['locale']}.js";

**Comment by z-song** [comment]
ok  I'll fix this later.

**Comment by z-song** [comment]
issue fixed  thx!
