### ISSUE TITLE
图片上传的建议

### ISSUE THREAD

**Issue by seqd** [z-song/laravel-admin#170]
这个后台管理很好用，先感谢 @z-song 

在使用过程中，我发现多次上传同一文件名的图片，系统会删除之前上传的图片且保存在服务器上的图片名称每次上传后都发生变化。这样在同一文件名但不同内容的情况下将会影响到已上传文件的路径

由于个人太菜，提出以下建议望大神采纳

1. 上传的文件先存放到os临时文件
2. 将os临时文件用md5_file()取得HASH
3. 用HASH作为最终上传的文件名

这样就可以保证上传的文件不重复且与原文件名称无关，如果能做到前端直接验证文件md5，就基本实现“秒传”了

**Comment by z-song** [comment]
目前的命名机制是，使用源文件名来存储，如果和文件同名的文件已经存在，则随机生成文件名，更新图片的时候会删除原文件，是为了避免遗留的文件后期无法清理

另外file和image组件提供name()方法来设置存储文件名：
```php
$form->image('picture')->name(function ($file) {
    return '你自定义的名字.'.$file->guessExtension();
});
```

**Comment by seqd** [comment]
这样同文件不同内容的图片就被“误杀”了，比如用户头像，存入数据库后。同名上传后以前的头像就消失了

**Comment by z-song** [comment]
按照你说的情况，更新头像的时候，如果只更新数据库记录，对原头像文件不处理的话，那原文件就成了脏文件，因为原文件在数据库里面已经没有了任何记录，它变成了`找不到的文件`。一个用户更新了十次头像，那么前九次的头像文件也没有办法找出来。

**Comment by seqd** [comment]
假如有10个用户更新头像的时候，文件名一样、内容都不一样。其他9个用户头像就会消失不见

**Comment by z-song** [comment]
更新头像的时候 删除的是数据库记录的原头像地址，不是删除目录下的同名头像文件

**Comment by seqd** [comment]
好像是我的数据库或者其他哪里出了问题
我把数据库清空然后新建编辑就没有掉文件了
万分感谢大神的耐心解答
