### ISSUE TITLE
一对一模型关联，不能保存关联数据

### ISSUE THREAD

**Issue by zbyjm6969** [z-song/laravel-admin#1708]
- Laravel Version: 5.5.32
- PHP Version: 7.2.1
- Laravel-admin: 1.5.*

### Description:
一个User，一个Phone，设置了一对一的关联，代码如下：
```php
UserModel
public function phone()
{
    return $this->hasOne('App\Models\Phone');
}

PhoneModel
public function user()
{
    return $this->belongsTo('App\User');
}
```
### 写了一个测试，是可以拿到手机号的
```php
$user = new \App\User();
$user_info = $user->find('2');
echo ($user_info->phone->phone);
```
---
但是在laravel-admin中无法显示&保存手机号
```php
$form->mobile('user.phone', '手机');
```

**Comment by dev-kang** [comment]
$form是通过哪个模型调用的？是UserModel 还是PhoneModel?

**Comment by zbyjm6969** [comment]
@dev-kang 是在UserModel中

**Comment by zbyjm6969** [comment]
Hey,
抱歉我之前没有看到邮件，我是通过Usermodel引用的。


--


Regards

Allen




在 2018-02-04 03:14:47，"DevKang" <notifications@github.com> 写道：


$form是通过哪个模型调用的？是UserModel 还是PhoneModel?

**Comment by nkjackzhang** [comment]
你的form用的User model，字段名就不能用user.xxx了，如果Phone表用code字段存号码，那应该用$form->mobile('phone.code', '手机');
a.b这种语法，a代表关系表的表名，b代表关系表里的字段
