### ISSUE TITLE
want to add confirm page before saved

### ISSUE THREAD

**Issue by zinmyotun-gic** [z-song/laravel-admin#1709]
I want to add a confirm page before saving to database.
Can I easily create confirm page?
Or is there away to do?

I want like below steps and is can be do with laravel-admin
1.Open Register page
2.Fill input
3.Show confirm page for input (no editable)
4.If something wrong go back to input page with input value
5.Show confirm page again (no editable)
6.Saving to databse
7.Show complete page

**Comment by tarikul05** [comment]
@z-song is there any way to do it 

> I want to add a confirm page before saving to database. Can I easily create confirm page? Or is there away to do?
> 
> I want like below steps and is can be do with laravel-admin 1.Open Register page 2.Fill input 3.Show confirm page for input (no editable) 4.If something wrong go back to input page with input value 5.Show confirm page again (no editable) 6.Saving to databse 7.Show complete page
