### ISSUE TITLE
编辑的时候如何拿到form里的数据进行处理后再显示？

### ISSUE THREAD

**Issue by ilevitate** [z-song/laravel-admin#1710]
- Laravel Version:5.5.*
- PHP Version: 7.1.12
- Laravel-admin: 1.5.*

### Description:
编辑的时候，怎么样才能在form里拿到数据进行操作后再输出？ 比如某个字段 amount，单位为分，我需要拿到这个数据将单位处理为 元 再输出。

**Comment by milkytsu** [comment]
请问如何解决了？

**Comment by milkytsu** [comment]
我用了get{FieldName}Attribute方法，写在model里，比如你要操作amout，就在相应的model里写一个方法：

`
public function getAmoutAttribute($value)
{
    return $value / 100;
}
`

**Comment by guandaxia** [comment]
@milkytsu 看来只能用这种方法了，谢谢

**Comment by imageslr** [comment]
我希望根据模型里的某个属性值展示不同的表单，比如邮箱未激活的时候才显示邮箱输入的表单项。请问这个要怎么实现？
