### ISSUE TITLE
请问一下form里面暂时不想存储的字段如何忽略？另外保存成功以后，未保存的字段如何继续获取回调使用？

### ISSUE THREAD

**Issue by dev-kang** [z-song/laravel-admin#1711]
- Laravel Version: 5.5.0
- PHP Version:7.1
- Laravel-admin: 1.5x-dev

### Description:
目前通过一下代码忽略保存字段
```
 $form->ignore(['image_files', 'description', 'cate_pid']);
```

如果在保存成功以后调用saved回调，如何继续使用未保存字段？

**Comment by z-song** [comment]
用 `request('description')`
