### ISSUE TITLE
表单验证失败以后，上传的图片消失，请问大家如何处理？

### ISSUE THREAD

**Issue by dev-kang** [z-song/laravel-admin#1712]
- Laravel Version: 5.5.0
- PHP Version: 7.1
- Laravel-admin: 1.5x-dev

### Description:

看demo也有这样的问题，如果保存验证未通过，上传的图片需要再次重新上传，这个问题怎么解决？

**Comment by z-song** [comment]
这个是`bootstrap-file-input`这个组件的限制，无法解决

**Comment by sayhei** [comment]
那么能否换个解决方案呢
