### ISSUE TITLE
Using Hyn tenancy with Laravel-admin

### ISSUE THREAD

**Issue by pcfjojo** [z-song/laravel-admin#1716]
@z-song 
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: latest

Description:
I am using  package for multi tenancy. 
https://laravel-tenancy.com/documentation/introduction/configuration
I could not change admin tables connection to the tenant connection.
If there any possible way to change this?

Even changing the connection in admin.php (config) some model use the default db connection.

**Comment by geekstek** [comment]
Yes, I am looking for it too!!
@pcfjojo do you have any idea of it?

**Comment by pcfjojo** [comment]
@geekstek 
 1. I copied admin folder 
2.  I put all admin related migration without passing the connection.
3. Also I have all basic insert query for create an admin. 

That's it.

**Comment by geekstek** [comment]
@pcfjojo Thank you for your share, I try your solution now, Thanks a lot!!

**Comment by geekstek** [comment]
@pcfjojo are you use laravel-admin for tenant db? or both (double laravel-admin for system and tenant)?

**Comment by pcfjojo** [comment]
No My tenent has it own admin panel and user. I dont use admin panel for system.

**Comment by geekstek** [comment]
Got it, thank you for your sharing :)
