### ISSUE TITLE
自定义form视图，如何知道当前在创建还是编辑数据？

### ISSUE THREAD

**Issue by xlkit456852** [z-song/laravel-admin#1719]
- Laravel Version: 5.3.*
- PHP Version:7
- Laravel-admin: 1.3.*

在form方法中使用了 $form->html(view('admin.gift.form'),'xxx);自定义视图，想在视图里判断当前是创建的操作（没有id）还是编辑的操作（有id）来进行不同的逻辑，但暂时没找到相关方法？求教~

**Comment by boomyanzi** [comment]
if (request()->route()->getActionMethod() == 'edit') {
}
