### ISSUE TITLE
Retorno do Select

### ISSUE THREAD

**Issue by leomusica77** [z-song/laravel-admin#1722]
Como faço para retornar mais de dois parâmetros no select? quero preencher outros campos a partir do select. Alguém para me ajudar?

**Comment by sistemasjg** [comment]
Hola, no hablo portugues, pero entiendo un poco lo que estas escribiendo. Coloca un ejemplo de lo que tratas de hacer y en donde, para poder  comprender mejor y ayudarte

**Comment by leomusica77** [comment]
Olá!

Em um select dessa forma:
$form->select('produto_id')->options(Produto::all()->pluck('nome', 'id'));
eu quero que ao lelecionar preencha também esse campo:
$form->text('valor_produto');
Tem alguma forma de fazer isso? ou ate mesmo disparar um ajax para fazer esse preenchimento.

**Comment by thalesreis** [comment]
@leomusica77 
Você pode utilizar o evento onchange do select... Segue aqui um exemplo
https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_onchange

**Comment by sistemasjg** [comment]
hola @leomusica77 , como @thalesreis  dice, vas a tener que hacer esta actualizacion con Javascript, por los momentos, es la unica manera de hacerlo. De hecho, de esta forma es que lo hace el componente select de este paquet

**Comment by leomusica77** [comment]
Estou desenvolvendo um novo tipo de campo de pesquisa, onde ele vai me retornar os campos que eu quiser. Acho que ficará melhor.
