### ISSUE TITLE
导出出错,头部和下面对不齐,下面数据会多出几列?

### ISSUE THREAD

**Issue by aoeng** [z-song/laravel-admin#1723]
版本是最新的,我想导出的和grid中的一致,并且标题为grid的表头 

![qq 20180207144827](https://user-images.githubusercontent.com/23565714/35902386-01f9af3a-0c16-11e8-939f-ccf947ac0eee.png)

**Comment by kaula1221** [comment]
导出我新写了一个导出类,但存在批量数据导出过大会报错的问题(自测只能导出2万条左右的数据)
    public function export()
    {
		$filename = Carbon::now()->format("YmdHis").'.csv';
        $headers = [
            'Content-Encoding'    => 'UTF-8',//'UTF-8',
            'Content-Type'        => 'text/csv;charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];
        response()->stream(function () {
            //开始下载
            $handle = fopen('php://output', 'w');

            $titles = [];

            if (empty($titles)) {
                //获取表头
                foreach($this->grid->columns() as $column) {
                    $titles[$column->getName()]=$column->getLabel();
                }
                //导出表头
                fputcsv($handle, $titles);
            }
            //获取显示的字段
            $recordkey=array_keys($titles);
            
            $records=$this->getData();

            foreach ($records as $record) {
//                logger('yj_debug',[array_dot($record)]);
                $export = array_only(array_dot($record),$recordkey);
                $new_array=[];
                foreach ($recordkey as $k) {
                    $new_array[$k] = $export[$k];
                }
                fputcsv($handle,$new_array);
            }
            //结束下载
            fclose($handle);
        }, 200, $headers)->send();
        exit;
	}

**Comment by kaula1221** [comment]
表头根据Grid的设置的来,不会按照表导出

**Comment by UpGod** [comment]
@kaula1221 那数据切片怎么做？有外关联的

**Comment by noogen** [comment]
You're hitting the SQL result limit because maybe you're missing the chunk statement? https://github.com/z-song/laravel-admin/blob/master/src/Grid/Exporters/CsvExporter.php#L29

I ran into the same issue.  Here's a modification of the original CsvExporter to fix the bad/unwanted extra data export:
```php
namespace App\Admin\Extensions;

use Encore\Admin\Grid\Exporters\AbstractExporter;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class CsvExporter extends AbstractExporter
{   
    /**
     * columns defintion
     * @var array
     */
    protected $cols = [];

    /**
     * Create a new CsvExporter instance.
     *
     * @param cols key:value column defintion
     *
     * @return void
     */
    public function __construct($cols = [])
    {
        $this->cols = [];
    }

    /**
     * {@inheritdoc}
     */
    public function export()
    {
        $filename = $this->getTable().'.csv';

        $headers = [
            'Content-Encoding'    => 'UTF-8',
            'Content-Type'        => 'text/csv;charset=UTF-8',
            'Content-Disposition' => "attachment; filename=\"$filename\"",
        ];

        response()->stream(function () {
            $handle = fopen('php://output', 'w');

            $titles = [];

            $this->chunk(function ($records) use ($handle, &$titles) {
                if (empty($titles)) {

                    if (empty($this->cols)) {
                        $this->buildHeaderRowFromRecords($records);
                    }

                    $titles = $this->cols;

                    // Add CSV headers
                    fputcsv($handle, array_values($titles));
                }

                foreach ($records as $record) {
                    fputcsv($handle, $this->getFormattedRecord($record, $titles));
                }
            });

            // Close the output stream
            fclose($handle);
        }, 200, $headers)->send();

        exit;
    }

    /**
     * @param Collection $records
     *
     * @return array
     */
    public function buildHeaderRowFromRecords(Collection $records)
    {
        $keys = collect(array_dot($records->first()->toArray()))->keys();
        foreach($keys as $key) {
            $title = Str::ucfirst(str_replace('.', ' ', $key));
            $this->cols[$key] = $title;
        }
    }

    /**
     * @param Model $record
     * @param Array $titles
     *
     * @return array
     */
    public function getFormattedRecord(Model $record, $titles)
    {
        $column_data = [];
        foreach ($titles as $key => $value) {
            $column_data[] = $record->getAttribute($key);
        }

        return $column_data;
    }
}
```

To use:
```php
// somewhere toward the end of grid definition
$grid->exporter(new \App\Admin\Extensions\CsvExporter());
```

@kaula1221 grid export usage
```php
// somewhere toward the end of grid definition
$cols = []
foreach($grid->columns() as $column) {
   $cols[$column->getName()] = $column->getLabel();
}
$grid->exporter(new \App\Admin\Extensions\CsvExporter($cols));
```

**Comment by kaula1221** [comment]
laravel-admin中的导出,有外部关联的导不出来,按照我的写法可以导出外部关联的数据,但在$grid->column('关联表.字段','列名');必须按照这个格式设置.

**Comment by kaula1221** [comment]
@UpGod 我原来想采用他默认的导出修改,但由于时间紧,发现切片数据里不包含关联数据,只好临时弄了一下

**Comment by UpGod** [comment]
@z-song 不做一些优化吗？

**Comment by noogen** [comment]
Are you looking for optimization?  I updated getFormattedRecord to be as close to the original CsvExporter as possible.

**Comment by UpGod** [comment]
@noogen  依赖注入,闭包传参,导出数据存在,但没有顺序对不齐

**Comment by noogen** [comment]
@aoeng sorry, not sure what the error is.  Overtime, I found a couple of errors while experimenting with more complicated grid.  I've fixed them and updated the code.  

Tip: for complex/computed column, it is better to define them in the model than inline grid definition.

Inline grid (won't work):
```php
$grid->model()->orderBy('created_at', 'DESC');
$grid->id('ID')->sortable();
$grid->donor()->display(function ($v) {
   return $v['first_name'] . ' ' . $v['last_name'];
});
```

Model (work better):
```php
$grid->model()->orderBy('created_at', 'DESC');
$grid->id('ID')->sortable();
$grid->manager()->fullname('Manager');

// inside of User model
    protected $appends = ['fullname'];

    public function getFullnameAttribute()
    {
        return $this->first_name . ' ' . $this->last_name;
    }

    public function manager()
    {
        return $this->belongsTo(\App\User::class, 'manager_id', 'id');
    }
    
```

Then export will just work with dot notation "manager.fullname" as identified in the grid.
