### ISSUE TITLE
删除、保存、更新等操作，没有右上角的  保存成功  这个提示

### ISSUE THREAD

**Issue by AndyShaw2048** [z-song/laravel-admin#1729]
- Laravel Version: 5.5.*
- PHP Version:7.0.26
- Laravel-admin: 1.5.*

### Description:
删除、保存、更新等操作，没有右上角的  保存成功  这个提示
只有登录的时候，右上角会有一个登录成功，但是其他页面的操作成功后没有弹出更新成功这种消息，而且也没有自动跳转，他只是刷新了一下。
我是在windows开发，然后上传到Linux上，如果在Linux上创建一个全新的laravel-admin就没有这种问题，是不是平台之间有什么差别？

**Comment by AndyShaw2048** [comment]
![image](https://user-images.githubusercontent.com/31623814/35956764-aa5ebe92-0cd2-11e8-8210-b2e2b38da8d4.png)
似乎与这个pjax有关

**Comment by XiaolonY** [comment]
应该是数据库的原因

**Comment by AndyShaw2048** [comment]
@XiaolonY 具体应该怎么处理呢？我百度了好多，都没有解决

**Comment by AndyShaw2048** [comment]
我解决了，是PHP版本不一样的原因
