### ISSUE TITLE
验证规则生效但是没有错误提示

### ISSUE THREAD

**Issue by liudong0763** [z-song/laravel-admin#173]
关于 model-form：
···
$form->text('name', '用户名')->rules('required|min:10');
···
增加了这段代码后，提交表单时未输入用户名，然后直接跳到列表页，并没有做任何的错误提示，求解

**Comment by z-song** [comment]
请问你的laravel已经laravel-admin版本？

**Comment by liudong0763** [comment]
我的laravel版本是5.3
laravel-admin的版本是 1.3.x-dev

**Comment by z-song** [comment]
犯了个低级错误，没有去掉调试输出信息，现在修复了，你可以稍后更新

谢谢提醒！

**Comment by liudong0763** [comment]
哈哈，好的，谢谢大神
