### ISSUE TITLE
复制后台模板到resources目录后，在app/Admin/bootstrap.php修改路径无效

### ISSUE THREAD

**Issue by yongyuanfan** [z-song/laravel-admin#1730]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
根据官网文档中提示，修改后台模板资源文件到resources目录，但是没有生效。

### Steps To Reproduce:
复制vendor/encore/laravel-admin/resources到resources/admin中
在app/Admin/bootstrap.php增加配置
app('view')->prependNamespace('admin', resource_path('views/admin'));
访问后台，发现没有生效。

**Comment by zhai8479** [comment]
同问，有解决方案了吗？

**Comment by ifreesec** [comment]
这是路径没复制对

是复制vendor/encore/laravel-admin/resources到resources/views/admin（!! 不是resources/admin）中
在app/Admin/bootstrap.php增加配置
app('view')->prependNamespace('admin', resource_path('views/admin'));

**Comment by yunlongw** [comment]
覆写内置视图
如果有需要自己修改view，但是不方便直接修改laravel-admin的情况，可以用下面的办法解决

复制vendor/encore/laravel-admin/views到项目的resources/views/admin，然后在app/Admin/bootstrap.php文件中加入代码：

```
// 覆盖`admin`命名空间下的视图
app('view')->prependNamespace('admin', resource_path('views/admin'));
```
这样就用resources/views/admin下的视图覆盖了laravel-admin的内置视图。

在laravel-admin每个新版本发布的时候, 内置视图都有可能会变更，所以如果你覆写了laravel-admin的视图，在更新laravel-admin版本的时候, 很有可能会出现视图方面的问题，这个需要你对照修改过的视图文件和内置视图自行修改解决。

---------------------------------------------------------------
以上在文档中被用横线划掉了， laravel-admin 1.7 版本复制到指定目录后没有效果
`已经 vendor/encore/laravel-admin/views/* 复制到  resources/views/admin/views/*`
```
app/Admin/bootstrap.php
app('view')->prependNamespace('admin', resource_path('views/admin'));
```
