### ISSUE TITLE
Cant access controller created by scaffold

### ISSUE THREAD

**Issue by kolep8** [z-song/laravel-admin#1733]
- Laravel Version: 5.5.34
- PHP Version: 7.13
- Laravel-admin: 1.5.x-dev

### Description:
Unable to access scaffold created controller in admin panel in fresh installed laravel

### Steps To Reproduce:
1. go to admin/helpers/scaffold
2.  enter - table name "dogs",  model "App\Models\dogs", controller "App\Admin\Controllers\dogs", first field name "dog_name"
3. add $router->resources(['dogs' => dogs::class ]); in admin routes file
4. go to admin/dogs

in 4 step I am getting error "Cannot declare class App\Admin\Controllers\dogs because the name is already in use"

**Comment by noogen** [comment]
The error is saying you cannot have dogs as model and also as controller name.  It should be:  Dogs, App\Models\Dogs, and App\Admin\Controllers\DogsController

From documentation (notice how they name foo, Foo, and FooController): https://github.com/z-song/laravel-admin.org/blob/master/public/docs/v1.4/en/helpers.md
