### ISSUE TITLE
$form->file()上传文件出现错误

### ISSUE THREAD

**Issue by AndyShaw2048** [z-song/laravel-admin#1734]
- Laravel Version: 5.5.*
- PHP Version:7.2.0
- Laravel-admin: 1.5.*

### Description:
$form->file()上传文件出现错误，上传doc文件后，路径变成了tmp格式的。

**Comment by xcm55054** [comment]
兄弟我也有这个问题，你用的环境是windows吗

**Comment by z-song** [comment]
参考这个issue #1805

**Comment by CantonBolo** [comment]
@z-song 不是gd2或者imagick的问题，是windows环境下上传后临时文件后缀是.tmp，导致intervention/image保存的时候无法识别图片文件的编码

**Comment by wujingquan** [comment]
关于这个问题的处理，可以参考下这里：https://www.wujingquan.com/781.html
