### ISSUE TITLE
filter（） 过滤查询无效果

### ISSUE THREAD

**Issue by kalordy** [z-song/laravel-admin#1737]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.6

### Description:
新手未入门。。。。

### Steps To Reproduce:
按照laravel-admin文档安装，当需要使用china-areas时，想要查询过滤像 where（）一样，
 $grid->filter(function($filter){
          $filter->is('parent_id', '0');
 });
Or
 $grid->filter(function($filter){
    $filter->where(function ($query) {
            $query->whereRaw('parent_id', "0")；
        });

    }, '市名');
}）；
Result:没效果，还是将所有数据都查出来了；感觉好绕，估计时我这么个新手的原因吧，还请大神指点一下，感激不尽

**Comment by yang5664** [comment]
可能你要的是
```
$grid->model()->where().........
```
