### ISSUE TITLE
添加管理员时，如果不分配角色，登陆后会发生无法退出现象

### ISSUE THREAD

**Issue by Dianwoung** [z-song/laravel-admin#1738]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5.#

### Description:
添加管理员时，不分配角色和权限，登陆后会导致无法退出。
只分配权限，不分配角色，仍会出现该现象。
分配角色后登陆，该现象消失，一切正常。

**Comment by yang5664** [comment]
這是權限（permission）問題，所以還是得配置一個角色擁有
```
/admin/auth/logout
```

**Comment by xiaomlove** [comment]
@z-song 这个不考虑改善一下吗？理论登录退出不需要验证权限。最好有一个地方可以自定义不进行权限检测的路由。
