### ISSUE TITLE
CSS, JS and images files are not accessible

### ISSUE THREAD

**Issue by triptisbinnovations** [z-song/laravel-admin#1742]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: #.#.#

### Description:
I have installed the admin in Laravel by command lines. I am able to access admin, log into the admin but assets files are not accessible. CSS, JS, and images are displaying blank. Please check the URL http://billing.sbware.com/vendor/laravel-admin/AdminLTE/dist/img/user2-160x160.jpg.

My admin URL is http://billing.sbware.com/admin.

I have set up the APP URL (http://billing.sbware.com) and DB details in the .env file. All Files permission is 0664 and folder permission is 0775. But still, i am getting this issue.

Can you please suggest me regarding this issue.

Looking forward to hearing from you soon!

Thanking You!

**Comment by allrested** [comment]
Try open this [http://billing.sbware.com/public/vendor/laravel-admin/AdminLTE/dist/img/user2-160x160.jpg](http://billing.sbware.com/public/vendor/laravel-admin/AdminLTE/dist/img/user2-160x160.jpg)
There are several ways to remove /public/ from URL, modifying .htaccess can do this trick.
You can find your answear [here](https://stackoverflow.com/questions/28364496/laravel-5-remove-public-from-url])
