### ISSUE TITLE
Multi-column Fields and onChange JS script for Fields

### ISSUE THREAD

**Issue by oopmvc** [z-song/laravel-admin#1750]
- Laravel Version: 5.5.*
- PHP Version: 7.*
- Laravel-admin: 1.5.*

### Description:
I would like to know how can I put multiple columns in one row?
I would also like to add JS code to some fields onChange method, or onBlur method.
-- Is that possible ?

**Comment by NickCoolii** [comment]
> I would like to know how can I put multiple columns in one row?
Try this:
https://github.com/z-song/laravel-admin/issues/872#issuecomment-336665176

> I would also like to add JS code to some fields onChange method, or onBlur method.
-- Is that possible ?
Try this:
`Admin::script($script);`
![default](https://user-images.githubusercontent.com/16125559/36289047-cff13d40-12ce-11e8-89d9-df11708ce49e.png)

P.S.: here is forum for questions - http://discuss.laravel-admin.org/
