### ISSUE TITLE
Nested Grid wtih Sorting, Is this possible? Expand button Text (Child row Count?)

### ISSUE THREAD

**Issue by oopmvc** [z-song/laravel-admin#1752]
- Laravel Version: 5.6
- PHP Version: 7.*
- Laravel-admin: 1.5.*

### Description:
Not sure If I can use $grid->expand -> new Admin::grid ()?
So that I can show a Table with its Child table rows in each expandable table. 

** Also would like to show the total number of rows for child table in <Expand> <a> Button?

**Comment by smtlk** [comment]
I can't even find expand on the Grid anymore and can't get the examples to work at all with the latest versions, is this method still available or has it been entirely removed?

**Comment by mRamadan0101** [comment]
can we use new grid in expand
