### ISSUE TITLE
How can I use with "dimsav/laravel-translatable" package?

### ISSUE THREAD

**Issue by naingwin** [z-song/laravel-admin#1753]
- Laravel Version: 5.6.*
- PHP Version: 7.1
- Laravel-admin: 1.5.*

### Description:
Want to use multiple languages with https://github.com/dimsav/laravel-translatable, but don't know how to use laravel-translatable in form method.

**Comment by luischavez** [comment]
@manzhouya 
Example:
```php
$form->tab('Document Type', function (Form $form) {
    $form->display('id', trans('columns.id'));

    $form->text('name', trans('columns.name_locale', [App::getLocale()]));
    $form->switch('use_pages', trans('columns.use_pages'));

    $form->display('created_at', trans('columns.created_at'));
    $form->display('updated_at', trans('columns.updated_at'));
})->tab('Translations', function (Form $form) {
    $form->hasMany('translationsexceptcurrent', trans('columns.translations'), function (Form\NestedForm $form) {
        $form->text('name', trans('columns.name'));
        $form->select('locale', trans('columns.locale'))->options(locale_options());
    });
});
```
in translated model:
```php
public function translationsExceptCurrent() {
    return $this->translations()->where('locale', '<>', App::getLocale());
}
```
![captura de pantalla 2018-08-16 a la s 08 55 47](https://user-images.githubusercontent.com/883068/44216471-41d95900-a132-11e8-8c07-e92cdcbb611f.png)
![captura de pantalla 2018-08-16 a la s 08 55 56](https://user-images.githubusercontent.com/883068/44216473-41d95900-a132-11e8-80d7-629975f39ea1.png)

**Comment by manzhouya** [comment]
@luischavez

I tried it and it succeeded. Thank you！

**Comment by uacode** [comment]
@luischavez 
Do you know any method to pass options for model method with hasMany?
