### ISSUE TITLE
Help json Model

### ISSUE THREAD

**Issue by marcosmaia** [z-song/laravel-admin#1754]
- Laravel Version: 5.5.28
- PHP Version:7.1
- Laravel-admin: 1.5.9

how do I get the value name of this json structure?
```php
$data = " {
  "nome": {
    "marks": {
      "condition": "new",
      "version": "1.2.9",
      "driver": "new"
    },
    "michael": {
      "condition": "news",
      "version": "1.2.9",
      "driver": "update",
    }
  },
 
  "current_version": "1.2.9",
  "avg_temp": 56.375,
  "capacity": "100.0",
  "per_info": {
    "status": {
      "load": 47,
      "per_alive_gpus": 9,
      "current_time": 1519301597
    }
  }
}";

class custom extends Model
{
    public function paginate()
    {
        $perPage = Request::get('per_page', 10);
        $page = Request::get('page', 1);
        $start = ($page-1)*$perPage;
      start=$start&count=$perPage");
        $data = json_decode($data, true);
        extract($data);
        $custom = static::hydrate($subjects);
        $paginator = new LengthAwarePaginator($custom, 1, $perPage);
        $paginator->setPath(url()->current());
        return $paginator;
    }
}
```
in Controlle 
```php
$grid->nome();    not  working
$grid->version();    working
$grid->condition();    working
$grid->capacity(); not  working
```
help me please

**Comment by maojr** [comment]
You should make sense the variables in paginate() first, 
try
```php
$custom = static::hydrate($nome);
```

**Comment by marcosmaia** [comment]
@maojr $custom = static::hydrate($nome); I tried more does not work 
$grid->nome(); not working
see json's structure
I want to get the name value plus just get condition for below

{
  "nome": {
    "marks": {
      "condition": "new",
      "version": "1.2.9",
      "driver": "new"
    },
    "michael": {
      "condition": "news",
      "version": "1.2.9",
      "driver": "update"
    }
  },
  "current_version": "1.2.9",
  "avg_temp": 56.375,
  "capacity": "100.0",
  "per_info": {
    "status": {
      "load": 47,
      "per_alive_gpus": 9,
      "current_time": 1519301597
    }
  }
}

**Comment by marcosmaia** [comment]
@z-song help me

**Comment by z-song** [comment]
`dd($paginator->toArray());` and see what the structure looks like?

**Comment by marcosmaia** [comment]
@z-song 
array:12 [▼
  "current_page" => 1
  "data" => array:2 [▼
    "marks" => array:3 [▼  **<--  I need to get the name "marks"**
      "condition" => "new"
      "version" => "1.2.9"
      "driver" => "new"
    ]
    "michael" => array:3 [▼   **<--  I need to get the name "michael"**
      "condition" => "news"
      "version" => "1.2.9"
      "driver" => "update"
    ]
  ]
  "first_page_url" => "/?page=1"
  "from" => 1
  "last_page" => 1
  "last_page_url" => "/?page=1"
  "next_page_url" => null
  "path" => "/"
  "per_page" => 10
  "prev_page_url" => null
  "to" => 2
  "total" => 1
]

**Comment by marcosmaia** [comment]
@z-song ?

**Comment by bolechen** [comment]
参考官网 demo

```php
    public function paginate()
    {
        $perPage = Request::get('per_page', 20);
        $page = Request::get('page', 1);
        $start = ($page-1)*$perPage;

        $data = file_get_contents("https://api.douban.com/v2/movie/in_theaters?city=上海&start=$start&count=$perPage");
        $data = json_decode($data, true);
        $movies = static::hydrate($data['subjects']);

        $paginator = new LengthAwarePaginator($movies, $data['total'], $perPage);
        $paginator->setPath(url()->current());

        return $paginator;
    }
```
