### ISSUE TITLE
pjax中间件 特定action排除

### ISSUE THREAD

**Issue by hangaoyu** [z-song/laravel-admin#1755]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
想把某一个路由不使用pjax中间件，这样处理好像pjax仍然起效果
     public function __construct()
    {
        $this->middleware('admin.pjax', ['except' => ['firstAuditDetail']]);
    }

**Comment by z-song** [comment]
你最终想要什么样的效果呢？
