### ISSUE TITLE
v1.5.9 new \Encore\Admin\Widgets\Form 创建表单无法提交保存

### ISSUE THREAD

**Issue by wangjinzhou** [z-song/laravel-admin#1756]
- Laravel Version: 5.5
- PHP Version:
- Laravel-admin: 1.5.9

### Description:
使用 new \Encore\Admin\Widgets\Form 创建表单提交后无法保存，降为1.5.7后正常

### Steps To Reproduce:
创建分类 category时，
       $content->body(function (Row $row) {

                $row->column(6, $this->treeView()->render());

                $row->column(6, function (Column $column) {
                    $form = new \Encore\Admin\Widgets\Form();
                    $form->action(admin_url('categories'));
                    $form->select('parent_id', '父级分类')->options(Category::selectOptions());
                    $form->text('title', '标题')->rules('required|string|max:30');

                    $form->number('order', '排序');

                    $column->append((new Box('新增', $form))->style('success'));
                });
            });

提交后未走到 store方法里

**Comment by z-song** [comment]
这个只是用来构建前端表单  要通过设置action和methd到指定的路由
