### ISSUE TITLE
form select 从api中获取选项列表，但当编辑时，下拉框并没有选中值 

### ISSUE THREAD

**Issue by ztyzjn** [z-song/laravel-admin#1758]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
<img width="870" alt="default" src="https://user-images.githubusercontent.com/9914196/36627581-d8f100a8-197f-11e8-901b-b9d3a2322fa6.png">
从api中获取选项列表，但当编辑时，下拉框并没有选中值 
<img width="911" alt="default" src="https://user-images.githubusercontent.com/9914196/36627608-10624d76-1980-11e8-918b-5e758c20772f.png">
如果用数组方式就没有问题，难道我是哪里设置有问题？

**Comment by yang5664** [comment]
那是因為在“編輯”時，api並沒有執行，所以你的select下拉資料應該是空的，這時候你應該要自己想辦法讓select取得資料。

**Comment by cnbattle** [comment]
类似问题: 编辑内容select 有没选中值,点击是有显示设置api的相关选项
