### ISSUE TITLE
Custom chartjs 

### ISSUE THREAD

**Issue by abdouTurki** [z-song/laravel-admin#1761]
i want to add custom chartjs in my admin dashboard but i cannot find a way to pass data from the controller like this ""return view('chart', ['data' => $data]);""
any help please ?

**Comment by abdou1236** [comment]
any help !?

**Comment by RomanGatchenko** [comment]
Did you solve the problem? Also looking for the best way to transfer data to the chart

**Comment by bahadorfarahani** [comment]
Hi
You can use compact.
`$bar = view('admin.chartjs.doughnut', compact('data'));`
