### ISSUE TITLE
图片上传删除按钮不显示

### ISSUE THREAD

**Issue by Breadem** [z-song/laravel-admin#1763]
- Laravel Version: 5.5.1
- PHP Version: 7.1.0
- Laravel-admin: 1.5.7

### Description:
$form->multipleImage('banner_images', '轮播图*')->removable()->help('如果要上传多张图片,上传时需要同时选中，本次上传的所有图片不能重名');
设置好removable还是没效果

**Comment by Breadem** [comment]
![tim 20180227150312](https://user-images.githubusercontent.com/25916562/36715018-5f2caaea-1bcf-11e8-8cce-b7cabc9dc147.png)
打印后数据中的removable的确是true，可是就是不出来那个删除的按钮

**Comment by think67** [comment]
同样遇到该问题，第一次貌似只能右上角的x删除全部图片，表单保存后，再次编辑时才会显示每一张图片删除按钮。

**Comment by Breadem** [comment]
@think67  是的，一样的情况

**Comment by shunhua** [comment]
@z-song  是的，一样的情况
