### ISSUE TITLE
Suport Laravel version 5.6

### ISSUE THREAD

**Issue by mr-zenith** [z-song/laravel-admin#1769]
Hi
When do you want to release support for Laravel version 5.6?because all model not working in Laravel 5.6
thanks

**Comment by langeuh** [comment]
+1

**Comment by mozgobol** [comment]
+

**Comment by jxlwqq** [comment]
the author said this project only support LTS.

**Comment by fhferreira** [comment]
+1

**Comment by ZeiyThink** [comment]
+1  那些extension都不能用。
