### ISSUE TITLE
表格模型grid中筛选功能如何在执行查询时不添加某个筛选字段做条件？

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#1773]
- Laravel Version: 5.5
- PHP Version:
- Laravel-admin: 1.5

### Description:

我再做条件筛选查询时，有个select字段需要view显示出来，但在做提交查询时就不需要这个字段做条件查询了，不知道在哪里控制这个问题，麻烦解答下!
下面这个server_id我不需要做查询，只需要展示出来提交后别的地方用到，如果不做处理，我数据表里没有这个字段就会报错。
```
      $grid->filter(function ($filter) {
                $this->getPlatform();
                // 去掉默认的id过滤器
                $filter->disableIdFilter();
                $filter->equal('platformID', '所在平台')->select($this->getPlatform());
                $filter->equal('server_id', '所在游戏服')->select($this->getServerOnline());
                $filter->like('name', '角色名');
            });
```
![qq 20180301100156](https://user-images.githubusercontent.com/17559363/36823327-9ed7eb32-1d37-11e8-9ff9-5ce6d7e3ce80.png)

**Comment by wangwenfan** [comment]
已经解决，用where查询

**Comment by Baiyongjian** [comment]
请问怎么解决的老铁， 我也碰到这个问题了。我再做条件筛选查询时，有个字段不需要查询。
