### ISSUE TITLE
image field使用阿里云oss编辑时报错不支持相对路径

### ISSUE THREAD

**Issue by zhdwwf** [z-song/laravel-admin#1774]
- Laravel Version: 5.5
- PHP Version: 7.1.0
- Laravel-admin: 1.5.9

### Description:
使用阿里云存储能够正常上传图片，但是编辑时报如下错误，
![image](https://user-images.githubusercontent.com/564279/36830934-af11acbc-1d60-11e8-8cf7-40d1bb6d1dec.png)
driver配置如下：
![image](https://user-images.githubusercontent.com/564279/36830964-c40bf578-1d60-11e8-9a00-367cf9a7769e.png)

请问如何能够设置编辑时的绝对路径呢

**Comment by Joken2** [comment]
可以教我 下怎么用oss上传图片，有资料吗？

**Comment by Joken2** [comment]
可以留下qq号码 ，交流下吗？

**Comment by zhdwwf** [comment]
@Joken2 使用这个https://github.com/jacobcyl/Aliyun-oss-storage，按照它的readme配置，然后在laravel-admin的config文件中选择对应的disk就行了

**Comment by Joken2** [comment]
可以留下qq吗？方便交流

**Comment by Joken2** [comment]
我昨天看了 ，这个但是今天还是调不通，可以留下qq请教一下你吗？

**Comment by zhdwwf** [comment]
@Joken2 把你的配置代码贴一下，调不通具体是哪里，报错的话贴一下错误信息，QQ公司不能用

**Comment by Joken2** [comment]
现在是filesystems.php文件我是按照那个配置来的，admin.php的upload也是配置好的，但是在$form->image()中的时候一直在报504，我追到代码中发现
/**
     * Upload file and delete original file.
     *
     * @param UploadedFile $file
     *
     * @return mixed
     */
    protected function uploadAndDeleteOriginal(UploadedFile $file)
    {

        $this->renameIfExists($file);

        $path = $this->storage->putFileAs($this->getDirectory(), $file, $this->name);

        $this->destroy();
        return $path;
    }
在这个方法中$path = $this->storage->putFileAs($this->getDirectory(), $file, $this->name);这一个代码走不下去

**Comment by Joken2** [comment]
可以微信吗？我这边有点急需这个，非常感谢你

**Comment by zhdwwf** [comment]
@Joken2 你加zhangdawei-ily
