### ISSUE TITLE
关于使用https之后，分页 链接依然是http的问题

### ISSUE THREAD

**Issue by Wh1221** [z-song/laravel-admin#1780]
- Laravel Version: 5.5.14
- PHP Version: 7.1.10
- Laravel-admin: 1.5.*

### Description:
我用这个开发微信小程序的后台，所以使用的域名是https，然后在AppServiceProvider.php里面已经开启了
```
\URL::forceScheme('https');
```
admin.php配置文件里面将secure也已经设置成了true，后台其他路由都可以访问。

但是右上角的 ==搜索== 以及右下角的： ==分页== ，链接依然使用的是http，请问一下有没有哪位大神知道这该如何解决？

**Comment by clearcodecn** [comment]
https://github.com/z-song/laravel-admin/issues/1768

**Comment by antennix** [comment]
I had same problem, but I am improving in this way:

https://stackoverflow.com/questions/28797590/php-generate-laravel-paginator-securehttps-links
`$this->app['request']->server->set('HTTPS','on');`

Perhaps「forceScheme」 is not necessary
