### ISSUE TITLE
权限检测的 Bug

### ISSUE THREAD

**Issue by Tairy** [z-song/laravel-admin#1794]
- Laravel Version: 5.4.*
- PHP Version: 7.1.9
- Laravel-admin: 1.4

### Description:
`/src/Auth/Permission.php` 中 [check](https://github.com/z-song/laravel-admin/blob/44189b2c8ea33a302dcf32b65aacc8d5a8f34fa0/src/Auth/Permission.php#L18) 函数，

```
if (static::isAdministrator()) {
    return true;
}
```
如果在
```
if (is_array($permission)) {
    collect($permission)->each(function ($permission) {
        call_user_func([Permission::class, 'check'], $permission);
    });
    return;
}
```
之前的话会导致 `$permission` 为数组时并且 `static::isAdministrator()` 为 `true` 是直接返回 true，而不是
```
[
    "permission_a" => true,
    "permission_b" => true,
    ...
]
```
的形式，这会导致在权限检测的时候出问题，希望能修复。

### Steps To Reproduce:

1. 超级管理员登录
2. 实现批量检测权限逻辑

**Comment by rainforyou** [comment]
不要玩1.4了···

**Comment by Tairy** [comment]
@rainforyou 1.5 也是这样的啊
