### ISSUE TITLE
编辑器里的图片上传如何配置？

### ISSUE THREAD

**Issue by sean1990** [z-song/laravel-admin#1795]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

通过 `$form->editor` 调用的富文本编辑器里面的图片插入功能目前只能插入图片的url，如何才能实现图片上传？

**Comment by luochunming** [comment]
我使用的是 ckedit , ck 默认关闭本地上传，你可以网上查看下打开 方式，然后在config.js中配置config.filebrowserUploadUrl 上传路由。默认编辑器没有尝试做图片上传。
