### ISSUE TITLE
tab组件中增加grid组件只会在第一个tab有筛选弹出层，其他的tab只弹出有遮蔽层。

### ISSUE THREAD

**Issue by DrMute** [z-song/laravel-admin#1797]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

   $tab = new Tab();
            $tab->add('1', $this->grid("1") );
            $tab->add('2', $this->grid("2") );
            $tab->add('3', $this->grid("3") );
            $tab->add('4', $this->grid("4") );
有遇到的这个BUG的同学没。

**Comment by andyhuang123** [comment]
有遇到

**Comment by Tomorrowxxy** [comment]
这个问题有解决办法了吗？

**Comment by DrMute** [comment]
早就放弃laravel-admin了,完全不好用,&nbsp;


————————————————————————————————————

如有表达不清之处存在疑问请回复邮件或者直接电话联系。

Best Regards.

彭晋&nbsp;|&nbsp;Wistron Information&nbsp;Technology &amp;&nbsp;Services (Beijing),&nbsp;Inc.
联系电话：18680525884

***@***.*** ***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年5月28日(星期五) 下午4:03
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [z-song/laravel-admin] tab组件中增加grid组件只会在第一个tab有筛选弹出层，其他的tab只弹出有遮蔽层。 (#1797)





 
这个问题有解决办法了吗？
