### ISSUE TITLE
The document of this repository does not work properly

### ISSUE THREAD

**Issue by alihastam** [z-song/laravel-admin#1803]
# **The document of this repository does not work properly**
http://laravel-admin.org/docs/#/en/

**Comment by barayuda** [comment]
Same here, some document just display blank page

**Comment by z-song** [comment]
@alihastam @barayuda It's ok now.

The docs page uses the latest version of prism.js to highlight the code, and the latest release of prismjs has some syntax matching issues, the earlier version is fine.
