### ISSUE TITLE
Encoding format (tmp) is not supported

### ISSUE THREAD

**Issue by rainforyou** [z-song/laravel-admin#1805]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5x

### Description:
$form->image()    使用crop等会报错如下：
 NotSupportedException In D:\wwwroot\manga\vendor\intervention\image\src\Intervention\Image\AbstractEncoder.php line 163 :
Encoding format (tmp) is not supported.

**Comment by taimaiduc** [comment]
Check your GD Library. I have been gotten this issue on window. MacOs and Linux is ok.
https://stackoverflow.com/questions/7851011/how-do-i-install-gd-on-my-windows-server-version-of-php
