### ISSUE TITLE
form 表单使用JS

### ISSUE THREAD

**Issue by imekkk** [z-song/laravel-admin#1807]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: #1.4

### Description:
laravel-admin提供了很丰富的表单控件，我目前有些需求：
1.需要多个input的输入框，数量不定，用户自己通过加减按钮控制（想在input后面放置加减号按钮）。
2.需求—根据不同的select选择  展示不同的小模块，如何在form中变换呢？（目前思路是分几个div 表示不同模块。通过JS控制隐藏和显示，但是如何在form 中再自定义div）。
不知道朋友们有没有 什么开发经历 或者 文档（可能我没有看到。大致看了一遍）
非常感谢

**Comment by z-song** [comment]
用`$form->html('<div></div>');`加入div
用`Admin::script('alert("hello")')`给当前页面加入js

**Comment by chan17** [comment]
好头痛……前端代码写php里 维护起来真要蛋碎了。。。。
