### ISSUE TITLE
form 表单下某个 输入框中的值的变化如何监听

### ISSUE THREAD

**Issue by V1ki** [z-song/laravel-admin#1811]
- Laravel Version: 1.5
- PHP Version: 7.1.5
- Laravel-admin: 5.5

### Description:
form 表单下某个 输入框中的值的变化如何监听。

**Comment by yang5664** [comment]
寫全域監聽 input, textarea，應該就可以了。

**Comment by z-song** [comment]
用`Admin::script('alert("hello");');`给当前页面注入js代码，你的监听逻辑就写在里面
