### ISSUE TITLE
Form number change callback

### ISSUE THREAD

**Issue by pcfjojo** [z-song/laravel-admin#1815]
@z-song Form number method has no callback. If we have a callback method when changed the number it would be better for some calculations.

**Comment by z-song** [comment]
Do you mean add a listener for `changed` event?

**Comment by pcfjojo** [comment]
Yes, for an example; you have **saved and saving callback** likewise If we have form number field changed call back it is better for validation like(quantity non available etc..)
_I had to throw an error when the product quantity not available. Now i use the saved callback to check the quantity availablitiy and throw error.
The same think in form hasmany nested from as well._
