### ISSUE TITLE
How to show the new button above the empty grid

### ISSUE THREAD

**Issue by enaeim** [z-song/laravel-admin#1819]
### Description:
Hi.
When my grid is empty, the new button will not appear at the top of the grid screen.

- Laravel Version: 5.5.36
- PHP Version: 7.1.9
- Laravel-admin: 1.5.6

![order payment](https://user-images.githubusercontent.com/33656061/37404578-84f1a2ba-27a7-11e8-8186-9daa329e6422.jpg)

![order payment2](https://user-images.githubusercontent.com/33656061/37404856-4ba4b9f6-27a8-11e8-9589-3ffbadac835d.jpg)

**Comment by yang5664** [comment]
plz refs to : 
[http://laravel-admin.org/docs/#/en/model-grid-custom-tools](url)

**Comment by enaeim** [comment]
tanks a lot [yang5664](https://github.com/yang5664)

**Comment by enaeim** [comment]
tanks a lot [yang5664](https://github.com/yang5664).

but new button is default button in grid page. By default there is a new button on top gird page but if grid is empty, not display new button on top grid.

please help me!
