### ISSUE TITLE
Admin/Controllers/UserController  does not exist

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#182]
通过git push  生成的 UserController 检测不到，
composer dump-autoload
也没用

**Comment by z-song** [comment]
你看看对应的目录下有没有文件 UserController.php

另外`git push 生成的 UserController`是什么意思？

**Comment by iianpan** [comment]
就是本地生成的控制器推到服务器上，后来发现是我自己粗心大意，大小写弄错了。。
