### ISSUE TITLE
Idea: Form->show the date picker on input and icon click

### ISSUE THREAD

**Issue by NickCoolii** [z-song/laravel-admin#1820]
@z-song 
Now date picker appears only by input click, but I think that it's a good idea to show date picker also by icon click.
https://github.com/z-song/laravel-admin/blob/f2430f3f060e2243a9c86f5edf5aceb91a0494b7/src/Form/Field/Date.php#L34-L45
We just need to add:
`$this->options['allowInputToggle'] = true;`
and change 
`$this->script = "$('{$this->getElementClassSelector()}').datetimepicker(".json_encode($this->options).');';`
for
`$this->script = "$('{$this->getElementClassSelector()}').parent().datetimepicker(".json_encode($this->options).');';`

So. What do you think about it?

**Comment by z-song** [comment]
Merged, Thanks!
