### ISSUE TITLE
Change dahsboard layout

### ISSUE THREAD

**Issue by SghaierFiras** [z-song/laravel-admin#1821]
- Laravel Version: 5.5
- PHP Version: 7.2.3
- Laravel-admin: 1.5

### Question:
How can i change the dashboard **layout** and **style** with customized CSS and Javascript - of course with keeping the same old functionality of the old dashboard features as it is -.

**Comment by z-song** [comment]
`laravel-admin` and `Adminlte` are highly integrated, so it is difficult to customize the layout and style
