### ISSUE TITLE
刷新页面后，左侧菜单栏怎么默认选中当前栏目,展开菜单栏选择的菜单并高亮

### ISSUE THREAD

**Issue by denghp** [z-song/laravel-admin#1829]
- Laravel Version: 5.6
- PHP Version: 7.1.3
- Laravel-admin: 1.5.9

### Description:
如当前点击的是管理员菜单展开并且是高亮显示，但是刷新后，怎么才能让当前默认展开并高亮当前菜单呢？
![image](https://user-images.githubusercontent.com/2291149/37526943-bdf0069a-296b-11e8-92fe-18a3e8225da8.png)
刷新后效果
![image](https://user-images.githubusercontent.com/2291149/37526965-cb84ac2a-296b-11e8-9103-47505182ba71.png)

**Comment by jaredwu** [comment]
$(function(){
        $('.sidebar-menu li:not(.treeview) > a').on('click', function(){
            var $parent = $(this).parent().addClass('active');
            $parent.siblings('.treeview.active').find('> a').trigger('click');
            $parent.siblings().removeClass('active').find('li').removeClass('active');
        });

        $(window).on('load', function(){
            $('.sidebar-menu a').each(function(){
                if(this.href === window.location.href){
                    $(this).parent().addClass('active')
                        .closest('.treeview-menu').addClass('.menu-open')
                        .closest('.treeview').addClass('active');
                }
            });
        });
    });


在 index.blade.php 的js 中加入这个

**Comment by denghp** [comment]
谢谢你的实现，加上你的代码这个功能正常达到我想要的效果了。还有一个效果不知道您实现没？
就是在sidebar-collapse 模式下，左侧点击的菜单栏鼠标离开后如何高亮显示？
![image](https://user-images.githubusercontent.com/2291149/37944794-9f4eb10e-31af-11e8-9220-e924bc4c6af1.png)

正常模板提供是点击后，鼠标离开该菜单属于高亮显示的，效果如下：
![image](https://user-images.githubusercontent.com/2291149/37945157-60992096-31b1-11e8-8e36-cc764b499855.png)

**Comment by denghp** [comment]
@jaredwu

**Comment by shencm** [comment]
请问你这个主题是怎么修改的

**Comment by denghp** [comment]
@shencm 
config配置下的app.php 修改  `'skin' => 'skin-green'`,参数

**Comment by lilianxu9327** [comment]
你好，请问你是怎么实现‘当前点击的是管理员菜单展开并且是高亮显示’，方便把代码发一下吗？

**Comment by jackbaron** [comment]
In case of pagination it fails. Does anyone have any other solutions?
