### ISSUE TITLE
表单提交数据清空

### ISSUE THREAD

**Issue by Breadem** [z-song/laravel-admin#1834]
- Laravel Version: 5.5.#6
- PHP Version: 7.1
- Laravel-admin: 1.5.7

### Description:
表单提交时，我想在提交之前做回调是否应该提交的判断，在
$form->saving(function (Form $form) {
...
里写return back()->with(compact('error'));
});
写了这个后，是不提交了，错误信息也有了，但是之前填的数据都清空掉了

**Comment by Breadem** [comment]
我想要的效果是不提交，显示错误，但是保留之前填写的表单信息。

**Comment by z-song** [comment]
试试
```php
return back()->withInput()->with(compact('error'));
```

**Comment by Breadem** [comment]
@z-song  可以了，非常感谢!
