### ISSUE TITLE
能否提供一份demo网址的完整案例代码

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#184]
有些方法调用和数据操作没有文档说明，希望能有完整代码参考，感谢！（邮箱windpursuer12@foxmail.com）

**Comment by z-song** [comment]
每个例子都在tab页放了代码，包括模型代码和数据库下载，有不明白的地方多去读一下代码，tests目录下面也有相关代码可以参考

**Comment by windpursuer** [comment]
原来tests文件夹有，没留意到，谢谢
