### ISSUE TITLE
菜单管理的一堆nbsp;显示怎么规避？不想改vendor

### ISSUE THREAD

**Issue by cevin** [z-song/laravel-admin#1844]
- Laravel Version: 5.6
- PHP Version:7.2
- Laravel-admin: latest

### Description:

![image](https://user-images.githubusercontent.com/338110/37827706-89f36db0-2ed3-11e8-85a0-85ae6a858d2d.png)

如上图所示。自带的应该是select2，我自己测试了一下没什么问题，应该是输出整理输出的时候出现的。

**Comment by never615** [comment]
HTML 实体编码

在之前版本的 Laravel 中，Blade 不会对 HTML 实体进行双重编码。这并不是底层 htmlspecialchars 函数的默认行为，而且会在渲染内容或传递内联 JSON 内容到 JavaScript 框架时导致预期之外的结果。

在 Laravel 5.6 中，Blade 以及辅助函数 e 默认会对特殊字符进行双重编码，从而与 PHP 底层 htmlspecialchars 函数的默认行为保持一致。如果你想要维持不进行双重编码的旧状，可以使用 Blade::withoutDoubleEncoding 方法：
```
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Blade::withoutDoubleEncoding();
    }
}
```

然后`php artisan view:clear`
