### ISSUE TITLE
popover  弹出图片为图片的代码,

### ISSUE THREAD

**Issue by phpLHT** [z-song/laravel-admin#1846]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5

### Description: 
弹出的图片代码不能解析为图片 作为字符串显示了

**Comment by phpLHT** [comment]
![1](https://user-images.githubusercontent.com/22925198/37862765-71aabde8-2f8d-11e8-98cd-c2041b739a8f.png)

**Comment by z-song** [comment]
设置html为true
```js
$('.popover-dismiss').popover({
  html: true
})

```
