### ISSUE TITLE
文档看不了了

### ISSUE THREAD

**Issue by jae-jae** [z-song/laravel-admin#1848]
![wx20180325-162559](https://user-images.githubusercontent.com/5620429/37873171-40c51e32-3049-11e8-9a44-2a94c8e6756c.png)
如图文档目录没有显示出来

**Comment by z-song** [comment]
文档发引用的cdn资源更新了版本 导致文档不能显示，已经修复

如果下次还是出现这个问题，在目录`https://github.com/z-song/laravel-admin/tree/master/docs/zh`下面有一样的文档
