### ISSUE TITLE
How remove one to one model relation?

### ISSUE THREAD

**Issue by arwtyxouymz** [z-song/laravel-admin#1854]
- Laravel Version: 5.5.39
- PHP Version:7.0.25
- Laravel-admin: 1.5

### Description:
I have **News** model and **JapNews** model, and they are one to one relation.
```
News
-id
-date

JapNews
-id
-title
-content
-news_id
```

In grid page, I want to delete both of them when I pushed delete button.
But I don't know how to do.
Please help me....

**Comment by z-song** [comment]
Use `deleting` event of eloquent model to do this:

In your News models add following method:

```php
    protected static function boot()
    {
        parent::boot();

        // before delete() method call this
        static::deleting(function($news) {
             $news->japnews()->delete();
        });
    }
```
