### ISSUE TITLE
发现一个bug,关于chart

### ISSUE THREAD

**Issue by q747985549** [z-song/laravel-admin#186]
![image](https://cloud.githubusercontent.com/assets/20881762/20995014/197748ac-bd2f-11e6-933c-5966ea6688fe.png)
![image](https://cloud.githubusercontent.com/assets/20881762/20995025/2a36d478-bd2f-11e6-9b42-3f78b961577f.png)

Encore\Admin\Widgets\Chart里面有一个uniqid函数来生成唯一的canvas id值，但是他生成的不是唯一的，导致有的canvas是空的，

**Comment by q747985549** [comment]
![image](https://cloud.githubusercontent.com/assets/20881762/20995158/1a9f3d24-bd30-11e6-8cef-5783bd551591.png)
可以用uniqid('',true)

**Comment by z-song** [comment]
谢谢提醒，欢迎提交pull request。

**Comment by z-song** [comment]
已修复
