### ISSUE TITLE
CKEditor 的图片上传问题?

### ISSUE THREAD

**Issue by aoeng** [z-song/laravel-admin#1862]
图片上传,老是提示 不正确的服务器响应 ,如何做呢?求laravel代码

**Comment by ycrao** [comment]
@aoeng 可以参考本插件 https://github.com/douyasi/laravel-ckeditor

**Comment by aoeng** [comment]
好了.网上的教程都是错的,[参考](https://docs.ckeditor.com/ckeditor4/latest/guide/dev_file_upload.html)

**Comment by jimmy8646** [comment]
@aoeng 可以請你分享一下代碼嗎

**Comment by ycrao** [comment]
@aoeng  @jimmy8646 `CKEditor` 支持传统表单（form文件表单上传）、浏览器拖曳上传（把图片文件直接拖放到编辑器中）及其剪切板粘贴图片（复制图片粘贴上传）三种上传方式，不同上传方式的返回是不一样的，还是 不正确的服务器响应，是你配置的问题，可以下载安装插件 `douyasi/laravel-ckeditor` 后体验demo页面之后，再研究改动到laravel-admin中，而不是茫然断言网上的教程配置都是错的。

**Comment by aoeng** [comment]
@ycrao 我没有茫然，我就是断言，他就是错的，我试过我才说！
@jimmy8646 
配置config：
```
config.extraPlugins = 'uploadimage';
config.imageUploadUrl = '/uploader/upload.php?type=Images';
```
php返回数据格式：
```
{
    "uploaded": 1,
    "fileName": "foo.jpg",
    "url": "/files/foo.jpg"
}
```
这些就够了，其他的config可以自己设置

**Comment by ycrao** [comment]
@aoeng 你所说的配置在 `laravel-ckeditor` [L16-L20](https://github.com/douyasi/laravel-ckeditor/blob/master/resources/views/example.blade.php#L16-L20) 里都有，不知道你 `case` 中所谓错的是啥错。 请直接看我录制的动图（本来想存储为视频的，但是视频太大，还得转码，不方便网络存储）吧，了解一下这三种上传模式，看看有没有你没考虑到的地方或者错误。 
录制动图的环境：
- Windows 10 + PHP7.0 
- 纯净版 Laravel + Laravel-CKEditor , 以 `php artisan serve` 方式启动
- 录制时登录了QQ，为了方便截图图片到剪切板上传
- 录制软件为 [ScreenToGif](http://www.screentogif.com/?l=zh_cn)

>  
动图地址： https://www.yascmf.com/uploads/content/20180503/5aeb2a713fcf5_45o.gif

**Comment by msl12** [comment]
还好看到这里，不然我还要浪费好多时间，感谢！ @aoeng
