### ISSUE TITLE
跨库搜索报错

### ISSUE THREAD

**Issue by 775397252** [z-song/laravel-admin#1864]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.*

### Description:跨库搜索报错
 $filter->between('public_user_info.last_login_date','最后登录时间')->datetime();
···
class PublicUsers extends Model
{
    protected $connection = 'user_mysql';
    protected $table = 'users';
}
错误信息
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'laravel_reserved_0.id' in 'where clause' (SQL: select count(*) as aggregate from `users` where (exists (select * from `userauthor` where `users`.`userid` = `userauthor`.`userid` and `name` like %未知十%)) and exists (select * from `users` as `laravel_reserved_0` where `laravel_reserved_0`.`id` = `users`.`userid` and `last_login_date` between 2018-03-01 00:00:00 and 2018-03-30 00:00:00))

**Comment by z-song** [comment]
试试表名前面加上数据库名：
```php
protected $table = '数据库名.users';
```

**Comment by 775397252** [comment]
thanks

**Comment by ed1sonyang** [comment]
大佬  帮我看看

SQLSTATE[42S02]: Base table or view not found: 1146 Table 'zw_zw_usystem.user_wechat' doesn't exist
