### ISSUE TITLE
How can I display the image?

### ISSUE THREAD

**Issue by arwtyxouymz** [z-song/laravel-admin#1865]
- Laravel Version: 5.5
- PHP Version: 7.0.25
- Laravel-admin: 1.5

### Description:

I created the form of the image upload.
The uploaded image doesn't display at edit although i uploaded image at creation.

### Steps To Reproduce:

My code is below.

NewsController.php
```php:NewsController.php
    protected function form()
    {
        return Admin::form(News::class, function (Form $form) {
                $form->hasMany('newsimages', function (Form\NestedForm $form) {
                    $form->image('image')->removable();
                });
        });
    }
```

config/filesystems.php
```php:config/filesystems.php
        'admin' => [
            'driver' => 'local',
            'root' => public_path('images'),
            'visibility' => 'public',
            'url' => env('APP_URL').'/images'
        ]
```

config/admin.php
```php:config/admin.php
    'upload' => [

        'disk' => 'admin',

        'directory' => [
            'image' => 'News',
            'file'  => 'files',
        ],
    ],
```

How can I fix it?

In addition, I upload the images to `public/images/News/` and it correctly saved now.
But in my table, the image path is `News/〇〇.png`.
I want to change the image path in my table from `News/〇〇.png` to `/images/News/〇〇.png`!
Please help me!

**Comment by yucolabjames** [comment]
I have the same problem as OP where the image thumbnail does not show up during edit.

Followed instructions posted in thread #687 #831 and #849

no luck so far, thanks!

**Comment by AhmadRaju007** [comment]
any solution?
