### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by debute** [z-song/laravel-admin#1866]
Ok, I'm new to this, but I completely don't understand that installation. I created new directory, opened command line and wrote this: `composer require encore/laravel-admin`

Then it downloaded vendors and all I had within this directory was `vendor` dir. In the same command line window I wrote this `php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider"` and I get error: `Could not open input file: artisan`

I haven't worked with laravel before, please, send me detailed approach to get it work.

Also, will this project work on shared hosting? I mean, I have no access to the shell or commands at all, I can just upload files which I have in PC.

**Comment by z-song** [comment]
laravel-admin is based on laravel, so before you install this package you should Install laravel first and make sure that the database connection settings are correct.
