### ISSUE TITLE
demo/users 无法出现页面

### ISSUE THREAD

**Issue by BartSu** [z-song/laravel-admin#1867]
- Laravel Version: 5.6.14
- PHP Version: 7.1.7
- Laravel-admin: 1.5.x-dev
### Description:
 我根据中文文档的 入门-快速开始 去熟悉这个开发平台，发现demo/users 总是出现Sorry, the page you are looking for could not be found.  仔细看过每个步骤，发现没错，转过看英文文档发现add_route部分中英文不一样，英文的是    $router->resource('demo/users', UserController::class);
而中文里的是 $router->resource('users', UserController::class);
前者报错，后者Sorry, the page you are looking for could not be found. 

### Steps To Reproduce:
根据document的步骤

**Comment by qzd1989** [comment]
没问题的.
routes.php
`<?php

use Illuminate\Routing\Router;

Admin::registerAuthRoutes();

Route::group([
    'prefix'     => config('admin.route.prefix'),
    'namespace'  => config('admin.route.namespace'),
    'middleware' => config('admin.route.middleware'),
], function (Router $router) {

    $router->get('/', 'HomeController@index');
    $router->resource('gifts', GiftController::class);

});
`
访问地址为xxx/admin/gifts

**Comment by BartSu** [comment]
成功了，之前看document里的url的例子，一直按demo/user去试，却一直没有已问过demo的问题
