### ISSUE TITLE
按照教程，导出类出错了

### ISSUE THREAD

**Issue by cnxfire** [z-song/laravel-admin#1868]
- Laravel Version: 5.5.39
- PHP Version:7.1.2
- Laravel-admin: 1.5

### Description:
Method Encore\Admin\Grid::__toString() must not throw an exception, caught Error: Class 'App\Admin\Extensions\ExcelExpoter' not found

**Comment by DreamboyA** [comment]
同问

**Comment by DreamboyA** [comment]
@cnxfire 需要安装该库
https://github.com/Maatwebsite/Laravel-Excel
