### ISSUE TITLE
调用grid上的display方法,在回调中使用了在Model中配置了cast的属性,会报错.附原因

### ISSUE THREAD

**Issue by never615** [z-song/laravel-admin#1869]
- Laravel Version: 5.4和5.6
- PHP Version:7.0/7.2
- Laravel-admin: 1.4/1.5

### Description:
调用grid上的display方法,在回调中使用了在Model中配置了cast的属性,会报错.
我示例中的调用报错就是json_decode错误,参数需要的是string,传入了array.

### Steps To Reproduce:
Model中的cast配置,park_info在数据库中是json格式:
```
    protected $casts = [
        'park_info' => 'array',
    ];
```
调用:
```
$grid->user_id("会员名")
            ->display(function ($value) {
                \Log::info($this->park_info);
            })
```

### 原因
Grid的build方法中设置了数据到Column:
`Column::setOriginalGridData($data);`
而这个data是经过orm查询得到的数据, 根据Model的配置已经被处理过一遍.

在Column中的bindOriginalRow方法中:
```
    protected function bindOriginalRow(Closure $callback, $key)
    {
        $originalRow = static::$originalGridData[$key];

        return $callback->bindTo(static::$model->newFromBuilder($originalRow));
    }
```
数据又通过newFromBuilder设置到了Model的属性$attributes上.

此时调用`$this->park_info`,因为是orm调用,又会进行一次cast,但是attributes中park_info已经被设置成了数组.

**Comment by z-song** [comment]
确实有这个问题，你试试用下面的方式避免第二次cast
```php
$this->getAttributes()['park_info'];
```

**Comment by mu0641** [comment]
这个问题什么时候能修复呀，我也遇到了

**Comment by never615** [comment]
@mu0641 你可以先用他说的方法
