### ISSUE TITLE
关于action按键链接的bug

### ISSUE THREAD

**Issue by edwinhuish** [z-song/laravel-admin#187]
刚刚扩展了一下grid, 然后发现Action 的path居然不是按照grid指定的resourcePath，而是：
```php
    protected function setUpScript()
    {
        $this->path = app('router')->current()->getPath();
        ....................
    }
```

这里应该改为：
```php
    protected function setUpScript()
    {
        $this->path = $this->row->getPath();
        if ( ! $this->path ){
             $this->path = app('router')->current()->getPath();
        }
        ....................
    }
```

**Comment by z-song** [comment]
已修复 谢谢提醒！

**Comment by edwinhuish** [comment]
@z-song 可以看到你确实在git上更新过了，可是为什么composer更新不了？

**Comment by z-song** [comment]
在开发分支上修复的，还没打tag，更新到开发分支：
`composer require encore/laravel-admin 1.3.x-dev`

**Comment by edwinhuish** [comment]
![image](https://cloud.githubusercontent.com/assets/5207925/21035149/f48dfd00-bdf7-11e6-88fe-6b8a522c8899.png)
![image](https://cloud.githubusercontent.com/assets/5207925/21035156/04430024-bdf8-11e6-8322-195a0555b7fa.png)
