### ISSUE TITLE
form button问题

### ISSUE THREAD

**Issue by never615** [z-song/laravel-admin#1877]
- Laravel Version: 5.4/5.6
- PHP Version:7.0/7.1/7.2
- Laravel-admin: 1.4/1.5

### Description:
调用button的on方法，传js代码报错：
Object of class Closure could not be converted to string

### 修复

```
    public function on($event, $callback)
    {

        $js = $callback();


        $this->script = <<<EOT

        $('{$this->getElementClassSelector()}').on('$event', function() {
            $js
        });

EOT;
    }
```

**Comment by charmsoya** [comment]
It seem there is not any documents about how to use 'button' on a form, could the author please add an example? and explain the about issue is true or not. Thanks a lot!
