### ISSUE TITLE
Cant change skin from blue to dark 

### ISSUE THREAD

**Issue by ryonguyen** [z-song/laravel-admin#1879]
- Laravel Version: 5.6
- PHP Version: 7.0
- Laravel-admin: 1.5.*

### Description:
I go to file in config/admin.php.
I want change skin to dark so i write : 
`'skin' => 'skin-black-light',`
but it not work. Please tell me how to do that. Thanks

**Comment by ryonguyen** [comment]
![screen shot 2018-04-06 at 17 47 51](https://user-images.githubusercontent.com/4860303/38417503-be6731e0-39c2-11e8-91f9-e4e3e677a48f.png)

**Comment by yurik94** [comment]
Hey, still not working, how did you resolved?
