### ISSUE TITLE
如何关联插入其他表

### ISSUE THREAD

**Issue by zanjs** [z-song/laravel-admin#188]
```
articles
tags
articles_tags
```
有以上三个表，
在提交  `articles` 表后 ，需要获取 `articles` 提交的 ` tags` 字段值 和当前 `article` 的 ID ，
根据 `tages` 循环插入 `articles_tags ` 表里 

### 或者其他方案；

提交后 能否有方法执行其他事件

**Comment by z-song** [comment]
这个和`laravel-admin`的[用户-角色]都是`many-to-many`关系，用multipleselect来处理，参考[用户-角色]代码的实现吧

**Comment by zanjs** [comment]
嗯 好 感谢 大大
