### ISSUE TITLE
对表单字段的一个小建议

### ISSUE THREAD

**Issue by hui-ho** [z-song/laravel-admin#1880]
- Laravel Version: 5.5.*
- PHP Version: 7.2
- Laravel-admin: 1.5.*

### Description:
表单字段前的图标会出现大小不一致的情况，建议每个图标加上 fa-fw 的 class ，保持字段的齐整

**Comment by uhowep** [comment]
请问有图吗？能否描述下什么情况下会出现这种情况？

**Comment by hui-ho** [comment]
http://laravel-admin.org/demo/widgets/form-1

像demo里的那样，第一个图标是37×34，第二个39×34，往后的都长宽都有点不一致，其实也没什么，就是有点别扭，每个图标加个fa-fw的class就好了

**Comment by z-song** [comment]
已修复
