### ISSUE TITLE
textarea.blade.php 中没有添加{{class}}

### ISSUE THREAD

**Issue by horityabiriko** [z-song/laravel-admin#1883]
- Laravel Version: 5.5.40
- PHP Version: 7.2.4
- Laravel-admin: 1.5

### Description:
->addElementClass('xxx');
没有反映到textarea.blade.php

### Steps To Reproduce:

**Comment by z-song** [comment]
已修复

**Comment by RobinVSRose** [comment]
@z-song  dateRange 没办法添加自定义class名称
