### ISSUE TITLE
上传图片至七牛云失败

### ISSUE THREAD

**Issue by phpLHT** [z-song/laravel-admin#1885]
- Laravel Version: 5.5
- PHP Version:7.0.23
- Laravel-admin: 1.5

### Description:上传文件至七牛云图片失败,但是线下windows 环境没有问题

![Uploading C)5DMC$BP7C6EQWCSYIM2CC.png…]()
![Uploading K$`N%7N26P$FHE23VVY~0)K.png…]()
![Uploading T`BXNX@X$L54F`(VLE@I(KX.png…]()

### Steps To Reproduce:
$form->image('headimg', '头像');
使用 $form->saving() 打印不出问题

**Comment by z-song** [comment]
看看日志里面有没有什么异常

**Comment by phpLHT** [comment]
改为上传到本地,上传是出现同样的问题;
![1](https://user-images.githubusercontent.com/22925198/38539430-be81bdc0-3cca-11e8-9483-99a20dcdf8da.png)
 ![2](https://user-images.githubusercontent.com/22925198/38539450-d7c7cd7e-3cca-11e8-83d4-414c43e5f202.png)
@z-song

**Comment by phpLHT** [comment]
查看的记录文件,
![3](https://user-images.githubusercontent.com/22925198/38539700-cc6f11fc-3ccb-11e8-83a3-d9620baf474f.png)

**Comment by z-song** [comment]
你先确认下目录是否存在并且有写入权限

**Comment by phpLHT** [comment]
/public  和 /storage   目录权限都是设置为了 0777 ,读取文件时没有,才报的错误.在本地临时保存时,是怎么执行的呢??,这个错误应该是这个时候引起的

**Comment by phpLHT** [comment]
已解决,程序上传所属权限在 www 下,但是文件上传临时保存文件 在/ 下,所以一直错误

**Comment by leeib** [comment]
@phpLHT 请问这个文件上传临时保存文件权限的问题要怎么设置呢？我也遇到这个问题
```
$form->file('video', '视频')
            ->removable()
            ->uniqueName()
            ->move(DateDir::videoMonthDayDir())->help('视频目前仅支持mp4格式');
```

**Comment by phpLHT** [comment]
你把项目所属的用户和环境所属的用户保持一致,如你的程序代码部署时 www用户,那么你的环境用户 也是www用户就可以了

**Comment by leeib** [comment]
@phpLHT 我是php限制了文件上传的大小，限制调大后，就不报这个异常了

**Comment by leeib** [comment]
不过想到要是权限问题，将php上传文件的临时目录设置到项目目录中，应该也可以解决这个问题

**Comment by longyunrui** [comment]
> @phpLHT 我是php限制了文件上传的大小，限制调大后，就不报这个异常了

我的也是 PHP 限制了文件上传的大小报了这个权限不足的错。。
