### ISSUE TITLE
How to set the min value of the input field？

### ISSUE THREAD

**Issue by pengzhendong** [z-song/laravel-admin#1886]
- Laravel Version: 5.5.40
- PHP Version: PHP/7.2.0-1+ubuntu16.04.1+deb.sury.org+1
- Laravel-admin: 1.5.x-dev

### Description:

How to set the min value of $form->number()? Although I use `number`, I found that the type of the `input` is `text`.

**Comment by z-song** [comment]
Try to add a `min` attribute:
```php
$form->number('num')->attribute('min', '10');
```

**Comment by pengzhendong** [comment]
Thanks! It worked.
