### ISSUE TITLE
Unable to save 'null' as a value for a column

### ISSUE THREAD

**Issue by langeuh** [z-song/laravel-admin#189]
Setup:
'clients' have a 'country_id' field that is optional and thus nullable (with a foreign key). It needs to be a valid ID (int) or null

```php
 $table->unsignedInteger('country_id')->nullable();
```
If I want to remove the linked country for a client who has a country selected, sql throws an error because it tries to set `country_id` to '' while it should be `null`

In the form function in my ClientController (I left out the other parts)

```php 
     return Admin::form(
            Client::class,
            function (Form $form) use ($id) {

                $form->select('country_id', 'Country')
                    ->options(Country::all()->pluck('name', 'id')->prepend('---', '')) // can't use 'null' so an empty string is used
                    ->rules('sometimes|exists:countries,id');

                $form->saving(
                    function (Form $form) {

                        if (empty($form->country_id)) {
                            $form->country_id = null; // as documented
                            // $form->input('country_id', null); // what it does and this shows why it fails to set country_id to null
                        }
                    }
                );
            }
        );
```

`Encore\Admin\Form -> input` prevents values to be set to `null`
The input should be split up for setting and getting a value in order to fix this problem

I'm on the  1.3-branch

**Comment by z-song** [comment]
In `Form::prepare()` method, after running saving callback, all items in input data with value `null` will be removed, so modify the input method is useless.

I think you can set up a saving callback for model `Client`:
```php
public static function boot()
{
    parent::boot();

    static::saving(function($model){
        if (empty($model->country_id)) {
            $model->country_id = null;
        }
    });
}
```
Use this you can ensure the column `country_id` to be int or null in anywhere you saving data for this model.

**Comment by langeuh** [comment]
This works, yet I don't understand why you would not be able to set a value to null. 
Encore\Admin\Form::input makes this impossible.

eg:
```php
$model->foreign_key_id = null;
$model->save();
```
