### ISSUE TITLE
Admin::script('console.log("</div>");'); didn't worked!

### ISSUE THREAD

**Issue by pengzhendong** [z-song/laravel-admin#1894]
- Laravel Version: 5.5.40
- PHP Version: PHP/7.2.0-1+ubuntu16.04.1+deb.sury.org+1
- Laravel-admin: 1.5.x-dev

### Description:

Something wrong with `Admin::script('console.log("</div>");')`?
* First open the page => `Uncaught SyntaxError: Invalid or unexpected token`
* Refresh the page => worked!

### Steps To Reproduce:

**Comment by z-song** [comment]
What about `Admin::script('console.log("<\/div>");')` ?

**Comment by pengzhendong** [comment]
Thanks!
