### ISSUE TITLE
功能测试时报错

### ISSUE THREAD

**Issue by Yang24556** [z-song/laravel-admin#1899]
- Laravel Version: 5.4.36
- PHP Version: 7.1
- Laravel-admin: 1.4.*

### Description:
测试代码部分如下：
 $admin = factory(Administrator::class)->make([
            'username' => 'admin',
            'password' => 'admin',
        ]);
        $response = $this->actingAs($admin, 'admin')->put(route('xxx.update', 1), [
          
        ]);

报错提示：
1) Tests\Feature\xxxTest::test
Illuminate\Database\QueryException: SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'user_id' cannot be null (SQL: insert into `admin_operation_log` (`user_id`, `path`, `method`, `ip`, `input`, `updated_at`, `created_at`)

**Comment by z-song** [comment]
参考[tests](https://github.com/z-song/laravel-admin/tree/master/tests)目录下的测试用例
