### ISSUE TITLE
icheck 多选框没有任何的样式

### ISSUE THREAD

**Issue by huyouheng** [z-song/laravel-admin#1900]
- Laravel Version: 5.6.12
- PHP Version:7.2.0
- Laravel-admin:  1.5.9

### Description:
在blade中使用 
`<input type="checkbox" id="userWeiChat"  name="weixin">`
没有icheck的效果，我看浏览器已经加载了icheck的js和css,不知道为什么，有人了解吗？

**Comment by z-song** [comment]
要初始化这个checkbox
```js
$('#userWeiChat').iCheck();
```

**Comment by huyouheng** [comment]
我添加后，原来的样式框都没有啦，
`<div class="icheckbox_minimal" aria-checked="false" aria-disabled="false" style="position: relative;"><input type="checkbox" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"><ins class="iCheck-helper" style="position: absolute; top: -20%; left: -20%; display: block; width: 140%; height: 140%; margin: 0px; padding: 0px; background: rgb(255, 255, 255); border: 0px; opacity: 0;"></ins></div>`
以上是添加 $('#userWeiChat').iCheck();  后显示的代码。
我就是 在$content->body(view('index'));  这里自定义啦一个页面，需要一个按钮框，可他就是显示不出来，不知道为啥。
