### ISSUE TITLE
grid中的editable项目错误提示末尾多出的换行符如何去掉? 如图

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#1907]
![qq 20180413115725](https://user-images.githubusercontent.com/8817046/38716416-3d59a730-3f13-11e8-9c9e-3f9fe4ea9fb2.png)

**Comment by z-song** [comment]
贴一下代码

**Comment by faydanube** [comment]
$grid->title('標題')->editable();
$form->text('title', '標題')->rules('required');
就是正常的代碼..為了避免是lang的問題,改回了en也是一樣的,如圖
![qq 20180413115725](https://user-images.githubusercontent.com/8817046/38722634-106ca966-3f31-11e8-8332-039c9fa7ce6e.png)

**Comment by z-song** [comment]
参考 c092c3e83fd9607f20c2d610fc6f80be8854a343 手动修改一下`public/vendor/laravel-admin/laravel-admin/laravel-admin.js`

**Comment by faydanube** [comment]
@z-song fixed. thanks
