### ISSUE TITLE
在form的saving中需要获取inputs这个数组，因为需要判断某个key值是否存在

### ISSUE THREAD

**Issue by cheerego** [z-song/laravel-admin#1909]
![image](https://user-images.githubusercontent.com/13394349/38721894-90ccbbe4-3f2e-11e8-8b80-a9617acaaec7.png)

反正我是这样做的。有什么更好的方式吗？

**Comment by z-song** [comment]
没明白你的意思，要获取请求数据用`request()->all();`就可以了

**Comment by cheerego** [comment]
@z-song 可以 确实是可以拿到，但是为毛 我用request()->has('enter')一直都是false 我就尴尬了。

**Comment by cheerego** [comment]
@z-song 最开始request()->has('enter') 一直都是false 我以为这里拿不到
