### ISSUE TITLE
Unable to install laravel-admin-media on Laravel 5.6

### ISSUE THREAD

**Issue by alpharameeztech** [z-song/laravel-admin#1916]
- Laravel Version: 5.6.*
- PHP Version: 7.2
- Laravel-admin: 1.5.*

### Description:
When i try to install laravel-admin-media manager, it throws this error

 composer require laravel-admin-ext/media-manager
Using version ^1.0 for laravel-admin-ext/media-manager
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.
```
  Problem 1
    - Can only install one of: laravel/framework[v5.6.16, 5.5.x-dev].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.16].
    - Can only install one of: laravel/framework[5.5.x-dev, v5.6.16].
    - laravel-admin-ext/media-manager v1.0 requires laravel/framework 5.5.* -> satisfiable by laravel/framework[5.5.x-dev].
    - Installation request for laravel-admin-ext/media-manager ^1.0 -> satisfiable by laravel-admin-ext/media-manager[v1.0].
    - Installation request for laravel/framework (locked at v5.6.16, required as 5.6.*) -> satisfiable by laravel/framework[v5.6.16].
```

**Comment by z-song** [comment]
laravel-admin only supports LTS version of laravel, currently laravel v5.5
