### ISSUE TITLE
Feature request: dynamic add array fields

### ISSUE THREAD

**Issue by NewEXE** [z-song/laravel-admin#1919]
Hi. My idea it was realize function like this:

![array-matrix_fields](https://user-images.githubusercontent.com/25324571/38783132-e85cc014-4106-11e8-9795-76a2b2bee00c.gif)

I will be very grateful for such feature!

**Comment by z-song** [comment]
There is already a similar implementation http://laravel-admin.org/demo/painters/create

Find code here https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Controllers/PainterController.php#L98-L102

**Comment by llxx-lord-xxll** [comment]
@z-song  
Is there any easy way to make a button and make the nested form dynamically generated on run-time with JS as it is in the image via zsong?

**Comment by z-song** [comment]
@NewEXE You can try to modify the code to support the `morphToMany` relation, and if it works, feel free to send a pull request.

**Comment by NewEXE** [comment]
Unfortunately, did not work. If we weaken the verification condition, then the _remove_ field tries to add to the database.

> SQLSTATE[42S22]: Column not found: 1054 Unknown column '_remove_' in 'field list' (SQL: insert into `optionables` (`_remove_`, `name`, `option_id`, `optionable_id`, `optionable_type`) values (0, opt 1, new_1, 1, App\Models\Course))

I want to implement support for all types of relationships. I'll look at the freedom that can be done.

**Comment by hoangnamitc** [comment]
Hello,

Link is dead: https://github.com/z-song/laravel-admin/issues/1919#issuecomment-381490559

How to use this feature to day!
