### ISSUE TITLE
select editbale grid 中 cell name 怎么显示关联数据表的值，而不是 id

### ISSUE THREAD

**Issue by iwillhappy1314** [z-song/laravel-admin#192]
有如下代码：
`$grid->cell_id()->editable( 'select', Cell::options() );`

显示效果如下图：
<img width="241" alt="cell" src="https://cloud.githubusercontent.com/assets/1455683/21036845/c4eb8eb2-be03-11e6-9745-597a57321ffb.png">
### Cells 数据表：

| id   | name |
| ---- | ---- |
| 1    | 电脑数码 |
| 2    | 服装鞋帽 |

### Plans 数据表
| id   | cell_id | name  |
| ---- | ------- | ----- |
| 1    | 2       | 笔记本电脑 |
| 2    | 1       | 平板电脑  |

cell_id 是关联的 Cells 数据表中的 id。

已经可以实现选择数据并保存的功能，只是显示的时候，数据列表中显示的是 id，对用户来说，不是很友好。

是否有办法在上图的列表中显示 Cells 数据表中的名称。

谢谢！

**Comment by z-song** [comment]
实现起来似乎不太容易，我会关注这个问题

**Comment by iwillhappy1314** [comment]
改变了数据类型，把 cell_id 直接修改成 cell_name 临时解决了，反正是内部用。
