### ISSUE TITLE
如何直接载入数据到From？

### ISSUE THREAD

**Issue by StringKe** [z-song/laravel-admin#1920]
- Laravel Version: 5.6.16
- PHP Version: 7.1.15
- Laravel-admin: 1.5.12

### Description:
如何直接创建一个From数据库载入数据到From表单
Setting表内有站点信息
类似wordpress的站点设置页面或者typecho的站点设置页面

顺便反馈一个小BUG？
![image](https://user-images.githubusercontent.com/31089228/38789053-35a19f08-416a-11e8-9768-99aa64cb15b6.png)

**Comment by z-song** [comment]
http://laravel-admin.org/docs/#/zh/widgets?id=%E8%A1%A8%E5%8D%95

eg:
```php
use Encore\Admin\Widgets\Form;

$form = new Form(['name' => 'laravel']);
$form->text('name');
```

**Comment by llxx-lord-xxll** [comment]
I have been finding this solution since a long time. Thank you @z-song and @StringKe .
Works perfectly
