### ISSUE TITLE
请问我怎么样可以重写新增的链接

### ISSUE THREAD

**Issue by sohenk** [z-song/laravel-admin#1923]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
我想修改新增按钮的链接。可以实现吗。我可以自定义一个新的tool。但是那个新增的按钮怎么去掉

**Comment by Aevit** [comment]
在 `grid()` 方法里：  

```
$grid->disableCreateButton();
```
