### ISSUE TITLE
upload file and it seems not in urls

### ISSUE THREAD

**Issue by unkn0wn9** [z-song/laravel-admin#1927]
- Laravel Version: 5.6.16
- PHP Version:7.2
- Laravel-admin: 1.5

### Description:

I change avatar of admin and it can't been shown.
url like :http://localhost/uploads/images/avatar.png
it returns 404.
but i can find the file in local disk
![tim 20180417152713](https://user-images.githubusercontent.com/23371839/38854674-d37ffa50-4253-11e8-8204-c7ca1a204e67.png)

**Comment by z-song** [comment]
What's the path of the file you uploaded?

**Comment by unkn0wn9** [comment]
@z-song /uploads/images/   I set the settings as docs

**Comment by rafayet-monon** [comment]
Same problem here.. Is there any solution? @z-song  @unkn0wn9

**Comment by ryonguyen** [comment]
I have same problem. Can u fixed it?

**Comment by BourneSuper** [comment]
u are using `php artisan serve`, starting with `127.0.0.1:8000`, not 'localhost'.
re-config APP_URL in .env and restart
