### ISSUE TITLE
如何将数据库结果集重新拼装新的数组后在页面显示该数据

### ISSUE THREAD

**Issue by guanghai1203** [z-song/laravel-admin#1936]
- Laravel Version: 5.5.*
- PHP Version: 7
- Laravel-admin: 1.5

### Description:
想要从数据库查到的结果集 重新拼装一个新的数组 在显示到页面 
grid 如何能把新的数组 传递过去

**Comment by ajiader** [comment]
同问  本来想用bulidData 但是报错了
