### ISSUE TITLE
更改edit action 路由自定义post, 会出现405

### ISSUE THREAD

**Issue by gm8300130** [z-song/laravel-admin#1940]
- Laravel Version: 5.4.36
- PHP Version: 5.6.4
- Laravel-admin: 1.4.5

### Description:

我把A的 编辑 action 置换成 自定义(B)的路由

B路由 
$router->post('/merchantsgroup/submitEdit','MerchantsGroupController@submitEdit')->name('merchantsgroup.submitEdit');

但送过去会显示405,
![4b313186-6bd1-4062-9cd3-3a4ef24bf54e](https://user-images.githubusercontent.com/20453680/38971473-f6cd9abe-43cd-11e8-819d-85331696e8f9.png)

查看html
![04b583b4-14e2-4a53-821a-005f988a0df0](https://user-images.githubusercontent.com/20453680/38971205-a03cdfa8-43cc-11e8-92eb-c3823d1e91b4.png)
表单就是post 

下面多了

`<input type="hidden" name="_method" value="PUT" class="_method">`

我把路由改成 $router->put 就可以了..

想请问编辑一定要用 put? 
不能只写 $router->post?

还是有设定可以更改或是移除 box-footer 里的 _method 

谢谢

**Comment by z-song** [comment]
根据restful的约定，更新资源使用http的put方法

如果都按照预定来定义你的路由，就能很清晰的知道每一个路由的作用了
