### ISSUE TITLE
请问grid里面怎么修改button按钮的文字，或者怎么新增一个button

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#1951]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:

如下图这个位置所示，新增按钮我想修改下文字，只是当前页面需要改，不是全局，或者新增一个按钮
### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/17559363/39027038-b2639aee-4482-11e8-8143-38867cefbf0c.png)

**Comment by sohenk** [comment]
重新写个组件自己定义吧
