### ISSUE TITLE
[功能优化]ModelTree下层展开调用ajax

### ISSUE THREAD

**Issue by jxlwqq** [z-song/laravel-admin#1952]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
如果层级很多，数据量很大，一次性载入，速度会很慢，建议下层展开是可以通过调用接口的方式载入。
### Steps To Reproduce:
![wechatimg41](https://user-images.githubusercontent.com/2421068/39028193-fd431fbc-4487-11e8-91f1-d398379aa101.jpeg)

**Comment by ajiader** [comment]
我也有这个需求    不晓得咋个入手好
