### ISSUE TITLE
多表存储怎么实现啊

### ISSUE THREAD

**Issue by w410006739** [z-song/laravel-admin#1954]
当car表里的name字段是从member表里取出的数据
代码如下
$form->display('id','ID');
            $form->text('member.name','姓名');
            $form->text('carnum','车牌号');
            $form->text('cartype','车辆类型');
            $form->text('purpose','是用性质');
            $form->text('powertype','动力类型');
            $form->image('licenceimgs','行车证')->uniqueName();            
            $form->image('insuranceimgs','保单')->uniqueName();
            $form->text('vin','车辆识别代号');
            $form->text('engine_no','发动机号');
            $form->text('model','车辆品牌型号');
            $form->text('owner','所有人');
            $form->text('addressx','行车证地址');
            $form->display('created_at', '添加时间');
            $form->display('updated_at', '修改时间');
但是在修改数据的时候  当修改了member.name的时候   数据库里不改变  还是保存原有数据 这个药怎么解

**Comment by a365893296** [comment]
试试使用关联关系
[关联](https://laravel-china.org/docs/laravel/5.5/eloquent-relationships)
