### ISSUE TITLE
tags 加入 Ajax 或 options 支持

### ISSUE THREAD

**Issue by bestony** [z-song/laravel-admin#1956]
- Laravel Version: 5.6.*
- PHP Version: 7.1.14
- Laravel-admin: 1.5.*

### Description:

希望为 tags组件 加入 options()  或 load 的支持，从而支持从已有的标签中去选择。

**Comment by z-song** [comment]
提交了commit c5b74a33b23a4e69b882f9db98ce49f023ca75a8， 支持`options()`方法设置标签
