### ISSUE TITLE
在哪里可以找到 示例教程？

### ISSUE THREAD

**Issue by iexe** [z-song/laravel-admin#1960]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5 dev

### Description:
在哪里可以找到 示例教程？我是一个新手，使用很迷茫！文档挺全面但是不知道怎么用。对不起是我太笨，但是应该还有和我一样的人...

**Comment by z-song** [comment]
https://github.com/z-song/laravel-admin.org

**Comment by helloMJW** [comment]
http://www.majianwei.com/archives/8969 实现基本的增删改查 参照 https://github.com/z-song/demo.laravel-admin.org/blob/master/app/Models/Article.php
