### ISSUE TITLE
Saving a single form field to file instead of database

### ISSUE THREAD

**Issue by llxx-lord-xxll** [z-song/laravel-admin#1961]
- Laravel Version: 5.5.*
- PHP Version: 7.1.1
- Laravel-admin: 1.5.x-dev

### Description:
I wanted to know if there is a way to ignore a form field value for saving it to model, but instead i want to save that form field(ckeditor) value to my storage disk.

### Steps To Reproduce:
[
![image](https://user-images.githubusercontent.com/6489365/39093113-e27bc2c8-463b-11e8-9af3-96e2105ba250.png)
](url)

I need this content field value saved to a storage file instead of the database on form submit.

`    protected function form()
    {
        return Admin::form(Layouts::class, function (Form $form) {
            $form->display('id', 'ID');
            $form->text('title');
            $form->text('slug');
            $form->ignore('content');

            $form->ckeditor('content')->default(function ($form) {
                //$layout = Layouts::find($id);
                if(Storage::disk("site_layout")->exists($form->model()->slug.".blade.php"))
                {
                    return Storage::disk("site_layout")->get($form->model()->slug.".blade.php");
                }
                else

                $error = new MessageBag([
                    'title'   => 'Layout Not Found Exception',
                    'message' => 'Layout file not found in the layout folder in the website, check your slug'
                ]);

                return back()->with(compact('error'));

                //return $tuple->id;
            });

            $form->saved(function (Form $form) {
                return response(dump($form));

                if(Storage::disk("site_layout")->exists($form->model()->slug.".blade.php"))
                {
                   // return Storage::disk("site_layout")->put($form->model()->slug.".blade.php",$form->content);
                }

            });

        });
    }`

This is a what i was trying. I wanted to catch form field values since it has a Form parameter of the same instance on which i was submitting the form on saved callback.

But i found the value of that ckEditor field's value nowhere.

**Comment by z-song** [comment]
Try to use `request('content')` to catch form field

**Comment by llxx-lord-xxll** [comment]
Worked. Thank you..
@z-song
