### ISSUE TITLE
我在表单添加了验证规则，但是没有任何提示，直接刷新页面

### ISSUE THREAD

**Issue by xcm55054** [z-song/laravel-admin#1964]
- Laravel Version: 5.6
- PHP Version:7.1
- Laravel-admin:1.5

### Description:
我的表单中新增了$form->text("name","姓名”)->rules("required")；这个规则没起作用

**Comment by zhiyuzheng** [comment]
我也遇到这个问题，  然后 try   catch一下就可以了

**Comment by usergao** [comment]
> 我也遇到这个问题， 然后 try catch一下就可以了

请问下是是怎么try catch 呢？
