### ISSUE TITLE
一对多表单中包含 editor 组件时, 无法保存内容 及 界面显示问题

### ISSUE THREAD

**Issue by weir008** [z-song/laravel-admin#1970]
- Laravel Version: 5.5.40
- PHP Version: 7.2.0
- Laravel-admin: 1.5.12

### Description:
当一对多表单中包含 editor 组件时, 出现以下问题. 
1, editor 内容无法保存:
```
$form->hasMany('contents', 'Name & Introduction', function (Form\NestedForm $form) {
                $form->text('locale', 'Lang');
                $form->text('name', 'Name');
                $form->editor('intro', 'Intro');
            });
```
![https://dl2.pushbulletusercontent.com/xWPIDD7i4ASKgoF0V2mP0MOrezpemjaz/Snipaste_2018-04-24_15-09-18.jpg](https://dl2.pushbulletusercontent.com/xWPIDD7i4ASKgoF0V2mP0MOrezpemjaz/Snipaste_2018-04-24_15-09-18.jpg)
提交保存后, 提示成功, 但编辑器中输入的内容并没有保存进去, 数据库中相应字段为空. 把 editor 改为 其它组件如 text 则可以正常保存.

2, 界面显示出错:
当点击 "New" 新增2条以上的记录时, 第一条和第二条的编辑器部分出现以下错误: 
![https://dl2.pushbulletusercontent.com/gyVmGqurfPxcLrjrpeHpdRUrI4iKweQv/Snipaste_2018-04-24_15-15-43.jpg](https://dl2.pushbulletusercontent.com/gyVmGqurfPxcLrjrpeHpdRUrI4iKweQv/Snipaste_2018-04-24_15-15-43.jpg)
但如果点击 "Remove" 移除出现错误的这两条, 再次添加, 则显示正常:
![https://dl2.pushbulletusercontent.com/LftlLqfu659hPYG2yUwjLBGlnPOveOeY/Snipaste_2018-04-24_15-26-59.jpg](https://dl2.pushbulletusercontent.com/LftlLqfu659hPYG2yUwjLBGlnPOveOeY/Snipaste_2018-04-24_15-26-59.jpg)

**Comment by ali18298262660** [comment]
遇到一样的问题
