### ISSUE TITLE
listbox

### ISSUE THREAD

**Issue by dptms** [z-song/laravel-admin#1972]
- Laravel Version: 5.5.40
- PHP Version: 7.1.7-1+ubuntu16.04
- Laravel-admin: v1.5.10

### Description:
当我在使用listbox的时候 确实可以更新或者新增中间便的记录，但是如果我中间表有额外的字段需要添加该如何操作呢？

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/22364664/39233819-17b2dc46-48a4-11e8-9ff0-1c380bcae652.png)

比如我想更新如图的 `theme_type` 字段

**Comment by z-song** [comment]
listbox不适合你的场景

**Comment by dptms** [comment]
我用这样的办法 貌似解决了
```
$form->saving(function (Form $form) {
                $form->top_products = collect($form->top_products)->filter()->mapWithKeys(function($item){
                    return [$item => ['theme_type' => 0]];
                })->all();
                $form->bottom_products = collect($form->bottom_products)->filter()->mapWithKeys(function($item){
                    return [$item => ['theme_type' => 1]];
                })->all();
            });
```
