### ISSUE TITLE
组件表单调用的会有加载不成功的现象

### ISSUE THREAD

**Issue by asanshiwen** [z-song/laravel-admin#1974]
- Laravel Version: 5.6.17
- PHP Version:7.2.10 nts
- Laravel-admin: 1.5.x-dev

### Description:
现象：组件表单调用的会有加载不成功的现象。
具体描述：当我在自定义的控制器中调用表单组件（icon，datetime，timeRange等），然后到页面刷新效果的时候。以$form->datetime()为例，操作如下：       

1. 点击时间框，应该出现时间选择的效果，但却没有出现这种效果
2. 然后使用F5刷新页面，也是没有效果的
3. 但是当强制刷新（F5+Ctrl）的时候，组件的效果就出现了。

      不知道是什么原因，希望能得到解答，感谢。

### Steps To Reproduce:
jquery报错
 代码中的使用方式如下：
将$grid放入$content->body()里时候，jquery就会报错，不知道是不是我的使用方式有问题
![image](https://user-images.githubusercontent.com/16474003/39240426-4e69ff3c-48b6-11e8-9544-3b98173777e8.png)
![image](https://user-images.githubusercontent.com/16474003/39240486-7c26b442-48b6-11e8-9e0f-7c573ca94ec7.png)

**Comment by asanshiwen** [comment]
= =。。。

**Comment by luvvien** [comment]
自定义的form组件不加载
```
class mdEditor extends Field
{
    // 定义视图
    protected $view = 'admin.mdEditor';

    // css资源
    protected static $css = [
        'simplemde/src/css/simplemde.css'
    ];

    // js资源
    protected static $js = [
        'simplemde/src/js/codemirror/tablist.js',
        'simplemde/src/js/simplemde.js'
    ];

    public function render()
    {
//        $this->script = <<<EOT
//
//
//EOT;
        return parent::render();
    }
}
```
组件不显示，去前端控制台看，所有的js和css都没有加载进来
