### ISSUE TITLE
Sweet Alert delete confirmation dismiss

### ISSUE THREAD

**Issue by jonathanwkelly** [z-song/laravel-admin#1975]
- Laravel Version: 5.6.17
- PHP Version: 7.1.8
- Laravel-admin: 1.5.x-dev

### Description:
When I click "Confirm" on the delete confirmation dialog, the DELETE request completes, but the confirmation modal does not dismiss. How can I get it to dismiss? 

### Steps To Reproduce:
Click the delete icon on an item in the table grid. Click "Confirm" on the confirmation alert. See that no matter the response of the HTTP request (to the delete endpoint,) the confirmation alert does not dismiss.

**Comment by z-song** [comment]
See any error in browser console?

**Comment by jonathanwkelly** [comment]
@z-song I don't. That's all clear. Where does the callback to close the alert get called? I tried to find it, but only have the minified code.

**Comment by jonathanwkelly** [comment]
@z-song what advice do you have?

**Comment by z-song** [comment]
I can't reproduce your problem

**Comment by yurik94** [comment]
same here, it returns 200.

**Comment by z-song** [comment]
Upgrade to v1.6.0,  this version use `SweetAlert2` instead
