### ISSUE TITLE
Custom Form (base custom widgets example)

### ISSUE THREAD

**Issue by ryonguyen** [z-song/laravel-admin#1976]
- Laravel Version: 5.6
- PHP Version: 7.0
- Laravel-admin: 1.5.*

### Description:
hi guys,

I want create a view,  I have a form have a lot data of many table different, when I submit it will save data in function name bookStore(). But It alway show error : 419 unknown status. And i can catch any parameter in that function.
 I create an example base custom widgets . 
Please show me how i can do it.

### Steps To Reproduce:

I create an COntroller like this:
php artisan admin:make NonModelController 

`<?php

namespace App\Admin\Controllers;

use App\Http\Controllers\Controller; 
use Encore\Admin\Layout\Content;
use Encore\Admin\Widgets\Box;
use Encore\Admin\Widgets\Form;
use Encore\Admin\Facades\Admin; 

class NonModelController extends Controller
{
    /**
     * Create interface.
     *
     * @return Content
     */
    public function bookCreate()
    {

        return Admin::content(function (Content $content) {

            $content->header('header');
            $content->description('description');

            $form = new Form();

            $form->method('post');
            $form->text('name_book');
            $form->text('desc_book');

            $content->body(new Box('bookCreate', $form));
        });
    }

    public function bookStore()
    {
       // I want handler form_parameter and save data in here
        return Admin::content(function (Content $content) {

            $content->header('header');
            $content->description('description');

            $form = new Form();

            $form->display('save success');

            $content->body(new Box('bookStore', $form));
        });
    }
}
`
This is my route file:

> `<?php

use Illuminate\Routing\Router;

Admin::registerAuthRoutes();

Route::group([
    'prefix'        => config('admin.route.prefix'),
    'namespace'     => config('admin.route.namespace'),
    'middleware'    => config('admin.route.middleware'),
], function (Router $router) {

    $router->get('/', 'HomeController@index');
    $router->get('/books/create', 'NonModelController@bookCreate');
    $router->post('/books/create', 'NonModelController@bookStore');
});`

**Comment by ryonguyen** [comment]
When a Submit button in Form click , what api will call? And how i can catch all form parameter?

**Comment by z-song** [comment]
What's shows you under Network tab in browser devtools when you submit form?

**Comment by ryonguyen** [comment]
![screen shot 2018-04-26 at 15 57 41](https://user-images.githubusercontent.com/4860303/39296266-a2c39d90-496a-11e8-987d-44e4eb0d9ddc.png)
It look like that.

**Comment by z-song** [comment]
419 means `Authentication Timeout`,  logout and try again

**Comment by ryonguyen** [comment]
![screen shot 2018-04-26 at 16 16 51](https://user-images.githubusercontent.com/4860303/39297277-4b87bbda-496d-11e8-94d5-35c7374ef731.png)
I show like this sir :(

**Comment by ryonguyen** [comment]
I see in this link:
[https://github.com/z-song/laravel-admin/issues/978](url)

can u show me how to write method  Controller->action().

In my case, what should I write method "bookStore"?

**Comment by ryonguyen** [comment]
Did u have any example? I dont find any example about function "request" sir :(

**Comment by ryonguyen** [comment]
Someone help me please? :(

**Comment by smunir** [comment]
Can somebody help in creating custom controller by using command php artisan admin:make NonModelController, I am getting Invalid model[] error. Which part of documentations refers to custom forms and views

**Comment by extralam** [comment]
protected function bookStore(Request $request)
{  
$request->all()
}
