### ISSUE TITLE
一对多，子表查询为什么这么慢？

### ISSUE THREAD

**Issue by edwinhuish** [z-song/laravel-admin#198]
每次都是点击查询后，发送带问号参数的get请求，然后URL跳回不带URL的参数，每次都需要等待1.2min左右才会有成功跳转到查询结果页面。请问为什么？
```php
            $grid->filter(function ($filter) {
                $filter->useModal();
            	$filter->disableIdFilter();
                $filter->like('reference', trans('sql.reference'));
                $filter->like('esp_name', trans('sql.esp_name'));
                $filter->like('colors.barcode', trans('sql.barcode'));
            });

```
```php
class Product extends Model
{
	/**
	 * 一对多，一个product有多个productColor
	 *
	 * @return \Illuminate\Database\Eloquent\Relations\HasMany
	 * author Edwin Hui
	 */
	public function colors()
	{
		return $this->hasMany(ProductColor::class);
	}
}
```

![image](https://cloud.githubusercontent.com/assets/5207925/21072150/b7dd359a-bef3-11e6-8cb2-67b55692c7af.png)
![image](https://cloud.githubusercontent.com/assets/5207925/21072152/c7086328-bef3-11e6-9a1c-23e370fe99fa.png)
![image](https://cloud.githubusercontent.com/assets/5207925/21072153/d3443720-bef3-11e6-9e28-2a83dcccd5ff.png)
![image](https://cloud.githubusercontent.com/assets/5207925/21072154/d96b7118-bef3-11e6-8eb3-6ebd5bd9786d.png)
![image](https://cloud.githubusercontent.com/assets/5207925/21072156/eab82ac4-bef3-11e6-9b12-e0245f581996.png)
![image](https://cloud.githubusercontent.com/assets/5207925/21072158/f717c8b0-bef3-11e6-907e-dc307cd883e5.png)

**Comment by z-song** [comment]
建议把sql语句拿出来  单独运行一下  看看是否很慢

**Comment by edwinhuish** [comment]
@z-song 请问怎么修改$filter的查询语句和逻辑？这个是另外一台比较好的机器上的测试，等待了20多秒。

![image](https://cloud.githubusercontent.com/assets/5207925/21085671/9582f13a-c04f-11e6-8c8a-f743d6751d93.png)

**Comment by edwinhuish** [comment]
@z-song 这性能差别真不是一点点。。。

![image](https://cloud.githubusercontent.com/assets/5207925/21085798/06e73f6a-c051-11e6-808f-b476ccbd833b.png)


![image](https://cloud.githubusercontent.com/assets/5207925/21085832/3fdddbf8-c051-11e6-8c50-e7a0ea1f5ff0.png)

**Comment by z-song** [comment]
要看一下你的数据量情况和索引情况

**Comment by edwinhuish** [comment]
谢谢提醒。
