### ISSUE TITLE
Image field doesn't work if I disable pjax

### ISSUE THREAD

**Issue by msassa** [z-song/laravel-admin#1981]
- Laravel Version: 5.5.28
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
Image field doesn't work if I disable pjax.
I removed all lines related to pjax into the laravel-admin.js in order to get the admin working without the ajax load. This works just fine, except for the image field.
This never validate the image, always say:

![image](https://user-images.githubusercontent.com/570080/39320734-74083cfe-495b-11e8-92fc-ef915c36e185.png)

**Comment by alihastam** [comment]
Admin::disablePjax();
