### ISSUE TITLE
demo里面的user表格，某一字段的下拉是怎么实现的

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#1983]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
请问下，demo里面的user表格，某一字段的下拉是怎么实现的，如下图所示，文档没找到
![image](https://user-images.githubusercontent.com/17559363/39348934-b1b8f90a-4a2b-11e8-8890-832616413118.png)

**Comment by never615** [comment]
demo 源码
https://github.com/z-song/laravel-admin.org

**Comment by z-song** [comment]
这是一个列扩展，不是内置功能，参考 https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/bootstrap.php#L23
