### ISSUE TITLE
建议对issuse中不是提bug和功能建议的(有很多是库的使用帮助),强制引导到项目网站的讨论板块提问

### ISSUE THREAD

**Issue by never615** [z-song/laravel-admin#1989]
这类issuse以不是一个issuse为理由直接关闭,然后让他们去这里:http://discuss.laravel-admin.org/ 
,进行库使用方面的提问.

因为需要关注这个库的动态,太多使用方面的issuse关注起来容易忽略有用的issuse

**Comment by z-song** [comment]
我没有多少时间在这个项目上，所以看到问题能解决的就帮忙解决一下，discuss.laravel-admin.org也没有时间去管理了
