### ISSUE TITLE
change value of field in edit

### ISSUE THREAD

**Issue by mirabdolbaghi** [z-song/laravel-admin#1993]
- Laravel Version: 5.6
- PHP Version:
- Laravel-admin: 1.5

### Description:
hi 
i want to change value of filed in edit

 i use jalili date 
but in database save date in georgian style 

i dont how to change value of date in edit

**Comment by uacode** [comment]
```
$form->datetime($column[, $label]);

// Set the date format, more format reference http://momentjs.com/docs/#/displaying/format/
$form->datetime($column[, $label])->format('YYYY-MM-DD HH:mm:ss');
```
