### ISSUE TITLE
[REQUEST] GRID Add Numerical order first column

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#1994]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5.dev

### Description:
How to create a column with 1, 2 ,3.. number on GRID not base on the column on model

**Comment by z-song** [comment]
I just pushed a commit cdad43b  to make `number` property of `Grid\Row` public, so you can do this: 
```php
$grid->rows(function (Grid\Row $row) {
   $row->column('number', $row->number);
});

// Your custom column.
$grid->number();
```
Update laravel-admin to `1.5.x-dev`

**Comment by taimaiduc** [comment]
It is working 
![image](https://user-images.githubusercontent.com/10907980/39612025-06982aea-4f86-11e8-883f-65b79df2255e.png)

**Comment by bthiban** [comment]
$grid->rows(function (Grid\Row $row) {
            $xRow = Photo::find($row->id);
            $img = '<img src="' . $xRow->getThumb() . '" />';
            $row->column('Image', $img);
        });

$grid->column('Image');

**Comment by aman0009-hacker** [comment]
$grid->rows(function (Grid\Row $row) {
   $row->column('number', $row->number);
});

// Your custom column.
$grid->column('number');


It start the number from 0 not from 1

**Comment by aman0009-hacker** [comment]
$grid->rows(function (Grid\Row $row) {
   $row->column('number', $row->number);
});

// Your custom column.
$grid->column('number');

It start the number from 0 not from 1

![Capture2](https://github.com/z-song/laravel-admin/assets/121216872/9c0b5777-72a7-4081-b51a-c5b8b062b70e)

**Comment by raniya49** [comment]
$grid->rows(function (Grid\Row $row) {
   $row->column('number', ++$row->number);
});

  // Your custom column.
  $grid->column('number')->display(function ($number)  {
      return $number;
  });
  
 it start the number from 1
