### ISSUE TITLE
导出操作，导出选择的行时，js报错selectRow()未定义

### ISSUE THREAD

**Issue by yiyufxst** [z-song/laravel-admin#1995]
- Laravel Version:5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
导出操作，导出选择的行时，js报错selectRow()未定义

### Steps To Reproduce:
1. 选中一行数据
2. 点击导出操作下拉按钮
3. 选择"选择的行"
4. 无下载csv弹窗返回，控制台报错
 `users:406 Uncaught ReferenceError: selectedRows is not defined`

**Comment by z-song** [comment]
无法重现你的问题

**Comment by yiyufxst** [comment]
我在laravel-admin网站的demo重现该问题。 @z-song
#### 复现步骤
1. 登录进入http://laravel-admin.org/demo/auth/users
2. F12进入Source栏，搜索selectRow无结果，搜索export-selected发现两个结果后
3. 选中一行数据，点击导出操作下拉按钮，选择"选择的行"
4. 无下载csv弹窗返回，控制台报错
5. 强制刷新也无效（初次打开示例网站，无第二步时可以正常导出）
![export](https://user-images.githubusercontent.com/19691753/39558222-5ebcef66-4ebf-11e8-8c14-dc94c9bee8e0.JPG)

**Comment by z-song** [comment]
提交了修复

**Comment by orzcc** [comment]
1.7.x 仍然存在这个问题

**Comment by chan17** [comment]
laravel admin publish 试试
