### ISSUE TITLE
提交的时候 走不到saving中

### ISSUE THREAD

**Issue by dupengshenyang** [z-song/laravel-admin#1996]
- Laravel Version: 5.5.*
- PHP Version: 7.2
- Laravel-admin: 1.5.*

### Description:
我把后台用户的控制器拿出来了 别的都正常 想在saving中处理一些数据 但是发现程序根本不走saving 翻了手册也没找到解决方法

**Comment by z-song** [comment]
哪个form的saving？

**Comment by dupengshenyang** [comment]
是我搞错了  抱歉
