### ISSUE TITLE
[bug]Embeds Form field not working when inserting data

### ISSUE THREAD

**Issue by hirossyi73** [z-song/laravel-admin#1998]
- Laravel Version: 5.5.*
- PHP Version: 7.1.*
- Laravel-admin: 1.5-dev

### Description:
If I set Embeds fields

``` ExampleController.php
return Admin::form(ExModel::class, function (Form $form) {
            $form->embeds('value', function (Form\EmbeddedForm $form) {
                $form->text('extra1')->rules('required');
                //$form->email('extra2')->rules('required');
                //$form->mobile('extra3');
                //$form->datetime('extra4');
            });
            $form->display('created_at', 'Created At');
            $form->display('updated_at', 'Updated At');
        });
```

When I saved as creating, column "value" is null, but when I saved as updating, column "value" is saveing as json.

I investigated "Form.php", and I found the function "isHasOneRelation" in "prepareInsert" is true.
I think the function "isHasOneRelation" is for relationship "hasOne", but using embed, it's true. so, the "value" array converts to flatten dotted string, it's wrong.

How to reslove this?

--

**Comment by hirossyi73** [comment]
@gozhhu 
Thanks a comment.

What you say the mean is adding a column before "$form->embeds"?

ex.

```
return Admin::form(ExModel::class, function (Form $form) {
            $form->hidden('foobar'); // ←add.
            $form->embeds('value', function (Form\EmbeddedForm $form) {
                $form->text('extra1')->rules('required');
                //$form->email('extra2')->rules('required');
                //$form->mobile('extra3');
                //$form->datetime('extra4');
            });
            $form->display('created_at', 'Created At');
            $form->display('updated_at', 'Updated At');
        });
```

**Comment by gozhhu** [comment]
Yes something like that, I added another field before embeds, I have not
tested hidden, I added a text or select field.
