### ISSUE TITLE
column()方法似乎不能正常工作

### ISSUE THREAD

**Issue by ilessy** [z-song/laravel-admin#2]
我用的5.2版本的laravel。因为我表里面有个column叫title和一个方法重名，所以要按照文档里面：

`使用column()方法：$grid->column('name', '用户名');`

但是我使用的时候提示

```
ErrorException in Grid.php line 131:
Undefined variable: relation
```

**Comment by ilessy** [comment]
```
 if($relation instanceof Relation) {
            $this->model()->with($relationName);
            $column->setRelation($relation, $relationColumn);
        }
```
把这段注释掉后正常了,不过我想这段是需要处理关联表的显然不能直接删除. 请帮忙看看这是怎么回事.

**Comment by z-song** [comment]
@ilessy 修改成
`
if(isset($relation) && $relation instanceof Relation) {
    $this->model()->with($relationName);
    $column->setRelation($relation, $relationColumn);
}
`
谢谢反馈！！

**Comment by ilessy** [comment]
非常感谢,你做的这个节约了我这新手好多时间.
可以早点下班回家了.
