### ISSUE TITLE
How to Authenticate user login with email ?

### ISSUE THREAD

**Issue by thatoe** [z-song/laravel-admin#2007]
- Laravel Version: 5.5.34
- PHP Version:7.2
- Laravel-admin: 1.5.9

How to customize AuthController to access login with Username or Email ?

**Comment by z-song** [comment]
@thatoe See this https://github.com/z-song/laravel-admin/issues/1739#issuecomment-383784417

**Comment by thatoe** [comment]
I also want to access admin login with username or email. how can i customize that ? 
I copied AuthController.php to Admin/Controller. 

`public function postLogin(Request $request)
    {
        $credentials = $request->only(['username', 'password']);
        $validator = Validator::make($credentials, [
            'username' => 'required', 'password' => 'required'
        ]);

        if ($validator->fails()) {
            return Redirect::back()->withInput()->withErrors($validator);
        }
        dd(Auth::guard('admin')->attempt($credentials));

        if (Auth::guard('admin')->attempt($credentials)) {
            admin_toastr(trans('admin.login_successful'));

            return redirect()->intended(config('admin.route.prefix'));
        }

        return Redirect::back()->withInput()->withErrors(['username' => $this->getFailedLoginMessage()]);
    }` 

How to customize that function ?

**Comment by llxx-lord-xxll** [comment]
I also need to know how to edit AuthController, i tried by copying those files to App/Admin/Controllers. Other files are getting edited but AuthController is still being read from Vendor Package

**Comment by kundius** [comment]
@llxx-lord-xxll @thatoe The field name is also present in the [view](https://github.com/z-song/laravel-admin/blob/master/resources/views/login.blade.php).
You can change field name manually [here](https://github.com/DomenART/abcfarben/blob/master/app/Admin/Controllers/AuthController.php#L54)
