### ISSUE TITLE
Modify Form Footer Content

### ISSUE THREAD

**Issue by llxx-lord-xxll** [z-song/laravel-admin#2010]
- Laravel Version: 5.5.40
- PHP Version: 7.1.1
- Laravel-admin: 1.5.x-dev

### Description:
Is there any way to change save button text in the Form ? 

### Steps To Reproduce:

I have done this so far
![image](https://user-images.githubusercontent.com/6489365/39660629-0bc17d02-5065-11e8-9a9b-7d02587468e1.png)

Now i want to rename this save button to "Reply"
![image](https://user-images.githubusercontent.com/6489365/39660632-294dd280-5065-11e8-8c1b-cbd2a9ba4ecb.png)

**Comment by z-song** [comment]
You can copy `vendor/encore/laravel-admin/resources/views/form.blade.php` to `resources/views` folder,  and modify it according to your needs, then specify your custom view by using `$form->setView('xxx');`

**Comment by llxx-lord-xxll** [comment]
Thank you @z-song
