### ISSUE TITLE
文件上传 $form->file() 上传文件报错

### ISSUE THREAD

**Issue by feivorid** [z-song/laravel-admin#2018]
- Laravel Version: 5.5.39
- PHP Version: 7.1.15
- Laravel-admin: ^1.5

### Description:
![image](https://user-images.githubusercontent.com/5013223/39683142-7cb3bf5c-51e6-11e8-99e7-0f7c26a98d93.png)
如图 是 上传文件的代码 暂时还没限制上传文件的类型

但是效果是只有上传图片好用    上传.mp3文件就报错 
![image](https://user-images.githubusercontent.com/5013223/39683182-ba1208ae-51e6-11e8-8e00-7b40549fb0c4.png)

上传word excel 文件  不报错 但是 是不能取到上传之后的文件的url  编辑的时候显示空白

很费解 这个问题   @z-song 

在issue 里面找了一下  文件上传报错的  让看 [https://github.com/z-song/laravel-admin/issues/1805] 但是我的Gd库安装好了  已经有了 感觉跟这个没关系    求帮助  大神们

**Comment by z-song** [comment]
照着异常，跟一下代码，看看具体原因在哪里

**Comment by feivorid** [comment]
@z-song    xdebug  跟了一下  但是都是回调 实在是找不到哪里处理提交后这个路径的   还希望大神指点一下 🙏

**Comment by z-song** [comment]
看异常，FilesystemAdapter.php209行，进去看看

**Comment by feivorid** [comment]
![image](https://user-images.githubusercontent.com/5013223/39685002-3d207b76-51f2-11e8-8800-209a2a175175.png)

@z-song   恩 这个看了    如图红圈圈起来的地方  打印出来的结果 有问题  结果如下图
![image](https://user-images.githubusercontent.com/5013223/39684984-25f1e8d6-51f2-11e8-8c49-c7c4c4422df5.png)

正常的图片好用的情况下  打印出来的结果 是   tmp/xxxxxx

主要是不知道 从 哪不到 这步的   所以找不到问题所在

**Comment by z-song** [comment]
文件上传的入口是`\Encore\Admin\Form\Field\File::prepare`, 文件`vendor/encore/laravel-admin/src/Form/Field/File.php`

**Comment by feivorid** [comment]
@z-song   首先感觉大神的指点  我用xdebug 跟踪一下 发现纬度当文件格式为mp3的时候   上传的error = 1 且tmp_name 为空
![image](https://user-images.githubusercontent.com/5013223/39688324-c6a1ce1a-5204-11e8-8084-70f294c99e65.png)

![image](https://user-images.githubusercontent.com/5013223/39688347-e486109e-5204-11e8-8747-7b4acce20838.png)


当文件为图片 word excel txt 等格式时候都是正常的    😭 😭

**Comment by z-song** [comment]
http://php.net/manual/en/features.file-upload.errors.php 在这里看error代码，1表示上传文件大小超过了你的php限制，需要修改php.ini的相关配置

**Comment by feivorid** [comment]
@z-song   很尴尬 😅    抱歉 浪费您时间了   问题像您说的  已解决  ！
