### ISSUE TITLE
页面载入不全情况

### ISSUE THREAD

**Issue by BI7PRK** [z-song/laravel-admin#2019]
- Laravel Version: #.#.#
- PHP Version: 7.2
- Laravel-admin: 1.5.13

### Description:
有时候页面载入不全。页面的源代码显示：
从<title> 开始，
到
```HTML
<!-- /.box-footer -->
    </form>
</div>
</div></div>
</section>
```
刷新一下页面才可以。
----------------------
已经搜索过 issue，似乎没看到有这方面的反馈。这是什么原因？如何处理？谢谢。

**Comment by ShuiPingYang** [comment]
你的最后怎么解决的?我也遇到了这个问题,同一个页面,刷新几次就可以显示,接着刷新几次,又不显示.
![image](https://user-images.githubusercontent.com/22534808/116530152-4826b800-a910-11eb-9c7a-1cc2dc3cc0ab.png)
下面刷新几次显示正常:
![image](https://user-images.githubusercontent.com/22534808/116530246-67bde080-a910-11eb-97a7-69401072728f.png)
