### ISSUE TITLE
一对一的关系form构建问题

### ISSUE THREAD

**Issue by elinxer** [z-song/laravel-admin#202]
我的文章表articles表和内容表article_content进行了拆分，怎么form里面关联，模型已经建立了加入了content()建立hasOne关系
![image](https://cloud.githubusercontent.com/assets/7327251/21085023/45474732-c047-11e6-89ee-2dfd76d08546.png)

因为article_content内容表有多个字段要更新，怎么在form里面进行关联呢？

**Comment by z-song** [comment]
`关系名.关联表字段名` => `$form->textarea('content.content');`
