### ISSUE TITLE
怎么为过滤器添加默认值？

### ISSUE THREAD

**Issue by MoonLiu666** [z-song/laravel-admin#2023]
- Laravel Version: 5.5.#
- PHP Version:7.0
- Laravel-admin: 1.5.#

##### 请问一下大佬，对过滤器添加默认值需要哪些操作？
    
     比如过滤器中有个按时间between过滤，数据库数据比较多，我想进来时默认显示当月数据，当然，使用者也可以修改这个查询时间来查询其他月份数据，需要怎么处理？

**Comment by geekli** [comment]
替代方案  使用 $request 对象的合并参数
