### ISSUE TITLE
多图与多文件删除出错。

### ISSUE THREAD

**Issue by qiumzh** [z-song/laravel-admin#2025]
- Laravel Version: 5.5.*
- PHP Version:7.1.13
- Laravel-admin: 1.5.*

### Description:

多图文件删除时报错：
![image](https://user-images.githubusercontent.com/12442026/39806424-7f583824-53ac-11e8-8354-042ebfb423c0.png)

**Comment by manzhouya** [comment]
@qiumzh 怎么解决的，我也遇到了
