### ISSUE TITLE
assets are getting load over http

### ISSUE THREAD

**Issue by alpharameeztech** [z-song/laravel-admin#2027]
- Laravel Version: 5.6
- PHP Version: 7.3
- Laravel-admin: 1.5

### Description:
Laravel is not loading my http asset files. How can I change that admin_asset() function to load asset files over https

**Comment by tfarneau** [comment]
Same problem

**Comment by alpharameeztech** [comment]
@tfarneau thankyou for the help

**Comment by rap2hpoutre** [comment]
haha thanks @tfarneau ;)
