### ISSUE TITLE
Grid->column 根據當前字段值的不同 設置不同的 Grid->column類型

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#2033]
如何實現:
if (該字段當前值>1) {
    $grid->column('status', '訂單狀態')->editable('select', config('yesfood.type.order_status'));
} else {
    $grid->column('status', '訂單狀態');
}

這個問題卡了一整天了~ 各種方法都嘗試了, 甚至去table.blade.php裡去判斷也沒能解決
其中$grid->actions(function($action))是可以獲取當前行的數據進行判斷的, 
不知是否能夠對$grid->column也進行擴展來滿足這個需求..已經遇到好多次了.
非常感謝

**Comment by z-song** [comment]
没有比较方便的方法，用下面的方法试试看
```php
        $grid->column('status', '訂單狀態')->display(function ($status) use ($grid) {

                if ($status > 1) {
                    $column = new Grid\Column('status', '');

                    $editable = new Grid\Displayers\Editable($status, $grid, $column, $this);

                    return $editable->display('select', config('yesfood.type.order_status'));
                }

                return $status;
            });
```

**Comment by faydanube** [comment]
非常感謝..針對從這個需求我找到了一個還算簡單的方法,,貼出來.
因為editable之後 傳入的$value 就相當於是一個editable實例,,而$this->status則是一個值,所以可以這麼做.這個問題可以關閉啦.非常感謝!
            $grid->column('status', '訂單狀態')->editable('select', config('yesfood.type.order_status1'))->display(function($value) {
                if ($this->status == 1) {
                    return config('yesfood.type.order_status')[$this->status];
                } else {
                    return $value;
                }
            });
