### ISSUE TITLE
如何重构后台页面

### ISSUE THREAD

**Issue by iiDestiny** [z-song/laravel-admin#2034]
- Laravel-admin: 1.5.x-dev

比如我想重构一些页面如，菜单样式、列表、是不是只有把 vendor 下面的 laravel-admin package 给拷贝出来，让 laravel 加载拷贝的 package，这样才可以或者这样才方便？

**Comment by z-song** [comment]
参考 http://laravel-admin.org/docs/#/zh/qa?id=%E9%87%8D%E5%86%99%E5%86%85%E7%BD%AE%E8%A7%86%E5%9B%BE
