### ISSUE TITLE
Editor not working

### ISSUE THREAD

**Issue by rafayet-monon** [z-song/laravel-admin#2036]
- Laravel Version: 5.6.17
- PHP Version: 7.1.16
- Laravel-admin: latest. (can't find the version)

### Description:

I have a blog table and a field named 'content'
I am trying to use the editor like this
            $form->editor('content');
But nothing shows. No error in the js either. Would really like some help.

**Comment by msassa** [comment]
Try to remove 'editor' from:
- app/Admin/bootstrap.php
   Encore\Admin\Form::forget(['map', 'editor']);

**Comment by rafayet-monon** [comment]
Thanks a lot, didn't notice that.

**Comment by protectedfor** [comment]
It didn't help me. Why?

**Comment by RaiserWeb** [comment]
Looks like it's been removed from the core field registration. Adding the following inside App\Admin\bootstrap.php (above the forget method) fixed for me.

`Encore\Admin\Form::extend('editor', Encore\Admin\Form\Field\Editor::class);`
