### ISSUE TITLE
怎么把图片上传到腾讯云cos

### ISSUE THREAD

**Issue by maokuan** [z-song/laravel-admin#2041]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5

### Description:
              怎么把图片上传到腾讯云cos，没有找到对应的laravel storage适配器咋办？

**Comment by huangxiaoye** [comment]
我也想知道，看来作者是不打算支持了。

**Comment by z-song** [comment]
https://laravel-admin.org/docs/zh/model-form-upload#%E4%BA%91%E5%AD%98%E5%82%A8%E9%80%82%E9%85%8D%E5%99%A8

最下面列出了常用云存储的Laravel适配器
