### ISSUE TITLE
wangEditor中的bug

### ISSUE THREAD

**Issue by Liujingying** [z-song/laravel-admin#2043]
- Laravel Version: 5.6
- PHP Version:7.1.3
- Laravel-admin: 1.5

### Description:
使用demo查看wangEditor的时候，返回再前进，就会出现两个嵌套的Editor，生成Editor的代码执行了两次。
![image](https://user-images.githubusercontent.com/10573518/39993990-6ec9870e-57aa-11e8-86cb-ddaf1b0f96f7.png)

**Comment by z-song** [comment]
初始化了多次，你要在脚本里面检查一下是否已经初始化过来
