### ISSUE TITLE
Getting error if reload model form page or open it not from model grid

### ISSUE THREAD

**Issue by Mike-Savin** [z-song/laravel-admin#2044]
- Laravel Version: 5.5
- PHP Version: 7.1.12
- Laravel-admin: 5.5.13

### Description:
When I try to reload model edit/create page or open it directly through url, not through Grid page, getting error:

Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
…/vendor/encore/laravel-admin/src/Layout/Column.php:0

Method Encore\Admin\Form::__toString() must not throw an exception, caught Error: Call to a member function model() on null

### Steps To Reproduce:
1. Open model edit page.
2. Reload it.

**Comment by chenzm** [comment]
It is dingo that causes this problem, and it is recommended to use the API _DOMAIN configuration in the .env file to avoid the same domain name in the API and Admin panel
