### ISSUE TITLE
MultipleImage 无法正常保存。

### ISSUE THREAD

**Issue by Tairy** [z-song/laravel-admin#2046]
- Laravel Version: 5.6.*
- PHP Version: 7.1.12
- Laravel-admin: 1.5.*

### Description:
在 Form 里面只存在一个 `MultipleImage` 时保存不了，查了一下应该是提交的参数是以文件名命名的字符串，导致触发了 `MultipleImage` 的 `image` 检测规则，返回了 false。

```
$form->multipleImage('pic', '图片'); // 单独一个 multipleImage 无法保存。
```

在 form 里面又加了一个 image ，居然可以保存了，不知道啥原因。

```
$form->multipleImage('pic', '图片');
$form->image('pic2', 'pic2');
// 这样就可以保存了，pic2 是随便取得一个字段名，不一定在数据库中存在。
```

**Comment by mineschan** [comment]
確實有這樣的問題 + 1
