### ISSUE TITLE
覆盖vendor模板没有成功

### ISSUE THREAD

**Issue by crazytonygo** [z-song/laravel-admin#205]
app('view')->addNamespace('admin', resource_path('views/admin'));
按照文档中的方法,在app/Admin/bootstrap中写入上面的代码
再复制vendor/encore/laravel-admin/views下的其中一个blade文件到项目的resources/views/admin目录下
发现还是没有被覆盖,依然读取vendor/encore/laravel-admin/views下的文件,求教,问题出在哪个环节,是我从文档中理解错了吗

**Comment by z-song** [comment]
@crazytonygo 不好意思，使用`prependNamespace()`方法才能覆盖，已经修改文档。

```php
app('view')->prependNamespace('admin', resource_path('views/admin'));
```

**Comment by crazytonygo** [comment]
谢谢你,很抱歉没有去看最新的文档,放到app/admin/routes.php执行后成功了

**Comment by yatong2008** [comment]
遇到类似的问题，我放在bootstrap.php里面没有用不过放在routes.php就可以，我在bootstrap里面debug打了断点但是没有走到这里，想问一下是不是App/Admin/Bootstrap.php是不是没有正确加载，如果是没有加载的话，应该在哪里设置呢？

**Comment by JefferyWong** [comment]
@crazytonygo 请问放在routes.php什么位置？我放在routes.php 和 bootstrap.php 都不管用
