### ISSUE TITLE
Laravels环境下执行tools->append的时候会超时

### ISSUE THREAD

**Issue by sandersyao** [z-song/laravel-admin#2052]
- Laravel Version: 5.6.21
- PHP Version:7.2.4
- Laravel-admin: v1.5.13

### Description:
项目是在laravels的环境下运行不是fpm，有可能是受swoole的特性影响导致响应超时。

### Steps To Reproduce:
```
//$grid:Encore\Admin\Grid
$grid->tools(function ($tools) {
    $tools->append();
});
```
添加这段代码的时候会超时

**Comment by z-song** [comment]
没有能复现你的问题
