### ISSUE TITLE
BUG: On model-tree re-order : POST don't save new order, but INSERT new empty line in DB

### ISSUE THREAD

**Issue by connected-company** [z-song/laravel-admin#2053]
- Laravel Version: v5.4.36
- PHP Version: v5.6.31 ( WAMP v3.1.0 on Windows 10 64bit )
- Laravel-admin: v1.4.6

### Description:

I create a new model-tree like the controller in vendor MenuController

### Steps To Reproduce:

When I re-order (index view) and click on the save button, browser POST to my MenuController@store method this application/x-www-form-urlencoded; charset=UTF-8 datas :

_order | [ {"id":1}, {"id":2,"children":[ {"id":3}, {"id":4} ]} , ... ]
_token | ONE_TOKEN

Like MenuController in vendor, for Laravel-admin menu itself.

My controller version don't persiste new order and new parent_id, but INSERT in DB a new empty item.

**Comment by connected-company** [comment]
This was related to mony other issues #243 : **Can't insert null value.**

To fix this I have in my model a boot() with :

https://github.com/z-song/laravel-admin/issues/243#issuecomment-269586362

```
static::saving(function (Model $branch) {
    if ( $branch->page_id == '')
        $branch->page_id = null;
}
```

BUT This overide the Trait ModelTree static::saving(function (Model $branch) closure

```
static::saving(function (Model $branch) {
    if ( $branch->page_id == '')
        $branch->page_id = null;

    // NEED to call ModelTree Trait closure : static::saving( function (Model $branch) { ... } );
}
```

**Comment by Liujingying** [comment]
how do you resolve this question？

**Comment by Baiyongjian** [comment]
I also encountered the same problem, how are you solved?

**Comment by Baiyongjian** [comment]
> 你怎么解决这个问题？

你也是在做一个新的树的时候发现保存不好使的吗？

**Comment by yuan1998** [comment]
@Baiyongjian 你是不是用一个 Class 继承了另一个Model.
```
TestCategory extends Category {
   ....
}
```

**Comment by lutianxiong** [comment]
How did you solve this bug?

**Comment by r-nkj** [comment]
```
    use AdminBuilder, ModelTree {
        ModelTree::boot as treeBoot;
    }
```

```
    protected static function boot()
    {
        ...
        static::treeBoot();
        ...
    }
```
