### ISSUE TITLE
分页的时候，在点到第5页的时候，会出现这个错误

### ISSUE THREAD

**Issue by wnaghuixin** [z-song/laravel-admin#2054]
- Laravel Version: 5.5.21
- PHP Version:7.0.25
- Laravel-admin:1.5.*

### Description:
Method Encore\\Admin\\Grid::__toString() must not throw an exception, caught Error: Call to a member function toArray() on null\/data\/www\/order\/vendor\/encore\/laravel-admin\/src\/Layout\/Column.php(0)

**Comment by z-song** [comment]
无法重现
