### ISSUE TITLE
Form set Actions error

### ISSUE THREAD

**Issue by ryonguyen** [z-song/laravel-admin#2056]
- Laravel Version: 5.6
- PHP Version: 7.0
- Laravel-admin: 1.5.*

### Description:
I create a model (not exists table ) then when i create function form() I set action on a new url. but it always show error "method not allow 405".
This is my code : 
` protected function form()
    {
        return Admin::form(Posts::class, function (Form $form) {

            $form->display('UserName')->value(Admin::user()->username);

            $form->text('title');
            $form->ckeditor('descriptions');
            $form->text('user_id')->value(Admin::user()->id);
            $form->datetime('created_at');
            $form->datetime('updated_at');

            $form->tools(function (Form\Tools $tools) {
                // Disable list btn
                $tools->disableListButton();

            });
            $form->method('POST');
            $form->setAction ('/admin/api/store');
        });
    }`
this is my route:
`$router->post('/api/store', 'PostController@bookStore');
    $router->get('/api/store', 'PostController@bookStore');
    $router->resources([

        'posts'                  => PostController::class,

    ]);`

Can u help me fix it?
### Steps To Reproduce:
![screen shot 2018-05-21 at 10 21 45](https://user-images.githubusercontent.com/4860303/40289205-3a0f88ec-5ce1-11e8-84c1-2fd6bb85eee2.png)

**Comment by frogle** [comment]
I have the same problem

**Comment by yassinMk** [comment]
you handle the form action by adding the `create` and `update` action in your admin controller, that's how laravel-admin form is working

**Comment by ujju3073** [comment]
I have more than one form on same controller but it always define to the same route?

**Comment by agentemotor** [comment]
> * Versión de Laravel: 5.6
> * Versión PHP: 7.0
> * Laravel-admin: 1.5. *
> 
> ### Descripción:
> Creo un modelo (no existe una tabla) luego, cuando creo el formulario de función (), configuro la acción en una nueva URL. pero siempre muestra el error "el método no permite 405".
> Este es mi código:
> `formulario de función protegida ()
> {
> return Admin :: formulario (Publicaciones :: clase, función (formulario $ formulario) {
> 
> ```
>         $form->display('UserName')->value(Admin::user()->username);
> 
>         $form->text('title');
>         $form->ckeditor('descriptions');
>         $form->text('user_id')->value(Admin::user()->id);
>         $form->datetime('created_at');
>         $form->datetime('updated_at');
> 
>         $form->tools(function (Form\Tools $tools) {
>             // Disable list btn
>             $tools->disableListButton();
> 
>         });
>         $form->method('POST');
>         $form->setAction ('/admin/api/store');
>     });
> }`
> ```
> 
> esta es mi ruta:
> `$ router-> post ('/ api / store', 'PostController @ bookStore');
> $ router-> get ('/ api / store', 'PostController @ bookStore');
> $ enrutador-> recursos ([
> 
> ```
>     'posts'                  => PostController::class,
> 
> ]);`
> ```
> 
> ¿Puedes ayudarme a arreglarlo?
> 
> ### Pasos para reproducir:
> ![captura de pantalla 2018-05-21 a las 10 21 45](https://user-images.githubusercontent.com/4860303/40289205-3a0f88ec-5ce1-11e8-84c1-2fd6bb85eee2.png)

Change use Encore\Admin\Widgets\Form;   to use Encore\Admin\Form;
