### ISSUE TITLE
文件上传如何获取文件名？

### ISSUE THREAD

**Issue by qiumzh** [z-song/laravel-admin#2058]
- Laravel Version: 5.5.*
- PHP Version:7.1.2
- Laravel-admin: 1.5.*

### Description:

我上传一个文件，我想获取该文件的名字，并把文件的名字保存到数据库，请问我应该怎样获取？

$form->file($column[, $label]);

// 修改文件上传路径和文件名
$form->file($column[, $label])->move($dir, $name);

// 并设置上传文件类型
$form->file($column[, $label])->rules('mimes:doc,docx,xlsx');

// 添加文件删除按钮
$form->file($column[, $label])->removable();

**Comment by jxlwqq** [comment]
在saving方法里获取：
```
$form->saving(function(Form $form) {
$originName  = \Request::file('column')->getClientOriginalName();
})
```
