### ISSUE TITLE
how to remove the single image while previewing

### ISSUE THREAD

**Issue by periyakannan** [z-song/laravel-admin#2060]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#
![2018-05-22-124837_1366x768_scrot](https://user-images.githubusercontent.com/38691572/40347610-82344d64-5dbe-11e8-8f05-0a197b655747.png)

### Description:
how to remove the single image while previewing the images..

### Steps To Reproduce:

**Comment by periyakannan** [comment]
@z-song pls answer

**Comment by periyakannan** [comment]
@z-song how to delete single image while previewing the multiple image..

**Comment by sepehr09** [comment]
` $form->multipleImage('images')->removable();`

**Comment by MicoHe** [comment]
have you got an answer?i am meeting the same problem，when you use the '$form->mutipleimage(),how to delete the single image when preview?

**Comment by z-song** [comment]
@periyakannan @MicoHe This upload plugin is based on [bootstrap-fileinput](https://github.com/kartik-v/bootstrap-fileinput), and it's not support to remove files that not upload.

See explanation here https://github.com/kartik-v/bootstrap-fileinput/issues/754#issuecomment-247843511
