### ISSUE TITLE
Getting inputs of hasmany relations field

### ISSUE THREAD

**Issue by pcfjojo** [z-song/laravel-admin#2062]
@z-song 
`   $form->hasMany('credits', 'Credits Remains', function (Form\NestedForm $form) {
$form->currency('price', 'Price')->symbol('Rs.')->rules('required');
});
`

` $form->saving(function (Form $form) { });`

In this method how can i retrive current input field value of the **hasmany** relations filed?
#here i need to get the price of each credit to compare with previous price.
Any help?

**Comment by shelestovas** [comment]
$form->saving(function (Form $form) {
                dump($form->credits);
            });
