### ISSUE TITLE
[Form] uploaded image doesn't appear

### ISSUE THREAD

**Issue by fokoz** [z-song/laravel-admin#2064]
- Laravel Version: 5.5
- PHP Version: 7.0
- Laravel-admin: 1.5

### Description:
the uploaded image doesn't appear after uploading(but it is saved) when the model's method is camelCase.
I've tried both
`$form->image('profile_image.path', 'profile image')->uniqueName();`
and
`$form->image('profileImage.path', 'profile image')->uniqueName();`

**Comment by fokoz** [comment]
PS. 
if I use this one:
`$form->image('profile_image.path', 'profile image')->uniqueName();`
It will cannot be saved but it will appear.
but if I use this one instead:
`$form->image('profileImage.path', 'profile image')->uniqueName();`
It will can be saved but won't appear.

**Comment by almo7amady** [comment]
the best way is to change the **APP_URL** in your _.env_ file from **http://localhost** to **http://localhost:8000** and you are done 👍
