### ISSUE TITLE
Replace delete action for spesific controller

### ISSUE THREAD

**Issue by victormeidy** [z-song/laravel-admin#2069]
- Laravel Version: 5.6
- PHP Version: 7
- Laravel-admin: 1.5

I need to replace delete action to become update action which just update value to 1 of my database column at one of my controller.
Is there any ways i can do it on laravel-admin?

Thanks before.

**Comment by z-song** [comment]
Just add a `destroy` action to your controller  and do the update work
```php
public function destroy($id)
{
    // Update the column value here

    return response()->json([
        'status'  => true,
        'message' => 'success',
    ]);
}
```

**Comment by victormeidy** [comment]
Thank you @z-song , can you please with below code, still not success update the value

```
public function destroy($id)
    {
        Admin::form(Department::class, function (Form $form) {
            $form->text('isactive')->value(0);
        });
        if ($this->form()->update($id))
            {
                return response()->json([
                    'status'  => true,
                    'message' => 'success',
                ]);
            }
    }
```

**Comment by chiwex** [comment]
> Thank you @z-song , can you please help below code, still not success update the value
> 
> ```
> public function destroy($id)
>     {
>         Admin::form(Department::class, function (Form $form) {
>             $form->text('isactive')->value(0);
>         });
>         if ($this->form()->update($id))
>             {
>                 return response()->json([
>                     'status'  => true,
>                     'message' => 'success',
>                 ]);
>             }
>     }
> ```
this method is no longer working. is there anyway to validate before deleting

**Comment by sonpvl-AGL** [comment]
> Just add a `destroy` action to your controller and do the update work
> 
> ```
> public function destroy($id)
> {
>     // Update the column value here
> 
>     return response()->json([
>         'status'  => true,
>         'message' => 'success',
>     ]);
> }
> ```

I've try by it does not work, any update? thank you
