### ISSUE TITLE
导出功能中文乱码

### ISSUE THREAD

**Issue by yiyufxst** [z-song/laravel-admin#2071]
### Description:
导出功能，导出的csv文件，中文显示乱码

### Steps To Reproduce:
1. 进入http://laravel-admin.org/demo
2. 选择Demo-Users ，点击导出当前页
3. 打开csv文件，中文显示乱码
@z-song

**Comment by MoonLiu666** [comment]
我这边也是。
只能重写了部分代码，进行了转码
希望优化一下

![image](https://user-images.githubusercontent.com/22115885/40821163-c7a29bc2-6597-11e8-94bd-4b20bdc74da3.png)
