### ISSUE TITLE
can not get selected items in Checkbox in many to many relation

### ISSUE THREAD

**Issue by shelestovas** [z-song/laravel-admin#2072]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:

In form() method
`
$form->checkbox('buildingClasses', 'Класс жилого комплекса')
     ->options(BuildingOption::where('type', 'building_class')->pluck('name', 'id'));
`
In Model:
`
    public function buildingClasses()
    {
        return $this->belongsToMany(BuildingOption::class);
    }
`

and after save form checkbox in edit page is empty
![joxi_screenshot_1527162470938](https://user-images.githubusercontent.com/12628413/40483781-e0258380-5f61-11e8-9eed-373a2fb590f0.png)

in base all good
![joxi_screenshot_1527162427305](https://user-images.githubusercontent.com/12628413/40483767-ca988314-5f61-11e8-8705-9a25877359e0.png)

how can this be fixed? Thank you!

**Comment by xiaomlove** [comment]
use snake_case relationship and filed name  will be OK.
