### ISSUE TITLE
nbsp tag spam

### ISSUE THREAD

**Issue by siteincity** [z-song/laravel-admin#2077]
- Laravel Version: 5.6.*
- PHP Version: 7.2.6RC1 For windows 7 x86
- Laravel-admin: ^1.5
- DB:    10.1.31-MariaDB - mariadb.org binary distribution 

### Description:
After install
![11](https://user-images.githubusercontent.com/14177061/40576245-b0e772c4-6103-11e8-8b1b-df65a1200975.jpg)
How to fix this?

### Steps To Reproduce:
composer require encore/laravel-admin
php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider"
php artisan admin:install

**Comment by z-song** [comment]
```php
<?php

namespace App\Providers;

use Illuminate\Support\Facades\Blade;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    /**
     * Bootstrap any application services.
     */
    public function boot()
    {
        // add this line
        Blade::withoutDoubleEncoding();
    }

    /**
     * Register any application services.
     */
    public function register()
    {
        //
    }
}

```

**Comment by daniel-werner** [comment]
I have the same issue, modifying the service provider didn't solve the issue for me (using Laravel 5.6).

**Comment by alexandrekadri** [comment]
doesn't work
