### ISSUE TITLE
Unable to use this package with Laravel 5.6

### ISSUE THREAD

**Issue by floodedcodeboy** [z-song/laravel-admin#2078]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: 1.5.4

### Description:

Upgrading a project to laravel 5.6. 
This package references laravel 5.5 as a dependency using ~ and not ^ 

### Steps To Reproduce:

Update package.json with "laravel/framework": "5.6.*"
then run `composer update`  observe composer problems

**Comment by siteincity** [comment]
I installed this on the laravel version 5.6 without problems, but found a lot of minor interface bugs =(
