### ISSUE TITLE
Model id is empty in form

### ISSUE THREAD

**Issue by AndreyBashuk** [z-song/laravel-admin#2080]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

Hi, first of all thanks for this incredible package. But i find some issues when i want to fetch model id on the fly. Imagine that i want to create path to storage files for a specitic user:
![image](https://user-images.githubusercontent.com/35767496/40589549-d8900760-61f7-11e8-846d-8882c7048407.png)

Model data is empty:
![image](https://user-images.githubusercontent.com/35767496/40589579-5d1d7b0c-61f8-11e8-8a34-f9d27dfd9263.png)

But in the form my model is null, and i can't do this. I cant specify id related to model that i edit. Maybe i miss something, but please, can you help me with this issue?

**Comment by OppPMatos** [comment]
Also having this problem.
