### ISSUE TITLE
文件上传视频类保存后，不显示预览

### ISSUE THREAD

**Issue by shencm** [z-song/laravel-admin#2083]
- Laravel Version: 5.5.#
- PHP Version:
- Laravel-admin: 1.5.#

### Description:
$form->file上传视频的预览有视频控件，保存后就不显示视频了，看html，是插入了img标签

顺便问下，怎么判断上传视频的秒数

**Comment by changPHP** [comment]
是的，以文件形式上传视频后，在点开编辑，视频是以img标签遍历的，我这边也遇到这个问题了，请问这问题是否解决了？

**Comment by xialamp** [comment]
我这边也遇到这个问题了,请问你们解决了吗？

**Comment by a1300657068** [comment]
我这边也遇到这个问题了,请问你们解决了吗？

**Comment by wuhaohui** [comment]
我这边也遇到这个问题了，请问你们解决了吗

**Comment by elevenDimension** [comment]
$form->multipleFile('video', 'videoLabel')->options([
                    'initialPreviewConfig' => [['filetype' => 'video/mp4']],
                    'initialPreviewFileType' => 'video',
                ]);

**Comment by xdli-ch** [comment]
实测可行：
        $form->file('url', '上传视频')->uniqueName()->move('files/movie')->options([
            'initialPreviewConfig' => [['filetype' => 'video/mp4']],
            'initialPreviewFileType' => 'video',
        ])->rules('required',['required'=>'请上传视频']);
