### ISSUE TITLE
不修改图片无法更新

### ISSUE THREAD

**Issue by Justes** [z-song/laravel-admin#2085]
- Laravel Version: 5.6.15
- PHP Version: 7.1.14
- Laravel-admin: 1.5

### Description:

管理员管理，修改管理员信息

表单里如果有图片，不修改图片其他的内容也无法修改

![image](https://user-images.githubusercontent.com/8057887/40620427-5ddc16e2-62cb-11e8-827f-e63e40ad4e69.png)

**Comment by mineschan** [comment]
我也遇到了這個問題，這個問題只在比較新的Safari會出現，有fix之前可以試試用chrome繞過..

**Comment by mineschan** [comment]
@z-song 可以看看嗎

**Comment by mineschan** [comment]
5.5也一樣 @z-song 大大 =(

**Comment by z-song** [comment]
在chrome和Safari都没有重现这个问题

**Comment by mineschan** [comment]
提供一下環境資料

Laravel Version: 5.5.* / 5.6.*
PHP Version: 7.2.8
Laravel-admin: 1.5.18

OS: 10.13.4
Safari Version: 11.1
Web Server: nginx

nginx環境會有關係嗎？

**Comment by mineschan** [comment]
我現在只可以用
```Admin::script("$('form').attr('pjax-container', null)");```
解決一下

**Comment by imageslr** [comment]
我也遇到了这个问题。二次编辑的时候，如果不修改头像，会报错：`Argument 1 passed to Encore\Admin\Form\Field\File::getStoreName() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, string given, called in /home/vagrant/code/Laravel/vendor/encore/laravel-admin/src/Form/Field/Image.php on line 34`。

环境信息：
PHP: 7.2.5-1+ubuntu18.04.1+deb.sury.org+1 (cli) 
Laravel: 5.6.*
Laravel-admin: 1.5.19
