### ISSUE TITLE
登出时报500： Object of class Illuminate\Routing\Redirector could not be converted to string

### ISSUE THREAD

**Issue by milkytsu** [z-song/laravel-admin#2088]
- Laravel Version: 5.6

- PHP Version: 7.2.5
- Laravel-admin: 1.5.13

### Description:
使用默认帐号admin登出时，报500
/Library/WebServer/Documents/lexueying/lexueying_admin/vendor/symfony/http-foundation/Response.php

 387:       $this->content = (string) $content;
 
"Object of class Illuminate\Routing\Redirector could not be converted to string"

**Comment by AlmazDelDiablo** [comment]
Fixed by adding route prefix to admin config. Example:

```
    'route' => [
        'domain' => env('ADMIN_DOMAIN', 'admin'),
        'namespace' => 'App\\Admin\\Controllers',
        'middleware' => ['web', 'admin'],
        'prefix' => '',
    ],
```

Because not set prefix loads as null, not empty string. So Laravel tries to return Redirector instead of RedirectResponse from logout action.
