### ISSUE TITLE
点击搜索按钮 无效，弹出信息提示 undefined

### ISSUE THREAD

**Issue by luandun** [z-song/laravel-admin#209]
在列表页点击搜索按钮 会弹框提示 undefined

**Comment by luandun** [comment]
![image](https://cloud.githubusercontent.com/assets/11463204/21224033/2f707c92-c305-11e6-8777-727147fef24e.png)

**Comment by z-song** [comment]
@luandun 看下network返回的什么

**Comment by luandun** [comment]
network 没有响应。  不知道这个是否需要设置。我在最开始把项目装上的时候就有这个原因。 120.26.143.106 这个地址的demo源码能否 发下。 可能有些细节的地方没有处理好。我想参照下你的写法

**Comment by edwinhuish** [comment]
应该是路由没有配置好吧？

另外松说的是浏览器的network，如下图：
![image](https://cloud.githubusercontent.com/assets/5207925/21416784/91926c14-c850-11e6-9898-024f57e6a124.png)

**Comment by z-song** [comment]
这个问题解决了  更新到最新版本
