### ISSUE TITLE
hasMany中获取某字段值。

### ISSUE THREAD

**Issue by BuXcXFly** [z-song/laravel-admin#2093]
### Description:
如图为$form内容，欲获取蓝圈中的type值来做判断，只显示type=1的数据。
其他issue中的获取request()方法都是null，无奈求助。
![image](https://user-images.githubusercontent.com/29780772/40710841-51ca42fe-642c-11e8-9210-da899b941cf3.png)

<pre>
                $form->hasMany('userdatas','身份证资料审核', function (Form\NestedForm $form) {
                    $form->text('type');
                    $form->image('image','图片资料');
                    $form->text('brief','描述');
                });
</pre>
↑就是上面这段代码怎么只让type=1的显示。

**Comment by qiuyuhome** [comment]
我也想知道.
