### ISSUE TITLE
急求，怎样实现下拉框加载不同视图的效果？

### ISSUE THREAD

**Issue by caicaizi251** [z-song/laravel-admin#2094]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.5.#

### Description:
如题怎样实现下拉框加载视图的效果？
比如我在下拉框中选择“群发”，然后加载出单选框的对应视图（ios、安卓）。
在下拉框中选择选择"用户"，然后加载出用户的下拉多选框。有没有大佬搞过，求助

**Comment by jxlwqq** [comment]
Admin::script();

**Comment by laraCai** [comment]
@jxlwqq 大佬实现过吗？能具体提供一下实现代码吗？
