### ISSUE TITLE
某些情况下会导致数据表导出的数据全部导了一行

### ISSUE THREAD

**Issue by MoonLiu666** [z-song/laravel-admin#2100]
- Laravel Version: 5.5.#
- PHP Version:7.0
- Laravel-admin: 1.5.#

### Description:
某些情况下会导致数据表导出的数据全部导了一行

没找到原因，把数据对应到其他模型就能正常，怀疑是字段名用的key、value导致?

![image](https://user-images.githubusercontent.com/22115885/40777197-bae98136-64ff-11e8-80c2-366ce8eb39a0.png)

![image](https://user-images.githubusercontent.com/22115885/40777246-eb29a6d2-64ff-11e8-83df-bae0df00486a.png)

```
            $grid->actions(function ($actions) {
                $actions->disableDelete();
//
            });//禁用删除

            $grid->id('ID')->sortable();
            $grid->key('Key');
            $grid->value('Value');
            $grid->describe('Describe');
```

**Comment by xiangxihenli** [comment]
可能你导出的数据中有英文逗号吧

**Comment by z-song** [comment]
建议自定义导出类来实现，内置的csv导出功能比较简陋
