### ISSUE TITLE
请问在$grid->filter()中的$filter->where()方法如何去掉md5加密或者如何将加密后的参数解密呢？

### ISSUE THREAD

**Issue by WuYeYouMing** [z-song/laravel-admin#2103]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
下面的address的参数值我需要获取并作相应的处理，但是参数获取到之后是md5加密的，请问怎么不加密，或者怎么获取解密后的address呢？
已经试了$filter->equal()方法，但是此处不适用，因为我这里需要两个表联合查询

### Steps To Reproduce:

               $filter->where(function ($query) {
                    $query->whereHas('address', function($query){
                        $query->where('address',$this->input);
                    });
                }, trans('lang.deposit_addr'));

**Comment by syw0602** [comment]
where方法第三个参数是query的key

**Comment by safakz** [comment]
不，它不是......哪里的方法只接受两个参数。 仍在寻找解决方案。

**Comment by z-song** [comment]
你想获取这个filter传递进来的参数，参考 @syw0602 的办法
