### ISSUE TITLE
Need Help

### ISSUE THREAD

**Issue by LanKing** [z-song/laravel-admin#2105]
How to prevent updating or inserting result, using saving form callback?

**Comment by llxx-lord-xxll** [comment]
You need to describe your problem more. The title is so much short which is difficult to understand.
However, i think you can return back by throwing a new Exception

```
$form->saving(function (Form $form) {

    // throws an exception
    throw new \Exception('Error friends. . .');

});
```

**Comment by LanKing** [comment]
Thank you!
In $form->saving() function I am making some validation and want to redirect to list of products if verification passed, or to previous page where I import list of new products in textarea. But I need to change new value of textarea in $form->saving() function.

return back()->withInput(); works, but if I am changing input on the fly:

                        Request::replace(
                            array('list' => array_merge($result->invalid_login, $result->invalid_count))
                        );

it redirects to list of products
