### ISSUE TITLE
How to use package spatie/laravel-medialibrary

### ISSUE THREAD

**Issue by shelestovas** [z-song/laravel-admin#2109]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:

How to use package spatie/laravel-medialibrary in image and multipleImage field&

**Comment by llxx-lord-xxll** [comment]
I am searching for the same thing

**Comment by mhenselin** [comment]
seems to be a good solution: https://github.com/nicklasos/laravel-admin-media-library

**Comment by jangidgirish** [comment]
> seems to be a good solution: https://github.com/nicklasos/laravel-admin-media-library

this is incomplete package

**Comment by CHUN-WEI-HSU** [comment]
I have tried this packge. The form edit mode works well, but the creating mode doesn't work, which will get the following message.
`getBasePath(): Return value must be of type string, null returned`
I think the media-library should upload file after model saved, this package seems not completely implement it.
