### ISSUE TITLE
How to handle messages from $form->saving() function?

### ISSUE THREAD

**Issue by LanKing** [z-song/laravel-admin#2111]
[ found ]

**Comment by caicaizi251** [comment]
use Illuminate\Support\MessageBag;

$error = new MessageBag(['title' => '保存失败', 'message' => "手机号输入重复"]);
return back()->with(compact('error'));

**Comment by LanKing** [comment]
Doesn't works for editable fields.

**Comment by LanKing** [comment]
Also, redirect doesn't works.

**Comment by taimaiduc** [comment]
use Illuminate\Support\MessageBag;
$form->saving(function ($form) {

                $error = new MessageBag([
                    'title'   => 'title...',
                    'message' => 'message....',
                ]);

                return back()->with(compact('error'));
            });

![image](https://user-images.githubusercontent.com/10907980/42020910-72c84960-7ae3-11e8-92fb-9f36cc1706fc.png)

**Comment by zzzeee** [comment]
How to keep formdata?

**Comment by taimaiduc** [comment]
I think you can add more `->with(request()->all()) ` Something like that.

**Comment by carlospinhod** [comment]
@taimaiduc hey,  tried these and couldn't archive filling the form with old data, what am i doing wrong?

return back()->with(compact('error'), request()->all());

return back()->with(compact('error'))->with(request()->all());

thank you already

**Comment by alexoleynik0** [comment]
> @taimaiduc hey, tried these and couldn't archive filling the form with old data, what am i doing wrong?
> 
> return back()->with(compact('error'), request()->all());
> 
> return back()->with(compact('error'))->with(request()->all());
> 
> thank you already

Personally I prefer to throw an Exception from there or anywhere I need to stop processing form saving. 

For example a ValidationException: 
```php
$form->saving(function (Form $form) {
    throw \Illuminate\Validation\ValidationException::withMessages(['name' => ['Is that really your name?']]);
});
```
This will work even for Grid's `editable` -- it will show content of "message" near to the field. 

You can also use [Content messages](https://laravel-admin.org/docs/en/content-message) to add a Toastr to the response or an Alert.
```php
$form->saving(function ($form) {
    admin_toastr('Message...', 'error', ['timeOut' => 5000]); // toastr "notification"
    admin_error('Title', 'Message...'); // bootstrap closable alert

    // throw new Exception('Is that really your name?'); // this will show Warning with the stack trace, not ideal..

    // but you can use this
    return back()->withInput(); // will ruin your Grid editable (=_=)
    
    // OR even this
    // $error = new \Illuminate\Support\MessageBag([
    //     'title'   => 'This will replace the one in `admin_error`',
    //     'message' => 'Message!!',
    // ]);
    // return back()->withInput()->with(compact('error'));  // will ruin your Grid editable (=_=)
});
```

Giving all pros and cons, my personal favorite is this:
```php
$form->saving(function ($form) {
    if (! request('_editable')) {
        admin_error('Title', 'Message...');
        admin_toastr('Message...', 'error', ['timeOut' => 5000]);
    }
    throw \Illuminate\Validation\ValidationException::withMessages(['dummy' => ['General error for the Grid\'s editable.']]);
});
```
