### ISSUE TITLE
edit 编辑状态下 select 联动 没有初始值

### ISSUE THREAD

**Issue by iiDestiny** [z-song/laravel-admin#2115]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.5-x

### Description:
select 联动的情况下。在编辑页面被联动的 select 表单控件并没有复制

![image](https://user-images.githubusercontent.com/17637481/40967869-c5dc4476-68e6-11e8-8ec1-4f5f78626c6f.png)

这是编辑状态下的

![image](https://user-images.githubusercontent.com/17637481/40967883-d1d8d55a-68e6-11e8-9594-39e1998d17b9.png)

**Comment by iiDestiny** [comment]
应该在编辑状态下面，下面两个被联动的 select 单选框也应该随着第一个被选而附有初始值

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/40968946-5ab71114-68e9-11e8-9887-d2bbe97efe41.png)

这里为什么要加一个隐藏的字段呢？ 我把 select disabled 之后，编辑的时候会提交这个隐藏字段，把我原有select字段的值给替换掉了。。

**Comment by iiDestiny** [comment]
这是  Select.php 组件的模版

**Comment by iiDestiny** [comment]
@z-song 楼主联动这个看看呢。。。

**Comment by iyueshang** [comment]
大佬 是自己修改的样式吗？很漂亮 ，可以分享一下吗

**Comment by iyueshang** [comment]
大佬 是自己修改的样式吗？很漂亮 ，可以分享一下吗

**Comment by iiDestiny** [comment]
![image](https://user-images.githubusercontent.com/17637481/41138229-698d796e-6b12-11e8-86a6-43d96d7c3b59.png)

联动初始值可以了。希望作者修复一下

![image](https://user-images.githubusercontent.com/17637481/41138243-7e23b08c-6b12-11e8-9e68-a8d5d5bceb91.png)

重构了一下后台样式

![image](https://user-images.githubusercontent.com/17637481/41138260-9b51ba14-6b12-11e8-9205-a4c7a7b37f49.png)

![image](https://user-images.githubusercontent.com/17637481/41138285-de52acc4-6b12-11e8-9e5d-9ad6ab0ae0a8.png)

**Comment by iyueshang** [comment]
很漂亮

**Comment by lvtu0316** [comment]
联动初始值怎么解决的，你这js这是写在哪里的啊？

**Comment by iiDestiny** [comment]
@lvtu0316 加载的时候去触发 联动的 change 事件

![image](https://user-images.githubusercontent.com/17637481/41404543-12d95f88-6ffa-11e8-85a7-8c902ee73111.png)

**Comment by lvtu0316** [comment]
@iiDestiny 我发现不用这样可以实现的，我是这么实现的：
`$form->select('operate_user_role_id','角色')->options($roles)->load('operate_user_id', '/api/role_users');

            $form->select('operate_user_id','用户')->options(function ($userid){
                $data = User::find($userid);
                return [$data['id']=>$data['name']];
            });`

**Comment by iiDestiny** [comment]
@lvtu0316 嗯嗯，这种方式也可以哈哈。不过得多些点代码。

**Comment by xiaomlove** [comment]
@lvtu0316 这样子确定能行吗？select默认在第一位添加一个value为空的option，假如这里operate_user_id是一个关联不是一个字段，判断的时候operate_user_id是关联目标的数组而不是一个关联id，选不中了。

**Comment by kwinH** [comment]
@z-song 希望大神尽快修复这个BUG

**Comment by lvtu0316** [comment]
@xiaomlove 没太懂你的意思啊？你举实际应用的例子。

**Comment by skys215** [comment]
@iiDestiny 可以发个PR吗？

**Comment by ebsinori** [comment]
@iiDestiny 这个方式默认选中的是第一个啊，并不是数据绑定的那个

**Comment by jxlwqq** [comment]
@iiDestiny 有业余时间的话，可以将样式抽出来写成扩展包吗？大家共同丰富生态，这是我做的一个扩展，供参考：https://github.com/laravel-admin-extensions/material-ui

**Comment by hitobias** [comment]
> @iiDestiny 我发现不用这样可以实现的，我是这么实现的：
> 
> ```
>  $form->select('operate_user_role_id','角色')->options($roles)->load('operate_user_id', '/api/role_users');
> 
>   $form->select('operate_user_id','用户')->options(function ($userid){
>          $data = User::find($userid);
>          return [$data['id']=>$data['name']];
>  });
> ```
這種方法不能選擇新的值

**Comment by strongWei** [comment]
到现在还不修复 ，我笑了
