### ISSUE TITLE
composer安装的时候提示错误代码1073740791

### ISSUE THREAD

**Issue by 77zealous** [z-song/laravel-admin#2117]
- Laravel Version: 5.5.28
- PHP Version:7.2
- Laravel-admin: 1.5.*

### Description:
安装的时候提示错误代码1073740791

### Steps To Reproduce:
`D:\www\zcdLaravel>composer require encore/laravel-admin "1.5.*"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 2 installs, 0 updates, 0 removals
  - Installing symfony/dom-crawler (v3.4.11): Loading from cache
  - Installing encore/laravel-admin (v1.5.13): Loading from cache
encore/laravel-admin suggests installing intervention/image (Required to handling and manipulation upload images (~2.3).)
encore/laravel-admin suggests installing spatie/eloquent-sortable (Required to built orderable gird.)
Writing lock file
Generating optimized autoload files
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover
Script @php artisan package:discover handling the post-autoload-dump event returned with error code -1073740791`

**Comment by z-song** [comment]
应该是composer的问题
