### ISSUE TITLE
form中标记一个字段是不提交的

### ISSUE THREAD

**Issue by xiaalngf** [z-song/laravel-admin#212]
在一个新增页面，我需要根据下拉框选择商店shop，再根据商店选择商品类型goodsType，然后添加商品信息，在提交的时候，程序会判断goods表中是否有shop这个字段，导致提交不成功。如何设置shop字段不提交？

**Comment by z-song** [comment]
```php
$form->ignore(['column1', 'column2', 'column3']);
```
如果方法不存在，请更新包
