### ISSUE TITLE
the login will go wrong if using more than one database

### ISSUE THREAD

**Issue by uhowep** [z-song/laravel-admin#2121]
- Laravel Version: 5.5.*
- PHP Version: >7.0
- Laravel-admin: 1.5.dev

### Description:
如果我使用了多个数据库的话，则当我登录后台的时候会报SQL语句的语法错误。
env环境文件默认连接的是sqlsrv，而laravel-admin的相关数据库文件链接的是mysql。
则在src/Auth/Database/Menu.php源文件中，allNodes方法（67行处）里的$orderColumn变量所得到的值不正确，该处由于使用DB类进行处理，所以构造函数中的setConnection无效，则使用的是env文件中默认配置的connection，会导致结果错误，像我这边得到的结果是sqlsrv的语法[order]而非`order`

### Steps To Reproduce:
1、.env文件中DB_CONNECTION=sqlsrv
2、config/admin.php文件中的connection=mysql
3、login operation
4、
![image](https://user-images.githubusercontent.com/24932775/41076644-30bb67c2-6a45-11e8-8b38-a661ddbc4d81.png)

**Comment by z-song** [comment]
已合并 谢谢
