### ISSUE TITLE
中文文档发现了一个错误. 示例代码缺少;

### ISSUE THREAD

**Issue by qiuyuhome** [z-song/laravel-admin#2122]
- Laravel Version: 5.5.*
- PHP Version: 7.2
- Laravel-admin: 1.5

### Description:
![image](https://user-images.githubusercontent.com/17526777/41085978-2732591a-6a6b-11e8-99be-6d169e3b37de.png)

### Steps To Reproduce:
对应的链接: http://laravel-admin.org/docs/#/zh/model-grid-column

**Comment by z-song** [comment]
已修复  谢谢
