### ISSUE TITLE
表单提交其他字段rules验证未通过，返回到表单时图片字段被清空

### ISSUE THREAD

**Issue by milkytsu** [z-song/laravel-admin#2126]
- Laravel Version: 5.6.24
- PHP Version: 7.2.5
- Laravel-admin: 1.5.14

### Description:
有上传图片空间的表单，选择了上传图片，提交时如果其他字段没有通过rules验证，返回表单后图片被清空，请问这个有办法解决吗？

**Comment by noogen** [comment]
Also, confirming this issue as I've came across it during testing.  Just so busy with other things that I can kick the can on this and tell my App users that it's not on my high priority list as they can workaround it... LOL... But that is probably a very bad excuse though...

**Comment by fplun** [comment]
> 我最后只能是在有图片上传的表单用 js 去验证字段了，有字段有问题就不提交了😅

好吧,这样也可以,现在我卡在embeds上传多图这了

**Comment by sayhei** [comment]
哎，我也遇到了，这个问题还没被解决~~

**Comment by lePig** [comment]
@sayhei 你现在用的laravel-admin是什么版本？我目前用的还是1.5.15也有问题
