### ISSUE TITLE
How can I change prefix from "admin" to "something else" ?

### ISSUE THREAD

**Issue by ryonguyen** [z-song/laravel-admin#2128]
How can I change prefix from "admin" to different word  ?
Current now all router always like ".../admin/..." . I want to change to ".../hvl/....".

How can I do it ? 
I go to config/admin.php change "route->prefix" but it not working

**Comment by Romerski** [comment]
Delete `bootstrap/cache/config.php` and try again.

**Comment by ryonguyen** [comment]
thanks sir
