### ISSUE TITLE
在grid页面添加二级联动过滤

### ISSUE THREAD

**Issue by xiaalngf** [z-song/laravel-admin#213]
在grid列表页面，我希望有联动过滤，先选择商店下拉框，再选择此商店对应的商品类型下拉，然后列表中显示出此商店此商品类型下的商品列表。  在form里面实现多级联动有一个load方法，但是在grid里面的filter里面没有这个方法 。

另外，感谢z-song提供laravel-admin这个框架！

**Comment by iianpan** [comment]
+1

**Comment by iianpan** [comment]
我的思路是通过filters判断是否有第一级的过滤，通过第一级过滤的结果，动态的获取第二级的过滤参数

**Comment by iianpan** [comment]
同时 请求
```
$filter->where(fucntion (){}, $label, $column);
```
在没有设定colnmn下用md5，不然老是变来变去。

**Comment by edwinhuish** [comment]
这种类型，在grid的上面加一个box，里面放一个form，通过提交form，刷新pjax请求。

另外 @z-song 我觉得数据应该挂在content上，而不是gird，form上。以便可以实现更复杂的页面。

**Comment by z-song** [comment]
已经实现了 在版本1.3.x-dev #310
