### ISSUE TITLE
如何直接覆盖form某个组件的js文件

### ISSUE THREAD

**Issue by archmage666** [z-song/laravel-admin#2136]
Laravel-admin: 1.5+

前提：需要修改组件内部分js源码，所以需要覆盖组件内的js资源，而不是在弄一个新的

以form组件内的select举例，该如何在所需页面覆盖掉vendor目录下的js资源，有什么办法？

protected static $js = [
        '/vendor/laravel-admin/AdminLTE/plugins/select2/select2.full.min.js',
    ];

**Comment by noogen** [comment]
That directly is actually not the same as the composer vendor directory.  It actually under "public/vendor/laravel-admin/..." so you can totally overwrite it with whatever you want since it is part of your public/source folder.
