### ISSUE TITLE
求助：select 选中后如何恢复成未选择的状态？

### ISSUE THREAD

**Issue by XueTools** [z-song/laravel-admin#2137]
- Laravel Version: 5.5.40
- PHP Version: 7.2.4
- Laravel-admin: 1.5.13

### Description:
![qq 20180614231434](https://user-images.githubusercontent.com/29800287/41421173-bbf96904-7028-11e8-8c69-d42d00cccf8f.png)

如图，选择了一个条件之后无法恢复到未选择的状态，不知有什么好办法解决这个问题？

**Comment by lePig** [comment]
请问如何解决的  我也遇到了这个问题

**Comment by XueTools** [comment]
我只改了搜索的，
重写了 input 的 reset
resources/views/admin/filter/modal.blade.php
<script type="text/javascript">
    $("#filter-modal").on('click', '.modal-footer .btn-warning', function(){
        $("#filter-modal input").val('');
        $("#filter-modal select").val(null).trigger('change');
        return false;
    });
</script>

**Comment by XueTools** [comment]
我只改了搜索的，
重写了 input 的 reset
`resources/views/admin/filter/modal.blade.php`
```
<script type="text/javascript">
    $("#filter-modal").on('click', '.modal-footer .btn-warning', function(){
        $("#filter-modal input").val('');
        $("#filter-modal select").val(null).trigger('change');
        return false;
    });
</script>
```

**Comment by lePig** [comment]
@XueTools 谢谢，刚我直接在`laravel_admin\vendor\encore\laravel-admin\resources\views\filter\modal.blade.php`加了这段js后发现确实可以满足我的需求了。

但是我像在追问一下，我如何不修改系统的。比如我复制一份系统的modal.blade.php到我的项目`my_project/resources/views/admin/filter/modal.blade.php`后 我改如何调用我自己定义的这个，而不是系统自带的那个。
再次表示感谢

**Comment by XueTools** [comment]
[http://laravel-admin.org/docs/#/zh/qa?id=%e9%87%8d%e5%86%99%e5%86%85%e7%bd%ae%e8%a7%86%e5%9b%be](http://laravel-admin.org/docs/#/zh/qa?id=%e9%87%8d%e5%86%99%e5%86%85%e7%bd%ae%e8%a7%86%e5%9b%be)
