### ISSUE TITLE
form中单选框

### ISSUE THREAD

**Issue by xiaalngf** [z-song/laravel-admin#214]
firefox、IE10 中文字与单选框垂直方向不对齐，

**Comment by xiaalngf** [comment]
![qq 20161219232142](https://cloud.githubusercontent.com/assets/8611771/21317872/f14133b8-c641-11e6-998e-ef2125baaf01.png)

**Comment by edwinhuish** [comment]
@xiaalngf 松比较忙，这些小问题最好是自己解决后issues发上来，为开源提供一份力。或者弄一个pull requests
