### ISSUE TITLE
public/vendor/laravel-admin/  *.css *.js showing 403 (Forbidden: Access is denied.)

### ISSUE THREAD

**Issue by 13127755587** [z-song/laravel-admin#2144]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: #.#.#

### Description:
![image](https://user-images.githubusercontent.com/25541463/41496480-a04996d8-7173-11e8-9f68-a8c103d016ce.png)

### Steps To Reproduce:
install and deploy this to azure, the css and js files in the laravel-admin folders can't be loaded,
https://jeryphp-laravel-admin.azurewebsites.net/vendor/laravel-admin/AdminLTE/bootstrap/css/bootstrap.min.css 403 (Forbidden: Access is denied.)

it works fine in local environment

**Comment by 13127755587** [comment]
duplicated

**Comment by felipeschulz** [comment]
change the files to another in CDN. works for me.

**Comment by xalatech** [comment]
This post helped me. https://stackoverflow.com/questions/35177360/getting-permission-error-with-rewrite-rules-within-azure-web-app
