### ISSUE TITLE
public/vendor/laralvel-admin *.css *.js files showing 403 (Forbidden: Access is denied.)

### ISSUE THREAD

**Issue by 13127755587** [z-song/laravel-admin#2145]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: #.#.#

### Description:
![image](https://user-images.githubusercontent.com/25541463/41496517-366aecac-7174-11e8-80c0-017442cec8a8.png)

### Steps To Reproduce:
it works ok in local environment.

but in azure, it will show the 403 (Forbidden: Access is denied.) error
GET https://jeryphp-laravel-admin.azurewebsites.net/vendor/laravel-admin/AdminLTE/bootstrap/css/bootstrap.min.css 403 (Forbidden: Access is denied.)

**Comment by noogen** [comment]
@13127755587 Looks like you resolved the issue because I was able to access the file and your login page.

**Comment by asterism612** [comment]
how to solve?

**Comment by 13127755587** [comment]
@asterism612 I raised a support case in Azure, and they told me to add a tag in the web.config file

**Comment by fguidotti-git** [comment]
Can you share the solution with us? Tks
