### ISSUE TITLE
How to customize sidebar menu logic?

### ISSUE THREAD

**Issue by hirossyi73** [z-song/laravel-admin#2147]
- Laravel Version: 5.5
- PHP Version: 7.X
- Laravel-admin: dev 1.5

### Description:
I want to customize sizebar menu logic.
(I want to use original authority.)

But I found that this framework calls Menu logic statically.

~~~php 
//  views/partials/sidebar.blade.php l.34
            @each('admin::partials.menu', Admin::menu(), 'item')
~~~

~~~php 
// src/Admin.php l.172
public function menu()
    {
        return (new Menu())->toTree();
    }
~~~ 

~~~php 
// src/Traits/ModelTree.php l.133
public function toTree()
    {
        return $this->buildNestedArray();
    }
~~~ 

So, t think I cannot customize Menu(ModelTree) logic.
How can I do??

**Comment by noogen** [comment]
In this case, you can try to overwrite the entire view by copying the file from "vendor/encore/laravel-admin/resources/views/partials/menu.blade.php" to "resources/views/vendor/admin/partials/menu.blade.php" and update the new view to render anything you want.
