### ISSUE TITLE
How to add dynamic from fields like adding items to invoice form?

### ISSUE THREAD

**Issue by amanullah-1** [z-song/laravel-admin#2148]
- Laravel Version: 5.6.0
- PHP Version:7.1.16
- Laravel-admin: 1.5

### Description:

I need to create a invoice system where user can create invoice.
The will be able to add items, quantity of items and there price.
Based on the input the system will calculate the total amount and generate the invoice.

I am stuck on it as I don't know how to implement dynamic from fields in laravel-admin.

Can anyone help me on this?

thanks and regards
Aman Ullah

**Comment by dynamohuang** [comment]
see it  http://laravel-admin.org/docs/#/en/model-form-fields?id=hasmany
