### ISSUE TITLE
hasMany 一对多关系中两表存在的相同字段，则会被主表对应字段的值覆盖

### ISSUE THREAD

**Issue by lois2014** [z-song/laravel-admin#2152]
- Laravel Version: 5.6.*
- PHP Version:7.1.3
- Laravel-admin: 1.5

出现报错信息时，会出现关联表相同字段的值被主表值覆盖的情况
如 Encore\Admin\Form\Field\Text
`      $this->initPlainInput();
        $this->prepend('<i class="fa fa-pencil"></i>')
            ->defaultAttribute('type', 'text')
            ->defaultAttribute('id', $this->id)
            ->defaultAttribute('name', $this->elementName ?: $this->formatName($this->column))
            ->defaultAttribute('value', old($this->column, $this->value()))
            ->defaultAttribute('class', 'form-control '.$this->getElementClassString())
            ->defaultAttribute('placeholder', $this->getPlaceholder());
`

问题就是：
`old($this->column, $this->value())
`

两张关联表$this->column 相同，得到的值会被主表的$this->column的值覆盖
如果能改成
`$name = $this->elementName ?: $this->formatName($this->column);  
old($name, $this->value())
`
就没问题了

**Comment by jesse7866** [comment]
在其中一个模型里做模型修改试试

**Comment by solgh** [comment]
模型修改？
