### ISSUE TITLE
保存的时候存的时间戳；1529510400这种，编辑的时候需要显示成日期格式y-m-d h:i:s的格式怎么办？

### ISSUE THREAD

**Issue by yijiepifu** [z-song/laravel-admin#2155]
- Laravel Version: 5.6
- PHP Version: 7.0
- Laravel-admin: 1.5

### Description:
保存的时候存的时间戳；1529510400这种，编辑的时候需要显示成日期格式y-m-d h:i:s的格式怎么办？

**Comment by Rming** [comment]
https://laravel.com/docs/5.6/eloquent-mutators

**Comment by yangbaojan** [comment]
如楼主说的保存是时间戳类型，筛选的如何做到呢

**Comment by z-song** [comment]
@ghost 用where过滤器
