### ISSUE TITLE
how to add style in widgets table

### ISSUE THREAD

**Issue by tezaditz** [z-song/laravel-admin#2157]
- Laravel Version: 5.5
- PHP Version: 7
- Laravel-admin: 1.5.x-dev

### Description:
i want to give style on my table.
### Steps To Reproduce:
 $headers = ['Keys', 'Values'];
            $rows = [
            'name'   => 'Joe',
            'age'    => 25,
            'gender' => 'Male',
            'birth'  => '1989-12-05',
            ];
            $styles = [
                'background-color' => 'red'
            ];

            $table = new Table($headers, $rows , $styles);

            $content->row((new Box('Table', $table))->style('info')->solid());

**Comment by chookg** [comment]
vendor/encore/laravel-admin/src/Widgets/Table.php
`$this->class('table '.implode(' ', $this->style));`

**Comment by spike014** [comment]
Is there any sample to set style for `Table` or `Tab` ？
