### ISSUE TITLE
when i use database is sqlserver, The admin can't select the right menu

### ISSUE THREAD

**Issue by Bouqute** [z-song/laravel-admin#2158]
- Laravel Version:5.5
- PHP Version:7.0.1
- Laravel-admin: laster

### Description: when i use database is **sqlserver**, The admin can't select the right menu data.
The ErrorException:
`SQL: select * from [admin_menu] order by [order] =0,[order]` 
`View: C:\phpStudy\WWW\blog2\vendor\encore\laravel-admin\resources\views\partials\sidebar.blade.php`

Someone has used sql server to establish the admin sys???

**Comment by pcfjojo** [comment]
@Bouqute any solution ?? I also have the same issue.
