### ISSUE TITLE
$filter->between查询mongodb报错。

### ISSUE THREAD

**Issue by teg1c** [z-song/laravel-admin#2162]
- Laravel Version: 5.5
- PHP Version:7
- Laravel-admin: 1.5.13

### Description:
$filter->between查询mongodb报错。之前看到有人提过，给出的解决办法是
写一个filter继承Encore\Admin\Grid\Filter\Between, 然后复写相应的方法。
但是1.5.13版本用这个办法不可行。

**Comment by BackStBoy** [comment]
解决了吗?

**Comment by z-song** [comment]
如果还有这个问题，请重新打开
