### ISSUE TITLE
使用laradock创建的docker环境无法进入admin后台

### ISSUE THREAD

**Issue by susucool527237808** [z-song/laravel-admin#2165]
- Laravel Version: #.#.#
- PHP Version: 7.12
- Laravel-admin: #.#.#

### Description:
大佬你好，我使用laravel-admin创建的程序在本地跑没问题，在centos和ubuntu上跑也没问题，但是在服务器上用laradock创建的docker环境就无法进入后台。laravel-admin的安装完全没问题，在docker环境下，DB_HOST和REDIS_HOST也分别设置成了mysql和redis，但是就是无法进入admin后台。我试过用非docker环境在服务器上搭建好laravel-admin，没有问题，然后就用这个项目切换为laradocker的环境，就又发现不能进入admin后台了。
不知道是什么原因~

**Comment by dynamohuang** [comment]
无法重现 我也是用的 laradock  运行无误

**Comment by susucool527237808** [comment]
@dynamohuang 好吧，我决定把服务器重装了，重新装laradock来测试，应该是我自己的问题。
