### ISSUE TITLE
Use IPAD/Safari as browser Insert Image/File failed

### ISSUE THREAD

**Issue by tommyctwu2004** [z-song/laravel-admin#2166]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Steps To Reproduce:

I insert jpg or pdf file use $form->image('image') or $form->file('file) for Windows Edge, Windows.Chrome is work fine, event Android Mobile, but use iPad, when click update, 
it loops until time out.

Any one have idea?

**Comment by varesc90** [comment]
Hmm. For me the issue seem to be with Android device.

**Comment by ysafarov** [comment]
I have same issue in Safari on MacOS. But in Chrome on MacOS is work fine.

- Laravel Version: 5.6.33
- PHP Version: 7.1.21
- Laravel Admin: 1.5.19

**Comment by ysafarov** [comment]
This issue in jquery.pjax.js. I've find solution.

https://stackoverflow.com/questions/49614091/safari-11-1-ajax-xhr-form-submission-fails-when-inputtype-file-is-empty
