### ISSUE TITLE
Model Form HasMany ReOrdering

### ISSUE THREAD

**Issue by llxx-lord-xxll** [z-song/laravel-admin#2177]
- Laravel Version: 5.5.40
- PHP Version:7.1.7
- Laravel-admin:1.5.x-dev

### Description:
Is there anyway to make ModelForm HasMany reorder-able in laravel-admin?

**Comment by dynamohuang** [comment]
You set in the Model.
   public function paintings()
    {
        return $this->hasMany(Painting::class, 'painter_id')->orderBy('top', 'DESC');
    }

**Comment by llxx-lord-xxll** [comment]
@dynamohuang this should work on the order part from database,
now is there any way to drag drop order in hasMany field?
