### ISSUE TITLE
当form里面使用了saving的时候，grid里switch操作无法生效

### ISSUE THREAD

**Issue by zhai8479** [z-song/laravel-admin#2180]
- Laravel Version: 5.5.38
- PHP Version:7.1.10
- Laravel-admin: 1.5.5

### Description:
           当我在form里不使用form->saving的时候，在列表点击切换，数据更新成功，
           但是使用了saving后，数据未能正常修改到数据库中。
### Steps To Reproduce:
gird中    

            $states = [
                'on' => ['value' => 1, 'text' => '显示', 'color' => 'primary'],
                'off' => ['value' => 0, 'text' => '隐藏', 'color' => 'default'],
            ];
            $grid->is_show('前端显示')->switch($states);

form中

          $states= [
                        'on' => ['value' => 1, 'text' => '显示', 'color' => 'success'],
                        'off' => ['value' => 0, 'text' => '隐藏', 'color' => 'danger'],
                    ];
           $form->switch('is_show', '前端是否显示')->states($states);

           $form->saving(function (Form $form) {
                $start_at = $form->input('start_at');
                if (empty($start_at)) {
                    $form->input('start_at', date('Y-m-d H:i:s'));
                };
           });

        调试结果显示，如果我在saving中使用了$form->input(),那么我在grid中的修改就无效，这种问题如何解决？我的saving中必须要做这种判断。

**Comment by dynamohuang** [comment]
我来重现试试看看

**Comment by 307118593** [comment]
题主解决了吗.我也遇到了
