### ISSUE TITLE
laravel-admin FROM表单同行展示问题

### ISSUE THREAD

**Issue by liufenyu** [z-song/laravel-admin#2182]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.5

### Description:
请问如何在form方法中，通过调用表单方法生成同行多个下拉框的效果 类似于下图效果，不知道是否存在这样的方法 文档和论坛中没有找到，请指教
![image](https://user-images.githubusercontent.com/38523907/42072503-68b53dec-7b93-11e8-8878-4ed97812d93f.png)

**Comment by dynamohuang** [comment]
` $form->row(function ($row) {
                $row->width(6)->text('title', '商品名')->rules('required', [
                    'required' => '请填写促销商品名',
                ]);
                $row->width(6)->text('title', '商品名')->rules('required', [
                    'required' => '请填写促销商品名',
                ]);
            });`

**Comment by dynamohuang** [comment]
结题 close 下一个~

**Comment by liufenyu** [comment]
感谢，正需要，你也在用这个框架么

**Comment by dynamohuang** [comment]
是的

**Comment by liufenyu** [comment]
你这个有个问题，就是会把我其他的覆盖，而且label会在表单上方，有没有办法保留其他表单，还是说都必须写成row的方式，或者有没有办法将label像我现在这样输出

**Comment by dynamohuang** [comment]
一行就都行  参考bootstrap 网格布局 一行12

**Comment by zhaoyingshuang** [comment]
@liufenyu 我也出现同样的问题，把其他的都覆盖了，您是怎么解决的呢？

**Comment by Kaniwong** [comment]
@zhaoyingshuang https://qiita.com/akimats/items/acd24cc5e32a0eac979e   可以使用这个方法，1.7的render需要修改，我有在这文章下面贴上要该的代码

**Comment by Kaniwong** [comment]
@zhaoyingshuang https://qiita.com/akimats/items/acd24cc5e32a0eac979e 参照这文章可以实现

**Comment by kaodouqifei** [comment]
$row->width(6)->text('check_outbox_barcode', __('Check outbox barcode'))->setLabelClass(['col-sm-2']);
自己加个class吧
