### ISSUE TITLE
http://laravel-admin.org/demo/config  Is this an egg or a mistake?

### ISSUE THREAD

**Issue by puzzle9** [z-song/laravel-admin#2185]
http://laravel-admin.org/demo/config

![2018-07-01 15-03-05](https://user-images.githubusercontent.com/13518196/42131937-07a3fce2-7d40-11e8-9289-9fd1232cdb13.png)

**Comment by dynamohuang** [comment]
Are you joking,I can`t see it?

**Comment by puzzle9** [comment]
This is a fun egg

**Comment by z-song** [comment]
fixed
