### ISSUE TITLE
表单验证required_unless 报错

### ISSUE THREAD

**Issue by RoseEnd** [z-song/laravel-admin#2186]
laravel5.6  

![3s w 6nf_ 2nhg zzn 53](https://user-images.githubusercontent.com/19225061/42146416-3ca7c24c-7dfa-11e8-8f02-c848633279ce.png)
![tv 4w m ub2mr _ 96c](https://user-images.githubusercontent.com/19225061/42146435-5809d2aa-7dfa-11e8-9d68-c15c668d0bd9.png)

**Comment by dynamohuang** [comment]
确定原因 
Encore\Admin\Form\Field\File  line 73   
 $this->removeRule('required');  方法对于required_unless 不兼容
我待会儿提个pr修复下吧

**Comment by dynamohuang** [comment]
ok 提了pr了，请求参考采纳  @z-song
