### ISSUE TITLE
multipleImage最后一张图片无法删除

### ISSUE THREAD

**Issue by Gethin2018** [z-song/laravel-admin#2189]
- Laravel Version: 5.6.*
- PHP Version:^7.1.3
- Laravel-admin: ^1.5

### Description:
数据库中商品图片字段类型为json
前端配置为:  $form->multipleImage('goods_desc','详情图')->removable();
### Steps To Reproduce:
当一直删除图片的时候,会出现最后一张图片无法删除的问题

**Comment by Gethin2018** [comment]
再次测试发现不是最后一张的问题,是有几率删除成功有几率删除失败,要多删几次
remark:图片是网络图片

**Comment by Gethin2018** [comment]
真的是,每张图片下面的删除按钮带有数组的key,当第一张图片被删除,那第二张的图片key不就是0了吗,还去删key=1能删掉吗?这个key怎么能写死?醉了

**Comment by blackbai** [comment]
这个组件，创建的时候能上传多张图片吗。 为什么我只能上传一张

**Comment by jxlwqq** [comment]
@Gethin2018 你这口气，大爷当久了？作者免费给你用，你还牛逼起来了？有问题提交pr呗。
