### ISSUE TITLE
主键为零开头的字符,而且正好后面都是数字,会被处理成整数

### ISSUE THREAD

**Issue by RobinHoo1973** [z-song/laravel-admin#2190]
- Laravel Version: 5.6
- PHP Version: 7.2.1
- Laravel-admin: 1.5

### Description:
字符型的主键如果是0开头而且是数字,会被处理成整数,grid和form控件都会这样,导致存储的数据不正确!

**Comment by z-song** [comment]
在模型里面加上属性
```php
protected $keyType = 'string';
```
