### ISSUE TITLE
Model does not exists !

### ISSUE THREAD

**Issue by imvicchen** [z-song/laravel-admin#2193]
- Laravel Version: 5.5.*
- PHP Version: 7.2.5
- Laravel-admin: 1.5

### Description:
我新make了一个model类Education
当我执行下面的命令后，提示我 Model does not exists !
php artisan admin:make EducationController --model=App\Models\Education

但是，默认的User Model类却是好用的~

因为是前端学习后端的，所以麻烦大家帮忙指点指点！~

**Comment by ancoka** [comment]
App\Models\Education 这个类在你项目中存在吗？不存在的话肯定找不到啊，存在的话检查是不是命名空间错误。

**Comment by imvicchen** [comment]
在Mac环境下成功了，在Windows下失败

**Comment by jmluang** [comment]
见文档 http://laravel-admin.org/docs/#/zh/quick-start?id=%E6%B7%BB%E5%8A%A0%E8%B7%AF%E7%94%B1%E5%99%A8
```
php artisan admin:make UserController --model=App\\User

// 在windows系统中
php artisan admin:make UserController --model=App\User
```

**Comment by m45adiwinata** [comment]
re-create your model with resource controller option, like this:
php artisan make:model YourModelName -cr
and then try to make your admin controller again.

**Comment by alexlhc906** [comment]
Hi, I was able to do it with: 

php artisan admin:make UsersController --model='App\Models\User'

Just add quotes in the model path.

**Comment by iwil** [comment]
// Windows
php artisan admin:make UserController --model=App\Models\User
