### ISSUE TITLE
Adding dynamic options(tags) select2

### ISSUE THREAD

**Issue by Martyn911** [z-song/laravel-admin#2195]
- Laravel Version: 5.6
- PHP Version: 7.1.3
- Laravel-admin: 1.5

### Description:
Not working adding dynamic options select2 https://select2.org/tagging for saving in json

### Steps To Reproduce:
$form->multipleSelect('payload')
                    ->config('tags', true)
                    ->config('multiple', true)
                    ->config('debug', true);

**Comment by taimaiduc** [comment]
Can you try to use  $form->tags('payload')
