### ISSUE TITLE
表格中直接编辑数据返回成功，但是库中数据没有改变

### ISSUE THREAD

**Issue by RoachBully** [z-song/laravel-admin#2201]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.5

### Description:

editable的字段在库中是存在的
![image](https://user-images.githubusercontent.com/21255523/42546579-95f38aa0-84f0-11e8-880e-9cd7def6ce3b.png)
![image](https://user-images.githubusercontent.com/21255523/42546585-9efbe930-84f0-11e8-8eaf-2dacd1462fe3.png)
![image](https://user-images.githubusercontent.com/21255523/42546603-af0358fe-84f0-11e8-9a69-ed617679cb5e.png)

**Comment by yiihub** [comment]
grid()中有了编辑的字段，同时 form()也要有该字段，才会真正更新成功。

**Comment by haohexin** [comment]
Laravel Version: 5.8.*
PHP Version:^7.1.3
Laravel-admin: ^1.6

也存在一样的问题

**Comment by ajiader** [comment]
现在是form()有此字段也不行了  以前都可以的

**Comment by z-song** [comment]
@ajiader @haohexin 提交了修复，更新到v1.6.14

**Comment by testsecer** [comment]
坑爹排查了半天原来是框架bug，文档上面还是v1.6.13以为还是最新的，才知道更新到1.6.15了，composer require encore/laravel-admin v1.6.15
