### ISSUE TITLE
过滤表单select希望增加一个"全部"选项

### ISSUE THREAD

**Issue by lePig** [z-song/laravel-admin#2202]
- Laravel Version: 5.5.40
- PHP Version: 7.2
- Laravel-admin: 1.15.14

### Description:
现在筛选表单中的select当选择了一个选项进行筛选一次后，这个每次都会参与搜索条件。想取消还得到列表页去点重置按钮。
所以我现在是这样弄的
```php
$filter->equal('status', '状态')
           ->select(array_prepend(['1' => '已激活', '2' => '未激活'] , '全部', ' '));
```
但是总感觉这样用着不舒服。所以希望的结果是
```php
$filter->equal('fd')->select(['1' => '已激活', '2' => '未激活'])->first('全部');
```
增加一个类似`first`函数的来配置。

最终想实现类似下面这样

![select](https://staticache.oss-cn-hangzhou.aliyuncs.com/o_1ci4n6r3mt4v164n193l19rm1lura.png)

**Comment by terranc** [comment]
同样遇到这个问题

**Comment by lePig** [comment]
@terranc 老铁，很强势。  这个应该得1.6.3了。到时候更新下。感谢

**Comment by terranc** [comment]
@lePig 今天才发现select还有一个config方法，而且发现config不支持远程数据源的，索性优化了一下
