### ISSUE TITLE
$form 下一对一关系不能正常使用?

### ISSUE THREAD

**Issue by panghaoran** [z-song/laravel-admin#2205]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5

### Description:
$form->text(chapterData.content);  输入的 chapterData 是一个一对一关系.不能取得 content 内容;
但在 $grid->column('chapterData.content') 可以取得 content 内容.

### Steps To Reproduce:
通过一对一关系读取 与 chapter 有关联的 chapterData 里的内容,进行编辑.显示 label 的地方就显示 chapterData content 而不是预期的 content .

**Comment by mountainguan** [comment]
同样发现类似问题...一对一情况下

**Comment by mountainguan** [comment]
我找到问题了，你要把关联关系的名字改为一个单词的...不要用驼峰式命名就可以

**Comment by panghaoran** [comment]
谢谢,是的不用驼峰式命名,可以解决 $form.

左边的 label不设置还是有点问题 会解析成 chapterdata content,不过可以用 自定义的label 盖住 :D

**Comment by mountainguan** [comment]
我看到作者在grid那边解决过类似问题，但是form这边好像一直没解决。
