### ISSUE TITLE
文件上传，配置好了之后，使用$form中move方法存在一些问题，求解

### ISSUE THREAD

**Issue by soulferry2018** [z-song/laravel-admin#2209]
##文件上传，配置好了之后，使用$form中move方法，
###move方法中路径具体是怎么要求的？？

##试了好多次，都保存在配置目录下，而不是保存在move目录下。

**Comment by panghaoran** [comment]
需要在 filesystems.php 中去定义 disks 里的相关选项的 root 目录,来确定是 storage 还是以 public 为根目录

**Comment by jiangyongx** [comment]
我的意思是laravel-admin中带有move方法修改存储路径：
$form->image('picture')->move('public/upload/image1/');
就想问文件不会移动到move路径中，只会移动到配置文件中的目录
