### ISSUE TITLE
过滤表单select从远程api获取数据无法显示

### ISSUE THREAD

**Issue by lePig** [z-song/laravel-admin#2219]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5.15

### Description:
远程api地址为另外的项目地址，比如`http://example.com/index.php`请求返回数据如下
![image](https://user-images.githubusercontent.com/5689279/42791399-01f22228-89a3-11e8-8331-8e9877ff0865.png)

参考了[文档](http://laravel-admin.org/docs/#/zh/model-grid-filters?id=%E8%A1%A8%E5%8D%95%E7%B1%BB%E5%9E%8B)中的select部分，代码编写如下
```php
$filter->equal('测试')->select('http://example.com/index.php');
```
但是最终得到的结果是 结果没渲染。而且我在chrome的network中也看到请求返回了正确的json数据。
![image](https://user-images.githubusercontent.com/5689279/42791469-56c0101c-89a3-11e8-8a04-2fcccb6753db.png)

**Comment by Harrypoters** [comment]
大兄弟，解决了？我按照文档去弄不行哦

**Comment by Harrypoters** [comment]
@lePig

**Comment by lePig** [comment]
@Harrypoters 兄弟 你看看是不是跨域了。 我当时是这个问题导致数据不对的。

然后还要比对下返回的json数据结构是不是和文档一致
