### ISSUE TITLE
Linkage select old value not persisting

### ISSUE THREAD

**Issue by pkkandel1** [z-song/laravel-admin#2221]
- Laravel Version: 5.5.40
- PHP Version: 7.0.30
- Laravel-admin: 1.5.*

### Description:
The linkage select breaks when the form encounters validation errors.

### Steps To Reproduce:
On live version of demo, on the user add form::
- jump to address tab
- select the linkage options
- submit without filling any other fields
- validation error occurs and the linkage field breaks.

The linked field doesn't show old value neither we get options from api.

@z-song, can we fix this ?

**Comment by smunir** [comment]
@pkkandel1 Did you come by any workaround. I need to fix this too. Another favor if possible, any suggestions for adding empty option in linked field. first option gets selected and looks pretty odd.
