### ISSUE TITLE
查询过滤器filter如何把字段展开？

### ISSUE THREAD

**Issue by maojindao55** [z-song/laravel-admin#2222]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
考虑到好多用户找不到查询功能，想把过滤器字段展开，如何配置？我记得之前版本默认是展开的。

**Comment by z-song** [comment]
过滤器已经重构了显示方式，可以更新到`1.5.x-dev`体验
效果参考 http://laravel-admin.org/demo/posts
