### ISSUE TITLE
筛选时，重新选择筛选条件，page不是从1开始的

### ISSUE THREAD

**Issue by lePig** [z-song/laravel-admin#2223]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5.15

### Description:
当我在订单列表页面执行一次搜索后，我选择了第3页，也就是`page=3`。然后我在点击“筛选”按钮，更换搜索条件的时候点击提交，这个时候依然展示的是新数据的第3页.
我期望每次更换搜索条件应该是从第一页开始。看了一些网站的搜索，大部分都是更换条件后从第一页开始

**Comment by Quekie** [comment]
好想法

**Comment by lePig** [comment]
@z-song 请教下 这个就是设计这样的吗？

**Comment by z-song** [comment]
现在的设计是搜索的时候不影响其它参数变化

**Comment by lePig** [comment]
@z-song 想请教那如果更换搜索条件的话，大概要如何自定义一下呢。可以说说大致的处理方式吗。 
刚用larave-admin不久，还有一些高级用法没整过

**Comment by lePig** [comment]
#2326

**Comment by lePig** [comment]
#2326
