### ISSUE TITLE
请教 editable 的功能扩展问题. 当从一个状态切换至另一个状态时, 拦截操作并显示提示, 能否给个思路 ? 

### ISSUE THREAD

**Issue by weir008** [z-song/laravel-admin#2236]
[https://dl2.pushbulletusercontent.com/8c5TjJj6Ru9nEoUDOsnvj7Dr5XF5Ahdo/editable.jpg](https://dl2.pushbulletusercontent.com/8c5TjJj6Ru9nEoUDOsnvj7Dr5XF5Ahdo/editable.jpg)
如图, 我希望实现:
如果 status 当前是 comfirmed 状态, 那么切换到其它状态时, 拦截操作并显示一个提示.

目前在模型观察器里面这么做, 虽然能达到拦截的目的, 但体验不是很好: 
```
public function updating(Booking $booking)
    {
        if ($booking->isDirty('status')) {
            switch ($booking->getOriginal('status')){
                case BookingStatusEnum::CANCELLED:
                    $booking->status = BookingStatusEnum::CANCELLED;
                    break;
                ...
            }
        }
    }
```

**Comment by z-song** [comment]
后端数据的拦截可以用模型观察器实现，如果需要前端显示一个提示，可以在当前的grid页面嵌入一段js来实现：
```php
            $script = <<<JS
$('.grid-editable-Name').on('save', function(e, params) {
    toastr.success('保存成功');
});
JS;
            Admin::script($script);
```
`grid-editable-Name`这个根据你的字段来，可以在页面源码里找到，editable组件的事件在https://vitalets.github.io/x-editable/docs.html里面找

**Comment by weir008** [comment]
@z-song 谢谢!

**Comment by weir008** [comment]
@z-song 有办法在 editable 里面获取到当前列的数据吗,  就像 display 那样 ?
