### ISSUE TITLE
form的内嵌无数据

### ISSUE THREAD

**Issue by z0921** [z-song/laravel-admin#2237]
- Laravel Version: 5.5.40
- PHP Version:7.2.6
- Laravel-admin: 1.5.15

### Description:
我按照文档中标准的方法使用form的内嵌试图插入json数据到MySQL,
http://laravel-admin.org/docs/#/zh/model-form-fields?id=%e5%86%85%e5%b5%8c
但是数据一直没进去,最后发现在执行插入的代码时完全没有插入我想要插入json字段的信息,
截图如下:
![image](https://user-images.githubusercontent.com/20654119/43199627-2a082a3e-9045-11e8-911a-42fa088a2104.png)
![image](https://user-images.githubusercontent.com/20654119/43199633-2ef2cf18-9045-11e8-9234-12f65bcd7e64.png)

**Comment by terranboy** [comment]
发现了同样的问题   $form->embeds 不能放在第一个  放在第一个就不插入数据  能尽快修复吗  谢谢

**Comment by ixhuman** [comment]
@terranboy 跟一样的情况，通过你说的多加了一个字段，插入就成功。
