### ISSUE TITLE
$form->multipleSelect 如何设置默认值

### ISSUE THREAD

**Issue by pengbo37877** [z-song/laravel-admin#2238]
如题所诉

**Comment by qiuyuhome** [comment]
我也遇到了这个问题, 请求给个思路.

**Comment by ajiader** [comment]
同问

**Comment by ajiader** [comment]
找到方法可以这样：
`
 $form->multipleSelect('goods_txt', '商品')->options(function () {
$goodsInput = ['1'=>‘a’, 2=>'b', 3=>'c']
 $resultStr = implode(',', array_keys($goodsInput));
                $script    = <<<JS
$('.goods_txt').select2().val([{$resultStr}]).trigger("change");
JS;
                Admin::script($script);
                return $goodsInput;
});`

**Comment by MrJoker1991** [comment]
$form->multipleSelect('roles', trans('admin.roles'))->options($roleModel::all()->pluck('name', 'id'))->default([2])->readonly();   
default 里面，传数组形式 可行
