### ISSUE TITLE
提交保存后我希望可以跳转到第三方网站

### ISSUE THREAD

**Issue by 119002602** [z-song/laravel-admin#2246]
提交保存后我希望可以跳转到第三方网站，目前是提交保存后老是跳转到列表页面。
可以修改跳转到第三方的url吗

**Comment by z-song** [comment]
```php
$form->saved(function (Form $form) {
    return redirect('第三方网站url');
});
```

**Comment by MooOne** [comment]
> ```
> $form->saved(function (Form $form) {
>     return redirect('第三方网站url');
> });
> ```

这里redirect可以带上提示信息吗,例如(message,刷新页面)

**Comment by MooOne** [comment]
![image](https://user-images.githubusercontent.com/28894376/58165554-978ef300-7cba-11e9-834c-7e49b76acbb6.png)
