### ISSUE TITLE
编辑的时候图片不展示了吗？

### ISSUE THREAD

**Issue by cheerego** [z-song/laravel-admin#2248]
- Laravel Version: 5.6
- PHP Version:7.1
- Laravel-admin: 1.5.x

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/13394349/43355246-dc601c4e-928b-11e8-8211-24e188dc5b2b.png)
![image](https://user-images.githubusercontent.com/13394349/43355253-ed10b42c-928b-11e8-81fb-e9e3d30a7fd6.png)

**Comment by cheerego** [comment]
编辑的时候，那个图片的显示框没有了 改掉了?
@z-song

**Comment by xiaomlove** [comment]
下载最新dev-master看，确实是编辑的时候图片不展示了。
@z-song

**Comment by xiaomlove** [comment]
经测试，跟配置文件 admin.php 中 upload 选择的disk有关，若disk有实现url()方法，是会显示图片的。比如disk选择public，有url属性，会显示图片。若选择local，默认没有url属性，不会显示图片。你给local设置url属性，一样会显示图片。

**Comment by lun1bz** [comment]
> 经测试，跟配置文件 admin.php 中 upload 选择的disk有关，若disk有实现url()方法，是会显示图片的。比如disk选择public，有url属性，会显示图片。若选择local，默认没有url属性，不会显示图片。你给local设置url属性，一样会显示图片。

不行的

**Comment by lun1bz** [comment]
> 经测试，跟配置文件 admin.php 中 upload 选择的disk有关，若disk有实现url()方法，是会显示图片的。比如disk选择public，有url属性，会显示图片。若选择local，默认没有url属性，不会显示图片。你给local设置url属性，一样会显示图片。

多图显示,单图就不显示
