### ISSUE TITLE
form中，code字段不显示

### ISSUE THREAD

**Issue by mycherish** [z-song/laravel-admin#2251]
- Laravel Version: 5.6
- PHP Version: 7.1.19
- Laravel-admin: 1.5

### Description:
form表单中，code字段不显示吗，为什么我写各种类型都看不到效果，我数据库没有id字段只有一个char类型的code
![image](https://user-images.githubusercontent.com/37433102/43379159-9565af3e-93fd-11e8-9bc7-52b834312624.png)
@z-song 请问该怎么解决

**Comment by z-song** [comment]
没有主键，还是code作为主键？
