### ISSUE TITLE
数据模型树排序无法保存  post 请求返回302的解决办法

### ISSUE THREAD

**Issue by EVA09** [z-song/laravel-admin#2252]
- Laravel Version: 5.5.40
- PHP Version: 7.2.2
- Laravel-admin:15.15

### Description:
数据模型树的表单中如果使用过file的表单验证。会导致数据模型树在排序页面无法保存。原因是file模块的getValidator()方法不会在表单中没有字段的时候清空自己的 rules规则

### Steps To Reproduce:
修改vendor\encore\laravel-admin\src\Form\Field\File.php 中的58行到93行中的getValidator()方法
增加类似
if (!array_has($input, $this->column)) {
       return false;
 }
这样的判定方法

**Comment by yang5664** [comment]
只要在你的rules加上 ‘sometimes’ 就可以了
````
‘sometimes|required|max....’
```
