### ISSUE TITLE
当select的的数组有键值为0时，会去除该项

### ISSUE THREAD

**Issue by jesse7866** [z-song/laravel-admin#2256]
- Laravel Version: 5.5.40
- PHP Version: 7.2.1
- Laravel-admin: 1.5.x-dev

### Description:
当select的options里的数组有键值为0时，
Select.php [此处](https://github.com/z-song/laravel-admin/blob/master/src/Form/Field/Select.php#L305) 的代码：

`$this->options = array_filter($this->options);`

array_filter会将数组里键值为0的去除，修改为如下即可：

`$this->options = array_filter($this->options, 'strlen');`

**Comment by lePig** [comment]
这个确实不错。
但是我还发现，对于select的option的key如果是`''`空字符串，则会直接帮我过滤掉。

**Comment by jesse7866** [comment]
@lePig 
空字符串本身就是不合理的

**Comment by lePig** [comment]
@jesse7866 那select下拉列表 如果说有一个选项叫做`全部` 你是怎么处理的

**Comment by jesse7866** [comment]
如果是form的话，可以用0或-1代表，然后在模型修改或者saving里处理。
filter里就不知道了。
