### ISSUE TITLE
自定义数据来源，后使用数过滤

### ISSUE THREAD

**Issue by phpLHT** [z-song/laravel-admin#2257]
自定义使用复杂的sql 语句获取数据后，如何添加数据过滤

**Comment by z-song** [comment]
覆盖模型的where方法，获取查询条件

**Comment by phpLHT** [comment]
谢谢,

**Comment by jesse7866** [comment]
明白了，再模型里重写where方法就可以了
`public function where()
{
    return $this;
}`
