### ISSUE TITLE
help on getting data

### ISSUE THREAD

**Issue by jkevinp** [z-song/laravel-admin#2260]
$grid -> column('test') -> display(function() use($start,$end,$mid){
    $id = $this -> id;
 });

is there any way to get the $this of display without executing display function?
I want to get the id of the current row or get the current row

**Comment by jkevinp** [comment]
that might work but thats not what I wanted to do.

I need something like
$data = $grid ->  afunctionThatReturnsCurrentRowData;

**Comment by Romerski** [comment]
I think the way you want is not possible.

```
$grid->actions(function($actions) {
    $actions->getKey(); //current row id
    $actions->row; //whole record
});
```
