### ISSUE TITLE
8月2日跟新后，所有列表后都会有一个眼睛的图标

### ISSUE THREAD

**Issue by cdhraesaemer** [z-song/laravel-admin#2261]
- Laravel Version: 5.5.28
- PHP Version:7.1.14
- Laravel-admin: 1.5.16

### Description:
今日laravel-admin更新至1.5.16版本
发现所有列表后面都出现了一个眼睛图标，在编辑图标和删除图标的前方

### Steps To Reproduce:
更新后出现了这种上述情况，有点蒙了，我只是在项目中看了一眼源码而已，并没有改动
![eye](https://user-images.githubusercontent.com/3795018/43562114-2d1ff04a-964d-11e8-85cb-b77db551c596.png)

**Comment by youruan** [comment]
估计是加入了查看详情的功能吧  应该是有地方可以关闭的

**Comment by youruan** [comment]
目测是和不显示删除按钮的屏蔽方式一样

**Comment by z-song** [comment]
@cdhraesaemer @youruan 是的，新增的feature，详细使用参考 http://laravel-admin.org/docs/#/zh/model-show

**Comment by jesse7866** [comment]
@z-song 
能不能做一个全局关闭列表“查看”、”“编辑”、“删除”的功能，要用的时候再启用
还有form里面的“撤销”、“保存”按钮

**Comment by jourdon** [comment]
@cdhraesaemer 文档中还没有更新  不显示详情的方法 disableView @z-song 文档加一下吧。

**Comment by leeib** [comment]
@z-song 我8月6号安装的 为什么没有这个model-show哦  composer update也没用  laravel版本为5.5.40

**Comment by leeib** [comment]
@z-song 我看了laravel-admin 版本为v1.5.15，composer update后 为什么laravel-admin不更新呢

**Comment by SmallRuralDog** [comment]
@leeib 1.5.x 换成 1.5.x-dev

**Comment by ajiader** [comment]
建议 弄个全局开关  然后手动在需要的页面去开启
