### ISSUE TITLE
filter表单redio和select渲染逻辑不同

### ISSUE THREAD

**Issue by lePig** [z-song/laravel-admin#2264]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5.15

### Description:
文档里radio的代码如下
```php
$filter->equal('released')->radio([
    ''   => 'All',
    0    => 'Unreleased',
    1    => 'Released',
]);
```

然后我参照这个写了一个select的
```php
$filter->equal('isnew', '用户')
        ->select([
                '' => '全部',
                '1' => '新用户',
                '2' => '老用户',
            ]
        );
```

而导致的结果是，直接把我的`全部`那个选项过滤掉了。

![1](https://user-images.githubusercontent.com/5689279/43569804-2a5bc550-966b-11e8-8b88-bdde9277d422.png)

**Comment by terranc** [comment]
up
