### ISSUE TITLE
查询过滤中的表单radio可以设置默认值吗

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#2265]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
查询过滤中的表单radio可以设置默认值吗
```
 $filter->equal('type', '类型')->radio([1 => '全服', 2 => '渠道']);
```
我后面加了default的值但是没有用

**Comment by guanhui07** [comment]
我们这也遇到这问题,有解决吗

**Comment by wuzhihui819** [comment]
我也遇到这个问题了
