### ISSUE TITLE
How Can I Find Menu Bar table ? How can I put them like the default 'admin menu'?

### ISSUE THREAD

**Issue by laziestcoder** [z-song/laravel-admin#2269]
- Laravel Version: 5.6.23
- PHP Version: 7.2.7
- Laravel-admin: 1.5.16

### Description:
How Can I Find Menu Bar table ? How can I put them like the default 'admin menu'?

I have created my own menu list but they are not generation automatically after using admin install. how can I do it ?
how can I manually change admin user name and password as if run admin install in my own project and then it change as my desired admin credentials ?

**Comment by moqiaoduo** [comment]
Hi,
You can make your own INSTALL COMMAND by using "make:command", and you should totally read this documentation:https://laravel.com/docs/5.5/artisan#generating-commands
Then, copy the relevant code from "/vendor/encore/laravel-admin/src/Console/InstallCommand.php" to your new command file, and change WHAT YOU WANT.  For example, "initDatabase" function is waht you want.
Next, find "\Encore\Admin\Auth\Database\AdminTablesSeeder" and copy to "/database/seeds". You know what to do if you understand the use of Artisan command "db:seed".
Finally, try to understand my poor English and archive your goal. :)
If you have any question, please feel free to reply.
