### ISSUE TITLE
一对一对一深层次的关系，如果构建form表单

### ISSUE THREAD

**Issue by gaoyl101** [z-song/laravel-admin#2270]
- Laravel Version: laravel5.6
- PHP Version:7.1.9
- Laravel-admin: 1.5

我有这样一个关系表
提现申请表 apply ， 用户表 member，用户资料表，profile
现在  我在提现申请form中，构建如下form
$form->text('member.profile.age');
通过我观察源码，我发现源码只能处理member.name  这样一层关系
如果出现一对一对一，或者更深的层次，就无法处理了。
请问作者是否有遇到这样的需求？请赐教

**Comment by TyrantG** [comment]
可以用中间一层模型来构建表单吧

**Comment by gaoyl101** [comment]
实际上一般都是会在member模型去处理profile。我只不过是在开发的时候，发现无法实现我提出的需求。我看了作者源码里面Form类中有一个getRelations()的方法:
![image](https://user-images.githubusercontent.com/12226835/43676706-eda58578-9828-11e8-86a9-6121fa2df40a.png)
这里获取到的relations只能获取第一个 "."的关系。

**Comment by kasougrey** [comment]
模型建个远程一对多的关系

**Comment by aoeng** [comment]
@kasougrey  申请提现表是 belongsTo Users的吧, User和profile 是HasMany的,这不能建立远程一对一关系吧?
我现在也遇到了,我是 两个belongsTo
