### ISSUE TITLE
switch组件在embeds中的bug

### ISSUE THREAD

**Issue by moqiaoduo** [z-song/laravel-admin#2272]
- Laravel Version: 5.6.28
- PHP Version: 7.2.2
- Laravel-admin: 1.5.17

### Description:
在非embeds中，使用switch组件可以正确的保存on/off所指value的值
但在embeds中，使用switch组件则会导致保存的值为on/off，而不能指向相应的value值

**Comment by Quekie** [comment]
.... 官方文档说支持 laravel 5.5  不知道有没有关系,
而且......embed 是什么???

**Comment by moqiaoduo** [comment]
@Quekie
embed是form组件里的内嵌。如果是因为laravel版本的问题，那么内外都应该用不了才对，但是只有在json字段出现这个问题就很怪了。
