### ISSUE TITLE
请问有没有别名方法将get参数中的paramA映射为模型中的paramB?

### ISSUE THREAD

**Issue by windmagic** [z-song/laravel-admin#2274]
- Laravel Version:5.5
- PHP Version: 7.2.7
- Laravel-admin:1.5.x-dev

### Description:
RT `` 目前我是靠魔改\Encore\Admin\Grid\Model addConditions 方法来折腾

**Comment by z-song** [comment]
试试给当前的request增加一个键值看看，比如将参数cid的值映射为id
```php
request()->merge(['id' => request('cid')]);
```
