### ISSUE TITLE
Pjax middleware 过滤的时候 script 标签问题

### ISSUE THREAD

**Issue by Quekie** [z-song/laravel-admin#2278]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin:  1.5.9

### Description:
当\Encore\Admin\Middleware\Pjax 尝试过滤的时候,用了 DOMDocument的 loadHTML 方法, 然而 loadHtml 会自动 把Script 标签内的第一个  '</' 当做结束符,导致返回错误的结果.
 \Encore\Admin\Middleware\Pjax  try to filter response with DOMDocument->loadHTML(), how ever ,
loadHtml HTML parser is required to take the first "</" as marking the end of the script element.

相关问题 :  
[stackoverflow](https://stackoverflow.com/questions/24575136/domdocument-removes-html-tags-in-javascript-string)
[stackoverflow](https://stackoverflow.com/questions/15925961/domdocument-remove-script-tags-from-html-source)

我的临时解决方法 (str_get_html 是simple html dom 的一个方法):
My temporary solution (str_get_html is from simple_html_dom): 

    protected function filterResponse(Response $response, $container)
    {
        $html = $response->getContent();
        $dom = str_get_html($html, $lowercase=true, $forceTagsClosed=true, $target_charset = DEFAULT_TARGET_CHARSET, $stripRN=false, $defaultBRText=DEFAULT_BR_TEXT, $defaultSpanText=DEFAULT_SPAN_TEXT);
        $tittle = $dom->find('title')[0];
        $content = $dom->find($container)[0];
        $response->setContent( $tittle.$content );
        return $this;
    }

希望对大家有帮助.
I hope it's helpful

**Comment by cyclegtx** [comment]
建议将 js中的html代码用php escape 加密，在js里用的时候再unescape，这样可以绕过Pjax middleware对"</"的过滤
