### ISSUE TITLE
请问二级联动如果载入数据

### ISSUE THREAD

**Issue by yangw1990** [z-song/laravel-admin#228]
调用load已有数据，却加入不了二级select中

**Comment by z-song** [comment]
返回的JSON数据要符合约定的格式

**Comment by yangw1990** [comment]
@z-song `，符合约定格式`[{"id":3,"text":"qwe"},{"id":4,"text":"wer"}]`

**Comment by yangw1990** [comment]
@z-song `return Admin::form(SpecialsItems::class, function (Form $form) use($special) {
            $form->select('special_id','专题:')->options(
                $special
            )->load('specials_id', '/admin/select/catalog');

            $form->select('specials_id','类目:')->options(function ($id) {

            });
 //           $form->text('specials_id','类目:')->default(0);
            $form->select('item_id','商品ID:')->options(function ($id) {

            })->ajax('/admin/select/item');

            $form->text('order','商品排序:')->default(0);
//            $form->saving(function(Form $form) {
//                unset($form);
//            });
        });`
请问这个有问题吗？“类目”select加载不了数据

**Comment by z-song** [comment]
你看下demo上面的ajax返回的数据结构，有分页信息的

**Comment by yangw1990** [comment]
@z-song `[{"id":36,"text":"\u5b89\u5e86"},{"id":37,"text":"\u868c\u57e0"},{"id":38,"text":"12"},{"id":39,"text":"\u6c60\u5dde"},{"id":40,"text":"\u6ec1\u5dde"},{"id":41,"text":"\u961c\u9633"},{"id":42,"text":"\u6dee\u5317"},{"id":43,"text":"\u6dee\u5357"},{"id":44,"text":"\u9ec4\u5c71"},{"id":45,"text":"\u516d\u5b89"},{"id":46,"text":"\u4e0d\u77e5\u9053"},{"id":47,"text":"\u5bbf\u5dde"},{"id":48,"text":"\u94dc"},{"id":49,"text":"fxcv"},{"id":50,"text":"\u5ba3\u57ce"},{"id":51,"text":"\u4eb3\u5dde"},{"id":3401,"text":"\u5408\u80a5"}]`
这是demo返回的数据，没有分页呀，我试着加了分页，这是加了分页返回的数据，任然加载不了
`{"total":2,"per_page":15,"current_page":1,"last_page":1,"next_page_url":null,"prev_page_url":null,"from":1,"to":2,"data":[{"id":3,"text":"qwe"},{"id":4,"text":"wer"}]}`

**Comment by z-song** [comment]
好像是有这个问题，我提交了commit修复了这个问题，请更新
