### ISSUE TITLE
How to show multiple json values in grid.

### ISSUE THREAD

**Issue by hirossyi73** [z-song/laravel-admin#2280]
- Laravel Version: 5.5
- PHP Version: 7.0
- Laravel-admin: 1.5.dev

### Description:
I want to show multiple json values in grid.
Ex. 
 
~~~ php
class Product extends Model
{
    protected $casts = ['value' => 'json'];
}

~~~

The value's val is as below.
{
    "value": [
        {
            "name": "ABC",
            "code": "abc"
        },
        {
            "name": "XYZ",
            "code": "xyz"
        }
    ]
}

And I want to show columns in grid.
So I wrote as below.

~~~ php
Admin::grid(Product::class, function (Grid $grid) {
$grid->column("value.name");
$grid->column("value.code");
});
~~~

But I have error.
Method Encore\Admin\Grid::__toString() must not throw an exception, caught ArgumentCountError: Too few arguments to function Illuminate\Database\Eloquent\Builder::value(), 0 passed in C:\work\Dropbox\3_Develop\TFS_Exc\ExManagement\vendor\laravel\framework\src\Illuminate\Database\Eloquent\Model.php on line 1470 and exactly 1 expected

And so I wrote as below, but result is that the name and code column is empty.

~~~ php
Admin::grid(Product::class, function (Grid $grid) {
$grid->column("value->name");
$grid->column("value->code");
});
~~~

How to write?
Thank you.

**Comment by z-song** [comment]
So do you want the name field to display ABC or XYZ?  the code field display abc or xyz?

**Comment by hirossyi73** [comment]
No, sorry.
I want to show like this.

![goal](https://user-images.githubusercontent.com/8457265/43718975-567dba80-99c7-11e8-9b83-d2e269bab78a.png)

If I write like this, it's error.
Admin::grid(Product::class, function (Grid $grid) {
    $grid->column("value.name", 'name');
    $grid->column("value.code", 'code');
});

If I write like this, it's all empty.
Admin::grid(Product::class, function (Grid $grid) {
    $grid->column("value->name", 'name');
    $grid->column("value->code", 'code');
});
![error2](https://user-images.githubusercontent.com/8457265/43719160-e38e3e04-99c7-11e8-98d2-816304bbd984.png)


If I write like this, it's all NULL.
Admin::grid(Product::class, function (Grid $grid) {
    $grid->column("value", 'name')->display(function($value){
        return array_get($value, 'name');
    });
    $grid->column("value", 'code')->display(function($value){
        return array_get($value, 'code');
    });
});

![error3](https://user-images.githubusercontent.com/8457265/43719268-38d134e8-99c8-11e8-9a65-0c22e8d26751.png)

**Comment by z-song** [comment]
Dump the variable `$value` inside display callback, to show how it looks like.

**Comment by hirossyi73** [comment]
@z-song 
I wrote this code.
$grid->column("value", 'name')->display(function($value){
    dump('value for name:'.json_encode($value));
    $val = array_get($value, 'name');
    dump('value name result:'.$val);
    return $val;
});
$grid->column("value", 'code')->display(function($value){
    dump('value for code:'.json_encode($value));
    $val = array_get($value, 'code');
    dump('value code result:'.$val);
    return $val;
});

And result is as below.
![image](https://user-images.githubusercontent.com/8457265/43815391-7551ae82-9b0a-11e8-964b-01967ceb0815.png)

**Comment by yzzhushu** [comment]
I got the same error

**Comment by ss-mokumoku** [comment]
I have one suggestion for this solution.
```
        $grid->column('column1_not_in_table')->display(function () {
            return json_decode($this->avlue)->map;
        });
        $grid->column('column2_not_in_table')->display(function () {
            return json_decode($this->avlue)->route;
        });

```
