### ISSUE TITLE
Ability to add sub controller

### ISSUE THREAD

**Issue by vlados** [z-song/laravel-admin#2281]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: latest

### Description:
Is there any way to add sub controller to a controller. For example if I edit a product to have after the form another grid of related product variations where I can edit/create or delete variation of the product?
In other words to have Grid in Form

**Comment by z-song** [comment]
For example, there are now two tables `posts` and `comments`, the models are `App\Models\Post` and `App\Models\Comment`, which are one-to-many relationships.
```php
class Post extends Model
{
    public function comments()
    {
        return $this->hasMany(Comment::class);
    }
}

class Comment extends Model
{
}
```

You want to display the comments grid under the form on the posts edit page. You can refer to the following code:
```php
class PostController extends Controller
{
    public function edit($id)
    {
        return Admin::content(function (Content $content) use ($id) {

            $content->header('header');
            $content->description('description');

            // add a form
            $content->row($this->form()->edit($id));

            // add a grid of table `comments`
            $content->row(Admin::grid(Comment::class, function (Grid $grid) use ($id) {

                $grid->setName('comments')
                    ->setTitle('Comments')
                    ->setRelation(Post::find($id)->comments())
                    ->resource('/demo/comments');

                $grid->id();
                $grid->content();
                $grid->created_at();
                $grid->updated_at();

            }));
        });
    }
}
```
> Note: In order to be able to use this data table function normally, you must use the `resource() `method to set the url access path of the comments resource.

**Comment by vlados** [comment]
Thanks! I will test it :) 
🥇🥇🥇🥇🥇🥇🥇🥇🥇 ❤️
