### ISSUE TITLE
如何把laravel-admin安装在子目录

### ISSUE THREAD

**Issue by clock1129** [z-song/laravel-admin#2282]
- Laravel Version: 5.5
- PHP Version: 7.1.8
- Laravel-admin: 1.5.14

### Description:
我有个laravel项目叫sub，存取的url是http://server.name/sub，
我希望把laravel-admin安装在sub项目里(与原来共同model)，
存取的url是http://server.name/sub/admin。
sub项目用到apache的rewrite base /sub，
而我的http://server.name/sub/admin/auth/login是可以正常进到login页面的，
但是需要提交的form的action地址却是http://server.name/admin/auth/login，少了/sub。
请问是否有设定支援这样的目录配置层级吗？
谢谢。

**Comment by jxlwqq** [comment]
在 config/admin.php 文件中，修改 prefix 的值。
```php
'route' => [

        'prefix' => 'sub/admin',

        'namespace' => 'App\\Admin\\Controllers',

        'middleware' => ['web', 'admin'],
    ]
```

**Comment by moxuanyuan** [comment]
> 在 config/admin.php 文件中，修改 prefix 的值。
> 
> ```
> 'route' => [
> 
>         'prefix' => 'sub/admin',
> 
>         'namespace' => 'App\\Admin\\Controllers',
> 
>         'middleware' => ['web', 'admin'],
>     ]
> ```

修改后还是不行

**Comment by moxuanyuan** [comment]
我的做法是修改/vendor/encore/laravel-admin/src/helpers.php中的``admin_base_path`` 函数中的返回值改为return admin_asset( $prefix.'/'.$path);
