### ISSUE TITLE
Relational sorting issue

### ISSUE THREAD

**Issue by vntrungld** [z-song/laravel-admin#2283]
I have 2 tables: `users` and `activities`. Both has the **name** field.

My `grid` function of `ActivityController` looks like this:
```php
protected function grid()
{
    return Admin::grid(Activity::class, function (Grid $grid) {

        $grid->id('ID')->sortable();
        $grid->column('user.username', 'Owner')->sortable();
        $grid->column('name')->sortable();

        $grid->created_at();
        $grid->updated_at();
    });
}
```
When I sort by `name` it works fine
![image](https://user-images.githubusercontent.com/19848743/43769962-32359c08-9a65-11e8-8f64-3db73f70d3ec.png)

But when I sort by `Owner` the name field replaced by name of the `Owner`
![image](https://user-images.githubusercontent.com/19848743/43770016-5bf53102-9a65-11e8-85c0-37099bdcdf0c.png)

Is there anyone has this problem?

**Comment by z-song** [comment]
pr merged, Thanks!
