### ISSUE TITLE
Problem saving value of the input inside blade using $form->html

### ISSUE THREAD

**Issue by jkevinp** [z-song/laravel-admin#2285]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: 1.5

### Description:
I am trying to add a custom html input but $form won't save the value of that field when saving/storing form data to db.

The blade  contains  <input type="name" type="text">

How can I make $form to recognize the value so that I can save the value to database.

### Steps To Reproduce:

$form -> html(view('blade'))

**Comment by z-song** [comment]
You can add your column as a hidden field, And assign the value of you html field to the hidden field in saving callback
