### ISSUE TITLE
Saving form with related model , get property with same name overwritten

### ISSUE THREAD

**Issue by beniaminorossini** [z-song/laravel-admin#2293]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
We have got a little problem.
Say that we have a model A with a property named "description" and a reletaed model B with a property "description" too.
If we use `$form->tab` and `$form->hasMany`, when we save form, property of model B get overwritten by property of model A (note, same name, but different model).

How we can deal with  that?

thx

**Comment by yang5664** [comment]
I have same issue too, for now try to add prefix character to field of detail table.

```
d_title,
d_name
```
something like that...
