### ISSUE TITLE
multiple filters not working in grid

### ISSUE THREAD

**Issue by mberende** [z-song/laravel-admin#23]
When adding 2 or more filters to a grid it only filters by the latest filter added, it doesn't consider the others.

**Comment by z-song** [comment]
Issue fixed.

Thanks a lot.

**Comment by mberende** [comment]
I fixed this too and a few more other bugs. I need to learn how to make a pull request to help you with the fixes.

**Comment by mberende** [comment]
I really think you made a great job with this package.

**Comment by z-song** [comment]
Fork this repository and clone it,  after you fix issues  push your commits to the repository which you forked, then click the `New pull request` button in the page to send a pull request. 

Really happy that you can help me fix these bugs.
