### ISSUE TITLE
关于save的问题

### ISSUE THREAD

**Issue by yangw1990** [z-song/laravel-admin#230]
在页面上5个字段，其中有一个字段在当前数据表里面是不存在的，但是需要在页面上展示出来，但submit时报错表不存在该字段，看到文档中提到，可以在有个saving的回调方式，但仍然不知道如何把这个键值对去掉，保存时不传送，或者是有其他解决方法，还望回答！

**Comment by z-song** [comment]
@yangw1990 在你开的另外一个issue里面已经回答了，用下面的方式忽略掉不需保存的数据
```php
$form->ignore(['column1', 'column2', 'column3']);
```

**Comment by yangw1990** [comment]
万分感谢！解决了
