### ISSUE TITLE
$grid->content('描述')->style('width:20%')，当content为空时，显示null，应该不显示才对的吧

### ISSUE THREAD

**Issue by Harrypoters** [z-song/laravel-admin#2300]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
![image](https://user-images.githubusercontent.com/24694539/43989009-a551ae36-9d74-11e8-94f7-d924de90e969.png)

**Comment by z-song** [comment]
这个问题在新的版本里面已经修复了，你这个版本用display方法修改一下显示吧
