### ISSUE TITLE
Field prepare方法会过滤掉所有为0或者‘0’的值.

### ISSUE THREAD

**Issue by RobinHoo1973** [z-song/laravel-admin#2301]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5.18

### Description:
在更新数据是的Field prepare方法会过滤掉所有为0或者‘0’的值.

DEBUG发现受这个影响的字段有MultipleSelect/Select/Tags
原因是array_filter
解决办法是
array_filter($value,'strlen');

**Comment by RobinHoo1973** [comment]
建议检查所有array_filter的使用

**Comment by z-song** [comment]
好的  我会看一下

**Comment by lePig** [comment]
#2256
