### ISSUE TITLE
模型表单可以自定义插入代码吗

### ISSUE THREAD

**Issue by xlkit456852** [z-song/laravel-admin#2302]
Laravel Version: 5.5.*
PHP Version: >=7.0.0
Laravel-admin: ^1.5

### Description:
比如现在有一个已经构建好的模型表单，但是希望在其中插入一个自定义的htm+js逻辑，并可以使用此模型表单进行提交。即模型表单+自定义代码并存？当前版本是否能够实现呢？

**Comment by z-song** [comment]
用$form->html($label, $html);可以在表单内部插入HTML代码，用Admin::script('alert(123);');可以在当前页面插入js代码，如果要在这个页面的form外添加html，参考http://laravel-admin.org/docs/#/zh/content-layout
