### ISSUE TITLE
Union 2 tables and paginator

### ISSUE THREAD

**Issue by jkevinp** [z-song/laravel-admin#2303]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: 1.5
### Description:
Sql error caused by paginator's aggregate when using union in 2 different tables.
Is there anyway to use the or extend paginator  when using union ?

### Steps To Reproduce:

$grid -> model() -> union()

**Comment by uacode** [comment]
@jkevinp Hello, union does not works on tables with different structure

@z-song How to make update works with union? Many thx!

**Comment by uacode** [comment]
Hardcode way:

Model use scope for admin grid
```
public function scopeGoods($query)
    {
        // Get active Projects....       
        $first = \DB::table('nis_market_u_1.goods')
            ->selectRaw('`id`, ......, \'1\' AS `dbName`');

        $query->union($first);
        ....
    }
```

Admin:
```
    protected function form()
    {
        $form = new Form(new Model());

        if (request()->has('dbName')) {
            $dbname = (int) request()->get('dbName');
            \Config::set('database.connections.userDB.database', 'nis_market_u_' . $dbname);

            $form->html('<input type="hidden" name="dbName" value="' . $dbname . '" />');
        }
```

In grid, pass dbName
```
$grid->actions(function ($actions) {
                    .....
                    $actions->append('<a href="' . $this->getResource() . '/' . $this->getKey() . '/edit?dbName=' . $r['dbName'] . '"><i class="fa fa-edit"></i></a>');
                });
```


Update works correctly, but return error:
> ModelNotFoundException In Builder.php line 366 :
> No query results for model [App\Models\Market\MarketGoods] 7

Inline update (editable() method) from the grid does not work.

@z-song Do you have any ideas, how to fix it?
