### ISSUE TITLE
使用基于数据模型的表格的一些问题

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#231]
基于数据模型的表格是基于单个表数据生成的，如果该表中有多个类型，我只想取其中一种类型的数据来生成表格，并可进行创建删除等操作。请问如果增加条件语句？

**Comment by z-song** [comment]
一张表的多个类型？能详细举例吗？

**Comment by windpursuer** [comment]
例如一个表是所有文件的上传数据记录，文件有多个类型，如jpg,txt等，如果我只想取出txt文件数据，那请问怎么使用基于单个表数据的表格呢？

**Comment by z-song** [comment]
比如有个字段是`type`来表示文件类型，可以用下面的方式：
```php
// 在grid定义里加一行
$grid->model()->where('type', 'text');
```
