### ISSUE TITLE
My Admin Dashboard is changing automatically

### ISSUE THREAD

**Issue by laziestcoder** [z-song/laravel-admin#2313]
my admin panel and menus are changing automatically after using this command admin:install.

I have added my own customized menu and admin dashboard. but when I upload it to a server and use again the command it changes to its origin interface. Then I had to edit all the thing again.

For your kind info, I have edited all these in vendor/encore/laravel-admin but composer does not allow to keep my changes. When I run composer install or composer update it changes into the origin.

How can I user composer to update my dependencies and both keep my edited files or data?

N:B: Sorry for my bad English. :(

**Comment by z-song** [comment]
Why do you run install command on production server?

**Comment by laziestcoder** [comment]
basically I run composer update and install. but it does not allow me to login in admin panel. so for admin credentials I had to use install command

**Comment by z-song** [comment]
Why not add admin credentials to database manually, but not by run install command?

**Comment by z-song** [comment]
No reply, close.
