### ISSUE TITLE
Clipboard is not defined当使用multiSelect时

### ISSUE THREAD

**Issue by mi-autumn** [z-song/laravel-admin#2314]
- Laravel Version: 5.5.40
- PHP Version:7.1.14
- Laravel-admin: 1.5.15

### Description:
当使用multiSelect时点击编辑页面会出现
返回无法点击F12查看发现Clipboard is not defined错误
![image](https://user-images.githubusercontent.com/38519056/44140516-d915893c-a0ac-11e8-9fc4-16fb05bca940.png)
![image](https://user-images.githubusercontent.com/38519056/44140989-62157eb2-a0ae-11e8-92ca-bf6d16686373.png)

刷新编辑页面又正常了
![image](https://user-images.githubusercontent.com/38519056/44141019-76ee1312-a0ae-11e8-9507-0c56a06cf184.png)

**Comment by z-song** [comment]
你的页面引入了Clipboard？

**Comment by z-song** [comment]
看下页面源代码 看看当前页面有没有调用

**Comment by mi-autumn** [comment]
` <script src="http://dg.xinj.net/vendor/clipboard/dist/clipboard.min.js"></script>`
有的...是js没直接暴露吗?

**Comment by z-song** [comment]
只有引入  没有调用？

**Comment by mi-autumn** [comment]
有个tool用了...那个tool是照着urlwapper改的

**Comment by mi-autumn** [comment]
没用require...
