### ISSUE TITLE
Idea about WidgetForm, Form 

### ISSUE THREAD

**Issue by hirossyi73** [z-song/laravel-admin#2315]
- Laravel Version: 5.5
- PHP Version: 7.0～
- Laravel-admin: 1.5.18

### Description:
I have two ideas about WidgetForm and Form .

1. Add WidgetForm disableReset and disableSubmit
"Encore\Admin\Form" has funcions disableSubmit and disableReset.
But "Encore\Admin\Widgets\Form" doesn't has them.
So I want to add these functions.

2. Add Form disableViewCheck and disableEditCheck
Recently "Encore\Admin\Form" add features showing checkboxes. When check them and submit, redirect to show or re-edit form.
It's very good feature, but I want to disable some forms.
So I want to add functions disableViewCheck and disableEditCheck to Form. 

@z-song 
Do you think these idea?
If you say OK, I will develop, and pull request.

**Comment by z-song** [comment]
Good idea! I will implement these features in the next version.

**Comment by hirossyi73** [comment]
@z-song 
Thanks! I created pull request.
#2327
