### ISSUE TITLE
hasMany字段名重名  验证提示问题

### ISSUE THREAD

**Issue by guoxinliang** [z-song/laravel-admin#2316]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.5

### Description:
hasMany字段名重名  验证提示问题

```
$form->text('name', '名称')->rules('required|max:32');
$form->hasMany('hasattrs','属性项',function(Form\NestedForm $form){
       $form->text('name','属性项')->rules('required');
});
```
属性项没有填 提交后 hasMany中重名字段 自动填充了
![image](https://user-images.githubusercontent.com/20662469/44144216-2e21c13c-a0b9-11e8-896e-cf21f38a7d92.png)

**Comment by Xuan-Goldenf** [comment]
這個原因應該是你的“名稱”的欄位名和“屬性項”的欄位名“一樣”造成的。
比如兩個欄位都用“title“。

**Comment by yfengze** [comment]
请问这个问题解决了吗？遇到了相同的情况了

**Comment by RobinHoo1973** [comment]
参见PR:https://github.com/z-song/laravel-admin/pull/2905

**Comment by RobinHoo1973** [comment]
好像是在出错返回时才显示出错,新加载时不会

**Comment by uhowep** [comment]
`hasMany`中的`name`字段会被外部的`name`字段的值给填充覆盖，目前处理方案可以尝试如下方式：
在`saving`回调中手动进行赋值，如：
```
$form->saving(function (Form $form) {
        foreach ($form->hasattrs as $htkey=>$attr) {
                $form->input("hasattrs.{$htkey}.name", $attr['name']);
        }
 });
```
