### ISSUE TITLE
switch组件默认不选中怎么设置

### ISSUE THREAD

**Issue by imlida** [z-song/laravel-admin#232]
switch组件默认不选中怎么设置？

**Comment by yang5664** [comment]
@imlida 默認應該就是off吧，是資料表欄位默認為true嗎?

**Comment by imlida** [comment]
就是可以设置默认值吗

**Comment by z-song** [comment]
```php
$form->switch('column')->default(2)
```

**Comment by yang5664** [comment]
測試是用value可以設定
```ruby
$form->switch('column')->value(0)
```

**Comment by edwinhuish** [comment]
按照我的理解，虽然暂时没有用过。。。

value是直接将值改了，如果直接提交form，提交的值也就是你设定的值。不可取。

default是当值为空才用到的。

**Comment by yang5664** [comment]
@edwinhuish  不過我測試是正常的哦，在laravel 5.3 && laravel-admin 1.3.x。
使用default不起作用。
測試案例：
新增
switch 為 1(on) -> 使用者改為 off -> 存入資料庫 -> 0(off)
修改
switch 為 0(off) -> 使用者改為 on -> 存入資料庫 -> 1(on)

**Comment by edwinhuish** [comment]
如果真如你所说，这个就是一个BUG. @z-song

**Comment by z-song** [comment]
#221 已经解决了这个问题
