### ISSUE TITLE
Javascript, JQuery and $form->select

### ISSUE THREAD

**Issue by krsmga** [z-song/laravel-admin#2322]
- Laravel Version: 5.6.33
- PHP Version: 7.1.19
- Laravel-admin: 1.5.*

### Description:
Javascript, JQuery and $form->select

### Steps To Reproduce:
I'm having problems in the type field "$form->select". I have two distinct situations that I can not resolve. Both use JQuery.

I need to get a "Click", "Blur", "Change" event anyway, but I need to find a way to get an event with JQuery when I change the value in a "$form->select" field. So I can update another field with this "$form->select" information. I've tried everything I've got but no event works.

Another major problem I encountered is that I can not set a value to a "$form->select" field with JQuery. An example when I exit a text field, when executing a Javascript method it update the "$form->select" field with a certain value. All I did was in vain. Please help me.

**Comment by luischavez** [comment]
may be this help
```php
protected function form() {
    $script = <<<SCRIPT
        $(document).on('select2:select', 'select.locale', function (event) {
            var selected = event.params.data;
            
            $('input.name').val(selected.text);
        });
SCRIPT;

    Admin::script($script);

    return Admin::form(Model::class, function (Form $form) {
        $form->text('name', trans('columns.name'));
        $form->select('locale', trans('columns.locale'))->options(locale_options());
    });
}
```

**Comment by krsmga** [comment]
tks
