### ISSUE TITLE
$grid->disableFilter()后筛选按钮依旧还在

### ISSUE THREAD

**Issue by qzd1989** [z-song/laravel-admin#2323]
- Laravel Version: 5.6
- PHP Version:7.2.8
- Laravel-admin: 1.5.18

### Description:
$grid->disableFilter()后筛选按钮依旧还在

### Steps To Reproduce:
在controller类中的grid方法里如下写:
return Admin::grid(Config::class, function (Grid $grid) {

            $grid->disableCreateButton();
            $grid->disableFilter();
            $grid->disableExport();
            $grid->disableRowSelector();
            $grid->intro('参数描述');
            $grid->value('参数值');
            $grid->updated_at('最后更新时间');

            $grid->actions(function ($actions) {
                $actions->disableDelete();
                $actions->disableView();
            });
        });
发现筛选按钮依旧还在
而且点击按钮也会增加active方法,只是应该显示的筛选表单元素是空的.
应该是要隐藏筛选按钮的吧

**Comment by qzd1989** [comment]
翻译文件中还缺失admin.search翻译 :)

**Comment by qzd1989** [comment]
按照你的写法,我在src/Grid/Tools.php增加了一个方法
`public function disableFilterButton()
    {
        $this->tools = $this->tools->reject(function ($tool) {
            return $tool instanceof FilterButton;
        });
    }`
然后在src/Grid.php的第530行的disableFilter方法增加如下代码
` $this->tools(function ($tools) {
            $tools->disableFilterButton();
        });` :)

**Comment by z-song** [comment]
谢谢指出 下个版本修复
