### ISSUE TITLE
点击浏览器的前进后退后筛选失效

### ISSUE THREAD

**Issue by zxl409774878** [z-song/laravel-admin#2325]
- Laravel Version: 5.6.33
- PHP Version:7.2
- Laravel-admin: 1.5.18

### Description:
点击浏览器的前进后退后，筛选按钮点击无效，弹不出筛选界面。
使用的是谷歌浏览器

### Steps To Reproduce:
点开一个有筛选的页面
任意点击其他页面
通过浏览器前进/后退按钮回到刚才的页面
点击筛选按钮

**Comment by nkjackzhang** [comment]
我是没有碰到这情况，筛选用的是bootstrap的modal窗，没有问题的
