### ISSUE TITLE
多图片上传,选择新的图片会自动替换之前选择的图片问题

### ISSUE THREAD

**Issue by kalepan** [z-song/laravel-admin#2328]
- Laravel Version: 5.6
- PHP Version:7.1
- Laravel-admin: 1.5.7

### Description:
多图片上传,每次选择新的图片,会自动替换上次所选择图片.可以帮忙解决我碰到这个问题吗?.谢谢!
我使用autoReplace false, 但没有作用

**Comment by mojiajuzi** [comment]
@kalepan 我也遇到了相同的问题

**Comment by mojiajuzi** [comment]
@kalepan  一次选择多张图片可以显示

**Comment by fan153693** [comment]
我也遇到了同样的问题，有解决方案吗
环境信息：
Laravel Version: 5.6
PHP Version:7.2
Laravel-admin: 1.6.0

**Comment by kalepan** [comment]
晚上整理一下,我把我的解决方案发出来. 方案不是太好

**Comment by shencm** [comment]
> @kalepan 一次选择多张图片可以显示

安卓手机端不支持多选
