### ISSUE TITLE
新版，筛选框不是弹出层的那款，发现有两个BUG

### ISSUE THREAD

**Issue by c903494855** [z-song/laravel-admin#2329]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Steps To Reproduce:
1、所有的查看按钮点击后会报错
/admin/auth/users
 BadMethodCallException In Controller.php line 68 :

Method [show] does not exist on [Encore\Admin\Controllers\UserController].

2、列表点击新增，之后点击右上角的view，返回目录页面，在点击其他任何链接全部404，目测是路由问题，因为点击view路由末尾多了一个斜线

**Comment by reatang** [comment]
+1 也遇到这个问题了，还没学习此组件的开发，求大大解决

**Comment by jxlwqq** [comment]
```
$key = $this->form->getResourceId();
```
create 页面无 $key 值的原因，已提交 PR。

**Comment by c903494855** [comment]
@jxlwqq  auth/users 这个，需要在源码修改了吧


 BadMethodCallException In Controller.php line 68 :
Method [show] does not exist on [Encore\Admin\Controllers\UserController].

**Comment by jxlwqq** [comment]
@c903494855 Encore\Admin\Controllers\UserController 的最新代码是有 show 方法的，但是还未正式发布，v1.5.18 可能有问题。

**Comment by c903494855** [comment]
@jxlwqq 我在源码添加了show方法就可以了，不过另一个问题，路由，匹配规则还是有问题的，只要末尾多了一个/，点击其他链接就会404。

**Comment by jxlwqq** [comment]
@c903494855 https://github.com/z-song/laravel-admin/pull/2346 问题已修复并合并了，作者还没正式发布，稍等。

**Comment by z-song** [comment]
已经发布了

**Comment by mRamadan0101** [comment]
still not working button view after update
