### ISSUE TITLE
Help Form Currenly

### ISSUE THREAD

**Issue by anhld-c1707g** [z-song/laravel-admin#2330]
- Laravel Version: 5.6
- PHP Version:  7.
- Laravel-admin: 1.4

@z-song 
 
I want to add more numbers '0' after dots . See image below:

![image](https://user-images.githubusercontent.com/31912286/44259913-198a5100-a23d-11e8-937d-0fe59021ec52.png)

**Comment by z-song** [comment]
Show me your code

**Comment by anhld-c1707g** [comment]
public function form() {
        return Admin::form(PairInfo::class, function (Form $form) {
			$w_100 = 'width: 100%;';
			$fa_pencil = '<i class="fa fa-pencil fa-fw" aria-hidden="true"></i>';
			$form->display('id', 'ID');
			$form->text('symbol')->rules('required');
			$form->currency('trading_fee')->attribute('style',$w_100)->symbol($fa_pencil);
			$form->hidden('createdAt');
			$form->saving(function (Form $form) {
				$form->createdAt = time();
			});

			if(!request()->is(['admin/pairinfo/create','admin/pairinfo'])) {
				$form->text('assetId1', 'Asset ld1');
				$form->text('assetId2', 'Asset ld2');
				$form->currency('threshold')->attribute('style', $w_100)->symbol($fa_pencil);
				$form->text('dec_price');
				$form->text('dec_amount');
				$status_trading = [
					1 => 'Active',
					-1 => 'Inactive',
				];				
				$form->select('status_trading', 'Status Trading')->options($status_trading);
				$form->hidden('updatedAt', 'Updated at');
				$form->saving(function (Form $form) {
					$form->updatedAt = time();
				});
			}
        });
    }

**Comment by anhld-c1707g** [comment]
![image](https://user-images.githubusercontent.com/31912286/44272165-456dfc80-a266-11e8-825f-95118d1ff2be.png)

**Comment by z-song** [comment]
The currency field is based on [Inputmask](https://github.com/RobinHerbots/Inputmask), you can find all the options in the docs

```php
$form->currency('fee)->options(['digits' => 4]);
```
