### ISSUE TITLE
$form->text('name')->rules('required',['required'=>'不能为空'])；

### ISSUE THREAD

**Issue by xgs736214763** [z-song/laravel-admin#2331]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

from组件的rules验证没有生效，最新版本的有问题，过年之前的版本是正常的

**Comment by z-song** [comment]
没有重现你的问题

**Comment by xgs736214763** [comment]
1964楼的也有这个情况反馈的

**Comment by xgs736214763** [comment]
![image](https://user-images.githubusercontent.com/22212275/44384632-6167eb80-a54f-11e8-828d-30eb5f09ff36.png)
