### ISSUE TITLE
How can I change prefix 

### ISSUE THREAD

**Issue by sujitkv92** [z-song/laravel-admin#2335]
- Laravel Version: 5.6.0
- PHP Version:7.1
- Laravel-admin: 1.5.15

I need to change prefix of my project.
current is http://www.abc.com/admin
need - http://www.abc.com/xyz/pqr/admin

and then all url should be created by the new one.

**Comment by z-song** [comment]
Change config `route.prefix` in `config/admin.php`

**Comment by OppPMatos** [comment]
I know @z-song just replied to what was asked but the solution seems incomplete.
If, as proposed in config/admin.php, we remove completely the prefix.
The site doesn't work properly.
