### ISSUE TITLE
laravel-admin生成的menu 点击时隐藏了当前li标签并产生了多余的下拉搜索框

### ISSUE THREAD

**Issue by usergao** [z-song/laravel-admin#2336]
- Laravel Version: 5.6
- PHP Version:   7.1.16
- Laravel-admin: 1.5

### Description:
生成的前端menu 里面的两个 `li` 点击时，会被添加上 `select2-hidden-accessible`  的class，并且产生了一个 class 为 `select2 select2-container select2-container--default` 的 下拉搜索栏，怎样都去不掉，也不好改源码

**Comment by pysoftware** [comment]
how did you solve it ?
