### ISSUE TITLE
编辑的时候点保存，页面没反应，手动刷新后数据没更新上

### ISSUE THREAD

**Issue by zhengmin4516** [z-song/laravel-admin#2338]
- Laravel Version: 5.5
- PHP Version: 7.1.16
- Laravel-admin: 1.5

### Description:
![image](https://user-images.githubusercontent.com/12004034/44375860-564d9500-a528-11e8-99c8-74a7720af20d.png)
点保存后
![image](https://user-images.githubusercontent.com/12004034/44375866-69606500-a528-11e8-959b-ccbd768a3170.png)
浏览器地址从http://127.0.0.1:3000/admin/swipers/1/edit 变成了 http://127.0.0.1:3000/admin/swipers/1

**Comment by yuyulu** [comment]
解决了吗

**Comment by zhengmin4516** [comment]
@yuyulu 刚刚回复你的时候突然想到了会不会是config/admin.php 里面开启https的问题，然后回头测试了一下，secure设置成false，就正常保存，设置成true，就出现上面的问题，还要再深入测试一下

**Comment by mineschan** [comment]
看看 #2085 #2319 
我有提供暫時的解決方法
是Safari的Bug
