### ISSUE TITLE
如何在非操作列添加自定义的操作按钮

### ISSUE THREAD

**Issue by xlkit456852** [z-song/laravel-admin#2339]
- Laravel Version: 5.5.*
- PHP Version:>=7.0.0
- Laravel-admin: ^1.5

### Description:
想在非操作列添加一个复杂功能的按钮，即希望可以其他列可以像在操作列那样插入一个自定义操作：
```
$actions->append(new BindWechat($actions->getKey()));
```
请问应该怎么写？

**Comment by z-song** [comment]
```php
$grid->column_name()->display(function () {
    return new BindWechat($this->id);
});
```

**Comment by xlkit456852** [comment]
我的代码：
```
$grid->column('绑定微信')->display(function () {
        return new BindWechat($this->id);
});
```
显示结果：
![image](https://user-images.githubusercontent.com/7323450/44377577-0a9ee980-a530-11e8-8606-8365a3c749f1.png)
这样直接把数据给显示出来了。。

**Comment by z-song** [comment]
有render方法么，调用它渲染输出
```php
return (new BindWechat($this->id))->render();
```

**Comment by xlkit456852** [comment]
有的，可以渲染出来了，谢谢！
