### ISSUE TITLE
Call to a member function push() on null

### ISSUE THREAD

**Issue by pierrocknroll** [z-song/laravel-admin#2341]
Hello,

Since the last version (1.5.18), I can't use 

```
$tools->append( something );
```

I think it's because your 
```
protected $appends;
```
in class Tools, is never initialized...

Thanks

**Comment by pierrocknroll** [comment]
This commit :
https://github.com/z-song/laravel-admin/pull/2305/commits/526a395d5d7cd425c05e7090fb4972ba8cfd59c4

Is not in the file.
Here's the content of my up to date file :
```php
    /**
     * Create a new Tools instance.
     *
     * @param Builder $builder
     */
    public function __construct(Builder $builder)
    {
        $this->form = $builder;
    }

    /**
     * Append a tools.
     *
     * @param mixed $tool
     *
     * @return $this
     */
    public function append($tool)
    {
        $this->appends->push($tool);

        return $this;
    }
```

**Comment by z-song** [comment]
You can update to `1.5.x-dev` to resolve this currently.

**Comment by z-song** [comment]
You can upgrade to `v1.5.19` now
