### ISSUE TITLE
Session Issue When Uploaded to Production

### ISSUE THREAD

**Issue by jandayanan** [z-song/laravel-admin#2343]
- Laravel Version: 5.5.42
- PHP Version: 7.2.8
- Laravel-admin: 1.5.18

### Description:

Production upload has problematic session when logging in, but local deployment works just fine. Tested this in multiple production deployments and subdomains. Any pointers as to what might be the issue?

![image](https://user-images.githubusercontent.com/3338545/44397599-81110b00-a573-11e8-8423-be767503ac82.png)

.env file:
```
APP_NAME="Test App"
APP_ENV=local
APP_KEY=base64:xNQ6WupKGr1k+sadasdasdasd=
APP_DEBUG=true
APP_LOG_LEVEL=error
APP_URL=domain.com
COOKIE_DOMAIN=domain.com

# THIRD PARTY
GOOGLE_API_KEY=GOOGLE_API_KEY

DB_CONNECTION=mysql
DB_PORT=3306
DB_HOST=127.0.0.1
DB_DATABASE=app.db
DB_USERNAME=root
DB_PASSWORD=root

BROADCAST_DRIVER=log
CACHE_DRIVER=file
QUEUE_DRIVER=sync

REDIS_HOST=127.0.0.1
REDIS_PASSWORD=null
REDIS_PORT=6379

MAIL_DRIVER=smtp
MAIL_HOST=smtp.gmail.com
MAIL_PORT=587
MAIL_USERNAME=email@gmail.com
MAIL_PASSWORD=testpassword
MAIL_ENCRYPTION=tls
MAIL_FROM_ADDRESS="email@gmail.com"
MAIL_FROM_NAME="Application Administrator"

PUSHER_APP_ID="asdasdsad"
PUSHER_APP_KEY="asdasdasd"
PUSHER_APP_SECRET="asdasdasdasd"
PUSHER_APP_CLUSTER=ap1

SESSION_DOMAIN=null
SESSION_DRIVER=file
SESSION_LIFETIME=120
SESSION_COOKIE=sdfghsdfgewrysdfgjhserfytsertsefgsdfgsert

API_PREFIX=api
API_SUBTYPE=app
API_VERSION=v1

SIGN_UP_RELEASE_TOKEN=false
PASSWORD_RESET_RELEASE_TOKEN=false

JWT_SECRET=my-dummy-token
```

### Steps To Reproduce:
Can't reproduce this on your local.

**Comment by z-song** [comment]
Try to set the write permission of the session directory under `storage/framework`

**Comment by jandayanan** [comment]
Already did, and I can also see that the sessions are being written to the folder.

![image](https://user-images.githubusercontent.com/3338545/44399268-896c4480-a579-11e8-8b48-1b9ba7376085.png)

**Comment by z-song** [comment]
Maybe can find solution here https://github.com/laravel/framework/issues/23212

**Comment by jandayanan** [comment]
Already checked those possible fixes, nothing worked to be honest. I am not sure exactly what's the problem because my PHP configuration on my local machine is already almost the same as prod.

**Comment by jandayanan** [comment]
Update:

I noticed that this only happens when this is exists:
![image](https://user-images.githubusercontent.com/3338545/44418342-b08f3a00-a5aa-11e8-89dd-ad8a28b810e8.png)

On my local machine, it doesn't show this redirect message once I go to web.app/admin

**Comment by jandayanan** [comment]
I am not sure though, maybe it's just redirecting faster in my local machine.

**Comment by dhachayawat** [comment]
After chmod 

> storage/framework/sessions
can fixed.
