### ISSUE TITLE
模型表单添加自定义工具报错

### ISSUE THREAD

**Issue by zhangpipi** [z-song/laravel-admin#2348]
- Laravel Version: 5.5.*
- PHP Version:7.2
- Laravel-admin: 1.5.18

### Description:
在模型表单 使用
`$tools->add(new DownloadTemplateButton());`
或者
`$tools->append(new DownloadTemplateButton());`

都报错 "Call to a member function push() on null"

同样的这个button在模型表格里面添加 没有问题。

**Comment by zhangpipi** [comment]
![image](https://user-images.githubusercontent.com/41517203/44453842-a31a9400-a62c-11e8-8b6f-06ae7afb7caa.png)

**Comment by zhangpipi** [comment]
我把文档里面的
`$tools->add('<a class="btn btn-sm btn-danger"><i class="fa fa-trash"></i>&nbsp;&nbsp;delete</a>');`

放上去 也是一样的报错

**Comment by z-song** [comment]
可以先更新到`1.5.x-dev`

**Comment by z-song** [comment]
更新到`v1.5.19`应该就好了
