### ISSUE TITLE
url链接中用主键ID来当关键字 有个BUG . .

### ISSUE THREAD

**Issue by anyexinyang** [z-song/laravel-admin#2349]
- Laravel Version: 5.5.*
- PHP Version:  7.1
- Laravel-admin: 1.5.*

### Description:
       url链接中用主键ID来当关键字 有个BUG . .

### Steps To Reproduce:
      当我修改链接中ID的数值,我就可以进入这条数据的修改页面来随便的修改内容,并且当我猜到别的路由名时  我可以用同样的方法来修改内容,这样只要能进到修改页面就可以随意的修改整个数据库的内容,并且记录下来.
     希望可把ID加密一下再放出来,同时控制器中的id也加密一下比较好

**Comment by z-song** [comment]
做好权限控制
