### ISSUE TITLE
每一个行下面如何再增加一行隐藏行

### ISSUE THREAD

**Issue by edwinhuish** [z-song/laravel-admin#235]
请问如何达到下面这种效果？

原理就是在每一个```<tr>```下面再增加一行隐藏```<tr>```，然后通过点击触发显示/隐藏。可以用于行的详情，或者子表的显示。
![1](https://cloud.githubusercontent.com/assets/5207925/21474558/35009e30-cb5c-11e6-94f7-7cffebecb44d.gif)
![1](https://cloud.githubusercontent.com/assets/5207925/21474611/f257bb8a-cb5c-11e6-9207-ee79e881a5f9.gif)

**Comment by z-song** [comment]
我有看到过这个效果，接下来的版本实现吧

**Comment by z-song** [comment]
通过列扩展的方式可以实现了 http://120.26.143.106/admin/demo/users
