### ISSUE TITLE
登录认证后有回调吗

### ISSUE THREAD

**Issue by zhangpipi** [z-song/laravel-admin#2351]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

大大，请问一下，我想在登录认证后自动操作一下session。除非我重写整个登录认证的逻辑，有什么好的简单的办法吗？

**Comment by z-song** [comment]
登录认证后, laravel会触发一个`Illuminate\Auth\Events\Login`事件,  你可以监听这个事件来处理你的逻辑

**Comment by zhangpipi** [comment]
OK 非常感谢
