### ISSUE TITLE
Help with $form-saving (relation)

### ISSUE THREAD

**Issue by krsmga** [z-song/laravel-admin#2354]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

I have a HasOne relationship in a form, but during the save I need to modify an address information field address['CEP'] which is a measure of the parent table. But I'm getting an error

> Indirect modification of overloaded property Encore\Admin\Form::$address has no effect

can anyone help me how to change this field before saving.

### Steps To Reproduce:

            $form->row(function ($row) use ($form) {
                $row->width(2)->text('address.cep', 'CEP *')
                              ->attribute(['data-inputmask' => '"mask": "99 999-999"'])
                              ->placeholder('00 000-000');
            });

            $form->saving(function (Form $form) 
            {
                $form->address['cep'] = preg_replace( '#[^0-9]#', '', $form->address['cep']);     
            });

**Comment by krsmga** [comment]
I was able to solve

                $arrAddress = $form->address;
                $arrAddress['cep'] = preg_replace( '#[^0-9]#', '', $arrAddress['cep']);
                $form->address = $arrAddress;

**Comment by z-song** [comment]
Use `$form->input();`
```php
$form->saving(function ($form) {
    $form->input('address.cep', preg_replace( '#[^0-9]#', '', $form->address['cep']));
});
```
