### ISSUE TITLE
How to change the data-url in editable

### ISSUE THREAD

**Issue by dvijnru** [z-song/laravel-admin#2355]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: 1.5

### Description:
How to change the data-url in $ grid-> title () -> editable ();

The problem is that I'm trying to edit the material on the 'sklad' page, which is stored on the 'production' page. On the page 'sklad' I get this attribute 'data-url = "/ sklad / 174/213"' (I'm at '/ sklad / 174') and I need to make this attribute 'data-url = "/ production / 213 "'

**Comment by z-song** [comment]
Not support， But you can do this by extending the column.
```php
class CustomEditable extend \Encore\Admin\Grid\Displayers\Editable
{
    public function display()
    {
        // change data-url
    }
}
```
Register in `app/Admin/bootstrap.php`
```php
Encore\Admin\Grid\Column::extend('customEditable', CustomEditable::class);
```
Then use it in grid
```php
$grid->title ()->customEditable();
```

**Comment by dvijnru** [comment]
Thank you.
And is it possible to make the editing page 'production' at '/ sklad / 174/213'?
I did so
`Route - 
$router->get('sklad/{ids}/{id}', 'SkladController@sklad_view_post');`
`SkladController - `
```
public function sklad_view_post($ids, $id)
    {
        return Admin::content(function (Content $content) use ($id) {

            $content->header('Продукция');
            $content->description('description');
            $content->body($this->form2()->edit($id));
        });
    }
```
```
protected function form2()
{
    return Admin::form(Post::class, function (Form $form){
        $ grid-> title () -> editable ();
    });
}
```

But when editing it produces - No query results for model [App \ Models \ Sklad] 218
