### ISSUE TITLE
批量删除错误

### ISSUE THREAD

**Issue by panghaoran** [z-song/laravel-admin#2356]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.5.18

### Description:
错误
```
Cannot use object of type Encore\Admin\Grid\Tools\BatchDelete as array (View: /srv/www/novelspread.com/laravel/laravel55/vendor/encore/laravel-admin/resources/views/grid/batch-actions.blade.php) (View: /srv/www/novelspread.com/laravel/laravel55/vendor/encore/laravel-admin/resources/views/grid/batch-actions.blade.php)
```

### Steps To Reproduce:
据同事说是更新(没有使用 composer update)以后线上报了一个批量删除错误 , 我不知道怎么触发的.本地没触发这个错误.,目前使用屏蔽批量删除的方法缓解.

config 扩展插件不能使用.

我更新到 1.5.19 可以解决这个问题吗,看不到 1.5.18 修复 bug 的更新日志

**Comment by panghaoran** [comment]
升级了版本有效

**Comment by wangwenfan** [comment]
今天升级到最新的1.5.19出现这个批量删除报错的问题了。
![tim 20181011113849](https://user-images.githubusercontent.com/17559363/46779428-5a3cad00-cd4a-11e8-83fe-0dcca8ebdb99.png)
![tim 20181011113747](https://user-images.githubusercontent.com/17559363/46779430-5b6dda00-cd4a-11e8-94e9-3d5752f91b62.png)
