### ISSUE TITLE
select组件在使用api获取选项后无法自动选中已有的选项

### ISSUE THREAD

**Issue by zhangpipi** [z-song/laravel-admin#2357]
- Laravel Version: 5.5.42
- PHP Version: 7.2.5
- Laravel-admin: 1.5.19

### Description:
`$form->select('category_id', '所属大类')->options('/api/categories')->rules('required');`

![image](https://user-images.githubusercontent.com/41517203/44511294-9f007c00-a6e9-11e8-9bc1-0b0299b3d1d6.png)

![image](https://user-images.githubusercontent.com/41517203/44511330-b7709680-a6e9-11e8-8237-7d16f20795c9.png)

### Steps To Reproduce:
在模型表单
如果是用
`options([1 => 'foo', 2 => 'bar', 'val' => 'Option name']);`
这种方式写死的 options，select就有默认值。如果是用api获取到的选项，就没有默认值。本身这个字段是有值的，不手动选择一下的话提交的时候会用null覆盖。所以我不得不加上了一个 `->rules('required');`

**Comment by zhangpipi** [comment]
![image](https://user-images.githubusercontent.com/41517203/44511662-d6235d00-a6ea-11e8-95ae-8c405800b0cf.png)

**Comment by z-song** [comment]
这里貌似是个bug，待我修复

**Comment by z-song** [comment]
提交了修复，先更新到`1.5.x-dev`吧

**Comment by guoxinliang** [comment]
@z-song  3级联动使用api 按你的方法修复后 第一级会选中 剩下两级默认到第一个选项了 如何修复？
![image](https://user-images.githubusercontent.com/20662469/44717820-b035f800-aaf0-11e8-85b8-cd0976887c39.png)

**Comment by z-song** [comment]
参考 https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Resources/UserResource.php#L231-L237

**Comment by terranc** [comment]
@z-song 顺带把filter里面的select也解决一下吧，有同样的问题

**Comment by jiangdan09** [comment]
v1.7.2 在编辑里二级子菜单不能根据现有值被选中，还是会被主菜单联动更换成其二级数据。我是不是要改成1.5版本？

**Comment by unizhu** [comment]
> @z-song 顺带把filter里面的select也解决一下吧，有同样的问题

好像filter里面的没有修复。二级选项初始的时候query了一个404的url。然后搜索后，二级选项里面的值就没有了

Laravel-admin 1.7.7

**Comment by hulingling** [comment]
@z-song filter里面使用api获取选项，搜索后，选项里面没有初始化值
