### ISSUE TITLE
export feature not working with maatwebsite/excel version 3.0

### ISSUE THREAD

**Issue by sujitkv92** [z-song/laravel-admin#2359]
- Laravel Version: 5.6.0
- PHP Version: 7.1
- Laravel-admin: 1.5.15

I have followed the instruction of http://laravel-admin.org/docs/#/en/model-grid-export
it was working with maatwebsite/excel:~2.1.0. But now I have update maatwebsite/excel to version 3.0. Now export feature is not working in laravel-admin.

Please provide the export script that support with maatwebsite/excel 3.0

**Comment by z-song** [comment]
I have found the documentation for 3.0 version [here](https://laravel-excel.maatwebsite.nl/3.0/exports/collection.html), so you can try to implement it yourself based on this documentation.
