### ISSUE TITLE
Tabs and Rows

### ISSUE THREAD

**Issue by krsmga** [z-song/laravel-admin#2361]
- Laravel Version: 5.6
- PHP Version: 7
- Laravel-admin: 1.5.*

### Description:

I'm using Rows in my form to better take advantage of the screen space.

```
$form->row(function($row) {
    $row->text('field','textfield');
});
```

But I have many fields and I thought about separating them in Tabs
but when I try to do this

```
$form->tab('text', function($form) {
    $form->row(function($row) {
         $row->text('field','textfield');
    });
});
```

It simply does not print anything on the screen. Is it possible to use tabs and rows?

**Comment by luischavez** [comment]
@krsmga may be this work: #2363

**Comment by krsmga** [comment]
tks
