### ISSUE TITLE
Exception Driver [] is not supported when show image

### ISSUE THREAD

**Issue by imageslr** [z-song/laravel-admin#2365]
- Laravel Version: 5.6
- PHP Version: 7.2.5
- Laravel-admin: 1.5.19

### Description:
I have a User model which contains `avatar_url` field. **The field might be null**. 

In `grid()` function, it will display empty when `avatar_url` is null: 

![image](https://user-images.githubusercontent.com/17822028/44567576-a1281080-a7a5-11e8-8cf7-24fcc777fa77.png)

```php
$grid->avatar_url('头像')->image();
```

But in `show()` function, when `avatar_url` is null, it will throw the exception:

```php
$show->avatar_url('头像')->image();

// Driver [] is not supported. (View: /home/vagrant/code/Laravel/vendor/encore/laravel-admin/resources/views/show/panel.blade.php)
```
To solve this problem, I have to write `if...else`. Is there some method to avoid writing `if...else...`? Just like it in `grid()` —— **show nothing if the image field is null**.

Thank you.

**Comment by z-song** [comment]
提交了修复，可以更新到`v1.5.x-dev`

这个问题主要是会读取admin设置的disk来拼接图片地址，所以你也可以在`config/filesystems.php`中添加一个名为admin的disk的配置来修复你的问题

**Comment by imageslr** [comment]
1.5.x-dev是没有Show这个类的吧？我昨天用的就是1.5.x-dev版本，但是发现列表右侧只有编辑和删除两个按钮，没有查看详情，于是又改到1.5.19。

**Comment by imageslr** [comment]
请问是1.5.x-dev版本高还是1.5.19版本高？

**Comment by imageslr** [comment]
BTW，请问有没有什么方法能动态设置列的显示内容？我现在有个列，我想让它根据模型的值，在某些情况下显示Switch，某些情况下显示Tag。现在只发现display方法能动态设置文字，但是不能设置整个列。

**Comment by imageslr** [comment]
BTW，请问有没有什么方法能动态设置列的显示内容？我现在有个列，我想让它根据模型的值，在某些情况下显示Switch，某些情况下显示Tag。

我发现`display`方法是可以返回一个组件的，但是`SwitchDisplay`组件接收的4个参数`$value, Grid $grid, Column $column, $row`不知从何获取。

**Comment by z-song** [comment]
@imageslr 1.5.x-dev是最新的代码，对应master分支，关于动态设置列的功能我要考虑一下怎么实现

**Comment by z-song** [comment]
在`1.5.x-dev`版本里以下面的方式实现
```php
        $grid->column_name()->display(function ($value, $column) {
            if ($value.....) {
                return $column->switch();
            } else {
                return $column->tag();
            }
        });
```
