### ISSUE TITLE
[Feature Request] Support customized font-awesome icon in form text field

### ISSUE THREAD

**Issue by imageslr** [z-song/laravel-admin#2366]
The default icon of text field is `fa-pencil`. Could you please support setting customized icon of this form field? For example, if I want to get a field with `phone` icon, I have to use `$form->mobile()`. I hope have a method `icon()` so that I can replace default icon by linked call: 

```php
 $form->text('phone', '手机号')->icon('phone');
```

P.S: The reason I use `text` instead of `mobile` field is that I don't want to validate the field : )

**Comment by z-song** [comment]
Try this:
```php
$form->text('phone', '手机号')->prepend('<i class="fa fa-phone fa-fw"></i>');
```

**Comment by imageslr** [comment]
Works. Thank you.

**Comment by imageslr** [comment]
Actually I hope the function is like `prependIcon`

```PHP
$grid->email()->prependIcon('envelope');
```
