### ISSUE TITLE
Strange graphic difference

### ISSUE THREAD

**Issue by MarKco** [z-song/laravel-admin#2370]
- Laravel Version: 5.5.42
- PHP Version: 7.2.9-1
- Laravel-admin: 1.5

Hello everybody,
We developed a website using laravel-admin. This is a corner of our grid interface on our test server

![selection_128](https://user-images.githubusercontent.com/1422362/44594668-3091eb80-a7c7-11e8-9017-b8eaabaf447e.png)

and this is the same part of the interface on our customer's server after I installed laravel, laravel-admin and loaded the same database

![selection_129](https://user-images.githubusercontent.com/1422362/44594703-443d5200-a7c7-11e8-8727-8d77f0dbb949.png)

As you can see the icons are very different and some buttons are moved around.

The same happens when I enter one item for editing. In the lower corner I see the "save" button

![selection_131](https://user-images.githubusercontent.com/1422362/44594735-5ae3a900-a7c7-11e8-9728-566ae5467584.png)

this is the same on the customer's server

![selection_130](https://user-images.githubusercontent.com/1422362/44594753-620ab700-a7c7-11e8-8fae-f5fa9de35f01.png)

Could it be due to some missing permission? What could I do in order to check?

Thank you
Marco

**Comment by z-song** [comment]
The latest version of laravel-admin is installed on your customer's server. In the new version, some changes have been made to the grid.

You should also update the language file by running `php artisan vendor:publish --tag=laravel-admin-lang`

**Comment by MarKco** [comment]
Thank you so much!

**Comment by uacode** [comment]
@z-song Add plz this solution to README.md
