### ISSUE TITLE
Tab->add第二参数不能转换对象

### ISSUE THREAD

**Issue by ysfl** [z-song/laravel-admin#2371]
- Laravel Version: 5.5.27
- PHP Version:7.0
- Laravel-admin: 1.5.19
可以使用的版本：v1.5.15
### Description:
在tab里面调用grid时提示Object of class Encore\Admin\Grid could not be converted to string 
在v1.5.15版本的时候是没有问题的
### Steps To Reproduce:

    use Encore\Admin\Widgets\Tab;

    $content->body($this->tab());

    protected function tab()
    {
      $tab = new Tab();
      $tab->add('未完成任务', $this->grid(0));
      $tab->add('已完成任务', $this->grid(1));
      $tab->add('已删除任务', $this->grid(2));
      return $tab->render();
    }

    protected function grid($state)
    {

        return Admin::grid(Task::class, function (Grid $grid) use($state) {

          //事务状态筛选
          if ($state == 2) {
            $grid->model()->onlyTrashed();
          }else{
            $grid->model()->where('state', '=', $state);
          }

          $grid->id('编号')->sortable();
...

**Comment by taha-moghaddam** [comment]
Call render function after grid creation like this:
`Admin::grid(.., ..)->render()`

**Comment by ysfl** [comment]
@taha-moghaddam Thank you very much！

**Comment by andyhuang123** [comment]
Admin::grid(.., ..)->render() ,分页总是刷新到page=1
