### ISSUE TITLE
权限列表有一个小问题

### ISSUE THREAD

**Issue by zhangpipi** [z-song/laravel-admin#2373]
- Laravel Version: 5.5.42
- PHP Version:7.2
- Laravel-admin: 1.5.19

### Description:
权限列表变成这样了
![image](https://user-images.githubusercontent.com/41517203/44615274-fe38ca80-a868-11e8-9112-7fd49d8d13e9.png)

正常情况下，应该是这样的
![image](https://user-images.githubusercontent.com/41517203/44615284-1c062f80-a869-11e8-9bf7-5ffe47e9ff79.png)

### Steps To Reproduce:
首先，为了能迁移到生产环境，我用了这个「orangehill/iseed」这个包。配置好管理员、权限、角色、菜单等等后，逆向生成了这些 Seeder：[admin_operation_log] 这个表没有要。
![image](https://user-images.githubusercontent.com/41517203/44615301-83bc7a80-a869-11e8-88f0-932a1ebe8e30.png)

然后，`php artisan migrate:refresh --seed`

就会出现上面那样的情况了。导致新配置的管理员用户权限出错。解决办法：出错的权限点一下编辑，然后直接再保存。就OK了。

反映一下，不知道算不算bug...

**Comment by z-song** [comment]
应该是生产seed的时候，去掉了换行符，导致不能正确parse字符串到权限

**Comment by zhangpipi** [comment]
生产出来的seed是这样的：
![image](https://user-images.githubusercontent.com/41517203/44626405-2f3efb00-a94e-11e8-935d-a02bdebbc619.png)

`--seed`以后，用 phpstorm 看表：
![image](https://user-images.githubusercontent.com/41517203/44626417-5eee0300-a94e-11e8-9a4b-bcbbfbf3f8d8.png)

貌似换行符也在。但是在网页上换行符就不见了，必须要编辑再保存一下。

**Comment by fplun** [comment]
我这里也是这样,必须重新编辑一下才可以
