### ISSUE TITLE
https挂掉

### ISSUE THREAD

**Issue by cdhraesaemer** [z-song/laravel-admin#2375]
- Laravel Version: 5.6.*
- PHP Version:7.1.10
- Laravel-admin: 1.5.18

### Description:
站点上了证书前端没有问题，在访问 https;//localhost/admin 时有的js和css都挂掉了，而且链接http不带s

### Steps To Reproduce:
站点上了证书前端没有问题，在访问 https;//localhost/admin 时有的js和css都挂掉了，而且链接http不带s，但是能访问

![_20180825180640](https://user-images.githubusercontent.com/3795018/44617391-ffcbb800-a893-11e8-8e10-f4becd9e1c1b.png)
![_20180825180648](https://user-images.githubusercontent.com/3795018/44617392-01957b80-a894-11e8-8c65-c7d18c59dd27.png)

**Comment by ysfl** [comment]
config/admin.php 里面的'secure' => true,
config/app.php 里面的 'url' => env('APP_URL', 'https:// 这里加s
.env 里面的 APP_URL=https://127.0.0.1这里加s

**Comment by cdhraesaemer** [comment]
@ysfl 嗯谢谢，但是我改完之后登陆成功默认跳的还是普通的链接

**Comment by cdhraesaemer** [comment]
啊， 我nginx80强转443了
