### ISSUE TITLE
CKeditor 新增一对多关系表时失效?-- 已解决!

### ISSUE THREAD

**Issue by wizarot** [z-song/laravel-admin#2382]
- Laravel Version: 5.6.*
- PHP Version: 7.2.7
- Laravel-admin: 1.5.18

### Description:
在项目表单中,增加一对多关系表,按 新增 按钮, 新出来的字段没有正确加载CKeditor.

### Steps To Reproduce:
form 表关系 一对多
![image](https://user-images.githubusercontent.com/4525203/44656044-fe33f880-aa29-11e8-9c47-71ad59cb5d8c.png)

在编辑时,已有数据的字段,是这样的(正常情况):
![image](https://user-images.githubusercontent.com/4525203/44656099-33404b00-aa2a-11e8-8798-3a0db354ca4b.png)

但是在按下面绿色新增按钮,出现新的字段是,ckeditor并没有工作?
![image](https://user-images.githubusercontent.com/4525203/44656145-59fe8180-aa2a-11e8-8684-23304f79b4bc.png)

我的ckeditor是按照文档加入的,功能本身并没有问题. 我猜想应该是按 新增 按钮之后,应当增加一个手动触发js事件,这个地方需要修改. 但我不清楚应该怎么修改?

![image](https://user-images.githubusercontent.com/4525203/44656197-9500b500-aa2a-11e8-968f-3fd8dc46f684.png)

**Comment by yang5664** [comment]
/vendor/encore/laravel-admin/resources/views/form/editor.blade.php
```
<div class="{{$viewClass['form-group']}} {!! !$errors->has($errorKey) ? '' : 'has-error' !!}">

...
        <textarea class="form-control ckeditor {{$class}}" id="{{$id}}" name="{{$name}}" placeholder="{{ $placeholder }}" {!! $attributes !!} >{{ old($column, $value) }}</textarea>

        @include('admin::form.help-block')

    </div>
</div>

```
/vendor/encore/laravel-admin/src/Form/Field/Editor.php
```
<?php

namespace Encore\Admin\Form\Field;

use Encore\Admin\Form\Field;

class Editor extends Field
{
    protected static $js = [
        // '//cdn.ckeditor.com/4.5.10/standard/ckeditor.js',
    ];

    public function render()
    {
 ...
        //$this->script = "CKEDITOR.replace('{$this->column}', $options);";
        $this->script = "$('textarea.ckeditor').ckeditor($options);";
        return parent::render();
    }

}
```
試試看

**Comment by wizarot** [comment]
Thank it works!
非常感谢,解决问题了.  我用这个框架不太熟悉,你这样写我就明白问题的原因了.  ckeditor依赖 $('textarea.ckeditor')  也就是 class 找到对应的节点. 我之前按照文档中写的, 使用了 $('textarea.{$this->getElementClassString()}').ckeditor();  这样虽然可以精确定位到对应节点,但是却造成按新建按钮出现的节点无法被正确找到.  我尝试在blad.php 中给 textarea 增加节点 ckeditor,然后再editor.php文件中直接用你给的  textarea.ckeditor 查找,这样是可行的.

非常感谢!
![image](https://user-images.githubusercontent.com/4525203/44762838-0a7b9b00-ab7b-11e8-9ef8-ecc5dee2c975.png)

![image](https://user-images.githubusercontent.com/4525203/44762847-149d9980-ab7b-11e8-870a-e07167115894.png)

这样做确实可以解决问题的.
