### ISSUE TITLE
Permission help

### ISSUE THREAD

**Issue by krsmga** [z-song/laravel-admin#2383]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:

I have a table people that control through PeoplesController. I want to make a table relationship between people and users.

What I would like to do is a route so that the user, when logged in, has access only to the Edit method of his form, or in case there is no registration in people he has access to Create. I do not want him to have access to the Grid or to the register of other users. Can you do that?

**Comment by luischavez** [comment]
I manage that by using middleware.

Example route:
```php 
$router->resource('translations', TranslationController::class)
        ->middleware('owner:quotes,translator_id,translation');
```
middleware:
```php
<?php

namespace App\Http\Middleware;

use Closure;

use Illuminate\Support\Facades\DB;

use Encore\Admin\Facades\Admin;

class ResourceOwner
{

    public function handle($request, Closure $next, $table, $ownerField, $parameterName)
    {
        $user = Admin::user();
        $id = request()->route($parameterName);

        if ($user->isRole('administrator') || null == $id) return $next($request);

        $isOwner = DB::table($table)->whereId($id)->where($ownerField, '=', $user->id)->exists();

        if (!$isOwner) abort(401, 'Unauthorized');

        return $next($request);
    }
}
```
