### ISSUE TITLE
重写了model类下边的paginate,结果使用表单的filter功能的时候 ，点击搜索没有走自定义的方法

### ISSUE THREAD

**Issue by space-blank** [z-song/laravel-admin#2384]
- Laravel Version: 5.5.30
- PHP Version: 7.0.23
- Laravel-admin: 1.5.19

### Description:
表单的数据来源用的是自定义的数据，也就是重写了model类下边的paginate方法，可是用filter功能的时候，我看sql没有走自定义的方法，而是走了Eloquent ORM类的方法。这个是个大问题啊，而且我想把搜索条件里的字段处理下，请问我需要调用那个方法？有入口吗？
在线等....

**Comment by z-song** [comment]
走了Eloquent ORM类的哪个方法，你就重写哪个方法

**Comment by space-blank** [comment]
不好意思，不是很明白。
public function paginate(){
        $perPage = (int)Request::get('per_page', 20);

        $page = (int)Request::get('page', 1);

        $start = ($page-1)*$perPage;
        $channel = Admin::user()->channel;
        $query = DB::table('daily_record')
        ....
}
我是按照文档里边的 表格数据源 修改的这个方法，现在是页面中点击搜索之后，没走这个paginate()方法。

**Comment by space-blank** [comment]
/admin/stats/channel
/admin/stats/channel?_pjax=%23pjax-container&date%5Bstart%5D=&date%5Bend%5D=&channel_p=cj
就是这1个方法，加了搜索条件之后，走了不同的分页策略

**Comment by z-song** [comment]
试试重写where方法

**Comment by space-blank** [comment]
这么做岂不是越来越复杂了。。。失去了意义啊 。

**Comment by lanru** [comment]
model的where方法没被调用

**Comment by space-blank** [comment]
那请问怎么解决，重写where是可以，但不知道怎么重写 。。。额

**Comment by lanru** [comment]
在线等..

**Comment by zydudu** [comment]
同问这个问题

**Comment by feistiny** [comment]
因为eloquent的`where`方法返回的`$this`指针改变了，当调用`where`方法时
走了`vendor/laravel/framework/src/Illuminate/Database/Eloquent/Model.php`里的
```
public function __call($method, $parameters)
{
    if (in_array($method, ['increment', 'decrement'])) {
        return $this->$method(...$parameters);
    }     

    return $this->newQuery()->$method(...$parameters);
}
public function newQuery()
{
    return $this->registerGlobalScopes($this->newQueryWithoutScopes());
}
public function registerGlobalScopes($builder)
{
    foreach ($this->getGlobalScopes() as $identifier => $scope) {
        $builder->withGlobalScope($identifier, $scope);
    }
    return $builder;
}
```
根据现在的写法
```
$this->queries->unique()->each(function ($query) {
    $this->model = call_user_func_array([$this->model, $query['method']], $query['arguments']);
});
```
每次调用模型方法都会重置$this->model，而eloquent/model的方法是通过__call调用的eloquent/builder里的wheret和paginate方法，但是自定义的模型并没有直接继承builder，所以调用完where后，$this->model变成了eloquent/builder，再调用paginate方法，就不走自定义的paginate方法了。可以这样解决：
```
foreach ($this->queries->unique()->toArray() as $query) {
    $tmp_model = call_user_func_array([$this->model, $query['method']], $query['arguments']);
}
$this->model = $tmp_model;
```
只在方法链最后改变$this->model指向最后返回的$this（即$tmp_model），这样就行了。@松看看有什么副作用没

**Comment by feistiny** [comment]
上边的方法是不对的，每次调用都会new Builder，所以where之后想再调用其他的方法，只能在原来的方法返回值上调用，而方法链是在
```php
$this->queries->unique()->each(function ($query) {
    $this->model = call_user_func_array([$this->model, $query['method']], $query['arguments']);
});
```
这里调用的，如果有filter的话，相当于先调用了where，那么paginate方法调用的只能是已经实例化的builder对象的。
所以只有重写where方法，来实现两个自定义方法都调用，简单实现如下：
```php
    public function where()
    {
        $this->query = parent::where(...func_get_args());
        return $this;  // 返回自定义的模型给方法链中的$this->model
    }
    public function paginate()
    {
        dd(request()->input('id'));
        $this->query->paginate();
        ...
    }
```
访问`?id=123`时，先调用where再调用paginate

**Comment by fireinme** [comment]
> 上边的方法是不对的，每次调用都会new Builder，所以where之后想再调用其他的方法，只能在原来的方法返回值上调用，而方法链是在
> 
> ```
> $this->queries->unique()->each(function ($query) {
>     $this->model = call_user_func_array([$this->model, $query['method']], $query['arguments']);
> });
> ```
> 
> 这里调用的，如果有filter的话，相当于先调用了where，那么paginate方法调用的只能是已经实例化的builder对象的。
> 所以只有重写where方法，来实现两个自定义方法都调用，简单实现如下：
> 
> ```
>     public function where()
>     {
>         $this->query = parent::where(...func_get_args());
>         return $this;  // 返回自定义的模型给方法链中的$this->model
>     }
>     public function paginate()
>     {
>         dd(request()->input('id'));
>         $this->query->paginate();
>         ...
>     }
> ```
> 
> 访问`?id=123`时，先调用where再调用paginate


> 上边的方法是不对的，每次调用都会new Builder，所以where之后想再调用其他的方法，只能在原来的方法返回值上调用，而方法链是在
> 
> ```
> $this->queries->unique()->each(function ($query) {
>     $this->model = call_user_func_array([$this->model, $query['method']], $query['arguments']);
> });
> ```
> 
> 这里调用的，如果有filter的话，相当于先调用了where，那么paginate方法调用的只能是已经实例化的builder对象的。
> 所以只有重写where方法，来实现两个自定义方法都调用，简单实现如下：
> 
> ```
>     public function where()
>     {
>         $this->query = parent::where(...func_get_args());
>         return $this;  // 返回自定义的模型给方法链中的$this->model
>     }
>     public function paginate()
>     {
>         dd(request()->input('id'));
>         $this->query->paginate();
>         ...
>     }
> ```
> 
> 访问`?id=123`时，先调用where再调用paginate

可以举个例子吗

**Comment by fireinme** [comment]
> 上边的方法是不对的，每次调用都会new Builder，所以where之后想再调用其他的方法，只能在原来的方法返回值上调用，而方法链是在
> 
> ```
> $this->queries->unique()->each(function ($query) {
>     $this->model = call_user_func_array([$this->model, $query['method']], $query['arguments']);
> });
> ```
> 
> 这里调用的，如果有filter的话，相当于先调用了where，那么paginate方法调用的只能是已经实例化的builder对象的。
> 所以只有重写where方法，来实现两个自定义方法都调用，简单实现如下：
> 
> ```
>     public function where()
>     {
>         $this->query = parent::where(...func_get_args());
>         return $this;  // 返回自定义的模型给方法链中的$this->model
>     }
>     public function paginate()
>     {
>         dd(request()->input('id'));
>         $this->query->paginate();
>         ...
>     }
> ```
> 
> 访问`?id=123`时，先调用where再调用paginate



> * Laravel Version: 5.5.30
> * PHP Version: 7.0.23
> * Laravel-admin: 1.5.19
> 
> ### Description:
> 表单的数据来源用的是自定义的数据，也就是重写了model类下边的paginate方法，可是用filter功能的时候，我看sql没有走自定义的方法，而是走了Eloquent ORM类的方法。这个是个大问题啊，而且我想把搜索条件里的字段处理下，请问我需要调用那个方法？有入口吗？
> 在线等....
> 
> ### Steps To Reproduce:

老哥 你的解决了吗

**Comment by feistiny** [comment]
重定义了 paginate，想使用 Grid 的 Filter 的，可以用 [layoutOnlyFilter](https://github.com/z-song/laravel-admin/pull/2855)

**Comment by fireinme** [comment]
> 重定义了 paginate，想使用 Grid 的 Filter 的，可以用 [layoutOnlyFilter](https://github.com/z-song/laravel-admin/pull/2855)
是这样加吗？ 加了也不生效啊 
`   $grid->filter(function($filter){
            // 去掉默认的id过滤器
            $filter->disableIdFilter();
            // 在这里添加字段过滤器
            $filter->layoutOnly()->like('id', '注单号');

        });`
这是我重写的paginate 是复杂sql出来的
`  public function paginate()
    {
        $perPage = Request::get('per_page', 10);

        //返回联合查询数据
        $lists=$this->getUnionData();

        $total=count($lists);

        $movies = static::hydrate($lists);

        $paginator = new LengthAwarePaginator($movies, $total, $perPage);

        $paginator->setPath(url()->current());

        return $paginator;
    }`

**Comment by fireinme** [comment]
> 重定义了 paginate，想使用 Grid 的 Filter 的，可以用 [layoutOnlyFilter](https://github.com/z-song/laravel-admin/pull/2855)

因为我的表是分表，模型没用对应的边，所有
`$grid->model()
            ->when(!request('id'), function ($query) {
                return $query->where('id', '>', 10);
            });`
加了这段 会报错表不存在

**Comment by feistiny** [comment]
layoutOnly 就只是界面上会显示这个筛选器，只是 post 把参数传到后端，不会在 $grid->model 上加 where 过滤，获取到参数值后，在哪使用都可以。像你的例子，直接在 paginate 里 获取 $id = request('id'); 然后使用就行了。

**Comment by fireinme** [comment]
> layoutOnly 就只是界面上会显示这个筛选器，只是 post 把参数传到后端，不会在 $grid->model 上加 where 过滤，获取到参数值后，在哪使用都可以。像你的例子，直接在 paginate 里 获取 $id = request('id'); 然后使用就行了。
感谢 解决了

**Comment by tanjhysj0** [comment]
> 上边的方法是不对的，每次调用都会new Builder，所以where之后想再调用其他的方法，只能在原来的方法返回值上调用，而方法链是在
> 
> ```
> $this->queries->unique()->each(function ($query) {
>     $this->model = call_user_func_array([$this->model, $query['method']], $query['arguments']);
> });
> ```
> 
> 这里调用的，如果有filter的话，相当于先调用了where，那么paginate方法调用的只能是已经实例化的builder对象的。
> 所以只有重写where方法，来实现两个自定义方法都调用，简单实现如下：
> 
> ```
>     public function where()
>     {
>         $this->query = parent::where(...func_get_args());
>         return $this;  // 返回自定义的模型给方法链中的$this->model
>     }
>     public function paginate()
>     {
>         dd(request()->input('id'));
>         $this->query->paginate();
>         ...
>     }
> ```
> 
> 访问`?id=123`时，先调用where再调用paginate

然后你告诉我，为何就出现了不可调用静态方法这样的错？
`Non-static method App\Models\Ebusiness\EbusinessOrder::where() should not be called statically`

当我加入
```
    public static function __callStatic($funcname, $arguments)
    {
        echo "我是魔术呀";
        $app = new self(...$arguments);
        return $app;
    }
```
发现不执行，没用
当我去掉static时如下
```
    public  function __callStatic($funcname, $arguments)
    {
        echo "我是魔术呀";
        $app = new self(...$arguments);
        return $app;
    }
```
就发生以下错
```
Symfony \ Component \ Debug \ Exception \ FatalErrorException (E_UNKNOWN)
Cannot make static method Illuminate\Database\Eloquent\Model::__callStatic() non static in class App\Models\Ebusiness\EbusinessOrder
```
