### ISSUE TITLE
表单验证出现的Object of class Closure could not be converted to string

### ISSUE THREAD

**Issue by zhangpipi** [z-song/laravel-admin#2385]
Laravel Version: 5.5.42
PHP Version:7.2
Laravel-admin: 1.5.19

### Description:
这是我写的一个关于首页轮播图上传的表单验证：
    
    $form->image('image', '*图片')->crop(640, 256)->help('图片标准尺寸640*256，超出部分将被裁切')
            ->rules('required', [
                'required' => '请上传图片',
            ])
            ->rules(function ($form) {
                if(!$id = $form->model()->id) {
                    return  function($attribute, $value, $fail) {
                        if (TopBanner::all()->count() >= 5) {
                            return $fail('轮播图最多不超过5张');
                        }
                    };
                }
            });

我几乎就是照着laravel文档和admin文档写的。当 [新建] 的时候是没有问题的，也可以按照预期进行验证，但是当 [编辑] 的时候，保存就出现：
    `ErrorException In Field.php line 453 :`
    `Object of class Closure could not be converted to string`
我调试了半天，也没弄明白。反正就是 [新建] 就一切正常， [编辑] 就 ：
    `Object of class Closure could not be converted to string`
哪怕我把这一块注释掉：

    if(!$id = $form->model()->id) {
                    return  function($attribute, $value, $fail) {
                        if (TopBanner::all()->count() >= 5) {
                            return $fail('轮播图最多不超过5张');
                        }
                    };
                }

请问是我哪里弄错了吗？

**Comment by z-song** [comment]
提交了修复，先更新到`v1.5.x-dev`

**Comment by zhangpipi** [comment]
谢谢
我还发现貌似：
`$form->model()->id`
好像不管是 编辑 还是 新增 都是空值哦

**Comment by zhangpipi** [comment]
谢谢，我刚刚还发现：
我在:

    protected function form(){ 
    $form = new Form(new TopBanner);
    ....
    dd($form->model()->id)
    ....
    }

不管是新增还是编辑，这个值都是空的。 是不是要用别的方法来判断了？

**Comment by z-song** [comment]
因为这个时候还没有去查询数据，只有在渲染form之前才会执行查询
