### ISSUE TITLE
与 laravel-nestedset 有冲突

### ISSUE THREAD

**Issue by jourdon** [z-song/laravel-admin#2387]
- Laravel Version: 5.5.42
- PHP Version:  7.2
- Laravel-admin: 1.5.19

### Steps To Reproduce:

为了方便 排序和查看，分类使用的模型树，
但同时我使用了**laravel-nestedset**来做无限极分类，两个扩展包在模型的trait有冲突
```
class Category extends Model
{
    use ModelTree,AdminBuilder,NodeTrait;
}
```
>
Trait method parent has not been applied, because there are collisions with other trait methods on App\Models\Category

这个要怎么兼容一下？

**Comment by z-song** [comment]
parent方法冲突了，就给其中一个的parent方法取个别名
```php
use ModelTree,AdminBuilder,NodeTrait {
    parent as nodeParent;
}
```
注意调用NodeTrait方法的parent的地方全部替换为用nodeParent调用
