### ISSUE TITLE
软删除 针对上传文件无效

### ISSUE THREAD

**Issue by ahu** [z-song/laravel-admin#2388]
- Laravel Version: 5.6.*
- PHP Version: 7.1.20
- Laravel-admin: 1.5.*

### Description:
启用了laravel 的软删除（Soft Delete）及删除恢复，结果发现上传的文件被真正删除掉了，无法恢复。

### Steps To Reproduce:
后查找发现在`/vendor/encore/laravel-admin/src/Form/Field/UploadField.php` 最末尾的删除文件方法里没有软删除校验。应该做一下吧~

**Comment by jxlwqq** [comment]
“软删除”针对是对数据表的某条记录，并不针对文件本身。
你如果要实现软删除，应该删除对应的那条记录，而非删除存储文件路径的那个字段的值。
LA 处理的逻辑是为了避免脏文件。

**Comment by z-song** [comment]
@ahu 提交了修复，先更新到`v1.5.x-dev`

ps. 欢迎提交pull request

**Comment by ahu** [comment]
very good!
