### ISSUE TITLE
Safari 浏览器兼容性问题

### ISSUE THREAD

**Issue by zhangpipi** [z-song/laravel-admin#2389]
Laravel Version: 5.5.42
PHP Version:7.2
Laravel-admin: 1.5.19

### Description:
![image](https://user-images.githubusercontent.com/41517203/44716195-369c0b00-aaec-11e8-8ca7-20759af8b97c.png)
[Error] Failed to load resource: the server responded with a status of 404 (Not Found) (toastr.js.map, line 0)

进入Laravel-admin 首页，Safari会有个这样的错误。 同时用户信息更改不了，保存就无响应。其它页面都无问题。
我的是 MBA OSX10.13.6 Safari版本11.1.2

我测试了一下chrome，ie， edge，都正常。

**Comment by ahu** [comment]
我刚刚也发现了这个问题，不同是我是在更新 form 时出现，且除了上图所示404错误提示外，发现 nginx 返回400错误
