### ISSUE TITLE
如何在我的select里面加一个'请选择'

### ISSUE THREAD

**Issue by xiaalngf** [z-song/laravel-admin#239]
$form->select('shop','商店名称')->options(
                [-1,'请选择'],Shop::where('admin','=',Admin::user()->id)->pluck('short_name','id')
            )
我这个定法是错误的。

**Comment by edwinhuish** [comment]
试一下这个：
```
$form->select('shop','商店名称')->options(
     Shop::where('admin','=',Admin::user()->id)->pluck('short_name','id')->prepend('请选择', '')
)
```
