### ISSUE TITLE
在一个项目里面创建两个Admin的问题

### ISSUE THREAD

**Issue by xiaozha87** [z-song/laravel-admin#2397]
- Laravel Version: 5.6
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
我们想在一个Laravel里面创建两个后台，前台用户users登录后，也需要一个后台管理。
        @@@@@@@@参考了scr/Admin.php,增加了src/Frontend.php,Layout/FrontendContent.php,Facades/Frontend.php,和部分模板文件，修改后前台登录后页面布局显示没什么大问题，但是Form对象有问题，编辑时显示不了里面的字段，只显示了表单下部分的“重置”，“提交”，想问下问题出在哪里，或者有更好的解决方案。多谢，@z-song

**Comment by lihe6666** [comment]
我也有这样的需求，可是觉得封装上有些过于死板，不太好扩展。

**Comment by terranc** [comment]
同问

**Comment by z-song** [comment]
不支持

**Comment by terranc** [comment]
@z-song 是否有这个打算呢？
