### ISSUE TITLE
Form without user authentication

### ISSUE THREAD

**Issue by krsmga** [z-song/laravel-admin#2398]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
I'm trying to create a route to a form without authentication. This route is for the user to access a form to register with the system. After that he will have access to only this form.

But I'm having the following problem.

![erro](https://user-images.githubusercontent.com/8964209/44761465-a1177000-ab19-11e8-9681-f2c602b3b0d6.PNG)

My Route

```
Route::group([
    'prefix'        => config('admin.route.prefix'),
    'namespace'     => config('admin.route.namespace'),
    'middleware'    => config('admin.permission:free'),
], function (Router $router) {

    $router->get('testnewuser', 'PeoplesController@create');
});
```

I do not know if I'm doing it right, but what I want is just that. Create a custom route for any user to register on the form.

Then when you have your username and password, logging in will only have access to your registry. You can only edit your own data. You can not delete.

The admin user will have access to all records in a way that can handle them.

**Comment by z-song** [comment]
Show me your code

**Comment by krsmga** [comment]
it is this

https://github.com/krsmga/test-laravel-admin
