### ISSUE TITLE
上传视频问题

### ISSUE THREAD

**Issue by changPHP** [z-song/laravel-admin#2399]
Laravel Version: 5.5
PHP Version: 7.1
Laravel-admin: 1.5

![image](https://user-images.githubusercontent.com/26112014/44772519-a966be00-aba0-11e8-89f5-24dbf54ff4cc.png)

我使用 $form->file('detail')->move('public/upload/vodeo/')->removable(); 上传视频文件后，点开编辑进行查看，发现是使用 img 标签来进行解析的，导致上传视频无法查看，麻烦问下这里我需要如何进行更改~

**Comment by mi-autumn** [comment]
@changPHP 自己重写个,要不就只能修改对应的blade文件

**Comment by guyaofei** [comment]
@mi-autumn 是需要自己重写上传视频的功能，

**Comment by mi-autumn** [comment]
@guyaofei OSS应该要定义个disk然后换下文件系统的驱动

**Comment by jncinet** [comment]
这个前端js的配置有问题，fileinput这个前端JS的问题，把所有文件都以图片处理，无法预览。

**Comment by wuhaohui** [comment]
> 这个前端js的配置有问题，fileinput这个前端JS的问题，把所有文件都以图片处理，无法预览。

请问怎样解决

**Comment by mi-autumn** [comment]
改vendor呗

**Comment by wuhaohui** [comment]
> 改vendor呗

具体那个参数可以说下吗？，谢谢

**Comment by mi-autumn** [comment]
这个是不改vendor的
$form->multipleFile('video', 'videoLabel')->options([
'initialPreviewConfig' => [['filetype' => 'video/mp4']],
'initialPreviewFileType' => 'video',
]);

**Comment by wuhaohui** [comment]
> 这个是不改vendor的
> $form->multipleFile('video', 'videoLabel')->options([
> 'initialPreviewConfig' => [['filetype' => 'video/mp4']],
> 'initialPreviewFileType' => 'video',
> ]);
感谢，可以了

**Comment by chenzhulin** [comment]
上传一个mp4文件表单中点击提交没有反应，这是什么情况呢，也做了相应的配置了
