### ISSUE TITLE
select filters not working when the option value is 0.

### ISSUE THREAD

**Issue by mberende** [z-song/laravel-admin#24]
when you try to filter the grid with something like this my_filter=0&my_other_filter=2
 then the filters that are = 0 are not considered. 
This is a bug when working with mysql boolean fields (0,1) - you can only filter for 1, not for 0

**Comment by mberende** [comment]
actually when passing 0 as a filter it's ignored for any type of field.

**Comment by z-song** [comment]
Now  issue fixed.

I use array_filter() to remove empty inputs and it remove string `"0"`, which i didn't noticed.

Really thank you for find this.

**Comment by mberende** [comment]
Did you push this fix already?

**Comment by z-song** [comment]
Sorry, I pushed it just now.

**Comment by mberende** [comment]
Thanks! Suggestion of improvement
in AbstractFilter::condition() method you have to replace

        if (empty($value)) {
            return null;
        }

// because empty(0) is true 

        if ( ! isset($value)) {
            return null;
        }
