### ISSUE TITLE
权限控制的一朵疑云

### ISSUE THREAD

**Issue by ahu** [z-song/laravel-admin#2405]
- Laravel Version: 5.5.*
- PHP Version:7.1.20
- Laravel-admin: 1.5.*

### Description:

> （近几个月来官方文档快被我翻烂了，这个问题我很犹豫要不要提，不过不提不能解决我的问题）

我遇到的问题是：**页面控制权限覆盖了路由权限**

所以我想知道，正确的权限设置方法是什么。

### Steps To Reproduce:

在官方文档的「权限控制」文档部分关于「页面控制」的介绍中，如需要对页面展现细节的控制，可以简单的添加一个权限标识和权限名称就可以了。

我的一个项目（例如部署在`http://domain.com/admin`下）其中一个页面（例如是/admin/demos）有「场景2」的权限控制需求，故如法添加了一个权限（暂叫 A 权限）。添加完后，我看到在「权限列表」页里相关权限对应的路由自动显示为`【ANY】/admin`，但没有在意。

今天因为需要赋予某个拥有 A 权限的用户对另一页面的只读权限，添加了一条常规路由（暂叫 B 权限，例如HTTP 路径为/tests，HTTP方法为空），实际在权限列表里现实的路由为`【GET】/admin/tests`。之后进行简单测试发现：

_我惊奇的发现_ 该用户竟然可以对`/admin/tests`进行编辑删除等操作......

经过反复尝试，我发现去掉之前分配的 A 权限后，B 权限生效了！

**Comment by z-song** [comment]
`【ANY】/admin`表示对路径`/admin`下的所有路径都有了权限

**Comment by ahu** [comment]
所以，页面控制场景2权限设置，除了标识和名称还是需要具体设置 HTTP 方法和 HTTP 路径。
