### ISSUE TITLE
$grid->model()->where();

### ISSUE THREAD

**Issue by mRamadan0101** [z-song/laravel-admin#2406]
- Laravel Version: 5.5
- PHP Version:7
- Laravel-admin: 1.5

### Description:
$parameter  is array
and i want to modify source data using $grid->model by search by array in table and display all data with this condition 
i mean to add more than 1 parameter in  $grid->model()->where('id','=', array ); 
problem is get data using first parameter only 
### Steps To Reproduce:
try to use for loop and not working 
`       for ($a=0; $a <count($customer_id_filter) ; $a++) { 
            $grid->model()->where(['id'=> $customer_id_filter]);
            }`
try by add 2 where and not working 

try to use whereIn and not working too 

Thanks
waiting your answer

**Comment by z-song** [comment]
Use `whereIn` works fine for me like this

```php
$grid->model()->whereIn('id', [1, 2, 3, 4]);
```

**Comment by mRamadan0101** [comment]
i try it and this response 
` ErrorException In Builder.php line 765 :

Invalid argument supplied for foreach()`

**Comment by mRamadan0101** [comment]
Its working now
Thanks

**Comment by KulwinderKohli** [comment]
How can I get list of all user before 30 days of expiry date.

$grid->model()->whereDate('expiry_date', '<=', ?? );

**Comment by mRamadan0101** [comment]
> How can I get list of all users before 30 days of expiry date.
> 
> $grid->model()->whereDate('expiry_date', '<=', ?? );

$grid->model()->whereDate('expiry_date', '<=', \Carbon\Carbon::now()->subDays(30) )
