### ISSUE TITLE
Multiple export formats and column select

### ISSUE THREAD

**Issue by marzochi** [z-song/laravel-admin#2408]
- Laravel Version: 5.6.35
- PHP Version: 7.2.9
- Laravel-admin: 1.5.19

### Description:
If be is multiple exporting formats, it would be useful. Example export as XLSX, PDF etc.
And should be selectable columns for exporting. ( Defined on controller file )
If model has many relation with other models, on csv file contains more unncessary columns.

Thanks in advance

**Comment by noogen** [comment]
You can write your own exporter if you need other export format.  Here's example of my modification of the CsvExporter to export just the column I wanted (i.e. just the column I defined on my grid) or just pass in any column definition you're looking to export:

https://github.com/z-song/laravel-admin/issues/1723#issuecomment-364580224
