### ISSUE TITLE
自制的form表单如何提交到update或者store方法中去并拥有toastr提示

### ISSUE THREAD

**Issue by mi-autumn** [z-song/laravel-admin#2409]
- Laravel Version: 5.5
- PHP Version:7.1.19
- Laravel-admin: 1.5.15

### Description:
自制的form表单如何提交到update或者store方法中更新某些字段去并拥有toastr提示
还有就是前端组件form如何改变data的格式form-data和application/x-www-form-urlencoded转换
### Steps To Reproduce:
把可editable字段修改时,发送的请求数据,用form的格式传过去到是可以了(只是单个的),想来store和update是不是就得传全部数据了.但是我不想更新全部..

**Comment by Orocker** [comment]
return redirect(admin_base_path('test/test'))->withErrors(admin_toastr('tips','error'));
