### ISSUE TITLE
如何自动为每行数据生成view按钮

### ISSUE THREAD

**Issue by qskane** [z-song/laravel-admin#2410]
- Laravel Version: 5.5.4
- PHP Version: 7.0.12
- Laravel-admin: 1.5.19

### Description:

如何自动为每行数据生成view按钮 ? 效果类似于编辑按钮和删除按钮?
是否需要手动 ` $actions->prepend("");` ?

**Comment by z-song** [comment]
1.5.19版本  默认就有view按钮  参考demo
