### ISSUE TITLE
How to save data from nested form

### ISSUE THREAD

**Issue by vfa-quangnx** [z-song/laravel-admin#2412]
- Laravel Version: 5.6
- PHP Version: 7.1.3
- Laravel-admin: 1.5.9

### Description:
Currently, I want to save data from nested form, but I can't find way to handle it.

### Steps To Reproduce:
Please take a look at my source code and help me how to save data in nested form at TODO

`   

        $form = new Form(new Offers);
        $form->display('id', 'ID');
        $statusList = OfferStatus::all()->toArray();
        $productsOffer = Offers::find($offerId)->products()->get()->toArray();
        $products = Products::all()->toArray();
        $products = array_column($products, 'name', 'id');
        $statusList = array_column($statusList, 'status_name', 'status_code');
        
        $form->select('status')->options($statusList);
        $this->createdBasicForm($form);
        $form->display('total_price', 'Total price');
        $this->allProducts = $products;

        $form->hasMany('productsinoffers', 'Offer products', function(Form\NestedForm $nestedForm) {
            $nestedForm->select('product_id', 'Product')->options($this->allProducts);
        });

        $form->saved(function(Form $form){
            // Get form data & save to DB
            // Save from driect form
            $form->shopper_id = $form->model()->shopper_id;
            $form->buyer_id = $form->model()->buyer_id;
            $form->status = $form->model()->status;
            $form->currency = $form->model()->currency;
            $form->currency_rate = $form->model()->currency_rate;
            $form->discount_rate = $form->model()->discount_rate;

            // TODO: Save from nested form, how to do it? I tried the way below
            /// but it doesn't anythings
            $form->productsinoffers = $form->model()->productsinoffers;
        });

        return $form;
    `

Hope you will help me, thank you.

**Comment by z-song** [comment]
You don't need to define a saved callback, you just need to define a one-to-many relationship between the two models.

**Comment by vfa-quangnx** [comment]
@z-song thank you for your replying. In my context, I created the the relationship between 2 models: Offers, ProductsInOffers: one - many.
At models: Offers:
` 
public function productsinoffers() {
        return $this->hasMany('App\Models\ProductsInOffers', 'offer_id');
}
`
At model: ProductsInOffers:
`    public function offers()
    {
        return $this->belongsTo('App\Models\Offers', 'offer_id');
    }`
In the function design form, I do this:
`$form = new Form(new Offers);

        $form->display('id', 'ID');
        $statusList = OfferStatus::all()->toArray();
        $productsOffer = Offers::find($offerId)->products()->get()->toArray();
        $products = Products::all()->toArray();
        $products = array_column($products, 'name', 'id');
        $statusList = array_column($statusList, 'status_name', 'status_code');
        
        $form->select('status')->options($statusList);
        $this->createdBasicForm($form);
        $form->display('total_price', 'Total price');
        $this->allProducts = $products;

        $form->hasMany('productsinoffers', 'Offer products', function(Form\NestedForm $nestedForm) {
            $nestedForm->select('product_id', 'Product')->options($this->allProducts);
        });

        // QUESTION: It's still not save in nested form

        $form->saved(function (Form $form) {
            // QUESTION: Get list of product_id from nested form
            $productIds = $form->model()->productsinoffers; // It doesn't work
        });

        return $form;`
But it still not save data from nested form its correspond model(ProductsInOffers). How I solve this problem.
And by the way, I want to get list product_id from nested form for my own calculating. I notes in "QUESTION" tag at code. Please take a look and help me use Caravel-Admin better.

**Comment by vfa-quangnx** [comment]
Hi, can you help me please.

**Comment by sharppanyang** [comment]
> Hi, can you help me please.

hey, man, I came across the same problem with you. Can you tell have you fixed it?

**Comment by phantomsom** [comment]
Bump, anyone found a fix to this?

**Comment by phantomsom** [comment]
back()->withInput() doesn't save nested forms

**Comment by Cristian-Blanco** [comment]
You must enabled the fillable in the model.
in this case, in the model "ProductsInOffers":

`
  class ProductsInOffers extends Model {
     protected $fillable = ['product_id'];

    public function offers()
    {
        return $this->belongsTo('App\Models\Offers', 'offer_id');
    }
  }
`
