### ISSUE TITLE
怎么在create页面默认的新增按钮上传递参数？

### ISSUE THREAD

**Issue by Orocker** [z-song/laravel-admin#2414]
- Laravel Version: 5.6.35
- PHP Version:7.2.10
- Laravel-admin: ^1.5

怎么在默认的新增按钮上传递参数？

**Comment by mojiajuzi** [comment]
@Orocker 我是直接增加了一个扩展
```
    /**
     * @var string
     */
    private $queryParams;

    /**
     * Create a new CreateButton instance.
     *
     * @param Grid $grid
     * @param string $queryParams
     */
    public function __construct(Grid $grid, string $queryParams)
    {
        $this->queryParams = $queryParams;
        $this->grid = $grid;
    }

    /**
     * Render CreateButton.
     *
     * @return string
     */
    public function render():string
    {
        $new = trans('admin.new');
        return <<<EOT

<div class="btn-group pull-right" style="margin-right: 10px">
    <a href="{$this->grid->resource()}/create{$this->queryParams}" class="btn btn-sm btn-success">
        <i class="fa fa-save"></i>&nbsp;&nbsp;{$new}
    </a>
</div>

EOT;
    }
```

**Comment by Orocker** [comment]
@mojiajuzi 这个具体是怎么用的？

**Comment by mojiajuzi** [comment]
@Orocker 
```php
$query = '?'.http_build_query(['tool_id' => $toolId]);
$grid->tools(function ($tools)use($grid, $query){
    $tools->append(new CreateNewButton($grid, $query));
});
```

**Comment by Orocker** [comment]
@mojiajuzi CreateNewButton这个类没有

**Comment by mojiajuzi** [comment]
@Orocker  第一个回复里面的类就是`CreateNewButton`

**Comment by Orocker** [comment]
$toolId = 1;
        $query = '?'.http_build_query(['tool_id' => $toolId]);
        $grid->tools(function ($tools)use($grid, $query){
            $tools->append(new Grid\Tools\CreateButton($grid, $query));
        });
我这grid里面添加了这段代码之后，创建的url还是/test/create

**Comment by Orocker** [comment]
\vendor\encore\laravel-admin\src\Grid\Tools\CreateNewButton.php
我在这里定义了一个扩展，代码如下，
`<?php

namespace Encore\Admin\Grid\Tools;

use Encore\Admin\Grid;

class CreateNewButton extends AbstractTool
{
    /**
     * @var Grid
     */
    protected $grid;

    protected $queryParams;

    /**
     * Create a new CreateButton instance.
     *
     * @param Grid $grid
     */
    public function __construct(Grid $grid,string $queryParams)
    {
        $this->grid = $grid;
        $this->queryParams = $queryParams;
    }

    /**
     * Render CreateButton.
     *
     * @return string
     */
    public function render():string
    {
        $new = trans('admin.new');
        return <<<EOT
        <div class="btn-group pull-right" style="margin-right: 10px">
            <a href="{$this->grid->resource()}/create{$this->queryParams}" class="btn btn-sm btn-success">
                <i class="fa fa-save"></i>&nbsp;&nbsp;{$new}
            </a>
        </div>
       EOT;
    }
}
`

在控制器里面调用：
`  $toolId = 1;
        $query = '?'.http_build_query(['tool_id' => $toolId]);
        $grid->tools(function ($tools)use($grid, $query){
            $tools->append(Grid\Tools\CreateNewButton($grid,$query));
        });
`
报错：
Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to undefined function Encore\Admin\Grid\Tools\CreateNewButton()`
`
这是怎么回事呢？

**Comment by Orocker** [comment]
谢谢

**Comment by Orocker** [comment]
@mojiajuzi 为什么用这个创建的按钮默认是展开的呢？怎么让他默认不是展开
