### ISSUE TITLE
文档版本是否和代码1.5.x-dev版本不一致?

### ISSUE THREAD

**Issue by qskane** [z-song/laravel-admin#2415]
- Laravel Version: 5.5.*
- PHP Version: 7.0
- Laravel-admin: 1.5.x-dev

文档上面显示[模型详情](http://laravel-admin.org/docs/#/zh/model-show?id=%E6%95%B0%E6%8D%AE%E6%A8%A1%E5%9E%8B%E8%AF%A6%E6%83%85) 使用的是 
`Admin::show()`方法,但是代码中使用show方法会报错找不到show方法,是因为文档不一致吗?

**Comment by qskane** [comment]
抱歉,是由于composer使用了中国镜像,导致代码版本与文档版本不一致

**Comment by z-song** [comment]
用命令`php artisan admin`可以查看当前的版本
