### ISSUE TITLE
Image preview on edit mod ?

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#2416]
@z-song 
Can you show me how to display preview image file on edit mod?

![image](https://user-images.githubusercontent.com/10907980/44898260-90891480-ad28-11e8-9546-c78960d1466e.png)

**Comment by Orocker** [comment]
protected function form()
    {
    ...
        $form->image('picture');
        return $form;
    }

**Comment by taimaiduc** [comment]
@Orocker I see him have been removed preview image on edit mode
@z-song Is that right?

**Comment by z-song** [comment]
Image preview is not removed in edit mode

http://demo.laravel-admin.org/auth/users/1/edit

**Comment by taimaiduc** [comment]
I mean when you go back to edit. The original image is not shown. Only text value

**Comment by Orocker** [comment]
@taimaiduc  if you want to display image, 
```
public function form()
{
 $form->image('cloumn', 'description'));
}
         
```

**Comment by taimaiduc** [comment]
@Orocker Yes, I know this. It worked before. 
What your current laravel admin version?
![image](https://user-images.githubusercontent.com/10907980/45546827-b6460b80-b848-11e8-912e-fd6ed4022f2c.png)

**Comment by Orocker** [comment]
v1.5.9

**Comment by taimaiduc** [comment]
Can you upgrade and check again ? @Orocker

**Comment by z-song** [comment]
@taimaiduc Check your admin disk configuration in `config/filesystem.php`, it should have a `url` key like:
```php
    'admin' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'url' => env('APP_URL').'uploads',
            'visibility' => 'public',
        ],
```

**Comment by taimaiduc** [comment]
@z-song Thank you so much it working.

**Comment by ntqthaihv** [comment]
Thank you. It worked
