### ISSUE TITLE
关于grid中新增按钮的url问题

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#242]
当前这个按钮的url是`/{{$grid->resource()}}/create`，能否换成带值的。
我现在就遇到一个问题。我当前的路径为 `***/admin/vote/1`,但是这个新增按钮的路径却是`***/admin/vote/{vid}/create`，没有转换过来,这个好纠结啊，表单的url也是这样

**Comment by edwinhuish** [comment]
个人感觉，button 这个类， @z-song 还没有做好。 View很多细化的功能，暂时有需要的话，只能自己扩展。

**Comment by z-song** [comment]
正在优化  等更新吧

**Comment by z-song** [comment]
@iianpan 目前新增按钮是根据当前资源的url来设定的 如果要实现你的需求，可以把新建按钮关掉
```php
$grid->disableCreation();
```

再参考 https://github.com/z-song/laravel-admin/blob/master/docs/zh/grid-custom-tools.md 自定义个按钮工具 链接到你想要的地址上去

**Comment by rainsens** [comment]
为什么自定义的按钮只能显示在左侧，不能显示在右侧？如果右侧也能显示会更好一些。

**Comment by freework-y** [comment]
我把新增按钮禁了,但是可以通过/create进入 @z-song
