### ISSUE TITLE
JSON数据格式的字段，改怎么增改呢？

### ISSUE THREAD

**Issue by OranTing** [z-song/laravel-admin#2420]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: v1.5.19

### Description:
例如，商品模型，会有很多属性。不同商品属性也不一样。
例如，服装商品有属性，颜色，尺码。而手机商品有内存，颜色等。
在数据库里使用json进行储存。
格式如下：
`{"尺码": ["L", "XL", "XXL"], "性别": ["男", "女"], "颜色": ["红色", "黄色", "蓝色"]}`

这样的字段，使用laravel-admin可以进行维护么？像上面的例子里， 尺码、性别、颜色之外，还可能会增加 型号、这样的属性名。

仔细阅读了文档，没有找到很好的解决方案。

**Comment by jxlwqq** [comment]
可以试试这个扩展：https://github.com/laravel-admin-extensions/json-editor
