### ISSUE TITLE
Help-me please. User register!!!!!

### ISSUE THREAD

**Issue by krsmga** [z-song/laravel-admin#2422]
php artisan admin:install

This has already been done, but only the screen appears for the user to log in. This is not what I want, I need an option so that the user who does not have a login can register to the portal.

I have a lot of difficulties, and there is little information on that. I can not find solutions and I'm stagnant without being able to continue with my project. I need a lot of help. Please.

![login](https://user-images.githubusercontent.com/8964209/44929770-8e2bb800-ad32-11e8-870c-04d5e53dcad9.JPG)

**Comment by ngomile** [comment]
While I'm just a random passerby and haven't really even touched Laravel much or this. I think this is something you have to handle in your controller, essentially you should add a route that the controller should redirect to in case the user does not have an account. Sorry for not being much help.

**Comment by ysfl** [comment]
default username : admin or password:admin
if you need register , please custom you routes in app/Admin/Controllers/routes.php and create you register code model and Controllers

**Comment by Tatoo2018** [comment]
you can pass login auth if you dont use laravel admin's middleware.
and you need to make signup page yourself.

// no login auth
//you can see this URL without login auth
//http://test.com/signup
Route::group([
    'namespace' => config('admin.route.namespace')
        ], function (Router $router) {
    $router->resource('signup', SignUpController::class);
});

//or 
//you can see this URL without login auth
//http://test.com/admin/signup
Route::group([
     'prefix' => config('admin.route.prefix'),
    'namespace' => config('admin.route.namespace')
        ], function (Router $router) {
    $router->resource('signup', SignUpController::class);
});

you need to add this on  [ App/Admin/routes.php ]
