### ISSUE TITLE
form数据提交，如果某些字段需要提交，但不保存，该如何处理？

### ISSUE THREAD

**Issue by SuzutsukiKagami** [z-song/laravel-admin#2428]
- Laravel Version: 5.5
- PHP Version:7.2.8
- Laravel-admin: #.#.#

### Description:
for exanple:
$form->text('seller', '商家');
$form->ignore(['seller']);

i can't get this value by "$form->seller;" in $form->saving or $form->saved

**Comment by z-song** [comment]
用`request('seller')` 获取

**Comment by fenghoer** [comment]
> 用`request('seller')` 获取

很有用，刚好要用这一点。建议把这个加到文档里面，怎么取form提交时的参数信息。
