### ISSUE TITLE
显示筛选关联表中字段如何做

### ISSUE THREAD

**Issue by mygithahah** [z-song/laravel-admin#2429]
- Laravel Version: 5.5.41
- PHP Version: 7.1.20
- Laravel-admin: 1.5.17

### Description:

有个问题，当前用使用users表的数据，我如何在限制profiles表的gender字段呢，比如我只要显示用户表gender为女的用户，怎么来写

**Comment by mygithahah** [comment]
CREATE TABLE `users` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`name` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
`email` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
`created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
`updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `profiles` (
`id` int(10) unsigned NOT NULL AUTO_INCREMENT,
`user_id` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
`age` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
`gender` varchar(255) COLLATE utf8_unicode_ci NOT NULL,
`created_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
`updated_at` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
附上表结构

**Comment by z-song** [comment]
到laravel的文档里搜`whereHas`

**Comment by Orocker** [comment]
@z-song 怎么对关联表中的字段进行筛选

**Comment by mygithahah** [comment]
@z-song  whereHas是对字段筛选，我的目的是显示,不做filter

**Comment by z-song** [comment]
文档里面都有写
```php
$grid->model()->whereHas('profiles', function ($query) {
    $query->where('gender', '女');
});
```

**Comment by mygithahah** [comment]
可以，😆

**Comment by bravist** [comment]
推荐用这个方法解决问题：

https://github.com/hoyvoy/laravel-cross-database-subqueries
