### ISSUE TITLE
不能存null吗？

### ISSUE THREAD

**Issue by eroy4u** [z-song/laravel-admin#243]
我看了文档都找不到如何规定可以存Null
例如我的数据表有一个user_id栏，是可以null的
那我可写成
$user_options = User::all()->pluck('name', 'id')->all();
$form->select('user_id')->options($user_options);
这个可以走，介面可以选择不同的user，但我这个user_id是可有可没有的，即是数据表中可以null的，
这样介面就没有留空user这个选项，
我试了
$user_options = array_merge([0 =>'-- None --'], $user_options);
$form->select('user_id')->options($user_options);
什至加了
            $form->saving(function(Form $form) {
                echo ' in saving';
                if(!$form->user_id)
                {
                     $form->user_id = null;
                }
            });
但在提交时，也是会SQL出错，我看走了的SQL是
(SQL: update `users` set `updated_at` = 2016-12-28 07:52:52, `user_id` = 0 where `id` = 1)
但问题我的user_id想是NULL而不是0

**Comment by edwinhuish** [comment]
如果你的SQL字段仅有 name 和 id，存null还不如直接不存。如果有其他字段，保存其他字段，而 name 不设值，就能达到效果。

**Comment by eroy4u** [comment]
我不太明白你的意思，例如我的Model是Task，這個Model其中一欄是user_id是一個外鍵，是指向另一個User的，可以是null即是沒有User擁有這個Task，
我在介面上用了一個select來選User，我想選null的話就會SQL出錯

**Comment by z-song** [comment]
因为前端form想后端传的数据都是字符串类型的，但是插入之前不知道数据库该字段的类型，所以会有异常，你可以用下面的方式来解决：

在模型中加入代码:
```php
    protected static function boot()
    {
        parent::boot();

        static::saving(function ($model) {

            if ($model->user_id == '0') {
                $model->user_id = null;
            }

        });
    }
```
