### ISSUE TITLE
sweetalert不支持html

### ISSUE THREAD

**Issue by cdhraesaemer** [z-song/laravel-admin#2430]
- Laravel Version: 5.5.*
- PHP Version: 7.1.14
- Laravel-admin: 1.5.15

### Description:
sweetalert 不支持html

### Steps To Reproduce:
使用sweetalert 不支持html
![_20180903150615](https://user-images.githubusercontent.com/3795018/44972237-0c829700-af8b-11e8-9962-e0a63821ca1f.png)
![_20180903150548](https://user-images.githubusercontent.com/3795018/44972245-0ee4f100-af8b-11e8-8a01-b54849e258bf.png)

之后我替换了 `/public/vendor/laravel-admin/sweetalert/dist` 中的内容，
将 `sweetalert.css` 中的内容 替换为 https://cdn.jsdelivr.net/npm/sweetalert2@7.26.12/dist/sweetalert2.css
将 `sweetalert.min.js` 中的内容 替换为 https://cdn.jsdelivr.net/npm/sweetalert2@7.26.12/dist/sweetalert2.all.min.js

现在OK了，但是，但是，但是 整个样式小了2圈如图：
![_20180903151145](https://user-images.githubusercontent.com/3795018/44972435-b6622380-af8b-11e8-8453-129f98ace243.png)
比例小了2圈，感觉很奇怪，求解答，求原大小
😂😂😂😂😂😂😂😂😂😂😂😂😂😂😂

**Comment by z-song** [comment]
sweetalert2的默认样式就是这样，你只能习惯它

**Comment by cdhraesaemer** [comment]
那好吧
