### ISSUE TITLE
How can i save images in multiple sizes

### ISSUE THREAD

**Issue by chiwex** [z-song/laravel-admin#2431]
- Laravel Version: 7.2.7
- PHP Version: 5.5.42
- Laravel-admin: 1.5

How can i save images in multiple sizes like
'thumb' => '200x200',
'large'=> '200x200',
'thumb => '200x200',

I have check the documentation no such feature like that.

**Comment by taimaiduc** [comment]
Can you try  https://laravel.com/docs/5.6/eloquent#observers
Model save -> Get image -> Resize whatever you want

**Comment by volkish** [comment]
You can use custom Field class. For example [https://gist.github.com/volkish/d6140885aa18245e13d8dedec0bba872](https://gist.github.com/volkish/d6140885aa18245e13d8dedec0bba872).

**Comment by chiwex** [comment]
Thank you @volkish I am grateful. this is the solution i need, I will try it
