### ISSUE TITLE
Method Encore\Admin\Grid::__toString() must not throw an exception, caught Error: Class 'Symfony\Component\Filesystem\Exception\FileNotFoundException' not found

### ISSUE THREAD

**Issue by encone** [z-song/laravel-admin#2437]
- Laravel Version: 5.5
- PHP Version: 7.1.13
- Laravel-admin: 1.5

### Description:
Method Encore\Admin\Grid::__toString() must not throw an exception, caught Error: Class 'Symfony\Component\Filesystem\Exception\FileNotFoundException' not found

**Comment by taimaiduc** [comment]
Can you show your code ?

**Comment by Orocker** [comment]
`Can you show your code ?`

**Comment by z-song** [comment]
No reply, close
