### ISSUE TITLE
Listbox with hasMany model relation (One-to-many)

### ISSUE THREAD

**Issue by Romerski** [z-song/laravel-admin#2438]
For example, I have cars and users.

One car belongs to a user but a user can have many cars. I want to render a listbox on UserController (with hasMany relation to cars), showing all available cars on left box of the listbox. Yea, this works and store fine in database. But if I want to edit this user to add a new car, on right box of the listbox, I cant see his related cars, it's blank.

Can this be done? I don't want to use $form->hasMany() because cars are already created, don't want to create them on user form. Only select desired cars from listbox (or remove them of related cars) options and save it to database.

**Comment by mineschan** [comment]
Show your code of listbox field

**Comment by Romerski** [comment]
@mineschan Sure, here you have:

```
$form->listbox('muestras', 'Muestras')->options(
    Muestra::all()->pluck('full_rey', 'id')
 );
```

If I go to edit form on the model who has this "Muestras" related (2 in this case) you can see empty the second listbox, like if there was not any related (screen).

https://i.gyazo.com/70640b71b8c0edb8b5c334a88973312f.png

I think its because of relationship (1-n). Because on my other relationship (n-m) it works fine.

Thanks.

**Comment by mineschan** [comment]
any possibility that the eloquent models relationship configuration wrong?

**Comment by Romerski** [comment]
@mineschan Here you have... I think its ok.

One 'Muestra' belongs to one 'Analisis' but one 'Analisis' can have 1 or more 'Muestras'.

```
class Muestra extends Model
{
    protected $connection = 'mysql';
    protected $table = 'muestras';
    protected $fillable = ['rey, num_muestra, analisis_id, created_by, updated_by'];

    public function getFulLReyAttribute()
    {
        return $this->rey . "-" . sprintf("%02d", $this->num_muestra);
    }

    public function analisis()
    {
        return $this->belongsTo('App\Models\Analisis', 'analisis_id', 'id');
    }
}
```
```
class Analisis extends Model
{
    protected $table = 'analisis';
    protected $connection = 'mysql';
    protected $fillable = ['referencia, estado, num_contrato, cliente_id, created_by, updated_by'];

    public function muestras()
    {
        return $this->hasMany('App\Models\Muestra', 'analisis_id', 'id');
    }
}
```

**Comment by mineschan** [comment]
try to remove both ```'analisis_id', 'id'```

**Comment by z-song** [comment]
The listbox works fine in [demo](http://demo.laravel-admin.org/auth/roles/1/edit) with a one-to-many relationship

Code is here 
 https://github.com/z-song/laravel-admin/blob/master/src/Controllers/RoleController.php#L148

Maybe you can find the answer by referring to the code.

**Comment by Romerski** [comment]
@z-song thanks for your answer but as I can see role and permission is N-M relationship. Or I'm getting confused?

I have a N-M relationship and listbox works well. But not in this case. Also, I have to update manually "Muestras" table to add "Analisis" ID when created, because "Muestras" are created first, and then I create an "Analisis" and "Muestras" are selected on his creation form from listbox. Because is 1-n relationship and "Analisis" hasMany "Muestras" even if creation is afterwards. 

I think there's no other way to do it... Is it?
