### ISSUE TITLE
Column::extend() undefined 

### ISSUE THREAD

**Issue by pheonix-inno** [z-song/laravel-admin#244]
当我在bootstrap添加扩展时，运行显示以下错误：

FatalErrorException in bootstrap.php line 25:
Call to undefined method Encore\Admin\Grid\Column::extend()
in bootstrap.php line 25

怎么回事，版本低的问题？

**Comment by edwinhuish** [comment]
请贴代码，不过初步判断，应该是没有 ``` use Encore\Admin\Grid\Column; ```

**Comment by pheonix-inno** [comment]
bootstrap.php的代码如下：

<?php

/**
 * Laravel-admin - admin builder based on Laravel.
 * @author z-song <https://github.com/z-song>
 *
 * Bootstraper for Admin.
 *
 * Here you can remove builtin form field:
 * Encore\Admin\Form::forget(['map', 'editor']);
 *
 * Or extend custom form field:
 * Encore\Admin\Form::extend('php', PHPEditor::class);
 *
 * Or require js and css assets:
 * Admin::css('/packages/prettydocs/css/styles.css');
 * Admin::js('/packages/prettydocs/js/main.js');
 *
 */

use Encore\Admin\Grid\Column;
use App\Admin\Extensions\ExpandRow;

Column::extend('expand', ExpandRow::class);

**Comment by pheonix-inno** [comment]
bootstrap.php的代码如下：

`
<?php

/**
 * Laravel-admin - admin builder based on Laravel.
 * @author z-song <https://github.com/z-song>
 *
 * Bootstraper for Admin.
 *
 * Here you can remove builtin form field:
 * Encore\Admin\Form::forget(['map', 'editor']);
 *
 * Or extend custom form field:
 * Encore\Admin\Form::extend('php', PHPEditor::class);
 *
 * Or require js and css assets:
 * Admin::css('/packages/prettydocs/css/styles.css');
 * Admin::js('/packages/prettydocs/js/main.js');
 *
 */

use Encore\Admin\Grid\Column;
use App\Admin\Extensions\ExpandRow;

Column::extend('expand', ExpandRow::class);
`

**Comment by z-song** [comment]
请更新到最新版本
