### ISSUE TITLE
My delete  action is not working

### ISSUE THREAD

**Issue by laziestcoder** [z-song/laravel-admin#2443]
My delete action is not working. When I click on delete icon it shows me a confirmation box. After click on the confirm it does nothing. 

How to fix this?

**Comment by Romerski** [comment]
You may have an exception on a foreign key.

I would recommend to install [Laravel DebugBar](https://github.com/barryvdh/laravel-debugbar) and check exceptions tab for more info.

**Comment by laziestcoder** [comment]
I am using Exception Reporter and it has no error regarding this issue.

**Comment by laziestcoder** [comment]
how can I remove this laravel Debugger ? It is very odd looking . :/

**Comment by krsmga** [comment]
If you're using Chrome, refresh the screen and press Ctrl + Shift + I and go to the console. After you try to delete again, the error that is preventing it from working will probably appear. This delete action calls a DELETE route through a JQuery, so it will show an error in the console. Take a print and show it here.

But you're probably having an exception to some relationship. Is this record you're deleting related to another table?

**Comment by laziestcoder** [comment]
No, I was trying to delete in the same table.

By the way, I have figured out my problem. It was a problem with routing. Thank you all. ^_^

**Comment by Pashaster12** [comment]
@krsmga @Romerski and what should I do if I have an error because of related data?

**Comment by Romerski** [comment]
@Pashaster12 Maybe settings correct foreign key constraints (on delete cascade por example) or setting `SET FOREIGN_KEY_CHECKS=0;` and then back to `1` after delete your needed rows.

**Comment by Pashaster12** [comment]
@Romerski and what about code inside admin controllers? Is it possible?

**Comment by Pashaster12** [comment]
@Romerski by the way, thanks for your suggestion with constraints. It's the easiest way of implementation in my case.

**Comment by shahnawazdaanish** [comment]
In my case, I found it was a bug. When I use material design, it sends extra "plugin_ripples" parameter in data at src/Actions/Action.php file in the core of the library. unsetting it in both Action.php and interactor/Dialog.php files works perfectly.
