### ISSUE TITLE
View [partials.error] not found. (View:vendor/encore/laravel-admin/resources/views/content.blade.php)

### ISSUE THREAD

**Issue by tuine** [z-song/laravel-admin#2446]
- Laravel Version: 5.5.43
- PHP Version:7.2.4
- Laravel-admin: 1.5.19

### Description:
View [partials.error] not found. 
(View: /data/code/vendor/encore/laravel-admin/resources/views/content.blade.php)

### Steps To Reproduce:

1. At first, I used 1.5.x-dev，It works.
2. Then, I switch to  1.5.19: An error occurred after login.
```
(View [partials.error] not found. (View: /data/code/vendor/encore/laravel-admin/resources/views/content.blade.php))
```
3. Accidental, I found that use the same version(1.5.19) which from a project that can work to cover (vendor/encore/laravel-admin) directly . Miracles happen. It works. 

4. Then I switch back to 1.5.x-dev, composer update, but It can't work!!! WTF???
error:
```
(View [partials.alerts] not found. (View: /code/laravel-admin/vendor/encore/laravel-admin/resources/views/content.blade.php)
```
5. Then I switch back to 1.5.19 again， It can work！！！

**Comment by z-song** [comment]
After switch version, try running `php artisan view:clear`

**Comment by tuine** [comment]
@z-song 
Thanks!
