### ISSUE TITLE
vendor\encore\laravel-admin\src\Controllers 中没有调用配置中的 Model

### ISSUE THREAD

**Issue by codingyu** [z-song/laravel-admin#2457]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.5.19

### Description:
配置中可以定义 `Model` 路径，但是 `vendor\encore\laravel-admin\src\Controllers` 中并没有调用配置中的 `Model`，不能方便的重写 `Model` 。

**Comment by codingyu** [comment]
也可以 👌

**Comment by codingyu** [comment]
@z-song 还是这个问题，是后台的默认头像，`/vendor/laravel-admin/AdminLTE/dist/img/user2-160x160.jpg` 如果不替换这个文件（缺点：更新版本资源后还需再次要替换，不重写 路由 和 Model， 有什么办法 方便的换头像吗？  要不加个配置？

**Comment by z-song** [comment]
可以的  下个版本加个配置
