### ISSUE TITLE
省市区联动问题

### ISSUE THREAD

**Issue by c903494855** [z-song/laravel-admin#2458]
- Laravel Version: #.#.#5.6
- PHP Version:7.2
- Laravel-admin: #.#.#1.5+

### Description:
参照文档里的，在使用省市区联动的时候，出现问题，
![image](https://user-images.githubusercontent.com/24372394/45207359-5d133080-b2ba-11e8-9351-15e0125aec60.png)
有时候能用有时候报错
报错：选择北京、山西省等
![image](https://user-images.githubusercontent.com/24372394/45207397-70260080-b2ba-11e8-9857-2c02e8e74e63.png)
比如我选择天津市的时候，就好了

**Comment by z-song** [comment]
检查一下接口返回数据的结构
