### ISSUE TITLE
登录系统页面会提示:The page has expired due to inactivity. 

### ISSUE THREAD

**Issue by Orocker** [z-song/laravel-admin#2459]
- Laravel Version: 5.6.35
- PHP Version:7.2.10
- Laravel-admin: v1.5

使用其他子账号登录时，有时页面会提示：The page has expired due to inactivity. (419)
本地环境：win7+phpStudy(nginx)
在login.blade.php form加了 @csrf 还是会偶尔出现
@z-song

**Comment by z-song** [comment]
查了一圈貌似是session目录权限的问题，但是我没有遇到过这个问题

**Comment by Orocker** [comment]
> session

但是我验证过了session目录权限是没问题的，然后我把登录的路由写到了verifycsrftoken里面

**Comment by sayhei** [comment]
这个问题还会时不时的出现

**Comment by Orocker** [comment]
@sayhei 我也没有找到解决办法。

**Comment by rootrl** [comment]
@z-song 同出现 1.6版本

**Comment by rootrl** [comment]
跟csrf 有关 我暂时关闭了login的csrf验证

**Comment by rootrl** [comment]
不对，观察了下，这是因为你本地开发项目跟laravel-admin demo 这个项目的cookie冲突有关。

出现这种情况用户大部分都是同一个流程器打开自己开发的项目，然后也打开过laravel-admin demo

所以不需要解决，换个浏览器分别打开这两个项目就可以了

**Comment by sayhei** [comment]
> 不对，观察了下，这是因为你本地开发项目跟laravel-admin demo 这个项目的cookie冲突有关。
> 
> 出现这种情况用户大部分都是同一个流程器打开自己开发的项目，然后也打开过laravel-admin demo
> 
> 所以不需要解决，换个浏览器分别打开这两个项目就可以了

可是我们同事测试的时候也是有这个问题，而且他根本没打开过laravel-admin demo页面

**Comment by rootrl** [comment]
> > 不对，观察了下，这是因为你本地开发项目跟laravel-admin demo 这个项目的cookie冲突有关。
> > 出现这种情况用户大部分都是同一个流程器打开自己开发的项目，然后也打开过laravel-admin demo
> > 所以不需要解决，换个浏览器分别打开这两个项目就可以了
> 
> 可是我们同事测试的时候也是有这个问题，而且他根本没打开过laravel-admin demo页面

好吧，原谅我说的太绝对。那同志们继续观察。。

**Comment by Orocker** [comment]
@rootrl @sayhei 继续加油

**Comment by xiangxihenli** [comment]
登录官方demo也会显示这个错误。

![avtar](https://s1.ax1x.com/2018/12/03/FMdQ1J.md.png)

**Comment by jesse7866** [comment]
可能是cookie冲突了，laravel-admin的官网和demo就不能同时登陆，清除这个网站下的cookie就可以重新登陆了

**Comment by Orocker** [comment]
可以结帖了吗

**Comment by fplun** [comment]
> > 可能是cookie冲突了，laravel-admin的官网和demo就不能同时登陆，清除这个网站下的cookie就可以重新登陆了。
> > 可以修改 `.env` 的`APP_NAME`或cookie作用域
> 
> 亲测可用。

亲测不行

**Comment by MoKaiKwong** [comment]
> > > 可能是cookie冲突了，laravel-admin的官网和demo就不能同时登陆，清除这个网站下的cookie就可以重新登陆了。
> > > 可以修改 `.env` 的`APP_NAME`或cookie作用域
> > 
> > 
> > 亲测可用。
> 
> 亲测不行

在\resources\views\errors\419.blade.php 文件上加上 <script> location.href = '/admin'</script>
完美解决

**Comment by yljphp** [comment]
> <script> location.href = '/admin'</script>

还是不行

**Comment by yljphp** [comment]
遇到这个问题了

**Comment by parse-dinghua** [comment]
因为用了pjax，切换一直没有更新 csrf token，token 时间到了再有 post 提交就会提示过期

**Comment by baliejian** [comment]
> 不对，观察了下，这是因为你本地开发项目跟laravel-admin demo 这个项目的cookie冲突有关。
> 
> 出现这种情况用户大部分都是同一个流程器打开自己开发的项目，然后也打开过laravel-admin demo
> 
> 所以不需要解决，换个浏览器分别打开这两个项目就可以了
赞！
亲测换个浏览器就可以了。
**我的情况是同域名不同端口，实际为：**
本地已登录127.0.0.1:1000的一个测试站，当再在同一浏览器登录另一个测试网站127.0.0.1:1001后，即造成了冲突。
**测试成功解决方案1**
关闭退出其中一个测试站，另一个网站正常使用后台；
**测试成功解决方案2**
新开一个浏览器，或同一浏览器新开一个无痕模式打开另一个网站，两个网站全部正常运行

**Comment by baliejian** [comment]
亲测换个浏览器就可以了。

**我的情况是同域名不同端口，实际为：**
本地已登录127.0.0.1:1000的一个测试站，当再在同一浏览器登录另一个测试网站127.0.0.1:1001后，即造成了冲突。
**测试成功解决方案1**
关闭退出其中一个测试站，另一个网站正常使用后台；
**测试成功解决方案2**
新开一个浏览器，或同一浏览器新开一个无痕模式打开另一个网站，两个网站全部正常运行

**Comment by WalkingNormal** [comment]
- 我的环境是什么样的？

nginx 转发的

- 我是如何解决这个问题的？

在 `.env` 文件中增加以下配置
`SESSION_DOMAIN=false`

---
希望能帮到一些人
