### ISSUE TITLE
[HELP] Return collection eloquent in $grid 

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#246]
In $grid->relation() can return collection eloquent ?

[http://120.26.143.106/admin/sakila/films](url)

```
$grid->categories()->value(function ($categories) {
  $categories = can be a collection eloquent ? 
});
```

**Comment by edwinhuish** [comment]
try..... and you can see...

**Comment by z-song** [comment]
@taimaiduc  It can not.

But you can use  `Model::hydrate()` method to turn the array into collection of eloquent model.

**Comment by taimaiduc** [comment]
@z-song @edwinhuish 
Thanks for support me a lot.
