### ISSUE TITLE
Roles list issue

### ISSUE THREAD

**Issue by newtekDev** [z-song/laravel-admin#2460]
- Laravel Version: 5.6.3
- PHP Version: 7.2.5
- Laravel-admin: 1.5.*

### Description:
When I go to `/admin/auth/roles`
I see this error:
```
BadMethodCallException In Macroable.php line 99 :
Method Illuminate\Support\Collection::label does not exist.
```

**Comment by z-song** [comment]
Can't reproduce your issue

**Comment by siavashgolabi** [comment]
I have the same problem with user list edit page.
When I go to /admin/auth/users/{id}/edit
I see this error:

    ErrorException In Macroable.php line 100 :

    Method Illuminate\Database\Eloquent\Collection::getKey does not exist.
