### ISSUE TITLE
header 和 description 一直显示 1，如图所示

### ISSUE THREAD

**Issue by Yunlong2cn** [z-song/laravel-admin#2461]
- Laravel Version: 5.7.*
- PHP Version:7.1.2
- Laravel-admin: 1.5.*

### Description:
<img width="209" alt="1" src="https://user-images.githubusercontent.com/1751219/45252262-30c4e600-b386-11e8-9940-d468ae406117.png">
经验证，将 content.blade.php 中的 or 修改为 ?? 即可，如图
<img width="654" alt="2" src="https://user-images.githubusercontent.com/1751219/45252263-391d2100-b386-11e8-96f1-e53242c9c7f6.png">
结果，如图
<img width="362" alt="3" src="https://user-images.githubusercontent.com/1751219/45252268-41755c00-b386-11e8-9632-f4389d8651e1.png">

**Comment by z-song** [comment]
在最新的版本里面已经修复了

**Comment by langeuh** [comment]
@z-song is the admin compatible with laravel 5.6 or 5.7? if so, i might upgrade and help out again

**Comment by z-song** [comment]
> @z-song is the admin compatible with laravel 5.6 or 5.7? if so, i might upgrade and help out again
> 
> PS: a changelog.md would be REALLY helpful

Yes ,compatible.

Change log is here http://laravel-admin.org/docs/#/en/change-log
