### ISSUE TITLE
BelongsTo relation not work

### ISSUE THREAD

**Issue by runfan** [z-song/laravel-admin#2462]
- Laravel Version: 5.6.*
- PHP Version:7.1
- Laravel-admin: 1.5.19

### Description:
when store
Illuminate\Database\Query\Builder::getForeignKeyName does not exist.

### Steps To Reproduce:

``` php
class User extends Model
{
    public function profile()
    {
        return $this->hasOne(Profile::class);
    }
}

class Profile extends Model
{
    public function user()
    {
        return $this->belongsTo(User::class);
    }
}

Admin::grid(Profile::class, function (Grid $grid) {

    $grid->id('ID')->sortable();
    $grid->name();
    $grid->column('user.email');
    $grid->column('user.password');
    $grid->created_at();
    $grid->updated_at();
});

```
save failed with error 
```
Illuminate\Database\Query\Builder::getForeignKeyName
```
when use BelongsTo User should saved before Profile but code in *Form* , relation is after model save.

**Comment by runfan** [comment]
table Profile has field user_id

**Comment by runfan** [comment]
# replenish
the relation class **BelongsTo** don't have a function named ** getForeignKeyName**, it is only getForeignKey

**Comment by runfan** [comment]
#1708 is the same issue

**Comment by z-song** [comment]
@runfan @Romerski Fixed, updated to `dev-master` or wait for the next release.

**Comment by runfan** [comment]
Thank you.
it looks fine when  field _user_id_ in table _Profile_  is _nullable_.
but if _user_id_  is not null
 https://github.com/z-song/laravel-admin/blob/e066b123af7c18af2cbfcbe36b66a35addf62c7f/src/Form.php#L341
it will throw an error when model->save(),  because of _Profile_->_user_id_  is null.

**Comment by runfan** [comment]
@z-song
