### ISSUE TITLE
如何在grid里面的display调用关联模型而不产生N+1的问题？

### ISSUE THREAD

**Issue by sampanhuang** [z-song/laravel-admin#2463]
- Laravel Version: 5.5.40
- PHP Version: 7.1.1
- Laravel-admin: 1.5.X

### Description:
事先我已经加上了这个
`$grid->model()->with('belongsToType');`
在列中加入了其他关联模型
`$grid->column('belongsToType.name','类型');`
可是在其他列的调用中
```php
$grid->column('name','姓名')->display(function ()  {
        return $this->belongsToType->code . $this->name;
});
```
这个时候会因为在display中调用了关联模型，而产生N+1问题，他在里面又会重新查询一遍
可是我之前已经预加载了啊，是不是因为使用了闭包的原因？
请问要如何避免在display里面不产生N+1的问题？

**Comment by z-song** [comment]
提交了修复，你可以更新到`dev-master`或者等下一个版本发布
