### ISSUE TITLE
建议：grid允许单独在上下扩展行

### ISSUE THREAD

**Issue by daguye918** [z-song/laravel-admin#2466]
我们做电商系统。比较常会需要做一些价格或者订单相关统计，例如周订单金额汇总，实际营收统计这块。。目前的实现方式是grid在筛选之后。自己再从url去取参数自己查询统计一边。在grid外单独增加一块区域来展示统计结果。所以个人建议grid是否可以增加在头部或者底部添加一块区域的方法，如：addHeader(),然后可以通过类似筛选一样，对数据做汇总计算。设置自己想要计算的字段。将结果传递到想要展示的view当中去。

**Comment by wangwenfan** [comment]
这个需求的确实用，我们做游戏也会用到

**Comment by z-song** [comment]
@daguye918 @wangwenfan 提交了一个commit，可以实现的你需求，比如有一个字段foo，你要获取sum的结果显示在表格的底部
```php
$grid->footer(function ($query) {
    $total = $query->sum('foo');

     // 渲染你的视图
    return view('你的视图', compact('total'));
});
```
更新到`dev-master`或者等下一个版本使用

**Comment by daguye918** [comment]
耐斯~正是我想要的样子！十分感谢~

**Comment by bravist** [comment]
视图，这样写：https://github.com/z-song/laravel-admin/issues/879#issuecomment-310622220
