### ISSUE TITLE
how to save model

### ISSUE THREAD

**Issue by setsrl** [z-song/laravel-admin#2467]
- Laravel Version: 5.7.2
- PHP Version: 7.2.9
- Laravel-admin: 1.5.19

Hi there,

I successfully created my own model Game, and controller using admin:make command, then I added these routes:

$router->get('games', 'GameController@index');
$router->get('games/create', 'GameController@create');

but when I click submit, how to save the model? which route to add and where to save?

thanks a lot

**Comment by Romerski** [comment]
You need `store` action but you can use `resource ` method to handle variety of actions.

`$router->resource('games', 'GameController');`

https://laravel.com/docs/5.6/controllers#resource-controllers

**Comment by setsrl** [comment]
great, thanks a lot!
