### ISSUE TITLE
mongodb 查询

### ISSUE THREAD

**Issue by BackStBoy** [z-song/laravel-admin#2469]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.x

### Description:
数据库 created_at 字段类型: date

![image](https://user-images.githubusercontent.com/28390158/45290409-1758a100-b522-11e8-95f1-6ce36a4569ab.png)
查询条件 created_at 类型:string
![image](https://user-images.githubusercontent.com/28390158/45290454-33f4d900-b522-11e8-8872-177c19a8510d.png)

导致我现在查询不到数据

### Steps To Reproduce:
我该怎么做，才能解决这个问题。

**Comment by z-song** [comment]
参考这个问题 #1515 自定义一个过滤器，在condition方法里面构建你的查询

**Comment by BackStBoy** [comment]
好的，非常感谢

**Comment by ajiader** [comment]
能贴下代码吗 我也遇到这个问题
