### ISSUE TITLE
foreign id render

### ISSUE THREAD

**Issue by setsrl** [z-song/laravel-admin#2470]
- Laravel Version: 5.7.2
- PHP Version: 7.2.9
- Laravel-admin: 1.5.19

Hello,
I have 2 models with a one to many relationship, which renders with a input box with a plus and a minus buttons, like in the attachment
<img width="268" alt="screen shot 2018-09-10 at 12 19 32" src="https://user-images.githubusercontent.com/42962198/45291932-d47fd480-b4f3-11e8-938f-9af6937c7f84.png">
, to set external id. Is it possible to renderer it with a dropdown with the name instead of id?
thanks a lot

**Comment by z-song** [comment]
It's better to use a `select` field to list all relation parents as options
