### ISSUE TITLE
hasMany() 问题

### ISSUE THREAD

**Issue by BackStBoy** [z-song/laravel-admin#2476]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
User Model 
![image](https://user-images.githubusercontent.com/28390158/45358918-97076e00-b5fd-11e8-96bb-64466336ae2b.png)
 
Advertisings  Model
![image](https://user-images.githubusercontent.com/28390158/45358941-a981a780-b5fd-11e8-98b6-81509d770589.png)

AdvertisingsController
![image](https://user-images.githubusercontent.com/28390158/45358982-c74f0c80-b5fd-11e8-9085-c5d71bdce005.png)

输出数据
![image](https://user-images.githubusercontent.com/28390158/45359036-e483db00-b5fd-11e8-94a8-fe7f36b3578b.png)

是我写错了，还是有bug。。。

**Comment by jxlwqq** [comment]
try this:
```php
$grid->User()->nickname('发布人');
```
see more: 
http://laravel-admin.org/docs/#/zh/model-grid?id=%E5%85%B3%E8%81%94%E6%A8%A1%E5%9E%8B

**Comment by BackStBoy** [comment]
还是不行

**Comment by BackStBoy** [comment]
> try this:
> 
> ```
> $grid->User()->nickname('发布人');
> ```
> 
> see more:
> http://laravel-admin.org/docs/#/zh/model-grid?id=%E5%85%B3%E8%81%94%E6%A8%A1%E5%9E%8B

还是不行。

**Comment by z-song** [comment]
@BackStBoy 方法名用小写

**Comment by BackStBoy** [comment]
> @BackStBoy方法名用小写

改了小写没起作用

**Comment by jxlwqq** [comment]
@BackStBoy 看看 Laravel Eloquent 一对多的文档，是不是 foreign_key 或者 local_key 之类的参数写错了。

**Comment by BackStBoy** [comment]
$grid->column('发布人')->display(function () {
         $user = $this->users()->first();
         return $user->nickname;
});

这种可以
