### ISSUE TITLE
Retrieve Data from other table

### ISSUE THREAD

**Issue by emadrashad** [z-song/laravel-admin#2478]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
Hi , i have used Multi select input to display genres of movies , the author can select multiple genres for a movie , am storing them in movies table as an array of ids using Mutators and accessors , the way you guide us , how to display the names of these genres in the listing of movies 

-- what i mean is that storing and updating info using multi select (  $form->multipleSelect() ) is working great , but what about displaying in the grid ? 

###  Screen shot 
![screenshot-127 0 0 1-8000-2018 09 11-16-35-53](https://user-images.githubusercontent.com/16463475/45367297-35390b00-b5e1-11e8-8fbb-199bf5a2a1d4.png)

**Comment by emadrashad** [comment]
@z-song if you can have a look

**Comment by z-song** [comment]
@emadrashad Show me your model and grid code?

**Comment by emadrashad** [comment]
@Romerski  thanks man actually you way helped me a lot and worked , but the result is like the following 
![screenshot](https://user-images.githubusercontent.com/16463475/45488439-b3242000-b761-11e8-8e3c-9021886d06b2.png)


and here is my model implementaiton 

`
class Movie extends Model
{
    use SoftDeletes;


    protected $casts = [

    	'multiple_images' => 'json' ,
    	'genres'          => 'json' , 

    ];

    public function setPicturesAttribute($multiple_images)
	{
	    if (is_array($multiple_images)) {
	        $this->attributes['multiple_images'] = json_encode($multiple_images);
	    }
	}

	public function getPicturesAttribute($multiple_images)
	{
	    return json_decode($multiple_images, true);
	}


	public function setGenresAttributes($genres){

		if(is_array($genres)){

			// do your encoding
			$this->attributes['genres'] = json_encode($genres) ; 
		}
	}

	public function getGenresAttributes($genres){

		return json_decode($genres , true) ; 

	}

 




}
`

thanks

**Comment by omarfci2010** [comment]
hi @emadrashad ,
how you  storing and updating info using multi select ( $form->multipleSelect() ) ?
when click to edit the old data not showing.
can you help me to show old data in update form?
