### ISSUE TITLE
列表页面使用多个grid后，翻页不起作用了，而且点击后面的tab会跳到第一个tab里

### ISSUE THREAD

**Issue by guyaofei** [z-song/laravel-admin#2480]
列表页面使用多个grid后，翻页不起作用了，而且点击后面的tab会条到第一个tab里
![1536724920 1](https://user-images.githubusercontent.com/30075084/45401565-c8c31800-b683-11e8-8271-ae503f1a4387.png)。

**Comment by guyaofei** [comment]
现在用的是1.5.12的

**Comment by guyaofei** [comment]
是因为版本的原因吗，现在用的是1.5.12
![Uploading 1536737512(1).png…]()   @z-song

**Comment by z-song** [comment]
你的版本不支持一个页面多个grid，更新到最新，然后`$grid->setName('xxx');`区分开多个grid

**Comment by guyaofei** [comment]
但是我更新到最新版后会报错，关于tab的错误
![1536747330 1](https://user-images.githubusercontent.com/30075084/45418760-e3af7f80-b6b7-11e8-8ea4-17d7d6326b8b.png)

@z-song

**Comment by z-song** [comment]
运行一下`artisan view:clear`

**Comment by z-song** [comment]
无回复  先关了

**Comment by extralam** [comment]
Grid paging not work even setName. 
Paging work only when

comment Grid/Model.php line 481
//        if (isset($paginate['arguments'][0])) {
//            return $paginate['arguments'];
//        }

I dont know any bad effect now.

**Comment by extralam** [comment]
還有的是， filtering OR paging 不能話返回原來的Tab
現在我只能用cookie 處理.

$('a[data-toggle="tab"]').on('shown.bs.tab', function (e) {
  var target = $(e.target).text();
  createCookie("current_tab",target);
});
