### ISSUE TITLE
添加动态路由之后发现不起作用。直接404只要带了动态参数就找不到

### ISSUE THREAD

**Issue by jackwangshukai** [z-song/laravel-admin#2481]
- Laravel Version: #.#.#
- PHP Version: 7.1
- Laravel-admin: #.#.#

### Description:

    $router->get('{$id}/MedicineDataLog/createNew/', function($id){
        return "99";
    });

**Comment by z-song** [comment]
`{$id}`改为`{id}`试试

**Comment by jackwangshukai** [comment]
恩改成{id}可以了谢谢
