### ISSUE TITLE
laravel-admin批量插入数据的问题

### ISSUE THREAD

**Issue by Orocker** [z-song/laravel-admin#2482]
- Laravel Version: 5.6.32
- PHP Version:7.2
- Laravel-admin: 1.5
我有一个问题textarea框，通过换行符分隔开，有几个换行就向数据库插入几天记录，怎么实现呢，可以在$form->saving方法里面出来吗？

@z-song

**Comment by z-song** [comment]
laravel-admin不支持，但是通过模型的creating事件应该是可以的，你自己多尝试一下
