### ISSUE TITLE
建议，给字段ID加上表名

### ISSUE THREAD

**Issue by Nash-x9** [z-song/laravel-admin#2486]
- Laravel Version: 5.5.28
- PHP Version: PHP7.2
- Laravel-admin: 1.5.*

### Description:
如果有两个表单，这两个表单的表拥有相同的字段名时，提交会异常。
![file](https://lccdn.phphub.org/uploads/images/201809/13/28711/tIpVdrtXLt.png?imageView2/2/w/1240/h/0)QQ20180913-152443@2x.png

**Comment by xiaomlove** [comment]
你是说一个页面有多个表单吗？

**Comment by Nash-x9** [comment]
> 你是说一个页面有多个表单吗？

是的。当多表单有字段名一样的时候，他们dom的id 都是一样的，这样不科学，而且一个表单输入内容，另一个不输入，提交的时候，会把输入表单的内容赋值给未输入的表单对应的相同字段。我猜测是dom id的锅。

**Comment by NoobCai** [comment]
有临时解决办法吗？

**Comment by jxlwqq** [comment]
`->alias()` 用这个函数试试行不行。

**Comment by Nash-x9** [comment]
> > `->alias()` 用这个函数试试行不行。
> 
> `hasMany`里面的`Form\NestedForm`没有这个函数，而且是存有数据的不会覆盖，但是数据如果为空的会用同字段名的数据填充

尝试给ID加了表名，但是这里简单的把column和id混为一个概念了。导致name 和id一致，提交还是有问题

**Comment by Nash-x9** [comment]
@z-song 审一下这样处理是否可行。
/vendor/encore/laravel-admin/src/Form/Field.php Line:228
`    public function __construct($column, $arguments = [])
    {
        $this->id = $this->formatId($column);
        $column = array_get(explode('-',$column),1);
        $this->column = $column;
        $this->label = $this->formatLabel($arguments);

    }`
/vendor/encore/laravel-admin/src/Form.php Line:1507
`public function __call($method, $arguments)
    {
        if ($className = static::findFieldClass($method)) {
            $column = array_get($arguments, 0, ''); //[0];

            $element = new $className($this->model->getTable().'-'.$column, array_slice($arguments, 1));

            $this->pushField($element);

            return $element;
        }

        admin_error('Error', "Field type [$method] does not exist.");

        return new Field\Nullable();
    }`
@NoobCai 可以看看我这个临时解决方案
