### ISSUE TITLE
重写了store和update方法，怎么让form方法里面的验证规则生效

### ISSUE THREAD

**Issue by Orocker** [z-song/laravel-admin#2487]
- Laravel Version: 5.6.35
- PHP Version:7.2
- Laravel-admin: v1.5

**Comment by xiaomlove** [comment]
这个不好搞吧，本身是一套的。为何要重写，saving()回调也不能解决问题么？

**Comment by Orocker** [comment]
> 这个不好搞吧，本身是一套的。为何要重写，saving()回调也不能解决问题么？

我的业务逻辑比较复杂，用自带的saving方法实现不了，

**Comment by Orocker** [comment]
> @Orocker @xiaomlove 提交了一个修改 [fd74056](https://github.com/z-song/laravel-admin/commit/fd74056ed732a4805f557bf3099fed7dcff16c29)
> 
> 之后可以调用form对象的validationMessages方法获取验证错误信息
> 
> ```
> if ($validationMessages = $form->validationMessages($data)) {
>     return back()->withInput()->withErrors($validationMessages);
> }
> ```

怎么在store方法获取到验证的对象呢，就是 $form->validationMessages($data)) 里面的$data
