### ISSUE TITLE
Show Builder XSS漏洞

### ISSUE THREAD

**Issue by Nash-x9** [z-song/laravel-admin#2490]
- Laravel Version: 5.5
- PHP Version: PHP 7.2
- Laravel-admin: 1.6.0

### Description:
经测试，Show 直接将用户的输入值展示了出来，把原来laravel 自带的转义给去掉了。带来了XSS漏洞，grid正常。

<img width="735" alt="qq20180913-190443 2x" src="https://user-images.githubusercontent.com/12541919/45484885-45d7b580-b788-11e8-8608-3ae991ca700c.png">
<img width="1088" alt="qq20180913-190758 2x" src="https://user-images.githubusercontent.com/12541919/45484915-5ab44900-b788-11e8-9b9d-b82827d6af7b.png">

**Comment by z-song** [comment]
欢迎pr

**Comment by TrojanMa** [comment]
有处理方案吗
