### ISSUE TITLE
新版本中控制器创建Grid新写法不传递回调导致export()方法不可用

### ISSUE THREAD

**Issue by xiaomlove** [z-song/laravel-admin#2491]
- Laravel Version: 5.7.2
- PHP Version: 7.1.9
- Laravel-admin: 1.6.0

### Description:
新生成的控制器直接$grid = new Grid(new Model())，然后在下边为grid添加字段信息。这时候调用$grid->export()设置exporter不可用。

### Steps To Reproduce:

- 使用admin:make创建控制器
- 在grid()方法返回$grid之前调用$grid->export(new XXXExporter())设置自定义导出类
- 结果没有用到自定义的类，还是默认的CSVExporter

导出这样的结果是之前旧写法传递了回调，Grid中有builder属性，在[setupExporter()](https://github.com/z-song/laravel-admin/blob/master/src/Grid.php#L213)时会运行一次builder设置导出类，新写法Grid初始化没有传递builder，自然无法设置导出类，而导出操作就是在初始化Grid时进行的。

**Comment by z-song** [comment]
@xiaomlove 确实有这个问题，已经修复，更新到`dev-master`或者等下个版本

**Comment by richer0718** [comment]
这个 怎么修复呢，，之前写的都废掉了 跪等跟新

**Comment by z-song** [comment]
这个问题已经修复  更新到最新版本
