### ISSUE TITLE
filter 查询

### ISSUE THREAD

**Issue by BackStBoy** [z-song/laravel-admin#2495]
- Laravel Version: 5.6.*
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:

$filter->text('user_id', '用户id');
数据库mongodb ，字段类型是int，经过测试，int可以查，但上面这个是string类型的，我该怎么修改，谢谢您@z-song
怎么才能使user_id  为int类型

**Comment by z-song** [comment]
参考 #1515，  自己定义一个filter，继承`Encore\Admin\Grid\Filter\Equal`，修改condition方法修改数据的类型

**Comment by BackStBoy** [comment]
过滤器
public function condition($inputs)
{
        $value = array_get($inputs, $this->column);

        if (!isset($value)) {
            return;
        }

        $this->value = (int)$value;

        return $this->buildCondition($this->column, '=', $this->value);
}
调用
$grid->filter(function ($filter) { 
        $filter->use(new MongodbEqual('user_id','用户id'));
        $filter->disableIdFilter();
});
