### ISSUE TITLE
怎么在Tab组件里添加表单并且添加和修改数据

### ISSUE THREAD

**Issue by Baiyongjian** [z-song/laravel-admin#2501]
- Laravel Version: 5.5.42
- PHP Version:PHP/7.0.12
- Laravel-admin: 1.5

### Description:
我想在我的每一个tab里增加一个表单。并且单独的创建和修改操作。请问用api里说的tab怎么能实现。

**Comment by Baiyongjian** [comment]
> 更新版本，新在版本的里面有`$tab->addLink($title, $href, $active = false)`方法来给标签添加一个链接，你把不同的形式写到不同的页面然后用addLink添加进选项卡，这样几个形式就分开了

哦哦哦。 谢谢你， 我去试一下

**Comment by nkjackzhang** [comment]
> 
> 
> 更新版本，在新的版本里面有`$tab->addLink($title, $href, $active = false)`方法来给tab添加一个链接，你把不同的form写到不同的页面然后用addLink添加进tab，这样几个form就分开了

这个addLink没有设置content的地方，下面怎么添加form呢？要是有个content的参数就好了，我是在原来的add方法最后自己添加了一个url参数，默认为空，用这个参数判断是跳转新页面并在tab下面显示内容，还是在同一页面切换tab
