### ISSUE TITLE
error occurs when using together with dingo api

### ISSUE THREAD

**Issue by lubobill1990** [z-song/laravel-admin#2509]
- Laravel Version: 5.6.28
- PHP Version:7.1.13
- Laravel-admin: 1.6.1

### Description:
![image](https://user-images.githubusercontent.com/641540/45600437-3cbc4200-ba2f-11e8-943a-1828a1d86807.png)

### Steps To Reproduce:
Install dingo api, then this error will occur.

No error when using 1.5.14

**Comment by z-song** [comment]
按照报错到相关文件里面debug一下，贴出更详细信息

**Comment by lubobill1990** [comment]
好的，我试一下
