### ISSUE TITLE
更新不到最新版本， 中国镜像源的问题

### ISSUE THREAD

**Issue by feistiny** [z-song/laravel-admin#2510]
packagist的源不是最新的了， 换用laravel-china的源可以
```bash
composer config repo.packagist composer https://packagist.laravel-china.org
```

下边是具体过程， 有兴趣的可以看一下
准确来说这不是一个issue
但是只有在中国使用composer源的人才会碰到这样的问题
更新不到最新版本，使用`composer show encore/laravel-admin --all`时，没有显示最新的几个版本
其实可以用`composer update encore/laravel-admin -vvv`会显示源的json文件
```bash
Reading /root/.cache/composer/repo/https---packagist.laravel-china.org/provider-encore$laravel-admin.json from cache
```
`composer clear-cache`删除缓存

再udpate会重新下载这个json文件，可以格式化json查一下，里边确实没有最新的几个版本，应该推测出来是源的问题
还是应该根据现有的的线索推测问题，盲目的尝试只会徒劳无获
如果有人知道这样的说明应该提交在哪里，请指出，我也会不断的学习，谢谢

**Comment by z-song** [comment]
国内好多人在用https://pkg.phpcomposer.com/这个镜像， 已经两个月没更新了

**Comment by bihantan** [comment]
现在我已经弃用这个镜像用代理了，没办法
