### ISSUE TITLE
修改操作时文件无法预览,请问如何修改文件目录

### ISSUE THREAD

**Issue by canon1014** [z-song/laravel-admin#2515]
- Laravel Version: 5.5.40
- PHP Version:7.1.13
- Laravel-admin: 1.5

### Description:
修改操作时文件上传无法预览, 文件名和文件没有问题,F12 文件目录错误;
请问如何修改预览目录

**Comment by canon1014** [comment]
![image](https://user-images.githubusercontent.com/39935301/45671536-3d042c80-bb58-11e8-8464-39766902df30.png)

**Comment by z-song** [comment]
检查一下`config/filesystem.php`里面的`admin`disk配置

**Comment by donglianyou** [comment]
Laravel Version: 5.7.*
PHP Version:7.2.9
Laravel-admin: 1.6.1
Description:
表单添加存储图片时报错误！
Encodingformat (tmp) is not supported！
![image](https://user-images.githubusercontent.com/10190223/45673595-b6eae480-bb5d-11e8-82e0-208dc242d0a6.png)

**Comment by canon1014** [comment]
@

> 一下检查`config/filesystem.php`里面的`admin`磁盘配置

感谢,已经好使了
