### ISSUE TITLE
Multiselect form field is empty while editing

### ISSUE THREAD

**Issue by OstrikovG** [z-song/laravel-admin#2517]
- Laravel Version: 5.7.4
- PHP Version: 7.2.0.
- Laravel-admin: 1.6.1

Multiselect form field is empty while editing

### Description:
**form:**
![image](https://user-images.githubusercontent.com/11738030/45702395-6c2b9580-bb7a-11e8-89a0-9313d9fee964.png)
**relations in model:**
![image](https://user-images.githubusercontent.com/11738030/45702735-43f06680-bb7b-11e8-9ae9-bdc9a60968c8.png)
**actual result:**
![image](https://user-images.githubusercontent.com/11738030/45702465-91200880-bb7a-11e8-87e3-a0803ff1b63e.png)

**Comment by mRamadan0101** [comment]
same issue when edit multi select not display

**Comment by JeffcottLu** [comment]
same issue [自定义表格数据源，重写了model的paginate()方法之后，还是展示不出来自定义的数据 · Issue #3370 · z-song/laravel-admin](https://github.com/z-song/laravel-admin/issues/3370)
