### ISSUE TITLE
Model without PrimaryKey Grid Page Open with Error via Pjax

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#2519]
- Laravel Version: 5.7
- PHP Version: 7.1
- Laravel-admin: 1.6

### Description:
When Show Grid with Model without PrimaryKey via Pjax, it would give below error.
![image](https://user-images.githubusercontent.com/6511003/45725747-d120d300-bbee-11e8-928c-9d201e1d3054.png)

### Steps To Reproduce:
Created a View without Primary Key
![image](https://user-images.githubusercontent.com/6511003/45725691-8ef79180-bbee-11e8-9391-40bee2f46a6f.png)

And Create a Grid page with relevant route configure and add a menu for it. When you launch the grid page via menu, which would trigger the pjax to call it. It would give you error as described previous.

**Comment by RobinHoo1973** [comment]
BTW, if yu try to refresh the page or call via javascript window.location.href='url' wouldn't trigger the error.
