### ISSUE TITLE
详情页里面的图片被转义了？

### ISSUE THREAD

**Issue by manzhouya** [z-song/laravel-admin#2520]
按照文档更新到最新的版本。发现详情页图片被转义。

**Comment by z-song** [comment]
建议更新到`v1.6.2`

或者在使用更早的版本的话，用`$show->picture()->image()->setEscape(false);`;

**Comment by manzhouya** [comment]
> 建议更新到`v1.6.2`
> 
> 或者在使用更早的版本的话，用`$show->picture()->image()->setEscape(false);`;

刚找到设置的方法。刚才看好像没有1.6.2版本 ╮(╯▽╰)╭，现在有了
