### ISSUE TITLE
建议：增加登录页验证码模块

### ISSUE THREAD

**Issue by daguye918** [z-song/laravel-admin#2521]
目前来说大多数后端使用用户都觉得要有个验证码比较安全（甲方的需求。不得不做）。相比大多数项目也都是这样。我们自己重写了登录页面跟逻辑。但是实际上这边只是一个验证码的校验逻辑。登录的整个逻辑都是不变的。建议可以在登录页面下面加一些简单的字符验证码或者允许接入滑动验证等。

**Comment by z-song** [comment]
自定义登陆页和登陆两个路由，来覆盖laravel-admin的这两个内置路由，可以很容易的实现你的需求

**Comment by daguye918** [comment]
重写了登录路由跟界面。已实现~
