### ISSUE TITLE
Rules in multipleFile field

### ISSUE THREAD

**Issue by izakruta** [z-song/laravel-admin#2528]
- Laravel Version: 5.6.0
- PHP Version: 7.1.0
- Laravel-admin: last

### Description:

$rules = 'required|mimes:zip';
$form->multipleFile('data', 'Files')->rules($rules);

verification does not work. the form is sent. error messages are not displayed. How to fix it?
Only checking for 'required'

### Steps To Reproduce:

open - new item 
I add a file png 
save item

======================
validate - error
message error - not show

if you use the single file field, then everything is fine.
Multyfile field - only 'required'. The rest is not displayed

**Comment by yurik94** [comment]
Same....

**Comment by yurik94** [comment]
Hey @lukaskris 
Digging in bootstrap input I finally resolved!

```
$form->file('apk', 'APK')
            ->rules('mimes:apk')
            ->options([
                'allowedFileExtensions' => ['apk']
            ])
            ->attribute('accept', '.apk')
            ->required();
```

@z-song Can you please include in docs?
