### ISSUE TITLE
新修复的export [#2491 #2426]，又有新问题，导出文件头部出现<div class="row"><div class="col-md-12">

### ISSUE THREAD

**Issue by tomcoolz** [z-song/laravel-admin#2529]
- Laravel Version: 5.6.34
- PHP Version: 7.2.4
- Laravel-admin: 1.6.1

### Description:
Fix issue #2491 #2426，但导出的文件头部出现`<div class="row"><div class="col-md-12">`

### Steps To Reproduce:
翻了下源码，Encore\Admin\Grid::handleExportRequest() 被执行了2次，应该是第1次时没执行export()输出，然后触发了 Encore\Admin\Layout\Row 和 Encore\Admin\Layout\Column 的 build()。
望优化流程。

**Comment by z-song** [comment]
@tomcoolz 确实有这个问题，提交了修复，更新到`v1.6.3`
