### ISSUE TITLE
[HELP] Grid $grid in relation can not use 2 time ?

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#253]
In $gird relation can use 2 time ? Sorry for asking too much. 

<img width="423" alt="6683c082d5b0b5c0c24f41655a22382a" src="https://cloud.githubusercontent.com/assets/10907980/21548227/bce78494-ce1d-11e6-8c6b-0be0a3f559f7.png">

<img width="1011" alt="e24f169864ea048f9749c1cac7e92dd3" src="https://cloud.githubusercontent.com/assets/10907980/21548231/c4e9689c-ce1d-11e6-8bb2-86bc110ee6f3.png">

<img width="436" alt="a090fe02a816f6d311b3ef21bab4feb4" src="https://cloud.githubusercontent.com/assets/10907980/21548234/d0610662-ce1d-11e6-8094-25c0960a22a5.png">

<img width="1011" alt="013601866d9ec2e1ec372fa670229500" src="https://cloud.githubusercontent.com/assets/10907980/21548266/ecf46404-ce1d-11e6-8de1-9351fc9883ac.png">

**Comment by z-song** [comment]
Form your screenshot, it's a one-to-many relation and you want to show the first `employee`, right ?

Try following code:
```php
$grid->model()->with('employee');

$grid->column('employee_id')->display(function () {
    return $this->employee[0]['id'];
});

$grid->column('employee_name')->display(function () {
    return $this->employee[0]['name'];
});
```

**Comment by taimaiduc** [comment]
Thanks it works. @z-song 
Have you have an email for work? I hope you can help me to understand more laravel-admin

**Comment by z-song** [comment]
@taimaiduc Find it in my profile.
