### ISSUE TITLE
Syntax error or access  violation: 1103 Incorrect table name

### ISSUE THREAD

**Issue by rdtandel** [z-song/laravel-admin#2530]
- Laravel Version: #.#.# Laravel Framework 5.6.38
- PHP Version: PHP Version 7.1.9
- Laravel-admin: #.#.# latest

### Description:
D:\xampp\htdocs\lara-admin>php artisan admin:install

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access
 violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigne
d not null auto_increment primary key, `username` varchar(190) not null, `passwo
rd` varchar(60) not null, `name` varchar(255) not null, `avatar` varchar(255) nu
ll, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at
` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at D:\xampp\htdocs\lara-admin\vendor\laravel\framework\src\Illuminate\Database
\Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll
 format the error
    661|         // message to include the bindings with SQL, which will make th
is exception a
    662|         // lot more helpful to the developer instead of just the databa
se's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

### Steps To Reproduce:
php artisan admin:install

**Comment by taimaiduc** [comment]
Are you have a file `config/admin.php` ?

**Comment by jusyjk** [comment]
> Are you have a file `config/admin.php` ?

Yes i've but showing same error

**Comment by rdtandel** [comment]
> 
> 
> Are you have a file `config/admin.php` ?

yes i have config/admin.php.
the error shows that there may be table name missing in migration file but there is no issue like that.

**Comment by taimaiduc** [comment]
I think we missing config on somewhere. @z-song

**Comment by rdtandel** [comment]
tried again from scratch. and now working fine for me.

**Comment by sunkeyfong** [comment]
seems like config cache problem,  just try "php artisan config:cache" to clear cache.

**Comment by VICIWUOHA** [comment]
Thank you @sunkeyfong , you were right. I had the same issue today on my laravel project and `"php artisan config:cache"` worked for me.

**Comment by tendomart** [comment]
Thanks Guys   " php artisan config:cache " worked for me as well. i don't usually ike Github solutions but , this has worked almost instantly.

**Comment by xxnjdlys** [comment]
Thanks Guys " php artisan config:cache " worked for me as well.

**Comment by uchchwas1** [comment]
Thanks. php artisan config:cache worked for me.
