### ISSUE TITLE
php artisan admin:create-user 失败

### ISSUE THREAD

**Issue by ljf1172361058** [z-song/laravel-admin#2536]
- Laravel Version: 5.7
- PHP Version: 7.2.1
- Laravel-admin: 1.6.1

### Description:
php artisan admin:create-user 失败,到 Please enter a username to login: 时输入完成按回车
提示   LogicException  : Choice question must have at least 1 choice available.

### Steps To Reproduce:
php artisan admin:create-user 输入完成后按步骤进行到 Please enter a username to login: 
输入完毕后出现的异常

**Comment by JILeXanDR** [comment]
Check table **admin_roles** it should not be empty

**Comment by Bmariahyvonne** [comment]
My admin_roles was empty and when I did a **php artisan admin:install** command and administrator role was added to the table. after that when I ran a **php artisan admin:create-user**, I managed to create the user successfully without getting the same error.
