### ISSUE TITLE
filter筛选框里面怎么给select设置默认值

### ISSUE THREAD

**Issue by wangwenfan** [z-song/laravel-admin#2537]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
filter筛选框里面怎么给select设置默认值？有这个功能吗
```
  $filter->equal('channel_id', '渠道')->select();//后面加default和options方法都不行
```

**Comment by BackStBoy** [comment]
$filter->use(new MongodbEqual('status','状态'))->select(['1'=>'未付款','2'=>'已付款','3'=>'申诉中','4'=>'已取消','5'=>'交易完成']);

**Comment by lePig** [comment]
#2202

**Comment by nkjackzhang** [comment]
这个没有什么好办法，因为select是否选中是根据url的参数来决定的，blade里用了request($name, $value)判断

**Comment by lePig** [comment]
@nkjackzhang 能贴下部分代码吗？ 我试了`default()`不行

**Comment by nkjackzhang** [comment]
@lePig 你default的给的是数字还是字符串？那个判断条件要求必须是字符串的，数字不行，你看下[这行代码](https://github.com/z-song/laravel-admin/blob/e22186280ed159f1d474bd75e091aef20ffd7050/resources/views/filter/select.blade.php#L4)就清楚该怎么做了，另外你用的什么IDE？用PHPstorm断点调试一下，看看最终组件里的value是多少

**Comment by lePig** [comment]
@nkjackzhang 谢谢。我当时用的也是1.5.14  现在在开发前台项目，后台很久没看了。我放假去调试一下
