### ISSUE TITLE
怎么在form中使用事务？

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#2542]
### Description:

在业务实现中，有些时候需要在提交后对多表进行操作，laravel-admin有提供saveing和saved来处理逻辑，但并无法保证在特殊情况下多个数据操作都能执行通过，想问如何将事务Transaction加入到代码中？

**Comment by nkjackzhang** [comment]
本身表单就是执行事务保存的，而且可以通过model的关系模型保存关联数据，如果需要更复杂的多表操作的话，自己写保存方法吧，里面用DB的事务方法。

**Comment by terranc** [comment]
@nkjackzhang 已经提交了个PR，其实修改很简单，毕竟这种场景很多，不见得一定是关联数据，每个地方都去自己写个保存方法的话，就很大程度失去了用 laravel-admin 的意义吧

**Comment by terranc** [comment]
@nkjackzhang 暂时我这还没遇到这样的场景，因为saving是发生在前的，如果saving需要中断直接抛出错误即可，感觉没什么好回滚的

**Comment by terranc** [comment]
事务的问题现在有好的方案了吗？

**Comment by lisqorz** [comment]
事务的问题现在有好的方案了吗？
