### ISSUE TITLE
"Custom tools"  Failed to import JS file 

### ISSUE THREAD

**Issue by tuine** [z-song/laravel-admin#2543]
### Description:
Model grid ==>"Custom tools"
**The blade file of view that imports JS:**
The first visit to this web page failed to import JS(<script src=></script>), but it's right to load when I refresh the web page.

<script>//js</script> without using src is no problem.

Thanks.

---
**The solution to this problem in  [2550](https://github.com/z-song/laravel-admin/pull/2550).**

**Comment by tuine** [comment]
I'm crazy.....
Report errors when I wrote HTML in JS:
`Uncaught SyntaxError: Invalid or unexpected token`,
Parsing failed.
Same as previous one，It's can work when I refresh the page.

**Comment by tuine** [comment]
**And when I first visit this page,the functions can't parse also.**
![failed](http://www.tuine.me/img/admin_parse_failed.png)

Thanks.

**Comment by taimaiduc** [comment]
Can you show your code ?

**Comment by tuine** [comment]
> Can you show your code ?

All problems have been fixed.Thanks
