### ISSUE TITLE
module tree收起和展开失效

### ISSUE THREAD

**Issue by DamonSnow** [z-song/laravel-admin#2547]
- Laravel Version: 5.5.43
- PHP Version:7.2.4
- Laravel-admin: 1.6.3

### Description:
如题，如菜单页面中点击tree上的展开和收起都没有反应

**Comment by NoobCai** [comment]
试下往边缘的地方点下，别点字，好像是禁止冒泡了

**Comment by Baiyongjian** [comment]
> 试下往边缘的地方点下，别点字，好像是禁止冒泡了

请问怎么设置才能点击文字也能好使，收起和展开功能。另外，tree的保存功能也不好使了， 去官网给的demo看也是不好使的。

**Comment by NoobCai** [comment]
> > 试下往边缘的地方点下，别点字，好像是禁止冒泡了
> 
> 请问怎么设置才能点击文字也能好使，收起和展开功能。另外，tree的保存功能也不好使了， 去官网给的demo看也是不好使的。

点击方法在`\vendor\encore\laravel-admin\src\Tree.php`
```
$('.{$this->elementId}-tree-tools').on('click', function(e){
    var target = $(e.target),
        action = target.data('action');
    if (action === 'expand') {
        $('.dd').nestable('expandAll');
    }
    if (action === 'collapse') {
        $('.dd').nestable('collapseAll');
    }
});
```
把`e.target`改成`this`；

**Comment by jxlwqq** [comment]
@NoobCai 我把span标签给删了也正常了。之前的版本也是没有span标签的。算是恢复到之前的版本。

**Comment by Baiyongjian** [comment]
> @NoobCai我把跨度标签给删了也正常了。之前的版本也是没有跨度标签的。算是恢复到之前的版本。

谢谢你老铁，我的好使了。
