### ISSUE TITLE
如果不想在actions里显示图标，能否给个可以配置的方式

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#2554]
有时候客户比较小白，对于一堆icon其实是不知所以的，看了看源码，好似这块是写死的，要不就全部disabled了自己整，但对于删除这种还附带了confirm交互的每个都去处理就比较麻烦了，希望能提供一个是用icon还是text的选项。

**Comment by v8v** [comment]
可以这样子修改

    // append一个操作
    $actions->append('<a href=""><i class="fa fa-eye"></i></a>');

    // prepend一个操作
    $actions->prepend('<a href=""><i class="fa fa-paper-plane"></i></a>');

**Comment by nkjackzhang** [comment]
目前应该只能disable掉之后自己写，如果重复的地方多就写个公用的方法，需要用到的参数传递进去，反正$this是不能用了

**Comment by terranc** [comment]
如果能提供一个方法/属性可以设置a标签里面的html就好了
