### ISSUE TITLE
How to view the data in other controller in Laravel Admin

### ISSUE THREAD

**Issue by fahmyemyy** [z-song/laravel-admin#2556]
- Laravel Version: 5.7
- PHP Version: 7.2.7
- Laravel-admin: 1.5

### Description: Can someone help to view the data product into the productSeller. The data cant retrieve from the product when i click the action button. The button can pass to the other controller but cant view the data. And the data want view in grid if can. 
![action button](https://user-images.githubusercontent.com/42174050/45937647-a66eba00-bff4-11e8-9d52-cb784372d0df.JPG)
![details](https://user-images.githubusercontent.com/42174050/45937649-aa9ad780-bff4-11e8-8884-c6c3a814806f.JPG)
![extension file](https://user-images.githubusercontent.com/42174050/45937652-acfd3180-bff4-11e8-8909-6447e2563122.JPG)

**Comment by taimaiduc** [comment]
Are you create route `seller/productSeller` ?

**Comment by fahmyemyy** [comment]
> Are you create route `seller/productSeller` ?

yup. but this one for me to set the action button in laravel admin dashboard. The function still pointing in ProductSeller controller.

**Comment by taimaiduc** [comment]
I have been done it by this step.

1. Create a custom route

**Comment by fahmyemyy** [comment]
> I have been done it by this step.
> 
> 1. Create a custom route
> 2. Create custom action if you want.
> 3. Create a function in a controller using form admin.
> 
> Can you try ?

![image](https://user-images.githubusercontent.com/42174050/46052936-1c009480-c173-11e8-9a18-0f2285dbe629.png)

![image](https://user-images.githubusercontent.com/42174050/46052949-2fabfb00-c173-11e8-9459-8e10907cd0d8.png)

![image](https://user-images.githubusercontent.com/42174050/46052962-40f50780-c173-11e8-8cd5-9ad6c85122ae.png)


i have done this. if something wrong can u let me know. sorry im still new
