### ISSUE TITLE
软删除的model，在Form里没办法给model加上withTrashed()

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#2557]
有时候我们在Grid中指定了`model()->withTrashed()`，希望把软删除的内容也一并搜出来，并且软删除掉的也是可以编辑的，可没有找到可以给Form中model指定withTrashed的方法

**Comment by OranTing** [comment]
同样的需求，希望在Form里也可以使用 withTrashed 和 withoutGlobalScopes

**Comment by z-song** [comment]
已经提交了修复，等待下一个版本发布

**Comment by OranTing** [comment]
> 已经提交了修复，等待下一个版本发布

期待新版本

**Comment by dullme** [comment]
我也需要软删除的数据能重新编辑，还有我对数据库title字段设置了唯一unique 但是被软删除了，这时候我需要重新添加回来相同的名字，没办法操作！

**Comment by mi-autumn** [comment]
@dullme 这个还原回去的时候检查下对应字段重复就修改就行了吗..软删除的编辑可以啊.demo里有.

**Comment by ahu** [comment]
@dullme 如需对启用软删除的数据进行 unique 校验时忽略已软删除的数据，使用如下方式：

```
$form->text('username')
    ->creationRules(['required', "unique:user_table,username,NULL,id,deleted_at,NULL"])
    ->updateRules(['required', "unique:user_table,username,{{id}},id,deleted_at,NULL"]);
```

@z-song 大大的文档在 [unique 示例](https://laravel-admin.org/docs/zh/model-form-validation)是这样的：

```
$form->text('username')
    ->creationRules(['required', "unique:user_table"])
    ->updateRules(['required', "unique:user_table,username,{{id}}"]);
```

可以看一下区别:) 希望能帮到更多的人
