### ISSUE TITLE
Call to a member function newFromBuilder() on null

### ISSUE THREAD

**Issue by hungryandfoolishboy** [z-song/laravel-admin#2562]
- Laravel Version: 1.5.*
- PHP Version:>=7.0.0 (7.2.1)
- Laravel-admin: ^1.0

### Description:
emm，我不知道有没有别人遇到同样的问题，总是这个一个非常之坑的问题，如果你在模型的注释上面加上 @mixin \Eloquent 这一行注释，那么vendor\encore\laravel-admin\src\Grid\Column.php::setModel()
就会报错，因为$model instanceof Model 为false，我不知道是因为PHP版本的原因，还是其他什么原因导致的问题。希望遇到同样问题的同学能找到解决方案。也希望开源者能对此进行一些兼容或者优化

**Comment by z-song** [comment]
没有重现你的问题，贴一下代码看看
