### ISSUE TITLE
table 不能设置class属性

### ISSUE THREAD

**Issue by uyson** [z-song/laravel-admin#2564]
- Laravel Version: 5.6
- PHP Version:7.2
- Laravel-admin: 1.5

table 不能设置class属性

**Comment by z-song** [comment]
`Encore\Admin\Widgets\Table`吗？

试试
```php
$table->class('table custom-class');
```

**Comment by qianfunian** [comment]
@z-song 请教下grid 表格行的属性怎么设置？谢谢
