### ISSUE TITLE
1.6.1版导出功能异常

### ISSUE THREAD

**Issue by hezhiying** [z-song/laravel-admin#2567]
- Laravel Version: 5.7.1
- PHP Version: 7.1.19 
- Laravel-admin: 1.6.1

### Description:
导出功能异常，如果注释掉 `src/Grid.php 182` 行 `$this->handleExportRequest`则正常

### Steps To Reproduce:
![1](https://user-images.githubusercontent.com/16780849/46064102-0dc96d00-c1a1-11e8-9de5-5631236a6ece.jpg)
![2](https://user-images.githubusercontent.com/16780849/46064104-0e620380-c1a1-11e8-918e-3680b0cd376d.jpg)

**Comment by z-song** [comment]
这个问题已经修复了，更新到`1.6.3`

**Comment by hezhiying** [comment]
尝试过多次安装最新1.6.3还是同样的问题，麻烦再看下
![3](https://user-images.githubusercontent.com/16780849/46122942-35c2da00-c24e-11e8-8f0b-83cbbf782ffb.png)
![4](https://user-images.githubusercontent.com/16780849/46122947-42dfc900-c24e-11e8-8e91-532c2cc3df30.png)

**Comment by z-song** [comment]
已经提交了修复，等下一个版本发布，或者先更新到`dev-master`版本

ps 下次如果遇到问题可以尝试自己解决并提交pr
