### ISSUE TITLE
问下框架里上传的视频特别大，一直失败，框架里有分片上传的功能吗

### ISSUE THREAD

**Issue by guyaofei** [z-song/laravel-admin#2569]
问下框架里上传的视频特别大，一直失败，框架里有分片上传的功能吗

**Comment by guyaofei** [comment]
laravel_admin中我是使用框架自带的file方法进行上传图片直接上传到OSS，但是视频太大的话报错

**Comment by guyaofei** [comment]
在laravel-admin里将大视频上传到OSS上需要修改那些配置文件吗

**Comment by z-song** [comment]
没有这个功能
