### ISSUE TITLE
Command "admin:extend" is not defined

### ISSUE THREAD

**Issue by hqin2013** [z-song/laravel-admin#2571]
- Laravel Version: 5.5.28
- PHP Version: 7.1 
- Laravel-admin: dev-master

### Description: 
测试扩展开发：http://laravel-admin.org/docs/#/zh/extension-development
运行命令：
php artisan admin:extend laravel-admin-ext/phpinfo --namespace=Encore\\PHPInfo

提示：
 ```
Command "admin:extend" is not defined.

  Did you mean one of these?
      admin:import
      admin:install
      admin:make
      admin:menu
      admin:uninstall
```

**Comment by z-song** [comment]
更新到1.6以上的版本

**Comment by hqin2013** [comment]
> 更新到1.6以上的版本

现在库里面的版本只有到1.5，指定1.6以上 更新失败

**Comment by z-song** [comment]
@hqin2013 检查你设置的composer镜像

**Comment by jxlwqq** [comment]
教程：https://laravel-china.org/wikis/16722
