### ISSUE TITLE
Embeds Form field not working when inserting data

### ISSUE THREAD

**Issue by AlexTherzyan** [z-song/laravel-admin#2572]
- Laravel Version: 5.7
- PHP Version: 7.1.*
- Laravel-admin: 1.6

### Description:
If I set Embeds fields
`  return Admin::form(Setting::class, function (Form $form) {
              $form->embeds('content', function (Form\EmbeddedForm $form) {
                  $form->text('extra1')->rules('required');
              });
        });
`
When I saved as creating, column "value" is null, but when I saved as updating, column "value" is saveing as json
my form code:
`
class Setting extends Model
{
    protected $fillable = ['content'];
    protected $casts = [
        'content' => 'json',
    ];
}
`
in database my field  type text
How to reslove this?

**Comment by AlexTherzyan** [comment]
the problem was solved by adding callback function, but it's not very good

` $form->saving(function (Form $form)   {

                 $content =  \request()->get('content');
                 $form->model()->content = $content ;

             });`

**Comment by RobinHoo1973** [comment]
Hope this could solved officially!

**Comment by peacemoon** [comment]
Agree, this should be solved officially. @z-song
