### ISSUE TITLE
请问如何获取上传的文件大小，并保存到数据库中？

### ISSUE THREAD

**Issue by donglianyou** [z-song/laravel-admin#2574]
- Laravel Version: 5.7.5
- PHP Version:7.2.9 
- Laravel-admin: 1.6.2

### Description:
请问如何获取上传的文件大小，并保存到数据库中？
有自带的什么方法嘛？

**Comment by z-song** [comment]
给文件大小的字段加一个hidden的field, 然后在saving回调中，获取到文件的大小，赋值给这个字段
