### ISSUE TITLE
Call to a member function delete() on null

### ISSUE THREAD

**Issue by RomanGatchenko** [z-song/laravel-admin#2581]
- Laravel Version:  5.6.38
- PHP Version: 7.2.0
- Laravel-admin: 1.6.3

### Description:
If the record of table was deleted when the "only trashed" filter was turned on, when trying to permanently delete the record, we get an error:

> Call to a member function delete() on null

> exception: "Symfony\Component\Debug\Exception\FatalThrowableError"
> file: "D:\OSPanel\domains\chronos\vendor\encore\laravel-admin\src\Form.php"
> line: 284
> message: "Call to a member function delete() on null"

**Comment by z-song** [comment]
Fixed, will be available in the next version
