### ISSUE TITLE
开发一个扩展，请问如何将路由注入到前台页面访问，而不是后台页面访问

### ISSUE THREAD

**Issue by BEIBEI123** [z-song/laravel-admin#2586]
比如我开发一个博客扩展，希望有后台设置和前台访问，我看了扩展开发文档，router/web.php下面访问的是 http://www.test.com/admin/blog 的形式来设置后台数据，请问如何做到 http://www.test.com/blog 
 形式来访问前台？只有能开发前台页面，可扩展开发能能力才会加大，比如开发一个博客插件或cms插件等等，这样一个插件直接作为一个应用运行了,类似拥有laravel-modules的功能

**Comment by z-song** [comment]
@BEIBEI123 要设置前台路由，就用Laravel的路由机制来设置就好了，不要局限在文档描述的范围里面

比如在扩展的ServiceProvider里面：
```php
class PHPInfoServiceProvider extends ServiceProvider
{
    public function boot(PHPInfo $extension)
    {

        ...

        // 设置前台路由
        $this->app['router']->get('/test', function () {
            return 'test';
        });
    }
}

```
然后就可以在前台访问了`http://localhost/test`

**Comment by BEIBEI123** [comment]
这样的确可以实现，但如果能集中到router下面甚至web.php下面就最好了
