### ISSUE TITLE
Cannot delete items because of JS error

### ISSUE THREAD

**Issue by vladkucherov** [z-song/laravel-admin#2590]
- Laravel Version: 5.6
- PHP Version: 7.1
- Laravel-admin: 1.5

### Description:
Error is thrown when delete modal is opened, and delete is not happening because of that:
`Uncaught TypeError: Cannot read property 'then' of undefined`

Happens because of this code in `Tree.php` line 262 and `Actions.php` line 210
```
$('.tree_branch_delete').click(function() {
    var id = $(this).data('id');
    swal({
        title: "$deleteConfirm",
        type: "warning",
        showCancelButton: true,
        confirmButtonColor: "#DD6B55",
        confirmButtonText: "$confirm",
        showLoaderOnConfirm: true,
        cancelButtonText: "$cancel",
        preConfirm: function() {
            return new Promise(function(resolve) {
                $.ajax({
                    method: 'post',
                    url: '{$this->path}/' + id,
                    data: {
                        _method:'delete',
                        _token:LA.token,
                    },
                    success: function (data) {
                        $.pjax.reload('#pjax-container');

                        resolve(data);
                    }
                });
            });
        }
    }).then(function(result) { <-------------
        var data = result.value;
        if (typeof data === 'object') {
            if (data.status) {
                swal(data.message, '', 'success');
            } else {
                swal(data.message, '', 'error');
            }
        }
    });
});
```
Can't tell why it fails, probably related to `Sweetalert`.
could be because versions of the lib changed?

### Steps To Reproduce:

1. Try to delete either through Tree or Grid
2. modal shows up
3. error is thrown (see console)
4. hit OK
5. modal closed, item not deleted, request not sent to server

**Comment by z-song** [comment]
Sweatalert updated to Sweatalert2 since `v1.6.0`

You may need to run `php artisan vendor:publish --tag=laravel-admin-assets` to repulish the assets.

**Comment by vladkucherov** [comment]
Thanks, helped
