### ISSUE TITLE
省市区联动问题

### ISSUE THREAD

**Issue by zhushiqiang** [z-song/laravel-admin#2592]
- Laravel Version: 5.5.28
- PHP Version:7.2.5
- Laravel-admin: 1.5.*

### Description:
![image](https://user-images.githubusercontent.com/17295335/46251895-68f5ab00-c492-11e8-80cf-57031b830caf.png)
![image](https://user-images.githubusercontent.com/17295335/46251906-8aef2d80-c492-11e8-8a7f-551b789403de.png)
省市区联动在提交后， 回显感觉有点bug ，代码参照您的demo 写的。城市与区县会没有数据，且点击已经选中的省份也会无 相应

**Comment by z-song** [comment]
建议更新到`v1.6`, 用这个插件https://github.com/laravel-admin-extensions/china-distpicker

**Comment by zhushiqiang** [comment]
考虑到省市区数据 需要经常维护，所以数据需要存到数据库当中，所以这个差件用不到了。已经更新到v1.6

**Comment by z-song** [comment]
这个插件的省市区数据是基于国家统计局发布的数据,  数据字典可以下载到，比如https://github.com/eduosi/district

**Comment by zhushiqiang** [comment]
这个bug有时间您会修复吗，还是这个不是bug？

**Comment by sayhei** [comment]
> 建议更新到`v1.6`, 用这个插件https://github.com/laravel-admin-extensions/china-distpicker

这个插件只能用在form里耶
