### ISSUE TITLE
寻找代码定义

### ISSUE THREAD

**Issue by Cishanduwang** [z-song/laravel-admin#2597]
- Laravel Version: 5.6
- PHP Version:7.2
- Laravel-admin: 1.5.x-dev

### Description:
请问App\Admin\Controllers\xxxxController@destroy
App\Admin\Controllers\xxxxController@show
App\Admin\Controllers\xxxxController@update
在那个文件中定义的？

**Comment by z-song** [comment]
看一些这个controller引入的trait
