### ISSUE TITLE
multiselect filter feature - do you think it's possible to have something like this in the future ?

### ISSUE THREAD

**Issue by mberende** [z-song/laravel-admin#26]
in many enterprise apps you need to filter by a many to many relation - that would generate a sql like:

SELECT
  personID
FROM
  people_to_sports
WHERE
  sportID IN (1, 2)
GROUP BY
  personID
HAVING
  COUNT(*) = 2

Do you something like this could be done sometime in the future ?

**Comment by z-song** [comment]
Now can use a `where` filter to handle complex queries

https://github.com/z-song/laravel-admin/blob/master/docs/en/model-grid.md#add-query-filters
