### ISSUE TITLE
如何限制表单上传文件的大小

### ISSUE THREAD

**Issue by CanonNr** [z-song/laravel-admin#2605]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5

### Description:
想限制表单中文件上传的文件或图片大小,因为在文档中没有找到类似介绍所以提问,感谢各位前辈

### Steps To Reproduce:
$form->file("xx",trans("xx"))->uniqueName()->move('xx')->rules('mimes:pdf');

**Comment by CreationLee** [comment]
> 我自己在上传图片时限制图片文件尺寸以及大小时的限制是这样写的，你可以参考下：
> 
> `$form->image('headimage','Head Image')->uniqueName()->move($path)->rules('required|dimensions:min_width=300,min_height=300;|max:2048');`

请问在多图上传的时候怎么解决呢

**Comment by Cuifc** [comment]
> > 我自己在上传图片时限制图片文件尺寸以及大小时的限制是这样写的，你可以参考下：
> > `$form->image('headimage','Head Image')->uniqueName()->move($path)->rules('required|dimensions:min_width=300,min_height=300;|max:2048');`
> 
> 请问在多图上传的时候怎么解决呢

使用->options(['maxFileSize' => 1024])
