### ISSUE TITLE
Admin went down went upgrading laravel to 5.7

### ISSUE THREAD

**Issue by alpharameeztech** [z-song/laravel-admin#2606]
- Laravel Version: 5.7
- PHP Version: 7.2
- Laravel-admin: 1.5

### Description:
I have tried upgrading to laravel 5.7 but the admin went down with a lot of errors.
What the heck guys.

**Comment by t-perm** [comment]
Are you install a new fresh laravel admin ?

**Comment by smunir** [comment]
Shouldn't you try with laravel-admin 1.6. But as per docs, only laravel 5.5 is supported.

**Comment by fhferreira** [comment]
Is it possible? use Laravel 5.7 and Laravel admin?

**Comment by smunir** [comment]
I upgraded to laravel 5.7 with laravel-admin 1.6.5 around 2 weeks ago, faced a few errors but found quick fixes from google, everything is working fine. please visit https://laravel.com/docs/5.7/upgrade also

**Comment by fhferreira** [comment]
@smunir do you have an FORK with your fixes?

**Comment by uacode** [comment]
I just updated laravel. I do not observe problems with laravel-admin
