### ISSUE TITLE
无法更新到1.5.18版本以上

### ISSUE THREAD

**Issue by sayhei** [z-song/laravel-admin#2608]
- Laravel Version: 5.5.*
- PHP Version:
- Laravel-admin: 1.5.15

### Description:
在执行更新操作时，报了如下错误
 Problem 1
    - The requested package encore/laravel-admin ^v1.6 exists as encore/laravel-admin[1.1.x-dev, 1.2.x-dev, 1.3.x-dev, 1.4.x-dev, 1.5.x-dev, dev-analysis-8AvKDk, dev-analysis-q14nMj, dev-develop, dev-master, v1.1.6, v1.2.10, v1.2.6, v1.2.8, v1.2.9, v1.3.3, v1.3.4, v1.4.1, v1.4.4, v1.4.5, v1.4.6, v1.5.10, v1.5.11, v1.5.12, v1.5.13, v1.5.14, v1.5.15, v1.5.5, v1.5.6, v1.5.7, v1.5.8, v1.5.9] but these are rejected by your constraint.

**Comment by jxlwqq** [comment]
https://laravel-china.org/wikis/16722
