### ISSUE TITLE
[HELP] GET current user login in Middleware

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#261]
Hi guy, how can i get current user in Middleware
```php
<?php

namespace App\Http\Middleware;

use Closure;

class CheckUploadImageBackend
{
    public function handle($request, Closure $next, $role= NULL)
    {
      dd(\Auth::guard('admin')->user());
        if (auth()->check() && auth()->user()->hasRole($role)) {
            return $next($request);
        }

        return redirect('login');
    }
}
```

**Comment by smuzammilali** [comment]
Have you found any solution?

I like to update the config('filesystems.disks.local.root') as per login users.

For example:
filesystems.disks.local.root = public_path(\Auth::guard('admin')->user()->username);

How can I achieve that do you have any idea?
