### ISSUE TITLE
动态添加的form表单,插入不到数据库中

### ISSUE THREAD

**Issue by fplun** [z-song/laravel-admin#2610]
$form->saving()里面可以获取到,
到$form->saved()里面,用form->model()->item就获取不到了,数据库里面也没有

**Comment by fplun** [comment]
> 只会插入你在form里面定义的字段

收到,谢谢回复,我是绑定select用ajax实现的动态添加form表单,加到了id='tab-form-2'里面,因为添加产品的话,分类不一样,产品属性也不一样,并且特别多的属性,不想每次手动填写,请问下有什么更好的实现方式吗

**Comment by fplun** [comment]
> 只会插入你在form里面定义的字段

我可以在saved里面用request获取到这些数据,然后在回调里面updateOrcreate(['id' => $form->model()->id], ['item' => request()->item]),这样会有什么影响吗

**Comment by nkjackzhang** [comment]
你是动态添加的表单field吧，比如动态添加一个输入框什么的，因为ModelForm里的store()只会使用你自己定义的form()方法返回的表单里的字段，额外的属性可以在saving里设置到model里来保存。

**Comment by fplun** [comment]
> 你是动态添加的表单field吧，比如动态添加一个输入框什么的，因为ModelForm里的store()只会使用你自己定义的form()方法返回的表单里的字段，额外的属性可以在saving里设置到model里来保存。

嗯,现在我在saved里面实现了,saving里面获取不到当前id啊,然后还有别的表里面需要插入的东西,一并写在saved里面了,因为我写的是embed,内嵌的,可能还会需要多图,所以我在框架里面把form最后一个验证也取消了,不知道会不会有啥影响
![image](https://user-images.githubusercontent.com/38807395/46775406-b1865180-cd39-11e8-9cf8-4fb601755249.png)

**Comment by nkjackzhang** [comment]
> 
> 
> > 你是动态添加的表单field吧，比如动态添加一个输入框什么的，因为ModelForm里的store()只会使用你自己定义的form()方法返回的表单里的字段，额外的属性可以在saving里设置到model里来保存。
> 
> 嗯,现在我在saved里面实现了,saving里面获取不到当前id啊,然后还有别的表里面需要插入的东西,一并写在saved里面了,因为我写的是embed,内嵌的,可能还会需要多图,所以我在框架里面把form最后一个验证也取消了,不知道会不会有啥影响
> ![image](https://user-images.githubusercontent.com/38807395/46775406-b1865180-cd39-11e8-9cf8-4fb601755249.png)

你本来的需求是想实现form的model是一张表，多图是另外一张表，只是用嵌套form插入多图？那何不用一对多表单？$form->hasMany，可以关联保存多图的。saved不是事务操作，不太安全。

**Comment by fplun** [comment]
> > > 你是动态添加的表单field吧，比如动态添加一个输入框什么的，因为ModelForm里的store()只会使用你自己定义的form()方法返回的表单里的字段，额外的属性可以在saving里设置到model里来保存。
> > 
> > 
> > 嗯,现在我在saved里面实现了,saving里面获取不到当前id啊,然后还有别的表里面需要插入的东西,一并写在saved里面了,因为我写的是embed,内嵌的,可能还会需要多图,所以我在框架里面把form最后一个验证也取消了,不知道会不会有啥影响
> > ![image](https://user-images.githubusercontent.com/38807395/46775406-b1865180-cd39-11e8-9cf8-4fb601755249.png)
> 
> 你本来的需求是想实现form的model是一张表，多图是另外一张表，只是用嵌套form插入多图？那何不用一对多表单？$form->hasMany，可以关联保存多图的。saved不是事务操作，不太安全。

我本来想的是把主要信息存一张表,一些属性信息存到另外一张表,用hasMany,但是hasMany好像不支持多图,另外那些属性信息也是动态的,不一定有多少个,实在想不到办法了,所以目前只是用embeds内嵌了,把一个商品的全部属性用json存在一个字段里面,我知道这样很不好,现在还在想解决办法

**Comment by fplun** [comment]
> > > 你是动态添加的表单field吧，比如动态添加一个输入框什么的，因为ModelForm里的store()只会使用你自己定义的form()方法返回的表单里的字段，额外的属性可以在saving里设置到model里来保存。
> > 
> > 
> > 嗯,现在我在saved里面实现了,saving里面获取不到当前id啊,然后还有别的表里面需要插入的东西,一并写在saved里面了,因为我写的是embed,内嵌的,可能还会需要多图,所以我在框架里面把form最后一个验证也取消了,不知道会不会有啥影响
> > ![image](https://user-images.githubusercontent.com/38807395/46775406-b1865180-cd39-11e8-9cf8-4fb601755249.png)
> 
> 你本来的需求是想实现form的model是一张表，多图是另外一张表，只是用嵌套form插入多图？那何不用一对多表单？$form->hasMany，可以关联保存多图的。saved不是事务操作，不太安全。

我现在想我可不可以这样
Schema::table('goods_sepc', function (Blueprint $table) {
    $table->string($form->name);
});
添加属性的时候在回调里面添加字段;
然后就可以一对一的添加属性了

**Comment by xiaoxuan6** [comment]
动态form表单你怎么添加的？我使用append报错，能给个案例吗？

**Comment by fplun** [comment]
> 动态form表单你怎么添加的？我使用append报错，能给个案例吗？

我自己写的js添加的,select改变的时候发送ajax请求, $('#tab-form-2').append(data);

**Comment by xtzeng** [comment]
有更好的解决办法吗，用json存的话
