### ISSUE TITLE
Can the delete button be hidden when creating roles?

### ISSUE THREAD

**Issue by tuine** [z-song/laravel-admin#2615]
### Description:
![image](https://user-images.githubusercontent.com/9445048/46712337-25b1ee00-cc83-11e8-81c4-ae8edd94c56d.png)

Can the delete button be hidden when creating roles?

**Comment by z-song** [comment]
Fixed in b6a9dc0b6874b95227cb44226f74d89e4098f95d,  wait for next release

**Comment by tuine** [comment]
Thanks
