### ISSUE TITLE
filter筛选导出Excel的关联表错误

### ISSUE THREAD

**Issue by a1165203522** [z-song/laravel-admin#2618]
- Laravel Version: #.#.#
5.6
- PHP Version:
7.1
- Laravel-admin: #.#.#
1.5
- Laravel-excel 
2.1
### Description:
export导出列表数据的时候因为有一些附加的 关联表查询
导致filter中的created_at 筛选导出EXCEL的时候出现错误：Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous
有什么办法自定义可以去掉这个created_at的筛选条件么？然后再addFilter一个新的条件

![image](https://user-images.githubusercontent.com/12092664/46731051-421e4c80-ccbc-11e8-8452-a12fcd3a52ae.png)
![image](https://user-images.githubusercontent.com/12092664/46732015-df7a8000-ccbe-11e8-8d0d-818881f824cf.png)

**Comment by a1165203522** [comment]
@z-song 
$filter->where()是单个文本框的自定义查询条件，
但我需要$filter->between()->datetime()  的时间区间查询
有没有办法通过类似这种：$filter->between('created_at','创建时间')->datetime()->where(function($query,$params){
    return $grid->where('created_at','>',$params[0]);
})

**Comment by z-song** [comment]
提供另外一个思路，你尝试一下，自定义一个类继承Between
```php

class CustomBetween extends \Encore\Admin\Grid\Filter\Between
{
    // 覆盖这个方法
    public function condition($inputs)
    {
        //  在这个方法里面修改一下$this->column，带上表名
    }
}

```

然后在grid中使用这个自定义的类
```php
$filter->use(new CustomBetween)->datetime();
```

**Comment by a1165203522** [comment]
![image](https://user-images.githubusercontent.com/12092664/46781001-0d5cd480-cd52-11e8-89fa-9de57078c530.png)
嗯 用这个办法临时解决了！thks
