### ISSUE TITLE
[FILE] Can not crop image upload.

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#262]
Dear guys I try to crop image and got issues

```$form->image("thumb","Thumbnail")->crop(800,600,1,1);```

![screenshot-localhost 8000-2017-01-03-22-11-16](https://cloud.githubusercontent.com/assets/10907980/21611934/99bc09a8-d201-11e6-982d-70d7ce01f550.png)

```
    /*
     * Laravel-admin upload setting.
     */
    'upload'  => [

        'disk' => 'public',

        'directory'  => [
            'image'  => 'images',
            'file'   => 'files',
        ],

        'host' => 'http://localhost:8000/',
    ],
```

```
 'public' => [
    'driver' => 'local',
    'root' => public_path(),
    'visibility' => 'public',
    ],
```

**Comment by z-song** [comment]
`laravel-admin` use `intervention/image` to handling and manipulation images, which does not support crop tmp format images.

Images in `tmp` format is not supported by `intervention/image`.

**Comment by taimaiduc** [comment]
That mean I can not crop image?
How to crop image by your code ?
```
$form->image($column[, $label])->move($dir, $name);

// Crop picture
$form->image($column[, $label])->crop(int $width, int $height, [int $x, int $y]);

// Add a watermark
$form->image($column[, $label])->insert($watermark, 'center');
```

**Comment by z-song** [comment]
`tmp format images`
