### ISSUE TITLE
$grid使用中，editable的问题

### ISSUE THREAD

**Issue by Cheng-Lun** [z-song/laravel-admin#2621]
- Laravel Version: 5.5
- PHP Version:7.1.16
- Laravel-admin: 1.5.dev

### Description:
在使用列的扩展时，遇到一个问题。
`$grid->column('value','设置值')->editable('text');`
列表页就可以编辑了，但是这个地方是对该模型的value字段的update。我现在想实现，在点击确定后，能向表单提交一样，进行回调（saved()）操作，把这个更新的数据，写入日志表中。
value字段存在于setting表
目的：保存后回调，把数据存到setting_log日志表

**Comment by z-song** [comment]
在列表修改不是运行saved回调吗？

**Comment by Cheng-Lun** [comment]
主要是想问怎么实现在列表修改，表与表之间没有关联字段，操作其它表的字段。
editable在修改成功后，怎么把这个修改的存到另外表的字段中去

**Comment by z-song** [comment]
还是没明白你的意思，修改了一个表，要把修改存到另外一张表？ 两张表之间没有关联关系？

**Comment by z-song** [comment]
找laravel官方文档， eloquent model events 了解一下

**Comment by mini443** [comment]
> 使用editable点击确定按钮后，我想对其他表做操作，可以实现么？比如：点击确定后，我想写一条记录到日志表中去。

可以在saving里面操作啊
