### ISSUE TITLE
Help me please !!!

### ISSUE THREAD

**Issue by lbernardocu** [z-song/laravel-admin#2628]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: last

### Description:
Hello friends. The question is that I have the classic inheritance in my system. I have a table called people and one that inherits from it called clients. Using the model-form I only manage to save the data from the client table but I do not know how to intervene the method so that I save some data in the table people. Please, I need your help with some examples. Thanks in advance

**Comment by anhhuy2000** [comment]
Laravel Version: 5.6
PHP Version: 7.2
Laravel-admin: 1.6

Hi guys,

I would like to pass data to a view under **Content->row(function($row){**

Normally, it is like this to pass data to view
$users = $this->userRepository->all();
return view('users.index')->with('users', $users);

How could I pass the data into the Content like below?
return $content
            ->header($title = 'Visitor Profile')
            ->description('Data Entry')
            ->row(function ($row) {                
                $row->column(3, function (Column $column) {
                    **$profile_image = view('admin.visitor.profile')->with('users', $users);**                    
                    $summary = view('admin.visitor.summary');
                    $column->append($profile_image);
                    $column->append($summary);
                });
                $row->column(9, function (Column $column) {
                    $main = view('admin.visitor.main');
                    $column->append($main);
                });
            });   

I tried to pass the $contacts variable in the **row** function like this (assume $contacts is defined)
return $content
            ->header($title = 'Visitor Profile')
            ->description('Data Entry')
            ->row(function ($row, **$contacts**) { 
and I have this error below
**Too few arguments to function App\Admin\Controllers\DataEntryController::App\Admin\Controllers\{closure}(), 1 passed and exactly 2 expected**

Many thanks
Alan
