### ISSUE TITLE
form 表单多图上传rules 起作用但不显示错误提示

### ISSUE THREAD

**Issue by usergao** [z-song/laravel-admin#2630]
- Laravel Version: 5.6.25
- PHP Version: 7.1.16
- Laravel-admin: 1.5

### Description:
form 表单多图上传时，设定的 rules 验证起作用，但是 提示信息不显示到表单上来，只是会不停的回到编辑页面

### Steps To Reproduce:

表单多图上传代码：

`$form->multipleImage('path','图片')->move($path)->removable()->rules('required|dimensions:min_width=600,min_height=400;|max:2048');`

我在 `encore\laravel-admin\src\Form.php` 文件中的：

![image](https://user-images.githubusercontent.com/19534860/46847215-c89a7180-ce15-11e8-9c70-5ba3608bb1aa.png)

方法里打印 $message 时输出：

![image](https://user-images.githubusercontent.com/19534860/46847227-d5b76080-ce15-11e8-8156-3f5d5dba72b6.png)

好像提示信息去找字段名为 path0 的字段了，而我设置的字段为 path，这导致它无法将提示信息显示在正确的字段，请问下这个改怎么解决？

**Comment by jourdon** [comment]
同样遇到这个问题。。。

**Comment by usergao** [comment]
最后因为赶时间，就没有使用表单验证了，问题也没有解决，只是换了种方式实现需求。

**Comment by jourdon** [comment]
我直接放弃了，还是前后端分离写起来舒服

**Comment by iyueshang** [comment]
我也遇到了  这样的问题

**Comment by songlen** [comment]
我也遇到了同样的错误，图片这里的问题是真多，多的薅头发！！！
