### ISSUE TITLE
自定义excel导出无效

### ISSUE THREAD

**Issue by aogg** [z-song/laravel-admin#2633]
![image](https://user-images.githubusercontent.com/8998031/46902991-2788e500-cf01-11e8-9d1e-c63040164e4d.png)
![image](https://user-images.githubusercontent.com/8998031/46903044-1096c280-cf02-11e8-9543-5a1d00a1189f.png)

这时候调用实例化grid的时候，还没有赋值就已经调用export了，而且也不能通过不赋值builder来跳过，因为builder是protected

_Originally posted by @aogg in https://github.com/z-song/laravel-admin/issues/2426#issuecomment-429521206_

**Comment by nkjackzhang** [comment]
第一行不是判断是否设置了_export_参数吗？如果没有设置这个参数，应该不会导出的

**Comment by aogg** [comment]
> 第一行不是判断是否设置了_export_参数吗？如果没有设置这个参数，应该不会导出的

你点击导出的时候就带有这个参数。
当然是不影响正常列表功能，是影响正常导出功能

**Comment by nkjackzhang** [comment]
> 
> 
> > 第一行不是判断是否设置了_export_参数吗？如果没有设置这个参数，应该不会导出的
> 
> 你点击导出的时候就带有这个参数。
> 当然是不影响正常列表功能，是影响正常导出功能

他这个写法和老版的方法是类似的，都是call_user_func($this->builder, $this);这一行就设置了grid的值，然后才导出的，老版的可以正常使用，怎么会影响到导出功能而且还是没有给grid设值呢？

**Comment by z-song** [comment]
现在是自定义导出不正常吗？我测试过没有问题啊？

**Comment by aogg** [comment]
> 现在是自定义导出不正常吗？我测试过没有问题啊？

不太清楚你是怎么测试的，如果没问题，就在demo.laravel-admin.org实现下吧，谢谢

**Comment by aogg** [comment]
@nkjackzhang 
对象是值引用的
按java的理解也是可以的（ps：没学过java）

**Comment by z-song** [comment]
> 还有麻烦完善下，demo代码中自定义导出类
> 现在只有类库，没有调用

调用就是文档里面写的 `$grid->exporter(new ExcelExporter());`

你有什么问题先贴一下报错

**Comment by 77zealous** [comment]
最近我也出了同样的问题,之前的版本是1.5.19,升级到1.6.3之后自定义导出失效,一直为默认导出的csv;已在laravel-admin的论坛贴了代码 http://discuss.laravel-admin.org/d/328-excel

**Comment by nkjackzhang** [comment]
> 
> 
> @nkjackzhang
> 对象是值引用的
> 按java的理解也是可以的（ps：没学过java）

你一开始说的是对的，我一开始理解错了，以为你说的赋值是说exporter里面的grid的赋值问题。
实际上自定义exporter确实没有生效，因为先调用new Exporter($this)->resolve，导致给出来的$exporter实际上是默认的csvexporter，因为resolve的时候还没有给grid设置自定义exporter。

**Comment by z-song** [comment]
@aogg @nkjackzhang @77zealous 已经提交了修复，是因为1.6之后构建grid使用了新语法
```php
$grid = new Grid(new Model);

return $grid;
```
这和原来使用闭包构建方式执行流程不一样，更新到v1.6.5
