### ISSUE TITLE
Tab Display without HTML Tag Escape

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#2634]
- Laravel Version: 1.6
- PHP Version: 7.1
- Laravel-admin: 1.6

### Description:
Target to display the tab with icon like below screenshot first tab, but it displayed as the second one, which escaped all html tags.
![image](https://user-images.githubusercontent.com/6511003/46905288-fa016300-cf23-11e8-9242-c4c37169f6a0.png)

### Steps To Reproduce:

$tabs= new Tab();
$tabs->add('<i class="fa fa-user"></i>Users','test');

**Comment by lihe6666** [comment]
same problem.
