### ISSUE TITLE
HasMany BUG 与建议

### ISSUE THREAD

**Issue by edwinhuish** [z-song/laravel-admin#264]
首先感谢 @z-song 松大的开源。

在使用 HasMany 的时候，发现当 NEW 一个 Nested form 的时候，会出现类似如下的问题，或者是 JS 无反应，或者点击 JS 触发两个不同form，特别是新建的form。
![image](https://cloud.githubusercontent.com/assets/5207925/21617863/1df4b370-d223-11e6-95cf-b10ced5fde79.png)

粗略研究过源码，发现很多触发 JS 的selector 仅仅是 class，而由于新建form的class一致，而导致出现各种冲突。

个人觉得，理应为每个form设定一个id，然后通过form再找对应的field，如 $(#form_1 .select2) ...

另外，感觉NestedForm写得非常绕，也很繁琐，对于eloquent来说，据我所知，仅仅需要提交所有数据，它会根据有没有id的情况进行更新/插入操作。

仅属抛砖引玉，不知 @z-song 有何高见？

**Comment by z-song** [comment]
目前为止`NestedForm`是整个项目最复杂的一块，提交的时候要对老数据更新、删除，对新数据要添加，还要对所有的数据做验证和预处理。

这一块还有待完善，我还没有测试所有的form组件。

**Comment by edwinhuish** [comment]
@z-song 感觉不用这么复杂吧，更新和添加就交给 eloquent，删除的话，顶多做一个循环，判断对应id是否存在，没有就删除。

数据的验证和预处理貌似跟之前的一样。

**Comment by z-song** [comment]
@edwinhuish @langeuh issue fixed!
