### ISSUE TITLE
OpenStreetMap

### ISSUE THREAD

**Issue by rez1dent3** [z-song/laravel-admin#2641]
Hey. Do you plan to support OpenStreetMap?

**Comment by z-song** [comment]
Any demo or screenshots？

**Comment by rez1dent3** [comment]
https://wiki.openstreetmap.org/wiki/OpenLayers_Simple_Example
https://www.openstreetmap.org/

PS, free map

**Comment by rez1dent3** [comment]
The first version is ready, but there are many problems.
https://github.com/bavix/laravel-admin-leaflet
