### ISSUE TITLE
Wrong namespace using admin:make

### ISSUE THREAD

**Issue by alberto-bottarini** [z-song/laravel-admin#2642]
- Laravel Version: 5.7
- PHP Version: 7.1
- Laravel-admin: 1.6

### Description:
If I use admin:make command, I get a `use App\Http\Controllers\Controller;`

### Steps To Reproduce:
- change namespace in config/admin.php
- run admin:make command

**Comment by z-song** [comment]
How you changed `config/admin.php`?

**Comment by alberto-bottarini** [comment]
I'm speaking about
`admin.route.namespace configuration`. 

I write on it my custom namespace.

It is used properly for generated controller namespace but there are some problem about 
`use App\Http\Controllers\Controller;`

Maybe you need 2 configuration, one for generated controller and one for BaseController

**Comment by z-song** [comment]
The controllers in admin uses `App\Http\Controllers\Controller` as the BaseController by default.
