### ISSUE TITLE
在gird的自定义方法中怎么调用到当前行的其他数据？

### ISSUE THREAD

**Issue by StringKe** [z-song/laravel-admin#2645]
- Laravel Version: 5.6
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
![image](https://user-images.githubusercontent.com/31089228/46994245-3c09ef00-d146-11e8-92b4-fbcd6ba32de3.png)
红框的地方想要调用到当前这行数据的 ID 改如何操作呢？
我看了文档和demo但是没有找到不知道是不是眼拙了

**Comment by z-song** [comment]
updateBalance是你写的行扩展吗？

**Comment by StringKe** [comment]
是的，是用来更新这个余额的

**Comment by StringKe** [comment]
![image](https://user-images.githubusercontent.com/31089228/46996812-82fce200-d150-11e8-941b-e69b3ec9255c.png)
![image](https://user-images.githubusercontent.com/31089228/46996825-885a2c80-d150-11e8-9dd0-c4fb4f79bc05.png)

**Comment by z-song** [comment]
就是想在getApiMoney的display方法里获取当前行的id对吧？

getApiMoney继承了AbstractDisplayer，你要的数据到AbstractDisplayer里面找找看

**Comment by StringKe** [comment]
已经解决，谢谢
自定义跳用同行数据
 $this->row
