### ISSUE TITLE
使用embeds时编辑带有图片的数据时(图片不改变),提交后图片字段会被置空

### ISSUE THREAD

**Issue by mi-autumn** [z-song/laravel-admin#2646]
- Laravel Version: 5.5.40
- PHP Version:7.1.14
- Laravel-admin: 1.6.1

### Description:
使用embeds时编辑带有图片的数据时(图片不改变),提交后图片字段会被置空

**Comment by fplun** [comment]
保存回调前判断原数据试试

**Comment by chensongah** [comment]
see [1024](https://github.com/z-song/laravel-admin/issues/1024)
