### ISSUE TITLE
动态form，实现方案

### ISSUE THREAD

**Issue by sayhei** [z-song/laravel-admin#2648]
根据某个字段的值显示不同的输入框，可以像下图所示可以添加一个append方法
<img width="965" alt="2018-10-16 3 44 39" src="https://user-images.githubusercontent.com/8320880/47000244-6ebde280-d15a-11e8-9c84-e07b720ea427.png">

**Comment by sayhei** [comment]
看到同样的问题，不过我看作者没有写的计划，[#735](https://github.com/z-song/laravel-admin/issues/735)

**Comment by sayhei** [comment]
作者的建议是自己实现，这是自定义逻辑，但是自己实现的话需要自定义field，还有需要自定义验证，因为条件出现字段可能是必填或者其他验证规则，所以还是希望作者可以考虑下这个需求

**Comment by xiaoxuan6** [comment]
我用1.4 、1.5版本都不执行啊？你是用的那个

**Comment by jzblog** [comment]
同求此功能

**Comment by 307118593** [comment]
为什么我append报错呢

**Comment by YuCoLabKenny** [comment]
求此功能 可以分享嗎 @sayhei

**Comment by maojindao55** [comment]
append的方法有了吗？

**Comment by yinchuanjiang** [comment]
求此功能 可以分享嗎 @sayhei
