### ISSUE TITLE
Login not working

### ISSUE THREAD

**Issue by smunir** [z-song/laravel-admin#2649]
- Laravel Version: 5.5.*
- PHP Version: 7.0.29
- Laravel-admin: 1.6### 
Description:
Unable to login on localhost laravel-admin

### Steps To Reproduce:
1. Create Laravel 5.5.* project atcla and change db config (wamp environment)
2. Follow Laravel-admin installation steps
3. No provider was added in app.php, added Encore\Admin\AdminServiceProvider::class manually (tested without this too)
4. Run admin:install
5. Access login page at http://localhost/atcla/public/admin/auth/login
6. Attempt to login redirects to http://localhost/admin/auth/login. Manually tried to edit this url but nothing is working

**Comment by smunir** [comment]
Figured something out and gave a shot with vHost entry using DocumentRoot "${INSTALL_DIR}/www/atcla/public". App worked but still I shouldn't always have to use vhost, right?

**Comment by nkjackzhang** [comment]
> 
> 
> Figured something out and gave a shot with vHost entry using DocumentRoot "${INSTALL_DIR}/www/atcla/public". App worked but still I shouldn't always have to use vhost, right?

Please read [laravel doc](https://laravel.com/docs/5.5),  which said :

> After installing Laravel, you should configure your web server's document / web root to be the public directory. The index.php in this directory serves as the front controller for all HTTP requests entering your application.
