### ISSUE TITLE
如果需要对提交的表单数据进行验证和业务操作有对应的方法吗

### ISSUE THREAD

**Issue by jungege520** [z-song/laravel-admin#265]
表单提交的数据需要做一些业务上的操作，有没有对应的方法。

**Comment by z-song** [comment]
如果是数据验证，已经有文档说明了

其它的业务操作，可否详细举例？

**Comment by jungege520** [comment]
数据验证主要对于提交的参数来校验，业务操作主要是对提交过来的数据，写入到哪些表，触发哪些事件等等，就像你现在提交了post请求，我想通过获取过来的参数来做一个数据库操作

**Comment by z-song** [comment]
用内置的`model-form`会自动处理数据的保存、更新操作。

如果在保存、更新操作之后还有其它的业务要处理，可以参考 #286 下面的代码，在保存回调中假如你的其它业务逻辑。
