### ISSUE TITLE
FontAwesome 

### ISSUE THREAD

**Issue by rez1dent3** [z-song/laravel-admin#2651]
- Laravel Version: 5.7.x
- PHP Version: 7.2.x
- Laravel-admin: 1.6.1

### Description:
How to remove font awesome 4? I want to replace it with font awesome 5.

**Comment by z-song** [comment]
Just replace the files under `public/vendor/laravel-admin/font-awesome` with font awesome 5.

**Comment by RobinHoo1973** [comment]
It would not work as the class name changed a lot, even the icon in filed coming with the admin package wouldn't display properly

**Comment by rez1dent3** [comment]
@RobinHoo1973 there is a polyfill.

@z-song Yeah, I know! I would like to overload Has Assets. 
vendor/encore/laravel-admin/src/Traits/HasAssets.php:27

**Comment by RobinHoo1973** [comment]
@rez1dent3 when you tried, you'll found its quite headache. I did and rollback few days ago.

**Comment by schel4ok** [comment]
yeah. font awesome 5 is needed
