### ISSUE TITLE
Select && multipleselect bug 

### ISSUE THREAD

**Issue by Yusov** [z-song/laravel-admin#2653]
- Laravel Version: 5.7.9
- PHP Version: 7.2
- Laravel-admin: 1.6.3

### Description:

In the edit form, when you use select or multiple select, the selection of already selected records does not work if your relationship is named `exampleName`. It works only if you specify the name of the relationship as an `examplename`.

**Comment by smunir** [comment]
I was facing the same issue and just blindly tried snake case and it worked. It's also working with small case.

**Comment by Rishats** [comment]
Same problem. Just renamed function names in to snake_case format....
