### ISSUE TITLE
[PERFORMANCE] Query duplicate

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#266]
Sorry for asking too much.
I have debugged and see query run too much in the same sql.
![screenshot-job dev-2017-01-04-11-37-09](https://cloud.githubusercontent.com/assets/10907980/21631876/e02cd5f4-d272-11e6-99a3-caf795582cf3.png)

**Comment by z-song** [comment]
For the first section you pointed out, if you add column to grid like `$grid->name()`, it will check if the column `name` in table dynamic, that's why you see so many same sql, to fix this you can use `$grid->column('name')` instead.

For the second section, please show more code.

**Comment by taimaiduc** [comment]
Admin::user()->isRole('employer')
Admin::user()->inRoles(['administrator', 'manager'])
I thinks i use it in different function.

[![https://gyazo.com/7af191c32e3e4778b55bd6c70041b10c](https://i.gyazo.com/7af191c32e3e4778b55bd6c70041b10c.png)](https://gyazo.com/7af191c32e3e4778b55bd6c70041b10c)

[![https://gyazo.com/e9f872943c23f23f3614bc590fb0fa1e](https://i.gyazo.com/e9f872943c23f23f3614bc590fb0fa1e.png)](https://gyazo.com/e9f872943c23f23f3614bc590fb0fa1e)

**Comment by langeuh** [comment]
You can replicate this by building up a menu, where every item has x-amount of roles

The methods *can*, *isRole* and *inRoles* in *Encore\Admin\Auth\Database|Administrator* should get query only once and loop them instead of querying them every time

Hope this helps
