### ISSUE TITLE
多图上传时，name重命名bug

### ISSUE THREAD

**Issue by flymorn** [z-song/laravel-admin#2662]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.6.3

### Description:

> // 上传图片
        $form->multipleImage('filepaths', '图片')
            ->move("files/".date('Ym')."/".date('d'))// 上传目录
            ->name(function ($file) {// 自定义文件名
                return time() ."_". str_random(10) .".".$file->guessExtension();
            })
            ->removable();

上传多图时，第一个张图片是按照预期重命名了，但是第2张开始就默认采用的原始名称。

**Comment by Baiyongjian** [comment]
我也碰到了同样的问题

**Comment by gutao1994** [comment]
我也是这样！

**Comment by gutao1994** [comment]
@z-song

**Comment by Mrlaozhou** [comment]
@z-song 同问

**Comment by sofwu** [comment]
@z-song 同问
