### ISSUE TITLE
Need help --> FatalThrowableError In MigrationCreator.php line 157 :

### ISSUE THREAD

**Issue by YounessTayer** [z-song/laravel-admin#2663]
- Laravel Version: 5.7
- PHP Version:7.2
- Laravel-admin: 1.6.5

### Description:
 FatalThrowableError In MigrationCreator.php line 157 :

Too few arguments to function Illuminate\Database\Migrations\MigrationCreator::firePostCreateHooks(), 0 passed in /var/www/php72/mydomain/myproject/vendor/laravel-admin-ext/helpers/src/Scaffold/MigrationCreator.php on line 34 and exactly 1 expected

**Comment by YounessTayer** [comment]
Sorry, I already solved this problem, but forgot how I did.

**Comment by xtareq** [comment]
Check this link:
https://github.com/laravel-admin-extensions/helpers/issues/18

**Comment by z-song** [comment]
Fixed, upgrade laravel-admin-ext/helpers to `v1.1.1`
