### ISSUE TITLE
hasMany 中的form组件没有样式

### ISSUE THREAD

**Issue by manzhouya** [z-song/laravel-admin#2667]
- Laravel Version: 5.5+
- PHP Version: 7.0+
- Laravel-admin: 1.6.5

### Description:

![1539940202 1](https://user-images.githubusercontent.com/29374760/47209052-fbb6a500-d3c1-11e8-9017-0254bead30e9.jpg)

@z-song

**Comment by manzhouya** [comment]
@nkjackzhang 没有报错，写法也是之前一样的，没有问题，我我把版本降到1.6.2正常的

**Comment by nkjackzhang** [comment]
> 
> 
> @nkjackzhang 没有报错，写法也是之前一样的，没有问题，我把版本降到1.6.2正常的

1.6.5的HasMany进行了一些关于输入参数的修改，你提交之后报错可能和这个有关系。
关于样式，还是要看看页面js进行的是不是正常，比如File组件用到的fileinput js，Number用到的bootstrap-number-input.js

**Comment by never615** [comment]
+1 比如图片控件加载不出来,还有haveMany添加的多个控件的id是一样的.

**Comment by never615** [comment]
就是点新增出来的没有样式.已经新增过的跟随页面加载出来是有样式的.

**Comment by never615** [comment]
@z-song 我查了下源码,问题源头是这样的.
我在`HasAssets`中的script方法中,记录静态变量$script的数量.
通过截图中的日志可以看到,当hasMany中的file类型的form render后,静态变量$script数量由17变道了18.
但是下一次`HasAssets`中的script方法被调用的时候,这个数量又变成17了.
我查看数组内容,也确实是fileinput相关的代码又没了.

![image](https://user-images.githubusercontent.com/9959927/47483822-bdf7c780-d86c-11e8-831a-84615989ac3e.png)
![image](https://user-images.githubusercontent.com/9959927/47483847-cf40d400-d86c-11e8-90c8-49c53d972a49.png)

**Comment by z-song** [comment]
@manzhouya @nkjackzhang @never615 提交了修复，之前的一个pr导致了这个问题，稍后更新到`v1.6.6`

**Comment by never615** [comment]
@manzhouya 你好了吗?

**Comment by never615** [comment]
@manzhouya 你的样式出来了吗?我的还没好啊...

**Comment by manzhouya** [comment]
@never615 1.6.6 我不知道，我没更新，我是之前就把版本降到了 1.6.2 。

**Comment by never615** [comment]
@manzhouya 可以用..
我是因为改写了Filed.php中的getElementClass()方法导致加载不出来了....
