### ISSUE TITLE
如何根据表中的某个id查询其他多个关联表的数据导出？

### ISSUE THREAD

**Issue by xiaoxuan6** [z-song/laravel-admin#2668]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### [
![default](https://user-images.githubusercontent.com/32762220/47209640-674d4200-d3c3-11e8-9729-ee4636408b2e.png)
](url)

**Comment by nkjackzhang** [comment]
如果写个自定义exporter，然后在controller里显式调用，不知道可以不可以。
