### ISSUE TITLE
Form表单问题

### ISSUE THREAD

**Issue by Cheng-Lun** [z-song/laravel-admin#2669]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.dev

### Description:
![image](https://user-images.githubusercontent.com/37936633/47213365-586b8d00-d3cd-11e8-980b-30f94dd202e7.png)

怎么获取到form表单中任意的字段？主要是为了获取字段值，自己做些逻辑处理

**Comment by Cheng-Lun** [comment]
> > > 在这个方法里，还没有给form的modal设值，当然获取不到。你要做什么逻辑处理？有的可以在saving里做，有的可以在页面用js做。
> > 
> > 
> > 获取address的值，根据值写流程控制：
> > `if($form->address == '1'){ $form->radio('status','操作')->options(['1'=>'审核通过']); }else{ $form->radio('status','操作')->options(['0'=>'待审核']); }`
> 
> 这种只有一个选项的单选框是为了保存吧，那不如在saving里写$form->model()->status = 0;
> 你这种写法，在Admin::form()方法里是无法使用$form->address的，只有在saving的$form->inputs里才有所有的输入值。

但是我想在用户进入编辑页面，展示不同的内容啊，并不是为了保存。根据流程判断，显示不同的内容

**Comment by z-song** [comment]
从当前路由里面取出id，然后查出来吧

**Comment by MicoHe** [comment]
这个你要在保存前的回调函数里面通过request接收才能使用，因为你在赋值的时候并没提交数据，所以是没定义的
你可以在下面这个函数拿到该值
$form->saving(Form $form){
$address = $form->address;
}
这样就能拿到了
如果你想在一个字段里面访问其他字段的值可以这样写
$form->select('name')->options(function use ($form){
$address = $form->address;
dd($address);
})
