### ISSUE TITLE
加入自己的javascript代码后只能刷新才能生效！！！

### ISSUE THREAD

**Issue by Witype** [z-song/laravel-admin#267]
我在app/Admin/bootstrap.php中添加
~~~
Admin::js('./property/lockController.js');
~~~
当页面的grid翻页后，javaScript代码不生效，需要刷新才能生效。

**Comment by z-song** [comment]
因为框架使用pjax的原因，跳转页面的时候不会去执行引用的js文件，所以你可以在引用的js里面定义好方法，再用`Admin::script()`调用里面的方法。

比如js文件：
```javascript
var sayHello = function () {
    alert('hello');
}
```
然后在需要使用的页面调用这个方法：

```php
Admin::script('sayHello();');
```
