### ISSUE TITLE
表单radio组建问题

### ISSUE THREAD

**Issue by Moon1942** [z-song/laravel-admin#2671]
- Laravel Version: 5.7.*
- PHP Version:7.2
- Laravel-admin: 1.0

### Description:
组件$form->radio($column[, $label])->options(['m' => 'Female', 'f'=> 'Male'])->default('m');有默认值时，
radio组件模板的三目运算
($option == old($column, $value)) || ($value === null && in_array($label, $checked)) ?'checked':'' 
有bug

**Comment by nkjackzhang** [comment]
你这描述太不清晰了，具体有什么bug，别人重现的时候怎么才能知道你说的是哪个bug？
