### ISSUE TITLE
Extention config-->How to add more fields to the Config extension crud? 

### ISSUE THREAD

**Issue by YounessTayer** [z-song/laravel-admin#2676]
- Laravel Version: 5.7.9
- PHP Version:7.2
- Laravel-admin: 1.65

Where I can change the type of the "value" field of the Config extension?

In advance, thank you.

**Comment by tyndouf** [comment]
Hi,
Get a look to "src/Form.php" and "src/Form/Field.php"

**Comment by YounessTayer** [comment]
Hi,
I dead some changes in the two files you precised, now the edit action works but no the show action, I have the following error message : 
FatalThrowableError In ControllerDispatcher.php line 48 :
Call to undefined method Encore\Admin\Config\ConfigController::show()

**Comment by tyndouf** [comment]
Hi Youness,

Her are my advices,

1- set the database table in your config/src/ConfigModel.php
2- Add the show method to the config/src/ConfigController.php, like this:

     public function show($id)
     {
        return Admin::content(function (Content $content) use ($id) {
            $content->header('header');
            $content->description('description');
           
            $content->body($this->detail($id));
        });
       }

3- Add also detail method to the ConfigController.php, like this : 
 public function detail()
    {
         $configModel = config('ConfigModel');
        
        return Admin::show(ConfigModel::class, function (Show $show) {
            $show->id('id', 'ID');
            $show->name('name');
            $show->value('value');
            $show->description('description');
    
            $show->display('created_at');
            $show->display('updated_at');
            return $show;
        });
4- if your create a new fields, don't forget to add theme to the Field.php situeted under the folder encore/laravel-admin/src/Show

Good luck!

**Comment by YounessTayer** [comment]
Hi, Thank you for your help.

I did exactly what you explained but, when I hit the show button it will display to me an empty form, and no data is shown. 

What  I missed to do
