### ISSUE TITLE
form表单disablePjax之后，如何实现表单校验？

### ISSUE THREAD

**Issue by batouy** [z-song/laravel-admin#2679]
- Laravel Version: 5.5.*
- PHP Version: 7.1
- Laravel-admin: 1.6.3

### Description:
请问大大，form表单disablePjax之后，如何实现表单校验？
禁用了pjax后，表单校验失败，直接跳到列表页，错误信息看不到。在saving回调中使用如下语句也没有用：return back()->with(admin_toastr('名称必填', 'error'))->withInput(); 在列表页点击浏览器回退按钮，才会回到之前的表单页面，并显示错误信息

**Comment by zhangpf41** [comment]
我也遇到同样的问题
