### ISSUE TITLE
当form里面使用了saving的时候，grid里switch操作无法生效 

### ISSUE THREAD

**Issue by 307118593** [z-song/laravel-admin#2683]
- Laravel Version: 5.5
- PHP Version:71
- Laravel-admin: v1.5.19

### Description:
当我在form里不使用form->saving的时候，在列表点击切换，数据更新成功，
 但是使用了saving后，数据未能正常修改到数据库中。

### Steps To Reproduce:
form中:
$states = [
                'on'  => ['value' => 0, 'text' => '是', 'color' => 'success'],
                'off' => ['value' => 1, 'text' => '否', 'color' => 'default'],
            ];
            $form->switch('staff_share', '是否员工共享')->states($states)->default(0);

grid中:
$states = [
                'on'  => ['value' => 0, 'text' => '是', 'color' => 'success'],
                'off' => ['value' => 1, 'text' => '否', 'color' => 'default'],
            ];
            $grid->staff_share('是否员工共享')->switch($states);
network返回302  ,toastr.success弹出空值
![_20181024115730](https://user-images.githubusercontent.com/38151262/47405418-ff607800-d783-11e8-88d7-5741ad6fc06e.png)

![_20181024115959](https://user-images.githubusercontent.com/38151262/47405507-6847f000-d784-11e8-98e0-9acf89419b4d.png)

**Comment by never615** [comment]
你要把saveing也也贴出来啊

**Comment by 307118593** [comment]
> 你要把saveing也也贴出来啊

![_20181025113055](https://user-images.githubusercontent.com/38151262/47474430-77dd3c80-d849-11e8-8acf-f28999f1f938.png)

**Comment by z-song** [comment]
在saving里面判断一下  有`mac`和`name`参数的时候才去请求api

因为列表页操作switch的时候只会传递这一个字段的值

**Comment by jesse7866** [comment]
@z-song 
laravel 5.8
laravel-admin 1.6.9

同样碰到这样的问题，network返回302 ,toastr.success弹出空值

查询原因是：
form里设置了其它字段的验证规则，但列表页操作switch的时候只会传递这一个字段的值，所以会修改失败，并返回上一页
