### ISSUE TITLE
Default Laravel AUTHENTICATION and laravel-admin. Help please

### ISSUE THREAD

**Issue by sdasdas93** [z-song/laravel-admin#2687]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: 1.6

### Description:
How can I use the default Laravel user model for authentication in my admin interface?
for example: if I'm authenticated in my web-site using default laravel authentication (make:auth) and if I'm an administrator, I want to be automatically authenticated in my admin interface also. how can I do it?
P.S. sorry for my english.

**Comment by YounessTayer** [comment]
Hi, 
It's not the purpose of laravel-admin, If you do so, you lose all the roles permissions controls.
But you can do something in "Admin/Middeware/Authenicate.php".
