### ISSUE TITLE
浏览器后退 筛选按钮点击失效

### ISSUE THREAD

**Issue by Lexluth0r** [z-song/laravel-admin#2694]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.6.3

### Description:

点开一个有筛选的页面
任意点击其他页面
通过浏览器前进/后退按钮回到刚才的页面
点击筛选按钮 筛选按钮失效 

https://github.com/z-song/laravel-admin/blob/d4950856fe59be95e7d5f9cfeaad1da3f7320cbc/src/Grid/Tools/FilterButton.php#L49

应该在click之前 取消绑定 
$('.{$this->getElementClassName()}').unbind('click');

**Comment by jesse7866** [comment]
@z-song 麻烦在新版更新下

**Comment by z-song** [comment]
已经提交修复，等下个版本发布
