### ISSUE TITLE
最新版本页面显示异常

### ISSUE THREAD

**Issue by mygithahah** [z-song/laravel-admin#2696]
- Laravel Version: 5.5.44
- PHP Version:7.1.20
- Laravel-admin: 1.6

### Description:
使用最新版本我是直接通过composer拉取的代码
此次遇到的问题都是页面显示异常
![image](https://user-images.githubusercontent.com/42802642/47542191-d9b3aa00-d90e-11e8-82b0-886b4f4528f2.png)
![image](https://user-images.githubusercontent.com/42802642/47542200-e20be500-d90e-11e8-8b93-e4fb59790afa.png)
![image](https://user-images.githubusercontent.com/42802642/47542228-07005800-d90f-11e8-8abb-6ae4ee23b8ea.png)

**Comment by never615** [comment]
试试
1. php artisan vendor:publish --force --tag="laravel-admin-assets"
2. php artisan view:clear

**Comment by mygithahah** [comment]
好的，谢谢
