### ISSUE TITLE
How to put many-to-many releation pivot table data using form ?

### ISSUE THREAD

**Issue by anwar0x09** [z-song/laravel-admin#2702]
- Laravel Version: 5.7.11
- PHP Version: 7.2
- Laravel-admin: ~1.6

### Description:
Booking & Room table has many-to-many relation with pivot field quantity, price, discount.
I have tried with multi select but cant find way to fill pivot field quantity,price and discount. 

I have also tried with $form->hasMany()  with nested form but warning shows that only has-many and Morphy relation only supported

**Comment by Bluefitdev** [comment]
I'm actually having the same situation as well...
