### ISSUE TITLE
sorttable()排序问题

### ISSUE THREAD

**Issue by Cheng-Lun** [z-song/laravel-admin#2703]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.5.dev

### Description:
![image](https://user-images.githubusercontent.com/37936633/47598244-d3cfce80-d9cb-11e8-9d58-4df4949379b8.png)
怎么对某个字段求和后，在列表中排序？

**Comment by batouy** [comment]
同理，重写了paginate方法后，sortable也无法进行排序

**Comment by never615** [comment]
排序是根据是根据数据库的列名字段排序

**Comment by yurik94** [comment]
This could be an interesting feature, I have a lot of dynamic columns and I really want to sort them 😄

**Comment by z-song** [comment]
@Cheng-Lun @yurik94 This feature cannot be implemented

**Comment by luoxulx** [comment]
同问，现在 model 中使用的是外部数据源，grid 加了 sortable()后无法使用，它默认会生成查询数据库并排序，却没有把排序参数传给 model 中。
如下：
![image](https://user-images.githubusercontent.com/35016570/57362339-2d058f80-71b1-11e9-8564-85605733aaa7.png)

```sql
SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gm-duoke-admin.ce_sale_assists' doesn't exist (SQL: select count(*) as aggregate from `ce_sale_assists`)
```

**Comment by luoxulx** [comment]
> 同问，现在 model 中使用的是外部数据源，grid 加了 sortable()后无法使用，它默认会生成查询数据库并排序，却没有把排序参数传给 model 中。
> 如下：
> ![image](https://user-images.githubusercontent.com/35016570/57362339-2d058f80-71b1-11e9-8564-85605733aaa7.png)
> 
> ```sql
> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'gm-duoke-admin.ce_sale_assists' doesn't exist (SQL: select count(*) as aggregate from `ce_sale_assists`)
> ```

版本：1.6.10
