### ISSUE TITLE
Form editor oneToMany not loaded properly.

### ISSUE THREAD

**Issue by MochSM** [z-song/laravel-admin#2704]
- Laravel Version: 5.5.*
- PHP Version: 7.1.22
- Laravel-admin: 1.6.3

### Description:

```
$form->hasMany('post_features', '', function (Form\NestedForm $form) {
    $form->hidden('order')->value(0);
    $form->text('title');
    $form->editor('body');
    $form->text('active');
});
```
first

<img src="https://i.imgur.com/6OtUO4g.png">

then

<img src="https://i.imgur.com/dYv7jKd.png">

**Comment by nkjackzhang** [comment]
Does the js in editor field run properly?

**Comment by MochSM** [comment]
@nkjackzhang this is 'bug' maybe, since default editor use `CKEDITOR.replace('{$this->column}');` but @z-song has created the solution here. 

https://github.com/z-song/laravel-admin/blob/179aae581ae1f9ed0b1f4db1380df85add85dd2e/docs/zh/model-form-field-management.md

**Comment by MochSM** [comment]
@nkjackzhang  since default editor use CKEDITOR.replace('{$this->column}'); so it won't work with NestedForm, but @z-song has created the solution here.

https://github.com/z-song/laravel-admin/blob/179aae581ae1f9ed0b1f4db1380df85add85dd2e/docs/zh/model-form-field-management.md
