### ISSUE TITLE
form表单的tags插件输入中文的时候会把拼音与中文一起输进去

### ISSUE THREAD

**Issue by CreationLee** [z-song/laravel-admin#2706]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6

### Description:
form表单的tags插件输入中文的时候会把拼音与中文一起输进去

### Steps To Reproduce:
form表单的tags插件输入中文的时候会把拼音与中文一起输进去
![1540786872 1](https://user-images.githubusercontent.com/22748068/47629287-36180300-db75-11e8-8eae-7f9d0cbd606e.jpg)

**Comment by z-song** [comment]
这个select框使用的前端插件[select2](https://select2.org),  相关的bug到这个项目下去提issue
