### ISSUE TITLE
annot use object of type Encore\Admin\Grid\Tools\BatchDelete as array 

### ISSUE THREAD

**Issue by canon1014** [z-song/laravel-admin#2708]
- Laravel Version: 5.5
- PHP Version:7.1.13
- Laravel-admin: 1.5.19

### Description:
更新之后,出现这个错误
![image](https://user-images.githubusercontent.com/39935301/47635673-cfa0de00-db90-11e8-83f5-aa078d3c986c.png)
改了半天没效果,麻烦各位大佬帮一下

**Comment by z-song** [comment]
运行`php artisan view:clear`试试

**Comment by canon1014** [comment]
> 运行`php artisan view:clear`试试

试过的 还是不行 QAQ

**Comment by canon1014** [comment]
![image](https://user-images.githubusercontent.com/39935301/47641999-75a91400-dba2-11e8-9065-1795b81aad24.png)
是表格中的操作无法获取title和id

**Comment by z-song** [comment]
你贴的代码不是1.5.19这个版本的，你的视图文件是不是修改过，或者自定义过

**Comment by canon1014** [comment]
> 你贴的代码不是1.5.19这个版本的，你的视图文件是不是修改过，或者自定义过

万分感谢啊,解决了,我只升级了控制器但是重写的内置视图忘记更新了
