### ISSUE TITLE
form组件中，如何一排放置两个组件

### ISSUE THREAD

**Issue by xiaalngf** [z-song/laravel-admin#271]
protected function form()
    {
        return Admin::form(Shop::class, function (Form $form) {
           // $form->display('id', 'ID');
            $form->hidden('a','业务员')->default(Admin::user()->id);
            $form->text('b','简称');
            $form->text('c','营业执照');
            $form->text('d','公司全名');
            $form->text('e','公司描述');
      });
    }
如上面的代码，展示的时候是一row一个，这样页面很长，而我的输入框又不需要那么长。
有没有方式可以一排可以放两个，或三个，四个。
如下面这样：
 $form->row([text('b','简称'),text('c','营业执照')]); //一排放两个
 $form->row([text('b','简称'),text('c','营业执照'),select('f','级别')->options($f)]); //一排放三个

**Comment by z-song** [comment]
暂时没有办法实现。
