### ISSUE TITLE
Grid Header Info

### ISSUE THREAD

**Issue by smunir** [z-song/laravel-admin#2712]
- Laravel Version: 7.5.9
- PHP Version: 7.2.4
- Laravel-admin: 1.6.6

### Description:
How can I display information as grid header, like if I want to display students of a particular class in the grid, class needs to be displayed in the header. I believe there was a header function of grid, has that been removed?

**Comment by yurik94** [comment]
**Prepend another ->body ?**
![image](https://user-images.githubusercontent.com/13189646/47761370-62886800-dcb8-11e8-8e5e-5e64218676cb.png)

**Comment by smunir** [comment]
Hmmm, nice idea. Thanks. Will give this a shot.

**Comment by smunir** [comment]
Still not able to figure out how to get parent ID to fetch records in second body function. I have tried doing
````php
public function index(Content $content)
    {

        $grid = $this->grid();
        $header = $this->gridHeader();

        return $content
            ->header('Answer Keys')
            ->description('description')
            ->body($header)
            ->body($grid);
    }
````

But I am not able to get parent id in the gridHeader function. I have come from java background and this PHP scoping thing is strange to me. Can you post a working example code please?
