### ISSUE TITLE
请问如何Listen Select组件的onchange事件?

### ISSUE THREAD

**Issue by jzblog** [z-song/laravel-admin#2719]
- Laravel Version: 5.5.43
- PHP Version: 7.1.5
- Laravel-admin: 1.6.1

### Description:
请问如何Listen Select组件的onchange事件?并据此显示隐藏另一个控件？

**Comment by z-song** [comment]
select框使用的前端插件[select2](https://select2.org),  相关的事件到这个项目下去找

用`Admin::script();`给当前页面添加js脚本
