### ISSUE TITLE
在Grid中如何进行分组 (groupBy) 查询？

### ISSUE THREAD

**Issue by zaimuhuoche** [z-song/laravel-admin#272]
$grid->model()->groupBy('username');

会报错

SQLSTATE[42000]: Syntax error or access violation: 1055？？

**Comment by z-song** [comment]
能贴出更详细的错误信息吗？

**Comment by zaimuhuoche** [comment]
![jietu20170108-204855](https://cloud.githubusercontent.com/assets/20182639/21750008/0aa66380-d5e4-11e6-9884-df00363a2d79.jpg)

是这个样子的，想做个统计信息。不知道有什么更好的解决方案，把总数存到缓存中？ 刚加群：Q：Black先生

**Comment by z-song** [comment]
看错误是sql语法错误，你单独执行一下这个sql语句看看什么问题

**Comment by zaimuhuoche** [comment]
额，好的，谢谢。sql语句执行是没问题的，我再试试吧。ps: 这个问题可以随时关。
