### ISSUE TITLE
Model show multiple images preview

### ISSUE THREAD

**Issue by mjakub12** [z-song/laravel-admin#2723]
- Laravel Version: 5.6
- PHP Version: 7.1+
- Laravel-admin: 1.6.5

Is it possible to preview multiple images in model show?? 

When I do $show->photos()->image() it throws an error "array to string conversion".

Thanks in advance.

**Comment by chiwex** [comment]
if `$show->photos()` is a collection use **first()** method to display to the first image

example: 
$show->photos()->first()->image_name

**Comment by mjakub12** [comment]
But I want to display all images...like in form where you have multipleImage

**Comment by chiwex** [comment]
you have to loop the image collections

**Comment by mjakub12** [comment]
So I found a workaround, I am not sure if it is a good approach but it is working.
If anyone have a better idea I will be glad to hear it.
Bellow is a snapshot of my code

![image](https://user-images.githubusercontent.com/19220455/47926717-8b2f7e00-dec1-11e8-84bd-b806ecbad922.png)

**Comment by MicoHe** [comment]
i do that like you

**Comment by lihe6666** [comment]
这个方法也不错

**Comment by makhchan** [comment]
> Well I tried $show->photos()->each()->image() and still got an error "parameter expects to be string, array given" I even tried your example and still got the same error...

This one worked for me, Just need to add a function __toString on Photo Model that returns the image path.

`public function __toString()
    {
        return $this->path;
    }`
