### ISSUE TITLE
Error message when accessing Show() method --> FatalThrowableError In ControllerDispatcher.php line 48 : 

### ISSUE THREAD

**Issue by YounessTayer** [z-song/laravel-admin#2724]
Laravel Version: 5.7.9
    PHP Version:7.2
    Laravel-admin: 1.65

### Description:

Hello everybody,

The errro message appear when I try to preview (click on preview button my config view entries), it simply lead to the following error message : Call to undefined method Encore\Admin\Config\ConfigController::show()

![screenshot from 2018-11-02 21-09-13](https://user-images.githubusercontent.com/13769537/47938223-a7441700-dee3-11e8-94c3-21324f8a899a.png)

### Steps To Reproduce:
1- seted the database table in myconfig/src/ConfigModel.php
2- Added the show method to the config/src/ConfigController.php, like this:

 public function show($id)
 {
    return Admin::content(function (Content $content) use ($id) {
        $content->header('header');
        $content->description('description');
       
        $content->body($this->detail($id));
    });
   }

3- Add detail method to my ConfigController.php, like this :
public function detail()
{
$configModel = config('ConfigModel');

    return Admin::show(ConfigModel::class, function (Show $show) {
        $show->id('id', 'ID');
        $show->name('name');
        $show->value('value');
        $show->description('description');

        $show->display('created_at');
        $show->display('updated_at');
        return $show;
    });

4-Added my newly created fields to the "Field.php" situated under the folder encore/Admin/Show

Any idea please on how to solve this problem?
In advance, thank you.

**Comment by laraveldo** [comment]
Hi youness,
Please, Verify that your system call the right "ConfigController.php" file.

**Comment by YounessTayer** [comment]
Hi, 

Thank you Laraveldo,

You see it right, that was the problem : I renamed my original to ConfigController0.php and did all the changes in a new file. Now I have an empty form without  records values. As you can see it in the screenshot bellow :

![screenshot from 2018-11-02 22-17-48](https://user-images.githubusercontent.com/13769537/47942682-137a4700-def3-11e8-9ad0-8eba8ae51b46.png)

**Comment by Romerski** [comment]
Your `detail` function is wrong. Try:

```
protected function detail($id)
    {
        return Admin::show(ConfigModel::findOrFail($id), function (Show $show) {
            $show->id('ID');
            $show->name('name');
            $show->value('value');
            $show->description('description');

            $show->display('created_at');
            $show->display('updated_at');
        });
    }
```

**Comment by YounessTayer** [comment]
Thank you  Romerski,

Unfortunately it still not working after have tried your solution. Sure, I will figure out why one day :) For the moment I uses an another Laravel package builder.

Thanks again,
Youness
