### ISSUE TITLE
无限极分类问题

### ISSUE THREAD

**Issue by lpx20000** [z-song/laravel-admin#273]
看到demo在线的那个地址，里面有
use Encore\Admin\Traits\AdminBuilder;
use Encore\Admin\Traits\ModelTree;
这两个类貌似没有找到有？不知能否提供
另外Demo中的Menu List页面，那个页面的写法能否告知？
谢谢，麻烦了。。

**Comment by z-song** [comment]
demo基于`1.3.x-dev`版本，使用这个版本可以使用这个功能

切换demo上面的tab可以看到代码

**Comment by lpx20000** [comment]
好的，谢谢

**Comment by lpx20000** [comment]
咨询多一个问题，貌似每次进入后台都很慢，楼主是否考虑优化？

**Comment by z-song** [comment]
看浏览器network  部分组件引用了cdn资源，参考 https://github.com/z-song/laravel-admin/blob/master/docs/zh/field-management.md 关掉

**Comment by lpx20000** [comment]
嗯，有留意到，谢谢楼主
