### ISSUE TITLE
如果两个表的表名都是拼接的（有变量），怎么用model关联查询。

### ISSUE THREAD

**Issue by Baiyongjian** [z-song/laravel-admin#2731]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.6.0

### Description:
比如有两个表：user_1  book_1 有关联，但是1是会变的，有可能是user_2  book_2 （链接的是别的表的id）。现在的问题是在grid()里用了setTable方法，可以改user model里的表名，但是关联book表时(hasOne)，还是关联的book model的表名。我就是想让user_2  book_2 关联。

**Comment by nkjackzhang** [comment]
laravel的model的关系都是静态的，判断的是model里面有没有这个方法，不知道用魔法方法能不能把判断改成动态的。
