### ISSUE TITLE
低版本的自定义用户管理页面bug

### ISSUE THREAD

**Issue by Purelightme** [z-song/laravel-admin#2733]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.5

### Description:
![image](https://user-images.githubusercontent.com/16385534/48045592-ecaa6200-e1cb-11e8-9bba-25c52ed921fb.png)
![image](https://user-images.githubusercontent.com/16385534/48045598-f2a04300-e1cb-11e8-9c3c-df8a96a3a172.png)

### Steps To Reproduce:
`<?php

namespace App\Admin\Controllers\User;

use App\Models\Store;
use App\Models\User;

use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Layout\Content;
use App\Http\Controllers\Controller;
use Encore\Admin\Controllers\ModelForm;

class UserAdminController extends Controller
{
    use ModelForm;

    /**
     * Index interface.
     *
     * @return Content
     */
    public function index()
    {
        return Admin::content(function (Content $content) {

            $content->header('用户管理');
            $content->description('列表');

            $content->body($this->grid());
        });
    }

    /**
     * Edit interface.
     *
     * @param $id
     * @return Content
     */
    public function edit($id)
    {
        return Admin::content(function (Content $content) use ($id) {

            $content->header('用户管理');
            $content->description('编辑');

            $content->body($this->form()->edit($id));
        });
    }

    /**
     * Create interface.
     *
     * @return Content
     */
    public function create()
    {
        return Admin::content(function (Content $content) {

            $content->header('用户管理');
            $content->description('添加');

            $content->body($this->form());
        });
    }

    /**
     * Make a grid builder.
     *
     * @return Grid
     */
    protected function grid()
    {
        return Admin::grid(User::class, function (Grid $grid) {

            $grid->model()->latest();
            $grid->id('ID')->sortable();
            $grid->nickname('昵称');
            $grid->avatar('头像')->image(null,100,50);
            $grid->phone('手机号');
            $grid->active('状态')->display(function ($active){
                if ($active == Store::IS_NOT_ACTIVE){
                    return "<span class='label label-danger'>".Store::ACTIVE_MAP[$active]."</span>";
                }else{
                    return "<span class='label label-success'>".Store::ACTIVE_MAP[$active]."</span>";
                }
            });
            $grid->created_at('注册时间');

            $grid->disableExport();
            $grid->disableCreateButton();

            $grid->filter(function (Grid\Filter $filter){
                $filter->disableIdFilter();
                $filter->like('nickname','昵称');
                $filter->like('phone','手机号');
                $filter->equal('active','账号状态')->select([
                    0 => '封禁',
                    1 => '正常'
                ]);
                $filter->between('created_at','注册时间')->datetime();
            });

        });
    }

    /**
     * Make a form builder.
     *
     * @return Form
     */
    protected function form()
    {
        return Admin::form(User::class, function (Form $form) {

            $form->display('id', 'ID');
            $form->display('openid','用户openid');
            $form->display('nickname','昵称');
            $form->image('avatar','头像')->readOnly();
            $form->display('phone','手机号');
            $form->switch('active','状态')->states([
                'on'  => ['value' => 1, 'text' => '正常', 'color' => 'success'],
                'off' => ['value' => 0, 'text' => '封禁', 'color' => 'danger'],
            ]);
            $form->display('created_at', '创建时间');
            $form->display('updated_at', '最后更新时间');
        });
    }
}
`

**Comment by never615** [comment]
截图上的字放大也模糊了.

**Comment by Purelightme** [comment]
> 截图上的字放大也模糊了.

就是点击“用户管理”的菜单，页面刷新后，菜单栏就出现图2中的选择框，很奇怪的一个页面bug。用户管理的控制器代码已贴。

**Comment by never615** [comment]
这跟用户管理的控制器代码也没关系,用户管理的控制器的代码控制的是菜单右边的区域.

**Comment by feistiny** [comment]
请确定浏览器类型及其版本，更换其他浏览器试试

**Comment by Purelightme** [comment]
问题解决了。问题是user表里面有个active的字段，grid里面写的filter直接用$filter->equal('active'.....)时，跟laravel-admin的前端代码active冲突了。
修改成：
`$filter->where(function ($query){
                    $query->where('active',$this->input);
                },'账号状态')->select([
                    0 => '封禁',
                    1 => '正常'
                ]);`
问题解决，bug消失。
