### ISSUE TITLE
admin_base_path 和 admin_url

### ISSUE THREAD

**Issue by windqyoung** [z-song/laravel-admin#2735]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.6.1

### Description:
希望能修改一下这两函数的使用.
让项目在服务器子目录下也能正常运行.

**Comment by tienrocker** [comment]
project dead, no one care anymore, you just replace `admin_base_path` to `admin_url` in all files in `views` folder

**Comment by feistiny** [comment]
或许你要做的只是修改一下config/admin.php中的route.prefix？
```php
    function admin_base_path($path = '')
    {
        $prefix = '/'.trim(config('admin.route.prefix'), '/');

        $prefix = ($prefix == '/') ? '' : $prefix;

        return $prefix.'/'.trim($path, '/');
    }

```

**Comment by windqyoung** [comment]
不是这个。这个项目里面的 url 都是相对网站根目录的，如果把项目放到网站的子目录下，好多 url 都不正确。

**Comment by wakasann** [comment]
my way is

1. in `config/admin.php`  file add  `url_prefix` config item like:

```
    /*
    |--------------------------------------------------------------------------
    | Laravel-admin url prefix
    |--------------------------------------------------------------------------
    |
    | This value is the base url of admin_base_path method
    |
    */
    'url_prefix' => '',
```
2. in `app` folder create `admin_helpers.php` file,file content is 

```
<?php
//var_dump(function_exists('admin_base_path'));
if (!function_exists('admin_base_path')) {
    /**
     * Get admin url.
     *
     * @param string $path
     *
     * @return string
     */
    function admin_base_path($path = '')
    {
        $prefix = '/'.trim(config('admin.url_prefix')).trim(config('admin.route.prefix'), '/');

        $prefix = ($prefix == '/') ? '' : $prefix;

        return $prefix.'/'.trim($path, '/');
    }
}
```
3.   in `public/index.php`  and `bootstrap/autoload.php`  two files,
 ``` 
require __DIR__.'/../vendor/autoload.php';
```

 before  add 
```
require __DIR__ . '/../app/admin_helpers.php';
```

 i try this way can override `admin_base_path()` method when reutrn value at version `"^1.6"`

#### Reference ####
1. [How to redeclare helper function?](https://laracasts.com/discuss/channels/laravel/how-to-redeclare-helper-function#reply=124325)
2. [Overwrite laravel 5 helper function](https://stackoverflow.com/a/28475973)
