### ISSUE TITLE
302 status => Cant save or update form 

### ISSUE THREAD

**Issue by greentornado** [z-song/laravel-admin#2736]
- Laravel Version: 5.7.*
- PHP Version: ^7.1.3
- Laravel-admin: ^1.6

### Description:
When i create or update a model, no data was saved to the db, and I get a 302 status response

### Steps To Reproduce:

this is my form:
       protected function form_input()
        {

        $form = new Form(new LoanDocument);

        $form->setTitle("Nội dung hồ sơ");
        $form->tools(function (Form\Tools $tools) {
       
            $tools->disableList();
         
            $tools->disableDelete();
           
            $tools->disableView();
        });

        $form->tab('1. Thông tin cá nhân', function ($form) {
            $form->display('id', 'ID');
            $form->text('full_name', 'Họ và tên');
            $form->text('phone_number', 'Số ĐTDĐ');
            $form->text('phone_number_2', 'Số ĐTDĐ 2 Nếu có');
            $form->text('national_id', 'CMND');
            $form->select("marital_status", "Trạng thái hôn nhân")
                ->options(["single" => "Chưa từng lập gia đình",
                    "married" => "Đã có gia đình",
                    "disvorced" => "Ly hôn, goá"]);
            $form->divide();
            $form->text('address', 'Địa chị thường trú');
            $form->text('current_address', 'Địa chị hiện tại');
            $form->text('resident_time_city', 'Thời gian cư trú tại nơi ở');

        })->tab('2. Học vấn/ Nghề nghiệp', function ($form) {
            $form->text('university', 'Tên trường đại học');
            $form->text('class_name', 'Tên lớp đại học');
            $form->text('class_course', 'Tên khoá đại học');
            $form->divide();
            $form->text('company_name', 'Tên công ty/ cửa hàng');
            $form->text('company_address', 'Địa chỉ công ty');
            $form->text('company_job_title', 'Chức vụ');
            $form->text('company_work_years', 'Thời gian dã làm tại công ty');
            $form->text('company_phone', 'Điện thoại công ty');

        })->tab('3. Người thân', function ($form) {
            $form->text('spouse_name', 'Họ tên vợ/ chồng');
            $form->text('spouse_mobile', 'Số điện thoại vợ/ chồng');
            $form->text('spouse_job', 'Nghề nghiệp vợ/ chồng');
            $form->divide();
            $form->text('father_name', 'Họ tên cha ruột');
            $form->text('father_mobile', 'Số điện thoại cha ruột');
            $form->text('father_job', 'Nghề nghiệp cha ruột');
            $form->divide();

        })->tab('4. Thu nhập/ Tín dụng', function ($form) {

        })->tab('5. Khoản vay', function ($form) {

        })->tab('6. Tài khoản online', function ($form) {

        })->tab('7. Upload ảnh', function ($form) {

        });

        $form->footer(function ($footer) {
            // disable reset btn
            $footer->disableReset();
            // disable submit btn
            $footer->disableSubmit();
            // disable `View` checkbox
            $footer->disableViewCheck();
            // disable `Continue editing` checkbox
            $footer->disableEditingCheck();
            // disable `Continue Creating` checkbox
            $footer->disableCreatingCheck();
        });
        $form->setView('loan_documents.create_form');

       

        return $form;

      }`
<img width="469" alt="screenshot 2018-11-07 11 47 00" src="https://user-images.githubusercontent.com/280004/48111212-1bcfda80-e283-11e8-802f-97efc5452e25.png">

**Comment by feistiny** [comment]
It is not anything wrong that the form subimt with a 302 response, it will just redirect to the grid url.
Check you `Location` field in the response header.
```html
HTTP/1.1 302 Found
Server: nginx/1.10.3 (Ubuntu)
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Cache-Control: no-cache, private
Date: Wed, 07 Nov 2018 14:26:50 GMT
Location: http://localhost/admin/goods
Set-Cookie: XSRF-TOKEN=eyJpdiI6IjVHQkJzQUh1N25xRVZTMlhBRHpYelE9PSIsInZhbHVlIjoiN0VKa1hKdzh6SEkzd2ZWKzlUWUdxakFiaXBzS0R5M0lBSnlsc2tEaWxVVCtoYmFsM085clg4YnY3Uk9WOHpuOSIsIm1hYyI6IjRhZGE5NTQ2MjQxNzFiYjJjZGVjMTFiNzA4ODIzNTdjOTQwZDI4ZGM4MWZkNzY2NTc0NTk0MzFiOTNjNTIxOWMifQ%3D%3D; expires=Wed, 07-Nov-2018 16:26:50 GMT; Max-Age=7200; path=/
Set-Cookie: laravel_session=eyJpdiI6Ik16VlNwN2tsSG02enVmQUZia0d5TlE9PSIsInZhbHVlIjoiUlMzTVFIb2FPc0hkSHREZURBa25BMGplK25Ob2tLQkQ1ZVlyaERrbGVDNWdROXJ3d09DSGtDZFZoR0JPM0xidyIsIm1hYyI6IjczMGI3YTcyZGY2NTZkYWMzYWNkOGY1YWRjZmI0ZTU4YTMwMmYyMzE5YzRiMDk0OTg3NDQwMTQwOTEzNDM5NDUifQ%3D%3D; expires=Wed, 07-Nov-2018 16:26:50 GMT; Max-Age=7200; path=/; httponly
Content-Length: 392

<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8" />
        <meta http-equiv="refresh" content="0;url=http://localhost/admin/goods" />

        <title>Redirecting to http://localhost/admin/goods</title>
    </head>
    <body>
        Redirecting to <a href="http://localhost/admin/goods">http://localhost/admin/goods</a>.
    </body>
</html>
```

**Comment by greentornado** [comment]
I managed to do it by copy store & update fn to the controller
