### ISSUE TITLE
多图片上不起作用

### ISSUE THREAD

**Issue by Yw-melo** [z-song/laravel-admin#2738]
- Laravel Version: 5.7
- PHP Version:7.2
- Laravel-admin: 1.6.7

### Description:
添加multipleImage但是不起作用，删除的按钮也没有出现
<img width="877" alt="wx20181107-154754 2x" src="https://user-images.githubusercontent.com/33000435/48117558-89d8c980-e2a4-11e8-822f-7babd31edf96.png">
控制器代码:
`$form->multipleImage('images','Images')->move('/images/bars')->uniqueName()->removable();`

**Comment by feistiny** [comment]
多疑图片上传时，需要用ctrl配合多选，保存后，才会在图片上出现删除按扭
![image](https://user-images.githubusercontent.com/13468753/48136714-4ea5bd00-e2db-11e8-88e6-5fe73beac584.png)

**Comment by Yw-melo** [comment]
@feistiny 解决了 多谢
