### ISSUE TITLE
[HELP] How to show nested form in table like style

### ISSUE THREAD

**Issue by Muhammadinaam** [z-song/laravel-admin#274]
Very very nice admin package so far. I appreciate it very much. Please keep up the good work.

I have a question, how can I show nested form in table like style? (Please see the image below for example)

![rprt_master_detail2](https://cloud.githubusercontent.com/assets/22542738/21799210/16c2d7be-d73a-11e6-8065-de3425db7329.gif)

**Comment by z-song** [comment]
I'm afraid not, In your screenshoot, all fields in nested form are simple text input, it's easy to show them in table like style, but in `laravel-admin`  there are a lot of complex field, it's hard to use a table to organize fields with different size.

**Comment by Muhammadinaam** [comment]
I think, just put any kind of fields in a bootstrap table and table will adjust automatically.

**Comment by edwinhuish** [comment]
It's not a good style in modern. But if you need it similar, you can add a grid below the from, and add editable to all the fields.
