### ISSUE TITLE
Admin-menu 左侧菜单栏无法删除

### ISSUE THREAD

**Issue by Yw-melo** [z-song/laravel-admin#2741]
- Laravel Version: 5.7
- PHP Version: 7.2
- Laravel-admin: 1.6.7
<img width="614" alt="wx20181107-184229 2x" src="https://user-images.githubusercontent.com/33000435/48126737-eb0c9700-e2bc-11e8-897b-480ac115e171.png">

<img width="330" alt="wx20181107-183935 2x" src="https://user-images.githubusercontent.com/33000435/48126643-9f59ed80-e2bc-11e8-832e-c0722b270c1a.png">

### Description:
编辑按钮是没问题的，删除按钮点了没反应

**Comment by feistiny** [comment]
点删除时，看看有没有这样的请求，返回什么错误
![image](https://user-images.githubusercontent.com/13468753/48136230-16ea4580-e2da-11e8-90b2-5b42e3377f9a.png)

**Comment by Yw-melo** [comment]
> 点删除时，看看有没有这样的请求，返回什么错误
> ![image](https://user-images.githubusercontent.com/13468753/48136230-16ea4580-e2da-11e8-90b2-5b42e3377f9a.png)

点击删除并没有网络请求，只有控制台报错
![wx20181108-095841](https://user-images.githubusercontent.com/33000435/48173002-ebe50d80-e33c-11e8-9960-a8c1316620fe.png)

**Comment by Yw-melo** [comment]
确实是有js文件没加载，重新发布一下就OK了
