### ISSUE TITLE
如何设置登录cookie时长

### ISSUE THREAD

**Issue by 307118593** [z-song/laravel-admin#2745]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.15.19

### Description:
后台登录后过个几分钟cookie就失效了..我想设置长一点的时间..请问怎么操作

**Comment by windqyoung** [comment]
这个问题不应该发到这。和此项目无关。

**Comment by mushishixian** [comment]
这是laravel可以设置的吧,设置config里的session.php去修改时长可以加长登录
