### ISSUE TITLE
模型树排序保存时报500

### ISSUE THREAD

**Issue by rootrl** [z-song/laravel-admin#2748]
- Laravel Version: #.#.#
5.5
- PHP Version:
7.2
- Laravel-admin: #.#.#
1.6

### Description:

在模型树index列表页，拖动几个分类，然后点保存的时候，报500
我看了下详细报错会有条insert的语句 报错是因为有的字段没默认值（只insert `updated_at`, `created_at` 两个字段）

很奇怪，这里为什么会insert？有小伙伴遇到过吗？

**Comment by rootrl** [comment]
现在把Controller层全部简化成官方demo那样，还是报错
然后估计是model有问题，我发现我在model层重写了    protected static function boot() ，去掉就可以，但是为什么这样？

**Comment by rootrl** [comment]
在model层只写
`    protected static function boot()
    {
        parent::boot();
    }`

也会报错

**Comment by rootrl** [comment]
发现ModelTree的Traits里面已经写了boot方法，那我该怎么写自己的方法？我要在boot里写个static::deleting

**Comment by mushishixian** [comment]
我是直接用对应模型的方法的boot方法覆盖的,当然也要把ModelTree的Traits里面的boot方法复制过来
