### ISSUE TITLE
批量上传图片两个问题

### ISSUE THREAD

**Issue by Yw-melo** [z-song/laravel-admin#2749]
- Laravel Version: 5.7
- PHP Version: 7.2
- Laravel-admin: 1.6.7

1. 批量上传图片时没发限制上传图片的个数
2. 在编辑页面删除多张图片中的一个图片时，其余图片在数据库里存储的值全变成了图片的完整路径，而不是原来的路径+文件名

**Comment by mushishixian** [comment]
第一个去设置file file input的配置项,传到options方法里面去,第二个问题我这边没发现
