### ISSUE TITLE
[BUG]: Error when editing a record

### ISSUE THREAD

**Issue by Muhammadinaam** [z-song/laravel-admin#275]
I opened demo site and I visited following URL:

http://120.26.143.106/admin/world/city/2823/edit

Now when I click submit, it gives following error:

![bug](https://cloud.githubusercontent.com/assets/22542738/21801419/5ba7ebea-d743-11e6-9f70-067fea936eb8.png)

The problem is with Country field, It is showing country name is Pakistan but value is null. Therefore it is generating foreign key exception.

When I renter Pakistan in this field and hit submit button. Then form gets saved.

Please correct this issue.

**Comment by z-song** [comment]
Thanks for your support😁， I'll fix this later.

**Comment by Muhammadinaam** [comment]
has this issue been resolved???
