### ISSUE TITLE
有个需求,在实际开发中很常见的.列表中某列需要通过ID自定义显示内容

### ISSUE THREAD

**Issue by qzd1989** [z-song/laravel-admin#2752]
- Laravel Version: 5.6
- PHP Version:7.2
- Laravel-admin: 1.6.7
### Description:
有个需求,在实际开发中很常见的.列表中某列需要通过ID自定义显示内容. 希望能实现.... :)
### Steps To Reproduce:
这是需求,不是BUG....

**Comment by feistiny** [comment]
你的需求可以用Laravel的访问器实现吧

**Comment by nkjackzhang** [comment]
你可以用display(function(){})，函数里面自己写显示内容

**Comment by sollyu** [comment]
请问这个功能实现了？或者求相关的实例代码。
