### ISSUE TITLE
Model tree - One level hierarchy

### ISSUE THREAD

**Issue by s6carlo** [z-song/laravel-admin#2754]
### Description:
Is it possible to configure model tree in a way that it has only one level? I would like not a real "tree" but an orderable list.

Thanks

**Comment by feistiny** [comment]
Maybe what you really  need is a grid with an editable order column, thus you can easily find the row to change its order by filter or paginator, instead of look through the whole tree for your order target, since the Model tree doesnt support search.

**Comment by Romerski** [comment]
Yea, you can. 

```
protected function treeView()
    {
        return YourModel::tree(function (Tree $tree) {
            $tree->nestable(["maxDepth" => 1]);
        });
    }
```

**Comment by s6carlo** [comment]
Hint for someone in the same situation:
using a "one level tree" the buttons "Expand" and "Collapse" are useless.
To remove them I create a custom view just copying tree.blande.php inside a "resources/views/customadmin" directory.
Then in the new view remove the buttons and in the controller 
```
 protected function treeView()
    {
        return YourModel::tree(function (Tree $tree) {
            $views= array(
                'tree'   => 'customadmin.tree',
                'branch' => 'admin::tree.branch');
            $tree->setView($views);
            $tree->nestable(["maxDepth" => 1]);
        });
    }
```

**Comment by mRamadan0101** [comment]
where i can put this function @s6carlo 

> Hint for someone in the same situation:
> using a "one level tree" the buttons "Expand" and "Collapse" are useless.
> To remove them I create a custom view just copying tree.blande.php inside a "resources/views/customadmin" directory.
> Then in the new view remove the buttons and in the controller
> 
> ```
>  protected function treeView()
>     {
>         return YourModel::tree(function (Tree $tree) {
>             $views= array(
>                 'tree'   => 'customadmin.tree',
>                 'branch' => 'admin::tree.branch');
>             $tree->setView($views);
>             $tree->nestable(["maxDepth" => 1]);
>         });
>     }
> ```

**Comment by sangct-1630** [comment]
@mRamadan0101 
It is located in the controller. You can consult `/encore/laravel-admin/src/Controllers/MenuController.php`
