### ISSUE TITLE
腾讯地图修复

### ISSUE THREAD

**Issue by sohenk** [z-song/laravel-admin#2755]
- Laravel Version: 5.7
- PHP Version:7.2.11
- Laravel-admin: 1.6.#

### Description:
腾讯地图公告
关于JavaScript API调用必须注册开发者key的公告
为保证服务调用的安全性和稳定性，腾讯位置服务JavaScript API需先注册后调用。
请开发者及时调整，通过腾讯位置服务官网进行开发者密钥key注册 （前往申请key），并使用注册成功的key进行 JavaScript API 调用。平台将于 2018年9月30日，停止对未注册调用的维护。

所以需要在引入js那里加多个key

### Steps To Reproduce:
在laravel-admin/src/Form/Field/Map.php那里加多个key
```
  case 'tencent':
            	$js = '//map.qq.com/api/js?v=2.exp&key='.env('TENCENT_API_KEY');
                break;
```

然后在.env文件那里加上你申请的腾讯地图key就好了
TENCENT_API_KEY=*******

**Comment by skys215** [comment]
我也遇到这个问题了。
这个应该让官方支持。我们直接改源代码的话，在其他服务器上部署又得手动改一下了。

**Comment by z-song** [comment]
@sohenk @skys215 地图选择器在以后的版本会废弃掉，以后使用这个插件 https://github.com/laravel-admin-extensions/latlong
