### ISSUE TITLE
多图上传成功后进入详情页面会报错

### ISSUE THREAD

**Issue by longyunrui** [z-song/laravel-admin#2756]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6

### Description:

Method Illuminate\View\View::__toString() must not throw an exception, caught ErrorException: htmlspecialchars() expects parameter 1 to be string, array given (View: E:\Project\sicao\vendor\encore\laravel-admin\resources\views\show\field.blade.php)

### Steps To Reproduce:

多图上传成功后进入详情页面会报错

**Comment by longyunrui** [comment]
目前解决方案
```
$show->images('图片')->unescape()->as(function ($images) {
            if (empty($images)) {
                return '';
            }
            $disk = config('admin.upload.disk');
            if (config("filesystems.disks.{$disk}")) {
                $str = '';
                if(!empty($images)){
                    foreach ($images as $image){
                        $src = Storage::disk($disk)->url($image);
                        $str .= "<img src='$src' style='margin: 0 5px' class='img' />";
                    }
                }
            } else {
                return '';
            }

            return $str;
});
```

**Comment by fplun** [comment]
> 目前解决方案
> 
> ```
> $show->images('图片')->unescape()->as(function ($images) {
>             if (empty($images)) {
>                 return '';
>             }
>             $disk = config('admin.upload.disk');
>             if (config("filesystems.disks.{$disk}")) {
>                 $str = '';
>                 if(!empty($images)){
>                     foreach ($images as $image){
>                         $src = Storage::disk($disk)->url($image);
>                         $str .= "<img src='$src' style='margin: 0 5px' class='img' />";
>                     }
>                 }
>             } else {
>                 return '';
>             }
> 
>             return $str;
> });
> ```

现在好像不行了哎,我这直接出字符串了

**Comment by longyunrui** [comment]
> > 目前解决方案
> > ```
> > $show->images('图片')->unescape()->as(function ($images) {
> >             if (empty($images)) {
> >                 return '';
> >             }
> >             $disk = config('admin.upload.disk');
> >             if (config("filesystems.disks.{$disk}")) {
> >                 $str = '';
> >                 if(!empty($images)){
> >                     foreach ($images as $image){
> >                         $src = Storage::disk($disk)->url($image);
> >                         $str .= "<img src='$src' style='margin: 0 5px' class='img' />";
> >                     }
> >                 }
> >             } else {
> >                 return '';
> >             }
> > 
> >             return $str;
> > });
> > ```
> 
> 现在好像不行了哎,我这直接出字符串了

完全复制过去看看，可能版本不同解决的方式也不同

**Comment by lihe6666** [comment]
哇， 这个问题都没人解决吗？

**Comment by chinkiver** [comment]
// 在后面增加 image()
$show->images('图片')->image();

// 如果是文件的话，就是 file()
$show->files('文件')->file();
// 同时修改
```
// Encore\Admin\Show\Field

    /**
     * Show field as a file.
     *
     * @param string $server
     * @param bool   $download
     *
     * @return Field
     */
    public function file($server = '', $download = true)
    {
        $field = $this;

        return $this->unescape()->as(function ($path) use ($server, $download, $field) {
            return collect($path)->map(function ($path) use ($server, $download, $field) {
                $name = basename($path);

                $field->wrapped = false;

                $size = $url = '';

                if (url()->isValidUrl($path)) {
                    $url = $path;
                } elseif ($server) {
                    $url = $server.$path;
                } else {
                    $storage = Storage::disk(config('admin.upload.disk'));
                    if ($storage->exists($path)) {
                        $url = $storage->url($path);
                        $size = ($storage->size($path) / 1000).'KB';
                    }
                }

                if (!$url) {
                    return '';
                }

                return <<<HTML
<ul class="mailbox-attachments clearfix">
    <li style="margin-bottom: 0;">
      <span class="mailbox-attachment-icon"><i class="fa {$field->getFileIcon($name)}"></i></span>
      <div class="mailbox-attachment-info">
        <div class="mailbox-attachment-name">
            <i class="fa fa-paperclip"></i> {$name}
            </div>
            <span class="mailbox-attachment-size">
              {$size}&nbsp;
              <a href="{$url}" class="btn btn-default btn-xs pull-right" target="_blank"><i class="fa fa-cloud-download"></i></a>
            </span>
      </div>
    </li>
  </ul>
HTML;
            })->implode('&nbsp;');
        });
    }

```

**Comment by longyunrui** [comment]
> // 在后面增加 image()
> $show->images('图片')->image();
> 
> // 如果是文件的话，就是 file()
> $show->files('文件')->file();
> // 同时修改
> 
> ```
> // Encore\Admin\Show\Field
> 
>     /**
>      * Show field as a file.
>      *
>      * @param string $server
>      * @param bool   $download
>      *
>      * @return Field
>      */
>     public function file($server = '', $download = true)
>     {
>         $field = $this;
> 
>         return $this->unescape()->as(function ($path) use ($server, $download, $field) {
>             return collect($path)->map(function ($path) use ($server, $download, $field) {
>                 $name = basename($path);
> 
>                 $field->wrapped = false;
> 
>                 $size = $url = '';
> 
>                 if (url()->isValidUrl($path)) {
>                     $url = $path;
>                 } elseif ($server) {
>                     $url = $server.$path;
>                 } else {
>                     $storage = Storage::disk(config('admin.upload.disk'));
>                     if ($storage->exists($path)) {
>                         $url = $storage->url($path);
>                         $size = ($storage->size($path) / 1000).'KB';
>                     }
>                 }
> 
>                 if (!$url) {
>                     return '';
>                 }
> 
>                 return <<<HTML
> <ul class="mailbox-attachments clearfix">
>     <li style="margin-bottom: 0;">
>       <span class="mailbox-attachment-icon"><i class="fa {$field->getFileIcon($name)}"></i></span>
>       <div class="mailbox-attachment-info">
>         <div class="mailbox-attachment-name">
>             <i class="fa fa-paperclip"></i> {$name}
>             </div>
>             <span class="mailbox-attachment-size">
>               {$size}&nbsp;
>               <a href="{$url}" class="btn btn-default btn-xs pull-right" target="_blank"><i class="fa fa-cloud-download"></i></a>
>             </span>
>       </div>
>     </li>
>   </ul>
> HTML;
>             })->implode('&nbsp;');
>         });
>     }
> ```

改源码可能会不太好

**Comment by longyunrui** [comment]
> 哇， 这个问题都没人解决吗？

上面有解决方式，版本不同可能解决的方式会有差异，但是原理应该是一样的
