### ISSUE TITLE
请教一下,模型详情里的字段能不能实现同行展示

### ISSUE THREAD

**Issue by fplun** [z-song/laravel-admin#2760]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: dev-master

### Description:
我一个做php的,自己找个挺好用的后台框架,想给ui和前端省点事,老被领导喷..样式问题我是真不会啊

**Comment by nkjackzhang** [comment]
如果真有这样的需求，那只能自己写模板覆盖原有的模板

**Comment by fplun** [comment]
> 如果真有这样的需求，那只能自己写模板覆盖原有的模板

我准备想想办法给他写成form表单,form表单里面不是有row方法么,应该可以同行展示,然后全部给他改成display

**Comment by yuyulu** [comment]
$address->id('地址信息')->as(function ($id) {
			    $address = Address::find($id);
                return $address->province.$address->city.$address->area.$address->detail;
            });
没有改模板，应该也合理吧
