### ISSUE TITLE
自定义语言设置无效

### ISSUE THREAD

**Issue by CooperJin** [z-song/laravel-admin#277]
参考文档设置自定义语言
https://github.com/z-song/laravel-admin/blob/d99d095b5634c461d56170969c622adb453d6d84/docs/zh/qa.md#自定义语言
没有执行bootstrap.php
是哪里设置有问题么?

**Comment by z-song** [comment]
你使用的Laravel版本是多少？

**Comment by digitalprocoopers** [comment]
5.3

**Comment by z-song** [comment]
能贴一下你的代码最好了

**Comment by digitalprocoopers** [comment]
我又试了一下是在登录页没有执行，登录以后就没有问题了

**Comment by em0t** [comment]
同5.3版本，后台语言文件不生效，然后在`bootstrap`下添加`app('translator')->addNamespace('admin', resource_path('lang/admin'))`后，后台页面trans正常，但登陆页取不到语言文件
问题文件:
`encore/laravel-admin/views/login.blade.php`,blade中所有trans不生效

**Comment by yang5664** [comment]
根據 Laravel 5.3文件
https://laravel.com/docs/5.3/localization#overriding-package-language-files
設定語系
![screen shot 2017-02-05 at 10 43 01 pm](https://cloud.githubusercontent.com/assets/5953010/22627031/1617d9fc-ebf5-11e6-99be-971895dbb7a3.png)
放置Lang文件
![screen shot 2017-02-05 at 10 43 19 pm](https://cloud.githubusercontent.com/assets/5953010/22627034/2944bff4-ebf5-11e6-9de5-dffc508b9dde.png)
