### ISSUE TITLE
在form组件中, 如何让display的数据显示readonly的样式?

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#2777]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

**Comment by MochSM** [comment]
https://laravel-admin.org/docs/zh/model-form-fields#%E6%98%BE%E7%A4%BA%E5%AD%97%E6%AE%B5

```
显示字段
只显示字段，不做任何操作：

$form->display($column[, $label]);

//更复杂的显示
$form->display($column[, $label])->with(function ($value) {
    return "<img src="$value" />";
});
```

我建议你在这里问一下
https://discuss.laravel-admin.org/
