### ISSUE TITLE
No query results for model [App\Topic] index

### ISSUE THREAD

**Issue by venlee1993** [z-song/laravel-admin#2779]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6

Description:
![image](https://user-images.githubusercontent.com/27339765/48696378-beda0a00-ec1c-11e8-9ad2-d1a5807468c8.png)

![image](https://user-images.githubusercontent.com/27339765/48696444-e8933100-ec1c-11e8-9f3f-411158a67bd3.png)

![image](https://user-images.githubusercontent.com/27339765/48696574-3b6ce880-ec1d-11e8-9653-53d7f2705956.png)

**Comment by z-song** [comment]
列表访问路径是`/topic`  不是`/topic/index`
