### ISSUE TITLE
多对多关联更新

### ISSUE THREAD

**Issue by lpx20000** [z-song/laravel-admin#278]
在dev1.3版本中，有下面的代码
```
 if (!$isRelation && Str::contains($columns, '.')) {
                continue;
            } elseif ($isRelation && !Str::contains($columns, '.')) {
                continue;
            }
```

我操作更新时，始终无法管理更新，查看源代码，是在该处直接continue跳过 ，如果注释掉，即可通过更新，不知大大那边有没问题，还是我操作有误？

**Comment by z-song** [comment]
这里确实有问题，多对多关联的column是没有`.`的，不应该跳过。

谢谢指出错误，后续修正！

**Comment by lpx20000** [comment]
客气啦。

**Comment by lpx20000** [comment]
对了，问下大大，我看在线demo中的editors有Markdown和其他的文本编辑器，在1.3开发版中没找到对应的文件，是不是还在开发中的？

**Comment by z-song** [comment]
参考 https://github.com/z-song/laravel-admin/blob/master/docs/zh/field-management.md#扩展自定义组件

demo上的那几个编辑器是扩展示例。

**Comment by lpx20000** [comment]
好的，多谢，。

**Comment by z-song** [comment]
已经修复，多谢！
