### ISSUE TITLE
Field type [editor] does not exist.

### ISSUE THREAD

**Issue by Pashaster12** [z-song/laravel-admin#2780]
- Laravel Version: 5.7.13
- PHP Version: 7.2
- Laravel-admin: 1.6.7

### Description:

Got the error `Field type [editor] does not exist.` when trying to use editor field at the form.

### Steps To Reproduce:

I use the following code from the official specification:

```php
$form = new Form(new Page);
$form->editor('content');
```

**Comment by Pashaster12** [comment]
I've found the solution - editor and map field types are blocked by default in the package. Here is the code from the `App\Admin\bootstrap.php`:

```php
Encore\Admin\Form::forget(['map', 'editor']);
```

**Comment by protectedfor** [comment]
I have removed `editor` from array but still getting the same error.

**Comment by RaiserWeb** [comment]
Looks like it's been removed from the core field registration. Adding the following inside App\Admin\bootstrap.php (above the forget method) fixed for me.

`Encore\Admin\Form::extend('editor', Encore\Admin\Form\Field\Editor::class);`

**Comment by momosc** [comment]
https://laravel-admin.org/docs/zh/model-form-field-management
