### ISSUE TITLE
What do i have do to uninstall o remove a ext?

### ISSUE THREAD

**Issue by DiegoReales** [z-song/laravel-admin#2786]
- Laravel Version: 5.7.*
- PHP Version: 7.2.0
- Laravel-admin: 1.6.0

### Description:

Hi, I would like to know what I should do to uninstall or delete an extension.

Are there some standardized or recommended steps?

**Comment by KulwinderKohli** [comment]
try this:

`composer remove laravel-admin-ext/extension-name`
