### ISSUE TITLE
编辑时，怎么把 $form->image('config_image',) 赋值成其它图片。

### ISSUE THREAD

**Issue by lyongdee** [z-song/laravel-admin#2789]
- Laravel Version: 5.7.13
- PHP Version:7.1.19
- Laravel-admin: 1.6.7

### Description:
一些特殊操作，要求编辑时，把 $form->image('config_image',) 赋值成其它图片，怎么操作呢，求解？

**Comment by Chester-Hee** [comment]
可以使用 display()

**Comment by elinxer** [comment]
同问,display不起作用
