### ISSUE TITLE
编辑时，怎么赋值 $form->select('config_country')->options(function ($id) {...})->ajax('api') 已保存的选项数据

### ISSUE THREAD

**Issue by lyongdee** [z-song/laravel-admin#2790]
- Laravel Version: 5.7.13
- PHP Version:7.1.19
- Laravel-admin: 1.6.7

### Description:
如标题，编辑时，怎么把下拉列表 $form->select('config_country')->options(function ($id) {})->ajax('api') 赋值成已经保存的选项数据，怎么操作呢，求解？

**Comment by gongjieqi** [comment]
页面渲染完了才调用的ajax取值，所以在表单里取不到你保存的值得，直接在options里返回吧，我编辑的时候是这样做的：
$form->select('school_id', '学校')->options(function(){
            return  School::query()->pluck('name','id');
        })

**Comment by lyongdee** [comment]
@gongjieqi 感谢回复。因为我关联 Ajax 接口数据表的记录有几千条，如果这样查询的话性能是不是有点低了。

**Comment by lyongdee** [comment]
@z-song，这个有方法解决吗？

**Comment by gongjieqi** [comment]
@lyongdee 你可以在编辑的时候 对ajax做下处理，带上你的ID，再返回第一页值得时候，把你ID对应的值拼到数组的第一个

**Comment by lyongdee** [comment]
@gongjieqi 嗯，谢谢，有实现代码吗。
