### ISSUE TITLE
Grid 使用 admin::grid.image 视图时候的bug

### ISSUE THREAD

**Issue by gongjieqi** [z-song/laravel-admin#2791]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6.3

### Description:
image的blade里面checkbox的data-id是用{{ $row->id() }} 取的row对象id
`<input type="checkbox" class="grid-item" data-id="{{ $row->id() }}" />`

然而在row对象里，没有ID或者魔术方法导致报错，然而row对象里却有_get魔术方法，所以在这里，把image.blade里的这一样 改成
`<input type="checkbox" class="grid-item" data-id="{{ $row->id }}" />`

就可以解决这个问题

PS：不知道是否还有其他的方式解决这个问题？

**Comment by z-song** [comment]
你可以自定义视图使用, 使用在`resources/views`目录下的视图
```php
 $grid->setView('image');
```

**Comment by gongjieqi** [comment]
好的 谢谢
