### ISSUE TITLE
控制器中的detail方法图片问题

### ISSUE THREAD

**Issue by bobby2050** [z-song/laravel-admin#2797]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6,5

### Description:

控制器中的detail方法，有个字段图片的不完整的路径，我怎么对这个图片的地址做修改呢，求教大神

**Comment by z-song** [comment]
```php
$show->image()->as(function ($path) {
    // 对不完整的路径 $path 修改后return 
});
```
