### ISSUE TITLE
文檔 錯誤 https://laravel-admin.org/docs/zh/model-form-callback

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#2798]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
![_20181127092741](https://user-images.githubusercontent.com/8817046/49052465-f2bdbc80-f226-11e8-930c-429bffac30a1.png)

**Comment by z-song** [comment]
已修复
