### ISSUE TITLE
calender date field is not translated

### ISSUE THREAD

**Issue by axyr** [z-song/laravel-admin#28]
it shows chinese instead of english like the rest..

**Comment by z-song** [comment]
I did not see this issue,please ensure the `app.locale` config was set to `en`.

**Comment by axyr** [comment]
`app.locale` is set to `en` (by default) ...
this is happening on a fresh install of L 5.2 and Admin 1.2.5

**Comment by axyr** [comment]
ah, and the latest tag has the locale hardcoded...
https://github.com/z-song/laravel-admin/blob/1.2.5/src/Form/Field/Date.php#L23

**Comment by z-song** [comment]
I fixed many issues and add some features on master branch, your can update this package by using `composer require encore/laravel-admin "dev-master"`.
