### ISSUE TITLE
数据库有个字段label，默认Form输出class 被hidden了

### ISSUE THREAD

**Issue by ieliwb** [z-song/laravel-admin#2807]
默认表单字段输出如下：
`<input type="text" id="label" name="label" value="FREE" class="form-control label" placeholder="Input Label" />`
class label和系统默认的冲突，导致被hidden了，怎么处理呢？可以设置别名吗？

![avatar](https://ae01.alicdn.com/kf/HTB1b4YyXVzsK1Rjy1Xb760OaFXaP.png)

**Comment by wangshuo2333** [comment]
可以在列之后加->setElementClass('')； 将class设置为空或者需要的class名称之后Laravel-admin将不会将字段名称设为默认class，我已经提交PR，增加了一个为class取别名的功能

**Comment by ieliwb** [comment]
@wangshuo2333  谢谢，按你说的解决了
