### ISSUE TITLE
升级之后出现

### ISSUE THREAD

**Issue by Share-Man** [z-song/laravel-admin#2808]
- Laravel Version: 5.5
- PHP Version: 7+
- Laravel-admin: 1.6

### Description:
![image](https://user-images.githubusercontent.com/4065724/49160427-b347bb00-f361-11e8-87ca-796a9509939e.png)
升级之后出现未知字段。尝试过重新publish资源和重装都不行。

**Comment by z-song** [comment]
这是语言包没有更新，到`vendor/encore/laravel-admin/resources/lang`里面找语言包去替换掉`resources/lang`里面的
