### ISSUE TITLE
能不能设置两种没登录的跳转

### ISSUE THREAD

**Issue by kevenzhang2012** [z-song/laravel-admin#2816]
Laravel Version: 5.7.*
PHP Version:7.1.3
Laravel-admin: 1.6

### Description:
问题是这样的：权限管理用后台没问题，
但其他的业务处理我返回的都是json数据，比如订单管理、消费记录等。
当用户过期后，就会被未登录拦截，结果返回了html。
怎么才能设置为未登录也返回json格式的数据，而不影响原来的权限管理

**Comment by wangshuo2333** [comment]
可以尝试一下oauth
