### ISSUE TITLE
可以把案例站单独开源在一个仓库中吗？

### ISSUE THREAD

**Issue by smartymoon** [z-song/laravel-admin#282]
最近想深入了解学习 laravel-admin，所以一直在案例站中逛。虽然每个页面都有关键代码，但是想深入了解每个特性还是不方便，如果能单独开一个仓库，我就可以clone到本地尽情得折腾了，同时也不会污染官方的案例站点。

**Comment by z-song** [comment]
因为demo上还有其它项目在里面，所以不方便一起拿出来。
