### ISSUE TITLE
$content->body渲染显示页面，页面中引入的js未加载

### ISSUE THREAD

**Issue by BEIBEI123** [z-song/laravel-admin#2824]
- Laravel Version: 5.5
- PHP Version:7.01
- Laravel-admin: 1.6.0

### Description:
$content->body(view('upload_care', ['id' => $id]));显示一个模板页面，模板文件中有引入vue.js和写了一部分js代码，当我点击按钮进入页面时显示vue未加载，刷新这个页面就正常了
另外一个页面同样引入的是另外一个js文件，也同样出现这个问题了，点击按钮进入页面js文件未加载，刷新页面就行了
这个js文件不是每个页面都需要引入，只有这个页面需要，所以不希望通过Admin::js('path/to/your/js');的方式全局引入

**Comment by zhangpf41** [comment]
我也遇到同样的问题，经过查找，pjax的机制是自动异步加载html内容，然后会自动将script[src]的内容加入到<head>标签最后，问题，这个机制是为了减少js的请求次数，不必每次都加载js，但产生bug的具体原因不明。解决方案：禁止将script[src]的内容拷贝到<head>中，牺牲js缓存，也就是每次加载container都加载一次js，问题解决。找到query.pjax.js定位到746、747行，屏蔽掉。然后在blade模板中直接引入app.js文件。

**Comment by syw0602** [comment]
在view中使用 $.getScript 加载脚本，并在回调中继续写你的JS
