### ISSUE TITLE
使用leftjoin修改model数据源，并对created_at字段过滤后， 会发生过滤查询错误（两个表都有created_at字段）

### ISSUE THREAD

**Issue by wellzhen** [z-song/laravel-admin#2825]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

两个表都有相同的字段created_at, 
使用$filter->between("created_at", "下单日期")->date(); 
当进行过滤查询后， 发生错误 Column 'created_at' in where clause is ambiguous
几次修改都无法解决问题：
$filter->between("order.created_at", "下单日期")->date();

**Comment by JinPengCN** [comment]
请问解决了吗
