### ISSUE TITLE
hasMany的問題

### ISSUE THREAD

**Issue by soso851213** [z-song/laravel-admin#2826]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
想請問一下作者，HasMany裡的欄位可以使用one to one的field嗎？如下，因為我使用的時候不能抓到值。
$form->hasMany('type2_contents', '選擇項目', function (Form\NestedForm $form){
         $form->text('question_option.title', '選項名稱')->rules('required');
});
謝謝您。

**Comment by t-perm** [comment]
Can you add `protected $fillable = [field has many];` to your model
