### ISSUE TITLE
Grid Orderable not working 

### ISSUE THREAD

**Issue by naingwin** [z-song/laravel-admin#2827]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

$grid->orderable() not working even I have installed spatie/eloquent-sortable.

<img width="418" alt="screen shot 2018-12-06 at 3 47 46 pm" src="https://user-images.githubusercontent.com/4189090/49574324-90736300-f96e-11e8-9c7c-b19adccda0e3.png">

**Comment by naingwin** [comment]
suggestions pls

**Comment by artem-tverdokhlebov** [comment]
you need to create column 'order_column', INT 11, and then it will work :)

**Comment by artem-tverdokhlebov** [comment]
`use Illuminate\Database\Eloquent\Model;
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;

class Breakfast extends Model implements Sortable
{
    use SortableTrait;

    public $sortable = [
        'order_column_name' => 'order_column',
        'sort_when_creating' => true,
    ];`

and add this to your model

**Comment by naingwin** [comment]
Still not working :'(

Here is Model

<img width="754" alt="screen shot 2018-12-11 at 11 39 48 am" src="https://user-images.githubusercontent.com/4189090/49779647-88823d00-fd39-11e8-89a1-92238be72ca7.png">


And this is result

<img width="1024" alt="screen shot 2018-12-11 at 11 39 30 am" src="https://user-images.githubusercontent.com/4189090/49779663-9932b300-fd39-11e8-9a50-b274e7432a93.png">

**Comment by artem-tverdokhlebov** [comment]
Did you create 'order_column' in db? Also, try to flush the table.

This is the result, that you are looking for
![image](https://user-images.githubusercontent.com/1665709/49788420-fe82a600-fd31-11e8-9617-1e519ce286b0.png)

**Comment by naingwin** [comment]
Thanks, it's working now. 

`$grid->orderable()` is not working

`$grid->order_column()->orderable()` is worked
