### ISSUE TITLE
grid 中 groupBy 不可用

### ISSUE THREAD

**Issue by fengerwoo** [z-song/laravel-admin#2834]
我想表格根据用户ID去重，但是报错，试了下orderBy排序都是可以的，但是groupBy不行
<pre> <code> 
$grid->model()->groupBy('user_id');
</code> </pre>

报错：

<pre> <code> 
QueryException In Connection.php line 664 :
SQLSTATE[42000]: Syntax error or access violation: 1055 Expression #1 of SELECT list is not in GROUP BY clause and contains nonaggregated column 'ant.login_uvs.id' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by (SQL: select * from `login_uvs` group by `user_id` limit 20 offset 0)
</code> </pre>

**Comment by wangshuo2333** [comment]
**SELECT list is not in GROUP BY**
已经提示你要group BY的字段不存在了
