### ISSUE TITLE
Show relation in better format

### ISSUE THREAD

**Issue by kamov** [z-song/laravel-admin#2848]
Right now relations is show in JSON format.
Can I display only the values that I wish?

See screenshot:

![screenshot from 2018-12-11 12-35-11](https://user-images.githubusercontent.com/2345000/49798000-773d2e80-fd41-11e8-9c30-6d95b9daf645.png)

**Comment by z-song** [comment]
The value of this field is a complex data structure, you can use the `display` callback to handle the output logic, like:
```php
$grid->column('column_name')->display(function ($value) {
    return colloct($value)->pluck('name')->implode(',');
});
```
