### ISSUE TITLE
更新以后form中的radio以及image组件出现了问题

### ISSUE THREAD

**Issue by sanmisanFan** [z-song/laravel-admin#285]
$form->image()的样式无法正常显示，以及$form->radio()出现了Method Illuminate\View\View::__toString()，可以用自定义样式绕开问题，但是纯净环境重新安装了最新版本以后此问题依然存在。

**Comment by sanmisanFan** [comment]
重新安装了1.3.x-dev的一切正常，是否是上个版本中的问题呢？

**Comment by z-song** [comment]
是安装1.3.1出现的问题吗？

**Comment by sanmisanFan** [comment]
是的，1.3.0中各组件也都正常。

**Comment by z-song** [comment]
好的 了解了，下个版本修复一下，谢谢
