### ISSUE TITLE
Show组件扩展

### ISSUE THREAD

**Issue by SuzutsukiKagami** [z-song/laravel-admin#2862]
- Laravel Version: 5.5
- PHP Version:PHP 7.2
- Laravel-admin: 1.6.7

### Description:
//自定义高德地图组件
Form::extend('amap', App\Admin\Extensions\Show\Amap::class);
Show::extend('amap', App\Admin\Extensions\Form\Amap::class);

看了下源码，Show目前不支持自定义扩展？没找到extend，也看不到相关扩展的方法

**Comment by peterheider** [comment]
+1
Is this a planned feature?

**Comment by gutao1994** [comment]
同问

**Comment by z-song** [comment]
@SuzutsukiKagami @peterheider @gutao1994 Pushed a commit to implement this feature

Now you can extend `Show` field as follows：

```php

use Encore\Admin\Show\AbstractField;

class Amap extends AbstractField
{
    public function render($arg = null)
    {
        //Your code here
        return $this->value;
    }
}
```

Register this extension in `app/Admin/bootstrap.php`
```php
Encore\Admin\Show::extend('amap', \App\Admin\Extensions\Show\Amap::class);

// or

Encore\Admin\Show::extend('amap',  new \App\Admin\Extensions\Show\Amap());
```

Another way is to use closures to extend Show field
```php
Encore\Admin\Show::extend('amap',  function ($value) {
    return $value;
});
```

Use this feature in the dev-master version, or wait for the next release.

**Comment by SuzutsukiKagami** [comment]
thanks!
