### ISSUE TITLE
导出excel只能用2.1版本的吗

### ISSUE THREAD

**Issue by fplun** [z-song/laravel-admin#2865]
用Laravel Excel 3.1,一直会报错,
![image](https://user-images.githubusercontent.com/38807395/50268280-275b1780-0465-11e9-9578-b228d0be89a2.png)
用xdebug看源码看一会儿我就懵了,完全看不懂,看的想哭

**Comment by xiaomlove** [comment]
是的，不支持3，写法完全不一样了

**Comment by fplun** [comment]
> 是的，不支持3，写法完全不一样了

我也换成2.1了
