### ISSUE TITLE
[HELP]:Grid一对多关系，如何调用多的模型里的scopeWhere

### ISSUE THREAD

**Issue by AugusLarry** [z-song/laravel-admin#287]
关联关系如下：
![qq 20170113140348](https://cloud.githubusercontent.com/assets/9316266/21920074/c85eb996-d999-11e6-97aa-1a7171eabcfd.png)

$grid->comments();
如何给这个comments()添加这个type条件？

**Comment by AugusLarry** [comment]
试了多种方法，好像只能$grid->comments()->where('type', 1);

**Comment by z-song** [comment]
用`$grid->comments()->where('type', 1);`其实是全部查出来，再用`Collection::where()`筛选，可以用另外一种变通的方法

```php
    // parent
    public function comments_1()
    {
        return $this->comments()->type();
    }

    // related
    public function scopeType($query)
    {
        return $query->where('type', '1');
    }

    // 使用
    $grid->comments_1();
```

**Comment by AugusLarry** [comment]
这种也可以，不过这种是先把条件插入再去数据库查询，比我那个要好很多
