### ISSUE TITLE
使用阿里云OSS的时候报错

### ISSUE THREAD

**Issue by jingzhongwa** [z-song/laravel-admin#2871]
- Laravel Version: 5.5.44
- PHP Version:7.2
- Laravel-admin: 1.6.0

### Description:
按照https://github.com/z-song/laravel-admin/issues/1178上推荐的jacobcyl 扩展配置oss,
打开后台发现如下报错
<img width="1903" alt="image" src="https://user-images.githubusercontent.com/34508080/50332919-90fb2480-053e-11e9-930f-e3f11c1424e1.png">
到那一行代码查看，发现symfony路径下确实是没有这个组件的，不知道是什么原因，麻烦大大帮忙看看

**Comment by jxufeboy** [comment]
@jingzhongwa 请问一下后来你找到解决方法了么，今天我也碰到了这个问题哦
