### ISSUE TITLE
一个神奇的错误

### ISSUE THREAD

**Issue by safly** [z-song/laravel-admin#2874]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.6.8

### Description:
一定情况下，按钮链接会多一个斜线，如//creat，//1，//1/edit

### Steps To Reproduce:
1. controller删除edit函数
2. 回到页面，点击修改按钮，报错
3. 回到页面，发现所有按钮都多了斜线
4. 清除cookies，重新登陆，恢复正常

**Comment by aoxiang594** [comment]
唉，你这种标题就不对，
