### ISSUE TITLE
form->saving empty bug

### ISSUE THREAD

**Issue by kairye** [z-song/laravel-admin#2876]
- Laravel Version: 5.7
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
程序始终无法进入saving的if分支中，然后通过测试，出来了这个结果：

### Steps To Reproduce:

![6cxmn9j536](https://user-images.githubusercontent.com/25899134/50389352-3e02b680-0764-11e9-80b2-c575bc8dfa89.png)
![zq9zh1vcfv](https://user-images.githubusercontent.com/25899134/50389353-3e9b4d00-0764-11e9-8cf7-fcc346703600.png)

**Comment by ieliwb** [comment]
大佬怎么解决的，我也遇到了

**Comment by ieliwb** [comment]
单独搞个变量出来判断也太蛋疼了吧

**Comment by kairye** [comment]
这个项目不做了，忘了当时怎么考虑的。看了下代码，是这样的。希望对你有帮助。
```
if ($form->min_income && ($form->min_income > $form->max_income)) {
     throw new \Exception('用户收益区间设置错误！');
}
```
