### ISSUE TITLE
一对一， 要保存到第三张关联表中

### ISSUE THREAD

**Issue by guyaofei** [z-song/laravel-admin#2879]
三张表：学校表，问题表，问题学校关联表。添加问题时选择学校，一个问题只对应一个学校。问题与学校是一对一的关系。
现在采用的是select下拉框，但是在model中使用这种方式
![ubopaab 1sc6m6k_4tq i 2](https://user-images.githubusercontent.com/30075084/50398155-5f898f80-07b0-11e9-9531-2595639c4a3b.png)
可以添加成功，但是编辑的时候编辑页面无法回显，用multipleSelect下拉框是没问题的，但是这种方式不符合要求的，要求是一对一，不能多选。应该怎么解决

**Comment by guyaofei** [comment]
三张表：。学校表，问题表，问题学校关联表。添加问题时选择学校，一个问题只对应一个学校。问题与学校的关系一对一的关系

**Comment by guyaofei** [comment]
作者大佬帮忙解决下，急求啊

**Comment by milkmeowo** [comment]
建议你先理
