### ISSUE TITLE
1.3.x-dev中, grid->action()与row->action()问题

### ISSUE THREAD

**Issue by sanmisanFan** [z-song/laravel-admin#288]
如题，还在继续调试，无法通过action方法调整列的修改与删除操作。从报错中判断，应该是Grid.php的新增方法action需要传入闭包实例参数，实际上调用比如$grid->actions('edit|delete');参数传入的是string类型。以下是具体error msg：

Argument 1 passed to Encore\Admin\Grid::actions() must be an instance of Closure, string given

**Comment by z-song** [comment]
1.3.x-dev 已经重构掉了这部分  参考demo http://120.26.143.106/admin/demo/users

```php
$grid->actions(function ($actions) {
    if ($actions->getKey() % 2 == 0) {
        $actions->disableDelete();
        $actions->append('<a href=""><i class="fa fa-eye"></i></a>');
    } else {
        $actions->disableEdit();
        $actions->prepend('<a href=""><i class="fa fa-paper-plane"></i></a>');
    }
});
```

**Comment by sanmisanFan** [comment]
awesome, 我升级以后代码还是老版本的，正在把自己写的后台逐步迁移到laravel-admin中，非常感谢，我会以demo为参考的。

**Comment by z-song** [comment]
demo的代码是基于1.3.x-dev版本，基本上所有功能都在demo上有体现。
