### ISSUE TITLE
MultipleFile and MultipleImage are not deemed as "File" in laravel-admin

### ISSUE THREAD

**Issue by netbuilding** [z-song/laravel-admin#2882]
- Laravel Version: v5.7.13
- PHP Version: 7.1
- Laravel-admin: 1.6.7

### Description:

Validation error when using MultipleFile / MultipleImage. 
Having dive in the source code, I found MultipleFile and MultipleImage are extended from Encore\Admin\Form\Field. However, the 'hasFile' method checks if the form has any of File Fields by estimating fields are instance of Field\File, which result in this bug. The form's encode type(enctype) is not "multipart/form-data" because hasFile() returns false. 

```
/**
     * Determine if form fields has files.
     *
     * @return bool
     */
    public function hasFile()
    {
        foreach ($this->fields() as $field) {
            if ($field instanceof Field\File) {
                return true;
            }
        }
        return false;
    }
```

### Steps To Reproduce:
Use multipleFile or multipleImage in form builder and you won't get update after submitted. (no error message shown)

**Comment by z-song** [comment]
Please feel free to send a pr~
