### ISSUE TITLE
筛选按钮筛选后，点击进入详情，然后在浏览器返回上一页，筛选按钮就点不动了，且筛选项自动展现不隐藏

### ISSUE THREAD

**Issue by c903494855** [z-song/laravel-admin#2887]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

筛选按钮筛选后，点击进入详情，然后在浏览器返回上一页，筛选按钮就点不动了，且筛选项自动展现不隐藏

**Comment by echoBallon** [comment]
我也遇到了同样的问题
