### ISSUE TITLE
Bug with related json column saving 

### ISSUE THREAD

**Issue by Pashaster12** [z-song/laravel-admin#2889]
- Laravel Version: 5.7.15
- PHP Version: 7.1
- Laravel-admin: 1.6.7

### Description:

While editing the related table via NestedForm which contains the json field, changes saved only when every element changes. If I change one json variable, others cleared.

### Steps To Reproduce:

I edit the `menus` table instance via ResourceController which have records in the related `menu_items` table next way:

```php
protected function form($id = null)
{
       ...
       $form->tab('Элементы меню', function ($form) {
            $form->hasMany('items', 'Элементы', function (Form\NestedForm $form) {
                foreach (config('locales') as $locale_code => $locale_name) {
                    $form->text("serialized_data.title_{$locale_code}", "Заголовок ({$locale_name})");
                }

                $form->url('href', 'Ссылка на заголовке')->rules('max:100');
                $form->number('sort_order', 'Порядок сортировки')->min(0)->max(65535);
            });
        });
}
```

`serialized_data` is a json field and contains `title_ru, title_ua, title_en` values. The code above generates the following form:

![screenshot_7](https://user-images.githubusercontent.com/18751246/50457766-e3857800-0966-11e9-8b0d-a0dac67f95d0.png)

If I type any value in the serialized_data.title_en input - **Заголовок (Английский) field** - I lose my `title_ru` and `title_ua` input values. If I change all of them - they all will be changed.

**Comment by RobinHoo1973** [comment]
The problem of your code is not wrap the foreach block within embed form:
```
       $form->embeds('extra', function ($form) { //add this line for foreach language loop
              foreach (config('locales') as $locale_code => $locale_name) {
                    $form->text("title_{$locale_code}", "Заголовок ({$locale_name})"); //change the field name to title_{language_code}
                }
       }); //close embed block
```

DO NOT forget add the below lines in your Model
```
class XXX extends Model
{
    protected $casts = [
        'title' => 'json', //assume your embed field name is title
    ];
}
```

**Comment by Pashaster12** [comment]
@RobinHoo1973 Thanks for your response. I've tried your solution, but it doesn't work for me. My form:

```php
$form->tab('Элементы меню', function ($form) {
            $form->hasMany('items', 'Элементы', function (Form\NestedForm $form) {
                $form->embeds('serialized_data', '', function ($form) {
                    foreach (config('locales') as $locale_code => $locale_name) {
                        $form->text("title_{$locale_code}", "Заголовок ({$locale_name})");
                    }
                });

                $form->url('href', 'Ссылка на заголовке')->rules('max:100');
                $form->number('sort_order', 'Порядок сортировки')->min(0)->max(65535);
            });
        });

        $form->saving(function (Form $form) {
            dd($form->items);
        });
```

I also used the `casts` attribute at my related model and also I added my json field to the `fillable` attribute:

```php
protected $casts = [
        'serialized_data' => 'json'
    ];

    protected $fillable = [
        'menu_id',
        'href',
        'serialized_data',
        'sort_order'
    ];
```

But with `embeds` form the data of my related model doesn't save at all. Here my `$form->items` dump inside `$form->saving` hook:

```
array:4 [▼
  5 => array:4 [▼
    "href" => null
    "sort_order" => "1"
    "id" => "5"
    "_remove_" => "0"
  ]
  6 => array:4 [▶]
  7 => array:4 [▶]
  8 => array:4 [▶]
]
```

My json field diappeared from the form at all. In my variant with the code above it was here.

**Comment by Pashaster12** [comment]
Finally, I've fixed this bug with this solution making the custom `hasManyEmbeds` element. Why core developers don't include this component to the package code or fix the `embeds` inside `hasMany`?
