### ISSUE TITLE
表单验证不显示验证错误信息

### ISSUE THREAD

**Issue by uu6744** [z-song/laravel-admin#2891]
- Laravel Version: 5.5
- PHP Version:   >7.0
- Laravel-admin: 1.6

### Description:
表单字段验证规则加过之后，并没有显示错误信息，只刷新了一下表单页

**Comment by 775397252** [comment]
你是不是setaction了

**Comment by sunxiyuan** [comment]
我也遇到了相同的问题，一直未能解决
