### ISSUE TITLE
Expand扩展插件找不到

### ISSUE THREAD

**Issue by maojindao55** [z-song/laravel-admin#2892]
- Laravel Version: 5.5.0
- PHP Version:7.12
- Laravel-admin: 1.6.7

### Description:

1. 按照文档https://laravel-admin.org/docs/zh安装 laravel-admin, 发现expland扩展无法使用
2. 查了下是项目中缺少demo中的demo.laravel-admin.org/app/Admin/Extensions/Column/ExpandRow.php 插件
3. 官方插件不是在默认安装的时候给加进去吗？难道需要手动cp

**Comment by z-song** [comment]
这不是官方插件，只是一个列扩展的例子放到demo中，不是内置功能
