### ISSUE TITLE
在 grid 中使用 switch 控件更新状态时,  无论是否定义 value 是否设置, 更新时传入后台的值 都是on/off 

### ISSUE THREAD

**Issue by nfangxu** [z-song/laravel-admin#2893]
- Laravel Version: 5.6.39
- php version: php7.2.11
- Laravel-admin: 1.6.8

### Description:
```
        $grid->status('状态')->switch([
            "on" => ["value" => 1, "text" => "正常", "color" => "success"],
            "off" => ["value" => 0, "text" => "禁用", "color" => "danger"],
        ]);
```
> 当我在列表中点击这个控件时, 传入后台的status的值为: `on/off`

**Comment by tiderjian** [comment]
![image](https://user-images.githubusercontent.com/1665649/50590838-81c59080-0ec7-11e9-9856-748a0724d52c.png)
我将 Encore\Admin\Grid\Displayers\SwitchDisplay 对应位置的代码改成了上图的就能正常工作，不知道这样改对不对

**Comment by tiderjian** [comment]
要设置form对应的字段
如：
`$states = [
            "on" => ["value" => 1, "text" => "正常", "color" => "success"],
            "off" => ["value" => 0, "text" => "禁用", "color" => "danger"],
        ];
        $form->switch('status', '状态')->states(states);`

**Comment by nfangxu** [comment]
不是在form中使用switch   而是在个grid中使用

**Comment by tiderjian** [comment]
> 不是在form中使用switch 而是在个grid中使用

是的，我明白你的意思，你是说提交的时候无法正确更新数据库，其实是还需要在form里配置这个switch才能正确更新，文档也有相关的提示。

![image](https://user-images.githubusercontent.com/1665649/50622947-3f926280-0f4c-11e9-8e7d-149c8e348d1d.png)

**Comment by nfangxu** [comment]
@tiderjian 可以了    非常感谢
