### ISSUE TITLE
gird filter使用外部数据源怎么配置

### ISSUE THREAD

**Issue by Tianlong-zhang** [z-song/laravel-admin#2894]
- Laravel Version: 5,6
- PHP Version:7.2
- Laravel-admin: 1.6.7

### Description:
表格使用了外部数据源api
 public function paginate()
    {
        $limit = Request::get('limit', 1000);

        $symbol = Request::get('symbol', "ETHBTC");
        $interval = Request::get('interval', "5m");

        $startTime =strtotime(Request::get('strart_time', date('Y-m-d 00:00:00'))) * 1000;
        $endTime = strtotime(Request::get('end_time', date('Y-m-d H:i:s'))) * 1000;

        $url = "https://api.binance.com/api/v1/klines?symbol=$symbol&interval=$interval&startTime=$startTime&endTime=$endTime&limit=$limit";
        $client = new Client();
        $response = $client->get($url);
        $data = (string)$response->getBody();

        $data = json_decode($data, true);

        foreach ($data as $k => $d) {
            $model['id'] = $k;
            $model['close_time'] = date('Y-m-d H:i:s', $d[6] / 1000);
            $model['close_price'] = $d[4];

            $res[] = $model;
        }

        $total = count($res);

        $paginator = new LengthAwarePaginator(static::hydrate($res), $total, $total);

        $paginator->setPath(url()->current());

        return $paginator;
    }

    public static function with($relations)
    {
        return new static;
    }

controller  grid 方法
                $grid->filter(function($filter){

                // 去掉默认的id过滤器
                $filter->disableIdFilter();
                $filter->equal('symbol', '交易对');
                $filter->equal('interval', '时间间隔')->select([
                                                '1m' => '1m',
                                                '3m' => '3m',
                                            ]);
                $filter->date('strart_time', '开始时间');
                $filter->date('end_time', '结束时间');
                $filter->equal('limit', '上限')->select([
                                            '5' => '5',
                                            '10' => '10',
                                            ]);
            });
### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/26914418/50473447-e5e3e280-09f7-11e9-93da-d398ab69e968.png)
![image](https://user-images.githubusercontent.com/26914418/50473468-f72cef00-09f7-11e9-9bf5-0fc7f821d158.png)

**Comment by Tianlong-zhang** [comment]
重写了model跟where相关的function

**Comment by guijianchou123** [comment]
最终你怎么解决的呢？解决的兄弟能把你的代码贴上来看看吗？不胜感激，同样遇到了相同问题

**Comment by Ifor86** [comment]
@Tianlong-zhang @guijianchou123 你俩这个问题解决了吗？ 有没有 demo 给个参考啊？
