### ISSUE TITLE
hasmany的bug

### ISSUE THREAD

**Issue by soso851213** [z-song/laravel-admin#2895]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
先謝謝大家來看我的問題
我的問題是在ie11使用hasmany的時候，如果裡面有埋select field的話，按新增時會跑出兩個select field，不知道要怎麼處理，希望有大神幫解決，謝謝。

https://drive.google.com/file/d/1TkeiZskUSrcc9CH3hL5fFiDRG2xzZy97/view?usp=sharing
https://drive.google.com/file/d/1ZByI2SaCjo52v0M32VHgeLEiva9doReq/view?usp=sharing

**Comment by RobinHoo1973** [comment]
这个一般是select2初始化js没有完成造成的,看看console那里的js出错导致的
