### ISSUE TITLE
Bug Fix for HasMany/Embeds getValidator() Generating Validator without CustomerMessage Issues

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#2897]
- Laravel Version: 5.7.*
- PHP Version: 7.3.
- Laravel-admin: 1.6.8

### Description:
Any fields within hasMany form cannot display the customer validation message as well as the dateRange/timeRange etc. always get error while other fileds got error.

### FIxed by rewrite the getValidator function in HasMany.php
```
    /**
     * Get validator for this field.
     *
     * @param array $input
     *
     * @return bool|Validator
     */
    public function getValidator(array $input)
    {
        if (!array_key_exists($this->column, $input)) {
            return false;
        }

        $array_key_attach_str = function (array $a, string $b, string $c = '.') {
            return call_user_func_array(
                'array_merge',
                array_map(function ($u, $v) use ($b, $c) {
                    return ["{$b}{$c}{$u}" => $v];
                }, array_keys($a), array_values($a))
            );
        };

        $array_key_clean = function (array $a) {
            $a = count($a) ? call_user_func_array('array_merge', array_map(function ($k, $v) {
                return [str_replace(':', '', $k) => $v];
            }, array_keys($a), array_values($a))) : $a;

            return $a;
        };

        $array_clean_merge = function (array $a, $b) {
            return array_merge($a, call_user_func_array('array_merge', $b));
        };

        $array_key_clean_undot = function (array $a) {
            $keys = preg_grep('/[\.\:]/', array_keys($a));
            if ($keys) {
                foreach ($keys as $key) {
                    array_set($a, str_replace(':', '', $key), $a[$key]);
                    unset($a[$key]);
                }
            }

            return $a;
        };

        $input = array_only($input, $this->column);
        $form = $this->buildNestedForm($this->column, $this->builder);
        $rel = $this->relationName;
        $rules = $attributes = $messages = $newInputs = [];
        // remove all inputs & keys marked as removed
        $availInput = array_filter(array_map(function ($v) {
            return $v[NestedForm::REMOVE_FLAG_NAME] ? null : $v;
        }, $input[$rel]));
        $keys = array_keys($availInput);
        /* @var Field $field */
        foreach ($form->fields() as $field) {
            if (!$fieldRules = $field->getRules()) {
                continue;
            }
            $column = $field->column();
            $columns = is_array($column) ? $column : [$column];
            if ($field instanceof Field\MultipleSelect) {
                foreach ($keys as $key) {
                    $availInput[$key][$column] = array_filter($availInput[$key][$column], 'strlen') ? : null;
                }
            }

            $newColumn = call_user_func_array('array_merge', array_map(function ($u) use ($columns, $rel) {
                return array_map(function ($k, $v) use ($u, $rel) {
                    //Fix ResetInput Function! A Headache Implementation!
                    return $k ? "{$rel}.{$u}.{$v}:{$k}" : "{$rel}.{$u}.{$v}";
                }, array_keys($columns), array_values($columns));
            }, $keys));

            $fieldRules = is_array($fieldRules) ? implode('|', $fieldRules) : $fieldRules;
            $newRules = array_map(function ($v) use ($fieldRules, $availInput, $array_key_attach_str) {
                list($r, $k, $c) = explode('.', $v);
                //Fix ResetInput Function! A Headache Implementation!
                $col = explode(':', $c)[0];
                if (array_key_exists($col, $availInput[$k]) && is_array($availInput[$k][$col])) {
                    return $array_key_attach_str(preg_replace('/./', $fieldRules, $availInput[$k][$col]), $v, ':');
                }

                //May Have Problem in Dealing with File Upload in Edit Mode
                return [$v => $fieldRules];
            }, $newColumn);
            $rules = $array_clean_merge($rules, $newRules);

            $newInput = array_map(function ($v) use ($availInput, $array_key_attach_str) {
                list($r, $k, $c) = explode('.', $v);
                //Fix ResetInput Function! A Headache Implementation!
                $col = explode(':', $c)[0];
                if (!array_key_exists($col, $availInput[$k])) {
                    //May Have Problem in Dealing with File Upload in Edit Mode
                    return [$v => null];
                }

                if (is_array($availInput[$k][$col])) {
                    return $array_key_attach_str($availInput[$k][$col], $v, ':');
                }

                return [$v => $availInput[$k][$col]];
            }, $newColumn);
            $newInputs = $array_clean_merge($newInputs, $newInput);

            $newAttributes = array_map(function ($v) use ($field, $availInput) {
                list($r, $k, $c) = explode('.', $v);
                //Fix ResetInput Function! A Headache Implementation!
                $col = explode(':', $c)[0];
                if (array_key_exists($col, $availInput[$k]) && is_array($availInput[$k][$col])) {
                    return call_user_func_array('array_merge', array_map(function ($u) use ($v, $field) {
                        $w = $field->label();
                        //Fix ResetInput Function! A Headache Implementation!
                        $w .= is_array($field->column()) ? '[' . explode(':', explode('.', $v)[2])[0] . ']' : '';

                        return ["{$v}:{$u}" => $w];
                    }, array_keys($availInput[$k][$col])));
                }

                //May Have Problem in Dealing with File Upload in Edit Mode
                $w = $field->label();
                //Fix ResetInput Function! A Headache Implementation!
                $w .= is_array($field->column()) ? '[' . explode(':', explode('.', $v)[2])[0] . ']' : '';

                return [$v => $w];
            }, $newColumn);
            $attributes = $array_clean_merge($attributes, $newAttributes);

            if ($field->validationMessages) {
                $newMessages = array_map(function ($v) use ($field, $availInput, $array_key_attach_str) {
                    list($r, $k, $c) = explode('.', $v);
                    //Fix ResetInput Function! A Headache Implementation!
                    $col = explode(':', $c)[0];
                    if (array_key_exists($col, $availInput[$k]) && is_array($availInput[$k][$col])) {
                        return call_user_func_array('array_merge', array_map(function ($u) use ($v, $field, $array_key_attach_str) {
                            return $array_key_attach_str($field->validationMessages, "{$v}:{$u}");
                        }, array_keys($availInput[$k][$col])));
                    }

                    //May Have Problem in Dealing with File Upload in Edit Mode
                    return $array_key_attach_str($field->validationMessages, $v);
                }, $newColumn);
                $messages = $array_clean_merge($messages, $newMessages);
            }
        }

        $rules = array_filter($rules, 'strlen');
        if (empty($rules)) {
            return false;
        }

        $attributes = array_filter($attributes, 'strlen');
        $messages = array_filter($messages, 'strlen');
        $input = $array_key_clean_undot(array_filter($newInputs, 'strlen', ARRAY_FILTER_USE_KEY));
        $rules = $array_key_clean($rules);
        $attributes = $array_key_clean($attributes);
        $messages = $array_key_clean($messages);

        if (empty($input)) {
            $input = [$rel => $availInput];
        }

        return Validator::make($input, $rules, $messages, $attributes);
    }


```

**Comment by RobinHoo1973** [comment]
没有解决File在HasMany里验证的问题,这个字段直接找不到$input值

**Comment by RobinHoo1973** [comment]
发现Embeds的getValidator方法有同样的问题,一并修改了
···
    /**
     * {@inheritdoc}
     */
    public function getValidator(array $input)
    {
        if (!array_key_exists($this->column, $input)) {
            return false;
        }

        $input = array_only($input, $this->column);

        $rules = $attributes = $messages = [];
        $rel = $this->column;


        $availInput = $input;
        $array_key_attach_str = function (array $a, string $b, string $c = ".") {
            return call_user_func_array(
                'array_merge',
                array_map(function ($u, $v) use ($b, $c) {
                    return ["{$b}{$c}{$u}" => $v];
                }, array_keys($a), array_values($a))
            );
        };

        $array_key_clean = function (array $a) {
            $a = count($a) ? call_user_func_array('array_merge', array_map(function ($k, $v) {
                return [str_replace(':', '', $k) => $v];
            }, array_keys($a), array_values($a))) : $a;
            return $a;
        };

        $array_key_clean_undot = function (array $a) {
            if (count($a))
                foreach ($a as $key => $val) {
                array_set($a, str_replace(':', '', $key), $val);
                if (preg_match('/[\.\:]/', $key)) {
                    unset($a[$key]);
                }
            }
            return $a;
        };

        /** @var Field $field */
        foreach ($this->buildEmbeddedForm()->fields() as $field) {
            if (!$fieldRules = $field->getRules()) {
                continue;
            }

            $column = $field->column();
            $columns = is_array($column) ? $column : [$column];
            if ($field instanceof Field\MultipleSelect) {
                $availInput[$column] = array_filter($availInput[$column], 'strlen');
                $availInput[$column] = $availInput[$column] ? : null;
            }
            /*
             *
             * For single column field format rules to:
             * [
             *     'extra.name' => 'required'
             *     'extra.email' => 'required'
             * ]
             *
             * For multiple column field with rules like 'required':
             * 'extra' => [
             *     'start' => 'start_at'
             *     'end'   => 'end_at',
             * ]
             *
             * format rules to:
             * [
             *     'extra.start_atstart' => 'required'
             *     'extra.end_atend' => 'required'
             * ]
             */
            $newColumn = array_map(function ($k, $v) use ($rel) {
                //Fix ResetInput Function! A Headache Implementation!
                return !$k ? "{$rel}.{$v}" : "{$rel}.{$v}:{$k}";
            }, array_keys($columns), array_values($columns));

            $fieldRules = is_array($fieldRules) ? implode('|', $fieldRules) : $fieldRules;
            $rules = array_merge($rules, call_user_func_array(
                'array_merge',
                array_map(function ($v) use ($fieldRules) {
                    return [$v => $fieldRules];
                }, $newColumn)
            ));
            $attributes = array_merge($attributes, call_user_func_array(
                'array_merge',
                array_map(function ($v) use ($field) {
                    //Fix ResetInput Function! A Headache Implementation!
                    $u = $field->label();
                    $u .= is_array($field->column()) ? '[' . explode(':', explode('.', $v)[1])[0] . ']' : '';
                    return [$v => "{$u}"];
                }, $newColumn)
            ));
            if ($field->validationMessages) {

                $newMessages = array_map(function ($v) use ($field, $availInput, $array_key_attach_str) {
                    list($rel, $col) = explode('.', $v);
                    //Fix ResetInput Function! A Headache Implementation!
                    $col1 = explode(':', $col)[0];
                    if (!array_key_exists($col1, $availInput[$rel])) return [null => null];
                    $rows = $availInput[$rel][$col1];
                    if (!is_array($rows))
                        return $array_key_attach_str($field->validationMessages, $v);
                    $r = [];
                    foreach (array_keys($rows) as $k) {
                        $k = "{$v}{$k}";
                        $r = array_merge($r, $array_key_attach_str($field->validationMessages, $k));
                    }
                    return $r;
                }, $newColumn);
                $newMessages = call_user_func_array('array_merge', $newMessages);
                $messages = array_merge($messages, $newMessages);
            }
        }

        if (empty($rules)) {
            return false;
        }
        $newInput = call_user_func_array('array_merge', array_map(function ($idx) use ($availInput) {
            list($rel, $col) = explode('.', $idx);
            //Fix ResetInput Function! A Headache Implementation!
            $col1 = explode(':', $col)[0];
            if (!array_key_exists($col1, $availInput[$rel])) return [null => null];
            if (is_array($availInput[$rel][$col1])) {
                return call_user_func_array('array_merge', array_map(function ($x, $y) use ($idx) {
                    return ["{$idx}{$x}" => $y];
                }, array_keys($availInput[$rel][$col1]), $availInput[$rel][$col1]));
            }
            return ["{$idx}" => $availInput[$rel][$col1]];
        }, array_keys($rules)));

        $newInput = $array_key_clean_undot($newInput);
        $newRules = array_map(function ($idx) use ($availInput, $rules) {
            list($rel, $col) = explode('.', $idx);
            //Fix ResetInput Function! A Headache Implementation!
            $col1 = explode(':', $col)[0];
            if (!array_key_exists($col1, $availInput[$rel])) return [null => null];
            if (is_array($availInput[$rel][$col1])) {
                return call_user_func_array('array_merge', array_map(function ($x) use ($idx, $rules) {
                    return ["{$idx}{$x}" => $rules[$idx]];
                }, array_keys($availInput[$rel][$col1])));
            }
            return ["{$idx}" => $rules[$idx]];

        }, array_keys($rules));
        $newRules = array_filter(call_user_func_array('array_merge', $newRules), 'strlen', ARRAY_FILTER_USE_KEY);
        $newRules = $array_key_clean($newRules);;

        $newAttributes = array_map(function ($idx) use ($availInput, $attributes) {
            list($rel, $col) = explode('.', $idx);
            //Fix ResetInput Function! A Headache Implementation!
            $col1 = explode(':', $col)[0];
            if (!array_key_exists($col1, $availInput[$rel])) return [null => null];
            if (is_array($availInput[$rel][$col1])) {
                if (array_keys($availInput[$rel][$col1]))
                    return call_user_func_array('array_merge', array_map(function ($x) use ($idx, $attributes) {
                    return ["{$idx}.{$x}" => $attributes[$idx]];
                }, array_keys($availInput[$rel][$col1])));
                return [null => null];
            }

            return ["{$idx}" => $attributes[$idx]];
        }, array_keys($attributes));
        $newAttributes = array_filter(call_user_func_array('array_merge', $newAttributes), 'strlen');
        $newAttributes = $array_key_clean($newAttributes);

        $messages = $array_key_clean($messages);

        if (empty($newInput)) {
            $newInput = $availInput;
        }
        return Validator::make($newInput, $newRules, $messages, $newAttributes);
    }
···
