### ISSUE TITLE
[HELP] 求助，如何在调用ModelTree之前给模型增加条件

### ISSUE THREAD

**Issue by AugusLarry** [z-song/laravel-admin#290]
大兄弟我又来麻烦您了，我基础不好，还请见谅，谢谢了。
如图：
![qq 20170113214824](https://cloud.githubusercontent.com/assets/9316266/21932154/09dbced2-d9da-11e6-9878-7e68f9247f50.png)

**Comment by z-song** [comment]
可以这样使用：
```php
$model = Category::where('type', 2);

return Admin::tree($model, function (Tree $tree) {
    // ...
})
```

**Comment by AugusLarry** [comment]
我试过了，好像不行。
Category::where('type', 2)返回的是一个\Illuminate\Database\Query\Builder实例，而Admin::tree()方法传入这个$model的时候做了判断
![qq 20170114155319](https://cloud.githubusercontent.com/assets/9316266/21953432/b3c7c8f0-da71-11e6-8805-cae281af0366.png)
就是图片中的地方抛出异常。
不知道是否是版本不同还是其他原因...

**Comment by z-song** [comment]
my bad 那我需要加一个方法来实现这个需求了。

**Comment by z-song** [comment]
已经加上了这个方法：
```php

Category::tree(function ($tree) {

    $tree->query(function ($model) {
        return $model->where('type', 1);
    });

})
```

**Comment by AugusLarry** [comment]
谢谢，真是太效率了！！！
另外还有一个小问题，就是
![qq 20170116111240](https://cloud.githubusercontent.com/assets/9316266/21969874/bcd671be-dbdc-11e6-968a-f866c3b91c7c.png)
这个selectOptions方法可能也有这样的需求。

**Comment by z-song** [comment]
这个倒是没考虑到，多谢提醒！

**Comment by AugusLarry** [comment]
这个selectOptions也弄好了是吗？
怎么使用呢？

**Comment by AugusLarry** [comment]
大兄弟请明示一下，不是很懂怎么在selectOptions里使用条件...

**Comment by z-song** [comment]
我已经提交了更新，在1.3.x-dev版本可以使用：

```php
Category::where('type', 1)->selectOptions();
```

**Comment by fplun** [comment]
这样写没用啊
