### ISSUE TITLE
how to move image or file  from default storage to any other folder ?

### ISSUE THREAD

**Issue by csesumonpro** [z-song/laravel-admin#2900]
- Laravel Version:  5.7 
- PHP Version: 7.2 
- Laravel-admin:  latest 

how to move image or file  from default storage location  to any other folder ?
//Form 
  $form->image('photo', 'Photo')->required()->uniqueName();  // from code 
// filesystem 

 'admin' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'visibility' => 'public',
            'url' => env('APP_URL') . '/uploads',
        ],

// admin.php 

  'upload' => [
        'disk' => 'admin',
    
        'directory' => [
            'image' => 'image',
            'file' => 'file',
        ],

    ],

**Comment by uacode** [comment]
Use [move method](https://laravel-admin.org/docs/#/en/model-form-upload?id=fileimage-upload) and read docs :)

**Comment by csesumonpro** [comment]
I have already used move method it work properly but it's under default storage directory not any other destination.

**Comment by uacode** [comment]
> how to move image or file from default storage location to any other folder ?

1) You need to configure [new location in config/filesystems.php](https://laravel.com/docs/5.7/filesystem)
2) Modify config/admin.php
// Disk in `config/filesystem.php`.
'disk' => 'admin',
3) create symlink
