### ISSUE TITLE
BUG新建或编辑返回时,会调用show()方法

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#2906]
- Laravel Version: 5.7
- PHP Version: 7.3
- Laravel-admin: 1.6.8

### Description:
当调用编辑和创建方法后,在redirectAfterSaving()是会先调用show()方法

### Steps To Reproduce:
删除或注释show()方法,进行操作,会出错提示show()方法不存在

**Comment by RobinHoo1973** [comment]
调试了半天,发现是Pjax调用了show()方法,平时由于show()方法存在没法知晓问题,在重定向前屏蔽了PJAX问题没有了

**Comment by terranc** [comment]
请问具体怎么屏蔽的？
