### ISSUE TITLE
很多地方的中文未显示出来

### ISSUE THREAD

**Issue by yadgen** [z-song/laravel-admin#2912]
- Laravel Version: 5.7.19
- PHP Version: 7.3.0
- Laravel-admin: 1.6

### Description:
很多地方的中文未显示出来，左边菜单，后台首页等等。
config/app.php已经将语言改成zh-CN了。

### Steps To Reproduce:
新安装就会出现。

**Comment by yadgen** [comment]
> 因为这部分没有做多语言版，直接hardcode了英文

好的，谢谢，我想请教你一个问题。
我在使用Jquery pjax和sweetalert2。
加载出来的sweetalert2的中文字，被unicode了。

jquery-pjax Version: [jquery pjax](https://raw.githubusercontent.com/defunkt/jquery-pjax/master/jquery.pjax.js)
sweet-alert Versrion: 7.33.1

**Comment by tiderjian** [comment]
> &#22823;&#23478;&#22909;

这个是转成了utf-8了吧，检查下是不是编码格式不对

**Comment by yadgen** [comment]
> > 大家好
> 
> 这个是转成了utf-8了吧，检查下是不是编码格式不对

我该检查哪里呢？
文件编码，浏览器编码均没问题。

**Comment by yadgen** [comment]
> > 大家好
> 
> 这个是转成了utf-8了吧，检查下是不是编码格式不对

我该检查哪里呢？
文件编码，浏览器编码均没问题。

**Comment by yadgen** [comment]
> > 大家好
> 
> 这个是转成了utf-8了吧，检查下是不是编码格式不对

done, thanks.
