### ISSUE TITLE
form里面如何区分删除图片还是submit?

### ISSUE THREAD

**Issue by aBusyAnt** [z-song/laravel-admin#2923]
请问：form表单的图片字段删除，和submit都会走form->saved()方法，里面如何区分是删除图片还是submit啊？

form表单的图片删除，和submit都会走form方法，由于submit成功的时候需要跳转到指定页面，但是删除图片也会走跳转，就导致删除的response返回了302的跳转数据，json解析出错。

        $form->saved(function (Form $form) {
            return redirect('/admin/xxx');
        });

**Comment by GrayLuo** [comment]
the same as #2436
