### ISSUE TITLE
上传文件保存后，在数据的编辑页文件预览不了 ，PDF 用的是 img标签

### ISSUE THREAD

**Issue by a1300657068** [z-song/laravel-admin#2924]
- Laravel Version: 5.6
- PHP Version:7.1.3
- Laravel-admin: 1.6

### Description:
![image](https://user-images.githubusercontent.com/22309178/50886829-796fd700-142c-11e9-8feb-38f0134aeb8a.png)

**Comment by tiderjian** [comment]
建议你上传其他pdf看看，有可能是你这个pdf无法获取到缩略图，其实这个issue你应该提给bootstrap fileinput

**Comment by a1300657068** [comment]
@tiderjian Thank you 这个问题我已解决，对于这个问题，我昨天晚上进行了源代码的修改
[https://www.jianshu.com/p/dbbbe8d88bd0](url) 这是 solutions
