### ISSUE TITLE
如何在FORM中設置選擇填寫

### ISSUE THREAD

**Issue by z6a3s9dx** [z-song/laravel-admin#2925]
- Laravel Version: 5.7
- PHP Version:7.2
- Laravel-admin: 1.5

### Steps To Reproduce:
$form->text('productsname','材料名稱')->rules('required');

**Comment by tiderjian** [comment]
选择填写，不是应该用select组件吗

**Comment by z6a3s9dx** [comment]
@tiderjian  大大你好，我這邊的意思是說必填跟選填，不好意思說明不夠清楚
這邊我已經找到答案了$form->text('productsname','材料名稱')->rules('nullable')這樣的方式
