### ISSUE TITLE
如何自動產生編號

### ISSUE THREAD

**Issue by z6a3s9dx** [z-song/laravel-admin#2929]
- Laravel Version: 5.7
- PHP Version:7.2
- Laravel-admin: 1.7

### Description:
資料庫中主鍵id是預設成流水號
我想要寫一個訂單系統在其中一個欄位(訂單編號)寫一個自動產生編號，應該怎麼做呢
像是YYMMDD+XXX=190110001

**Comment by z-song** [comment]
试试`$form->text()->default(date('ymd').rand(1,1000));`

**Comment by z6a3s9dx** [comment]
@z-song 感謝大大，想請問您後面的值有甚麼方法可以從001開始計算呢

**Comment by z6a3s9dx** [comment]
$num =DB::table('dc_b1002')->insert(
            array('single_number' => '19011140')
        );
$form->text('single_number','單號')->default(date('ymd').sprintf('%2d',$num));
![image](https://user-images.githubusercontent.com/33858241/51013380-046fdf00-159d-11e9-857e-9c8ec64c01d8.png)

**Comment by mineschan** [comment]
這個應該在saving callback裡做吧

**Comment by extralam** [comment]
in your model 
public static function boot()
    {
        parent::boot();
        self::creating(function ($model) {
            if(empty($model->single_number))
                $model-> single_number = "something you want"
        });
    }
