### ISSUE TITLE
How to filter from an ID passed in a Grid action to another page

### ISSUE THREAD

**Issue by lordjack** [z-song/laravel-admin#2933]
- Laravel Version: 5.5
- PHP Version: 7.1.20
- Laravel-admin: 1.6.7

### Description:
Hi

I'm wanting to pass an id to another page by filtering according to the passed ID Ex:

**area - Main table**
id
name
type_id

**area_type - secondary table**
id
area_id
name

I'm looking for an example, when clicking on an "area" action I can pass the area id and filter "area_type" from this filter. The example I found closest in the demo was the Post and comment.

when opening a post in the demo example through the link below. When you click on any view action, edit or delete the comment, it presents an error, does not open the form nor excludes.
https://demo.laravel-admin.org/posts/1/edit

this error.
https://demo.laravel-admin.org/demo/post-comments/38

I accessed the post controller, but I did not identify the error.
https://github.com/z-song/demo.laravel-admin.org/blob/master/app/Admin/Controllers/PostController.php

Anyone have any tips, thanks?
### Steps To Reproduce:

**Area grid - PostController**

``
 $grid->actions(function (Grid\Displayers\Actions $actions) {
            $actions->append('<a href="area-categoria/'.$actions->getKey().'"><i class="fa fa-paper-plane"></i></a>');
        }); ``

**Area type grid - PostCommentController**

``
  $grid->filter(function ($filter) {
            $filter->like('content');
        });
 ``

**Comment by chiwex** [comment]
this is what i normally do to filter base on the selected field

`    public function gridFilterJavascriptActions(){

        $location = route('marks.index');

        $script = <<<EOT

         $('.class_id').on('change', function(){
              var id = $(this).val();
              window.location = '$location' + '?class_id=' + id;
         });

EOT;

        \Encore\Admin\Facades\Admin::script($script);

    }`

in your filter code work with query string

`$filter->equal('class_id', 'Class')
                    ->select(Clasx::query()
                        ->whereIn('id', $sIds)
                        ->pluck('name', 'id')
                    );
                $filter->equal('section_id', 'Section')->select(Section::query()->pluck('name', 'id'));

                if(request()->has('class_id')){
                    $filter->equal('subject_id', 'Subject')
                        ->select(Subject::query()
                            ->where('teacher_id', Teacher::getTeacherId())
                            ->where('class_id', request()->get('class_id'))
                            ->pluck('name', 'id')
                        );
                }`
