### ISSUE TITLE
Bootstrap 4

### ISSUE THREAD

**Issue by maxlen** [z-song/laravel-admin#2939]
- Laravel Version: 5.7.14
- PHP Version: 7.2.10
- Laravel-admin: 1.6.7

### Description:

Hi.
Could you help me for implement Bootstrap 4 to laravel-admin?
Thanks

**Comment by peacemoon** [comment]
Take a look at this Material UI package to see how others implemented new theme via extension https://github.com/laravel-admin-extensions/material-ui
