### ISSUE TITLE
使用 maatwebsite/excel version 3 后报错

### ISSUE THREAD

**Issue by Hanson** [z-song/laravel-admin#2942]
- Laravel Version: 5.7.20
- PHP Version:  7.2.13
- Laravel-admin: 1.6.8

### Description:

导出报错

![image](https://user-images.githubusercontent.com/10583423/51235353-37094580-19aa-11e9-8891-c3f9c0035e9b.png)

### Steps To Reproduce:

导出处代码 
![image](https://user-images.githubusercontent.com/10583423/51235380-47b9bb80-19aa-11e9-824e-1c2d80bcba75.png)

$this 为当前的 exporter

### 更多线索

\Encore\Admin\Grid\Tools\Paginator :35 行

此处已经是 `Illuminate\Database\Eloquent\Collection` 类，并非分页类了，不知是否导出类影响到

**Comment by liuwei0514** [comment]
同样问题 降级到 maatwebsite/excel 2  但是降级又遇到问题  安装不了

**Comment by Hanson** [comment]
@liuwei0514 我使用 2 版本没有问题

**Comment by liuwei0514** [comment]
composer require maatwebsite/excel 2.1.30

**Comment by huibo0** [comment]
这个问题在3版本有解决方案吗？

**Comment by z-song** [comment]
@Hanson @liuwei0514 @huibo0 version 3用下面的方法解决这个问题
```php
Excel::download($this, '报名表.xlsx')->prepare(request())->send();

exit;
```

下个版本优化一下这一块功能
