### ISSUE TITLE
后台的日志会记录所有的input数据，这样就会有一个安全隐患。password等敏感字段会被记录

### ISSUE THREAD

**Issue by zishang520** [z-song/laravel-admin#2948]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: all

### Description:
后台的日志会记录所有的input数据，这样就会有一个安全隐患。password等敏感字段会被记录

**Comment by z-song** [comment]
打开`config/admin.php`，找到log相关的配置看一下
