### ISSUE TITLE
如何简单点实现excel文件导入到Grid显示

### ISSUE THREAD

**Issue by csgofeng** [z-song/laravel-admin#2957]
- Laravel Version: #.#.#5.7
- PHP Version:7.1
- Laravel-admin: #.#.#1.6

**Comment by FirEarly** [comment]
> * Laravel Version: #.#.#5.7
> * PHP Version:7.1
> * Laravel-admin: #.#.#1.6
> 
> ### Description:框架默认的只有导出的功能，导入的功能应该如何做呢，append一个button，然后写个方法，解析上传的文件，把文件一行一行的数据全部存入数据库，然后刷新页面，grid重新读取model。这是一个好方法吗，感觉笨笨的。
> ### Steps To Reproduce:

有同样的需求！

**Comment by 2601533690** [comment]
有同样的需求
