### ISSUE TITLE
如何直接在grid中直接編輯、新增

### ISSUE THREAD

**Issue by z6a3s9dx** [z-song/laravel-admin#2960]
- Laravel Version: 5.7.13
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
想請教大神，在laravel中應該如何製作出下圖的呈現方式呢

![image](https://user-images.githubusercontent.com/33858241/51522364-26524700-1e64-11e9-9013-aa5b071effcc.png)

**Comment by canon1014** [comment]
新增不太清楚.修改可以参考
>$grid->value(trans("system_config.admin.value"))->editable();  

[官方文档](https://laravel-admin.org/docs/zh/model-grid-column#%E5%85%B6%E5%AE%83%E6%96%B9%E6%B3%95)
