### ISSUE TITLE
Role model 没有 menus()方法?

### ISSUE THREAD

**Issue by aoeng** [z-song/laravel-admin#2966]
给某个角色添加多个菜单
```
        Role::first()->menus()->attach([2, 8, 9, 10, 11, 12]);
```
没有`menus()`方法!

**Comment by lun1bz** [comment]
public function menus() : BelongsToMany
    {
        $pivotTable = config('admin.database.role_menu_table');

        $relatedModel = config('admin.database.menu_model');

        return $this->belongsToMany($relatedModel, $pivotTable, 'role_id', 'menu_id');
    }
是不是少个这个

**Comment by aoeng** [comment]
@z-song 加个关联呗

**Comment by fevwind** [comment]
请在问题解决后关闭它

**Comment by z-song** [comment]
@aoeng 已加上关联，欢迎提交pr
