### ISSUE TITLE
How Can I generate Total Payment In Grid Footer?

### ISSUE THREAD

**Issue by oopmvc** [z-song/laravel-admin#2973]
- Laravel Version: 5.6.*
- PHP Version: 7.*
- Laravel-admin: 1.5.*

### Description:
I would like to make a Footer in Grid - With Addition of any Column, For example, I would like to get Total Number of sales($) in footer from Invoice table? Is this possible?

**Comment by uacode** [comment]
Add ```use (&$count)``` to closure http://php.net/manual/functions.anonymous.php

**Comment by z-song** [comment]
Try this https://github.com/z-song/laravel-admin/issues/2466#issuecomment-419967748

**Comment by oopmvc** [comment]
Thank You very much @z-song  :) Great work. Also, I would like to show/hide column feature, is there any way?

**Comment by NickCoolii** [comment]
@oopmvc is it work at Laravel-admin 1.5.x?
As I can see from commit https://github.com/z-song/laravel-admin/commit/fe99a994fe427ee65d74e5c430f78ea9738c4357 it's refer to v. 1.6.1.

**Comment by oopmvc** [comment]
> @oopmvc is it (total number of sales) work at Laravel-admin 1.5.x?
> As I can see from commit [fe99a99](https://github.com/z-song/laravel-admin/commit/fe99a994fe427ee65d74e5c430f78ea9738c4357) it's refer to v. 1.6.1.

Yes, It work

**Comment by NickCoolii** [comment]
> Yes, It works for me

To be clear: is `composer show encore/laravel-admin` returns you row like this one:
`versions : * v1.5.19`?
Right?
