### ISSUE TITLE
$form->hasMany中字段验证remove

### ISSUE THREAD

**Issue by uhowep** [z-song/laravel-admin#2974]
- Laravel Version: 5.6
- PHP Version: 7.1.19
- Laravel-admin: 1.6.9

### Description:
在含有`hasMany`的`form`中，若点击了`新增/new`后再点击`移除/remove`，则提交的数据中数组仍存在，只是将值`_remove_`置为`1`，这将造成`validate`的时候会一并验证，导致无法成功提交

### Steps To Reproduce:
1. 点击新增得到2组数据：
![_20190128112055](https://user-images.githubusercontent.com/24932775/51812841-39469a80-22ee-11e9-8d56-a56f6fcee89f.png)

2. 点击移除移除第2组数据：
![2](https://user-images.githubusercontent.com/24932775/51812878-5d09e080-22ee-11e9-812f-8176752d0ffa.png)

3. 点击提交，被移除的第2组数据会经过验证，导致无法成功提交，且也无法显示出无法通过验证规则时的`message`信息（因为被移除的那一组数据未显示出来）

**Comment by uhowep** [comment]
目前处理方式：在`HasMany.php`文件中的`106行`加入如下代码，去掉`input`中`_remove_=1`的数组
```
    // remove 
    foreach ($input[$this->column] as $ikey => $ivalue) {
        if (isset($ivalue[NestedForm::REMOVE_FLAG_NAME]) && $ivalue[NestedForm::REMOVE_FLAG_NAME]==1) {
            unset($input[$this->column][$ikey]);
        }
    }
```

**Comment by miurabo** [comment]
@uhowep 
Thank you.
I did well

**Comment by LeeDawson** [comment]
我今天也遇到了这个bug 啥时候修复呢？用楼上的办法也成，直接 HasMany.php 461  行

 $(this).closest('.has-many-{$this->column}-form').hide(); 换成下面这行删除掉也行
  $(this).closest('.has-many-{$this->column}-form').remove();


作者有时间合并一下吧

**Comment by miurabo** [comment]
@LeeDawson

1. I Created app\Admin\Extensions\FixedHasMany.php
extends HasMany, override getValidator()
add
```
        // remove
        foreach ($input[$this->column] as $ikey => $ivalue) {
            if (isset($ivalue[NestedForm::REMOVE_FLAG_NAME]) && $ivalue[NestedForm::REMOVE_FLAG_NAME] == 1) {
                unset($input[$this->column][$ikey]);
            }
        }
```
2. add app\Admin\bootstrap.php
```
Encore\Admin\Form::extend('fixedHasMany', FixedHasMany::class);
```

I try pr
but, Not yet authorized. 
because he can't reproduce this problem.

https://github.com/z-song/laravel-admin/pull/3215#event-2308369791
