### ISSUE TITLE
'Reset' button is not working for select/Multiple select in Form method

### ISSUE THREAD

**Issue by Makennsky** [z-song/laravel-admin#2975]
- Laravel Version: 5.7.*
- PHP Version: 7.1.3
- Laravel-admin: 1.6

### Description:
'Reset' button is not working for select/Multiple select in Form method

### Steps To Reproduce:
when I create something in the form method, then pressing the reset button all is reset except for select/multipleSelect

**Comment by beniaminorossini** [comment]
As a workaround, you can place that in bootstrap.php
`\Encore\Admin\Admin::script(
/** @lang JavaScript */
    <<<EOT
$( "button:reset" ).on('click',function(){
    $('.select2-hidden-accessible').val(null).trigger('change');
});
EOT
);
`
