### ISSUE TITLE
jquery  即時計算

### ISSUE THREAD

**Issue by z6a3s9dx** [z-song/laravel-admin#2982]
- Laravel Version: 5.7
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
請問圖片中我的"單價"跟"數量"在第一筆的時候可以自動相乘，但是要在新增第二筆或以上的時候時"單價"跟"數量"卻不會再自動相乘，這是我寫的方式有問題嗎，請求協助><"
![image](https://user-images.githubusercontent.com/33858241/52025167-64bfc400-253e-11e9-8bea-25d3817d361e.png)
下圖是我的程式碼
![image](https://user-images.githubusercontent.com/33858241/52025197-7a34ee00-253e-11e9-963e-2aa835b66405.png)

**Comment by extralam** [comment]
hints: 
1. 你知道 CSS Class 與 CSS ID , 一個html page 可以有多少相同CSS ID?

提外話, 你是如何增加多一筆資料?
