### ISSUE TITLE
关于无限极分类:ModelTree

### ISSUE THREAD

**Issue by lpx20000** [z-song/laravel-admin#299]
```
/**
     * @var string
     */
    protected $titleColumn = 'title';

    /**
     * @var string
     */
    protected $orderColumn = 'order';
```

在使用Tree方法的过程中，发现以上的column是写死的，虽然可以自己覆盖更改`allNodes`方法更改查找操作，但是以上这些属性，无法重写覆盖，导致建表时，必需有这些字段，感觉有点没必要，当然，除非自己重新实现`buildNestedArray`方法，重新更改，但是感觉没必要，。我看下源码不知有没找错，如果是这样，能否更改下？

**Comment by z-song** [comment]
可以修改 https://github.com/z-song/laravel-admin/blob/master/docs/zh/model-tree.md#表结构和模型

如果不能，更新一下包

**Comment by lpx20000** [comment]
好的。谢谢
