### ISSUE TITLE
Upload the project to the hosting, and failed trans button translation method

### ISSUE THREAD

**Issue by lordjack** [z-song/laravel-admin#2994]
- Laravel Version: 5.5.4
- PHP Version: 7.1
- Laravel-admin: 1.6.7

### Description:
Upload the project to the hosting, and all the buttons stayed like this, does anyone know how do I resolve?

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/6691621/52280980-d8e1d980-293b-11e9-889b-d733120f412c.png)

![image](https://user-images.githubusercontent.com/6691621/52281348-b8664f00-293c-11e9-8eec-13111c97c74a.png)

**Comment by uacode** [comment]
https://github.com/z-song/laravel-admin/issues/2370#issuecomment-415810843 Try this

**Comment by lordjack** [comment]
> 
> 
> [#2370 (comment)](https://github.com/z-song/laravel-admin/issues/2370#issuecomment-415810843) Try this

@uacode Unfortunately it did not work. 

Was there any more clue what I could do?

I ran the command as @z-song spoke and did not work. Continued with the same problem

`php artisan vendor:publish --tag=laravel-admin-lang`

**Comment by uacode** [comment]
@lordjack You need open your console terminal (SSH), on hosting or PC. Next you should go to project directory and run artisan command

Like this:
```
cd /home/user/my_project_folder
php artisan vendor:publish --tag=laravel-admin-lang
```

**Comment by lordjack** [comment]
> 
> 
> > [#2370 (comment)](https://github.com/z-song/laravel-admin/issues/2370#issuecomment-415810843) Try this
> 
> @uacode Unfortunately it did not work.
> 
> Was there any more clue what I could do?
> 
> I ran the command as @z-song spoke and did not work. Continued with the same problem
> 
> `php artisan vendor:publish --tag=laravel-admin-lang`

I was able to identify the problem, as I was working on the site, I had put the following configuration /config/App.php
Was:
     'locale' => 'pt-br',
     'fallback_locale' => 'pt-br',
The correct is:
    'locale' => 'en-BR',
     'fallback_locale' => 'pt-BR',

I missed the BR in Caps Lock, I made the change and it worked.

Thanks for the help anyway.
