### ISSUE TITLE
Search in Models

### ISSUE THREAD

**Issue by amirbagh75** [z-song/laravel-admin#2997]
- Laravel Version: 5.7.21
- PHP Version:  PHP/7.3.1
- Laravel-admin: 1.6.9

### Description:
hi. 
How can we have that?
https://docs.djangoproject.com/en/dev/ref/contrib/admin/#django.contrib.admin.ModelAdmin.search_fields

for example:
in book form, search in all authors and select one or two ... (for relations)

**Comment by z-song** [comment]
https://laravel-admin.org/docs/#/en/model-form-fields?id=select 

Can load select options by ajax request.

**Comment by pcfjojo** [comment]
@z-song looks like, Select input does not active in Data form model for some reason.
