### ISSUE TITLE
多文件或多图片

### ISSUE THREAD

**Issue by ilessy** [z-song/laravel-admin#3]
现在的File和Image模块好像只能处理一对一关系. 也就是说我的一篇文章只能附加一个文件或者一张图片.
但多数时候我会想要附加不止一个, 请问有什么思路可以解决这样的问题吗? 谢谢.

**Comment by z-song** [comment]
这个功能还在规划中，打算在接下来的小版本中实现。

**Comment by ilessy** [comment]
真是太感谢了, 刚才我又找到了一个毛子开发的后台系统, 还在DEV中, 不过我把他的DEMO在本地跑了一下之后发现他们已经实现了多图的上传功能. 所以我想推荐你参考一下. 帮助你更好的规划.
```
Repo:  https://github.com/LaravelRUS/SleepingOwlAdmin
Demo: https://github.com/LaravelRUS/SleepingOwlAdminDemo
```

**Comment by z-song** [comment]
事实上laravel-admin就是参考[SleepingOwlAdmin](https://github.com/sleeping-owl/admin)和[rapyd-laravel](https://github.com/zofe/rapyd-laravel)这两个包开发的，慢慢把它们的功能吸收进来，再加入自己的idea。

**Comment by ilessy** [comment]
恩不过好像你给的SleepingOwlAdmin的地址他们已经不maintain了转到了新的我刚才发的那个.
然后他们提到用的js上传plugin是[flow.js](https://github.com/flowjs/flow.js)
看上去好像很流行的样子

**Comment by z-song** [comment]
现在用另一种方式实现了一对多的功能

在model里面定义好关系：
```php
// Article.php

public function comments()
{
    return $this->hasMany(Comment::class);
}
```
然后后在`form`里面
```php
$form->hasMany('comments', function(Grid $grid) {

     // Set resource path for items.
    $grid->resource('admin/article-comments');

    $grid->id('ID');

    $grid->content()->value(function($content) {
        return mb_strimwidth($content, 0, 40, '...');
    });
});
```

**Comment by caicaizi251** [comment]
我在控制器的form()里面加入如下代码：
```php
  $form->hasMany('floorprods', function(Grid $grid) {
                // Set resource path for items.
               
            });
```
报错如下：
 ErrorException In FloorController.php line 96 :
Argument 1 passed to App\Admin\Controllers\Floor\FloorController::App\Admin\Controllers\Floor\{closure}() must be an instance of Encore\Admin\Grid, instance of Encore\Admin\Form\NestedForm given (View: E:\xampp\www\xzshop\resources\views\admin\form.blade.php)
