### ISSUE TITLE
刪除圖片出現SQL BUG

### ISSUE THREAD

**Issue by jim515jim** [z-song/laravel-admin#3009]
- Laravel Version: 5.7
- PHP Version: 7.3
- Laravel-admin: 1.6

### 描述:
protected function form()
    {
        $form = new Form(new Flexslider);

        $form->text('flexslidername', '圖片名稱');
        $form->file('image_column', '圖片路徑')->uniqueName();
        return $form;
    }

刪除時出現
"message": "SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'image_column' cannot be null (SQL: update `flexsliders` set `image_column` = , `updated_at` = 2019-02-13 16:44:20 where `id` = 1)",

**Comment by uacode** [comment]
Add null by default, to table structure

**Comment by jim515jim** [comment]
> 默認情況下，為表結構添加null

感謝處理完成了

**Comment by uacode** [comment]
:)

Close issue plz
