### ISSUE TITLE
关于关联关系的一些问题

### ISSUE THREAD

**Issue by tanchengjin** [z-song/laravel-admin#3011]
如果我有一个A（文章）表与I（图片）表，关系是一个文章对应一个图片。在laravel-admin中创建文章时如何让I表入库之后返回id并插入到A表的img_id字段呢?

**Comment by hui-ho** [comment]
可以使用模型表单回调处理：

```php
// 保存前回调
$form->saving(function (Form $form) {
    // ...
});
```
- [文档链接](https://laravel-admin.org/docs/zh/model-form-callback)

**Comment by kaodouqifei** [comment]
@hui-ho 那回显的时候呢

**Comment by kaodouqifei** [comment]
@tanchengjin 有解决方法了吗
