### ISSUE TITLE
文档里面[扩展开发]里面发布扩展描述有误

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3015]
原文:
安装完成之后，运行php artisan vendor:publish --provider=Encore\PHPInfo\PHPInfoServiceProvider.php，文件将会复制到public/vendor/laravel-admin-ext/phpinfo目录中。
应该是:
`php artisan vendor:publish --provider=Encore\PHPInfo\PHPInfoServiceProvider`吧
带'.php'后缀试了很多次都没发布成功,仅显示'Publishing complete.'，但资源没移动到对应目录。
不加后缀一次就成功。

**Comment by z-song** [comment]
已修正  谢谢提醒
