### ISSUE TITLE
如何在模型内直接返回错误

### ISSUE THREAD

**Issue by CrazyCodes** [z-song/laravel-admin#3017]
![image](https://user-images.githubusercontent.com/9151227/52942776-9d68f580-33a6-11e9-87c8-463a3a5be003.png)

在model中使用back，return后依旧会继续执行

**Comment by wangshuo2333** [comment]
模型不能直接返回错误，因为模型只是一个被调用的方法

**Comment by CrazyCodes** [comment]
好的，谢谢
