### ISSUE TITLE
图片/文件 删除（垃圾桶图标）按钮无法隐藏

### ISSUE THREAD

**Issue by almas1992** [z-song/laravel-admin#3024]
- Laravel Version: 5.5.45
- PHP Version:7.1
- Laravel-admin: 1.6.9

### Description:
`thumbnail`字段是非空字段，所以一旦按了垃圾桶图标，就会报错，我跟踪源码，`showRemove`  值明明是 `false` 可图标还是会显示出来。

```php
$form->image('thumbnail', '缩略图')
            ->move('img/news')
            ->uniqueName()
            ->rules('required')
            ->help('请上传 345 * 495 像素大小的图片。');
```
![image](https://user-images.githubusercontent.com/9382335/53142854-6bd37280-35d0-11e9-8230-e31141716ab5.png)

**Comment by piaohan** [comment]
关注中

**Comment by piaohan** [comment]
问题同上

**Comment by kongxu633** [comment]
->options(['fileActionSettings' => ['showRemove' => false, 'showDrag' => false]])

**Comment by piaohan** [comment]
@kongxu633 tanks
