### ISSUE TITLE
Show and hide  $form->text on based on radio button selection

### ISSUE THREAD

**Issue by koussaimb** [z-song/laravel-admin#3029]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
Hi 
 have two $ form-> text()
 I would like to show and hide depending on the selection of the radio buttons.

I managed to show and hide using JS but I can not perform the addition because it does not recognize the names and ids of the inputs

sorry for my English

**Comment by koussaimb** [comment]
$form->html(function () use ($form){
                    return '<div id="ifYes" style="display:none">
                    <div class="form-group 1">
                        <label for="test" class="col-sm-2 control-label">Test</label>
                        <div class="col-sm-8">
                            <div class="input-group">
                                 <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                                 <input type="text" id="test" name="test" value="" class="form-control" >
                            </div>
                        </div>
                    </div> ';
                });

$form->html(function () use ($form){
                    return '<div id="ifNo" style="display:none">
                    <div class="form-group 1">
                        <label for="test" class="col-sm-2 control-label">Test1</label>
                        <div class="col-sm-8">
                            <div class="input-group">
                                 <span class="input-group-addon"><i class="fa fa-pencil"></i></span>
                                 <input type="text" id="test1" name="test1" value="" class="form-control" >
                            </div>
                        </div>
                    </div> ';
                });

**Comment by mehdi89** [comment]
I am looking for a solution for such a case. Can anyone help me with how to implement this?
