### ISSUE TITLE
[BUG]form下的value方法在编辑页无法正确使用（The value function of model-form can't work expectantly）

### ISSUE THREAD

**Issue by lenkaren** [z-song/laravel-admin#303]
在新建的时候，value方法是可以按预期生效的，但是在编辑功能的时候就会有问题。

比如在form控制器使用如下代码：
`$form->hidden('user_id')->default(4);$form->hidden('updated_user_id')->value(3);`

在create页会正常工作
`<input type="hidden" name="user_id" value="4">
<input type="hidden" name="updated_user_id" value="3">
`

在edit页则value方法不正常（读取的仍旧数据库的记录2），无法按预期效果修改更新update用户的记录
`<input type="hidden" name="user_id" value="2">
<input type="hidden" name="updated_user_id" value="2">
`

**Comment by z-song** [comment]
已修复
