### ISSUE TITLE
没有做后台校验？？

### ISSUE THREAD

**Issue by zhusaidong** [z-song/laravel-admin#3030]
- Laravel Version:  5.5.44
- PHP Version:7.1.8
- Laravel-admin: 1.6.9

### Description:
新建管理员，输入存在的用户名，没有`用户名已存在`的提醒，而是直接报了一个sql错误

### Steps To Reproduce:
![qq 20190223113328](https://user-images.githubusercontent.com/3039961/53281155-e16d4900-375e-11e9-9005-32daa0195dfe.png)

**Comment by nkjackzhang** [comment]
加一个unique的rule试试看

**Comment by z-song** [comment]
提交了修复，等下个版本发布
