### ISSUE TITLE
编辑无法显示图片

### ISSUE THREAD

**Issue by haoyq02** [z-song/laravel-admin#3042]
- Laravel Version: 5.7.28
- PHP Version: 7.1
- Laravel-admin: 1.6.9

编辑时，不显示图片，只显示文件名。
图片是可以正常访问的，在列表、详情中都可以显示。

`$form->image('image', '图片')->uniqueName()->removable()->rules('required', ['required' => '请填写完整！']);`

![2019-03-04 4 50 59](https://user-images.githubusercontent.com/45658979/53721289-cf498400-3e9d-11e9-998f-2fbe1bff94b7.png)

**Comment by haoyq02** [comment]
![2019-03-04 4 50 59](https://user-images.githubusercontent.com/45658979/53721271-bf31a480-3e9d-11e9-9791-e0543495cdf7.png)

**Comment by haoyq02** [comment]
是否和 **Homestead** 有冲突？
本地无法显示，在其他环境可以显示。

**Comment by ichynul** [comment]
我觉得是原始图片名字里面有中文，就不显示预览。

**Comment by haoyq02** [comment]
> 我觉得是原始图片名字里面有中文，就不显示预览。

原始图片中没有中文

**Comment by l3n641** [comment]
我今天也遇到和你同样的情况,编辑图片后无法显示.然后我php artisan admin:uninstall ,再重新安装的时候抛出异常,
`Migrating: 2016_01_04_173148_create_admin_tables

   Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `username` varchar(190) not null, `password` varchar(60) not null, `name` varchar(255) not null, `avatar` varchar(255) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at /Users/lengai/lavavel_test/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
    660|         // If an exception occurs when attempting to run a query, we'll format the error
    661|         // message to include the bindings with SQL, which will make this exception a
    662|         // lot more helpful to the developer instead of just the database's errors.
    663|         catch (Exception $e) {
  > 664|             throw new QueryException(
    665|                 $query, $this->prepareBindings($bindings), $e
    666|             );
    667|         }
    668|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''")
      /Users/lengai/lavavel_test/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''")
      /Users/lengai/lavavel_test/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61

  Please use the argument -v to see more details.`

**Comment by BlackHades** [comment]
i am having this same issue, any help

**Comment by BlackHades** [comment]
> 
> 
> 我今天也遇到和你同样的情况,编辑图片后无法显示.然后我php artisan admin:uninstall ,再重新安装的时候抛出异常,
> `Migrating: 2016_01_04_173148_create_admin_tables
> 
> Illuminate\Database\QueryException : SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name '' (SQL: create table `` (`id` int unsigned not null auto_increment primary key, `username` varchar(190) not null, `password` varchar(60) not null, `name` varchar(255) not null, `avatar` varchar(255) null, `remember_token` varchar(100) null, `created_at` timestamp null, `updated_at` timestamp null) default character set utf8mb4 collate 'utf8mb4_unicode_ci')
> 
> at /Users/lengai/lavavel_test/vendor/laravel/framework/src/Illuminate/Database/Connection.php:664
> 660| // If an exception occurs when attempting to run a query, we'll format the error
> 661| // message to include the bindings with SQL, which will make this exception a
> 662| // lot more helpful to the developer instead of just the database's errors.
> 663| catch (Exception $e) {
> 
> > 664|             throw new QueryException(
> > 665|                 $query, $this->prepareBindings($bindings), $e
> > 666|             );
> > 667|         }
> > 668|
> 
> Exception trace:
> 
> 1 Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''")
> /Users/lengai/lavavel_test/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:63
> 
> 2 PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1103 Incorrect table name ''")
> /Users/lengai/lavavel_test/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:61
> 
> Please use the argument -v to see more details.`

Just run php artisan config:clear and try the command again. that fixed it for me
