### ISSUE TITLE
方法不起效，不报错

### ISSUE THREAD

**Issue by luvvien** [z-song/laravel-admin#3046]
- Laravel Version: 5.6.*
- PHP Version: 7.1.3
- Laravel-admin: 1.6

### Description: 由于我的create和edit不一样，所以我不能只写一个form方法解决，于是我价格一个newForm方法，让create用，类似于这样
```
public function create(Content $content)
    {
        return $content
            ->header('Create')
            ->description('description')
            ->body($this->newForm());
    }
```
开始工作的还好好地，有一天我要修改这个newForm方法，添加markdown编辑，然后奇怪的事情发生了，所有回调方法不执行，比如saving，submited这些方法都不执行，我直接在这些方法里面写exit也没用。而且我集成了markdown，提交的时候这些markdown字段也都没有。怎么改都不行。最后我把newFrom的名字换成了form，用老外的话说就是 it worked！
这是什么情况啊。

另外 添加markdown的时候 最初我是自定义组件的方式，然而却一直不工作，页面也不显示，而且我在自定义组件类里 添加的 js代码 也不执行，变量 $js $css引入的文件 也都没有加载。同样的问题也出现在我之前集成富文本编辑器。自定义组件的集成参考了：https://vien.tech/article/103
[集成uEditor](https://vien.tech/article/103)  

还有就是之前上传文件也是一样的，也不提示上传失败，却总是没有上传，数据库也没有存那么个字段，最主要的是从不报错，包括上面的组件集成，从不报错但是就是不成功。

这真的让我很头疼，遇到好多次这种问题了，不报错但是却不成功，只能自己瞎折腾，最后可能就成功了

**Comment by z-song** [comment]
表单数据的创建和更新是依赖当前的form的，打开当前控制器引入的HasResourceActions看看
里面的update和store方法就是用来处理更新和创建操作的

你要做的是在当前控制器重写store方法在里面使用`$this->newForm()->store()`
