### ISSUE TITLE
How can I show multi column on grid uging same name

### ISSUE THREAD

**Issue by KenichiKajiwara** [z-song/laravel-admin#3049]
- Laravel Version: 5.7.27
- PHP Version: 7.3.2
- Laravel-admin: 1.6.9

### Description:
I want to adding same column on grid.
example:

        $grid = new Grid(new TestTable);

        $grid->column('Id','id1')->display(function($id)) {
            return Test2::getValue1($id);
        };

        $grid->column('Id','id2')->display(function($id)) {
            return Test2::getValue2($id);
        };

the result I expect is
> | id1　　| id2　　|
> | test123| test789|

but actual result is
> | id1　　| id2　　|
> | test789| test789|

How can I output the results as expected?

**Comment by z-song** [comment]
Try this
```php
    $grid->column('id2','id2')->display(function($id)) {
        return Test2::getValue2($this->id);
    };
```

**Comment by KenichiKajiwara** [comment]
Thank you for reply.

I tried your suggestion.
I can!

Thank you.
