### ISSUE TITLE
吐个槽，laravel-admin如果能解决The page has expired due to inactivity.就好了

### ISSUE THREAD

**Issue by lujscn** [z-song/laravel-admin#3051]
首先这个问题很多人反馈过了，但是一直还没有修复。
登录到laravel-admin后出现：
The page has expired due to inactivity. 
Please refresh and try again.

刷新没有用，只有把浏览器相关的cookies删除才能临时解决，
这个情况在我这里出现的场景是：前台 xxx.com用了laravel默认的登录验证，后台 xxx.com/admin用的是laravel-admin，前台后台都登录后，就有可能出现后台登录不了的情况。

希望下一版的laravel-admin能直接用laravel默认的登录验证，这样前后台登录就不冲突了。

因为这个问题，我一度想逃离laravel-admin改用nova，但是用了一段时间nova后，发现还是laravel-admin好，希望laravel-admin这致命bug能改正。

**Comment by z-song** [comment]
@lujscn 已经提交了修复，待下个版本发布

**Comment by Linlt1** [comment]
现在所有项目的laravel-admin无法使用，清除了cookie也没用，怎么解决？一样是报错 The page has expired due to inactivity.Please refresh and try again.

**Comment by langeuh** [comment]
Please revert this commit
[https://github.com/luomoxu/laravel-admin/commit/f85c01e1e5208d9c5bfd86ea78ace2ca77bf5440#commitcomment-33029952](url)

**Comment by ligaofeng** [comment]
还是没修复，下载的最新的样例代码，并升级到1.18.4后一样报

**Comment by ligaofeng** [comment]
必报的场景是：先用php artisan serve方式启动，成功登录后台后，然后再通过nginx配置虚拟domain访问，再登录，必报

**Comment by ligaofeng** [comment]
还是没修复，下载的最新的样例代码，并升级到1.18.14后一样报
