### ISSUE TITLE
Getting error in admin users edit page  (ErrorException In Macroable.php)

### ISSUE THREAD

**Issue by siavashgolabi** [z-song/laravel-admin#3059]
- Laravel Version:  5.7.26
- PHP Version: 7.1.9
- Laravel-admin: 1.6.9

### Description:
When I go to /admin/auth/users/{id}/edit
I see this error:

     ErrorException In Macroable.php line 100 :

     Method Illuminate\Database\Eloquent\Collection::getKey does not exist. (View: C:\wamp64\www\project\vendor\encore\laravel-admin\resources\views\form.blade.php)

**Comment by llz** [comment]
@siavashgolabi Check your "app\Providers\RouteServiceProvider.php" file,do you defined a explicit model binding of  "user"  in the boot method?if so,comment that and try again.

**Comment by siavashgolabi** [comment]
create and grid work fine but I get 404 error on edit page
