### ISSUE TITLE
form-image不支持rules

### ISSUE THREAD

**Issue by hulkwan** [z-song/laravel-admin#306]
form-image不支持rules，不能添加验证规则

**Comment by z-song** [comment]
刚测试了
```php
$form->image('image')->rules('max:10');
```
能正常使用，你的规则是什么？

**Comment by hulkwan** [comment]
required

**Comment by hulkwan** [comment]
$form->image('profile.face_card_img', '身份证照片-正面')->move(config('ytl.img_path.identity'))->help('jpg、peg、png格式')->rules('required');

**Comment by z-song** [comment]
已修复 谢谢反馈

**Comment by zxy198717** [comment]
@z-song 设置`rules('required')`, 在编辑模式下，不修改图片直接提交，会提交不成功，报 `field is required` 可否看下?
