### ISSUE TITLE
BatchAction label的翻译问题

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3062]
https://github.com/z-song/laravel-admin/blob/f412485946265f9a8fd3bfb53071ff43bec9a56c/src/Grid/Tools/BatchActions.php#L42

翻译文件里面有`'batch_delete' => '批量删除',`
但未使用这个，却使用`trans('admin.delete')`

**Comment by z-song** [comment]
已提交修复，谢谢
