### ISSUE TITLE
Select readonly bugfix

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#3064]
- Laravel Version: 5.8.0
- PHP Version: 7.3
- Laravel-admin: 1.6.*

### Description:
Select 没法实现readonly不是disable,提交PR都没法通过,分享在这里吧

### BugFix
```
    public function readonly()
    {
        $script = <<<EOT
        $("form select").on("select2:opening", function (e) {
    if($(this).attr('readonly') || $(this).is(':hidden')){
        e.preventDefault();
    }
});
EOT;
        Admin::script($script);
        $this->attribute('readonly');
        return $this;
    }
```

**Comment by z-song** [comment]
@RobinHoo1973 你之前提交的pr修改的内容比较多，合并风险比较大，所以建议可以每次可以创建一个分支来修复一个问题，这样更容易验证修复

另外非常感谢对这个项目的支持！

**Comment by RobinHoo1973** [comment]
> @RobinHoo1973 你之前提交的pr修改的内容比较多，合并风险比较大，所以建议可以每次可以创建一个分支来修复一个问题，这样更容易验证修复
> 
> 另外非常感谢对这个项目的支持！

我这里重新提交了HasMany/Embed字段无法正确显示自定义验证消息的问题
https://github.com/z-song/laravel-admin/pull/3036
还有一个错误显示重复的PR
https://github.com/z-song/laravel-admin/pull/3036
以及目前关于Select字段功能补全的PR
https://github.com/z-song/laravel-admin/pull/3039
如果可以通过的话最好了,不然我都有自建一个源的心了

**Comment by z-song** [comment]
@RobinHoo1973 比如#3039这个修复，还是包含了其它问题修复的代码。希望修改的代码只是涉及到这一个问题的修复

**Comment by RobinHoo1973** [comment]
> @RobinHoo1973 比如#3039这个修复，还是包含了其它问题修复的代码。希望修改的代码只是涉及到这一个问题的修复

好的我来拆一下

**Comment by RobinHoo1973** [comment]
@z-song 更新了单独修订了
另外能否看看HasMany和Embed的修正啊,这是个大修订,很多地方都用的

**Comment by z-song** [comment]
@RobinHoo1973 我已经参考你的代码 提交了一个commit了 496db05ef2329078d7112992b89645c0c8c11e8b

**Comment by RobinHoo1973** [comment]
> @RobinHoo1973 我已经参考你的代码 提交了一个commit了 [496db05](https://github.com/z-song/laravel-admin/commit/496db05ef2329078d7112992b89645c0c8c11e8b)

我看到了,不过哪个没有考虑MulipleSelect

**Comment by RobinHoo1973** [comment]
@z-song 不好意思,之前branch都push到了origin,所以新开的branch 都带过去了,现在重新搞了一遍,应该好了
