### ISSUE TITLE
upload image not mime image/webp

### ISSUE THREAD

**Issue by jlwgeneral** [z-song/laravel-admin#3066]
- Laravel Version: 5.6
- PHP Version:7.1
- Laravel-admin: 1.6.10

### Description:
Using lavaravel validation, images in the last webp format could not be validated

**Comment by z-song** [comment]
Try following:
```php
$form->image('xx')->rules(function () {
    return 'mimes:jpeg,bmp,png,gif,svg,webp';
});
```

**Comment by jlwgeneral** [comment]
I have try，but it doesn't work

**Comment by jlwgeneral** [comment]
I try
### $form->image('image', '图片')->uniqueName()->rules(function (){
                return 'mimes:jpeg,bmp,png,gif,svg,webp';
            });
is ok, thank you!

**Comment by jlwgeneral** [comment]
I try:

$form->image('image', '图片')->uniqueName()->rules(function (){
            return 'mimes:jpeg,bmp,png,gif,svg,webp';
        });

is ok, thank you!

**Comment by jlwgeneral** [comment]
I try:

### 
$form->image('image', '图片')->uniqueName()->rules(function (){
return 'mimes:jpeg,bmp,png,gif,svg,webp';
});

is ok, thank you!

**Comment by jlwgeneral** [comment]
I try:

**$form->image('image', '图片')->uniqueName()->rules(function (){
       return 'mimes:jpeg,bmp,png,gif,svg,webp';
});**

is ok, thank you!

**Comment by jlwgeneral** [comment]
I try:

```
$form->image('image', '图片')->uniqueName()->rules(function (){
return 'mimes:jpeg,bmp,png,gif,svg,webp';
});
```

is ok, thank you!

**Comment by jlwgeneral** [comment]
#

**Comment by toknT** [comment]
![image](https://user-images.githubusercontent.com/15935037/76676221-46127480-65fc-11ea-8742-abd5212bd992.png)
```php
$form->image('icon', __('admin.icon'))->rules(function () {
            return 'mimes:jpeg,bmp,png,gif,svg,webp';
        });
```
v1.7.13  laravel admin 依然有问题.
