### ISSUE TITLE
用resource创建的路由，无法在设置权限时匹配到路由里的参数。

### ISSUE THREAD

**Issue by lllllxz** [z-song/laravel-admin#3067]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
通过resouce生成的路由，其中有两个路由：详情页的/admin/customer/{customer} ， 和编辑页的/admin/customer/{customer}/edit。看到过有兄弟有  *  代替参数。但是这种情况，如果用 * 替代参数 会导致编辑页路由权限毫无意义。请大佬告知！急求！项目搞不下去了！！！

**Comment by z-song** [comment]
说清楚一点？

**Comment by lllllxz** [comment]
> 说清楚一点？

在后台默认的权限管理系统中，如果要进行以下设置：
用户A  要给他查看详情的权限。  （/admin/customer/{customer}）
用户B  要给他编辑的权限。   （/admin/customer/{customer}/edit）  
如果我给A设置  /admin/customer/*    ，那么A也拥有编辑的权限了。

**Comment by ichynul** [comment]
创建权限 `customer-edit`
编辑页面
```php
if(!Admin::user()->can('customer-edit'))
{
      //无权操作
}
```
这样行不

**Comment by tangyus** [comment]
我也遇到了同一样的问题，估测是路由的中间件直接拦截下来了，根本还没有到达控制器的 `show` 方法中去，请问是怎么解决的呢?
