### ISSUE TITLE
模型设置了getRouteKeyName但是编辑链接不起作用

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#3078]
- Laravel Version: 5.7.8
- PHP Version:7.2
- Laravel-admin: 1.6.10

### Description:
在模型里设置了getRouteKeyName为uuid,应该在编辑显示链接为/projects/{uuid}/edit,但是还是显示id,安全性问题,当然这里的uuid和id一样都是唯一的可以作为主键

**Comment by RobinHoo1973** [comment]
BugFix:https://github.com/z-song/laravel-admin/pull/3079
