### ISSUE TITLE
UNIQUE表单验证不起作用的BUG

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#3080]
- Laravel Version: 5.7.8
- PHP Version:7.2
- Laravel-admin: 1.6.10

### Description:
使用unique:table,field,id,id_column的验证时,使用传入$id,填入总是变成null或空

### Steps To Reproduce:
```
public function form($id=null)
{
    $form->email(''email')->rules('unique:users,email,{$id}');
    return $form;
}
```

**Comment by robinhoo1973** [comment]
问题的原因是,form的update方法没有传入$id,虽然以前有类似的解决方法,希望能在之后的框架版本里更正,我之后提交了PR,希望合并.调了一晚上啊,回去补个觉

**Comment by robinhoo1973** [comment]
PR:https://github.com/z-song/laravel-admin/pull/3081

**Comment by ichynul** [comment]
注入id的时机有点迟。
form()的时候form里面model没有id，没有values。

你的需求可以应该可以这样 
```php
public function form()
{
        $email = $form->email('email');
        $form->editing(function ($form) use ($email) {
                $id = $form->model()->id;
                $email->rules("unique:users,email,{$id}");
                //可以拿到 model 的values ,做一些判断控制 
                if($form->model()->name == 'admin')
                {
                    $email->readOnly();
                    //$email->setDisplay(false);
                }
        });
        return $form;
}
```

**Comment by ichynul** [comment]
我觉得会有问题吧，有时候我的会在Controller的form()方法里面传参数。
```php
public function form($id=0,$type=0)
{

}
```
这可以兼容。
但难保其他人的其他写法，比如
```php
public function form($type=0,$id=0)
{

}
```
或
```php
public function form($type=0)
{

}
```
修改框架后，`return $this->form($id)->update($id);`有不确定性，可能破坏已有代码。

**Comment by robinhoo1973** [comment]
> 我觉得会有问题吧，有时候我的会在Controller的form()方法里面传参数。
> 
> ```
> public function form($id=0,$type=0)
> {
> 
> }
> ```
> 
> 这可以兼容。
> 但难保其他人的其他写法，比如
> 
> ```
> public function form($type=0,$id=0)
> {
> 
> }
> ```
> 
> 或
> 
> ```
> public function form($type=0)
> {
> 
> }
> ```
> 
> 修改框架后，`return $this->form($id)->update($id);`有不确定性，可能破坏已有代码。

这个看取舍了
