### ISSUE TITLE
这俩版本差别好大 什么时候release1.5.20呀

### ISSUE THREAD

**Issue by kalsolio** [z-song/laravel-admin#3082]
![image](https://user-images.githubusercontent.com/14342288/54247800-51f4d200-4575-11e9-801b-35b4f49adff1.png)
![image](https://user-images.githubusercontent.com/14342288/54247838-6cc74680-4575-11e9-91c7-935391b081e6.png)

**Comment by z-song** [comment]
1.5版本不再添加新功能，建议更新到1.6
