### ISSUE TITLE
How to set a value in the hidden field before saving the form

### ISSUE THREAD

**Issue by lordjack** [z-song/laravel-admin#3087]
- Laravel Version: 5.5
- PHP Version: 7.1.26
- Laravel-admin: 1.6.9

### Description:

Hello,

I tried to follow this example, but it did not work.

Error
![image](https://user-images.githubusercontent.com/6691621/54085313-b1f03c00-431b-11e9-94ab-2aae82d125d2.png)

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/6691621/54085349-f8de3180-431b-11e9-9841-2d05d5344e19.png)

![image](https://user-images.githubusercontent.com/6691621/54085339-e95ee880-431b-11e9-86c3-1ccbc7fa4c6d.png)

My Model
![image](https://user-images.githubusercontent.com/6691621/54085383-49558f00-431c-11e9-889d-95972ea15155.png)

Table Artigo
![image](https://user-images.githubusercontent.com/6691621/54085606-a9e5cb80-431e-11e9-89c0-9a04fba4df8a.png)

Table Admin_users
![image](https://user-images.githubusercontent.com/6691621/54085615-bc600500-431e-11e9-8d6b-fd5f086c4e72.png)

Anyone have any tips on what I should do?

**Comment by ichynul** [comment]
Try this:
`$form->hidden('persion_id')->default(Admin::user()->persion_id);`

**Comment by lordjack** [comment]
Thank you @ichynul, it worked!
