### ISSUE TITLE
Grid的Actions栏位全局定义了样式后,无法prepend和append其他按钮

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#3088]
- Laravel Version: 5.8.*
- PHP Version:7.2
- Laravel-admin: 1.6.*

### Description:
Grid的Actions栏位全局定义了样式后,无法prepend和append其他按钮 
参见https://github.com/z-song/laravel-admin/issues/431

### Steps To Reproduce:
参见https://github.com/z-song/laravel-admin/issues/431

**Comment by robinhoo1973** [comment]
提交了BugFix:https://github.com/z-song/laravel-admin/pull/3089
使用方法:
```
        $grid->setActions(ButtonTextActions::class);
        $grid->actions(function ($actions) {
            if ($actions->getKey() == 1) {
                $actions->disableDelete();
            }
            $actions->prepend('before');
            $actions->append('after');
        });
```

**Comment by z-song** [comment]
这个问题已经解决了

在app/Admin/bootstrap.php里全局设置操作列
```php
Grid::init(function (Grid $grid) {
    $grid->actions(CustomActions::class);
});
```

在grid中：
```php
$grid->actions(function ($actions) {
    $actions->prepend('before');
    $actions->append('after');
});
```

**Comment by robinhoo1973** [comment]
`Argument 1 passed to Encore\Admin\Grid::actions() must be an instance of Closure, string given,`

**Comment by z-song** [comment]
参考 b72548bde08b93b00c12e3b6fcafc5b6855e7708 

还没有发版本，dev-master分支上可以看到

**Comment by robinhoo1973** [comment]
> 参考 [b72548b](https://github.com/z-song/laravel-admin/commit/b72548bde08b93b00c12e3b6fcafc5b6855e7708)
> 
> 还没有发版本，dev-master分支上可以看到

看见了,不过感觉为了一个设置写个闭包函数有点累:)

**Comment by z-song** [comment]
参考 
https://laravel-admin.org/docs/zh/model-grid-init
https://laravel-admin.org/docs/zh/model-form-init

**Comment by robinhoo1973** [comment]
嗨,闭包函数有个缺点,就是设置了这个,就排他性,不能设置第二次,而且需要叠加的,除非init闭包是个array,依次执行,就像Admin::script一样
这样写扩展的就很为难了,别人先调用了init,后来的可以覆盖,而不是叠加

**Comment by z-song** [comment]
@robinhoo1973 提交了一个commit 0fea44cdc805bf8c5cf8796635e9ee02409a01ae，可以重复调用init初始化

**Comment by robinhoo1973** [comment]
> @robinhoo1973 提交了一个commit [0fea44c](https://github.com/z-song/laravel-admin/commit/0fea44cdc805bf8c5cf8796635e9ee02409a01ae)，可以重复调用init初始化
赞👍

**Comment by robinhoo1973** [comment]
@z-song 好像源没更新,下来的还是旧的
