### ISSUE TITLE
try to upload image grater than 2MB

### ISSUE THREAD

**Issue by mRamadan0101** [z-song/laravel-admin#3094]
- Laravel Version:5.7
- PHP Version: 7.2
- Laravel-admin: 1.6

### Description:
when i try to upload image grater than 2MB i have this error msg 
` The Photo failed to upload.`

### Steps To Reproduce:
try to change imge to file but in this case file saved in 0 Byte 
try to make new rules for this filed but same error
`        $form->image('photo', 'Photo')->uniqueName()->rules('required|image|mimes:jpeg,png,jpg|size:5000');`

**Comment by yurik94** [comment]
Check out your PHP post_max_size and and upload_max_filesize  ;)

**Comment by mRamadan0101** [comment]
i checked it and problem was path of php.ini 
create phpinfo() page and check path of php.ini file and then edit it to allow server upload files and image grater than 2MB
