### ISSUE TITLE
Validation Form

### ISSUE THREAD

**Issue by Makennsky** [z-song/laravel-admin#3095]
- Laravel Version: 5.7.
- PHP Version:7.1
- Laravel-admin: 1.6.

### Description:
Form Validation don't work 

### Steps To Reproduce:
in form method rules construction won't react for rules and submitting process work without validation

**Comment by saSHADE** [comment]
Google-trans:
faced the same problem, validation dont work on Encore\Admin\Widgets\Form
in Encore\Admin\Form validation work
