### ISSUE TITLE
获取关联表关联的表数据

### ISSUE THREAD

**Issue by xingchenboy** [z-song/laravel-admin#3102]
- Laravel Version: 5.7.*
- PHP Version:7.2
- Laravel-admin: 1.6.*

### Description:
我尝试了下下面issue提供的办法，但无法获取到关联表关联的表的数据
[https://github.com/z-song/laravel-admin/issues/1353](url)
我尝试了用这种方法获取不到关联表关联的表，用原生的Model::with('xx.xx')->get().可以获取到关联表的关联表的数据。。。
$grid->model()->with('country.continent');

$grid->country()->continent()->display(function ($continent) {
return $continent['name_zhcn'];
});

// or

$grid->column('name_zhcn')->display(function () {
return $this->country['continent']['name_zhcn'];
});

**Comment by z-song** [comment]
你的代码呢？

**Comment by xingchenboy** [comment]
### 一共三个表UserRelation,User,School ,关联关系都在Model中设置好。
* 模型中关系设定如下
```
public function user()
{
     return $this->belongsTo('App\Models\User');
}
public function school_table()
{
     return $this->belongsTo('App\Models\School', 'school_id', 'id');
}
```
我测试了下，使用第一种方法，可以得到数据，但会出现n+1问题
```` 
$grid->model()->with('user.school_table');

$grid->column('admins')->display(function () {
        return $this->user['school_table']['admins'];
 });

error:You should add "with('school_table')" to eager-load this relation


第二种方法，得不到数据

$grid->model()->with('user.school_table');

$grid->user()->school_table()->display(function ($school_table) {
      return $school_table['admins'];
});
