### ISSUE TITLE
自定义Filter能否使用多个column

### ISSUE THREAD

**Issue by zhousak** [z-song/laravel-admin#3105]
- Laravel Version: 5.6.39
- PHP Version: 7.1.19
- Laravel-admin: 1.6.10

### Description:
我想自定义一个三级联动的filter，需要用三个数据库字段，也就是说一个filter中有多个column，但试了下好像如果不该动框架的话不能实现。请问有什么解决办法吗？

**Comment by jxlwqq** [comment]
在filter 中选择 select option load ，使用方法和在form中类似。
