### ISSUE TITLE
建议后台用户表内置phone(手机号)字段 方便自定义短信验证码登录后台

### ISSUE THREAD

**Issue by pianqifei** [z-song/laravel-admin#3113]
- Laravel Version: 5.8.5
- PHP Version:7.2
- Laravel-admin: 1.6.10

### Description:
在admin_users表中内置phone(手机号)字段 感觉此字段比较常用
##
migration
Schema::connection($connection)->create(config('admin.database.users_table'), function (Blueprint $table) {
            $table->increments('id');
            $table->string('username', 190)->unique();
            $table->string('password', 60);
            $table->string('name');
            $table->string('phone')->nullable();
            $table->string('avatar')->nullable();
            $table->string('remember_token', 100)->nullable();
            $table->timestamps();
        });
##
Encore\Admin\Controllers\UserController
$grid->phone(trans('admin.phone'));
$show->phone(trans('admin.phone'));
$form->text('phone', trans('admin.phone'))->rules('required|regex:/^1[3456789][0-9]{9}$/', [
            'required' => '请设置手机号',
            'regex'   => '手机号格式错误',]);
##
本地化语言对应增加翻译选项

**Comment by lihe6666** [comment]
很好的建议， 这样可以增加安全性。 但是后台需要有配置页面，这块的涉及的事情可能比较多。不知道作者有何见解 @z-song

**Comment by z-song** [comment]
建议还是根据需要  自己实现，有需要修改的页面可以通过覆盖路由的方式来实现

**Comment by wangwei92** [comment]
如何实现短信验证码登录后台？
