### ISSUE TITLE
无法调用Admin::css添加全局css

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#3114]
- Laravel Version: 5.8.*
- PHP Version:7.3
- Laravel-admin: 1.6.10

### Description:
在ServiceProvider理设置添加Navbar时,需要加载额外的css,发现总是加不上,看了代码,好像Admin::css那时候还没初始化,而且最后生成HTML头的时候,只看form里的assets

**Comment by ichynul** [comment]
换个写法怎么样
```php
Admin::booted(function () {
　　//
});
```
