### ISSUE TITLE
Laravel-admin启用二级域名后，cookies生成有异常

### ISSUE THREAD

**Issue by hetoo** [z-song/laravel-admin#3118]
- Laravel Version: 5.5.45
- PHP Version: 7.2.5
- Laravel-admin: 1.6.10

### Description:
Laravel-admin更新到最新版，设置二级域名后，发现cookies生成有异常，导致表单无法正常提交
![QQ图片20190322113503](https://user-images.githubusercontent.com/7521166/54799127-caa30f00-4c96-11e9-9711-0d08545c9aae.png)

### Steps To Reproduce:
**具体操作步骤**
修改 config/admin.php
```
'route' => [
    'domain'    => env('ADMIN_DOMAIN', null),
    'prefix'    => env('ADMIN_ROUTE_PREFIX', 'admin'),
    'namespace' => 'App\\Admin\\Controllers',
    'middleware' => ['web', 'admin'],
],
```
在 env 文件中加入ADMIN_DOMAIN 和 ADMIN_ROUTE_PREFIX

**貌似问题出在src/Middleware/Session.php**
```
if ($domain = config('admin.route.domain')) {
    config(['session.domain' => $domain]);
}
```

**Comment by z-song** [comment]
已经修复
