### ISSUE TITLE
Change action button for delete

### ISSUE THREAD

**Issue by rassemdev** [z-song/laravel-admin#3120]
I'm successfully changed the edit and view button for model grid row action buttons, but not having any idea how should i change the delete button.searched in google/stackoverflow, couldn't find any solution.  can anyone help me out? 

Here is my code for edit button.
`$actions->append("<a class='btn btn-sm btn-info' href='question/{$id}/edit' style='margin-bottom: 5px;'><i class='fa fa-eye'> Details</i></a><br/>");`

**Comment by anditsung** [comment]
how did you get the {$id} from grid?

**Comment by rassemdev** [comment]
@anditsung `$grid->actions(function ($actions) {
            $id = $actions->getKey();
            $actions->append("<a class='btn btn-sm btn-info' href='question/{$id}/edit' style='margin-right: 5px;'><i class='fa fa-eye'> Details</i></a>");
            $actions->append("<a class='btn btn-sm btn-success' href='question/{$id}/edit' style='margin-right: 5px;'><i class='fa fa-edit'> Edit</i></a>");
            $actions->append(new DeleteQuestion($id));

            $actions->disableEdit();
            $actions->disableView();
            $actions->disableDelete();
        });`

here is my code. In case you need anything else..

**Comment by anditsung** [comment]
got it. thanks
