### ISSUE TITLE
在同一grid中多次调用modal，同一行的每个点击按钮点开内容都一样

### ISSUE THREAD

**Issue by zhengyajun** [z-song/laravel-admin#3121]
- Laravel Version: 5.7.28
- PHP Version: 7.1
- Laravel-admin: 1.6.10

### Description:
在同一个`grid`中如果多次调用`modal`方法，每一行的每个按钮点开，结果都是一样的，是第一个调用的结果。
查看了`namespace Encore\Admin\Grid\Displayers\Modal`，似乎执行一次就会和整行绑定在一起，请问这个有没有什么方法能和某行某列绑定在一起呢？

### Steps To Reproduce:
`namespace App\Admin\Controllers\GamesController`
```php
    protected function grid()
    {
        $grid = new Grid(new Game);

        //...
       //第一次调用modal
        $grid->topic_count('主题')
            ->sortable()
            ->modal('最新主题', function ($model) {
            $topics = $model->topics()
                ->orderBy('id', 'desc')
                ->take(10)
                ->get()
                ->map(function ($topics) {
                return $topics->only(['id', 'title', 'user_id', 'reply_count', 'like_count']);
            });
            return new Table(['ID', '标题', '用户ID', '回复数', '获赞数'], $topics->toArray());
        });

       //第二次调用modal
        $grid->follow_count('关注')
            ->sortable()
            ->modal('最新关注用户', function ($model) {         //这里展示的结果还是最新主题
            $likes = $model->userlikes()
                ->orderBy('id', 'desc')
                ->take(10)
                ->get()
                ->map(function ($likes) {
                return $likes->only(['id', 'name', 'uuid', 'email']);
            });
            return new Table(['ID', '姓名', '身份标识', '邮箱'], $likes->toArray());
        });

        return $grid;
    }
```

**Comment by lauwen** [comment]
你这边解决这个问题了吗？

**Comment by zhengyajun** [comment]
> 你这边解决这个问题了吗？

没有，
最后我用的替代方案是把需要用到`modal`的地方替换成`<a>`标签，点击后直接跳转到 相关内容过滤后的结果页。

**Comment by lauwen** [comment]
我刚刚也解决了  原因是因为我这边做统计数据  每行没有设置唯一id

**Comment by zhengyajun** [comment]
> 我刚刚也解决了 原因是因为我这边做统计数据 每行没有设置唯一id

你这边目前是指一行一个`modal`成功显示了还是指一行多个`modal`也可以了？当时看了下源码确实是和行绑定在一起的，尝试改了一下也没有成功。

**Comment by maojindao55** [comment]
> 我刚刚也解决了 原因是因为我这边做统计数据 每行没有设置唯一id modal是取每行id来和弹出模态框做绑定的 所以一行多个的话 实际上是和同一个模态框绑定了 所以内容会一样

不明白,你是解决了还是没解决?

**Comment by 348251248** [comment]
`$grid->push_group_id()->modal('FCM Push Notification', function($model) use ($alert_controller){
            $model->id = $model->alert_id;
            return $alert_controller->fcm_form($model);
        });`
Bind id for each row. It works for my case.

**Comment by zhengyajun** [comment]
Wonderful，can you tell me what “$alert_controller” is,  It's your personal package？

**Comment by zhengyajun** [comment]
> ```
> $grid->push_group_id()->modal('FCM Push Notification', function($model) use ($alert_controller){
>       $model->id = $model->alert_id;
>       return $alert_controller->fcm_form($model);
> });
> ```
> 
> Bind id for each row. It works for my case.

Wonderful，can you tell me what “$alert_controller” is, It's your personal package？

**Comment by zhengyajun** [comment]
> ```
> $grid->push_group_id()->modal('FCM Push Notification', function($model) use ($alert_controller){
>       $model->id = $model->alert_id;
>       return $alert_controller->fcm_form($model);
> });
> ```
> 
> Bind id for each row. It works for my case.

Wonderful，can you tell me what “$alert_controller” is, Is it your personal package？

**Comment by 348251248** [comment]
Yes, I just copy this example from my project.

**Comment by zhengyajun** [comment]
> Yes, I just copy this example from my project.

I see, thank you for your thoughts

**Comment by sonhineboy** [comment]
我也遇到这样的问题，我是用外部数据api;原因是模型没有绑定id,绑定上唯一的id就可以了。
