### ISSUE TITLE
1.6.10 版本 Grid 禁用查询过滤器报错

### ISSUE THREAD

**Issue by ixianming** [z-song/laravel-admin#3125]
- Laravel Version: 5.8.7
- PHP Version:7.2.7
- Laravel-admin: 1.6.10

Description:
调用 $grid->disableFilter(); 时，报错。
错误内容：Argument 1 passed to Encore\Admin\Grid\Tools::Encore\Admin\Grid\{closure}() must be an instance of Encore\Admin\Grid\Tools\AbstractTool, string given

错误位置：\encore\laravel-admin\src\Grid\Tools.php  88行。
```
public function disableFilterButton(bool $disable = true)
{
        $this->tools = $this->tools->map(function (AbstractTool $tool) use ($disable) {
            if ($tool instanceof FilterButton) {
                return $tool->disable($disable);
            }
 
            return $tool;
        });
}
```

**Comment by z-song** [comment]
你这里应该是设置了一个自定义的tool， 并且是个字符串

**Comment by chenqixuan** [comment]
$tools->append('some string') ，tools 里面就有不是AbstractTool 实例的类型，如果$grid->disableFilter();定义在 $grid->tools(function ($tools) {});之后就会有这个错误，定义在前面就不会报错，但是为了严谨还是扩展一个AbstractTool 实例的工具。

**Comment by z-song** [comment]
@chenqixuan 提交了修复  等下个版本发布
