### ISSUE TITLE
Session.path导致后台图片验证码一直失败问题

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3127]
https://github.com/z-song/laravel-admin/blob/d2e0e5c1ac8ada92a52c616dc928ef7b214ac536/src/Middleware/Session.php#L11
后台登录页面使用了`mews/captcha`做图片验证码
原理是验证码保存在session里面。
它生成图片的路径；类似：
`http://www.site3.com/captcha/default?JJs7JtH8`
所有他的session path 是　'/'，
但后台把session path 设置为'/admin'，
导致拿不到session,一直验证失败。
![深度截图_选择区域_20190326113255](https://user-images.githubusercontent.com/10061650/54970249-61840a00-4fbc-11e9-84bb-66e131d053be.png)
![深度截图_选择区域_20190326113154](https://user-images.githubusercontent.com/10061650/54970253-621ca080-4fbc-11e9-8517-a01b5ea552c2.png)

**Comment by ichynul** [comment]
最好再单独做一个设置项，不要用`admin.route.prefix`

**Comment by ichynul** [comment]
临时解决方案
在`/routes/web.php`里面加个路由:
```php
Route::get('captcha/admin/{config?}', '\Mews\Captcha\CaptchaController@getCaptcha')->middleware(['web', Encore\Admin\Middleware\Session::class]);
```
```html
<img  class="captcha" src="/captcha/admin/default" style="display:inline-block;vertical-align:middle;" onclick="refresh()" title="点击刷新">
      <script>
          function refresh(){
              $('img[class="captcha"]').attr('src','/captcha/admin/default'+Math.random());
          }
      </script>
```

**Comment by zishang520** [comment]
最好的解决方案是去掉session中间件，用guard来进行授权隔离😀

**Comment by ichynul** [comment]
@zishang520 
你的意思是用/captcha/api/default?
api改起来也差不多麻烦，`login.blade.php`里面代码增多。

**Comment by hetoo** [comment]
#3118 后台配置二级域名也发现session这里有问题

**Comment by zishang520** [comment]
[https://github.com/zishang520/laravel-admin/commit/3312502e627058d4d81dc90dae5a9b137e829ca3](https://github.com/zishang520/laravel-admin/commit/3312502e627058d4d81dc90dae5a9b137e829ca3) 我说的这种，在很久以前我提出使用Guard进行数据的隔离多后台，提议作者没有通过

[https://github.com/zishang520/laravel-admin/commit/c09d0d0f7b48032ce537dfda1b522105cf303595](https://github.com/zishang520/laravel-admin/commit/c09d0d0f7b48032ce537dfda1b522105cf303595)

**Comment by pkdog** [comment]
可以仿照vendor/encore/laravel-admin/src/Middleware/Session.php 去重写一个session中间件，然后再config/admin.php 里面重新配置中间件组去解决这个session问题

**Comment by langeuh** [comment]
https://github.com/z-song/laravel-admin/blob/d2e0e5c1ac8ada92a52c616dc928ef7b214ac536/src/Middleware/Session.php#L11

The code should either be reverted or changed in to a new config setting

```php
$path = '/'.trim(config('admin.route.session_path'), '/');
```
currently the session gets stored in the /admin meaning you're unable to access the current logged in admin outside the admin itself.
If you need to know if an administrator is logged in or not inside your application to show extra content/preview content/... you're unable to detect it since `Admin::user()` will always return `null` inside your application

**Comment by z-song** [comment]
@langeuh Pushed an commit to remove `admin.session` from the admin middleware group.

I'll tag new release later today.

**Comment by z-song** [comment]
@zishang520 你的pr貌似只是把guard名称配置化，这个在admin.php中的`auth`也可以修改啊

**Comment by zishang520** [comment]
@z-song admin.php能改，但是你代码里固定的admin[https://github.com/z-song/laravel-admin/blob/master/src/Middleware/Authenticate.php#LC23](https://github.com/z-song/laravel-admin/blob/master/src/Middleware/Authenticate.php#LC23):23

以及 [https://github.com/z-song/laravel-admin/blob/master/src/Controllers/AuthController.php#LC201](https://github.com/z-song/laravel-admin/blob/master/src/Controllers/AuthController.php#LC201):203
