### ISSUE TITLE
Filter tool UI

### ISSUE THREAD

**Issue by thaibuu** [z-song/laravel-admin#313]
in Filter need button clear form.

**Comment by langeuh** [comment]
Ideally this should not be a 'reset' button. But a button, that is only active if filters are applied, and gets the full list of items again.

eg
*admin/products*  => reset filter button is disabled 
![screen shot 2017-01-19 at 09 14 16](https://cloud.githubusercontent.com/assets/5647964/22098642/c4b6bd42-de27-11e6-999b-d147a40d9c2b.png)

*admin/projects?title=test&status=declined*  => reset filter button is not disabled and clicking it takes you back to admin/products
![screen shot 2017-01-19 at 09 14 35](https://cloud.githubusercontent.com/assets/5647964/22098656/e121b2ca-de27-11e6-8867-4dfb8a1aecaa.png)


Currently when results are filtered in the grid view, there is no way you can see that the results are filtered. Especially if you're using filters in a modal
So adding the button there would be great as well
![screen shot 2017-01-19 at 09 19 05](https://cloud.githubusercontent.com/assets/5647964/22098771/66126524-de28-11e6-91b2-70bb62f21daa.png)

The action of the button would always be the current URL without the filter field parameters

**Comment by thaibuu** [comment]
simple solution, thank you.

**Comment by langeuh** [comment]
I'd like to keep my suggestion open to be honest. User Exeperience wise it would be better

**Comment by z-song** [comment]
@langeuh You are right.

**Comment by z-song** [comment]
Issue fixed!
