### ISSUE TITLE
$form->hasMany() 中使用wangEditor，样式显示错误

### ISSUE THREAD

**Issue by popfaker** [z-song/laravel-admin#3137]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.6.10

### Description:
- 当form表单使用hasMany() 动态新增编辑器时，编辑器相互影响
```
$form->hasMany('contents', '内容', function (Form\NestedForm $form) {
              $form->editor('content', '内容');
 });
```
- 页面显示排版错误，编辑器折叠
![image](https://user-images.githubusercontent.com/38718383/55070106-81045b00-50c0-11e9-8b71-ddbd334883e4.png)

**Comment by never615** [comment]
你用的是作者写的扩展的话,是因为初始化编辑器用的id,见下面的作者源码:
https://github.com/laravel-admin-extensions/wangEditor/blob/master/src/Editor.php#L36
改成name就好了,可以参考:
https://github.com/never615/laravel-admin-enhance/blob/master/src/Form/Field/WangEditor.php#L56

**Comment by popfaker** [comment]
> 你用的是作者写的扩展的话,是因为初始化编辑器用的id,见下面的作者源码:
> https://github.com/laravel-admin-extensions/wangEditor/blob/master/src/Editor.php#L36
> 改成name就好了,可以参考:
> https://github.com/never615/laravel-admin-enhance/blob/master/src/Form/Field/WangEditor.php#L56

十分感谢！
