### ISSUE TITLE
Column selector

### ISSUE THREAD

**Issue by Makennsky** [z-song/laravel-admin#3138]
- Laravel Version: 5.8.
- PHP Version: 7.1
- Laravel-admin: 1.6.

### Description:
Disable column selector

### Steps To Reproduce:
How to make disabled column selector?

**Comment by ludo1960** [comment]
What is a column selector? I don't see that in http://laravel-admin.org/docs/#/en/model-grid-column?id=built-in-methods

**Comment by mhenselin** [comment]
is fixed with mentioned commit. you can now disable the column selector. will be in the next release 
regards
Marcel

**Comment by mhenselin** [comment]
@z-song please close this issue :-)

**Comment by Makennsky** [comment]
thanks
