### ISSUE TITLE
上传图片能否自主选择保留原图？

### ISSUE THREAD

**Issue by zhengmin4516** [z-song/laravel-admin#3141]
- Laravel Version: 5.7
- PHP Version:7.1
- Laravel-admin: 1.6

使用上传图片组件
```
$form->image('default_bg', '默认背景图片')->uniqueName();
```
在上传图片后原图就没了，可是我的业务逻辑里面有可能别的数据里面会用到同一个文件，就会导致图片找不到。
这个删除的行为能不能放在配置文件里面自由选择是否删除原图？
还是已经有这样的功能，我不会用？

## 问题二
已经保存到数据库的图片路径，怎么删除数据库中的数据？点击右上角x然后保存，数据库还是记录着图片的路径
![image](https://user-images.githubusercontent.com/12004034/55134902-283ace00-5165-11e9-9f10-df4df11ed73b.png)

**Comment by tiderjian** [comment]
可以试试这个图片上传的扩展，默认不会删除图片，如果想删除也可以在配置里打开 https://github.com/tiderjian/la-filepond
