### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by ludo1960** [z-song/laravel-admin#3143]
- Laravel Version: 5.9
- PHP Version: 7.3
- Laravel-admin: 1.6.9

### Description:
From admin home page, link from Administrator/setting (admin/auth/setting) takes you to a User setting page, the view link leads to a 404, i.e. admin/1. The Administrator/setting link should be admin/auth/users/1 and not admin/auth/setting, In encore/laravel-admin/resources/views/partials/header.blade.php I changed                          
<a href="{{ admin_base_path('auth/setting') }}" class="btn btn-default btn-flat">{{ trans('admin.setting') }}</a>

to:

<a href="{{ admin_base_path('auth/users/'. Admin::user()->id ) ) }}" class="btn btn-default btn-flat">{{ trans('admin.setting') }}</a>
not sure that is the correct solution? 

Many thanks for your awesome work on this project

### Steps To Reproduce:
Go to admin home page /admin, click Administrator then setting (top right) then click the view link = 404

**Comment by ludo1960** [comment]
Man I hate the code editor on github, changed auth/setting to auth/users/'. Admin::user()->id

**Comment by coderboy-11** [comment]
![laravel-admin](https://user-images.githubusercontent.com/32748285/59551182-22e66600-8f93-11e9-924f-c77b9d089967.png)

Please share the fix of this issue.
