### ISSUE TITLE
cant access user statically

### ISSUE THREAD

**Issue by anditsung** [z-song/laravel-admin#3147]
- Laravel Version: 5.8
- PHP Version: 7.1.3
- Laravel-admin: 1.6

### Description:
Non-static method Encore\Admin\Admin::user() should not be called statically

### Steps To Reproduce:
$grid->actions(function($actions) {
            if (!Admin::user()->can('hr.department-delete')) {
                $actions->disableDelete();
            }
        });

![Screen Shot 2019-03-29 at 14 46 10](https://user-images.githubusercontent.com/1090413/55217195-7b7a5280-5231-11e9-894f-84764ab0f123.png)

**Comment by z-song** [comment]
@anditsung 
```php
use Encore\Admin\Facades\Admin;
```
