### ISSUE TITLE
bootstrap-datetimepicker issue

### ISSUE THREAD

**Issue by alihastam** [z-song/laravel-admin#3153]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: last version

### Description:
How can i change position of time or date picker ?
i know it is solved by **widgetPositioning** 
(Takes an object parameter that can contain two keys vertical and horizontal each having a value of 'auto', 'top', 'bottom' for vertical and 'auto', 'left', 'right' for horizontal which defines where the dropdown with the widget will appear relative to the input element the component is attached to.)

but I do not know how to do it.

**Comment by alihastam** [comment]
answer is 👍 
`$this->script = "$('{$this->getElementClassSelector()}').parent().datetimepicker({
          format: 'ss:mm:HH',
          locale : 'en',
          allowInputToggle:true,
          widgetPositioning: {
            horizontal: 'right',
            vertical: 'top'
          }
        });";`

in the Date or Time render function

**Comment by alihastam** [comment]
> * Laravel Version: 5.5
> * PHP Version:7.2
> * Laravel-admin: last version
> 
> ### Description:
> How can i change position of time or date picker ?
> i know it is solved by **widgetPositioning**
> (Takes an object parameter that can contain two keys vertical and horizontal each having a value of 'auto', 'top', 'bottom' for vertical and 'auto', 'left', 'right' for horizontal which defines where the dropdown with the widget will appear relative to the input element the component is attached to.)
> 
> but I do not know how to do it.
answer is 👍
`$this->script = "$('{$this->getElementClassSelector()}').parent().datetimepicker({ format: 'ss:mm:HH', locale : 'en', allowInputToggle:true, widgetPositioning: { horizontal: 'right', vertical: 'top' } });";`

in the Date or Time render function

**Comment by hanachan1026** [comment]
Hi, how did you managed to extend Encore\Admin\Form\Field\Date class?
