### ISSUE TITLE
MongoDB install

### ISSUE THREAD

**Issue by ludo1960** [z-song/laravel-admin#3157]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: latest

### Description:
After first installing 
https://github.com/jenssegers/laravel-mongodb

I go through the install for laravel-admin, the last step php artisan admin:install then I check the database, all tables and data are there. But when i go to login admin/auth/login, I get the following error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function prepare() on null

/var/www/slimmongo.local.com/vendor/laravel/framework/src/Illuminate/Database/Connection.php

    public function select($query, $bindings = [], $useReadPdo = true)
    {
        return $this->run($query, $bindings, function ($query, $bindings) use ($useReadPdo) {
            if ($this->pretending()) {
                return [];
            }
 
            // For select statements, we'll simply execute the query and return an array
            // of the database result set. Each element in the array will be a single
            // row from the database table, and will either be an array or objects.
            $statement = $this->prepared($this->getPdoForSelect($useReadPdo)
                              ->prepare($query));
 
            $this->bindValues($statement, $this->prepareBindings($bindings));
 
            $statement->execute();
 
            return $statement->fetchAll();
        });
    }
 

    public function cursor($query, $bindings = [], $useReadPdo = true)
    {
        $statement = $this->run($query, $bindings, function ($query, $bindings) use ($useReadPdo) {
Arguments
"Call to a member function prepare() on null"

**Comment by ludo1960** [comment]
Forgot to change the migrations to mongodb, now install fails here:
```
   Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function roles() on null

  at /var/www/slimmongo.local.com/vendor/encore/laravel-admin/src/Auth/Database/AdminTablesSeeder.php:126
    122|             ],
    123|         ]);
    124| 
    125|         // add role to menu.
  > 126|         Menu::find(2)->roles()->save(Role::first());
    127|     }
    128| }
    129| 

  Exception trace:

  1   Encore\Admin\Auth\Database\AdminTablesSeeder::run()
      /var/www/slimmongo.local.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  2   call_user_func_array([])
      /var/www/slimmongo.local.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32
```

**Comment by ludo1960** [comment]
After yet another play with the installation I've got everything working apart from
` @each('admin::partials.menu', Admin::menu(), 'item')` in the sidebar.blade.php. If I comment the code out I see the laravel-admin package in the browser, albeit without the menu. If someone can suggest a workaround, I will publish the steps required to install laravel-admin with mongodb, so that it can be added to the manual. Please try to help me out.

Thanks in advance

**Comment by devenpateldp** [comment]
Laravel Version: 5.7
PHP Version:7.1
Laravel-admin: latest

After first installing
https://github.com/jenssegers/laravel-mongodb

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Call to a member function prepare() on null

Symfony\Component\Debug\Exception\FatalThrowableError
…/vendor/laravel/framework/src/Illuminate/Database/Connection.php326

vendor/laravel/framework/src/Illuminate/Database/Connection.php

any solution?
