### ISSUE TITLE
form select input value to form display

### ISSUE THREAD

**Issue by anditsung** [z-song/laravel-admin#3159]
- Laravel Version: 5.8.8
- PHP Version: 7.2.8
- Laravel-admin: 1.6.10

### Description:
`$form->select('employee')->options(Employee::all()->pluck('name', 'id'));
        $form->display('old_department');
        $form->divider();
        $form->select('new-department')->options(Department::all()->pluck('name', 'id'));
        $form->textarea('note')->rules('nullable');`

how to get the value from select employee to display on old_department.
so the old_department will be showing the current department for selected employee

### Steps To Reproduce:

**Comment by mhenselin** [comment]
one possible solution with the chance to modify the output:
```
            $form->display('old_department')->with(function ($value) {
                return $value;
            });
```

**Comment by anditsung** [comment]
this is how i solve this issue, not the best solution but its working

MutationController.php
`
protected function form()
    {
        $form = new Form(new Mutation);

        $form->select('employee')
            ->options(Employee::all()
                ->pluck('name', 'id'))
            ->loads(['old_department', 'new_department'], [ '/admin/api/old_dept', '/admin/api/new_dept']);
        $form->select('old_department', 'Old Department');
        $form->divider();
        $form->select('new_department', 'New Department');
        $form->textarea('note')
            ->rules('nullable');
        $form->hidden('user_id')->value(Admin::user()->id);

        $form->saved(function(Form $form){
            // update employee department after save to table
            $newDept = $form->input('new_department');
            $newDeptId = Department::where('name', $newDept)->first()->id;
            $employeeId = $form->input('employee');
            $employee = Employee::find($employeeId);
            $employee->department = $newDeptId;
            $employee->save();
        });

        $form->footer(function ($footer) {
            $footer->disableReset();
            $footer->disableViewCheck();
            $footer->disableEditingCheck();
            $footer->disableCreatingCheck();
        });

        return $form;
    }
`

EmployeeController.php
`
public function old_dept(Request $request)
    {
        $employeeId = $request->get('q');
        $employee = Employee::find($employeeId);
        $department = Department::find($employee->department);
        return [$department->id => $department->name];
    }

    public function new_dept(Request $request)
    {
        $employeeId = $request->get('q');
        $employee = Employee::find($employeeId);
        $department = Department::where('id', '!=', $employee->department)->get()->pluck('name', 'id');
        return $department;
    }
`

routes.php
`
// API
    Route::group(['prefix' => '/api/'], function(Router $router) {
        $router->get('old_dept', 'HR\EmployeeController@old_dept');
        $router->get('new_dept', 'HR\EmployeeController@new_dept');
    });
`
