### ISSUE TITLE
How to remove default filter ID for searching?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#316]
![2017-01-18_1827](https://cloud.githubusercontent.com/assets/24757934/22087445/f9a249bc-ddab-11e6-83ff-a09eab0e37b2.png)

Please let me know how can I remove these default filter which search ID?

**Comment by z-song** [comment]
@smuzammilali 
```php
$grid->filter(function($filter){
    $filter->disableIdFilter();
});
```

**Comment by smuzammilali** [comment]
Thank you it works also it's possible to remove the labels?
![2017-01-20_1516](https://cloud.githubusercontent.com/assets/24757934/22164094/b1922268-df23-11e6-8a52-7531aa56d9f8.png)

**Comment by smuzammilali** [comment]
@z-song Any help regarding above issue?

Also can we use just one input field for all filters? which called just Search

**Comment by z-song** [comment]
@smuzammilali It's unable to remove the label currently.

For the second question:
```php
$filter->where(function ($query) {

    $query->where('title', 'like', "%{$this->input}%")->orWhere('content', 'like', "%{$this->input}%");

}, 'Search');
```
You can write the search query just use eloquent methods.
