### ISSUE TITLE
Please make Encore\Admin\Grid\Filter's Input extendable

### ISSUE THREAD

**Issue by xiaohuilam** [z-song/laravel-admin#3161]
- Laravel Version: 5.8.*
- PHP Version: 7.2.*
- Laravel-admin: LTS

**Please make `Encore\Admin\Grid\Filter` input extendable, Such as `Encore\Admin\Form::extend()` same working**

Currently, it support operator extends, such as `greater than`/`less than`, not the form extending, such as`select`/`multiple-select`. and i want the last one.

### Description:

![image](https://user-images.githubusercontent.com/6964962/55345794-5f054100-54e3-11e9-9c89-c0af1bfdf42f.png)

### Revenue:
The list page we using, and then we can blow them all sky high

**Comment by xiaohuilam** [comment]
My mistake, it already been supported `Encore\Admin\Grid\Filter::extend()`

**Comment by mhenselin** [comment]
I would love to help, but that language is not in my repertoire :-(

**Comment by xiaohuilam** [comment]
> I would love to help, but that language is not in my repertoire :-(

hahhh... i've done translate into english all the description sentense
