### ISSUE TITLE
关联数据中被软删除了，无法查询出来

### ISSUE THREAD

**Issue by devilcry52** [z-song/laravel-admin#3162]
- Laravel Version: 5.5
- PHP Version:
- Laravel-admin: 1.6.10

### Description:
签到表和学生表关系如下

```
    public function student()
    {
        return $this->belongsTo(Student::class);
    }
```

### Steps To Reproduce:

```
$grid = new Grid(new Sign);
        $grid->model()->with(['student'=>function($query){
            $query->withTrashed();
        }]);
        $grid->id('Id');
        $grid->student()->student_name('学生姓名');
```
数据库signs表
![image](https://user-images.githubusercontent.com/20323383/55379688-6dd60d00-5550-11e9-8746-9017fc11fe48.png)
student表
![image](https://user-images.githubusercontent.com/20323383/55379725-847c6400-5550-11e9-94f0-a54f5100f20b.png)
展示结果
![image](https://user-images.githubusercontent.com/20323383/55379468-c35dea00-554f-11e9-9428-761860e74428.png)
查询不出来结果

**Comment by z-song** [comment]
这里貌似有点bug，你先用下面的方式吧
```php
    public function student()
    {
        return $this->belongsTo(Student::class)->withTrashed();
    }
```

**Comment by ShynHan** [comment]
> 这里貌似有点bug，你先用下面的方式吧
> 
> ```
>     public function student()
>     {
>         return $this->belongsTo(Student::class)->withTrashed();
>     }
> ```

暂时在用这个方法，不知道现在修复了么，或者有什么更好的方法么

**Comment by ShynHan** [comment]
发现一个新方法，将
```php
$grid->model()->with(['student'=>function($query){
            $query->withTrashed();
        }]);
```
这段代码放到关联字段下面，原理大概就是放在下面会覆盖上面的关联 with 设置
