### ISSUE TITLE
ColumnSelector button names hardcoded

### ISSUE THREAD

**Issue by Pashedu** [z-song/laravel-admin#3163]
- Laravel Version: 5.7.*
- PHP Version: 7.2.16
- Laravel-admin: ^1.6

### Description:
In "Encore\Admin\Grid\Tools\ColumnSelector.php" we have hardcoded button names 
` <button class="btn btn-xs btn-instagram column-select-all">全选</button>
            <button class="btn btn-xs btn-primary column-select-submit" style="float: right">确定</button>`

Could it be possible to change it with something like: 
` <button class="btn btn-xs btn-instagram column-select-all">{{ trans('admin.select_all') }}</button>`
?

### Steps To Reproduce:
Open Column selector in any grid controller.

**Comment by mhenselin** [comment]
in commit 9037dd1cc690fbfe85e9172ad74d86a631ea33c3 the fix was already pushed 
so you could use the master branch or need to wait for the next release 
@z-song - can we close this issue?

**Comment by z-song** [comment]
@mhenselin ok
