### ISSUE TITLE
Pjax导致新页面丢失css和inline脚本的问题修复

### ISSUE THREAD

**Issue by robinhoo1973** [z-song/laravel-admin#3166]
- Laravel Version: 5.8.x
- PHP Version:7.3
- Laravel-admin: 1.6.10

### Description:
当调用新页面而且有自定义的Admin::css或Admin::script的时候会出现丢失现象。而且这个问题在框架里也有表现，那就是很多当前页面没有用的script和css都在页面中被调用，可能也是为了别面出现css或脚本不起作用的情况。

### Steps To Avoid:
避免的方法，
1.在你的index方法里加上
```
if(request()->url()!=url()->previouse()){
     Admin::disablePjax();
}
```

2.修改vendor/encore/laravel-admin/src/Middleware/Pjax.php第34行的那段try block为下面的代码
```
        if($request->url()==url()->previous()){
            try {
                $this->filterResponse($response, $request->header('X-PJAX-CONTAINER'))
                    ->setUriHeader($response, $request);
            } catch (\Exception $exception) {
            }
        }
```

**Comment by nkjackzhang** [comment]
我是在bootstrap.php里加上的判断，index里这些helper都不太好用，而且方法名是previous()
