### ISSUE TITLE
$form->text会保存null，应该优化空值为空字符串

### ISSUE THREAD

**Issue by aogg** [z-song/laravel-admin#3167]
$form->text会保存null，应该优化空值为空字符串

现在在数据库中设置了varchar not null default ''无效了

**Comment by popfaker** [comment]
这个是laravel中间件导致的，会把所有空字符转换为null，数据库设置可以为null即可。

**Comment by popfaker** [comment]
![image](https://user-images.githubusercontent.com/38718383/56113596-e4cbc680-5f90-11e9-892f-cebd453eef04.png)
