### ISSUE TITLE
多图修改时不操作任何东西直接提交报错，

### ISSUE THREAD

**Issue by xiaoxuan6** [z-song/laravel-admin#3168]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
 添加时图片必填
$form->multipleImage('images', '商品图片')->uniqueName()->removable()->rules('required')->required();

 修改时不操作图片将原来的图片保存报错，显示未上传图片
### Steps To Reproduce:
![图片](https://user-images.githubusercontent.com/32762220/55537333-867c2980-56ee-11e9-9617-4b48530b3fbd.png)

**Comment by xiaoxuan6** [comment]
补充：修改时导致报错的是required()

**Comment by songlen** [comment]
laravel-admin 的github代码到底还有没有人维护啊，很多bug啊，没人管啊
