### ISSUE TITLE
上传图片数量限制

### ISSUE THREAD

**Issue by haoyq02** [z-song/laravel-admin#3169]
- Laravel Version: 5.7
- PHP Version: 7.1.8
- Laravel-admin: 1.6.10

### Description:
提交表单时，最多只能上传 20 张图片，请问在哪里可以设置？

### Steps To Reproduce:
表单共有三个上传图片的字段，一个单图上传，两个多图上传。
累加共 20 张图片后，其余图片不会上传。

**Comment by haoyq02** [comment]
已解决。
和框架无关。`php.ini` 设置 `max_file_uploads`

**Comment by zhouhai920** [comment]
你好,请问表单共有三个上传图片的字段,点击提交直接报错,找了很久都找不到原因,单个字段完全没问题,就是多个字段都需要上传的时候报错,请教您是怎么做到的,麻烦了!

**Comment by Xuan-Goldenf** [comment]
> 已解决。
> 和框架无关。`php.ini` 设置 `max_file_uploads`

因為laravel-admin是使用 bootstrap file input，所以你可以使用
```
// 限制數量 ->options(['maxFileCount'=>2])
$form->multipleImage('photos', '相簿')->options(['maxFileCount'=>2])->removable();
```

**Comment by songlen** [comment]
> > 已解决。
> > 和框架无关。`php.ini` 设置 `max_file_uploads`
> 
> 因為laravel-admin是使用 bootstrap file input，所以你可以使用
> 
> ```
> // 限制數量 ->options(['maxFileCount'=>2])
> $form->multipleImage('photos', '相簿')->options(['maxFileCount'=>2])->removable();
> ```

创建时可以，修改时就不行了，这个只能限制最新添加的数量，已经上传的没计算在内，好坑啊

**Comment by fengbingji** [comment]
> > > 已解决。
> > > 和框架无关。`php.ini` 设置 `max_file_uploads`
> > 
> > 
> > 因為laravel-admin是使用 bootstrap file input，所以你可以使用
> > ```
> > // 限制數量 ->options(['maxFileCount'=>2])
> > $form->multipleImage('photos', '相簿')->options(['maxFileCount'=>2])->removable();
> > ```
> 
> 创建时可以，修改时就不行了，这个只能限制最新添加的数量，已经上传的没计算在内，好坑啊

我看了bootstrap file input文档, 是可以实现的,加上'validateInitialCount'=>'true'就可以统计包含初始状态的数量了,也就是这样
```
// 限制总数量为2个
$form->multipleImage('photos', '相册')->options(['maxFileCount'=>2, 'validateInitialCount'=>'true'])->removable();
```

**Comment by wangjingyu** [comment]
- 控制器中设置初始化信息（主要是这个 最大总文件数 maxTotalFileCount）

`$form->multipleImage('goods_images', __('Goods images'))->options([
    'language' => 'zh',         // 设置语言（不管用，我是去 public/vendor/laravel-admin/bootstrap-fileinput/js/fileinput.min.js 手动改的）
    'maxFileCount' => Goods::GOODS_IMAGES_COUNT,         // 单次上传最大文件数
    'maxTotalFileCount' => Goods::GOODS_IMAGES_COUNT,    // 最大总文件数
    'maxFileSize' => 2048,    // 单位KB
    'showCaption' => false, // 是否显示输入框
    'showBrowse' => true,  //是否开启input的浏览文件 true:开启
    'msgFilesTooMany' => "选择上传的文件数量({n}) 超过允许的最大数值{m}！", // 上传数量超出的错误提示
    'msgSizeTooLarge' => '文件 “{name}” ({size} KB) 超过了允许大小 {maxSize} KB.', // 图片大小超出的提示
])->removable()->help('最多上传5张，单张大小不超过2M');;// 多图`


- 修改js代码：进入到 vendor/encore/laravel-admin/src/Form/Field/MultipleFile.php 查找setupScripts方法，在其后加入如下代码：
`    /**
     * @param string $options
     */
    protected function setupScripts($options)
    {
        // .....这是原有代码.....
        
        // 开始
        // 修复多度上传最大数量控制bug问题

        $optionsArr = json_decode($options, true);
        if (!empty($optionsArr['maxTotalFileCount'])) {
            $maxTotalFileCount = $optionsArr['maxTotalFileCount'];
            $maxTotalFileCountIdex = $maxTotalFileCount - 1;

            $this->script .= <<<EOT
$("input{$this->getElementClassSelector()}").on('filebatchselected', function (evt, file) {
        // 选择图片后执行，用于判断选择的图片是否超出限制，超出限制就禁用选择按钮
        // 比如只允许上传4张，我分两次上传，第一次上传两张，第二次上传3张，此时手动禁用选择按钮
        
        console.log(polymeric);
        if ($(this).parent().parent().find('.kv-preview-thumb').length > {$maxTotalFileCount}) {
            alert('图片数量最多为{$maxTotalFileCount}');
            
            // 定义超出制定数量的div
            var polymeric = $(this).parent().parent().find('.kv-preview-thumb:gt({$maxTotalFileCountIdex})');
            // 定义超出制定数量的缓存div
            var polymericCache = $(this).parent().parent().find('.kv-zoom-cache:gt({$maxTotalFileCountIdex})');
            
            // 删除
            polymeric.each(function(index, value){
                value.remove();
            });
            // 删除
            polymericCache.each(function(index, value){
                value.remove();
            });
            
//            $("input{$this->getElementClassSelector()}").attr('disabled', 'disabled')
//            $("input{$this->getElementClassSelector()}").closest('div.btn-file').addClass('btn-disabled');
        }
    })
    .on('filebatchuploadcomplete', function (evt, file) {
        // 只会调用一次，所有图片都上传成功调用，这是为了弥补上传成功后部分DOM结构重新渲染，导致filebatchselected钩子中执行的操作失效
        if ($(this).parent().parent().find('.kv-preview-thumb').length > {$maxTotalFileCount}) {
            $("input{$this->getElementClassSelector()}").attr('disabled', 'disabled')
            $("input{$this->getElementClassSelector()}").closest('div.btn-file').addClass('btn-disabled');
        }
    })
    .on('fileuploaded', function (event, data, previewId, index) {
        // 上传成功几次就调用几次，把后端返回的地址附加到DOM结构上，为以后得操作做准备
        if (data.response.status == 1) {
            $(".file-preview-thumbnails").find('#' + previewId).attr('data-url', data.response.data.name);
        } else {
            alert(data.response.info);
        }
    })
    .on('fileclear', function (evt, file) {
        // 点击右上角叉叉执行
        $("input{$this->getElementClassSelector()}").removeAttr('disabled')
        $("input{$this->getElementClassSelector()}").closest('div.btn-file').removeClass('btn-disabled')
        $(".file-preview-thumbnails").find('.fileinput-upload-button').removeAttr('disabled')
    })
    .on("filesuccessremove", function (event, uploadedId, index) {
        // 仅对上传成功的图片有效，未上传的图片不执行这里
        // 延迟一秒后删除，否则不准确
        setTimeout(function () {
            if ($(this).parent().parent().find('.kv-preview-thumb').length < {$maxTotalFileCount}) {
                $("input{$this->getElementClassSelector()}").removeAttr('disabled')
                $("input{$this->getElementClassSelector()}").closest('div.btn-file').removeClass(
                    'btn-disabled')
            }
        }, 1000)
    })
    .on('fileremoved', function () {
        // 该事件钩子针对只选择不上传的情况
        if ($(this).parent().parent().find('.kv-preview-thumb').length <= {$maxTotalFileCount}) {
            $("input{$this->getElementClassSelector()}").removeAttr('disabled')
            $("input{$this->getElementClassSelector()}").closest('div.btn-file').removeClass('btn-disabled')
            $(".file-preview-thumbnails").find('.fileinput-upload-button').removeAttr('disabled')
        }
    });
EOT;

        }
        //结束
    
    }`

经过以上步骤已经可以做到在页面上删除掉多余的图片了，但是！！！！保存时还是会存入数据库。

- 修改对应模型文件：app/WJY/Models/Goods.php，加入更新过程中处理逻辑
`<?php

namespace App\WJY\Models;

use Illuminate\Database\Eloquent\Model;

class Goods extends Model
{
    // 设置goods_images字段最大上传图片数
    const GOODS_IMAGES_COUNT = 5;
    
    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub

        static::updating(function ($update) {
            // 更新时，计算图片数量，多出的进行删除
            if (!empty($update->goods_images) && count($update->goods_images) > self::GOODS_IMAGES_COUNT) {
                $update->goods_images = array_chunk($update->goods_images, self::GOODS_IMAGES_COUNT)[0];
                // dd($update->goods_images);

            }
        });


    }
}
`
至此结束。

**Comment by wangjingyu** [comment]
可以参考这个看看：[https://github.com/z-song/laravel-admin/issues/5658#issue-1369001579](url)
