### ISSUE TITLE
laravel-admin v1.6.10 The page has expired due to inactivity.   Please refresh and try again.

### ISSUE THREAD

**Issue by Linlt1** [z-song/laravel-admin#3171]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.6.10

### Description:
laravel-admin登录后，
The page has expired due to inactivity. Please refresh and try again.

### Steps To Reproduce:
原本的laravel-admin 1.5的版本就有这个问题，后更新到1.6 仍然无法解决问题。
尝试过清除cookie也没有奏效

**Comment by xiaohuilam** [comment]
change your composer.json
```
{
    "require": {
        "encore/laravel-admin": "dev-master as v1.6.x-dev",
        ....
    }
}
```

and then 
```bash
composer update -vvv
```

retry the function

**Comment by Nicko0x1Chan** [comment]
i have the same matter, and @xiaohuilam suggestion doesn't work, anyone can tell me why happend?

**Comment by phuongaev** [comment]
Why do you not solve this problem thoroughly?
