### ISSUE TITLE
数据来自外部API

### ISSUE THREAD

**Issue by safly** [z-song/laravel-admin#3176]
- Laravel Version: 1.5
- PHP Version:7.2
- Laravel-admin: 1.6.0

### Description:
感谢作者！今天发现个小问题，数据来自外部API时不支持列sort和筛选，期待作者下次升级时可以考虑一下 :)

**Comment by safly** [comment]
https://laravel-admin.org/docs/zh/model-grid-data
建议在文档里提示下$grid->disableFilter();

**Comment by nkjackzhang** [comment]
你把filter传递的参数转换成外部api的参数是否可以实现排序和筛选？如果外部api支持排序和筛选的话。
