### ISSUE TITLE
如何重构 Laravel-admin 的左侧菜单栏

### ISSUE THREAD

**Issue by undefinedobj** [z-song/laravel-admin#3178]
- Laravel Version: 5.5.44
- PHP Version: 7.2.10
- Laravel-admin: 1.6.7

### Description:
如何重构原有的左侧菜单栏，主要是样式，和菜单栏的显示等等。

### Steps To Reproduce:
如何重构原有的左侧菜单栏

**Comment by chanble** [comment]
当前版本不支持， 我已经提交这个功能，要看看作者会不会采纳

**Comment by chanble** [comment]
现在没有这个功能，我已经提交改功能支持，看作者会不会采纳吧

**Comment by chanble** [comment]
https://github.com/z-song/laravel-admin/pull/3195

**Comment by chenjiabin** [comment]
咋没合并上
