### ISSUE TITLE
form->hidden疑似bug

### ISSUE THREAD

**Issue by hulkwan** [z-song/laravel-admin#318]
form-hidden的value值设置在update的时候不起作用，form传递的还是数据库中现有字段的值，而不是hidden的value值

**Comment by edwinhuish** [comment]
没有发现类似问题。

**Comment by z-song** [comment]
已修复

**Comment by twsphere** [comment]
$form->hidden($column)->value($value);
一樣有bug 無法 給值

**Comment by nkjackzhang** [comment]
> 
> 
> $form = new Encore\Admin\Widgets\Form()
> $form->hidden($column)->value($value);
> 一樣有bug 無法 給值

这种情况用$form->hidden($column)->default($value);就可以正常设值了

**Comment by xiaomlove** [comment]
> > $form = new Encore\Admin\Widgets\Form()
> > $form->hidden($column)->value($value);
> > 一樣有bug 無法 給值
> 
> 这种情况用$form->hidden($column)->default($value);就可以正常设值了

这。。。猜测是编辑时候数据是会从 $model 中获取来填充，而此时 $model 中并没有此 $column 的值，因此为 null，不会考虑 value()方法赋予的值。

**当要传递一个数据库不存在的字段的值时，不要使用  hidden()->value()，直接 hidden()->default()**
