### ISSUE TITLE
I want to updated the jquery.slimscroll.min.js(v1.3.8)

### ISSUE THREAD

**Issue by yamaguppy31** [z-song/laravel-admin#3184]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.6.9

### Description:
Does not work in browser(chrome73)

##### developertool error
`jquery.slimscroll.min.js?date=1554891142:1 [Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312`

### Steps To Reproduce:
use slimscroll!

![image](https://user-images.githubusercontent.com/20530099/55927305-8d0b2380-5c4f-11e9-8d71-af70cc324341.png)

**Comment by z-song** [comment]
@yamaguppy31 Download the latest version of [slimscroll](https://github.com/rochal/jQuery-slimScroll/releases) and replace `Laravel\public\vendor\laravel-admin\AdminLTE\plugins\slimScroll\jquery.slimscroll.min.js`
