### ISSUE TITLE
使用filter的datetime方法，出现datetimpicker未定义

### ISSUE THREAD

**Issue by lifenglsf** [z-song/laravel-admin#3185]
- Laravel Version: 5.7,28
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
 ```php 
$grid->filter(function ($filter) {
            $filter->between('send_time', Messages::$columnMapping['send_time'])->datetime();
        });
```
访问页面出现js错误
```javascript
Uncaught TypeError: $(...).datetimepicker is not a function
```

不知道什么原因datetimepicker的js未自动加载到html中

ps：使用了laravel的多模块功能 "caffeinated/modules"，5.0版本

**Comment by lifenglsf** [comment]
'middleware'    => config('admin.route.middleware'),
路由中的middleware使用admin的middleware就没问题了

**Comment by leexiaobo** [comment]
哪个文件？我的也有这个问题，还没解决

**Comment by lifenglsf** [comment]
路由的文件
