### ISSUE TITLE
MongoDB install, nearly there!

### ISSUE THREAD

**Issue by ludo1960** [z-song/laravel-admin#3188]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: latest

### Description:
fo;lowing on from here https://github.com/jenssegers/laravel-mongodb/issues/1739

This is laravel-admin bug, not laravel-mongodb bug
My solution:
Replace all content in function allNodes of Menu model by
return static::with('roles')->orderBy('order')->get()->toArray();

this gets the menu sort of working, still a bug in AdminTablesSeeder.php. install fails 

Exception trace:

  1   Encore\Admin\Auth\Database\AdminTablesSeeder::run()
      /var/www/slimmongo2.local.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

    125|         // add role to menu.
  > 126|         Menu::find(2)->roles()->save(Role::first());

If I manually input the starting values into the MongoDB, the laravel-admin package is displayed properly. But when I try to input data, I get " FatalThrowableError In ManagesTransactions.php line 109 :
Call to a member function beginTransaction() on null" Surely as a gifted coder you want to see your hard work be a success. Give us some clues where to look for solutions

**Comment by varshneygaurav** [comment]
Facing the same issue.
