### ISSUE TITLE
Encore\Admin\Show::init()报错

### ISSUE THREAD

**Issue by popfaker** [z-song/laravel-admin#3189]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: v1.6.10

### Description:
在使用Encore\Admin\Show::init() 初始化模型详情页时，提示错误
![image](https://user-images.githubusercontent.com/38718383/56008654-817f3180-5d0f-11e9-8a4c-10a308c55161.png)

排查发现，Encore\Admin\Show类中，缺少 Closure命名空间，加上use Closure, 即可正常显示。
![image](https://user-images.githubusercontent.com/38718383/56008710-b7bcb100-5d0f-11e9-8316-3ad49ef142c0.png)

望尽快修复

**Comment by z-song** [comment]
这个问题已经在ec2ab0d修复，等下一个版本发布，或者使用dev-master版本

**Comment by popfaker** [comment]
> 这个问题已经在 [ec2ab0d](https://github.com/z-song/laravel-admin/commit/ec2ab0dbfc04878a14bd245caaa5a5d97818d8bd) 修复，等下一个版本发布，或者使用dev-master版本

多谢
