### ISSUE TITLE
使用WangEditor时，切换不同编辑内容以后出现编辑器以及后台个别样式无法正确加载问题

### ISSUE THREAD

**Issue by sanmisanFan** [z-song/laravel-admin#319]
在form页面引入编辑器后，切换页面回到grid视图，或者直接去别的页面，这时候再进入任何有editor的页面，都会发现editor以及个别比如switch样式无法正常加载。官方demo中也存在此类问题。刷新页面就可以正常显示。

**Comment by edwinhuish** [comment]
能否指定具体的操作？如官方demo有的话，请指明链接。

**Comment by sanmisanFan** [comment]
在火狐浏览器中测试存在此问题，在其他浏览器中正常。似乎是页面资源缓存的问题。
具体在火狐浏览器下访问http://120.26.143.106/admin/editors  编辑器加载正常，此时点击菜单中其他页面链接，跳转到其他页面，之后在通过菜单点击回到Editors，火狐下就会无法正常加载编辑器组件。
![default](https://cloud.githubusercontent.com/assets/3042601/22138368/2ddbfcb2-df1b-11e6-9260-2683cdcd4f41.png)

**Comment by edwinhuish** [comment]
没有出错信息？

这个理应是WangEditor的兼容性没有做好，前端组件的问题，你应该去对应的github提issues了。。。或者你可以替换另外一种editor

**Comment by sanmisanFan** [comment]
我也是浏览器测试的时候在火狐下遇到的问题，查看了没有出错信息和样式加载错误信息。调试之后感觉是资源缓存的问题。我去咨询一下吧，别的editor目前比较正常。谢谢解答。

另外还有一个非常微小的问题：
![default](https://cloud.githubusercontent.com/assets/3042601/22140507/d2a7f1ae-df27-11e6-8597-1bd1d64ecead.png)
在form编辑页面工具条上的后退按钮关联事件没有定义，我自己的项目里面自己改掉了，非常小的问题。
![default](https://cloud.githubusercontent.com/assets/3042601/22140519/e8c233e6-df27-11e6-890c-90c63d8ffc89.png)

**Comment by edwinhuish** [comment]
@sanmisanFan 这个你最好发个pull request 给 @z-song , 我跟你一样，也不是这个项目的开发者。

**Comment by sanmisanFan** [comment]
@edwinhuish 没有问题，另外这个issue确定是WangEditor加载的问题。
