### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by hakhsin** [z-song/laravel-admin#3190]
- Laravel Version: 5.8.*
- Laravel-admin: last

### Description:
Hi, is the laravel-admin compatible with RTL languages?

**Comment by chanble** [comment]
I think it is not compatible

**Comment by cherryred5959** [comment]
I hope for this.

**Comment by amirbagh75** [comment]
>     * Laravel Version: 5.8.*
> 
>     * Laravel-admin: last
> 
> 
> ### Description:
> 
> Hi, is the laravel-admin compatible with RTL languages?

hi
i working on this project to prepare RTL admin panel ui (and persian lang)
https://amirbagh75.liara.run/?p=171

**Comment by bahadorfarahani** [comment]
I made #2154  for persian language and merged to master branch. If your @amirbagh75 are agree i can work on RTL version.

**Comment by amirbagh75** [comment]
> I made #2154 for persian language and merged to master branch. If your @amirbagh75 are agree i can work on RTL version.

hi bahador.
I was very busy and couldn't do it.
If you can and have the opportunity, I can help wherever you want.

**Comment by amirbagh75** [comment]
@bahadorfarahani 
are you working on rtl?

**Comment by bahadorfarahani** [comment]
@amirbagh75 
Yes i do. currently i am working on responsive part.

**Comment by amirbagh75** [comment]
> @amirbagh75
> Yes i do. currently i am working on responsive part.

@bahadorfarahani  are you still working?

**Comment by bahadorfarahani** [comment]
I doped this case because after i finalized my changes, admin css got edited and some new features like module box added to it. So i think we have to add RTL support to admin LTE css framework.
