### ISSUE TITLE
如何控制上传文件的后缀格式

### ISSUE THREAD

**Issue by hkylin** [z-song/laravel-admin#3201]
- Laravel Version: 
- PHP Version:7.3.4
- Laravel-admin: 1.6.9

### Description:
在进行文件上传，传ico文件时报错；想请教下可以在哪儿进行配置上传文件的后缀格式？
![QQ截图20190414202638](https://user-images.githubusercontent.com/9944291/56093181-f614c480-5ef7-11e9-80d9-1957ed0e0297.jpg)

**Comment by nkjackzhang** [comment]
admin里面的image field 组件是用rules='image'来验证的，底层是用了‘mimes’的rules，只支持'jpeg', 'png', 'gif', 'bmp', 'svg'这几个后缀，你可以直接自己定义你需要的'mimes' rules.

**Comment by hkylin** [comment]
> admin里面的image field 组件是用rules='image'来验证的，底层是用了‘mimes’的rules，只支持'jpeg', 'png', 'gif', 'bmp', 'svg'这几个后缀，你可以直接自己定义你需要的'mimes' rules.

这个rules='image'我倒是看到了，看了下，有个js文件中

> WebStack-Laravel-master\public\vendor\laravel-admin\bootstrap-fileinput\js\fileinput.min.js
有对文件格式的判断，
`getMimeType:function(e,t,i){switch(e){case"ffd8ffe0":case"ffd8ffe1":case"ffd8ffe2":return"image/jpeg";case"89504E47":return"image/png";case"47494638":return"image/gif";case"49492a00":return"image/tiff";case"52494646":return"image/webp";case"66747970":return"video/3gp";case"4f676753":return"video/ogg";case"1a45dfa3":return"video/mkv";case"000001ba":case"000001b3":return"video/mpeg";case"3026b275":return"video/wmv";case"25504446":return"application/pdf";case"25215053":return"application/ps";case"504b0304":case"504b0506":case"504b0508":return"application/zip";case"377abcaf":return"application/7z";case"75737461":return"application/tar";case"7801730d":return"application/dmg";default:switch(e.substring(0,6)){case"435753":return"application/x-shockwave-flash";case"494433":return"audio/mp3";case"425a68":return"application/bzip";default:switch(e.substring(0,4)){case"424d":return"image/bmp";case"fffb":return"audio/mp3";case"4d5a":return"application/exe";case"1f9d":case"1fa0":return"application/zip";case"1f8b":return"application/gzip";default:return t&&!t.match(/[^\u0000-\u007f]/)?"application/text-plain":i}}}}`
，但是不知道ico对应的这个hex代码是啥
还请指教下底层的文件是在哪儿修改 ，多谢~

**Comment by hkylin** [comment]
OK了 已解决，fileinput.min.js中增加icon文件的文件头即可~
`case"00000100":return"image/x-icon"`

**Comment by nkjackzhang** [comment]
> 
> 
> OK了 已解决，fileinput.min.js中增加icon文件的文件头即可~

你那截图里是框架的validate，怎么通过的？原来的validate可没有ico这个后缀。

**Comment by hkylin** [comment]
> > OK了 已解决，fileinput.min.js中增加icon文件的文件头即可~
> 
> 你那截图里是框架的validate，怎么通过的？原来的validate可没有ico这个后缀。

按照你上面说一样，他用rules='image'验证，我根据你说的在下面的(底层？)fileinput.min.js中找到了通过文件头来确定文件类型的判断，新增了这个image/x-icon，就可以了

**Comment by nkjackzhang** [comment]
本来我设想的是把image field的rules改成mimes:xxx,yyy这样的形式自定义扩展名，没想到你是改js文件，能实现就行。

**Comment by hkylin** [comment]
> 本来我设想的是把image field的rules改成mimes:xxx,yyy这样的形式自定义扩展名，没想到你是改js文件，能实现就行。

全靠兄台指点，谢谢哈~
