### ISSUE TITLE
请问一下，这个效果是怎么实现的？

### ISSUE THREAD

**Issue by w773880227** [z-song/laravel-admin#3202]
#请问一下,怎么实现这个效果
@z-song 

![QQ图片20190415145621](https://user-images.githubusercontent.com/38902915/56113031-40955000-5f8f-11e9-8d60-abdeae375109.png)

**Comment by w773880227** [comment]
> #请问一下,怎么实现这个效果
> @z-song
> 
> ![QQ图片20190415145621](https://user-images.githubusercontent.com/38902915/56113031-40955000-5f8f-11e9-8d60-abdeae375109.png)

**Comment by w773880227** [comment]
> #请问一下,怎么实现这个效果
> @z-song
> 
> ![QQ图片20190415145621](https://user-images.githubusercontent.com/38902915/56113031-40955000-5f8f-11e9-8d60-abdeae375109.png)

**Comment by w773880227** [comment]
我是想做一个自动分词    获取标签的功能    请问怎么才能获取input里面输入的数据

**Comment by z-song** [comment]
试试这个
```php
$form->multipleSelect('class')->options(function () {
    return jieba($this->title);
});
```

**Comment by w773880227** [comment]
额   实在不好意思。能不能告诉我这个按钮怎么实现的？已点start，感谢

![QQ图片20190426191336](https://user-images.githubusercontent.com/38902915/56804252-adde9600-6857-11e9-9ca2-011c61e5b44c.png)

**Comment by z-song** [comment]
https://github.com/z-song/demo.laravel-admin.org/blob/master/app/Admin/Controllers/PostController.php#L159

上面这个仓库有全套demo代码，clone下来很好找
