### ISSUE TITLE
how to hidden the delete image button?

### ISSUE THREAD

**Issue by youruan** [z-song/laravel-admin#3206]
- Laravel Version: 5.8.
- PHP Version:
- Laravel-admin: 1.6.11

### Description:
 sometimes, we need to hidden the delete image button, but we don't find the document about that, who know about that? thanks~

**Comment by z-song** [comment]
Where to hide the button？

**Comment by youruan** [comment]
> Where to hide the button？

in form image field

**Comment by z-song** [comment]
The button is hidden by default

Show me the screenshot or codes?

**Comment by youruan** [comment]
![image](https://user-images.githubusercontent.com/40481556/56187144-5587e700-6054-11e9-8f72-fd9c14ecd1f5.png)

![image](https://user-images.githubusercontent.com/40481556/56187168-68022080-6054-11e9-885c-32aa2e60081e.png)

when id edit it the button show

**Comment by z-song** [comment]
@youruan 这是个bug，提交了commit 03896d5来修复这个问题，等下个版本发布生效

**Comment by youruan** [comment]
> @youruan 这是个bug，提交了commit [03896d5](https://github.com/z-song/laravel-admin/commit/03896d52fc2490aaf1484c13b8b89ca9d017bf61) 来修复这个问题，等下个版本发布生效

收到 多谢
