### ISSUE TITLE
於NestedForm明細中使用CKEditor，無法正常加載。

### ISSUE THREAD

**Issue by yang5664** [z-song/laravel-admin#321]
可能原因
```ruby
// Editor.php中
CKEDITOR.replace('{$this->column}', //<==重複 id
```
已存在的資料，目前改用 $this->elementName，Html Tag name(例：details[old][3][spec])，可以暫時解決，
不過當點擊"新增"，此時是用template中產生新明細，也會無法正常加載，正在試著解決。

**Comment by yang5664** [comment]
目前暫時解法
```ruby
editor.blade.php
...
<textarea class="form-control" input-type="ckeditor" 
...
Editor.php
$column = trim($this->elementName) === '' ? $this->column : $this->elementName;
$this->script = "
var count = $(\".has-many-details-forms [input-type=ckeditor]\").size();  <==抓取ckeditor在明細的數量
var column = '{$column}';
column = column.replace(/_key_/g, count); <===替換xxx[new][_key_][xxx] => xxx[new][3][xxx]
CKEDITOR.replace(column,{
...
```
若有正確的解法，麻煩告訴我，謝謝大大。

**Comment by z-song** [comment]
因为ckeditor这个包引用的是cdn资源，网络不好的情况会影响使用，所以在以后的版本里面会移除掉，推荐的办法是扩展一个ckeditor，参考这里 ：https://gist.github.com/z-song/d6a32634f98f74b9243550c6389356fc

**Comment by yang5664** [comment]
原因應該不是這個，因為我需要對ckeditor做一些客製的config設定，如語系/主題更換、隱藏按鈕、上傳圖片的資源管理(使用unisharp/laravel-ckeditor、unishar/laravel-filemanager)，我已經將內部cdn的取消，改為本機加載，所以網絡應該沒有影響，ckeditor使用CKEDITOR.replace('{$this->column}'是採用 id 或是 name進行渲染編輯器(另外可設定class為ckeditor)，所以只要id或name重複的話，就會出現錯誤。

**Comment by z-song** [comment]
因为`CKEDITOR`只能通过`id`来渲染编辑器，所以你可以在[gist](https://gist.github.com/z-song/d6a32634f98f74b9243550c6389356fc)里面看到，里面引入了`jquery adapter`,这样就可以通过class来渲染，避免id重复的问题。

**Comment by yang5664** [comment]
@z-song 謝謝大大，我再來試試看。
