### ISSUE TITLE
Unable to edit users

### ISSUE THREAD

**Issue by siavashgolabi** [z-song/laravel-admin#3210]
- Laravel Version: 5.7.26
- PHP Version: 7.1.9
- Laravel-admin: 1.6.9

### Description:
I have extended user model as below:

- This is my new model:

         class CustomAdministrator extends Administrator
          {
               public function __construct(array $attributes = [])
               {
                    parent::__construct($attributes);
                    array_push($this->fillable, 'university_id');
               }
              public function university()
              { 
                   return $this->belongsTo(University::class);
               }

          }

- made this changes to config/admin.php

      // User tables and model.
      'users_model' => \App\Models\CustomAdministrator::class,

- defined model binding in the boot method in "app\Providers\RouteServiceProvider.php"
       
      Route::bind('admin-user', function ($value) {
            if (is_numeric($value)) {
                return CustomAdministrator::findOrFail($value);
            } else {
                return CustomAdministrator::where('username', $value)->firstOrFail();
            }
        });

- and added my route as below in "app\admin\routes.php"

        Route::group([
        'prefix'        => config('admin.route.prefix'),
        'namespace'     => config('admin.route.namespace'),
        'middleware'    => config('admin.route.middleware'),
         ], function (Router $router) {

        Route::resource('auth/admin-users', AdminUserController::class);

        });

### Steps To Reproduce:
Everything works fine, I can see users list and create new one but I can't delete or edit any user. whenever I want to edit a user I get this error:

    BadMethodCallException In Macroable.php line 100 :
    Method Illuminate\Database\Eloquent\Collection::setAttribute does not exist.

**Comment by z-song** [comment]
What about remove the model binding step?

**Comment by siavashgolabi** [comment]
> 
> 
> What about remove the model binding step?

What do you mean by that? How can I remove the binding model? 
Isn't it enough to define new model binding in the boot method in "app\Providers\RouteServiceProvider.php"?
Can you explain more. Thanks

**Comment by z-song** [comment]
```php
Route::bind('admin-user', function ($value) {
      if (is_numeric($value)) {
          return CustomAdministrator::findOrFail($value);
      } else {
          return CustomAdministrator::where('username', $value)->firstOrFail();
      }
  });
```
Remove the above code in your RouteServiceProvider.php

**Comment by siavashgolabi** [comment]
> 
> 
> ```
> Route::bind('admin-user', function ($value) {
>       if (is_numeric($value)) {
>           return CustomAdministrator::findOrFail($value);
>       } else {
>           return CustomAdministrator::where('username', $value)->firstOrFail();
>       }
>   });
> ```
> 
> Remove the above code in your RouteServiceProvider.php

Thank you so much. It did work, although I don't understand why binding new model was the problem

**Comment by z-song** [comment]
If the route model is bound, the first parameter passed into the `update` and `delete` action is a CustomAdministrator instance instead of the user id, which breaks the conventions for delete and update methods.
