### ISSUE TITLE
Where to change Global $id

### ISSUE THREAD

**Issue by ludo1960** [z-song/laravel-admin#3211]
- Laravel Version: 6.8
- PHP Version:7.2
- Laravel-admin: latest

### Description:The global $id field is tied to the id of each of the controllers, I want to change that to the _id of each controller. I can manually edit each controller, like so:
`use Encore\Admin\Facades\Admin; `and 
` $id = Admin::user()->_id ;`
This works, but I am hoping there is a global setting somewhere.

Thanks...

**Comment by nkjackzhang** [comment]
Which global $id do you mean? The "id" field is defined in Model，when you define a Model, you can change it to "_id".

**Comment by ludo1960** [comment]
Hello,

I was trying to install laravel-admin with a mongodb backend, but had to give up because mongo does not support pivot tables, I thought if I could find the $id source code in the package I could somehow work round the issue. But I failed .

**Comment by nkjackzhang** [comment]
> 
> 
> Hello,
> 
> I was trying to install laravel-admin with a mongodb backend, but had to give up because mongo does not support pivot tables, I thought if I could find the $id source code in the package I could somehow work round the issue. But I failed .

Laravel as well as Lavarel-admin doesn't support mongodb, according to [this page](https://laravel.com/docs/5.8/database)

**Comment by ludo1960** [comment]
Have a look at https://github.com/jenssegers/laravel-mongodb laravel works perfectly with mongodb


________________________________

**Comment by nkjackzhang** [comment]
The laravel-mongodb is a third lib, not supported originally in laravel and laravel-admin.The Model in laravel-admin is laravel's Model, not Jenssegers's Model, for example, Encore\Admin\Auth\Database\Administrator is a laravel's Model, not Jenssegers's Model, maybe if you use Jenssegers's Model as it's parent Model, you can use '_id' instead of 'id' which is defined in laravel's Model.
