### ISSUE TITLE
在Grid中使用belongstomany作为数据源时，会获取到错误的ID数据

### ISSUE THREAD

**Issue by kevin1018** [z-song/laravel-admin#3212]
举例 用户与 角色 表，多对多关系，通过user_role表建立关系

```
class User {
public roles() {
    return $this->belongsToMany(Role::class, 'user_role');
}
}
```

当使用user->roles()作为Grid的数据源时，期望获取role的id，但实际id字段的数据是 user_role 的id内容。

查看代码定位问题应该在：
https://github.com/z-song/laravel-admin/blob/be5c07e5daf8b2d5ddfad72bbcd5a6a90dc23e82/src/Grid/Model.php#L361

尝试
```
User::find(1)->roles()->getQuery()->get();
// 获取到的id内是user_role表的数据
```

尝试
```
User:find(1)->roles()->get();
// 获取到的id是role表的数据 ，这个应该是期望值
```

因此是否应该将`getQuery()`这个方法去掉

考虑到这里可能会有其他影响，没有直接发起PR。

**Comment by z-song** [comment]
【当使用user->roles()作为Grid的数据源时】  你的grid代码是怎么写的？

**Comment by kevin1018** [comment]
用的 https://laravel-admin.org/docs/zh/model-show 里面的 一对多或多对多关系 用法

**Comment by z-song** [comment]
是在详情页显示多对多grid的时候出现这个问题是吧？

**Comment by kevin1018** [comment]
是的

**Comment by z-song** [comment]
没有重现你的问题

在`\Encore\Admin\Controllers\UserController::detail`方法里加上下面的代码，id显示正常
```php
    $show->roles('Roles', function ($roles) {
            $roles->id('ID');
            $roles->name();
        });
```

**Comment by kevin1018** [comment]
是我没描述清楚，测试用例有偏差

将admin_role_users 表修改一下，增加id列，设置为自增，修改id为任意数字，即可复现问题

**Comment by z-song** [comment]
@kevin1018 扒了一下eloquent的代码，发现执行`User:find(1)->roles()->get();`的时候发现下面的逻辑
https://github.com/illuminate/database/blob/0077d90140cd3ec52ea75964b0d2005699cfc9f8/Eloquent/Relations/BelongsToMany.php#L607-L609
```php
        $models = $builder->addSelect(
            $this->shouldSelect($columns)
        )->getModels();
```
其中`$this->shouldSelect($columns)`的值是
```php
array (
 0 => 'admin_roles.*',
 1 => 'admin_role_users_copy.user_id as pivot_user_id',
 2 => 'admin_role_users_copy.role_id as pivot_role_id',
)
```
只读取了中间表的两个关系字段，忽略掉了中间表的主键id

## 解决办法
```php
    $show->roles(function ($role) {

            // 不读取中间表的字段
            $role->model()->select(['admin_roles.*']);

            $role->id();
            $role->name();
        });
```
