### ISSUE TITLE
select load  二级联动 编辑 时不显示默认值

### ISSUE THREAD

**Issue by chencongbao** [z-song/laravel-admin#3216]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6.11

修改select.php

原
$(document).off('change', "{$this->getElementClassSelector()}");
$(document).on('change', "{$this->getElementClassSelector()}", function () {
    var target = $(this).closest('.fields-group').find(".$class");
    $.get("$sourceUrl?q="+this.value, function (data) {
        target.find("option").remove();
        $(target).select2({
            data: $.map(data, function (d) {
                d.id = d.$idField;
                d.text = d.$textField;
                return d;
            })
        }).trigger('change');

    });
});

改成

$(document).off('change', "{$this->getElementClassSelector()}");
$(document).on('change', "{$this->getElementClassSelector()}", function () {
    var target = $(this).closest('.fields-group').find(".$class");
    $.get("$sourceUrl?q="+this.value, function (data) {
        target.find("option").remove();
        $(target).select2({
            data: $.map(data, function (d) {
                d.id = d.$idField;
                d.text = d.$textField;
                return d;
            })
        }).trigger('change');

var value = target.data('value') + '';
  
  if (value) {
    value = value.split(',');
    target.select2('val', value);
  }
    });
});

**Comment by ayousoft** [comment]
好像只要是select2，使用ajax加载数据，都会这样不设置edit加载的值。

**Comment by DesarrolloSiget** [comment]
I have the same problem

**Comment by lakely** [comment]
add following:

if (target.data('value')) {
          var value = target.data('value');
          target.val(value).trigger('change');
}
