### ISSUE TITLE
composer require 一直卡住

### ISSUE THREAD

**Issue by wongvio** [z-song/laravel-admin#3219]
- Laravel Version: 5.8.10
- PHP Version:7.1.4
- Laravel-admin: 准备安装最新版

### Description:
换了很多个composer镜像源，都是卡在 ``Updating dependencies (including require-dev)`` 就没有反应了
```
Using version ^1.6 for encore/laravel-admin
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
```

### Steps To Reproduce:
composer require encore/laravel-admin 就会出现

**Comment by z-song** [comment]
没有重现你的问题

加上-vvv参数运行命令来显示更多信息

`composer require encore/laravel-admin -vvv`

**Comment by kapbook-huwenfeng** [comment]
我这边也遇到了：这个问题你有解决方案么？
