### ISSUE TITLE
change https 

### ISSUE THREAD

**Issue by luozhanxin** [z-song/laravel-admin#322]
网站添加https加密后出现
Mixed Content: The page at 'https://admin.xxxx.com/auth/permissions/1' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://admin.lxxxx.cn/auth/permissions'. This request has been blocked; the content must be served over HTTPS.
请问在那里可以修改以解决此问题

**Comment by z-song** [comment]
是在什么操作下产生这个问题的？

**Comment by yang5664** [comment]
假如在https下存取http的url，如圖片的話，瀏覽器就會出現這樣子的警告，應該要將所有http的資源轉為https，如cdn、圖片url等等…。
甚至要在middleware判斷目前url不為http時，要強制轉為https。

**Comment by luozhanxin** [comment]
把laravel-admin部署到https加密后出现这个问题的

**Comment by z-song** [comment]
或许要修改.env里面的APP_URL为`https://admin.xxxx.com`吧

**Comment by judgej** [comment]
I had this issue too, and changing the `.env` entry made no difference, even after uninstalling and reinstalling. It seems that the `secure` option in `config/admin.php` got set to `false` during the first install, and that then remembered the old URL scheme in `.env`.

Manually setting the `secure` option to `true` fixed it.

**Comment by saber13812002** [comment]
In my case it's because I wasn't aware that the asset() function didn't handle https automatically (as pointed out by frankfurt-laravel's answer).

To get around this, since I don't use SSL in dev, I set ASSET_URL in the .env to the https url:

APP_URL=https://example.com
ASSET_URL="${APP_URL}"

**Comment by penmetsa18** [comment]
You need set `ADMIN_HTTPS=true` in `.env` file
```

/*
    |--------------------------------------------------------------------------
    | Access via `https`
    |--------------------------------------------------------------------------
    |
    | If your page is going to be accessed via https, set it to `true`.
    |
    */
    'https' => env('ADMIN_HTTPS', false),

```
