### ISSUE TITLE
文档问题，模型表单中的select选择框

### ISSUE THREAD

**Issue by Dev-Liangjian** [z-song/laravel-admin#3220]
- Laravel-admin: 1.6.11

### Description:
模型表单中的select选框的参数在 https://laravel-admin.org/docs/zh/model-form 文档表述为
```
    $directors = [
        'John'  => 1,
        'Smith' => 2,
        'Kate'  => 3,
    ];

    $form->select('director', '导演')->options($directors);
````

而在 [文档的另外一处](https://laravel-admin.org/docs/zh/model-form-fields#select%E9%80%89%E6%8B%A9%E6%A1%86)表述为

```
$form->select($column[, $label])->options([1 => 'foo', 2 => 'bar', 'val' => 'Option name']);
```

所以select选择框的options参数形式哪种为正确的？
```
    $directors1 = [
        'John'  => 1,
        'Smith' => 2,
        'Kate'  => 3,
    ];
    $directors2 = [
       1 => 'John',
       2 => 'Smith',
       3 => 'Kate' ,
    ];
```

猜测：据我亲自验证应该为 $directors2的参数形式为正确的

**Comment by z-song** [comment]
正确的参数形式为`['value' => 'text']`,  我把第一处文档调整了一下，谢谢
