### ISSUE TITLE
Laravel 5.8 Deprecated String and Array Helpers Functions

### ISSUE THREAD

**Issue by noogen** [z-song/laravel-admin#3222]
- Laravel Version: 5.8.*
- PHP Version: ^7.2.*
- Laravel-admin: ^1.6.11

### Description:

Laravel 5.8 Deprecated String and Array Helpers Functions
https://laravel.com/docs/5.8/upgrade#string-and-array-helpers 
https://github.com/laravel/helpers/blob/master/src/helpers.php

### Steps To Reproduce:

Errors when these functions are used: array_set, array_dot, etc..  see the helpers.php above for additional method details.

Add dependency to laravel\helpers or go through and replace all (chore) to use `Arr::` or `Str::` facades for future compatibility.

**Comment by z-song** [comment]
Please feel free to send pull request.
