### ISSUE TITLE
修改模型数据源后的查询

### ISSUE THREAD

**Issue by fireinme** [z-song/laravel-admin#3224]
- Laravel Version: 5.5.30
- PHP Version:7.0.23
- Laravel-admin: 1.5.19

### Description:
修改了模型数据源，来自复杂SQL查询（我的是分表数据），页面都能正常展示，但是就是查询一致报错，找不到对应表，因为是分表所有找不到。如何解决查询问题？

**Comment by DcxIt** [comment]
大哥，你是在框架自带的搜索方法下写分表查询的方法吗
