### ISSUE TITLE
post error 419 in v1.6.11

### ISSUE THREAD

**Issue by pennfly** [z-song/laravel-admin#3225]
Laravel Version: v5.8.13
PHP Version:7.2.15
Laravel-admin: v1.6.11

我今晚项目运行composer update后发生了 #1651  的问题.

在我将composer.json中的laravel-admin版本"encore/laravel-admin": "1.6.11"修改为更新前的"encore/laravel-admin": "1.6.10",后恢复正常。

我在我的项目中能复现，不确定其他人是否遇到这个问题。

以下是我的出现问题时的composer.json
`{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": [
        "framework",
        "laravel"
    ],
    "license": "MIT",
    "require": {
        "php": "^7.1.3",
        "encore/laravel-admin": "^1.6",
        "fideloper/proxy": "^4.0",
        "laravel-admin-ext/log-viewer": "^1.0",
        "laravel-admin-ext/media-manager": "^1.0",
        "laravel-admin-ext/redis-manager": "^1.0",
        "laravel/framework": "5.8.*",
        "laravel/passport": "^7.2",
        "laravel/tinker": "^1.0"
    },
    "require-dev": {
        "beyondcode/laravel-dump-server": "^1.0",
        "filp/whoops": "^2.0",
        "fzaninotto/faker": "^1.4",
        "mockery/mockery": "^1.0",
        "nunomaduro/collision": "^2.0",
        "phpunit/phpunit": "^7.5"
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/"
        },
        "classmap": [
            "database/seeds",
            "database/factories"
        ]
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "minimum-stability": "dev",
    "prefer-stable": true,
    "scripts": {
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    }
}
`

**Comment by z-song** [comment]
所有的post请求都有这个问题，试试清空各种缓存呢？

**Comment by pennfly** [comment]
更换浏览器后正常了。感谢大佬
