### ISSUE TITLE
Call to undefined method Encore\Admin\Show::extend()

### ISSUE THREAD

**Issue by nosun** [z-song/laravel-admin#3232]
- Laravel Version:5.7
- PHP Version:7.1
- Laravel-admin: 1.6.11

### Description:
view::extend() undefined method 错误

### Steps To Reproduce:

按照官方文档扩展 view 方法，在 bootstrap.php 中设置：

Encore\Admin\Show::extend('custom', CustomShow::class);

然后，报错，看了下 show 类，确实没有 extend 方法

**Comment by z-song** [comment]
更新到v1.6.12

**Comment by nosun** [comment]
真快～
