### ISSUE TITLE
阿里云 oss 上传文件，返回异常， object name is empty。

### ISSUE THREAD

**Issue by unizhu** [z-song/laravel-admin#3235]
- Laravel Version: 5.8
- PHP Version: 7.3.1
- Laravel-admin: 1.6.12

### Description:
阿里云 oss 上传文件，返回异常， object name is empty。
看情况好像是第一次上传成功了，但又传了第二次到oss，然后就报错了。
用文档中七牛云存储是可以正常使用的。

### Steps To Reproduce:
1.安装文档中推荐的aliyun oss 插件 （我也换过几个不同的），经过测试是可用的。
2.设置admin.php 中的 disk 为 oss
3. 后台controller中 $form->image('logo', 'Logo');
4. 上传图片后报错： object name is empty ，这个异常是官方aliyun oss sdk 抛出的。
5. 通过日志文件查看，发现好像进行了2次上传。
6. 其实阿里云oss里已经有这个上传的文件了，但是laravel admin没有捕获到。

**Comment by Louhwz** [comment]
还有一种可能是文件写入时权限不足，导致上传文件为空，亲测修改目录权限即可。
