### ISSUE TITLE
1.6.12 导出当前页会导出部数据

### ISSUE THREAD

**Issue by leo-yi** [z-song/laravel-admin#3236]
- Laravel Version: 5.7
- PHP Version: 7.2
- Laravel-admin: 1.6.12

### Description:
使用新增 Laravel-Excel 3.* 导出时， 选择导出当前页跟导出全部是一样的

**Comment by z-song** [comment]
确实有这个问题

**Comment by leo-yi** [comment]
request($model->getPerPageName())  这里会出现 NULL 值 导致：

**Comment by terranc** [comment]
可以先针对1.6.12里修复的bug发布一个新版本不

**Comment by oskey** [comment]
可以先针对1.6.12里修复的bug发布一个新版本不? 同求

**Comment by z-song** [comment]
@terranc @oskey 已经发布`v1.6.13`版本

**Comment by nosun** [comment]
v1.6.13 版本，好像问题仍然在：

筛选：无效
当前页：无效

新弹出的 url 显示出了 page 和筛选信息，但是最终还是导出了全部数据。

**Comment by EzrealR** [comment]
一样的问题，我现在1.7的版本还是有这个问题
