### ISSUE TITLE
tab里面生成的id会重复，导致tab无法切换

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3238]
https://github.com/z-song/laravel-admin/blob/662a77ac0f07cd627dc9470aaa73b22097386b20/src/Form/Tab.php#L50

`$id = uniqid('form-');`生成的id重复导致tab无法切换。

原因不知道。
我本机生成的不重复，但服务器上就是重复的。
![深度截图_选择区域_20190424162537](https://user-images.githubusercontent.com/10061650/56644307-070ac600-66ae-11e9-925f-eed3c4f8b71a.png)

**Comment by ichynul** [comment]
远程服务器：win server 2008 使用 IIS 7
测试了一下，重复率很高。
```php
for ($i = 0; $i < 10; $i += 1) {
            \Log::info(uniqid('form'));
        }
```
![深度截图_选择区域_20190424164954](https://user-images.githubusercontent.com/10061650/56645862-0e7f9e80-66b1-11e9-974b-ba83d84f9ecf.png)

**Comment by z-song** [comment]
提交了修复，以当前的tab的序号来拼id
