### ISSUE TITLE
面包屑导航Home汉化处理

### ISSUE THREAD

**Issue by yhs603** [z-song/laravel-admin#3239]
- Laravel Version: 5.8.8
- PHP Version:7.1.3
- Laravel-admin: 1.6.12

### Description:
@z-song 面包屑导航的Home建议做语言包处理，本来是可以继承自己改，但为了如此小的功能把所有的view发布一次到自己的项目中个人觉得有点得不偿失，建议更改下。

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/17921758/56644911-3a9a2000-66af-11e9-89cc-0dea06644e60.png)
![image](https://user-images.githubusercontent.com/17921758/56645141-ad0b0000-66af-11e9-9fd9-49425b4dbc6b.png)

**Comment by yhs603** [comment]
希望大神处理下啊，改成语言包完美解决该问题@z-song

**Comment by zmj1368** [comment]
希望大神处理下,不要沉!
