### ISSUE TITLE
NestedForm使用驗證(必填…)，當驗證失敗時，所有明細資料會被更新成同一筆資料。

### ISSUE THREAD

**Issue by yang5664** [z-song/laravel-admin#324]
<img width="611" alt="screen shot 2017-01-21 at 11 02 21 am" src="https://cloud.githubusercontent.com/assets/5953010/22171442/2018fefa-dfc9-11e6-89b7-57569e576390.png">

```ruby
驗證失敗時
```
<img width="592" alt="screen shot 2017-01-21 at 11 00 33 am" src="https://cloud.githubusercontent.com/assets/5953010/22171434/f15313f8-dfc8-11e6-9a29-bc920654c7c8.png">

**Comment by edwinhuish** [comment]
这个问题已经解决，请稍等 @z-song 更新并打 tag 吧。
