### ISSUE TITLE
如何实现表单修改做二次提醒

### ISSUE THREAD

**Issue by bfqymmt** [z-song/laravel-admin#3240]
- Laravel Version: 5.7.19
- PHP Version:7.2
- Laravel-admin: 1.6.7

### Description:
表单修改提交的时候，如何实现弹出框做二次提醒功能？参考删除前的提醒，想使用删除的提醒框。

**Comment by z-song** [comment]
给当前页面注入js
```php

Admin::script('$('form').on('submit', function () {
     // 弹出confirm
})');

```
