### ISSUE TITLE
菜单没有做本地化

### ISSUE THREAD

**Issue by mobileliker** [z-song/laravel-admin#3241]
- Laravel Version: 5.5
- PHP Version:PHP7.3
- Laravel-admin: 1.7.11

### Description:
菜单没有做本地化

### Steps To Reproduce:
lang目录的admin.php有预留menu_titles变量
但是AdminTablesSeeder的代码却没有使用该本地化的字段，是有意为之还是忘了？

### 解决方案
- 只需要在语言文件加入：
```
    'menu_titles' => [
        'Index' => '首页',
        'Admin' => '管理员',
        'Users' => '用户',
        'Roles' => '角色',
        'Permission' => '权限',
        'Menu' => '菜单',
        'Operation log' => '操作日志',
    ],
```
- 将AdminTablesSeeder复制到填充器所在目录，修改对应的title为本地化字段，然后加到DataSeeder即可

PS: 但是我觉得更好的方法还是直接在Laravel-admin提供支持而非自己改

**Comment by almas1992** [comment]
菜单不是保存在数据库的麽，可在菜单管理里自己改





**来自GitHub小程序客户端：**

![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

**Comment by mobileliker** [comment]
> 菜单不是保存在数据库的麽，可在菜单管理里自己改
> 
> **来自GitHub小程序客户端：**
> 
> ![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)

可以菜单管理哪里改，但是每次开发项目完项目部署都要改一次是非常麻烦的，增加部署的工作量

**Comment by almas1992** [comment]
> > 菜单不是保存在数据库的麽，可在菜单管理里自己改
> > **来自GitHub小程序客户端：**
> > ![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)
> 
> 可以菜单管理哪里改，但是每次开发项目完项目部署都要改一次是非常麻烦的，增加部署的工作量

考虑部署工作量，建议自己写个artisan命令，清空menu表，根据项目需要重新写入菜单信息，权限信息。这只是个人建议，我一般都是这么做的

**Comment by mobileliker** [comment]
> > > 菜单不是保存在数据库的麽，可在菜单管理里自己改
> > > **来自GitHub小程序客户端：**
> > > ![image](https://user-images.githubusercontent.com/8692455/51429898-b159f400-1c4e-11e9-91a1-59cd1fab5042.png)
> > 
> > 
> > 可以菜单管理哪里改，但是每次开发项目完项目部署都要改一次是非常麻烦的，增加部署的工作量
> 
> 考虑部署工作量，建议自己写个artisan命令，清空menu表，根据项目需要重新写入菜单信息，权限信息。这只是个人建议，我一般都是这么做的

我一般都是写一个菜单填充器和权限填充器来完成这个的

**Comment by tingfeng-key** [comment]
希望菜单添加本地化支持，在执行admin:install之前修改local配置应该可以直接入库
