### ISSUE TITLE
1.6.10版本编辑时图片不显示

### ISSUE THREAD

**Issue by owen4comes** [z-song/laravel-admin#3248]
- Laravel Version: 5.5.*
- PHP Version:7.1
- Laravel-admin: 1.6.10

### Description:

升级到1.6.10后，编辑时图片不显示。之前1.5版本的时候是能显示的。

我已确认做过以下操作：

（1）已更新静态资源，并清除了浏览器的缓存。在浏览器里看到bootstrap-fileinput的版本为v4.5.2
（2）已执行过php artisan config:clear、composer dump-autoload
（3）filesystem中disks中的admin配置已有url值（其实以前我也遇到过图片不显示的问题，那次是因为这里url没有写上去，后来写了就OK了，但现在升了1.6.10后又不行了），代码：
```
'admin' => [
            'driver' => 'local',
            'root' => public_path('/'),
            'url' => '/',
            'visibility' => 'public',
        ],
```
（4）admin.php中upload配置如下：
```
'upload' => [
        'disk' => 'admin',
        'directory' => [
            'image' => 'upload/admin/images/'.date('Y-m-d'),
            'file'  => 'files',
        ],
    ],
```
（5）数据库中图片地址存放的值为：upload/admin/images/201x-xx-xx/XXX.jpg

由于上述这些配置都是之前一直在用的，所以我目前也无法判断是哪里导致了图片不显示。请帮忙看一下谢谢。

### Steps To Reproduce:

如描述。

**Comment by z-song** [comment]
试试更新到v1.6.12看下是否正常

**Comment by owen4comes** [comment]
升级到v1.6.12已正常，谢谢。
