### ISSUE TITLE
1.6.12 Hasmany Remove Button malfunction

### ISSUE THREAD

**Issue by mineschan** [z-song/laravel-admin#3249]
- Laravel Version: 5.8.14
- PHP Version: 7.2
- Laravel-admin: 1.6.12

### Description:

Remove button in hasmany hide the row, but after form submit, relationship is not deleted.
Revert to 1.6.11 fixes the problem.

**Comment by tezrik** [comment]
#3234

**Comment by z-song** [comment]
Fixed
