### ISSUE TITLE
关于自定义按钮

### ISSUE THREAD

**Issue by unizhu** [z-song/laravel-admin#3251]
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-admin: 1.6.12

### Description:

Show:
显示模型中没找到可以去掉编辑和删除的按钮。。

**Comment by nosun** [comment]
$show->panel()->tools(function ($tools) use ($id) {
            $tools->disableDelete();
            $tools->disableEdit();
        });

应该可以
