### ISSUE TITLE
能不能增加 deleting , deleted 的方法？

### ISSUE THREAD

**Issue by unizhu** [z-song/laravel-admin#3252]
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-admin: 1.6.12

### Description:
能不能参照 form 的 saving 方法，增加 deleting , deleted 的方法？防止误删数据

**Comment by z-song** [comment]
你可以用模型的deleting , deleted的两个事件来处理这个情况

**Comment by unizhu** [comment]
@z-song 
1。模型里根据条件禁止删除后，返回还是删除成功
2.  如果记录里存在oss上传的图片，那么先会把oss里的图片删掉里，但是这样返回列表后，会出现找不到图片的异常。

**Comment by z-song** [comment]
考虑下个版本加上

**Comment by z-song** [comment]
已经加上了，等下个版本发布

**Comment by fg607** [comment]
期待新版本,因为laravel 模型的事件回调真的获取不到模型id
