### ISSUE TITLE
image 字段设置必填之后，更新时提示“请选择一个文件”

### ISSUE THREAD

**Issue by nosun** [z-song/laravel-admin#3253]
- Laravel Version: 5.7
- PHP Version: 7.1
- Laravel-admin: 1.6.12

### Description:
如题，form 表单中image 字段设置为必填项，保存记录之后，在更新的过程中，并不能正确的判断 image 字段实际上已经有值，会提示“请选择一个文件”，前端校验卡住。

**Comment by z-song** [comment]
提交了修复
