### ISSUE TITLE
How to format date in grid

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3254]
- Laravel Version: 5.8.14
- PHP Version: 7.3.3
- Laravel-admin: 1.6.12

### Description:
How I can formata the date column on a grid? I tried with:
` ->format('d/m/Y');`

But doesn't works.

Any solution?

Thanks

**Comment by Tiny-Fire** [comment]
$grid->column('active_time', 'time')->display(function ($active_time) {
    return 'xxxxxx';
});

**Comment by mendizalea** [comment]
> $grid->column('active_time', 'time')->display(function ($active_time) {
> return 'xxxxxx';
> });

Thanks you, works fine :)

**Comment by mendizalea** [comment]
Thanks @Tiny-Fire
