### ISSUE TITLE
`Admin::registerAuthRoutes();` 增加路由命名前缀建议

### ISSUE THREAD

**Issue by learnku** [z-song/laravel-admin#3257]
@jonphipps  @Fisiu  @hayeah  @noogen  @terranc 
- Laravel Version: ^5.7
- PHP Version: ^7.1
- Laravel-admin: ^1.6

### Description: 
建议将 文件：`\vendor\encore\laravel-admin\src\Admin.php` 中定义的路由名称 全部加上 `admin.` 前缀。如下图这样.
![image](https://user-images.githubusercontent.com/49932979/56789797-621af500-6835-11e9-98f1-73b0c5444f75.png)

### 效果
![image](https://user-images.githubusercontent.com/49932979/56789856-8080f080-6835-11e9-9aad-c726fc3f38ce.png)

我总觉得，这样会不会比较好，或者说有其他方案可以实现我这种功能呢？

**Comment by z-song** [comment]
欢迎提交pr

**Comment by truesnow** [comment]
admin/routes.php 中的可以给命名加上 admin 前缀吗？
