### ISSUE TITLE
1.6.12版本无法添加菜单

### ISSUE THREAD

**Issue by owen4comes** [z-song/laravel-admin#3258]
Laravel Version: 5.5.*
PHP Version:7.1
Laravel-admin: 1.6.12

### Description:
升级1.6.12版本后，添加menu菜单提交后当前页面刷新了一下，但无任何改变，也没有任何错误提示，也没有成功新增到菜单。我已填完所有可填的内容（包括权限），但仍没有效。
（已执行过php artisan view:clear）

查看控制台Network，发现是请求了
https://www.weiyuxinwen.com/admin/auth/menu
但返回的是当前页面的html代码。

请问这是什么问题？谢谢

### Steps To Reproduce:
如描述。

**Comment by xlkit456852** [comment]
然后又发现了在此版本下，在$form->saving中返回错误信息，虽然返回了编辑页面，但没有正常显示错误信息。

**Comment by z-song** [comment]
重现不了你的问题

**Comment by owen4comes** [comment]
找到问题了，是因为admin_menu表缺少了permission字段，我手动加上去就OK了。

**Comment by BourneSuper** [comment]
demo项目的问题
https://github.com/z-song/demo.laravel-admin.org/blob/e817644a014ef6d8206d8911cd09d69e0631dd1f/database/migrations/2016_01_04_173148_create_admin_tables.php#L43-L52
