### ISSUE TITLE
form表单编辑，图片required状态，已存在图片，但不能修改提交，始终提示“请选择一个文件”

### ISSUE THREAD

**Issue by lbsfei** [z-song/laravel-admin#3262]
- Laravel Version: 5.5.*
- PHP Version: 7.2.15
- Laravel-admin: ^1.6

### Description:
操作表单提交：单图片上传
1.表单编辑，图片已存在，想编辑其他数据；
2.提交表单时，总是提示“请选择一个文件”，明明我是有图片的，且我也不需要再更换图片

### Steps To Reproduce:
如何解决此问题？

**Comment by lbsfei** [comment]
![bug1](https://user-images.githubusercontent.com/12455682/56859983-1c406700-69c4-11e9-899c-75210a720822.png)

**Comment by z-song** [comment]
这个问题已经修复过了  更新到dev-master版本，或者等下一个版本发布
