### ISSUE TITLE
addElementClass对隐藏域无效

### ISSUE THREAD

**Issue by huangkaiwang** [z-song/laravel-admin#3263]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6.12

### Description:
排查一对多关联表单无法移除的问题的时候查看源码发现
对hidden input使用addElementClass没有效果，使fom-removed类没有加上，导致移除按钮没有使fom-removed(隐藏域)的值变为1，移除功能失效

**Comment by huangkaiwang** [comment]
暂时我只能重写HasMany组件修复这个问题
`namespace App\Admin\Extensions\Form;


use Encore\Admin\Admin;
use Encore\Admin\Form\Field\HasMany;
use Encore\Admin\Form\NestedForm;

class HasManyExtend extends HasMany
{
    protected function setupScriptForDefaultView($templateScript){
        //$removeClass = NestedForm::REMOVE_FLAG_CLASS;
        $defaultKey = NestedForm::DEFAULT_KEY_NAME;
        $flagName = NestedForm::REMOVE_FLAG_NAME;

        /**
         * When add a new sub form, replace all element key in new sub form.
         *
         * @example comments[new___key__][title]  => comments[new_{index}][title]
         *
         * {count} is increment number of current sub form count.
         */
        $script = <<<EOT
var index = 0;
$('#has-many-{$this->column}').on('click', '.add', function () {

    var tpl = $('template.{$this->column}-tpl');

    index++;

    var template = tpl.html().replace(/{$defaultKey}/g, index);
    $('.has-many-{$this->column}-forms').append(template);
    {$templateScript}
});

$('#has-many-{$this->column}').on('click', '.remove', function () {
    $(this).closest('.has-many-{$this->column}-form').hide();
    $(this).closest('.has-many-{$this->column}-form').find('[type=hidden]').each(function(){
        if($(this).attr('name').indexOf('{$flagName}') !== -1){
            $(this).val(1);
        }
    });
});

EOT;

        Admin::script($script);
    }
}`
在bootstrap里
`Form::extend('hasManyExtend', HasManyExtend::class);`

**Comment by z-song** [comment]
这个问题已经修复了 等下个版本发布

**Comment by jason-hu-dl** [comment]
> 这个问题已经修复了 等下个版本发布

1.7版本中未修复这个问题

**Comment by pangjincai** [comment]
> 这个问题已经修复了 等下个版本发布

请问大牛，在哪个版本修复了呢？目前的一对多数据 （多图上传）删除还是不管用
