### ISSUE TITLE
Dependent multiselect

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3265]
- Laravel Version: 5.8.14
- PHP Version: 7.3.3
- Laravel-admin: 1.6.12

I had problem in generating dependent multiselect. Who I can populated  second multiselect will be based on first multiselect value?

Thanks you

**Comment by Romerski** [comment]
https://github.com/z-song/laravel-admin/issues/663

**Comment by mendizalea** [comment]
Thanks you Romerski,

I just saw the example but I just can not understand.

I have these tables:
```
nations (id, name)
championships (id, name, nation_id)
categories (id, name, championship_id)
groups (id, name, nation_id)
divisions (id, name, nation_id)
events (id, name, date)
event_nations (event_id, nation_id)
event_championships (event_id, championship_id)
participants (id, name, event_id, group_id, division_id)
participant_categories (participant_id, category_id)
```

What I need is the following:

First, when registering a new participant, when selecting an event the select of group_id and division_id show the groups and divisions related to the nations that have the selected event.

And on the other hand, in the same form show a multiselect that only shows the categories of the championships to which the event belongs.

**Comment by mendizalea** [comment]
Works correctly until I select a second nation, once selected a second nation only shows the championships of the first selection.

Route
`$router->get('api/championships', 'ApiController@championships');`

ApiController
```
public function championships(Request $request)
    {
        $nationId = $request->get('q');

        return Championship::where('nation_id', $nationId)->get(['id', DB::raw('name as text')]);
    }
```
Form
```
$form->multipleSelect('nations', __('Nations'))->options(
                Nation::all()->pluck('name', 'id'))
                ->load('championships', '/admin/api/championships')
                ->rules('required');
        $form->multipleSelect('championships');
```
