### ISSUE TITLE
grid 使用中文显示字段的时候 无法正常显示

### ISSUE THREAD

**Issue by phpSign110** [z-song/laravel-admin#3269]
- Laravel Version: 5.7
- PHP Version:7.2
- Laravel-admin: 1.6.11

### Description:
 $grid->name("用户名称"); 不能正常在页面显示
 $grid->name("name"); 这样才能显示 中文无法显示

**Comment by Tiny-Fire** [comment]
$grid->column('name', '用户名称');

**Comment by Tiny-Fire** [comment]
$grid->column('name', '用户名称');

**Comment by phpSign110** [comment]
关键是我admin.php 配置文件里面的title 也是这个问题 包含中文就无法显示

![image](https://user-images.githubusercontent.com/29399444/56937824-52e7c000-6b31-11e9-8d76-2aac51ddefc4.png)

**Comment by z-song** [comment]
@phpSign110 去google一下`Laravel 中文乱码`，尝试一下它们的解决方案
