### ISSUE TITLE
grid 添加字段的时候 无法通过中文描述

### ISSUE THREAD

**Issue by phpSign110** [z-song/laravel-admin#3271]
- Laravel Version: 5.7.2
- PHP Version:PHP/7.2.17-1+ubuntu18.04.1+deb.sury.org+3
- Laravel-admin: 1.6.11

### Description:
![image](https://user-images.githubusercontent.com/29399444/56938264-7dd31380-6b33-11e9-9fb9-b3863c6ed9bd.png)

**Comment by z-song** [comment]
去google一下`Laravel 中文乱码`，尝试一下它们的解决方案
