### ISSUE TITLE
1.6.12版本 form一对多hasMany中无法移除数据

### ISSUE THREAD

**Issue by owen4comes** [z-song/laravel-admin#3273]
- Laravel Version: 5.5.*
- PHP Version:7.1
- Laravel-admin: 1.6.12

### Description:
升级1.6.12后，表单模型中tab中的使用了一对多hasMany的地方全部无法移除数据。新增、修改都可以，但点击移除并保存后，数据还是没有被删除，还在。升级1.6.12之前是正常的，请问应该如何处理？相关代码：
```
 protected function form()
    {

        return Admin::form(WynProduct::class, function (Form $entry_form) {

            $entry_form->tab('基本信息',function($form){
                //$form->display('id', 'ID');
                $form->text('name', '产品标题')->rules('required');
                $form->text('tags', '产品标签');
                $form->image('image', '产品封面图')->uniqueName()->removable();
            });

            $entry_form->tab('产品图集',function($form){
                $form->hasMany('albums','',function(Form\NestedForm $form)  {
                    $form->text('title', '标题');
                    $form->image('image', ' 图片')->uniqueName()->removable();
                    $form->number('sort_order','排序')->default(100);
                    return $form;
                });
            });
        });
    }
```

**Comment by chinkiver** [comment]
同样问题

**Comment by huangkaiwang** [comment]
这个问题在现在这个版本里面是存在的，我提过这个issue：https://github.com/z-song/laravel-admin/issues/3263，我目前修复的方式是把HasMany.php里面的内容拷贝出来重写
![image](https://user-images.githubusercontent.com/13937883/57172768-12e94b80-6e57-11e9-9dd4-c6b0bf2ab462.png)

**Comment by xlkit456852** [comment]
等老大发新版本~~

**Comment by z-song** [comment]
@owen4comes @chinkiver @huangkaiwang @xlkit456852 已经发布了`v1.6.13`

**Comment by jason-hu-dl** [comment]
这个问题 1.7版本都没有解决

**Comment by jason-hu-dl** [comment]
> 这个问题在现在这个版本里面是存在的，我提过这个issue：[https://github.com/z-song/laravel-admin/issues/3263，我目前修复的方式是把HasMany.php里面的内容拷贝出来重写](https://github.com/z-song/laravel-admin/issues/3263%EF%BC%8C%E6%88%91%E7%9B%AE%E5%89%8D%E4%BF%AE%E5%A4%8D%E7%9A%84%E6%96%B9%E5%BC%8F%E6%98%AF%E6%8A%8AHasMany.php%E9%87%8C%E9%9D%A2%E7%9A%84%E5%86%85%E5%AE%B9%E6%8B%B7%E8%B4%9D%E5%87%BA%E6%9D%A5%E9%87%8D%E5%86%99)
> ![image](https://user-images.githubusercontent.com/13937883/57172768-12e94b80-6e57-11e9-9dd4-c6b0bf2ab462.png)

按照您的这个方式 ， 数据库中的数据还是没有被删除啊
