### ISSUE TITLE
Multiple authentication in single Laravel admin codebase

### ISSUE THREAD

**Issue by KulwinderKohli** [z-song/laravel-admin#3276]
- Laravel Version: 5.8.*
- PHP Version: 7.1
- Laravel-admin: 1.6

How can I make multiple authentication in single Laravel admin codebase? I want these three auth
- Admin
- Customers
- Vendors

**Comment by z-song** [comment]
@KulwinderKohli Do you mean multi-tenant admin panel,  There is a multi-tenant extension [here](https://laravel-admin.org/extensions/14), but it is a commercial extension and you need pay for it.

**Comment by KulwinderKohli** [comment]
I wrote an email to you regarding this.

Thanks!

**Comment by z-song** [comment]
I have sent you the installation package, please check it.

**Comment by RikuHirose** [comment]
Hi, I also want to make multi auth in laravel-admin.
Could you tell me how to get a extension?
