### ISSUE TITLE
Delete row problems

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3280]
Laravel Version: 5.8.14
PHP Version: 7.3.3
Laravel-admin: 1.6.12

### Description:
I have a user who does not have permission to delete records.

But when the user tries to delete a record after accepting the confirmation message, it remains locked with the clock and until it does not press F5 it does not show the permission denied message.

**Comment by z-song** [comment]
Upgrade to v1.6.13 to use a deleting callback to check permission and modify the confirmation message.

https://laravel-admin.org/docs/#/en/model-form-callback?id=deleting-amp-deleted

**Comment by galexth** [comment]
same problem, i'm using route permissions and i cant use callbacks in my case. The code simply aborts in Permission middleware
