### ISSUE TITLE
为什么保存有回调，删除没有回调呢？

### ISSUE THREAD

**Issue by angusty** [z-song/laravel-admin#3282]
- Laravel Version: 5.8.15
- PHP Version: 7.2.6
- Laravel-admin: 1.6.12

### Description:
模型表单回调 添加和修改的回调都有 比如支持下面这种写法
// 在表单提交前调用
$form->submitted(function (Form $form) {
    //...
});
但为什么删除的回调没有呢，可否支持删除回调呢？

**Comment by z-song** [comment]
https://laravel-admin.org/docs/zh/model-form-callback#%E5%88%A0%E9%99%A4%E5%89%8D%E5%90%8E
