### ISSUE TITLE
菜单搜索有bug

### ISSUE THREAD

**Issue by mobileliker** [z-song/laravel-admin#3283]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: 1.6.13

### Description:
升级新版本以后的菜单搜索功能有bug，没有做权限控制。
截图该用户为普通用户（自定义的role），而menu等权限设置只有管理员用户能看到（下图也没有显示出来），但是搜索的时候展示出来，没有根据用户可以查看的菜单做显示
[截图](https://i.loli.net/2019/05/05/5cce9c18efe58.jpg)

**Comment by z-song** [comment]
确实有这个问题

**Comment by ichynul** [comment]
感觉这个功能作用不大，后台的使用人群都是有针对性的，不可能连某个菜单在什么地方都找不到。
他输入某个关键字去搜，说明知道有某个菜单，既然他知道有这个菜单，说明它熟悉。

**Comment by never615** [comment]
@ichynul  那你还是菜单少....
