### ISSUE TITLE
totalRow()方法bug

### ISSUE THREAD

**Issue by never615** [z-song/laravel-admin#3285]
- Laravel Version: #.#.#
5.6
- PHP Version:
7.2
- Laravel-admin: #.#.#
1.6.3
### Description:
某些使用场景下无效

### Steps To Reproduce:
直接调用->totalRow(),不填写参数.
可以看到源码这行:https://github.com/z-song/laravel-admin/blob/master/src/Grid/Tools/TotalRow.php#L67.

不填写参数的话,$this->columns数组的value都是null.后面的$this->total()方法就不会调用.

**Comment by z-song** [comment]
@never615 确实有这个问题，已经提交了修复，谢谢！
