### ISSUE TITLE
$form->table()方法，多对多的时候，数据能正常添加，但是显示的时候不能有效的显示出来！

### ISSUE THREAD

**Issue by licxuas** [z-song/laravel-admin#3289]
$form->table()方法，多对多的时候，数据能正常添加，但是显示的时候不能有效的显示出来！

**Comment by licxuas** [comment]
$form->table('specs', '商品规格', function ($table) {
                $spec_lists = Spec::where('status', 1)->pluck('name', 'id');
                $table->select('spec_id', '名称')->options($spec_lists)->rules('required');
                $table->currency('price', '价格')->symbol('￥')->rules('required');
                $table->number('stock', '库存')->default(9999)->rules('numeric');
                $table->image('thumb', '图片');
            });

**Comment by ccforeve** [comment]
一样，修改的时候页面不显示

**Comment by z-song** [comment]
建议用hasMany，不要用table

**Comment by licxuas** [comment]
> 建议用hasMany，不要用table

谢谢啊。 但是 hasMany是一对多的情况，多对多的时候会报错。
  hasMany field must be a HasMany or MorphMany relation.
另外 table这个处理多对多挺好的， 只是在修改数据的时候把数据显示出来就完美了。 数据条数都显示了，就是没有数据
