### ISSUE TITLE
Fill user id before save form

### ISSUE THREAD

**Issue by louis-l** [z-song/laravel-admin#329]
Hi

I have a model that has relationship with user model so I need to add the user_id before saving the form. Here is my code in `protected funtion form()`:

````
               $form->saving(function (Form $form) {
		        // $form->text('user_id')->value(Admin::user()->id);
		        $form->user_id = Admin::user()->id;
	        });
````

I tried `$form->user_id = Admin::user()->id;` and `$form->text('user_id')->value(Admin::user()->id);` but still did not work. The `user_id` is inserted as **NULL**

The model `$fillable` already set with these cols

When I add `$form->hidden('user_id')->value(Admin::user()->id);` that works fine.

Do I miss something?

Thanks

P/S: I make somes tests by adding:
````
$form->user_id = Admin::user()->id;
$form->testing_1 = Admin::user()->id;
$form->desc = 'isdji ajsd s ' . Admin::user()->id;
````

Only `desc` col get added the user id but not the other 2.

**Comment by z-song** [comment]
`mdoel-form` only saves column data which defined as a field in the form.

Try this:
```php
$form->hidden('user_id');
$form->saving(function (Form $form) {
    $form->user_id = Admin::user()->id;
});
```

**Comment by LuuHuy** [comment]
That works

Thanks

**Comment by lordjack** [comment]
> 
> 
> `mdoel-form` only saves column data which defined as a field in the form.
> 
> Try this:
> 
> ```
> $form->hidden('user_id');
> $form->saving(function (Form $form) {
>     $form->user_id = Admin::user()->id;
> });
> ```

Hello,

I tried to follow this example, but it did not work.
Error
![image](https://user-images.githubusercontent.com/6691621/54085313-b1f03c00-431b-11e9-94ab-2aae82d125d2.png)

![image](https://user-images.githubusercontent.com/6691621/54085349-f8de3180-431b-11e9-9841-2d05d5344e19.png)

![image](https://user-images.githubusercontent.com/6691621/54085339-e95ee880-431b-11e9-86c3-1ccbc7fa4c6d.png)

My Model
![image](https://user-images.githubusercontent.com/6691621/54085383-49558f00-431c-11e9-889d-95972ea15155.png)

Do you have any tips on what I should do?

**Comment by vonsogt** [comment]
> `mdoel-form` only saves column data which defined as a field in the form.
> 
> Try this:
> 
> ```
> $form->hidden('user_id');
> $form->saving(function (Form $form) {
>     $form->user_id = Admin::user()->id;
> });
> ```

That fixed my problem
