### ISSUE TITLE
修改$grid->actions()列的样式

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3290]
- Laravel Version: 5.5
- PHP Version:》7.0
- Laravel-admin: ~1.6.*

### Description:
![image](https://user-images.githubusercontent.com/40032190/57269037-7625e880-70b8-11e9-82bd-f01deb40261f.png)
上图的样式没有对齐，我想给列设置样式让他变宽，但是文档里只介绍了修改模型数据字段的样式，没有操作列样式修改的教程

**Comment by z-song** [comment]
先`$grid->disableActions();`, 然后再添加一个匿名字段放入你的操作组件，设置样式

**Comment by newbrash** [comment]
> 先`$grid->disableActions();`, 然后再添加一个匿名字段放入你的操作组件，设置样式

不太懂，禁掉原有组件之后在然后模仿原有重新写一个组件吗? 这样子我怎么知道他原来的组件写了啥呢？
我现在是使用jquery直接修改样式的

**Comment by llxcyzgh** [comment]
效果:
![image](https://user-images.githubusercontent.com/25409804/57983084-8490de80-7a80-11e9-8c4a-a59cb8f9dbae.png)
代码在此
![image](https://user-images.githubusercontent.com/25409804/57983096-a25e4380-7a80-11e9-8a4e-764de73b45d3.png)
