### ISSUE TITLE
form image  未设置 removeable，图片上仍然显示删除按钮

### ISSUE THREAD

**Issue by nosun** [z-song/laravel-admin#3293]
- Laravel Version: 5.7
- PHP Version: 7.2
- Laravel-admin: 1.6.14

### Description:
form 表单，image字段，未设置 removeable() 的情况下，已经上传的图片上仍然会显示删除按钮。

第二个相关的问题：对于已经成功保存的表单中的图片，编辑的时候，点击删除图片，即使这个图片的设置是 required(), 仍然能够跳过前端的检查，进行保存，因为点击了删除，所以实际上保存之后的表单中，图片字段是空，保存的时候跳过了检查。

**Comment by nosun** [comment]
第三个相关的问题是，对于设置了requeired 图片字段，未上传图片，错误消息的提示位置定位有问题。

![23C99F6D-1C11-4f87-AF1B-D5E926217329](https://user-images.githubusercontent.com/2755419/57271054-85a92f80-70c0-11e9-89e6-96551bbcd74e.png)

**Comment by nosun** [comment]
稍后我再多测试一下

**Comment by nosun** [comment]
code
```
        $form->image('thumb', '活动横幅')->setWidth(5)->uniqueName()->required();
```
![image](https://user-images.githubusercontent.com/2755419/57499766-6e15b500-7313-11e9-8ecd-4fcb266b026f.png)

打印出来的配置也是正确的：

array:10 [▼
  "overwriteInitial" => false
  "initialPreviewAsData" => true
  "browseLabel" => "浏览"
  "cancelLabel" => "取消"
  "showRemove" => false
  "showUpload" => false
  "dropZoneEnabled" => false
  "fileActionSettings" => array:2 [▼
    "showRemove" => false
    "showDrag" => false
  ]
]

或许是前端插件的问题。

**Comment by z-song** [comment]
运行`php artisan vendor:publish --tag=laravel-admin-assets --force`,  再清空浏览器缓存
