### ISSUE TITLE
压缩未包含皮肤style

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3294]
压缩后不能换皮肤

**Comment by ichynul** [comment]
也不灵活，换皮肤就得重新压缩，如果要让每个管理可以自定义他的皮肤就不好弄。
最好是把所有皮肤都压缩进去，和配置`admin.skin`无关。

**Comment by z-song** [comment]
我认为换皮肤是个低频操作，没必要设计成这么灵活

**Comment by ichynul** [comment]
#3284
绕来绕去还是一个问题，要允许动态css、js资源的引入，那动态换肤也不是问题。
我在另外一个里面的方法也许可以
