### ISSUE TITLE
Dynamic fields for hasMany with embeds

### ISSUE THREAD

**Issue by zeroiszero** [z-song/laravel-admin#3296]
Is there a way to implement hasMany relationship which contain embeds fields. And, dynamic fields for embeds based on a key/column in hasMany relationship.

Idea is similar to [this](https://github.com/pvtl/voyager-page-blocks)

```
$form->hasMany('paintings', function (Form\NestedForm $form) {
    // paintings has a field to store json
    $form->embeds('extra', function ($form) {
        // these fields can be dynamic
        // eg:
        //  id=1, we have fields: extra1 and extra2 
        //  id=2 we have fields: extra1 , extra2 and extra3 
        //  .....
        $form->text('extra1')->rules('required');
        $form->email('extra2')->rules('required');
        $form->mobile('extra3');
        $form->datetime('extra4');
        $form->dateRange('extra5', 'extra6', 'Date range')->rules('required');

    });
});
```

**Comment by z-song** [comment]
Do you mean this https://laravel-admin.org/docs/#/en/model-form-fields?id=hasmany ?

**Comment by zeroiszero** [comment]
updated the first comment with an example

**Comment by yurik94** [comment]
> updated the first comment with an example

How did you resolve? I have a custom multipleSelect in a nestedform and i can't access index nor model :(
