### ISSUE TITLE
菜单搜索 能關掉嗎?

### ISSUE THREAD

**Issue by extralam** [z-song/laravel-admin#3297]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
菜单搜索 能關掉嗎?

**Comment by z-song** [comment]
不能

**Comment by z-song** [comment]
@extralam 增加了一个配置`enable_menu_search`来控制它

**Comment by extralam** [comment]
感動，感激

**Comment by mrmangyang** [comment]
@z-song 还是不可以关掉，我的1.6.13版本的 是不是不可以啊
