### ISSUE TITLE
多文件上传

### ISSUE THREAD

**Issue by xialamp** [z-song/laravel-admin#3299]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

**Comment by xialamp** [comment]
多文件上传的时候需要按住Ctrl 键这个问题有办法处理吗？

**Comment by z-song** [comment]
不明白你的意思

**Comment by xialamp** [comment]
多图上传的时候，选择一张图后，然后再选择，会替换原来选择的，如果按住Ctrl键选择多张可以选择

**Comment by Kuaile1234** [comment]
他的意思是选择多个图片怎么上传，帮忙解决吧

**Comment by z-song** [comment]
弹出选择框之后，一次选多张图就可以了
