### ISSUE TITLE
editable doesnt work in new version!

### ISSUE THREAD

**Issue by amirbagh75** [z-song/laravel-admin#3301]
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-admin: v1.6.13

### Description:
i cant use editable! it's rollback to previous state!

**Comment by amirbagh75** [comment]
>     * Laravel Version: 5.8
> 
>     * PHP Version: 7.3
> 
>     * Laravel-admin: v1.6.13
> 
> 
> ### Description:
> 
> i cant use editable! it's rollback to previous state!
> ### Steps To Reproduce:

**Comment by amirbagh75** [comment]
@z-song 
why ?

**Comment by z-song** [comment]
@amirbagh75 upgrade to v1.6.15
