### ISSUE TITLE
更新1.6.15之后富文本编辑框无法使用

### ISSUE THREAD

**Issue by Twilightsixteen** [z-song/laravel-admin#3306]
- Laravel Version: 5.5.#
- PHP Version:7.1.2
- Laravel-admin: 1.16.15

### Description:
更新之后富文本编辑框无法使用 无论是ueditor 还是 wang-editor
错误信息为找不到type[editor]
降级为1.6.10就没有这个问题

**Comment by z-song** [comment]
打开app/Admin/bootstrap.php， 改一下`Form::forget(['map']);`

**Comment by shenheishe** [comment]
我也有这个问题 还是显示老的编辑器

**Comment by 53756e4c69** [comment]
`Encore\Admin\Form::forget(['map']); `
bootstrap已经改成这样了，还是没法用editor
`Field type [editor] does not exist.`

**Comment by minosss** [comment]
查看 composer.lock 看具体下的是哪个版本的。
过了commit 4e37319 的，editor 和 map 已经从 Form 中移除，改用组件的方式了
`composer require laravel-admin-ext/ckeditor`
项目 -> https://github.com/laravel-admin-extensions/ckeditor
