### ISSUE TITLE
$form->image('images')->multiple();无法支持mongodb数组？

### ISSUE THREAD

**Issue by guilinli001** [z-song/laravel-admin#331]
现在我mongodb中这个字段存的是这样的，但是显示不了。
    "images" : [
        "1474097283865.jpg", 
        "1484875217774.jpg", 
        "1484875218694.jpg", 
        "1484875219584.jpg"
    ], 
显示一个图片是正常的，如：
"cover" : "1484874961969.jpg",

**Comment by z-song** [comment]
已经提交了修复

要在模型里面添加下面代码来修改存储逻辑：

```php
public static function boot()
{
    parent::boot();

    static::saving(function ($model) {
        if (is_string($model->screenshots)) {
            $model->screenshots = json_decode($model->screenshots, true);
        }
    });
}
```

**Comment by guilinli001** [comment]
多谢，群主，已经OK
