### ISSUE TITLE
Issue in CREATE form for table data field inside hasMany relation model

### ISSUE THREAD

**Issue by rwmediaworks** [z-song/laravel-admin#3310]
- Laravel Version: 5.8.15
- PHP Version: 7.2.8
- Laravel-admin: 1.6.13

### Description:

I am trying to create form for below relationship:

**Hotel**  (1)->(M) **Room**

Where **Room** having field **meals** which I want it in **table** data field.

------------------------------------------------------------------------------------

Below is the screen shot of create form:

![image](https://user-images.githubusercontent.com/49428866/57372342-fdf01d80-71b2-11e9-9eeb-f894a2b1cc59.png)

Button in **Red** box is for adding new meals & button in **Blue** is for adding new room.

But when I click button in **Red** box it adds Room & not Meals.

What could be the issue? How should I fix this?

### Steps To Reproduce:

Create Hotel model (table -> id,name).
Create Room model (table -> id, hotel_id, name, meals).
Relationship between them is:
1(Hotel) -> M(Rooms)

Hotel Model (App\Admin\Hotel):

```
   public function rooms()
    {
        return $this->hasMany( Room::class, 'hotel_id' );
    }
```

Room Model (App\Admin\Room):

```
    public function hotel()
    {
    	return $this->belongsTo(Hotel::class,'hotel_id');
    }

    public function getMealsAttribute($meals)
    {
        return array_values(json_decode($meals, true) ?: []);
    }

    public function setMealsAttribute($meals)
    {
        $this->attributes['meals'] = json_encode(array_values($meals));
    }
```

Create Admin controller for Hotel. **\App\Admin\Controllers\HotelsController**

Now in **form** method should be look like:

```
    protected function form()
    {
        $form = new Form(new Hotel);

        $form->tab('Hotel info', function ($form) {

            $form->text('hotel_name', 'Hotel name')->rules('required|min:2');

        })->tab('Room Info', function ($form) {

            $form->hasMany('rooms', function (Form\NestedForm $form) {


                $form->table('meals', function ($table) {

                    $table->text('name');

                });

            });

        });


        return $form;
    }
```

Now go to admin section -> click to **add** Hotel -> see **Room Info** tab for above issue

**Comment by eine91** [comment]
Same issue with me...How can it be solved?

**Comment by Jlundmark12** [comment]
in your hotel controller, in the form method, are you sure you are suppose to use ->tab? Maybe it should be ->tap

**Comment by dominhnhien1997** [comment]
Dear @rwmediaworks
have you solved this error yet. Can you share your solution
Thanks
