### ISSUE TITLE
A null value in the request if used ckeditor field in v1.6.15

### ISSUE THREAD

**Issue by godkot** [z-song/laravel-admin#3311]
- Laravel Version: 1.5.6
- PHP Version:7.2.9
- Laravel-admin: 1.6.15

### Description:
A null value in the request if used ckeditor field in v1.6.15

### Steps To Reproduce:
I have the usual form with ckeditor fields. When I submitted this form, I have a null value in this field on request. All works in Laravel-admin: 1.6.12.

**Comment by linkimfly** [comment]
@godkot Open edit app/Admin/bootstrap.php， 
> modify 
```php
Form::forget(['map'， 'editor']);
```
> to 
```php
Form::forget(['map']);
```
