### ISSUE TITLE
layer.js压缩后样式路径有误

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3312]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: 1.6.15
### Steps To Reproduce:
layer.js 是根据 layer.js所在路径去加载layer.css的。
使用minify压缩js后，若某扩展依赖于layer.js，加载的css路径是错误的。
像这样：`http://localhost:802/vendor/laravel-admin/theme/default/layer.css?v=3.1.1`。
修复建议，压缩的时候判断是否有layer.js，有的话主动加上css：
```php
Admin::css(preg_replace('/^(.+)layer\.js.*$/i', '$1theme/default/layer.css', $layer_path));
```

**Comment by 77zealous** [comment]
ckeditor的相关js/css文件同样有此问题

**Comment by z-song** [comment]
@ichynul @77zealous 在config/admin.php中增加了一个配置来排除不需要被压缩的文件：
```php
    'minify_assets' => [

        // Assets will not be minified.
        'excepts' => [
            '/vendor/laravel-admin/theme/default/layer.css?v=3.1.1',
        ]

    ],
```
