### ISSUE TITLE
Use of routes and controllers

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3313]
- Laravel Version: 5.8.16
- PHP Version: 7.3.4
- Laravel-admin: 1.6.15

Now I have two controllers to manage this 2 tables:
```
events (id, name, date)
participants (id, number, name, event_id)
```
And the routes are the following:
```
'events'        => EventController::class,
'participants'   => ParticipantController::class,
```
The URLs would be the following:
```
https://example.com/admin/events
https://example.com/admin/events/{id}
https://example.com/admin/events/create
https://example.com/admin/events/{id}/edit

https://example.com/admin/participants
https://example.com/admin/participants/{id}
https://example.com/admin/participants/create
https://example.com/admin/participants/{id}/edit
```
But what I want is for the participants to be integrated into the URL of the event, like this one:
```
https://example.com/admin/events
https://example.com/admin/events/{id}
https://example.com/admin/events/create
https://example.com/admin/events/{id}/edit

https://example.com/admin/events/{id}/participants
https://example.com/admin/events/{id}/participants/{id}
https://example.com/admin/events/{id}/participants/create
https://example.com/admin/events/{id}/participants/{id}/edit
```

Now, in the events controller I have a function to show participants that shows only the participants of the event, but when click edit, show or new goes to /admin/participants URL:
```
// Show Participants grid for selected Event
		$show->participants(__('Participants'), function ($participants) {

			$participants->resource('/admin/participants');
			$participants->number(__('Number'));
			$participants->name()->name(__('Name'));
			$participants->admin_user()->name(__('Author'));
			$participants->updated_at(__('Updated at'));
			$participants->model()->orderBy('number', 'asc');
		});
```
I want the URL to be / events / {id} / participants because, on the one hand, I do not want to see all the participants of all the events and another for the permissions, so that they can only edit or add participants of their event.

How could I do it?

Thanks

**Comment by z-song** [comment]
You can get event id by using `request()->route()->parameters()`

**Comment by mendizalea** [comment]
Thanks you z-song, I tried with this and yours fine:

**Controller**
```
protected function grid()
{
	.........
	$event = request()->route()->parameters();
	if (!empty($event)) {$grid->model()->where('event_id', '=', $event);}
	..........
}
```
**Route**
`'events/{event}/participants'	=> ParticipantController::class,`

Now I have got second problems related with this change. This is my event controller details code where I had a grid with the event participant:

```
// Show Participants grid for selected Event
$show->participants(__('Participants'), function ($participants) {

	$participants->resource('/admin/participants');
	$participants->number(__('Number'));
	$participants->name()->name(__('Name'));
	$participants->admin_user()->name(__('Author'));
	$participants->updated_at(__('Updated at'));
	$participants->model()->orderBy('number', 'asc');
});
```
Now, how can I load the resource so that it points to the correct address?

If I access the controller by a different route, for example /admin/manager/events/{id}, how I do to not show the participant grid?

Thanks
