### ISSUE TITLE
Sort in grid

### ISSUE THREAD

**Issue by axsweet** [z-song/laravel-admin#3314]
- Laravel Version: 5.6.39
- PHP Version: 7.2.18
- Laravel-admin: 1.6.15

### Description: Grid sort does not work on numbers of different lengths 
  $grid->price('Sell Price')->sortable()->display(function () {
                return '$' . number_format($this->price,2);
            });

### Steps To Reproduce:

create model grid with wide ranging number length and format

look at grid and sort

<img width="122" alt="Screen Shot 2019-05-08 at 1 03 12 PM" src="https://user-images.githubusercontent.com/46913828/57393729-b5743800-7191-11e9-8ddd-e2a600b7aeaf.png">
<img width="114" alt="Screen Shot 2019-05-08 at 1 03 24 PM" src="https://user-images.githubusercontent.com/46913828/57393730-b5743800-7191-11e9-95da-c11ef692481d.png">
<img width="110" alt="Screen Shot 2019-05-08 at 1 03 31 PM" src="https://user-images.githubusercontent.com/46913828/57393732-b5743800-7191-11e9-966d-fc7d0549e8e5.png">

**Comment by z-song** [comment]
What's the data type of price column in your database? Try to modify to float type

**Comment by axsweet** [comment]
Z-SONG IS A BEAST.
