### ISSUE TITLE
ajax select with concat

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3315]
I have problems get the options for select with ajax:

"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'where clause' (SQL: select count(*) as aggregate from `drivers` where `full_name` like %% ▶"

```
public function drivers(Request $request)
    {
        $q = $request->get('q');

        return Driver::select("id", "first_name", "last_name"
                ,DB::raw("CONCAT(first_name,' ',last_name) as full_name"))
            ->where('full_name', 'like', "%$q%")->paginate(null, ['id', 'full_name as text']);
    }
```

**Comment by z-song** [comment]
The `ajax` method of Select provides two parameters to specify the name of the id and text field
```php
$form->select('column_name')->ajax('your/api', 'id', 'full_name');
```

Change the code of API to:

```php
    public function drivers(Request $request)
    {
        $q = $request->get('q');

        return Driver::select("id", "first_name", "last_name"
                ,DB::raw("CONCAT(first_name,' ',last_name) as full_name"))
            ->where('full_name', 'like', "%$q%")->paginate();
    }
```

**Comment by mendizalea** [comment]
Thanks you z-song but same problem with the API:

`"SQLSTATE[42S22]: Column not found: 1054 Unknown column 'full_name' in 'where clause' (SQL: select count(*) as aggregate from `drivers` where `full_name` like %% ▶"`

**Comment by mendizalea** [comment]
With what you told me about ajax and in the query using haviny and simplepaginate it work.
```
public function drivers(Request $request)
{
    $q = $request->get('q');

    return Driver::select("id", "first_name", "last_name",
           DB::raw("CONCAT(first_name,' ',last_name) as full_name"))
           ->having('full_name', 'like', "%$q%")->simplePaginate();
}
```
