### ISSUE TITLE
关于grid、form、detail中关联表数据问题

### ISSUE THREAD

**Issue by lauwen** [z-song/laravel-admin#3316]
- Laravel Version: 5.7
- PHP Version:7.1.3
- Laravel-admin: 1.6

### Description:
在grid、form、detail中使用获取关联表数据方法时，如果数据不存在会直接报错
`Trying to get property 'markrting_system' of non-object (View: D:\bd\treasure_box\vendor\encore\laravel-admin\resources\views\form.blade.php)`
所以建议在获取关联表数据时能对不存在数据进行返回空值处理，因为关联表数据是后期才会添加进来的

![image](https://user-images.githubusercontent.com/24284307/57420416-11929700-723a-11e9-9de0-84f1f16fa067.png)

### Steps To Reproduce:
grid、form、detail中获取不存在的关联表数据都会出现

**Comment by z-song** [comment]
可以自己做判断，或者使用Laravel的方法来处理这种情况
```php
return optional($this->crm)->group;
```

**Comment by lauwen** [comment]
已自行处理 不过你建议的方法更加好一点 赞
