### ISSUE TITLE
$filter->between 定义其他类型的范围筛选

### ISSUE THREAD

**Issue by siuu** [z-song/laravel-admin#332]
要筛选的字段类型是decimal
`$filter->between('balance', '账户余额'); `

但是会变成这样

![image](https://cloud.githubusercontent.com/assets/17903971/22181710/607d11b2-e0cc-11e6-8f1d-2808ed35f6be.png)

![image](https://cloud.githubusercontent.com/assets/17903971/22181711/665d2f36-e0cc-11e6-8a46-55e804a89ad0.png)

请问这个问题如何解决

**Comment by z-song** [comment]
在modal模式下样式有些问题，待我修复

**Comment by z-song** [comment]
已修复  更新1.3.x-dev
