### ISSUE TITLE
Overriding class file

### ISSUE THREAD

**Issue by rwmediaworks** [z-song/laravel-admin#3320]
- Laravel Version: 5.8.15
- PHP Version: 7.2.8
- Laravel-admin: 1.6.13

### Description:

Can I override below class file?

**Encore\Admin\Form\Field\HasMany**

To something like:

**App\Admin\Form\Field\HasMany**

I want to make some changes in below method:

**setupScriptForTableView()**

**Comment by ichynul** [comment]
Maybe can do like this:
`Form::extend('hasMany',App\Admin\Form\Field\HasMany::class)`

**Comment by rwmediaworks** [comment]
@ichynul Thanks. It works.
