### ISSUE TITLE
Time with milliseconds

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3328]
Is it possible to change the format of a time field? I have it stored in the database as time (3)

I need it to be introduced only in the following format:

```
HH:mm:ss:SSS
Example: 17:15:59.111
```

Thanks

**Comment by NickCoolii** [comment]
@mendizalea you can try something like this:
https://github.com/z-song/laravel-admin/issues/1727#issuecomment-366563597

By you need just accessor (maybe) and set field format:
https://laravel-admin.org/docs/#/en/model-form-fields?id=time-input
plus http://momentjs.com/docs/#/displaying/format/

**Comment by mendizalea** [comment]
I may have explained wrongly. What I need is that the datetimepicker if it is possible that it comes with the options of the milliseconds, and no only default hour-minute-seconds.
