### ISSUE TITLE
[HELP] butch actions and row render event

### ISSUE THREAD

**Issue by serzhiio** [z-song/laravel-admin#333]
Hi, thanks for so good project.
Now I can't understand how to add some new butch actions (ex. 'check all rows') and how to fire some scripts after the row was rendered. Please help.

**Comment by z-song** [comment]
Here has a example https://github.com/z-song/laravel-admin/blob/master/docs/en/grid-custom-tools.md#batch-operation

**Comment by serzhiio** [comment]
Thank you very much!
But guess this string doesn't work: 
`toastr.success('操作成功');`

Message doesn't appear.

**Comment by z-song** [comment]
Which version of laravel-admin do you use?

**Comment by serzhiio** [comment]
I'm sorry for stupid questions. It works!
