### ISSUE TITLE
重写控件

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3331]
- Laravel Version: 5.5
- PHP Version:》7.0
- Laravel-admin: 1.6.0

### Description:

如何重写前端监听事件
![image](https://user-images.githubusercontent.com/40032190/57605147-93ffbb80-7598-11e9-8413-646672056d93.png)
我想知道这些控件书写的源码位置，参考源码进行修改，保留源码的功能的同时，同时新增自己的功能

**Comment by newbrash** [comment]
![image](https://user-images.githubusercontent.com/40032190/57605801-0d4bde00-759a-11e9-8487-1f17dfce383f.png)
我看了switch控件，貌似就只有$states参数是可以更改的，其它的得重写源码

**Comment by ichynul** [comment]
可以在view里面覆盖
比如覆盖form 的 textarea
创建`resources/views/admin-override/form/textarea.blade.php`
`app/Admin/bootstrap.php`里面加上
`\View::prependNamespace('admin', __DIR__ . '/../../resources/views/admin-override'); //重新指定view`

**Comment by puzzle9** [comment]
> 可以在view里面覆盖
> 比如覆盖form 的 textarea
> 根目录创建`resources/views/admin-override/form/textarea.blade.php`
> `app/Admin/bootstrap.php`里面加上
> `\View::prependNamespace('admin', __DIR__ . '/../../resources/views/admin-override'); //重新指定view`

按照`优雅`的写法应该是

```
View::prependNamespace('admin', resource_path('views/laravel-override'));
```
