### ISSUE TITLE
select 連動填入

### ISSUE THREAD

**Issue by hrlbmrnr** [z-song/laravel-admin#3332]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
$form->select()->load()
$form->text()
$form->text()

請教各位先進,是否有人開發過,
creat 新的form
select 表單點選後,自動填入相關表單欄位資料,怎麼調整比較理想.

**Comment by linkimfly** [comment]
这种需求，只能是自己开发扩展了

**Comment by 382580322** [comment]
试试
[FieldInteraction](https://github.com/zuweie/FieldInteraction)
![FieldInteraction](http://cdn.qiniu.inetwon.com/field-Interaction.gif)
@hrlbmrnr

**Comment by hrlbmrnr** [comment]
谢谢回帖喔.
我自己現在是只能做出一亇textarea联动.
研究出再分享
