### ISSUE TITLE
添加自定义控件无效

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3333]
- Laravel Version: 5.5
- PHP Version:>7.0
- Laravel-admin: 1.6.*

### Description:
![image](https://user-images.githubusercontent.com/40032190/57609538-ab8f7200-75a1-11e9-917e-3e10aebb5b84.png)
![image](https://user-images.githubusercontent.com/40032190/57609552-b34f1680-75a1-11e9-8d87-8ab0e1775c61.png)
这是直接复制粘贴的switch控件，但是没起作用啊

**Comment by SuzutsukiKagami** [comment]
grid也要做设置的，贴代码

**Comment by newbrash** [comment]
> grid也要做设置的，贴代码

我设置错位置了，我上面设置到form的组件了，应该修改grid组件库的
