### ISSUE TITLE
HasManyThrough ? Or Three related tables

### ISSUE THREAD

**Issue by byemen** [z-song/laravel-admin#3337]
- Laravel Version: 5.8
- PHP Version: 7.1.3
- Laravel-admin: 1.6.15

### Description:
I have Three Models,

```php
class Branch extends Model
{
    protected $table = 'tbl_brc';
    protected $primaryKey = 'brc_idx';
    protected $fillable = [ 'brc_cd', 'brc_nm'  ];

    public function qna()
    {
        return $this->hasManyThrough(QnA::class, User::class, 'brc_cd', 'user_idx', 'brc_cd', 'brc_cd');
    }

    public function user(){
        return $this->hasMany(User::class, 'brc_cd');
    }
}

class User extends Model
{
    protected $table = 'tbl_user';
    protected $primaryKey = 'user_idx';
    protected $fillable = ['user_id', 'brc_cd', 'user_name'];
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function qna()
    {
        return $this->hasMany(QnA::class);
    }

    public function branch()
    {
        return $this->belongsTo(Branch::class, 'brc_cd');
    }

}

class QnA extends Model
{
    protected $table = 'tbl_qna';
    protected $primaryKey = 'qna_idx';
    protected $fillable = [
        'user_idx', 'question', 'answer', 'status', 'user_read', 'admin_read', 'asn_dt', 'ans_admin_id', 'del_admin_id'
    ];

    public function user()
    {
        return $this->belongsTo(User::class, 'user_idx');
    }
}

```

And, QnA Controller Grid

```php

    protected function grid()
    {


        $grid = new Grid(new QnA);

        $grid->user()->branch()->display(function ($branch) {
            return $branch;
        });
        $grid->column('user.user_id','User');
        $grid->question('question')->limit(20);
        $grid->answer('answer')->limit(20);;
        return $grid;
    }
```
How can I show Branch.brc_nm column on the QnA Grid??
From Above code, shows nothing..

**Comment by z-song** [comment]
Try this
```php
$grid->model()->with('user.branch');

$grid->column('brc_nm')->display(function ($branch) {
    return $this->user->branch->brc_nm;
});
```

**Comment by byemen** [comment]
Hi @z-song, I got an error 

×
 ErrorException In QnAController.php line 90 :

  Trying to get property of non-object

#0 /Users/byemen/DevSource/AK-Soft/laravel-admin/app/Admin/Controllers/QnAController.php(90): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Trying to get p...', '/Users/byemen/D...', 90, Array)
#1 [internal function]: App\Admin\Controllers\QnAController->App\Admin\Controllers\{closure}(NULL, Object(Encore\Admin\Grid\Column))
#2 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Grid/Column.php(432): call_user_func_array(Object(Closure), Array)
#3 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Grid/Column.php(481): Encore\Admin\Grid\Column->callDisplayCallbacks(NULL, 0)
#4 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Grid.php(585): Encore\Admin\Grid\Column->fill(Array)
#5 [internal function]: Encore\Admin\Grid->Encore\Admin\{closure}(Object(Encore\Admin\Grid\Column), 1)
#6 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Support/Collection.php(1120): array_map(Object(Closure), Array, Array)
#7 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Grid.php(588): Illuminate\Support\Collection->map(Object(Closure))
#8 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Grid.php(1012): Encore\Admin\Grid->build()
#9 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Layout/Column.php(100): Encore\Admin\Grid->render()
#10 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Layout/Row.php(80): Encore\Admin\Layout\Column->build()
#11 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Layout/Content.php(178): Encore\Admin\Layout\Row->build()
#12 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Layout/Content.php(259): Encore\Admin\Layout\Content->build()
#13 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Http/Response.php(42): Encore\Admin\Layout\Content->render()
#14 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/symfony/http-foundation/Response.php(202): Illuminate\Http\Response->setContent(Object(Encore\Admin\Layout\Content))
#15 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Symfony\Component\HttpFoundation\Response->__construct(Object(Encore\Admin\Layout\Content))
#16 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(720): Illuminate\Routing\Router::toResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#17 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\Routing\Router->prepareResponse(Object(Illuminate\Http\Request), Object(Encore\Admin\Layout\Content))
#18 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Routing\Router->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#19 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Middleware/Permission.php(42): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#20 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Encore\Admin\Middleware\Permission->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#22 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Middleware/Bootstrap.php(15): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#23 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Encore\Admin\Middleware\Bootstrap->handle(Object(Illuminate\Http\Request), Object(Closure))
#24 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#25 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Middleware/LogOperation.php(38): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#26 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Encore\Admin\Middleware\LogOperation->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Middleware/Pjax.php(24): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#29 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Encore\Admin\Middleware\Pjax->handle(Object(Illuminate\Http\Request), Object(Closure))
#30 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#31 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/encore/laravel-admin/src/Middleware/Authenticate.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#32 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Encore\Admin\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#33 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#34 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#35 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Routing\Middleware\SubstituteBindings->handle(Object(Illuminate\Http\Request), Object(Closure))
#36 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#37 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#38 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle(Object(Illuminate\Http\Request), Object(Closure))
#39 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#40 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#41 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#42 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#43 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#44 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#47 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#48 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#49 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#50 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#51 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#52 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#53 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#54 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#55 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\Routing\Router->runRoute(Object(Illuminate\Http\Request), Object(Illuminate\Routing\Route))
#56 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#57 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#58 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}(Object(Illuminate\Http\Request))
#59 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#60 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\Proxy\TrustProxies->handle(Object(Illuminate\Http\Request), Object(Closure))
#61 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#62 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#63 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#64 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#65 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#66 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\TransformsRequest->handle(Object(Illuminate\Http\Request), Object(Closure))
#67 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#68 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#69 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle(Object(Illuminate\Http\Request), Object(Closure))
#70 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#71 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#72 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#73 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#74 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\Routing\Pipeline->Illuminate\Routing\{closure}(Object(Illuminate\Http\Request))
#75 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#76 /Users/byemen/DevSource/AK-Soft/laravel-admin/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#77 /Users/byemen/DevSource/AK-Soft/laravel-admin/public/index.php(55): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#78 /Users/byemen/DevSource/AK-Soft/laravel-admin/server.php(21): require_once('/Users/byemen/D...')
#79 {main}

**Comment by z-song** [comment]
@byemen 
```php
$grid->column('brc_nm')->display(function ($branch) {
    if (!$this->user || !$this->user->branch) {
        return ''
    }

    return $this->user->branch->brc_nm;
});
```

**Comment by byemen** [comment]
@z-song 

hmm, now it displays nothing. returns '';
