### ISSUE TITLE
增加登录方式后，登录成功一直跳转到登录页

### ISSUE THREAD

**Issue by lauwen** [z-song/laravel-admin#3338]
- Laravel Version: 5.7
- PHP Version:7.0
- Laravel-admin: 1.6

### Description:
在保留原有账户密码的登录方式外，接入了一键单点登录，单点登陆成功后获取到用户ID,并通过ID认证用户的方式验证用户，也显示验证成功，但是没有进入到系统，一直跳转到登录页（原账户密码登录方式正常），图中用户信息正常输出
![image](https://user-images.githubusercontent.com/24284307/57742981-d7bc0780-76f5-11e9-908b-7949221f0952.png)

附：
![image](https://user-images.githubusercontent.com/24284307/57743234-cde6d400-76f6-11e9-8185-7d854d3d8aee.png)

**Comment by ichynul** [comment]
好像要传grud name
`Auth->grud('admin')->loginUseingId(1)`

**Comment by lauwen** [comment]
`Auth->guard('admin')->loginUsingId(1)` 也是一样  没起作用

**Comment by ichynul** [comment]
你的单点登录url有没有 配置到`admin.auth.excepts`里面，不然的逻辑代码还没运行就被拦截跳转登录页面了
```php
/**
     * Determine if the request has a URI that should pass through verification.
     *
     * @param \Illuminate\Http\Request $request
     *
     * @return bool
     */
    protected function shouldPassThrough($request)
    {
        $excepts = config('admin.auth.excepts', [
            'auth/login',
            'auth/logout',
        ]);

        return collect($excepts)
            ->map('admin_base_path')
            ->contains(function ($except) use ($request) {
                if ($except !== '/') {
                    $except = trim($except, '/');
                }

                return $request->is($except);
            });
    }
```

**Comment by lauwen** [comment]
逻辑代码已经执行了 就是最后跳转不到登陆后页面  不知道是否是缺少什么  
直接把单点登录逻辑写在getLogin登录页渲染方法里面却能成功登录  不过这样就只能单点登陆了

**Comment by z-song** [comment]
运行`php artisan route:list`看下这个单点登录的路由设置的中间件？

**Comment by lauwen** [comment]
没有设置中间件  我把它单独写出来了  
如果写进admin的路由分组里面，逻辑代码会运行不了
![image](https://user-images.githubusercontent.com/24284307/57754162-60e83400-7720-11e9-8b97-0f6274fe12f0.png)

**Comment by lauwen** [comment]
没有设置中间件，我把它写在admin路由分组外面了
直接写在admin路由分组里面会跳不了单点登陆逻辑（中间件限制登录了）
![image](https://user-images.githubusercontent.com/24284307/57755102-9aba3a00-7722-11e9-95b9-f17140068812.png)
![image](https://user-images.githubusercontent.com/24284307/57755248-fa184a00-7722-11e9-96b6-31326b071a65.png)

**Comment by z-song** [comment]
至少要加一个`web`中间件，不然这个路由不受session影响，也不会去处理session,  当然就没办法实现登陆了

**Comment by lauwen** [comment]
设置了web中间件，能单点登录但还是会跳回登录页面
![image](https://user-images.githubusercontent.com/24284307/57763625-58015d80-7734-11e9-8205-0570cc57cb90.png)

**Comment by lauwen** [comment]
感谢松哥im热情解答  也感谢@ichynul 的回复（你的解决思路是对的）期间因版本和文件问题出现误处理，现说明一下：
- Laravel-admin Version: 1.6.10
单点登录路由还是放到Admin默认的路由分组里面，不过要将该路由添加到忽略登录验证的路由组里面，如下图所说，可以看到下图是可以直接从配置文件读取相关路由的：
![image](https://user-images.githubusercontent.com/24284307/57819310-790c9180-77ba-11e9-98ca-8ba4ada3df88.png)

但是我的版本并不支持直接配置（具体可从源码或配置文件中查看，配置文件：`admin.auth.excepts`；源码位置：`encore\laravel-admin\src\Middleware\Authenticate.php`）
![image](https://user-images.githubusercontent.com/24284307/57819583-be7d8e80-77bb-11e9-9813-34b0e432db00.png)

所以解决方式是，分版本解决：
支持配置文件配置的，直接将路由配置到`admin.auth.excepts`中；不支持配置文件的可以尝试升级到新版本或者直接在`encore\laravel-admin\src\Middleware\Authenticate.php`（一定要是这个文件，不是Permission.php）的shouldPassThrough中添加
