### ISSUE TITLE
使用cosv5云盘存储多图图片的时候添加 ->removable()会删除云盘的文件，不添加又无法删除数据表对应字段内容

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#3340]
- Laravel Version: 5.5.1
- PHP Version:7.13
- Laravel-admin: 1.6.1

### Description:
使用cosv5云盘存储图片的时候添加 ->removable()会删除云盘的文件，不添加又无法删除数据表文件
$form->multipleImage('images', '图片')  ->removable();
### Steps To Reproduce:
这个该怎么解决，问题就是在多图上传的时候，想替换图片，但是添加removable()会删除云盘文件，不添加又无法替换图片

**Comment by YangZhengHuan** [comment]
我不想删除cosv5云盘文件，只是想替换多图中的文件，求解决

**Comment by YangZhengHuan** [comment]
@z-song

**Comment by YangZhengHuan** [comment]
看见底层源码调用了    public function prepare($image)
    {
        if (request()->has(static::FILE_DELETE_FLAG)) {
            //return $this->destroy();
            return '';
        }

        $this->name = $this->getStoreName($image);

        $this->callInterventionMethods($image->getRealPath());

        return $this->uploadAndDeleteOriginal($image);
    }
}
然后调用了    /**
     * Destroy original files.
     *
     * @return void.
     */
    public function destroy()
    {
        if ($this->storage->exists($this->original)) {
            $this->storage->delete($this->original);
        }
    }

**Comment by YangZhengHuan** [comment]
通过底层方法这样实现的：
$form->image('image','广告图片')->uniqueName()->removable()->setOriginal([]);
解决问题，不知道有没有更好的解决方案@z-song

**Comment by z-song** [comment]
待我加个方法来控制收要删除文件吧

**Comment by YangZhengHuan** [comment]
@z-song   那这样使用会有什么问题吗， $form->image('image','广告图片')->uniqueName()->removable()->setOriginal([]);

**Comment by YangZhengHuan** [comment]
@z-song 麻烦您了，谢谢

**Comment by z-song** [comment]
@YangZhengHuan 更新到dev-master版本
```php
$form->multipleImage('images', '图片') ->removable()->retainable();
```
