### ISSUE TITLE
Select input resets when the form encounters validation errors

### ISSUE THREAD

**Issue by siavashgolabi** [z-song/laravel-admin#3341]
- Laravel Version: 5.7.26
- PHP Version: 7.1.9
- Laravel-admin: 1.6.15

### Description:
I have some select input which loads option by ajax in my form, such as:
```
$form->select('university_id')->options(function ($id) {
                    $university = University::find($id);
                    if ($university) {
                        return [$university->id => $university->title];
                    }
                })->ajax('/admin/api/universities', 'id', 'title');
```
Select input resets when the form encounters validation errors.
I want to have the old value after validation fails.

**Comment by siavashgolabi** [comment]
Can anyone help me with that?!
all my ajax loaded select inputs resets when the form encounters validation errors.
@z-song ?!

**Comment by shacky** [comment]
It's an old issue, but I resolved it some kind of this way (pseudocode):
`
$form->select('university_id')->options(function ($id) {
                    if(!$id) $id = old('university_id');
                    $university = University::find($id);
                    if ($university) {
                        return [$university->id => $university->title];
                    }
                })->ajax('/admin/api/universities', 'id', 'title');
`
Why? On validation error it's redirected to previous URL with setting old input into session and error messages. Submitted values are handled by templates itself by using "old" helper function, so field itself doesn't keep value on error and it's not passed by $id argument.

**Comment by beniaminorossini** [comment]
@shacky super cool, thx!
