### ISSUE TITLE
How to load 2 select after parent is selected

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3343]
Hello,

I have 3 select in my form, one main and the other two depend on the first one:

```
$form->select('event_id', __('Event'))->options(
		Event::all()->pluck('name', 'id'))
		->load('participant_id', '/admin/api/participants')
		->load('stage_id', '/admin/api/stages')
		->rules('required')
		->value(request('event_id'));
		
$form->select('stage_id')
	->options(function ($id) {
		return Stage::options($id);
	})
	->rules('required')
	->value(request('stage_id'));
	
$form->select('participant_id')
	->options(function ($id) {
		return Participant::options($id);
	})
	->rules('required')
	->value(request('participant_id'));
```
	
But only the last one is loaded instead of loading both.
In the example load the stages, if I change the order of the load it is loaded only of participants, always load the last load.

**Comment by mRamadan0101** [comment]
$form->select('event_id', __('Event'))->options(
		Event::all()->pluck('name', 'id'))
		->loads(['participant_id','stage_id'],[ '/admin/api/participants','/admin/api/stages'],'id','title')
		->value(request('event_id'));

**Comment by mendizalea** [comment]
Thanks you @mRamadan0101
