### ISSUE TITLE
文件上传后，再编辑，文件显示异常

### ISSUE THREAD

**Issue by chinkiver** [z-song/laravel-admin#3347]
- Laravel Version: 5.5.45
- PHP Version: 7.2.5
- Laravel-admin: 1.6.15

### Description:
文件上传后，再此编辑表单，文件明显夸张

### Steps To Reproduce:
1、文件表单提价
2、修改该记录

<img width="906" alt="questions-001" src="https://user-images.githubusercontent.com/13643790/57791428-5a34dd80-776f-11e9-8860-a7eafc12437f.png">

**Comment by z-song** [comment]
贴代码？

**Comment by 382580322** [comment]
非图片格式的文件全都这样
关闭非图片类型的文件预览即可
$form->file('fileurl')->options(["showPreview"=>false]);

**Comment by chinkiver** [comment]
```
// 批准文件
            $form->file('transfer_premise4_stamp_file', trans('equity.transfer_premise4_stamp_file'))
                ->move(getPledgeFileSavePath())
                ->removable()
                ->rules('required|file')
                ->options(["showPreview" => FALSE]);
```
![image](https://user-images.githubusercontent.com/13643790/57829206-d0bdf380-77e0-11e9-954c-eda6c305655d.png)

完美解决，感谢

**Comment by faydanube** [comment]
> ```
> // 批准文件
> $form->file('transfer_premise4_stamp_file', trans('equity.transfer_premise4_stamp_file'))
>     ->move(getPledgeFileSavePath())
>     ->removable()
>     ->rules('required|file')
>     ->options(["showPreview" => FALSE]);
> ```
> 
> ![image](https://user-images.githubusercontent.com/13643790/57829206-d0bdf380-77e0-11e9-954c-eda6c305655d.png)
> 
> 完美解决，感谢

亲, 这样没了删除和下载按钮... 客户又明确需要这两个功能=.=
@z-song
