### ISSUE TITLE
prependIcon not working?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#335]
$grid->email()->prependIcon('envelope');

Error:

 BadMethodCallException In Macroable.php line 52 :

Method prependIcon does not exist.

**Comment by z-song** [comment]
`prependIcon()` is not a builtin method, it's a column extension.

See documentation here https://github.com/z-song/laravel-admin/blob/master/docs/en/model-grid-column.md#extend-the-column

And find code http://120.26.143.106/admin/demo/users  in `Column Extension` tab.
