### ISSUE TITLE
表单二级联动，当验证失败，返回没数据的问题

### ISSUE THREAD

**Issue by angusty** [z-song/laravel-admin#3350]
- Laravel Version: 5.8.17
- PHP Version:7.2.17
- Laravel-admin: 1.6.15

### Description:
遇到一个问题：
form表单添加数据的时候用到了二级联动，主select表单用的$form->select()->options()->loads()方式调用，因为涉及到2个子select表单的联动。表单有验证，当验证不通过的时候，其他数据的值都会保存下来显示在表单中，包括主select表单的数据也保存下来了，只有之前提到的那2个子select表单数据是空的，需要再次重新选择主select，那2个子select表单才会有数据。

**Comment by 382580322** [comment]
```
if(old('select1')){
    $form->select('select1')->options(...)->load(...)->default(old('select1'));
    if(old('select2')){
        $form->select('select2')->options(...)->load(...)->default(old('select2'));
    }
    if ...
}else{
    $form->select('select1')->options(...)->load(...);
    $form->select('select2')->options(...)->load(...);
    $form->select('select3')->options(...)->load(...);
}
```

**Comment by angusty** [comment]
我试了这个办法，好像也没有解决我的问题呢，大概是load方法只有change事件才会触发，我那个场景是第一次加载的时候主select是有值的，所以没有触发change事件，就没有ajax请求，不会有子类的select数据。


------------------



 




------------------ 原始邮件 ------------------
发件人: "382580322"<notifications@github.com>;
发送时间: 2019年5月16日(星期四) 中午1:51
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>;
抄送: "涛   瑞"<8236138@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [z-song/laravel-admin] 表单二级联动，当验证失败，返回没数据的问题 (#3350)



if(old('select1')){     $form->select('select1')->options(...)->load(...)->default(old('select1'));     if(old('select2')){         $form->select('select2')->options(...)->load(...)->default(old('select2'));     }     if ... }else{     $form->select('select1')->options(...)->load(...);     $form->select('select2')->options(...)->load(...);     $form->select('select3')->options(...)->load(...); }

**Comment by 382580322** [comment]
@angusty
$form->select('select1')->options(...)->loads(...)->default(old('select1'));
提交失败后这句代码会触发一系列的联动，重点是提交之前的old('select1')设置为默认值，然后联动设置select2 select3 select4的old('select1234')默认值

**Comment by 382580322** [comment]
我已经解决了呢 ，多试试代码就解决了哦。

**Comment by angusty** [comment]
这个问题是因为第一次加载的时候 主select已经被选中了，两个子select由于没有触发change事件，没有ajax请求，也不会有值，现在的解决方案是在控制器中给两个子select赋值。先判断临时session有没有主select的值，有的话查询两个字select的值，然后放在其option中，另一种场景是修改的时候，这个时候使用闭包的方式实现（因为我的create和edit在一个form）大体代码如下：
```
public function form($id) {
		...

    //主select
    $school_option = School::getOptions()
    $form->select('school_id', trans('admin_student.school_name'))
        ->loads(
            ['institution_id', 'specialty_id'],
            ['/admin/api/adult-education/institutions', '/admin/api/adult-education/specialties']
        )
        ->required()
        ->options($school_option)
        ->rules(function(Form $form) {
            return ['required'];
        });

    $institution_option = [];
    $speciaity_option = [];

    if (old('school_id')) {
    	//先查找一次性session (create或edit当验证失败均走此逻辑)
        $institution_option = Institution::getOptions(old('school_id'));
        $speciaity_option = Specialty::getOptions(old('school_id'));

    } else if ($id) {
    	//使用闭包 (edit第一次打开页面时走此逻辑)
        $institution_option = function() {
            return Institution::getOptions($this->school_id);
        };
        $speciaity_option = function() {
            return Specialty::getOptions($this->school_id);
        };
    }
    //子select1
    $form->select('institution_id', trans('admin_student.institution_name'))
        ->required()
        ->options($institution_option)；
     
    //子select2
    $form->select('specialty_id', trans('admin_student.specialty_name'))
        ->required()
        ->options($speciaity_option)；
        
    ...
}
		
```
select除了能使用load或loads方法触发change事件，能不能当第一次加载select已选中的时候能触发一个事件，比如类似于 $(document).ready的事件，以便能给子select赋初始options。

**Comment by smm229** [comment]
我也遇到了这个问题，多级联动提交表单报错之后，除了一级，其他的select都没有值了，有最终解决方案吗？ @z-song
