### ISSUE TITLE
laravel-admin grid value

### ISSUE THREAD

**Issue by xxxlo71** [z-song/laravel-admin#3352]
- Laravel Version: 5.8.16
- PHP Version: 7.2.10
- Laravel-admin: 1.6

### Description:
i want to use laravel grid add a link with product_id (not PK) to open new window with iframe-tabs
for search

### Steps To Reproduce:
$grid->sn(trans('admin.product_id'))->sortable();
$grid->com_num(trans('admin.com_num'))->sortable()->link( '/admin/com/search/'.$xxx,'','' );
$grid->agent_num(trans('admin.agent_num'))->sortable()->link( '/admin/agent/search/'.$xxx,'','' );

1.how can i get $xxx from $grid->sn
2.how can i set route to other page like /admin/com/search/123 for search not edit

**Comment by z-song** [comment]
1.
```php
$grid->com_num(trans('admin.com_num'))->sortable()->display(function ($com_num) {
    return "<a href='/admin/com/search/{$this->sn}'>{$com_num}</a>";
});
```

2.Don't quite understand your question.

**Comment by xxxlo71** [comment]
2.
$router->get('/com/search/{id}', 'comController@search');//商戶/搜尋

**Comment by z-song** [comment]
所以问题是什么？

**Comment by xxxlo71** [comment]
想要透過$grid 開啟新的頁面 但是要帶入 產品編號 一直出現失敗 現在總算解了

**Comment by xxxlo71** [comment]
追問一下 如果要開啟的方式是 iframe-tabs 開新頁 要怎麼改
