### ISSUE TITLE
批量操作多选框data-id值长度不足的情况

### ISSUE THREAD

**Issue by ygcool** [z-song/laravel-admin#3354]
- Laravel Version: 5.8
- PHP Version:7.1
- Laravel-admin: 1.6.15

### Description:
从第三方获取列表，自定义数据源。然后添加一个自定义批量操作去调用第三方接口。
现在第三方接口那边默认id是一个很长的字符（例：179277261462179840，都是这么长的），这时在laravel-admin的列表前面的多选框data-id值就都是：2147483647（全部都是这个值，猜测应该是源码内在渲染时，做了一个(int)$id的操作）。 请教该如何解决？或者多选框该如何自定义一个data-xx 值，多个选中后取data-xx的值传后端

**Comment by z-song** [comment]
模型里面加上
```php
protected $keyType = 'string';
```

**Comment by ygcool** [comment]
> 模型里面加上
> 
> ```
> protected $keyType = 'string';
> ```

感谢作者，用此方法就能解决！
