### ISSUE TITLE
Join table to order problems with ID

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3356]
Hello,

I have this code from order the results grid with second table field:

```
$grid->model()->join('participants', 'participants.id', '=', 'results.participant_id')
	->orderBy('results.event_id', 'desc')
	->orderBy('participants.number', 'asc');
```

The problem is that when I'm going to edit or view any line, the id that I am seeing / editing is not from the results table, it is from the participants table.

I have something wrong? Does it happen to someone else?

Thanks

**Comment by z-song** [comment]
It's because the results.id is overwriting by the participants.id in your case.

Can find a solution here https://github.com/laravel/framework/issues/4962

**Comment by mendizalea** [comment]
Thanks you z-song, solved with your help :)

**Comment by amun1303** [comment]
> Thanks you z-song, solved with your help :)

Please show me your solution. I have the same problem. Thanks so much.
