### ISSUE TITLE
在管理员字段中如何添加电话和邮箱字段？？？

### ISSUE THREAD

**Issue by LiveLys** [z-song/laravel-admin#3357]
在管理员字段中如何添加电话和邮箱字段？？？，现在只是单一的几个昵称，权限之后的，怎么扩展字段？

**Comment by z-song** [comment]
自行到admin_users表中加字段，

然后到app/Admin/routes.php中覆盖掉系统的laravel-admin的相关路由

参考vendor/encore/laravel-admin/src/Controllers/UserController.php

**Comment by LiveLys** [comment]
感谢
