### ISSUE TITLE
更新到 v1.6.13 版本后 左侧菜单栏默认全部展开，如何默认折叠？

### ISSUE THREAD

**Issue by zesai** [z-song/laravel-admin#3358]
- Laravel Version: 5.5
- PHP Version:7.1.13
- Laravel-admin: 1.6.13

### Description:
更新 `laravel-admin`版本后，左侧菜单栏默认全部展开了，如何设置为默认折叠？

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/39072304/57900458-7893f980-7893-11e9-8008-57a9ac6b13f8.png)

**Comment by z-song** [comment]
重现不了你的问题，更新到最新的v1.6.15试试

**Comment by wojianishanghaojiugoujia** [comment]
![image](https://user-images.githubusercontent.com/17558843/59201012-12697080-8bcc-11e9-8bc3-993ded53ac2d.png)

config/admin.php 里面的 layout， 如果想要默认折叠就加上 sidebar-collapse 否则就去掉 sidebar-collapse
