### ISSUE TITLE
$form->hasMany 中的 $form->table 按钮冲突

### ISSUE THREAD

**Issue by dptms** [z-song/laravel-admin#3360]
- Laravel Version: 5.5.*
- PHP Version: 7.2
- Laravel-admin: 1.6.15

### Description:
当我在`form` 的 `hasMany` 中使用 `$form->table` 的时候，两个新增会有冲突，试问一下是不是两个按钮的 `class` 都为 `add` 所以造成的冲突，点击 `table` 的 `add` 会有点击 `hasMany` 中 `add` 的效果

![image](https://user-images.githubusercontent.com/22364664/57915853-38993a80-78c4-11e9-9127-12669a1eac2c.png)

```
$form->text('title', '方案名称')->rules('required');
        $form->number('value', '建议摄入热量')->default(1)->rules('required')->help('单位：大卡');
        $form->hasMany('plan_items', '包含内容', function (Form\NestedForm $form) {
            $form->select('classification_id', '类别')->options(Classification::query()->where('type', Classification::TYPE_DIET)->get()->pluck('title', 'id'))->load('items', '/admin/parameters-diet')->rules('required');
            $form->rate('percent', '占比')->rules('required');
            $form->table('items', function ($table) {
                $table->text('key');
                $table->text('value');
                $table->text('desc');
            });
        });
```

**Comment by dptms** [comment]
![image](https://user-images.githubusercontent.com/22364664/58065176-637ed980-7bb7-11e9-88ce-1b86cce512d4.png)

还有一个问题呢。感觉也是 `class` 的命名冲突，如果在一个form里面有两个`table`,点击上面的新增，也触发了下面的新增。

**Comment by 77zealous** [comment]
前不久我也遇到这个问题 目前先尽量避免嵌套使用hasmany和table吧...
