### ISSUE TITLE
Edit with route parameter

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3365]
Hello,

I have a route with one paremeter:

`'/events/{event}/participants' => Events\ParticipantController::class,`

The problem is that when editing a record always edit the same record, because I take as participant parameter the id of the event, which I have defined in the route.

The same code without making use of the parameter in the route works correctly.

**Comment by z-song** [comment]
@mendizalea Rewrite the following three actions in your controller
```php
public function edit($event, $id, Content $content)
{
    ...
}

public function edit($event, $id, Content $content)
{
    ...
}

public function update($event, $id)
{
    ...
}

public function destroy($event, $id)
{
    ...
}
```

**Comment by mendizalea** [comment]
Thanks you @z-song :)

**Comment by Xiujuan** [comment]
> @mendizalea Rewrite the following three actions in your controller
> 
> ```
> public function edit($event, $id, Content $content)
> {
>     ...
> }
> 
> public function update($event, $id)
> {
>     ...
> }
> 
> public function destroy($event, $id)
> {
>     ...
> }
> ```

I tried this way in my EntryController, then an error is happened.
`Declaration of App\Admin\Controllers\EntryController::edit($camp_no, $id, Encore\Admin\Layout\Content $content) must be compatible with Encore\Admin\Controllers\AdminController::edit($id, Encore\Admin\Layout\Content $content)`
How can I solve this problem?
