### ISSUE TITLE
An invalid form control with name='XXX' is not focusable.

### ISSUE THREAD

**Issue by UsamaITS** [z-song/laravel-admin#3368]
- Laravel Version: 5.7.*
- PHP Version: 7.2.10
- Laravel-admin: 1.6.15

### Description:

![gethub](https://user-images.githubusercontent.com/36929361/57973401-26e19100-79b1-11e9-9c46-96b9e385abf4.PNG)

I got this message after i submit any form on my project : "**An invalid form control with name='xxx' is not focusable"**. This messages appears on the browser console ;  where xxx is the name of my form field, i realize later that if i submit my form with no data, the browser console print out all the forms fields attached with "**rules**" validation with that message, .

it's mean there are a problem with validation on laravel-admin, i think this problem related with last 3-4 laravel-admin release update, because i didn't touch the vendors lib's neither the vendor assests. I try testing all my forms, even i made a form with one field attach with a "**rules**". same problem ; it's clear that the problem is public, and the validation moved to HTML browser.

![gethub2](https://user-images.githubusercontent.com/36929361/57973446-a1aaac00-79b1-11e9-905c-b2d7d78f86ca.PNG)

I replace **vendor/encore** folder by older version 1.6.7, the problem was solved ; validations rules works fine! no more messages ?? 

Supposedly, the validation error message must appear above or down to my form field being validated, but it appear in a console, which mean there is something wrong with laravel-admin validation, i could not trace the problem, please help, thanks in advance.

**Comment by z-song** [comment]
Which browser are you using?

**Comment by UsamaITS** [comment]
Mr. z-song thank you for come by,

I'm using Google Chrome, but I already test my forms with Firefox,Opera and UC Browsers ; 
Chrome,Opera & UC have the same messages, Firefox have no messages but replace validation with Browser HTML validation.

I tried all my forms, and my previous projects, replacing all my assets with fresh one. same issue. But when i downgrade to laravel-admin 1.6.7 forms works fine with validation ( I just replace vendor/encore folder with v1.6.7).

I'm sure because i'm the only one have this problem as I can see, maybe something related to my code after updating laravel-admin and it seems something public to my code because all my forms even all my projects after being updated, validation problem occurs !.

**Comment by alexskin** [comment]
Dear Z-song! 
On 1.6.11 Laravel-admin I have same bug, but on 1.6.7 works fine.

**Comment by z-song** [comment]
@UsamaITS @alexskin What type of Field have this problem？I tried many fields and didn't reproduce your problem.

**Comment by UsamaITS** [comment]
The issue is not related to the fields,it related to validation, when I use validation such 'require' with any field, Browser validation take place instead of Laravel ; like the switch field above.
When I use Tabs inside a form ; because JS involved with switching between tabs, error messages on the console appear for every field required validation on the other non-active tabs.

**Comment by alexskin** [comment]
Step to reproduce (v1.6.15):

1. Didn't have any extra
![image](https://user-images.githubusercontent.com/13488229/59255062-a91c4880-8c31-11e9-9d3c-ceb20eb2930c.png)

2. Click add new
![image](https://user-images.githubusercontent.com/13488229/59255128-c9e49e00-8c31-11e9-9b5d-37d25e832d03.png)

3. Click remove
![image](https://user-images.githubusercontent.com/13488229/59255157-d832ba00-8c31-11e9-82a3-999be4d8f7bf.png)

4. Click save, and got this error.
![image](https://user-images.githubusercontent.com/13488229/59255200-f0a2d480-8c31-11e9-931f-79d0364849d2.png)

**Comment by UsamaITS** [comment]
@alexskin, Please try my last [replay](https://github.com/z-song/laravel-admin/issues/3368#issuecomment-500176244) that identify the issue place.

**[ver: 1.6.13 to 1.6.15] :** 
**File** : src/Form/Field.php  
**Function** : public function rules($rules = null, $messages = [])
**Disabling** 2 lines [ $this->addRequiredAttribute($rules); ] solve the issue.

 **[ver: 1.7.0 -> 1.7.1] :** 
**File** : src/Form/Field.php 
**Function** : protected function addRequiredAttributeFromRules()
**Disabling**  line [ $this->addRequiredAttribute($rules); ] solve the issue.

@z-song  I didn't trace the cause of this issue , but this helps me temporarily.

**Comment by minosss** [comment]
I guess because the remove button just hidden item(tr), does not delete it.

**Comment by UsamaITS** [comment]
Mr. @z-song ,

After Updating to ver 1.7.2 , It clearly shows that you have restructured the file **src/Form/Field.php**.
This issue appear again and now i tracked the issue until i got that the **"addRequiredAttribute"** which add attribute **required="1"** to the Form Field cause this issue.

I couldn't disable it till now with ver 1.7.2 it seems there is a checker before rendering that make sure that every **required** rule in the form  have the html attribute **required="1"** on the field.

**Comment by yhorozco90** [comment]
Here is other solution without modify a vendor class directly wich is the main problem with the aboved solution:
Removing the html5 validation in forms. For do this go to your laravel-admin bootstrap file and add the following lines:
```
Admin::script(
    <<<SCRIPT
$(document).ready(function() {  
    $('form').attr('novalidate','novalidate');    
});
SCRIPT
);
```
If you want to do this just for one from add the script in the form needed like this:

  ```
public  function form() {
        return Admin::form(Users::class, function (Form $form) use ($id) {
            Admin::script(
                <<<SCRIPT
                    $(document).ready(function() {  
                       $('form').attr('novalidate','novalidate');    
                    });
                SCRIPT
            );
///.... rest of form........
        });
    }
```

**Comment by UsamaITS** [comment]
Thanks all, 
I was late to clarify the whole issue caused by JS vendor "jquery-pjax" file , I forgot to update (publish) public venodr files that coressponds to laravel-admin version.

**Comment by alexandrekadri** [comment]
Try to use ->rules('required') instead ->required();
Ex: $form->text('nome_pt', trans('admin.nome_pt'))->required(); //will throw error
$form->text('nome_pt', trans('admin.nome_pt'))->rules('required'); // will run ok

**Comment by blackcolt** [comment]
> Try to use ->rules('required') instead ->required();
> Ex: $form->text('nome_pt', trans('admin.nome_pt'))->required(); //will throw error
> $form->text('nome_pt', trans('admin.nome_pt'))->rules('required'); // will run ok

This answer solved my issue, thanks!
