### ISSUE TITLE
[BUG?] Jquery error

### ISSUE THREAD

**Issue by serzhiio** [z-song/laravel-admin#337]
Hi, i got a strange bug.
When open any listing(grid) and after choose other page butch selector doesn't work and jquery error appears.

**Comment by serzhiio** [comment]
I've just found out that this bug appears after add of a new batch action.
If I delete new batch action everything work as expected.

**Comment by z-song** [comment]
Check the new batch action class, and maybe can find out what causes the error.

**Comment by serzhiio** [comment]
Z-song thanks for very fast response.
Found my error.
