### ISSUE TITLE
重写数据源paginate方法无效

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3375]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

![image](https://user-images.githubusercontent.com/40032190/58005019-3da1f800-7b17-11e9-947e-b22bc3ad85c9.png)
![image](https://user-images.githubusercontent.com/40032190/58005050-57dbd600-7b17-11e9-8517-89d318e0e294.png)
打断点怎么连paginate都不跑了

**Comment by z-song** [comment]
哪里打断点？

**Comment by newbrash** [comment]
断点执行顺序为   ProductPriceController（controller）->new Grid()->ProductPrice（model）-> return $Grid-> ProductPriceController
并没有进去paginate方法里


还碰到一种情况，数据源修改成功，index主页数据确实来源于paginate，但是filter搜索没有跑paginate


------------------ 原始邮件 ------------------
发件人: "Song"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 晚上6:30
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>;
抄送: "布鲁布鲁"<2199374997@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [z-song/laravel-admin] 重写数据源paginate方法无效 (#3375)




哪里打断点？

**Comment by newbrash** [comment]
> 哪里打断点？

filter筛选数据源数据采取的解决办法是，重写搜索按钮：
![image](https://user-images.githubusercontent.com/40032190/58016146-836aba80-7b2f-11e9-95ad-018b84808d8a.png)
对比原来的链接去掉了pjax参数，但是这种效果会导致整个页面刷新，体验不好
![image](https://user-images.githubusercontent.com/40032190/58016234-abf2b480-7b2f-11e9-98a9-cc8187cf7767.png)

**Comment by z-song** [comment]
filter搜索会调用模型的where方法，所以你要去重写模型的where方法

**Comment by newbrash** [comment]
我不开启xdebug的时候它跑where方法，但是xdebug开启之后它就不跑where了，是我断点打的有问题吗



断点位置为    controller->new Grid ->return $grid->model->model的where方法
------------------ 原始邮件 -----------------
发件人: "Song"<notifications@github.com>;
发送时间: 2019年5月20日(星期一) 晚上6:54
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>;
抄送: "布鲁布鲁"<2199374997@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [z-song/laravel-admin] 重写数据源paginate方法无效 (#3375)




filter搜索会调用模型的where方法，所以你要去重写模型的where方法

**Comment by tanjhysj0** [comment]
谁告诉我如何重写where?

**Comment by Ifor86** [comment]
> 谁告诉我如何重写where?

@tanjhysj0 我也想知道怎么重写where
