### ISSUE TITLE
请问如何在同一个header中插入两个不同的chart.js图形统计

### ISSUE THREAD

**Issue by Twilightsixteen** [z-song/laravel-admin#3376]
- Laravel Version: 5.5
- PHP Version:7.1.2
- Laravel-admin: 1.6.10

### Description:
插入单图形统计完全没有问题, 现在我需要插入多个, 翻阅文档也没有提及相关操作, 只能来这里求问了

**Comment by orzcc** [comment]
`通过 Row

$grid->header(function () {
            $row = new Row;
             $row->column(1/2, new Box('xxx', xxx));
            $row->column(1/2, new Box('xxx', xxx));
            return $row;
});`

**Comment by Twilightsixteen** [comment]
> 正好之前也有这个需求，稍微研究下。通过 Row就可以轻松实现多个。
> 
> ```
> $grid->header(function () {
>     $row = new Row;
>     $row->column(1/2, new Box('xxx', xxx));
>     $row->column(1/2, new Box('xxx', xxx));
>     return $row;
> });
> ```


我好像还是没整明白... 这是我的代码部分
Controller部分:

use Encore\Admin\Layout\Row;

            $sex = view('admin.userGender', compact('sexArray'));
            $age = view('admin.userGender', compact('ageArray'));

            $row = new Row();
            $row->column(1/2, new Box('性别统计', $sex));
            $row->column(1/2, new Box('年龄统计', $age));
            return $row;

blade部分:
<canvas id="sex" width="200" height="300"></canvas>
<canvas id="age" width="200" height="300"></canvas>
<script>
    $(function () {

        var ctx = document.getElementById('sex').getContext('2d');
        new Chart(ctx, {
            type: 'doughnut',
            data: {
                datasets: [{
                    data: [
                        {{ $sexArray['man'] }},
                        {{ $sexArray['women'] }},
                        {{ $sexArray['unknown'] }},
                    ],
                    backgroundColor: [
                        'rgb(54, 162, 235)',
                        'rgb(255, 99, 132)',
                    ]
                }],
                labels: [
                    '男性 ' + "{{ $sexArray['man'] }}",
                    '女性 ' + "{{ $sexArray['women'] }}",
                    '未知 ' + "{{ $sexArray['unknown'] }}",
                ]
            },
            options: {
                maintainAspectRatio: false,
                cutoutPercentage:0,
            }
        });


        var ctx = document.getElementById('age').getContext('2d');
        new Chart(ctx, {
            type: 'doughnut',
            data: {
                datasets: [{
                    data: [
                        {{ $ageArray['10'] }},
                        {{ $ageArray['20'] }},
                        {{ $ageArray['30'] }},
                        {{ $ageArray['40'] }},
                        {{ $ageArray['50'] }},
                        {{ $ageArray['60'] }},
                        {{ $ageArray['70'] }},
                        {{ $ageArray['80'] }},
                        {{ $ageArray['90'] }},
                    ],
                    backgroundColor: [
                        'rgb(54, 162, 235)',
                        'rgb(255, 99, 132)',
                    ]
                }],
                labels: [
                    '0-10岁 ' + "{{ $ageArray['10'] }}",
                    '11-20岁 ' + "{{ $ageArray['20'] }}",
                    '21-30岁 ' + "{{ $ageArray['30'] }}",
                    '31-40岁 ' + "{{ $ageArray['40'] }}",
                    '41-50岁 ' + "{{ $ageArray['50'] }}",
                    '51-60岁 ' + "{{ $ageArray['60'] }}",
                    '61-70岁 ' + "{{ $ageArray['70'] }}",
                    '71-80岁 ' + "{{ $ageArray['80'] }}",
                    '80岁以上 ' + "{{ $ageArray['90'] }}",
                ]
            },
            options: {
                maintainAspectRatio: false,
                cutoutPercentage:0,
            }
        });

    });
</script>

现在抛出异常说模板上找不到ageArray... 是哪里写错了吗?
