### ISSUE TITLE
where，orderby等方法来源于源码那个位置

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3378]
- Laravel Version: 5.5
- PHP Version:>7.0
- Laravel-admin: >1.6.*

### Description:

![image](https://user-images.githubusercontent.com/40032190/58018497-97b1b600-7b35-11e9-9166-6b0c4d045c1e.png)
我想知道链式查询的方法来自于哪里，怎么用xdebug找到，以及怎么重写查询方法
感觉用xdebug的方式不对，断点总是没有按照自己想要的方向跑，xdebug用了好久了，总是云里雾里的

**Comment by nkjackzhang** [comment]
$model->where()最后都落在Illuminate\Database\Eloquent\Builder里的，直接去那里设置断点就行了
