### ISSUE TITLE
form表单一对一的时候有个非常奇怪的问题？（框架BUG已解决）

### ISSUE THREAD

**Issue by dmf-code** [z-song/laravel-admin#3379]
- Laravel Version: v5.8.17
- PHP Version: 7.3.0
- Laravel-admin: 1.6.15

### Description:
![image](https://user-images.githubusercontent.com/22268578/58033471-208d1980-7b57-11e9-8977-b6a7b87f816a.png)
文档上也是对应函数名而非表名？
在使用一对多的时候，在编辑时使用classInfo无法显示值，使用class_info就能显示值。如果将classInfo中的text全部注释掉，全部的class_info也就无法显示值了。
![image](https://user-images.githubusercontent.com/22268578/58032292-e753aa00-7b54-11e9-9b8b-b037edfd0790.png)

![image](https://user-images.githubusercontent.com/22268578/58032230-c428fa80-7b54-11e9-9abc-a4096c8e4d9e.png)

```php
        $form->text('classInfo.grade', '年级');
        $form->text('class_info.grade', '年级');
        $form->text('classInfo.class', '班级');
        $form->text('class_info.class', '班级');
```

数据表：
```
CREATE TABLE `students` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '姓名',
  `gender` tinyint(3) unsigned NOT NULL DEFAULT '0' COMMENT '性别',
  `enrol` year(4) NOT NULL COMMENT '入学年份',
  `birth` date NOT NULL COMMENT '出生日期',
  `address` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '家庭住址',
  `avatar` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '头像',
  `status` tinyint(3) unsigned NOT NULL COMMENT '状态',
  `desc` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '备注',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `students_name_index` (`name`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

classInfo模型
```
class ClassInfo extends Model
{
    protected $table = 'class_info';
    protected $fillable = ['grade', 'class'];
    public function students()
    {
        return $this->belongsTo(Students::class);
    }
}
```

数据表：
```
CREATE TABLE `class_info` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `student_id` int(11) NOT NULL COMMENT '学生id',
  `grade` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '年级',
  `director` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '辅导员',
  `class` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '班级',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```
students模型
```
class Students extends Model
{
    protected $table = 'students';
    public function contacts()
    {
        return $this->hasMany(Contacts::class, 'student_id');
    }

    public function classInfo()
    {
        return $this->hasOne(ClassInfo::class, 'student_id');
    }
}
```

### Steps To Reproduce:
@z-song

**Comment by dmf-code** [comment]
问题我已经找到了，这里是因为Form组件会找定义好的函数例如`classInfo`这个依赖（`method_exists`），所以我不填写`$form->text('classInfo.grade', '年级');`这个的话根本上就不会查数据库，所以就没有数据。
然后数据找出来后又直接使用模型的`toArray`导致字段输出为`class_info`字段
```
array:13 [▼
  "id" => 5
  "name" => "s1"
  "gender" => 0
  "enrol" => 2019
  "birth" => "2019-04-22"
  "address" => "test"
  "avatar" => null
  "status" => 0
  "desc" => "test"
  "created_at" => "2019-04-22 15:42:20"
  "updated_at" => "2019-04-22 15:42:20"
  "class_info" => array:7 [▼
    "id" => 1
    "student_id" => 5
    "grade" => "1"
    "director" => null
    "class" => "2"
    "created_at" => "2019-04-22 15:42:20"
    "updated_at" => "2019-05-20 14:37:40"
  ]
  "contacts" => array:2 [▶]
]
```
所以这里就造成了无法对应上的Bug了。
这里面我使用直接将函数的字段名也添加到data变量上，然后就可以直接使用classInfo这个字段了，不然使用class_info还会出现无法更新的问题。
解决方案：
Form组件setFieldValue函数里面添加多一段代码：
```
        foreach ($this->model->getRelations() as $k => $v) {
            if ($v instanceof Model && isset($data[$v->getTable()])) {
                $data[$k] = $data[$v->getTable()];
            }
        }
```
![image](https://user-images.githubusercontent.com/22268578/58040201-7cf83500-7b67-11e9-83cb-6983c7e47f68.png)
@z-song

**Comment by newbrash** [comment]
你好，我想问一下Admin::form加在哪个位置，控制器里的 form函数要要做改变吗

**Comment by dmf-code** [comment]
> 你好，我想问一下Admin::form加在哪个位置，控制器里的 form函数要要做改变吗
具体修改文件在这里
[修改文件](https://github.com/z-song/laravel-admin/blob/d2f8d9ecc47a7ecc82e5abd60f3ce09aecbe2689/src/Form.php#L1066)
@newbrash

**Comment by newbrash** [comment]
> > 你好，我想问一下Admin::form加在哪个位置，控制器里的 form函数要要做改变吗
> > 具体修改文件在这里
> > [修改文件](https://github.com/z-song/laravel-admin/blob/d2f8d9ecc47a7ecc82e5abd60f3ce09aecbe2689/src/Form.php#L1066)
> > @newbrash
项目名称并没有查出来
![image](https://user-images.githubusercontent.com/40032190/58069633-8a91d700-7bc8-11e9-90ee-0033b3237d96.png)
![image](https://user-images.githubusercontent.com/40032190/58069643-9a112000-7bc8-11e9-8a6f-dc606d7feaf2.png)

![image](https://user-images.githubusercontent.com/40032190/58069667-ba40df00-7bc8-11e9-9b76-23faadf699f9.png)
![image](https://user-images.githubusercontent.com/40032190/58069673-c036c000-7bc8-11e9-9118-cf7430475c97.png)
上面的一对一关联并没有问题，应为grid查到了数据
![image](https://user-images.githubusercontent.com/40032190/58069700-d9d80780-7bc8-11e9-8cbf-f5f8a29a6b00.png)
![image](https://user-images.githubusercontent.com/40032190/58069710-ed836e00-7bc8-11e9-9da9-eda7422ca91b.png)

**Comment by dmf-code** [comment]
> > > 你好，我想问一下Admin::form加在哪个位置，控制器里的 form函数要要做改变吗
> > > 具体修改文件在这里
> > > [修改文件](https://github.com/z-song/laravel-admin/blob/d2f8d9ecc47a7ecc82e5abd60f3ce09aecbe2689/src/Form.php#L1066)
> > > @newbrash
> > > 项目名称并没有查出来
> > > ![image](https://user-images.githubusercontent.com/40032190/58069633-8a91d700-7bc8-11e9-90ee-0033b3237d96.png)
> > > ![image](https://user-images.githubusercontent.com/40032190/58069643-9a112000-7bc8-11e9-8a6f-dc606d7feaf2.png)
> 
> ![image](https://user-images.githubusercontent.com/40032190/58069667-ba40df00-7bc8-11e9-9b76-23faadf699f9.png)
> ![image](https://user-images.githubusercontent.com/40032190/58069673-c036c000-7bc8-11e9-9118-cf7430475c97.png)
> 上面的一对一关联并没有问题，应为grid查到了数据
> ![image](https://user-images.githubusercontent.com/40032190/58069700-d9d80780-7bc8-11e9-8cbf-f5f8a29a6b00.png)
> ![image](https://user-images.githubusercontent.com/40032190/58069710-ed836e00-7bc8-11e9-9da9-eda7422ca91b.png)

大哥，我一直都是说回显有问题呀

**Comment by dmf-code** [comment]
> > > 你好，我想问一下Admin::form加在哪个位置，控制器里的 form函数要要做改变吗
> > > 具体修改文件在这里
> > > [修改文件](https://github.com/z-song/laravel-admin/blob/d2f8d9ecc47a7ecc82e5abd60f3ce09aecbe2689/src/Form.php#L1066)
> > > @newbrash
> > > 项目名称并没有查出来
> > > ![image](https://user-images.githubusercontent.com/40032190/58069633-8a91d700-7bc8-11e9-90ee-0033b3237d96.png)
> > > ![image](https://user-images.githubusercontent.com/40032190/58069643-9a112000-7bc8-11e9-8a6f-dc606d7feaf2.png)
> 
> ![image](https://user-images.githubusercontent.com/40032190/58069667-ba40df00-7bc8-11e9-9b76-23faadf699f9.png)
> ![image](https://user-images.githubusercontent.com/40032190/58069673-c036c000-7bc8-11e9-9118-cf7430475c97.png)
> 上面的一对一关联并没有问题，应为grid查到了数据
> ![image](https://user-images.githubusercontent.com/40032190/58069700-d9d80780-7bc8-11e9-8cbf-f5f8a29a6b00.png)
> ![image](https://user-images.githubusercontent.com/40032190/58069710-ed836e00-7bc8-11e9-9da9-eda7422ca91b.png)

仔细看看我发的第二条评论的图片，我是在回显出错了。grid组件是没问题的，我这边也有值显示。但是form组件就有问题了。

**Comment by dmf-code** [comment]
> > > 你好，我想问一下Admin::form加在哪个位置，控制器里的 form函数要要做改变吗
> > > 具体修改文件在这里
> > > [修改文件](https://github.com/z-song/laravel-admin/blob/d2f8d9ecc47a7ecc82e5abd60f3ce09aecbe2689/src/Form.php#L1066)
> > > @newbrash
> > > 项目名称并没有查出来
> > > ![image](https://user-images.githubusercontent.com/40032190/58069633-8a91d700-7bc8-11e9-90ee-0033b3237d96.png)
> > > ![image](https://user-images.githubusercontent.com/40032190/58069643-9a112000-7bc8-11e9-8a6f-dc606d7feaf2.png)
> 
> ![image](https://user-images.githubusercontent.com/40032190/58069667-ba40df00-7bc8-11e9-9b76-23faadf699f9.png)
> ![image](https://user-images.githubusercontent.com/40032190/58069673-c036c000-7bc8-11e9-9118-cf7430475c97.png)
> 上面的一对一关联并没有问题，应为grid查到了数据
> ![image](https://user-images.githubusercontent.com/40032190/58069700-d9d80780-7bc8-11e9-8cbf-f5f8a29a6b00.png)
> ![image](https://user-images.githubusercontent.com/40032190/58069710-ed836e00-7bc8-11e9-9da9-eda7422ca91b.png)

大兄弟，不好意思哈。今天没看清你的问题，还以为你是来确认bug的。这个问题和我的一样呢？你在vendor项目中找到laravel-admin的源码，然后里面有Form.php文件的，只要修改这个文件就行。上面我有发链接还标记了在哪里添加我之前发的代码。
只要添加上去就行了。
修改文件链接：在1066行
https://github.com/z-song/laravel-admin/blob/d2f8d9ecc47a7ecc82e5abd60f3ce09aecbe2689/src/Form.php#L1066
添加的代码
```
        foreach ($this->model->getRelations() as $k => $v) {
            if ($v instanceof Model && isset($data[$v->getTable()])) {
                $data[$k] = $data[$v->getTable()];
            }
        }
```
