### ISSUE TITLE
[BUG] Call to a member function hasBag() on string

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#338]
I have been set error message for content and got it.
[![https://gyazo.com/6ce5dd93315cc4b1c5202aa1dabf0db1](https://i.gyazo.com/6ce5dd93315cc4b1c5202aa1dabf0db1.png)](https://gyazo.com/6ce5dd93315cc4b1c5202aa1dabf0db1)

[![https://gyazo.com/edfc8941ff749392b9d12980b1781125](https://i.gyazo.com/edfc8941ff749392b9d12980b1781125.png)](https://gyazo.com/edfc8941ff749392b9d12980b1781125)

**Comment by z-song** [comment]
Just return the `$content` object.

**Comment by taimaiduc** [comment]
Got it thanks.
