### ISSUE TITLE
Force user to change password

### ISSUE THREAD

**Issue by rwmediaworks** [z-song/laravel-admin#3381]
- Laravel Version: 5.8.15
- PHP Version: 7.2.8
- Laravel-admin: 1.6.13

### Description:

In our project user credentials are generated through script & those credentials are mailed to the respective users.

When user log in for the first time I want to force user to change the password. What will be the ideal procedure?

Note: I do not want user to access any page under /admin route until password has been changed.

**Comment by z-song** [comment]
You can add a middleware to to all admin routes  in `config/admin.php`

```php
class ChangePassword
{
    public function handle($request, Closure $next)
    {
        if (first time login && !$request->is('admin/auth/setting')) {
            admin_warning('Warning', 'Please change your password.');

            return redirect()->route('admin.setting');
        }

        return $next($request);
    }
}
```

**Comment by eine91** [comment]
Thnaks @z-song for the help

**Comment by rwmediaworks** [comment]
Thanks @z-song  for the help.
