### ISSUE TITLE
gird使用多个expand，只会展开第一个

### ISSUE THREAD

**Issue by Yuner2018** [z-song/laravel-admin#3383]
- Laravel Version: 5.8.12
- PHP Version:7.1.18
- Laravel-admin: 1.6.11

### Description:
 $grid->column('okdetail', '成交')->expand(function () {
            $headers = ['母账户', '成交价', '成交量', '成交编号', '成交时间', '持仓单号', '下单时间'];
            $rows = Deal::where('delegation_sn', $this->order_sn)->get(['disk_account', 'price', 'amount', 'disk_index', 'ok_time', 'position_sn', 'created_at'])->toArray();
             return new Table($headers, $rows);
   }, '成交');
$grid->column('deledetail', '委托')->expand(function () {
          $headers = ['母账户', '委托量', '合同编号', '是否做T', '时间'];
          $rows = DelegationDisk::where('delegation_sn', $this->order_sn)->get(['disk_account', 'amount', 'disk_sn', 'is_all', 'created_at'])->toArray();
          return new Table($headers, $rows);
  }, '委托');

点击成交或者委托，都只会显示第一个成交明细。

**Comment by z-song** [comment]
提交了修复

**Comment by edwinhuish** [comment]
提交了我的解决PR，请查看 @z-song

**Comment by vonsogt** [comment]
solved my problem, thanks
