### ISSUE TITLE
资源路由，权限不生效问题。

### ISSUE THREAD

**Issue by tangyus** [z-song/laravel-admin#3393]
- Laravel Version: 5.5
- PHP Version: 7.1.19
- Laravel-admin: 1.6.15

### Description:
使用资源路由，权限无法正常生效的问题。
以上 **issue** 也出现过相同的情况
https://github.com/z-song/laravel-admin/issues/3067#issue-419370557

### Steps To Reproduce:
使用 `resource` 创建资源路由
``` php
$router->resource('shops', ShopController::class, ['except' => ['destroy']]);
```

我赋予后台一个市场人员查看列表和查看详情的权限
其中 
 `/admin/shops` `index` 方法，查看列表
 `/admin/shops/{shop}` `show` 方法，查看详情

最后测试的过程中，`查看列表` 权限访问无问题，`查看详情` 的权限一直页面显示 **无权访问**

而在 `index` 方法
```
dd(Admin::user()->can('shops.show')) // true
```
说明权限是正确赋予了的!!!

追查源码过程中，发现是中间件 `Middleware\Permission` 的 `handle` 方法拦截了。
``` php
if (!Admin::user()->allPermissions()->first(function ($permission) use ($request) {
     return $permission->shouldPassThrough($request);
})) {
     Checker::error();
}
```
以上代码 **拦截**

而我的路由中间件设置是原始的，如下
``` php
Route::group([
    'prefix'        => config('admin.route.prefix'),
    'namespace'     => config('admin.route.namespace'),
    'middleware'    => config('admin.route.middleware'),
], function (Router $router) {
    $router->resource('shops', ShopController::class, ['except' => ['destroy']]);
});
```

还请劳烦帮忙解决一下，十分感激。

**Comment by tangyus** [comment]
补充一下，如果我把 查看详情 的权限写死的话，是可以生效的。

**Comment by nkjackzhang** [comment]
因为这个admin的权限匹配只支持*这样的通配符，不支持{}这样的占位符，所以你权限路由写{}是不生效的，无论后面的参数是多少

**Comment by tangyus** [comment]
> 因为这个admin的权限匹配只支持*这样的通配符，不支持{}这样的占位符，所以你权限路由写{}是不生效的，无论后面的参数是多少，权限匹配和路由匹配不是一回事，所以can(‘show’)可以返回true，同时路由也可以不匹配的。
> 解决办法，用/admin/shops/*来替换掉你原来写的，这时候要注意，如果你要写/admin/shops/dosomeaction这样的路由也会被/admin/shops/*匹配到，所以这样的路由应该命名成/admin/api/shops/dosomeaction，让/admin/shops/*匹配不到。

got it!
