### ISSUE TITLE
[Grid] totalRow列隐藏后仍然显现

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3399]
数据导出按钮后面有个控制列显示，隐藏某些列后，表格下面的统计没有隐藏。
![img](https://user-images.githubusercontent.com/10061650/58235979-830f3100-7d74-11e9-853a-8d1dc471e939.png)

![img](https://user-images.githubusercontent.com/10061650/58235780-13994180-7d74-11e9-9b39-71efed46f2bd.png)

**Comment by z-song** [comment]
已修复
