### ISSUE TITLE
how to use required_if

### ISSUE THREAD

**Issue by mRamadan0101** [z-song/laravel-admin#3406]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
i want to user required_if when set role in user
`        $form->multipleSelect('roles', trans('admin.roles'))->options($roleModel::all()->pluck('name', 'id'));
        $form->select('res_id', 'Restaurant')->rules('required_if:roles[0],2');`

**Comment by z-song** [comment]
@mRamadan0101 Try `'required_if:roles.0,2'`

**Comment by mRamadan0101** [comment]
Thanks its working
