### ISSUE TITLE
BUG - HasMany stores only 1 new row

### ISSUE THREAD

**Issue by langeuh** [z-song/laravel-admin#341]
Recent rewrite concerning the form fields adds a lot of errors
I already wrote 2 fixes
#340 #339 

but the HasMany form has other problems:
Only 1 new row gets stored
this is a dump of the input from a HasMany component with multiple new fields

```php
array:1 [▼
  "new__key_" => array:3 [▼
    "product_id" => "4"
    "unit_price" => 30.0
    "_remove_" => "0"
  ]
]
```

**Comment by edwinhuish** [comment]
where do you get this array? 

I didn't have the error.

**Comment by z-song** [comment]
@langeuh issue fixed, thank you for point out this!

**Comment by langeuh** [comment]
works fine now. Resolved

**Comment by langeuh** [comment]
reopening this, since it is still broken
see fix #369

**Comment by langeuh** [comment]
reopening this, since it is still broken
see fix #369

**Comment by langeuh** [comment]
@z-song still broken :)  #369 fixes it

**Comment by z-song** [comment]
@langeuh thanks , your pull request has been merged
