### ISSUE TITLE
这种一对多的Form的View布局如何？

### ISSUE THREAD

**Issue by edwinhuish** [z-song/laravel-admin#3411]
![image](https://user-images.githubusercontent.com/5207925/58322426-862d1e80-7e53-11e9-8f85-5b1baa042138.png)
![image](https://user-images.githubusercontent.com/5207925/58322440-90e7b380-7e53-11e9-9702-35d9484d6d34.png)

在其他地方看到，感觉下面这个一对多的Form的View布局更合理。

不知道 @z-song 感觉如何？

**Comment by z-song** [comment]
这个布局在多个一对多字段的场景里面会比较实用
