### ISSUE TITLE
更新1.6.15之后，压缩css/js，富文本编辑框无法使用

### ISSUE THREAD

**Issue by jinmaodao116** [z-song/laravel-admin#3413]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.6.15

### Description:
压缩css/js，富文本编辑器文件引用路径错误。
CKEditor,uEditor 无法使用

**Comment by fangke2688** [comment]
说一下我处理的过程：
首先去找到command
分析源码
查找excepts处理代码
用了最笨的方法，把变量打印出来，之后找到需要的路径，加入config/admin.php minify_assets->excepts即可。

**Comment by fangke2688** [comment]
说一下我的处理方法：
找到对应的command，分析处理方法，采用最笨的方法，将变量打印出来，找到需要的，加入excepts即可。
