### ISSUE TITLE
rules如果传入函数，required图标效果不会显示出来

### ISSUE THREAD

**Issue by qusheng19890714** [z-song/laravel-admin#3414]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

        $form->text('authorization.identifier', trans('user::user.identifier.label'))->rules(function($form) {

            return 'required|string|max:255';
        });

**Comment by z-song** [comment]
```php
    $form->text('authorization.identifier', trans('user::user.identifier.label'))->rules(function($form) {

        return 'required|string|max:255';
    })->required();
```
