### ISSUE TITLE
点击搜索后between框的值会消失

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3415]
- Laravel Version: 5.5
- PHP Version:》7.0
- Laravel-admin: 1.6.3

### Description:
筛选之后的筛选条件值没有保留
比如：
![image](https://user-images.githubusercontent.com/40032190/58392188-6a03ca00-806b-11e9-9fb3-e0b5c160512b.png)
点击筛选后 select框的值保留了下来，但是between的值消失了
![image](https://user-images.githubusercontent.com/40032190/58392201-75ef8c00-806b-11e9-85bb-a6f31a51b8a7.png)
打印出来的对象信息
![image](https://user-images.githubusercontent.com/40032190/58392277-d5e63280-806b-11e9-9b68-c09647027bfb.png)

**Comment by nkjackzhang** [comment]
这是用的grid的filter？url是什么，between的话，url应该是column['start']=xxx&column['end']=yyy这样的形式，这才能保存between输入框的值

**Comment by newbrash** [comment]
> 这是用的grid的filter？url是什么，between的话，url应该是column['start']=xxx&column['end']=yyy这样的形式，这才能保存between输入框的值

我重写了paginates数据源，filter搜索也是使用paginate返回来的数据，类似这种方法需要在哪里给between添加值呢

**Comment by tanjhysj0** [comment]
同问

**Comment by tanjhysj0** [comment]
> * Laravel Version: 5.5
> * PHP Version:》7.0
> * Laravel-admin: 1.6.3
> 
> ### Description:
> 筛选之后的筛选条件值没有保留
> 比如：
> ![image](https://user-images.githubusercontent.com/40032190/58392188-6a03ca00-806b-11e9-9fb3-e0b5c160512b.png)
> 点击筛选后 select框的值保留了下来，但是between的值消失了
> ![image](https://user-images.githubusercontent.com/40032190/58392201-75ef8c00-806b-11e9-85bb-a6f31a51b8a7.png)
> 打印出来的对象信息
> ![image](https://user-images.githubusercontent.com/40032190/58392277-d5e63280-806b-11e9-9b68-c09647027bfb.png)
> 
> ### Steps To Reproduce:

哥，你的这个问题解决了吗？

**Comment by newbrash** [comment]
没有，我这个是重写数据源之后产生的问题




------------------ 原始邮件 ------------------
发件人: "tanjhysj0"<notifications@github.com>;
发送时间: 2019年7月8日(星期一) 中午11:15
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>;
抄送: "布鲁布鲁"<2199374997@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [z-song/laravel-admin] 点击搜索后between框的值会消失 (#3415)



  
Laravel Version: 5.5
 
PHP Version:》7.0
 
Laravel-admin: 1.6.3
  
Description:
 
筛选之后的筛选条件值没有保留
 比如：
 
 点击筛选后 select框的值保留了下来，但是between的值消失了
 
 打印出来的对象信息
 
 
Steps To Reproduce:
  
哥，你的这个问题解决了吗？

**Comment by tanjhysj0** [comment]
我现在和你一样，重写了paginate，还重写了where




------------------ 原始邮件 ------------------
发件人: "Jason zhang"<notifications@github.com>; 
发送时间: 2019年7月8日(星期一) 中午11:18
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>; 
抄送: "谭积海"<1218714931@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [z-song/laravel-admin] 点击搜索后between框的值会消失 (#3415)



没有，我这个是重写数据源之后产生的问题 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "tanjhysj0"<notifications@github.com>; 
 发送时间: 2019年7月8日(星期一) 中午11:15 
 收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>; 
 抄送: "布鲁布鲁"<2199374997@qq.com>;"Author"<author@noreply.github.com>; 
 主题: Re: [z-song/laravel-admin] 点击搜索后between框的值会消失 (#3415) 
 
 
 
    
 Laravel Version: 5.5 
   
 PHP Version:》7.0 
   
 Laravel-admin: 1.6.3 
    
 Description: 
   
 筛选之后的筛选条件值没有保留 
  比如： 
   
  点击筛选后 select框的值保留了下来，但是between的值消失了 
   
  打印出来的对象信息 
   
   
 Steps To Reproduce: 
    
 哥，你的这个问题解决了吗？

**Comment by zhijiangPan** [comment]
这是一个bug,这个情况应该只有在从外部获取数据且赛选条件为数组的时候才出现这种情况。
```
value="{{ request($name['start'], \Illuminate\Support\Arr::get($value, 'start')) }}" 
```
模板里面 request() 取值翻译过来是 request('created_at[start]') 这样的写法肯定取不到对应的值，request()里面默认值 $value 只有在真实数据模型进行了赛选查询以后才会有值

**Comment by Kaniwong** [comment]
我的做法是直接补充值，如果有更好的方法麻烦告知一下
   //补充between
    protected function auto_complete_between($start,$end)
    {
        return <<<SCRIPT
            $(document).ready(function() {
                $("input[name='created_at[start]']").val("{$start}");
                $("input[name='created_at[end]']").val("{$end}");
            });
SCRIPT;
    }

**Comment by newbrash** [comment]
> start



> 我的做法是直接补充值，如果有更好的方法麻烦告知一下
> //补充between
> protected function auto_complete_between($start,$end)
> {
> return <<<SCRIPT
> $(document).ready(function() {
> $("input[name='created_at[start]']").val("{$start}");
> $("input[name='created_at[end]']").val("{$end}");
> });
> SCRIPT;
> }

1.7.2已经修复这个bug了，你楼上的那个就是修复的结果
value="{{ request($name['start'], \Illuminate\Support\Arr::get($value, 'start')) }}"
