### ISSUE TITLE
uuid做主键时,grid的action链接不正确

### ISSUE THREAD

**Issue by ichynul** [z-song/laravel-admin#3418]
想对laravel框架自带的通知表notification做删除功能，id是类似`840e78ea-7fda-4238-b594-20fc115d8bab`,
`delete`链接的`data-id`不正确导致无法找到要删除的数据

**Comment by z-song** [comment]
https://github.com/z-song/laravel-admin/issues/3354

**Comment by ichynul** [comment]
明白了，谢谢
