### ISSUE TITLE
[REQUEST] Can i create sortable by Relation ?

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#342]
I have a job with many views. 
In grid, I have been join relation and get the view. Can I add sortable for that column

[![https://gyazo.com/d95e83e22161e16c1767d338dc296240](https://i.gyazo.com/d95e83e22161e16c1767d338dc296240.png)](https://gyazo.com/d95e83e22161e16c1767d338dc296240)

 [![https://gyazo.com/420c37decfdb09f49d9708e369364f6f](https://i.gyazo.com/420c37decfdb09f49d9708e369364f6f.png)](https://gyazo.com/420c37decfdb09f49d9708e369364f6f)

**Comment by z-song** [comment]
It's impossible to do `order by` query on related column througth one-to-many relation.

One solution is, add a column `views_count` in current table, so you can make it sortable as other columns.
