### ISSUE TITLE
删除数据时，如何限制只能删除自己创建的数据

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3420]
Laravel-admin: 1.6.15

### Description:

当把laravel-admin用于子用户后台时，需要在操作数据时验证是否有权限操作，比如要求只能删除自己所创建的数据，看了下本想使用`form->deleting`，但发现其回调中无法取到当前操作的数据id及model，请问有什么好办法？

**Comment by z-song** [comment]
可以从路由对象里面获取当前操作数据的id

**Comment by terranc** [comment]
> 可以从路由对象里面获取当前操作数据的id

恩 我看form的destory里其实是查过一次数据库了的，感觉在这里能增加一个一个事件就好了，也免得多查一次数据库应该更好

**Comment by manren** [comment]
要不试着在回调外取好这两值，use进回调呢？不知道可行不

**Comment by nkjackzhang** [comment]
如果想简单的做就在grid里对非当前用户创建的数据隐藏删除按钮

**Comment by terranc** [comment]
> 如果想简单的做就在grid里对非当前用户创建的数据隐藏删除按钮

那只是掩耳盗铃，不妥

**Comment by terranc** [comment]
> 要不试着在回调外取好这两值，use进回调呢？不知道可行不

给个示例？

**Comment by manren** [comment]
> > 要不试着在回调外取好这两值，use进回调呢？不知道可行不
> 
> 给个示例？

Request里拿不到参数？或是从路由对像中拿

**Comment by terranc** [comment]
> > > 要不试着在回调外取好这两值，use进回调呢？不知道可行不
> > 
> > 
> > 给个示例？
> 
> Request里拿不到参数？或是从路由对像中拿

Request拿到了，然后先查一次数据，然后destory里再查一次数据？这不就重复查询了吗？

**Comment by keller31** [comment]
form->deleting 拿不到当前的model确实很奇怪哦

**Comment by keller31** [comment]
目前看来只能在 model 里面做 deletiing 检测了

**Comment by terranc** [comment]
> 目前看来只能在 model 里面做 deletiing 检测了

除非给后台单独一个model，如果前后台用同一个model，把这个逻辑写到deleteing里就不妥了，因为model里还去取后台的当前登录用户的session啥的。
