### ISSUE TITLE
Controlling the redirect after delete

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#3421]
Hi,
I want to controll the redirect after the delete in view and edit.

I tried to and return redirect in destroy method but doesn't works.

Thanks

**Comment by z-song** [comment]
The delete operation is through an ajax request, and currently does not support redirect after delete.

**Comment by KrenZfer** [comment]
hi, i write this to control my redirect delete after deleting data from show and edit/add form,

1. First open /src/Show/Tools.php for redirect delete when view or /src/Form/Tools.php
2. And then add this at the variable declarations
```
    /**
     * Redirect Path After Delete
     */
    protected $redirectDeletePath;
```
3. Add this as function for accessor and mutator for these variable
 ```
    /**
     * Set Redirect After delete path
     * 
     */
    public function setRedirectDeletePath($path)
    {
        $this->redirectDeletePath = $path;
    }

    /**
     * Get redirect delete after path, 
     * but when is not set it return form resource path
     */
    protected function getRedirectDeletePath()
    {
        if($this->redirectDeletePath === "")
        {
            return ltrim($this->getResource(), '/');
        }else{
            return $this->redirectDeletePath;
        }
    }
```
4. The last step, on function renderDelete() there is code like this
```
  $.pjax({container:'#pjax-container', url: '{$this->getListPath()}' });
```
Change it to
```
  $.pjax({container:'#pjax-container', url: '{$this->getRedirectDeletePath()}' });
```

this work for me, i hope it helps you
