### ISSUE TITLE
Upload Single or Multiple Image Relationship to a Different Table

### ISSUE THREAD

**Issue by JFOC** [z-song/laravel-admin#3422]
- Laravel Version: 5.8.18
- PHP Version: 7.2.10
- Laravel-admin: 1.6.15

### Description:
I have table:
1. Subjects Table
id, course_id, title

2. Image Table
id, subject_id, unit_id, filename

3. Unit table
id, subject_id, title

I want to upload multiple/single (if a subject single image, if unit multiple image) image with relation to subject_id or unit_id depend on what going to upload image either subject or unit.

Trying using $form->multipleImage or $form->image cannot make an image related to subject/unit id.

Do you have any clue how to achieve this?

**Comment by pirmanduiana** [comment]
I have the same problem, how to approach this?

**Comment by julles** [comment]
same issue here
