### ISSUE TITLE
使用Laravel_excel 3导出不过滤数据

### ISSUE THREAD

**Issue by manren** [z-song/laravel-admin#3425]
- Laravel Version: 5.6
- PHP Version:7.2
- Laravel-admin: 6.1.15

### Description:
以这种方式导出，数据关联正常，当Grid有条件的时候，还是导出全部，不知道该怎么处理，我看getQuery里面好像没有去处理Filter的条件
```php
class EvaluateExporter extends ExcelExporter implements WithMapping
{
    protected $fileName = '评价表.xlsx';

    protected $columns = [
        'order_id' => '订单号',
        'score' => '评分',
        'order.takeDriver.name' => '取车司机',
        'order.returnDriver.name' => '还车司机',
        'created_at' => '评价时间',
        'content' => '评价内容'
    ];

    public function map($row): array
    {
        return [
            $row->order_id,
            Evaluate::EVALUATE_SCORE[$row->score],
            data_get($row, 'order.takeDriver.name'),
            data_get($row, 'order.returnDriver.name'),
            $row->created_at,
            $row->content
        ];
    }
}
```

**Comment by manren** [comment]
恩恩，多谢，由于不想改包的代码，我临时覆盖了一下getQuery方法
`public function getQuery()
    {
        $filter = $this->grid->getFilter();
        if ($scope = $filter->getCurrentScope()) {
            $scopeConditions = $scope->condition();
        } else {
            $scopeConditions = [];
        }
        $conditions = array_merge(
            $filter->conditions(),
            $scopeConditions
        );
        $model = $filter->getModel()->addConditions($conditions);
        $queryBuilder = $model->getQueryBuilder();

        // Export data of giving page number.
        if ($this->page) {
            $keyName = $this->grid->getKeyName();
            $perPage = request($model->getPerPageName(), $model->getPerPage());

            $scope = (clone $queryBuilder)
                ->select([$keyName])
                ->setEagerLoads([])
                ->forPage($this->page, $perPage)->get();

            $queryBuilder->whereIn($keyName, $scope->pluck($keyName));
        }
        return $queryBuilder;
    }`

**Comment by uniteweiwei** [comment]
这getQuery是写在EvaluateExporter里面的么

**Comment by uniteweiwei** [comment]
写在EvaluateExporter无效果,可能是get请求吧

**Comment by winstor** [comment]
上面不能过滤列的筛选
可以参考$this->chunk（）
直接调用类自带筛选
$this->grid->applyQuery();  
就ok了
如果导出大量数据会卡，
可以参考Grid\Exporters\CsvExporter 重新定义export 方法，getHeaders方法
 protected function getHeaders()
    {
        return [
            'Content-Encoding' => 'UTF-8',
            'Content-Type' => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=UTF-8',
            'Content-Disposition' => "attachment;filename=\"{$this->fileName}.xlsx\"",
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function export()
    {
        $response = function () {
            $handle = fopen('php://output', 'w');

            //导出的CSV文件是无BOM编码UTF-8，而我们通常使用UTF-8编码格式都是有BOM的。所以添加BOM于CSV中
            fwrite($handle, chr(0xEF) . chr(0xBB) . chr(0xBF));

            fputcsv($handle, $this->headings());

            $this->chunk(function ($collection) use ($handle) {
                foreach ($collection as $row) {
                    fputcsv($handle, $this->map($row));
                }
            });
            fclose($handle);
        };

        response()->stream($response, 200, $this->getHeaders())->send();

        exit;
    }
这样就ok了
