### ISSUE TITLE
建议：是否支持列快速筛选功能

### ISSUE THREAD

**Issue by hetoo** [z-song/laravel-admin#3426]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 6.1.15

### Description:

翻了几遍文档，也没有找到列快速筛选功能，为了表达清楚，借其他系统的图解释一下

![QQ图片20190529111426](https://user-images.githubusercontent.com/7521166/58526824-f268a300-8202-11e9-8191-cb661624cd51.png)
![QQ图片20190529111434](https://user-images.githubusercontent.com/7521166/58526829-f5639380-8202-11e9-90b9-741a1c350657.png)

**Comment by newbrash** [comment]
这些都是要重写的吧

**Comment by nkjackzhang** [comment]
你这个需求用filter可以实现，不过就是麻烦点而已，要不你试试用js框架，进行页面筛选，不查后台？

**Comment by hetoo** [comment]
> 你这个需求用filter可以实现，不过就是麻烦点而已，要不你试试自己扩展一个colum，集成用js框架，进行页面筛选，不查后台？

对的，不查询数据库

**Comment by nkjackzhang** [comment]
> 
> 
> > 你这个需求用filter可以实现，不过就是麻烦点而已，要不你试试自己扩展一个colum，集成用js框架，进行页面筛选，不查后台？
> 
> 对的，不查询数据库

但是现在的页面是分页的，必然要查询数据库，最多只能在当页进行筛选。
