### ISSUE TITLE
Admin::Script('') 使用时候，报错 Array to string conversion

### ISSUE THREAD

**Issue by zuweie** [z-song/laravel-admin#3428]
- Laravel Version: 5.5.*
- PHP Version:7.0
- Laravel-admin: 1.6.15

### Description:
在使用Admin::Script("alert('hello')");时候报错 Array to string conversion

原因：
新版本的encore/laravel-admin/src/Traits/HasAsserts.php 中的Script() 函数的返回值有所变化：
```php
public static function script($script = '')
{
     if (!empty($script)) {
     return self::$script = array_merge(self::$script, (array) $script);
     }
    return view('admin::partials.script', ['script' => array_unique(self::$script)]);
}
```
新版本会返回 self::$script

旧版本：
```php
public static function script($script = '')
{
     if (!empty($script)) {
          self::$script = array_merge(self::$script, (array) $script);
          return；
     }
    return view('admin::partials.script', ['script' => array_unique(self::$script)]);
}
```
旧版本不会返回 self::$script

新版本会报错，旧版本不会报错。

### Steps To Reproduce:
在使用Admin::Script("alert('hello')");时候报错 Array to string conversion

**Comment by z-song** [comment]
不要去使用`Admin::Script("alert('hello')");`的返回结果

**Comment by zuweie** [comment]
好的
