### ISSUE TITLE
不准备加一个软删除后的restore方法吗

### ISSUE THREAD

**Issue by cevin** [z-song/laravel-admin#3429]
- Laravel Version: 5.8
- PHP Version:7.3
- Laravel-admin: 1.6

### Description:
软删除后的数据restore，绝大数的后台操作都需要。许愿加一个restore功能按钮

**Comment by nkjackzhang** [comment]
可以自己实现吧

**Comment by fplun** [comment]
> 可以自己实现吧

不能直接put请求把deleted_at 改成null吗

**Comment by cevin** [comment]
@nkjackzhang @fplun 可以自己时间没错，但是官方支持不是最好的方案吗

**Comment by never615** [comment]
你使用软删除后,数据库唯一约束还用吗?

**Comment by cevin** [comment]
@never615  他跟数据库没关系 数据库还是唯一索引生效的

**Comment by never615** [comment]
@cevin  软删除不是就表格deleted_at赋了个值吗?  
比如admin_users表,username数据库约束唯一,软删除了一个admin_test用户后,应该就无法在创建叫admin_test的用户了吧.

**Comment by nkjackzhang** [comment]
> 
> 
> @cevin 软删除不是就表格deleted_at赋了个值吗?
> 比如admin_users表,username数据库约束唯一,软删除了一个admin_test用户后,应该就无法在创建叫admin_test的用户了吧.

所以有软删除的表一般不会设置唯一索引吧

**Comment by never615** [comment]
> > @cevin 软删除不是就表格deleted_at赋了个值吗?
> > 比如admin_users表,username数据库约束唯一,软删除了一个admin_test用户后,应该就无法在创建叫admin_test的用户了吧.
> 
> 所以有软删除的表一般不会设置唯一索引吧

是,用了软删除就不能依赖数据库约束了....对于小项目来说可以依赖数据库约束还是开放更方便,不然全部都要依靠业务层代码控制了......所以我一直没用软删除...
