### ISSUE TITLE
How to save custom value

### ISSUE THREAD

**Issue by sahadatfci** [z-song/laravel-admin#3432]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6

I have a form like this
$form->text('unique_id', trans('admin.unique_id'))->rules($uniqueRule);
$form->textarea('street_address', trans('admin.street_address'));
$form->text('unit_number', trans('admin.unit_number'));

now I want to save a custom value to a field which does not come from the form like
I want to save `type = 2`

How can i save `type = 2`

**Comment by z-song** [comment]
```php
$form->hidden('type')->value(2);
```

**Comment by sahadatfci** [comment]
@z-song than this value will be in the form hidden field. But I don't wanna use hidden field. Let's say I want to store logged in user_id to a field. How can I do it?

**Comment by mendizalea** [comment]
```
$form->hidden('user_id');
	$form->saving(function (Form $form) {
		$form->user_id = Admin::user()->id;
});
```
