### ISSUE TITLE
Max rules for tags not work

### ISSUE THREAD

**Issue by hamxn** [z-song/laravel-admin#3439]
- Laravel Version: 5.8.*
- PHP Version: 7.1.3
- Laravel-admin: ^1.6

### Description:
Form->tags('test')->rules('max:100') not work
With total input tags > 100 character, form did not validate as rule.

**Comment by hamxn** [comment]
I can use rules('size:100')

**Comment by chinkiver** [comment]
you should goto select2, to see how to limit
