### ISSUE TITLE
表单里使用multiselect多对多组件，提交的时候，想插入一些附加数据，可以吗？

### ISSUE THREAD

**Issue by JeffcottLu** [z-song/laravel-admin#3442]
求使用方法；

**Comment by JeffcottLu** [comment]
比如这种的多对多组件；想在提交的同时，往关系表里，插入一个字段的对应的数据，有办法吗？

```
        $form->row(function ($row) {
            $row->width(9)->multipleSelect('categories', '产品分类')
                ->options($this->productCategory->getCurrentAppProductCategoryInfo()->pluck('category_name', 'id')->toArray())->help('请填写产品分类，可以选择多个分类');
        });

```

**Comment by nkjackzhang** [comment]
在form的saving回调里写吧，或者只能saved之后自己再插入字段了

**Comment by JeffcottLu** [comment]
看了一下调用栈；

![image](https://user-images.githubusercontent.com/8591495/58627382-aeac9100-8309-11e9-8c3e-5bee780e94a3.png)


看到了\Encore\Admin\Form::updateRelation方法里772行的

```
$relation->sync($prepared[$name]);

```

\Illuminate\Database\Eloquent\Relations\Concerns\InteractsWithPivotTable::sync

这个方法应该是laravel的多对多sync这个方法吧；
如果laravel-admin已经封装这个方法的话，应该可以使用laravel自带的sync方法，实现这个功能吧；

但是具体怎么调用，还是不太了解；

求助；

 @z-song

**Comment by JeffcottLu** [comment]
> 在form的saving回调里写吧，或者只能saved之后自己再插入字段了

还没到saving()或者saved()就报app_id不存在的错了；刚刚写到submitted()里，也取不到mutipleSelect里的数据；

**Comment by chenjiabin** [comment]
解决了吗
