### ISSUE TITLE
关于 Grid 表头扩展能力需求的建议

### ISSUE THREAD

**Issue by linkimfly** [z-song/laravel-admin#3446]
- Laravel Version: 5.5.*
- PHP Version:7.14
- Laravel-admin: 1.6.15

### Description:
> 想在表格的表头扩展一些功能，但是研究了半天没找到可扩展的地方入口。
参考了 ```sortable``` 是在```Encore\Admin\Grid\Column```中实现的，所以目前需求也是在这边改源码实现的。
另外 ```Column::extend``` 貌似只能扩展单元格，没法对表头扩展
当然也可能是我自己没有找到正确的方式 :disappointed_relieved: 还望指点
### Current effect
> 目前只能通过修改源码去实现，但总觉得这样不太好，后期升级的什么会比较麻烦，觉得最好不去动源码，想做成扩展分享出来。

常见的表头需求例如：
- 排序（官方已经实现）
- 筛选
- 表格宽度可调整
- 表头锁定
- ...
### Screenshot
<img width="342" alt="Xnip2019-06-01_06-51-38" src="https://user-images.githubusercontent.com/30326966/58738993-b28c0080-843a-11e9-80de-450eba129117.png">

### IDEA:
@z-song 想知道是否是我没找到正确的方式，如果是还希望指点一下正确的方法，如不是后期是否可以开放对表头的扩展能力呢。谢谢 :grimacing:

**Comment by hetoo** [comment]
#3426 已经给 @z-song 提过建议了

**Comment by z-song** [comment]
表头现在不支持扩展

表头筛选之前实现过一次，但是实现的不够好，就搁置了，我的想法是给字段设置了filter之后，再给表头相应字段增加一个快捷方式

如果按照 @hetoo 给的#3426里面图片的modal方式，就能复用现在的filter组件，实现起来相对简单。

如果按照你给的图片里面popover的形式来展现，就要重写前端，需要实现input/select/range/datetime/radio/checkbox等等这些东西，但是这种方式用户体验会好一些

**Comment by z-song** [comment]
表格宽度现在也可以设置
```php
$grid->column('title')->width(200);
```

**Comment by z-song** [comment]
表头锁定和列锁定这两个有尝试过，但是没找到比较好的方案

**Comment by hetoo** [comment]
> 表头现在不支持扩展
> 
> 表头筛选之前实现过一次，但是实现的不够好，就搁置了，我的想法是给字段设置了filter之后，再给表头相应字段增加一个快捷方式
> 
> 如果按照 @hetoo 给的#3426里面图片的modal方式，就能复用现在的filter组件，实现起来相对简单。
> 
> 如果按照你给的图片里面popover的形式来展现，就要重写前端，需要实现input/select/range/datetime/radio/checkbox等等这些东西，但是这种方式用户体验会好一些

截图里的方案是基于TP的一个系统的
使用方法：https://www.kancloud.cn/ming5112/dolphinphp/256390
相关代码：https://github.com/caiweiming/DolphinPHP/blob/master/application/common/builder/table/Builder.php

**Comment by terranc** [comment]
其实只要去设置th的宽度即可，下面每个td的宽度是不需要去设置的，自动会对齐，而相反仅仅设置下面td的宽度是没意义的。

**Comment by z-song** [comment]
列过滤器已实现  https://laravel-admin.org/docs/zh/model-grid-column-filter
