### ISSUE TITLE
数据表格列选择器

### ISSUE THREAD

**Issue by ChenTokikuni** [z-song/laravel-admin#3450]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
请问如何关闭右上方数据表格列选择器

### Steps To Reproduce:
![QQ截图20190602195737](https://user-images.githubusercontent.com/16290238/58760905-b91c9400-8570-11e9-886c-05a7102a8976.png)

**Comment by z-song** [comment]
```php
$grid->disableColumnSelector();
```
