### ISSUE TITLE
从列表进入编辑页显示正常，但是一刷新就会显示报错

### ISSUE THREAD

**Issue by ColgateShu** [z-song/laravel-admin#3451]
页面显示错误：
`<div class="row"><div class="col-md-12">{"message":"Method Encore\\Admin\\Form::__toString() must not throw an exception, caught Error: Call to a member function getTab() on null","code":1,"status_code":500}`

查看laravel.log：
`local.ERROR: Method Encore\Admin\Form::__toString() must not throw an exception, caught Error: Call to a member function getTab() on null {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 1): Method Encore\\Admin\\Form::__toString() must not throw an exception, caught Error: Call to a member function getTab() on null at /home/api/BirdManager/vendor/encore/laravel-admin/src/Layout/Column.php:0)`

求解，不知道动了哪里的代码，我把最近的改动还原后还是不起作用
谢谢！

**Comment by z-song** [comment]
版本多少？

先更新到最新的版本

**Comment by ColgateShu** [comment]
颜面逃........版本问题
