### ISSUE TITLE
自定义哪些字段显示，哪些不显示

### ISSUE THREAD

**Issue by luoxulx** [z-song/laravel-admin#3458]
- Laravel Version: 5.5.x
- PHP Version:7.2.18
- Laravel-admin: 1.6.x

### Description:
如下图：我想默认打开不显示‘客户状态’，想显示状态时在点开，意思就是 默认不选中 某些字段，请问有什么办法吗
![image](https://user-images.githubusercontent.com/35016570/58804614-d91d8780-8644-11e9-995d-39f814961de7.png)

**Comment by luoxulx** [comment]
我只能想出一个临时解决办法：
``` php
if (request()->get('_columns_') === null) {
    request()->offsetSet('_columns_', '默认要显示的字段');
}
```
但终究治标不治本，求解惑

**Comment by z-song** [comment]
dev-master版本已经提供了方法
```php
$grid->column('column_name')->hide();
```
更新到dev-master或者等新版版发布

**Comment by luoxulx** [comment]
ok
