### ISSUE TITLE
Laravel Excel 3.1 导出数据 重新定义字段的值

### ISSUE THREAD

**Issue by yuyulu** [z-song/laravel-admin#3459]
- Laravel Version: 5.8.19
- PHP Version:PHP/7.2.19
- Laravel-admin: 1.6.15

### Description:
比如users表有status 状态字段，0为冻结 1为激活，怎么在导出的时候将1改为激活导出，谢谢指导！

**Comment by manren** [comment]
class DriverAttenceExporter extends ExcelExporter implements WithMapping
{
    protected $fileName = '考勤.xlsx';

    protected $columns = [
        'driver_id' => '司机ID',
        'driver.name' => '名称',
        'updated_at'=>'工作时长',
        'start_time' => '上班时间',
        'end_time' => '下班时间',
        'rest_begin_1'=>'休息1',
        'rest_end_1'=>'休息结束1',
        'rest_begin_2'=>'休息2',
        'rest_end_2'=>'休息结束2'
    ];

    public function map($row): array
    {
        return [
            $row->driver_id,
            data_get($row, 'driver.name'),
            $this->getTl($row),
            $row->start_time,
            $row->end_time,
            $row->rest_begin_1,
            $row->rest_end_1,
            $row->rest_begin_2,
            $row->rest_end_2
        ];
    }


大约是这个意思

**Comment by ashuiccc** [comment]
> class DriverAttenceExporter extends ExcelExporter implements WithMapping
> {
> protected $fileName = '考勤.xlsx';
> 
> ```
> protected $columns = [
>     'driver_id' => '司机ID',
>     'driver.name' => '名称',
>     'updated_at'=>'工作时长',
>     'start_time' => '上班时间',
>     'end_time' => '下班时间',
>     'rest_begin_1'=>'休息1',
>     'rest_end_1'=>'休息结束1',
>     'rest_begin_2'=>'休息2',
>     'rest_end_2'=>'休息结束2'
> ];
> 
> public function map($row): array
> {
>     return [
>         $row->driver_id,
>         data_get($row, 'driver.name'),
>         $this->getTl($row),
>         $row->start_time,
>         $row->end_time,
>         $row->rest_begin_1,
>         $row->rest_end_1,
>         $row->rest_begin_2,
>         $row->rest_end_2
>     ];
> }
> ```
> 
> 大约是这个意思

您好 您这个是自定义的还是用的laravel-admin的,麻烦贴下完整代码,我这块有虚拟字段导出,数据库直接就报错了,麻烦了

**Comment by ashuiccc** [comment]
`namespace App\Admin\Extensions;

use Encore\Admin\Grid\Exporters\ExcelExporter;
use Maatwebsite\Excel\Concerns\WithMapping;

class RechargeOrderExporter extends ExcelExporter implements WithMapping
{

    protected $fileName = '充值订单.xlsx';

    protected $columns = [
        'sys_order_id' => '系统订单号',
        'pay_amount' => '充值金额',
        'pay_poundage' => '手续费',
        'real_amount' => '实际到账',
        'created_at' => '提交时间',
        'success_time' => '成功时间',
        'pay_status' => '订单状态',
    ];


    public function map($row): array
    {
        return [
            $row->sys_order_id,
            $row->pay_amount,
            $row->pay_poundage,
            $row->pay_amount - $row->pay_poundage,
            $row->created_at,
            $row->success_time,
            $row->pay_status == 1 ? '已支付' : '未支付',
        ];
    }
}`

**Comment by ashuiccc** [comment]
上面是我需要导出的数据,会报real_amount不存在,想知道虚拟字段如何设置

**Comment by manren** [comment]
> 上面是我需要导出的数据,会报real_amount不存在,想知道虚拟字段如何设置

`namespace App\Admin\Extensions;

use Encore\Admin\Grid\Exporters\ExcelExporter;
use Maatwebsite\Excel\Concerns\WithMapping;

class RechargeOrderExporter extends ExcelExporter implements WithMapping
{

protected $fileName = '充值订单.xlsx';

protected $columns = [
    'sys_order_id' => '系统订单号',
    'pay_amount' => '充值金额',
    'pay_poundage' => '手续费',
    'updated_at' => '实际到账',
    'created_at' => '提交时间',
    'success_time' => '成功时间',
    'pay_status' => '订单状态',
];


public function map($row): array
{
    return [
        $row->sys_order_id,
        $row->pay_amount,
        $row->pay_poundage,
        $row->pay_amount - $row->pay_poundage,
        $row->created_at,
        $row->success_time,
        $row->pay_status == 1 ? '已支付' : '未支付',
    ];
}
}`

随便写一个字段就行，或是你试试重复的字段应该也没事

**Comment by fan153693** [comment]
@manren 
![image](https://user-images.githubusercontent.com/7405726/62182347-e2974780-b388-11e9-8303-5f949bf9349a.png)
如果只展示实际到账字段，该怎么弄？
protected $columns = [
        'sys_order_id' => '系统订单号',
        'updated_at' => '实际到账',
        'created_at' => '提交时间',
        'success_time' => '成功时间',
        'pay_status' => '订单状态',
    ];
我改成这样，实际到账就没有值了

**Comment by ashuiccc** [comment]
@manren  你要继承我上面那几个类+接口

**Comment by ashuiccc** [comment]
`use Encore\Admin\Grid\Exporters\ExcelExporter;
use Maatwebsite\Excel\Concerns\WithMapping;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;

class RechargeOrderExporter extends ExcelExporter implements WithMapping, ShouldAutoSize`

<img width="1010" alt="QQ20190731-171922@2x" src="https://user-images.githubusercontent.com/50192266/62200128-5e0fed80-b3b7-11e9-825c-97a32219eae7.png">
