### ISSUE TITLE
Where can I find SortableTrait code?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#346]
http://120.26.143.106/admin/demo/articles

**Comment by z-song** [comment]
Google `Spatie\EloquentSortable` and you'll find it

**Comment by smuzammilali** [comment]
Thanks it works but have one issue:
return Admin::grid(Page::class, function (Grid $grid) {
            $grid->model()->with('user')->where('user_id',Auth::guard('admin')->user()->id);
            $grid->model()->ordered();
             ...
Sorting works fine but it sorts all pages with different users, where I would like to sort only pages which are current users pages.

Is there anyway I can fix the problem?

**Comment by smuzammilali** [comment]
Is there any solution for this problem? 
Also does orderable() supports in 1.4.*
