### ISSUE TITLE
项目中require dingo/api 后，admin登录后的页面报错

### ISSUE THREAD

**Issue by Jeremy198532** [z-song/laravel-admin#3460]
- Laravel Version: 5.8.19
- PHP Version: 7.8.8
- Laravel-admin: 1.6.15
- dingo/api: 2.2.3

### Description:
项目中require dingo/api 后，admin登录后的页面报错"sha1() expects parameter 1 to be string, object given"，原因为 encore/laravel-admin/src/Layout/Content.php 中缺少 __toString() 方法。临时添加 public function __toString() { return $this->render(); } 页面正常可以显示了。

### Steps To Reproduce:

**Comment by ruoge3s** [comment]
.env中
```
APP_URL=http://www.domain.com
API_DOMAIN=api.domain.com
```
他就不报这个问题了，但是需要两个域名，让人很尴尬

**Comment by mini443** [comment]
> .env中
> 
> ```
> APP_URL=http://www.domain.com
> API_DOMAIN=api.domain.com
> ```
> 
> 他就不报这个问题了，但是需要两个域名，让人很尴尬

我也遇到了这个问题，多亏看到了你的回答

**Comment by 191834552** [comment]
我这加了API_DOMAIN 不好使啊

**Comment by 191834552** [comment]
> .env中
> 
> ```
> APP_URL=http://www.domain.com
> API_DOMAIN=api.domain.com
> ```
> 
> 他就不报这个问题了，但是需要两个域名，让人很尴尬

可以设置为null，也可以的

**Comment by 191834552** [comment]
> 我这加了API_DOMAIN 不好使啊

解决了，一开始没生效是由于，docker 设置的环境变量 API_DOMAIN 和config/api.php env('API_DOMAIN') 冲突，并且在项目代码中无法覆盖。API_DOMAIN和后台域名一致导致前后台混淆，后台的视图也走了dingo/api接口的逻辑！
