### ISSUE TITLE
如何才能额外生成缩略图

### ISSUE THREAD

**Issue by wannabing** [z-song/laravel-admin#3462]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6.5

### Description:
在没有使用图片第三方云存储的情况下，上传图片都是原图，而使用了intervention/image插件进行生成缩略图之后原图又丢失了，如何才能生成两张图，一张原图用于显示在详情页，缩略图显示在列表页。

**Comment by SoulMate94** [comment]
更新到Laravel-Admin 1.7.2
https://laravel-admin.org/docs/zh/model-form-fields
自带上传缩略图
