### ISSUE TITLE
$form->hasMany中的unique rule报错

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3471]
- Laravel-admin: #.#.#

### Description:
当在$form->hasMany中的字段的rule中设置了判断是否重复的规则事，提交会报错。
```
$form->select('channel', '支付渠道')->options($channels)->config('allowClear', false)->rules(function($form) {
    return [
         'required', Rule::unique('merchant_charges_configs')->ignore($id)
     ];
});
```

# Error:

![image](https://user-images.githubusercontent.com/224353/58967071-05243e80-87e6-11e9-9084-e6e9caea7b57.png)

**Comment by uacode** [comment]
Try this https://laravel-admin.org/docs/#/en/model-form-validation?id=database-unique-check

```
$form->text('username')
     ->creationRules(['required', "unique:user_table"])
     ->updateRules(['required', "unique:user_table,username,{{id}}"]);
```

**Comment by terranc** [comment]
Thanks for the tip, but it still doesn't solve

**Comment by uacode** [comment]
In table merchant_charges_configs primary key is id ?

You should pass id
$form->select('channel', '支付渠道')->options($channels)->config('allowClear', false)->rules(function($form) **use($id)** {

**Comment by terranc** [comment]
yes, is id. I passed id.

It looks like the query has syntax problems.
![image](https://user-images.githubusercontent.com/224353/60265814-342b5d00-9919-11e9-9d00-5955cab0ee61.png)
