### ISSUE TITLE
admin的中间件是在哪里注册的

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3472]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

![image](https://user-images.githubusercontent.com/40032190/59004125-397e1600-884b-11e9-80be-123722bf02c0.png)
如上图的admin组件是个中间件组吧，我在kenel并没有看到注册相关的中间件
![image](https://user-images.githubusercontent.com/40032190/59004170-5dd9f280-884b-11e9-8839-f0bbba508682.png)

**Comment by lixiansheng123** [comment]
我也想知道

**Comment by lixiansheng123** [comment]
我也想知道,楼主知道了吗

**Comment by wonbin2011** [comment]
为什么没有回答就关了呢

**Comment by yuange** [comment]
vendor/encore/laravel-admin/src/AdminServiceProvider.php
