### ISSUE TITLE
调用$grid->actions(...);这个方法报method undifined错误

### ISSUE THREAD

**Issue by fsf11080612** [z-song/laravel-admin#348]
$grid->actions(function ($actions) {

    // append一个操作
    $actions->append('<a href=""><i class="fa fa-eye"></i></a>');

    // prepend一个操作
    $actions->prepend('<a href=""><i class="fa fa-paper-plane"></i></a>');
}

调用上面的方法报method undifined错误，看了grid类的源代码，发现grid类里面没有定义actions方法

**Comment by z-song** [comment]
你的版本？

**Comment by fsf11080612** [comment]
我的laravel版本是5.1

**Comment by z-song** [comment]
5.1版本对应的laravel-admin已经没时间维护了，很多功能跟不上

建议升级到5.3

**Comment by fsf11080612** [comment]
好的，谢谢
