### ISSUE TITLE
table表格，表头含小数点‘.’时，被隐藏

### ISSUE THREAD

**Issue by luoxulx** [z-song/laravel-admin#3482]
- Laravel Version: 5.5.x
- PHP Version:7.2.18
- Laravel-admin: 1.6.x

### Description:
如下图：
![image](https://user-images.githubusercontent.com/35016570/59166665-91c05b00-8b5e-11e9-8e27-6e3855dbbcbf.png)
![image](https://user-images.githubusercontent.com/35016570/59166673-a6045800-8b5e-11e9-97d5-653ee01a685f.png)

**Comment by luoxulx** [comment]
@z-song ,请问表头可以有小数点吗？

**Comment by z-song** [comment]
重现不了你的问题，建议更新版本

**Comment by luoxulx** [comment]
1.7.0版本正常，谢谢
