### ISSUE TITLE
laravel-admin是如何将Content对象解析成html界面的

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3485]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6

### Description:
![image](https://user-images.githubusercontent.com/40032190/59178409-7c185900-8b91-11e9-903b-207575b7611c.png)
Content对象只有一些数据的基本属性，这些基本属性是在哪里解析成html，分别调用了哪些接口呢

**Comment by newbrash** [comment]
布鲁布鲁 2019/6/10 15:39:19
我的看法是，中间件有一步渲染主界面，主界面有php标签或者js根据返回的对象寻找api获取数据展示，不知道这样想对不对呢？老哥们

**Comment by z-song** [comment]
不是laravel-admin将Content渲染为html输出，这是Laravel的行为，Content实现了Renderable接口

控制器action返回实现了Renderable的对象实例时，会调用对象中的render方法，输出渲染结果
