### ISSUE TITLE
在 form 的 hasmany 使用 rules('required') 出问题，右上角的刷新按钮报错

### ISSUE THREAD

**Issue by weasiser** [z-song/laravel-admin#3487]
- Laravel Version: 5.8.*
- PHP Version:
- Laravel-admin: 1.7.1

### Description:
![image](https://user-images.githubusercontent.com/28592681/59183979-b8eb4c80-8b9f-11e9-96ae-953e4c41009e.png)
![image](https://user-images.githubusercontent.com/28592681/59184056-dae4cf00-8b9f-11e9-92d3-4f8a67391a7d.png)
用 `$form->hasMany()->mode('table')` 时，如果某一个字段设置了 `rules('required')` ，就会出现多一个 label ，配合 [ichynul/row-table](https://github.com/ichynul/row-table) 使用时也会多一个 label ，不使用 `rules('required')` 的时候就没问题。

还有点击右上角的刷新按钮控制台报错：
![image](https://user-images.githubusercontent.com/28592681/59184650-29469d80-8ba1-11e9-913c-3f662320469c.png)

**Comment by weasiser** [comment]
上面那个`->rules('required')`替换成`->required()`就可以了。

**Comment by minosss** [comment]
`$.admin.reload is not a function` 是因为资源没更新

**Comment by weasiser** [comment]
@minosss 谢谢提醒

// 强制发布静态资源文件
`php artisan vendor:publish --tag=laravel-admin-assets --force`

// 清理视图缓存
`php artisan view:clear`

**Comment by maojindao55** [comment]
> `php artisan vendor:publish --tag=laravel-admin-assets --force`

更新了依旧报错 $.admin.reload is not a function

**Comment by itanea** [comment]
> @minosss 谢谢提醒
> 
> // 强制发布静态资源文件
> `php artisan vendor:publish --tag=laravel-admin-assets --force`
> 
> // 清理视图缓存
> `php artisan view:clear`

Unfortunately, this doesn't work. Error is always here.
