### ISSUE TITLE
如何通过zh-CN.json控制label进行翻译

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3488]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: 1.6

### Description:
![image](https://user-images.githubusercontent.com/40032190/59186662-07034e80-8ba6-11e9-8925-7814caab0914.png)
通过zh-CN.json控制label进行翻译

**Comment by z-song** [comment]
最新发布的v1.7.*版本之后，用admin:make会生成上图的代码，用column方法的原因是为了IDE友好
