### ISSUE TITLE
关于 http_path 指定请求方法判断权限错误的问题

### ISSUE THREAD

**Issue by wojianishanghaojiugoujia** [z-song/laravel-admin#3491]
- Laravel Version: 5.8.21
- PHP Version: PHP/7.1.23
 Laravel-admin: 1.7.0

### Description:
你好，
在创建权限的时候，`http_path` 字段可以在行内指定请求的方法（虽然文档中没看到有相关的用法，看了代码发现支持这样的写法）：
![image](https://user-images.githubusercontent.com/17558843/59213617-e2c86180-8be7-11e9-9b22-66e5e7bff1d4.png)
在列表上也正常解析了
![image](https://user-images.githubusercontent.com/17558843/59213670-fecc0300-8be7-11e9-8b78-c259a395d9c1.png)
但是在权限校验的时候，总是提示无权访问。
在 `Encore\Admin\Auth\Database\Permission::shouldPassThrough`中把 `$matches` 打印出来发现
![image](https://user-images.githubusercontent.com/17558843/59213826-608c6d00-8be8-11e9-9bf9-f1a5f1c99f22.png)
拼接`config('admin.route.prefix')` 在解析`method`之前了。

### 我的解决方案
![image](https://user-images.githubusercontent.com/17558843/59214098-f32d0c00-8be8-11e9-80fb-bfb641d1d5a6.png)

**Comment by 354651432** [comment]
是的 很牛逼的一段逻辑，可惜字符串拼错了

**Comment by BuiltTo1ast** [comment]
今天也发现这个问题，作者应该考虑修改一下。为啥issue被关闭了
