### ISSUE TITLE
$form->table

### ISSUE THREAD

**Issue by popfaker** [z-song/laravel-admin#3497]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: v1.7.0

### Description:
$form->table()插入的数据，在编辑页面新增元素，之前添加的被删除。如图：
![image](https://user-images.githubusercontent.com/38718383/59262840-95450680-8c72-11e9-978b-6317b08dc36c.png)

![image](https://user-images.githubusercontent.com/38718383/59262876-aa219a00-8c72-11e9-9c96-3a59ef476037.png)

**Comment by z-song** [comment]
操作步骤？

**Comment by popfaker** [comment]
> 操作步骤？

抱歉，没说清楚。
**重现步骤**
1.form中使用table，$form->table()
2.进入添加页面，点击table中的新增按钮，新增3条数据，录入任意数据，点击保存按钮，正常提交表单，保存成功。
3.进入该条记录的编辑页面，table中再次点击新增按钮，新增3条数据，填入任意数据，点击保存按钮，提交表单，保存成功

**预期结果**
table中出现6条数据

**实际结果**
table只有3条数据，只剩下在编辑页面新增的table数据

> 初步分析
table组件继承的是hasmany组件，在hasmany组件的js中，每次点击新增按钮，都是从new_1开始，所以在编辑页面，造成之前保存的new_1被覆盖。
如图：
![image](https://user-images.githubusercontent.com/38718383/59276540-13b0a100-8c91-11e9-9671-46afb877e08d.png)

希望大佬再次分析

**Comment by minosss** [comment]
正常操作正常保存貌似没事。

当~  保存的时候出现错误保存不了，刷新提示错误
input 的 name 属性 本来是 new_1/2/3 全部变成 new___LA_KEY__

laravel-admin 1.7.1
laravel 5.8.21

**Comment by z-song** [comment]
重现不了你的问题

**Comment by minosss** [comment]
我说的是 保存的时候如果数据库保存失败，pjax刷新提示错误，table > tr 的 defaultKey 没有替换，还是默认的 `__LA_KEY__`

1. 数据库迁移中某个字段必填
2. table 新建几行数据，填入数据，上面必填那个字段留空，保存（失败）

原本应该是
![image](https://user-images.githubusercontent.com/1515069/59317521-d92d1f80-8cf5-11e9-8078-d1a86b3378bb.png)

结果是
![image](https://user-images.githubusercontent.com/1515069/59317444-7cca0000-8cf5-11e9-90b5-aa2903d2a4de.png)

**Comment by z-song** [comment]
> > 操作步骤？
> 
> 抱歉，没说清楚。
> **重现步骤**
> 1.form中使用table，$form->table()
> 2.进入添加页面，点击table中的新增按钮，新增3条数据，录入任意数据，点击保存按钮，正常提交表单，保存成功。
> 3.进入该条记录的编辑页面，table中再次点击新增按钮，新增3条数据，填入任意数据，点击保存按钮，提交表单，保存成功
> 
> **预期结果**
> table中出现6条数据
> 
> **实际结果**
> table只有3条数据，只剩下在编辑页面新增的table数据
> 
> > 初步分析
> > table组件继承的是hasmany组件，在hasmany组件的js中，每次点击新增按钮，都是从new_1开始，所以在编辑页面，造成之前保存的new_1被覆盖。
> > 如图：
> > ![image](https://user-images.githubusercontent.com/38718383/59276540-13b0a100-8c91-11e9-9671-46afb877e08d.png)
> 
> 希望大佬再次分析

按照你的步骤，重现不了问题

**Comment by popfaker** [comment]
> 重现不了你的问题

我做了一张图，如下：

![gif](https://user-images.githubusercontent.com/38718383/59318869-2eb7fb00-8cfb-11e9-9432-5062ef5ace21.gif)

> 分析
hasmany的新增js有问题，每次点击table中的新增按钮，都是从new_1开始，所以造成之前已保存过的new_1被覆盖。  

> 初步解决
将key值每次都重置一个值
![image](https://user-images.githubusercontent.com/38718383/59319017-c9b0d500-8cfb-11e9-8c5b-e41355b28d91.png)

**Comment by z-song** [comment]
文档中的下面这一步写了吗？

同时在模型里面给这个字段增加访问器和修改器:

```php

    public function getExtraAttribute($extra)
    {
        return array_values(json_decode($extra, true) ?: []);
    }

    public function setExtraAttribute($extra)
    {
        $this->attributes['extra'] = json_encode(array_values($extra));
    }

```

**Comment by popfaker** [comment]
> 文档中的下面这一步写了吗？
抱歉大佬，文档中看到过，我以为仅是转换数组的，所以只在模型中设置了protected $casts属性。


没有仔细看文档，浪费大佬时间了，十分抱歉。
