### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by kusnet** [z-song/laravel-admin#35]
安装报错：
[root@iZ23m2zt6hsZ laravel-admin]# composer require encore/laravel-admin "dev-master"
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package encore/laravel-admin No version set (parsed as 1.0.0) is satisfiable by encore/laravel-admin[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

Installation failed, reverting ./composer.json to its original content.

**Comment by z-song** [comment]
在composer.json中设置minimum-stability为dev可以解决这个问题

`"minimum-stability": "dev"`

**Comment by rdtandel** [comment]
> 
> 
> 在composer.json中设置minimum-stability为dev可以解决这个问题
> 
> `"minimum-stability": "dev"`

still got this issue
