### ISSUE TITLE
php artisan route:list not working?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#350]
![2017-01-24_1130](https://cloud.githubusercontent.com/assets/24757934/22256415/a50b71ea-e228-11e6-9d35-3ca5d331bc07.png)

Possible solution:
https://github.com/mrakodol/Laravel-5-Bootstrap-3-Starter-Site/pull/65/commits/2ba2d7d8f708771e38e9d9e8d87640a4d49a23f8

**Comment by z-song** [comment]
I think this issue has nothing to do with laravel-admin.
