### ISSUE TITLE
升级到1.7.1版本后,右上角刷新按钮点击js报错

### ISSUE THREAD

**Issue by maojindao55** [z-song/laravel-admin#3501]
- Laravel Version:5.7
- PHP Version:7.15
- Laravel-admin: 1.7.1

### Description:
list:1121 Uncaught TypeError: $.admin.reload is not a function

前提是已经按照升级注意事项更新了并且提示成功

```
// 强制发布静态资源文件
php artisan vendor:publish --tag=laravel-admin-assets --force

// 强制发布语言包文件
php artisan vendor:publish --tag=laravel-admin-lang --force

// 清理视图缓存
php artisan view:clear
```

**Comment by z-song** [comment]
清理浏览器缓存

或者建议用admin:minify命令压缩静态文件

**Comment by maojindao55** [comment]
> 清理浏览器缓存
> 
> 或者建议用admin:minify命令压缩静态文件

通过清理缓存解决谢谢

**Comment by phpfengxi** [comment]
清理缓存解决+1

**Comment by phpfengxi** [comment]
希望告知原因

**Comment by itanea** [comment]
Unfortunately, this doesn't work. Error is always here.
