### ISSUE TITLE
1.7之后filter里的select变成浏览器自带下拉框了

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3505]
- Laravel-admin: 1.7

### Description:
![image](https://user-images.githubusercontent.com/224353/59323032-82cadb80-8d0b-11e9-8019-89094c7e180a.png)

之前是用jquery select的，是bug还是特意为之？在对待默认值等细节的处理上有些差异

**Comment by z-song** [comment]
是个bug  已经修复  e7f9d1f1d087c17dd04b839a3c229f09042783c0
