### ISSUE TITLE
grid中editable更新无效

### ISSUE THREAD

**Issue by leo-yi** [z-song/laravel-admin#3509]
- Laravel Version: 5.8
- PHP Version: 7.2
- Laravel-admin: 1.7.1

### Description:
接口返回200，更新成功 !， 但是数据库里并没有更新到数据

**Comment by popfaker** [comment]
这个应该跟你form定义的有关系，editable 调用的也是update()方法，检查你的form方法组件设置

**Comment by leo-yi** [comment]
> 这个应该跟你form定义的有关系，editable 调用的也是update()方法，检查你的form方法组件设置

确实，需要form定义这个字段，光grid中有定义不行，感谢！
