### ISSUE TITLE
[HELP] How to create row expander with ajax loaded content

### ISSUE THREAD

**Issue by serzhiio** [z-song/laravel-admin#351]

**Comment by z-song** [comment]
In this [demo](http://120.26.143.106/admin/demo/users)，find `Admin/Extensions/Column/ExpandRow.php` under `Column extension` tab,  check the code and you will know how to show content load by ajax

**Comment by serzhiio** [comment]
Sorry, but I don't see where is the ajax request for expanded row content (I mean ajax req after grid is rendered)? And now I see only that both main rows and expanded are loaded at grid render.

It would be great to create such functionality this way:
`           $grid->column('expand')->expand(function () {
                $profile = array_only($profile, ['homepage', 'gender', 'birthday', 'address', 'last_login_at', 'last_login_ip', 'lat', 'lng']);
                return new Table([], $profile);
            }, 'Profile', '/admin/profile/get', 50);`
After all rows rendered and expand button clicked ajax request (generated automatically for '/admin/profile/get/50' path) should be executed and response data rendered into expanded row.

**Comment by z-song** [comment]
It's a custom column extension, but not builtin functionality.

For your needs, you need to change the javascript code inside display method of class `ExpandRow`. 

In the demo， content load with code `var html = $('template.grid-expand-'+key).html();`

If you want load by ajax request, you can write code like this：
```php
 public function display($api, $num)
{
    ...
    // javascript

current_row.click(function () {
    $.get($api, {num: $num}, function (data) {
        // append data to current row
        current_row.after(data)
    });
});
    ...
} 
```
use extension in grid:
```php
$grid->column('Profile')->expand('/admin/profile/get', 50);
```
