### ISSUE TITLE
form hasMany 中 multipleImage 图片显示

### ISSUE THREAD

**Issue by Mrlaozhou** [z-song/laravel-admin#3510]
- Laravel Version: 5.8
- PHP Version: 7.2
- Laravel-admin: 1.6

### Description:
```
$form->hasMany('opus', __('Opus'),function (NestedForm $nestedForm) {
            $nestedForm->text('title', '作品名称')->rules('required');
            //  TODO 图片显示重复
            $nestedForm->multipleImage('works', '作品')->removable();
            $nestedForm->date('at', '创作时间')->rules('required');
            $nestedForm->hidden('role', '角色')->default($role);
            $nestedForm->text('in', '创作地址');
            $nestedForm->textarea('desc', '描述');
        });
```
第一条数据图片显示正常， 之后的都跟第一条一样
![1560335795596](https://user-images.githubusercontent.com/24409981/59344632-123eb180-8d41-11e9-803a-e034c2dde906.jpg)

**Comment by Mrlaozhou** [comment]
@z-song

**Comment by Yesr00** [comment]
参照 https://github.com/z-song/laravel-admin/pull/2425/commits/ca884d4deefdf53aa783ccf40407ccf6d5344267
我查了下源码是src/Form/NestedForm.php这个文件的代码没有合并到好像。对应的两行把$key加上就好了。
