### ISSUE TITLE
Refresh button not working.

### ISSUE THREAD

**Issue by Spit-Biagio** [z-song/laravel-admin#3511]
- Laravel Version: 5.8.#
- PHP Version: 7.3.6
- Laravel-admin: 1.7.0

### Description:
i have update to latest version, and the new button to refresh page not working return an error in javascript:

![js](https://user-images.githubusercontent.com/47725236/59373013-07881a80-8d49-11e9-8cf7-12f573ba27b6.PNG)

afterwards I  have another request, that is to UPDATE font awesome to latest version 5, i have already edited your files 5 times for the changes, and since is stressful always edit file...

**Comment by gweecl** [comment]
You have update the assets:
https://laravel-admin.org/docs/#/en/updating?id=precautions

```
/ / Force to publish release assets files
Php artisan vendor:publish --tag=laravel-admin-assets --force
```

**Comment by zeroiszero** [comment]
You have update the assets:
https://laravel-admin.org/docs/#/en/updating?id=precautions

```
/ / Force to publish release assets files
Php artisan vendor:publish --tag=laravel-admin-assets --force
```

**Comment by Spit-Biagio** [comment]
thanks for the help, and yes, i have executed the command, I had forgotten this passage.

and, have you some notice about font-awesome 5?

Thanks.
