### ISSUE TITLE
hasMany使用table 无法保存table的值

### ISSUE THREAD

**Issue by guandeng** [z-song/laravel-admin#3513]
- Laravel Version: #.#.#
- PHP Version:7.2
- Laravel-admin: 1.7.1

### Description:
 
<img width="799" alt="WX20190613-105554@2x" src="https://user-images.githubusercontent.com/7838221/59400542-50cc7e80-8dca-11e9-9c20-b66457aeb56c.png">
<img width="683" alt="WX20190613-105640@2x" src="https://user-images.githubusercontent.com/7838221/59400559-5de96d80-8dca-11e9-8d3e-21ad10b45d75.png">
extra不应该在sku下吗 
sku[71][extra]

**Comment by bohehe** [comment]
我也碰到同样问题
我使用$form->table时，编辑原先的表单，新增的值会覆盖原先的值，没法保存table所有行的值

**Comment by guandeng** [comment]
> 我也碰到同样问题
> 我使用$form->table时，编辑原先的表单，新增的值会覆盖原先的值，没法保存table所有行的值

恩恩 js这块写的不太好

**Comment by EricRun** [comment]
> 我也碰到同样问题
> 我使用$form->table时，编辑原先的表单，新增的值会覆盖原先的值，没法保存table所有行的值

这个问题解决了没？
