### ISSUE TITLE
关联文件表，删除不了文件

### ISSUE THREAD

**Issue by wendaomumao** [z-song/laravel-admin#3515]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
表单一对多 (文件路径表)  主表删除，附表也删除后（通过boot删除） 文件没删除。请问还要自己在boot里面写删除文件逻辑吗？还是内置有，只是我不知道

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/32691629/59411921-f1349a00-8dee-11e9-8e7b-b662fddc119c.png)

**Comment by z-song** [comment]
关联表的文件需自行删除
