### ISSUE TITLE
switch开关选择无法正常修改(已提供解决方案)

### ISSUE THREAD

**Issue by bugcat** [z-song/laravel-admin#3518]
### Description:
当$grid使用switch方法时，即使有相关配置：
```
$states = [
        'on'  => ['value' => 1, 'text' => 'ON', 'color' => 'primary'],
        'off' => ['value' => 0, 'text' => 'OFF', 'color' => 'default'],
];
```
但也无法正常修改，纠其原因，是即使这里定义了value的值，但在提交表单的时候并未使用该值，而是使用了固定值on和off。

### 解决办法:
https://github.com/z-song/laravel-admin/blob/8c64c3cd97e5f547b3641e335c7faa201ee31b2d/src/Grid/Displayers/SwitchDisplay.php#L49
https://github.com/z-song/laravel-admin/blob/8c64c3cd97e5f547b3641e335c7faa201ee31b2d/src/Grid/Displayers/SwitchGroup.php#L63
相同的代码：
`$(this).val(state ? 'on' : 'off');`
修改为：
```
$(this).val(
    state 
    ? '{$this->states["on"]["value"]}' 
    : '{$this->states["off"]["value"]}'
);
```
即可

**Comment by vic091** [comment]
laravel 导入最新的包，还是有这个问题
encore/laravel-admin 
这个问题解决了没有
