### ISSUE TITLE
Security: Manually edit URL and update record? 

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#352]
Can't we use POST method for such editing?

It's insecure to use GET method for editing purpose:
http://120.26.143.106/admin/demo/users/18/edit

Can't we just use:
http://120.26.143.106/admin/demo/users/edit 

So the user only permissible to edit record which are visible in Grid.

**Comment by z-song** [comment]
I don't really know what you mean，the restful url is based on Laravel's `resource route`.

When editing a record in database, you must specify a resource id first,  otherwise you don't know which record to edit.

**Comment by smuzammilali** [comment]
For example if Users have many Pages relation.

And page are loaded by logged in users:

User 1 has only 1 Page with id 4
http://zadmin/admin/user/pages/4/edit

What if user manually change the url to:
http://zadmin/admin/user/pages/1/edit

And edit other users pages how can we prevent this happening?

**Comment by z-song** [comment]
try add following code to edit method in your controller.
```php
public function edit($id)
{
    if (Admin::user() don't have page $id) {
        throw new Exception('permission denied!');
    }
}
```
