### ISSUE TITLE
批量操作js报错 selectedRows is not defined

### ISSUE THREAD

**Issue by zeyingli** [z-song/laravel-admin#3521]
- Laravel Version: 5.7
- PHP Version: 7.3
- Laravel-admin: 1.7.0

### Description:
更新版本至1.7.0后发现无法进行批量操作，js报错提示selectedRows is not defined

```
Uncaught ReferenceError: selectedRows is not defined
    at HTMLAnchorElement.eval (eval at globalEval (jQuery-2.1.4.min.js:2), <anonymous>:162:18)
    at HTMLAnchorElement.dispatch (jQuery-2.1.4.min.js:3)
    at HTMLAnchorElement.r.handle (jQuery-2.1.4.min.js:3)
```

同样问题发生在demo.laraval-admin.org网站内
![屏幕快照 2019-06-13 下午11 25 32](https://user-images.githubusercontent.com/18704595/59487856-beac9080-8e32-11e9-9572-8645854553a6.png)

### Steps To Reproduce:
1. 随机勾选一行数据
2. 点击Action里的Batch Delete
3. 控制台报错

已知相关联问题:
#1995

**Comment by swustyc** [comment]
我从laravel-admin 1.6.15 升级到 1.7.0 也出现了这个问题，目前通过替换 selectedRows 为 $.admin.grid.selected() 可以解决。

**Comment by ashuiccc** [comment]
我也是 而且批量操作上面显示的是admin.grid_items_selected

**Comment by swustyc** [comment]
替换 ids: selectedRows(), 为 ids: $.admin.grid.selected(),
但是，最近发现第一次批量操作，选择了3个，操作结束后，第二次选择2个，然而上面显示的数量却为5个

**Comment by chinkiver** [comment]
> 我也是 而且批量操作上面显示的是admin.grid_items_selected

你是因为语言文件没有替换

**Comment by chinkiver** [comment]
> $.admin.grid.selected(),

感觉没有被初始化，会留存上次的数据

**Comment by z-song** [comment]
> 替换 ids: selectedRows(), 为 ids: $.admin.grid.selected(),
> 但是，最近发现第一次批量操作，选择了3个，操作结束后，第二次选择2个，然而上面显示的数量却为5个

已经提交了修复，等下个版本发布

**Comment by jeff-forest** [comment]
After changed to $.admin.grid.selected() 
tested OK with Version 1.7.2
