### ISSUE TITLE
改进下用户权限部分

### ISSUE THREAD

**Issue by webphper** [z-song/laravel-admin#3523]
- Laravel Version:5.7 #.#.#
- PHP Version:7.2
- Laravel-admin:1.7 #.#.#

### Description:
是否可以将角色，用户，权限部分也放开进行一定程度的重写，现在有个需求想在角色上关联实现数据权限的功能

**Comment by never615** [comment]
config admin.database 中角色权限等的model可以修改,然后你可以写角色权限的控制器,重写路由覆盖原库. 我就是这么改的,只实现这个功能完全不需要改源码. 可以参考:https://github.com/never615/laravel-admin-enhance
