### ISSUE TITLE
关联字段列展开expand错误，展开显示undefined

### ISSUE THREAD

**Issue by shanjiechen** [z-song/laravel-admin#3528]
- Laravel Version: 5.8
- PHP Version:7.3
- Laravel-admin: 1.7.0

### Description:
如果是关联模型的列使用了expand，如 `$grid->item()->name('项目名称')->expand(function($model) { return $html; })` 点击展开后会看到undefined字样，看不到本应有的html。

目测原因是，关联字段的"column name" 中含有小数点. ，导致jQuery选择器不能正确定位template元素， 将 `Encore\Admin\Grid\Displayers\Expand`  line 17 修改为  `$key = str_replace('.', '-', $this->column->getName()).'-'.$this->getKey();` 可以解决问题。

**Comment by phpcxy** [comment]
同样遇到这个问题

**Comment by Gethin0321** [comment]
@z-song

**Comment by vgocoder** [comment]
不能提一个PR吗?
