### ISSUE TITLE
WangEditor Blade Template Is Missing?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#353]
http://120.26.143.106/admin/editors

protected $view = 'admin.wang-editor';

**Comment by z-song** [comment]
`WangEditor` is created by chinese, and no English documents, so I write a example to show you how to  [Integrate CKEditor](https://github.com/z-song/laravel-admin/blob/master/docs/en/field-management.md#integrate-ckeditor).

I think it may help.

**Comment by smuzammilali** [comment]
Never mind I have used TinyMCE editor with https://github.com/UniSharp/laravel-filemanager/ Filemanager.

Just one question:

- How to prevent loading default CKEditor CDN?

**Comment by z-song** [comment]
@smuzammilali https://github.com/z-song/laravel-admin/blob/master/docs/en/field-management.md#remove-field

**Comment by llxx-lord-xxll** [comment]
https://ace.c9.io/

This seemed best editor so far for me. Has all the things i need. Supports laravel blade too.

![image](https://user-images.githubusercontent.com/6489365/39594065-6f6f1fd2-4f2d-11e8-9585-8918004e7662.png)
