### ISSUE TITLE
多图上传的问题，需要每张图片生成一条数据

### ISSUE THREAD

**Issue by guyaofei** [z-song/laravel-admin#3531]
上传多张图片，每张图片生成一条数据，添加成功后获取到每张图片的ID，添加到另一张表中，图片的路径需要自定义

**Comment by guyaofei** [comment]
还有个问题，有办法点击提交按钮之后，在数据库里不生成数据吗。ignore可以忽略不添加的字段，但是数据库里面还是会添加一条空的数据

**Comment by guyaofei** [comment]
@z-song 大神，帮忙看一下

**Comment by sofwu** [comment]
+1
