### ISSUE TITLE
form表单中select组件如何联动更新？

### ISSUE THREAD

**Issue by aBusyAnt** [z-song/laravel-admin#3533]
有一个form表单中的$form->product 是select组件，还有3个字段是显示product的信息，product改变的时候，这3个字段的信息也跟着更新，如何实现？

**Comment by dengxit** [comment]
<img width="845" alt="屏幕快照 2019-06-19 下午11 13 54" src="https://user-images.githubusercontent.com/24811226/59777829-ef377300-92e7-11e9-8d23-059700cee547.png">

**Comment by GrayLuo** [comment]
@dengxit 我动态更新的不是select组件，就text啊？而且select变化的时候需要动态改变需要展示的form字段，并不是固定的。

**Comment by dengxit** [comment]
我只用过select的联动，没有尝试过对文本联动，如果你就是想要对某个字段比如省份选择，然后另外一个form列出对应市的效果的话，用图中方法即可。

**Comment by chenjiabin** [comment]
@GrayLuo  有解决方案了吗
