### ISSUE TITLE
富文本问题

### ISSUE THREAD

**Issue by wploey** [z-song/laravel-admin#3536]
- Laravel Version: 5.8
- PHP Version: 7.2.18
- Laravel-admin: 1.7.1

### Description:
浏览器后退时, 富文本会写进富文本里面, 以前自己扩展 ueditor 也会

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/16448892/59691988-9a77f780-9216-11e9-8526-7cb903b1dbfd.png)
![image](https://user-images.githubusercontent.com/16448892/59691998-a06dd880-9216-11e9-93a1-cf248e4267af.png)
![image](https://user-images.githubusercontent.com/16448892/59692006-a2d03280-9216-11e9-86c3-c0accbc80e28.png)
![image](https://user-images.githubusercontent.com/16448892/59692019-a8c61380-9216-11e9-9c5b-08d37fb244ea.png)

**Comment by z-song** [comment]
已经提交了修复，更新wangEditor到v1.1

你自己扩展的编辑器参考这个commit来修复 c5f3d5688ef1a84e6966a63e5ec3e39d0afb0f3b
