### ISSUE TITLE
Custom Popup/sweetAlert

### ISSUE THREAD

**Issue by Neakit** [z-song/laravel-admin#3538]
- Laravel Version: 5.8.2
- PHP Version: 7.2
- Laravel-admin: ^1.6

### Description:
I want to customize sweet modal/popup.
after clicking delete button at grid row I want to show some information in popup, so is there any beforeHook can I use? New in laravel. Help with examples please:)  

![example](https://user-images.githubusercontent.com/24417949/59696076-fc733580-91f3-11e9-9629-d578111e5a4a.png)

**Comment by pysoftware** [comment]
Hey how did you solve it?

**Comment by azaman2204** [comment]
https://github.com/z-song/laravel-admin/issues/3538#issue-457539215
Can you share how to use popup/sweetalert in laravel-admin controller?
