### ISSUE TITLE
Can't nullable of field on NestedForm

### ISSUE THREAD

**Issue by moriken** [z-song/laravel-admin#3541]
- Laravel Version: 5.8.7
- PHP Version: 7.2.19
- Laravel-admin: 1.7.1

### Description:
The value can not be updated as empty or null when form->hasMany.
```
$form->hasMany('samples', function (Form\NestedForm $form) {
    $form->text('label', 'Label'); // Can not be empty
});
```
I think that it is better to delete "is_null" of NestedForm.
https://github.com/z-song/laravel-admin/blob/master/src/Form/NestedForm.php#L270

Is this correct?

**Comment by InsomniakDev** [comment]
this is still an active matter

**Comment by oneWaveAdrian** [comment]
having the same issue here

**Comment by coziboy** [comment]
> having the same issue here

kinda curious, why we need to skip prepare record if column value is null?

https://github.com/z-song/laravel-admin/blob/6c59792713d7f93fcd979432b5fc14b636f2de2c/src/Form/NestedForm.php#L285-L287

@z-song

**Comment by oneWaveAdrian** [comment]
> > having the same issue here
> 
> kinda curious, why we need to skip prepare record if column value is null?
> 
> https://github.com/z-song/laravel-admin/blob/6c59792713d7f93fcd979432b5fc14b636f2de2c/src/Form/NestedForm.php#L285-L287
> 
> @z-song

Would also be interested in the reason @z-song, since it seems to work fine once those lines are removed. What does this prevent?

**Comment by backendsd** [comment]
I had the same problem, but i created a extensión hasManyPro (is copy of Original class HasMany ), and also created a Nested FormPro (is child of Original class NestedForm, I put it in folder extension too), well i replace in NestedFormPro but only that method.

if (is_null($value)) { 
     continue; 
 } 

for

if (is_null($value) && !($field instanceof \Encore\Admin\Form\Field\Text)) {
    continue;
}

my NestedFormPro look like;


`<?php
namespace App\Admin\Extensions;

use Illuminate\Support\Arr;
use Encore\Admin\Form\NestedForm as NestedFormBase;

class NestedForm extends NestedFormBase
{
    /**
     * Do prepare work before store and update.
     *
     * @param array $record
     *
     * @return array
     */
    protected function prepareRecord($record)
    {
        if ($record[static::REMOVE_FLAG_NAME] == 1) {
            return $record;
        }

        $prepared = [];

        /* @var Field $field */
        foreach ($this->fields as $field) {
            $columns = $field->column();

            $value = $this->fetchColumnValue($record, $columns);

            if (is_null($value) && !($field instanceof \Encore\Admin\Form\Field\Text)) {
                continue;
            }

            if (method_exists($field, 'prepare')) {
                $value = $field->prepare($value);
            }

            if (($field instanceof \Encore\Admin\Form\Field\Hidden) || $value != $field->original()) {
                
                if (is_array($columns)) {
                    foreach ($columns as $name => $column) {
                        Arr::set($prepared, $column, $value[$name]);
                    }
                } elseif (is_string($columns)) {
                    
                    Arr::set($prepared, $columns, $value);
                }
            }
        }

        $prepared[static::REMOVE_FLAG_NAME] = $record[static::REMOVE_FLAG_NAME];

        return $prepared;
    }
}`



And also verified that class HasManyPro use NestedFormPro.

I hope my answer could help you.

**Comment by taitin** [comment]
I share my way
```
$form->hasMany('details', '', function (NestedForm $form) {
    $form->text();
    .....
    
}
   $form->saved(function () {
            foreach (Request()->details as $key => $detail) {
                if (is_numeric($key)) {
                    $q = ExtractionQualityDetails::find($key);
                    foreach ($detail as $key => $value) {
                        if (is_null($value)) $q->{$key} = $value;
                    }
                    $q->save();
                }
            }
        });
        
```
 After saved ,then check the post request and put the empty value in.
       
 but it have to set every time on diffetent relation
