### ISSUE TITLE
1.7.0版列表中批量删除之后，未清除已删除的ids

### ISSUE THREAD

**Issue by devilcry52** [z-song/laravel-admin#3544]
- Laravel Version: 5.8.*
- PHP Version: 7.2.5
- Laravel-admin: 1.7.0

### Description:
批量删除之后，被删除的ids没有清理掉，页面刷新之后，在存在。

### Steps To Reproduce:
1.列表中有id为1-10的数据
2.勾选1-3，批量删除，成功之后，页面刷新(pjax)。
3.再次勾选4-6，提示已选择6项。经断点发现原先选择的1-3还在selects中。 导致跟批量操作有关的操作可能出现错误，比如 批量删除会报Model不存在。
4.F5浏览器刷新页面，再次勾选4-6，提示已选择3项，选择正常。

**Comment by chuoke** [comment]
我也遇到了，是所有选中操作之后，pjax后，选中未清除

**Comment by chinkiver** [comment]
同样的问题为：自定义批量操作上

**Comment by z-song** [comment]
提交了修复，等下个版本发布

**Comment by Gethin0321** [comment]
最新版1.7.14依然存在此问题,建议禁用pjax.

https://laravel-admin.org/docs/zh/qa#%E5%8F%AF%E4%BB%A5%E5%85%B3%E6%8E%89pjax%E5%90%97%EF%BC%9F
