### ISSUE TITLE
select会添加一个隐藏的input可能导致bug

### ISSUE THREAD

**Issue by HFX3389** [z-song/laravel-admin#3547]
- Laravel Version: 5.8.23
- PHP Version:7.2.11
- Laravel-admin: ^1.7

### Description:
MySQL数据库中假如字段有type，使用select添加时，查看Elements时发现会多出一个隐藏的input，而且无法通过Form添加数据进数据库，但是将字段中的"type"修改为"types"即可正常添加数据！
而且在Network中，无论是字段为"type"还是"types"，数据包都会出现两个相同属性！

### Steps To Reproduce:
![1](https://user-images.githubusercontent.com/15773134/59773045-8a781a80-92df-11e9-9a94-f0168fd3a3a1.png)
![2](https://user-images.githubusercontent.com/15773134/59773047-8a781a80-92df-11e9-98c7-9244c5536f89.png)
![3](https://user-images.githubusercontent.com/15773134/59773049-8b10b100-92df-11e9-805c-c915b7a27039.png)
![4](https://user-images.githubusercontent.com/15773134/59773051-8b10b100-92df-11e9-9dee-d9bc5e8957ef.png)
![5](https://user-images.githubusercontent.com/15773134/59773052-8b10b100-92df-11e9-8a49-b0291c96f227.png)

**Comment by jim515jim** [comment]
Field 'type' doesn't have a default value
资料库栏位的原因

**Comment by jim515jim** [comment]
https://github.com/z-song/laravel-admin/issues/3009#issuecomment-464168983
