### ISSUE TITLE
富文本静态资源是否有引入

### ISSUE THREAD

**Issue by DavidNineRoc** [z-song/laravel-admin#3554]
- Laravel Version: 5.5.*
- PHP Version:
- Laravel-admin: 1.7

按照文档使用 Wangeditor, 未能出现样式。需要手动
```
Admin::css(cssFile);
Admin::js(jsFile);
```
方可

**Comment by z-song** [comment]
安装这个扩展 https://github.com/laravel-admin-extensions/wangEditor

**Comment by DavidNineRoc** [comment]
如果我想使用别的富文本， 如 ueditor， 我看代码并未实际引入静态变量中的 css 和 js
