### ISSUE TITLE
如何重写模型表格create页面的提交按钮的脚本呢？

### ISSUE THREAD

**Issue by ync11** [z-song/laravel-admin#3560]
- Laravel Version: 5.8.*
- PHP Version: 7.3.5
- Laravel-admin: 1.7

### Description:
如何重写模型表格create页面的提交按钮的脚本呢？我想让这个按钮只将表单数据post到服务器而不写入数据库
如图：
![批注 2019-06-22 150029](https://user-images.githubusercontent.com/26475310/59960695-87a74080-94fe-11e9-8d63-880797b45378.png)

**Comment by chan17** [comment]
$form->action();

**Comment by ync11** [comment]
@chan17 这个模型表单的按钮自带添加到数据库的功能，我是想要去掉这个功能。目前有两种思路：1. 禁用这个按钮的提交数据库的功能，再添加一个脚本，加入另外的功能；2. 去掉提交按钮，再在此处添加一个新的按钮。对于1，我不知道如何去禁用这个按钮的提交到数据库的功能；对于2，我不知道如何将按钮加在这个位置。我不知道我表述清楚没有...

**Comment by chan17** [comment]
$form->action('/admin/XXX/脚本‘);
对啊  改了html form的action 属性啊。。不是可以吗

**Comment by ync11** [comment]
@chan17 非常感谢，我明白了
