### ISSUE TITLE
Getting model instance in deleting callback

### ISSUE THREAD

**Issue by sahadatfci** [z-song/laravel-admin#3562]
- Laravel Version: 5.5
- PHP Version:
- Laravel-admin: 1.6

### Description:
I am not getting model instance in deleting call back. its null

### Steps To Reproduce:
I tried this code
$form->deleting(function(Form $form){
	              $model = $form->model(); //I found null here
        });

**Comment by mehdi89** [comment]
Same here. can anyone please help?

**Comment by vlados** [comment]
why not 
```
$form->deleting(function() use ($form) {
$model = $form->model(); //I found null here
});


```

**Comment by mehdi89** [comment]
@vlados It's not working but, I think it supposes to work. 
anyway, for time being I have implemented this to get the id to run some validation check before delete
```php
$url = Input::url();
$arr = explode("/", $url);
$id = end($arr);
```
so, full code 
```php
$form->deleting(function () {
	$url = Input::url();
	$arr = explode("/", $url);
	$id = end($arr);
	
	//check if any dependency
	
	if ($check != null) {
		throw new \Exception("Can't delete.....");
	}
});
```

**Comment by vlados** [comment]
It should be the same but in the documentation there is no info - https://laravel-admin.org/docs/#/en/model-form-callback?id=deleting-deleted
```
$form->saved(function (\Encore\Admin\Form $form) {
	$this->customUpdate($form->model());
});
```

Why not try:
```
$model = $form->model()
$form->deleting(function () use ($model) {
});

```

**Comment by ericpereira** [comment]
same problem, any solution?

**Comment by joe94113** [comment]
@ericpereira  The following is my solution

Slightly modified according to @mehdi89 's practice

```php
$form->deleting(function () {
    $url = url()->full();
    $arr = explode("/", $url);
    $id = end($arr);

    // ...

    if (true) {
        return response()->json([
            'status'  => false,
            'message' => 'something error....',
        ]);
    }
});
```
