### ISSUE TITLE
$form->hasMany与$form->table组合使用有bug

### ISSUE THREAD

**Issue by ashuiccc** [z-song/laravel-admin#3564]
- Laravel Version: #.#.#1.7.1
- PHP Version:7.3
- Laravel-admin: #.#.#5.8

### Description:

$form->hasMany('userChannelFeeRate', function ( $form) {
               
               $form->table('fee_rate', '', function ($table) {
                    $table->text('gt', '大于')->default(-1)->rules('required');
                });

});

当点击table的新增按钮时,会直接增加hasMany选项,不会增加table选项

### Steps To Reproduce:

**Comment by guandeng** [comment]
更新到1.7.2可以了

**Comment by phpLHT** [comment]
> 更新到1.7.2可以了

已经更新到了 1.7.2   依然是这种情况

**Comment by guandeng** [comment]
> > 更新到1.7.2可以了
> 
> 已经更新到了 1.7.2 依然是这种情况

有清理过压缩文件吗

**Comment by phpLHT** [comment]
> > > 更新到1.7.2可以了
> > 
> > 
> > 已经更新到了 1.7.2 依然是这种情况
> 
> 有清理过压缩文件吗

使用php artisan admin:minify    压缩过，后来又清理了，php artisan admin:minify --clear 这个会影响吗

**Comment by ashuiccc** [comment]
> > > > 更新到1.7.2可以了
> > > 
> > > 
> > > 已经更新到了 1.7.2 依然是这种情况
> > 
> > 
> > 有清理过压缩文件吗
> 
> 使用php artisan admin:minify 压缩过，后来又清理了，php artisan admin:minify --clear 这个会影响吗

我刚清理了压缩文件,还是不行,而且我没用过那个压缩,用了之后会忽略我引入的js

**Comment by phpLHT** [comment]
> > > 更新到1.7.2可以了
> > 
> > 
> > 已经更新到了 1.7.2 依然是这种情况
> 
> 有清理过压缩文件吗

这个是要做什么操作呢？

**Comment by phpLHT** [comment]
> > > > > 更新到1.7.2可以了
> > > > 
> > > > 
> > > > 已经更新到了 1.7.2 依然是这种情况
> > > 
> > > 
> > > 有清理过压缩文件吗
> > 
> > 
> > 使用php artisan admin:minify 压缩过，后来又清理了，php artisan admin:minify --clear 这个会影响吗
> 
> 我刚清理了压缩文件,还是不行,而且我没用过那个压缩,用了之后会忽略我引入的js

这个是两个原因 引起的，连个新增事件 冲突 和  hasMany  里的table  事件页面加载时不能绑定引起的

**Comment by Cuifc** [comment]
> 更新到1.7.2可以了

$form->hasMany()里不支持table组件吧，我看1.7.2版本的代码也不支持的啊，请问怎么用呢？
