### ISSUE TITLE
当删除 $form->list 中最后一个元素时删除不了

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3565]
- Laravel-admin: 1.7.1

### Description:
当list中以后数据，想全部删除时，删除之后保存，数据依然存在。

![2](https://user-images.githubusercontent.com/224353/59971568-0ceb2d80-95b1-11e9-8524-6cc4d375335a.gif)

**Comment by smartymoon** [comment]
我也遇到了这个问题，请问是如何解决的
