### ISSUE TITLE
如何在bootstrap 模态框 中使用Encore\Admin\Form ？

### ISSUE THREAD

**Issue by chan17** [z-song/laravel-admin#3568]
用Encore\Admin\Form render表单，放bootstrap 模态框 中无法正常

只能加上Content $content 这么写：
![image](https://user-images.githubusercontent.com/3273748/60012531-c4b23500-96ae-11e9-8135-24acd300a224.png)
结果就带上  网页的整个content了 ：
![image](https://user-images.githubusercontent.com/3273748/60012638-0a6efd80-96af-11e9-89b9-b9bb3de4e12e.png)

有没有办法只使用表单Encore\Admin\Form？？

**Comment by czhong0** [comment]
遇到了类似的问题。我想在模态框展示另一个grid。目前没找到好的方法。您目前的写法方便提供下grid的代码参考吗。

-

**Comment by chan17** [comment]
> 遇到了类似的问题。我想在模态框展示另一个grid。目前没找到好的方法。您目前的写法方便提供下grid的代码参考吗。

没用 直接return Content类后会出错  laravel admin 前端就报错了

**Comment by chan17** [comment]
> 遇到了类似的问题。我想在模态框展示另一个grid。目前没找到好的方法。您目前的写法方便提供下grid的代码参考吗。

你还是直接打开一个新页面吧

**Comment by czhong0** [comment]
> > 遇到了类似的问题。我想在模态框展示另一个grid。目前没找到好的方法。您目前的写法方便提供下grid的代码参考吗。
> 
> 你还是直接打开一个新页面吧

![image](https://user-images.githubusercontent.com/44249828/60426200-c340b980-9c26-11e9-95da-a52a686bd929.png)
![image](https://user-images.githubusercontent.com/44249828/60426261-e23f4b80-9c26-11e9-8335-7115fd7490d5.png)
模仿着写了一个视图，可以达到我的需求。感谢！
