### ISSUE TITLE
Refresh grid : Uncaught TypeError: $.admin.reload is not a function

### ISSUE THREAD

**Issue by itanea** [z-song/laravel-admin#3569]
- Laravel Version: 5.8.24
- PHP Version: 7.2.11
- Laravel-admin: 1.7.2

### Description:
When I click on refresh icon on the top righ corner to reload grid content, I have the javascript error :

```
projects:944 Uncaught TypeError: $.admin.reload is not a function
    at HTMLAnchorElement.<anonymous> (projects:944)
    at HTMLAnchorElement.dispatch (jQuery-2.1.4.min.js:3)
    at HTMLAnchorElement.r.handle (jQuery-2.1.4.min.js:3)
```

### Steps To Reproduce:
Just click on the refresh button on the top right corner :

![image](https://user-images.githubusercontent.com/425998/60050646-68acd800-96d1-11e9-8908-59febab91a07.png)

I already try tips give in other bugs of the same type :

```
php artisan vendor:publish --tag=laravel-admin-assets --force
php artisan view:clear
php artisan admin:minify
```

The bug still here, unfortunately :-(

Can you help me please ?
Thanks to all.

**Comment by itanea** [comment]
So weird..... when I add a custom css class for my project, this bug disappears.
So I close the bug.
Thanks all.

**Comment by xxxlo71** [comment]
when i click the container-refresh button this bug show up ,

i plugin iframe-tabs , please help

![螢幕快照 2019-09-10 下午2 44 50](https://user-images.githubusercontent.com/33816886/64590305-d8ca2080-d3d9-11e9-954e-5c3444f434b3.png)

**Comment by xxxlo71** [comment]
PHP version | PHP/7.1.26
-- | --
Laravel version | 5.8.35
CGI | fpm-fcgi


encore/laravel-admin | 1.7.1
-- | --
fideloper/proxy | ^4.0
ichynul/iframe-tabs | 1.0.27
