### ISSUE TITLE
视频在预览时模板变成image！！！！在线急救

### ISSUE THREAD

**Issue by ming-lau-1024** [z-song/laravel-admin#3573]
有人遇到这个问题么？要怎么修复
![image](https://user-images.githubusercontent.com/49233234/60069470-8ddb2e00-9745-11e9-8a91-9c8061453f55.png)
![image](https://user-images.githubusercontent.com/49233234/60070887-e95bea80-974a-11e9-960a-6feb5eabbda2.png)

**Comment by z-song** [comment]
更新到v1.7.2
