### ISSUE TITLE
Deleting an image with removable function (laravel-admin). Image deleted successfully but getting json error

### ISSUE THREAD

**Issue by sujitkv92** [z-song/laravel-admin#3575]
- Laravel Version: 5.6.0
- PHP Version: 7.1
- Laravel-admin: 1.5.15

Deleting an image with removable function (laravel-admin). Image deleted successfully but getting json error. It seems not able to redirect page.

SyntaxError: Unexpected token < in JSON at position 0. below image section

**Comment by iyueshang** [comment]
同样遇到 这样的问题

**Comment by zhusaidong** [comment]
同问

**Comment by bjbjbjbj** [comment]
同问

**Comment by alexoleynik0** [comment]
Faced the same issue and it took me half a day to end up with this code in Form's saved callback. 
php 7.4, laravel 8.34.0, laravel-admin 1.8.11.
Hope this will help someone. Similar issues #2436 #4206
`
$form->saved(function (Form $form) {
    if (request()->wantsJson() && request()->has(\Encore\Admin\Form\Field::FILE_DELETE_FLAG)) {
        return response();
    }
});
`
