### ISSUE TITLE
如何实现一个字段根据值显示不同的操作样式？

### ISSUE THREAD

**Issue by bugcat** [z-song/laravel-admin#3577]
### 需求:
假设有我一个字段type，其值可能为 0  1  2 ，有以下业务规则：
当值为0时，可操作变更为1或2；
当值为1或2时，不可操作变更。

### 伪代码描述:
```
if ( 0 == type的值 ) {
    $form->radio('type')->options(['1' => '一', '2'=> '二']);
} else {
    $form->display('type');
}
```
如上代码描述 ，主要是想实现如此功能。
当然，如果能在表格列表grid中实现，那更好了。

**Comment by ichynul** [comment]
用editing实现
```php
$type = $form->radio('type')->options(['1' => '一', '2'=> '二']);

$form->editing(function ($form) use($type) {
     if( $form->model()->type>0)
    {
          $type->readOnly();
    }
});
```

**Comment by bugcat** [comment]
经测试，用editing并不能实现...

**Comment by SoulMate94** [comment]
经测试，用editing并不能实现... +1

**Comment by lutianxiong** [comment]
$method = request()->route()->getActionMethod();

    if ($method == 'edit') {

        switch ($type) {
            case 0:
                # code...
            break;
            case 0:
                # code...
            break;
            case 0:
                # code...
            break;
        }
    }

**Comment by lutianxiong** [comment]
```
$method = request()->route()->getActionMethod();

if ($method == 'edit') {

    switch ($type) {
        case 0:
            # code...
        break;
        case 1:
            # code...
        break;
        case 2:
            # code...
        break;
    }
}
```

**Comment by bugcat** [comment]
其实重点就是 type这个值怎么获取   能获取才能判断

**Comment by lutianxiong** [comment]
> 其实重点就是 type这个值怎么获取 能获取才能判断

那只能获取路由的ID再查询Type了

`
$id = request()->route()->parameters['xxx'];
`

**Comment by a1165203522** [comment]
@bugcat 
            主要是获取当前行的记录和column对象进行自定义。
            $statusColumn=$grid->column('status','状态');
            $statusColumn->display(function($val) use($statusColumn){
                    $modelArr=$this->toArray();//这个是当前行的记录
                    //可根据当前的记录做判断来渲染指定的下拉选项
                    return $statusColumn->editable('select',['1'=>'未付款','2'=>'已付款']);
            });

**Comment by chenfeizhou** [comment]
以下是我的解决方案
       $options = Article::OPTIONS_TXT[Article::STATUS_WAIT];
        if (Article::find(request()->article)->is_pushed ?? '') {
            $options = Article::OPTIONS_TXT[Article::STATUS_SUCCESS];
        }

**Comment by kaka775905353** [comment]
> 用editing实现
> 
> ```
> $type = $form->radio('type')->options(['1' => '一', '2'=> '二']);
> 
> $form->editing(function ($form) use($type) {
>      if( $form->model()->type>0)
>     {
>           $type->readOnly();
>     }
> });
> ```

可以用来实现 form，但grid 可能不行
