### ISSUE TITLE
Object of class Encore\Admin\Grid\Column could not be converted to string (View: /var/www/ershou-platform/vendor/encore/laravel-admin/resources/views/grid/table.blade.php)

### ISSUE THREAD

**Issue by pengbo37877** [z-song/laravel-admin#3578]
- Laravel Version: 5.6.39
- PHP Version: 7.3.6
- Laravel-admin: 1.6.15

### Description:
执行了如下三条命令后出现了问题
php artisan vendor:publish --tag=laravel-admin-assets --force
php artisan vendor:publish --tag=laravel-admin-lang --force
php artisan view:clear

**Comment by selfrefresh** [comment]
@z-song 我也是这个问题

**Comment by z-song** [comment]
检查下是否自定义了视图

**Comment by bob5266** [comment]
我升级后也报这个错误

**Comment by bob5266** [comment]
直接升级后 也报这个错误，最后发现 是因为PHP页面缓存之前的结果导致

**Comment by ZeiyThink** [comment]
我也遇到这个问题，是因为 自定义了视图   在bootstrap里去掉后就好了，以后尽量不包里的文件，不好更新。

**Comment by UsamaITS** [comment]
I just had the same issue. I didn't have a time to track the issue but I solve it 👍 .
First : I download the latest version of laravel-admin and extract to a folder.
Second : I make a forced copy for those Folders:
- Delete Folder : \resources\views\vendor\laravel-admin
- Replace Content of folder Extracted laravel-admin-master\resources\views **with** \resources\views\vendor\laravel-admin
- maybe 
By the way : those who still use the old syntax functions should change, like the demo code. 
See the [controllers on the demo](https://github.com/z-song/demo.laravel-admin.org/tree/master/app/Admin/Controllers).

**Comment by meiwentiya** [comment]
清理一下模板缓存 `php artisan view:clear`
