### ISSUE TITLE
需求：editable()日期选择器

### ISSUE THREAD

**Issue by luoxulx** [z-song/laravel-admin#3580]
- Laravel Version: 5.5.x
- PHP Version:7.2.x
- Laravel-admin: 1.6.x

### Description:
请问这样的 `$grid->column('xx','xx')->editable('date');`
![image](https://user-images.githubusercontent.com/35016570/60178717-b9960b00-984e-11e9-9151-00d7cf9854b7.png)
我要怎样改才能变成这样：
![image](https://user-images.githubusercontent.com/35016570/60178862-f95cf280-984e-11e9-9b45-a733743b5d4e.png)
求指点一二😁

**Comment by GrayLuo** [comment]
$grid->column('xx', 'xxx')->display(function () {
            return 'html';
   })->editable();

**Comment by luoxulx** [comment]
```php
$grid->column('approved_at', '支付时间')->display(function ($val){
            $html = '<div class="input-group"><span class="input-group-addon"><i class="fa fa-calendar fa-fw"></i></span><input type="text" name="value" value="'.str_limit($val, 10, '').'" class="form-control"></div>';
            return $html;
        })->editable();
```
不可以。。。。
成这样了~~
![image](https://user-images.githubusercontent.com/35016570/60250951-316d3f80-98fa-11e9-97e6-a0458db16ab9.png)

**Comment by luoxulx** [comment]
现在的解决办法是这样的：
在 grid 输出一段 js 来控制
```php
 $script = <<<script
$('.grid-editable-approved_at').click(function(){
    setTimeout("$('.editable-input input').datetimepicker({'format':'YYYY-MM-DD','locale':'zh-CN','useCurrent':true});", 200)
})
script;

        Admin::script($script);
        return $grid;
```
```javascript
// 一点击就渲染datetimepicker的话，JQ 会找不到那个editable-input input输入框，所以200ms 后再去找 input 元素
```
但是这样有一个**坏处**：
点击`小铅笔`后弹出 input 框，此时并没有日期选择器，需要把光标移出 input后再移入 input 框，才有效
如下：
- 第一次光标
![image](https://user-images.githubusercontent.com/35016570/60253754-3f718f00-98ff-11e9-9427-939aed741c04.png)
- 第二次移入光标
![image](https://user-images.githubusercontent.com/35016570/60253822-5dd78a80-98ff-11e9-90f3-e93a3168b2e5.png)

请问有什么解决办法吗？

**Comment by luoxulx** [comment]
Hello?

**Comment by luoxulx** [comment]
Anyone There?
