### ISSUE TITLE
在grid的匿名函数外部如何获取当前行的数据？

### ISSUE THREAD

**Issue by GrayLuo** [z-song/laravel-admin#3581]
在grid的匿名函数外部如何获取当前行的数据？需要根据当前行的数据判断是否可以编辑。

```
  if($**order**->state == 1) {
            $grid->column(self::$redeemCodeKey, '核销')->editable();
        } else {
            $grid->column(self::$redeemCodeKey, '核销');
  }
```

**Comment by z-song** [comment]
外面获取不到

```php
        $grid->column(self::$redeemCodeKey, '核销')->display(function ($value, $column) {

            if ($this-> state == 1) {
                return $column->editable();
            }

            return $value;
        });
```

**Comment by GrayLuo** [comment]
> 外面获取不到
> 
> ```
> $grid->column(self::$redeemCodeKey, '核销')->display(function ($value, $column) {
>     if ($this->state == 1) {
>         return $column->editable();
>     }
> 
>     return $value;
> });
> ```

非常感谢！！！！

**Comment by ahu** [comment]
> 外面获取不到
> 
> ```
> $grid->column(self::$redeemCodeKey, '核销')->display(function ($value, $column) {
>     if ($this->state == 1) {
>         return $column->editable();
>     }
> 
>     return $value;
> });
> ```

此方法怒赞！！！ 这个在文档里可以体现一下

**Comment by z-song** [comment]
@ahu 文档里面一直都有的  https://laravel-admin.org/docs/zh/1.x/model-grid-column-display#%E6%A0%B9%E6%8D%AE%E6%9D%A1%E4%BB%B6%E6%98%BE%E7%A4%BA%E4%B8%8D%E5%90%8C%E7%9A%84%E7%BB%84%E4%BB%B6

**Comment by ahu** [comment]
抱歉，我漏掉了！印象再次加深了！
