### ISSUE TITLE
在grid中直接修改后是否有办法只刷新这一行？

### ISSUE THREAD

**Issue by GrayLuo** [z-song/laravel-admin#3585]
grid中某一行有3个字段，其中有一个字段是editable()，在grid中直接修改这个字段后，另外2个字段跟着变化，是否有办法只刷新这一行？谢谢！

**Comment by z-song** [comment]
不支持

**Comment by chenjiabin** [comment]
如何调用刷新整个页面呢
 $.pjax.reload('#pjax-container');

**Comment by chenjiabin** [comment]
$script = <<<JS
$('.class').on('save', function(e, params) {
   $.pjax.reload('#pjax-container');
});
JS;
        Admin::script($script);
