### ISSUE TITLE
Class 'Intervention\Image\Facades\Image' not found

### ISSUE THREAD

**Issue by suryaadhisam** [z-song/laravel-admin#3594]
- Laravel Version: 5.8.*
- PHP Version: 7.1
- Laravel-admin: 1.7.2

### Description:
I just try to use your new feature to create thumbnail, but it show me that intervention class is not found. Help me to fix this. I need that feature.

![Screen Shot 2019-06-30 at 10 57 11](https://user-images.githubusercontent.com/36851071/60391680-aa50df00-9b26-11e9-8043-44316cdb6e6e.png)

**Comment by uacode** [comment]
http://image.intervention.io/getting_started/installation#laravel

**Comment by suryaadhisam** [comment]
Thanks a lot
