### ISSUE TITLE
bug:更新到1.7.2版本后表单验证出现bug 

### ISSUE THREAD

**Issue by ajiader** [z-song/laravel-admin#3596]
- Laravel Version: 5.5.X
- PHP Version:7.1
- Laravel-admin: 1.7.2

### Description:
更新到1.7.2后表单验证报错 Invalid argument supplied for foreach()

![QQ图片20190701114900](https://user-images.githubusercontent.com/4979798/60409455-40076f80-9bf6-11e9-83f6-d21158f57da3.png)

**Comment by uacode** [comment]
Twice run **->rules** ?

**Comment by z-song** [comment]
建议自行修复，然后提交pr
