### ISSUE TITLE
安装中出现的问题

### ISSUE THREAD

**Issue by kusnet** [z-song/laravel-admin#36]
你好，在根据readme的安装步骤中有以下问题：

安装
问题1：git clone 的master版本找不到config/app.php这个文件
在config/app.php加入ServiceProvider:

Encore\Admin\Providers\AdminServiceProvider::class
然后运行下面的命令完成安装：

问题2：在根目录执行php artisan，提示Could not open input file: artisan
php artisan vendor:publish --tag=laravel-admin
php artisan admin:install

另外，请问你有及时联系的方式么，比如QQ或者微信，遇到问题也可以及时请教

**Comment by z-song** [comment]
你好
你需要先安装laravel，然后在laravel中安装这个package
我的邮箱 zosong#126.com

**Comment by LincLiu** [comment]
你好，你上面所说的在laravel中安装package是指通过 laravel new demo创建应用后在demo目录下执行composer require encore/laravel-admin "1.3.x-dev"这个命令吗？

**Comment by z-song** [comment]
@LincLiu 对的

**Comment by LincLiu** [comment]
但是当我进行到最后一步 php artisan admin:install 时报了下面的错误
[PDOException]                                                                               
  SQLSTATE[HY000] [1045] Access denied for user 'homestead'@'localhost' (using password: YES)
你知道这是什么原因吗

**Comment by z-song** [comment]
@LincLiu `laravel-admin`需要在数据库中建表，所以你要先设置好数据库连接，设置好了之后再运行`php artisan admin:install`

**Comment by LincLiu** [comment]
是在config/database.php中修改设置用户名密码什么的吗？我设置了过后还是同样的错误

**Comment by z-song** [comment]
@LincLiu 对的，先确保你的数据库连接设置是正确的，检查一下能从数据库读出数据吗

**Comment by LincLiu** [comment]
@z-song 我只是对mysql一项中进行了配置，设置了            
             'database' => env('DB_DATABASE', 'APM'),
            'username' => env('DB_USERNAME', 'root'),
            'password' => env('DB_PASSWORD', '123'),
这三个选项，并且用户名和密码都是对的

**Comment by z-song** [comment]
@LincLiu  `env('DB_DATABASE', 'APM')`会从 `.env`文件的`DB_DATABASE`读取配置，所以你要修改的是`.env`文件的`DB_DATABASE`、`DB_USERNAME `、`DB_USERNAME `三项

**Comment by LincLiu** [comment]
@z-song 已经安装成功了，但是浏览器中输入http://localhost/admin/ 无法打开
我的文件目录是下面这样的
htdocs/apm/lfapp/(package相关)
这是输入的路径出错了吗

**Comment by z-song** [comment]
先打开http://localhost 确保laravel能正常启动

**Comment by LincLiu** [comment]
先打开http://localhost没有问题啊

**Comment by LincLiu** [comment]
<img width="1011" alt="2016-10-14 11 40 10" src="https://cloud.githubusercontent.com/assets/13136305/19393539/ac47c4d8-9267-11e6-87fb-65e0ce2e544f.png">
我在htdocs目录下先是通过laravel新建了apm这个项目
然后再apm目录下执行composer require encore/laravel-admin "dev-master"这个命令
...
到最后安装也成功了
但浏览器打开http://localhost/admin还是有问题，报错如图所示

**Comment by z-song** [comment]
这是apache的404错误 不是laravel的，所以应该还是你的laravel没有安装好

**Comment by z-song** [comment]
@LincLiu 你在项目目录用artisan启动服务看看
```
php artisan serve
```
然后打开 http://localhost:8000/admin

**Comment by LincLiu** [comment]
我之前试过用那种方式启动，但执行命令后就不动了，如下图所示，在浏览器也无法打开 http://localhost:8000/admin

<img width="526" alt="2016-10-15 12 35 15" src="https://cloud.githubusercontent.com/assets/13136305/19395263/536b5a34-926f-11e6-9f02-a64c2af570c5.png">

**Comment by z-song** [comment]
打开 http://localhost:8000/admin 是什么？

**Comment by LincLiu** [comment]
无法访问
<img width="678" alt="2016-10-15 12 40 10" src="https://cloud.githubusercontent.com/assets/13136305/19395386/f4dd07f0-926f-11e6-9ad7-35ed94067bb4.png">

**Comment by z-song** [comment]
那就很奇怪了，你是在mac上调试还是在虚拟机里？

**Comment by LincLiu** [comment]
Mac

**Comment by z-song** [comment]
你看下log吧  或者看下terminal的输出

**Comment by LincLiu** [comment]
我有按照其他教程新建一个项目，然后执行php artisan serve启动服务，但浏览器中还是无法打开laravel界面

**Comment by z-song** [comment]
http://localhost:8000/无法打开还是http://localhost:8000/admin无法打开？

**Comment by z-song** [comment]
如果出现你上面的截图的话  看下log吧

**Comment by LincLiu** [comment]
http://localhost:8000/无法打开，估计还是laravel哪里有问题

**Comment by z-song** [comment]
不知道是不是端口的问题  `sudo php artisan serve --port=80`再打开`http://localhost`试试

**Comment by LincLiu** [comment]
执行sudo php artisan serve --port=80，终端仍然是卡在那不动
浏览器还是404那个错误

**Comment by z-song** [comment]
你先把apache停掉吧 那个404错误是apache的

**Comment by LincLiu** [comment]
apache停掉之后报这个错误了，
<img width="523" alt="2016-10-15 12 59 04" src="https://cloud.githubusercontent.com/assets/13136305/19395940/df00ba0a-9272-11e6-9a4d-15e26fa57a31.png">

**Comment by z-song** [comment]
`http://localhost`能打开吗，或者你换个其他的端口试试看

**Comment by LincLiu** [comment]
http://localhost可以正常打开
<img width="376" alt="2016-10-15 1 03 39" src="https://cloud.githubusercontent.com/assets/13136305/19395986/3e5c1e90-9273-11e6-82c1-9de12ff6ad3c.png">

**Comment by z-song** [comment]
这个也不是laravel的页面，貌似是nginx的输出，你看看是不是还开了nginx，如果开了关掉试试

**Comment by LincLiu** [comment]
我刚刚在终端关了nginx，还是一样的情况，之前没弄过nginx，应该跟那个没关吧。
我给你说下完整情况哈
我是安装了xampp，htdocs现在是web根目录，在这个目录下我在终端通过laravel new apm创建了apm这个项目，然后在apm目录下执行composer require encore/laravel-admin "dev-master"这个命令，并修改了.env等相关文件，并成功安装，直到现在无法打开网页

**Comment by z-song** [comment]
把Apache和Nginx都关掉 就用artisan来启动服务调试吧

**Comment by z-song** [comment]
现在的问题是你的laravel都没能正常运行起来

**Comment by LincLiu** [comment]
我把Apache关掉过后localhost打不开了

**Comment by z-song** [comment]
把Apache和Nginx都关掉 用artisan来启动服务 再打开 注意启动的端口

**Comment by LincLiu** [comment]
这是我刚刚进行的操作，浏览器打开还是有问题
<img width="522" alt="2016-10-15 1 27 39" src="https://cloud.githubusercontent.com/assets/13136305/19396638/9d1886c8-9276-11e6-90a3-5b312ac3b720.png">

**Comment by LincLiu** [comment]
我先休息了哈，明天还要上班，明天我再研究研究，辛苦你啦，非常感谢，也休息了哈

**Comment by LincLiu** [comment]
@z-song 我今天通过http://localhost/apm/public/可以看到下面的界面，这应该是代表laravel安装成功了的吧，
<img width="1194" alt="2016-10-15 10 01 56" src="https://cloud.githubusercontent.com/assets/13136305/19406773/c742afca-92bf-11e6-85c8-663cd2c29fd4.png">

**Comment by z-song** [comment]
正常首页URL应该是http://localhost

**Comment by LincLiu** [comment]
@z-song 执行php artisan serve这个命令的时候正常情况是什么样的？终端卡在那不动吗？

**Comment by z-song** [comment]
@LincLiu 正常情况就是卡着，浏览器有请求，会输出响应

![qq20161015-0 2x](https://cloud.githubusercontent.com/assets/1479100/19407808/afc3eb32-92df-11e6-9348-a387006dd843.png)

**Comment by LincLiu** [comment]
@z-song 终于装成功啦，找出了问题所在
1.之前没有将httpd.conf文件中的根目录定位到htdocs/apm/public这个路径下
2.没有将apm这个文件夹赋予读写权限
