### ISSUE TITLE
Why loading all package dependencies even if they are not in use?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#360]
![2017-01-25_1341](https://cloud.githubusercontent.com/assets/24757934/22304185/6fd1be12-e304-11e6-9563-7e1a1793b2b8.png)

Can't this be manage in a way to load package files only when they are use in a page?

For example Ckeditor cdn is loaded even wen we are not using editor on the page.

**Comment by z-song** [comment]
`laravel-admin` use pjax to load all pages, all package files will be loaded just once after login.

You should know more about pjax.
