### ISSUE TITLE
单表但字段较多，如何使用expand呢？

### ISSUE THREAD

**Issue by ync11** [z-song/laravel-admin#3604]
- Laravel Version: 5.8.*
- PHP Version: 7.3.5
- Laravel-admin: 1.7

### Description:
单表字段很多，在界面上显示不完全，demo里面使用的expand是一对多的关系，但是单表如何使用expand呢？

**Comment by z-song** [comment]
可以用fieldset给表单项分组

```php

$form->fieldset('高级设置', function (Form $form) {
    $form->text('name')->required();
    $form->number('number')->rules('required|min:5');
})->collapsed();
```

**Comment by ync11** [comment]
可能我没描述清楚，目前遇到的是这个grid的问题。
![图片](https://user-images.githubusercontent.com/26475310/60778109-2de27f80-a168-11e9-995d-70d028992f6a.png)
![图片](https://user-images.githubusercontent.com/26475310/60778139-59656a00-a168-11e9-9d1b-f3a088ca4f9b.png)
