### ISSUE TITLE
模型表格，列过滤器 一直不生效

### ISSUE THREAD

**Issue by kilvn** [z-song/laravel-admin#3609]
- Laravel Version: 5.8.*
- PHP Version: 7.3
- Laravel-admin: 1.6.13

### Description:
$grid->column('status', '状态')->filter([1 => '启用', 2 => '禁用']);
代码是这样的，只显示值为1，筛选器一直不显示

$grid->column('code')->filter();
会提示 filter 方法不存在，奇了怪了

### Steps To Reproduce:
no

**Comment by kilvn** [comment]
无奈，我只能用数据查询过滤了。

**Comment by SoulMate94** [comment]
试试用这种 别用$grid->column();
        $grid->is_show('是否开启')->switch($is_show)->filter([
            1 => '开启',
            0 => '关闭'
        ]);
        $grid->created_at('发布时间');

**Comment by z-song** [comment]
@kilvn 注意版本
