### ISSUE TITLE
migrate 失败

### ISSUE THREAD

**Issue by YaoKaiLun** [z-song/laravel-admin#361]
对项目进行数据库迁移时，报 “Undefined index: 2016_01_04_173148_create_admin_tables” ，大概是数据库 migrations 表中存在 2016_01_04_173148_create_admin_tables ，但在项目的 database/migrations 下不存在该文件，该文件是放在 laravel-admin 里的。

**Comment by z-song** [comment]
把文件复制到database/migrations下面试试看

`vendor/encore/laravel-admin/migrations/2016_01_04_173148_create_admin_tables.php`

**Comment by YaoKaiLun** [comment]
哈哈，我就是这么做的，也成功了。不过遇到一个问题，没有将数据备份，数据库里的数据都被清除了，找到 laravel-admin 的数据填充文件 AdminTablesSeeder.php ，复制出来，添加一些作用域后，仍然报 "Class AdminTableSeeder does not exist"

**Comment by z-song** [comment]
用`artisan db:seed`命令来运行AdminTablesSeeder.php

**Comment by YaoKaiLun** [comment]
还是不可以，估计是复制出的 AdminTablesSeeder.php 文件运行出错了，有些变量没引入

**Comment by langeuh** [comment]
@z-song can you change `drop` to `dropIfExists`  in the down function?
```php
Schema::connection($connection)->dropIfExists(config('admin.database.users_table'));
```

**Comment by z-song** [comment]
@langeuh changed now 5d00f00

**Comment by Gijera** [comment]
@YaoKaiLun 你可以先把原先的Admin文件重命名一下，然后使用```php artisan admin:install```生成数据库之后再删除新建的Admin文件，然后把原来的文件重命名为Admin。
