### ISSUE TITLE
Change profile image path

### ISSUE THREAD

**Issue by rwmediaworks** [z-song/laravel-admin#3613]
- Laravel Version: 5.8.15
- PHP Version: 7.2.8
- Laravel-admin: 1.6.13

### Description:

On users setting edit:

When avatar changed it gets saved in **/storage/app/public/images**.

I want to change this path to **/storage/app/public/images/profile_images**

I tried changing path in /config/admin.php under upload.directory.image array, but it's not working.

Does any one have idea how to do it?

### Steps To Reproduce:

1. Go to below path:

http://localhost/admin/auth/setting

2. Change avatar and save it. The new image should get saved in above required path.

**Comment by Karim-Rahali** [comment]
You need to add a disk in config/filesystems.php

For more details, check https://laravel-admin.org/docs/#/en/model-form-upload?id=upload-to-local

**Comment by rwmediaworks** [comment]
@Karim-Rahali I wanted to change image path of users picture only.

1. I created below new file :

/app/Admin/Controllers/AuthControllers.php

2. Extended by:

Encore\Admin\Controllers\AuthController

3. Changes value of **auth.controller** in **config/admin.php** by:

App\Admin\Controllers\AuthController::class,

4. Overridden below method:

settingForm()

5. And changed below line from:

$form->image('avatar', trans('admin.avatar'));

To:

$form->image('avatar', trans('admin.avatar'))->move('images/profile_images')->uniqueName();

It's working now.
