### ISSUE TITLE
快捷搜索功能设置placeholder问题

### ISSUE THREAD

**Issue by Yuner2018** [z-song/laravel-admin#3618]
- Laravel Version: 5.8.24
- PHP Version:7.1.18
- Laravel-admin: 1.7.2

### Description:
现在有一个功能需要用到快捷搜索功能，想要设置搜索文本框的placeholder,提示用户可以按哪些字段可以搜索，作者能不能考虑加上这个功能。

**Comment by z-song** [comment]
@Yuner2018 已经提交实现

```php
$grid->quickSearch()->placeholder('搜索...');
```
