### ISSUE TITLE
$footer 底部选择能不能出一个默认选择的方法?

### ISSUE THREAD

**Issue by SoulMate94** [z-song/laravel-admin#3619]
- Laravel Version: 5.8.27
- PHP Version: 7.2
- Laravel-admin: 1.7.2

### Description:
$form->footer(function ($footer) {

    // 去掉`重置`按钮
    $footer->disableReset();

    // 去掉`提交`按钮
    $footer->disableSubmit();

    // 去掉`查看`checkbox
    $footer->disableViewCheck();

    // 去掉`继续编辑`checkbox
    $footer->disableEditingCheck();

    // 去掉`继续创建`checkbox
    $footer->disableCreatingCheck();

});

### Steps To Reproduce:
能不能出几个默认选中的方法?

**Comment by z-song** [comment]
@SoulMate94 参考这个提交 6943ef03ffad8bc7efaf72137a09b9088cb2a432

**Comment by SoulMate94** [comment]
好的,谢谢
