### ISSUE TITLE
saving里面验证数据唯一出错

### ISSUE THREAD

**Issue by guyaofei** [z-song/laravel-admin#3620]
![image](https://user-images.githubusercontent.com/30075084/60662694-a955df80-9e8f-11e9-82a5-dc34367bdf09.png)
作者大佬，看下我这样写有问题吗？rank字段是int类型的，但是在编辑的时候当前编辑的数据不修改也会提示数据已存在，但是数据库里只有当前的这一条数据，没有其他相同的数据。而且验证名称唯一的方法是可以的，没有出现这种问题

**Comment by guyaofei** [comment]
编辑时，和当前的数据做了对比，当前数据不修改，同样会报数据已存在。

**Comment by lutianxiong** [comment]
判断下有没有修改，没有修改提交的时候忽略吧。

**Comment by z-song** [comment]
rank字段的表单项怎么写的?

**Comment by guyaofei** [comment]
![image](https://user-images.githubusercontent.com/30075084/60854061-6306d480-a231-11e9-9e40-75bdb1213fea.png)zheyang这样的
