### ISSUE TITLE
命令行生成的controller少了路由访问的那几个方法

### ISSUE THREAD

**Issue by Cuifc** [z-song/laravel-admin#3629]
- Laravel Version: 5.8.27
- PHP Version: 7.1.13
- Laravel-admin: 1.7.2

### Description:
执行 php artisan admin:make ShopController --model='App\Models\Shop'
命令后，ShopController 只生成了grid(), detail()及form()方法，为什么index(),show(),edit(),create()方法没有生成？

**Comment by Cuifc** [comment]
跟踪源码才发现 Laravel-admin 1.7.2 下 vendor/encore/laravel-admin/src/Console/stubs/controller.stub  这个模板只保留了grid，detail，form 三个方法，为什么这么设计？

**Comment by Cuifc** [comment]
@z-song 望解答下，谢谢~

**Comment by z-song** [comment]
看控制器父类代码
