### ISSUE TITLE
grid列数据过滤预处理

### ISSUE THREAD

**Issue by donallin** [z-song/laravel-admin#3636]
- Laravel Version: 5.8.15
- PHP Version: PHP/7.3.2
- Laravel-admin: ^1.7

### Description:
希望在grid渲染数据之前，根据拥有的资源权限进行一次过滤，该如果事先做处理

**Comment by z-song** [comment]
使用`$grid->model()-where()`来过滤数据可以么？

**Comment by donallin** [comment]
这个后面的model后面的方法遵循的是Illuminate\Support\Collection的方法使用，对吗

**Comment by z-song** [comment]
文档都有写 

https://laravel-admin.org/docs/zh/model-grid#%E4%BF%AE%E6%94%B9%E6%9D%A5%E6%BA%90%E6%95%B0%E6%8D%AE
