### ISSUE TITLE
editable('textarea')/editable('text')发起修改后应该如何触发回调？

### ISSUE THREAD

**Issue by sausager** [z-song/laravel-admin#3637]
- Laravel Version: 5.5.45
- PHP Version: 7.2.18
- Laravel-admin: 1.7.2

### Description:
在使用列的扩展时，遇到一个问题。
$grid->column('value','设置值')->editable('textarea');
$grid->column('value','设置值')->editable('text');
在列表直接修改数据成功了，但是不知如何让页面发起浮动窗提示，提示用户修改成功。
看了文档，发现Grid并未提供像是Form中的saving或者saved函数，帮助发起提示浮动窗。
而使用admin_toastr函数需要刷新一次页面才能显示提示窗。
如果editable('textarea')/editable('text')其实是可以触发回调提示的话，不知能否提供一个演示范例？

**Comment by z-song** [comment]
不支持
