### ISSUE TITLE
thumbnail 希望能配置缩略图裁剪方式

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3639]
- Laravel-admin: 1.7.2

### Description:
目前 thumbnail 只能固定尺寸，多余部分白色填充，但其实这种缩略图是很影响美观的，更多时候是希望按最小边居中裁剪，而其实 InterventionImage 是有提供 fit 方法的，但现在 uploadAndDeleteOriginalThumbnail 里写死的这部分逻辑，能给 thumbnail 传值时多传一个参数指定缩略图裁剪方式更好。
如：
```php

        $form->image('thumb', __('配图'))->uniqueName()->removable()->thumbnail([
            'mini' => [60, 60, 'resize'],
            'small' => [292, 178, 'fit'],
            'large' => [500, 500],
        ]);
```

**Comment by tmxd09887** [comment]
遇到类似的问题，缩略图多余部分白色填充了，最好有FIT模式

**Comment by tmxd09887** [comment]
试了下可以用fit方法
$form->image('avatar','头像')->fit(300, 300)->uniqueName();

所以InterventionImage的方法都可以用？

**Comment by terranc** [comment]
> 试了下可以用fit方法
> $form->image('avatar','头像')->fit(300, 300)->uniqueName();
> 
> 所以InterventionImage的方法都可以用？

https://github.com/z-song/laravel-admin/pull/3640/files
