### ISSUE TITLE
1.3.x-dev is broken? 1.3.* setting page functionality is not working?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#364]
Can I implement settings in 1.3.*

I was using 1.3.x-dev and settings was working fine recently update the composer and its all broken.

Also can I upgrade it to 1.4.x-dev for laravel 5.4

**Comment by smuzammilali** [comment]
It's fixed now on 1.3.x-dev after composer update.

But have issued on 1.4.xdev Laravel 5.4

**Comment by z-song** [comment]
You can update ` 1.4.x-dev` now.
