### ISSUE TITLE
想要用laravel-admin做数据统计表的展示，grid好像不合适，有推荐的插件可以用的吗

### ISSUE THREAD

**Issue by donallin** [z-song/laravel-admin#3641]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
如图
![image](https://user-images.githubusercontent.com/5716754/61021505-5e2e5600-a3d4-11e9-97ea-97ef7fd13c90.png)

**Comment by lutianxiong** [comment]
用表格

**Comment by donallin** [comment]
最后选择把下面的内容和表格分成两部分，然后左右展示，感谢
