### ISSUE TITLE
在表单图片上传时，form->image，能否不使用第三方的上传插件（类似七牛，阿里oss），直接上传到自己封装好的图片服务，看了以下配置好像没有自定义的说明

### ISSUE THREAD

**Issue by donallin** [z-song/laravel-admin#3642]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
在表单图片上传时，form->image，能否不使用第三方的上传插件（类似七牛，阿里oss），直接上传到自己封装好的图片服务，看了以下配置好像没有自定义的说明
![image](https://user-images.githubusercontent.com/5716754/61099400-c17fbd00-a494-11e9-9b49-915733863ee4.png)

**Comment by z-song** [comment]
你要按照Laravel的方式封装一个基于你的图片服务的文件系统适配器

https://learnku.com/docs/laravel/5.8/filesystem/1319#custom-filesystems

**Comment by donallin** [comment]
我目前的处理方式是，form表单中填写一个辅助字段img_upload，然后ignore这个字段；在提交前saving中获取request()->file('img_upload')，然后根据这个参数传递到自己封装好的图片服务；但是可能因为laravel-admin自身自带了对uploadFile的处理，应该是做了两次处理的。以上是暂时快速处理方法。
![image](https://user-images.githubusercontent.com/5716754/61426668-cee1ef00-a94d-11e9-828d-b385152e6414.png)

**Comment by donallin** [comment]
我这边走了一套完全不用走文件系统就可以把文件上传并且返回地址的机制哈，有空再给大家分享。上面给的是其中一部分，还需要加这一句，支持纯url传递的img字段
![image](https://user-images.githubusercontent.com/5716754/61609551-0ff93c80-ac89-11e9-8945-b22166798ce2.png)

**Comment by guanhui07** [comment]
@donallin 我们这也有这需求,有便捷方式不
