### ISSUE TITLE
BUG使用hasMany保存，验证不通过俩次后，列的id值变成___LA_KEY__

### ISSUE THREAD

**Issue by samaelnine** [z-song/laravel-admin#3646]
- Laravel Version: 5.8.11
- PHP Version:7.2.2
- Laravel-admin: 1.6.13

### Description:
使用hasMany保存前，如果俩次验证不成功，会自动删除新增的记录，id值变了。此问题使用最新的1.7.2，也是一样的问题！！
备注：在火狐浏览器上，操作出问题

### Steps To Reproduce:
![QQ图片20190713182729](https://user-images.githubusercontent.com/42225747/61170452-c24f4680-a59b-11e9-8879-863f6159b93b.png)
![QQ图片20190713182733](https://user-images.githubusercontent.com/42225747/61170456-ced39f00-a59b-11e9-845c-deae59f2bc17.png)
![QQ图片20190713182737](https://user-images.githubusercontent.com/42225747/61170459-dbf08e00-a59b-11e9-89f7-b3cf48ed96ed.png)
第二次验证不通过后，id值变为___LA_KEY___

**Comment by crisis111** [comment]
顶

**Comment by whmlol** [comment]
1

**Comment by whmlol** [comment]
https://github.com/z-song/laravel-admin/pull/3721/commits/13ea3ba37b4df4b37ccb5069cb7088b29cf05a57

**Comment by Cuifc** [comment]
> * Laravel Version: 5.8.11
> * PHP Version:7.2.2
> * Laravel-admin: 1.6.13
> 
> ### Description:
> 使用hasMany保存前，如果俩次验证不成功，会自动删除新增的记录，id值变了。此问题使用最新的1.7.2，也是一样的问题！！
> 备注：在火狐浏览器上，操作出问题
> 
> ### Steps To Reproduce:
> ![QQ图片20190713182729](https://user-images.githubusercontent.com/42225747/61170452-c24f4680-a59b-11e9-8879-863f6159b93b.png)
> ![QQ图片20190713182733](https://user-images.githubusercontent.com/42225747/61170456-ced39f00-a59b-11e9-845c-deae59f2bc17.png)
> ![QQ图片20190713182737](https://user-images.githubusercontent.com/42225747/61170459-dbf08e00-a59b-11e9-89f7-b3cf48ed96ed.png)
> 第二次验证不通过后，id值变为___LA_KEY___

请问你这页面布局怎么弄出来的，使用$form->hasMang('', function($form) { $form->table() } )吗
