### ISSUE TITLE
Colmun 增加一个默认值设置方法

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3649]
- Laravel-admin: 1.7.2

### Description:
为了让空field在表格数据显示时有一个默认占位字符，目前每次都要display里去写回调，为了让这个效率更高，希望能增加一个default方法，来设置空字符占位符。

**Comment by z-song** [comment]
每个人判断为空的方式有所不同，所以这里还是建议自行扩展吧

在app/Admin/bootstrap.php里面加上

```php
use Encore\Admin\Grid\Column;

Column::extend('default', function ($value, $default) {
    return empty($value) ? $default : $value;
});
```

使用方式`$grid->column('column_name')->default('-');`

**Comment by terranc** [comment]
ok
