### ISSUE TITLE
Laravel 5.4 upgrade with 1.4.x-dev some issues

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#365]
grid function editable() is not working:
![2017-01-26_1808](https://cloud.githubusercontent.com/assets/24757934/22354287/a0e39df6-e3f2-11e6-9136-57c5cab826ee.png)

Settings page also not working which was working fine 1.3.x-dev:
![2017-01-26_1811](https://cloud.githubusercontent.com/assets/24757934/22354329/d2744096-e3f2-11e6-9559-28b05db69efe.png)

**Comment by smuzammilali** [comment]
Also please remove sensor parameter from:
Form\Field\Map.php
Line 19:             $js = 'https://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false&key='.env('GOOGLE_API_KEY');

![2017-01-26_1930](https://cloud.githubusercontent.com/assets/24757934/22356277/18224e98-e3fe-11e6-88d1-f681725b9668.png)

**Comment by smuzammilali** [comment]
Any updates coming for these issues?

**Comment by z-song** [comment]
fixed now, just update version 1.4.x-dev

**Comment by smuzammilali** [comment]
Thanks problems are fixed!
