### ISSUE TITLE
form表单中选填可为空时建议不使用数据库置null的方法

### ISSUE THREAD

**Issue by donallin** [z-song/laravel-admin#3653]
- Laravel-admin: 1.7.2

### Description:
![image](https://user-images.githubusercontent.com/5716754/61342927-8a3b5280-a87e-11e9-898c-073686109754.png)
其实往往在数据库中是不会设置字段为null，且会赋予一个默认值类似空字符串；但是此时如果传一个null值过去数据库就会报错，这里有没有更好的设置方法

**Comment by junsonw** [comment]
Form::init(function (Form $form) {
    $form->saving(function (Form $form) {
        $request = request()->all();
        if($request)foreach($request as $key => $value){
            if(empty($value)){
                $form->$key = '';
            }

        }
    });
});
