### ISSUE TITLE
删除某个数据时，如何删除与其关联的数据

### ISSUE THREAD

**Issue by LZXprogrammer** [z-song/laravel-admin#3654]
- Laravel Version: 5.5
- PHP Version: 7.2.5
- Laravel-admin: 1.6.10

### Description:
我的用户表分为两个，用户主表和用户子表，使用 laravel-admin 的默认删除，当删除用户时，希望也能删除对应用户子表的数据，

### Steps To Reproduce:
我的想法是自定义一个按钮，把原先的删除按钮禁用，然后在 Extensions 里写一个操作类，不知道有没有人遇到过这样的问题，或者说作者有关联数据删除的方法吗？

**Comment by z-song** [comment]
不要搞这么麻烦

https://learnku.com/docs/laravel/5.8/eloquent/3931#events

**Comment by LZXprogrammer** [comment]
明白了，感谢
