### ISSUE TITLE
How to determine form is saving or updating

### ISSUE THREAD

**Issue by sahadatfci** [z-song/laravel-admin#3656]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.6

### Description:
Hi is there any way to determine form is saving or updating??

I want to trigger an event when a new record is saving. but don't want to trigger when updating.

**Comment by anditsung** [comment]
```
protected function form($edit = false, $id = 0)
{}
```

```
public function edit($id, Content $content)
    {
        return $content
            ->header('Employee')
            ->description('Edit')
            ->body($this->form(true, $id)->edit($id));
    }
```

using this, you will know is updating or saving
