### ISSUE TITLE
上传图片问题和删除图片问题

### ISSUE THREAD

**Issue by chenzhulin** [z-song/laravel-admin#3659]
- Laravel Version: 5.7
- PHP Version:7.1.3
- Laravel-admin: 1.7

 Description:
上传图片问题，上传图片的时候如果uploads中有相同名字的图片，会出现修改了他会保存某些以前的图片，不会保存当前你修改的图片
后台已经上传的图片不能删除，只能替换。今天要删除不需要的图片时发现的这个问题

**Comment by chenjiabin** [comment]
发现同样的问题，请问解决了吗

image: (binary)
后台已经上传的图片不能删除，只能替换

**Comment by chenzhulin** [comment]
没有，后面我删除了重新上传的




------------------ 原始邮件 ------------------
发件人: "chenjiabin"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 上午9:57
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>;
抄送: "菜鸟"<2655310177@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [z-song/laravel-admin] 上传图片问题和删除图片问题 (#3659)




发现同样的问题，请问解决了吗
 
image: (binary)
 后台已经上传的图片不能删除，只能替换

**Comment by chenzhulin** [comment]
我前几天想到了，你可以在后台控制器中重写它的编辑方法，实现图片删除




------------------ 原始邮件 ------------------
发件人: "chenjiabin"<notifications@github.com>;
发送时间: 2019年7月24日(星期三) 上午9:57
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com>;
抄送: "菜鸟"<2655310177@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [z-song/laravel-admin] 上传图片问题和删除图片问题 (#3659)




发现同样的问题，请问解决了吗
 
image: (binary)
 后台已经上传的图片不能删除，只能替换

**Comment by chenjiabin** [comment]
->removable()  文档中是有删除的

**Comment by chenjiabin** [comment]
$form->image('ad_picture_code', __('Ad code'))->removable();
