### ISSUE TITLE
安装了新的样式material-ui，现在想要改回原来laravel-admin默认的样式，该怎么处理

### ISSUE THREAD

**Issue by donallin** [z-song/laravel-admin#3660]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.7.2

### Description:
安装了新的样式material-ui，现在想要改回原来laravel-admin默认的样式，该怎么处理

**Comment by jxlwqq** [comment]
```bash
composer remove jxlwqq/material-ui
rm -rf public/vendor/laravel-admin-ext/material-ui
```
最后把 config/admin.php 的插件配置删掉

**Comment by donallin** [comment]
感谢，我直接在composer文件中把相关项去掉，composer update就可以了哈
