### ISSUE TITLE
how to catch the url change event?

### ISSUE THREAD

**Issue by HughBliss** [z-song/laravel-admin#3663]
- Laravel Version: 5.8.*
- PHP Version: 7.1.3
- Laravel-admin: ^1.7

### Description:
I'm trying to initialize js code that should only work on a specific page. because laravel-admin is a SPA, all custom js code is executed only once and it will not be executed when you move from another page. 
how can I solve this problem ?

**Comment by y-oksaku** [comment]
Using this, you can catch page load complete event. 

```javascript
$(document).on('pjax:complete', () => {
    // write code
});
```
