### ISSUE TITLE
本项目代码有一些使用了 PHP7.1 及以上的新特性，但 composer.json 的 PHP 版本仍然是 >7.0

### ISSUE THREAD

**Issue by licxisky** [z-song/laravel-admin#3668]
- Laravel Version: null
- PHP Version: 7.2
- Laravel-admin: master

### Description:
本项目代码有一些使用了 PHP7.1 及以上的新特性，但 composer.json 的 PHP 版本仍然是 >7.0

### Steps To Reproduce:
src/Actions/Response.php line 88

**Comment by z-song** [comment]
已提交修复
