### ISSUE TITLE
Laravel 5.4: FatalError Method Illuminate\View\View::__toString()

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#367]
on form closure throwing this error:
![2017-01-27_1610](https://cloud.githubusercontent.com/assets/24757934/22387886/c79ae260-e4ab-11e6-95d4-5d581079b898.png)

**Comment by z-song** [comment]
Use `$this->form()->render()` instead `$this->form()` to avoid exception like `Illuminate\View\View::__toString()`.

**Comment by smuzammilali** [comment]
Your solution doesn't work:
![2017-02-04_1548](https://cloud.githubusercontent.com/assets/24757934/22621460/42e5c2cc-eaf2-11e6-9add-9f537488ccfb.png)


Problem fixed after remove password confirmation field, problem is because of closure:
![2017-02-04_1549](https://cloud.githubusercontent.com/assets/24757934/22621465/6683d2d2-eaf2-11e6-81f8-4a18bbf6c59c.png)

**Comment by smuzammilali** [comment]
Just to mention its after:
update composer update encore/laravel-admin:1.4.x-dev

Further detaial:
![2017-02-04_1631](https://cloud.githubusercontent.com/assets/24757934/22621686/8da2074e-eaf7-11e6-9456-90373ad926db.png)

**Comment by z-song** [comment]
Try to dump `$form->model()` or `$form->model()->password` and see what is output

**Comment by smuzammilali** [comment]
I have figure out that default closure functionality was not define under Field.php,

So I just copied Field.php from 1.3.x-dev to my 1.4.x-dev and it's fix the problem.

**Comment by smuzammilali** [comment]
After 1.4.x-dev update problem is fixed now!
