### ISSUE TITLE
上传图片成功后，在编辑页面，点击删除图标删除图片，不会成功

### ISSUE THREAD

**Issue by liuyi61123** [z-song/laravel-admin#3671]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.7.2

### Description:
使用$form->multipleFile()上传图片，在编辑页面，点击删除图标删除图片，不会成功
提示：
`SyntaxError: Unexpected token < in JSON at position 0`

**Comment by zzr7** [comment]
我也报这个错，请问你解决了吗？

**Comment by bjbjbjbj** [comment]
> * Laravel Version: 5.8
> * PHP Version:7.2
> * Laravel-admin: 1.7.2
> 
> ### Description:
> 使用$form->multipleFile()上传图片，在编辑页面，点击删除图标删除图片，不会成功
> 提示：
> `SyntaxError: Unexpected token < in JSON at position 0`
> 
> ### Steps To Reproduce:

能解决么？
