### ISSUE TITLE
Also publish migration and views?

### ISSUE THREAD

**Issue by royduin** [z-song/laravel-admin#368]
Currently `php artisan migrate:refresh` is throwing errors because it can't find the migration file from laravel-admin, maybe it's an idea to make the migration publishable with `php artisan vendor:publish`?

And maybe publish the views too so they can easily be modified?

**Comment by jonphipps** [comment]
One thing about the views, you can override any of the view files by putting a replacement file in ```resources/views/admin``` following the structure of ```vendor/encore/laravel-admin/views```. Laravel will try to load anything in that directory first as long as it's namespaced with ```admin::```.

...and there's only one migration file in ```/vendor/encore/laravel-admin/migrations``` so it's easy enough to copy it if you need to.

**Comment by ihsanberahim** [comment]
Hi @jonphipps, I glad to hear that we can override all views but we need to put the replacement files in `resources/views/vendor/admin` instead of `resources/views/admin`. Just the missing `vendor` in the path. ;)

**Comment by alpharameeztech** [comment]
@jonphipps where should i change the namespace? as i need  to change the layout of the Views file.

**Comment by alpharameeztech** [comment]
@ihsanberahim I need to publish the views folder from the Laravel admin vendor directory. I have tried creating the same views folder structure under my Resources folder but Laravel couldn't recognize it.

**Comment by llxx-lord-xxll** [comment]
Same requirement is also needed for me

**Comment by z-song** [comment]
@alpharameeztech @llxx-lord-xxll 
You can change the namespace by adding `app('view')->prependNamespace('admin', resource_path('views/admin'));` to `AppServiceProvider.php`

**Comment by alpharameeztech** [comment]
@llxx-lord-xxll well i figured that out. Just copy and vendor/laravel-admin/resources/view folder and paste it over project-root-dir/resources/views/vendor/laravel-admin

**Comment by llxx-lord-xxll** [comment]
Thanks to both of you @alpharameeztech @z-song
