### ISSUE TITLE
批量操作表单无法使用下拉联动

### ISSUE THREAD

**Issue by howth** [z-song/laravel-admin#3681]
- Laravel Version: 5.5
- PHP Version:7.3
- Laravel-admin: 1.7.3

### Description:

通过自定义工具类中的 form 方法定义下拉与下拉联动，下拉触发后无法同步联动下拉框。

## 代码：

```php
    public function form()
    {
        $this->select('supplier_id', __('供应商'))
            ->options('supplier/selector')
            ->load('supplier_storage_id', 'supplier/storage/selector');
        $this->select('supplier_storage_id', __('供应商仓库'))->options([]);
    }
```

## 原因排查：

`encore/laravel-admin/src/Form/Field/Select.php` 中的 load 方法对联动目标对象使用了以下选择器：

```javascript
var target = $(this).closest('.fields-group').find(".$class");
```

但是在批量操作的表单弹窗中并不存在 `class` 为 `fields-group` 的元素，导致联动读取的数据无法正确赋值给联动目标下拉框。

**Comment by wcxxxxxx** [comment]
怎么解决呢

**Comment by howth** [comment]
> 
> 
> 怎么解决呢

emmm。已经发了 PR，不过我觉得不是最好的办法（不过 PR 至今没动静）#3685

**Comment by kaodouqifei** [comment]
用jquery把class手动加上去吧
Admin::script("$('.modal-dialog .modal-body').addClass('fields-group')");

**Comment by howth** [comment]
> 
> 
> 用jquery把class手动加上去吧
> Admin::script("$('.modal-dialog .modal-body').addClass('fields-group')");

我提了个 PR 就这么处理的，然而 PR 完全没有回应，现在官方版本都迭代两个版本了，这个问题还没解决_(:з」∠)_

**Comment by howth** [comment]
> 
> 
> 用jquery把class手动加上去吧
> Admin::script("$('.modal-dialog .modal-body').addClass('fields-group')");

不失为一个好办法_(:з」∠)_   我提的 PR 都好多个月过去了都没回应，现在都迭代两个版本了，这问题依然存在_(:з」∠)_

**Comment by kaodouqifei** [comment]
行吧，现在官方好多issues都不管
