### ISSUE TITLE
更新后出现  Call to undefined method Encore\Admin\Admin::favicon()

### ISSUE THREAD

**Issue by Ciroygo** [z-song/laravel-admin#3683]
- Laravel Version: 5.8
- PHP Version:7.2.8
- Laravel-admin: 1.7.4

### Description:
更新之后出现
Call to undefined method Encore\Admin\Admin::favicon()

![WX20190724-142125](https://user-images.githubusercontent.com/13675974/61769878-5b911f00-ae1e-11e9-80a2-c0b52a096d56.png)

**Comment by Ciroygo** [comment]
已经解决，是我自己的问题，添麻烦了

**Comment by zs1211** [comment]
请问下怎么解决的，我也遇到了这个问题

**Comment by zs1211** [comment]
由于每个版本的静态资源或者语言包都有可能会有更新，所以升级版本之后最好运行下面的命令
```
// 强制发布静态资源文件
php artisan vendor:publish --tag=laravel-admin-assets --force

// 强制发布语言包文件
php artisan vendor:publish --tag=laravel-admin-lang --force

// 清理视图缓存
php artisan view:clear
```

**Comment by jsonlove-cc** [comment]
你好请问怎么解决的
