### ISSUE TITLE
quickCreate? How to?

### ISSUE THREAD

**Issue by vlados** [z-song/laravel-admin#3687]
### Description:
I've noticed HasQuickCreate trait in the last commits. That's pretty cool if you can supply with quick documentation how to use it?
https://github.com/z-song/laravel-admin/search?q=quickcreate&unscoped_q=quickcreate

**Comment by z-song** [comment]
This is a new feature in v1.7.3. Due to lack of time, updating English documents may be delayed.

Now I have added the documentation.  https://laravel-admin.org/docs/#/en/model-grid-quick-create

Also see the changelog here https://laravel-admin.org/docs/#/en/changelog/v1.7.3
