### ISSUE TITLE
Separate migrations for releases

### ISSUE THREAD

**Issue by vlados** [z-song/laravel-admin#3688]
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-admin: 1.7.4

### Description:
I am using for some projects laravel admin since 1.4 and update regularly and I've encountered an error that permissions column in the menu is missing. When searched for the problem I've noticed that you are updating the main migration [database/migrations/2016_01_04_173148_create_admin_tables.php](https://github.com/z-song/laravel-admin/commits/1167c4860c99de5d663ea353e979e954eccecfce/database/migrations/2016_01_04_173148_create_admin_tables.php).
I think that is wrong. Why not use separate migrations by version for example and everybody can update his file and database?

**Comment by z-song** [comment]
I will pay attention to it in next versions.

Thanks！
