### ISSUE TITLE
Grid里多个actions时会生成相同的.grid-row-action-,临时修改方案，希望作者修改下

### ISSUE THREAD

**Issue by tickwudi** [z-song/laravel-admin#3697]
- Laravel Version: 5.5.*
- PHP Version:7.1.16
- Laravel-admin: 1.7.5

### Description:
Grid里多个actions时会生成相同的.grid-row-action-XXXXXX
导致问题就是我点击编辑或查看触发-》删除或者复制（随机的，也可能全部是删除）
我临时修改了Encore\Admin\Actions\Action.php的makeSelector
`
public static function makeSelector($class, $prefix)
    {

        if (!isset(static::$selectors[$class])) {
            //Log::info('get_called_class():'.$class);
            static::$selectors[$class] = $prefix.uniqid(mt_rand(10000,90000));
        }

        return static::$selectors[$class];
    }

`

**Comment by z-song** [comment]
@tickwudi 参考你的方式提交了修复。
