### ISSUE TITLE
[HELP] jQuery UI is conflicting with laravel-admin

### ISSUE THREAD

**Issue by HughBliss** [z-song/laravel-admin#3699]
- Laravel Version: 5.8.*
- PHP Version: 7.1.3
- Laravel-admin: ^1.7

### Description:
We are trying to connect jQuery UI to the project.
To do this, make changes to the file app/Admin/Bootstrap.php:

```
Encore\Admin\Form::forget(['map', 'editor']);

Admin::css('/admin/css/jquery-ui.css');
Admin::js('/admin/js/jquery-ui.js');

Admin::css('/admin/css/app.css');
Admin::js('/admin/js/app.js');
```
![image](https://user-images.githubusercontent.com/28117613/61862484-44116f00-aece-11e9-9a71-fd37612a291e.png)

**Comment by z-song** [comment]
jquery-ui.js needs to be loaded before bootstrap.min.js, you can use `Admin::headerJs('/admin/js/jquery-ui.js');` to put it in header section.
