### ISSUE TITLE
404 error

### ISSUE THREAD

**Issue by ltreer** [z-song/laravel-admin#37]
php artisan admin:install
之后访问 http://localhost/admin/ 出现 404

**Comment by z-song** [comment]
当前laravel服务启动了吗？首页访问url是多少？

**Comment by ltreer** [comment]
http://xx.com 启动正常 输出 laravel 5
http://xx.com/admin  404
是不是 需要 在 Http/route.php里面还要配置下？

**Comment by z-song** [comment]
跑一下artisan命令 看看路由列表

**Comment by ltreer** [comment]
| GET|HEAD                       | admin                                                    |                                | App\Admin\Controllers\HomeController@index            | web,admin.auth,admin.pjax |
看情况是 走进来了

**Comment by z-song** [comment]
http://xxx.com/admin/auth/login  能访问吗？

**Comment by ltreer** [comment]
不行，直接在 admin/route.php 里面 配置echo 也没效果

**Comment by z-song** [comment]
如果没加载App/Admin/routes.php的话，路由表里面就不会有admin的

laravel版本呢？

**Comment by ltreer** [comment]
Laravel Framework version 5.1.41 (LTS)

**Comment by z-song** [comment]
不好意思 dev-master版本只支持laravel5.2

5.1版本可以用1.1分支安装 composer require encore/laravel-admin "1.1.x-dev"

**Comment by ltreer** [comment]
没事，也是我不熟悉，装个5.2在 试试，多谢，有问题再请教

**Comment by ltreer** [comment]
L53 也出来 ，楼主 与时俱进啊

**Comment by z-song** [comment]
ok 正式版已经发布了吗？ 等有时间了再做个兼容

**Comment by ltreer** [comment]
刚发布的吧，想装L52，结果：Laravel Framework version 5.3.2

**Comment by z-song** [comment]
laravel 5.3安装:

`composer require encore/laravel-admin "1.3.x-dev"`

**Comment by ltreer** [comment]
试了试L53，还是404

**Comment by z-song** [comment]
刚刚用laravel 5.3.4安装测试过  没有重现你的问题。

**Comment by ltreer** [comment]
看nginx错误日志，/admin的请求 访问去了public目录下（/opt/upgrade/public/admin），这个是不是说哪里需要配置下路由？

**Comment by ltreer** [comment]
![image](https://cloud.githubusercontent.com/assets/20695108/18083727/effe92ba-6ed6-11e6-8aaa-cf482e334ac1.png)

**Comment by z-song** [comment]
你需要在nginx里面相应的server加一下配置：
`
location / {
    try_files $uri $uri/ /index.php?$query_string;
}
`

**Comment by ltreer** [comment]
可以了，多谢，原来是laravel没配置好

**Comment by z-song** [comment]
欢迎多提意见和反馈，欢迎star😁

**Comment by wumeihk** [comment]
@ltreer 我也遇到同样的404问题，请问你是laravel哪里的配置没配好导致的，然后解决了的
