### ISSUE TITLE
[HELP] Class admin.auth does not exist

### ISSUE THREAD

**Issue by serzhiio** [z-song/laravel-admin#370]
Hi, after laravel upgrade to 6.4 strange error appears:
ReflectionException in Container.php line 681: Class admin.auth does not exist

Please, help to find out what's wrong.

**Comment by serzhiio** [comment]
Removed 1.3.x version and installed 1.4.x-dev. Error disappeared. But now i've faced with bad ajax requests when deleting items from grid. All requests goes to: "http://admin/comments/7" without domain specified.

**Comment by serzhiio** [comment]
Found a bug in "/{$this->getResource()}/". First slash not needed here, it couses url like "//admin/comment/".
`$('.grid-row-delete').click(function() {
    var id = $(this).data('id');
    if(confirm("{$confirm}")) {
        $.post('/{$this->getResource()}/' + id, {_method:'delete','_token':'{$token}'}, function(data){

            $.pjax.reload('#pjax-container');

            if (typeof data === 'object') {
                if (data.status) {
                    toastr.success('{$successMsg}');
                } else {
                    toastr.error('{$faildMsg}');
                }
            }
        });
    }
});`

**Comment by z-song** [comment]
Fixed now, update this package:
`composer update encore/laravel-admin:1.4.x-dev`
