### ISSUE TITLE
$actions->add();不存在

### ISSUE THREAD

**Issue by 377123** [z-song/laravel-admin#3703]
- Laravel Version: #.#.#
- PHP Version: 7.2
- Laravel-admin: #.#.#   1.7

### Description:
        $grid->actions(function ($actions) {
//            $actions->disableDelete();
//            $actions->disableEdit();
//            $actions->disableView();
            $actions->add(new VerifyAction());
        });
$actions->add();不存在
 $actions->append() 不能转换为字符串

**Comment by z-song** [comment]
https://laravel-admin.org/docs/zh/model-grid-custom-actions  翻到最下面看
