### ISSUE TITLE
升级最新版本后, 切换到手机模式头部导航栏会遮挡,不正确显示

### ISSUE THREAD

**Issue by Chen-Zhitong** [z-song/laravel-admin#3704]
- Laravel Version: #.#.#
- PHP Version:7.2
- Laravel-admin: 1.7.3

### Description:
升级最新版本后, 切换到手机模式显示头部导航栏会遮挡,不正确显示

**Comment by FirEarly** [comment]
我也遇到，我把
header.blade.php文件
中18行备注了就ok了，暂时没发现有bug。
        
        {!! Admin::getNavbar()->render('left') !!}

**Comment by FirEarly** [comment]
> * Laravel Version: #.#.#
> * PHP Version:7.2
> * Laravel-admin: 1.7.3
> 
> ### Description:
> 升级最新版本后, 切换到手机模式显示头部导航栏会遮挡,不正确显示
> 
> ### Steps To Reproduce:

我也遇到，我把
header.blade.php文件
中18行备注了就ok了，暂时没发现有bug。

        
        {!! Admin::getNavbar()->render('left') !!}
