### ISSUE TITLE
Call to undefined method Encore\Admin\Form::registerBuiltinFields()

### ISSUE THREAD

**Issue by AnnaNovitskaya1990** [z-song/laravel-admin#3705]
- Laravel Version: v5.7.28
- PHP Version:  7.2.15
- Laravel-admin: > 1.7

### Description:
Call to undefined method Encore\Admin\Form::registerBuiltinFields();

### Steps To Reproduce:
after composer update

Help me please

**Comment by z-song** [comment]
Fixed in 84753d4

It is recommended not to use `Admin::form(function(){});` to build your form,  This method will be deprecated in a future version.
