### ISSUE TITLE
我发现一个bug，请作者查看！谢谢！

### ISSUE THREAD

**Issue by wangmingxv** [z-song/laravel-admin#371]
form组件中的开关选择控件配置中的value参数不启作用
```php
$states = [
    'on'  => ['value' => 1, 'text' => '打开', 'color' => 'success'],
    'off' => ['value' => 0, 'text' => '关闭', 'color' => 'danger'],
];

$form->switch($column[, $label])->states($states);
```
我感觉SwitchField.php文件中的50行`$this->value = ($key == 'on') ? 'on' : 'off';`有错误！请作者查看更正！谢谢！

**Comment by z-song** [comment]
没有遇到这个问题，数据库存储的值就是两个状态设置的`value`值

**Comment by zxy198717** [comment]
@z-song 按照 $states 的定义，里面有个key是value, 是不是数据库存储value定义的值会通用一点? 比如数据库可以用0和1
