### ISSUE TITLE
文档更正： model-grid-column-display#列展开

### ISSUE THREAD

**Issue by mr-cn** [z-song/laravel-admin#3712]
- Laravel Version: #.#.#
- PHP Version: 
- Laravel-admin: #.#.#

### Description:

列展开：http://www.laravel-admin.org/docs/zh/model-grid-column-display#%E5%88%97%E5%B1%95%E5%BC%80

```
use Encore\Admin\Widgets\Table;

$grid->column('title', '标题')->expand(function ($model) {

    $comments = $model->comments()->take(10)->get()->map(function ($comment) {
        return $comment->only(['id', 'content', 'created_at']);
    });

    return new Table(['ID', '内容', '发布时间'], $comments->toArray());
});
```

示例代码中第五行` ->comments()->take(10)->get()->map`这里 take后不应该跟get

不然会造成`Too few arguments to function Illuminate\Support\Collection::get(), 0 passed`错误

不过我也不清楚会什么会这样

**Comment by z-song** [comment]
已修复，谢谢
