### ISSUE TITLE
不用embeds怎么给单个json节点字段赋值？

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3713]
- Laravel-admin: 1.7.5

### Description:
由于业务更改，需要把之前存在json字段里的一个节点单独放在靠前的位置去编辑，之前是放表单最后一个embeds里的，如下尝试发现修改没问题，但每次新增数据时无法赋值：
```php
$form->text('data->location', '位置')->rules(['required']);
```
在creating里打印对象，发现也没有data字段，而request里是有如下数据：
![image](https://user-images.githubusercontent.com/224353/62001995-2a6e6280-b12e-11e9-98e9-15e640a534f9.png)

**Comment by ShuiPingYang** [comment]
这里是有bug,我也碰到这个问题了,新增是null,但是修改的时候可以.
xxx\vendor\encore\laravel-admin\src\Form.php
![image](https://user-images.githubusercontent.com/22534808/105659312-6b9e2900-5f03-11eb-9693-a6040c403e04.png)

**Comment by stu640978** [comment]
@ShuiPingYang 小弟也碰到同樣的問題，請問您是怎麼解決這個bug的呢?
