### ISSUE TITLE
多层一对多时如何制作表单？

### ISSUE THREAD

**Issue by fortheday001** [z-song/laravel-admin#3717]
比如有一个需求：
添加一个课程-》课程中要添加多个周-》周里面要添加多个课程-》课程里面有多个视频组成。

这个功能中有 课程表、课程周表、课程周课程表、课程周课程视频四张表，关系都是一对多。
请问这时如何解决？

**Comment by endachao** [comment]
老哥问题解决了吗？我这遇到同样的问题
