### ISSUE TITLE
既然有$form->editing了，能再有一个$form->creating？

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#3720]
- Laravel-admin: 1.7.5

### Description:
比如在tools中需要针对新增和编辑做不同的处理，我把Tools放到了editing事件回调里去执行的，但这导致在新增数据时又不能被执行，所以能加一个creating吗？
```php
$form->editing(function(Form $form) {
            $form->tools(function(Form\Tools $tools) use ($form) {
                        // 通过 $form->model()->xxx 取到当前编辑的对象进一步 append 一些针对性操作
            });
});
```

**Comment by z-song** [comment]
增加了两个方法`isCreating`、`isEditing` 两个方法来判断页面

**Comment by terranc** [comment]
> 增加了两个方法`isCreating`、`isEditing` 两个方法来判断页面

不过感觉这个根据route信息去判断的方式不完美，还是不如editing事件这种好，比如一个Form不是用于create和edit方法时，自己自定义的其它操作里就不管用了
