### ISSUE TITLE
后台grid展示

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#3724]
- Laravel Version: 5.5.#
- PHP Version:
- Laravel-admin: 1.6.1

### Description:
后台展示能不翻页，自行按照鼠标滚动，类似于瀑布流那样的吗

### Steps To Reproduce:
麻烦问一下，后台展示能不翻页，自行按照鼠标滚动，类似于瀑布流那样的吗

**Comment by z-song** [comment]
不支持

**Comment by YangZhengHuan** [comment]
@z-song 我是在您的框架式进行了扩展，有什么建议吗，谢谢啦

**Comment by YangZhengHuan** [comment]
@z-song 好比您的show操作
