### ISSUE TITLE
分页搜索问题

### ISSUE THREAD

**Issue by jackDengqipeng** [z-song/laravel-admin#373]
在比如我在第三页点击搜索的时候，会携带页数过去，这样会导致数据无法出来，因为我搜索的结果可能没有3页那么多

**Comment by z-song** [comment]
已修复(1.3.x-dev) 谢谢提醒!

**Comment by lePig** [comment]
@z-song 这个问题在1.5又出现了啊 #2223

**Comment by Harrypoters** [comment]
@z-song 分页问题又出现啊
