### ISSUE TITLE
[QUESTION] How to make operation log to specific table

### ISSUE THREAD

**Issue by vonsogt** [z-song/laravel-admin#3730]
### Description:
I just wanna create an operation log in a specific table that I call from OperationLog where accessing 'path' so the table will show up

or

How to make own operation log table.

### Image
![image](https://user-images.githubusercontent.com/35516476/62101948-58d07700-b2c1-11e9-8717-4c87e5ae7b23.png)

**Comment by uacode** [comment]
You can change a table, see config/admin.php
database.operation_log_table

**Comment by vonsogt** [comment]
> You can change a table, see config/admin.php
> database.operation_log_table

I mean that I can filter some query from Admin_Operation_Log column 'path'

**Comment by hanachan1026** [comment]
I did something like this

```
protected function whateverHistory($id)
    {
        $grid = new Grid(new OperationLog());
        $url = Str::replaceFirst('/', '', route('whatever.update', $id, false));

        $grid->model()->where([
            ['method', '=', 'PUT'],
            ['path', '=', $url]
        ]);

        $grid->header(function ($query) {
            return '<h3 class="box-title">Whatever History</h3>';
        });

// and add to show method
public function show($id, Content $content)
    {
        return $content
            ->title($this->title())
            ->description($this->description['show'] ?? trans('admin.show'))
            ->body($this->detail($id))
            ->body($this->WhateverHistory($id));
    }
```

**Comment by vonsogt** [comment]
I replace /data/costumers, it says 

`"Route [{$name}] not defined."`

**Comment by vonsogt** [comment]
> I replace /data/costumers, it says
> 
> `"Route [{$name}] not defined."`

Okay, I defined the route name then I edit 
```
$grid-> column...
...
return $grid
```

But it not show any logs

**Comment by vonsogt** [comment]
> I did something like this
> 
> ```
> protected function whateverHistory($id)
> {
>         $grid = new Grid(new OperationLog());
>         $url = Str::replaceFirst('/', '', route('whatever.update', $id, false));
> 
>         $grid->model()->where([
>             ['method', '=', 'PUT'],
>             ['path', '=', $url]
>         ]);
> 
>         $grid->header(function ($query) {
>             return '<h3 class="box-title">Whatever History</h3>';
>         });
> }
> 
> // and add to show method
> public function show($id, Content $content)
> {
>         return $content
>             ->title($this->title())
>             ->description($this->description['show'] ?? trans('admin.show'))
>             ->body($this->detail($id))
>             ->body($this->WhateverHistory($id));
> }
> ```

Thanks for your solution. It's work for me now after doing some changes

**Comment by vonsogt** [comment]
After making any changes, then how to compare before edit and after

**Comment by uacode** [comment]
Php diff

**Comment by vonsogt** [comment]
Thanks
