### ISSUE TITLE
fixColumns cause batch action not working， fixColumns 导致批量操作按钮显示问题

### ISSUE THREAD

**Issue by parse-code** [z-song/laravel-admin#3736]
- Laravel Version: 5.8
- PHP Version: 7.2
- Laravel-admin: 1.7.3

### Description:
使用 `fixColumns` 后，在列表中选择不能触发显示批量操作按钮。

### Steps To Reproduce:

1. 使用 `$grid->fixColumns(1, -1);`
2. 在列表页面任意选中一列，应该出现批量操作按钮， 但是没有出现，但是点击全选后就会出现批量操作按钮。
![image](https://user-images.githubusercontent.com/350474/62117037-cdb9a600-b2ed-11e9-8e18-6b2e81edd017.png)
![image](https://user-images.githubusercontent.com/350474/62117065-d611e100-b2ed-11e9-9cb3-d8473fc590d0.png)

**Comment by z-song** [comment]
已提交修复，谢谢！
