### ISSUE TITLE
[Help] How can I create grid title edit links?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#374]
![2017-02-05_1943](https://cloud.githubusercontent.com/assets/24757934/22631440/64afe61e-ebdb-11e6-9e06-595b3016830b.png)

How can I access Page id under title column to that I can generate relevant edit URL

Can you also please show the code of the Inventory page where you use the edit links:
http://120.26.143.106/admin/sakila/inventory

**Comment by z-song** [comment]
```php
$grid->store_id('Store link')->value(function ($store_id) {
    return "<a href='/admin/sakila/stores/$store_id/edit'>store link</a>";
});
```
`store_id` is one column of `inventory` table.

If you have a column named `page_id` in this table, then get `page_id` in value callback:
```php
$grid->column('title')->value(function ($title) {
    return "<a href='/admin/users/pages/{$this->page_id}/edit'>$title</a>";
});
```

**Comment by smuzammilali** [comment]
Also how can I apply css property to any field like .class or #id?

I want to apply some jquery on select box to show particular tab only
For example:
![2017-02-05_2251](https://cloud.githubusercontent.com/assets/24757934/22634232/d556e5ec-ebf5-11e6-8a41-3956ff433351.png)

Select: Default show only Default tab
Select Agent Business Plan to show Default and Agent Business Plan and so on

**Comment by smuzammilali** [comment]
Can I use Box under page edit? so  I will load the particular box according to the page type?

Page hasOne Pagetype I would like to edit some extra values as per the selected page type.

**Comment by z-song** [comment]
You can use `Admin::script('')` to add script to current page.

**Comment by smuzammilali** [comment]
Can I apply custom class or id to the particular field in form?

For example:
$form->select('pagetype')->options($arrayOpt)->cssClass('testclass');
$form->select('pagetype')->options($arrayOpt)->tagId('testId');

**Comment by smuzammilali** [comment]
Never mind I found the solution using ->attribute()
