### ISSUE TITLE
数据表单，table类型的field赋值失败

### ISSUE THREAD

**Issue by ealiwood** [z-song/laravel-admin#3742]
- Laravel Version: 5.8.29
- PHP Version: 7.3.3
- Laravel-admin: 1.7.3

### Description:
数据表单使用data() 方法赋值，table类型的field无法成功赋值。admin:make 创建的控制器中的form方法是可以展示数据的。

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/22855571/62186499-15493c00-b399-11e9-907d-42668fbef55d.png)
![image](https://user-images.githubusercontent.com/22855571/62186508-1a0df000-b399-11e9-80b8-13c5b0e64e05.png)

**Comment by taobali32** [comment]
解决了吗, 我也遇到了, 调试了代码 发现 注入的表单不一样,然后调试未果.

**Comment by taobali32** [comment]
@z-song

**Comment by jehazXu** [comment]
同样的问题，请问解决了吗

**Comment by jehazXu** [comment]
@taobali32 @ealiwood  你们解决了没有？

**Comment by z-song** [comment]
@ealiwood @taobali32 @jehazXu  提交了修复，更新到dev-master分支即可

**Comment by rongtou** [comment]
@z-song 更新后，table不赋值默认值，就报错了
![table](https://user-images.githubusercontent.com/370443/66534721-ab43d480-eb49-11e9-8776-e0cbb3e6ac01.jpg)
![image](https://user-images.githubusercontent.com/370443/66534768-d8908280-eb49-11e9-89ca-ac0d444e8be8.png)

**Comment by vonsogt** [comment]
> @z-song 更新后，table不赋值默认值，就报错了
> ![table](https://user-images.githubusercontent.com/370443/66534721-ab43d480-eb49-11e9-8776-e0cbb3e6ac01.jpg)
> ![image](https://user-images.githubusercontent.com/370443/66534768-d8908280-eb49-11e9-89ca-ac0d444e8be8.png)

same, I got the same warning #4285

**Comment by hugh2113** [comment]
Is anyone fixed it ? i still has same problem
