### ISSUE TITLE
Print page

### ISSUE THREAD

**Issue by xn0ak** [z-song/laravel-admin#3745]
Hello,

How can I add a print button so that I can print the grid information?
I already have the button, but I'm having some difficulties creating the print page.

Thank you.

**Comment by vlados** [comment]
onclick="document.print()"

**Comment by xn0ak** [comment]
What I mean is print something like this:
<img width="419" alt="report-with-total" src="https://user-images.githubusercontent.com/7122663/62280168-4b42fa80-b443-11e9-9928-170429c9557c.png">

Is possible?

Thank you.

**Comment by z-song** [comment]
Not support yet

**Comment by vlados** [comment]
You can export the file to excel and convert it to pdf, or just create an print css
