### ISSUE TITLE
view prependNamespace not working

### ISSUE THREAD

**Issue by yuan1998** [z-song/laravel-admin#3748]
- Laravel Version: 5.8
- PHP Version: 7.3.4
- Laravel-admin: 1.7

### Description:
![image](https://user-images.githubusercontent.com/32232389/62264466-9b758900-b452-11e9-8e4f-221a32e6fc2a.png)
![image](https://user-images.githubusercontent.com/32232389/62264689-982ecd00-b453-11e9-808a-4b8a78d85574.png)

### Steps To Reproduce:
最开始复制出来修改footer.blade.php和添加了几个自定义文件,当时是生效了
印象中好像是后面卸载了 laravel-admin-material-ui 并运行了下面几行代码后就失效 (不完全确定)
footer.blade.php修改的部分没有了和自定义文件也没有引入了
```
$ php artisan config:clear
$ php artisan cache:clear
$ php artisan view:clear
```

**Comment by hanachan1026** [comment]
I have the same issue when it comes to logging in not as a default administrator but as a staff I created which has a staff role.

**Comment by hanachan1026** [comment]
So, `admin.permission` middleware is in a middleware group `admin`

the question is `prependNamespace()` only works for middleware `admin` not `admin.permission` ??

**Comment by hanachan1026** [comment]
I figured it out that if you have `admin` middleware included on your route group, it should work.

Please see `Encore\Admin\AdminServiceProvider'
