### ISSUE TITLE
表格字段太多，没有上下滚动， 点击不了提交按钮！

### ISSUE THREAD

**Issue by luochaovg** [z-song/laravel-admin#3751]
- Laravel Version: 5.8.29
- PHP Version:7.3.7
- Laravel-admin: ^1.7
### Description:
字段太多， 做字段刷选时，没有提交按钮。。

![image](https://user-images.githubusercontent.com/20222544/62344667-7f8ce880-b521-11e9-8b39-c91385405fff.png)

**Comment by z-song** [comment]
已修复
