### ISSUE TITLE
Laravel Admin 支持自己查库后传入 grid 么？

### ISSUE THREAD

**Issue by Chasers9527** [z-song/laravel-admin#3752]
- Laravel Version: 5.8.29
- PHP Version: 7.3
- Laravel-admin: 1.7

### Description:
我想自己查询库存信息后，再展示在前端，而不是我先 new model 后在进行 with 如果只用 with ，业务逻辑不可能只通过简单的 with 和 where 就得到我想要的数据的

**Comment by jqhph** [comment]
可以，文档有说明

**Comment by Chasers9527** [comment]
@jqhph  可一个给个地址么
