### ISSUE TITLE
如何实现控件联动

### ISSUE THREAD

**Issue by zhusaidong** [z-song/laravel-admin#3754]
不是select联动，是控件联动。
比如，下拉选择A时，C控件显示，选择B时，C控件隐藏。
文档翻了好几遍没找到。

**Comment by Chenjiajing** [comment]
同问

**Comment by Chenjiajing** [comment]
@z-song

**Comment by jqhph** [comment]
这个你自己写js控制不就好了

**Comment by jxlwqq** [comment]
```
Admin::script();
```

**Comment by zhusaidong** [comment]
@jqhph @jxlwqq 
不能单纯的用js显示隐藏，如果该控件是必填的，隐藏了会报错。
`An invalid form control with name='banner_url' is not focusable.`
