### ISSUE TITLE
Where is documentation admin:minify assets?

### ISSUE THREAD

**Issue by suryaadhisam** [z-song/laravel-admin#3755]
- Laravel Version: 5.8.*
- PHP Version:
- Laravel-admin: 1.7.2

### Description:
I want to minify my assets, why the documentation is gone?

**Comment by mehdi89** [comment]
I also need that documentation. Please let me know where can I find that?

**Comment by suryaadhisam** [comment]
@mehdi89 you can see the documentation [here ](https://laravel-admin.org/docs/#/en/minify-css-js)

**Comment by mehdi89** [comment]
> @mehdi89 you can see the documentation [here ](https://laravel-admin.org/docs/#/en/minify-css-js)

Thank you so much
