### ISSUE TITLE
縂管理員可見所有左側菜單 同時 不同角色可看見不同左側菜單 menu role permission

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#3757]
- Laravel-admin: 1.7.3

### Description:
控制左側菜單可見性只能通過 admin_menu 的 permission 字段進行設置嗎?
縂管理員的權限是 *, 若要實現題目的需求就需要增加 role_permission 的對應關係

假設有:
兩個菜單 menu_A, menu_B
三個用戶 user_A, user_B, user_Admin
三種權限 permission_A, permission_B, permission_Admin
三種角色 role_A, role_B, role_Admin
現要求 用戶 admin 能看見所有菜單, 用戶 A,B 只能看到各自的菜單, 則

1, 表 admin_menu
設置 menu_A 的 permission 為 permission_A
設置 menu_B 的 permission 為 permission_B
2, 表 admin_role_permissions
為 role_Admin 增加 permission_A 與 permission_B
為 role_A 增加 permission_A
為 role_B 增加 permission_B

除此之外是否有更簡單的方式解決某個菜單同時對縂管理員和其他角色可見的問題?

ps:所以, admin_role_menu 表的作用是?

@z-song

**Comment by yavana** [comment]
同问
