### ISSUE TITLE
latest version grid custom actions not showing

### ISSUE THREAD

**Issue by anditsung** [z-song/laravel-admin#3758]
- Laravel Version: 5.5.46
- PHP Version: 7.2.8
- Laravel-admin: 1.7.3

### Description:
custom actions not showing

using example from
https://laravel-admin.org/docs/#/en/model-grid-actions?id=custom-actions

### Steps To Reproduce:

**Comment by anditsung** [comment]
got new info from this
https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=old-version-compatible

**Comment by xuanchau99** [comment]
how to change action from ... to icon 
laravel admin 1.8
![image](https://user-images.githubusercontent.com/56724036/100248616-46765400-2f6e-11eb-8ccb-cf33fe9b10ae.png)

**Comment by SUXUMI** [comment]
ინ 

> how to change action from ... to icon
> laravel admin 1.8
> ![image](https://user-images.githubusercontent.com/56724036/100248749-6f96e480-2f6e-11eb-9266-42ff96174f64.png)
> 
> to
> 
> ![image](https://user-images.githubusercontent.com/56724036/100248616-46765400-2f6e-11eb-8ccb-cf33fe9b10ae.png)

In config/admin.php

line with code:
`'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,`

change to:

`'grid_action_class' => \Encore\Admin\Grid\Displayers\Actions::class,`

**Comment by xuanchau99** [comment]
> > how to change action from ... to icon
> > laravel admin 1.8
> > ![image](https://user-images.githubusercontent.com/56724036/100248749-6f96e480-2f6e-11eb-9266-42ff96174f64.png)
> > to
> > ![image](https://user-images.githubusercontent.com/56724036/100248616-46765400-2f6e-11eb-8ccb-cf33fe9b10ae.png)
> 
> In config/admin.php
> 
> line with code:
> `'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,`
> 
> change to:
> 
> `'grid_action_class' => \Encore\Admin\Grid\Displayers\Actions::class,`

Thank you, it's working. 
how to get the API function show, edit, delete, ... ?
