### ISSUE TITLE
form image 设置rules required, 编辑的时候会有个小问题

### ISSUE THREAD

**Issue by zxy198717** [z-song/laravel-admin#376]
```
$form->image('banner', "图片")->rules('required');
```
编辑的时候，如果不修改此字段，会报错:
```
The 图片 field is required.
```

**Comment by yang5664** [comment]
@zxy198717 因為在"編輯"的時候該field並"無填寫"又為"必填"，應該要判斷當前表單是否為"新增"或"編輯"，再設定"required"。

**Comment by zxy198717** [comment]
@yang5664 好的

**Comment by zxy198717** [comment]
@yang5664 这个我理解应该是把原来的值填上，减少不必要的判断。

**Comment by yang5664** [comment]
@zxy198717 把原本的值回填的話，不知道會不會造成跟圖片上傳的動作一樣，引發錯誤，可能要試一試。

**Comment by zxy198717** [comment]
@yang5664 方便的话，麻烦帮忙试一下。如果在编辑的时候不设置required，用户这时候删除图片提交，可能会产生异常数据。

**Comment by edwinhuish** [comment]
@z-song 建议不要对比原始数据并过滤没有修改的数据，可以避免这个bug。

**Comment by yang5664** [comment]
@zxy198717 我提供目前自己的做法，但不是很好，但請你參考看看
就目前"圖片" / "檔案"上傳使用 bootstrap-fileinput/js/fileinput.min.js，所以在src的File.php
有一段，當"檔案移除"後，會對"隱藏欄位"給值為"1"，所以我以這個為思路
```ruby
$("input.{$class}").on('filecleared', function(event) {
    $(".{$class}_action").val(1);
});
```
加上一段，當"檔案載入"後，給值為"0"
```ruby
$("input.{$class}").on('fileloaded', function(event) {
    $(".{$class}_action").val(0);
});
```
這一步蠻重要的，因為我把view image.blade.php的
```ruby
<input type="hidden" class="{{$class}}_action" name="{{$actionName}}" value="0"/>
```
改為，當value不為空時，值為0，否則為1(表示沒有檔案)
```ruby
<input type="hidden" class="{{$class}}_action" name="{{$actionName}}" value="{{empty($value)?'1':'0'}}"/>
```
然後在form saving的時候進行判斷，而不用required了
```ruby
            $form->saving(function ($form) {
                if ($form->image_url_action == '1') {
                    $error = new MessageBag([
                        'title'   => '請修正下列問題',
                        'message' => '缺少圖片',
                    ]);
                    return back()->with(compact('error'));
                }
            });
```

**Comment by zxy198717** [comment]
@yang5664 我在想这个是不是在框架的层面能解决掉，如果实在解决不掉，可以用你的这个方法.   @z-song 你怎么看?

**Comment by z-song** [comment]
在这个commit中 e31c8dcb，如果是编辑模式，就把`required`这个验证规则直接去掉了。

**Comment by zxy198717** [comment]
@z-song 测试了一下。正常情况下是可以的。但还有个小问题:
用户编辑的时候，删除了图片，但是没有点提交，而是直接返回了，这时候其实图片已经被删除了。如果这个是头像字段的话，就会导致这个用户没有头像了。

**Comment by edwinhuish** [comment]
单文件理应取消ajax delete

**Comment by lanhktc** [comment]
``

**Comment by taitin** [comment]
required_without  一樣會有這個問題~
也許也要加入 file.phpˋ中
