### ISSUE TITLE
使用新版的操作按钮时,想要定义Action的Auth操作权限,因为使用的/_handle_action_的方法,无法控制权限

### ISSUE THREAD

**Issue by Chen-Zhitong** [z-song/laravel-admin#3760]
- Laravel Version: 5.8.29
- PHP Version: 7.2
- Laravel-admin: 1.7.3

### Description:

使用新版的操作按钮时,想要定义Action的Auth操作权限,因为使用的/_handle_action_的方法,无法控制权限

**Comment by Chen-Zhitong** [comment]
不符合 RESTful , 想要权限控制还是只能自己写页面和提交操作了

**Comment by gotophp** [comment]
怎么解决的啊

**Comment by gotophp** [comment]
> 不符合 RESTful , 想要权限控制还是只能自己写页面和提交操作了

咋解决的 大佬

**Comment by Chen-Zhitong** [comment]
> 
> 
> > 不符合 RESTful , 想要权限控制还是只能自己写页面和提交操作了
> 
> 咋解决的 大佬
最后还是自己写的页面和提交操作
