### ISSUE TITLE
右上角批量删除操作不出现

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#3764]
- Laravel Version: 5.5.*
- PHP Version: 7.13
- Laravel-admin: 1.7.5

### Description:

升级到最新版本，右上角批量删除操作不出现
### Steps To Reproduce:
升级到最新版本，右上角批量删除操作不出现，未调用$grid->disableRowSelector();不知道是什么原因

**Comment by YangZhengHuan** [comment]
之前的版本是1.6.10，升级之后添加了
  'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,
同样不行

**Comment by YangZhengHuan** [comment]
报错信息如下：
contentconfig:2107 Uncaught TypeError: Cannot read property 'select' of undefined
    at HTMLInputElement.<anonymous> (contentconfig:2107)
    at Function.each (jQuery-2.1.4.min.js:2)
    at n.fn.init.each (jQuery-2.1.4.min.js:2)
    at HTMLInputElement.<anonymous> (contentconfig:2105)
    at HTMLInputElement.dispatch (jQuery-2.1.4.min.js:3)
    at HTMLInputElement.r.handle (jQuery-2.1.4.min.js:3)
    at Object.trigger (jQuery-2.1.4.min.js:3)
    at HTMLInputElement.<anonymous> (jQuery-2.1.4.min.js:3)
    at Function.each (jQuery-2.1.4.min.js:2)
    at n.fn.init.each (jQuery-2.1.4.min.js:2)
(anonymous) @ contentconfig:2107
each @ jQuery-2.1.4.min.js:2
each @ jQuery-2.1.4.min.js:2
(anonymous) @ contentconfig:2105
dispatch @ jQuery-2.1.4.min.js:3
r.handle @ jQuery-2.1.4.min.js:3
trigger @ jQuery-2.1.4.min.js:3
(anonymous) @ jQuery-2.1.4.min.js:3
each @ jQuery-2.1.4.min.js:2
each @ jQuery-2.1.4.min.js:2
trigger @ jQuery-2.1.4.min.js:3
F @ icheck.min.js:2
(anonymous) @ icheck.min.js:10
dispatch @ jQuery-2.1.4.min.js:3
r.handle @ jQuery-2.1.4.min.js:3

**Comment by YangZhengHuan** [comment]
![image](https://user-images.githubusercontent.com/29086696/62517209-78cfdf80-b859-11e9-9d9b-7b68c44a6da2.png)

**Comment by YangZhengHuan** [comment]
![image](https://user-images.githubusercontent.com/29086696/62517266-a0bf4300-b859-11e9-91f5-882bdeb0993a.png)

**Comment by YangZhengHuan** [comment]
![image](https://user-images.githubusercontent.com/29086696/62517345-d2d0a500-b859-11e9-93c0-e6dab5470e45.png)
右上角批量操作不出现，点击勾选处，点不动，出现报错信息

**Comment by YangZhengHuan** [comment]
compser更新提示升级到1.7.5，应该是没有指定版本号，默认更新最新版本，版本的bug吧

**Comment by YangZhengHuan** [comment]
指定版本1.7.3 和1.7.2仍然报错，更新版本到1.7.0之后，只不过右上角方框能出来，但是仍然点击报错，

**Comment by YangZhengHuan** [comment]
@zong
麻烦给予帮助，谢谢啦，我也尝试了很多

**Comment by YangZhengHuan** [comment]
通过继续尝试，版本降低到1.6.13,问题解决
![image](https://user-images.githubusercontent.com/29086696/62519677-a8351b00-b85e-11e9-8729-4c5c17a89762.png)

**Comment by JasonDurian** [comment]
遇到了同样的问题 希望不通过降低版本解决 @z-song

**Comment by YangZhengHuan** [comment]
@JasonDurian 哈哈，上面的过程是我给作者一个完整错误出现以及验证版本问题的过程，肯定不能通过减低版本来解决呀

**Comment by z-song** [comment]
@YangZhengHuan @JasonDurian 升级版本看文档中的注意事项  https://laravel-admin.org/docs/zh/upgrading#%E6%B3%A8%E6%84%8F%E4%BA%8B%E9%A1%B9

**Comment by JasonDurian** [comment]
已通过注意事项提及方法解决

**Comment by YangZhengHuan** [comment]
我的不行啊，之前我都仔细看了，我再次尝试一下吧

**Comment by YangZhengHuan** [comment]
@z-song 可以啦，之前错误的认为语言包和版本更新关系不大，谢谢啦
