### ISSUE TITLE
这个项目是不是更新的幅度太大了，扩展包没发现一个能用的，很难受 =_=

### ISSUE THREAD

**Issue by sunxiyuan** [z-song/laravel-admin#3776]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

**Comment by wzhih** [comment]
最近使用了一下，好多扩展其实都是依赖别人写的插件，但是，别人写的插件更新大版本了，admin扩展却一直没更新。。。用的很难受
