### ISSUE TITLE
[QUESTION] How to format date without return 01 Jan 1970 in $grid

### ISSUE THREAD

**Issue by vonsogt** [z-song/laravel-admin#3779]
- Laravel Version: 5.8
- PHP Version: 7.3.7
- Laravel-admin: 1.5.x

### Description:
I want to format date in the grid, but the null value will show 01 January 1970
how to make the default date to null

**Comment by vonsogt** [comment]
should add  type="reset" ?

**Comment by uacode** [comment]
```
$grid->updatet_at()->display(function ($date) {
   return !is_null($date) ? 'format date':'empty....';
});
```

**Comment by vonsogt** [comment]
> ```
> $grid->updated_at()->display(function ($date) {
>    return !is_null($date) ? 'format date':'empty....';
> });
> ```

It's same as call $grid->column('updated_at', trans('admin.updated_at));
but, i just want to format the date from "2019-08-07 00:00:00" to "17 Aug 2019" and the null date will not show 01 Jan 1970

**Comment by vonsogt** [comment]
Okay, I found the solution, Thanks @uacode

**Comment by vonsogt** [comment]
Some mistake, the code I have done returned today's date
```
$grid->column('finished_date', 'Finished Date')->display(function ($date) {
    return !is_null($date) ? $date : null;
});
```
Any suggestion?

**Comment by vonsogt** [comment]
Okay I found the another solution
```
$grid->column('finished_date', 'Finished Date')->display(function ($date) {
    return !is_null($date) ? date('d M Y', strtotime($date)) : null;
});
```
and thats work as well
