### ISSUE TITLE
filter的select能支持ajax吗?

### ISSUE THREAD

**Issue by zxy198717** [z-song/laravel-admin#378]
比如有这样一个场景:
在订单列表页，需要过滤某一用户所下订单，系统中可能存在上万个用户，如果把用户都展示出来不太友好。可否做像form的select一样的实现，支持ajax搜索?

**Comment by z-song** [comment]
暂不支持，有待实现

**Comment by z-song** [comment]
已提交到版本`1.3.x-dev`，使用：
```php
$filter->equal('user_id')->select('/api/users');
```

**Comment by zxy198717** [comment]
@z-song 这个可以在优化一下吗？form的select是可以预先放一下默认值的。filter的这个貌似不行，这样会导致，如果用户刷新页面，select会没有默认值。
另一种场景是： 
用户在会员列表，点击 `查看会员订单`，在订单页面也需要预先把 会员信息 填写到select里.
