### ISSUE TITLE
在config/admin.php 文件中，修改 prefix 的值，后出现404

### ISSUE THREAD

**Issue by moxuanyuan** [z-song/laravel-admin#3782]
- Laravel Version: 5.8.31
- PHP Version: 7.2.13
- Laravel-admin: 1.7.5

### Description:
我把laravel安装在子目录，按照https://github.com/z-song/laravel-admin/issues/2282 中的方法在config/admin.php 文件中，修改 prefix 的值，后出现404
最后只能通过修改``vendor/encore/larvel-admin/src/helpers.php`` 中的``admin_base_path``函数的返回值``return admin_asset( $prefix.'/'.$path);`` 来实现在子目录中打开laravel-admin

**Comment by artecfeng** [comment]
我添加上return admin_asset( $prefix.'/'.$path); 也不行
