### ISSUE TITLE
[QUESTION] How to make select option by ajax (Unauthorized)

### ISSUE THREAD

**Issue by vonsogt** [z-song/laravel-admin#3785]
- Laravel Version: 5.8.x
- PHP Version:7.x.x
- Laravel-admin: 1.5.x

### Description:
Based on https://laravel-admin.org/docs/#/en/model-form-fields?id=select
I want to apply ajax, but I put the API Controller at api.php it shows Unauthorized 

How to do that the right way?

**Comment by SmauelL** [comment]
I think you should put the API Controller at /app/Admin/routes.php

**Comment by vonsogt** [comment]
> I think you should put the API Controller at /app/Admin/routes.php

Thanks, it works
