### ISSUE TITLE
[Help] hasOne relational model not saving data on create/edit

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#379]
Model Page has this relation with Model Pagetype:
![2017-02-06_2309](https://cloud.githubusercontent.com/assets/24757934/22677599/de202932-ecc1-11e6-9b66-186b85a9af0c.png)

On the edit form having different tabs for Pagetype data and Default tab is for Page data:
![2017-02-06_2311](https://cloud.githubusercontent.com/assets/24757934/22677622/19d9ad36-ecc2-11e6-80bc-864b63eb0fa4.png)

I'm following this example of tabs for saving hasOne relation data:
http://120.26.143.106/admin/demo/users

But hasOne relational model data(eg: pagetypes.abp_commission) is not saving and getting no errors?

even under Form.php receiving submitted data including the Pagetype data but only Pagetype data is not saving?

Any clue?

**Comment by smuzammilali** [comment]
Also have some issues with Text editor:
![2017-02-06_2320](https://cloud.githubusercontent.com/assets/24757934/22677731/f20c6bb2-ecc2-11e6-84ab-27a81ab617a6.png)

It doesn't always load and without any errors on console, after refresh the page text editor automatically loads.

It happens all the time it not always loads properly needs a refresh to load the text editor.

**Comment by z-song** [comment]
How you import the editor assets?

**Comment by smuzammilali** [comment]
Problem is this render function its not loading the script content, once I refresh the content loads and editor works fine.
![2017-02-07_1324](https://cloud.githubusercontent.com/assets/24757934/22705252/d602b4d2-ed38-11e6-8d69-6c24b8f8bf4d.png)

**Comment by smuzammilali** [comment]
Getting this error on saving hasOne relation data:
![2017-02-07_1942](https://cloud.githubusercontent.com/assets/24757934/22718317/b5dec1f2-ed6d-11e6-8908-a27f423c7394.png)


Schema:
![2017-02-07_1944](https://cloud.githubusercontent.com/assets/24757934/22718356/f01200d2-ed6d-11e6-8020-17e7e5572f50.png)

**Comment by z-song** [comment]
I found that the relation method name is `pagetype`, but use it in form with `pagetypes.abp_commission`,  maybe try to use `pagetype.abp_commission`?

**Comment by smuzammilali** [comment]
yeah I have fix that problem and it was working fine on 1.3.x-dev but not working on 1.4.x-dev

**Comment by z-song** [comment]
Could you please show me the exception trace which could be found in `laravel.log`.

**Comment by z-song** [comment]
Another suggestion, put the extension view in `resource/view` is fine, no need to put it in directory of `laravel-admin` package.

**Comment by smuzammilali** [comment]
For the editor there is no problem in laravel.log, 
I have already tried loading view from my app instead from vendor.

The problem I have found is:
![2017-02-07_2111](https://cloud.githubusercontent.com/assets/24757934/22720689/43124272-ed7a-11e6-8b47-5657a8f3c195.png)

**Comment by z-song** [comment]
Have you tried download the tinymce package and require from local ?

**Comment by smuzammilali** [comment]
Yes I have tried this as well with no luck.

Can I render the this->script after cdn load? this will fix the problem

**Comment by z-song** [comment]
I have no idea about your problem.

Every script is wrappered by `$(function() {});`, and this ensure that your function is called once all the DOM elements of the page are ready to be used.

[integrate-ckeditor](https://github.com/z-song/laravel-admin/blob/master/docs/en/field-management.md#integrate-ckeditor) works fine for me, maybe try this?

**Comment by smuzammilali** [comment]
It's fixing probme $(function() {});

Instead issue is something else:
![2017-02-08_0028](https://cloud.githubusercontent.com/assets/24757934/22724671/cac5c5b6-ed95-11e6-9d54-cbb764ffff21.png)

As soon as I get alert(1); which is actually the content of alert.js Tinymce editor loads perfectly.

That means cdn is not loading on page visit until I refresh/reload the page.

**Comment by smuzammilali** [comment]
I don't know but there is something wrong with TinyMCE Editor,

I have changed to CK Editor and it start works perfectly.
