### ISSUE TITLE
前后台 session 冲突

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#3790]
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-admin: 1.7.3

### Description:

> 前后台session冲突
如果网站前台和管理后台在同一个Laravel项目中，并且在一个域名下，登录的时候可能会遇到前后台session冲突的问题，在版本v1.6.10之后修复了这个问题，先更新到v1.6.10以上，然后在config/admin.php的route.middleware上加上一个中间件admin.session即可

    'route' => [

        'middleware' => ['web', 'admin', 'admin.session'],

    ],

### Steps To Reproduce:
- 新建 Laravel 
- 安装 Laravel-admin
- 按照文档的 前后台 session 冲突解决办法, 
- 前台, 后台分别登入
- 后台退出, 则前台自动退出

**Comment by faydanube** [comment]
@z-song

**Comment by xianlinzhang** [comment]
网站前台和管理后台在同一个Laravel项目中，并且在一个域名下，后台退出, 则前台自动退出，因为共用一个cookie，是否有解决方法？ @faydanube @vlados

**Comment by xianlinzhang** [comment]
> 网站前台和管理后台在同一个Laravel项目中，并且在一个域名下，后台退出, 则前台自动退出，因为共用一个cookie，是否有解决方法？ @faydanube @vlados

```
<?php

namespace App\Http\Middleware;

use Closure;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Http\Response;

class ChangeSessionConfig
{
    /**
     * Handle an incoming request.
     *
     * @param Request $request
     * @param Closure(\Illuminate\Http\Request): (\Illuminate\Http\Response|\Illuminate\Http\RedirectResponse)  $next
     * @return Response|RedirectResponse
     */
    public function handle(Request $request, Closure $next)
    {
        $path_prefix = '';
        $path_arr = parse_url($request->url());

        if (array_key_exists('path', $path_arr) && ! empty($path_arr['path'])) {
            $path_prefix = explode('/',trim($path_arr['path'], '/'))[0];
        }

        if ($path_prefix==trim(config('admin.route.prefix'))){
            config(['session.cookie' => 'admin_session']);
        }

        return $next($request);
    }
}

```

加了个全局中间件，目前OK

> 网站前台和管理后台在同一个Laravel项目中，并且在一个域名下，后台退出, 则前台自动退出，因为共用一个cookie，是否有解决方法？ @faydanube @vlados

**Comment by 8108905** [comment]
laravel admin 不是用 admin:install 新建的 admin表 新建的用户吗？ 难道你前台 不是用的user吗
