### ISSUE TITLE
Edit page

### ISSUE THREAD

**Issue by xn0ak** [z-song/laravel-admin#3795]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

Hello, how can I change the fields only for edit page?
My code:
![Code_qpyDIwD1mZ](https://user-images.githubusercontent.com/7122663/62943490-80036a00-bdd2-11e9-8d56-77df88a27606.png)

This is for new record, but I don't want to use all the fields in the edit page.

Thank you for your help.

**Comment by vlados** [comment]
Use https://github.com/z-song/laravel-admin/blob/5ccba3f2673fa4c3c5645b00ddbfb487adc89fff/src/Form/Builder.php#L158

**Comment by vonsogt** [comment]
Try this
```
$isEdit = (substr(trim(request()->path(), '/'), -5) === '/edit') || !request()->isMethod('get');
if ($isEdit) {
    $form-> ....
}
```
Source from : #2127

**Comment by xn0ak** [comment]
Thank you, now it works.
Another question, is possible to get the id that i'm editing? Like $form->id or $id ?

Thank you for your help.

**Comment by ichynul** [comment]
```php
//...
$name_text = $form->text('name');
$somefield_text = $form->text('somefield');
//...
$form->editing(function($form)use($name_text){
    $name_text->readOnly();
    if ($form->model()->somefield == 'something') {
          $somefield_text->readOnly();
    }
});
```

**Comment by xn0ak** [comment]
Thank you very much. That worked.
