### ISSUE TITLE
form构建通过数据库表中不存在字段构建

### ISSUE THREAD

**Issue by z0921** [z-song/laravel-admin#3796]
- Laravel Version: 7.2.19
- PHP Version:5.5.47
- Laravel-admin: 1.7.5

### Description:
在构建form的时候我想使用multipleImage组件,但是数据库表中没有对应的字段,
我想通过setter 和 getter来使用一个虚拟的字段,我设置了对应的setter和getter,发现这样使用multipleImage组件可以正确的保存到数据,但是却无法加载保存的值
我尝试过在setter 和 getter代码中下断点,发现setter被正常触发了,但是getter却一直没有触发,导致multipleImage界面显示没有数据
请问是multipleImage不支持数据库表中不存在的字段这种用法么?
还是是个bug?
### Steps To Reproduce:
```php
$form->multipleImage('unknow_column'')->uniqueName();
```
setter 和 getter
```php
    public function setUnknowColumnAttribute($pictures)
    {
        $message='message';
        if (is_array($pictures)) {
            $m = json_decode($this->attributes[$message],true);
            $m['banners'] = $pictures;
            $this->attributes[$message] = json_encode($m);
        }
    }

    public function getUnknowColumnAttribute($s)
    {
        $message='message';
        return json_decode($this->attributes[$message], true)['banners'] ?: [];
    }
```

**Comment by z-song** [comment]
模型里面加上：
```php
protected $appends = ['unknow_column'];
```

**Comment by z0921** [comment]
感谢说明,建议把这个加入到form文档中,类似的这种构建不存在的字段的form需求应该还是蛮大的

**Comment by WenkeChen** [comment]
> 模型里面加上：
> 
> ```
> protected $appends = ['unknow_column'];
> ```

只能用这种方式吗？这样每次查询都会自动append，但是有的字段并不是在所有地方都需要，有没有手动append的方式？
