### ISSUE TITLE
非自增的主键，在form，create情况下怎么显示？

### ISSUE THREAD

**Issue by hsw409328** [z-song/laravel-admin#380]
非自增的主键，在form，create情况下怎么显示？
我是单独在model里设置的$primaryKey，因为不是自动增长的，需要人工手动填写，所以单独设置，但是在create情况下不显示。

**Comment by z-song** [comment]
create的时候，主键还没有生成，怎么显示？

**Comment by hsw409328** [comment]
我有一个字段，是一个编号，但是需要手动录入，不需要id来自动增长。这时候用grid，我需要强制把编号字段设置primaryKey，然后grid才可以显示出来。但是form里在create情况下就没法填写了？这个您看有没有什么办法强制显示吗？

**Comment by z-song** [comment]
你的主键是手动维护的？最好不要这样设置

**Comment by hsw409328** [comment]
嗯。是的，主键是手动的，我要修改表，全部增加id自增字段吗？这个有处理的方法吗？

**Comment by z-song** [comment]
建表的时候没有设置主键吗？

**Comment by hsw409328** [comment]
嗯。没有设置，其实我有一些表编号都是手动来输入的。如果没有处理方法，我就修改表，增加自增的主键，然后把这个编号当成一个普通的来处理，做个惟一设置。

**Comment by z-song** [comment]
建议增加一个自增的主键

**Comment by z-song** [comment]
```sql
ALTER TABLE `table_name` ADD id INT PRIMARY KEY AUTO_INCREMENT;
```

**Comment by hsw409328** [comment]
嗯。好的，谢谢您的回复。

**Comment by hzysoft** [comment]
遇到同样的问题，因为有些表确实不需要自增ID，但又需要create的时候手工输入，怎么解决，盼复！
这种情况会经常存在的，比如配置表，错误代码表.....

**Comment by z-song** [comment]
@hzysoft 

https://stackoverflow.com/questions/840162/should-each-and-every-table-have-a-primary-key

可以参考一下大家的讨论，总结一下就是，给每个表设置自增主键是强烈推荐的。

**Comment by alanchen365** [comment]
@z-song 
正常应该是这样的没错，可有些时候表已经被创建好了，或者是领导创建的表，自己没权限修改的时候就很尴尬了。

**Comment by jesse7866** [comment]
在操作一些老系统的数据库时，那些表没有主键，或主键不自增(如uuid)，

新增数据时就很尴尬，只能在saving里截断并修改了。

**Comment by slow-is-fast** [comment]
在Model里设置一下属性 

`public    $incrementing = false;`

就可以在创建页面看到主键了
