### ISSUE TITLE
删除回调里面如何获取删除的id？

### ISSUE THREAD

**Issue by ygd1994** [z-song/laravel-admin#3801]
- Laravel Version: 5.5
- PHP Version: 7.3.4
- Laravel-admin: 1.7.5

### Description:
`$form->deleted(function ($model) {
            dd($model);
        });`
` public static function boot()
    {
        parent::boot();
        static::deleted(function ($model) {
            dd($model);
            exit();
        });
    }`
两张方式都获取不到模型信息
### Steps To Reproduce:

**Comment by ygd1994** [comment]
`$form->deleting(function () {`
`            $url = Input::url();`
`            $arr = explode("/", $url);`
`            $id = end($arr);`
`            ...`
`});`
可以通过链接地址来获取。

**Comment by yavana** [comment]
怎么获取到的呢？@ygd1994
