### ISSUE TITLE
Argument 1 passed to Illuminate\Database\Grammar::parameterize() must be of the type array, string given

### ISSUE THREAD

**Issue by Hanson** [z-song/laravel-admin#3806]
最新版本

`$form->text('custom_text');`

报错信息

![image](https://user-images.githubusercontent.com/10583423/63113339-e64fde80-bfc4-11e9-9cb6-4aa23941cb00.png)

**Comment by z-song** [comment]
重现不了

**Comment by Hanson** [comment]
最终发现似乎是 json 字段，model 没有 cast 为 array 导致的

**Comment by Hanson** [comment]
实际字段是用了 `$form->checkbox()`
