### ISSUE TITLE
OnetoOne relationship not working on Laravel 5.4 any update coming?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#381]
![2017-02-07_1942](https://cloud.githubusercontent.com/assets/24757934/22725024/58fe24c0-ed98-11e6-8ce5-724b521662a0.png)

Same code working perfectly on 1.3.x-dev

**Comment by z-song** [comment]
Works fine for me,  show your code?

**Comment by smuzammilali** [comment]
Error:
![2017-02-10_1402](https://cloud.githubusercontent.com/assets/24757934/22840011/d81eea2a-ef99-11e6-823f-96c31ebafc8d.png)


Code:
![2017-02-10_1403](https://cloud.githubusercontent.com/assets/24757934/22840018/e301b490-ef99-11e6-8291-4f28f4d5214a.png)

Pagetype:
![pagetype](https://cloud.githubusercontent.com/assets/24757934/22840023/e9b66718-ef99-11e6-9a9f-32a9874d3710.png)


Page:
![page](https://cloud.githubusercontent.com/assets/24757934/22840027/ee0d1b7c-ef99-11e6-927d-9487a1675bd5.png)


The same code works perfectly on 1.3.x-dev

**Comment by smuzammilali** [comment]
Any update for this issue?

**Comment by smuzammilali** [comment]
Not working in the simplest form(1.4.x-dev):
![2017-02-13_1659_001](https://cloud.githubusercontent.com/assets/24757934/22905377/06ca73c8-f20e-11e6-8222-da7fc286d609.png)
![2017-02-13_1659](https://cloud.githubusercontent.com/assets/24757934/22905376/06c52620-f20e-11e6-9f79-be110c19be09.png)


Working perfectly unerd 1.3.x-dev

**Comment by z-song** [comment]
I pushed a commit to fix this now, update the package and try again.

**Comment by smuzammilali** [comment]
Thanks working perfectly!
