### ISSUE TITLE
建议增加多个后台路由文件

### ISSUE THREAD

**Issue by webphper** [z-song/laravel-admin#3813]
- Laravel Version: .5.7
- PHP Version:7.3
- Laravel-admin: 1.7.5

### Description:
建议增加多个后台路由文件，大部分时候都是多个人在开发后台，多人修改同一个路由文件很容易产生冲突。可以在app/Admin下边增加专门的目录管理路由文件或者通过配置项管理

**Comment by puzzle9** [comment]
其实嘛 你可以在开发的时候 用
`App\Providers\RouteServiceProvider.php` 一样的方式引进去呀
