### ISSUE TITLE
Cascading Select

### ISSUE THREAD

**Issue by xn0ak** [z-song/laravel-admin#3817]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: 1.7.3

### Description:
I'm using this code to make a cascading select:

  $form->select('idCliente', 'Cliente ALP')
        ->options(Cliente::orderBy('nome', 'asc')
            ->get()
            ->pluck('nome', 'idCliente'))
        ->load('idObra', '/api/obras')
        ->default('')
        ->required();
        $idObra =$form->select('idObra', 'Projeto')->required();

I want to have a select with all the customers and the second only shows information related to the customer selected. That is working well for new records.
The problem I'm having is that when I edit, the second select is blank.
How can I load the value from the database directly to the second select?

Thank you.

---
Example:
Creating new record:
![chrome_1mNU3kL1eQ](https://user-images.githubusercontent.com/7122663/63343838-e0e8f000-c346-11e9-8b81-5908cb838ccf.png)

Edit page:
![chrome_JAfGPKdiZC](https://user-images.githubusercontent.com/7122663/63343830-dd556900-c346-11e9-933b-1632bc796c97.png)

**Comment by hanachan1026** [comment]
I'm having the exactly same problem.

**Comment by vonsogt** [comment]
Same here too

**Comment by vonsogt** [comment]
You need to modify your model, like this: 
```
public function parent()
{
	return $this->belongsTo(DataPartner::class, 'id');
}

public function children()
{
	return $this->hasMany(DataPartnerDirector::class, 'id');
}
public function brothers()
{
	return $this->parent->children();
}

public static function options($id)
{
	if (!$self = static::find($id)) {
		return [];
	}
	return $self->brothers()->pluck('name', 'id');
}
```

And the controller:
```
$form->select('partner_id', 'Rekanan')
	->options(DataPartner::where('sector', 'ppat')->pluck('name', 'id'))
	->load('partner_director_id', '/admin/api/data/partner/directors')
	->value(request('partner_id'));
$form->select('partner_director_id', 'Direktur')
	->options(function ($id) {
		return DataPartner::options($id);
	})
	->value(request('partner_director_id'));
```

The conclusion is the function of _'options'_ it will check the parent and children. When we try to edit the row it will only return one child that saved in the database, BUT we must reselect again the parent to get the children.

I still trying to fix get the children without reselecting the parent

**Comment by lehelkeresztes** [comment]
I've had the same problem. Solved it by extending the Select component with a custom method, like this one:
```
public function autoLoadCascading(): void
    {
        $script   = <<<JS
if ($('{$this->getElementClassSelector()}').val() !== ''){
    $('{$this->getElementClassSelector()}').trigger('change');
}
JS;
        Admin::script($script);
    }
```

Then you just need to call the method where you want the cascading select to autoload:
```
$form->select(...)
                ->options(...)
                ->load(...)
                ->autoLoadCascading();
```
