### ISSUE TITLE
sidebar.menu等菜单栏翻译

### ISSUE THREAD

**Issue by Huelse** [z-song/laravel-admin#3819]
- Laravel Version: 5.8.32
- PHP Version:7.2.21
- Laravel-admin: 1.7

### Description:
怎么设置左侧菜单栏的翻译？
我已经设置了`locale => zh-CN`
在`lang\zh-CN\admin.php`里也添加了几个样例，但都没有成功
`menu.blade.php`里的`admin.menu_titles.`

### Steps To Reproduce:
![Snipaste_2019-08-21_09-28-37.png](https://i.loli.net/2019/08/21/BCPr2pRQDiowI7x.png)

感谢给个例子或者提示！

**Comment by SoulMate94** [comment]
这几个直接在数据库admin_menu修改就可以了
