### ISSUE TITLE
->format() is not working  on both 1.3x and 1.4x

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#382]
![2017-02-08_0124](https://cloud.githubusercontent.com/assets/24757934/22725759/5d72e612-ed9d-11e6-9ba3-1ef473f47a99.png)

It was working fine but with latest composer update not working anymore.

**Comment by z-song** [comment]
Use `->options(['mask' => '999999']);` instead.

I'll update the docs later.
