### ISSUE TITLE
修改数据源，覆盖`where`无效。

### ISSUE THREAD

**Issue by liyuliang1** [z-song/laravel-admin#3820]
- Laravel Version: 5.8.30
- PHP Version:7.2.11
- Laravel-admin: 1.7.5

### Description:
修改数据源，覆盖`where`无效。

    // 覆盖`where`来收集筛选的字段和条件
    public function where($column, $operator = null, $value = null, $boolean = 'and')
    {
            // 进不来！
    }

**Comment by MrKaGod** [comment]
请问找到解决办法了嘛？
