### ISSUE TITLE
在grid调用json数据无效问题

### ISSUE THREAD

**Issue by CrazyCodes** [z-song/laravel-admin#3824]
- Laravel Version: 5.8
- PHP Version:7.1.3
- Laravel-admin: 1.7

### Description:
使用代码
$grid->column('profile->mobile', '手机号');
未得到预期的效果
JSON数据为
```
{"mobile":"18555555555"}
```
请问如何去解决，是使用的问题吗。

**Comment by z-song** [comment]
profile字段在数据库中必须为json类型，而不是json格式
