### ISSUE TITLE
富文本显示问题

### ISSUE THREAD

**Issue by llxcyzgh** [z-song/laravel-admin#3827]
- Laravel Version: 5.8.
- PHP Version:7.2
- Laravel-admin: 1.7.3

### Description:
富文本在 show 详情里面显示出错
使用 pre 后, 依然全部被转义了, pre 也被转义了
```
$show->contents()->as(function ($content) {
    return "<pre>{$content}</pre>";
});
```
![图片](https://user-images.githubusercontent.com/25409804/63561437-7628f600-c58c-11e9-82e8-324f702956a4.png)

**Comment by fangke2688** [comment]
调用unescape方法即可。
