### ISSUE TITLE
多图片上传，二次编辑问题

### ISSUE THREAD

**Issue by hsw409328** [z-song/laravel-admin#383]
图片上传，二次编辑问题。
1、多图片不能执行单个清除
2、如果图片不编辑的情况下，修改了其它字段信息，submit的时候报错
   ErrorException In D:\wamp\www\lvyouapp\vendor\encore\laravel-admin\src\Form\Field\File.php line 304 : 
Argument 1 passed to Encore\Admin\Form\Field\File::getStoreName() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given, called in D:\wamp\www\lvyouapp\vendor\encore\laravel-admin\src\Form\Field\Image.php on line 45 and defined

请问是否可以支持单图片删除，如果不上传新的图片，只是修改了其它信息，提交不了。

**Comment by z-song** [comment]
第一个问题确实存在

第二个问题没有重现，你使用的版本是多少？

**Comment by hsw409328** [comment]
"php": ">=5.5.9",
        "laravel/framework": "5.2.*",
        "encore/laravel-admin": "1.2.*",
        "barryvdh/laravel-ide-helper":"dev-master",

**Comment by z-song** [comment]
已经在1.3.x-dev分支优化了第一个问题 http://120.26.143.106/admin/demo/multiple-images/51/edit
