### ISSUE TITLE
关于1.7版本的控制器删除方法重写问题

### ISSUE THREAD

**Issue by chenzhulin** [z-song/laravel-admin#3831]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
当我的数据库中的记录，上传图片之后，会保存一个图片地址，但是我删除这条记录时，对应的图片应该删除才对，但是图片并未删除，本来打算重写删除方法时，发现删除方法，重写不了，不知道删除方法走的那个地址，怎么改对应控制器重写的删除方法都不执行

**Comment by z-song** [comment]
请参考laravel的模型事件来处理你的情况  https://learnku.com/articles/5671/several-uses-of-model-events
