### ISSUE TITLE
gird 表字段不能有updated，created字段，否则调用了model的底层updated，created方法

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#3837]
Laravel Version: 5.5.*
PHP Version: 7.2。0
Laravel-admin: 1.7.3

### Description:
升级版本之后，grid的一个字段叫update，结果发生报错
![image](https://user-images.githubusercontent.com/29086696/63664448-226f1480-c7f9-11e9-8ce4-13a6800f3052.png)

### Steps To Reproduce:
调试如下：
![image](https://user-images.githubusercontent.com/29086696/63664489-50ecef80-c7f9-11e9-830a-e97d06a93ff9.png)
发现不用updated字段可以解决问题，但是项目之前是基于老版本1.6.0的用了好多的这个字段，这个有办法解决吗

**Comment by YangZhengHuan** [comment]
通过源码查看：
![image](https://user-images.githubusercontent.com/29086696/63665478-1c2f6700-c7fe-11e9-8c59-33a1d7c6f367.png)
解决问题，请问一下后续版本可否增加一个选择，个人觉得这个功能应该去掉

**Comment by YangZhengHuan** [comment]
@z-song 麻烦有时间回复一下，谢谢

**Comment by jqhph** [comment]
可以这样解决
```php
$grid->column('实际更新量')->display(function () {
    return $this->updated;
});
```

**Comment by z-song** [comment]
@YangZhengHuan 按照 @jqhph 的办法解决吧
