### ISSUE TITLE
How to get the current authenticated admin user id in Form field value 

### ISSUE THREAD

**Issue by rajkumarForDev** [z-song/laravel-admin#3839]
How to get the current authenticated admin user id in Form field value 

     $form->text('created_by', 'created_by')->default(Admin::user()->id)->setWidth(3, 2);

Error:

Symfony \ Component \ Debug \ Exception \ FatalThrowableError (E_ERROR)
Class 'App\Admin\Controllers\Admin' not found

**Comment by maksimbondarau** [comment]
@rajkumarForDev you must add to header
`use Encore\Admin\Facades\Admin;`
