### ISSUE TITLE
希望form能自定义url

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#384]
如果能加入url参数就更好了
```
 {!! $form->open(['class' => "form-horizontal", 
'url' => 'foo/bar']) !!}
```
在Form类中再加一个方法，setUrl

**Comment by z-song** [comment]
```php
$form->setAction('foo/bar');
```

如果找不到方法，更新版本

**Comment by MooOne** [comment]
![image](https://user-images.githubusercontent.com/28894376/58241106-e7cf8900-7d7e-11e9-815f-a6e522767ce8.png)
加了if判断之后setAction无效
