### ISSUE TITLE
视频和图片是否在上传的时候可以存入不同的disk

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#3841]
Laravel Version: 5.5
PHP Version: 7.1
Laravel-admin: 1.7.3

### Description:

看文档上面只有能配置一个disk，然后放入不同的disk下面的目录，我这个是使用七牛云，上面建立了两个bucket，目的是视频和图片在不同的bucket，这个可以实现吗？尝试修改源码中
### Steps To Reproduce:
admin.php中目前只能配置一个
![image](https://user-images.githubusercontent.com/29086696/63744450-f6739200-c8d1-11e9-8e33-e28e7c68c491.png)

**Comment by z-song** [comment]
这个 `$form->file('video')->disk('qiniu');`
