### ISSUE TITLE
a security issue

### ISSUE THREAD

**Issue by ssssdl** [z-song/laravel-admin#3847]
# laravel-admin background XSS

first.add xss Roles

![test.png](https://i.loli.net/2019/08/27/uoDUdJcxlBz7ARE.png)

next go to operation log page

![snipaste_20190827_234917.png](https://i.loli.net/2019/08/27/vMjSsJpAE9Qh8qD.png)

The following is my system environment
![snipaste_20190827_235047.png](https://i.loli.net/2019/08/27/vhxEFKLDY9WkZ8j.png)

And I think this issue also exists in other versions.And don't know this place.

**Comment by iseafish** [comment]
有漏洞不解决？
