### ISSUE TITLE
上传相同名称和后缀的图片会被重命名！！

### ISSUE THREAD

**Issue by SmallRuralDog** [z-song/laravel-admin#3850]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.7

### Description:
先上传一张图片
然后点击编辑，重新上传这张图片，保存后图片会被重命名！！！没有覆盖替换原来的图片！

**Comment by fangke2688** [comment]
这个不是问题，本应如此。

**Comment by SmallRuralDog** [comment]
> 这个不是问题，本应如此。

为什么应该这样呢

**Comment by fangke2688** [comment]
> > 这个不是问题，本应如此。
> 
> 为什么应该这样呢

原本就是这个样，如果你需要更新或删除的时候去把图片删掉的话，可以利用[模型事件](https://learnku.com/docs/laravel/5.8/eloquent/3931#events)来做。

**Comment by SmallRuralDog** [comment]
> > > 这个不是问题，本应如此。
> > 
> > 
> > 为什么应该这样呢
> 
> 原本就是这个样，如果你需要更新或删除的时候去把图片删掉的话，可以利用[模型事件](https://learnku.com/docs/laravel/5.8/eloquent/3931#events)来做。



> > > 这个不是问题，本应如此。
> > 
> > 
> > 为什么应该这样呢
> 
> 原本就是这个样，如果你需要更新或删除的时候去把图片删掉的话，可以利用[模型事件](https://learnku.com/docs/laravel/5.8/eloquent/3931#events)来做。

好的！！感谢！！不过还是希望作者能加一个 `同名是否覆盖的设置`

**Comment by SmallRuralDog** [comment]
> > > 这个不是问题，本应如此。
> > 
> > 
> > 为什么应该这样呢
> 
> 原本就是这个样，如果你需要更新或删除的时候去把图片删掉的话，可以利用[模型事件](https://learnku.com/docs/laravel/5.8/eloquent/3931#events)来做。

好的！！感谢  不过还是希望作者加一个 `同名是否覆盖的设置`

**Comment by fangke2688** [comment]
> > > > 这个不是问题，本应如此。
> > > 
> > > 
> > > 为什么应该这样呢
> > 
> > 
> > 原本就是这个样，如果你需要更新或删除的时候去把图片删掉的话，可以利用[模型事件](https://learnku.com/docs/laravel/5.8/eloquent/3931#events)来做。
> 
> 好的！！感谢 不过还是希望作者加一个 `同名是否覆盖的设置`

同名不代表同图。

**Comment by SmallRuralDog** [comment]
> > > > > 这个不是问题，本应如此。
> > > > 
> > > > 
> > > > 为什么应该这样呢
> > > 
> > > 
> > > 原本就是这个样，如果你需要更新或删除的时候去把图片删掉的话，可以利用[模型事件](https://learnku.com/docs/laravel/5.8/eloquent/3931#events)来做。
> > 
> > 
> > 好的！！感谢 不过还是希望作者加一个 `同名是否覆盖的设置`
> 
> 同名不代表同图。

是的，但是有些情况下有覆盖的需求！！
