### ISSUE TITLE
想问一下，为什么在二级联动过程中，第一个select传的是id，第二个select传的是text的值，为什么呢

### ISSUE THREAD

**Issue by donallin** [z-song/laravel-admin#3851]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
想问一下，为什么在二级联动过程中，第一个select传的是id，第二个select传的是text的值，为什么呢
![image](https://user-images.githubusercontent.com/5716754/63841790-0664a200-c9b6-11e9-91c6-c6b6b8594481.png)

**Comment by fangke2688** [comment]
使用了load()联动加载数据，数据就是从API返回的，需要是下边这种格式，不应再使用options()。
```
[
    {
        "id": 9,
        "text": "xxx"
    },
    {
        "id": 21,
        "text": "xxx"
    },
    ...
]
```

**Comment by donallin** [comment]
感谢
