### ISSUE TITLE
有办法兼容下mongodb吗

### ISSUE THREAD

**Issue by peilanluo** [z-song/laravel-admin#3852]
装jenssegers/mongodb扩展之后，再使用laravel-admin执行php artisan admin:make VideoController --model=App\\Models\\Video命令的时候会报这么个错误

ErrorException  : call_user_func_array() expects parameter 1 to be a valid callback, class 'MongoDB\Database' does not have a method 'getDoctrineDriver'

  at /home/admin/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:268
    264|      * @return mixed
    265|      */
    266|     public function __call($method, $parameters)
    267|     {
  > 268|         return call_user_func_array([$this->db, $method], $parameters);
    269|     }
    270| }
    271|

  Exception trace:

  1   call_user_func_array([])
      /home/admin/vendor/jenssegers/mongodb/src/Jenssegers/Mongodb/Connection.php:268

  2   Jenssegers\Mongodb\Connection::__call("getDoctrineDriver", [])
      /home/admin/vendor/laravel/framework/src/Illuminate/Database/Connection.php:887

  Please use the argument -v to see more details.

**Comment by qingdi** [comment]
同样问题
