### ISSUE TITLE
关于表格使用固定列fixColumns后与行内编辑editable层级冲突问题

### ISSUE THREAD

**Issue by lauwen** [z-song/laravel-admin#3853]
- Laravel Version: 5.7
- PHP Version:7
- Laravel-admin: 1.7.5

### Description:
editable和固定列同时使用时出现弹出的编辑框被遮住，层级较低问题
![image](https://user-images.githubusercontent.com/24284307/63845092-f9e34800-c9bb-11e9-8f6f-34108f2acb60.png)

**Comment by lauwen** [comment]
补充一下，贴边被隐藏问题希望也能一起解决一下

**Comment by lauwen** [comment]
![image](https://user-images.githubusercontent.com/24284307/63845665-e1bff880-c9bc-11e9-8773-b1cc45fde880.png)
以及贴边部分被隐藏了

**Comment by ieliwb** [comment]
@lauwen  大佬，解决了没，设置了fixColumns，就会出现

**Comment by lauwen** [comment]
没有  放弃了  这需要框架底层支持   有时间的话你可以尝试重写下laravel-admin的行编辑功能来实现层级调整

**Comment by ieliwb** [comment]
#
<img width="195" alt="截屏2021-01-15 16 08 07" src="https://user-images.githubusercontent.com/2177409/104698164-e4ef8c00-574b-11eb-894f-ad5f7eedfd66.png">

我的是这个搜索只有一个的时候，点更多被盖住了，我找到div容器，设置了style="min-height: 400px;"，解决了，我感觉你也可以这样解决，把箭头搞成auto
