### ISSUE TITLE
多级联动保留选择后的值

### ISSUE THREAD

**Issue by newbrash** [z-song/laravel-admin#3856]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.7.2

### Description:
代码：
![image](https://user-images.githubusercontent.com/40032190/63910959-49c51c00-ca5b-11e9-8728-44aa9e06a106.png)
结果：
![image](https://user-images.githubusercontent.com/40032190/63917299-ea700780-ca6c-11e9-9efa-856457f357da.png)

简单说下思路，二级select接受一级值并初始option

保留下来的原因很简单，详情看:admin\filter\select.blade.php  及  vendor\encore\laravel-

**Comment by malonzhao** [comment]
提交了一个PR 现在还没合并，涉及到 select 还有 multipleselect  关于修复无法载入原始值的
