### ISSUE TITLE
自定义的行操作如何进行权限控制？

### ISSUE THREAD

**Issue by hui-ho** [z-song/laravel-admin#3858]
- Laravel Version: 5.8.*
- PHP Version: 7.3.8
- Laravel-admin: 1.7.*

### Description:

对于默认的**显示、编辑、删除**按钮可以通过权限控制每一行是否显示：

```php
$grid->actions(function ($actions) {

    // 没有`delete-image`权限的角色不显示删除按钮
    if (!Admin::user()->can('delete-image')) {
        $actions->disableDelete();
    }
});
```

那自定义的行操作按钮也可以通过权限控制按需显示呢？

**Comment by z-song** [comment]
@hui-ho https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6
