### ISSUE TITLE
多图上传rules规则无效，required无效

### ISSUE THREAD

**Issue by aBusyAnt** [z-song/laravel-admin#3859]
多图上传rules规则无效，required无效，图片规格设置也无效，好像是由于多图字段为path,但校验的时候是path0,path1....如何修复这个问题？

只能修改为sometimes才行能提交成功，否则 required会导致异常的reload到编辑页面，也不报错。 谢谢！  @z-song 

 ```
$form->multipleImage('carinfo.images', '行驶证或购车发票照片')
                ->removable()
                ->move('orders/'.date("Y-m-d"))
                ->uniqueName() ->rules('sometimes|required|dimensions:max_width=2000,max_height=2000|max:1024');
```

**Comment by rust17** [comment]
laravel-admin version: 1.7.9
laravel version: 6.0
php 7.4 
同样遇到了多图上传设置 required 无效的问题

**Comment by songlen** [comment]
兄弟们，这不仅仅是required 无效的问题，是多图上传 加上排序功能导致的没有读取到所有该字段的验证规则。我看到 @rust17 已经修复了该bug，但是不应该这样修复，直接删掉那个判断即可，因为排序不是异步完成的，是跟修改时一块提交的
