### ISSUE TITLE
v1.7.6 forms 中的table失效

### ISSUE THREAD

**Issue by Iamzz-cn** [z-song/laravel-admin#3870]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.7.6

### Description:

1.7.5升级到的1.7.6
使用forms 在1.7.5是没有问题的，1.7.6会error。

### Steps To Reproduce:
不需要什么特殊条件就能复现！！！！！！

**Comment by z-song** [comment]
什么error  贴出来

**Comment by never615** [comment]
没问题啊.
![image](https://user-images.githubusercontent.com/9959927/64252915-b3a75f00-cf4e-11e9-8efb-6ee8984a52ce.png)

**Comment by Iamzz-cn** [comment]
app\Admin\Forms\SomeForm.php
```php
...
 public function form()
{
        $this->text('name')->rules('required');
        $this->email('email')->rules('email');
        $this->datetime('created_at');
        $this->table('extra', __('extra'), function ($table) {
            $table->text('key');
            $table->text('value');
            $table->text('desc');
        });
}
...
````

![TIM截图20190905113717](https://user-images.githubusercontent.com/21697242/64310143-95367780-cfd1-11e9-827a-affbee589b93.png)

**Comment by Iamzz-cn** [comment]
@z-song

**Comment by Iamzz-cn** [comment]
我尝试这取消这部分的注释，是可以的，但是我们有仔细的看，不知道会不会有什么其他的影响。
![TIM截图20190905113907](https://user-images.githubusercontent.com/21697242/64310224-e6466b80-cfd1-11e9-90a2-ded22a064676.png)

**Comment by Iamzz-cn** [comment]
他似乎强制我必须在data中添加对应的默认值，并且默认值还没有生效。
```php
...
    public function form()
    {
        $this->text('name')->rules('required');
        $this->email('email')->rules('email');
        $this->datetime('created_at');
        $this->table('extra', __('extra'), function ($table) {
            $table->text('key');
        });
    }
    public function data()
    {
        return [
            'name' => 'John Doe',
            'email' => 'John.Doe@gmail.com',
            'created_at' => now(),
            'extra' => ['key' => ['123']]
        ];
    }
...

```
也是可以的。

**Comment by Iamzz-cn** [comment]
@never615

**Comment by never615** [comment]
$form->table确实有问题...
我那个图是$form->hasMany()->useTable()..
 @Iamzz-cn

**Comment by Iamzz-cn** [comment]
是用法改了吗？我建议把文档也开源吧，文档里面确实有些写的不是很清晰，而且没有对版本标注。

**Comment by never615** [comment]
文档本来就开源dosc目录下
