### ISSUE TITLE
自定义工具 ids: selectedRows(), 报错  selectedRows is not defined

### ISSUE THREAD

**Issue by gyp719** [z-song/laravel-admin#3874]
php 7.2
laravel 5.8
laravel-admin 1.7.2

自定义工具 ids: selectedRows(), 报错  selectedRows is not defined  

![image](https://user-images.githubusercontent.com/30563368/64190422-ef87e900-cea8-11e9-82bf-278e071493f1.png)

**Comment by z-song** [comment]
参考最新的文档 https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E6%89%B9%E9%87%8F%E6%93%8D%E4%BD%9C

**Comment by gyp719** [comment]
在 laravel-admin 1.7.2 中  没有这样的命令 `php artisan admin:action Post\\Replicate --grid-row --name="复制"`
且  没有 这个类  use Encore\Admin\Actions\RowAction;  use Encore\Admin\Actions\BatchAction;

**Comment by yeminlideveloper** [comment]
Can be use ` $.admin.grid.selects`

**Comment by AhmadRaju007** [comment]
thanks a lot @yeminlideveloper. `$.admin.grid.selected()` worked for me!
