### ISSUE TITLE
Hotkeys break native functions + Fix

### ISSUE THREAD

**Issue by sjorsbroersen** [z-song/laravel-admin#3875]
- Laravel Version: 5.8.34
- PHP Version: 7.3.6
- Laravel-admin: 1.7.6

### Description:
When enabling hotkeys the browser is not able to do the default functionality anymore. Functions like CTRL + F and CTRL + C

### Steps To Reproduce:
1 press: CTRL + F 
2 result: Search box doens't open

### Solution
file: Grid\Concerns\HasHotKeys.php
include ctrl key detection around switch for actions:
```
if (!e.ctrlKey) {
     switch(e.which) {
              
     }
     e.preventDefault();
}
```

**Comment by TingSyuanWang** [comment]
@sjorsbroersen
Hi, I met the same problem.
would you like to pull request to this repository?
