### ISSUE TITLE
Admin::disablePjax() 开启后有问题

### ISSUE THREAD

**Issue by chencongbao** [z-song/laravel-admin#3882]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.7.6

### Description:
Admin::disablePjax() 
开启之后  编辑表单 就会跳转到 show 详情页面 ，不会跳转到列表页面

**Comment by chencongbao** [comment]
![image](https://user-images.githubusercontent.com/7532419/64306848-b2197d80-cfc6-11e9-8abd-f01c632cbb12.png)


我打印的  跳转url 是这个 但是 最终跳转的 是
admin/exercise/4

**Comment by chencongbao** [comment]
问题找到了 我发现是  laravel redirect  的问题，跳转成功后 浏览器的url 改变了以下，我修改了源码
Encore\Admin\Form
redirectAfterSaving方法中的
return redirect($url) 替换成了
echo '<script>window.location.href="'.$url.'";</script>';
就正常了， 希望作者修复以下啊

**Comment by mydansun** [comment]
执行`composer update`后解决

**Comment by chencongbao** [comment]
这个问题 具体是什么问题啊，有解决方案吗

**Comment by nosun** [comment]
同样的问题，有解决方案么？

**Comment by wisp-x** [comment]
```php
$form->saving(function () {
    return redirect('url');
 });
```
