### ISSUE TITLE
grid自定义action不支持redirect的bug

### ISSUE THREAD

**Issue by xiaohuilam** [z-song/laravel-admin#3888]
- Laravel Version: 5.8.*
- PHP Version: 7.2.*
- Laravel-admin: 1.7.*-latest

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/6964962/64316582-d3d72c80-cfe7-11e9-9452-f2584b447a8a.png)

返回了 redirect 和 url
但没有跳转

**Comment by z-song** [comment]
提交了修复，另外`redirect()`方法只能跳转后台页面，比如 `$response->redirect('/admin/pricing');`

增加了一个location方法来跳转站外页面`$response->location('http://www.githu.com');`

**Comment by xiaohuilam** [comment]
thanks
