### ISSUE TITLE
Full page reload on "CREATE"

### ISSUE THREAD

**Issue by sayawan** [z-song/laravel-admin#389]
I get full page reload on create, on my production server, but everything is okay when testing locally. When submitting empty form, any validation errors appear, and just redirects to the main list. Maybe somethings with response/request headers ? or .. 

Local Env: Mac, chrome, Laravel 5.3, Encore Admin 1.3
Production: Dreamhost, php 7

**Comment by z-song** [comment]
Any errors could be found in network logs? or check exceptions in `laravel.log`

**Comment by sayawan** [comment]
There are any errors in `network logs` either in` laravel.log`. But I realized that, when sending POST request it gets `200` response, instead of `302`. I am not sure what is causing that issue.

**Comment by sayawan** [comment]
POST request headers
General
```
Request URL:http://www.example.com/admin/news
Request Method:POST
Status Code:200 OK
```

Response Headers
```
Connection:Keep-Alive
Content-Encoding:gzip
Content-Length:214
Content-Type:text/html; charset=UTF-8
Date:Fri, 10 Feb 2017 08:10:38 GMT
Keep-Alive:timeout=2, max=100
Server:Apache
Vary:Accept-Encoding
```

Request Header
```
Accept:text/html, */*; q=0.01
Accept-Encoding:gzip, deflate
Accept-Language:en-US,en;q=0.8,ru;q=0.6,tr;q=0.4
Connection:keep-alive
Content-Length:827
--skip--
X-PJAX:true
X-PJAX-Container:#pjax-container
X-Requested-With:XMLHttpRequest
```

**Comment by pkkandel1** [comment]
How was this issue solved ?? I am having exactly same issue.
