### ISSUE TITLE
laravel6.0 无法安装啊

### ISSUE THREAD

**Issue by cjango** [z-song/laravel-admin#3892]
- Laravel Version: 6.0.0
- PHP Version:7.2
- Laravel-admin: 1.7.6

**Comment by JackieHome** [comment]
Notice：本地php 版本和当前composer所要求的不相符会安装失败，一般在导入第三方库都会出现。只需在导包前执行：composer install --ignore-platform-reqs 或者 composer update --ignore-platform-reqs（忽略版本匹配）

**Comment by chenronglin** [comment]
因为6.0是长期支持版本，强烈建议尽快更新版本，以支持6.0。谢谢！

**Comment by aoeng** [comment]
@JackieHome 没用啊

**Comment by z-song** [comment]
更新到v1.7.7
