### ISSUE TITLE
在laravel-admin 1.7.2中没有这样的命令php artisan admin:action Post\\Replicate --grid-row --name="复制" 

### ISSUE THREAD

**Issue by gyp719** [z-song/laravel-admin#3899]
在laravel-admin 1.7.2中没有这样的命令php artisan admin:action Post\\Replicate --grid-row --name="复制"
且没有这个类使用Encore \ Admin \ Actions \ RowAction; 使用Encore \ Admin \ Actions \ BatchAction;

我需要在头部自定义按钮，点击按钮可以弹窗 表单页面

**Comment by z-song** [comment]
文档上写了`Since v1.7.3`
