### ISSUE TITLE
Image uploading not working in 1.4.x-dev

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#390]
Image uploading not working

**Comment by z-song** [comment]
Woks fine for me, maybe check permissions of directories, or exceptions.

**Comment by smuzammilali** [comment]
Yeah works fine now but have one issue:
$grid->avator()->image();
(That's not displaying anything on grid list)

**Comment by z-song** [comment]
See what will displays just use `$grid->avator();`

**Comment by smuzammilali** [comment]
thank it was spelling mistake from my end
 $grid->avatar()
