### ISSUE TITLE
【BUG】[1.3.x-dev] Grid下的查询过滤器的select功能貌似有bug

### ISSUE THREAD

**Issue by lenkaren** [z-song/laravel-admin#391]
页面的value和控制器设置的value不一致（字符型没有问题，但整形数值有问题），

控制器设置为
'1' => '选项1'
'2 => '选项2'
'3' => '选项3'

页面则是
'0' => '选项1'
'1 => '选项2'
'2' => '选项3'

**页面的value值被自动减1了。**

**控制器代码**
`$filter->where(function ($query) {
                    $input = $this->input;
                    $query->whereHas('recoms', function ($query) use ($input) {
                        $query->where('recom_id', $input);
                    });
                }, '推荐位')->select([
                    '1' => '无效推荐',
                    '2' => '首页推荐',
                    '3' => '金融推荐',
                ]);`

**页面html**

`<select class="form-control c797bea83697972dcbbc329b3e6151b3" style="width: 100%;" name="c797bea83697972dcbbc329b3e6151b3">
             <option value="" selected="">选择</option>
             <option value="0">无效推荐</option>
             <option value="1">首页推荐</option>
             <option value="2">金融推荐</option>
 </select>`

**Comment by z-song** [comment]
已经push commit到1.3.x-dev
