### ISSUE TITLE
when i click the container-refresh button this bug show up , $.admin.reload is not a function

### ISSUE THREAD

**Issue by xxxlo71** [z-song/laravel-admin#3912]
when i click the container-refresh button this bug show up ,

i plugin iframe-tabs , please help

![螢幕快照 2019-09-10 下午2 44 50](https://user-images.githubusercontent.com/33816886/64590305-d8ca2080-d3d9-11e9-954e-5c3444f434b3.png)

PHP version | PHP/7.1.26
-- | --
Laravel version | 5.8.35
CGI | fpm-fcgi

encore/laravel-admin | 1.7.1
-- | --
fideloper/proxy | ^4.0
ichynul/iframe-tabs | 1.0.27

_Originally posted by @xxxlo71 in https://github.com/z-song/laravel-admin/issues/3569#issuecomment-529797224_

**Comment by z-song** [comment]
It seems that this plugin is not compatible with the current laravel-admin version.

**Comment by xxxlo71** [comment]
> It seems that this plugin is not compatible with the current laravel-admin version.

how to hidden this button ?

**Comment by xxxlo71** [comment]
i try to update to 1.2.26 newest (2019/09/12) but have Page breaking issue

![螢幕快照 2019-09-12 上午10 42 15](https://user-images.githubusercontent.com/33816886/64749937-0635dc00-d54a-11e9-9449-93a82a81141c.png)
