### ISSUE TITLE
 php artisan admin:install  -- error

### ISSUE THREAD

**Issue by zbing121** [z-song/laravel-admin#3915]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

 "require": {
        "php": "^7.2",
        "encore/laravel-admin": "^1.7",
        "fideloper/proxy": "^4.0",
        "laravel/framework": "^6.0",
        "laravel/tinker": "^1.0"
    },

  Illuminate\Database\QueryException  : SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to
 use near '('0'), `order` int not null default ('0'), `title` varchar(50) not null, `icon` ' at line 1 (SQL: create table `admin_menu` (`id` int unsigned not null auto_increment primary key, `parent_id` int not null defau
lt ('0'), `order` int not null default ('0'), `title` varchar(50) not null, `icon` varchar(50) not null, `uri` varchar(50) null, `permission` varchar(191) null, `created_at` timestamp null, `updated_at` timestamp null) de
fault character set utf8mb4 collate 'utf8mb4_unicode_ci')

  at D:\web\study\laravel-admin\vendor\laravel\framework\src\Illuminate\Database\Connection.php:665
    661|         // If an exception occurs when attempting to run a query, we'll format the error
    662|         // message to include the bindings with SQL, which will make this exception a
    663|         // lot more helpful to the developer instead of just the database's errors.
    664|         catch (Exception $e) {
  > 665|             throw new QueryException(
    666|                 $query, $this->prepareBindings($bindings), $e
    667|             );
    668|         }
    669|

  Exception trace:

  1   Doctrine\DBAL\Driver\PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax
to use near '('0'), `order` int not null default ('0'), `title` varchar(50) not null, `icon` ' at line 1")
      D:\web\study\laravel-admin\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:63

  2   PDOException::("SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('0'), `
order` int not null default ('0'), `title` varchar(50) not null, `icon` ' at line 1")
      D:\web\study\laravel-admin\vendor\doctrine\dbal\lib\Doctrine\DBAL\Driver\PDOConnection.php:61

  Please use the argument -v to see more details.

### Steps To Reproduce:

php artisan admin:install

**Comment by zbing121** [comment]
Schema::create(config('admin.database.menu_table'), function (Blueprint $table) {
            $table->increments('id');
            $table->integer('parent_id');
            $table->integer('order');
            $table->string('title', 50);
            $table->string('icon', 50);
            $table->string('uri', 50)->nullable();
            $table->string('permission')->nullable();

            $table->timestamps();
        });

去掉 default 就可以了。

**Comment by z-song** [comment]
重现不了这个问题
