### ISSUE TITLE
Send data to another page

### ISSUE THREAD

**Issue by xn0ak** [z-song/laravel-admin#3917]
Hello,

How can I send to another page, soma grid data information?
For example, I have this table:
![chrome_tm2ApZDbVR](https://user-images.githubusercontent.com/7122663/64714796-25375e00-d4b7-11e9-8a70-85c947777ed2.png)

I also have some filters and a button that redirects to another page. In this new page I would like to show only the date from the table, for printing.

Is there some way to do this?

Thank you for your help.

**Comment by unizhu** [comment]
1. Create a filter on the 2nd-page.
2. Try to search and check the URL parameters on the browser navigation bar. (e.g. projeto=Obra)
3. Add link or button on the 1st page:
```php
$grid->column('xxx')->display(function(){
       //button or link html e.g
       return "<a href='2nd-page?projeto=".$this->projeto."'>link name</a>
});
```
