### ISSUE TITLE
multipleImage 已传多图后，删除多张，刷新发现照片还有

### ISSUE THREAD

**Issue by hbkq110** [z-song/laravel-admin#3919]
- Laravel Version: 5.5.*
- PHP Version: 7.0
- Laravel-admin: 1.5

### Description:
![image](https://user-images.githubusercontent.com/24600445/64762518-e8c83880-d570-11e9-8fdb-bedcc05864f8.png)

**Comment by zzr7** [comment]
@hbkq110 你好，我倒是没出现这个问题。但是我用json字段保存多图，删除时可以删除成功，但是页面错乱，报 Unexpected token < in JSON at position 0 这个错误，请问你删除图片是否正常？ 是否有设置修改器和访问器？

**Comment by Nosirc** [comment]
@zzr7 你这个可以打开f12 看删除请求接口的返回值,应该是返回值不合规

**Comment by zzr7** [comment]
@Nosirc 感谢，我试一下

**Comment by chenjiabin** [comment]
从最后一张一张开始删除起
