### ISSUE TITLE
[HELP] Can you give example "Add ability to customize navbar."

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#392]
Like the title you can help me give customize navbar
Thanks

**Comment by z-song** [comment]
In `app/Admin/bootstrap.php`, add following code:
```php
use Encore\Admin\Widgets\Navbar;

Admin::navbar(function (Navbar $navbar) {

    $navbar->add(view('admin.navbar'));

});
```
Then you can customize your navbar in blade file of view `admin.navbar` like this:

```php
<li class="dropdown messages-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-envelope-o"></i>
        <span class="label label-success">4</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">You have 4 messages</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li><!-- start message -->
                    <a href="#">
                        <div class="pull-left">
                            <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Support Team
                            <small><i class="fa fa-clock-o"></i> 5 mins</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <!-- end message -->
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            AdminLTE Design Team
                            <small><i class="fa fa-clock-o"></i> 2 hours</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
                <li>
                    <a href="#">
                        <div class="pull-left">
                            <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
                        </div>
                        <h4>
                            Developers
                            <small><i class="fa fa-clock-o"></i> Today</small>
                        </h4>
                        <p>Why not buy a new awesome theme?</p>
                    </a>
                </li>
            </ul>
        </li>
        <li class="footer"><a href="#">See All Messages</a></li>
    </ul>
</li>
<!-- Notifications: style can be found in dropdown.less -->
<li class="dropdown notifications-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-bell-o"></i>
        <span class="label label-warning">10</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">You have 10 notifications</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li>
                    <a href="#">
                        <i class="fa fa-users text-aqua"></i> 5 new members joined today
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
                        page and may cause design problems
                    </a>
                </li>
                <li>
                    <a href="#">
                        <i class="fa fa-users text-red"></i> 5 new members joined
                    </a>
                </li>
            </ul>
        </li>
        <li class="footer"><a href="#">View all</a></li>
    </ul>
</li>
<!-- Tasks: style can be found in dropdown.less -->
<li class="dropdown tasks-menu">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        <i class="fa fa-flag-o"></i>
        <span class="label label-danger">9</span>
    </a>
    <ul class="dropdown-menu">
        <li class="header">You have 9 tasks</li>
        <li>
            <!-- inner menu: contains the actual data -->
            <ul class="menu">
                <li><!-- Task item -->
                    <a href="#">
                        <h3>
                            Design some buttons
                            <small class="pull-right">20%</small>
                        </h3>
                        <div class="progress xs">
                            <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                <span class="sr-only">20% Complete</span>
                            </div>
                        </div>
                    </a>
                </li>
                <!-- end task item -->
                <li><!-- Task item -->
                    <a href="#">
                        <h3>
                            Create a nice theme
                            <small class="pull-right">40%</small>
                        </h3>
                        <div class="progress xs">
                            <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                                <span class="sr-only">40% Complete</span>
                            </div>
                        </div>
                    </a>
                </li>
                <!-- end task item -->

            </ul>
        </li>
        <li class="footer">
            <a href="#">View all tasks</a>
        </li>
    </ul>
</li>
```

**Comment by zhangdong1104** [comment]
这尴尬得

**Comment by Baiyongjian** [comment]
> In `app/Admin/bootstrap.php`, add following code:
> 
> ```
> use Encore\Admin\Widgets\Navbar;
> 
> Admin::navbar(function (Navbar $navbar) {
> 
>     $navbar->add(view('admin.navbar'));
> 
> });
> ```
> 
> Then you can customize your navbar in blade file of view `admin.navbar` like this:
> 
> ```
> <li class="dropdown messages-menu">
>     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
>         <i class="fa fa-envelope-o"></i>
>         <span class="label label-success">4</span>
>     </a>
>     <ul class="dropdown-menu">
>         <li class="header">You have 4 messages</li>
>         <li>
>             
>             <ul class="menu">
>                 <li>
>                     <a href="#">
>                         <div class="pull-left">
>                             <img src="dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
>                         </div>
>                         <h4>
>                             Support Team
>                             <small><i class="fa fa-clock-o"></i> 5 mins</small>
>                         </h4>
>                         <p>Why not buy a new awesome theme?</p>
>                     </a>
>                 </li>
>                 
>                 <li>
>                     <a href="#">
>                         <div class="pull-left">
>                             <img src="dist/img/user3-128x128.jpg" class="img-circle" alt="User Image">
>                         </div>
>                         <h4>
>                             AdminLTE Design Team
>                             <small><i class="fa fa-clock-o"></i> 2 hours</small>
>                         </h4>
>                         <p>Why not buy a new awesome theme?</p>
>                     </a>
>                 </li>
>                 <li>
>                     <a href="#">
>                         <div class="pull-left">
>                             <img src="dist/img/user4-128x128.jpg" class="img-circle" alt="User Image">
>                         </div>
>                         <h4>
>                             Developers
>                             <small><i class="fa fa-clock-o"></i> Today</small>
>                         </h4>
>                         <p>Why not buy a new awesome theme?</p>
>                     </a>
>                 </li>
>             </ul>
>         </li>
>         <li class="footer"><a href="#">See All Messages</a></li>
>     </ul>
> </li>
> 
> <li class="dropdown notifications-menu">
>     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
>         <i class="fa fa-bell-o"></i>
>         <span class="label label-warning">10</span>
>     </a>
>     <ul class="dropdown-menu">
>         <li class="header">You have 10 notifications</li>
>         <li>
>             
>             <ul class="menu">
>                 <li>
>                     <a href="#">
>                         <i class="fa fa-users text-aqua"></i> 5 new members joined today
>                     </a>
>                 </li>
>                 <li>
>                     <a href="#">
>                         <i class="fa fa-warning text-yellow"></i> Very long description here that may not fit into the
>                         page and may cause design problems
>                     </a>
>                 </li>
>                 <li>
>                     <a href="#">
>                         <i class="fa fa-users text-red"></i> 5 new members joined
>                     </a>
>                 </li>
>             </ul>
>         </li>
>         <li class="footer"><a href="#">View all</a></li>
>     </ul>
> </li>
> 
> <li class="dropdown tasks-menu">
>     <a href="#" class="dropdown-toggle" data-toggle="dropdown">
>         <i class="fa fa-flag-o"></i>
>         <span class="label label-danger">9</span>
>     </a>
>     <ul class="dropdown-menu">
>         <li class="header">You have 9 tasks</li>
>         <li>
>             
>             <ul class="menu">
>                 <li>
>                     <a href="#">
>                         <h3>
>                             Design some buttons
>                             <small class="pull-right">20%</small>
>                         </h3>
>                         <div class="progress xs">
>                             <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
>                                 <span class="sr-only">20% Complete</span>
>                             </div>
>                         </div>
>                     </a>
>                 </li>
>                 
>                 <li>
>                     <a href="#">
>                         <h3>
>                             Create a nice theme
>                             <small class="pull-right">40%</small>
>                         </h3>
>                         <div class="progress xs">
>                             <div class="progress-bar progress-bar-green" style="width: 40%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
>                                 <span class="sr-only">40% Complete</span>
>                             </div>
>                         </div>
>                     </a>
>                 </li>
>                 
> 
>             </ul>
>         </li>
>         <li class="footer">
>             <a href="#">View all tasks</a>
>         </li>
>     </ul>
> </li>
> ```

 请问，自定义导航右侧<li>标签里的消息数怎么能动态化，从数据库取。看文档里好像没有。
