### ISSUE TITLE
行操作BUG

### ISSUE THREAD

**Issue by yuyulu** [z-song/laravel-admin#3924]
- Laravel Version: 5.8
- PHP Version:7.3.6
- Laravel-admin: 1.7.3

### Description:
![image](https://user-images.githubusercontent.com/29749865/64921277-d9a4ed00-d7f3-11e9-8cf2-cc59e233cbc8.png)

页面一旦缩放，所有按钮就没办法显示了

**Comment by augustpluscn** [comment]
请问这个问题有没有什么解决方案

**Comment by liangshuocj** [comment]
针对移动端访问，也是这个问题。。 页面排版错乱了。

**Comment by zzDylan** [comment]
关注一下

**Comment by liangshuocj** [comment]
> 关注一下

楼上有位大佬解决了这个问题，坐等 @z-song  大佬更新啦，万分感谢 @cawa0505

**Comment by z-song** [comment]
已更新！
