### ISSUE TITLE
Laravel 6 support

### ISSUE THREAD

**Issue by vlalaw** [z-song/laravel-admin#3928]
- Laravel Version: 6.0.3
- PHP Version: 7.3
- Laravel-admin: 1.7.7

### Description:
Can't install extensions on laravel 6. Seems like a global issue for most extensions so I post it here.

### Steps To Reproduce:
composer require laravel-admin-ext/redis-manager
or
composer require laravel-admin-ext/scheduling

**Comment by bthiban** [comment]
composer require laravel-admin-ext/api-tester -vvv

As well
