### ISSUE TITLE
edit password

### ISSUE THREAD

**Issue by ridwans2** [z-song/laravel-admin#3929]
- Laravel Version:  5.5
- PHP Version:  7.2
- Laravel-admin: 1.7

### Description:
how to encrypt password when edit?

### Steps To Reproduce:

https://prnt.sc/p72i3n
i made user controller and model
when i try to edit with new password, its become normal text, not encrypted
i need password field encrypted by Bcrypt()

**Comment by pokleh** [comment]
i found this example on demo version.

$form->saving(function (Form $form) {
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = bcrypt($form->password);
            }
        });
