### ISSUE TITLE
如何自定义User表？

### ISSUE THREAD

**Issue by yatong2008** [z-song/laravel-admin#393]
laravel-admin初始化的时候就建立了User Table
如果我想在这个table里面加一些别的内容，比如FirstName LastName DateOfBirth之类的，该如何改文件？在project里面找了半天看不到源文件，好像不能改vendor里面的源文件吧？

**Comment by z-song** [comment]
你可以直接在mysql里面跑sql语句，不用去修改文件了，比如：
```sql
ALTER TABLE `admin_users` ADD COLUMN `first_name` varchar(255) CHARACTER SET utf8 COLLATE utf8_unicode_ci NOT NULL;
```

**Comment by yatong2008** [comment]
不好意思可能没有问的清楚，我知道需要添加column可以再DB里面操作，不过如果我想在/admin/auth/users/*/edit里面按照table的column来修改from()和grid()的时候，我找不到默认的UserController，我改了一些column名字之后，出现SQL error比如像
 QueryException In Connection.php line 770 :

SQLSTATE[42S22]: Column not found: 1054 Unknown column 'name' in 'field list' (SQL: update `admin_users` set `password` = $2y$10$2KFI/vy84Z4v2YXWVp3e4eF35pc68Td0KlP6L8xqc99ak58GQpqGu, `updated_at` = 2017-02-12 06:10:47, `name` = t1 where `id` = 2)

请问如何修改默认的page里面这个grid() form() ？

**Comment by yatong2008** [comment]
问题补充，比如我之前用自带的auth的时候我可以在User class里面添加自定义的column到fillable里面，然后修改register.blade来修改界面，但是我在laravel-admin中修改了user table之后，找不到对应class，不知如何修改fillable之类的

**Comment by z-song** [comment]
打开`config/admin.php`, 找到`database`的配置，里面有`laravel-admin`内置表的模型和表名配置，你完全可以修改成自己的表和模型。

**Comment by yatong2008** [comment]
追加一个小问题，我是用了自己的User Model和Controller之后，我添加了一个Middleware，但是我在Middleware里面使用方法Auth::user()的时候无法获得当前的user，请问laravel-admin里面的是否有方法获取current user的？

**Comment by yatong2008** [comment]
已经在这里找到了答案
http://z-song.github.io/laravel-admin/index.html#/zh/permission.md

**Comment by pcfjojo** [comment]
@z-song When using tenancy, is it not enough only say the connection. I think all your models are depends on other models like Permission, Role etc.. how to simple set the admin model connection to the tenent connection?
