### ISSUE TITLE
自定义行操作方法绑定时报错

### ISSUE THREAD

**Issue by pianqifei** [z-song/laravel-admin#3933]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/26913071/65126788-9b910e80-da29-11e9-8be6-1c80ea13eac0.png)
laravel-admin 1.7.7 php7.2 laravel 6.0.3

**Comment by pianqifei** [comment]
![image](https://user-images.githubusercontent.com/26913071/65127090-c1b6ae80-da29-11e9-8112-8ed3e4716b10.png)

**Comment by phpcxy** [comment]
你laravel-admin是从旧版本升级上来，还是新安装的1.7.7？

**Comment by pianqifei** [comment]
更新上来的 强制重新发布所有的前端资源后问他解决



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "XinYong&nbsp;Chen"; 
发送时间: 2019年10月9日(星期三) 中午11:09
收件人: "z-song/laravel-admin";
抄送: "pianqifei"<1726441799@qq.com>;"Author";
主题: Re: [z-song/laravel-admin] 自定义行操作方法绑定时报错 (#3933)




你laravel-admin是从旧版本升级上来，还是新安装的1.7.7？
 
&mdash;
