### ISSUE TITLE
使用loads选择联动,编辑时没有选中值,而是重新赋值

### ISSUE THREAD

**Issue by yangforme** [z-song/laravel-admin#3934]
- Laravel Version: 5.8
- PHP Version:7.1.3
- Laravel-admin: 1.7.6

### Description:
        我有一个需求,根据仓库的选择,分别联动物品分类和摆放地区,新增的时候没问题,但是修改的时候,并没有选中值,而是根据仓库id重新查找分类和子类的集合,然后默认选中第一个值,请问要怎么做才可以在编辑时,显示当前值为选中状态

### Steps To Reproduce:
 $form->select('w_id', __('仓库'))->options('/api/getWarehouse')->loads(['pt_id','a_id'],['/api/getPartstype','/api/getArea']);
        $form->select('pt_id', __('分类'))->load('pdt_id', '/api/getPdType');
        $form->select('pdt_id', __('子类'));
        $form->select('a_id', __('摆放地区'));

**Comment by changanbeilu39hao** [comment]
我也有这个问题

**Comment by malonzhao** [comment]
修改vendor/encore/laravel-admin/src/Form/Field/Select.php 文件中 load() 和 loads()方法；
在EOF;前加上以下代码：
`$("{$this->getElementClassSelector()}").each(function(){
    if ($(this).data('value')) {
        $(this).trigger('change');
    }
})`
[PR](https://github.com/z-song/laravel-admin/pull/3835)

**Comment by sicaboy** [comment]
@malonzhao 谢谢分享, 这个方法可以在编辑页面载入联动菜单中的内容, 但是有个问题, 载入完后没有选定之前的数据. (之前主次菜单分别选了 "家电"->"第二条", 但是显示"家电",ajax请求次级菜单后选择了"第一条"). 麻烦大神分享一下解决方法

**Comment by jianzhiyao** [comment]
加了代码以后可以了
```javascript
//需要最后加分号，最新版本不加分号会报错
$("{$this->getElementClassSelector()}").each(function(){ if ($(this).data('value')) { $(this).trigger('change'); } });
```
