### ISSUE TITLE
laravel 调用google矩阵api，使用file_get_contents报错

### ISSUE THREAD

**Issue by guyaofei** [z-song/laravel-admin#3936]
问个问题我在laravel中调用google矩阵测量两地剧里，在laravel框架中用file_get_contents(),请求api的时候报错，但是在框架外，不会报错
![QQ图片20190918175241](https://user-images.githubusercontent.com/30075084/65138501-a05fbd80-da3d-11e9-8963-712d81773d25.png)

**Comment by unizhu** [comment]
这不是被墙了么。。。

**Comment by guyaofei** [comment]
@unizhu 我知道啊，可是为啥我在框架外面使用没事呢，在框架外是可以访问的
![image](https://user-images.githubusercontent.com/30075084/65210841-237d2400-dacf-11e9-9646-a0c77ec92ac3.png)

**Comment by unizhu** [comment]
https://www.php.net/file_get_contents
https://www.php.net/manual/en/function.stream-context-create.php

试试：
```php
$opts=array(
    "ssl"=>array(
        "verify_peer"=>false,
        "verify_peer_name"=>false,
    ),
);  

$response = file_get_contents("https://google.com", false, stream_context_create($opts));
```

不过感觉还是GFW的问题
