### ISSUE TITLE
Google Maps Autocomplete search box

### ISSUE THREAD

**Issue by MsFoued** [z-song/laravel-admin#394]
How to add Google Maps Autocomplete search box?

**Comment by z-song** [comment]
Any example?

**Comment by MsFoued** [comment]
i added the following script in the file vendor\encore\laravel-admin\views\partials\js.blade.php under the @foreach bloc :
 <script>
    function initialize() {

        new google.maps.places.Autocomplete((document.getElementById("myInputId")), {
                       types: ["geocode"]
                });
        		}

        initialize();

</script> 

also you need to add GOOGLE_API_KEY=yourGoogleApiKey in the .env file

**Comment by z-song** [comment]
You can use `Admin::script('your scripts here');` to inject javascript code to current page, and avoid edit file in `laravel-admin` vendor.

**Comment by MsFoued** [comment]
great!

**Comment by mRamadan0101** [comment]
> You can use `Admin::script('your scripts here');` to inject javascript code to current page, and avoid edit file in `laravel-admin` vendor.
can i use this in form ?
