### ISSUE TITLE
Call to undefined method Encore\Admin\Grid\Displayers\Actions::add()

### ISSUE THREAD

**Issue by pcfjojo** [z-song/laravel-admin#3943]
laraval admin version : * dev-master
laravel/framework 6.0

 **Call to undefined method Encore\Admin\Grid\Displayers\Actions::add()** 

In windows 10 it is working, But in Linux server through this error.

Note: I have did all update steps, including clear cache etc.

**Comment by kingofzihua** [comment]
edit you app/admin.php

add or update 
'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,


see : https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=old-version-compatible

**Comment by pcfjojo** [comment]
Closing this issue, as i have risolved this pointing action class in admin.php.

**Comment by maxlcoder** [comment]
> edit you app/admin.php
> 
> add or update
> 'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,
> 
> see : https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=old-version-compatible

how to keep the actions  display as them in old version? I don't want to use the dropdown style.

**Comment by tkin1992** [comment]
> > edit you app/admin.php
> > add or update
> > 'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,
> > see : https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=old-version-compatible
> 
> how to keep the actions display as them in old version? I don't want to use the dropdown style.

You can publish laravel-admin views and rewrite your own dropdown-menu style.
see: https://github.com/z-song/laravel-admin/issues/368#issuecomment-386967894
