### ISSUE TITLE
急，求楼主帮忙改善这个样式问题啊！！！！

### ISSUE THREAD

**Issue by jsonlove-cc** [z-song/laravel-admin#3946]
Laravel版本：5.5.*
PHP版本：7.1.9
Laravel-admin：1.6

布局样式的问题
[问题.docx](https://github.com/z-song/laravel-admin/files/3634037/default.docx)
![问题](https://user-images.githubusercontent.com/55566773/65296378-d3699480-db96-11e9-824d-678f9cc19835.png)
![想要](https://user-images.githubusercontent.com/55566773/65296383-d49ac180-db96-11e9-873e-dbaafeace856.png)

**Comment by cawa0505** [comment]
![螢幕快照 2019-09-20 下午10 50 47](https://user-images.githubusercontent.com/3434037/65337705-46a4f200-dbfb-11e9-9790-007b4fa6da6f.png)

1. 六欄是真的有點多啦，所以改了一個範例供參考，官網的文檔是分兩欄。
2. adminlte2 是基於 bootstrap3，偏偏 bootstrap 3 的 control-label 是 float: right，所以只好多一個判斷螢幕顯示的 label(不加任何自訂的 css 作法)。
3. 只改了 where.blade.php，其他像是 between 在 md 時若多欄位也是會太長。
