### ISSUE TITLE
使用外部数据源的Grid中的查询过滤

### ISSUE THREAD

**Issue by heivin** [z-song/laravel-admin#3947]
使用外部数据源的Grid中的查询过滤，Model中的where方法应该static

文档中的例子    
// 覆盖`where`来收集筛选的字段和条件
    public function where($column, $operator = null, $value = null, $boolean = 'and')
    {

    }

实际应该写成
static public function where($column, $operator = null, $value = null, $boolean = 'and')
    {
        dd($column);
    }

**Comment by MrKaGod** [comment]
不好使啊，打印$column没有反应

**Comment by MrKaGod** [comment]
@heivin 不好使啊，打印$column没有反应
