### ISSUE TITLE
Find a way to save pivot table along with some attributes

### ISSUE THREAD

**Issue by peacemoon** [z-song/laravel-admin#395]
As I can see from this https://github.com/z-song/laravel-admin/blob/1.4/src/Form.php#L634 , there is no way to save the relations with some attached attributes, we should think of away to attach some additional attributes to the pivot table.

**Comment by fuacici** [comment]
in the same situation now

**Comment by peacemoon** [comment]
@z-song any suggestion to solve this problem?

**Comment by z-song** [comment]
Currently only `MultipleSelect` and `Checkbox` supports `BelongsToMany` relation, any other scenario need to save attributes to the pivot table?

**Comment by peacemoon** [comment]
For example you have 2 Models Posts & Comments
```
products
id - integer

features
id - integer

product_feature
product_id - integer
feature_id -integer
is_enabled - boolean
```
At this moment, there is no way to save value for the attribute `is_enabled` into pivot table `product_feature`.

**Comment by z-song** [comment]
I mean i didn't find any type of field can save relation and pivot attributes at the same time.

**Comment by peacemoon** [comment]
:) sorry but I still don't understand what you mean.

1. I can not find any built-in functionality in laravel-admin to accomplish that purpose, so I ask you if you know how to do something like this with the current code base.
2. If you asking me for a solution, I don't have any. But I see that you implemented `hasMany` type field, and using NestedForm to save data into the related table. I think we could use something similar to save attributes into the pivot table.
3. If you asking me for what scenarios I'm using so that you can implement a solution, then yes, I'm using `MultipleSelect` to save data to the pivot table.

Hope this can clarify my thought here.

**Comment by z-song** [comment]
I also don't have any solution.

`MultipleSelect` only save relations, and how do you save data to the pivot table?

**Comment by peacemoon** [comment]
@z-song @edwinhuish : Yes, I'm using `$form->saving()` & `$form->saved()` at this moment to save additional attributes in pivot tabl using `$form->model()->realation()->sync()` 
But it would be nice if `Form` can handle `belongsToMany` as `hasMany` internally.

**Comment by anhhuy2000** [comment]
Hi peacemoon,

Can you please share how you handle that in $form->saving() & $form->saved()? I am in the same situation and trying to work out how to use that feature?

Many thanks,
Alan

**Comment by edwinhuish** [comment]
@matondojoao put your example code here, please don't ask questions in unrelated projects

**Comment by edwinhuish** [comment]
> @antranapp @anhhuy2000 @z-song @fuacici could you help me please to Find a way to save pivot table along with some attributes i do not know how to use $form->saving() & $form->saved() , $form->model()->realation()->sync() give me some examples pelase

Before asking question, please provide minimum demo

**Comment by matondojoao** [comment]
@edwinhuish here is my pivot table colled fees_months

Schema::create('fees_months', function (Blueprint $table) {
            $table->id();
            $table->double('fee_value')->nullable();
            $table->boolean('fine')->nullable();
            $table->double('fine_value')->nullable();
            $table->boolean('discount')->nullable();
            $table->double('discount_value')->nullable();
            $table->unsignedBigInteger('pagamento_propina_id')->nullable();
            $table->foreign('payment_fees_id')->references('id')->on('payment_fees')->onDelete('cascade');
            $table->unsignedBigInteger('month_id')->nullable();
            $table->foreign('month_id')->references('id')->on('months')->onDelete('cascade');
            $table->timestamps();
        });

here is my relationship

public function months()
    {
        return $this->belongsToMany(Month::class, 'fee_months', 'fee_payment_id', 'month_id');
    }

here is my controller

$form->multipleSelect('months', __('Months'))->options(function ($id) {
            $m = Month::find($id);

            if ($m) {
                return [$m->id => $m->name];
            }
        })->ajax('/admin/months/list');
        
when associating the fee with the months I want to insert the discount amount, fee_value and fine_value which are in the pivot table

**Comment by edwinhuish** [comment]
[As I said before](https://github.com/z-song/laravel-admin/issues/395#issuecomment-284458861),  you could split the many-to-many relation to 2 has-many relation for form
