### ISSUE TITLE
步骤表单：浏览文件，点击下一步，出现异常，怎么解决？Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: The GET method is not supported for this route. Supported methods: POST.

### ISSUE THREAD

**Issue by js201909** [z-song/laravel-admin#3951]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
步骤表单：浏览文件，点击下一步，出现异常，怎么解决？Symfony\Component\HttpKernel\Exception\MethodNotAllowedHttpException: The GET method is not supported for this route. Supported methods: POST.

**Comment by js201909** [comment]
是路径问题，已解决

**Comment by pcfjojo** [comment]
@js201909  in which version it is resolved?

**Comment by js201909** [comment]
version 1.7.6
