### ISSUE TITLE
select框一个让我苦恼很久的问题

### ISSUE THREAD

**Issue by chenzhulin** [z-song/laravel-admin#3954]
- Laravel Version: 6.0
- PHP Version:7.2
- Laravel-admin: 1.7

### Description:
我有一张商品表和一张商品详情表，关系是一对一的，我添加商品详情时，比较了商品表和商品详情表，因为我添加只给没有商品详情的商品添加，然后我把数据转换成了
$directors = [
    1 => 'John',
    2 => 'Smith',
    3 => 'Kate' ,
];这样
下面是对应的调用
$form->select('good_id', '商品名称')->options($directors);
但是保存时，却提示我good_id没有值，我也输出过提交时的保单数据，里面确实是有值的，但是还是给我报错，很疑惑

**Comment by nkjackzhang** [comment]
你这个select的options是从1开始的，所以表单上默认没有任何一个被选中，所以如果你提交表单之前没有选中一个选项，提交表单后good_id是没有值的。

**Comment by chenzhulin** [comment]
> 你这个select的options是没有0的，所以表单上默认没有任何一个被选中，所以如果你提交表单之前没有选中一个选项，提交表单后good_id是没有值的。

后面解决了，问题出在我判断了当前的url地址，导致的，换了另一种方式判断之后，这个问题就解决了
