### ISSUE TITLE
模型详情一对一问题

### ISSUE THREAD

**Issue by iiDestiny** [z-song/laravel-admin#3959]
- Laravel Version: 5.8
- PHP Version: 7.2
- Laravel-admin: 1.7.3

### Description:
在模型详情中一对一关系显示中如何禁用右上角操作按钮

![image](https://user-images.githubusercontent.com/17637481/65414834-12157e00-de27-11e9-8ecc-8ec9060504bf.png)

**Comment by unizhu** [comment]
和$grid使用的方式一样啊。

**Comment by iiDestiny** [comment]
不行的，都试过了。你试一下

**Comment by iiDestiny** [comment]
那是 「一对多」 才可以使用 Grid

**Comment by unizhu** [comment]
``php
$userInfo->panel()
    ->tools(function ($tools) {
        $tools->disableEdit();
        $tools->disableList();
        $tools->disableDelete();
    });;
```
因为是继承show的，所以应该有这个方式。

**Comment by iiDestiny** [comment]
没有的

**Comment by nkjackzhang** [comment]
> 
> 
> 没有的

源码里有这种用法，不过按照文档的写法，应该是
```
Admin::show($user,  function (Show $show){
        $show->panel()->tools(function(Tools $tools) {
            $tools->disableEdit();
            $tools->disableList();
            $tools->disableDelete();
        });
});
```
