### ISSUE TITLE
Multiple select can not set original values if pivot table has some extra attributes

### ISSUE THREAD

**Issue by peacemoon** [z-song/laravel-admin#396]
This line https://github.com/z-song/laravel-admin/blob/4cf05dada263e5d855a9804bf2e26a86d5f11c5a/src/Form/Field/MultipleSelect.php#L17 assumes that the id of related column is at the end of the array. This assumption doesn't work if the pivot table has some extra attributes.

**Comment by z-song** [comment]
Thanks for point out this issue !

I fixed this by add a method which will find the `otherKey` of `BelongsToMany` relation automatically.

**Comment by peacemoon** [comment]
Can you also merge this to 1.4 branch? I'm currently using branch 1.4 with Laravel 5.4 and it would be helpful if this fix is also available in 1.4

**Comment by z-song** [comment]
This fix merged to 1.4 branch now.

**Comment by peacemoon** [comment]
In Laravel 5.4, `BelongToMany` has `getQualifiedRelatedKeyName` instead of `getOtherKey`. I made a new pull request to fix this issue https://github.com/z-song/laravel-admin/pull/407

**Comment by z-song** [comment]
Thanks!  I didn't notice this, your pr already merged.
