### ISSUE TITLE
编辑页面的文件预览图报错

### ISSUE THREAD

**Issue by MoonLiu666** [z-song/laravel-admin#3960]
- Laravel Version: 5.5.#
- PHP Version:7.0
- Laravel-admin: 1.7.#

### Description:

编辑页面的文件预览图报错，除了图片能正常展示，其他格式附件都无法正常展示，excel甚至报错了，有没有办法优化一下？

另外，有没有办法关闭上面的预览图，但是保留下面的下载删除按钮？

![QQ图片20190923182548](https://user-images.githubusercontent.com/22115885/65419926-5ce8c300-de32-11e9-93e1-b37d9050b0fa.png)

**Comment by LiweiDong** [comment]
我这图片 查看页预览正常 编辑页显示不了  路径多了一层public

**Comment by almas1992** [comment]
这个问题最终怎么解决的？

**Comment by faydanube** [comment]
同问~~ 此问题还没有完美解决~~被自动关闭了 =.=
