### ISSUE TITLE
How to use raw query in grid?

### ISSUE THREAD

**Issue by enaeim** [z-song/laravel-admin#3963]
Hi.
How to use raw query in grid?
thanks for your guide.

**Comment by bthiban** [comment]
$grid->model()->where('id', '>', 100);

$grid->model()->orderBy('id', 'desc');

$grid->model()->take(100);

**Comment by enaeim** [comment]
no. no. I don't want to use query builder. I need to use raw query. @bthiban

**Comment by pcfjojo** [comment]
@enaeim 
$grid->model()
        ->select(
            \DB::raw(
                'customers.name',
                'loans.total as total_amount',
                'sum(loan_payments.paid) as total_paid'
        ->orderBy('customers.name', 'desc')
        ->groupBy('loan_payments.loan_id', 'loan_payments.customer_id');

**I hope this may help you.**
