### ISSUE TITLE
可不可以把下拉框接入树状数据！！！！！急 -》看图

### ISSUE THREAD

**Issue by jsonlove-cc** [z-song/laravel-admin#3965]
- Laravel Version: 5.7.19
- PHP Version:7.1.9
- Laravel-admin: 1.6.3

### Description:
能不能把下拉框搞成像这样的，怎么做？
![image](https://user-images.githubusercontent.com/55566773/65573974-bb32b480-df9e-11e9-9f53-ffe00853f6f0.png)

**Comment by z-song** [comment]
暂不支持

**Comment by parse-dinghua** [comment]
可以做出这样的，不能交互，只能展示

![image](https://user-images.githubusercontent.com/54979620/65659727-2a6fdd80-e05f-11e9-9a96-0434db6409ae.png)

**Comment by guohanlin1** [comment]
> 暂不支持

好的，谢谢

**Comment by guohanlin1** [comment]
> 可以做出这样的，不能交互，只能展示
> 
> ![图片](https://user-images.githubusercontent.com/54979620/65659727-2a6fdd80-e05f-11e9-9a96-0434db6409ae.png)

只能展示没作用就没意义了把。。。
