### ISSUE TITLE
How to make Laravel admin custom tool

### ISSUE THREAD

**Issue by Iceberg1109** [z-song/laravel-admin#3967]
- Laravel Version: 5.7.0
- PHP Version:
- Laravel-admin: #.#.#

### Description:
https://github.com/z-song/laravel-admin/blob/master/docs/en/model-grid-custom-tools.md
I followed above link to make a custom tool.
But when I finished and tried it, it says it couldn't find the CheckReminder.
(I changed UseGender to CheckReminder)

![image](https://user-images.githubusercontent.com/49850848/65586772-4ae45d00-dfb7-11e9-9a40-7807bc23b582.png)

I use this tool on admin controller
this is my code
ReminderController.php
protected function grid()
    {
        $grid = new Grid(new Customer_reminder);

        $grid->id('Id');
        $grid->email('Email');
        $grid->days('Days');
        $grid->status('Status');
        $grid->created_at('Created at');
        $grid->updated_at('Updated at');
        $grid->tools(function ($tools) {
            $tools->append(new CheckReminder());
        });
        return $grid;
    }

CheckReminder.php
![image](https://user-images.githubusercontent.com/49850848/65587181-04433280-dfb8-11e9-9603-a3c8da9f86c4.png)

I think i have to import the CheckReminder tool
but not sure how to do it.
Help me.

code structure

![image](https://user-images.githubusercontent.com/49850848/65587020-b9c1b600-dfb7-11e9-8cf2-17a9974c85e0.png)

**Comment by vonsogt** [comment]
You should define the CheckReminder class into your controller

add this into **ReminderController.php**:
`use App\Admin\Actions\Post;`

**Comment by Smart1109** [comment]
so move CheckReminder.php to /admin/controller directory?

**Comment by vonsogt** [comment]
> so move CheckReminder.php to /admin/controller directory?

check my new edit

**Comment by Smart1109** [comment]
thanks for your reply
I will do it and get back
