### ISSUE TITLE
laravel-admin form hasMany 富文本编辑器如何使用？

### ISSUE THREAD

**Issue by yupengzhen** [z-song/laravel-admin#3969]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.7

您好，想问一下：在使用表单form->hasMany 下有富文本编辑器，富文本编辑器会自动变成文本输入框，有没有好的办法解决？
$form->hasMany('modules','会议模块',function($form){
        $form->text('moduleName','模块名称');
        $form->editor('moduleContent','模块内容');
 });

**Comment by vgocoder** [comment]
遇到同样的问题

**Comment by Cuifc** [comment]
请问这个问题解决了吗

**Comment by vgocoder** [comment]
@Cuifc 没解决

**Comment by lexingzai** [comment]
遇到同样的问题

**Comment by xnzj** [comment]
可以修改富文本编辑器生成 id 的代码，比如 wangeditor:
增加一行代码即可，已验证。可以用我改过的 package 
`composer require "xnzj/wang-editor-fix:1.*"`
其他富文本编辑器我想是同理
```php
// Editor.php
public function render()
{
    $this->id = str_replace('.', '', $this->id . microtime(true)); <-- 增加这一行即可
    $id = $this->formatName($this->id);

    $config = (array) WangEditor::config('config');

    $config = json_encode(array_merge([
        'zIndex'              => 0,
        'uploadImgShowBase64' => true,
    ], $config, $this->options));
```
