### ISSUE TITLE
Remove password value in edit mode ?

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#397]
How to remove value password in edit mode ?
[![https://gyazo.com/a4aad6da2bc956436582605176270304](https://i.gyazo.com/a4aad6da2bc956436582605176270304.png)](https://gyazo.com/a4aad6da2bc956436582605176270304)

**Comment by z-song** [comment]
Set hidden columns in your model:
```php
protected $hidden = ['password'];
```

**Comment by taimaiduc** [comment]
[![https://gyazo.com/ef9d962f98fc9aa34a6b99b0e4d373cb](https://i.gyazo.com/ef9d962f98fc9aa34a6b99b0e4d373cb.png)](https://gyazo.com/ef9d962f98fc9aa34a6b99b0e4d373cb)
I using protected $hidden = ['password'];
But when to to edit value is **1** ?
[![https://gyazo.com/a6bc9d8af7b5b6a7c05cfd25fdb0c1f4](https://i.gyazo.com/a6bc9d8af7b5b6a7c05cfd25fdb0c1f4.png)](https://gyazo.com/a6bc9d8af7b5b6a7c05cfd25fdb0c1f4)
