### ISSUE TITLE
重写paginate后，重写的where方法不生效

### ISSUE THREAD

**Issue by MrKaGod** [z-song/laravel-admin#3971]
- Laravel Version: 5.8.35
- PHP Version:7.2.18
- Laravel-admin: 1.6

### Description:
在model文件中重写了paginate方法
使用filter搜索时，打断点发现where方法依旧使用的是框架本身的where方法，自己从新定义的where并不生效。
如果将重写的paginate方法注释掉，使用filter搜索时，where方法居然使用的是从新定义的where，框架本身的where方法缺不起效。

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/20720787/65651911-782a1d00-e042-11e9-8b87-572da6d8a8dc.png)

**Comment by z-song** [comment]
你可以在paginate方法中获取查询参数来组装查询条件

**Comment by MrKaGod** [comment]
在我没有更新laravel-admin的时候，这个方法都是行得通的，可是更新后就不好使了，请问是为什么呢？

**Comment by komahui** [comment]
更新之后筛选那里已经被改过了，现在只能paginate方法获取参数来组装条件了

**Comment by MrKaGod** [comment]
好吧，谢谢

**Comment by MrKaGod** [comment]
@z-song 这个功能希望可以在文档中提现一下，谢谢
