### ISSUE TITLE
$form->divider()能否添加像表单控件那样设置属性方法

### ISSUE THREAD

**Issue by Yuner20** [z-song/laravel-admin#3972]
- Laravel Version: 6.0.0
- PHP Version:7.2.22
- Laravel-admin: 1.7.7

### Description:
现在有个需求，需要对分隔线做一些样式设置，对它设置一个类方便写css，发现没有能够像表单控件那样有个attribute方法，作者能否考虑让它支持一下，在此感谢！

**Comment by jqhph** [comment]
这么简单的需求你自己重写一个divider字段就行了，参考下表单字段扩展的相关文档

**Comment by Yuner20** [comment]
使用$form->html()解决问题，谢谢作者！
