### ISSUE TITLE
左侧菜单无法全部显示

### ISSUE THREAD

**Issue by smm229** [z-song/laravel-admin#3974]
- Laravel Version: 5.8
- PHP Version: 7.2
- Laravel-admin: 1.7.3

### Description:
左侧菜单过多时，左侧菜单无法上下滑动

**Comment by nkjackzhang** [comment]
左侧菜单在载入过程中是无法滑动的，载入完成就可以正常滑动了，你说的无法滑动是在哪个过程账中无法滑动？如果载入完成还无法滑动，这时候菜单是多少个？

**Comment by smm229** [comment]
载入完成之后无法上下滑动，一级菜单12个，点开最底下的一级菜单，其中包含子菜单6个，只能显示4个，剩下的菜单无法显示，也无法上滑
