### ISSUE TITLE
$grid->column('title')->width(200);BUG

### ISSUE THREAD

**Issue by manren** [z-song/laravel-admin#3976]
- Laravel Version: 5.8.#
- PHP Version:7.2
- Laravel-admin: 1.7

### Description:
$grid->column('title')->width(200);设置宽度不生效
看到是在<td>标签加的style这样好像是不行，如果设置宽度，过长的是overflow:hidden还是换行也没有明确声明，还是会撑开

**Comment by z-song** [comment]
我这边使用width设置宽度是正常的，无法重现这个问题

**Comment by Haovk** [comment]
在使用新版下拉按钮时候会出现一样的情况
$grid->setActionClass(DropdownActions::class);
使用width会顶出去
使用style会溢出
