### ISSUE TITLE
How to get value of ID in the form?

### ISSUE THREAD

**Issue by june415** [z-song/laravel-admin#3981]
- Laravel Version: 5.7.12
- PHP Version: 7.1
- Laravel-admin: 1.7.0

### Description:
我想在当前的form中添加一个发送邮件的按钮，需要提取当前form里用户的ID，有么有哪位大神知道怎么获取表格里的数据？

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/32455481/65757010-d0e3dd80-e148-11e9-927b-f5e54d0c93a8.png)

**Comment by CoderMrPu** [comment]
$form->tools(function () use ($form) {
         $form->model()->id;
})

**Comment by CoderMrPu** [comment]
```php
$form->tools(function () use ($form) {
       $form->model()->id;
})
```

**Comment by june415** [comment]
我试过 $form->model()->id; 但是$form好像是空的，没有value
![image](https://user-images.githubusercontent.com/32455481/65760986-9716d500-e150-11e9-97ae-0bd3ef8f30c9.png)

**Comment by maksimbondarau** [comment]
@june415 I suggest overriding the edit() method in your controller and adding a id parameter when called form():

    public function edit($id, Content $content)
    {
        return $content
            ->title($this->title())
            ->description($this->description['edit'] ?? trans('admin.edit'))
            ->body($this->form($id)->edit($id));
    }

    public function form($id = null) {
        ...
       $form->tools(function ($tools) use ($id) {

       });
       ...
    }

**Comment by june415** [comment]
> function ($too

@maksimbondarau Thanks! It works!
