### ISSUE TITLE
字段值为时间戳，用date方法格式化输出的问题！！！

### ISSUE THREAD

**Issue by komahui** [z-song/laravel-admin#3988]
$grid->column('created_at')->date('Y-m-d');如果值为空，就变成1970了

**Comment by z-song** [comment]
用display方法来处理这个问题吧

**Comment by nkjackzhang** [comment]
> 
> 
> 用date不就是为了方便吗

display也不麻烦，date就是给无空值字段用的，要不然你写个pr修改下，有空值的话返回空字符串吧。
