### ISSUE TITLE
v1.7.3后，软删除记录的操作请加以注意 

### ISSUE THREAD

**Issue by laoha0201** [z-song/laravel-admin#3989]
v1.7.3版本对数据表格的行操作和批量操作进行了重构后，软删除记录的操作的会出现问题，例如对软删除记录添加一个恢复行操作，会使用到：
Encore\Admin\Actions\RowAction 文件中的
```
    public function retrieveModel(Request $request)
    {
        if (!$key = $request->get('_key')) {
            return false;
        }

        $modelClass = str_replace('_', '\\', $request->get('_model'));

        return $modelClass::findOrFail($key);
    }
```
其中$modelClass::findOrFail($key);这样的查询，显然将软删除记录都排除在外，而使其无法操作...

**Comment by z-song** [comment]
在RowAction类中增加了一个属性`$withTrashed`来控制是否查询软删除的数据，自定义行操作类的时候，设置为true就可以了
