### ISSUE TITLE
Model Show Relations

### ISSUE THREAD

**Issue by itsnotyoutoday** [z-song/laravel-admin#3990]
- Laravel Version: 6.x
- PHP Version: 7.3.9
- Laravel-admin: 1.7

### Description:
Model shows aren't showing relations correctly.

### Steps To Reproduce:
For Example:
$show->field('user.username', 'User');

This will display nothing in the display over the User.  However, if I omit the .username i will see all the json of the relation.

**Comment by vonsogt** [comment]
Try this
```
$show->field('user_id', 'User')->as(function ($user_id) {
    return UserModel::where('id', $user_id)->first()->name ?? null;
});
```

**Comment by AvionicsBird** [comment]
Thanks, that a good workaround.

**Comment by nkjackzhang** [comment]
I haven't use version 1.7, but after I readed the doc, I found you can find answer on [this page](https://laravel-admin.org/docs/#/en/model-show-relationship)
