### ISSUE TITLE
User Object in Backend Admin

### ISSUE THREAD

**Issue by itsnotyoutoday** [z-song/laravel-admin#3991]
- Laravel Version: 6.x
- PHP Version: 7.3.9
- Laravel-admin: 1.7
### Description:
The Admin:: facade does not retrieve the right user object.  It seems to be retrieving the builtin Administrator user object regardless of if you swapped out the user model to your own user model in your web app.  Should you try to grab the user object between Auth:: that doesn't work as it seems that facade is only valid for the frontend.

### Steps To Reproduce:
1. Replace the default user model with your own in the config files.
2. Override a a default laravel-admin-view (such as header.blade.php).  In my case, I grab avatars differently, so I'm trying to use a function off of my user object to display correctly in the laravel-admin them.

```
                        <img src="{{ Admin::user()->image() }}" class="user-image" alt="User Image">
                        <!-- hidden-xs hides the username on small devices so only the image appears. -->
                        <span class="hidden-xs">{{ Admin::user()->name }}</span>`
```
3. Refresh the admin page..

> Facade\Ignition\Exceptions\ViewException
> Call to undefined method Encore\Admin\Auth\Database\Administrator::image() (View: C:\Users\admin\PhpstormProjects\mywebsite\resources\views\vendor\admin\partials\header.blade.php)
> http://mysite.localhost/admin/auth/users

**Comment by uacode** [comment]
What about \Auth::user() ?

**Comment by AvionicsBird** [comment]
\Auth::user() is null when the front end is not logged in and only authenticated through the backend.. It seems \Auth:: doesn't cover the middleware over laravel-admin side of things

**Comment by z-song** [comment]
@AvionicsBird You also need to replace `auth.providers.admin.model` with your custom user model in admin.php
