### ISSUE TITLE
This looks really nice... even in chinese...

### ISSUE THREAD

**Issue by axyr** [z-song/laravel-admin#4]
This is what I was looking for..

It installed straightforwarded and without errors.

It would be really nice if you could default to englush though... :)

**Comment by axyr** [comment]
awesome ! :)

**Comment by z-song** [comment]
Now you can update the package and reinstall it.

I add a command `artisan admin:uninstall` to remove old files and directories.

**Comment by axyr** [comment]
I saw it, but is does not work.
A fresh install does publish the translations files, but uninstall and install gives this error : 

```
 file_put_contents(/Controllers/HomeController.php): failed to open stream: No such file or directory
```

**Comment by z-song** [comment]
run commands:
```
artisan admin:uninstall
artisan vendor:publish
artisan admin:install
```

**Comment by axyr** [comment]
Ah I did not know I needed to republish as well :) great work!

**Comment by z-song** [comment]
May be I can put the publish work in `admin:install ` command.
