### ISSUE TITLE
GRID FORM 使用文档

### ISSUE THREAD

**Issue by ltreer** [z-song/laravel-admin#40]
有没有 GRID FORM 的使用文档之类的！用着好吃力！
还有 默认 edit creat 方法 提交 是提交到哪里

**Comment by z-song** [comment]
参考 [ExampleController.stub](https://github.com/z-song/laravel-admin/blob/master/src/Commands/stubs/ExampleController.stub)

`grid`和`form`方法里面定义好了表格和表单的元素就好了，它会自动生成页面。

添加数据提交到当前`controller`的`store`方法，更新数据提交到当前`controller`的`update`方法，这些都不用关心，`laravel-admin`会自动处理好的。

**Comment by ltreer** [comment]
created_at updated_at 如何根据当前时间自动处理

**Comment by ltreer** [comment]
有点晕乎，form grid 如何 跟模型关联起来，数据如何取得，比如 排序，查找什么的

**Comment by z-song** [comment]
```php
protected function grid()
{
    return Admin::grid(User::class, function (Grid $grid) {

        $grid->id('ID')->sortable();

        $grid->created_at();
        $grid->updated_at();
    });
}
```
`User::class`就是你的数据模型，`Admin::grid()`方法根据传入的模型名称和闭包，自动读取模型里面的数据。
