### ISSUE TITLE
Action menu in grid. Not append new item

### ISSUE THREAD

**Issue by AnatolyAstapov** [z-song/laravel-admin#4000]
- Laravel Version: 5.8.30
- PHP Version: 7.3.3
- Laravel-admin: 1.7

### Description:
Can't add new item in dropdown row menu on action in grid list

```
  $this->actions(function (Grid\Displayers\Actions $actions) {
            $actions->disableDelete();
            $actions->append('<a href=""><i class="fa fa-paper-plane"></i>show item 1</a>');
            $actions->prepend('<a href=""><i class="fa fa-paper-plane"></i>show item 2</a>');
        });
```

"show item X" not showing in row menu.
but disabled working.

Please fix it. =)

**Comment by AnatolyAstapov** [comment]
sorry ...  this section in  documentation is wrong. ...

``
$this->actions(function (Grid\Displayers\DropdownActions $actions) {
            $actions->add(new CustomView())
        });
``
where CustomView extends RowAction ....

will work...

**Comment by vonsogt** [comment]
`$actions->add()` is working, but it will get error "intelephense(1013)"
