### ISSUE TITLE
上传文件的浏览按钮样式错位了

### ISSUE THREAD

**Issue by terranc** [z-song/laravel-admin#4005]
- Laravel-admin: 1.7.7

### Description:
上传文件的浏览按钮样式错位了

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/224353/66175555-d1bac900-e68c-11e9-9ad5-77c4729efb7a.png)

**Comment by 9776887181** [comment]
遇到同样问题

**Comment by terranc** [comment]
发现是edge的问题，chrome没问题，不过这里也确实用display:inline-block;更合理
