### ISSUE TITLE
添加不存在的数字字段如何在表格的底部显示统计?

### ISSUE THREAD

**Issue by keithshih** [z-song/laravel-admin#4006]
添加不存在的字段后(值为数字)，display()要如何像totalRow()一样在表格的底部 显示统计?

```
// 添加不存在的字段
$grid->column('奖金')->display(function () {
    $commission = Users::where('id',$this->user_id)->value('commission');
    $commission_amount = $this->column('total_amount') * ($commission/100); 
    return $commission_amount;
});
```
请问如何在表格的底部显示统计? 因为在display()之后加上 ->totalRow()是错误的

**Comment by z-song** [comment]
实现不了

**Comment by PaulCnth** [comment]
> 添加不存在的字段后(值为数字)，display()要如何像totalRow()一样在表格的底部 显示统计?
> 
> ```
> // 添加不存在的字段
> $grid->column('奖金')->display(function () {
>     $commission = Users::where('id',$this->user_id)->value('commission');
>     $commission_amount = $this->column('total_amount') * ($commission/100); 
>     return $commission_amount;
> });
> ```
> 
> 请问如何在表格的底部显示统计? 因为在display()之后加上 ->totalRow()是错误的

指出一处用法上的问题。
display() 回调里调用 User model 进行查询，
**手册里明确强调，这样写效率很低，要使用 关联模型。**
有多少条数据，SQL 就要查询多少次！
模型关联，ORM 组装出来的就一句：
`SELECT * FROM User where ID IN (1,2,2324....)`
哪个效率高不言而喻。

很多同学会这样随手一写，其实有危害。

---

对于当前页的数据统计，
是基于当前页model过滤后生成的集合进行的，
所以你需要手动获取这个集合，
然后计算，然后将计算结果$result 写入 ->totalRow($result);

_tips: 实现之后再来补充_

**Comment by wploey** [comment]
>[LaravelORM 中的 withSum ， withAvg, withMax,withMin 的实现](https://learnku.com/laravel/t/7085/the-implementation-of-withsum-withavg-withmax-withmin-in-laravelorm)
* 看看可否这样统计
```
// 统计每个用户的所有充值
protected function grid()
{
    $grid = new Grid(new User());
    $grid->model()->withCount(
            [
                'orders as orders_sum' => fn($q) => $q->select(\DB::raw("sum(total_amount) as orders_sum")),
            ]);
    $grid->column('总捐款')->display($grid->column('总捐款')->display(fn() => $this->orders_sum));
}
```
