### ISSUE TITLE
Action中form方法中 select 选项框的options和groups无效

### ISSUE THREAD

**Issue by dptms** [z-song/laravel-admin#4013]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.7.6

### Description:
通过`php artisan admin:action Post\\ImportPost --name="导入数据"`生成的Action类，为了添加一个普通操作，目的是通过Excel导入数据，但是在 form 方法中，使用如下代码
```
$this->select('groups', '省份(年份)')
->groups($groups)
->load('type_id', '/admin/score-types/province-year-to-types')
->required();
$this->select('type_id', '高考分类')->required();
```

groups 方法不生效，没有选项，但是我打印 $groups 确实是处理好的，按照

```
* eg: $group = [
     *        [
     *        'label' => 'xxxx',
     *        'options' => [
     *            1 => 'foo',
     *            2 => 'bar',
     *            ...
     *        ],
     *        ...
     *     ]
     *
```

结构来的数据，后来我把 groups 替换成了 options 方法，有数据，但是无法在 select 中搜索，选中选项之后，loads 又没有生效，不能联动第二个选项框，求大家帮忙，谢谢大家帮我答疑解惑

**Comment by nkjackzhang** [comment]
![图片](https://user-images.githubusercontent.com/2102078/66693581-01954c80-ecdd-11e9-89c0-cec5f816d70d.png)
我的1.5.x版本的是好用的，你可以删除多余的代码，只用最简单的select的形式试试看，然后再把其他的配置一个个加回去。

**Comment by dptms** [comment]
你这个是基本表单里面的吧？我说的是php artisan admin:action Post\\ImportPost --name="导入数据"生成的Action类中的 form 方法的表单

**Comment by youruan** [comment]
遇到相同的问题了 请问解决了吗?
