### ISSUE TITLE
laravel-admin downloadable() 上传中文名称的文件 不显示名称

### ISSUE THREAD

**Issue by shunhua** [z-song/laravel-admin#4017]
- Laravel Version:5.8
- PHP Version:7.1.3
- Laravel-admin: 1.7.7

### Description:

本地 windows上正常的 线上就不行了 版本问题？

**Comment by nkjackzhang** [comment]
会不会是路径编码问题？

**Comment by shunhua** [comment]
> 会不会是路径编码问题？

英文是可以的  中文不显示
