### ISSUE TITLE
filter 中如何使用datetime 筛选数据库中的时间戳字段(int类型)

### ISSUE THREAD

**Issue by keller31** [z-song/laravel-admin#4019]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.7

filter 中如何使用datetime 筛选数据库中的时间戳字段(int类型)

**Comment by komahui** [comment]
![QQ截图20191011084921](https://user-images.githubusercontent.com/29142910/66616592-09cd8900-ec04-11e9-9d2a-9d6f667be172.png)
继承原先的between，重写condition方法，在这里面把时间转换成int类型

**Comment by keller31** [comment]
谢谢 已解决！
