### ISSUE TITLE
能否实现form表单ajax/js动态验证

### ISSUE THREAD

**Issue by hulkwan** [z-song/laravel-admin#402]
能否实现form表单ajax/js动态验证
例如：用户名的input右侧或者下方可以显示onblur或者ajax返回的错误信息

**Comment by z-song** [comment]
已经有了验证显示，不过不是ajax实现的
```php
$form->text('title')->rules('required');
```

**Comment by z-song** [comment]
`Admin::script('xxx'); `   用这个自己写js来实现吧

**Comment by lvye** [comment]
@z-song OK, thx.
