### ISSUE TITLE
V1.7.7使用\Encore\Admin\Widgets\Form()创建表单时调用table方法报错

### ISSUE THREAD

**Issue by Jetcoder926** [z-song/laravel-admin#4025]
- Laravel Version:5.8.13
- PHP Version:7.2
- Laravel-admin: 1.7.7

### Description:
使用\Encore\Admin\Widgets\Form()创建表单时调用table方法报错.

### Steps To Reproduce:
我的代码:
![微信图片_20191012101851](https://user-images.githubusercontent.com/47552738/66693259-a57cf900-ecd9-11e9-8100-17a521f394af.png)
报错的代码:
![微信图片_20191012095117](https://user-images.githubusercontent.com/47552738/66693064-4cac6100-ecd7-11e9-8c4f-106bb22ab96e.png)

**Comment by Jetcoder926** [comment]
@z-song  作者大神麻烦您有空看看吧

**Comment by Jetcoder926** [comment]
我似乎找到这个报错的解决方案了. 但是还有一个问题就是,在使用上required()方法时。添加了一行数据然后点击移除后.按提交会出现js报错
我的代码:
![微信图片_20191012105641](https://user-images.githubusercontent.com/47552738/66693751-1ecb1a80-ecdf-11e9-8d19-81adb631a316.png)

console.log报错:
![微信图片_20191012105625](https://user-images.githubusercontent.com/47552738/66693754-28548280-ecdf-11e9-91c2-50b91a9503a6.png)

**Comment by nkjackzhang** [comment]
前面php的错误估计是foreach循环的那行代码不是数组无法循环，你可以在那里打个断点，看看那一行的$this->value到底是怎么值，js错误搜了下，就是说你的必填项是隐藏的，有可能提交表单的时候都是隐藏的，chrome没有办法定位，你试着把这些required的字段显示出来，或者就只能去掉required了

**Comment by crusj** [comment]
@Jetcoder926 我也遇到了怎么解决的啊
