### ISSUE TITLE
数据表单中，多图上传图片无法删除

### ISSUE THREAD

**Issue by zhw569700663** [z-song/laravel-admin#4039]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.7.7

### Description:
数据表单中，多图上传图片无法删除
![图片](https://user-images.githubusercontent.com/22650230/66802903-9d7abe80-ef50-11e9-84fa-e4b94ac2e2a9.png)

**Comment by liuyi61123** [comment]
我也遇到同样的问题，一直解决不了
