### ISSUE TITLE
模型表单回调会返回当前模型的ID值吗

### ISSUE THREAD

**Issue by fsf11080612** [z-song/laravel-admin#404]
![image](https://cloud.githubusercontent.com/assets/12817128/22878996/e2623b34-f216-11e6-96f0-53ac4a6e761e.png)
模型表单回调会返回当前模型的ID值吗

**Comment by z-song** [comment]
不会返回

**Comment by fsf11080612** [comment]
还有什么方法可以获取当前模型的ID值吗

**Comment by z-song** [comment]
贴一下你的需求，可能可以通过其它的方式解决

**Comment by fsf11080612** [comment]
![image](https://cloud.githubusercontent.com/assets/12817128/22880637/e3810e58-f21d-11e6-9788-d699d6d8c4ad.png)
例如，我想获取form保存后的id值

**Comment by fsf11080612** [comment]
我知道怎么获取了，可以根据$form->model()->id获取到id值
