### ISSUE TITLE
看图！急急急！在grid（）能不能把外面的变量传入display（）里面啊怎么做？

### ISSUE THREAD

**Issue by guohanlin1** [z-song/laravel-admin#4044]
- Laravel Version: 5.5
- PHP Version:7.1.9
- Laravel-admin: 1.6

### Description:
![image](https://user-images.githubusercontent.com/55566773/66820061-8fd63080-ef72-11e9-93b6-076aa2e1e2d6.png)

**Comment by z-song** [comment]
```php
display(function () use ($v) {
    $v...
});
```
