### ISSUE TITLE
Rename an uploaded image with a column value

### ISSUE THREAD

**Issue by herol-gl** [z-song/laravel-admin#4045]
How to rename an uploaded image with a value from a column?

```
$form->text('book_name', 'Book name');    //From database record, editable 
$form->image('img_name', 'Upload your book image')->name(function($file) {
	return ????.'.jpg';
});

```

**Comment by z-song** [comment]
You can get column data from the model bound by the form:

```php
$form->image('img_name', 'Upload your book image')->name(function($file) {
    dd($this->form->model()->book_name);
});
```

**Comment by herol-gl** [comment]
@z-song Thanks for the help. When I use `->name(function($file))`, how can I save the form without uploading any image? When $file is null, it throws below error.

`Argument 1 passed to Encore\Admin\Form\Field\File::getStoreName() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given,`
