### ISSUE TITLE
模型表单自定义头部信息

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#4048]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
用了很久了，之前一直都是修改模板添加头部提示信息，最近想版本grid已经可以自定义 header 和 footer，方便了很多，能基本满足需求，希望扩展一下模型表单的自定义提示信息（一般在头部），这个需求非常普遍，很多表单操作和编辑操作都需要在顶部醒目的显示一些重要提示。

**Comment by nkjackzhang** [comment]
你是说form里的提示？头部的话你自己用$form->html()写html代码，每个字段可以用$form->text()->help('xxxx')，里面写要提示的话。

**Comment by z-song** [comment]
参考下面
```php
    public function create(Content $content)
    {
        return $content
            ->title('Title')
            ->description('Description')
            ->row('你的提示。。。');
            ->row($this->form());
    }
```
