### ISSUE TITLE
如何调用查询过滤中输入的值，想在模型表格的腳部做查询后的统计

### ISSUE THREAD

**Issue by keithshih** [z-song/laravel-admin#4049]
- Laravel Version: 5.7
- PHP Version: 7.1
- Laravel-admin: 1.7.2

### Description:
请问要如何调用查询过滤的值，想在模型表格的腳部做查询后的一些统计?

**Comment by z-song** [comment]
直接从request对象值获取  `request('column_name')`;

**Comment by keithshih** [comment]
> 直接从request对象值获取 `request('column_name')`;

可以获取到订单编号, 但广告商如何获取?


`$grid->filter(function($filter){
// 去掉默认的id过滤器
$filter->disableIdFilter();
$filter->equal('no', '订单编号');

$filter->where(function ($query) {
    $query->whereHas('aduser', function ($query) {
        $query->where('name', 'like', "%{$this->input}%");
    });
}, '广告商');  
});`

**Comment by Paik-yoonsuk** [comment]
you can set column name by third parameter.

$grid->filter(function($filter){
// 去掉默认的id过滤器
$filter->disableIdFilter();
$filter->equal('no', '订单编号');

$filter->where(function ($query) {
    $query->whereHas('aduser', function ($query) {
        $query->where('name', 'like', "%{$this->input}%");
    });
}, '广告商', **_'set_column_name_what_you_want_in_here'_**);  
});

**Comment by Paik-yoonsuk** [comment]
@keithshih 
you can set column name by third parameter.

$grid->filter(function($filter){
// 去掉默认的id过滤器
$filter->disableIdFilter();
$filter->equal('no', '订单编号');

$filter->where(function ($query) {
    $query->whereHas('aduser', function ($query) {
        $query->where('name', 'like', "%{$this->input}%");
    });
}, '广告商', **_'set_column_name_what_you_want_in_here'_**);  
});
