### ISSUE TITLE
[HELP] api referencing

### ISSUE THREAD

**Issue by mp43819** [z-song/laravel-admin#406]
Hi, 

you are always referencing to API inside code, e.g. https://github.com/mp43819/laravel-admin/blob/master/docs/en/model-form.md for "select" field function. 

Do you expose this api with custom methods or just json response? Could you be so kind and elaborate?

**Comment by z-song** [comment]
These are just simple apis with json response.

You can find example here http://120.26.143.106/admin/demo/posts/40/edit

and code in this page http://120.26.143.106/admin/demo/posts under `Code` tab.

**Comment by mp43819** [comment]
ok. thank you!. Could you also put demo inside git? I think that it will reduce lot of questions...
