### ISSUE TITLE
form:图片存储为base64,无法正常显示问题 && grid:列表弹出表单的方法

### ISSUE THREAD

**Issue by UnaHe** [z-song/laravel-admin#4067]
- Laravel Version: 6.3.0
- PHP Version: 7.3.8
- Laravel-admin: 1.7.7

### 图片存储为base64,无法正常显示问题:
1. 表单上传图片之后我在 saving 函数中调用 [Intervention\Image](http://image.intervention.io) 将图片转为base64(data-url) 存入数据库
2. 表单显示时 调用 $form->image 显示图片默认在之前拼接了disks中设置的upload了路径(https://{host}/upload/data:image/jpeg;base64,/9j/4AA...)导致无法正常显示
请问是否有办法解决~(翻了源码没找到在哪改qaq)

### 列表弹出表单的方法:
1. 
```php
$grid->column($name, $label)->display(function ($name, Grid\Column $column) {
    return「要显示在行内的内容」;
})->modal($title, function ($model) {
    return 「点击后弹出的HTML」;
});
```
2. 至于css,js什么的预定义函数Admin::style,Admin::script就好啦
3. 最终结果:(demo)
![截屏2019-10-2018 13 06](https://user-images.githubusercontent.com/30680842/67158673-639d2400-f365-11e9-9ac8-1ab7bc8958e0.png)

**Comment by z-song** [comment]
第一个问题，你可以写一个类继承`Encore\Admin\Form\Field\Image`作为form扩展， 然后重写`preview`方法输出base64的字符串即可

**Comment by UnaHe** [comment]
@z-song 
我尝试了你的方法url已经正确,依旧不显示,我找到了原因:
「Encore\Admin\Form\Field > initialPreviewConfig」方法中返回的js配置「$config['type'] = 'other'」

重写此方法为
```php
protected function initialPreviewConfig()
{
    $config = ['caption' => basename($this->value), 'key' => 0];
    $config = array_merge($config, $this->guessPreviewType($this->value));
    if ($config['type'] === 'other' && strpos($this->value, 'data:image') !== false) {
            $config['type'] = 'image';
    }
    return [$config];
}
```
问题解决,谢谢!!!

**Comment by haihai456** [comment]
请问一下Laravel-admin中图片怎么存储为base64的
