### ISSUE TITLE
 $form->table里面上传图片bug

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#4068]
- Laravel Version: 5.6.x
- PHP Version:
- Laravel-admin:1.7.2

### Description:
            $form->table('extra','图片和描述', function ($table) {
                $table->image('img','图片')->uniqueName()->removable();
                $table->text('desc','描述');
            })->disableDelete();

### Steps To Reproduce:
使用image上传图片，第一次上传成功，没有问题，再次编辑时候，未改变image,修改其他字段，再次进来，发现图片字段为空，图片丢失

**Comment by YangZhengHuan** [comment]
原因上传过程，存入表数据中，extra字段值包含img值，编辑过程就未存在img值：

array:1 [
  0 => array:2 [
    "img" => "images/7639f19dedc90b23de090de897385a63.jpg"
    "desc" => "asdsadsadasd sa11"
  ]
]

array:1 [
  0 => array:2 [
    "desc" => "asdsadsadasd sa11"
  ]
]

**Comment by YangZhengHuan** [comment]
@z-song 麻烦给予帮助

**Comment by CherishNA** [comment]
我也是一个情况 请给予帮助@z-song

**Comment by JoviLau** [comment]
@YangZhengHuan 我也是这个问题，是怎么解决的

**Comment by newbietao** [comment]
我也是遇到上面的问题

**Comment by lwt33713803** [comment]
我也是上面问题

**Comment by ilonaliao** [comment]
same issue with me
