### ISSUE TITLE
gird表格能否实现本页数据统计

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#4070]
-Laravel Version: 5.6.x
-PHP Version:
-Laravel-admin:1.7.2

Description:
现在gird底部有一个求和统计->totalRow();，不知道是否可以实现本页数据统计，类似于加一个方法->totalPageRow()

Steps To Reproduce:

**Comment by YangZhengHuan** [comment]
@z-song 麻烦看见基于帮助一下，谢谢

**Comment by jsonlove-cc** [comment]
$grid->column('amount', '金额')->totalRow(function ($amount) {

    return "<span class='text-danger text-bold'><i class='fa fa-yen'></i> {$amount} 元</span>"

});你是说这个嘛

**Comment by YangZhengHuan** [comment]
@jsonlove-cc 这个是所有页的求和吧，我说的是分页求和

**Comment by Xuan-Goldenf** [comment]
说的是这个功能吗？
![image](https://user-images.githubusercontent.com/40749214/118633418-0d73b980-b804-11eb-8726-895a15763d01.png)
