### ISSUE TITLE
自定义行&批量操作  form表单与$grid->filter 同字段form类型不一致样式错乱问题

### ISSUE THREAD

**Issue by gai871013** [z-song/laravel-admin#4071]
- Laravel Version: 6.3
- PHP Version:7.3
- Laravel-admin: 1.7.7

### Description:
控制器查询过滤form字段类型与actions form字段类型不一致会导致，操作弹框界面显示异常
![image](https://user-images.githubusercontent.com/3212029/67181788-35285300-f410-11e9-873b-2d07ef285331.png)
![image](https://user-images.githubusercontent.com/3212029/67181888-715bb380-f410-11e9-912f-e984c5e68dcb.png)

### Steps To Reproduce:

App\Admin\Actions\Models\Action.php
```php
...
public function form(Model $model){
    $this->radio('pay_status',  '状态')->options(Record::PAY_STATUS)->default($model->status);
    $this->radio('status',  '状态')->options(Record::STATUS)->default($model->status);
}
...
```

App\Admin\Controllers\xxxController.php

```php
...
protected function grid()
    {
        ......
            $filter->equal('pay_status', '付款状态：')->select(Record::PAY_STATUS)->default(0);
            $filter->equal('status', '发货状态：')->select(Record::STATUS)->default(0);
        ......
        ......
    }
...
```

**Comment by z-song** [comment]
建议form换一个字段名，比如统一加个前缀
