### ISSUE TITLE
自定义导入功能 form使用 select联动 无效

### ISSUE THREAD

**Issue by UnaHe** [z-song/laravel-admin#4072]
- Laravel Version: 6.3.0
- PHP Version: 7.3.8
- Laravel-admin: 1.7.7

### Description:
```php
use Encore\Admin\Actions\Action;
// 第126行
var target = $(this).closest('.fields-group').find(".$class");
```
这个查找方式在form组件中并没有问题,但是在自定义方法中,弹出的form并没有包含在类 「.fields-group」中,使得联动失效

### Steps To Reproduce:
自定义按钮时使用
```php
$this->select('name', '所属公司label')->options($options)->load(
    'sub', admin_url('sub')
)->rules('required');
```

**Comment by UnaHe** [comment]
#### 临时解决办法
1. 方法中调用「Admin::script」给模态框「body」增加类「fields-group」:
```php
Admin::script("$('.modal-body').addClass('fields-group')");
```
2. 修改load方法源代码(不推荐)

**Comment by momosc** [comment]
it's ok
