### ISSUE TITLE
select2 allowClear option false is not working

### ISSUE THREAD

**Issue by hanachan1026** [z-song/laravel-admin#4074]
- Laravel Version: 5.8.11
- PHP Version: 7.3.*
- Laravel-admin: 1.7.7

### Description:
Thanks to Pull Request #3517 allowClear option is added to select()->load() function.
I tried to set it to false(I needed to) but I got javascript error, and select2 not working.

```
Uncaught SyntaxError: Unexpected token ','
```
### Steps To Reproduce:

select('parent')
->load('child', '/api/test, 'id', 'text', false)

**Comment by z-song** [comment]
Fixed in #4075
