### ISSUE TITLE
action 操作样式能否自定义？

### ISSUE THREAD

**Issue by nosun** [z-song/laravel-admin#4077]
- Laravel Version: 5.8
- PHP Version: 7.1
- Laravel-admin: 1.7

### Description: 
laravel admin 后台默认的 grid 列表中 action 操作现在都缩在一个图标下面，我想把它修改为平铺的，该如何操作才能做到？谢谢。

**Comment by nosun** [comment]
主要是删除按钮，好像是需要添加一个自动生成的类才能执行删除

**Comment by z-song** [comment]
看文档  https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E5%88%87%E6%8D%A2%E6%93%8D%E4%BD%9C%E5%88%97%E7%9A%84%E5%BD%A2%E5%BC%8F

**Comment by nosun** [comment]
多谢大神，🙏

**Comment by maojindao55** [comment]
平铺 就不能用新特性了吧（比如：$actions->add(new Replicate);），必须用旧版本方式preappend()？
