### ISSUE TITLE
左侧菜单栏能否当前页的时候高亮显示

### ISSUE THREAD

**Issue by hulkwan** [z-song/laravel-admin#408]
左侧菜单栏能否当前页的时候高亮显示，目前只有一级菜单展开的时候会高亮显示

**Comment by skys215** [comment]
可以自己开发好了然后提PR。实现起来不是很难。

**Comment by yang5664** [comment]
參考 https://github.com/z-song/laravel-admin/issues/199

**Comment by z-song** [comment]
@yang5664 谢谢，已经加入了你的代码
