### ISSUE TITLE
关于操作类的权限问题

### ISSUE THREAD

**Issue by komahui** [z-song/laravel-admin#4085]
![QQ截图20191024165202](https://user-images.githubusercontent.com/29142910/67469690-22678580-f67f-11e9-99d1-faffa1938225.png)
![QQ截图20191024165211](https://user-images.githubusercontent.com/29142910/67469693-23001c00-f67f-11e9-9428-b30cf41f158c.png)
为什么没有访问权限，不是在这里定义的吗？版本是1.7.6

**Comment by lr874355227** [comment]
看源码是没到这步，权限的中间件验证没通过,这个设置不起作用
