### ISSUE TITLE
多图上传 rules('required') 字段名后没有自动添加星号

### ISSUE THREAD

**Issue by keithshih** [z-song/laravel-admin#4091]
- Laravel Version: 5.7
- PHP Version: 7.1
- Laravel-admin: 1.7.3

### Description:
多图上传这表单组件的字段名添加->rules('required') 后不会出现星号

### Steps To Reproduce:
```
$form->mulitiImages('image', '产品图')->rules('required')->removable();
```

**Comment by yinchuanjiang** [comment]
$form->mulitiImages('image', '产品图')->required()->removable();
