### ISSUE TITLE
How to add an external javascript file in Laravel-Admin

### ISSUE THREAD

**Issue by djoyromeo-git** [z-song/laravel-admin#4094]
- Laravel Version: 5.8
- PHP Version: 7.2.19
- Laravel-admin: 1.7

### Description:
How to add an external javascript file in Laravel-Admin

I am stuck with a problem since yesterday with the use of Laravel Admin (https://laravel-admin.org/)

I would like to add a javascript script to be able to select all the elements of a multiSelect field.

1. I can not import the javascript file
2. how can I proceed (by javascript code) to select all the options of a field multiSelect

**Comment by z-song** [comment]
In  app/Admin/boostrap.php:

```php
Admin::js('path/to/your/javascript/file');
```
