### ISSUE TITLE
星标 列操作

### ISSUE THREAD

**Issue by maojindao55** [z-song/laravel-admin#4096]
- Laravel Version: 5.8
- PHP Version:
- Laravel-admin: 1.7.6

### Description:
看文档有个星标操作的例子
![image](https://user-images.githubusercontent.com/6436125/67612488-961ba680-f7d5-11e9-9e3f-3bd9c5001da2.png)

https://laravel-admin.org/docs/zh/model-grid-column-display#%E5%88%97%E6%93%8D%E4%BD%9C

有完整的demo吗，按照文档未实现。

**Comment by z-song** [comment]
将`列操作`应用到某一列

```php
use App\Admin\Actions\Document\StarDocument;

$grid->column('star')->action(StarDocument::class);
```
