### ISSUE TITLE
laravel5.5 + jenssegers/mongodb 3.3.*  执行   php artisan admin:install  报错！！

### ISSUE THREAD

**Issue by PerfectWorld233** [z-song/laravel-admin#4098]
- Laravel Version: #.#.#    laravel 5.5
- PHP Version:     php7.2.1
- Laravel-admin: #.#.#   laravel-admin  1.7  

### Description:
我是用 mongodb 数据库 在安装  laravel-admin  时， 执行    php artisan admin:install   命令时报错：
    In Connection.php line 326:

  Call to a member function prepare() on null

mongodb  中会生成 集合， 但是集合中没有数据

**Comment by z-song** [comment]
不支持mongodb
