### ISSUE TITLE
avator update error 

### ISSUE THREAD

**Issue by korodo** [z-song/laravel-admin#410]
![default](https://cloud.githubusercontent.com/assets/25667826/22961415/16834d7c-f389-11e6-92fd-4c1a8374e563.png)

Hello, z-song.

Thank you for your awesome packages. It's so helpful to me.
That screen shot is shown when I try edit avator image.
Could you let me know why? and how can I slove it?

**Comment by z-song** [comment]
I did not reproduce the problem, this work fine for me.

**Comment by yang5664** [comment]
這個錯誤發生在同一個form裡有multiselect
![screen shot 2017-02-16 at 11 05 25 am](https://cloud.githubusercontent.com/assets/5953010/23005629/30811100-f438-11e6-9846-4aed32cd6d29.png)

**Comment by z-song** [comment]
Fixed in version 1.3.x-dev

**Comment by korodo** [comment]
@z-song Thank you your answer. 
Don't you guess why? 
Sorry for bothering you.
