### ISSUE TITLE
multipleImage 新增图片的时候能对图片删除和排序操作吗 每次都要去编辑操作一次

### ISSUE THREAD

**Issue by yinchuanjiang** [z-song/laravel-admin#4101]
- Laravel Version: 6.0
- PHP Version:7.2
- Laravel-admin: 1.7

### Description:

多图上传新增的时候不能对图片进行排序和单个图片删除

**Comment by liangshuocj** [comment]
问题解决了吗？我这边也是这个问题：
Laravel Version: 5.8
PHP Version:7.3.8
Laravel-admin: 1.7.7
$form->multipleImage('images', __('图片'))->sortable()->removable();
![image](https://user-images.githubusercontent.com/39985607/68017845-a39fc780-fcd2-11e9-85cd-e8e2a9b4908d.png)

**Comment by yinchuanjiang** [comment]
没有

**Comment by zenghuang19** [comment]
沉了，没人管了吗？
