### ISSUE TITLE
can i add id for elemnt in form 

### ISSUE THREAD

**Issue by mRamadan0101** [z-song/laravel-admin#4104]
- Laravel Version: 5.5
- PHP Version: 7.2
- Laravel-admin: 1.6.15

### Description:
i want to show and hide selected field when i select from drop down 
ex.
i have form with select  drop down and 4 text
when i select option 1 text1 and text 2 display and text3 and text 4 hidden 
i want do this using javascript 
my Q. can i add id for this select drop down or any field in form ? 

### Steps To Reproduce:
`$form->select('discount_type')->options([1 => 'Amount', 2 => 'Percentage'])->rules('required_if:type,1')->config('id','discount_amount)';`
and this didnt work

**Comment by mRamadan0101** [comment]
edit src/select.blade.php or any input type u want to show and hide it 
add 
` id="{{$name}}"` in Main **div** 
then create new js file and add it in 
admin/bootstrap.php
Admin::js(asset('js/show_hide.js'));
this my show_hide.js file 
```
`$('.type').attr('id','type_id');`
`$(document).on('change', '.type', function(){`
` $type_id_val = $('#type_id').val();`
	 if ($type_id_val == 1) {
	 	document.getElementById('discount').style.display = 'block';
	 	document.getElementById('amount').style.display = 'none';
```
	 }else if ($type_id_val == 2) {
	 	document.getElementById('discount').style.display = 'none';
	 	document.getElementById('amount').style.display = 'block';

	 }
});
```

**Comment by mRamadan0101** [comment]
this work with me thanks for all

**Comment by Dennies-Chang** [comment]
I found another way for all "Widget" of caravel-admin, we can assign the 'id' with the method "offsetSet".
For example, I wish to assign "selectedDeviceContainer" as the id of Box, I can do with the following codes:

$box = new Box('myBoxTitle', 'BoxContent');
$box->offsetSet('id', 'selectedDeviceContainer');

And when the box is rendered, id was assigned. it's convenient.
