### ISSUE TITLE
Can´t close the second modal when deleting something for the grid.

### ISSUE THREAD

**Issue by maxichiale** [z-song/laravel-admin#4107]
- Laravel Version:  5.8.35
- PHP Version: 7.3.9 
- Laravel-admin: 1.7.7

### Description:
When deleting something listed on the grid with the delete button, you get a modal with a confirmation, if you delete success you get a second modal that you can´t close.

### Steps To Reproduce:
Go to a grid.
Click the delete button (trash icon)
Confirm the delete in the first modal.
See the second modal (can´t close)

**Comment by adaoss** [comment]
Hello. 
I had same issue while i havent removed deny middleware from config/admin.php
'middleware'    => ['web', 'admin', 'deny'],
change to 
'middleware'    => ['web', 'admin'],

hope this helps.

**Comment by maxichiale** [comment]
I had already 'middleware' => ['web', 'admin'] .

**Comment by adaoss** [comment]
Try to use web developer tools to analyse console messages or errors. 

Have you already seen ajax response from delete call to server?
