### ISSUE TITLE
 Call to a member function roles() on null

### ISSUE THREAD

**Issue by cnitker** [z-song/laravel-admin#4113]
- Laravel Version: 5.8.35
- PHP Version: 7.1.16 
- Laravel-admin: 1.7.7

### Description:
  Symfony\Component\Debug\Exception\FatalThrowableError  : Call to a member function roles() on null

  at /Users/DUDU/Documents/wwwroot/xxx/vendor/encore/laravel-admin/src/Auth/Database/AdminTablesSeeder.php:126
    122|             ],
    123|         ]);
    124| 
    125|         // add role to menu.
  > 126|         Menu::find(2)->roles()->save(Role::first());
    127|     }
    128| }
    129| 

  Exception trace:

  1   Encore\Admin\Auth\Database\AdminTablesSeeder::run()
      /Users/DUDU/Documents/wwwroot/xxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  2   call_user_func_array([])
      /Users/DUDU/Documents/wwwroot/xxxx/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php:32

  Please use the argument -v to see more details.

**Comment by varshneygaurav** [comment]
@cnitker How you solve that.
