### ISSUE TITLE
form text 如何自定义显示？

### ISSUE THREAD

**Issue by rust17** [z-song/laravel-admin#4114]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.7.2

### Description:
比如：某个字段以加密的形式存储，我想解密显示该字段的值，应该怎样做呢？
```php
$form->text('secret', '密码');
```

**Comment by jsonlove-cc** [comment]
获取到加密的字符串
$str = '你的解码逻辑解出来的字符串'
$form->text('a','密码')->value($str);

**Comment by rust17** [comment]
@jsonlove-cc 根据你的建议，我试了一下，并没有显示 `$str` 的值，还是显示字段原来的值

**Comment by jsonlove-cc** [comment]
$form->display('password', trans('admin.password'))->with(function ($value) {
            //解码逻辑
            return "明文密码";
        });
这样可以显示你的密码但是这个不能编辑你让他编辑只能在来一个password让他编辑
$form->password('password', '密码');
上面显示明文密码下面编辑密码

**Comment by rust17** [comment]
@jsonlove-cc  嗯嗯，是的，我希望在一个框里既能显示明文又可以编辑，自定义表单的话那整个表单都得重新写了，我想问下有没有针对单个字段的自定义表单呢？

**Comment by z-song** [comment]
可以通过设置这个字段的访问器和修改器来实现吧

**Comment by rust17** [comment]
@z-song thanks
