### ISSUE TITLE
看图->！！！！！！！！！！！

### ISSUE THREAD

**Issue by jsonlove-cc** [z-song/laravel-admin#4116]
- Laravel Version: 5.5
- PHP Version:7.1.9
- Laravel-admin: 1..6.1

### Description:
select可以弄成这样吗
![QQ图片20191101153943](https://user-images.githubusercontent.com/55566773/68009947-33874680-fcbe-11e9-92df-aa5cba2a9257.png)

**Comment by dcsite** [comment]
可以
