### ISSUE TITLE
上传图片右侧上传按钮样式不对

### ISSUE THREAD

**Issue by CrazyCodes** [z-song/laravel-admin#4118]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: ^1.7

### Description:

![image](https://user-images.githubusercontent.com/9151227/68066409-6b4fc600-fd72-11e9-892e-98c3eb9a1e94.png)
你好，大佬，我更新到最新版本后，发现上传样式有些问题，具体你看下图

**Comment by yinchuanjiang** [comment]
你是啥浏览器啊

**Comment by 9776887181** [comment]
chrome  出现同样的问题
