### ISSUE TITLE
Language pack problem with Select2 | Select2语言包问题

### ISSUE THREAD

**Issue by UnaHe** [z-song/laravel-admin#4119]
- Laravel Version: 6.4.1
- PHP Version: 7.3.8
- Laravel-admin: 1.7.7

### Description:
下拉框默认提示 ‘No results found’, 原因没有引入语言包选择

### Steps To Reproduce:
没有option的select

解决办法
vendor/encore/laravel-admin/src/Form/Field/Select.php 文件
第26行加入:'/vendor/laravel-admin/AdminLTE/plugins/select2/i18n/zh-CN.js',
406行加入:'language'    => 'zh-CN',

**Comment by gomes2191** [comment]
I added it here, but I didn't allow the issue.
![image](https://user-images.githubusercontent.com/4576117/231857374-1cc6347f-d0e1-4d9b-8763-eb85c3ea759e.png)
