### ISSUE TITLE
Permission denied for customized User DB table and Model/Controller

### ISSUE THREAD

**Issue by yatong2008** [z-song/laravel-admin#412]
I added my own user DB Table and set it from the admin.php('users_table', 'users_model' both point to my own classes), but the role and permission are the original ones, I added a few roles and permissions, they are fine, however, when I tried something just now, the page seems pop-up "Oops! Something went wrong. Permission denied!", It happens for /auth/menu, /auth/roles, /auth/permission and /auth/logs, my own user url is ok. Any hints what's going wrong?

**Comment by yatong2008** [comment]
It seems all of the url has an auth to /permission, but I did not change anything in the table actually, I am a new learner and no idea which this url routes are set in this project.

**Comment by z-song** [comment]
The message `"Oops! Something went wrong. Permission denied!"` may appears in an earlier version,I suggest you update to the latest version
