### ISSUE TITLE
Question: how to get the multiple file/image component to work with preview/rearrange/delete options

### ISSUE THREAD

**Issue by langeuh** [z-song/laravel-admin#413]
In the example of bootstrap-fileinput (http://plugins.krajee.com/file-advanced-usage-demo) 
there are rearrange/delete/zoom buttons which make it really handy to manage uploaded image/files

Currently if you have multiple files/images uploaded, and you want to delete 1, there is no way. You can only delete all the files and upload them again.

I've tried a lot of stuff, but I can't get it to work
any ideas?

**Comment by z-song** [comment]
This pr #411 is works for your idea, but it has some unresolved conflicts.

I'll implements this when i get some free time.

**Comment by z-song** [comment]
Implemented in branch 1.3.x-dev, see demo http://120.26.143.106/admin/demo/multiple-images

**Comment by smuzammilali** [comment]
Is this available in 1.4.1 ?

**Comment by z-song** [comment]
@smuzammilali available in 1.4.x-dev now，after composer update you need to update bootstrap-fileinput also.
