### ISSUE TITLE
v1.7.7$form->isUpdating();方法不存在

### ISSUE THREAD

**Issue by becage** [z-song/laravel-admin#4130]
Laravel Version: 6.4.1
PHP Version:7.2
Laravel-admin: 1.7.7

### Description:
![image](https://user-images.githubusercontent.com/41765271/68279653-d836c900-00ae-11ea-8c30-4e5eb72d511c.png)
```$form->isUpdating();```方法不存在
![image](https://user-images.githubusercontent.com/41765271/68279996-98bcac80-00af-11ea-95b6-b121f44f83f2.png)

### Steps To Reproduce:
```
    protected function form()
    {
        var_dump($form->isCreating());
        var_dump($form->isUpdating());
    }
```
```bool(true) ```
```Field type [isUpdating] does not exist.```

**Comment by z-song** [comment]
完整代码看一下

**Comment by muhlisabdi** [comment]
the correct way is using $form->isEditing.  There is a little mistake in documentation

**Comment by faydanube** [comment]
@z-song the correct way is using $form->isEditing. There is a little mistake in documentation
