### ISSUE TITLE
升级到新的版本 自定义行&批量操作 很方便  form提交按钮加个防止重复提交就更好了

### ISSUE THREAD

**Issue by ajiader** [z-song/laravel-admin#4137]
- Laravel Version: 5.7.X
- PHP Version:7.2
- Laravel-admin: 1.7.6

### Description:
首先感谢大佬升级到新的版本 自定义行&批量操作很方便，但是form生成的提交按钮，怎么在提交按钮加防止重复提交效果，和之前提交页面一样点击按钮的时候 按钮先loading...

**Comment by woodzeng** [comment]
这个怎么解决呢？
