### ISSUE TITLE
建议附上版本更新记录说明

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#414]
感谢开源了这么好的一个项目，从一开始一百个star到现在快破千了，见证着项目的成长。项目不时都有更新，因此建议在readme中附上更新说明，谢谢

**Comment by z-song** [comment]
好的，谢谢

**Comment by z-song** [comment]
以后的更新记录说明 会写在这里

http://z-song.github.io/laravel-admin/#/zh/change-log.md
