### ISSUE TITLE
laravel 6.2 installation error 

### ISSUE THREAD

**Issue by jin-null** [z-song/laravel-admin#4140]
- Laravel Version: 6.2
- PHP Version:7.2
- Laravel-admin: 1.7

### Description:
when i run php artisan admin:install 
it appends error :"Class name must be a valid object or a string"
![image](https://user-images.githubusercontent.com/9098750/68569248-9cc64100-0498-11ea-9e37-fe5a68d5d7a4.png)

**Comment by z-song** [comment]
Try to run `php artisan config:clear`

**Comment by Daniyal-Javani** [comment]
Same error, I tried:
```
sudo rm -rf storage/framework/cache/data/*
sudo rm -rf bootstrap/cache/*
sudo chown $USER:www-data storage/ -R
composer dump-autoload
php artisan clear
php artisan debugbar:clear
php artisan cache:clear
php artisan auth:clear-resets
php artisan config:clear
php artisan route:clear
php artisan view:clear
php artisan cache:forget spatie.permission.cache
php artisan config:cache
```
Would you please help me to install it?

**Comment by 247246** [comment]
Hi guys, have you solved the problem? I had the same error.

**Comment by Alexwalt** [comment]
I had solved the problem? copy "\vendor\encore\laravel-admin\config\admin.php" into "\config\admin.php",then try again "php artisan admin:install",can solve the problem.

**Comment by Jason-LZai** [comment]
I had solved the problem, just changed the laravel version to 5.5, there will no problem.

**Comment by Alexwalt** [comment]
Because of we forgot to run command `php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider"`, to publish the admin.php configure file

**Comment by ThedoRap** [comment]
Tried the solution of a few friends upstairs, can't solve

**Comment by zfy603206328** [comment]
php artisan vendor:publish

**Comment by cnicn** [comment]
1.copied the "\vendor\encore\laravel-admin\config\admin.php" file into "\config\admin.php" 
2. copy \vendor\encore\laravel-admin\database\migrations\2016_01_04_173148_create_admin_tables.php"  to  "\database\migrations\2016_01_04_173148_create_admin_tables.php"
3. run "php artisan admin:install"
