### ISSUE TITLE
编辑/创建后路由跳转错误

### ISSUE THREAD

**Issue by QiiSyhx** [z-song/laravel-admin#4141]
- Laravel Version: 5.5
- PHP Version:7.1
- Laravel-admin: 1.7

### Description:
禁用pjax:
```
\Encore\Admin\Facades\Admin::disablePjax();
```
路由：
```
$router->resource('users', 'UserController');
```
编辑用户资料的时候：
从列表进入：
编辑路由：/admin/user/1/edit
保存之后：
自动跳转到了: admin/user/1
应该要跳转回：admin/user

**Comment by TingSyuanWang** [comment]
#3882

**Comment by TingSyuanWang** [comment]
#2906

**Comment by codecodify** [comment]
我也遇到这个问题，主要是在全局禁止`disablePjax()`，后面改成在`form()`方法里禁止`disablePjax()`就正常跳转了。

**Comment by TingSyuanWang** [comment]
@codecodify 
嗨，谢谢你的帮忙
我有尝试在 form() 里面禁止 pajx，但是测试之后并没有生效，可以指正哪里错误了吗？
```
protected function form()
{
     Admin::disablePjax();
....内容....
     return $form;
}
```

**Comment by QiiSyhx** [comment]
\request()->headers->set('X-PJAX', false);
我有试过这种方法，暂时好像是可以的
