### ISSUE TITLE
after upgrading to v1.7.8

### ISSUE THREAD

**Issue by vonsogt** [z-song/laravel-admin#4142]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: 1.78

### Description:
Facade\Ignition\Exceptions\ViewException
Undefined variable: _user_ (View: D:\!BPN New\Program\ntappat\vendor\encore\laravel-admin\resources\views\index.blade.php)

I got that error when upgrade to latest version

**Comment by umerhassan82** [comment]
Try to clean your view cache
```php artisan view:clear```

**Comment by BoHongtao** [comment]
> Try to clean your view cache
> `php artisan view:clear`
that's good
