### ISSUE TITLE
hasMany issue in version 1.7.8

### ISSUE THREAD

**Issue by vonsogt** [z-song/laravel-admin#4144]
- Laravel Version: 6.x
- PHP Version:
- Laravel-admin: 1.7.8

### Description:
My Code:
```
public function ppat_deed_numbers()
{
    return $this->hasMany(PpatDeedNumber::class, 'data_order_id');
}
```
In previous version it work as well, but after upgrade to latest one it shows this
![image](https://user-images.githubusercontent.com/35516476/68636644-b87c2680-052e-11ea-8c22-a9e419b1f807.png)

@z-song Please help, that's buggy for latest version

**Comment by vonsogt** [comment]
Then, I tried to make a new column(s) and it will save like JSON
```
{"4":{"id":"4","_remove_":"0"},"new_1":{"number":"780","date":"2019-11-12","type":"apht","price":269000000,"_remove_":"0"}}
```
and absolutely there will not show/save into other table that have relations

**Comment by muhlisabdi** [comment]
Can you more specific? Is it one to many or many to many and can you provide your controller code?

**Comment by vonsogt** [comment]
> Can you more specific? Is it one to many or many to many and can you provide your controller code?

It's one to many, so this is the code:

Controller:
```
$form->hasMany('deed_legalization_numbers', 'Legalisasi', function (Form\NestedForm $nestedForm) {
	$nestedForm->number('number', 'Nomor Leges')->placeholder('Nomor Leges');
	$nestedForm->date('date', 'Tgl Disahkan')->placeholder('Tgl Disahkan');
	$nestedForm->text('title', 'Sifat Dokumen');
	$nestedForm->multipleSelect('name', 'Penghadap')
		->options(Costumer::all()->pluck('name', 'id'))
		->ajax('/admin/api/data/costumers');
});
```

Model:
```
public function deed_legalization_numbers()
{
	return $this->hasMany(DeedLegalizationNumber::class, 'data_order_id', 'id');
}
```

**Comment by muhlisabdi** [comment]
pakai ini mungkin bias mas
https://github.com/z-song/laravel-admin/pull/4112#issue-334874244

**Comment by vonsogt** [comment]
Let's wait for the changes in the next release

**Comment by jianminLee** [comment]
框架最新版本会导致下划线命名无法提交，找不到 “关系名”   列，该会驼峰命名后会成功，但是在编辑时又无法显示原先数据！
#3894
