### ISSUE TITLE
Is there anyway to update these buttons on the form: Back and List

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#415]
![2017-02-15_2141](https://cloud.githubusercontent.com/assets/24757934/23005136/9de5a15e-f3c8-11e6-91f9-7803435d57e5.png)

Can we edit these Back and List button links?

**Comment by z-song** [comment]
I have not done this yet

**Comment by zxy198717** [comment]
+1

**Comment by z-song** [comment]
Implemented see http://z-song.github.io/laravel-admin/index.html#/en/model-form.md#custom-tools

update to version 1.3.x-dev plz

**Comment by smuzammilali** [comment]
Any help how can I implement it, the link above is not working?

Also is it available in 1.4.x-dev?

**Comment by z-song** [comment]
@smuzammilali http://z-song.github.io/laravel-admin/#/en/model-form.md?id=custom-tools
