### ISSUE TITLE
右键行操作菜单如何添加一个以上？

### ISSUE THREAD

**Issue by datangkang123** [z-song/laravel-admin#4155]
第一个：
$grid->tools(function (Grid\Tools $tools) {$tools->append(new ImporDrcjtController());});
第二个：
$grid->actions(function ($actions) {$actions->add(new CjckController);});/

第一个会被第二个覆盖，如何才能添加一个以上的操作？

**Comment by z-song** [comment]
tools是在表格的头部设置操作按钮，actions是在每一行设置操作按钮，两个之间不冲突吧
