### ISSUE TITLE
我groupby 之后的分组数据 怎么导出呢

### ISSUE THREAD

**Issue by michelleyaoyao** [z-song/laravel-admin#4157]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

$grid->model()->groupBy('from_email','from_username','from_company')->select([DB::raw("count(*) as total")

怎么导出excel呢？

$excel = new Excel();
            $excel->columns = ([DB::raw("count(*) as total") => 'ddd'

报错 Illegal offset type

**Comment by jsonlove-cc** [comment]
https://laravel-admin.org/docs/zh/model-grid-export

**Comment by michelleyaoyao** [comment]
这个文档早就看过了。 正常的数据库字段是没问题的。 可是用到了groupby 和 count（*）的时候 就报错呢

**Comment by jsonlove-cc** [comment]
![image](https://user-images.githubusercontent.com/55566773/69039409-d5c95d00-0a26-11ea-8231-af823d92010e.png)
![image](https://user-images.githubusercontent.com/55566773/69039431-df52c500-0a26-11ea-9f3c-f905424ccaea.png)
我也用了没问题啊。你是报什么错误啊

**Comment by michelleyaoyao** [comment]
嗯。我用的laravel-excel 3.0  。  没法设置要导出的字段 

$excel = new Excel();
$excel->columns = ([DB::raw("count(*) as total") => 'ddd'



比如分组的数量。  。  如果是全部导出 倒是可以的。 

谢谢您的帮助。 先不赛选字段了。 全部字段下载了 。
