### ISSUE TITLE
/src/Form/Field/SwitchField.php switch开关的值写死为on和off，无法使用自定义值，比如1和0

### ISSUE THREAD

**Issue by xXys** [z-song/laravel-admin#4161]
- Laravel Version: 5.8
- PHP Version:7.1.3
- Laravel-admin: 1.7.7

### Description:
/src/Form/Field/SwitchField.php switch开关的值写死为on和off，无法使用自定义值，比如1和0

**Comment by wuxiumu** [comment]
我这边也遇到同样的问题，你那解决了吗？

**Comment by xXys** [comment]
switch开关的value默认是on和off，需要重写SwitchField的onSwitchChange方法
将
$(event.target).closest('.bootstrap-switch').next().val(state ? 'on' : 'off').change();
改为
$(event.target).closest('.bootstrap-switch').next().val(state ? '{$this-&gt;states['on']['value']}' : '{$this-&gt;states['off']['value']}').change();


$states = [
    'on'  =&gt; ['value' =&gt; 1, 'text' =&gt; '打开', 'color' =&gt; 'success'],
    'off' =&gt; ['value' =&gt; 2, 'text' =&gt; '关闭', 'color' =&gt; 'danger'],
];




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "五朽木"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 上午10:32
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com&gt;; 
抄送: "徐永胜"<964392197@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [z-song/laravel-admin] /src/Form/Field/SwitchField.php switch开关的值写死为on和off，无法使用自定义值，比如1和0 (#4161)




我这边也遇到同样的问题，你那解决了吗？

**Comment by z-song** [comment]
前端固定提交on和off，后端会通过src/Form/Field/SwitchField.php的prepare方法中处理为`states`属性中设置的值

**Comment by xXys** [comment]
刚又测试了一下，正常情况比如我在user表使用switch开关修改status字段是能够实现的
不过我的问题出在另一种情况，比如我有个setting表，字段不是固定的，是在model里面使用appends追加，然后组装成json存储到value字段中，这里使用switch就只会存储on和off
目前的解决方案是使用radio





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Song"<notifications@github.com&gt;; 
发送时间: 2019年11月21日(星期四) 中午11:14
收件人: "z-song/laravel-admin"<laravel-admin@noreply.github.com&gt;; 
抄送: "徐永胜"<964392197@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [z-song/laravel-admin] /src/Form/Field/SwitchField.php switch开关的值写死为on和off，无法使用自定义值，比如1和0 (#4161)




前端固定提交on和off，后端会通过src/Form/Field/SwitchField.php的prepare方法中处理为states属性中设置的值
 
&mdash;

**Comment by aoeng** [comment]
@z-song  列表中用 ,依然只提交on 和 off,疯狂报错,我只能使用修改器看看
