### ISSUE TITLE
quickSearch 问题

### ISSUE THREAD

**Issue by SmallRuralDog** [z-song/laravel-admin#4163]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.7.7

### Description:
用了`$grid->model()->where('xx',xx)`后`$grid->quickSearch()`不生效

**Comment by z-song** [comment]
`$grid->model()->where('xx',xx)`是设置的基础查询，`$grid->quickSearch()`会在基础查询上叠加查询条件

**Comment by manzhouya** [comment]
quickSearch 查询的条件导出表格的时候不会带上

**Comment by vlados** [comment]
See #3772
