### ISSUE TITLE
重构自带的用户管理、权限管理、菜单管理等

### ISSUE THREAD

**Issue by selfrefresh** [z-song/laravel-admin#4164]
- Laravel Version: 5.8
- PHP Version: 7.1.3
- Laravel-admin: 1.7.8

### Description:

@z-song 

如何重构laravel-admin自带的用户管理、权限管理、菜单管理等这几个功能

**Comment by selfrefresh** [comment]
@z-song 现在要用laravel-admin做个saas系统。根据域名来获取全局ID，然后，自带的后台用户管理、角色管理等是写在包里面的，有什么办法，可以给这些管理增加一个全局ID做CURD的过滤条件呢？ 求帮助

**Comment by z-song** [comment]
通过覆盖路由可以实现

**Comment by selfrefresh** [comment]
> 通过覆盖路由可以实现
有相关的参考吗？

**Comment by selfrefresh** [comment]
> 通过覆盖路由可以实现

有相关的参考吗？

**Comment by z-song** [comment]
@selfrefresh 比如自带的用户模块路径是`admin/auth/users`
路由注册为`$router->resource('auth/users',  \Encore\Admin\Controllers\UserController::class);`

那么你可以自定义一个控制器继承上面的控制器，修改里面的表格和表单

然后在`app/Admin/routes.php`注册相同的路由覆盖掉内置的用户模块路由

`$router->resource('auth/users',  你自定义的控制器);`
