### ISSUE TITLE
form hasMany 下的 multipleImage 在编辑时多个模型显示的图片一样

### ISSUE THREAD

**Issue by Liiijabn** [z-song/laravel-admin#4166]
- Laravel Version: 6.2
- PHP Version: 7.2
- Laravel-admin: 1.7.8

### Description:

如下代码所示，一个楼盘有多个户型，每个户型有多张图片。新建和查看楼盘的时候都没问题，但是在编辑楼盘时，多个户型显示的图片是一样的，都是第一个户型的图片。

```php 
        $form->hasMany('units', '楼盘户型', function(Form\NestedForm $nestedForm){
            $nestedForm->text('name', '户型名称');
            $nestedForm->number('area', '户型面积（㎡)');
            $nestedForm->text('position', '楼盘位置');
            $nestedForm->textarea('introduction', '户型介绍');
            $nestedForm->switch('recommend', '是否推荐户型');
            $nestedForm->multipleImage('images', '户型图片')->removable()->sortable();
        });
```

**Comment by Liiijabn** [comment]
编辑时其他户型名称、面积等字段各自显示是正常的，只有图片显示不对

**Comment by Yesr00** [comment]
[https://github.com/z-song/laravel-admin/pull/2425/commits/ca884d4deefdf53aa783ccf40407ccf6d5344267#diff-aab4e0be6522d00c8c377d1626748fe2](url)

查看这个地方。merge的时候src/Form/NestedForm.php 的代码没有合并进去。
