### ISSUE TITLE
列表删除bug

### ISSUE THREAD

**Issue by hxsen** [z-song/laravel-admin#4167]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: v1.7.8

### Description:
列表删除有bug。
在form删除回调deleting已经阻止了删除了，批量删除是被阻止了，但是grid列表的右侧的那个删除，还是可以删除数据，

**Comment by muhlisabdi** [comment]
Controller must have public function form to enabling delete batch

**Comment by hxsen** [comment]
> Controller must have public function form to enabling delete batch

The batch that is deleted now is no problem. When the deletion is blocked, the batch deletion can be blocked normally. The problem is that the right side of the list item is deleted individually and is not blocked. This is a place I don't understand.

**Comment by hxsen** [comment]
solved. Find the root of the problem. This is the link:
[权限控制](https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6)
The general meaning is that the deletion operation is not defined by the form, and additional permission logic is needed inside the model. As for other usages, still exploring
