### ISSUE TITLE
Data saves correctly in database for hasMany field. But it shows empty when editing.

### ISSUE THREAD

**Issue by Muhammadinaam** [z-song/laravel-admin#4174]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
Data saves correctly in database for hasMany field. But it shows empty when editing.

![image](https://user-images.githubusercontent.com/22542738/69505379-73eb8480-0f4b-11ea-9284-23d6b384a092.png)

**Comment by Muhammadinaam** [comment]
I think I have found where is bug:

in file:
vendor\encore\laravel-admin\src\Form\Field\HasMany.php
add $this->value = $relation->get()->toArray(); at line 428 (above: if (empty($this->value)) {)

**Comment by kelkmere** [comment]
@Muhammadinaam This fixed for me. Thanks.
