### ISSUE TITLE
希望自定义的新增按钮在右侧也能显示

### ISSUE THREAD

**Issue by rainsens** [z-song/laravel-admin#4175]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
如题：非常希望自定义的新增按钮在右侧也能显示。以前老版本是可以的，不知道新版本为什么取消了。

**Comment by z-song** [comment]
没明白你的意思，列表还是表单？

**Comment by foxtool23** [comment]
他的意思估计是 在列表页的右上角, 也能加一个自定义的 按钮,点击按钮可以做一些事情如跳转 或者弹窗

**Comment by rainsens** [comment]
![image](https://user-images.githubusercontent.com/11830109/69843647-78919f00-12a3-11ea-8ba2-9c0c7cf627d1.png)
感谢回复！
我的意思是加在红框位置

**Comment by z-song** [comment]
目前加不了，只能放在左边

不过你可以通过自定义表格的视图来实现， 参考`vendor/encore/laravel-admin/resources/views/grid/table.blade.php`自定义一个视图，加上你的按钮，然后通过`$grid->setView($view)`来指定它

**Comment by rainsens** [comment]
Ok, Thanks a lot.
