### ISSUE TITLE
使用关联表导出时报约束条件冲突

### ISSUE THREAD

**Issue by wzlzking** [z-song/laravel-admin#4176]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.7.7

### Description:
因为需要只查询文章类型的记录，所以在grid里先进行了一次left join进行筛选，这样的话，列表页可以正常显示，但导出时报约束条件冲突，麻烦请大神指教！

代码：
return Admin::grid(Recommend::class, function (Grid $grid) {

    //只显示文章推送记录，在这多进行了一次条件筛选
    $grid->model()->select('recommends.*','resources.title')
        ->leftJoin('resources', 'resources.id', 'recommends.resource_id')
        ->where('resources.type', Resource::TYPE_ARTICLE);
    $grid->id('ID')->sortable();
    $grid->column('resource.title', "标题");
    $grid->created_at();
    $grid->exporter(new RecommendExport());
});

报错信息：
 Integrity constraint violation: 1052 Column 'id' in field list is ambiguous (SQL: select `id` from `recommends` left join `resources` on `resources`.`id` = `recommends`.`resource_id` where `resources`.`type` = 0 and `recommends`.`deleted_at` is null limit 20 offset 0

**Comment by JinPengCN** [comment]
字段冲突的这个问题怎么解决？
