### ISSUE TITLE
duplicate "action" button global

### ISSUE THREAD

**Issue by aboveyunhai** [z-song/laravel-admin#4177]
- Laravel Version: 5.8.33
- PHP Version: 7.3.8
- Laravel-admin: 1.7

### Description:
I just wonder there are any straight ways to **duplicate** the action button **globally** (so it applies all form through out all the grid in admin). I only found the custom actions from document. I just used the default action button. I can create custom actions button but it seems unnecessary for this case.
It would look like 
![image](https://user-images.githubusercontent.com/35160613/69564698-7b2d8500-0f81-11ea-88b0-0b2e81ea5596.png)

**Comment by z-song** [comment]
You mean, if you want to add an action column to all the tables like your picture through global settings？

I think it may not be possible

**Comment by aboveyunhai** [comment]
Yes ,  I also noticed that it will cause some display problems if I try to duplicated regular data column. is that the limitation or constraint of admin?
