### ISSUE TITLE
能否把行操作的样式添加一个可以展开

### ISSUE THREAD

**Issue by yangforme** [z-song/laravel-admin#4179]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
如题,现在添加行操作比之前简单易用,但是需要像以前那种展开的样式,同时添加行操作的时候,就会变得很麻烦,老大有没有考虑过,新增一个默认展开的配置!

**Comment by z-song** [comment]
@yangforme 没太明白你的意思，你想使用原来的平铺按钮的操作列吗？按照文档设置就好了

https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E5%88%87%E6%8D%A2%E6%93%8D%E4%BD%9C%E5%88%97%E7%9A%84%E5%BD%A2%E5%BC%8F
