### ISSUE TITLE
Form里table编辑时丢图片

### ISSUE THREAD

**Issue by tickwudi** [z-song/laravel-admin#4180]
- Laravel Version: 5.5
- PHP Version:7.1.6
- Laravel-admin: 1.7.8

### Description:
`       $form->table('catelistconfig','分类信息',function (Form\NestedForm $nform){
            $nform->number('order','序号')->default(0);
            $nform->text('text','名称');
            $nform->image('imagesz',__('图标'))->uniqueName();

        });`
这是我的代码，新增时保存到数据表上的json正确，进入编辑页面也显示图片，就在点击保存后。查看数据库里的json是没有图标数据的。
正确:[{"order":"1","text":"\u79d1\u5b66","imagesz":"images\/68a2dc71de1abb62923a134d03d45bdf.png"}]
保存后:[{"order":"1","text":"\u79d1\u5b66"]
如果再点击上传图片，保存也能正确保存

**Comment by tickwudi** [comment]
仔细看了下，编辑时保存确实没有提交图片数据
因为我的那个字段是json格式的，所以想着在Model里的Set上判断写就可以了
`public function setcatelistconfigAttribute($catelist)
    {
        usort($catelist,function ($a,$b){
            return $a['order']>$b['order'];
        });
        $oldArray=json_decode($this->attributes['catelistconfig'],true);
        $fileKey='imagez';
        $newArray=array();
        foreach ($catelist as $cateitem){
            if(!isset($cateitem[$fileKey])){
                //未设置，可能是编辑
                $oldItem=Arr::first($oldArray,function($val,$key) use($fileKey,$cateitem){
                    if(isset($val[$fileKey]) && $val['text']==$cateitem['text']){
                        return true;
                    }
                });
                $cateitem[$fileKey]=$oldItem[$fileKey];
            }
            array_push($newArray,$cateitem);
        }
        $this->attributes['catelistconfig'] = json_encode(array_values($newArray));
    }`

**Comment by tickwudi** [comment]
`php
public function setcatelistconfigAttribute($catelist)
    {
        usort($catelist,function ($a,$b){
            return $a['order']>$b['order'];
        });
        $oldArray=json_decode($this->attributes['catelistconfig'],true);
        $fileKey='imagez';
        $newArray=array();
        foreach ($catelist as $cateitem){
            if(!isset($cateitem[$fileKey])){
                //未设置，可能是编辑
                $oldItem=Arr::first($oldArray,function($val,$key) use($fileKey,$cateitem){
                    if(isset($val[$fileKey]) && $val['text']==$cateitem['text']){
                        return true;
                    }
                });
                $cateitem[$fileKey]=$oldItem[$fileKey];
            }
            array_push($newArray,$cateitem);
        }
        $this->attributes['catelistconfig'] = json_encode(array_values($newArray));
    }
`

**Comment by sohenk** [comment]
我也有这个问题。请问解决了吗

**Comment by TheBlueSkim** [comment]
@sohenk   他提供的解决思路是对的，或者看 #4304 这个里面也有解决的思路
