### ISSUE TITLE
rules required 星标不见了

### ISSUE THREAD

**Issue by UnaHe** [z-song/laravel-admin#4181]
- Laravel Version: 6.5.2
- PHP Version: 7.3.8
- Laravel-admin: 1.7.8

### Description:
字段rules设置为required，星标不见了

### Steps To Reproduce:
现在的样式
![截屏2019-11-2717 19 59](https://user-images.githubusercontent.com/30680842/69715288-97285680-113a-11ea-9254-411b2a015b0c.png)
以前的（1.7.7）
![截屏2019-11-2717 23 57](https://user-images.githubusercontent.com/30680842/69715371-baeb9c80-113a-11ea-8820-6ad83af3b5d8.png)

**Comment by z-song** [comment]
提交了修复，你可以等下个版本，或者使用`$form->text()->required()`
