### ISSUE TITLE
权限BUG问题

### ISSUE THREAD

**Issue by Iamtong** [z-song/laravel-admin#4184]
- Laravel Version: 5.8
- PHP Version:7.3
- Laravel-admin: 1.7.8

### Description:
单行删除没有权限判断；
批量删除及编辑页面里面的删除按钮，当用户没有权限时，直接卡页面。也就是没有AJAX没有做error处理。

**Comment by shenjunbin** [comment]
我也遇到了这个问题，有什么方法可以解决吗？

**Comment by shenjunbin** [comment]
我也遇到了这个问题，有什么方法可以解决吗？

**Comment by shenjunbin** [comment]
我也遇到了这个问题，有什么方法可以解决吗？

**Comment by shenjunbin** [comment]
我也遇到了这个问题，包括行编辑的switch开关也是这样，卡住了

**Comment by z-song** [comment]
单行删除的权限控制，参考：https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6

**Comment by Iamtong** [comment]
> 单行删除的权限控制，参考：https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6

单行我是利用这个解决的。批量和编辑页面的删除卡住的问题，希望下个小版本能解决
