### ISSUE TITLE
$form->hasMany()时，当内部表单加上required()时，会出现移除后无法提交的bug！

### ISSUE THREAD

**Issue by yeardley** [z-song/laravel-admin#4187]
- Laravel Version: 6.*
- PHP Version: 7.2
- Laravel-admin: 1.7

### 描述:

$form->hasMany('items', __('project.Items'), function ($table) {
            $table->text('name', __('Name'))->required();
            $table->select('type', __('Type'))->options(['1' => ‘type 1’, '2' => 'type 2'])->required();
        });
然后在界面上，点击新增， 再点击移除。 会导致表单无法提交！

### 原因：
查看源码发现，点击移除按钮时， 在新增的div.has-many-items-form上增加了一个style="display:none"
同时点击提交按钮时，被移除的表单项还在继续验证required属性。 导致表单无法提交

**Comment by asen477** [comment]
和你遇到的问题雷同，我这里是编辑的时候，不能查看内容。

**Comment by WhiteKingdom** [comment]
自己创建一个 HasMany.php 文件继承 \Encore\Admin\Form\Field\HasMany.php，重写其中的 
 setupScriptForDefaultView() 方法中的 JS 部分
```js
$('#has-many-{$this->column}').off('click', '.remove').on('click', '.remove', function () {
    $(this).closest('.has-many-{$this->column}-form').remove();
    return false;
});
```

**Comment by asen477** [comment]
> 自己创建一个 HasMany.php 文件继承 \Encore\Admin\Form\Field\HasMany.php，重写其中的
> setupScriptForDefaultView() 方法中的 JS 部分
> 
> ```js
> $('#has-many-{$this->column}').off('click', '.remove').on('click', '.remove', function () {
>     $(this).closest('.has-many-{$this->column}-form').remove();
>     return false;
> });
> ```

ok,已经解决了，3q

**Comment by asen477** [comment]
ok，该问题已经解决，谢谢。



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"王旭"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月30日(星期一) 中午1:15
收件人:&nbsp;"z-song/laravel-admin"<laravel-admin@noreply.github.com&gt;;
抄送:&nbsp;"Trunks"<52351240@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [z-song/laravel-admin] $form-&gt;hasMany()时，当内部表单加上required()时，会出现移除后无法提交的bug！ (#4187)




自己创建一个 HasMany.php 文件继承 \Encore\Admin\Form\Field\HasMany.php，重写其中的
 setupScriptForDefaultView() 方法中的 JS 部分
 $('#has-many-{$this-&gt;column}').off('click', '.remove').on('click', '.remove', function () {     $(this).closest('.has-many-{$this-&gt;column}-form').remove();     return false; });

**Comment by Cuifc** [comment]
> 自己创建一个 HasMany.php 文件继承 \Encore\Admin\Form\Field\HasMany.php，重写其中的
> setupScriptForDefaultView() 方法中的 JS 部分
> 
> ```js
> $('#has-many-{$this->column}').off('click', '.remove').on('click', '.remove', function () {
>     $(this).closest('.has-many-{$this->column}-form').remove();
>     return false;
> });
> ```

这样做模型是不会删除掉这部分数据的
