### ISSUE TITLE
关于grid表头使用html问题

### ISSUE THREAD

**Issue by komahui** [z-song/laravel-admin#4192]
![image](https://user-images.githubusercontent.com/29142910/70024964-9aa65c80-15d6-11ea-82dc-5fd7b1f49ffe.png)
![image](https://user-images.githubusercontent.com/29142910/70025000-b7db2b00-15d6-11ea-9851-e77ad27be469.png)

这里能弄成{!! !!}的形式吗，不然表头不能用html了

**Comment by z-song** [comment]
已修改
