### ISSUE TITLE
Form tags组件无法正常输入中文

### ISSUE THREAD

**Issue by moqiaoduo** [z-song/laravel-admin#4193]
- Laravel Version: 6.2.0
- PHP Version: 7.2
- Laravel-admin: 1.7.8

### Description:
使用tags组件时，win10中文输入法只能输入第一个字，从第二个字开始无法正常输入，输入时输入法会闪，但无法选字，只能输入英文。

### Steps To Reproduce:
只需载入tags组件，在win10任意浏览器上打开有该组件的页面即可复现。

**Comment by jqhph** [comment]
提交了修复版本 [#4201](https://github.com/z-song/laravel-admin/pull/4201)。你可以先按这里面的方法重写下`Tags`组件，重写完在`app/Admin/bootstrap.php`中加入`Form::extend('tags', xxx);`覆盖原始组件即可。

**Comment by moqiaoduo** [comment]
@jqhph 感谢您的修复
不过我觉得应该在$this.val('');
这一句后面再加上$select.select2('close');
这样回车添加的同时候选框就能关闭了，也是符合原来操作的

**Comment by jqhph** [comment]
> @jqhph 感谢您的修复
> 不过我觉得应该在$this.val('');
> 这一句后面再加上$select.select2('close');
> 这样回车添加的同时候选框就能关闭了，也是符合原来操作的

有道理，我再提交个版本
