### ISSUE TITLE
升级jQuery3后，日期控件不能使用

### ISSUE THREAD

**Issue by yanxiaofeng** [z-song/laravel-admin#4202]
- Laravel Version: v6.5.2
- PHP Version: 7.2.18
- Laravel-admin: 1.7

### Description:
将public/vendor/laravel-admin/AdminLTE/plugins/jQuery/jQuery-2.1.4.min.js 替换为jQuery-3.4.1后，表单中日期时间控件不能使用

**Comment by yanxiaofeng** [comment]
![image](https://user-images.githubusercontent.com/13862014/70332524-b6cb2780-187c-11ea-9c3e-1b5c486a6d8c.png)

**Comment by Yanghsuanming** [comment]
是jQuery 3 的問題，要修改datepicker的套件把 show() 改css('display', 'block');
