### ISSUE TITLE
[BUG] "Home" 在多语言文件下导致出错

### ISSUE THREAD

**Issue by kslr** [z-song/laravel-admin#4203]
从1.7.6版本开始

https://github.com/z-song/laravel-admin/commit/5bd17e45df1789b7ed042589fcc9dffe9cdbcaab#diff-ba33d090eb56406038b444fd1476528c

```php
<li><a href="{{ admin_url('/') }}"><i class="fa fa-dashboard"></i> {{__('Home')}}</a></li>
```
如果存在
lang -> home.php

这样的文件就会导致获取到的翻译是一个数组，从而导致错误。

**Comment by z-song** [comment]
增加一个`resources/lang/zh-CN.json`文件, 加上`Home`的翻译

**Comment by kslr** [comment]
不放到现在的多语言里面(admin.php)是出于什么考虑的
