### ISSUE TITLE
感觉这个项目学习路径比较陡峭，比vue上手还要复杂一些

### ISSUE THREAD

**Issue by tu6ge** [z-song/laravel-admin#4205]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

**Comment by UnaHe** [comment]
是的吧，但是习惯了模式还是比较方便的 
毕竟作者除了这个项目也还有别的事情，不能面面俱到
大家多多支持，希望越来越好😊

**Comment by tu6ge** [comment]
设计思路类似vue，不过vue可以渐进的应用到项目中，这一块是不是可以借鉴一下

**Comment by puzzle9** [comment]
这个项目 可能对于后端来说 很方便
从前端给后端转的话 对于这个里面的概念 可能有点不太清楚
这个文档 先理解出那三个类型 模型 表格 / 表单 / 详情
再理解下 数据表单
这样 应该就发现这个很简单了

**Comment by z-song** [comment]
这个项目是基于Laravel的，再使用laravel-admin之前最好能对Laravel有一定的使用经验。
