### ISSUE TITLE
删除图片失败

### ISSUE THREAD

**Issue by bjbjbjbj** [z-song/laravel-admin#4206]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.7

### Description:
$form->multipleImage('pictures', '焦点图')->removable()->sortable()
删除图片提示
SyntaxError: Unexpected token < in JSON at position 0

**Comment by Jackfinal** [comment]
同问，我的图片能删除，但是提交表单后，图片还存在

**Comment by chenjiabin** [comment]
multipleImage 多图删除，只能从后面开始一张一张删除，
因为删除的是索引。 从前面开始删除算起。会有问题

**Comment by bjbjbjbj** [comment]
> multipleImage 多图删除，只能从后面开始一张一张删除，
> 因为删除的是索引。 从前面开始删除算起。会有问题

我直接删最后一张也这样，我自己写图片维护吧。。。

**Comment by zenghuang19** [comment]
这个问题是没时候能解决啊

**Comment by BinZhiZhu** [comment]
为什么没fix 就直接关闭了很多类似的issue ？
