### ISSUE TITLE
remove default form text icon  

### ISSUE THREAD

**Issue by topegret** [z-song/laravel-admin#4209]
Noticed that form text input by default has a 'fa-pencil' icon in 'input-group-addon' <span>. How to remove that prepand icon without touch package class file ( "Encore\Admin\Form\Field\Text.php") ?
I am able to remove it by

commend out "prepend('<i class="fa '.$this->icon.' fa-fw"></i>') " after "$this". But I prefer the elegant way from the controller.

**Comment by z-song** [comment]
There is no more elegant way currently

The simplest way is use `$form->text('text')->prepend(false);`

**Comment by topegret** [comment]
thanks, this is better than editing the package ! `'-> prepend(false)' ` is good enough for small width form.  But it  still makes the input field shorter on a large (wider) single line display settings.
