### ISSUE TITLE
[ASK] Can i using field back end to front end ?

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#421]
how can i use field backend to front end ? i hope can reuse your vendor css and js.

Thanks.

[![https://gyazo.com/269080406a36e5216c79b00958b467e3](https://i.gyazo.com/269080406a36e5216c79b00958b467e3.png)](https://gyazo.com/269080406a36e5216c79b00958b467e3)

**Comment by z-song** [comment]
The UI of laravel-admin is based on AdminLTE, which is designed for admin interface, it's inconvenient to put into the front end.
