### ISSUE TITLE
使用Laravel_excel 3导出搜索条件过滤

### ISSUE THREAD

**Issue by chenjiabin** [z-song/laravel-admin#4213]
- Laravel Version: 5.5
- PHP Version: 7.1
- Laravel-admin: 1.7.2

### Description:
当Grid有条件的时候，还是导出全部，不知道该怎么处理，
用$grid->column('player', __('openid'))->filter('like'); 的形式下无法使用搜索条件

### Steps To Reproduce:
用列过滤器 是无法使用导出搜索条件
$grid->column('player', __('openid'))->filter('like');

只能使用数据查询过滤的方式
 $grid->filter(function($filter) {
 $filter->like('player')
});

**Comment by uniteweiwei** [comment]
这个问题还是没有解决吧
