### ISSUE TITLE
表单中怎么在文件上传之后获取回调赋值

### ISSUE THREAD

**Issue by feikai2012** [z-song/laravel-admin#4214]
- Laravel Version: 5.6
- PHP Version:
- Laravel-admin: 1.7

### Description:
上传时调用
 $form->file('file_upload', '上传安装包')->removable()->addElementClass('apk_upload')->options([
        'showPreview' => false,
        'allowedFileExtensions'=>['apk'],
        'showUpload'=>true,
        'uploadAsync' =>true,
        'uploadUrl' => '/admin/common/apk_upload',
        'uploadExtraData' => [
            '_token'    => csrf_token(),
            '_method'   => 'POST',
        ],
    ])如何使用fileinput中的回调返回信息进行赋值表单

**Comment by OneZale1995** [comment]
遇到了同样的问题，你解决了吗？
