### ISSUE TITLE
Form->html 组件内的表单值不能自动保存，必须在 saving 回调中单独保存……

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#4219]
1，是否能够支持 自定义html页面表单的保存？
2，如果不支持，有没有简单的实现方法？我目前是比较笨的挨个 
$model->xxx = $form->xxx; 
$model->save();

@z-song

**Comment by faydanube** [comment]
定位到 vendor\encore\laravel-admin\src\Form.php 中 prepareInsert 方法的如下代碼：
`
        foreach ($inserts as $column => $value) {
            if (($field = $this->getFieldByColumn($column)) === null) {
                unset($inserts[$column]);
                continue;
            }

            $inserts[$column] = $field->prepare($value);
        }
`

希望作者能夠優化此部分，個人能力所限，只滿足了自己的需求，達不到pr的標準

@z-song

**Comment by z-song** [comment]
目前只能在saving回调中处理，你可以给html中的字段对应加一个hidden的field，在saving回调中，将html中的表单值 赋值给hidden

**Comment by lishuai199502** [comment]
请问在编辑时，用form->html(view())怎么把当前字段的值传给视图

**Comment by wannianma** [comment]
> 请问在编辑时，用form->html(view())怎么把当前字段的值传给视图
可以使用这种方式
```
        $form->html(function($model) {
           $vid = $model->vid;
            return view('ufms/wanlu/social/videoUploadPart', ["vid" => $vid]);
        });
```

**Comment by wannianma** [comment]
> 请问在编辑时，用form->html(view())怎么把当前字段的值传给视图

可以使用类似方式
```
        $form->html(function() {
            return view('ufms/wanlu/social/videoUploadPart', ["vid" => $this->vid]);
        }, 'video');
```
