### ISSUE TITLE
Cannot rewrite image path on the form element

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4220]
- Laravel Version: 6.2
- PHP Version: 7.2.19
- Laravel-admin: 1.7

### Description:
On the page to edit Model data image field use image path from home directory and I cannot rewrite it to specific directory **/public/images/news/**
As a result link to image on the page is broken, because it is looking for image located in /public/BTS-75V.jpg whereas this image located in /public/images/news/BTS-75V.jpg
![Capture](https://user-images.githubusercontent.com/10367464/70831359-6cf5ba80-1e03-11ea-958d-6312caa45f77.JPG)

Picture should appear in 3 pages: grid, detail, form.
In grid and detail there is no problems. But on the form page I cannot see picture, though everywhere I have the same path.

![Capture](https://user-images.githubusercontent.com/10367464/70868496-77928a00-1f92-11ea-9955-5eca8d6ca63b.JPG)

### Steps To Reproduce:
I tried to rewrite path using instruction here https://laravel-admin.org/docs/#/en/model-form-upload
```
    protected function grid()
    {
        $grid->column('image', 'Изображение')->display(function ($name) {
            return "img/news/$name";
            })->lightbox();
    }
    protected function detail($id)
    {
        $show->image('image', __('Изображение'))->as(function ($name) {
            return "img/news/$name";
            })->image();
    }
    protected function form()
    {
        $form = new Form(new News);
            $form->image('image', __('Изображение'))->name(function ($file) {
            return "images/news/$file";
            });
        return $form;
    }
```

In database I keep only image file name without full path. Then when I open in admin interface page to edit already existing content variable $file = 'BTS-75V.jpg' 
So I expect that code above is going to add path to my file and I will be able to see my image. But is doesn' happen.
This is only first problem.

Second problem - if I try to select new image from PC and upload to localhost I got error
```
 Exception In Local.php line 112 :
  Impossible to create the root directory "C:\laragon\www\steklo-group\storage\app\images/images/news/C:/Users/Anastasia/AppData/Local/Temp".
```

**Comment by pq16** [comment]
Анастасия, добрый вечер. 
Пользуйтесь поиском, тут эта проблем уже обсуждалась. (вроде я видел)
надо настроить в фале filesystems.php пути 
         'admin' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'visibility' => 'public',
             'url' => env('APP_URL').'/uploads',
        ],
И проверьте в фале .env 
APP_URL=http://{имя домена}

Удачи, если, что в хроме смотрите в инспекторе какие пути прописываются до картинок.

**Comment by schel4ok** [comment]
Спасибо я видел и это всё уже настроено.

Эта фотка выводится в 3 местах: grid, detail, form
В grid и detail фотка отображается на странице нормально. А вот на странице редактирования новости (form) нифига. Хотя пути везде прописаны одинаково.

```
    protected function grid()
    {
        $grid->column('image', 'Изображение')->display(function ($name) {
            return "img/news/$name";
            })->lightbox();
    }
    protected function detail($id)
    {
        $show->image('image', __('Изображение'))->as(function ($name) {
            return "img/news/$name";
            })->image();
    }

```

**Comment by pq16** [comment]
Вот, что то из старого нашел, может поможет.
 В контроллере :
 protected function tree()
    {
        return Equipment::tree(function (Tree $tree) {
            $tree->branch(function ($branch) {
                $src = config('admin.upload.host') . '/' . $branch['photo'] ;
                // $src->image();
                $photo = "<img src='$src' style='max-width:30px;max-height:30px' class='img'/>";
                return "{$branch['id']} - {$branch['title']} $photo";
            });
        });
    }
 protected function detail($id)
    {
        $show = new Show(Equipment::findOrFail($id));
        $show->field('title', 'Оборудование');
        $show->field('desc','Описание');
        $show->photo('Фотография')->image();
           return $show;
    }    
 protected function form()
    {
        $form = new Form(new Equipment());
        $form->display('id', 'ID');
        $form->select('parent_id', 'Верхний уровень')->options(Equipment::selectOptions());
        $form->text('title', 'Оборудование')->required();
        $form->textarea('desc','Описание');
        $form->image('photo', 'Фотография');
        return $form;
    }
в DB в таблице, столбец "photo" запись часть пути "images/equip.jpg"
и в конфиге admin.php:
'upload' => [
        // Disk in `config/filesystem.php`.
        'disk' => 'admin',
        'host' => '/uploads',
        // Image and file upload path under the disk above.
        'directory' => [
            'image' => 'images',
            'file'  => 'files',
        ],
    ],

Ну и в браузере соответственно:
<img src="http://testadmin/uploads/images/equip.jpg" class="file-preview-image kv-preview-data" title="equip.jpg" alt="equip.jpg" style="width:auto;height:auto;max-width:100%;max-height:100%;">
Надеюсь вам это поможет.
Удачи.

**Comment by schel4ok** [comment]
I found non-conformity. But I don't know how to solve it.

When you have image field in your resource it appears in 3 pages: grid, detail, form.
BUT it uses different directories!

For example my **config/filesystem.php**
```
        'admin' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => '',
        ],
```
In grid and detail image path rewritten using URL property. So in my case it is empty and if in image field in database I keep image name = 'BTS-75V.jpg' and then in controller I have **img/news/$name**
```
    protected function grid()
    {
        $grid->column('image', 'Изображение')->display(function ($name) {
            return "img/news/$name";
            })->lightbox();
    }
    protected function detail($id)
    {
        $show->image('image', __('Изображение'))->as(function ($name) {
            return "img/news/$name";
            })->image();
    }
```
Then browser willl looking for my image in http://myhostname/public/img/news/BTS-75V.jpg.
And he will found image there, because it is real file location.

But in form page image field is rewritten using ROOT property. So in my case it is **/storage/app** and if in image field in database I keep image name = 'BTS-75V.jpg' and then in controller I have **img/news/$name**
Resulting directory is "C:\laragon\www\steklo-group\storage\app\img/news/".
![Capture](https://user-images.githubusercontent.com/10367464/70937385-38793d00-2055-11ea-9f86-ff3be34ea5a1.JPG)

**Comment by ncham** [comment]
I also faced the same issue. In my case I upload the image to S3 and delete that. 
When the grid is loading I can give the image url from S3 but what about the form?
How to assign S3 url to form?
