### ISSUE TITLE
多图上传时如何使用异步上传

### ISSUE THREAD

**Issue by OneZale1995** [z-song/laravel-admin#4221]
- Laravel Version: 6.7.0
- PHP Version: 7.2
- Laravel-admin:  1.7.7
--
### Description:
我想使用异步上传进行多图上传，但我不知道如何操作，有完整的实例能进行参考吗？
### Steps To Reproduce:

**Comment by jqhph** [comment]
只能自己重新写一个MultipleImage字段了，然后上传到自己指定的接口，挺多工作的

**Comment by OneZale1995** [comment]
> 只能自己重新写一个MultipleImage细分了，然后上传到自己指定的接口，挺多工作的

嗯，我自己写了个多图上传的组件。
