### ISSUE TITLE
How to add button in the header

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4222]
- Laravel Version: 6.6.2
- PHP Version: 7.2.19
- Laravel-admin: 1.7

### Description:
I want to add button here to have possibility to view resource on the web page for example.
![www](https://user-images.githubusercontent.com/10367464/70845231-10bf8480-1e5d-11ea-9278-e98756616bd1.png)

In manual it is written how to add header above the grid table. But this header is added between button row and table. I want to add button above that header.

**Comment by uytpv** [comment]
Is there any solution? I have the same question. Thank you
