### ISSUE TITLE
How to add Total column?

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4224]
Laravel Version: 6.6.2
PHP Version: 7.2.19
Laravel-admin: 1.7

Let say I have 2 columns: **price** and **quantity**.
Is it possible to add 3rd column with  Total = price x quantity?

**Comment by z-song** [comment]
```php
$grid->column('price');

$grid->column('quantity');

$grid->column('total')->display(function () {
    return $this->price * $this->quantity;
});
```

**Comment by schel4ok** [comment]
Cool. Thanks
