### ISSUE TITLE
自定义权限控制

### ISSUE THREAD

**Issue by niyelail** [z-song/laravel-admin#4226]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.7.2

### Description:
自定义laravel-admin的权限控制

### Steps To Reproduce:
如何自定义laravel-admin的权限控制及菜单的展示，不更改源码的情况下

**Comment by jqhph** [comment]
app/Admin/routes.php中覆盖原路由，然后更改下中间件
