### ISSUE TITLE
how to disable auth log delete action

### ISSUE THREAD

**Issue by toknT** [z-song/laravel-admin#4229]
- Laravel Version: 5.5.45
- PHP Version: PHP 7.3.12-1
- Laravel-admin:  v1.6.15 

### Description:

How to disable auth log delete action.
管理员日志删除功能如何禁止

**Comment by vlados** [comment]
You can disable it from the config -> operation_log

**Comment by engr-hasanuzzaman** [comment]
> You can disable it from the config -> operation_log

@vlados would you please share the configuration? I did not find anything on the documentation.
