### ISSUE TITLE
Delete Action is NOT working in "grid" view at any controller

### ISSUE THREAD

**Issue by MohamedGamil** [z-song/laravel-admin#4231]
- Laravel Version: 5.8
- PHP Version: PHP 7.1.33
- Laravel-admin: 1.7.8

### Description:
So far this has been an issue that we were unable to resolve or even determine the reason behind it, clicking the "Delete" action from the drop-down menu for any row at any Admin CRUD controller will result in displaying the confirmation "swal" modal **without actually making a call or redirecting to the delete resource url**, this behavior has been observed only in "**grid**" view

### Steps To Reproduce:
1. Create / Open any admin controller that implements the modal grid functionality
2. Click on the actions menu trigger icon on the side of the row
3. Click delete from the displayed drop-down
4. Confirm the action by clicking "submit"
5. Nothing happens!

Here is a screenshot of the issue:
![Screenshot from 2019-12-17 11-12-09](https://user-images.githubusercontent.com/1338116/70981741-66469c00-20be-11ea-9b7b-a530579d1588.png)

**Comment by z-song** [comment]
Any error in console ?

**Comment by MohamedGamil** [comment]
No nothing at all!

**Comment by MohamedGamil** [comment]
Any updates regarding this?

**Comment by MohamedGamil** [comment]
By the way, I think the `handle` method is never called, 
I assumed so since I tried to make a custom action and its `handle` method is never called as well, so this means the `handle` method is never called via JS code in the UI for some reason.

I'd be happy to help with closing this issue just point me in the direction and I'll try to fix it and make a pull request, thanks again..

**Comment by MohamedGamil** [comment]
@z-song Please, I need this fixed ASAP, any updates?

**Comment by vlados** [comment]
You need to give more information. Please put some code...
First of all debug the swal - what is the js code for it in the view source

**Comment by MohamedGamil** [comment]
Hello everyone, 

this might be a bit late, but it might be handy for anyone facing a similar issue with using the new actions which implements `$.admin.swal({..})`.

I've narrowed down the reasons behind this issue, which is primarily because there isn't any request `data` sanitization before sending the request, at the `buildActionPromise()` method which can be located at `Dialog.php:L187`.

The reason in my case this variable got polluted with an unnecessary property `plugin_ripples`, which is the result of using the material UI extensions **jxlwqq/material-ui**, that and using the data object without performing any kind of sanitization before sending the `$.ajax({...})` request.

How I fixed the issue is by simply omitting the `plugin_ripples` property, a more final solution should simply dictate which properties can be sent for any performed ajax request, such that all properties that negates that rule should simply be omitted from request body data, which should allow for more flexibility using any extensions designed to work with Laravel Admin.

Please note that I'm using _Laravel_ version `5.8`, and _Laravel Admin_ version `1.7`.

Here is a detailed look at the changes I did to **Dialog.php**'s `buildActionPromise()` method:

```
    /**
     * @return string
     */
    protected function buildActionPromise()
    {
        call_user_func([$this->action, 'dialog']);

        $route = $this->action->getHandleRoute();
        $settings = $this->formatSettings();
        $calledClass = $this->action->getCalledClass();

        if ($this->uploadFile) {
            return $this->buildUploadFileActionPromise($settings, $calledClass, $route);
        }

        return <<<PROMISE
        var process = $.admin.swal({
            {$settings},
            preConfirm: function(input) {
                return new Promise(function(resolve, reject) {
                    Object.assign(data, {
                        _token: $.admin.token,
                        _action: '$calledClass',
                        _input: input,
                    });

                    data.plugin_ripples && delete data.plugin_ripples;

                    $.ajax({
                        method: '{$this->action->getMethod()}',
                        url: '$route',
                        data: data,
                        success: function (data) {
                            resolve(data);
                        },
                        error:function(request){
                            reject(request);
                        }
                    });
                });
            }
        }).then(function(result) {
            if (typeof result.dismiss !== 'undefined') {
                return Promise.reject();
            }
            
            if (typeof result.status === "boolean") {
                var response = result;
            } else {
                var response = result.value;
            }

            return [response, target];
        });
PROMISE;
    }
```

Thanks yall for your concern, I'll create a final solution for similar issues, and make a pull request very soon.
Stay safe everyone <3

**Comment by qahtansaid** [comment]
![image](https://user-images.githubusercontent.com/28402531/101526877-d4ffc200-39bf-11eb-8f2c-e1861d11c718.png)

in my case, i'm writing class in models with snake case (my_class), so as u can see, laravel-admin getting a wrong path model, with underscore changed to '/' so what i did was changing the snake case class in model with camel case(MyClass), and everything works fine ! hope it helps someone !
