### ISSUE TITLE
Unable to append / prepend new actions neither using the old nor the new suggested method

### ISSUE THREAD

**Issue by MohamedGamil** [z-song/laravel-admin#4232]
- Laravel Version: 5.8
- PHP Version: PHP 7.1.33
- Laravel-admin: 1.7.8

### Description:
This is a recently discovered issue as well with version 1.7.8, I'm unable to add any custom actions to grid actions, I've followed the documentation instructions word for word with no success. I think the latest version is quite buggy to be honest and needs some double checking, much love for the great work so far <3 

### Steps To Reproduce:
1. Use "append" or "prepend" on the actions instance passed down from the callback on grid actions method 
2. Expecting the link to be added to the drop-down, but nothing shows up or even the anchor content gets added to page's markup

**Comment by z-song** [comment]
Use "append" or "prepend" to add custom action to grid is deprecated now, Please refer to the method  in  https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=row-action

**Comment by MohamedGamil** [comment]
I'll try that and close the issue if it solves the problem, thanks bro <3

**Comment by MohamedGamil** [comment]
It's working now as expected, thanks bro <3
