### ISSUE TITLE
Model-show textfield without html tags

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4235]
Laravel Version: 6.6.2
PHP Version: 7.2.19
Laravel-admin: 1.7

### Description:
in model-show inside this field `$show->field('description', 'Description');` I can see raw text with html tags on the page
![Capture](https://user-images.githubusercontent.com/10367464/71029662-e867ac80-2120-11ea-8d4e-733a236e3cb9.JPG)

Is it possible to do output showing the resulting text?

**Comment by MohamedGamil** [comment]
You can use the `->unescape()` method which will display the value as intended.

**Comment by schel4ok** [comment]
cool. thanks!
