### ISSUE TITLE
slug from title. IMPORTANT!

### ISSUE THREAD

**Issue by leume** [z-song/laravel-admin#4236]
- Laravel Version: 6.*
- PHP Version: ^7.2
- Laravel-admin: ^1.7

Description: make slug from title, slug column should be hidden and autogenerated from title

Steps To Reproduce: how i can make it?

Example: 

        $form->text('title', __('Title'));
        $form->hidden('slug', __('Slug'))->value(this->title);

solutions like this->model()->slug doesn't work! please give proper solution.

**Comment by schel4ok** [comment]
Попробуй прикрутить этот пакет
https://github.com/ElForastero/Transliterate

Он для ларавел 5, но там кода совсем мало.
Даже если на 6 не встанет сразу, то допилить можно за пару сек

**Comment by leume** [comment]
@z-song

**Comment by z-song** [comment]
You can assign the value of title field to slug in a saving callback like:
```php
$form->saving(function ($form) {
    $form->slug = $form->title;
});
```

**Comment by leume** [comment]
@z-song thank you a lot! i think this code should be in documentation :)
