### ISSUE TITLE
v1.7.3版本后怎么修改自定义行操的路由（给路由传参）

### ISSUE THREAD

**Issue by maokuan** [z-song/laravel-admin#4241]
- Laravel Version: 5.8
- PHP Version:7.3.4
- Laravel-admin: 1.7.6

### Description:
我们的作品表是根据作者id进行分表的，现在“操作”删除和查看都会报错，因为模型里面找不到对应的表，找表需要作者id。在v1.7.3版本之前还可以指定操作的路由
![image](http://chuantu.xyz/t6/707/1576808982x2073530529.jpg)

但是v1.7.3之后是根据创建的文件自动生成路由，我需要在路由上面再增加一个参数作者id,该怎么操作呢。麻烦大家指教

**Comment by z-song** [comment]
https://laravel-admin.org/docs/zh/model-grid-custom-actions#%E5%88%87%E6%8D%A2%E6%93%8D%E4%BD%9C%E5%88%97%E7%9A%84%E5%BD%A2%E5%BC%8F

你可以继续使用原来的操作按钮方式

**Comment by maokuan** [comment]
@z-song  大佬，你发的这一块文档（v1.7.3版本对数据表格的行操作和批量操作进行了重构，数据的行操作重构为下拉菜单的形式）我已经看了好几遍，没看到传参啊。
原来的方式（上面的截图）在1.7.6里面不起作用。我目的是想把grid里面想一个参数传递到“查看”或“删除”操作里面

**Comment by z-song** [comment]
原来的方式还可以继续用，翻到上面文档最下面的【切换操作列的形式】部分

**Comment by maokuan** [comment]
现在看到了，谢谢大佬Thanks♪(･ω･)ﾉ
