### ISSUE TITLE
Image upload field put only filename to DB

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4250]
Laravel Version: 6.6.2
PHP Version: 7.2.19
Laravel-admin: 1.7

### Description:
I have local disk setup like that
```
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => '',
```
And I keep all images in `/storage/app/public/img`
Then after creating symlink `php artisan storage:link` my images also accessible from `/public/storage/img`

Then in model form for News resource I want to keep all images realted to News under `/public/storage/img/news`

And when I do upload field like that I can see full path public/img/news/bts-75v.jpg in my DB.
`$form->image('image', 'Picture')->move('/public/img/news');`

But I don't want to store full path in DB. It is too long and not comfortable.
I want to store filename only.
Is it possible?

**Comment by z-song** [comment]
For the file system, you must record the full path to access the file

If you just want to store the file name in DB, setting the accessor and mutator to the `image` field is the best way

**Comment by schel4ok** [comment]
Yes. It works with mutator. Thanks
```
    public function setImageAttribute($value) {
		// remove path and save only filename in database
		$this->attributes['image'] = substr($value, strrpos($value, '/') + 1);
    }
```

But still image upload field is not perfect.  I have 3 more remarks:
```
$form->image('image', 'Picture')->move('/public/img/news');
```
1) When you select file from another directory it is copied to the **move directory**. It is ok.
2) But if inside move directory exists file with the same name as selected file from another directory then file is copied with  filename like **1103086fe4879b91a62879beb16b3e87.jpg**. To me it is not correct. I prefer to overwrite existing file. But this is only up to me.
3) When you select file inside the **move directory** script try to make copy of this file with filename like **1103086fe4879b91a62879beb16b3e87.jpg**, but it is not needed in this case. If image already exists then there is no reason to create copy of it. User just wants to change image in the post. He doesn't want to create many copies of single image. This should be fixed I believe.

4) I cannot see current picture in upload field. Something wrong with the path
![Снимок](https://user-images.githubusercontent.com/10367464/71370540-408a2d00-25bf-11ea-9e25-65478ec94020.JPG)

On the picture above I open to edit post after just few seconds before I uploaded image bts-75v.jpg and this image was uploaded to directory **/public/img/news**
In chrome dev tools I see path like http://localhost/storage/bts-75v.jpg
But in **filesystems.php** I have 
```
        'admin' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => env('APP_URL').'/storage',
        ],
```


then in admin.php
```
    'upload' => [
        'disk' => 'admin',
        'directory' => [
            'image' => 'public/img/news', // here I tried to change with '' or 'public' no difference
            'file'  => 'files',
        ],
    ],
```

Any setting I put in  'image'  setting doesn't have any influence on upload image field.
Path is always http://localhost/storage/image.jpg
