### ISSUE TITLE
Hide actions button if column is true IMPORTANT!

### ISSUE THREAD

**Issue by leume** [z-song/laravel-admin#4254]
- Laravel Version: 6.x
- PHP Version: ^7.2
- Laravel-admin: 1.7

Description: in grid should hide (view, edit, delete) buttons if for example column is set to true

Example: 
if ($this->column == true) {
$grid->disableActions();
}
Steps To Reproduce: help please!

**Comment by leume** [comment]
@z-song

**Comment by z-song** [comment]
```php
$grid->actions(function ($actions) {
            if ($actions->row['column_name']  == true) {
                $actions->disableView()
                    ->disableEdit()
                    ->disableDelete();
            }
});
```

**Comment by leume** [comment]
thanks, works fine!
