### ISSUE TITLE
inline edit in grid with switch button

### ISSUE THREAD

**Issue by leume** [z-song/laravel-admin#4255]
Laravel Version: 6.x
PHP Version: ^7.2
Laravel-admin: 1.7

Description:
when inline edit with switch, can't save row with custom value, it saves with only 1 and 0.

Example:
        $states = [
            'on' => ['value' => Admin::user()->id, 'text' => 'locked', 'color' => 'primary'],
            'off' => ['value' => null, 'text' => 'unlocked', 'color' => 'default'],
        ];
        $grid->column('edit', __('Editing.'))->switch($states);

but table row saves it with 1 and 0, like default switch. i need if true admin user_id and if false null or 0.

Steps To Reproduce: help please!

**Comment by leume** [comment]
@z-song

**Comment by leume** [comment]
help please @z-song

**Comment by yosirn** [comment]
@leume 
try adding the values in  the form too
$states = [
'on' => ['value' => Admin::user()->id, 'text' => 'locked', 'color' => 'primary'],
'off' => ['value' => null, 'text' => 'unlocked', 'color' => 'default'],
];
  $form->switch('edit', __('editing'))->states($states);
