### ISSUE TITLE
Question: Limit users to only their own records?

### ISSUE THREAD

**Issue by vlados** [z-song/laravel-admin#4257]
How I can add condition if the user is not admin to see only the records that he created to the grid and edit action?

**Comment by adaoss** [comment]
Hi Vlados.
I think you can do that with global scopes. 
This link might help you
https://softonsofa.com/laravel-5-eloquent-global-scope-how-to/

**Comment by z-song** [comment]
Assume the `creator_id` field in your table represents the creator's id
```php
use Encore\Admin\Facades\Admin;

$grid->model()->where('creator_id', Admin::user()->id);
```

**Comment by vlados** [comment]
Thanks @z-song

**Comment by technilogics** [comment]
> 

How to allow form editing only for creator/owner
Ofcourse, if form is editing, as no need to check for new form creating
