### ISSUE TITLE
是否支持单元格合并展示

### ISSUE THREAD

**Issue by smirkcat** [z-song/laravel-admin#4259]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

![image](https://user-images.githubusercontent.com/13444394/71403645-50f7e180-266b-11ea-9d94-1ac832d4eab3.png)

是否支持呢

**Comment by z-song** [comment]
不支持

**Comment by phpstudyone** [comment]
> 不支持

这个需求不是非常常见么?
