### ISSUE TITLE
Coma in template.

### ISSUE THREAD

**Issue by iLegion** [z-song/laravel-admin#4260]
- Laravel Version: 6.8.0
- PHP Version: 7.3.2
- Laravel-admin: 1.7

### Description:
After rendering view i see coma.
[Screenshot #1](http://prntscr.com/qf62vs)
[Screenshot #2 (View)](http://prntscr.com/qf63gu)

### Steps To Reproduce:
Only this:
[My Controller](http://prntscr.com/qf63ub)

**Comment by z-song** [comment]
Can't reproduce your problem

**Comment by iLegion** [comment]
> Can't reproduce your problem

Hmm. Code below for me. P.S. HomeController:
`
public function index(Content $content)
    {
        return $content
            ->title(__('admin.index_page'))
            ->view('admin.pages.index');
    }
`

**Comment by z-song** [comment]
Update to the latest version, this issue has been fixed
