### ISSUE TITLE
复选框编辑选中的BUG

### ISSUE THREAD

**Issue by komahui** [z-song/laravel-admin#4262]
因为数据库用的是sql server，所以字段名都是大写的形式，新版本加入的这段代码会导致复选框编辑时不能被选中
![image](https://user-images.githubusercontent.com/29142910/71428613-bcd65a80-26fc-11ea-88a8-4c047fb74c53.png)

**Comment by z-song** [comment]
提交了修复，更新到dev-master版本，然后在你的model里面设置`$snakeAttributes`为false

```php
class Foo extends Model
{
    public static $snakeAttributes = false;
}
```

**Comment by komahui** [comment]
多谢！

**Comment by komahui** [comment]
snakeAttributes是要在每个模型里面都加吗？

**Comment by z-song** [comment]
> snakeAttributes是要在每个模型里面都加吗？

是的

**Comment by komahui** [comment]
这个加和不加区别是什么呢，我不是很明白这原理

**Comment by komahui** [comment]
@z-song 我这里有100多个模型，每个手动加手软了o(╥﹏╥)o

**Comment by z-song** [comment]
如果你所有的表字段都是驼峰命名，那么可以全局设置，在`app/Providers/AppServiceProvider.php`

```php
use Illuminate\Database\Eloquent\Model;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Model::$snakeAttributes = false;
    }
}
```

**Comment by komahui** [comment]
![image](https://user-images.githubusercontent.com/29142910/71438985-bf53a700-2732-11ea-81b9-8226dfd00601.png)
我们ERP的数据库字段是这种方式命名的
