### ISSUE TITLE
Updating to version 1.7.8 might cause problem $content not defined

### ISSUE THREAD

**Issue by hanachan1026** [z-song/laravel-admin#4264]
- Laravel Version: 5.8.*
- PHP Version: 7.3.*
- Laravel-admin: 1.7.8

### Description:
When I upgraded laravel-admin from 1.7.7 to 1.7.8, I get `$content not defined in content.blade.php`.

I use `app('view')->prependNamespace('admin',resource_path('views/laravel-admin'));` in Admin/bootstrap.php.

And of course, copied files from `/vendor/encore/laravel-admin/resources/views` to `resources/views/laravel-admin`.

### Steps To Reproduce:
1. composer update
2. try to access admin route /admin/*

**Comment by hldh214** [comment]
same here
