### ISSUE TITLE
行内编辑，能否一键更新某个字段为最新时间

### ISSUE THREAD

**Issue by aboutboy** [z-song/laravel-admin#4267]
我在管理后台，希望对文章推荐进行管理。有个最新推荐的功能，是以文章推荐时间为排序的。
希望能够通过点击事件，将该字段设置为当前最新时间。
目前我试用了一下editable('datetime')，感觉这个很难用。或者把这个样式优化一下，默认获取当前最新时间。
谢谢万能的作者！

**Comment by z-song** [comment]
参考文档最下面的【列操作】

https://laravel-admin.org/docs/zh/model-grid-column-display#%E5%88%97%E6%93%8D%E4%BD%9C

**Comment by aboutboy** [comment]
非常详细的文档，谢谢了。
