### ISSUE TITLE
列表页删除动作, 文件不会自动删除

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#4275]
- Laravel Version: 6.x
- Laravel-admin: 1.7.x

### Description:
删除数据时, 文件不会自动删除

### Steps To Reproduce:
删除一条含有附件的数据,
详情页点删除按钮, 附件能够自动删除
列表页的删除按钮(单个), 附件不会自动删除

@z-song

**Comment by z-song** [comment]
给模型加一个删除回调来处理

```php
public static function boot()
{
    parent::boot();

    static::deleted(function ($model) {
        //  $model->file  删除文件
    });
}
```
