### ISSUE TITLE
content.blade.php 里面多了个分号  ：）

### ISSUE THREAD

**Issue by zhpefe** [z-song/laravel-admin#4277]
- Laravel Version: #.#.#
- PHP Version:  1.7
- Laravel-admin: #.#.#

### Description:
·
@if($_view_)
    @include($_view_['view'], $_view_['data'])；
@else
·
导致所有content 页面最后都多了个分号，小小的问题

**Comment by z-song** [comment]
https://github.com/z-song/laravel-admin/blob/master/resources/views/content.blade.php#L63

应该已经修复了
