### ISSUE TITLE
xss 漏洞

### ISSUE THREAD

**Issue by nosun** [z-song/laravel-admin#4278]
- Laravel Version: 6
- PHP Version: 7.3
- Laravel-admin:1.6

### Description:

laravel-admin 后台添加菜单，菜单的 title 字段没有防护，设置 xss 攻击脚本，可以成立。

同时，laravel-admin 日志中显示的详情也会收到 xss 攻击。

### 步骤

在 菜单中增加 <img src=''  onerror=alert(1)>

**Comment by nosun** [comment]
可以在菜单 saving 增加回调，进行过滤

**Comment by NickCoolii** [comment]
> 可以在菜单 saving 增加回调，进行过滤

Any examples of such kind of attacks?
Also example of filtering will be helpful.

@nosun are you talking about this?
https://github.com/z-song/laravel-admin/pull/4293

**Comment by nosun** [comment]
@NickCoolii ，no。

the example be filttered by github, I will attach the picture to 
![Snip20200222_11](https://user-images.githubusercontent.com/2755419/75091961-f5d06580-55ad-11ea-93f6-f6752db71bea.png)
you
