### ISSUE TITLE
自定义action,通过$this->getKey获取当前行主键不是当前行真实主键

### ISSUE THREAD

**Issue by zyenggook** [z-song/laravel-admin#4280]
- Laravel Version: 6.0.#
- PHP Version:7.2.24
- Laravel-admin:  1.7.8

### Description:
一个订单展示页面,根据主键(id)倒序展示.action选择自定义按钮获取当前行数据跟展示数据不对等

### Steps To Reproduce:
```php
class CancleOrder extends RowAction
{
    public $name = '撤销';

    public function handle(Model $model, Request $request)
    {
        $orderLog = OrderLog::find($this->getKey());
        $orderLog->status = '88888';
        $orderLog->save();
        return $this->response()->success('Success message.')->refresh();
    }

    public function dialog()
    {
        $this->confirm($this->getKey());
    }
}
```

**Comment by komahui** [comment]
$model就是当前行的数据，用$model->id

**Comment by zyenggook** [comment]
额$model是当前行数据这个明白,我这个问题说不清,我给复现一下哈...看下附件截图.


情况是这样,有2个疑问.
1.
数据界面是两个表格join之后根据id(主键)倒序展示的.
我点击不同行action的复制,都弹出截图里主键:488
按照文档所说, $this->getKey()是获取当前行的主键,应该是507才对吧?


2.
看第四个截图,只有handle的时候,进不去这个方法?看了日志没有任何输出
在2019年12月31日 15:08，komahui<notifications@github.com> 写道：

$model就是当前行的数据，用$model->id
