### ISSUE TITLE
Grid filter： Gt，Lt 在pjax渲染页面时走样deformed

### ISSUE THREAD

**Issue by a443939412** [z-song/laravel-admin#4284]
- Laravel Version: 5.5.*
- PHP Version:7.1
- Laravel-admin: ^1.6.*

### Description:
Grid filter： Class Gt and Lt 过滤对应的试图文件（view file）中有{{$label}}&nbsp;(>)，其中 <,> 在pjax渲染页面时走样（deformed），可将
【< 改成 & l t ;】 no blank space
【> 改成 & g t ;】 no blank space
即可解决显示问题。但是直接修改插件源码是不明智的做法， 重写Filter\Lt，Filter\Gt又不甘心， 坐等laravel-admin升级，等到现在还没好。

### Steps To Reproduce:
Pjax请求，打开带Gt，Lt过滤的页面，渲染走样！在chrome、firefox、IE下均都可复现。
![image](https://user-images.githubusercontent.com/13361366/71609286-2e614d80-2bc2-11ea-9224-03f7d1d10be3.png)

Another：Grid的快捷热键是在v1.6之后新增的吧，c是create的快捷键， 我ctrl + c的时候就不要触发了嘛。

**Comment by z-song** [comment]
确实有这个问题，已经提交了修复，谢谢指出，欢迎提交pr
