### ISSUE TITLE
Class admin.router does not exist!

### ISSUE THREAD

**Issue by Tairy** [z-song/laravel-admin#429]
最新版本报错@1.4.x-dev

Class admin.router does not exist!

**Comment by z-song** [comment]
参考 https://github.com/z-song/laravel-admin/blob/master/src/Commands/stubs/routes.stub 来定义你的路由

**Comment by Tairy** [comment]
嗯  已经解决了，不过比较好奇为什么要弃用之前的那种定义方式

**Comment by z-song** [comment]
之前的方式是对 laravel 路由定义的封装，其实不太灵活

直接使用Laravel的路由定义，能直接上手，不需要看laravel-admin的路由定义文档

**Comment by Tairy** [comment]
明白了，感谢 @z-song

**Comment by EdFuy** [comment]
“参考 https://github.com/z-song/laravel-admin/blob/master/src/Commands/stubs/routes.stub 来定义你的路由“
 地址404了
