### ISSUE TITLE
Admin::css('/css/uxx.css');为啥放在了html中css的最上面怎么覆盖对于的css

### ISSUE THREAD

**Issue by 377123** [z-song/laravel-admin#4294]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
bootstrap.php 里面添加
Admin::css('/css/uxx.css');
为啥放在了html中css的最上面 覆盖对于的css也覆盖不了

**Comment by Elevioux** [comment]
赞同，希望多一个参数或者直接把自己添加的css放到最后，否则自己写的样式全被覆盖了。非得加 !important 才行。
