### ISSUE TITLE
Issue performing composite unique validation

### ISSUE THREAD

**Issue by silver619** [z-song/laravel-admin#4298]
- Laravel Version: 6.9.0
- PHP Version: 7.2.25
- Laravel-admin: 1.7.8

### Description: I am trying to perform a composite unique validation on a field, but in order to do this i need to get the value of the previous field and cannot find a way to achieve this. For example i have two fields, item_number and design_number, and in the database you cannot have both those fields with the same values (ex: item_number = 1 together with design_number = green cannot occur a second time). My form definition has:

```
$form->number('item_number', __('Item number'))->required();
$form->text('design_number', __('Design number'))->required()->rules(function(Form $form ) {
     return 'unique:fabrics,design_number,NULL,fabrics,item_number,' . $form->item_number;
});
```
I do not know of how to get the item_number filled in the first field.

**Comment by z-song** [comment]
You may get the value of item_number field from `request('item_number')`

**Comment by silver619** [comment]
This works. Thank you.
