### ISSUE TITLE
自定义操作，并根据行数据，显示不同文字提示的弹窗

### ISSUE THREAD

**Issue by he5127** [z-song/laravel-admin#4300]
- Laravel Version: 5.8.*
- PHP Version:
- Laravel-admin: 1.5.#

### Description:
添加自定义操作后，在执行前，需要弹窗确认，弹窗显示的内容需要根据操作的本行的数据确定

### Steps To Reproduce:
![QQ截图20200107180501](https://user-images.githubusercontent.com/39181590/71887073-53346280-3178-11ea-8659-cafd8aff72d8.png)
![QQ截图20200107180537](https://user-images.githubusercontent.com/39181590/71887083-57f91680-3178-11ea-8c75-38df2177ad33.png)

**Comment by z-song** [comment]
贴一下你的代码看看？

**Comment by he5127** [comment]
public function dialog()
    {
        $title=$this->row->is_show?'确定要隐藏吗？':'确定要显示吗？';
        return $this->confirm($title);
    }
这样写并没有用，弹窗的内容是一样的

**Comment by z-song** [comment]
有一个替代方法，用两个action来控制

```php
        $grid->actions(function (ContextMenuActions $actions) {

            if ($actions->row['is_show']) {
                $actions->add(new Action1());
            } else {
                $actions->add(new Action2());
            }
        });
```

**Comment by he5127** [comment]
我现在就是这么做的

> 有一个替代方法，用两个action来控制
> 
> ```
>         $grid->actions(function (ContextMenuActions $actions) {
> 
>             if ($actions->row['is_show']) {
>                 $actions->add(new Action1());
>             } else {
>                 $actions->add(new Action2());
>             }
>         });
> ```

我现在就是这么做的

**Comment by z-song** [comment]
一个操作类也可以实现

```php
class ShowAction extends RowAction
{
    public $name = '操作';

    protected $confirm;

    public function __construct($type)
    {
        if ($type) {
            $this->confirm = '确定要隐藏吗?';
            $this->selector = '.action-hide';
        } else {
            $this->confirm = '确定要显示吗?';
            $this->selector = '.action-show';
        }

        parent::__construct();
    }

    public function handle(Document $document)
    {
        return $this->response()->success('success')->refresh();
    }

    public function dialog()
    {
        $this->confirm($this->confirm);
    }
}
```

加入grid中
```php
$actions->add(new ShowAction($actions->row['is_show']);
```

**Comment by he5127** [comment]
谢谢

**Comment by amun1303** [comment]
> ```
> ShowAction
> ```

I don't know Document name space. Please show me Document namespace, thank you.
