### ISSUE TITLE
can i using laravel admin with azure or amazon ?

### ISSUE THREAD

**Issue by mRamadan0101** [z-song/laravel-admin#4301]
- Laravel Version: 6.
- PHP Version: 7.2
- Laravel-admin: 1.7

### Description:
can i using azure services with laravel admin like storage and upload videos ?
i try to use storage services but can not access files after upload it from admin

**Comment by z-song** [comment]
Did the file upload successfully?

**Comment by mRamadan0101** [comment]
i want to use large file ext, with azure
file upload successfully to storage but i cant find way to upload it to media services

**Comment by mRamadan0101** [comment]
fixed and upload to S3

**Comment by mRamadan0101** [comment]
> Did the file upload successfully?

Yes
