### ISSUE TITLE
$form->table 编辑时，数据不保存

### ISSUE THREAD

**Issue by catlane** [z-song/laravel-admin#4304]
- Laravel Version: #.#.# 5.8
- PHP Version:7.2
- Laravel-admin: #.#.#

### Description:
 $form->table('works', '作品预览', function ($table) {

        $table->text('title', '标题');
        $table->image('cover', '图片');
       $table->textarea('description', __('描述'))->style('height', '50px');
    });
这样写的代码，添加的时候数据有显示，执行show()方法的时候也显示，但是编辑保存后，cover的值就丢了，
保存数据由：
[{"cover":"arts\/images\/338dfd0285833d3acfa88b282197d7ba.jpeg","title":"Blue ocean","description":"Blue ocean"},{"cover":"arts\/images\/d52b168f7371ed9733ff7cfc318f0990.jpg","title":"Morning glory","description":"Morning glory"},{"cover":"arts\/images\/05bcb027423492bee5808754cdfbe584.jpg","title":"zebra","description":"zebra"}]
变为下边的格式了：
[{"title":"Blue ocean","description":"Blue ocean"},{"title":"Morning glory","description":"Morning glory"},{"title":"zebra","description":"zebra"}]

**Comment by TheBlueSkim** [comment]
我遇到了同样的问题，话说可以用中文提交问题的吗。。我的垃圾英文快把我逼崩溃了

**Comment by TheBlueSkim** [comment]
老哥，我找到解决的办法了，其实这个不是bug，是form组件的默认行为，经过测试，当你编辑时，文件类的组件如果没有上传新的内容，这个字段是不会进入到request内的，所以update的时候，其实这个字段是没有修改的。
这个在普通的表单内是没问题的，但是在$form->table()内就有问题，由于table内是二维数组，大概率是个[{title=>***,image=>***}]的形式，组件之间是互不干涉的，所以编辑保存的时候，title会传，image如果没有上传新图片就不传了，也就重现了咱们现在的问题。

为了解决这个问题，其实也简单，在自定义的修改器里，获取旧数据，然后与新数据比对，如果对应索引的数据存在且图片文件为空，就将旧的文件路径添加进去即可。下面是我的自定义修改器代码，仅供参考：
`
            $old_content = $this->getContentsAttribute();
            foreach ($content as $key => &$val) {
                // 如果旧数据未删除，且当前不存在图片，则将旧图片路径添加进去
                if (isset($old_content[$key]) && !isset($val['image'])) {
                    $val['image'] = $old_content[$key]['image'];
                }
            }
            $this->attributes['content'] = json_encode(array_values($content));
`

**Comment by TheBlueSkim** [comment]
@z-song  老哥你看下这个解决思路对不对，我看issue里好多关于这个的问题，如果思路没问题就可以归并到这个解决方案下来了。
