### ISSUE TITLE
action 模态框 form表单 select 选择框不能搜索

### ISSUE THREAD

**Issue by Ctlynl** [z-song/laravel-admin#4308]
![image](https://user-images.githubusercontent.com/38125573/72034156-39f1fa00-32cf-11ea-83ce-d06ef51f7514.png)

**Comment by ruibin** [comment]
跟我的问题重复，下面是我的解决办法：
https://github.com/z-song/laravel-admin/issues/4276

**Comment by nioxiao** [comment]
可以去掉 modal 的 tabindex="-1" 来解决，在 app/Admin/bootstrap.php 文件中加入以下代码：
`
Admin::script('$(document).ready(function(){ $(".modal").removeAttr("tabindex"); });');
`
