### ISSUE TITLE
Error when use $form->table($column, $label, $builder)->setDisplay(false)

### ISSUE THREAD

**Issue by TheBlueSkim** [z-song/laravel-admin#4309]
- Laravel Version: 5.6
- PHP Version: 7.2
- Laravel-admin: 1.7.7

### Description:
When i want to hide field in form, I use `$form->table($column, $label, $builder)->setDisplay(false)` but I get a error with "call to a member function with() on string".
### Steps To Reproduce:
With reading the source code, I find the reason, in HasMany.php line 669 `
return parent::render()->with([
            'headers'      => $headers,
            'forms'        => $this->buildRelatedForms(),
            'template'     => $template,
            'relationName' => $this->relationName,
            'options'      => $this->options,
        ]);
` , the "parent::render" will return empty string when it's property of display is false, and this make the bug.

**Comment by z-song** [comment]
Fixed, thanks for pointing out this issue
