### ISSUE TITLE
How to replace action buttons globally?

### ISSUE THREAD

**Issue by jonphipps** [z-song/laravel-admin#431]
I'd like to set a different set of default row actions for all grids. But I can't see a way to do this in bootstrap.php. If this can't be done, I would also like to change the class and icon for the edit|delete actions, but this looks difficult too.

Right now, I'm doing this on each grid:
```php 
$grid->actions(function ($actions) {
    $actions->disableEdit();
    $actions->append(
        '<a href="'.$actions->getResource().'/'.$actions->getKey().'" class="btn btn-xs btn-info" style="margin-right:4px">
        <i class="fa fa-search" data-toggle="tooltip" data-placement="top" title="" data-original-title="View"></i></a>' );
    $actions->prepend(
         '<a href="'.$actions->getResource().'/'.$actions->getKey().'/edit" class="btn btn-xs btn-primary" style="margin-right:4px">
        <i class="fa fa-pencil" data-toggle="tooltip" data-placement="top" title="" data-original-title="Edit"></i></a>' );
});
```

And then the 'delete' button styling doesn't match unless I replace that too.

**Comment by z-song** [comment]
Currently not support.

I'll add this feature in next version.

**Comment by z-song** [comment]
The latest dev version already supports defining global columns.

In app/Admin/bootstrap.php
```php
Column::define('dummy', function () {
    return 'column content';
});
```
Then any column in grid  with name `dummy` use above definition.

The name of action column in grid is `__actions__`, so you can override builtin actions column as follows:

Define a action class extends `Encore\Admin\Grid\Displayers\Actions` and override the html：
```php
class CustomActions extends \Encore\Admin\Grid\Displayers\Actions
{
    protected function editAction()
    {
        return <<<EOT
<a href="/{$this->getResource()}/{$this->getKey()}/edit" class="btn btn-xs btn-default">
    <i class="fa fa-edit"></i> Edit
</a>
EOT;
    }

    protected function deleteAction()
    {
        parent::deleteAction();
       
                return <<<EOT
<a href="javascript:void(0);" data-id="{$this->getKey()}" class="grid-row-delete btn btn-xs btn-danger">
    <i class="fa fa-trash"></i> Remove
</a>
EOT;
    }
}
```
In bootstrap.php
```php
Column::define('__actions__', CustomActions::class);
```

After this, all actions column will be replaced with `CustomActions`.

**Comment by jonphipps** [comment]
Cool! Thanks! :1st_place_medal:

**Comment by langeuh** [comment]
This works only partly.

Overriding the '__ actions __' column as described, works, but it completely ignores any call to $actions->prepend(), append(), disableDelete(),...

eg
```
return Admin::grid(
            $this->modelClass,
            function (Grid $grid) {

                $grid->actions(
                    function (Actions $actions) {
                            $actions->prepend( 'before' );
                            $actions->disableDelete();
                            $actions->append('after');
                        }
                    }
                );
            }
        );
``` 
The action column only shows the 'edit' and 'delete' buttons


Propably the same thing happens for '__ row_selector __' as Grid->appendActionsColumn() and Grid->prependRowSelectorColumn() don't use the overwritten classname defined in bootstrap.php

**Comment by z-song** [comment]
@langeuh Yes you're right, I didn't notice that, need to find another way to fix this.

**Comment by naingwin** [comment]
@z-song  I can't prepend action to actions column after I customize, if already solve, please let me know.

**Comment by banstola** [comment]
I still have same problem in version 1.7 . Is this fixed?

**Comment by schel4ok** [comment]
I tried to do that, but I have error
Symfony\Component\Debug\Exception\FatalThrowableError
Class 'Column' not found

**Comment by toknT** [comment]
@schel4ok  from the document https://laravel-admin.org/docs/#/en/model-grid-init?id=grid-initialization-settings .Just custom `Grid::init`

**Comment by toknT** [comment]
From the document https://laravel-admin.org/docs/#/en/model-grid-init?id=grid-initialization-settings.

We can global disable delete tool and action like this
```php
Grid::init(function (Grid $grid) {
    $grid->actions(function (Grid\Displayers\Actions $actions) {
        $actions->disableDelete();
    });
    $grid->tools(function ($tools) {
        $tools->batch(function ($batch) {
            $batch->disableDelete();
        });
    });
});
```
to enable delete do this in every grid

```php
$grid->actions(function ($actions) {
    $actions->disableDelete(true);
});

$grid->tools(function ($tools) {
      $tools->batch(function ($batch) {
          $batch->disableDelete(false);
     });
});
```

**Comment by Incher25** [comment]
It still ignores appending custom actions (I'm using 1.7.6). Is it solved?

**Comment by seeyeong** [comment]
I used render to override the render Edit and Delete, but the view button still come out, but at least I got change the button globally.

bootstrap.php

```
Grid::init(function (Grid $grid) {
  $grid->actions(function (Grid\Displayers\Actions $actions) {
    $actions->disableView();
    $actions->disableEdit();
    $actions->disableDelete();
  });
});
```

CustomActions.php
```
class CustomActions extends \Encore\Admin\Grid\Displayers\Actions
{
  protected function renderEdit()
  {
    return <<<EOT
<a href="/{$this->getResource()}/{$this->getKey()}/edit" class="btn btn-xs btn-default">
    <i class="fa fa-edit"></i> Edit
</a>
EOT;
  }

  protected function renderDelete()
  {
    parent::renderDelete();

    return <<<EOT
<a href="javascript:void(0);" data-id="{$this->getKey()}" class="grid-row-delete btn btn-xs btn-danger">
    <i class="fa fa-trash"></i> Remove
</a>
EOT;
  }
}
```

![image](https://user-images.githubusercontent.com/7313564/80260292-2457e300-86ba-11ea-840d-391c74850c9f.png)

**Comment by alexandrekadri** [comment]
> I tried to do that, but I have error
> Symfony\Component\Debug\Exception\FatalThrowableError
> Class 'Column' not found

try  to use on bootstrap.php
Encore\Admin\Grid\Column::define('__actions__', \App\Admin\Controllers\CustomActions::class);

"\App\Admin\Controllers\" is where you will save the CustomActions::class

**Comment by xuanchau99** [comment]
> @langeuh Yes you're right, I didn't notice that, we need to find another way to fix this.

how to fix it?

**Comment by Erandelax** [comment]
> how to fix it?

Instead of
`Column::define('__actions__', CustomActions::class);`

Use
`Grid::init(fn(Grid $grid) => $grid->setActionClass(CustomActions::class));`

**Comment by webeasystep** [comment]
how to do this with v 2 beta5 , because grid is already replaced with Table class ?

**Comment by diasgab** [comment]
If you just want to display the actions but without using the dropdown:

<img width="709" alt="Screenshot 2023-06-21 at 16 44 33" src="https://github.com/z-song/laravel-admin/assets/523604/7f8c07a9-cbde-4266-a9be-c0b2e91d87d9">

Then you will see something like:

<img width="85" alt="Screenshot 2023-06-21 at 16 45 32" src="https://github.com/z-song/laravel-admin/assets/523604/d585c2c2-a583-482e-bb69-d9123b5bec43">
