### ISSUE TITLE
详情展示附件（多文件，文件格式未知，且不一定相同）

### ISSUE THREAD

**Issue by he5127** [z-song/laravel-admin#4310]
- Laravel Version: 5.8.#
- PHP Version:
- Laravel-admin: 1.5.#

### Description:
详情页面中，附件是来自于另外一张表的多条记录，包含文件路径，如何展示所有文件（展示图标）
![多文件展示](https://user-images.githubusercontent.com/39181590/72051376-227e3580-32fe-11ea-8cda-8ba96658feb9.png)
![image](https://user-images.githubusercontent.com/39181590/72051425-3cb81380-32fe-11ea-8d0c-c6871ac363ba.png)

**Comment by z-song** [comment]
`as` 方法的回调可以返回一下视图，在视图文件里面去渲染你的图片列表就行了

```php
$show->field('message_attachments')->as(function () {
    
    $attachments = 拿到文件数据

    return view('你的视图路径',   compact('attachments'));
});
```
