### ISSUE TITLE
delete_at为时间戳类型，软删除怎么使用

### ISSUE THREAD

**Issue by Cuifc** [z-song/laravel-admin#4311]
- Laravel Version: 6.2
- PHP Version: 7.3.12
- Laravel-admin: 1.7.8

### Description:
数据库中的删除字段delete_at是时间戳类型，请问如何实现软删除？谢谢

**Comment by batouy** [comment]
我觉得文档应该多看看：

![微信截图_20200111085525](https://user-images.githubusercontent.com/9566549/72195969-2b7f1c00-3450-11ea-98b3-6b895073dec0.png)

**Comment by Cuifc** [comment]
> 我觉得文档应该多看看：
> 
> ![微信截图_20200111085525](https://user-images.githubusercontent.com/9566549/72195969-2b7f1c00-3450-11ea-98b3-6b895073dec0.png)

谢谢回答，删除时间这个字段是int类型而不是timestamp类型。已经通过改造软删除SoftDeletes实现。
