### ISSUE TITLE
laravel-admin 1.7.8 无法添加菜单但是不报错 只是301重定向到当前页

### ISSUE THREAD

**Issue by DreamSeekerKaiser** [z-song/laravel-admin#4313]
Laravel Version: 5.5.*
PHP Version:7.3
Laravel-admin: 1.7.8

Description:
一台电脑正常 一台电脑
添加menu菜单提交后当前页面刷新了一下，但无任何改变，也没有任何错误提示，也没有成功新增到菜单。我已填完所有可填的内容（包括权限），但仍没有效。
（已执行过php artisan view:clear）
 已经打开DEBUG 但是没有任何错误提示
查看控制台Network，发现是请求了
https://www.xxx.com/admin/auth/menu
但返回的是当前页面的html代码。

请问这是什么问题？谢谢

Steps To Reproduce:
如描述。

**Comment by z-song** [comment]
重现不了你的问题

**Comment by running8gubin** [comment]
我也遇到这个问题。直接在数据库中添加了菜单。

**Comment by smartymoon** [comment]
我也遇到了这个问题，只是冲定向到当前页面，没有提示

**Comment by imydou** [comment]
你看下控制台，是不是表单页面是https，添加请求的确实http？

**Comment by imydou** [comment]
我看了源代码

admin_url 函数读取了 config/admin.php 的 https，也就是 .env 的 ADMIN_HTTPS
