### ISSUE TITLE
自动登录Auth::login在laravel-admin中应该怎么写？

### ISSUE THREAD

**Issue by datangkang123** [z-song/laravel-admin#4314]
- Laravel Version: 6.9
- PHP Version:7.3
- Laravel-admin: 1.7.9

### Description:
在laravel中，使用模型获取用户后，可以直接使用Auth:login($user)来登录，在laravel-admin中应该怎样才能登录呢？例：
$user = AdminUserModel::where('id', $id)->first();
Auth:login($user);
这样就自动登录了，但laravel-admin中无法使用。
$this->guard()->attempt($user, false);
报错：attempt() must be of the type array, object given，将其转array也一样报错。

**Comment by z-song** [comment]
```php
use Encore\Admin\Facades\Admin;

// 用户名密码登陆
Admin::guard()->attempt([
    'username' => 'xxx',
    'password'  => 'xxx'
]);

// 或者用户模型登陆
$user = AdminUserModel::where('id', $id)->first();
Admin::guard()->login($user);
```
