### ISSUE TITLE
Did anyone tried disabling pjax in laravel-admin, and had problem?

### ISSUE THREAD

**Issue by hanachan1026** [z-song/laravel-admin#4315]
- Laravel Version: 5.8.*
- PHP Version: 7.3.*
- Laravel-admin: 1.7.7

### Description:

I'm thinking of disabling pjax but it's in the middle of development. So if anyone have experience disabling pjax and if you know any degrade happens I would like to know. Thank you.

**Comment by vlados** [comment]
I want to ask you why? Pjax is making your admin more faster. Why you want to disable this?

**Comment by seekstris** [comment]
@vlados to enable the external JS?

**Comment by uacode** [comment]
Admin::disablePjax();

**Comment by alihastam** [comment]
`Admin::disablePjax(); in bootstap.php`
