### ISSUE TITLE
Disabled field does not submit value

### ISSUE THREAD

**Issue by Bluefitdev** [z-song/laravel-admin#4325]
- Laravel Version: 6.2.0
- PHP Version: 7.3.1
- Laravel-admin: 1.7

### Description:
I want to submit the userID of the one who submitted the form... Thus I can't let them update the UserID field, but I can't seem to submit the value with it if its disabled / displayed

### Steps To Reproduce:
at form()

tried

`$form->text('bf_user_id', __('Bf User'))->value($userID)->disable();`

`$form->display('bf_user_id', __('Bf User'))->value($userID);`

**Comment by zaku33** [comment]
$form->display() only show the result , not request when you submitted 

> Only display the fields and without any action:
[https://laravel-admin.org/docs/#/en/model-form-fields?id=display-field](url)

disable is the same if I ain't wrong ✌️

**Comment by Bluefitdev** [comment]
yeah i end up using hidden inputs.. should be fine now
