### ISSUE TITLE
自定义操作中，form()中radio显示异常

### ISSUE THREAD

**Issue by he5127** [z-song/laravel-admin#4328]
- Laravel Version: 5.8.#
- PHP Version:
- Laravel-admin: 1.7.#

### Description:
自定义操作中，form()中$this->radio(),单选按钮变成下面的样子，是什么原因
![image](https://user-images.githubusercontent.com/39181590/72513733-63d78d80-3888-11ea-8c7c-f557795b8d54.png)
![image](https://user-images.githubusercontent.com/39181590/72513786-7e116b80-3888-11ea-987a-ef0c22e17e5c.png)

**Comment by z-song** [comment]
这个问题应该已经修复了，你更新到最新的版本试试看吧

**Comment by he5127** [comment]
我发现，只要筛选和这个表单字段同名，就会出现这个问题
