### ISSUE TITLE
Redirect to different page after logged out.

### ISSUE THREAD

**Issue by eine91** [z-song/laravel-admin#4329]
- Laravel Version: 5.8.*
- PHP Version: 7.2
- Laravel-admin: 1.6.3

### Description:

I have **user_type** column in **admin_users** table for various type of users.

I want if **user_type = 'ABC'** to be redirected to **'/'** after he/she logs out and others to default one viz. **'/admin'**.

I have overridden logout method:

```
public function getLogout(Request $request)
    { 
        $userType = \Admin::user()->user_type;logger('User: '.$userType);

        $this->guard()->logout();

        $request->session()->invalidate();

        if ( $userType == 'ABC' ) {
            
            return redirect('/');
        }

        return redirect(config('admin.route.prefix'));
    }
```

When I try to log out getting below error:

**Trying to get property 'user_type' of non-object**

This might be due to its getting called twice.

Any one know what I can do here?

### Steps To Reproduce:

Just try to override **getLogout** method from **Encore\Admin\Controllers\AuthController**

In this method put some condition like above in my code & logout.

**Comment by lbsfei** [comment]
upgrade laravel-admin.
