### ISSUE TITLE
editable works only with defined form

### ISSUE THREAD

**Issue by mp43819** [z-song/laravel-admin#433]
Hello, 

why editable works only if we have defined all fields in form()

```
 protected function grid()
    {
        return Admin::grid(UplinkchannelsModel::class, function (Grid $grid) {
      
			$grid->Name()->sortable()->editable();
	        });
    }

```

```
  protected function form()
    {
        return Admin::form(UplinkchannelsModel::class, function (Form $form) {
$form->text('Name','Name')->rules('required');
    });
    }
```

e.g. first I decided to make editable field and with every editing nothing was saved to database, then I decided to add form field to be able to "edit" with action button, after that "editable" started to work normally as usual...

can you please check? 

thank you!

**Comment by z-song** [comment]
The resource controller uses form to handle data saving.

**Comment by JefferyWong** [comment]
Wish you can point out that in doc, I got this problem solved until I find this post.
