### ISSUE TITLE
CSRF exception when developing custom field

### ISSUE THREAD

**Issue by Bluefitdev** [z-song/laravel-admin#4331]
- Laravel Version: 6.2
- PHP Version: 7.2
- Laravel-admin: 1.7

### Description:

I created a custom signature field with popular SignaturePad package, the data got converted into image successfully. However when I tried to submit the form I've got an error saying CSRF token miss match. Here's my code for rendering SignaturePad class

```
    public function render()
    {

        $this->script = <<<EOT


        var canvas = document.getElementById('signature-pad');

        // Adjust canvas coordinate space taking into account pixel ratio,
        // to make it look crisp on mobile devices.
        // This also causes canvas to be cleared.
        function resizeCanvas() {
            // When zoomed out to less than 100%, for some very strange reason,
            // some browsers report devicePixelRatio as less than 1
            // and only part of the canvas is cleared then.
            var ratio = Math.max(window.devicePixelRatio || 1, 1);
            canvas.width = canvas.offsetWidth * ratio;
            canvas.height = canvas.offsetHeight * ratio;
            canvas.getContext("2d").scale(ratio, ratio);
        }

        window.onresize = resizeCanvas;
        resizeCanvas();

        var signaturePad = new SignaturePad(canvas, {
            backgroundColor: 'rgb(255, 255, 255)' // necessary for saving image as JPEG; can be removed is only saving as PNG or SVG
        });


        $('button[type="submit"]').click(function() {
            console.log(signaturePad.toDataURL());
            $('input[type=hidden]').val(signaturePad.toDataURL());
        });


        EOT;
        return parent::render();
    }
```

If I remove the line below then I won't get it, but obviously my data is not sent. The way it works is I converts the value of the image and put it to the hidden input field to be sent. Can anyone help?

```
        $('button[type="submit"]').click(function() {
            console.log(signaturePad.toDataURL());
            $('input[type=hidden]').val(signaturePad.toDataURL());
        });
```

Everything else seems fine... Console.log shows my data as well converted to image, was gonna use the form callbacks to save image and path after. Can anyone that has experience in developing plugin helps?

Thanks

**Comment by z-song** [comment]
The form has a hidden field by default to store the `csrf token`, which is used to check the validity of the request when the form is submitted. Your `$ ('input[type = hidden]').val(signaturePad.toDataUR ()); ` overridden this hidden field

You'd better add a hidden field, and then fill the value to it

in form
```php
$form->hidden('signaturePad');
```

In your script:

```php
$('button[type="submit"]').click(function() {
    console.log(signaturePad.toDataURL());
    $('input[name=signaturePad]').val(signaturePad.toDataURL());
});
```

**Comment by Bluefitdev** [comment]
OMG I forgot...

Thankyou! 

It's almost finalised now i just need to save the photo and save the path

**Comment by nasimbahar** [comment]
@Bluefitdev  I need this custom field for the Laravel admin, Can you share the full source code.
