### ISSUE TITLE
左侧菜单过长的使用体验

### ISSUE THREAD

**Issue by Cuifc** [z-song/laravel-admin#4337]
- Laravel Version: 6.0
- PHP Version: 7.3
- Laravel-admin: 1.7.9

### Description:
左侧菜单在很长时，要选择下面的菜单，滚动鼠标，整个页面会跟着滚动，影响使用，所以左侧菜单边栏能不能做成独立滚动的，滚动左侧菜单栏不影响右侧主页面。谢谢！

**Comment by parse-dinghua** [comment]
试一下在 `config/admin.php` 里的 `layout` 里加上 `fixed`
![image](https://user-images.githubusercontent.com/54979620/73129386-4c816880-401d-11ea-8ff0-3a45bec8c311.png)

**Comment by Cuifc** [comment]
> 试一下在 `config/admin.php` 里的 `layout` 里加上 `fixed`
> ![image](https://user-images.githubusercontent.com/54979620/73129386-4c816880-401d-11ea-8ff0-3a45bec8c311.png)

非常感谢！
