### ISSUE TITLE
模型表格排序sortable()方法，只针对唯一数值排序，分页显示正确吗？

### ISSUE THREAD

**Issue by 1007894070** [z-song/laravel-admin#4346]
求教：模型表格排序sortable()方法，只针对唯一数值排序，分页显示正确吗？
$grid->column('id', __('TTour.stock_list.id'))->sortable();
点击排序后数据正常
$grid->column('time', __('TTour.stock_list.id'))->sortable();
time字段有重复数据，点击排序后，不同的分页中出现相同的数据，相同的id。
![image](https://user-images.githubusercontent.com/43439755/73535327-a5f6f680-4466-11ea-872c-0f8fde78fc8b.png)
![image](https://user-images.githubusercontent.com/43439755/73535359-b60ed600-4466-11ea-95de-1f3f5c5f1191.png)

**Comment by woodzeng** [comment]
同样的问题，这个怎么解决呀

**Comment by woodzeng** [comment]
解决了，笨办法在前面通过判断再排序一下
```
$grid->model()->when(request('_sort')['column'] === 'nums', function ($query) {
                return $query->orderByRaw('nums ' . request('_sort')['type'] . ', created_at_time');
            });
```
