### ISSUE TITLE
if one page will be have multy Grid with different model  in method ->display()  column has incorrect model in $this 

### ISSUE THREAD

**Issue by OnePeople** [z-song/laravel-admin#4358]
- Laravel Version: 5.5
- PHP Version: "php": "7.1.0"
- Laravel-admin: 1.7.7

### Description:
if one page will be have multy Grid with different model

in method ->display()  column has incorrect model in $this 

```
function grid1(){
Admin::grid(
  (1.1)              Model1::class,
                function (Grid $grid)  {

****
$grid->someColumn('label column')->display(
                        function ($valueColumn) {
// correct $this
                        }
                    ) ;

}
****

function grid2(){
Admin::grid(
  (1.2)              Model2::class,
                function (Grid $grid)  {
 .....
 ***
$grid->someColumn('label column')->display(
                        function ($valueColumn) {
(2)                         // incorrect $this   dd($this);
                        }
                    ) ;
}
```
$this - has incorrect Model (Model1), but has correct attributes

may be problem in singleton

in class \Encore\Admin\Grid\Column
      **!!!!always one and the same model for all Grids on one page**
   
  ```
  public function setModel($model)
    {
   
        if (is_null(static::$model) && ($model instanceof Model)) {
            static::$model = $model->newInstance();
        }
    }
```
  App::forgetInstance(Admin::class);
        App::forgetInstance(\Encore\Admin\Grid::class);
        App::forgetInstance(\Encore\Admin\Grid\Model::class);
        App::forgetInstance(\Encore\Admin\Grid\Column::class);  

This solution not working.
Please answer how use many Grids with different model on one page,
or fixed this problem.
Thank you

**Comment by lilashih** [comment]
Try this.
```php
use Encore\Admin\Grid;

function grid1(){
    $grid = new Grid(new Model1);
    ...
    return $grid;
}

function grid2(){
    $grid = new Grid(new Model2);
    ...
    return $grid;
}
```

But I think the filer will be the problems when use two grids in the same page.
