### ISSUE TITLE
如何使用权限禁止用户删除模型？

### ISSUE THREAD

**Issue by loveyuxiao** [z-song/laravel-admin#4361]
- Laravel Version:6.8
- PHP Version:7.3
- Laravel-admin: 1.7.9
### Description:
我新建了一个权限，用来控制登陆用户是否可以删除模型，我如何利用这个权限来允许或禁止用户删除模型？
显示列表可以在index(包括create edit)里判断用户权限
public funtion index(){
  if (Admin::user()->cannot('list')){
       Permission::error();
  }
}
那么删除权限判断应该在哪里呢？

**Comment by z-song** [comment]
可以在模型的删除回调`deleting`事件中判断权限，也可以在grid中通过权限判断来隐藏删除按钮
