### ISSUE TITLE
Grid表格中如何显示模型中的统计数据？

### ISSUE THREAD

**Issue by unizhu** [z-song/laravel-admin#4363]
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-admin: 1.7.9

### Description:
模型中有个usersCount方法，是hasmany后返回的count数，但是在grid中调用
```php
$grid->column('usersCount', __('Total Users'));
```
显示不了。

有什么办法吗？

**Comment by lilashih** [comment]
試試mutator
https://laravel.com/docs/7.x/eloquent-mutators
https://laravel.com/docs/7.x/eloquent-serialization#appending-values-to-json


```php
class Example extends Model
{
    protected $appends = ['users_count'];
    public function getUsersCountAttribute()
    {
        return ....;
    }
}
```

```php
$grid->column('users_count', __('Total Users'));
```
