### ISSUE TITLE
Problem with multipleImages

### ISSUE THREAD

**Issue by Nadioca** [z-song/laravel-admin#4364]
- Laravel Version: 6.*
- PHP Version: 7.3
- Laravel-admin: 1.7.9

### Description:

I'm doing a multiple lang form with tabs:

    protected function form($en = null)
    {
        $form = new Form(new Portada());

        $form->tab('Español', function (Form $form) {

            $form->text('id')->disable();

            $form->multipleImage('banner')->removable()-> sortable();
            
            $form->text('title');
            $form->ckeditor('content');
        })->tab('Inglés', function (Form $form) {
           
        });

        return $form;
    }

### Steps To Reproduce:

At first it works, but if you upload multiple images and enter enter to edit form, it returns this error:

" ViewException In MultipleFile.php line 189 :
  array_map(): Expected parameter 2 to be an array, string given (View: C:\xampp\htdocs\webadmin\vendor\encore\laravel-admin\resources\views\form.blade.php)"

Can you help me?

###sorry for my bad english

**Comment by Nadioca** [comment]
Solved with some functions in model

public function getBannerAttribute($banner)
    {
        if (is_string($banner)) {
            return json_decode($banner, true);
        }

        return $banner;
    }

    public function setBannerAttribute($banner)
    {
        if (is_array($banner)) {
            $this->attributes['banner'] = json_encode($banner);
        }
    }

**Comment by igorhaf** [comment]
thanks
