### ISSUE TITLE
关于自定义表单的权限问题

### ISSUE THREAD

**Issue by Fo0tMan** [z-song/laravel-admin#4368]
- Laravel Version: 6.2.0
- PHP Version: 7.3
- Laravel-admin: 1.7.9

### Description:

当使用自定义表单的时候，需要给对应角色赋予_handle_form_ 路由权限才能提交表单，请问给予角色_handle_form_权限是否会造成该角色能够提交其它未有权限的表单去，官方的最佳实践也是这样做的吗

**Comment by z-song** [comment]
可以在表单类的handle方法中做权限判断

**Comment by Fo0tMan** [comment]
但是这样赋予了某个角色_handle_form_权限之后  意味着该角色所以的自定义表单都不受权限的影响了，只能通过在handle方法里面去做权限判断 这样感觉有点不太好
