### ISSUE TITLE
怎么隐藏批量删除

### ISSUE THREAD

**Issue by ajiader** [z-song/laravel-admin#437]
做了个网站的 站点设置功能  数据只有一条  只能修改不能删除 ，单个删除可以隐藏
但是没有找到哪里可以隐藏批量删除。

**Comment by z-song** [comment]
http://z-song.github.io/laravel-admin/#/zh/model-grid-custom-tools.md?id=%e6%89%b9%e9%87%8f%e6%93%8d%e4%bd%9c
