### ISSUE TITLE
Artisan command does not detect model names/namespace

### ISSUE THREAD

**Issue by Bluefitdev** [z-song/laravel-admin#4373]
- Laravel Version: 6.2
- PHP Version: 7.2
- Laravel-admin: 1.7

### Description:

Does not detect the model, says 

`Model does not exists !`

even after mentioning namespace

### Steps To Reproduce:

I'm using nwidart/laravel-modules to create different modules on my app.

let's say models are located at `Modules/Blog/Entities/Post`, 

`php artisan admin:make Post --model=Modules\PoolTest\Entities\Post` 
says Model does not exist

`php artisan admin:make PoolType --namespace=Modules\PoolTest\Entities --model=Post`

Goes the same as well

**Comment by DjKammu** [comment]
@Bluefitdev 
Please use 
php artisan admin:make Post --model=Modules\\PoolTest\\Entities\\Post

**Comment by robertwt7** [comment]
@DjKammu It doesn't work,

I tried to do it with `php artisan admin:make User --model=Modules\MyModule\Entities\User`

Says model does not exist
