### ISSUE TITLE
行内编辑成功后数据没有刷新的问题

### ISSUE THREAD

**Issue by yfh1995** [z-song/laravel-admin#4376]
- Laravel Version: 5.5。45
- PHP Version: 7.2
- Laravel-admin: 1.7.9

### Description:

使用grid行内编辑后，response返回{"status":true,"message":"\u66f4\u65b0\u6210\u529f !"}，数据库也更新成功了，但是页面一直停留在提交加载中的状态

**Comment by yfh1995** [comment]
console在报错：Uncaught TypeError: Cannot read property 'success' of undefined，这个是为什么呢？烦请教，@z-song

**Comment by ninjacn** [comment]
> console在报错：Uncaught TypeError: Cannot read property 'success' of undefined，应当是$.admin.toastr.success属性没有找到。这个是为什么呢？烦请教，@z-song

#4470 看下这个

**Comment by yfh1995** [comment]
> > console在报错：Uncaught TypeError: Cannot read property 'success' of undefined，应当是$.admin.toastr.success属性没有找到。这个是为什么呢？烦请教，@z-song
> 
> #4470 看下这个

先改着用了，十分感谢
