### ISSUE TITLE
Is there any way we can remove the delete link on tree view for parents if have any child?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#438]
![2017-02-19_2229](https://cloud.githubusercontent.com/assets/24757934/23138308/9acbe6cc-f774-11e6-92a8-7cf6df6a8820.png)

Is there any way we can remove this delete button from parents if have any child.

In this way we can only remove parents with zero child.

**Comment by z-song** [comment]
You can solve this problem by hook deleting event of Menu model.

Open `app/Providers/EventServiceProvider.php` in `boot()` method add:
```php
\Encore\Admin\Auth\Database\Menu::deleting(function ($menu) {
    if $menu has children {
        return false;
    }
});
```

**Comment by llxx-lord-xxll** [comment]
@z-song but the link doesn't go away. We need a solution to modify actions in treeview like grid.

**Comment by hoangnamitc** [comment]
My same issues :( plz
