### ISSUE TITLE
网站前端要加一个用户登录的功能

### ISSUE THREAD

**Issue by HewieWang** [z-song/laravel-admin#4380]
- Laravel Version: 5.5
- PHP Version:7.3.4
- Laravel-admin: 1.7.9

### Description:
网站前端要加一个用户登录的功能,对应自建的Users表,怎么能最快实现呢，想直接用admin的Auth，可以实现吗?

**Comment by moqiaoduo** [comment]
Laravel本身就有Auth组件，laravel-admin使用的是Laravel自带的组件，只不过用了自己的模型，注册了一个guard。建议看Laravel文档。
还有，issue并不是讨论这些的地方，主要是反馈问题。
