### ISSUE TITLE
 FatalThrowableError In UploadField.php line 340 

### ISSUE THREAD

**Issue by cirvor** [z-song/laravel-admin#4384]
- Laravel Version: ^6.0
- PHP Version: 7.2.27
- Laravel-admin: ^1.7

### Description:

Argument 1 passed to Encore\Admin\Form\Field\File::getStoreName() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, string given, called in vendor/encore/laravel-admin/src/Form/Field/Image.php on line 34

### Steps To Reproduce:
1.  add image in model-form
2. upload a image for the form
3. open the form again and don't select any image, just submit
<img width="1096" alt="WeChat5026e038f1f20d2f7bd6b09a44c7a1c1" src="https://user-images.githubusercontent.com/10767295/74834041-9aa43600-5355-11ea-8598-0274d6f70531.png">

**Comment by KrenZfer** [comment]
Hi,
i had the same problem, have you found the solution ?
please share with me, Thank you

**Comment by cirvor** [comment]
> Hi,
> i had the same problem, have you found the solution ?
> please share with me, Thank you

I made it by myself:
```php
$form->saving(function (Form $form) {
    $form->img = $form->img ? :'';
});
```
This is my code, I have set a default value to the img
When user does not select picture, this form item became the string type, and then  throw the  `FatalThrowableError`
So, I just remove this judgement

This is just my fault

**Comment by KrenZfer** [comment]
thank you for fast response, i found that i forgot that i have something just like that too,

thanks for the answer

**Comment by komarove** [comment]
The above code does not work if you use switch() or textarea() in the greed() / table() method, in general, everything that causes editing, because the photo will simply disappear. I suggest this crutch:
```
$form->saving(function (Form $form) {
     if($form->isEditing()){
         $form->img = $form->img ?: $form->model()->img;
     }
     else{
         $form->img = $form->img ?: '';
    }
});
```
