### ISSUE TITLE
表单有联动时,导致gird页面搜索自动联动.请问要怎么解决

### ISSUE THREAD

**Issue by yangforme** [z-song/laravel-admin#4388]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
如题:我在表单页面有一个联动
`        
        $form->select('s_id',__('站点'))->options(Station::all()->pluck('name','id'))->load('t_id','/api/getTeamPhone');
        $form->select('t_id', __('成员'))->options(function($id){
            if($id){
                $p = Teams::find($id)->s_id;
                $data =  Teams::where('s_id',$p)->get([ \DB::raw("CONCAT(name,'-',phone) as text"),'id']);
                return $data->pluck('text','id');
            }
        });`
这会导致gird页面的搜索也自动联动,请问要怎么规避这个操作
gird搜索如下:
`$filter->equal('s_id','站点')->select(Station::all()->pluck('name','id'));
                $filter->equal('t_id','成员')->select(Teams::get([ \DB::raw("CONCAT(name,'-',phone) as text"),'id'])->pluck('text','id'));`

**Comment by jqhph** [comment]
这样试试
```php
$grid->setName('xxx');
```
