### ISSUE TITLE
Spatie-translatable not working on create

### ISSUE THREAD

**Issue by Nadioca** [z-song/laravel-admin#4389]
- Laravel Version: 6.14.0
- PHP Version:  7.3.12
- Laravel-admin: 1.7.9

### Description:

When I create a new record, the form is not storing the translations. But it works when I edit a form.

### Steps To Reproduce:

**Model**

`<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Spatie\Translatable\HasTranslations;

class Officeextends Model
{
    //
    use HasTranslations;

    protected $fillable = [
        'name', 'content', 'island'
    ];

    public $translatable = ['name', 'content'];

    public function island()
    {
        return $this->belongsTo(Island::class);
    }
}
`

**Controller**

`protected function form()
    {

        $office = new Office();

        $form = new Form($office );
        
        $form->tab('Español', function (Form $form) {
            $form->text('name', __('Name'));
            $form->text('content->es', __('Content'));
        })->tab('Inglés', function (Form $form) {

            $form->text('content->en', __('Content'));
        })->tab('Alemán', function (Form $form) {

            $form->text('content->de', __('Content'));
        })->tab('Francés', function (Form $form) {
            $form->text('content->it', __('Content'));
        })->tab('Italiano', function (Form $form) {

            $form->text('content->fr', __('Content'));
        });

        return $form;
    }
`

Can you help me?

**Comment by Nadioca** [comment]
At first I solved it with a trick that I really dislike, but works

I added at first this:

`
            if ($form->isCreating()) {
                $form->hidden('content'); 
            }
`

**Comment by vlados** [comment]
@Nadioca I had the same problem. You can do it by adding in update and store methods:
```
        $form->saving(function (Form $form) {
            $form->model()->title = [
              "bg" => $form->input("title")["bg"],
              "en" => $form->input("title")["en"]
            ];
            $form->model()->html = [
                "bg" => $form->input("html")["bg"],
                "en" => $form->input("html")["en"]
            ];
        });
```
