### ISSUE TITLE
table组件字段为null时，报错  Invalid argument supplied for foreach()

### ISSUE THREAD

**Issue by moqiaoduo** [z-song/laravel-admin#4398]
- Laravel Version: 6.15.1
- PHP Version: 7.3.4
- Laravel-admin: 1.7.9

### Description:
报错信息
ViewException In Table.php line 54 :
  Invalid argument supplied for foreach() (View: C:\Project\PHP\Laravels\newidc\vendor\encore\laravel-admin\resources\views\form\tab.blade.php)
模型中对应字段已设置cast为json，数据库字段类型也为json

### Steps To Reproduce:
添加$form->table(...)，callback不为空
保存前无报错，保存后报错

**Comment by jsonlove-cc** [comment]
同求 怎么回事啊

**Comment by moqiaoduo** [comment]
> 同求 怎么回事啊

读取的时候没有考虑到null的情况吧，直接foreach就会报错
