### ISSUE TITLE
Set multiple default values in multiple select field.

### ISSUE THREAD

**Issue by rwmediaworks** [z-song/laravel-admin#4399]
- Laravel Version: 6.13
- PHP Version: 7.13
- Laravel-admin: 1.7.9

### Description:

I want to set multiple default values in multiple select field.

I tried below but no success:

`$form->multipleSelect('meal_code', __('Select meal'))->options(['1' => 'Room only', '2' => 'Half board', '3' => 'Full board'])->default(['1', '2']);`

Does any one have any idea?

### Steps To Reproduce:

Try to set above field in form method of controller.

**Comment by amirbagh75** [comment]
i have the same problem

**Comment by monika45** [comment]
Try this:
Admin::script("$('select.YourFieldName').val([1,2]);");

**Comment by djmax2010** [comment]
try this:
$form->multipleSelectTable('company_ids')
        ->from(ProductionCompanyTable::make(['id' => $form->getKey()]))
        ->value(function(){
            return '1,2,3'; 
        })
        ->options() {
            return [1 => 'optionA', 2 => 'optionB', 3 => 'optionC']; 
        }
    }
    return [];
});
