### ISSUE TITLE
升级后出错!!

### ISSUE THREAD

**Issue by qq447665722** [z-song/laravel-admin#44]
Updating encore/laravel-admin 1.3.x-dev (aa5ecfa => a2a5f6d)

php 5.6.16
laravel 5.3.15
![qq 20160930173256](https://cloud.githubusercontent.com/assets/14967427/18987373/f38c4ace-8733-11e6-98f4-b72ade6b5857.jpg)

路径:  http://localhost/admin/auth/users/create

Oops! Something went wrong.
 
In `4b652399b4089f7b955876f81f16ce9006e97948.php` line `12` : Undefined variable: options (View: C:\wamp64\www\laravelapp\laravel\vendor\encore\laravel-admin\views\form\multipleselect.blade.php) (View: C:\wamp64\www\laravelapp\laravel\vendor\encore\laravel-admin\views\form\multipleselect.blade.php)

**Comment by z-song** [comment]
@qq447665722 已经修复，请再更新一下

ps：没有在windows环境下测试过，可能会有些bug，欢迎反馈
