### ISSUE TITLE
1.4.1 and 1.4.x-dev both are broken 

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#440]
![2017-02-20_2303](https://cloud.githubusercontent.com/assets/24757934/23150391/15ae28fe-f7c1-11e6-8185-aa8ee8a74330.png)

Both are broken not working and give this error:
ReflectionException in Container.php line 681:
Class admin.bootstrap does not exist

**Comment by smuzammilali** [comment]
Never mind find the solution I have extends AdminServiceProvider to update some routes and change the admin model to App/User.

However I have one question, how can I update the admin routes?

**Comment by z-song** [comment]
You can overwrite admin routes in app/Admin/routes.php.
