### ISSUE TITLE
How to show serial Number on grid?

### ISSUE THREAD

**Issue by minhajoptimal** [z-song/laravel-admin#4400]
Laravel Version: 5.8
PHP Version: 7.2
Laravel-admin: 1.6

### Description:
On Laravel admin grid I need to put serial but it's not a field from database. It want it will work on pagination. suppose, there are 20 rows per page, when I am on second page the first row SL will be 21. I am using the code on grid.

### Steps To Reproduce:
$grid->column('id', 'SL');

**Comment by khairu-aqsara** [comment]
you need to add some code on `src/Grid.php` to produce that results, here is mine

```
    public function set_number($name, $label, $width=32){
        $this->rows(function(Grid\Row $row) use($name) {
            $page = $this->model()->eloquent()->firstItem();
            $row->column($name,$row->number + $page);
        });

        return $this->__call($name, array_filter([$label]));
    }
```

**Comment by minhajoptimal** [comment]
It's working. Thank you very much.

**Comment by khairu-aqsara** [comment]
You are welcome, hope this can be added to next release.
