### ISSUE TITLE
自动登录登陆不行？急急急急！！！！！！

### ISSUE THREAD

**Issue by jsonlove-cc** [z-song/laravel-admin#4402]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.7.6

$user = Administrator::find($id);
Admin::guard()->login($user);
return redirect('/admin/test');

我这样写了后，打印过登录状态是ok的，为什么还是会回到原来的登录界面呢？
Admin::guard()->check()这个打印显示true
上面那样难道不是登录ok？

重点：
以上代码我是在laravel框架里面写的控制器，并没有在laravel-admin控制器里面写。

我想的是在laravel控制器里面访问http://epcom/api/md这个地址，这里面有一点逻辑，其中$user = Administrator::find($id);
Admin::guard()->login($user);//登录
return redirect('/admin/test');//跳转的地址
就在这个方法里面，然而他每次都登陆好了，但是只能返回登录首页。

**Comment by ReggieCai31** [comment]
怎么解决的啊@jsonlove-cc
