### ISSUE TITLE
组件名称使用中文开头就不显示

### ISSUE THREAD

**Issue by evolution-ant** [z-song/laravel-admin#4420]
- Laravel Version: 5.5.45
- PHP Version: 7.1.23
- Laravel-admin: 1.7.9

### Description:
当我使用英文开头作为组件名称时,可以正常显示,纯中文时不可以显示,谢谢了,我对前端不太懂,是不是我的使用有问题
![image](https://user-images.githubusercontent.com/24502661/75870578-1ae29500-5e46-11ea-8267-41dddc73c324.png)
![image](https://user-images.githubusercontent.com/24502661/75870601-2a61de00-5e46-11ea-95cf-777e80f13eed.png)

**Comment by z-song** [comment]
不能用纯中文, 用下面的
```php
$form->url('site', '域名');
```

**Comment by evolution-ant** [comment]
谢谢了 , 还是没好好看文档😄
