### ISSUE TITLE
v1.7.11 侧边栏布局, 功能出错, 部分 icon 不显示

### ISSUE THREAD

**Issue by Lweiis** [z-song/laravel-admin#4422]
- Laravel Version: 5.5.48
- PHP Version:7.3.1
- Laravel-admin: 1.7.11

### Description:
1. 侧边栏布局出错:
侧边栏在收缩状态下, 鼠标移至图标上方无法弹出显示折叠菜单
2. 用于收缩侧边栏的按钮图标无法正常显示
3. vendor 中替换为 1.7.9 则恢复正常

**Comment by mcwz** [comment]
我也遇到了相同的问题，今天 composer update 看已经更新到了1.7.12，以为修复了，刷新了看还是这样子。

**Comment by fangmuke** [comment]
受影响的版本只有1.7.10，更新到1.7.11即可。
更新后需要强制更新资源文件，如果压缩了CSS和JS则需要重新压缩。

**Comment by mcwz** [comment]
已经更新了 1.7.11
刚刚使用
`php artisan vendor:publish --provider="Encore\Admin\AdminServiceProvider" --force`
`php artisan vendor:publish --tag=laravel-admin-assets --force`
发布了资源文件
用于收缩侧边栏的按钮图标**已经正常显示**
**但是**侧边栏在收缩状态下, 鼠标移至图标上方仍然无法弹出显示折叠菜单

**Comment by Lweiis** [comment]
^1.7.11 是 support for Laravel 7 的, 使用 Laravel LTS 5.5, 6.0 的朋友指定 1.7.9 就好

**Comment by fangmuke** [comment]
> ^1.7.11 是 support for Laravel 7 的, 使用 Laravel LTS 5.5, 6.0 的朋友指定 1.7.9 就好

从commits看1.7.11是还原了对FA的升级及支持Laravel 7.x

**Comment by Lweiis** [comment]
谢谢提醒, 我倒没细看, 下次注意

**Comment by Lweiis** [comment]
> > ^1.7.11 是 support for Laravel 7 的, 使用 Laravel LTS 5.5, 6.0 的朋友指定 1.7.9 就好
> 
> 从commits看1.7.11是还原了对FA的升级及支持Laravel 7.x

谢谢提醒, 是我没细看, 下次注意
