### ISSUE TITLE
hasmany中嵌套$form->list('list'),更新时，关联模型的list字段（json）为空

### ISSUE THREAD

**Issue by WangQuanTang** [z-song/laravel-admin#4424]
- Laravel Version: 6.2
- PHP 7.2:
- Laravel-admin: v1.7.9

Description:
A模型和B模型进行一对多关联，关联方法为details，hasmany的代码如下：
`$form->hasMany('details','详情内容', function (Form\NestedForm $form) {
	
	  $form->select('type','类型')->options([0 => 'A类',1 => 'B类',2 => 'C类']);
	  $form->text('remark','备注');

	  $form->list('content','内容');
	});`
在B模型中，content字段也在$cats中指定为json。

Steps To Reproduce:
更新/新增操作后：

1. 除为json字段的“content”为空以外，其余字段，包括关联的id字段均有数据；

2. 保存回调中查看数据，无content内容，查询操作日志，打印出来的数据为：
`
{
    "name":"测试项目1",
    "tags":[
        "1",
        null
    ],
    "attrs":{
        "title":"测试项目1",
        "price":"10000",
        "area":"8000.1",
        "green":"30%",
        "address":"测试地址",
        "location":"111,2234"
    },
    "show_details":"on",
    "details":{
        "1":{
            "type":"0",
            "remark":"asdas",
            "id":"1",
            "_remove_":"0"
        }
    },
    "content":{
        "values":[
            "楼盘名称：测试楼盘"
        ]
    },
    "show_vr":"off",
    "vr":{
        "title":null,
        "url":null
    }
}
`
可以看到details里面无content内容，content的数组和details同级，尝试过[这个方法](https://github.com/z-song/laravel-admin/issues/899)中对于$form->hasMany和$form->table的方法，对于list无效，也尝试过重新实现Encore\Admin\Form\Field\ListField，均不起作用！

**Comment by leilidi2016** [comment]
我也遇到这个问题，临时修改了暂时用先，希望尽快修复。
（list,keyValue均无法在hasMany下正常使用）。
修改 src/Form/Field/ListField.php    setupScript方法
 $this->script = <<<SCRIPT
$('.{$this->column}-add').on('click', function () {
    var parent = $(this).closest('.has-many-fields-form');
    if (parent) {
        var tpl = parent.find('.{$this->column}-tpl').html();
        parent.find('tbody.list-{$this->column}-table').append(tpl);
    } else {
        var tpl = $('template.{$this->column}-tpl').html();
        $('tbody.list-{$this->column}-table').append(tpl);
    }
});
$('tbody').on('click', '.{$this->column}-remove', function () {
    $(this).closest('tr').remove();
});
SCRIPT;
resources/views/form/listfield.blade.php 修改两处 <input name="{{ $column }}[values][]"
为
<input name="{{ $name }}[values][]"

keyValue基本也一样

**Comment by WangQuanTang** [comment]
> 我也遇到这个问题，临时修改了暂时用先，希望尽快修复。
> （list,keyValue均无法在hasMany下正常使用）。
> 修改 src/Form/Field/ListField.php setupScript方法
> $this->script = <<<SCRIPT
> $('.{$this->column}-add').on('click', function () {
> var parent = $(this).closest('.has-many-fields-form');
> if (parent) {
> var tpl = parent.find('.{$this->column}-tpl').html();
> parent.find('tbody.list-{$this->column}-table').append(tpl);
> } else {
> var tpl = $('template.{$this->column}-tpl').html();
> $('tbody.list-{$this->column}-table').append(tpl);
> }
> });
> $('tbody').on('click', '.{$this->column}-remove', function () {
> $(this).closest('tr').remove();
> });
> SCRIPT;
> resources/views/form/listfield.blade.php 修改两处 <input name="{{ $column }}[values][]"
> 为
> <input name="{{ $name }}[values][]"
> 
> keyValue基本也一样

感谢老铁，现在去试试！
