### ISSUE TITLE
是否计划分页加入“首页”、“尾页”功能

### ISSUE THREAD

**Issue by hulkwan** [z-song/laravel-admin#443]
是否计划分页加入“首页”、“尾页”功能

**Comment by z-song** [comment]
![qq20170222-0](https://cloud.githubusercontent.com/assets/1479100/23193648/055dc70a-f8e5-11e6-8733-7c0bdd0ab544.png)

已经有首尾页了

**Comment by hulkwan** [comment]
ok，感谢
