### ISSUE TITLE
表单选项卡bug

### ISSUE THREAD

**Issue by tingfeng-key** [z-song/laravel-admin#4433]
- Laravel Version: 6.2
- PHP Version:7.4
- Laravel-admin: 1.7

### Description:
按照文档来的：https://laravel-admin.org/docs/zh/data-form#%E9%80%89%E9%A1%B9%E5%8D%A1%E8%A1%A8%E5%8D%95

报错如下：
![image](https://user-images.githubusercontent.com/13976521/76060461-530be400-5fbc-11ea-92cb-ad298432c297.png)

调试后可用：
![image](https://user-images.githubusercontent.com/13976521/76060811-1ee4f300-5fbd-11ea-9fe7-652d1ce6bbde.png)

将这个title方法改为title属性就正常

另外，希望Encore\Admin\Widgets\Form可以添加表单布局

**Comment by z-song** [comment]
5e56162f68bb176d9a76cbd1c793077a81b04608 在这里已经修复
