### ISSUE TITLE
I can see current picture on grid and detail page, but I cannot see it on form page in upload field

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4437]
- Laravel Version: 6.17.1
- PHP Version: 7.2.19
- Laravel-admin: 1.7

### Description:
I can see current picture on grid and detail page, but I cannot see it on form page.

Something wrong with the path, but I cannot catch where exactly.
On grid and detail page I have path like http://localhost/storage/img/news/imagename.jpg
![Снимок](https://user-images.githubusercontent.com/10367464/76151901-bedc7280-60ca-11ea-887f-95c28639e77c.JPG)

BUT
On form page I always have something like http://localhost/storage/imagename.jpg
![71370540-408a2d00-25bf-11ea-9e25-65478ec94020](https://user-images.githubusercontent.com/10367464/76151806-00205280-60ca-11ea-9a15-7e556aaad946.jpg)

### Steps To Reproduce:
pictures located in storage\app\public\img\news

```
function grid()
{
        $grid->column('image', 'Изображение')->display(function ($name) {
            return "img/news/$name";
            })->lightbox();
}

function detail($id)
{
        $show->field('image', 'Изображение')->as(function ($name) {
            return "img/news/$name";
            })->image();
}

function form()
{
        $form->image('image', 'Изображение')->move('public/img/news');
}
```

**config/admin.php**
```
    'upload' => [
        'disk' => 'admin',
        'directory' => [
            'image' => '', 
            'file'  => 'files',
        ],
    ],
```
**config/filesystems.php**
```
        'admin' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => env('APP_URL').'/storage',
        ],
```

When I select new picture from my PC it is copied to localhost\storage\app\public\img\news
But anyway when I open post to edit again I don't see this picture on the page in upload field

**Comment by z-song** [comment]
Modify  `admin.url` to `env('APP_URL').'/storage/img/news/'`, in config/filesystems.php.

**Comment by schel4ok** [comment]
It doesn't help
```
    'disks' => [

        'admin' => [
            'driver' => 'local',
            'root' => storage_path('app'),
            'url' => env('APP_URL').'/storage/img/news/',
        ],
```
Anyway on form page in upload field I still have something like http://localhost/storage/imagename.jpg

**Comment by z-song** [comment]
I think the better way is to set an accessor for this `image` field in your model and let this field return full url, like this:

```php
use Illuminate\Support\Facades\Storage;

    public function getImageAttribute($image)
    {
        if (url()->isValidUrl($image)) {
            return $avatar;
        }

        return Storage::disk('admin')->url($avatar);
    }
```

**Comment by schel4ok** [comment]
this works, thanks
```
	public function getImageAttribute($image)
	{
	    return Storage::disk('admin')->url('img/news/'.$image);
	}
```
But it doesn't work with `Storage::disk('public')`.

I don't have enough knowledge about Laravel Storage system, but I supposed that `admin` disk should be used only for admin section, whereas `public` is for web routes.

I wanted to use `Storage::disk('public')->url('img/news/'.$image);` in order to use it in my website layout also.
But with public disk I have `http://localhost/storage/storage/img/news/imagename.jpg` in admin website section.

**Comment by schel4ok** [comment]
I found one more bug with Laravel 7
- Laravel Version: 7.2.0
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description
Picture path contains `localhost` exactly like that http://localhost/storage/img/news/imagename.jpg.
Though I have `APP_URL=http://mysite.test` and I expect to see http://mysite.test/storage/img/news/imagename.jpg.
