### ISSUE TITLE
input number type max / 输入框存在最大数字问题

### ISSUE THREAD

**Issue by puzzle9** [z-song/laravel-admin#4439]
- Laravel Version: 7.0
- PHP Version: 7.4
- Laravel-admin: 1.7.13

### Description:

```php
$form->number('day', 'day')->default(1)->min(1)->max(255)->required();
```

当 输入 `2`开头的数字时正常 输入 `3` 开头的数字会直接变成 `255`

如果把 `max` 改成 `300` 则 输入 `4` 开头的数字会直接变成 `300`

```
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
```

**Comment by Cuifc** [comment]
> * Laravel Version: 7.0
> * PHP Version: 7.4
> * Laravel-admin: 1.7.13
> 
> ### Description:
> ```
> $form->number('day', 'day')->default(1)->min(1)->max(255)->required();
> ```
> 
> 当 输入 `2`开头的数字时正常 输入 `3` 开头的数字会直接变成 `255`
> 
> 如果把 `max` 改成 `300` 则 输入 `4` 开头的数字会直接变成 `300`
> 
> ```
> User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/80.0.3987.122 Safari/537.36
> ```

min 限制也会有相同的问题
