### ISSUE TITLE
建议控制器 form 方法默认传 id

### ISSUE THREAD

**Issue by Hanson** [z-song/laravel-admin#4442]
很多时候的操作都需要在 form 里面根据 id 做些操作等，因为编辑模式的 id 是在 `->edit($id)` 才传参，form 里面的操作会不友好。

目前我都是通过重写覆盖去实现，但其实 form 可以接收一个可为 null 的 $id 参数

**Comment by picasso250** [comment]
我也有同样的问题，但我并没找到加id的方法，请楼上告知。

**Comment by Hanson** [comment]
@picasso250 我是覆盖了 edit 和 create 方法实现的
