### ISSUE TITLE
$form->select和multipleSelect不走ajax设置的url加载数据

### ISSUE THREAD

**Issue by Yesr00** [z-song/laravel-admin#4447]
- Laravel Version: 5.5.48
- PHP Version: 7.2.20
- Laravel-admin: 1.7.7

### Description:
$form->select()->options()->ajax();
$form->multipleSelect()->options()->ajax();
不加ajax正常。加Ajax就没数据。。。从控制台可以看到没有走ajax里的url,

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/47804568/76397860-d3648780-63b6-11ea-8726-85e9829ee413.png)
![image](https://user-images.githubusercontent.com/47804568/76398069-30603d80-63b7-11ea-8674-45b2cd3f7bd5.png)

该行代码如下，请大佬指导！
`$form->multipleSelect('pco_id', __('联系人'))->options(function($pco_id){
            return ProjectContactor::all()->pluck('pco_id as id','pco_name as text');
        })->ajax('/admin/contactor_load');

`

**Comment by Yesr00** [comment]
![image](https://user-images.githubusercontent.com/47804568/76398385-bed4bf00-63b7-11ea-9082-c166c2db3873.png)
接口代码如图

**Comment by Yesr00** [comment]
Emmmm...我的问题。用了select2插件导致。

**Comment by AloneMrcao** [comment]
您好  我也遇到了这个问题 请问您是怎么解决的呢

**Comment by AloneMrcao** [comment]
> Emmmm...我的问题。用了select2插件导致。

您好 我也遇到了这个问题 请问您是怎么解决的呢

**Comment by gg22mm** [comment]
靠，我也是这样，这是bug吗

**Comment by Yesr00** [comment]
不用ajax,用match吧。。。

**Comment by Yesr00** [comment]
`$form->multipleSelect('pco_id','联系人')->match(function ($keyword) {
            return Model::where('key', 'LIKE', '%' . $keyword . '%')
                ->select([DB::raw('name AS text'), id])
                ->latest();
        })->text(function ($column) {
            return Model::whereIn('id', $column)->pluck('name AS text','id');
        })`
