### ISSUE TITLE
希望可以在模型表单跟表格中增加删除列，删除字段的方法，这样继承的控制器可以更灵活的控制页面内容

### ISSUE THREAD

**Issue by kaodouqifei** [z-song/laravel-admin#4469]
- Laravel Version: 5.5
- PHP Version:7.0
- Laravel-admin: 1.7

### Description:
我想要控制器复用，有些字段不用重新写，但是有些字段又有区别，希望继承的控制器中的字段可以覆盖父类的字段，或者可以删除父类添加的字段

`class DemandSaleController extends DemandController
{
    protected function grid() {
        $grid = parent::grid();
//        $grid->disableCreateButton();
        $grid->column('product_name', __('Product name'));
        return $grid;
    }

    protected function form() {
        $form = parent::form();
        $form->unsetInput('product_name');

        return $form;

    }

}`

**Comment by xx10n31y** [comment]
别想着提issue了...基本都是wontfix,或者被bot自动关闭的...
