### ISSUE TITLE
提交的时候 关于 字段冲突  样式改变或者输入 

### ISSUE THREAD

**Issue by 14718011108** [z-song/laravel-admin#447]
$form->text('content','回复内容');   提交的 content 字段   样式会变成很大， 改成content1或者别的就不会    这有什么解决方法吗？   label字段也会

**Comment by z-song** [comment]
截图？？

**Comment by 14718011108** [comment]
![Uploading image.png…]()

**Comment by 14718011108** [comment]
![qq 20170222160316](https://cloud.githubusercontent.com/assets/24646165/23202556/69ec1abc-f919-11e6-8e16-412c88bf86a2.png)
![qq 20170222155218](https://cloud.githubusercontent.com/assets/24646165/23202561/6e493e28-f919-11e6-823a-23c063e4a344.png)

**Comment by z-song** [comment]
确实有这个问题

**Comment by 14718011108** [comment]
![qq 20170222161959](https://cloud.githubusercontent.com/assets/24646165/23202814/cbb361f0-f91a-11e6-9cee-98dfac5962cb.png)
我试过这样 但是 也有点问题，  并没什么用

**Comment by z-song** [comment]
label 和 content 字段会和系统的css样式冲突

你先暂时用`$form->text('content')->attribute('class', 'form-control');`解决一下

**Comment by 14718011108** [comment]
![xt 0cyjnmcexor 5dj0 5o](https://cloud.githubusercontent.com/assets/24646165/23203119/10c105f8-f91c-11e6-96b1-d8d0ebc2c669.png)
![f0ttc eoz mtr9cpa9_3vyq](https://cloud.githubusercontent.com/assets/24646165/23203124/1692c6c4-f91c-11e6-83c9-07481f77f233.png)
这个没有默认值 是怎么回事呢  ？   没有存进去

**Comment by edwinhuish** [comment]
@14718011108 这个是基础。 SQL的字段没有设置默认值。

**Comment by fsf11080612** [comment]
我进入页面显示的时候 可以的  但是提交的时候就不可以
因为 要把获取到的值写进  给一个 hidden   给一个不提交  就能使用了

**Comment by fsf11080612** [comment]
例子里面的      多级联动看不到了  能不能修复一下

**Comment by 14718011108** [comment]
@edwinhuish

**Comment by edwinhuish** [comment]
@14718011108 ?????

@fsf11080612 demo站的多级联动貌似确实是挂了。。

**Comment by 14718011108** [comment]
都是我  同一个人  @edwinhuish
