### ISSUE TITLE
filter不支持integer类型？

### ISSUE THREAD

**Issue by guilinli001** [z-song/laravel-admin#448]
filter不支持integer类型，请问如何解决？
$filter->is('type')->select([1 => '正常', 2 => '锁定', 3 => '测试中']);
mongodb中   "type": NumberInt(1),

尝试过model中的修改器，也不起作用
    protected $casts = [
        'type' => 'string',
    ];

**Comment by z-song** [comment]
mongodb的查询是区分类型的，你要手动转一下请求数据的类型

在grid方法最前面加上：
```php

if (request()->has('type')) {
    request()->merge(['type' => (int) request()->get('type')]);
}
```
