### ISSUE TITLE
submitted不能取form里的数据嘛？

### ISSUE THREAD

**Issue by Yesr00** [z-song/laravel-admin#4489]
- Laravel Version: 5.5.48
- PHP Version: 7.2.20
- Laravel-admin: 1.7.14

### Description:
$form->submitted(function(Form $form){
            dd($form->字段名)；
});
在submitted里获取不到任何的form字段。
现在的需求是要先取得form里某个字段的值，进行更新以后在保存前把这个字段给ignore掉。在submitted里$form->ignore生效。但是生效了我在saving里又取不到对应字段值了。。。submitted不能取form里的数据嘛？？？

**Comment by duolabmeng6** [comment]
请问一下如何解决 我也遇到了这个问题~
