### ISSUE TITLE
Driver [] is not supported.

### ISSUE THREAD

**Issue by MisterNemo** [z-song/laravel-admin#449]
InvalidArgumentException in FilesystemManager.php line 121:
Driver [] is not supported.

**Comment by z-song** [comment]
Which version do you use?

**Comment by MisterNemo** [comment]
5.3

**Comment by MisterNemo** [comment]
$form->image('image') don't work

**Comment by z-song** [comment]
You need to config the filesystem, specify a driver to handle file/image uplaod

see http://z-song.github.io/laravel-admin/#/en/model-form-upload.md?id=upload-to-local
