### ISSUE TITLE
表单的table组件添加富文本编辑器第二个不显示

### ISSUE THREAD

**Issue by ZhjGo** [z-song/laravel-admin#4495]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: 1.7

### Description:
table组件添加富文本的时候第一个可以显示，第二个显示不出来

### Steps To Reproduce:

$form->table('extra', function ($table) {
    $table->UEditor('key');
});

**Comment by zhaojilinsy** [comment]
这个问题解决了么？我也也到了这个问题

**Comment by lexingzai** [comment]
一对多添加的时候多个富文本只有一个显示正常，要是存在两个一对多关系的时候，富文本名称还不能相同，相同也会出bug
