### ISSUE TITLE
不能多个 $form->hasMany 吗？

### ISSUE THREAD

**Issue by JayChew** [z-song/laravel-admin#4497]
- Laravel Version: 5.7
- PHP Version: 7.2
- Laravel-admin: 1.7.2

### Description:
`
    public function prices()
	{
		return $this->hasMany(RoomPrice::class);
	}

    public function special_prices()
    {
        return $this->hasMany(RoomPriceSpecial::class);
    }
`

`
        $form->tab(__('Price'), function ($form) use ($id) {
            $form->hasMany('prices', __('Prices'), function ($form) {
                $form->hidden('merchant_id', __('admin-ap.merchant'))->value(Admin::user()->merchant_id)->default(Admin::user()->merchant_id)->readOnly();
                $form->select('day', __('Day'))->options(RoomPrice::optionInDays())->rules('required');
                $form->select('member_type_id', __('Member Type'))->options(Admin::user()->merchant->member_types->pluck('name', 'id'));
                $form->time('time_start', __('Time start'))->format('HH:mm:ss')->rules('required');
                $form->time('time_end', __('Time end'))->format('HH:mm:ss')->rules('required');
                $form->currency('price', __('Price'))->symbol('');
            });
        });

        $form->tab(__('Special Price'), function ($form) use ($id) {
            $form->hasMany('special_prices', __('Special Prices'), function ($form) {
                $form->hidden('merchant_id', __('admin-ap.merchant'))->value(Admin::user()->merchant_id)->default(Admin::user()->merchant_id)->readOnly();
                $form->date('date_start', __('Start Date'))->format('YYYY-MM-DD')->rules('required');
                $form->select('member_type_id', __('Member Type'))->options(Admin::user()->merchant->member_types->pluck('name', 'id'));
                $form->time('time_start', __('Time start'))->format('HH:mm:ss')->rules('required');
                $form->time('time_end', __('Time end'))->format('HH:mm:ss')->rules('required');
                $form->currency('price', __('Price'))->symbol('');
            });
        });

`

却给我 Array to String conversion 错误

**Comment by lishuai199502** [comment]
大佬解决了没有，我也想这样搞
