### ISSUE TITLE
表单一对一 关联表重新赋值失败

### ISSUE THREAD

**Issue by yangforme** [z-song/laravel-admin#4498]
- Laravel Version:5.8
- PHP Version:7.3
- Laravel-admin: 1.7.8

### Description:
使用表单的一对一时,用户密码加密报错
`
模型内
    public function user(){
        $userModel = config('admin.database.users_model');
        return $this->belongsTo( $userModel,'admin_id');
    }
控制器内
        $form->text('user.name', __('名称'))->required();
        $form->text('user.username', __('用户名'));
        $form->password('user.password', __('密码'))->required();
        
        $form->saving(function (Form $form) {

                $form->user['password'] = bcrypt($form->user['password']);

            // }
        });
`
报错:
 ErrorException In BaseController.php line 106 :
  Indirect modification of overloaded property Encore\Admin\Form::$user has no effect

**Comment by Hoexhe** [comment]
你可以这样:

```php
$form->saving(function (Form $form) {
    $user = $form->user;
    $user['password'] = bcrypt($form->user['password']);
    $form->user = $user;
});
```
