### ISSUE TITLE
360浏览器删除功能不兼容

### ISSUE THREAD

**Issue by kaodouqifei** [z-song/laravel-admin#4503]
- Laravel Version: 5.5
- PHP Version:7.3
- Laravel-admin: 1.7.14

### Description:
360浏览器删除功能不兼容，点击删除后没有反应
js报错
SCRIPT5009: “Promise”未定义

**Comment by pannidezhuoyue** [comment]
自行加载promise.min.js就可以了,需要兼容IE浏览器
