### ISSUE TITLE
how to make custom modal for confirm delete action for any entity?

### ISSUE THREAD

**Issue by pysoftware** [z-song/laravel-admin#4509]
Need custom message in modal when confirm delete

**Comment by pysoftware** [comment]
![Capture](https://user-images.githubusercontent.com/42905793/78793113-cf506900-7966-11ea-8bfd-7882ddfa8296.JPG)
i meant those

**Comment by perniajd** [comment]
Hello, may be you need to view  the method **setupDeleteScript()** of the class  **Encore\Admin\Grid\Displayers\Actions**, it probably exist in your path  file:

     _vendor/encore/laravel-admin/src/Grid/Displayers/Actions.php_

**Comment by pysoftware** [comment]
![Capture](https://user-images.githubusercontent.com/42905793/78965067-d8e5e800-7ab0-11ea-8317-4e424edb91f2.JPG)
so i made it like this
and in controller
FOR FORM
$form->tools(function (Form\Tools $tools) {
           $tools->disableDelete();
           $tools->append(new DeleteButtonTool());
});
AND FOR SHOW
$show->panel()->tools(function (Show\Tools $tools) {
           $tools->disableDelete();
           $tools->append(new DeleteButtonTool());
});

**Comment by pysoftware** [comment]
also i have custom actions in grid 
![Capture](https://user-images.githubusercontent.com/42905793/78965582-4fcfb080-7ab2-11ea-8110-52e2765426c9.JPG)
![Capture](https://user-images.githubusercontent.com/42905793/78965609-5a8a4580-7ab2-11ea-9e81-75101a3c6a97.JPG)
and in bootstrap i wrote 
Encore\Admin\Grid\Column::define('__actions__', CustomActions::class);

**Comment by pysoftware** [comment]
P.S. Script the same in da DeleteButtonTool
