### ISSUE TITLE
No query results for model [App\Models\SmartQQ] index

### ISSUE THREAD

**Issue by yljphp** [z-song/laravel-admin#451]
我的laravel版本是 `laravel 5.4`

使用脚手架自动生成的控制器，模型，访问对应的url，提示下图
<img width="954" alt="qq20170223-101435 2x" src="https://cloud.githubusercontent.com/assets/8953279/23241893/f9e74bf4-f9b0-11e6-9122-b63c13b2f721.png">

**Comment by z-song** [comment]
贴你的路由配置和访问url

**Comment by yljphp** [comment]
页面是出来了`http://localhost/admin/smartqq`
之前的是url: `http://localhost/admin/smartqq/index`

**Comment by z-song** [comment]
你先去熟悉一下Laravel的resource路由设置和访问吧
