### ISSUE TITLE
多次302错误

### ISSUE THREAD

**Issue by dotcool** [z-song/laravel-admin#4515]
Laravel-admin version 1.6.10

你好，我升级laravel-admin到这个版本以后，出现修改用户信息的form表单，点击提交，发起多次post的302跳转。
![image](https://user-images.githubusercontent.com/6111056/79010146-ecb64a80-7b93-11ea-8bcc-b3568af205c3.png)
页面上的action是post
![image](https://user-images.githubusercontent.com/6111056/79010417-7c5bf900-7b94-11ea-9d51-332c1990c1ef.png)

当我点击提交的时候会出现两个302的跳转，这样导致了数据重复提交
![image](https://user-images.githubusercontent.com/6111056/79010243-29824180-7b94-11ea-9f84-669abe7c17e6.png)
![image](https://user-images.githubusercontent.com/6111056/79010260-34d56d00-7b94-11ea-8c24-bed35b33d4f0.png)
这两个302请求都是相同的数据，只是set-cookie: XSRF-TOKEN=eyJp****这个token值不一样
真的不太清楚怎么回事了，麻烦帮我看看，感谢

**Comment by baykier** [comment]
nginx 是不是强制https 了， 如果是这样 在config/admin.php 把ADMIN_HTTPS env 环境变量设为 true

**Comment by dotcool** [comment]
我这边的项目有2个后台，一个是admin一个是另外的代理商后台。错误发生在代理商后台的form提交，提交一次会出现2个post请求，一个是pjax另外一个不是。

**Comment by dotcool** [comment]
感谢 song大佬的指点

在1.6版本里面  Admin::js()也加载了laravel-admin.js，和下面的laravel-admin.js一起给form的提交按钮绑定了两次submit事件

**Comment by feivorid** [comment]
> 感谢 song大佬的指点
> 
> 在1.6版本里面 Admin::js()也加载了laravel-admin.js，和下面的laravel-admin.js一起给form的提交按钮绑定了两次submit事件

请问最后怎么解决的？ 我也遇到同样的问题了，没看懂你们说的这个 😂，请指点一下？
