### ISSUE TITLE
Install fail in second project with same step

### ISSUE THREAD

**Issue by chumicat** [z-song/laravel-admin#4516]
- Laravel Version: 7.3.13
- PHP Version: 7.4.4
- Laravel-admin: 1.7.14

### Description:
First project install is success.
Second project install is failed.
Error message is "Unable to locate publishable resources."
Difference between two project is that the first project have folder "public/vendor/laravel-admin" but the second one didn't after ```composer require encore/laravel-admin```, and this effect the following command ```php artisan vendor:publish --provider=Encore\Admin\AdminServiceProvider``` unable to find resources.

### Steps To Reproduce:
as official install steps.
```shell
composer require encore/laravel-admin
php artisan vendor:publish --provider=Encore\Admin\AdminServiceProvider
php artisan admin:install
```

**Comment by fredyzhang5532** [comment]
> * Laravel Version: 7.3.13
> * PHP Version: 7.4.4
> * Laravel-admin: 1.7.14
> 
> ### Description:
> First project install is success.
> Second project install is failed.
> Error message is "Unable to locate publishable resources."
> Difference between two project is that the first project have folder "public/vendor/laravel-admin" but the second one didn't after `composer require encore/laravel-admin`, and this effect the following command `php artisan vendor:publish --provider=Encore\Admin\AdminServiceProvider` unable to find resources.
> 
> ### Steps To Reproduce:
> as official install steps.
> 
> ```shell
> composer require encore/laravel-admin
> php artisan vendor:publish --provider=Encore\Admin\AdminServiceProvider
> php artisan admin:install
> ```

How to solve this problem？
