### ISSUE TITLE
关于   提交后的跳转

### ISSUE THREAD

**Issue by 14718011108** [z-song/laravel-admin#452]
$form   里面提交后 跳转 可以控制的吗？  可以自定义路由吗？

**Comment by z-song** [comment]
看文档。。。。

http://z-song.github.io/laravel-admin/#/zh/model-form-callback.md

**Comment by 14718011108** [comment]
禁用 表单里面的  列表按钮  要更新 什么文件吗？？    或者返回按钮

**Comment by z-song** [comment]
以后碰到没有的功能  就更新包

**Comment by 14718011108** [comment]
可以  ，，，麻烦了
