### ISSUE TITLE
batch download 。cannot work；

### ISSUE THREAD

**Issue by michelleyaoyao** [z-song/laravel-admin#4523]
- Laravel Version: 5.8
- PHP Version: 7.2
- Laravel-admin: 1.7

### Description: when I add the batch action 。 download cannot work
 $grid->batchActions(function ($batch) {
                $batch->add(new Download());
            });

then modify the handle function
         return response()->download($file, 'test.txt' ,$headers = ['Content-Type'=>'Content-type: application/octet-stream']);
   
it doesn't work。 then I chose other idea. it cannot work too please helpme 。 thanks

             header("Content-type: application/octet-stream");
            header('Location:'.asset($file));

**Comment by zaku33** [comment]
File csv work : 
 In Controller : (get method)
            header('Content-Description: File Transfer');
            header('Content-Type: application/octet-stream');
            header('Content-Disposition: attachment; filename="' . basename($file_name) . '"');
            header('Expires: 0');
            header('Cache-Control: must-revalidate');
            header('Pragma: public');
            header('Content-Length: ' . filesize($file_name));
            readfile($file_name);
            exit;
in blade :
windown.open(<url to Controller above>);
Test it with other file , hope this will work ✌️
