### ISSUE TITLE
Listbox not showing the values saved on DB on Many-to-Many relation 

### ISSUE THREAD

**Issue by perniajd** [z-song/laravel-admin#4529]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
Hi, i have the Models Car and Color in a many to many relation through the car_colors pivot table..

Model Car
```
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Car extends Model
{
   ...
    public function colors()
    {
        return $this->belongsToMany('App\Models\Color', 'car_colors', 'car_id', 'color_id')
                    ->using('App\Models\CarColor')
                    ->withTimestamps();
    }
}
```

Model Color
```
namespace App\Models;
use Illuminate\Database\Eloquent\Model;
class Color extends Model
{
   ...
    public function cars()
    {
        return $this->belongsToMany('App\Models\Car', 'car_colors', 'color_id', 'car_id')
                    ->using('App\Models\CarColor')
                    ->withTimestamps();
    }
}
```

Pivot table car_colors
```
namespace App\Models;
use Illuminate\Database\Eloquent\Relations\Pivot;
class CarColor extends Pivot
{
    protected $table = 'car_colors';

    protected $fillable = ['car_id', 'color_id'];

    public $incrementing = true;
}
```

I want to use a listbox to show and edit the Colors by a Car, i'm testing something like it in the CarController.php:

```
namespace App\Admin\Controllers;

use App\Models\Car;
use App\Models\CarColor;
use App\Models\Color;
use Encore\Admin\Controllers\AdminController;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Show;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Widgets\Tab;
use Encore\Admin\Layout\Content;

class CarController extends AdminController
{
     ...
    protected function detail($id)
    {
        $car = Car::findOrFail($id);
        $form2 = new Form($car);
        $form2->listbox('colors')->options(Color::all()->pluck('name', 'id'));
        return $form2;
    }    
    ...
}
```
it works in part, because it show the list with the Colors but no show initially the Colors saved in the Database in the "Selected List" (Right colunn) of the listbox, may be exists a problem with the Javascript code because in firefox 72.0.1 when i refresh the page (pushing F5 key or clicking the reload button) it works correctly with the database values. In chrome not works on reloading the page.

Please I no can see the error, the controller is saving correctly the data sent by  listbox, my problem is only to view the values of the DB loaded in the initial listbox.

**Comment by chieh301** [comment]
multipleSelect 也有一樣的狀況。
