### ISSUE TITLE
固定列显示问题

### ISSUE THREAD

**Issue by LuMitchell** [z-song/laravel-admin#4532]
- Laravel Version: 5.8
- PHP Version:7.3
- Laravel-admin: 1.7.14

### Description:
设置固定列之后，固定列和非固定列之间会有错开。
<img width="852" alt="15113757" src="https://user-images.githubusercontent.com/29627681/79296885-3d6cd100-7f0f-11ea-8d2c-8df67b93e3be.png">

### Steps To Reproduce:
$grid->fixColumns(6, -4);

**Comment by ahu** [comment]
我也发现有这个问题

**Comment by ieliwb** [comment]
有人知道怎么解决吗
