### ISSUE TITLE
执行php artisan admin:install 操作报错

### ISSUE THREAD

**Issue by beige123** [z-song/laravel-admin#4534]
- Laravel Version: 5.4
- PHP Version:
- Laravel-admin: 1.4.6

### Description:
执行php artisan admin:install 操作报错，
错误提示：
In Connection.php line 647:

  SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_C
  REATE_USER' (SQL: select * from information_schema.tables where table_schema = lar-admin and table_name = migration
  s)

In MySqlConnector.php line 150:

  SQLSTATE[42000]: Syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_C
  REATE_USER'

**Comment by Json-Luo** [comment]
syntax error or access violation: 1231 Variable 'sql_mode' can't be set to the value of 'NO_AUTO_C
REATE_USER' 
都写的蛮清楚了   sql_mode  设置错了，自己设置下 sql_mode 就好了
