### ISSUE TITLE
表单saving的时候如何执行js

### ISSUE THREAD

**Issue by gfd6th** [z-song/laravel-admin#4538]
试了下, 
```php
$form->saving(function($form){
  <<<JS
  console.log('aaaa')
JS
})
```
好像没办法执行

我的目的是想在saving的时候, 通过js获取vue组件里面的数据, 然后赋值给hidden的input, 进行提交, 请问有没有好的方法

**Comment by nkjackzhang** [comment]
执行saving的时候都已经提交给后台了，js当然不起作用，你得在页面js里拦截submit请求才行
