### ISSUE TITLE
Custom Row action Call to undefined method Encore\CustomActionsButton\CustomActions::add()

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4548]
- Laravel Version: 7.2.0
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description:
Documentation is not correct

### Steps To Reproduce:
Did steps from [documentation](https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=custom-row-amp-batch-action) to try Replicate action.
But I just get error page `Call to undefined method Encore\CustomActionsButton\CustomActions::add()`

And I even cannot find in directory `\vendor\encore` text string `CustomActions`

**Comment by chiwex** [comment]
what do you actually want to do

**Comment by schel4ok** [comment]
strange question.
I want to add one more button in row actions additionally to standard ones (view, edit, delete) and  simply copy code from documentation, but it gives error `Call to undefined method CustomActions::add()`

**Comment by chiwex** [comment]
use https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=row-action

**Comment by schel4ok** [comment]
I use this and it gives me error

**Comment by chiwex** [comment]
To create action button, use this command

`php artisan admin:action Post\\Replicate --grid-row --name="copy"
`
When this command run successfully, it will generate a **Post** folder and Replicate class.

`app/Admin/Actions/Post/Replicate.php:
`
To attach the button:

```
$grid->actions(function ($actions) {
    $actions->add(new Replicate);
});
```

**Comment by chiwex** [comment]
if it is not working, run composer update

**Comment by schel4ok** [comment]
I did that. Code is not working.
I update composer.
Now I just have Laravel Version 7.2.0, but code still not working.

**Comment by chiwex** [comment]
the error is from you code not from this package. 

i suggest you install a laravel project and install the admin package

**Comment by schel4ok** [comment]
Your suggestion was correct. I found problem.
It was because I have installed custom actions button extension from here https://github.com/nim4n136/custom-actions-button

So when I disable this extension in config/admin.php the code is working
```
    'extensions' => [
      'custom-actions-button' => [
          "enable" => false,,
```

But I like this extension. Original way of having actions in dropdown menu is not comfortable. What do you suggest to do?

**Comment by xuanchau99** [comment]
> Your suggestion was correct. I found problem.
> It was because I have installed custom actions button extension from here https://github.com/nim4n136/custom-actions-button
> 
> So when I disable this extension in config/admin.php the code is working
> 
> ```
>     'extensions' => [
>       'custom-actions-button' => [
>           "enable" => false,
> ```
> 
> But I like this extension. Original way of having actions in dropdown menu is not comfortable. What do you suggest to do?

how to fix it?

**Comment by schel4ok** [comment]
I don't find solution yet.

**Comment by MohamedUnis** [comment]
> To create action button, use this command
> 
> `php artisan admin:action Post\\Replicate --grid-row --name="copy" ` When this command run successfully, it will generate a **Post** folder and Replicate class.
> 
> `app/Admin/Actions/Post/Replicate.php: ` To attach the button:
> 
> ```
> $grid->actions(function ($actions) {
        if (\request('_scope_') == 'trashed') {
>            $actions->add(new Replicate);
        }
> });
> ```

**Comment by MohamedUnis** [comment]
> To create action button, use this command
> 
> `php artisan admin:action Post\\Replicate --grid-row --name="copy" ` When this command run successfully, it will generate a **Post** folder and Replicate class.
> 
> `app/Admin/Actions/Post/Replicate.php: ` To attach the button:
> 
> ```
> $grid->actions(function ($actions) {
        if (\request('_scope_') == 'trashed') {
>            $actions->add(new Replicate);
        }
> });
> ```
