### ISSUE TITLE
自定义行&批量操作，弹出表单中使用了select表单，下拉选择的时候，input无法获得输入焦点。

### ISSUE THREAD

**Issue by kaodouqifei** [z-song/laravel-admin#4549]
- Laravel Version: 5.5
- PHP Version:7.3
- Laravel-admin: 1.7.14

### Description:
自定义行&批量操作，弹出表单中使用了select表单，下拉选择的时候，input无法获得输入焦点。
![image](https://user-images.githubusercontent.com/14683935/79929173-8c6ab700-8477-11ea-9431-d2de8a282a03.png)
应该是被覆盖了吧 ，但是改z-index好像不管用，大佬们看看吧

**Comment by kaodouqifei** [comment]
暂时是这样解决的
找到modal的元素id，然后通过js删除tabindex属性
![image](https://user-images.githubusercontent.com/14683935/79946218-16c81080-84a2-11ea-9ab3-762f6f59c0e1.png)
form方法中引用
Admin::script("$('#app-admin-actions-bindproduct').removeAttr('tabindex')");

**Comment by kylin0702** [comment]
1.打开vendor\laravel-admin\AdminLTE\bootstrap\js\bootstrap.min.js
2.修改
`c.prototype.enforceFocus=function(){a(document).off("focusin.bs.modal").on("focusin.bs.modal",a.proxy(function(a){this.$element[0]===a.target||this.$element.has(a.target).length||this.$element.trigger("focus")},this))}`
为
`c.prototype.enforceFocus=function(){}`
3.清除服务器缓存和浏览器缓存
