### ISSUE TITLE
用了几个月的laravel-admin 框架，感觉很多地方还是很蹩脚的

### ISSUE THREAD

**Issue by songlen** [z-song/laravel-admin#4552]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
用了几个月的laravel-admin 框架，感觉很多地方还是很蹩脚的，bug不少，form表单不够智能，
亲们，把你们遇到的问题发出来看看吧
laravel-admin 的github感觉没人维护了

**Comment by nkjackzhang** [comment]
通用表单就是这样的，想智能化只能自己开发，遇到的问题搜下就知道了

**Comment by miaotiao** [comment]
具体问题可以提出来，上来就发个抱怨框架开发者的issue，这样不太好。

**Comment by TheBlueSkim** [comment]
这种也能提issue？
