### ISSUE TITLE
switch 开关设置 value 为 0、1，但是提交时依然是 on、off

### ISSUE THREAD

**Issue by mustangten** [z-song/laravel-admin#4556]
- Laravel Version: 5.5.48
- PHP Version: 7.1
- Laravel-admin: 1.7.14

### Description:
switch 开关设置 value 为 0、1，但是提交时依然是 on、off

### Steps To Reproduce:
https://learnku.com/laravel/t/43666

**Comment by DongDavid** [comment]
我今天刚下载下来也碰到这个问题了。
https://blog.csdn.net/weixin_43969402/article/details/102781568
百度了一波，改源码
`Encore\Admin\Form\Field\SwitchField`的`render`方法
```
// 原来的
$(event.target).closest('.bootstrap-switch').next().val(state ? 'on' : 'off').change();
// 改成这个就可以了
$(event.target).closest('.bootstrap-switch').next().val(state ? '{$this->states['on']['value']}' : '{$this->states['off']['value']}').change();
```
