### ISSUE TITLE
Refreshing migration

### ISSUE THREAD

**Issue by emmarvpol** [z-song/laravel-admin#4558]
- Laravel Version: 7.7.1
- PHP Version: 7.4.5
- Laravel-admin: 1.7.14

### Description:
Hello, I ran `php artisan migrate:refresh` and now my admin tables are empty.
I can't login to admin panel anymore. How can i fix that?

### Steps To Reproduce:
`php artisan db:seed` did nothing

Im getting errors for all of those
`php artisan admin:import helpers`

`php artisan admin:import media-manager`

`php artisan admin:import api-tester`

`php artisan admin:import config`

`php artisan admin:import scheduling`

**Comment by chiwex** [comment]
run `php artisan admin:install` to restore the default migration and seeding

**Comment by emmarvpol** [comment]
Thanks for your responce. I tried already with no luck. I got something like "already installed", I don't remember. I just reinstall both laravel and laravel-admin and that was very painful.

**Comment by chiwex** [comment]
you could have manually deleted all the tables that comes with laravel admin
