### ISSUE TITLE
Custom Batch action style cannot be modified

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4561]
- Laravel Version: 7.8.1
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description:
On fresh laravel admin installation I cannot repeat code from documentation.
Here https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=batch-action-1 documentation says that I shoud see new button in tool area like that
[![Снимок](https://user-images.githubusercontent.com/1479100/61609162-c9571280-ac87-11e9-8f93-869a188c5553.png)](https://user-images.githubusercontent.com/1479100/61609162-c9571280-ac87-11e9-8f93-869a188c5553.png)

### Steps To Reproduce:
class BatchReplicate
```
    public $name = 'batch copy';
    protected $selector = '.report-posts';
    public function html()
    {
        return "<a class='report-posts btn btn-sm btn-danger'><i class='fa fa-info-circle'></i>Report</a>";
    }
```

class PageController
```
        $grid->tools(function (Grid\Tools $tools) {
            $tools->append(new BatchReplicate());
        });
```

then I see just link without style.
[
![Снимок](https://user-images.githubusercontent.com/10367464/80277395-4b80d580-86f7-11ea-9578-c50be97ec419.JPG)
](https://user-images.githubusercontent.com/1479100/61609162-c9571280-ac87-11e9-8f93-869a188c5553.png
)

Then in source code I can see `<a href="javascript:void(0);" class="report-posts">batch copy</a>
` 
Later I found that code from html() function is completely  ignored
So even if I do like that
```
    public function html()
    {
        return "";
    }
```
Anyway on the page I see 
```
<a href="javascript:void(0);" class="report-posts">batch copy</a>
```

So in the final html I can see only values from     $name and $selector variables.
And I cannot change anything in the link style.

**Comment by chiwex** [comment]
the method is different for batch action

```
$grid->batchActions(function (Grid\Tools\BatchActions $batch) {

            if (!can('user-destroy')) {
                $batch->disableDelete();
            }

            if (can('user-ban')) {
                $batch->add(new BatchBan());
            }

            if (can('user-verify')) {
                $batch->add(new BatchVerify());
            }

            if (can('user-unverify')) {
                $batch->add(new BatchUnVerify());
            }

            if (can('user-restore') && \request('_scope_') == 'trashed') {
                $batch->add(new BatchRestore());
                $batch->add(new BatchPermanentDelete());
            }

        });
```

**Comment by chiwex** [comment]
Example to batch Action 

```
namespace App\Admin\Actions\General;

use Encore\Admin\Actions\BatchAction;
use Illuminate\Database\Eloquent\Collection;

class BatchPermanentDelete extends BatchAction
{
    public $name;

    public function __construct()
    {

        parent::__construct();
        $this->name = trans('admin.batch_delete_permanently');

    }

    public function handle (Collection $collection)
    {

        foreach ($collection as $model) {
            $model->forceDelete();
            activity()
                ->performedOn($model)
                ->causedBy(auth()->user())
                ->inLog('user')
                ->log(__('has permanently deleted'));
        }

        return $this->response()->success(__('Deleted Permanently'))->refresh();
    }

    public function dialog ()
    {
        $this->confirm(__('Are you sure you want to delete permanently?'));
    }

}

```

Example of row action

```
namespace App\Admin\Actions\General;

use Encore\Admin\Actions\RowAction;
use Illuminate\Database\Eloquent\Model;

class PermanentDelete extends RowAction
{

    public $name;

    public function __construct()
    {

        parent::__construct();
        $this->name = trans('admin.delete_permanently');

    }

    public function handle(Model $model)
    {

        $model->forceDelete();

        activity()
            ->performedOn($model)
            ->causedBy(auth()->user())
            ->inLog('user')
            ->log(__('has permanently deleted'));

        return $this->response()->success(__('Deleted Permanently'))->refresh();

    }

    public function dialog()
    {
        $this->confirm(__('Are you sure you want to delete permanently?'));
    }

}

```

**Comment by schel4ok** [comment]
This is clear. But my question is about html function of BatchAction class
If you add this function to BatchPermanentDelete class then you will see that 
```
    public function html()
    {
        return "<a class='batch-delete btn btn-sm btn-danger'><i class='fa fa-info-circle'></i>Report</a>";
    }
```

Then you will see that there is no difference what kind of code you put inside html function. Anyway in rendered html you will always see `<a href="javascript:void(0);" class="report-posts">batch copy</a>`

And in documentation we can see different statement
![Capture](https://user-images.githubusercontent.com/10367464/80301028-108baa00-87aa-11ea-8e08-e668330397f9.JPG)

**Comment by chiwex** [comment]
U need to use css to select and customise the button.

**Comment by schel4ok** [comment]
No problem.
But this also means that documentation is wrong, because it is saying that you can customize button inside html function of Bach Action class
