### ISSUE TITLE
模型表单-数字输入框可以支持小数吗？

### ISSUE THREAD

**Issue by becage** [z-song/laravel-admin#4562]
- Laravel Version: 6.*
- PHP Version:7.3
- Laravel-admin: 1.7

### Description:
模型表单-数字输入框可以支持小数吗？
```
$form->number('rate', '打分'); 
```
可不可以以加个步长参数？

**Comment by songlen** [comment]
可以啊，仿照 currency 货币的方法给number 扩展一个digits() 方法就行了
`    public function digits($digits)
    {
        return $this->options(compact('digits'));
    }`

**Comment by becage** [comment]
```
$form->decimal('float')->options(['max' => 10, 'min' => 1,'digits' => 2]);
```
