### ISSUE TITLE
安装dingo/api后：请求后台登陆：出现sha1() expects parameter 1 to be string, object given

### ISSUE THREAD

**Issue by littleangelio** [z-song/laravel-admin#4563]
- Laravel Version: 7.7.1
- PHP Version: 7.3.13
- Laravel-admin: 1.7.6
- dingo/api: 3.0.0
项目运行环境：valet 
.env 配置：
#Domain Settings
APP_URL=utopia.test
API_DOMAIN=api.utopia.test
ADMIN_DOMAIN=admin.utopia.test
ADMIN_HTTPS=false

#DingoAPI
API_STANDARDS_TREE=prs
API_SUBTYPE=utopia
API_PREFIX=
API_VERSION=v1
API_DEBUG=true
.env 配置：https://raw.githubusercontent.com/littleangelio/Feedback/master/.env
admin.php配置https://raw.githubusercontent.com/littleangelio/Feedback/master/config/admin.php
auth.php 配置：https://raw.githubusercontent.com/littleangelio/Feedback/master/config/atuth.php

### Description:
工程中：引入dingo/api 后：访问admin.example.com 
有如下错误返回：{"message":"sha1() expects parameter 1 to be string, object given","status_code":500}
当前页面截图：https://imgchr.com/i/Jclf2Q
详细报错截图：https://imgchr.com/i/JclOGF

### Steps To Reproduce:
访问admin.example.com 
输入完：admin admin 点击登陆按钮

**Comment by 191834552** [comment]
我也遇到这个问题，请问你是否解决了？

**Comment by 191834552** [comment]
> * Laravel版本：7.7.1
> * PHP版本：7.3.13
> * Laravel-admin：1.7.6
> * dingo / api：3.0.0
>   项目运行环境：valet 
>   .env配置：
>   #Domain设置
>   APP_URL = utopia.test 
>   API_DOMAIN = api.utopia.test 
>   ADMIN_DOMAIN = admin.utopia.test 
>   ADMIN_HTTPS = false
> 
> #DingoAPI
> API_STANDARDS_TREE = PRS
> API_SUBTYPE =乌托邦
> API_PREFIX =
> API_VERSION = V1
> API_DEBUG =真
> .ENV配置：https://raw.githubusercontent.com/littleangelio/Feedback/master/.env
> admin.php的配置[的https：//raw.githubusercontent。 com / littleangelio / Feedback / master / config / admin.php](https://raw.githubusercontent.com/littleangelio/Feedback/master/config/admin.php)
> auth.php配置：[https](https://raw.githubusercontent.com/littleangelio/Feedback/master/config/atuth.php) ://raw.githubusercontent.com/littleangelio/Feedback/master/config/atuth.php[](https://raw.githubusercontent.com/littleangelio/Feedback/master/config/atuth.php)
> 
> ### 描述：
> 工程中：日期ding / api后：访问admin.example.com
> 有如下错误返回：{“ message”：“ sha1（）期望参数1为字符串，对象已给定”，“状态码”：500}
> 当前页面截图：https://imgchr.com/i/Jclf2Q
> 详细报错截图：[https](https://imgchr.com/i/JclOGF) ://imgchr.com/i/JclOGF[](https://imgchr.com/i/JclOGF)
> 
> ### 重现步骤：
> 访问admin.example.com
> 输入完：admin admin点击登陆按钮

请问您是怎么解决的这个问题，我这边也是这个问题，一模一样

**Comment by 191834552** [comment]
已解决 [https://learnku.com/articles/56470](url)
