### ISSUE TITLE
cannot replicate model with unique slug field

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4564]
- Laravel Version: 7.8.1
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description:
I cannot understand how to replicate model with unique `slug` field.
I see success message, but this code doesn't create additional row into DB table. 
And no messages or exceptions in debugbar.

### Steps To Reproduce:
```

    public function handle(Model $model)
    {
        $model->replicate(['slug']);
        $model->slug = Str::slug($model->title, '-') . '-copy'; // or $model->id instead '-copy' string
        $model->save();
        return $this->response()->success('copied')->refresh();
    }
```

And if I add `dd($model)` somewhere in the middle it doesn't help me, because I don't see anything except Oops message. 
![sFuNe 1](https://user-images.githubusercontent.com/10367464/80301245-9d833300-87ab-11ea-93ad-1c62d015e53b.jpg)

Here is migration file
```
        Schema::create('news_posts', function (Blueprint $table) {
            $table->increments('id')->unsigned();
            $table->integer('category_id')->unsigned();
            $table->string('title', 255)->nullable();
            $table->string('slug', 255)->unique();
            $table->text('fulltext')->nullable();
            $table->string('image', 255)->nullable();
            $table->boolean('is_published')->default(false);
            $table->timestamp('published_at')->nullable();
            $table->timestamps();
            $table->softDeletes();

            $table->foreign('category_id')->references('id')->on('news_categories');
            $table->index('is_published');
        });
```

**Comment by chiwex** [comment]
You code is okay but will only work on row action

**Comment by chiwex** [comment]
Replace this line with

$model->replicate();

**Comment by schel4ok** [comment]
Actually it is not working. And if I replace according to your suggestion no difference.
```
        $model->replicate();
        $model->slug = Str::slug($model->title, '-') . '-copy';
        $model->save();
```
On attached screenshot you see Oops message. But this happens only when I put `dd` in the code. If no `dd` then I see success message, but new record is not saved to database and I don't see any exception. 

If I just have `$model->replicate()->save();` then I have SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry error message

**Comment by chiwex** [comment]
$new = $model->replicate();
$new->slug = Str::slug($model->title, '-') . '-copy'; 
$new->save();

**Comment by chiwex** [comment]
The problem can from the action. Check to know whetter is Batch Action or Row Action

**Comment by schel4ok** [comment]
That is working. I just add timestamp to make it more universal
```
        $new = $model->replicate();
        $new->slug = $new->slug . time();
        $new->save();
```

Thanks a lot!
