### ISSUE TITLE
error message when delete parent element 

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4565]
- Laravel Version: 7.8.1
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description:
If I delete category, which has children elements, then I see raw DB error. How to replace that with more user friendly error message? 
![Capture](https://user-images.githubusercontent.com/10367464/80301341-46319280-87ac-11ea-8365-902ca522376a.JPG)

**Comment by schel4ok** [comment]
I prefer to have message "This category has related posts and cannot be deleted" instead of raw sql error message

**Comment by lilashih** [comment]
Try this.


In your controller:
```php
public function destroy($id)
{
    try {
        return parent::destroy($id); // call laravel-admin destroy function
    } cache (\Exception $e) {
        return response()->json([
            'status'  => false,
            'message' => 'error message',
        ]);
    }
}
```

**Comment by schel4ok** [comment]
It doesn't work.
This just gives me same response for all categories.
If category has related posts from foreign table then I see "error message" and category is not deleted.
And if category doesn't have related posts anyway I see same message and category is not deleted, but I expect this category to be deleted (because it is empty).

**Comment by schel4ok** [comment]
More details about this issue.
Let say we have categories table and posts table.
Each category could have many subcategories and many related posts from foreign posts table.

When I try to delete category, which has subcategories, but has no related posts, then I see raw SQL error message and after that category anyway deleted, which is not acceptable!!!
When I try to delete category, which has related posts, then I see raw SQL error message and that category cannot be deleted.
But always I see that SQL error.

**Comment by lilashih** [comment]
Maybe the problem is your foreign keys.
Please see the **Referential Actions** section in this document [FOREIGN KEY Constraints](https://dev.mysql.com/doc/refman/8.0/en/create-table-foreign-keys.html).

In migration, you can specify the action for the "on delete" properties of the constraint.
https://laravel.com/docs/7.x/migrations#foreign-key-constraints
```php
$table->foreignId('user_id')->constrained()->onDelete('cascade');
```

**Comment by schel4ok** [comment]
You are right. There was no `onDelete` in my migration schema.
Now I changed like that.
```
        Schema::create('news_categories', function (Blueprint $table) {
            $table->increments('id')->unsigned();
            $table->integer('parent_id')->unsigned();
            $table->foreign('parent_id')->references('id')->on('news_categories')->onDelete('RESTRICT');
        });
        Schema::create('news_posts', function (Blueprint $table) {
            $table->increments('id')->unsigned();
            $table->integer('category_id')->unsigned();
            $table->foreign('category_id')->references('id')->on('news_categories')->onDelete('RESTRICT');
        });
```

And now it is not allowed to delete category from `news_categories` that has subcategories or related posts in `news_posts` table.
But your code to replace error message doesn't work. I still see raw SQL error 
```
Ошибка при удалении! : SQLSTATE[23000]: Integrity constraint violation: 1451 Cannot delete or update a parent row: a foreign key constraint fails (`steklo`.`news_categories`, CONSTRAINT `news_categories_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `news_categories` (`id`)) (SQL: delete from `news_categories` where `id` = 1)
```

Where could be problem?

**Comment by Fenslau** [comment]
> * Laravel Version: 7.8.1
> 
>     * PHP Version: 7.2.19
> 
>     * Laravel-admin: 1.7.14
> 
> 
> ### Description:
> 
> If I delete category, which has children elements, then I see raw DB error. How to replace that with more user friendly error message? ![Capture](https://user-images.githubusercontent.com/10367464/80301341-46319280-87ac-11ea-8365-902ca522376a.JPG)

Здравствуйте, как-нибудь решили этот вопрос? 
Мне тоже нужно, чтобы непустые категории не удалялись, поэтому поставил рестрикт, но вот это вырвиглазное сообщение .... Никак не могу его заменить. Даже подмена сообщения в самом этом исключении не помогает.
