### ISSUE TITLE
Validation of unique field doesn't allow to update record to database

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4566]
- Laravel Version: 7.8.1
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description:
Validation of unique field doesn't allow to update record to database

When open existing record to edit and click save button I see validation error  
**The URI has already been taken.**

### Steps To Reproduce:
```
$form->text('slug', trans('admin.uri'))->rules('unique:App\Models\NewsPost,slug');
```

**Comment by chiwex** [comment]
The is may help

https://laravel-admin.org/docs/#/en/model-form-validation?id=database-unique-check

**Comment by schel4ok** [comment]
Thanks a lot!
