### ISSUE TITLE
how to check that form field was changed

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4567]
- Laravel Version: 7.8.1
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description:
I have boolean form field `is_published` and when this field value changed from 0 to 1 I want to write current time to `published_at` field.
I can access field value under `$form->saving`, but I cannot understand how to access original `$model->is_published` value after form load.
If I don't take into account `$model->is_published` value then `published_at` field will be updated every time with `updated_at` field.
So for the moment I just found this solution. But I believe there should be some integrated way to do that, but looking at `dd($form)` I cannot find what I can use.
```
$form->switch('is_published', trans('myadmin.is_published'))->states( NewsPost::get()->pluck('is_published') );
$form->display('published_at', trans('myadmin.published_at'))->readonly();

        $form->saving(function ($form, $model) {
            
            // REQUEST_URI = admin/news/posts/$id
            // lastitem = id
            $path = explode('/', $_SERVER['REQUEST_URI']);
            $lastitem = end($path);
            // looking for value of is_published field for current record from database
            $model = NewsPost::whereId($lastitem)->select('is_published')->first();

            if ($model->is_published == 0 && $form->is_published == "on") {
                $form->published_at = Carbon::now();
            }

            if ($form->is_published == "off") {
                $form->published_at = NULL;
            }
        });
```

**Comment by schel4ok** [comment]
I think there should be something more beautiful like **isTouched** or **isDirty** properties

**Comment by chiwex** [comment]
This snippet from UserController can help to solve it

$form->saving(function (Form $form) {
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = bcrypt($form->password);
            }
        });

**Comment by schel4ok** [comment]
Cool. Thanks
