### ISSUE TITLE
访问任一页面时都提示 Class 'Admin' not found

### ISSUE THREAD

**Issue by zhukongyi** [z-song/laravel-admin#4571]
- Laravel Version: 5.5
- PHP Version:
- Laravel-admin: 1.7

我需要跑到laravel-admin里的 views/*.blade.php里将  Admin::method，如Admin::tile()改成Encore\Admin\Facades\Admin::title() 才能正常运行。
请问如何解决这个问题？

**Comment by mountainguan** [comment]
没有use

**Comment by zhukongyi** [comment]
我在config/app.php的aliases里添加 下面的代码就好了
```
aliases=>{
# 添加这行代码
 'Admin' => Encore\Admin\Facades\Admin::class
}
```
