### ISSUE TITLE
how to use charts-datalabels plugins in laravel-admin chartjs

### ISSUE THREAD

**Issue by azaman2204** [z-song/laravel-admin#4578]
- Laravel Version: 5.5
- PHP Version: 7.4.3
- Laravel-admin: 1.7
- laravel-admin-ext/chartjs": "^1.0",

### Description:
How to use the chartjs data-labels for the chartjs. Anyone has idea how to do this? Thanks

**Comment by chiwex** [comment]
A Piece of my code. You can figure what is going on the code, and refactor it

The blade file

```
<div class="box-body" >

        <canvas id="chart_0" height="40vw" width="80vw"></canvas>

        <script>

            $(function () {

                var myChart = new Chart(document.getElementById("chart_0"), {
                    type: 'line',
                    data: {
                        labels: [
                            "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
                        ],
                        datasets: [
                            {
                                label:  'Total',
                                backgroundColor: '#bdb33e',
                                borderColor: '#bdb33e',
                                data: @json($shipment_total),
                                borderWidth: 2,
                                fill: false
                            },
                            {
                                label:  'delivered',
                                backgroundColor: '#00a200',
                                borderColor: '#00a200',
                                data: @json($shipment_delivered),
                                borderWidth: 2,
                                fill: false
                            },
                            {
                                label:  'Pending',
                                backgroundColor: '#eec04a',
                                borderColor: '#eec04a',
                                data: @json($shipment_pending),
                                borderWidth: 2,
                                fill: false
                            },
                            {
                                label:  'Approved',
                                backgroundColor: '#ee2e43',
                                borderColor: '#ee2e43',
                                data: @json($shipment_approved),
                                borderWidth: 2,
                                fill: false
                            },
                            {
                                label:  'Cancelled',
                                backgroundColor: '#2403d2',
                                borderColor: '#2403d2',
                                data: @json($shipment_cancelled),
                                borderWidth: 2,
                                fill: false
                            }
                        ]
                    },
                    options: {
                        responsive: true,
                        title:{
                            display:true,
                            text:''
                        },
                        tooltips: {
                            mode: 'index',
                            intersect: false,
                        },
                        hover: {
                            mode: 'nearest',
                            intersect: true
                        },
                        scales: {
                            xAxes: [{
                                display: true,
                                scaleLabel: {
                                    display: true,
                                }
                            }],
                            yAxes: [{
                                display: true,
                                scaleLabel: {
                                    display: true,
                                    labelString: 'Value'
                                },
                                ticks: {
                                    beginAtZero:true
                                }
                            }]
                        }
                    }
                });
            });

        </script>

        <!-- /.table-responsive -->
    </div>
```

I used this code below to pass data to my view

```
$data['shipment_total'] = $this->getShipmentTotalChart();
        $data['shipment_pending'] = $this->getShipmentPendingChart();
        $data['shipment_approved'] = $this->getShipmentApprovedChart();
        $data['shipment_cancelled'] = $this->getShipmentCancelledChart();
        $data['shipment_rejected'] = $this->getShipmentRejectedChart();
        $data['shipment_delivered'] = $this->getShipmentDeliveredChart();
```

the controller methods  i used

```
public function getShipmentTotalChart()
    {

        $year = Carbon::now()->format('Y');

        $drow = [];

        for ($month = 1; $month <= 12; $month++) {
            $query = Shipment::query();
            $query->whereMonth('created_at', $month);
            $query->whereYear('created_at', $year);

            if (userType('customer')) {
                $query->where('customer_id', Admin::user()->id);
            } else if (deliveryAgent()) {
                $query->where('driver_id', Admin::user()->id);
            }

            $drow[] = $query->count();

        }

        return $drow;

    }

    public function getShipmentPendingChart()
    {

        $year = Carbon::now()->format('Y');

        $drow = [];

        for ($month = 1; $month <= 12; $month++) {

            $query = Shipment::query();

            $query->whereMonth('created_at', $month);

            $query->whereYear('created_at', $year);

            $query->where('shipment_status_id', 1);

            if (userType('customer')) {
                $query->where('customer_id', Admin::user()->id);
            } else if (deliveryAgent()) {
                $query->where('driver_id', Admin::user()->id);
            }

            $drow[] = $query->count();

        }

        return $drow;

    }

    public function getShipmentApprovedChart()
    {

        $year = Carbon::now()->format('Y');

        $drow = [];

        for ($month = 1; $month <= 12; $month++) {

            $query = Shipment::query();

            $query->whereMonth('created_at', $month);

            $query->whereYear('created_at', $year);

            $query->where('shipment_status_id', 1);

            if (userType('customer')) {
                $query->where('customer_id', Admin::user()->id);
            } else if (deliveryAgent()) {
                $query->where('driver_id', Admin::user()->id);
            }

            $drow[] = $query->count();

        }

        return $drow;

    }

    public function getShipmentCancelledChart()
    {

        $year = Carbon::now()->format('Y');

        $drow = [];

        for ($month = 1; $month <= 12; $month++) {

            $query = Shipment::query();

            $query->whereMonth('created_at', $month);

            $query->whereYear('created_at', $year);

            $query->where('shipment_status_id', 4);

            if (userType('customer')) {
                $query->where('customer_id', Admin::user()->id);
            } else if (deliveryAgent() ) {
                $query->where('driver_id', Admin::user()->id);
            }

            $drow[] = $query->count();

        }

        return $drow;

    }

    public function getShipmentRejectedChart()
    {

        $year = Carbon::now()->format('Y');

        $drow = [];

        for ($month = 1; $month <= 12; $month++) {

            $query = Shipment::query();

            $query->whereMonth('created_at', $month);

            $query->whereYear('created_at', $year);

            $query->where('shipment_status_id', 3);

            if (userType('customer')) {
                $query->where('customer_id', Admin::user()->id);
            }else if (deliveryAgent()) {
                $query->where('driver_id', Admin::user()->id);
            }

            $drow[] = $query->count();

        }

        return $drow;

    }

    public function getShipmentDeliveredChart()
    {

        $year = Carbon::now()->format('Y');

        $drow = [];

        for ($month = 1; $month <= 12; $month++) {
            $query = Shipment::query();
            $query->whereMonth('created_at', $month);
            $query->whereYear('created_at', $year);
            $query->where('delivery_status_id', 8);
            if (userType('customer')) {
                $query->where('customer_id', Admin::user()->id);
            }else if (deliveryAgent()) {
                $query->where('driver_id', Admin::user()->id);
            }
            $drow[] = $query->count();
        }

        return $drow;

    }
```

**Comment by azaman2204** [comment]
> A Piece of my code. You can figure what is going on the code, and refactor it to a single method.
> 
> The blade file
> 
> ```
> <div class="box-body" >
> 
>         <canvas id="chart_0" height="40vw" width="80vw"></canvas>
> 
>         <script>
> 
>             $(function () {
> 
>                 var myChart = new Chart(document.getElementById("chart_0"), {
>                     type: 'line',
>                     data: {
>                         labels: [
>                             "Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec"
>                         ],
>                         datasets: [
>                             {
>                                 label:  'Total',
>                                 backgroundColor: '#bdb33e',
>                                 borderColor: '#bdb33e',
>                                 data: @json($shipment_total),
>                                 borderWidth: 2,
>                                 fill: false
>                             },
>                             {
>                                 label:  'delivered',
>                                 backgroundColor: '#00a200',
>                                 borderColor: '#00a200',
>                                 data: @json($shipment_delivered),
>                                 borderWidth: 2,
>                                 fill: false
>                             },
>                             {
>                                 label:  'Pending',
>                                 backgroundColor: '#eec04a',
>                                 borderColor: '#eec04a',
>                                 data: @json($shipment_pending),
>                                 borderWidth: 2,
>                                 fill: false
>                             },
>                             {
>                                 label:  'Approved',
>                                 backgroundColor: '#ee2e43',
>                                 borderColor: '#ee2e43',
>                                 data: @json($shipment_approved),
>                                 borderWidth: 2,
>                                 fill: false
>                             },
>                             {
>                                 label:  'Cancelled',
>                                 backgroundColor: '#2403d2',
>                                 borderColor: '#2403d2',
>                                 data: @json($shipment_cancelled),
>                                 borderWidth: 2,
>                                 fill: false
>                             }
>                         ]
>                     },
>                     options: {
>                         responsive: true,
>                         title:{
>                             display:true,
>                             text:''
>                         },
>                         tooltips: {
>                             mode: 'index',
>                             intersect: false,
>                         },
>                         hover: {
>                             mode: 'nearest',
>                             intersect: true
>                         },
>                         scales: {
>                             xAxes: [{
>                                 display: true,
>                                 scaleLabel: {
>                                     display: true,
>                                 }
>                             }],
>                             yAxes: [{
>                                 display: true,
>                                 scaleLabel: {
>                                     display: true,
>                                     labelString: 'Value'
>                                 },
>                                 ticks: {
>                                     beginAtZero:true
>                                 }
>                             }]
>                         }
>                     }
>                 });
>             });
> 
>         </script>
> 
>         
>     </div>
> ```
> 
> I used this code below to pass data to my view
> 
> ```
> $data['shipment_total'] = $this->getShipmentTotalChart();
>         $data['shipment_pending'] = $this->getShipmentPendingChart();
>         $data['shipment_approved'] = $this->getShipmentApprovedChart();
>         $data['shipment_cancelled'] = $this->getShipmentCancelledChart();
>         $data['shipment_rejected'] = $this->getShipmentRejectedChart();
>         $data['shipment_delivered'] = $this->getShipmentDeliveredChart();
> ```
> 
> the controller methods i used
> 
> ```
> public function getShipmentTotalChart()
>     {
> 
>         $year = Carbon::now()->format('Y');
> 
>         $drow = [];
> 
>         for ($month = 1; $month <= 12; $month++) {
>             $query = Shipment::query();
>             $query->whereMonth('created_at', $month);
>             $query->whereYear('created_at', $year);
> 
>             if (userType('customer')) {
>                 $query->where('customer_id', Admin::user()->id);
>             } else if (deliveryAgent()) {
>                 $query->where('driver_id', Admin::user()->id);
>             }
> 
>             $drow[] = $query->count();
> 
>         }
> 
>         return $drow;
> 
>     }
> 
>     public function getShipmentPendingChart()
>     {
> 
>         $year = Carbon::now()->format('Y');
> 
>         $drow = [];
> 
>         for ($month = 1; $month <= 12; $month++) {
> 
>             $query = Shipment::query();
> 
>             $query->whereMonth('created_at', $month);
> 
>             $query->whereYear('created_at', $year);
> 
>             $query->where('shipment_status_id', 1);
> 
>             if (userType('customer')) {
>                 $query->where('customer_id', Admin::user()->id);
>             } else if (deliveryAgent()) {
>                 $query->where('driver_id', Admin::user()->id);
>             }
> 
>             $drow[] = $query->count();
> 
>         }
> 
>         return $drow;
> 
>     }
> 
>     public function getShipmentApprovedChart()
>     {
> 
>         $year = Carbon::now()->format('Y');
> 
>         $drow = [];
> 
>         for ($month = 1; $month <= 12; $month++) {
> 
>             $query = Shipment::query();
> 
>             $query->whereMonth('created_at', $month);
> 
>             $query->whereYear('created_at', $year);
> 
>             $query->where('shipment_status_id', 1);
> 
>             if (userType('customer')) {
>                 $query->where('customer_id', Admin::user()->id);
>             } else if (deliveryAgent()) {
>                 $query->where('driver_id', Admin::user()->id);
>             }
> 
>             $drow[] = $query->count();
> 
>         }
> 
>         return $drow;
> 
>     }
> 
>     public function getShipmentCancelledChart()
>     {
> 
>         $year = Carbon::now()->format('Y');
> 
>         $drow = [];
> 
>         for ($month = 1; $month <= 12; $month++) {
> 
>             $query = Shipment::query();
> 
>             $query->whereMonth('created_at', $month);
> 
>             $query->whereYear('created_at', $year);
> 
>             $query->where('shipment_status_id', 4);
> 
>             if (userType('customer')) {
>                 $query->where('customer_id', Admin::user()->id);
>             } else if (deliveryAgent() ) {
>                 $query->where('driver_id', Admin::user()->id);
>             }
> 
>             $drow[] = $query->count();
> 
>         }
> 
>         return $drow;
> 
>     }
> 
>     public function getShipmentRejectedChart()
>     {
> 
>         $year = Carbon::now()->format('Y');
> 
>         $drow = [];
> 
>         for ($month = 1; $month <= 12; $month++) {
> 
>             $query = Shipment::query();
> 
>             $query->whereMonth('created_at', $month);
> 
>             $query->whereYear('created_at', $year);
> 
>             $query->where('shipment_status_id', 3);
> 
>             if (userType('customer')) {
>                 $query->where('customer_id', Admin::user()->id);
>             }else if (deliveryAgent()) {
>                 $query->where('driver_id', Admin::user()->id);
>             }
> 
>             $drow[] = $query->count();
> 
>         }
> 
>         return $drow;
> 
>     }
> 
>     public function getShipmentDeliveredChart()
>     {
> 
>         $year = Carbon::now()->format('Y');
> 
>         $drow = [];
> 
>         for ($month = 1; $month <= 12; $month++) {
>             $query = Shipment::query();
>             $query->whereMonth('created_at', $month);
>             $query->whereYear('created_at', $year);
>             $query->where('delivery_status_id', 8);
>             if (userType('customer')) {
>                 $query->where('customer_id', Admin::user()->id);
>             }else if (deliveryAgent()) {
>                 $query->where('driver_id', Admin::user()->id);
>             }
>             $drow[] = $query->count();
>         }
> 
>         return $drow;
> 
>     }
> ```

Thanks for the example. I am able to do the chart ONLY thing I need to know where shall i keep or put the chartjs-datalabels plugins so that I can use it in the charts.  Is there anything to be done to make the chartjs-datalables-plugins  able to access when calling the options for the datalabels in the charts.

**Comment by chiwex** [comment]
Your question is not clear

**Comment by chiwex** [comment]
What is chartjs-datalables-plugins

**Comment by chiwex** [comment]
Your can put chartjs plugin at the footer of your blade
