### ISSUE TITLE
[BUG] $form->saving make field empty after inline edit in grid mode

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#4584]
- Laravel Version: 7.8.1
- PHP Version: 7.2.19
- Laravel-admin: 1.7.14

### Description:
If in **form mode** I have this code to make automatic slugs from post title when create or update record
```
        $form->saving(function ($form) {
            if (empty($form->slug)) {
                $form->slug = Str::slug($form->title, '-');
            }
        });
```

Then **any editable field**, except `title` in **grid mode** after inline edit and saving initiates transaction, which erase slug value. And save empty value in `SLUG` field in database table.
Even if you try to edit SLUG field inline you will get empty field after page refresh.
The only difference is **editable title**. When I edit `title` inline it initiates transaction, which erase slug value and save `Str::slug($form->title, '-')` value. At least this doesn't give me empty slug field, but anyway I don't want this to be replaced if I already have something in slug.

This behaviour is not expected to me.
Problem disappear only when I remove `$form->saving` code above or remove all inline editable fields in grid mode.

What can be done to avoid it?

**Comment by chiwex** [comment]
i don;t editable field are processed by `$form->saving(function ($form) {` method

you need to inspect the ajax request
