### ISSUE TITLE
model-tree 插件删除失败时依然提示成功

### ISSUE THREAD

**Issue by RoachBully** [z-song/laravel-admin#4585]
- Laravel Version: 5.5
- PHP Version:7.3
- Laravel-admin: 1.7

### Description:
在使用model-tree模型树时，我想要在删除数据前加一些判断，在model中抛出异常后页面能显示出来然后右上角依然提示删除成功，此时数据并没有删除

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/21255523/80862219-d3418380-8ca5-11ea-8c7d-5e36b0f016b2.png)
![image](https://user-images.githubusercontent.com/21255523/80862222-db99be80-8ca5-11ea-94ca-f1017227667e.png)

**Comment by ChinaXion** [comment]
补充：添加deleting验证的情况下，排序会报错。

**Comment by linyuanchang** [comment]
解决了吗？
