### ISSUE TITLE
HasMany DOM id attribute 

### ISSUE THREAD

**Issue by SpinyMan** [z-song/laravel-admin#4588]
- Laravel Version: 6
- PHP Version: 7.4.5
- Laravel-admin: 1.7.15

### Description:
HasMany renders fields with non-unique id attribute:
`[DOM] Found 6 elements with non-unique id #name`

I propose to add `public function setId(string $id)` OR add filter before render HasMany field that set non-unique id for this.

**Comment by pirmanduiana** [comment]
and z-song doesn't have a fucking answer
