### ISSUE TITLE
Sorting on relational table count

### ISSUE THREAD

**Issue by alimranahmed** [z-song/laravel-admin#4598]
- Laravel Version: ^7.0
- PHP Version: 7.2.5
- Laravel-admin: ^1.7

### Description:
I was trying to achieve sortable in related table's count, but seems it's doesn't work with sortable(). Note sure what should be the work around. 

### Steps To Reproduce:
```
$grid->comments()->display(function ($comments){
            $totalComment = count($comments);
            if($totalComment <= 0){
                return $totalComment;
            }
            return "<a href='" . route('comments.index', ['post_id' => $this->id]) . "'>{$totalComment}</a>";
        })->sortable();
```

I works absolutely fine without calling `sortable()` method. But I want to post by comment count. What to do?

**Comment by vlados** [comment]
@alimranahmed  https://github.com/z-song/laravel-admin/issues/3678#issuecomment-514488552
