### ISSUE TITLE
多图上传组件multipleImage使用了removable和sortable无效

### ISSUE THREAD

**Issue by wzlzking** [z-song/laravel-admin#4602]
- Laravel Version: 7.6
- PHP Version:7.3
- Laravel-admin: 1.7

Description:
多图上传组件使用了removable和sortable，在新增时无效，修改时有效
$form->multipleImage('thumb', __('封面'))->uniqueName()->move($this->img_path)->removable()->sortable();
![微信截图_20200508173711](https://user-images.githubusercontent.com/41713774/81393231-96b4d280-9152-11ea-8b7d-2165cdb71905.png)
![微信截图_20200508172553](https://user-images.githubusercontent.com/41713774/81393326-c368ea00-9152-11ea-8c1e-022dd072989c.png)

**Comment by nihaoajys** [comment]
没有人回答吗

**Comment by Dennies-Chang** [comment]
I have the same issue, the environment:
php: 8.1.1
Laravel: 9.52.0
Laravel-admin 1.8.17
