### ISSUE TITLE
只有一行数据情况下,行操作栏,增加了三个菜单,显示的宽度高度就不够了,下面几个被盖住

### ISSUE THREAD

**Issue by godhelpjun** [z-song/laravel-admin#4606]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

**Comment by chanble** [comment]
手机版有这个bug， [看这个](https://laravel-admin.org/docs/zh/model-grid-custom-actions) 调整操作栏样式吧
