### ISSUE TITLE
查询过滤器between出错

### ISSUE THREAD

**Issue by Ninee** [z-song/laravel-admin#462]
使用$filter->between()不起作用，跟踪发觉执行到`if (!array_has($inputs, $this->column)) {
            return;
        }`就直接return了，版本1.3和1.4都无法使用。

**Comment by z-song** [comment]
更新到dev版本，应该已经修复了

**Comment by Ninee** [comment]
更新至`encore/laravel-admin (1.4.x-dev c0c07ec)`版本，好像还是无法使用，奇怪。

**Comment by z-song** [comment]
http://120.26.143.106/admin/system/login-history

demo是基于1.3.x-dev   这个页面的between没有问题啊

**Comment by Ninee** [comment]
刚试过了，还是不行，我看源代码，好像Between这个类并没有很大的变化，是重写了`array_has()`帮助函数吗？T - T。有可能我本地的环境问题，对应的是`laravel (v5.3.30)`版本。

**Comment by z-song** [comment]
贴一下你的代码吧

**Comment by Ninee** [comment]
版本信息`encore/laravel-admin (1.3.x-dev 7182df4)`, laravel版本`laravel (v5.3.30)`,用了laravel自带的用户表，
```
protected function grid()
    {
        return Admin::grid(User::class, function (Grid $grid) {

            $grid->id('ID')->sortable();
            $grid->filter(function ($filter) {
               $filter->disableIdFilter();
               $filter->between('updated_at', 'updated_at')->datetime();
            });
            $grid->created_at();
            $grid->updated_at();
        });
    }
```

**Comment by Ninee** [comment]
按照文档的示例代码又重新跑了一遍，也是不行，T-T。其他都正常。虚拟机和本地windows都试过了，到底是啥原因呢。

**Comment by wonderful60** [comment]
这个问题是怎么解决的，我用的1.4版本遇到了一样的问题，各种尝试还是无效

**Comment by z-song** [comment]
@Ninee @wonderful60 这个问题应该已经修复，https://github.com/z-song/laravel-admin/blob/1.3/src/Grid/Filter.php#L111-L136 对比一下你们的这几行代码，如果不对的话，请更新1.3.x-dev

`composer require encore/laravel-admin 1.3.x-dev`

**Comment by wonderful60** [comment]
确实好了，非常感谢

**Comment by Ninee** [comment]
非常感谢，我自己重新实现了。。大神代码写的真好，看源代码学习到好多东西。。 @z-song
