### ISSUE TITLE
最新版本的覆写内置视图不起作用

### ISSUE THREAD

**Issue by Warrens-yg** [z-song/laravel-admin#4621]
![批注 2020-05-17 165326](https://user-images.githubusercontent.com/46614146/82138911-e04b9000-97d8-11ea-9aeb-dce2d946d62d.jpg)
文档上也被标记了

**Comment by mountainguan** [comment]
我是升级上来的最新版，覆写的效果还在

**Comment by mofengme** [comment]
有修改内置视图的方法吗
