### ISSUE TITLE
多图上传 上传完第一张图片后再上传图片会覆盖第一次上传的图片

### ISSUE THREAD

**Issue by xmy1024** [z-song/laravel-admin#4625]
- Laravel Version: 5.5
- PHP Version:
- Laravel-admin: 1.7.14

### Description:
多图上传 上传完第一张图片后再上传图片会覆盖第一次上传的图片

**Comment by qdladoooo** [comment]
same question :p

**Comment by RoachBully** [comment]
ctrl

**Comment by woodzeng** [comment]
有解决吗？
