### ISSUE TITLE
Export functionality in .pdf

### ISSUE THREAD

**Issue by vcaraseni** [z-song/laravel-admin#4628]
- Laravel Version: 7.10.3
- PHP Version: 7.4.4
- Laravel-admin: 1.7.16

### Description:
Hello there. I am using exporting data in .csv format, but also i want to add possibility to export in .pdf format. Is it possible? I checked the documentation but did not found any info about .pdf.

**Comment by chris-mao** [comment]
Hi, 
Here is another solution, you can add the package **Maatwebsite /
Laravel-Excel** ([https://github.com/Maatwebsite/Laravel-Excel](https://github.com/Maatwebsite/Laravel-Excel)) to your project, it not only supports exporting to excel files, but also supports exporting pdf.  

The above is my personal suggestion, I hope it will help you.

**Comment by vcaraseni** [comment]
@chris-mao thanks for suggestion. I am using export functionality that comes with **laravel-admin** also it creates front-end functionality, generates button for export, filters for different amount of data and the problem is here that i can not setup this - add another format to the end file and possibility to choose in which format to download. But anyway thanks.

**Comment by chris-mao** [comment]
You are welcome. As far as i know, the export functionality of laravel-admin only supports CSV format currently.
