### ISSUE TITLE
Form tags create or update error.

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#463]
Form tags get error.
[![https://gyazo.com/6133b7e6a195a34a0c14b0629d640b1c](https://i.gyazo.com/6133b7e6a195a34a0c14b0629d640b1c.png)](https://gyazo.com/6133b7e6a195a34a0c14b0629d640b1c)

[![https://gyazo.com/d4d4eb3d1aaf280f74c52ccfbd20d38c](https://i.gyazo.com/d4d4eb3d1aaf280f74c52ccfbd20d38c.png)](https://gyazo.com/d4d4eb3d1aaf280f74c52ccfbd20d38c)

[![https://gyazo.com/10ec115168ecc73263e54742589cfd82](https://i.gyazo.com/10ec115168ecc73263e54742589cfd82.png)](https://gyazo.com/10ec115168ecc73263e54742589cfd82)

**Comment by z-song** [comment]
You need to specify a format to store the tags in database, for example if use  `,` to separate tags， then define a mutator and a accessor for `tags` column in model:
```php
public function setTagsAttribute($tags)
{
    if (is_array($tags)) {
        $this->attributes['tags'] = implode(',', $tags);
    }
}

public function getTagsAttribute($tags)
{
    return explode(',', $tags);
}
```
In this way you can use any format you want to store the tags.

**Comment by taimaiduc** [comment]
Thanks it worked
