### ISSUE TITLE
动态表查询

### ISSUE THREAD

**Issue by chris-mao** [z-song/laravel-admin#4630]
- Laravel Version: 7.11.0
- PHP Version:7.2.18
- Laravel-admin: 1.7.16

### Description:

使用Grid制做了一个数据列表展现页面，同时使用了Grid自带的数据筛选功能，现在需要根据筛选条件的不同，动态切换到不同的数据表查询数据，这个功能需要如何实现？

**Comment by z-song** [comment]
```php
if (request('type') == 1) {
        $grid = new Grid(new Model1);
        ...
} else {
        $grid = new Grid(new Model2);
        ....
}

return $grid;
```

**Comment by chris-mao** [comment]
谢谢回复，接着您的回复我想再问一下如何做到在单击Grid自带的数据筛选面板中的“搜索”按钮时，执行上述代码呢？
