### ISSUE TITLE
$grid->model()->take(行数); 不起作用

### ISSUE THREAD

**Issue by lanqiukun** [z-song/laravel-admin#4635]
- Laravel Version: 5.5.49 / 6.18.14
- PHP Version: 7.4.6
- Laravel-admin: 1.7.16

### Description:
$grid->model()->take(行数); 
不起作用
比如我的表里面有50条数据，我只想要取出10条，那$grid->model()->take(10); 不起作用；
还是取出了50条

### Steps To Reproduce:
复现：
1. 创建一个User控制器
2. 用laravel的数据填充对users表填充50条数据
3. 在App\Admin\Controllers\UserController中定义grid()方法：

    protected function grid()
    {
        $grid = new Grid(new User());

        $grid->model()->take(10);

        $grid->column('id', __('Id'));
        $grid->column('name', __('Name'));
        $grid->column('email', __('Email'));
        $grid->column('password', __('Password'));
        $grid->column('remember_token', __('Remember token'));
        $grid->column('created_at', __('Created at'));
        $grid->column('updated_at', __('Updated at'));

        return $grid;
    }

**Comment by topegret** [comment]
please add :`  $grid->disablePagination();`

**Comment by lanqiukun** [comment]
> please add :` $grid->disablePagination();`

It works, thank you~
