### ISSUE TITLE
Please show me, how can I do that

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#4640]
- Laravel Version: 5.7.13
- PHP Version: 7.2.22
- Laravel-admin: #.#.#

### Description: Please show me how can I do that. Click on grid and show the popup image
![image](https://user-images.githubusercontent.com/7189244/82960245-1dd3c880-9fe4-11ea-93aa-8b10dfd00a18.png)

**Comment by z-song** [comment]
https://github.com/z-song/demo.laravel-admin.org/blob/master/app/Admin/Controllers/DocumentController.php#L64
