### ISSUE TITLE
laravel-admin 老版本升级，提交按钮失效

### ISSUE THREAD

**Issue by dongzhouzhoudz** [z-song/laravel-admin#4645]
- Laravel Version: 5.5.49
- 
- PHP Version: 7.3
- Laravel-admin: 1.8.0

### Description:
从 laravel-admin 1.7.16 升级到 1.8.0 后 页面提交按钮失效

**Comment by jxlwqq** [comment]
Admin::script('js code')。

可能你是自定义的一些 js code的，代码没有使用';'作为结束符？

https://github.com/z-song/laravel-admin/issues/4665
