### ISSUE TITLE
标签页表单 第一个标签页必填字段没填 切换其他标签页提交  提交按钮没反应 js 报错

### ISSUE THREAD

**Issue by Mr-wangwei** [z-song/laravel-admin#4650]
- Laravel Version: 7.13.0
- PHP Version: 7.4.6
- Laravel-admin: 1.8.1

### Description:
标签页表单 第一个标签页必填字段没填 切换其他标签页提交  提交按钮没反应 js 报错
An invalid form control with name='id_card' is not focusable.

**Comment by asundust** [comment]
https://github.com/z-song/laravel-admin/issues/3368#issuecomment-660078328
实测有效 @z-song 不知道这是什么bug
