### ISSUE TITLE
地图组件报错 ErrorException In Map.php line 27 :  Illegal string offset 'lat'

### ISSUE THREAD

**Issue by leirenzhichui** [z-song/laravel-admin#466]
我已经在Admin/bootstrap.php 开启map
不过一调用
$form->map('latitude', 'longitude', '位置');
就出现
ErrorException In Map.php line 27 :  Illegal string offset 'lat'

腾讯和Google都试过
我用的版本是1.4.1
难道说，地图组件已经去除了吗

**Comment by z-song** [comment]
没有去除   我这边也没有重现你的问题

**Comment by leirenzhichui** [comment]
这就奇怪了，难道是我哪里没弄对吗？
我上面的步骤哪里有问题吗？

我看代码，$this->column 这个在父类Field里面初始化为字符串，可是在Map里面直接用作数组$this->column['lat']，这样子没问题的吗？

**Comment by z-song** [comment]
看代码  https://github.com/z-song/laravel-admin/blob/1.4/src/Form/Field/Map.php#L25-L30

经纬度字段分别取map的第一二个参数

**Comment by leirenzhichui** [comment]
按道理来说，父类Field的$column是字符串，直接在Map用作数组应该是会报PHP warning的，作者君做了什么抑制错误，所以看不到我那个错误吗
![Uploading image.png…]()

**Comment by leirenzhichui** [comment]
我抑制错误之后地图组件倒是能显示了

**Comment by leirenzhichui** [comment]
不过即使组件能显示了，可是获取不到经度纬度，都是0

**Comment by leirenzhichui** [comment]
我在Map里面把$column初始化成一个空数组，再进行
$this->column['lat'] = $column;
$this->column['lng'] = $arguments[0];
就没问题了

**Comment by z-song** [comment]
提交了个commit修复这个问题，多谢提醒
