### ISSUE TITLE
请问一下1.7 到 1.8 版本有哪些更新，从哪里看

### ISSUE THREAD

**Issue by songlen** [z-song/laravel-admin#4664]
请问一下1.7 到 1.8 版本有哪些更新，从哪里看？文档和github上找了一遍也没找到，都不敢更新

**Comment by songlen** [comment]
找到了

**Comment by songlen** [comment]
> 请问一下1.7 到 1.8 版本有哪些更新，从哪里看？文档和github上找了一遍也没找到，都不敢更新

**Comment by songlen** [comment]
看到了文档里只有增加的功能，没看到修复了哪些bug

**Comment by se7en3** [comment]
更新到1.8好像switch样式垮了~

**Comment by songlen** [comment]
> 更新到1.8好像switch样式垮了~

好怕怕哦，我都不敢升级，新版本有我要的功能

**Comment by faydanube** [comment]
…… 这次更新的确很多bug~~~ 准备继续用1.7.x……
