### ISSUE TITLE
belongsToMany 排序

### ISSUE THREAD

**Issue by qq447665722** [z-song/laravel-admin#4666]
- Laravel Version: 7.13.0
- PHP Version:7.2.10
- Laravel-admin: 1.8.1

### Description:
想问一下,表单的belongtomany可以做排序吗
类似
![image](https://user-images.githubusercontent.com/14967427/83493675-b20fc500-a4e7-11ea-9abd-9138b0b34a00.png)

**Comment by qiuyuhome** [comment]
我也遇到了这样的需求. 想要一个设置排序的功能. 排序字段在关系表中.
