### ISSUE TITLE
$form->embeds,$form->table闭包内使用$fom->file()问题

### ISSUE THREAD

**Issue by gai871013** [z-song/laravel-admin#4670]
- Laravel Version:  6.18.18
- PHP Version:7.3.16
- Laravel-admin: v1.8.1

### Description:
代码如下：
```
$form->embeds('config', '设置', function ($form) {
                $form->switch('use_sandbox', '沙箱模式')->default(0);
                $form->text('app_id', '客户端AppId');
                $form->text('mch_id', '微信支付商户号');
                $form->text('key', '商户支付密钥Key');
                $form->file('cert_path', '支付证书cert')->uniqueName();
                $form->file('key_path', '支付证书key')->uniqueName();
                $form->text('notify_url', '异步通知地址');
            });
```

问题1.如下代码上传文件会上传两份

![image](https://user-images.githubusercontent.com/3212029/83594905-04f28680-a593-11ea-9a83-71127618d5ce.png)

问题2.编辑-不选择文件-保存会导致已保存的数据情况
这个是选择文件后数据库保存的数据
![image](https://user-images.githubusercontent.com/3212029/83594960-379c7f00-a593-11ea-9670-780e2f8d796d.png)
这个是编辑-不选择文件保存后的数据
![image](https://user-images.githubusercontent.com/3212029/83595004-57cc3e00-a593-11ea-8d07-22b5a03b03c0.png)

不在embeds闭包内的file上传路径不存在问题

`同样问题还出现在数据表单（App\Admin\Forms\Model\Class）内使用file组件`

**Comment by gai871013** [comment]
使用表单回调解决
```php
        $form->saving(function (Form $form) {
            if ($id = $form->model()->id) {
                session(['payment_db_' . $id => Payment::query()->find($id)]);
            }
        });


        $form->saved(function (Form $form) {
            $id = $form->model()->id;
            if ($old = session('payment_db_' . $id)) {
                $form->model()->config = array_merge($old->config, $form->model()->config);
                $form->model()->save();
            }
        });
```

**Comment by wangzhixiang001** [comment]
public function setJsonAttribute($content)
    {
        $old_content = json_decode($this->attributes['json'], true);
		$this->attributes['json'] = json_encode(array_merge($old_content, $content));
    }
