### ISSUE TITLE
1.8 新版本增加的表单联动功能，不能显示默认选中的表单项

### ISSUE THREAD

**Issue by songlen** [z-song/laravel-admin#4684]
1.8 新版本增加的表单联动功能，比如radio 表单设置默认选中第一个，但是第一个对应的联动表单项不显示

$form->radio('use_template', '使用模板')->options([1 => '基础模板', 2 => '服装', 3 => '不用'])
       ->checked('基础模板')
        ->when(1, function (Form $form) { 

            $form->text('name', '姓名');
            $form->text('idcard', '身份证');

        })->checked('基础模板')->when(2, function (Form $form) { 

            $form->text('name', '姓名');
            $form->text('passport', '护照');

        });
![微信截图_20200609154736](https://user-images.githubusercontent.com/12892457/84120561-93ba4400-aa68-11ea-9eaf-72da1189b7d9.png)

**Comment by NaturalGao** [comment]
解决了@下我

**Comment by Cuifc** [comment]
> 1.8 新版本增加的表单联动功能，比如radio 表单设置默认选中第一个，但是第一个对应的联动表单项不显示，真是悲哀。。做一个功能不做到极致，用着真费劲
> 
> $form->radio('use_template', '使用模板')->options([1 => '基础模板', 2 => '服装', 3 => '不用'])
> ->when(1, function (Form $form) {
> 
> ```
>         $form->text('name', '姓名');
>         $form->text('idcard', '身份证');
> 
>     })->checked('基础模板')->when(2, function (Form $form) { 
> 
>         $form->text('name', '姓名');
>         $form->text('passport', '护照');
> 
>     });
> ```
> 
> ![微信截图_20200609154736](https://user-images.githubusercontent.com/12892457/84120561-93ba4400-aa68-11ea-9eaf-72da1189b7d9.png)

这个心态建议你还是不要用了，多看下源码，能自己解决就自己解决，不能解决就虚心请教下！

**Comment by songlen** [comment]
> > 1.8 新版本增加的表单联动功能，比如radio 表单设置默认选中第一个，但是第一个对应的联动表单项不显示，真是悲哀。。做一个功能不做到极致，用着真费劲
> > $form->radio('use_template', '使用模板')->options([1 => '基础模板', 2 => '服装', 3 => '不用'])
> > ->when(1, function (Form $form) {
> > ```
> >         $form->text('name', '姓名');
> >         $form->text('idcard', '身份证');
> > 
> >     })->checked('基础模板')->when(2, function (Form $form) { 
> > 
> >         $form->text('name', '姓名');
> >         $form->text('passport', '护照');
> > 
> >     });
> > ```
> > 
> > 
> > ![微信截图_20200609154736](https://user-images.githubusercontent.com/12892457/84120561-93ba4400-aa68-11ea-9eaf-72da1189b7d9.png)
> 
> 这个心态建议你还是不要用了，多看下源码，能自己解决就自己解决，不能解决就虚心请教下！

我在这里问问题，你哪里看出来我心态不正了，提问题一是看别人有没有好的办法解决，二是希望下个版本能够改善问题。你这个回答我建议你你还是删除掉，态度有问题！

**Comment by kwinH** [comment]
@z-song 麻烦处理一下
