### ISSUE TITLE
Model Form relationship 404 not found in docs

### ISSUE THREAD

**Issue by Bluefitdev** [z-song/laravel-admin#4687]
<img width="808" alt="Screen Shot 2020-06-11 at 12 34 20 pm" src="https://user-images.githubusercontent.com/56941349/84338679-0bf74580-abe0-11ea-9a2d-8bef79064041.png">

Docs for model form shows 404 not found

Also happens to `model-form-linkage`. Seems to be showing the docs for zh / Chinese?

Is there any for english?

Thanks!

**Comment by bytebrain** [comment]
https://laravel-admin.org/docs/#/en/model-form-linkage

**Comment by Bluefitdev** [comment]
<img width="1230" alt="Screen Shot 2020-06-17 at 9 19 39 am" src="https://user-images.githubusercontent.com/56941349/84837603-df2dad00-b07b-11ea-81ef-e0b5963d4471.png">

First when you navigate to docs you can't find it on the tree (left hand side)

<img width="1250" alt="Screen Shot 2020-06-17 at 9 20 07 am" src="https://user-images.githubusercontent.com/56941349/84837623-ea80d880-b07b-11ea-896c-8d4146e346b3.png">

This is when I clicked your link, its changed

<img width="1246" alt="Screen Shot 2020-06-17 at 9 20 33 am" src="https://user-images.githubusercontent.com/56941349/84837639-f2407d00-b07b-11ea-8c92-1a186a66d123.png">

Finally the relationship only pops up when I clicked your link. If you go to docs home without clicking your link the tree on left hand side is missing

**Comment by Bluefitdev** [comment]
<img width="1278" alt="Screen Shot 2020-06-17 at 9 24 41 am" src="https://user-images.githubusercontent.com/56941349/84837860-6e3ac500-b07c-11ea-8c91-1b0cc2b82b3b.png">

@z-song I think the link should just be `#/en/model-form-linkage` and `#/en/model-form-relationships`

But i can't seem to find where you put the docs to do pull request. The docs folder here seems to be outdated?

If any of you can do pull request then that'll be great..

**Comment by z-song** [comment]
@Bluefitdev Fixed now
