### ISSUE TITLE
使用外部数据源，点击删除按钮时，提示Non-static method App\Models\HotVideo::findOrFail() should not be called statically 

### ISSUE THREAD

**Issue by fsf11080612** [z-song/laravel-admin#4688]
- Laravel Version: 5.5
- PHP Version:7.3..14
- Laravel-admin: 1.7

### Description:
使用外部数据源，我重写了findOrFail方法，点击删除按钮时，提示Non-static method App\Models\HotVideo::findOrFail() should not be called statically 

### Steps To Reproduce:
重写后的findOrFail方法如下：
![image](https://user-images.githubusercontent.com/12817128/84343280-4bbb2e80-abda-11ea-9bff-62450012976b.png)

![image](https://user-images.githubusercontent.com/12817128/84343057-b7e96280-abd9-11ea-9783-1ed36d6b8db5.png)

![image](https://user-images.githubusercontent.com/12817128/84343069-c20b6100-abd9-11ea-9b7d-9d3402154957.png)

**Comment by ieliwb** [comment]
@fsf11080612 大佬怎么解决的

**Comment by fsf11080612** [comment]
> @fsf11080612 大佬怎么解决的

有3个地方做了修改
1、修改对应的Model模型，app/Models/HotVideo.php
`public function findOrFail($id)
    {
        $handler = new HotVideoHandler();
        $result = $handler->video_detail($id);
        $data = isset($result['data']['video']) ? $result['data']['video'] : [];

        return static::newFromBuilder($data);
    }`

2、增加了新定义的删除菜单
![image](https://user-images.githubusercontent.com/12817128/106097074-a2797680-6171-11eb-9395-8ad6af59672c.png)


3、删除菜单我是重新定义的，没有使用框架自带的菜单
我定义的删除菜单路径是app/Admin/Controllers/HotVideoController.php，重写了里面的retrieveModel方法
`// 覆盖retrieveModel方法
    public function retrieveModel(Request $request)
    {
        if (!$key = $request->get('_key')) {
            return false;
        }

        $modelClass = str_replace('_', '\\', $request->get('_model'));

        if ($this->modelUseSoftDeletes($modelClass)) {
            return $modelClass::withTrashed()->findOrFail($key);
        }

        $obj = new $modelClass();
        return $obj->findOrFail($key);
    }`

**Comment by ieliwb** [comment]
谢谢，有点复杂，我准备加2个字段解决
