### ISSUE TITLE
本地服务器使用网页脚手架时报错

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#469]
InvalidArgumentException in Crawler.php line 566:
The current node list is empty.

请问如何解决？

**Comment by z-song** [comment]
没有能重现这个问题

**Comment by sayawan** [comment]
Had the same issue. The reason was:
I have two different forms for creating and editing 

```
protected function form() {}
protected function update() {}
```

renaming `update` to something else as `updateForm` did the job for my case.
