### ISSUE TITLE
1.8版本 hasMany 新增时报错：id插入为空

### ISSUE THREAD

**Issue by songlen** [z-song/laravel-admin#4694]
1.8版本 hasMany 新增时报错：id插入为空

**Comment by Mr-wangwei** [comment]
这个 bug 修复了 https://github.com/z-song/laravel-admin/pull/4669

**Comment by songlen** [comment]
看到了，但是感觉修复的方法不合适，z-song 原本是将$model->fill() 改成了$model->setAttribute() 的形式赋值，修复bug的人又给改回去了 我认为这样改比较妥：
````
                        foreach ($related as $colum => $value) {
                            $value === '' || $child->setAttribute($colum, $value);
                        }
````

**Comment by songlen** [comment]
> 这个 bug 修复了 #4669
大佬，问一下，我在本地用composer update encore/laravel-admin 更新后，为啥看不到代码变化，难道更新代码不是这个命令吗

**Comment by Mr-wangwei** [comment]
@songlen 清除 composer 缓存试试 composer clearcache

**Comment by songlen** [comment]
> @songlen 清除 composer 缓存试试 composer clearcache

刚试了下，代码还是没变化。 我把composer镜像改成了阿里云的，不知道跟这个有没有关系

**Comment by Mr-wangwei** [comment]
> 看到了，但是感觉修复的方法不合适，z-song原本是将$ model-> fill（）改成$ model-> setAttribute（）的形式赋值，修复bug的人又给改回去了我认为这样改比较妥：
> 
> ```
>                         foreach ($related as $colum => $value) {
>                             $value === '' || $child->setAttribute($colum, $value);
>                         }
> ```

这样修改有个 bug ，修改某个字段为空时，就会修改没有效果

**Comment by songlen** [comment]
> > 看到了，但是感觉修复的方法不合适，z-song原本是将$ model-> fill（）改成$ model-> setAttribute（）的形式赋值，修复bug的人又给改回去了我认为这样改比较妥：
> > ```
> >                         foreach ($related as $colum => $value) {
> >                             $value === '' || $child->setAttribute($colum, $value);
> >                         }
> > ```
> 
> 这样修改有个 bug ，修改某个字段为空时，就会修改没有效果

哦是是是，那从循环里单独对id做一下判断也行，或者就用fill吧，不过需要从model里加fillable

**Comment by Mr-wangwei** [comment]
> > @songlen 清除 composer 缓存试试 composer clearcache
> 
> 刚试了下，代码还是没变化。 我把composer镜像改成了阿里云的，不知道跟这个有没有关系

更新到开发版本
composer require encore/laravel-admin:dev-master -vvv
