### ISSUE TITLE
checkbox 应该象checked一样增加：readonly和disabled 两个方法

### ISSUE THREAD

**Issue by neatstudio** [z-song/laravel-admin#4695]
因为在实际应用中，有部分数据是不允许被 checked的。或者已经checked的不能被取消。所以需要这两个

**Comment by songlen** [comment]
disabled 目前可以啊

**Comment by neatstudio** [comment]
disabled只能整体啊。我只要指定value的

**Comment by neatstudio** [comment]
难道我姿势不对？

**Comment by songlen** [comment]
> disabled只能整体啊。我只要指定value的

哦，明白你的意思了，这个貌似真没有

**Comment by neatstudio** [comment]
目前我是自己写了个文件用Form::extend进行处理。但在加readonly的时候无法使用
 
应该是模板解析的问题，即使我设定 onclick="return false;"，但显示在页面中的时候就会变成：onclick=""return " false"，类似这样。如果我在 return false上不加引号，就会输出成：onclick="return" falsse 。

估计是对属性或者其他元素中的空格进行了处理。导致失败【最后，我只是自己加了一个disabled】。
