### ISSUE TITLE
请教关于权限控制的用法

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#47]
文档有提到可以在控制器类内进行权限控制，这样做的有一个小问题，后台菜单对所有用户都默认显示了，点击进去后才会执行权限控制代码。如果需要管理用户登录后立即判断管理权限并显示有权限的菜单选项，应该需要如何操作?

**Comment by z-song** [comment]
请问你的laravel版本？

**Comment by windpursuer** [comment]
秒回呀，厉害，5.2

**Comment by windpursuer** [comment]
哦哦，找到方法了，原来menu有rule用法。另外问一下，是不是创建新权限角色，都需要到menu.php进行配置？有更简单的用法吗？

**Comment by z-song** [comment]
刚好这几天添加了新功能，使用最新的代码不用在`menu.php`里面配置菜单了

有配置管理页面：
`http://120.26.143.106:84/admin/auth/menu` 账号/密码 admin/admin

**Comment by windpursuer** [comment]
好的，这个后台确实很好用，感谢开源出来

**Comment by z-song** [comment]
欢迎提issue，欢迎提pull request！

**Comment by hdnlove** [comment]
虽然菜单角色控制已经添加，但是没有起到实际的效果，我通过修改如下文件完成，如有好的解决方案一起讨论。
修改/vendor/encore/laravel-admin/src/Auth/Database/AdminPermission.php类中的visible()方法
public function visible($roles)
    {
        if($this->isAdministrator()){
            return true;
        }

        if (count($roles) == 0) {
            return false;
        }

        $roles = array_column($roles, 'slug');

        if ($this->inRoles($roles) || $this->isAdministrator()) {
            return true;
        }

        return false;
    }
