### ISSUE TITLE
How can I get the model  in the form method

### ISSUE THREAD

**Issue by lyd600lty** [z-song/laravel-admin#470]
How can I get the model in the form method? `$form->model()` seems not working.

**Comment by z-song** [comment]
Works fine for me use `$form->model()`, show me your code?

**Comment by lyd600lty** [comment]
In `form()` function, the model has no form data, Maybe I can get the form data in `$form->builder()`?

**Comment by pierrocknroll** [comment]
Did you found a solution ?

**Comment by OppPMatos** [comment]
$form->model()->first()->collumn_name
