### ISSUE TITLE
多图上传multipleImage无效

### ISSUE THREAD

**Issue by BinZhiZhu** [z-song/laravel-admin#4701]
- Laravel Version: 5.8
- PHP Version:
PHP 7.2.29 (cli) (built: Mar 19 2020 11:18:28) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.2.0, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.2.29, Copyright (c) 1999-2018, by Zend Technologies
### Description:
        $form->multipleImage('pictures', '图片')->removable()->sortable();
   多图上传这样设置之后无效，体验上还是单图上传

**Comment by songlen** [comment]
这个插件如果多图上传不能一个一个的选，必须一下选择多张才行

**Comment by BinZhiZhu** [comment]
> 这个插件如果多图上传不能一个一个的选，必须一下选择多张才行

还真的是  = = 哈哈 ☺️
