### ISSUE TITLE
1.8表单联动设置验证规则后无法提交

### ISSUE THREAD

**Issue by 38757974** [z-song/laravel-admin#4703]
- Laravel Version: 5.8
- PHP Version:7.3
- Laravel-admin: 1.8

### 设置了required后，选择任意一个后无法提交。无法提交
 $form->radio('project_category', '项目类型')
            ->options(ProjectModel::$CATEGORY)
            ->when(1, function (Form $form) {
                $form->text('article.title', '文章标题')->required();
            })
            ->when(2, function (Form $form) {
                $form->text('video.title', '视频标题')->required();
            });

### Steps To Reproduce:
[](url)

**Comment by kaodouqifei** [comment]
有没有解决方法啊

**Comment by zairl23** [comment]
同样的情况，主要是联动时只是做了hide处理，那些hide掉的表单输入项的验证规则依然是有效的，即使是不可见的情况。

**Comment by terranc** [comment]
无解吗
