### ISSUE TITLE
請問一下如果不用tree 

### ISSUE THREAD

**Issue by ticky520** [z-song/laravel-admin#4704]
- Laravel Version: 5.8
- PHP Version:7.3
- Laravel-admin: 1.8.1

### Description:
請問一下如果不用tree , 點選台北能傳值到下一頁?  進到下一頁後傳送台北的值做列表

![image](https://user-images.githubusercontent.com/10771089/84750984-9d0a5a00-afee-11ea-895f-e76dc695b3e7.png)

**Comment by acclea** [comment]
我是这么做的
A 页面使用  grid() 方法
$grid->column('title', __('city'))->width(550)->display(function ($title) {
            return "<a href='".url('/admin/B?city_id='.$this->id)."' target='_blank'>$title</a>";
        })->copyable();


B 页面使用  grid() 方法
$grid->filter(function($filter){
            // 去掉默认的id过滤器
            $filter->disableIdFilter();

            // 在这里添加字段过滤器
            $filter->equal('que_id', '问答ID');
        });

 $grid->disableFilter();
