### ISSUE TITLE
Radio::when does not exist.

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#4706]
- Laravel Version: 6.18
- PHP Version:7.2
- Laravel-admin: v1.7.14

### Description:
Radio::when does not exist.

### Steps To Reproduce:
使用以下操作报错，Radio::when does not exist.
并且 radioButton、radioCard 这个两个也不能使用

$form->radio('nationality', '国籍')
    ->options([
        1 => '本国',
        2 => '外国',
    ])->when(1, function (Form $form) { 

        $form->text('name', '姓名');
        $form->text('idcard', '身份证');

    })->when(2, function (Form $form) { 

        $form->text('name', '姓名');
        $form->text('passport', '护照');

    });

在线等，挺急的

**Comment by z-song** [comment]
更新到`1.8`
