### ISSUE TITLE
tree model

### ISSUE THREAD

**Issue by xiaalngf** [z-song/laravel-admin#471]
在tree后面，增加一个action . 
![image](https://cloud.githubusercontent.com/assets/8611771/23362868/b9fd3c44-fd32-11e6-9a97-77689f06ebef.png)
想增加一个"查看"的按键。

**Comment by z-song** [comment]
暂时还没有做到这里，你要是要使用可以先修改view文件 `vendor/encore/laravel-admin/views/tree/branch.blade.php`

**Comment by zgl-totti** [comment]
这个tree能不能加条件查询

**Comment by Jackfinal** [comment]
同问，能不能加查询条件
