### ISSUE TITLE
修改是文件后缀，获取的是添加是上传的文件后缀

### ISSUE THREAD

**Issue by weiyandong** [z-song/laravel-admin#4710]
- Laravel Version: 6.2.0
- PHP Version:
- Laravel-admin: 1.8

### Description:
`
// 自定义文件名
            ->name(function ($file) {
                $filename=date('YmdHis').Str::random(10);
                return $filename.'.'.$file->guessExtension();
            });
`

### Steps To Reproduce:
添加数据是正常。修改数据，$file->guessExtension() 获取的是添加上传的文件后缀。
如：上传提交zip文件，修改提交xlsx提交后文件还是.zip后缀。

**Comment by Gping123** [comment]
好像name方法，edit时候，偶尔也会出现不生效的问题。估计你也是遇到了跟我同样的问题
