### ISSUE TITLE
Using intervention / image with laravel-admin

### ISSUE THREAD

**Issue by DAGpro** [z-song/laravel-admin#4711]
- Laravel Version: 7.15.0
- PHP Version: 7.4
- Laravel-admin: 1. 8. 1

### Description:
        $form->image('image', __('Image'))
            ->move('/blog')
            use
            ->crop(600, 400)
             or
            ->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            })

  we get an exception

 NotSupportedException In AbstractEncoder.php line 173 :
  Encoding format (tmp) is not supported.

### Steps To Reproduce:
        $form->image('image', __('Image'))
            ->move('/blog')
            use
            ->crop(600, 400)
             or
            ->resize(300, null, function ($constraint) {
                $constraint->aspectRatio();
            })

in the Field / Image class, the prepare method is called which uses the callInterventionMethods method from the ImageField trait.
In it, the save method from Intervention\Image is passed the path to a temporary file, which leads to an exception

did everything according to the documentation in Chinese.

**Comment by DAGpro** [comment]
I studied the sources a bit if the save ($ target) method is passed the image extension save ($ target, null, $ format), the file is saved without errors

**Comment by vladrub** [comment]
still not fixed? I get the same error...
