### ISSUE TITLE
更新到`1.8`

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#4712]
更新到`1.8`

_Originally posted by @z-song in https://github.com/z-song/laravel-admin/issues/4706#issuecomment-645372621_

**Comment by acclea** [comment]
有几个页面模板自定义修改了，更新怎么避免覆盖自定义模板（还涉及到对模板组件的管理），还有我可以在create、edit 中添加自定义参数么

**Comment by songlen** [comment]
> 有几个页面模板自定义修改了，更新怎么避免覆盖自定义模板（还涉及到对模板组件的管理），还有我可以在create、edit 中添加自定义参数么

修改模板内容时把要修改的文件单拉出来修改，不能在包文件里修改

**Comment by acclea** [comment]
![image](https://user-images.githubusercontent.com/19919905/85088173-0b7b3200-b212-11ea-912f-fd418a36357d.png)
问一下，那向这样添加一个可以在控制器可以关闭/打开的按钮怎么把要修改的文件单独拿出去修改，谢谢

**Comment by acclea** [comment]
问一下，那如果需要加一个像提交按钮，可以在控制器中打开/关闭的按钮，怎么把文件拉出来修改，谢谢
