### ISSUE TITLE
文件上传目录能不能用form其他字段作为dir

### ISSUE THREAD

**Issue by YangZhengHuan** [z-song/laravel-admin#4716]
- Laravel Version: 6.x
- PHP Version:
- Laravel-admin: v1.8.0

### Description:
有一个需求，代表表达我的意思，希望大家帮忙看一下，这个dir获取的是空，代码如下：

![image](https://user-images.githubusercontent.com/29086696/85106518-e81aac00-b23e-11ea-9eba-e49940866f2f.png)
![Uploading image.png…]()

**Comment by songlen** [comment]
这dir是干什么用的

**Comment by YangZhengHuan** [comment]
@songlen 这个dir就是上传到disk的 目录，好比 cosv5.xxx.cn/dir/xxx.jpg
