### ISSUE TITLE
表单中属性名为invoice导致页面样式出错

### ISSUE THREAD

**Issue by mobileliker** [z-song/laravel-admin#4717]
- Laravel Version: 5.5
- PHP Version:7.2
- Laravel-admin: 1.7.X

### Description:
创建页面是代码为一下内容是：
```php
                $form->text('invoice', __('Invoice'));
```

会导致样式出错，经查为生产的input添加了名为invoice的class
```
class="form-control invoice"
```
导致使用了原有的invoice的样式
```
.invoice {
    position: relative;
    background: #fff;
    border: 1px solid #f4f4f4;
    padding: 20px;
    margin: 10px 25px;
}
```

PS：图片一直上传不了，只能外链一个。
![https://s1.ax1x.com/2020/06/19/NKcXHs.jpg]()

### Steps To Reproduce:

(1)去除新增invoice到class，估计会牵一发动全身
(2)做一点特殊处理，屏蔽某些关键class

**Comment by songlen** [comment]
这种的问题建议还是自己去适应框架比较好，你既然找到了问题所在，就自己改个name吧，框架用的class不可能避免与个别人冲突，我也遇到过row字段的冲突，自己改下就好了
