### ISSUE TITLE
Laravel Framework 7.16.1 is not supported?

### ISSUE THREAD

**Issue by ShunnMatsumura** [z-song/laravel-admin#4725]
- Laravel Version: 7.16.1
- PHP Version: 7.4.7
- Laravel-admin: #.#.#

### Description:
When I hit the following command with docker, I get an error reading the json file and cannot install . Unsupported?

`docker-compose exec myApp composer require encore/laravel-admin`

Here's the errors.

```
[Composer\Downloader\TransportException]
  The "https://repo.packagist.org/p/provider-2018%244c49a1daaa85c182fe3e399404805dab0f4ca0a260de6d95e0c988
  a14cec2b29.json" file could not be downloaded: failed to open stream: Connection refused
```

**Comment by z-song** [comment]
Internet problem
