### ISSUE TITLE
Validate edited data

### ISSUE THREAD

**Issue by gidaban** [z-song/laravel-admin#473]
I have rule in form
`$form->text('title')->rules('required|max:255|unique:blogs');`

It working fine if i add new record but not if i want to edit post.

Any solution for it?

**Comment by Fisiu** [comment]
What controller do you use? https://laravel.com/docs/5.4/validation

**Comment by gidaban** [comment]
i use BlogController make by admin:make
is same for adding and edit posts.

**Comment by Fisiu** [comment]
Then, show its content.

**Comment by edwinhuish** [comment]
you can make 2 different form() for edit() and update().

**Comment by yang5664** [comment]
maybe problem is Validation Rule of "unique:blogs", you may search previous posts for solve the problem. please ref #119
