### ISSUE TITLE
$form->select() 搜索才会触发ajax请求

### ISSUE THREAD

**Issue by Ambition9186** [z-song/laravel-admin#4731]
- Laravel Version: 7.13.0
- PHP Version:7.2.9
- Laravel-admin: 1.8.1

### Description:
$form->select('series_id')->options(function ($series_id){
            return Serie::options($series_id);
        })->ajax('/admin/api/series/series');

加载时没有请求ajax  但搜索才会请求ajax  这是什么情况呢

**Comment by ichynul** [comment]
默认是至少输入一个字符搜索，配置一下：
`->config('minimumInputLength', '0')->ajax('/admin/api/series/series')`

**Comment by Ambition9186** [comment]
> 默认是至少输入一个字符搜索，配置一下：
> `->config('minimumInputLength', '0')->ajax('/admin/api/series/series')`

非常感谢

**Comment by wjp8057** [comment]
> > 默认是至少输入一个字符搜索，配置一下：
> > `->config('minimumInputLength', '0')->ajax('/admin/api/series/series')`
> 
> 非常感谢

非常感谢，找了很久，终于可以了
