### ISSUE TITLE
Google Login in Laravel Admin | Custom UserProvider | Not Working

### ISSUE THREAD

**Issue by varshneygaurav** [z-song/laravel-admin#4738]
- Laravel Version: 7.15.0
- PHP Version: PHP/7.3.19
- Laravel-admin: 1.8.1

### Description:
Task: I want to add the google login functionality

- i have added Socialite done the config and created a route and callback
Callback Code: 
$existingUser = Administrator::where('email', $user->email)->first();
if($existingUser){
                // log them in
                Auth::loginUsingId($existingUser->id);
                //auth()->login($existingUser, true);
            } 

- Custom User Provider added as per documentaion -> CustomUserProvider implements UserProvider

 public function retrieveById($identifier)
    {
        $user = Administrator::where('id','=',$identifier)->first();
        return isset($user)?$user:null;
    }

- Email field added to admin_users table

But Still redirecting me to Login Page -> /admin/auth/login

**Comment by Webakula** [comment]
> * Laravel Version: 7.15.0
> * PHP Version: PHP/7.3.19
> * Laravel-admin: 1.8.1
> 
> ### Description:
> Task: I want to add the google login functionality
> 
> * i have added Socialite done the config and created a route and callback
>   Callback Code:
>   $existingUser = Administrator::where('email', $user->email)->first();
>   if($existingUser){
>   // log them in
>   Auth::loginUsingId($existingUser->id);
>   //auth()->login($existingUser, true);
>   }
> * Custom User Provider added as per documentaion -> CustomUserProvider implements UserProvider
> 
> public function retrieveById($identifier)
> {
> $user = Administrator::where('id','=',$identifier)->first();
> return isset($user)?$user:null;
> }
> 
> * Email field added to admin_users table
> 
> But Still redirecting me to Login Page -> /admin/auth/login
> 
> ### Steps To Reproduce:

Have you tried to log in using guard `admin`?
i.e.
`auth('admin')->login($user, true)`
