### ISSUE TITLE
Is is possible to access model()->fields under $form->html();

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#474]
Is is possible to access model()->fields under $form->html();
Example: 
$form->html($form->model()->id);

**Comment by z-song** [comment]
I didn't implemented yet in html field.

currently you can use display instead:

```php
$form->display('xxx')->with(function () {
    return $this->id;
});
```
The object `$this` was bound as `$form->model()`.

**Comment by smuzammilali** [comment]
Thanks display works!
