### ISSUE TITLE
Model grid row actions : Action button append/prepend not working 

### ISSUE THREAD

**Issue by hatsolutions003** [z-song/laravel-admin#4740]
- Laravel Version: 7.0.1
- PHP Version: 7.2.5
- Laravel-admin: 1.8.1
### Description:
i want to add a new button in action buttons list to open a new page with it but didn't show when I add the code snippet.

Code used in $grid:
$grid->actions(function ($actions) {
    // append an action.
    $actions->append('<a href=""><i class="fa fa-eye"></i></a>');
});

I have var_dump($actions) the output after this code and it shows that there is an append in the object now but it didn't show in the buttons list in view.
Please see attachment (issue.jpg) for the output of var_dump($actions);

### Steps To Reproduce:
Just add actions button code in grid section and check output.

Please help in this issue.

Thanks[
![issue](https://user-images.githubusercontent.com/66880511/85923594-c86e2e00-b8a5-11ea-956a-f3d0e2f5a506.PNG)
](url)

**Comment by mhanoglu** [comment]
You can use new method for this.
Documentation here: https://laravel-admin.org/docs/#/en/model-grid-custom-actions?id=row-action

**Comment by hatsolutions003** [comment]
Thanks, its working
