### ISSUE TITLE
JSON格式字段处理 BUG

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#4744]
- Laravel Version: 6.18.3
- PHP Version: 7.2.31
- Laravel-admin: 1.8

### Description:
list保存数据后，无法显示，二维数组如果只有一列，每次修改新增就会把历史数据丢失（删除）
https://laravel-admin.org/docs/zh/model-form-json-fields

### Steps To Reproduce:
1、list保存为json 数据后，再次编辑则无法显示，模板报错
2、二维数组如果只有一列，每次修改新增就会把历史数据丢失（删除）

**Comment by asen477** [comment]
嗯，是的，我也遇到这个问题了
只要编辑新增数据，历史数据就会顶掉。

**Comment by asen477** [comment]
https://laravel-admin.org/docs/zh/model-form-json-fields#%E4%BA%8C%E7%BB%B4%E6%95%B0%E7%BB%84
二维数组这块的js修改在哪里
