### ISSUE TITLE
【修复 BUG】  二维数组如果只有一列，每次修改新增就会把历史数据丢失（因为索引重新开始计数，旧数据会删除）

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#4745]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: 1.8

### Description:
JSON   二维数组如果只有一列，每次修改新增就会把历史数据丢失（删除）

### Steps To Reproduce:
找到以下文件，
vendor\encore\laravel-admin\src\Form\Field\HasMany.php

大概537行左右，这个方法
protected function setupScriptForTableView($templateScript)

把
var index = 0; 
修改为
var index = $('.has-many-{$this->column}-form').length;

**Comment by artisanz** [comment]
楼主的方法还是有点问题。
把
var index = 0;
$('#has-many-{$this->column}').on('click', '.add', function () {
改成
$('#has-many-{$this->column}').on('click', '.add', function () {
var index = $('.has-many-{$this->column}-form').length;

**Comment by imnpc** [comment]
这个bug一直没有进行修复
