### ISSUE TITLE
提交表单必填项未填写的情况下点击提交，页面没反应，console有报错

### ISSUE THREAD

**Issue by smm229** [z-song/laravel-admin#4747]
- Laravel Version: 5.8.*
- PHP Version: 7.2
- Laravel-admin: 1.7.0

### Description:
An invalid form control with name='video_url' is not focusable.

### Steps To Reproduce:
表单使用form->tab，各tab皆有必填项，所有内容都不填写，直接点击提交即可复现

**Comment by acclea** [comment]
+1

**Comment by asundust** [comment]
https://github.com/z-song/laravel-admin/issues/3368#issuecomment-660078328
本人也遇到了 试了这个方法可以过
