### ISSUE TITLE
改 number 插件可以为负数的问题

### ISSUE THREAD

**Issue by 14718011108** [z-song/laravel-admin#475]
![4 mgu6azkbuf7gjc4mj mv6](https://cloud.githubusercontent.com/assets/24646165/23388995/3e63a5be-fda0-11e6-9439-9fef8b8850a1.png)
![1lh4jvhkx u8ffpu3v gf](https://cloud.githubusercontent.com/assets/24646165/23388996/444b128c-fda0-11e6-89da-001c04c4135c.png)
 这个input的样式 要去哪里改  我找了/packages/admin/number-input/bootstrap-number-input.js
和Number.php 都没有

我看了/packages/admin/number-input/bootstrap-number-input.js 里面有不能为负数的  判断没有执行到

**Comment by 14718011108** [comment]
form/field  里面 少了这个   所以   可以为负数，     群主加上吧@z-song 
$this->prepend('')->defaultAttribute('min', '0');
![Uploading G01$K3H_1KC4NMU6S{O55SI.png…]()

**Comment by z-song** [comment]
`$form->number('count')->attribute('min', 0);`

**Comment by 14718011108** [comment]
，，，知道真相的我       眼泪掉下来，，，，，这玩意  也可以加属性值，，，，，  明明就用过为什么  这是为什么，，，，，，
