### ISSUE TITLE
表单联动的bug

### ISSUE THREAD

**Issue by TottyAndBaty** [z-song/laravel-admin#4754]
- Laravel Version: 6.18.18
- PHP Version:7.3.17
- Laravel-admin: 1.8

### Description:

 $form->radioButton('value_type', '值类型')
            ->options([
                1 => '一般',
                2 => '文件',
            ])->when(1, function (Form $form) {
                $form->text('values', __('Values')) ;
            })->when(2, function (Form $form) {
                $form->image('values', __('Values'));
            });
### Steps To Reproduce:

这里如果是新增的话，这个图片是没上传的

**Comment by phpcxy** [comment]
+1 图片上传不了~

**Comment by phpcxy** [comment]
刚调试了一下，这个问题应该是表单联动时候when里面的字段name一样，类型不一样，后一个表单组件覆盖了上一个组件导致的，希望可以修复下~

**Comment by helojianxin** [comment]
我也遇到了类似的问题，我用的是images时字段名用VALUES 解决的。
