### ISSUE TITLE
自定义行,批量操作里面  使用multipleSelect报错

### ISSUE THREAD

**Issue by uniteweiwei** [z-song/laravel-admin#4757]
- Laravel Version: 6.0
- PHP Version:7.2
- Laravel-admin: 1.8.0

### Description:
自定义行,批量操作里面  使用multipleSelect报错

`<?php
namespace App\Admin\Actions\User;
use App\Models\User;
use Encore\Admin\Actions\RowAction;
use Encore\Admin\Facades\Admin;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Http\Request;

class Follow extends RowAction
{
    public $name = '选择关注';

    public function handle(Model $model, Request $request)
    {

        return $this->response()->success('成功')->refresh();
    }

    public function form()
    {
 
        // 多选框
        $this->multipleSelect('user_arr', '选择的人')->options([1 => 'foo', 2 => 'bar', 'val' => 'Option name']);
    }

}`

`$grid->actions(function ($actions) {
                $actions->add(new SendGifts());
                $actions->add(new Evaluate());
                $actions->add(new Follow());
                $actions->disableView();
                $actions->disableDelete();
            });`

### Steps To Reproduce:
`Symfony\Component\Debug\Exception\FatalErrorException: Method Illuminate\View\View::__toString() must not throw an exception, caught Facade\Ignition\Exceptions\ViewException: in_array() expects parameter 2 to be array, null given (View: /Applications/MxSrvs/www/appoint/vendor/encore/laravel-admin/resources/views/actions/form/multipleselect.blade.php) in file /Applications/MxSrvs/www/appoint/storage/framework/views/421084bcd0b5ea4882be8f396ad3237b37488c64.php on line 0`

**Comment by walkerxy** [comment]
没人回答吗，我也遇到了

**Comment by Wong-Dy** [comment]
line 7:
<option value="{{$select}}" {{ in_array($select, old($column, $value)) ?'selected':'' }}>{{$option}}</option>
old($column, $value)) 参数错误，只能自己改了

**Comment by uniteweiwei** [comment]
> line 7:
> `<option value="{{$select}}" {{ in_array($select, old($column, $value)) ?'selected':'' }}>{{$option}}</option>`
> old($column, $value)) 参数错误，只能自己改了

怎么改哦

**Comment by GG-Dolts** [comment]
> > line 7:
> > `<option value="{{$select}}" {{ in_array($select, old($column, $value)) ?'selected':'' }}>{{$option}}</option>`
> > old($column, $value)) 参数错误，只能自己改了
> 
> 怎么改哦
我提供一个我的思路，我通过使用select选择框，然后修改select选择框的样式，将其改成multipleSelect的样式即可（form表单页面可以查看）。
php部分：
$this->select('your_select_class','你的选择框');

JavaScript部分：
let your_select = $('.modal-body .your_select_class');
your_select.attr('multiple', 'multiple');
your_select.attr('name', 'your_select_name[]');
your_select.children().first().remove();
your_select.parent().find('.select2-selection').removeClass('select2-selection--single');
your_select.parent().find('.select2-selection').addClass('select2-selection--multiple');

可以在当前action的form方法使用Admin::script()注入js脚本。

**Comment by uniteweiwei** [comment]
谢谢

**Comment by Wong-Dy** [comment]
> > line 7:
> > `<option value="{{$select}}" {{ in_array($select, old($column, $value)) ?'selected':'' }}>{{$option}}</option>`
> > old($column, $value)) 参数错误，只能自己改了
> 
> 怎么改哦

in_array第二个参数应该是数组
`<option value="{{$select}}" {{ in_array($select, is_array(old($column, $value))?old($column, $value):[old($column, $value)]) ?'selected':'' }}>{{$option}}</option>`

**Comment by rust17** [comment]
或者可以先将 `multipleSelect` 改成 `checkbox`
