### ISSUE TITLE
表单一对多关联关系 表单验证问题

### ISSUE THREAD

**Issue by guanghai1203** [z-song/laravel-admin#4758]
- Laravel Version: 7.0
- PHP Version: 7.4
- Laravel-admin: 1.8

### Description:
$form->hasMany()使用一对多关联关系后  子表表单验证无法提示错误信息并且子表的form表单的key名字由new_1,new_2,... 变成统一的new___LA_KEY__ 这个名字

**Comment by yang5664** [comment]
https://github.com/z-song/laravel-admin/issues/4612
