### ISSUE TITLE
一对多的时候添加富文本框，只显示一个问题（bug）

### ISSUE THREAD

**Issue by zhaojilinsy** [z-song/laravel-admin#4768]
- Laravel Version: 6.*
- PHP Version:7.4
- Laravel-admin: 1.8

### Description:
当添加多少富文本框的时候 只显示第一个富文本框，以后的都不显示 如下图 应该是个bug
![image](https://user-images.githubusercontent.com/46947965/86797953-d93b5280-c0a2-11ea-9bed-6a993277eac0.png)

**Comment by lexingzai** [comment]
遇到同样的问题。

**Comment by lexingzai** [comment]
能不能解决一下
