### ISSUE TITLE
Admin::content 如何自定义界面？

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#478]
后台管理的controller将HTML代码写在变量里虽然简单定义界面，但很难布局界面，是否有类似view()这样的方法来引用模板文件呢？

**Comment by z-song** [comment]
`$content->body(view('你的自定义view'));`

**Comment by windpursuer** [comment]
可以了，thanks~

**Comment by Fanxd** [comment]
@z-song 自定义的页面还能携带form组建吗？
