### ISSUE TITLE
\Encore\Admin\Widgets\Form 点击提交无反应问题

### ISSUE THREAD

**Issue by Sy-Dante** [z-song/laravel-admin#4782]
- Laravel Version: 6.18.24
- PHP Version: 7.3.15
- Laravel-admin: 1.8.1

### Description:

在 `$grid` 中使用 `\Encore\Admin\Widgets\Form` ，设置了 `$form->disablePjax();` 后，点击提交按钮无响应。

### Steps To Reproduce:

在 grid() 控制器访问中构建一个 modal 数据列
```php
        $grid->column('tes')
            ->display(function () {
                return '查看';
            })
            ->modal('测试', function () {
                $form = new \Encore\Admin\Widgets\Form();

                $form->method('POST');
                $form->action(route('admin.tests'));

                $form->hidden('data_id')->default(1);

                $form->number('num')->required();

                $form->disablePjax();

                return $form->render();
            });
```

点击构建后的表单的提交按钮没有任何响应（ console 无报错，network 无网络请求）

通过移除 `$form->disablePjax();` 可正常提交，但是提交处理完成后，模态背景（ model 的遮罩）没有消失。

在不移除 `$form->disablePjax();` 的情况下，通过移除 `vendor/encore/laravel-admin/src/Widgets/Form.php:559` 行的代码，就可以正常使用。这个问题麻烦处理一下

```php
// vendor/encore/laravel-admin/src/Widgets/Form.php:559

protected function addCascadeScript()
    {
        $id = $this->attributes['id'];

        $script = <<<SCRIPT
(function () {
    $('form#{$id}').submit(function (e) {
        e.preventDefault();  // 移除掉这行禁止事件冒泡的处理，就能正常工作了
        $(this).find('div.cascade-group.hide :input').attr('disabled', true);
    });
})();
SCRIPT;

        Admin::script($script);
    }
```

**Comment by a443939412** [comment]
同意
    protected function prepareForm()
    {
        if (method_exists($this, 'form')) {
            $this->form();
        }

        if (!empty($this->confirm)) {
            $this->addConfirmScript();
        }

        $this->addCascadeScript();    //  不加else？  但是不知道作者的用意是什么
    }
另一个解决方案是：走if， 设置$this->confirm，这次更新有点坑

**Comment by axsweet** [comment]
I am having the same issue I came up with a silly work around but do we have an esy solution? @z-song please beast this for me. I have all forms not workin that are widgets.

I am caught now because im on 7.4 so I need the other fixes.

love you, please help for the disablePjax

**Comment by axsweet** [comment]
Did with work around. I added a script to handle the submit button, I noticed in form.php there was a ;  on line 557 couldnt tell if that was effecting it or not.
        $script = <<<SCRIPT
(function () {
    $('form').submit(function (e) {
        this.submit();
    });
})();
SCRIPT;

        Admin::script($script);
