### ISSUE TITLE
在使用laravel-swoole加速模式下不兼容的代码如何解决

### ISSUE THREAD

**Issue by peter6968** [z-song/laravel-admin#4783]
- Laravel Version: 7.0
- PHP Version:7.3
- Laravel-admin: 1.8

### Description:
在使用laravel-swoole加速下运行的代码，gird导出代码中，swoole不支持在代码中执行exit，因此我知道这不关laravel-swoole包以及laravel框架的问题，这需要您的帮助，请问我该如何解决

**Comment by cn-ygf** [comment]
使用laravel-swoole并开启https时，分页的url是错误的（分页的url是http）

**Comment by peter6968** [comment]
使用laravel-swoole时在grid中非第一页删除时会重新回到第一页，在cgi模式中没有问题
