### ISSUE TITLE
laravel-admin route 重复，增加 name 方法报错问题

### ISSUE THREAD

**Issue by miaotiao** [z-song/laravel-admin#4785]
- Laravel Version: 7.20.0
- PHP Version:7.3.14
- Laravel-admin: 1.8.1

### Description:
![image](https://user-images.githubusercontent.com/28383349/87764811-89e6e600-c849-11ea-9717-bc6fe0d4b763.png)

route name 重复，为避免重复，给路由统一加上了 name 方法，但是报错如下：
![image](https://user-images.githubusercontent.com/28383349/87765054-eba75000-c849-11ea-8e49-8758a8426a0b.png)

**Comment by miaotiao** [comment]
方案：
![image](https://user-images.githubusercontent.com/28383349/87769274-fd8bf180-c84f-11ea-966c-8633aaf7c803.png)

原因：name 方法 和 带有选项的 group 方法冲突
参考：[error in adding routename to the group route](https://github.com/laravel/framework/issues/23494)

**Comment by never615** [comment]
![image](https://github.com/z-song/laravel-admin/assets/9959927/c8e85666-49b9-4ad2-87f0-d8a1369b9fee)
记录
