### ISSUE TITLE
请问一下我想替换内置自带的Content.blade.php该如何做

### ISSUE THREAD

**Issue by htmax** [z-song/laravel-admin#4794]
在追寻源码中找到这个
namespace Encore\Admin\Layout;
class Content implements Renderable
我想把它替换为我自定义的
namespace App\Admin\Layout;
class Content implements Renderable
在配置中可以映射吗

比如这种方式
\Encore\Admin\Layout\Content::class=>\App\Admin\Layout\Content::class

**Comment by htmax** [comment]
覆写内置视图
如果有需要自己修改view，但是不方便直接修改laravel-admin的情况，可以用下面的办法解决

复制vendor/encore/laravel-admin/views到项目的resources/views/admin，然后在app/Admin/bootstrap.php文件中加入代码：
// 覆盖`admin`命名空间下的视图
app('view')->prependNamespace('admin', resource_path('views/admin'));
这样就用resources/views/admin下的视图覆盖了laravel-admin的内置视图。

在laravel-admin每个新版本发布的时候, 内置视图都有可能会变更，所以如果你覆写了laravel-admin的视图，在更新laravel-admin版本的时候, 很有可能会出现视图方面的问题，这个需要你对照修改过的视图文件和内置视图自行修改解决。

**Comment by htmax** [comment]
文档中有这段，但是这样改的话，以后的更新就比较麻烦，我只想自定义某一个

**Comment by songlen** [comment]
按照这个文档更改完全没问题，不影响以后升级！想改哪个文件只复制这一份文件出来修改就行了。其实也可以不按照这个文档覆盖，系统已经有一个默认的目录可以覆盖视图，在view/vender 里
