### ISSUE TITLE
一个字段存储的是json格式的二维数组，编辑时bug

### ISSUE THREAD

**Issue by asen477** [z-song/laravel-admin#4799]
Laravel Version: 6.18.3
PHP Version: 7.2.31
Laravel-admin: 1.8
Description:
list保存数据后，无法显示，二维数组如果只有一列，每次修改新增就会把历史数据丢失（删除）
https://laravel-admin.org/docs/zh/model-form-json-fields

Steps To Reproduce:
1、list保存为json 数据后，再次编辑则无法显示，模板报错
2、二维数组如果只有一列，每次修改新增就会把历史数据丢失（删除）

**Comment by imnpc** [comment]
https://github.com/z-song/laravel-admin/issues/4745#issuecomment-755184481

参见这条修复
