### ISSUE TITLE
laravel5.3 按安装步骤，登录login点击后找不到页面

### ISSUE THREAD

**Issue by nistlrooy** [z-song/laravel-admin#48]
输入admin账号密码点击登录后，显示页面找不到。
是路由没设置还是其他什么情况呢？

**Comment by z-song** [comment]
登陆之后的url是多少？404页面吗？

**Comment by nistlrooy** [comment]
我在本机上测试，网站是http://localhost/base/下，admin登录页面url是http://localhost/base/public/admin/auth/login，输入账号密码登录跳转到http://localhost/admin/auth/login,错误404找不到改页，我应该在哪里设置路由呢？

**Comment by z-song** [comment]
laravel-admin 默认使用http://localhost/ 作为根目录的

正常的安装情况是

网站在http://localhost/下 
登陆页面是 http://localhost/admin/auth/login
后台首页是 http://localhost/admin

**Comment by nistlrooy** [comment]
原来如此，我通过apache设置vhost把http://localhost/base/public/跳转到test.com，这样就正常了。

**Comment by z-song** [comment]
欢迎提issue😀

**Comment by moore0903** [comment]
@z-song 除了修改vhost.conf 的方法除外,有其他的方法解决这个问题吗,
