### ISSUE TITLE
Hide Edit,Delete or List button for Show

### ISSUE THREAD

**Issue by vmourya** [z-song/laravel-admin#4800]
- Laravel Version: 7.0
- PHP Version: 7.2.5
- Laravel-admin: 1.8

How can i Hide Edit,Delete or List button for Show on record detail page ?

**Comment by songlen** [comment]
![image](https://user-images.githubusercontent.com/12892457/88888771-843dc700-d271-11ea-8fbd-b975d65adaa1.png)
