### ISSUE TITLE
Image upload doesn't work

### ISSUE THREAD

**Issue by rc-cd9** [z-song/laravel-admin#4806]
I've followed the documentation but it doesn't upload the image, and writes the temporary file's path to the DB (ex. /Applications/MAMP/tmp/php/php0PdTGD).

The folders are created on the public path, and I've configured the config/admin.php

```
'upload' => [

        'disk' => 'admin',

        'directory' => [
            'image' => 'image',
            'file' => 'file',
        ],
    ],    
```
and config/filesystems.php as shown in the docs.

```
'admin' => [
            'driver' => 'local',
            'root' => public_path('uploads'),
            'visibility' => 'public',
            'url' => env('APP_URL').'/uploads',
        ],    
```
I've also used the correct form function that the docs mandate, with the options that I need (and tested it already without them).

`$form_edit->image('value', 'Value')->uniqueName()->required();`
Lastly, I used

`php artisan storage:link`
that I found some people saying should be used to make sure the paths are set.

Despite all of this, it still doesn't upload the image to the right place.
Can anyone help me, please?

**Comment by dantinr** [comment]
check  fileinfo extentsion

**Comment by rc-cd9** [comment]
> check fileinfo extentsion

Found the error.
Because I am using some extra custom form functions in the Controller, I also have to create extra update and store functions and the respective put:: and post:: Routes, not just the custom get:: routes.

Though the post:: one for creating a new entry still gives me the same problem

**Comment by robertwt7** [comment]
+1, i'm having the same problem with the file upload as well.. path always go to `/tmp` instead of the declared file path in config

**Comment by BlueWhale235** [comment]
> > check fileinfo extentsion
> 
> Found the error. Because I am using some extra custom form functions in the Controller, I also have to create extra update and store functions and the respective put:: and post:: Routes, not just the custom get:: routes.
> 
> Though the post:: one for creating a new entry still gives me the same problem, while the put:: works fine

How, can you show an example?
