### ISSUE TITLE
@z-song 请你认真对待 laravel-admin

### ISSUE THREAD

**Issue by songlen** [z-song/laravel-admin#4811]
自己辛苦开发出来的产品就如同怀胎十月生出的孩子，自己一手创造的东西，就要认真负责直到他长大、变得完美。  
laravel-admin 目前的用户也非常多了，而且用户量应该在不断的增长。大家使用他是相信这个产品，他确实给大家带来了方便，减少了很多工作量，我们应该感谢你！  
laravel-admin 到目前算不上一个完整的产品，就我使用的情况来看，里面还存在很多 bug 。 大家都在积极的 提 PR 、 issue ，但是，请大家看看，有人回答吗，有人看吗？ 这个项目给人的感觉像没人维护了似的。  
qq 群里从来没见你说过话，提的 Issue 几乎没人回答， 私下联系你一块解决 Bug ， 也得不到不回复。你可能平时工作很忙，管理项目的时间少，但总该偶尔出来活跃一下吧，哪怕是群里说句话、回答一个 issue ，也好让人知道这项目还有人打理。给人一点信心，让大家知道这项目是个有妈的孩子。  要不然这项目的前途就茫茫了。。。
目前我遇到的问题都能自己解决，哪怕是 bug ，我也有其他办法解决，等我有时间我就会想办法修复 bug ，但是毕竟我们能力有限，有些bug能修复，有些 bug 解决起来确实费劲，希望能跟你一块探讨、共同完善项目。
但是哪里都找不到你。
说了这么多，就是希望你能偶尔出来看看大家提的问题，能解决的帮忙解决一下，不好解决的给个引导，毕竟这是自己的项目，底层逻辑你最熟。最主要的是这样能给大家带来积极性，让大家觉得这项目会越来越好，而不是感觉凉凉了。  
最最最主要的是关注一下大家提的 bug ，虽然暂时没时间解决，至少给个反响，让人有动力一块把项目做好。
如有说的不妥之处，还请谅解。我这也是希望 laravel-admin 能够越来越完美。

**Comment by z-song** [comment]
@songlen 这段时间很少处理这个项目，一是确实时间不多，第二对这个项目的热情越来越少，这种情况在过去发生了很多次了。

你说的这些问题确实存在，很多bug可能由于之前设计的错误，要花费太多时间去解决，甚至我也没办法解决，我看到issue列表里面很多都是针对不支持的功能，这是当初设计的时候没考虑过的，比如表单的hasmany和embeds, 由于我本人前端方面能力的欠缺，导致了这一块不能兼容一些复杂的组件。

 这个项目目前的状态应该只是暂停开发，上个月切出了2.0分支进行2.0版本的开发，目的是纠正一些之前的设计错误，修复一些遗留的bug，UI将会维持不变。这个版本将不会兼容之前的版本，也不会提供什么特有的功能。

对于开源项目的生命周期，我的想法是，这毕竟不是商业项目，投入的时间和精力都是需要热情来维持的，热情减少开发停滞，这是很正常的现象，就算项目走到了终点，也应该用平常心来接受，这样的例子在开源世界比比皆是，业余做开源在国内的环境确实也不太好。

总之这个项目我应该还会继续下去，但是能投入多少时间和精力进去没办法保证，这些取决于自己的工作和生活这些客观限制，谢谢你对这个项目的关注，我会考虑你的一些建议。

**Comment by lihe6666** [comment]
渣男！

**Comment by never615** [comment]
可以让一些热心的有技术的人一起参与审核代码等优化。

**Comment by nosun** [comment]
这个项目，真是个完美的项目，群主功德无量。

这个项目主要 靠 @z-song 支撑，精力顾不上很正常，表示理解。

不希望这个项目死掉，太喜欢了！
