### ISSUE TITLE
Access to PermissionController's grid instance (grid builder method)

### ISSUE THREAD

**Issue by mysteryreloaded** [z-song/laravel-admin#4812]
- Laravel Version: 7.20.0
- PHP Version: 7.2.19
- Laravel-admin: 1.8.1

### Description:
Is there a way to access PermissionController's grid builder and disable delete action button? Thing is, admin panel's end-user may delete administrator permissions by accident and if that happens, admin panel is unusable. Unless you add permissions manually into the database, which end-user doesn't know how to do. What I want to do is make these default permissions undeletable, so end-user can never encounter such situation where he erases his own permissions. Modifying PermissionController inside vendor folder is not an option, docs don't include solution for this scenario and google search didn't help neither. See image attached for visual description of this issue
![Screenshot_9](https://user-images.githubusercontent.com/43240758/88951974-055b8500-d297-11ea-80f8-3ea85f4e3921.png)

**Comment by mhanoglu** [comment]
Hello, you can do this with two ways

1- Override original controllers by defining new resource route with path of new controller.
Define route
`$router->resource('permissions', MyPermissionController::class);`

```
<?php
namespace App\Admin\Controllers;

use Encore\Admin\Controllers\PermissionController;

class MyPermissionController extends PermissionController
{
    public function grid()
    {
        // copy original codes to here and modify for disabling delete action button.
    }
}
```

2- Copy original controller file to your controller directory.
Define route
`$router->resource('permissions', PermissionController::class);`

And copy file as:
app/Admin/Controllers/PermissionController.php

**Comment by mysteryreloaded** [comment]
Got it, thanks!
