### ISSUE TITLE
【bug】使用前端组件 Form 构建 table 表单报错

### ISSUE THREAD

**Issue by songlen** [z-song/laravel-admin#4816]
- Laravel Version: 6.5
- PHP Version: 7.2
- Laravel-admin: 1.8.1

### Description:
使用 Encore\Admin\Widgets\Form 构建 table 表单报错

` Argument 1 passed to Encore\Admin\Form\NestedForm::setForm() must be an instance of Encore\Admin\Form or null, instance of Encore\Admin\Widgets\Form given, called in  \vendor\encore\laravel-admin\src\Form\Field\Table.php on line 93  `

**Comment by zairl23** [comment]
same error hanpped...

**Comment by Sunli9577** [comment]
发生同样的错误
