### ISSUE TITLE
Why not english?

### ISSUE THREAD

**Issue by renwarkurd** [z-song/laravel-admin#4819]
Why the main language of the official website and documentation is not English? So that we can understand project easily.
English language is standard and international language that is being used across the globe!

Regards

**Comment by stonepeng** [comment]
[https://laravel-admin.org/docs/en/README ](url)  ?

**Comment by JohnyProkie** [comment]
Unfortunately, en documentation is missing for V2. It is hard to get an idea what is purpose of new major release...

**Comment by stonepeng** [comment]
> Unfortunately, en documentation is missing for V2. It is hard to get an idea what is purpose of new major release...

just a beta, will be translate

**Comment by stonepeng** [comment]
> Unfortunately, en documentation is missing for V2. It is hard to get an idea what is purpose of new major release...



> Unfortunately, en documentation is missing for V2. It is hard to get an idea what is purpose of new major release...

@JohnyProkie just a beta, will be translate
