### ISSUE TITLE
Upgrade to AdminLTE3 (Bootstrap 4.5)

### ISSUE THREAD

**Issue by renwarkurd** [z-song/laravel-admin#4820]
We need updates for adminLTE (to v3) and bootstrap (to v4.5) so that we can manipulate the front-end easily.

**Comment by z-song** [comment]
I am doing this work, but it will take some time, not sure when it will be released

**Comment by jerome-zhang** [comment]
Looking forward to the new release!

**Comment by arbabi2010** [comment]
> I am doing this work, but it will take some time, not sure when it will be released

is new version with adminlte3 released or not ?
