### ISSUE TITLE
Embeded json error with php 7.4

### ISSUE THREAD

**Issue by elihaidv** [z-song/laravel-admin#4827]
- Laravel Version: 7.0
- PHP Version: 7.4
- Laravel-admin: 1.8

### Description:

When I try to insert 'embeds' object, it give this exception:

 ErrorException In EmbeddedForm.php line 185 :
"  array_key_exists(): Using array_key_exists() on objects is deprecated. Use isset() or property_exists() instead"

It seem new exception with php 7.4.

### Steps To Reproduce:
 
1. Create table with json field
2. In controller, put this: $form->embeds('json',function ($form) {
    $form->url('facebook');
});

3. Try to save a model.

**Comment by sergio3s** [comment]
I couldn't reproduce this error. Cloud you show how your created this field on your migration? And which DB are you using?

**Comment by fripig** [comment]
I have same issue.

it can create but will happen at update
