### ISSUE TITLE
求助，如何通过select组件load。动态加载 checkbox选项。form表单checkbox   通过load加载checkbox选项。

### ISSUE THREAD

**Issue by lovafeng** [z-song/laravel-admin#4829]
- Laravel Version: 6.x
- PHP Version:7.3.6
- Laravel-admin: 1.8.1

### Description:
求助，如何通过select组件load。动态加载 checkbox选项。form表单checkbox   通过load加载checkbox选项。

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/33741409/89602144-aef2d580-d898-11ea-8c70-ba4e5feba276.png)

**Comment by lovafeng** [comment]
现在临时通过自行写js来加载
有机会的话，就把这个写成组件
![image](https://user-images.githubusercontent.com/33741409/89613027-d73bfd80-d8b3-11ea-9f81-39f72bb178f9.png)

**Comment by ichynul** [comment]
用多选下拉替代也可以实现吧
