### ISSUE TITLE
model-form-tab 报错Call to a member function tab() on null

### ISSUE THREAD

**Issue by spc324** [z-song/laravel-admin#483]
代码如下：
 $form = new Form();
                    $form->action(admin_url('content/category'));

                    $form->tab('Basic info', function ($form) {

                        $form->text('username');
                        $form->email('email');

                    })->tab('Profile', function ($form) {

                        $form->image('avatar');
                        $form->text('address');
                        $form->mobile('phone');

                    });

运行报错：
FatalThrowableError in CategoryController.php line 47:
Call to a member function tab() on null

**Comment by z-song** [comment]
Widget/Form 没有这个功能暂时

**Comment by spc324** [comment]
好吧， 文档上应该备注一下
