### ISSUE TITLE
如何动态添加表单

### ISSUE THREAD

**Issue by wei-xf** [z-song/laravel-admin#4837]
- Laravel Version: 7.0.0
- PHP Version: 7.4
- Laravel-admin: 1.8.1

### Description:
想要在表单动态添加某个字段，实现增加删除元素内容？类似商品sku增加减少？

**Comment by running8gubin** [comment]
1.8.0版本有这个功能吧：
$form->radio('nationality', '国籍')
    ->options([
        1 => '本国',
        2 => '外国',
    ])->when(1, function (Form $form) { 

        $form->text('name', '姓名');
        $form->text('idcard', '身份证');

    })->when(2, function (Form $form) { 

        $form->text('name', '姓名');
        $form->text('passport', '护照');

    });

**Comment by wei-xf** [comment]
> 1.8.0版本有这个功能吧：
> 
> ```
> $form->radio('nationality', '国籍')
>     ->options([
>         1 => '本国',
>         2 => '外国',
>     ])->when(1, function (Form $form) { 
>         $form->text('name', '姓名');
>         $form->text('idcard', '身份证');
>     })->when(2, function (Form $form) { 
>         $form->text('name', '姓名');
>         $form->text('passport', '护照');
>     });
> ```

不是这个哈，可能我描述不够清楚，我是想要有一个字段，然后有两个按钮（增加和删除），增加就会添加这个元素，删除就是删除元素，类似数组的追加和移除。

**Comment by running8gubin** [comment]
用关联关系处理变通一下吧。模型 `一对多：`

// 主表字段
$form->text('username')->rules('required');
$form->textarea('bio')->rules('required');

// 子表字段
$form->morphMany('paintings', function (Form\NestedForm $form) {
    $form->text('title');
    $form->image('body');
    $form->datetime('completed_at');
});

**Comment by wei-xf** [comment]
> 用关联关系处理变通一下吧。模型 一对多：
> 
> ```
> // 主表字段
> $form->text('username')->rules('required');
> $form->textarea('bio')->rules('required');
> 
> // 子表字段
> $form->morphMany('paintings', function (Form\NestedForm $form) {
>     $form->text('title');
>     $form->image('body');
>     $form->datetime('completed_at');
> });
> ```

这也不行啊  这个得有关联关系吧  这咋能变通啊 大哥

**Comment by z-song** [comment]
https://laravel-admin.org/docs/zh/model-form-json-fields  这里找一个试试
