### ISSUE TITLE
关于 菜单栏权限的问题

### ISSUE THREAD

**Issue by 14718011108** [z-song/laravel-admin#486]
群主     定义菜单栏权限的时候          可以批量修改吗？   一个一个的改很麻烦

**Comment by z-song** [comment]
没有这个功能，你组织好菜单的结构，给父菜单赋角色就行了

而且改一遍下来也就两分钟，除非你菜单特别多

**Comment by 14718011108** [comment]
给 父级 菜单赋角色  子集不用也可以的吗？

**Comment by z-song** [comment]
菜单栏的Roles只是控制角色对这个菜单的可见性

如果看不到父级菜单 自己菜单也不会显示

**Comment by 14718011108** [comment]
哦     错别字  害人   看了三遍

**Comment by z-song** [comment]
修改了。。

**Comment by 14718011108** [comment]
还有  我发现一点   就是 有一个角色只有一个  别的权限  那个账户登录进去   会默认显示一个 用户的列表
就是好像 显示第一个菜单里面的列表

**Comment by 14718011108** [comment]
![7y4 rb vjws1q v7nnlw1d](https://cloud.githubusercontent.com/assets/24646165/23442499/bec09532-fe63-11e6-9700-483e0de91f5a.png)

**Comment by z-song** [comment]
抱歉，没看明白你上面写的。。

**Comment by 14718011108** [comment]
就是  只有   红色字 左边的    统计管理的权限     但是用那个账号登录的时候    一进去会显示   用户列表

**Comment by z-song** [comment]
菜单的显示之和角色有关   和权限不挂钩吧

**Comment by 14718011108** [comment]
但是我那个角色  也是只 设置了一个  统计管理的显示  别的显示都没有设置，  但是 一登录进去也显示了 用户列表

**Comment by z-song** [comment]
用户列表没有设置角色   默认所有的角色都可见

**Comment by 14718011108** [comment]
我设置了   administrator的   真的  不骗你

**Comment by z-song** [comment]
你给用户列表设置了administrator角色   然后非administrator也能看到？

**Comment by 14718011108** [comment]
![tc1 1pylic e dzy893y](https://cloud.githubusercontent.com/assets/24646165/23443296/da63a838-fe68-11e6-890d-b1af67490420.png)
![7rgk9scyr rrff5qgfudx0](https://cloud.githubusercontent.com/assets/24646165/23443301/e01f3e54-fe68-11e6-9c8b-541eb4d96cf3.png)

第一张图 是用户列表的  角色       第二是 用那个角色的账号登录的 一登录就显示   但是你 点击别的菜单   然后就没问题了

**Comment by edwinhuish** [comment]
@14718011108 你应该组织好语言再说，我也看不懂你的意思。

**Comment by edwinhuish** [comment]
@14718011108 你应该组织好语言再说，我也看不懂你的意思。

**Comment by 14718011108** [comment]
就是   我全部菜单列表都有 administrator的 角色的权限     只有专题管理的菜单有 有一个administrator 和业务员的角色                               我用业务员的账户    登录的时候  是不是应该只有 专题管理的菜单可以看见                但是 用业务员账户登录的时候   后台页面他会直接显示用户列表        一登录进去就显示 @edwinhuish

**Comment by 14718011108** [comment]
![j0 3xo69y 8fy9wcqazm8u](https://cloud.githubusercontent.com/assets/24646165/23448118/0d300466-fe8a-11e6-87fe-feb3ba0e6300.png)
![jr 6_mxv cok 7 3 4c3fu](https://cloud.githubusercontent.com/assets/24646165/23448132/1b8914bc-fe8a-11e6-9e71-85e51da86194.png)
    是不是  路由的问题

**Comment by bihantan** [comment]
看的我晕乎乎了哈

**Comment by shunhua** [comment]
@14718011108 语文。。

**Comment by songlen** [comment]
然后呢。。。哈哈哈哈
