### ISSUE TITLE
加入编辑器的

### ISSUE THREAD

**Issue by pangxiaofei94** [z-song/laravel-admin#487]
按文档加入编辑器后，还是只显示个内容区域，没有编辑器的功能 啊

**Comment by z-song** [comment]
贴代码吧

**Comment by pangxiaofei94** [comment]
![image](https://cloud.githubusercontent.com/assets/16313787/23442413/3910dc6c-fe63-11e6-9126-2ebbfee9ee1d.png)

![Uploading image.png…]()

**Comment by z-song** [comment]
图裂了。。。

**Comment by pangxiaofei94** [comment]
额。。。  是不是更新到最新版本，编辑器就有那些工具啊，例如，加粗....

**Comment by z-song** [comment]
你发的图没有上传成功，再发

**Comment by pangxiaofei94** [comment]
![image](https://cloud.githubusercontent.com/assets/16313787/23442982/da7ae590-fe66-11e6-834a-860cadbffd82.png)
![image](https://cloud.githubusercontent.com/assets/16313787/23443047/3d0aa93e-fe67-11e6-999f-1a74291ff95e.png)

**Comment by z-song** [comment]
你检查一下浏览器控制有没有错误

再贴一下你的CKEditor.php的代码

**Comment by pangxiaofei94** [comment]
![image](https://cloud.githubusercontent.com/assets/16313787/23443144/bdda82be-fe67-11e6-8b5b-1623f2239a8e.png)

**Comment by pangxiaofei94** [comment]
好了，能用，CKEditor.php里面的js路劲写错了，  不好意思啊
