### ISSUE TITLE
Show Page Flex

### ISSUE THREAD

**Issue by 15666446111** [z-song/laravel-admin#4878]
- Laravel Version: 5.8
- PHP Version: 7.3
- Laravel-admin: 1.8

### Description:
非常感谢@z-song 提供的laravel-admin 管理系统， 目前我们团队有很多项目在使用它!
但是我们最近遇到一个问题，在某些项目里面， 单个模型可能字段比较多， 导出 详情页面展示太长,  观看很不方便
目前试过像form 一样的column 尝试去多列布局, 但是并没有效果 ， 想问 这样的需要怎样处理 ?
感谢！

**Comment by z-song** [comment]
参考文档 https://laravel-admin.org/docs/zh/content-layout#%E8%87%AA%E5%AE%9A%E4%B9%89%E9%A1%B5%E9%9D%A2%E5%86%85%E5%AE%B9
