### ISSUE TITLE
表单字段带单位显示问题

### ISSUE THREAD

**Issue by rainsens** [z-song/laravel-admin#4880]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
![form-input](https://user-images.githubusercontent.com/11830109/90615782-26344c00-e23f-11ea-9f6e-f60817df75bf.png)

如图所示，现在支持这个功能吗？在输入框右侧显示单位，未曾在文档中找到相关内容。

**Comment by z-song** [comment]
```php
$form->text('column')->append('万');
```

很多功能没有写在文档里面，IDE的代码补全提示可以帮你找到一个对象有哪些方法

**Comment by rainsens** [comment]
目前只能完美适配 $form->text()组件，其它组件还不行，比如 currency,number 等
