### ISSUE TITLE
从 admin_users 表里查询数据费时，该如何优化

### ISSUE THREAD

**Issue by pccar** [z-song/laravel-admin#4887]
- Laravel Version: 7.24.0
- PHP Version: 7.3
- Laravel-admin: 1.8.1

### Description:
查询语句
select
  *
from
  `admin_users`
where
  `id` = ?
limit
  1
执行时间都是 10以上，其他的都是 1,该如何优化？给id 加索引貌似也没有作用

**Comment by z-song** [comment]
10以上？10秒？

**Comment by pccar** [comment]
> 10以上？10秒？

不是 10秒，laravel 的debug里面的计时，应该是毫秒。
有其他的表也是 select * ,但是 耗时都是在 3 以下

**Comment by z-song** [comment]
admin_users表的主键查询不可能产生性能问题。
