### ISSUE TITLE
  单设备登录 logoutOtherDevices 失效

### ISSUE THREAD

**Issue by muyi137** [z-song/laravel-admin#4893]
- Laravel Version: 5.8.*
- PHP Version:7.1.3
- Laravel-admin: 1.6.10

### Description:
namespace App\Admin\Controllers;

class AuthController extends BaseAuthController

if ($this->guard()->attempt($credentials, $remember)) { 
        	$res  = $this->sendLoginResponse($request);
        	 
            $this->guard()->logoutOtherDevices($request->password);
            
            return $res;
            // return $this->sendLoginResponse($request);
        }

logoutOtherDevices  怎么不管用 数据库的密码有变化 session好像没变化  是少什么东西吗 还是写错地方了

**Comment by yhorozco90** [comment]
Same situation here, at the moment i just overide the view in my project resource package.
