### ISSUE TITLE
quickSearch 多条件查询有误

### ISSUE THREAD

**Issue by winstor** [z-song/laravel-admin#4894]
- Laravel Version: 7
- PHP Version: 7.2.5
- Laravel-admin: 1.8

### Description:
$grid->model()->where('d',1);
$grid->quickSearch(‘a’，‘b’，‘c’）
查询条件无括号：
变成如下
select * from table where d=1 and a like '%input%' or b like '%%'  or c like '%%'
正常应该
select * from table where d=1 and （a like '%input%' or b like '%%'  or c like '%%'）

**Comment by winstor** [comment]
$grid->model()->where('d',1);
$grid->quickSearch(‘a’）
这个更扯 直接 or 了
select * from table where d=1 or a like '%input%'

**Comment by z-song** [comment]
@winstor 修复了 更新到v1.8.2
