### ISSUE TITLE
Grid Modal / Expand not rendering HTML code 

### ISSUE THREAD

**Issue by spektakl** [z-song/laravel-admin#4899]
- Laravel Version: 7.8
- PHP Version: 7.4
- Laravel-admin: 1.8

### Description:

Expand and Modal views in grids (as defined here in [https://laravel-admin.org/docs/en/model-grid-column-display#Popup%20modal%20box](https://laravel-admin.org/docs/en/model-grid-column-display#Popup%20modal%20box) are showing the HTML instead of rendering it.

### Steps To Reproduce:

Just follow the docs and you'll see it.

### Fix:

This is because of the code in the view. For example, for the "Modal", the view at /vendor/encore/laravel-admin/resources/views/components/column-modal.blade.php has this:

<img width="910" alt="Captura de pantalla 2020-08-25 a las 9 51 50" src="https://user-images.githubusercontent.com/45669520/91147532-b4358a00-e6b8-11ea-9bba-5d4d3938ef25.png">

... instead of this:

<img width="938" alt="Captura de pantalla 2020-08-25 a las 9 52 10" src="https://user-images.githubusercontent.com/45669520/91147544-b992d480-e6b8-11ea-915b-c5089e39ab0f.png">

Can this be fixed for the next package version? Or is intentioned? I remember it worked not long ago.

**Comment by yhorozco90** [comment]
Same situation here, at the moment i just overide the view in my project resource package.

**Comment by z-song** [comment]
@yhorozco90 @spektakl Fixed， Upgrade to v1.8.3

**Comment by xuchunhua-com** [comment]
modal not fix!!!

**Comment by AntonNosovich** [comment]
how to fix this????
