### ISSUE TITLE
关于，添加后台用户时，的修改

### ISSUE THREAD

**Issue by 14718011108** [z-song/laravel-admin#490]
如果我要改 ，后台添加用户，就是用户管理，改为添加的时候，可以直接查出所有菜单，   设置，这个用户可以操作哪些菜单， 这样   我要查什么表  ， 什么表里面的什么值要改，

**Comment by edwinhuish** [comment]
语文老师死的早？

**Comment by 14718011108** [comment]
我是不会组织语言，，你可以不回，我可以当没问过，但是你用不着这样

**Comment by edwinhuish** [comment]
Sorry 我的冷幽默影响到你。

不过我确实看不出你想表达什么意思。

**Comment by z-song** [comment]
@14718011108 在config/admin.php 的database配置项里面能看到所有内置的模型和表
