### ISSUE TITLE
Bug: grid date and time formatting not working

### ISSUE THREAD

**Issue by sd-evo** [z-song/laravel-admin#4903]
- Laravel Version: 7.2.2
- PHP Version: 7.4
- Laravel-admin: 1.8.2

### Description:
I have a problem with format date and time. Grid datetime, date and time formatting not working.

Code from laravel-admin package \src\Grid\Column\InlineEditing.php
![Снимок экрана от 2020-08-26 17-59-25](https://user-images.githubusercontent.com/66308935/91325449-df5cce00-e7cb-11ea-8e9c-862847d04e39.png)

### Steps To Reproduce:
```php
protected function grid()
{
    $grid = new Grid(new WebPage());

    $grid->column('updated_at')->datetime('DD.MM.YYYY HH:mm:ss');
    // or
    $grid->column('updated_at')->datetime('d.m.Y H:i:s');
    // or
    $grid->column('updated_at')->date('DD.MM.YYYY');
    // or
    $grid->column('updated_at')->date('d.m.Y');
    // or
    $grid->column('updated_at')->time('HH:mm:ss');
    // or
    $grid->column('updated_at')->time('H:i:s');

    return $grid;
}
```
### Result:
![Снимок экрана от 2020-08-26 18-52-29](https://user-images.githubusercontent.com/66308935/91326713-53e43c80-e7cd-11ea-8ba7-e71c79875486.png)

**Comment by z-song** [comment]
These methods are not formatting methods, but inline editing components

If you want to modify the display of a column, you can use the display callback of the column to handle it. 

```php
$grid->column('updated_at')->display(function ($updated_at) {
    return // format $updated_at
});
```

A better way is to use traits in the model to modify the default format of laravel.

```php
use Encore\Admin\Traits\DefaultDatetimeFormat;

class YorModel extends Model
{
    use DefaultDatetimeFormat;
}
```

**Comment by sd-evo** [comment]
Thanks
