### ISSUE TITLE
行操作 下拉菜单 在手机模式下样式无法撑开导致按钮显示不全

### ISSUE THREAD

**Issue by asundust** [z-song/laravel-admin#4910]
- Laravel Version: 6.18.35
- PHP Version:7.3.10
- Laravel-admin: 1.8.2

### Steps To Reproduce:
![手机模式,无法撑开](https://user-images.githubusercontent.com/6573979/91653587-c2c6db80-ead4-11ea-9e16-56f61b1ac768.png)
![手机模式,实际按钮高度](https://user-images.githubusercontent.com/6573979/91653594-ca868000-ead4-11ea-90e6-6840decbed0d.png)
![电脑模式,会出现滚动条](https://user-images.githubusercontent.com/6573979/91653595-cbb7ad00-ead4-11ea-87a9-45e85dc4b156.png)
![电脑模式,能够全部展现](https://user-images.githubusercontent.com/6573979/91653596-cbb7ad00-ead4-11ea-804f-9276abe35690.png)

**Comment by pgone01** [comment]
use Encore\Admin\Admin;
Admin::style('.box-body{overflow: scroll;}');

**Comment by asundust** [comment]
> 手机自适应问题，添加以下两行代码，强制刷新看看效果
> use Encore\Admin\Admin;
> Admin::style('.box-body{overflow: scroll;}');

@pgone01 实测了一下 确实能出现滚动条 但是这个滚动范围仅限在这个上拉“下拉菜单”这块内容才能把菜单展示出来 上拉其他区域不行

**Comment by pgone01** [comment]
1.8.2版本未知BUG太多了，我都退回1.7.6了

**Comment by asundust** [comment]
> 1.8.2版本未知BUG太多了，我都退回1.7.6了

@pgone01 这个bug貌似不是1.8.0才有的
