### ISSUE TITLE
json组件，当字段为image时，编辑修改表单重新提交，未修改的字段值被置空

### ISSUE THREAD

**Issue by jonexyz** [z-song/laravel-admin#4912]
- Laravel Version: #.#.#Laravel Framework 7.25.0

- PHP Version:PHP 7.3.9 (cli) (built: Aug 28 2019 09:28:30) ( NTS MSVC15 (Visual C++ 2017) x64 )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.9, Copyright (c) 1998-2018 Zend Technologies

- Laravel-admin: #.#.#Laravel-admin version 1.8.2

### Description:
`$form->table('content', __('详情'), function ($table) {
  $table->image('value');
});`

当编辑修改表单时，未重新修改的 image 数据被置空，只保存修改或新增的字段的数据

**Comment by jonexyz** [comment]
想到的办法就是，获取修改前后的数据，在保存后回调里修改添加进去

**Comment by z-song** [comment]
可在模型的字段修改器里解决
