### ISSUE TITLE
form()使用keyValue新增沒有反應

### ISSUE THREAD

**Issue by zeen828** [z-song/laravel-admin#4924]
使用1.8
在AdminController的form()使用keyValue新增沒有反應,
表單底下出現兩條未知input
這需要調整什麼嗎?
原本因該有一個
原本裝在template模板的元件好像調用不起來

**Comment by zeen828** [comment]
改寫方法
1.複製view檔案
  \vendor\encore\laravel-admin\resources\views\form\keyvalue.blade.php
  到
  \resources\views\vendor\admin\form\keyvalue.blade.php
2.增加設定\app\Admin\bootstrap.php
  // 強制給view
  app('view')->prependNamespace('admin', resource_path('views/admin'));
3.修改\resources\views\vendor\admin\form\keyvalue.blade.php
  增加一組DIV
  <div>
  <template class="{{$column}}-tpl">
  ...
  </template>
  </div>

**Comment by phpcxy** [comment]
你是不是用了vue?
