### ISSUE TITLE
1.8版本自定义excel导出无法使用

### ISSUE THREAD

**Issue by pianqifei** [z-song/laravel-admin#4930]
- Laravel Version: 7.13.0
- PHP Version:7.2
- Laravel-admin: 1.8.2

### Description:
按文档安装了Laravel-Excel 3.1 并自定义了导出类 执行导出方法默认产生的文件格式固定为 模型表名.csv 且数据为空 没有生成预期 自定义名称.xlsx 格式的导出数据 目前把后台版本回退到了1.7 希望尽快解决一下

**Comment by yulin1115** [comment]
按照文档data_get($user, 'profile.homepage'),获取不了关联字段

**Comment by 734290209** [comment]
我也遇到了  data_get（$ user，'profile.homepage'） 获取不了关联数据 你们最后都是怎么解决的

**Comment by 734290209** [comment]
我也遇到了data_get（$ user，'profile.homepage'）获取不了关联数据最后在论坛上找到一个解决方案https://discuss.laravel-admin.org/d/546-maatwebsite-excel-3-1 -excel
