### ISSUE TITLE
[!]批量操作BatchAction只能批量选择第一页的数据

### ISSUE THREAD

**Issue by BinZhiZhu** [z-song/laravel-admin#4937]
如题，如果我搜索到几百或者几千条数据，但是我全选选择批量操作，实际上只是选中了当前页的20条数据而已，
不能批量操作当前的所有的结果集吗？也就是全部，类似导出那样，现在就是只能操作当前分页的20条而已。

能否批量操作不仅仅是当前分页的数据？而且当前页面所有的结果集？例如我筛选到可能几万条数据，我想批量删除或者其他操作

类似文档贴出来的，批量复制仅仅显示了20条：

![image](https://user-images.githubusercontent.com/35824900/92318397-7f252200-f03e-11ea-9853-48021bf54430.png)

**Comment by z-song** [comment]
只能处理当前页

**Comment by BinZhiZhu** [comment]
> 只能处理当前页

好的 我自己单独写了功能处理这种问题了，另外还有一个问题请教下，fitter筛选出的结果以及参数能都暴露给开发者调用的？例如我想知道当前我的fitter里面有什么参数，就知道用户用了什么筛选，有什么参数，自己可以更好控制？

**Comment by z-song** [comment]
`$grid->getFilter()` 打印这个看看，你就知道用了什么筛选了
