### ISSUE TITLE
Form saving is NULL

### ISSUE THREAD

**Issue by kerwinzxc** [z-song/laravel-admin#494]
```php
....
$this->prepare($data, $this->saving);
...


/**
     * Prepare input data for insert or update.
     *
     * @param array    $data
     * @param callable $callback
     */
    protected function prepare($data = [], Closure $callback = null)
    {
        UserLog::debug("Form", "prepare 1 " . var_export($callback, true));
        $this->inputs = $data;

        if ($callback instanceof Closure) {
            UserLog::debug("Form", "prepare 2");
            $callback($this);

        }
        UserLog::debug("Form", "prepare 3");

        $this->relations = $this->getRelationInputs($data);

        $updates = array_except($this->inputs, array_keys($this->relations));

        $this->updates = array_filter($updates, function ($val) {
            return !is_null($val);
        });
    }
```

[2017-03-01 19:45:25] Form.INFO: 'prepare 1 NULL' {"memory_usage":"6.5 MB","url":"/admin/modeldata/list","ip":"::1","http_method":"POST","server":"localhost","referrer":"http://localhost:8000/admin/modeldata/list/create?model_id=1"} []

**Comment by z-song** [comment]
Sorry, I don't really know what you mean.

**Comment by kerwinzxc** [comment]
.....
Encore\Admin\Form


$form->saving(function($form){

                UserLog::debug('ModelDataStore', '+++++++++++before save the data');
                $form->input('data','asdasdasd');
   });
.....
I set the saving callback, but it does not work
when handle Form::store, the Form saving Closure callback is null

**Comment by z-song** [comment]
The method `prepare()` is changed now, see https://github.com/z-song/laravel-admin/blob/1.3/src/Form.php#L385-L400

Maybe you should update laravel-admin.
