### ISSUE TITLE
文档出现 500 错误

### ISSUE THREAD

**Issue by ahu** [z-song/laravel-admin#4941]
「页面内容和布局」https://laravel-admin.org/docs/zh/1.x/content-layout
「列的显示」https://laravel-admin.org/docs/zh/1.x/model-grid-column-display
「头部和脚部」https://laravel-admin.org/docs/zh/1.x/model-grid-header-footer
「自定义工具」https://laravel-admin.org/docs/zh/1.x/model-grid-custom-tools
「组件管理」https://laravel-admin.org/docs/zh/1.x/model-form-field-management 
「表单验证」https://laravel-admin.org/docs/zh/1.x/model-form-validation

**Comment by z-song** [comment]
都修复了
