### ISSUE TITLE
Flexible heredoc/nowdoc syntax 

### ISSUE THREAD

**Issue by fangmuke** [z-song/laravel-admin#4946]
- Laravel Version: 7.27.0
- PHP Version:7.2
- Laravel-admin: 2.0.0 Beta 1

### Description:
php <7.3时Table会报错

IDE报错：
![image](https://user-images.githubusercontent.com/26641510/92364203-4c098e00-f125-11ea-91c5-00a5dbedd6fe.png)

Laravel报错：
![image](https://user-images.githubusercontent.com/26641510/92364170-3d22db80-f125-11ea-80fb-dacfb6470657.png)

**Comment by z-song** [comment]
确实存在这个问题

**Comment by z-song** [comment]
安装`2.0.x-dev`版本体验最新的代码

```shell
composer require encore/laravel-admin:2.0.x-dev -vvv
