### ISSUE TITLE
Undefined variable: isHoldSelectAllCheckbox

### ISSUE THREAD

**Issue by bashman** [z-song/laravel-admin#4948]
- Laravel Version: 7.27
- PHP Version: 7.4
- Laravel-admin: 1.8.4

### Description:

ErrorException
Undefined variable: isHoldSelectAllCheckbox (View: .../views/grid/batch-actions.blade.php)

### Steps To Reproduce:

Entering in any list 

![Captura de pantalla de 2020-09-07 13-03-48](https://user-images.githubusercontent.com/1690516/92410727-a2b59e80-f10a-11ea-9192-b253b0757fdf.png)

**Comment by z-song** [comment]
Modify your view file according to this file https://github.com/z-song/laravel-admin/blob/master/resources/views/grid/batch-actions.blade.php

It is possible to update the view file in each version. When upgrading the version, pay attention to synchronously modify your view file

**Comment by kangsf1989** [comment]
我也遇到了这个问题，使用的是1.8.11 版本。但是admin对应的文件在vendor中，请问如何修改？？
