### ISSUE TITLE
AdminLTE and some files are missing: 404 File not found

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#4951]
- Laravel Version: 5.7.29
- PHP Version: 7.2
- Laravel-admin: 1.7

### Description:
![image](https://user-images.githubusercontent.com/7189244/92437831-ede6b480-f1d1-11ea-8bd6-5642e223f2cf.png)

On the production, website missing some files Ex: AdminLTE.min.css
But I can acccess these file
![image](https://user-images.githubusercontent.com/7189244/92438076-5c2b7700-f1d2-11ea-9997-88cf5b8dab74.png)

and the result is 404 not found
`http://realand.vn/vendor/laravel-admin/AdminLTE/dist/css/AdminLTE.min.css`
![image](https://user-images.githubusercontent.com/7189244/92438729-85003c00-f1d3-11ea-916b-c7e1974e15bf.png)

Beside that, another css files still exist and can access
`http://realand.vn/vendor/laravel-admin/AdminLTE/bootstrap/css/bootstrap.min.css`
![image](https://user-images.githubusercontent.com/7189244/92438561-4074a080-f1d3-11ea-9ffa-8796dd65d4be.png)

Please HELP ME

**Comment by amun1303** [comment]
Sorry all, my mistake. I forgot fill dist/ in .ignore file. Sorry again

**Comment by frontend-bravo-net-solution** [comment]
@amun1303 How you fix it?
