### ISSUE TITLE
求大佬解决 2.0 BETA 安装问题？

### ISSUE THREAD

**Issue by jsonlove-cc** [z-song/laravel-admin#4952]
- Laravel Version: 5.5.*
- PHP Version:7.1.*
- Laravel-admin: 2.* BETA

安装2.0 BETA 提示
  Problem 1
    - The requested package encore/laravel-admin 2.* is satisfiable by encore/laravel-admin[2.0.x-dev, v2.0.0-beta1] but these conflict with your requirements or minimum-stability.

**Comment by pucoder** [comment]
使用此命令安装，建议使用laravel 6.x 版本
```shell
composer require encore/laravel-admin:2.0.x-dev --prefer-dist
```

**Comment by xiaomlove** [comment]
@pucoder 为何这个命令不可以？
```
composer require encore/laravel-admin:dev-2.0
```
会报错：
```
  [InvalidArgumentException]
  Could not find package encore/laravel-admin in a version matching dev-2.0
```

**Comment by xiaomlove** [comment]
楼主的问题估计是要在 composer.json 最顶层添加这么个配置项：
```
"minimum-stability": "dev"
```

**Comment by jsonlove-cc** [comment]
我早就搞定了，忘记关了，抱歉
我的版本有问题 ，只有扩展现在用不了，例：定时任务安装不了
