### ISSUE TITLE
列中用于格式化时间的date方法失效

### ISSUE THREAD

**Issue by Roachard** [z-song/laravel-admin#4954]
- Laravel Version: 7.27
- PHP Version: 7.3
- Laravel-admin: 1.8.4

### Description:
首先感谢作者的努力，laravel-admin很好用。
但目前遇到了一些问题：

[laravel-admin 文档](https://laravel-admin.org/docs/zh/1.x/model-grid-column-display#%E6%97%A5%E6%9C%9F%E6%A0%BC%E5%BC%8F)中的该方法 `$grid->column('created_at')->date('Y-m-d');` 不见了，似乎被 `\src\Grid\Column\InlineEditing.php` 中的`date`方法替换了。

Laravel 7.x 中对 Model 的[日期序列化](https://learnku.com/docs/laravel/7.x/upgrade/7445#9d4f04) 进行了调整，laravel-admin 从 Model 中拿到的所有时间戳都是 ISO-8601 的格式。

用display来实现的话，重复的代码太多了；在 Model 中修改 Laravel 默认输出格式的话，影响范围很大，也可能影响 Model 的序列化。希望能把原本的 `date` 方法加回来，或者提供一个更优雅的方式全局修改时间戳格式。

另外，如果可能的话，希望尽量不要在小版本升级中对方法的调用方式进行较大的改动。

再次感谢作者为大家提供了这么好用的库。

**Comment by z-song** [comment]
目前推荐的方法是在模型里面解决

```php
<?php

namespace App\Models;

use Encore\Admin\Traits\DefaultDatetimeFormat;
use Illuminate\Database\Eloquent\Model;

class Role extends Model
{
    use DefaultDatetimeFormat;

    protected $table = 'admin_roles';
}

```

**Comment by Roachard** [comment]
但是这样做，模型在序列化时抛弃了时区信息和小数秒；
如果为每一个模型都创建laravel-admin专用的Model，只是为了解决日期格式问题的话，又会不太好看；
还是非常希望列能够包含时间格式化方法。

**Comment by z-song** [comment]
看下面的方法  扩展一个全局格式化日期的方法就行了

https://laravel-admin.org/docs/zh/1.x/model-grid-column#%E6%89%A9%E5%B1%95%E5%88%97%E5%8A%9F%E8%83%BD

**Comment by Roachard** [comment]
好的，谢谢
