### ISSUE TITLE
hasMany 能在一行显示吗？ 类似于 json 组件

### ISSUE THREAD

**Issue by gyp719** [z-song/laravel-admin#4956]
hasMany 能在一行显示吗？ 类似于 json 组件

```
  $form->hasMany('admin_user_appoint', '预约日期设置', function (Form\NestedForm $form) {
            $form->datetime('appoint_at', '日期')->format('YYYY-MM-DD')->rules('required|date');
            $form->number('appoint_num', __('每小时预约人数'))->min(0)->rules('required');
        });
```
![image](https://user-images.githubusercontent.com/30563368/92464295-85163100-f1ff-11ea-9015-5390145e3bca.png)

**Comment by lishuai199502** [comment]
请问大佬解决了吗，我也想这个样子

**Comment by gyp719** [comment]
> 请问大佬解决了吗，我也想这个样子



> 请问大佬解决了吗，我也想这个样子
没有解决呢

**Comment by lishuai199502** [comment]
我搞定了，给hasMany最后，加个useTable()
hasMany('xx','xx',function($form){})->useTable();



在 2021-04-19 11:30:32，"亦平凡" ***@***.***> 写道：

请问大佬解决了吗，我也想这个样子

请问大佬解决了吗，我也想这个样子
没有解决呢
