### ISSUE TITLE
open拼写错误，导致无法在新窗口打开

### ISSUE THREAD

**Issue by 0377** [z-song/laravel-admin#4957]
https://github.com/z-song/laravel-admin/blob/885639de38796fde2a1e8b45b5187b01f9026d0c/src/Actions/Action.php#L361

 if (then.action == 'oepn') {
       window.open(this.value, '_blank');
 }
open拼写错误，导致无法在新窗口打开

**Comment by 0377** [comment]
下一行的 
window.open(this.value, '_blank');
应该是
window.open(then.value, '_blank');

**Comment by z-song** [comment]
修复了
