### ISSUE TITLE
encore/laravel-admin/src/Table.php:505

### ISSUE THREAD

**Issue by imnicy** [z-song/laravel-admin#4958]
- Laravel Version: 7.24
- PHP Version: 7.2.19
- Laravel-admin: 2.0

### Description:
php语法致命错误

### Steps To Reproduce:
Heredoc末端结束标志未另起一行

**Comment by zljpz** [comment]
我的也是，我以为是只有我的会

**Comment by z-song** [comment]
@zljpz @imnicy 已经修复了这个问题 #4946   安装`2.0.x-dev`版本体验最新的代码

```shell
composer require encore/laravel-admin:2.0.x-dev -vvv
```
