### ISSUE TITLE
Filters not working on 1.8.4

### ISSUE THREAD

**Issue by opiy-org** [z-song/laravel-admin#4959]
- Laravel Version: 7.28.0
- PHP Version: 7.4.3
- Laravel-admin: 1.8.4

### Description:
Filters button above a grid is not working. Filters form not opening.
In console there is an js error: 
`Uncaught SyntaxError: Unexpected identifier`

It caused by this line:
`<script data-exec-on-popstate>$(function () { $.material.init()              $('#created_at_start').datetimepicker({"format":"YYYY-MM-DD","locale":"en"});`

![image](https://user-images.githubusercontent.com/10293975/92570771-7cc7ff80-f2ac-11ea-933e-9cb240df2bc3.png)

### Steps To Reproduce:
1. Go to grid page, 
2. click "Filters" button
3. Form not opens

### W/A:
downgrade laravel-admin to 1.8.1, button works.

**Comment by bandaranaike** [comment]
I am having the same problem. It was working in old version but after the update filter wont work.

**Comment by faydanube** [comment]
我也遇到了同樣的問題，我確認 1.84 版本的 filter 有問題，但是一天了都還沒找到原因。。。

**Comment by WenkeChen** [comment]
This issue caused by some third party extensions maybe. Open your browser console and check it.
