### ISSUE TITLE
AdminController   建议修改的部分，以利于扩展的开发

### ISSUE THREAD

**Issue by pucoder** [z-song/laravel-admin#4963]
- Laravel Version: 6.*
- PHP Version: 7.2.25
- Laravel-admin: 2.0

### Description:
- 我在开发RBAC扩展时，遇到的一些开发难题

- 当中间件需要使用当前控制器的title和description属性时，得到的都是默认值，希望将AdminController中title和description属性的 protected 改成 public

- 写控制器时发现，定义模型类的时候会重复使用相同的代码，希望在AdminController中加入一个$model属性，用于设置模型类，便于统一调用

- 我的RBAC扩展是基于路由来管理权限，希望每一个用户操作都是基于单独的路由来完成，而不是共用路由

- 希望包集成的每个路由都有一个别名（别名以 `admin` 开头，以点号 `.` 分割，以操作内容结尾，例如：管理员复制路由 `admin.auth_user.replicate`），这样就可以很好的使用翻译文件了

**Comment by z-song** [comment]
AdminController.php的title和description属性已经修改为public

$model属性定义感觉没必要，3、4两点无法实现
