### ISSUE TITLE
 $grid->column()->action(ObjectRowAction::class)中 form radio 页面变形

### ISSUE THREAD

**Issue by winstor** [z-song/laravel-admin#4966]
- Laravel Version: 7.0
- PHP Version:7.2.5
- Laravel-admin: 1.8.4

### Description:
class ObjectRowAction extends RowAction
 public function form()
    {
        $this->radio('is_sale', '是否转化')->options(['否', '是']);
    }
}
页面出现select 覆盖 radio 现象 ，select 代码不知道从哪儿来的  

![微信图片_20200914145631](https://user-images.githubusercontent.com/58460035/93054006-44089b80-f69b-11ea-8287-5432a05e7d71.png)

**Comment by winstor** [comment]
Google Chrome 已是最新版本
版本 85.0.4183.102（正式版本） （64 位）

**Comment by z-song** [comment]
页面可能有其它的select和这个字段同名，导致使用了select的样式，你把action里面这个字段换个名字试试看吧
