### ISSUE TITLE
2.0 版本 文件/图片上传 组件体验问题

### ISSUE THREAD

**Issue by longyunrui** [z-song/laravel-admin#4970]
- Laravel Version: 8.0
- PHP Version:7.4
- Laravel-admin: 2.0

### Description:

2.0 版本 文件/图片上传 组件体验问题，使用 `$form->image($column[, $label]);` 后在页面加载的样式未覆盖掉 `input` 输入框的样式，导致可以点击

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/18143599/93096848-7801b200-f6d7-11ea-9789-fd43ed202709.png)
![image](https://user-images.githubusercontent.com/18143599/93096965-95368080-f6d7-11ea-99be-fb64067a4db3.png)
如果将图中的 `<input>` 标签改为 `<span>` 标签，是否会有其他影响

**Comment by longyunrui** [comment]
-Laravel Version: 8.0.
-PHP Version:7.4.
-Laravel-admin: 2.0.

# Description:

Version 2.0 `File/Image upload` component experienced problems, using `$form->image($column [, $label]);` the style loaded on the page did not overwrite the style of the `input` input box, resulting in the ability to click.

# Steps To Reproduce:

If the `<input>` tag in the figure is changed to the `<span>` tag, will there be any other effects?

**Comment by z-song** [comment]
input框可以点击有什么影响吗？

**Comment by longyunrui** [comment]
> input框可以点击有什么影响吗？

这个是上传图片的按钮，一般来说是不需要可以点击输入的吧
