### ISSUE TITLE
建议2.0以后版本还是保留RBAC 

### ISSUE THREAD

**Issue by feirawang** [z-song/laravel-admin#4973]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
试用了新版本的，发现不错。建议有以下两点：
1、保留RBAC，用这个工具 在内网应用很方便，还可以不同授权。
2、详情页可能加入二维码及 打印view。

**Comment by z-song** [comment]
RBAC正在开发中，将会以扩展的形式提供支持。

**Comment by xiaomlove** [comment]
beta1，checkbox 有点问题，多一个“>”。

![微信图片_20200919021329](https://user-images.githubusercontent.com/8530353/93631747-b6240c00-fa1e-11ea-9a9c-d17b35239968.png)

**Comment by z-song** [comment]
@xiaomlove @feirawang 有兴趣的话可以试用一下rbac扩展 https://github.com/laravel-admin-extensions/rbac

需要先更新laravel-admin到v2.0.0 beta 2并且发布资源和语言

```shell
php artisan vendor:publish --tag=laravel-admin-assets --force

php artisan vendor:publish --tag=laravel-admin-lang --force
```

**Comment by xiaomlove** [comment]
beta2 Admin::assets()方法没了？文档没见有更新。 @z-song

**Comment by xiaomlove** [comment]
更新 beta 2 后，js 资源引入有问题了。
![beta2_path_error](https://user-images.githubusercontent.com/8530353/93662232-4733cb00-fa91-11ea-9e34-e3fb1bc0fa54.png)

**Comment by z-song** [comment]
> beta2 Admin::assets()方法没了？文档没见有更新。 @z-song

更新了文档，参考下面的方式引入静态资源

https://laravel-admin.org/docs/zh/2.x/view-rendering#%E8%B5%84%E6%BA%90%E5%85%B1%E7%94%A8

**Comment by z-song** [comment]
> 更新 beta 2 后，js 资源引入有问题了。
> ![beta2_path_error](https://user-images.githubusercontent.com/8530353/93662232-4733cb00-fa91-11ea-9e34-e3fb1bc0fa54.png)

没有发现这个错误

**Comment by pengxwei** [comment]
<img width="820" alt="微信截图_20200923092812" src="https://user-images.githubusercontent.com/33050232/93954009-33cd7c00-fd7f-11ea-87d7-b7ab425ca5ca.png">
laravel 8

**Comment by z-song** [comment]
@xiaomlove @pengxwei 更新到版本`2.0.x-dev`再看一下

```shell
composer require encore/laravel-admin:2.0.x-dev -vvv
```

**Comment by xiaomlove** [comment]
更新后可以了，但那个多了 ">" 的问题不存在么？这个 @color 感觉有问题。
![微信截图_20200924014746](https://user-images.githubusercontent.com/8530353/94049789-fbbe4b80-fe07-11ea-9c80-9cae7adfdb50.png)

**Comment by z-song** [comment]
@xiaomlove 提交了修复，再更新看看

**Comment by happiren** [comment]
> @xiaomlove @pengxwei 更新到版本`2.0.x-dev`再看一下
> 
> ```shell
> composer require encore/laravel-admin:2.0.x-dev -vvv
> ```
![1234](https://user-images.githubusercontent.com/10389226/94246320-2dd9c580-ff4e-11ea-9f2a-47f508cd1b5f.png)


更新后还是会出现问题。
PHP 7.4.10
laravel 5.8
laravel-admin: 2.0.x-dev

**Comment by z-song** [comment]
> > @xiaomlove @pengxwei 更新到版本`2.0.x-dev`再看一下
> > ```shell
> > composer require encore/laravel-admin:2.0.x-dev -vvv
> > ```
> 
> ![1234](https://user-images.githubusercontent.com/10389226/94246320-2dd9c580-ff4e-11ea-9f2a-47f508cd1b5f.png)
> 
> 更新后还是会出现问题。
> PHP 7.4.10
> laravel 5.8
> laravel-admin: 2.0.x-dev

@happiren 再更新看看

**Comment by happiren** [comment]
> > > @xiaomlove @pengxwei 更新到版本`2.0.x-dev`再看一下
> > > ```shell
> > > composer require encore/laravel-admin:2.0.x-dev -vvv
> > > ```
> > 
> > 
> > ![1234](https://user-images.githubusercontent.com/10389226/94246320-2dd9c580-ff4e-11ea-9f2a-47f508cd1b5f.png)
> > 更新后还是会出现问题。
> > PHP 7.4.10
> > laravel 5.8
> > laravel-admin: 2.0.x-dev
> 
> @happiren 再更新看看

更新后可以正常使用了，谢谢
