### ISSUE TITLE
table里 label标签是不是没有了。。。

### ISSUE THREAD

**Issue by Jackfinal** [z-song/laravel-admin#4982]
- Laravel Version: 8.0
- PHP Version:
- Laravel-admin: 2.0

### Description:
   `$table->column('statuss', __('状态'))->label('danger');`

初步查看是因为没有css样式.label label-danger,这个是否adminlte取消了对这个对支持

**Comment by z-song** [comment]
是bootstrap4 移除了label样式，更新到beta-2可以使用
