### ISSUE TITLE
你的想法 / Your ideas

### ISSUE THREAD

**Issue by z-song** [z-song/laravel-admin#4986]
如果你有希望在laravel-admin能够实现的功能，可以在下方留言（最好有截图），我会评估是否可以进行开发以及实现。

或者你有兴趣和时间的话也可以直接参与开发，请看[参与开发](https://laravel-admin.org/docs/zh/1.x/contribute)。

**Comment by attentive20** [comment]
Hello! Thanks for this product. I am using version 1.8.1 (in the versions above I see some problems, but this is a topic for other issues). In general, everything is fine. I would really like the Model-form-tab function to work correctly with the Form layout. Now, if Model-form-tab is used, Form layout does not work, it is very inconvenient.

**Comment by shacky** [comment]
Hello Z-Song, 
I tried to signup for WeChat, but it's not possible if I don't have any friends on WeChat to verify me. If you would like to take into account developers out of China please think about changing WeChat to something else.
For now, I will just submit pull requests from time to time... I think we should focus on bug fixes and enhancements of current features, like @attentive20 reported in the post above.
Thanks

**Comment by yanglei9999** [comment]
文档, 和版本更新后的说明, 应当更加详细一些

**Comment by uyson** [comment]
谢谢@z-song 提供laravel-admin, 我再开发中遇到无法实现嵌套资源、希望支持嵌套资源，https://laravel.com/docs/6.x/controllers#restful-nested-resources

**Comment by wangHeroGit** [comment]
Grid是否有考虑支持双表头呢？


|         个人信息      |
| 姓名 | 年龄 | 性别 |
|    1   |    2   |    3   |

**Comment by ffxhd** [comment]
列表页的批量删除、编辑页的删除、详情页的删除，都会走
```
$form->deleting(function () {
            return response()->json([
                'status'  => false,
                'message' => '删除失败，没有删除权限',
            ]);
 });
```
而列表页的单条删除却不走这个逻辑，我只好在Model中重写delete()才能实现权限控制，这增加了许多的工作。希望：在运行列表页的单条删除逻辑之前，走一下$form->deleting()，以便进行权限控制。

**Comment by lcc30521** [comment]
1.8说是有一个授权漏洞 具体是哪一块  官网没看到说明？

**Comment by sh4wn** [comment]
希望可以支持 tab模式

**Comment by songlen** [comment]
表格“”操作"列，希望可以增加个设置：显示到首列（我修改了源码，已实现该功能），如果考虑支持该功能，我可以提交PR ，或者作者以自己的想法实现！在此感谢！

**Comment by Sy-Dante** [comment]
> 表格“”操作"列，希望可以增加个设置：显示到首列（我修改了源码，已实现该功能），如果考虑支持该功能，我可以提交PR ，或者作者以自己的想法实现！在此感谢！

你可以通过编写自己的操作列显示类，然后修改下面这个配置项，来实现这个功能的，直接改源码不是正确的使用 composer 的方式

```
    /*
    |--------------------------------------------------------------------------
    | 设置数据表格的操作列显示类
    |--------------------------------------------------------------------------
    */
    'grid_action_class' => DropdownActions::class,
```

**Comment by hugh2113** [comment]
Tab 操作 與 HasMany Tab 的功能 看是否有辦法合併 ， 因為HasMany是向下 而Tab是向右且目前不支援 hasMany relation
