### ISSUE TITLE
表单中选择时间的时候被历史记录挡着

### ISSUE THREAD

**Issue by winstor** [z-song/laravel-admin#4988]
- Laravel Version: 1.8.4
- PHP Version:7.3
- Laravel-admin: 7

### Description:
![微信图片_20200922094015](https://user-images.githubusercontent.com/58460035/93837146-ac690580-fcb7-11ea-8dd4-80e152071901.png)
其它的就算了，像时间这种怎么填写内容，都挡着了
可以默认不显示历史记录吗？

**Comment by cjx2328** [comment]
这个是浏览器设置的层叠关系，试下见自动填充设置为off【autocomplete='off'】

**Comment by z-song** [comment]
已提交修复
