### ISSUE TITLE
關於1個Controller處理多個Model

### ISSUE THREAD

**Issue by Haogood** [z-song/laravel-admin#499]
請問作者老師，我想在Create頁取得其他Model的數據作為按鈕，要參考github文檔的哪一類?

1. Model_A 有3筆數據
2. Controller_B 和 Model_B 為一組
3. 要如何取得Model_A的3筆數據並打印在Controller_B的function form()作為radio button呢?

**Comment by edwinhuish** [comment]
可以这样写：
```
$form->checkbox($column[, $label])->options( Model_A::Data_1()->pluck('text','id') );

```

**Comment by Haogood** [comment]
請問老師，後半段 Model_A::Data_1()->pluck('text','id') 的 Data_1() 指的是哪個地方?

**Comment by Haogood** [comment]
老師我明白了，Data_1() 指的是下條件

**Comment by edwinhuish** [comment]
因为你没有指出Model_A的方法，Data_1是我假设的方法名。。。

每一个checkbox()的options就是一个checkbox

**Comment by Haogood** [comment]
原來Data_1是方法名，明白了

請問老師我的checkbox是可以複選的，有辦法寫成只能單選嗎?

**Comment by z-song** [comment]
@Haogood `$form->radio($column[, $label])->options( Model_A::Data_1()->pluck('text','id') );`

**Comment by Haogood** [comment]
謝謝老師解惑!
