### ISSUE TITLE
Filter button not clickable

### ISSUE THREAD

**Issue by bandaranaike** [z-song/laravel-admin#4990]
- Laravel Version: 7.28.2
- PHP Version: 7.4.3 
- Laravel-admin: 1.8.4

### Description:
When click on the filter button of list view, it does not expand or do any reaction.

### Steps To Reproduce:
1. Go to the any list view
2. Click on the filter button
3. It should be expand the filters. But does not.
![image](https://user-images.githubusercontent.com/6285773/93878939-82840300-fcf8-11ea-991b-63dcbe68a6a9.png)

**Comment by z-song** [comment]
Can't reproduce the problem

**Comment by bandaranaike** [comment]
I already had exported and customized views. Once updated the composer and got new laravel-admin version. Updated code does not work with old views. I have to replaced them with new views. Problem resolved.
