### ISSUE TITLE
laravel admin model 方法名定义问题

### ISSUE THREAD

**Issue by wzlzking** [z-song/laravel-admin#4992]
- Laravel Version:6.0
- PHP Version:7.3
- Laravel-admin: 1.8

### Description:
我有一个字段是article_type，然后在model里定义了一个方法articleType($type);
然后新增数据保存表单数据的时候会报Too few arguments to function App\Models\Article::articleType(), 0 passed and exactly 1 expected，把方法名改了之后就没事了，请问是怎么回事啊，就是保存表单的时候会自动调用与字段名相同的驼峰命令的方法，不知道是在哪调用的

**Comment by z-song** [comment]
提交的时候，会判断每一个提交字段是不是关联字段

**Comment by wzlzking** [comment]
方便告知一下源码在哪吗？找了没找到，希望看看学习一下 @z-song 十分感谢！

**Comment by z-song** [comment]
@wzlzking https://github.com/z-song/laravel-admin/blob/master/src/Form.php#L482
