### ISSUE TITLE
BUG---操作按钮显示

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#4993]
- Laravel Version: 6.1.#
- PHP Version:
- Laravel-admin: 1.8.#

### Description:
当
grid_action_class
为
'grid_action_class' => \Encore\Admin\Grid\Displayers\DropdownActions::class,
自定义按钮，无法添加，add方法不可用，append方法不生效

### Steps To Reproduce:
修改为
// 最原始的`按钮图标`形式
    'grid_action_class' => \Encore\Admin\Grid\Displayers\Actions::class,
以后，自定义方法可以显示。

**Comment by z-song** [comment]
文档上写了append方法已经废弃  不要再使用

自定义行操作参考文档 https://laravel-admin.org/docs/zh/1.x/model-grid-custom-actions
