### ISSUE TITLE
更新 laravel 8 后自定义按钮无法点击

### ISSUE THREAD

**Issue by ToogleLiu** [z-song/laravel-admin#4999]
- Laravel Version: 8.6.0
- PHP Version: 7.4.3
- Laravel-admin: 1.8.5

### Steps To Reproduce:

![Capture20200925163002](https://user-images.githubusercontent.com/6881085/94245131-68426300-ff4c-11ea-9480-91a234d42bf0.png)
![Capture20200925161315](https://user-images.githubusercontent.com/6881085/94245138-6bd5ea00-ff4c-11ea-9153-f8fb618708d0.png)

**Comment by binlihpu** [comment]
估计只支持到laravel5.x

**Comment by z-song** [comment]
> * Laravel Version: 8.6.0
> * PHP Version: 7.4.3
> * Laravel-admin: 1.8.5
> 
> ### Description: laravel-admin 1.8.5 更新 laravel 8 后，自定义按钮无法点击。js错误：Uncaught SyntaxError: Unexpected identifier
> ### Steps To Reproduce:
> ![Capture20200925163002](https://user-images.githubusercontent.com/6881085/94245131-68426300-ff4c-11ea-9480-91a234d42bf0.png)
> ![Capture20200925161315](https://user-images.githubusercontent.com/6881085/94245138-6bd5ea00-ff4c-11ea-9153-f8fb618708d0.png)

1752行少了一个【;】

```js
}); $('.started_at.action')....
```

**Comment by ToogleLiu** [comment]
@z-song 谢谢回复。是的，但是此处代码在laravel-admin项目文件里，需要您来修改，并且发一个版本。

**Comment by z-song** [comment]
`$('body').delegate()`这部分不是laravel-admin项目中的代码，你全局搜索一下看看

**Comment by ToogleLiu** [comment]
@z-song 是我看错了，谢谢~
