### ISSUE TITLE
Possible to use custom Form Fields?

### ISSUE THREAD

**Issue by axyr** [z-song/laravel-admin#5]
I have a custom file storage system and File class.

Therefore I would like to add my own File field so I can write the file in my own way.

But this prevents using custom forms:
```php
$className = __NAMESPACE__ . '\\Form\\Field\\' . ucfirst($method);
```

Am I missing something?

**Comment by axyr** [comment]
Encore\Admin\Form

if I add this : 

```php
public function field(Field $field)
{
    $this->builder->fields()->push($field);

    return $this;
}
```
I can do this :
```php
// App\Admin\Form\Field\Text extends Encore\Admin\Form\Field\Text
$form->field(new Text('name'));
```

**Comment by z-song** [comment]
Good idea,I will do this after I finish the multi-language support.

**Comment by Pashaster12** [comment]
@z-song What about multi-language support? Is it still in progress?
