### ISSUE TITLE
安装错误

### ISSUE THREAD

**Issue by jackqth** [z-song/laravel-admin#50]
![image](https://cloud.githubusercontent.com/assets/16730906/19338272/87509dcc-914e-11e6-9c57-324fc6ea1d34.png)

安装后出现这个错误，不知道是那里出了问题

**Comment by z-song** [comment]
检查一下你的项目语言设置，`config/app.php`的locale项，设置为 `zh_CN`或者`en`的时候，后台会自动根据设置选择语言包。

**Comment by jackqth** [comment]
![image](https://cloud.githubusercontent.com/assets/16730906/19344462/d73209f2-916c-11e6-86e9-690acd94ff6b.png)
我这项目config里面都设置的，但是好像没有读取的样子，是我那里的配置还有错误吗？

**Comment by jackqth** [comment]
还有就是除了菜单中的按钮，其他的地方点击就报这个找不到视图的错误，想问一下怎么回事，麻烦了

**Comment by jackqth** [comment]
![image](https://cloud.githubusercontent.com/assets/16730906/19344904/a9fc4540-916e-11e6-8d98-19ddc2c6d7ca.png)
还有就是点击编辑等按钮就报这个找不到视图的错误，不知道是我的安装出错，还是我的项目配置有问题，我是laravel5.2

**Comment by z-song** [comment]
语言的问题 你打印config('app.locale')看看输出什么

下面那个问题，我修改了一下代码，你更新一下再试试看

**Comment by jackqth** [comment]
我的跳转是相对服务器根目录而不是项目根目录？因为我本地好几个项目，所以路径会出现问题
打印出的结果是zh_CN

**Comment by z-song** [comment]
在`vendor/encore/laravel-admin/src/Providers/AdminServiceProvider.php`39行会调用`$this->loadTranslationsFrom(__DIR__.'/../../lang/', 'admin');`来加载语言包，你的情况是语言包没有被加载。

在下面断个点`dd(trans()->getLoader());`看看`$hints`属性是否已经加载了admin

![qq20161014-0](https://cloud.githubusercontent.com/assets/1479100/19373590/cd2ec5c2-91f7-11e6-8f05-5d06553d5bc5.png)

**Comment by jackqth** [comment]
![image](https://cloud.githubusercontent.com/assets/16730906/19373689/bfe4e648-91f8-11e6-8db5-4e49711c0eac.png)
看到的是已经加载的，我新建了个项目然后重新composer下来的语言包就没问题，不知道是不是我这个项目本身配置出现了什么问题

**Comment by z-song** [comment]
谢谢反馈！
