### ISSUE TITLE
Copyable() for "id" column

### ISSUE THREAD

**Issue by attentive20** [z-song/laravel-admin#5000]
- Laravel Version: 7.28
- PHP Version: 7.3
- Laravel-admin: 1.8.5

### Description:
![issue_laravel_admin](https://user-images.githubusercontent.com/71190913/94341876-afe0f180-0015-11eb-88ef-0d39e91b7546.jpg)
In versions above 1.8.1, if the copyable() method is used for the "id" column, we see the same as above. This is absolutely for all tables.

**Comment by z-song** [comment]
Fixed, upgrade to v1.8.6
