### ISSUE TITLE
1.8.4版本无法新增菜单

### ISSUE THREAD

**Issue by hulingling** [z-song/laravel-admin#5006]
- Laravel Version: 5.8.*
- PHP Version:
- Laravel-admin: 1.8.4

### Description:
刚更新了 Laravel-admin版本，项目是使用的https服务，在新增菜单提交时没有反应，但是编辑菜单没有问题，查看控制台，看起来是请求时走了http
network：
http://.../auth/menu
console:
Mixed Content: The page at 'https://.../auth/menu' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://.../auth/menu'. This request has been blocked; the content must be served over HTTPS.

已经设置了ADMIN_HTTPS，创建角色等其他功能没问题，只有新增菜单有问题，点了submit页面上看起来没有任何反应
 'https' => env('ADMIN_HTTPS', true),

**Comment by z-song** [comment]
重现不了，自己跟一下代码吧，在 vendor/encore/laravel-admin/src/Controllers/MenuController.php:34

**Comment by hulingling** [comment]
看起来是'https' => env('ADMIN_HTTPS', false),没有生效
使用了多项目插件，config中写的是'https' => env('ADMIN_HTTPS', false)，然后.env中写的是ADMIN_HTTPS=true

然后改成'https' => env('ADMIN_HTTPS', true)就没有问题了

@z-song 是不是多项目插件修改env有问题
