### ISSUE TITLE
hasMany is not working with Form linkage and embeds

### ISSUE THREAD

**Issue by hassyadai-hyokozeki** [z-song/laravel-admin#5007]
- Laravel Version: 7.4.0
- PHP Version:7.4.3
- Laravel-admin: 1.8.1

### Description:
HasMany's new button is not working with Form linkage and embeds.
Data field is json, and I want to change keyValue depending on select.

### Steps To Reproduce:
```
$form->select('templete')->options([
    '1'=>'1',
    '2'=>'2'
])->when('1', function (Form $form) {
    $form->hasMany('item', 'item', function (Form\NestedForm $form) {
        $form->embeds('data', function ($form){
            $form->text('text', 'text');
            $form->text('text2', 'text2');
        });
    });
})->when('2', function (Form $form) {
    $form->hasMany('item', 'item', function (Form\NestedForm $form) {
        $form->embeds('data', function ($form){
            $form->text('text3', 'text3');
            $form->text('text4', 'text4');
        });
    });
});
```

When I select 2, new button is not worked (1 is okey).
I tried nestedEmbeds in [this issue](https://github.com/z-song/laravel-admin/issues/899#issuecomment-402214996), still not worked.

**Comment by vlados** [comment]
@z-song I can confirm that this is a real issue. How I can fix it?
I am seeing that the addCascade is not called and the html and js for the cascade is missing

**Comment by Rashed-alam** [comment]
any update on this?!

**Comment by mubahood** [comment]
Still facing this problem.
