### ISSUE TITLE
1.7版本升级到1.8版本后Excel导出问题

### ISSUE THREAD

**Issue by xbw1125** [z-song/laravel-admin#5008]
1.7版本升级到1.8版本后Excel导出功能点击以后是可以正常下载的，但是数据是为空的，自定义导出也是同样的问题数据是空的（并没有走我写逻辑--主要是导出后的文件名都没改所以判定是没有走这边的逻辑）
vendor\encore\laravel-admin\src\Grid.php  render()方法
 $this->handleExportRequest(true);移动到try catch的下面 自定义导出就可以正常使用，希望赶紧更新一下这个bug吧大佬

**Comment by z-song** [comment]
1.8版本调整过导出  参考文档再写一下导出的逻辑吧  https://laravel-admin.org/docs/zh/1.x/model-grid-export
