### ISSUE TITLE
2.0 多选不能触发 batch action 按钮的显示

### ISSUE THREAD

**Issue by parse-code** [z-song/laravel-admin#5009]
- Laravel Version: 8.6.0
- PHP Version:7.4.8
- Laravel-admin: 2.0.0-beta2

### Description:
多选不能触发 batch action 按钮的显示
![image](https://user-images.githubusercontent.com/350474/94537780-c8e7dd80-0275-11eb-91c0-339c247c6c87.png)

### Steps To Reproduce:
1. 点击某一条目的checkbox, 没有出现批量操作的按钮
2. 点击全选的checkbox, 批量操作的按钮出现

**Comment by z-song** [comment]
提交了修复
