### ISSUE TITLE
grid显示关联模型时，关联方法名中无法用大写字母

### ISSUE THREAD

**Issue by Rainana** [z-song/laravel-admin#501]
```
class User extends Model
{
    public function roles() {
        return $this->belongsToMany(Role::class);
    }
}
```
```
return Admin::grid(User::class, function (Grid $grid) {
    $grid->roles()->display(function ($roles) {
        ......
    });
});
```

其中这个roles()方法的名字无法使用大写字母，有大写字母的话，$roles就变成null了

我以前习惯命名如belongsToManyRoles()，所以出现大写字母的方法很多，所以希望能修复这个问题

谢谢 ：）

**Comment by z-song** [comment]
这个问题应该已经修复  你更新到dev版本试试看

**Comment by Rainana** [comment]
我之前也在用dev版
刚刚更新试了一下，还是不能用大写字母

> Updating encore/laravel-admin 1.3.x-dev (09b33c7 => 1ae3d25) Checking out 1ae3d252b8

**Comment by z-song** [comment]
已经提交了修复 ecb4676

之前只修复了`HasOne`和`BelongsTo`，再更新一下看看

**Comment by Rainana** [comment]
试了，修复了，非常感谢！
