### ISSUE TITLE
What is latest combination for laravel-admin

### ISSUE THREAD

**Issue by raviduttverma** [z-song/laravel-admin#5012]
- Laravel Version: 5.8.38
- PHP Version: 7.3.17
- Laravel-admin: ^1.6

Have tried many different combinations to make a stable laravel-admin after update laravel version to 5.8, but faild.

**There are few errors which I'm getting**

-> Undefined variable: user (View: H:\xampp\htdocs\xxxxxx\vendor\encore\laravel-admin\resources\views\index.blade.php) (View: H:\xampp\htdocs\xxxxxx\vendor\encore\laravel-admin\resources\views\index.blade.php)

-> FatalThrowableError In OptionCheckBox.php line 355 :
  Call to a member function render() on string

and many more...

If i try to come with laravel 5.7 than laravel-admin breaks url base url(not appending website name in menu items) 

Please help to get a stable combination with php 7.3.

Thank you!

**Comment by lovafeng** [comment]
本人使用  php7.4  + laravel6 +laravel-admin 1.8 稳定运行

**Comment by lovafeng** [comment]
Laravel-admin的话，建议使用  laravel 5.5 吧
