### ISSUE TITLE
Javascript don't works only if you refresh the page by pressing F5

### ISSUE THREAD

**Issue by bashman** [z-song/laravel-admin#5014]
- Laravel Version: 7.X
- PHP Version: 7.3
- Laravel-admin: 1.8.6

Greetings. 

I'm working with several controllers and everything works very well, but I have a problem: I enter in the dashboard(home controller) and load via ajax some things, and I execute javascript code...everything is fine, but after clicking on the menu and go to other controllers, and, when I return to the dashboard the javascript code is not executed, the same happens with other controllers where I also have JS code, of course only if you refresh the page by pressing F5 it works again. 

What can I do to solve this situation?.

**Comment by vivozi** [comment]
laravel-admin uses https://github.com/defunkt/jquery-pjax to minimize full page reloads. does your javascript react to the pjax:end event or do you use onLoad or ready()? could you post some of your javascript code?

**Comment by bashman** [comment]
Ok. Let me show: 

In the view:
```
<div class="row">
    <div class="col-md-9">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Chart</h3>
            </div>
            <!-- /.box-header -->
            <div class="box-body ">

               <div class="tradingview-widget-container">
                    <div id="328473894230742947"></div>
                </div>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
```
In the controller:
```
            Admin::js('https://unpkg.com/mqtt/dist/mqtt.min.js'); //mqtt for IoT 
            Admin::js('https://s3.tradingview.com/tv.js'); //TV main library for charts
            Admin::js('/js/tvv.js'); // chart setup
```
In tvv.js

```
new TradingView.widget(
                            {
                                "width": \'100%\',
                                "height": 500,
                                "symbol": " FOO ",
                                "interval": "1D",
                                "timezone": "UTC-5",
                                  "allow_symbol_change": true,
                                "theme": "dark",
                                //"style": "10",
                                "timezone": Intl.DateTimeFormat().resolvedOptions().timeZone,
                                "locale": "es",
                                "toolbar_bg": "#f1f3f6",

                                "hide_side_toolbar": false,
                                "container_id": "328473894230742947",

                                "withdateranges": true,

                               "studies": [
                                    //"BB@tv-basicstudies"
                                ],
                            }

                        );
```
I am testing in onLoad and onready, and don't works.

**Comment by vivozi** [comment]
When working with laravel-admin you need to keep in mind, that you have a shared global scope between all your pages until a full page reload happens. When you leave a page you need to clean it up, and when you navigate back to that page, even when it comes from cache, you would build it up again. Maybe the Readme at https://github.com/defunkt/jquery-pjax#reinitializing-pluginswidget-on-new-page-content explains this better than i can.

Please try pjax:end instead of onLoad:
```
$(document).on('pjax:end', function() {
  alert ('page just finished loading');
})
```

```
$(document).on('pjax:start', function() {
  alert ('leaving the page. Are you sure?');
})
```

**Comment by bashman** [comment]
> When working with laravel-admin you need to keep in mind, that you have a shared global scope between all your pages until a full page reload happens. When you leave a page you need to clean it up, and when you navigate back to that page, even when it comes from cache, you would build it up again. Maybe the Readme at https://github.com/defunkt/jquery-pjax#reinitializing-pluginswidget-on-new-page-content explains this better than i can.
> 
> Please try pjax:end instead of onLoad:
> 
> ```
> $(document).on('pjax:end', function() {
>   alert ('page just finished loading');
> })
> ```
> 
> ```
> $(document).on('pjax:start', function() {
>   alert ('leaving the page. Are you sure?');
> })
> ```

Yes, thaks, I will make some testings.

**Comment by attentive20** [comment]
Had the same problem. The advice above helped. `$(document) .on ('ready pjax: end', function () { `
solved the problem. Thanks.
