### ISSUE TITLE
Relation sorting broken after updating to laravel 8

### ISSUE THREAD

**Issue by 4cc355-d3n13d** [z-song/laravel-admin#5016]
- Laravel Version: 8.7.1
- PHP Version: 7.4
- Laravel-admin: 1.8.6

### Description:
The code `$grid->column('commentable.id', __('fields.object_id'))->sortable();` was working fine @ laravel 5, after updating laravel, when we try to sort on that column the following error appears:

```
QueryException In Connection.php line 671 :
  SQLSTATE[42P01]: Undefined table: 7 ERROR: missing FROM-clause entry for table "JSON_EXTRACT(commentable, '$" LINE 1: ...s" where "comments"."deleted_at" is null order by "JSON_EXTR... ^ (SQL: select * from "comments" where "comments"."deleted_at" is null order by "JSON_EXTRACT(commentable, '$"."id')" desc limit 20 offset 0)
```

### Steps To Reproduce:
Update laravel to version 8 and try to sort by relational column.

**Comment by sangct-1630** [comment]
@4cc355-d3n13d 
@z-song 
I found the code that caused the relation sorting not to work.
path: `src/Grid/Model.php`
![Screenshot from 2020-10-20 14-16-31](https://user-images.githubusercontent.com/49383894/96553148-ee00c680-12de-11eb-9fa0-9df4deea388e.png)

Deleting `$isRelation` variable, it work fine.
I think this code is not necessary because the relationship is checked in the function `setRelationSort`
```
list($relationName, $relationColumn) = explode('.', $column);

if ($this->queries->contains(function ($query) use ($relationName) {
    return $query['method'] == 'with' && in_array($relationName, $query['arguments']);
})) {
    ...
}
```

**Comment by Erandelax** [comment]
I had a similar issue but resolved it by changing :529 in_array to:
`in_array(explode('.', $columnName, 2)[0], $query['arguments'], true)`

It treats "relation.attribute" both as relation attribute and json attribute selector and tries to differ the first one with that with/in_array check against the model relations list but fails comparing "relation.attribute" and "relation" instead. Cutting off the dotted part on check fixes the thing.

Would be better off for it to use "->" notation for json fields tho.

**Comment by bel1k0v** [comment]
Rly, man, are u borned too slow? U can't fix one line of code within 3 months? Please check out this bug for laravel 8 and fix one line of your Model pls.

**Comment by bel1k0v** [comment]
Same bug

**Comment by kenchengch** [comment]
What should we do? I dont want to change laravle-admin's source code

**Comment by 4cc355-d3n13d** [comment]
not good

**Comment by kinber126** [comment]
同样的问题。in_array(explode('.', $columnName, 2)[0], $query['arguments'], true)，用这个替换后，常规正常了。但是筛选用了created_at进行筛选，又发生Integrity constraint violation: 1052 Column 'created_at' in where clause is ambiguous 错误

**Comment by axsweet** [comment]
What I do is manually link the tables to the model. I felt this was always a limitation. 

I do the joins and set up the selects, its annoying BUT def works...
