### ISSUE TITLE
说明文档中模型表单基本使用中isUpdating()方法应该改为isEditing()方法

### ISSUE THREAD

**Issue by dds813** [z-song/laravel-admin#5017]
- Laravel Version: 8.0.0
- PHP Version:7.4
- Laravel-admin: 1.8.6

### Description:

说明文档中模型表单基本使用中isUpdating()方法应该改为isEditing()方法
### Steps To Reproduce:
说明文档中模型表单基本使用中isUpdating()方法应该改为isEditing()方法

**Comment by z-song** [comment]
已修改
