### ISSUE TITLE
switch开关

### ISSUE THREAD

**Issue by crazyxiaoqiang** [z-song/laravel-admin#5020]
### Description:
switch开关按照文档写法  报错

**$grid->('status')->switch();**

**Comment by uyson** [comment]
错误信息也附一下吧

**Comment by crazyxiaoqiang** [comment]
syntax error, unexpected '(', expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

**Comment by z-song** [comment]
`$grid->column('status')->switch();`

补一下PHP基础语法吧

**Comment by crazyxiaoqiang** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/12155453/95644285-34d50c00-0ae8-11eb-8eaa-c837e8ac5f8a.png">

**Comment by crazyxiaoqiang** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/12155453/95644300-4b7b6300-0ae8-11eb-8cff-49568e818628.png">
文档中这么写的

**Comment by reprover** [comment]
hhh
![image](https://user-images.githubusercontent.com/9566402/96704620-e4eb2480-13c6-11eb-9443-e923d0c83d35.png)
![image](https://user-images.githubusercontent.com/9566402/96704648-eb799c00-13c6-11eb-8355-76da55f01928.png)
