### ISSUE TITLE
2.0 多图上传插件 以及 列表展示多图控件 排版有问题

### ISSUE THREAD

**Issue by vagh** [z-song/laravel-admin#5022]
- Laravel Version: 8.9.0
- PHP Version: 7.4.10
- Laravel-admin: 2.0

### Description:
多图上传插件、以及列表轮播图片展示插件，样式出错

![image](https://user-images.githubusercontent.com/6220019/95670191-dd53a080-0bba-11eb-946d-d862f91ffa14.png)

多图上传插件，设置了可拖动，可排序，但无法操作。IconFront 也无法正常展示。

![image](https://user-images.githubusercontent.com/6220019/95670201-f6f4e800-0bba-11eb-987d-d24802dd3333.png)

打开 console 没看到有 JS 的报错信息。是不是少引用了 CSS 文件之类的？

**Comment by z-song** [comment]
图片轮播和拖动排序问题提交了修复，图标不显示的问题没有重现
