### ISSUE TITLE
关闭Pjax 前端闪烁

### ISSUE THREAD

**Issue by LampStudy** [z-song/laravel-admin#5028]
- Laravel Version: 6.x
- PHP Version:7.2
- Laravel-admin: 1.8.6

### Description:
  \Encore\Admin\Facades\Admin::disablePjax();

使用pjax 的时候，部分页面会加载样式失败(一定几率混乱)  刷新可解决.  所以尝试关闭pjax功能  

设置关闭pjax后  前端页面还是会先发起个 pjax页面请求  然后刷新  导致页面闪烁

**Comment by z-song** [comment]
修改`public/vendor/laravel-admin/laravel-admin/laravel-admin.js`文件，可以彻底关闭pjax
