### ISSUE TITLE
登录页面点击登录后，跳转后提示找不到页面

### ISSUE THREAD

**Issue by fsf11080612** [z-song/laravel-admin#503]
![image](https://cloud.githubusercontent.com/assets/12817128/23505486/d8fd0fe0-ff7e-11e6-81a0-c81e7fa12a8f.png)

**Comment by z-song** [comment]
你的apache配置有问题

**Comment by fsf11080612** [comment]
因为现在Apache服务器是放在客户那里，我改不了apache的配置。有没有什么方法可以不用修改apache的配置而解决这个问题？

**Comment by z-song** [comment]
ref http://stackoverflow.com/questions/12448912/apache-mod-rewrite-for-laravel

看第一个回答的第一步

**Comment by fsf11080612** [comment]
这是别人的回答
![image](https://cloud.githubusercontent.com/assets/12817128/23536126/da0eea82-fffd-11e6-88dd-931c8da1af1f.png)

我在public目录的.htaccess文件里面设置了RewriteRule ^(.*)$ public/$1 [L]，但还是没有起作用
![image](https://cloud.githubusercontent.com/assets/12817128/23536199/4dd6f9b4-fffe-11e6-8009-ab067c1fd43f.png)

修改后的效果
![image](https://cloud.githubusercontent.com/assets/12817128/23536326/0cdeebc8-ffff-11e6-92ac-470367cbd969.png)

**Comment by fsf11080612** [comment]
![image](https://cloud.githubusercontent.com/assets/12817128/23544101/76162364-0030-11e7-8368-2f45e9716474.png)
登录页面的路由是在哪里设置的？

**Comment by z-song** [comment]
用`artisan route:list`看
