### ISSUE TITLE
筛选--多列布局

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#5032]
- Laravel Version: 6.1
- PHP Version:7.2
- Laravel-admin: 1.8

### Description:
筛选--多列布局

Symfony\Component\Debug\Exception\FatalThrowableError
Cannot access protected property Encore\Admin\Grid::$filter

使用如下
`$grid->filter(function($filter){
            // 去掉默认的id过滤器
//            $filter->disableIdFilter();
            $filter->column(1/2, function ($filter) {
                $filter->like('title');
                $filter->between('rate');
            });
        });`

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/19919905/96394250-1233a900-11f4-11eb-99d7-762c66a33f2f.png)

**Comment by ZeiyThink** [comment]
2.0 beta4 版本中，这个  $form->column() 不生效啊，是2.0 没这功能吗？
`
 $form = new Form(new PromotionInfo());
        $form->column(6, function (Form $form) {
            $form->text('name', __('名称'));
            $form->decimal('price', __('单价'));
            $form->number('totalScore', __('总积分'));
            $form->number('scoreUnit', __('单次积分'));
        });
        //$form->number('needTimes', __('参与人次'));
        //$form->number('restTimes', __('剩余人次'));
        //$form->number('usedTimes', __('已用人次'));
        $form->column(6, function (Form $form) {
            $form->text('status', __('状态'));
            $form->image('imageurl', __('图片'));
            $form->datetime('startdate', __('活动开始时间'))->default(date('Y-m-d H:i:s'));
            $form->datetime('enddate', __('活动结束时间'))->default(date('Y-m-d H:i:s'));
        });
        return $form;
`
