### ISSUE TITLE
页面底部偶尔会出现空出来一截情况

### ISSUE THREAD

**Issue by pucoder** [z-song/laravel-admin#5054]
- Laravel Version: 7.*
- PHP Version:
- Laravel-admin: 2.0

### Description:

![J@}TQIZE%((Q8W1M4 OM2S](https://user-images.githubusercontent.com/36793767/97257873-1db94c80-1852-11eb-8b06-943b9bc271e9.png)

应该是一个JS控制的，本来应该会去掉，但是偶尔会去不掉

**Comment by z-song** [comment]
已修复
