### ISSUE TITLE
语法问题

### ISSUE THREAD

**Issue by shi1234** [z-song/laravel-admin#5059]
- Laravel Version: 6.X
- PHP Version:7.2
- Laravel-admin: 1.8.4
### Description:
手册
https://laravel-admin.org/docs/zh/1.x/model-grid-export
https://laravel-admin.org/docs/zh/2.x/model-table-export

```
    $export->column('column_5', function ($value, $original) {
        return $value;
    )};
```
语法错误,应该是});
```
    $export->column('column_5', function ($value, $original) {
        return $value;
    });
```

**Comment by z-song** [comment]
已修正

**Comment by shi1234** [comment]
谢谢，其实下面也是语法错误，但我看你只修复了上面。
![image](https://user-images.githubusercontent.com/14357986/97675581-8a3e8080-1aca-11eb-82be-ff2765344fba.png)
