### ISSUE TITLE
Form with hasMany relation but just showing one

### ISSUE THREAD

**Issue by nhoxbin** [z-song/laravel-admin#5066]
- Laravel Version: 7.x
- PHP Version: 7.4.x
- Laravel-admin: 1.8.6

### Description: hello. i'm stuck with form relation
example ```$form->hasMany('fields', 'Bài viết', function (Form\NestedForm $form) {...}```

but when it show in admin, it just show one one of second record? when i press the button
![image](https://user-images.githubusercontent.com/49804912/97729673-854af280-1b05-11eb-9f39-bcfe0b42c24e.png)
it save to db ok. But when i edit a post, it just show the second record, not show first
anyone help me.
Thanks. I'm Vietnam by the way if my english is suck, sorry.

**Comment by maksimbondarau** [comment]
Hello @nhoxbin, 
Please show your `fields()` method from Model-class. Make sure the models' relation is set up correctly. For example:
```
public function fields() {
    return $this->hasMany(Field::class, 'form_id');
}
```

**Comment by nhoxbin** [comment]
![image](https://user-images.githubusercontent.com/49804912/97894036-99405f80-1d64-11eb-95e1-e70ec12d6358.png)
my relation works fine!

**Comment by nhoxbin** [comment]
> Hello @nhoxbin,
> Please show your `fields()` method from the Model-class. Make sure the models' relation is set up correctly. For example:
> 
> ```
> public function fields() {
>     return $this->hasMany(Field::class, 'form_id');
> }
> ```

my relation works fine
![image](https://user-images.githubusercontent.com/49804912/97894106-b5440100-1d64-11eb-8553-5beaf26cd4b1.png)

**Comment by nhoxbin** [comment]
can anyone help me?

**Comment by maksimbondarau** [comment]
> can anyone help me?

This case is repeated if the model (`App\PostField`) doesn't have a primary key `id`, but it should be there.

**Comment by nhoxbin** [comment]
> model
![image](https://user-images.githubusercontent.com/49804912/98318495-4e973f80-2011-11eb-919d-ab3c20e27f4d.png)
my model has this code, when i deleted it, it's work, tks you very much!
