### ISSUE TITLE
关于多级联动，选中问题

### ISSUE THREAD

**Issue by qingdi** [z-song/laravel-admin#5070]
在修改逻辑中，如果遇到这样的操作。
```
$form->select('province_id', __('recycler.province'))->options('/api/province')->load('city_id', '/api/city')->required();
$form->select('city_id', __('recycler.city'))->load('county_id', '/api/county')->required();
$form->select('county_id', __('recycler.county'))->required();
```
现在的程序没法选中已选择的选项。

查看源代码
![image](https://user-images.githubusercontent.com/5287422/97821376-2cd64980-1ced-11eb-95e5-d988eb47963b.png)
发现这一段代码。意思是获取data-value值，然后执行选中操作。
<img width="1307" alt="iShot2020-11-02 09 24 55" src="https://user-images.githubusercontent.com/5287422/97821440-6ad36d80-1ced-11eb-8d22-63c2fe24f065.png">
查看发现所有的select中都有选中值得value。
所以。
![image](https://user-images.githubusercontent.com/5287422/97821513-ac641880-1ced-11eb-8303-824f60ab57cd.png)
在load函数中，添加选中逻辑。

项目大佬，看能把这段代码加入一下吗？

```
var value = $(target).data('value') + '';
if (value) {
     value = value.split(',');
     $(target).select2('val', value);
}
```

**Comment by jswh** [comment]
推荐提pr

**Comment by GHBJayce** [comment]
我也遇到同样的问题，在编辑页面中，`fieldB`和`fieldC`的默认值会被加载的数据项覆盖，且默认选中加载数据的头一个。

发现于：laravel-admin v1.8.11的loads的方法。
以下是调用的代码片段：
```php
$form->select('fieldA', __('fieldA'))
->options('url1')
->loads(['fieldB','fieldC'], ['url2', 'url3')]);
$form->select('fieldB', __('fieldB'));
$form->select('fieldC', __('fieldC'));
```
