### ISSUE TITLE
Issue 里面区分一下1.* 和2.*版本的吧

### ISSUE THREAD

**Issue by jswh** [z-song/laravel-admin#5079]
1.* 版本和 2.* 版本变更挺大的，我目前是直接上了2.0版本，反正新项目就当小白鼠了。issue里面没有版本的tag也没有其他的tag，这个处理起来太麻烦，不方便我们参与呐。
而且创建issue的时候好像也没法打tag。

**Comment by z-song** [comment]
@jswh 创建了两个新label `version 1.x`、`version 2.x`

**Comment by z-song** [comment]
目前很少人在用2.x版本
