### ISSUE TITLE
getLoadUrl子后台错误

### ISSUE THREAD

**Issue by jjkkopq** [z-song/laravel-admin#5080]
- Laravel-admin: 1.8.9

多个getLoadUrl处子后台链接错误
不应使用route，而是要用admin_url

   ```
protected function getLoadUrl($multiple = 0)
 {
        $selectable = str_replace('\\', '_', $this->selectable);
        $args = [$multiple];

        return route('admin.handle-selectable', compact('selectable', 'args'));
    }
```
改成
   ```
protected function getLoadUrl($multiple = 0)
 {
        $selectable = str_replace('\\', '_', $this->selectable);
        $args = [$multiple];

        return admin_url('_handle_selectable_',).'?selectable='.$selectable.'&args='.$args;
    }
```

**Comment by terranc** [comment]
刚也发现这个问题

**Comment by terranc** [comment]
尝试即便在Multitenancy.php中加上
![image](https://user-images.githubusercontent.com/224353/103120728-f77a2680-46b3-11eb-9e88-9ceba8a96cde.png)

route取到的依然是主后台的url

**Comment by terranc** [comment]
在子后台的routes.php中重新定义了一遍handle相关路由，算是临时解决了：
```php
Route::group([
    'middleware' => ['子后台自定义中间件'],
], function(Router $router) {
    // handle
    $router->namespace('\Encore\Admin\Controllers')->group(function($router) {
        $router->post('_handle_form_', 'HandleController@handleForm')->name('admin.handle-form');
        $router->post('_handle_action_', 'HandleController@handleAction')->name('admin.handle-action');
        $router->get('_handle_selectable_', 'HandleController@handleSelectable')->name('admin.handle-selectable');
        $router->get('_handle_renderable_', 'HandleController@handleRenderable')->name('admin.handle-renderable');
    });
});
```

**Comment by jjkkopq** [comment]
> 尝试即便在Multitenancy.php中加上
> ![image](https://user-images.githubusercontent.com/224353/103120728-f77a2680-46b3-11eb-9e88-9ceba8a96cde.png)
> 
> route取到的依然是主后台的url
`$router->name(Arr::get($config, 'route.prefix').'.')->namespace('Encore\Admin\Controllers')->group(function ($router) {
      $router->post('_handle_form_', 'HandleController@handleForm')->name('handle-form');
      $router->post('_handle_action_', 'HandleController@handleAction')->name('handle-action');
      $router->get('_handle_selectable_', 'HandleController@handleSelectable')->name('handle-selectable');
      $router->get('_handle_renderable_', 'HandleController@handleRenderable')->name('handle-renderable');
  });`
