### ISSUE TITLE
Laravel-Admin- Is that possible to Show/Hide Column when select dropdown in Form ?

### ISSUE THREAD

**Issue by MuhaiminS** [z-song/laravel-admin#5089]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 1.5

### Description:
In Form when select dropdown based on that need to show/hide one column. Is that possible in larave-admin ?
Can u help i tried many ways, but i couldn't get any solutions.

### Steps To Reproduce:
Sometime we want show/hide options to select admin user to choose which columns they want see or which columns they don't.

**Comment by vivozi** [comment]
I'm not sure i understand. Columns of what? A grid? A Table? How should it look like? Could you post a screenshot or mockup? In the worst case you could create your own form fields with custom javascript

**Comment by z-song** [comment]
@MuhaiminS What you might be looking for is this https://laravel-admin.org/docs/en/model-form-linkage
