### ISSUE TITLE
使用腳手架創建時報錯

### ISSUE THREAD

**Issue by btguys** [z-song/laravel-admin#509]
admin_user表報錯 
![image](https://cloud.githubusercontent.com/assets/18325797/23536294/d61bd7e0-fffe-11e6-83a3-76c2b9a014d2.png)

**Comment by btguys** [comment]
報405錯誤
![image](https://cloud.githubusercontent.com/assets/18325797/23536814/81a6e2aa-0002-11e7-9d16-dfe7092f2c6a.png)

**Comment by z-song** [comment]
更新到dev版本试试看

**Comment by xavier-chen** [comment]
遇到相同的问题，也是出线405问题。

**Comment by z-song** [comment]
贴一下post地址

**Comment by xavier-chen** [comment]
POST /admin HTTP/1.1
Host: yee.veryee.com
Connection: keep-alive
Content-Length: 2204
Origin: http://me.xavierchen.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryBYjGYF2brPJDO0m5
Accept: text/html, */*; q=0.01
X-Requested-With: XMLHttpRequest
X-PJAX: true
X-PJAX-Container: #pjax-container
Referer: http://yee.veryee.com/admin/helpers/scaffold
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6
Cookie: XSRF-TOKEN=eyJpdiI6ImF2b1NYNktwNGtmcndtVUhRa1wvQjN3PT0iLCJ2YWx1ZSI6InZ1WVQ1RE9tTFF4VVpkZmhHRzZYbjViOUhwN1pCdGE5SGpOZ0V5SkJTY0dHMGY4QlwvS2gwTVYwV2cxeE1zTjNwaEdVeGRBVDJXdmNqa3BDVmxUSk1UUT09IiwibWFjIjoiNmUwZTdhODU4OGNkZWJlMjg5ZWFmZDgxZGYzNzM5NDVhMzEyMDVjYjgzMGFjMDM5NjhkOTU0YTk4ZDU2MTEyNiJ9; laravel_session=eyJpdiI6IkRqTTFnbExlXC9pdzBnMXk4TUZrRFJ3PT0iLCJ2YWx1ZSI6ImdTcnpxZ2dYRnBUWmR4bGs1d3Y4aWw1RmU0eld1Q2tYQitmWFd4cmNXQUR3a2IxOW1SYktCY1NlVTlTNklGdGp0Y3dteXljV0ZWQmpkcTZZSE1FREp3PT0iLCJtYWMiOiI2NzYwYjMxZDU0N2Q5YzY1ZTA0NmEyOGFlODM2OTIzYjY0NWFjMzNjNDk2YTA5YjBlN2Q2MTE2YmI3ODk5OTUzIn0%3D

**Comment by xavier-chen** [comment]
POST /admin HTTP/1.1
Host: yee.veryee.com
Connection: keep-alive
Content-Length: 2204
Origin: http://xavierchen.com
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
Content-Type: multipart/form-data; boundary=----WebKitFormBoundaryBYjGYF2brPJDO0m5
Accept: text/html, */*; q=0.01
X-Requested-With: XMLHttpRequest
X-PJAX: true
X-PJAX-Container: #pjax-container
Referer: http://xavierchen.com/admin/helpers/scaffold
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.8,en;q=0.6
Cookie: XSRF-TOKEN=eyJpdiI6ImF2b1NYNktwNGtmcndtVUhRa1wvQjN3PT0iLCJ2YWx1ZSI6InZ1WVQ1RE9tTFF4VVpkZmhHRzZYbjViOUhwN1pCdGE5SGpOZ0V5SkJTY0dHMGY4QlwvS2gwTVYwV2cxeE1zTjNwaEdVeGRBVDJXdmNqa3BDVmxUSk1UUT09IiwibWFjIjoiNmUwZTdhODU4OGNkZWJlMjg5ZWFmZDgxZGYzNzM5NDVhMzEyMDVjYjgzMGFjMDM5NjhkOTU0YTk4ZDU2MTEyNiJ9; laravel_session=eyJpdiI6IkRqTTFnbExlXC9pdzBnMXk4TUZrRFJ3PT0iLCJ2YWx1ZSI6ImdTcnpxZ2dYRnBUWmR4bGs1d3Y4aWw1RmU0eld1Q2tYQitmWFd4cmNXQUR3a2IxOW1SYktCY1NlVTlTNklGdGp0Y3dteXljV0ZWQmpkcTZZSE1FREp3PT0iLCJtYWMiOiI2NzYwYjMxZDU0N2Q5YzY1ZTA0NmEyOGFlODM2OTIzYjY0NWFjMzNjNDk2YTA5YjBlN2Q2MTE2YmI3ODk5OTUzIn0%3D

**Comment by z-song** [comment]
https://github.com/z-song/laravel-admin/blob/1.4/views/helpers/scaffold.blade.php#L8
对比上面这行代码  如果不一样 说明没更新到最新的dev

**Comment by btguys** [comment]
確實不是最新版本
composer require encore/laravel-admin "1.4.*" --dev
貌似不起作用，需要重新部署嗎？
謝謝

![image](https://cloud.githubusercontent.com/assets/18325797/23537206/80759dec-0005-11e7-9ceb-60ee56c5639c.png)

**Comment by z-song** [comment]
Try `composer require encore/laravel-admin 1.4.x-dev`

**Comment by btguys** [comment]
Great, it works now

**Comment by xavier-chen** [comment]
问题解决

**Comment by gidaban** [comment]
Hello guys

whet i want to use "Scaffold" nothing happen but when i check XHR in Chrome i got notice

![error](https://cloud.githubusercontent.com/assets/1633884/23580566/29a5ed26-00fc-11e7-956f-8f977cb7cf32.jpg)

Anybody had same?
