### ISSUE TITLE
如何配置文件和图片使用不同的方式上传？

### ISSUE THREAD

**Issue by zys60233** [z-song/laravel-admin#5090]
- Laravel Version: 5.6.40
- PHP Version:7.x
- Laravel-admin: 1.7

### Description:
我现在有个需求是图片我要上传到oss上，但是文件上传到我本地的服务器，但是我看文档上只能指定一种方式，有没有什么解决方案可以提供。

**Comment by z-song** [comment]
```php
$form->image('image')->disk('oss');
$form->file('file')->disk('local');
```

用disk方法指定要保存的disk

**Comment by AnupDPokhrel** [comment]
check if you can put your file in another disk using storage facade. If everything works OK then further investigation needs to be done.
Check and start doing dd in these files, ...
```
vendor/encore/laravel-admin/src/Form/Field/UploadField.php 
vendor/encore/laravel-admin/src/Form/Field/File.php
```
