### ISSUE TITLE
$form->select()->load()  只能是select 之间的联动，有跟 text 或image的联动吗?

### ISSUE THREAD

**Issue by weishuiliang** [z-song/laravel-admin#5091]
$form->select()->load()  只能是select 之间的联动，有跟 text 或image的联动吗?
比如说：select选中user_id,
 然后再下方渲染昵称跟头像
 $form->text('nickname', __('昵称'));
 $form->image('avatar', __('头像'));

**Comment by z-song** [comment]
不支持
