### ISSUE TITLE
419 Page Expired

### ISSUE THREAD

**Issue by UsamaITS** [z-song/laravel-admin#5092]
- Laravel Version: 8.13.0
- PHP Version: 7.4.0
- Laravel-admin: 1.8.10

Description:
Appear since laravel-admin 1.5 from time to time when login to it .
I couldn't find solution for this issue #2459 , even with incognito chrome and most browsers ! sometimes with clean laravel installation, I just couldn't understand the issue cause from laravel or laravel admin  or both !

Now after this page appear [419] the route above point to **domian/admin-route/auth/login**, some times refreshing the page work and sometime if I clear [auth/login] from browser url it's work as I already logged in and admin page appear fine.

I can't make **Steps To Reproduce.**

**Comment by kaka775905353** [comment]
Cookie conflict.

**Comment by UsamaITS** [comment]
Just right now try it with fresh browser installation without any cookies, same issue.

**Comment by AppDevXtreme** [comment]
I am commenting on this thread as I have found the easiest solution to the 419 Page Expired error after uploading the dashboard to a shared hosting.

if your .htaccess is fine and there is no issues there, head over to config/admin.php.

Look for the line 'https' => env('ADMIN_HTTPS', false),

change that value to true and your problem will be resolved
