### ISSUE TITLE
登录页面无限重定向问题

### ISSUE THREAD

**Issue by mydansun** [z-song/laravel-admin#5093]
- Laravel Version: 5.6
- PHP Version: 7.4
- Laravel-admin: 1.8.10

### Description:

升级到1.8.10之后，登录页面无限重定向。
`src/Middleware/Authenticate.php`没有默认排除`auth/login`，请求没有到达`src/Middleware/Permission.php`中间件的88行，是因为路由优先级问题？

### Steps To Reproduce:
https://github.com/z-song/laravel-admin/compare/v1.8.6...v1.8.10

**Comment by z-song** [comment]
在`config/admin.php`的`auth.excepts`项手动加上排除路由`'auth/login'`
