### ISSUE TITLE
form 多选控件 错误

### ISSUE THREAD

**Issue by ltreer** [z-song/laravel-admin#51]
$form->multipleSelect($column[, $label])->options([1 => 'foo', 2 => 'bar', 'val' => 'Option name']);
多选框使用错误，貌似是数据格式不识别；
 
再有一点，麻烦 添加一些 ajax 调用 和 类似于省份市之类的多选！

**Comment by z-song** [comment]
@ltreer 是显示错误还是提交表单错误？

**Comment by ltreer** [comment]
显示错误
![image](https://cloud.githubusercontent.com/assets/20695108/19342966/c138da78-9166-11e6-9ac5-89ca0465d87d.png)

**Comment by z-song** [comment]
这应该是早期的版本产生的问题，已经在后续的版本修复了这个issue。

你可以直接这个package 或者修改文件代码。

修改文件`vendor/encore/laravel-admin/src/Form/Field/MultipleSelect.php` 

```
public function fill($data)
    {
        $relations = array_get($data, $this->column);

        if (!is_array($relations)) {
            return;
        }

        foreach ($relations as $relation) {
            $this->value[] = array_pop($relation['pivot']);
        }
    }
```

**Comment by ltreer** [comment]
确实是1.0版本，这个升级怎么升

**Comment by ltreer** [comment]
重新 composer require encore/laravel-admin "1.3.x-dev" 一下？

**Comment by z-song** [comment]
1.3.x-dev 是适用 laravel 5.3版本的

请问你的laravel版本是多少？

**Comment by ltreer** [comment]
就是5.3的

**Comment by ltreer** [comment]
，之前就是通过这个命令添加的

**Comment by z-song** [comment]
@ltreer `composer update encore/laravel-admin "1.3.x-dev"`

**Comment by z-song** [comment]
新版本的左侧菜单现在修改为在后台配置, [菜单配置](http://120.26.143.106/admin/auth/menu)

所以在数据库加了表，直接更新恐怕不行。

你可以重开一个项目，重新安装这个包，再把控制器、模型、数据等文件迁移过去。
