### ISSUE TITLE
laraveladmin2上传图片如果不填就报错Argument 1 passed to Encore\Admin\Form\Field\File::getStoreName() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given, called in /Applications/MxSrvs/www/web/dxhw/blog/vendor/encore/laravel-admin/src/Form/Field/Image.php on line 42

### ISSUE THREAD

**Issue by dongamao** [z-song/laravel-admin#5104]
- Laravel Version: 7
- PHP Version:7.2
- Laravel-admin: 2.0bate

表单中有 $form->image 如果不选择图片就报如下错误!
![image](https://user-images.githubusercontent.com/32496990/98923511-b4526280-250e-11eb-801c-603dd137e385.png)

Argument 1 passed to Encore\Admin\Form\Field\File::getStoreName() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, null given, called in /Applications/MxSrvs/www/web/dxhw/blog/vendor/encore/laravel-admin/src/Form/Field/Image.php on line 42

**Comment by cjx2328** [comment]
我是这样搞的，你看看：

`
 if(isset($data['image_url']) && !empty($data['image_url'])){

            $savedata = $this->upload($request,"image_url");

            $insertData['image_url'] =$savedata??"";

        }

/// 这个是upload代码：

public function upload(Request $request,$key="img"){

        if(!$request->hasFile($key)){

            $request->session()->flash('error_msg','文件不存在');

            return back();

        }
        $img = $request->file($key);

        // 获取后缀名

        $ext = $img->extension();

        // 新文件名
        $saveName = md5(time().rand()).".".$ext;


        // 使用 store 存储文件

        $path = $img->store(md5(date('Ymd')));

        return $path;
    }



`
希望对你有所哦帮助

**Comment by cjx2328** [comment]
主要目的就是判断下提交的数据中图片是否有值，有的话就开始后续的上传更新的逻辑，没有就忽略。这样还可以解决更新的时候如果图片文件为空而覆盖原有图片内容的BUG

**Comment by DAGpro** [comment]
The prepare method of the Image class is null by default, the getStoreName method expects the UploadedFile class.

```
    public function prepare($image = null)
    {
        if (is_string($image)) {
            return $image;
        }

        if ($this->picker) {
            return parent::prepare($image);
        }

        if (request()->has(static::FILE_DELETE_FLAG)) {
            return $this->destroy();
        }

        $this->name = $this->getStoreName($image);

        $this->callInterventionMethods($image->getRealPath());

        $path = $this->uploadAndDeleteOriginal($image);

        $this->uploadAndDeleteOriginalThumbnail($image);

        return $path;
    }
```

Need to add null check to prepare method or disable middleware ConvertEmptyStringsToNull

```
    public function prepare($image = null)
    {
        if (is_string($image)) {
            return $image;
        }
        
        if (is_null($image)){
            return $image;
        }
        
        .....
     }
```

Also in the HasValuePicker trait, the image validation rule is removed, so there is no validation in the Image fields
