### ISSUE TITLE
when 使用默认值出错

### ISSUE THREAD

**Issue by wen-gg** [z-song/laravel-admin#5107]
如图所示，默认值是字符串时错误
![image](https://user-images.githubusercontent.com/17865026/99055920-ab2bc900-25d4-11eb-9ff5-952dda5d35c3.png)
![image](https://user-images.githubusercontent.com/17865026/99056068-b848b800-25d4-11eb-9d46-8ffbbaab5356.png)

**Comment by kaka775905353** [comment]
在你的 config::getTypeConf()  返回值 看一下  问题应该是出在这

**Comment by wen-gg** [comment]
这里面没问题呢，用int可以，string就报错
![image](https://user-images.githubusercontent.com/17865026/99160480-db817d80-2722-11eb-815f-bc3a0d7beab1.png)

**Comment by z-song** [comment]
@wen-gg @kaka775905353 修复了，更新到v1.8.11
