### ISSUE TITLE
select的联动功能错误

### ISSUE THREAD

**Issue by u-nine** [z-song/laravel-admin#5108]
- Laravel Version: 8.14.0
- PHP Version:7.3.6
- Laravel-admin: 2.0.0 beta5

### Description:
文件：laravel-admin\resources\views\form\select.blade.php
![select_load](https://user-images.githubusercontent.com/12064578/99136756-e1fbf080-2661-11eb-837d-6a20dbcc4882.png)
![select_loads](https://user-images.githubusercontent.com/12064578/99136757-e45e4a80-2661-11eb-9657-fc43718b0ffa.png)

**Comment by sanye4639** [comment]
我也踩了。

**Comment by sanye4639** [comment]
完美解决，感谢大佬
