### ISSUE TITLE
1.3.x-dev  $form->image()  报错Method Illuminate\View\View::__toString() must not throw an exception

### ISSUE THREAD

**Issue by Makingss** [z-song/laravel-admin#511]
Method Illuminate\View\View::__toString() must not throw an exception

**Comment by z-song** [comment]
创建的时候还是编辑的时候，多给点信息

**Comment by Makingss** [comment]
![image](https://cloud.githubusercontent.com/assets/23512926/23537154/15f4f1ac-0005-11e7-82da-42edb2d5e7ee.png)
创建和编辑都是一样的情况

**Comment by z-song** [comment]
`$content->body($this->form());`  改成 `$content->body($this->form()->render());`再看详细错误

**Comment by Makingss** [comment]
![image](https://cloud.githubusercontent.com/assets/23512926/23537371/88f8bf52-0006-11e7-9c0d-5a0d410ec766.png)

还是报一样的错，没有太详细的错误信息打印出来

**Comment by z-song** [comment]
没有重现你的问题，   不知道你是修改了什么吗

**Comment by Makingss** [comment]
![image](https://cloud.githubusercontent.com/assets/23512926/23541292/5f3d17ce-0021-11e7-89ae-7b14b9e2bfe2.png)
不走__toString()  打印出这个错误信息，但还没有明表那里有问。

**Comment by Makingss** [comment]
![image](https://cloud.githubusercontent.com/assets/23512926/23541509/c8b3ebe6-0022-11e7-9e92-9d7d7ffde7ac.png)
![image](https://cloud.githubusercontent.com/assets/23512926/23541517/dc8561c2-0022-11e7-8a47-ba22442950ee.png)

好像和View 有关系，z-song 我注掉自定义View 可以正常，，，现在怎么破？

**Comment by z-song** [comment]
视图的改动会比较频繁，如果自定义了视图，更新之后用`vendor/encore/laravel-admin/views`覆盖一下你自定义的视图，记得做好备份就好

**Comment by Makingss** [comment]
哎呀，能告诉我是更新的那个文件么，。。。我自定义写了大量的view 文件

**Comment by Makingss** [comment]
自定义的view->form 下面有这个文件image.blade.php
vendeor/encore   的view->form 下面没有image.blade.php

**Comment by z-song** [comment]
vendor/encore/laravel-admin/views/form/multiplefile.blade.php
vendor/encore/laravel-admin/views/form/file.blade.php

这两个文件

**Comment by z-song** [comment]
如果用自定义的view 文件  以后还会遇到其它问题的

**Comment by Makingss** [comment]
我用了对比工具比较出多文件上传的View 是新增加的，我已同步了View 的代码，已解决。。

**Comment by longyunrui** [comment]
我也碰到相同的错误了，多图上传成功之后查看详情的时候会报错  setImageAttribute  和   getImageAttribute  都已经加了

**Comment by longyunrui** [comment]
现在的版本是1.6
