### ISSUE TITLE
admin:controller  创建控制器失效

### ISSUE THREAD

**Issue by hxsen** [z-song/laravel-admin#5114]
Laravel-admin version 1.8.11

```php
php artisan admin:controller --model=App\Models\Article
```
这种方式，是文档上显示的操作，但是并不能创建成功。一直显示`--model`不存在
```php
 The "--model" option does not exist.
```

**Comment by hxsen** [comment]
经过自己的探索，发现正确的创建方式，如下：
```php
php artisan admin:controller App\Models\Article
```
去掉`--model`即可。下面是创建过程
```php
G:\WWW\attract>php artisan admin:controller App\Models\Article
App\Admin\Controllers\ArticleController created successfully.

Add the following route to app/Admin/routes.php:

    $router->resource('articles', ArticleController::class);

```
希望作者留意下。看看是修改文档，还是修改代码！

**Comment by hxsen** [comment]
或者，是不是我少配置了什么？

**Comment by yljphp** [comment]
> 经过自己的探索，发现正确的创建方式，如下：
> 
> ```
> php artisan admin:controller App\Models\Article
> ```
> 
> 去掉`--model`即可。下面是创建过程
> 
> ```
> G:\WWW\attract>php artisan admin:controller App\Models\Article
> App\Admin\Controllers\ArticleController created successfully.
> 
> Add the following route to app/Admin/routes.php:
> 
>     $router->resource('articles', ArticleController::class);
> ```
> 
> 希望作者留意下。看看是修改文档，还是修改代码！

遇到了相同问题，感谢！

**Comment by GWesley** [comment]
mac os:

php artisan admin:controller App\\Models\\User
