### ISSUE TITLE
laravel-admin2.0 beta 编辑表单不上传文件报错

### ISSUE THREAD

**Issue by sanye4639** [z-song/laravel-admin#5117]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 2.0 BETA

### Description:
若新增/编辑表单时，不上传文件，则报错 local.ERROR: Argument 1 passed to Encore\Admin\Form\Field\File::getStoreName() must be an instance of Symfony\Component\HttpFoundation\File\UploadedFile, string given, called in /data/server/vendor/encore/laravel-admin/src/Form/Field/File.php on line 94

![1605662570687](https://user-images.githubusercontent.com/30991208/99470421-ae7dd680-297f-11eb-9815-093749f0476c.jpg)

找到源代码,重复字段提交
vendor/encore/laravel-admin/resources/views/form/file.blade.php
![1605662734504](https://user-images.githubusercontent.com/30991208/99470650-074d6f00-2980-11eb-9179-0e99a44ca7df.jpg)

**Comment by alinaTing** [comment]
怎么解决吗

**Comment by alinaTing** [comment]
也碰到同样的问题

**Comment by cjx2328** [comment]
在保存的时候在model中添加一个判断可行否？我是自己重构了保存和图片上传的方法解决的

**Comment by sanye4639** [comment]
> 也碰到同样的问题a

**Comment by sanye4639** [comment]
> 也碰到同样的问题

我是通过屏蔽input[hidden]隐藏域即可，验证过不会因此导致重复上传的问题就没管了。

**Comment by sanye4639** [comment]
> 在保存的时候在model中添加一个判断可行否？我是自己重构了保存和图片上传的方法解决的

在表单提交回调里面尝试过，似乎不行。

**Comment by cjx2328** [comment]
> > 在保存的时候在model中添加一个判断可行否？我是自己重构了保存和图片上传的方法解决的
> 
> 在表单提交回调里面尝试过，似乎不行。

我是这样搞的，你看看：

`
 if(isset($data['image_url']) && !empty($data['image_url'])){

            $savedata = $this->upload($request,"image_url");

            $insertData['image_url'] =$savedata??"";

        }

/// 这个是upload代码：

public function upload(Request $request,$key="img"){

        if(!$request->hasFile($key)){

            $request->session()->flash('error_msg','文件不存在');

            return back();

        }
        $img = $request->file($key);

        // 获取后缀名

        $ext = $img->extension();

        // 新文件名
        $saveName = md5(time().rand()).".".$ext;


        // 使用 store 存储文件

        $path = $img->store(md5(date('Ymd')));

        return $path;
    }



`
希望对你有所哦帮助

**Comment by cjx2328** [comment]
主要目的就是判断下提交的数据中图片是否有值，有的话就开始后续的上传更新的逻辑，没有就忽略。这样还可以解决更新的时候如果图片文件为空而覆盖原有图片内容的BUG
