### ISSUE TITLE
Laravel-admin form image control image source 

### ISSUE THREAD

**Issue by ncham** [z-song/laravel-admin#5118]
- Laravel Version: 4.0.5 
- PHP Version: 7.4.11
- Laravel-admin: 

### Description:
https://laravel-admin.org/docs/en/model-form-upload#Upload%20image
In my form I upload image to S3, store the image name and delete local image after that.
When I edit the record in grid it loads the form with blank image because form finds the image in local folder.
```
 'admin' => [
            'driver' => 'local',
            'root' => **storage_path('app/public')**,
            'url' => env('APP_URL').'/media',
            'visibility' => 'public',
```
Is there any way to set the image source url to form image control when editing a record?

**Comment by cjx2328** [comment]
hi there :
    just now i try config upload image . you can try config the public key 。 and this is my code
`    public function upload(Request $request,$key="img"){
        if(!$request->hasFile($key)){
            $request->session()->flash('error_msg','file not ex');
            return back();
        }
        $img = $request->file($key);
        // fileexten
        $ext = $img->extension();
        // new name
        $saveName = md5(time().rand()).".".$ext;    
        // store save 
        $path = $img->store(md5(date('Ymd')));
//        return back()->withInput(['url'=>'uploads/'.$path]);
        return $path;
    }`

may can help you

**Comment by ncham** [comment]
Thanks for your advise but my requirement is like follows.

Below is the image column of my grid
 ```
$grid->column('thumb_path', 'Thumbnail')->display(function ($picture) {
                return env('AWS_ENV') .  'FolderName/' . $picture;
            })->image(env('AWS_PATH'), 100, 100);

```
thumb_path is the column name and I store on file name(eg: sample.jpg) there.

But when setting the form image field I do like below.
$form->image('thumb_path', 'Thumbnail');

I cannot set the env('AWS_ENV') source in form field, how can I do that?

**Comment by cjx2328** [comment]
hi there
     you can config your filesystems; set the url 。 this is my config:
`
   'admin' => [
            'driver' => 'local',
            'root' => storage_path('/../public'),
            'url' =>  '/upload/',     /// there you can set the thumb_path 
            'visibility' => 'public',
        ],

`

**Comment by ncham** [comment]
It's not possible to set ('AWS_ENV') in url
`'url' =>  '/upload/',     /// there you can set the thumb_path `
