### ISSUE TITLE
如何防止表单重复提交

### ISSUE THREAD

**Issue by didiaozeng** [z-song/laravel-admin#512]
提交表单用了ajax，如果表单中包含了稍微大一点的文件，用户点击提交后，整个页面看不出变化，用户可能会继续点击。造成产生很多重复数据。可否用户点击后 提交 按钮变成loading的状态， 用户不可再次点击。

另外，用户点提交的时候，可否支持 添加一些自定义js，用js在前台做一些简单的验证。

**Comment by ajiader** [comment]
这个可以有

**Comment by zxy198717** [comment]
@z-song 这个可以有，有计划优化一下吗？

**Comment by z-song** [comment]
欢迎提交pull request

**Comment by zxy198717** [comment]
@z-song pull request 已提交，看看能merge不。

**Comment by z-song** [comment]
好的 谢谢！

**Comment by zxy198717** [comment]
可以使用 pjax:beforeSend 做简单验证。
Refer:
https://github.com/defunkt/jquery-pjax
