### ISSUE TITLE
自定义行操作 弹出表单 select联动功能不生效

### ISSUE THREAD

**Issue by 734918601** [z-song/laravel-admin#5122]
- Laravel Version: v6.20.4
- PHP Version:7.4.7
- Laravel-admin: 1.8.11

### Description:
自定义表单 使用select 联动下拉框，不生效。

### Steps To Reproduce:
```php
$this->select('county', '县')->options('/admin/selecter/county')->load('town', '/admin/selecter/town');
$this->select('town', '乡/镇')->options('/admin/selecter/town');
```

```php
    //api代码
    public function town(Request $request){
        $id = $request->get('q');
        $data =  County::where('pid',$id)->select('id','name as text')->get();
        return response()->json($data);
    }
```

**Comment by BestKind** [comment]
是bootstrap的modal框，tabindex=“-1”引起的，删掉就好了

**Comment by BestKind** [comment]
是bootstrap的modal框，tabindex=“-1”引起的，删掉就好了
找到modal的元素id，然后通过js删除tabindex属性
# 解决方式
`form`方法中引用
`Admin::script("$('#div[id^=row-action-modal]').removeAttr('tabindex')");`

上述 `div[id^=row-action-modal]` 看情况自行对应修改
[https://github.com/z-song/laravel-admin/issues/4549](url)
