### ISSUE TITLE
Switch default value on inline grid edit

### ISSUE THREAD

**Issue by herol-gl** [z-song/laravel-admin#5123]
Is there any way to get the value from DB and set the switch default value on grid?
```
	protected function grid()
	{
		$grid = new Grid(new MyDatabase);
		$states = [
			'on' => ['value' => 1, 'text' => 'yes', 'color' => 'primary'],
			'off' => ['value' => 0, 'text' => 'no', 'color' => 'default'],
		];
		$grid->column('status')->switch($states);
	}
		
	protected function form()
	{
		$form = new Form(new MyDatabase());	
		$states = [
			'on' => ['value' => 1, 'text' => 'yes', 'color' => 'primary'],
			'off' => ['value' => 0, 'text' => 'no', 'color' => 'default'],
		];
		$form->switch('status')->states($states);		
	}
```

**Comment by herol-gl** [comment]
I solved my problem by setting the default value. Not sure why it works.
`$grid->column('has_watermark')->default('on')->switch($states);`

**Comment by stonepeng** [comment]
> I solved my problem by setting the default value. Not sure why it works.
> `$grid->column('status')->default('on')->switch($states);`

@herol-gl default set the value:    

`$grid->column('status')->default(1)->switch($states);`

**Comment by herol-gl** [comment]
> > I solved my problem by setting the default value. Not sure why it works.
> > `$grid->column('status')->default('on')->switch($states);`
> 
> @herol-gl default set the value:
> 
> `$grid->column('status')->default(1)->switch($states);`

Do you know how to set the size of the switch? Not the column width.

**Comment by stonepeng** [comment]
> > > I solved my problem by setting the default value. Not sure why it works.
> > > `$grid->column('status')->default('on')->switch($states);`
> > 
> > 
> > @herol-gl default set the value:
> > `$grid->column('status')->default(1)->switch($states);`
> 
> Do you know how to set the size of the switch? Not the column width.

->style('css...')
how about this?

**Comment by herol-gl** [comment]
> > > > I solved my problem by setting the default value. Not sure why it works.
> > > > `$grid->column('status')->default('on')->switch($states);`
> > > 
> > > 
> > > @herol-gl default set the value:
> > > `$grid->column('status')->default(1)->switch($states);`
> > 
> > 
> > Do you know how to set the size of the switch? Not the column width.
> 
> ->style('css...')
> how about this?

It doesn’t work as it only change the column css. The switch is using a “bootstrap-switch-mini” class so I wonder how to change it to “bootstrap-switch-lg”.

**Comment by stonepeng** [comment]
> > > > > I solved my problem by setting the default value. Not sure why it works.
> > > > > `$grid->column('status')->default('on')->switch($states);`
> > > > 
> > > > 
> > > > @herol-gl default set the value:
> > > > `$grid->column('status')->default(1)->switch($states);`
> > > 
> > > 
> > > Do you know how to set the size of the switch? Not the column width.
> > 
> > 
> > ->style('css...')
> > how about this?
> 
> It doesn’t work as it only change the column css. The switch is using a “bootstrap-switch-mini” class so I wonder how to change it to “bootstrap-switch-lg”.

i have a idea, for example:
`$grid->header(function ($query) {
    return '<style>.bootstrap-switch-mini span.bootstrap-switch-handle-on {background:red !important}</style>'; 
});`
