### ISSUE TITLE
 php artisan admin:make UserController --model=App\User

### ISSUE THREAD

**Issue by theodoropoulos1** [z-song/laravel-admin#5125]
Hello, i just installedlaraevl-admin , everything was good , and when i jumped to quick start and ran php artisan admin:make UserController --model=App\User for windows , i faced with error model does not exists , what is the solution ? thanks

**Comment by vlados** [comment]
Try
```
php artisan admin:make "App\\User"
```

**Comment by axsweet** [comment]
php artisan admin:make Website\\OrdersController --model=App\\Models\\Orders

thats how I do it.

**Comment by alexlhc906** [comment]
Hi, I was able to do it with: 
```
php artisan admin:make UsersController --model='App\Models\User'
```
Just add quotes in the model path.

**Comment by tuyi1203** [comment]
Yes, add quotes is the point.

**Comment by ashrafulrcr43** [comment]
Why I  get Error 
I alrready create model Student 
I run this comment 
php artisan admin:controller \\App\\Models\\Student

Getting Error 
Model does not found! use, command like: artisan admin:controller \\App\\Models\\ModelName

I work with oprn-admin
