### ISSUE TITLE
数据模型setConnection方法无效bug

### ISSUE THREAD

**Issue by jinuary** [z-song/laravel-admin#5126]
- Laravel Version: 5.8.38
- PHP Version:7.4.12
- Laravel-admin: 1.8.6

### Description:
触发条件，grid方法下示列化grid ,并且model不添加任何查询条件，model有一对一的绑定关系
 $model = new model();
$model->setConnection("xxxx");
$grid=new Grid($model)

此时渲染的列表会使用默认的connection连接来查库，导致动态设置无效。

### Steps To Reproduce:

![image](https://user-images.githubusercontent.com/9252956/99667174-f8ada780-2aa6-11eb-9ff5-0f64bc5cdabf.png)

具体产生原因为model直接调用with方法为静态方法会产生新的Builder对象，不是从model里衍生出来的，导致设置的connection无效

**Comment by Endy-c** [comment]
之前也遇到过这问题，这是Laravel的问题，不是Laravel-admin的问题，Taylor关掉了相关issue，因为Laravel设计思想就不鼓励跨库建立关系，所以并不打算对这个问题进行支持。有relationship的两个模型，都放到同一个库里。
