### ISSUE TITLE
自定义footer

### ISSUE THREAD

**Issue by fangmuke** [z-song/laravel-admin#5129]
https://github.com/z-song/laravel-admin/blob/6ddd381a9f4928b6c2175dea297e6a8b385d8d28/resources/views/partials/footer.blade.php#L17

是否可以将这段html放至admin配置文件中？
虽然说可以覆盖视图，但需要创建一个新的blade文件。（我几乎每个项目都会创建）
所以希望可以在配置文件或者有更好的实现方式？

**Comment by cjx2328** [comment]
使用include来引用 
@include("/public/public_header") 
我是这样引用我的公共头部，不知道是否能解答你的问题

**Comment by fangmuke** [comment]
> 使用include来引用
> @include("/public/public_header")
> 我是这样引用我的公共头部，不知道是否能解答你的问题

No
