### ISSUE TITLE
多商户后台登陆无限重定向

### ISSUE THREAD

**Issue by nicesome** [z-song/laravel-admin#5137]
- Laravel Version: 6.X
- PHP Version:7.2
- Laravel-admin: 1.8.11

### Description:
以前开发人员让售的多商户后台系统，目前升级至 1.8.11 后就无限重定向了。目前我没有授权的情况下，有没有办法解决？

**Comment by z-song** [comment]
@nicesome 找到多后台的配置文件，默认是`config/tenancy.php`,  在里面找到配置`auth.excepts`，加上下面两项即可：

```php
    'excepts' => [

            // 加入下面两项
            'auth/login',
            'auth/logout',
    ],
```

**Comment by nicesome** [comment]
@z-song 谢谢，已解决
