### ISSUE TITLE
Show hide control according to select value

### ISSUE THREAD

**Issue by niwanta** [z-song/laravel-admin#5139]
Laravel Admin Version 1.7.8

According to the `$form->select('value')->option([0=>'Hide', 1=>'Show'])` I need to show and hide a textbox. 
`$form->text('mytext', 'My Textbox');`

Is it possible to implement this?

**Comment by mRamadan0101** [comment]
use custom javascript to show and hide form inputs

**Comment by vlados** [comment]
See https://laravel-admin.org/docs/en/model-form-linkage

**Comment by niwanta** [comment]
> See https://laravel-admin.org/docs/en/model-form-linkage

Since I'm using 1.7, the form linkage is not available.

**Comment by niwanta** [comment]
> use custom javascript to show and hide form inputs

Any sample code is available?

**Comment by vlados** [comment]
You can extend your field and copy the code from the latest version
See https://github.com/z-song/laravel-admin/blob/391dc4fce0b80fccf504865e8885a1b0a9f913a8/src/Form/Field/CanCascadeFields.php#L163
