### ISSUE TITLE
单选或多选只想要存name而不是value

### ISSUE THREAD

**Issue by dogelin** [z-song/laravel-admin#5145]
- Laravel Version: 5.7
- PHP Version:7.0
- Laravel-admin: 1.*

### Description:
我有几个单选，form表单存储的时候只想要存键值而不是key ，有这样的设置吗
![image](https://user-images.githubusercontent.com/17040400/100563308-0eb63600-32f9-11eb-8d9a-ef82dff192cd.png)

### Steps To Reproduce:
最开始想着，在saving的时候转一下，但是到编辑的时候，转了的值就没办法匹配上单选，所以想问问laravel-admin有相应的配置吗，或者我存的name，编辑的时候该如何匹配上单选

**Comment by Endy-c** [comment]
options(['武汉' => '武汉])
