### ISSUE TITLE
How to host this laravel admin on Cpanel Shared hosting

### ISSUE THREAD

**Issue by MuhaiminS** [z-song/laravel-admin#5152]
@jonphipps  @wuwx  @Fisiu  @vlados  @hayeah 
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
Dear Laravel admin Team.
I'm trying to host this project on cpanel shared hosting. But the issue was when i trying to move from public folder  all the files to root directory there are some conflict issue occurs.
Due to this the application not working. Is there best way to do this...?
Please help to figure it out...!

**Comment by vlados** [comment]
This is not laravel-admin related problem. It's more laravel case
https://www.google.com/search?q=laravel+on+cpanel&oq=laravel+on+cpanel&sourceid=chrome&ie=UTF-8

**Comment by MuhaiminS** [comment]
It's based on .htaccess file. Need to redirect the root directtory to  public folder.
