### ISSUE TITLE
关系处理--hasMany--图片显示错误 

### ISSUE THREAD

**Issue by xuanchen120** [z-song/laravel-admin#5158]
- Laravel Version: 8.17.0
- PHP Version: 7.1
- Laravel-admin: 1.8.11

### Description:
关系处理--hasMany:子表的图片字段和主表相同时，显示的是主表的图片。字段不相同时，子表的图片显示的是第一条子表数据的图片。

**Comment by yangforme** [comment]
$form->multipleImage('images', __('图片'))->setElementClass(Uuid::uuid4()->getHex());

**Comment by xuanchen120** [comment]
感谢，不过我用别名的方式解决了，之后试试这个方法。

**Comment by KillerZou** [comment]
请问有没有遇到删除图片时使用->removable()删除不掉图片的情况？点击删除后提交，刷新页面发现图片并没有被删除
代码： 
```
 $form->hasMany('test','测试',function (Form\NestedForm $nestedForm) {
       $nestedForm->multipleImage('imgs', '图片')->removable();
}
```
