### ISSUE TITLE
Multi database with SoftDeletes

### ISSUE THREAD

**Issue by rogerznts** [z-song/laravel-admin#5161]
- Laravel Version: 7.30
- PHP Version: 7.2
- Laravel-admin: 1.8.11

### Description:

I am creating an ERP that manages a group of companies. I created a database that has tables in common for all companies. Ex: authentication data, users, etc. And each company has its own database. With its relational tables. Ex: Customers, Providers, Packages, Bank, CostCenter, etc.

I created a custom AuthController that will set a session with the database id to automatically select the bank, related to the user of that company. And I use the auth rules to define this to the user.

Everything is working perfectly fine. But when I access the edit or delete, of a model that uses SoftDeletes, I get the following error.

```
  BadMethodCallException In ForwardsCalls.php line 50:
   Call to undefined method App \ Models \ Package :: withTrashed ()
```

### Steps To Reproduce:

- Set a connection to a model and use SoftDeletes.
- When editing or deleting through the grid, the error above will appear.

```
class Wallet extends Model
{
    use SoftDeletes;

    protected $connection = 'mysql_db2';

```

**Comment by mahdihassani12** [comment]
I have used below codes in my Model but still I have the same error

use SoftDeletes;
protected $connection = 'mysql2';

Can you guys please help me?
