### ISSUE TITLE
引入echarts调用报错echarts is not defined

### ISSUE THREAD

**Issue by sanye4639** [z-song/laravel-admin#5162]
- Laravel Version: 5.8
- PHP Version:7.2
- Laravel-admin: 2.0

### Description:
引入echarts，调用报错echarts is not defined（从echarts复制过来的例子，用html是正常的），但是laravel-admin例子引入chart.js就没有。这就很奇怪
![1607503466536](https://user-images.githubusercontent.com/30991208/101605986-d1128500-3a3d-11eb-97a6-38b816ef38b7.jpg)

**Comment by sunmingyang** [comment]
这个问题这么我好几天，因为好多年没写过前端代码了，所以用一种很low的办法解决的。

![image](https://user-images.githubusercontent.com/5117842/105691648-7d4df380-5f38-11eb-9a38-615f0f855d87.png)
![image](https://user-images.githubusercontent.com/5117842/105691696-8b037900-5f38-11eb-86b2-5d8802c07920.png)
![image](https://user-images.githubusercontent.com/5117842/105691758-9b1b5880-5f38-11eb-9faa-8da405a3eaf3.png)
