### ISSUE TITLE
Form Linkage in Action Class

### ISSUE THREAD

**Issue by Makennsky** [z-song/laravel-admin#5164]
- Laravel Version: 8
- PHP Version: 7.3
- Laravel-admin: 1.8

### Description:
Form Linkage in Custom Action

### Steps To Reproduce:
form linkage for radio element with options not working in custom action class. error message this:  Call to a member function cascadeGroup() on null.

**Comment by vlados** [comment]
Some code will be useful and some more info about the problem you are facing
