### ISSUE TITLE
开启xdebug，打开所有错误信息，会显示错误报告

### ISSUE THREAD

**Issue by dignfei** [z-song/laravel-admin#5167]
- Laravel Version: 7.28
- PHP Version: 7.4.8
- Laravel-admin: 1.8.10

### Description:
 Illuminate\Contracts\Container\BindingResolutionException: Target [Closure] is not instantiable while building [Encore\Admin\Layout\Content]. in /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 1017

### Steps To Reproduce:
/admin/route.php 的开头加入下面的语句：
error_reporting(E_ALL);
ini_set("display_errors","On");

**Comment by dignfei** [comment]
如何显示错误？提交表单时，如果语句错误，逻辑错误，语法错误，都不会显示，只会显示 404

**Comment by liangguifeng** [comment]
> 如何显示错误？提交表单时，如果语句错误，逻辑错误，语法错误，都不会显示，只会显示404

这个不是可以看laravel.log得到错误在哪么~

**Comment by atsimerman** [comment]
I also faced same issue:

PHP message: PHP Warning:  Uncaught Illuminate\Contracts\Container\BindingResolutionException: Target [Closure] is not instantiable while building [Encore\Admin\Layout\Content]. in /var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:1017

**Comment by liangguifeng** [comment]
> 我也面临同样的问题：
> 
> PHP消息：PHP警告：未被启发照亮\ Contracts \ Container \ BindingResolutionException：构建[Encore \ Admin \ Layout \ Content]时无法实例化目标[Closure]。在/var/www/vendor/laravel/framework/src/Illuminate/Container/Container.php:1017中

Send out the wrong code
