### ISSUE TITLE
Where can i get the Form4 Code

### ISSUE THREAD

**Issue by MuhaiminS** [z-song/laravel-admin#5169]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
@Laravel-Admin team where can i get the Form4 code ?
https://demo.laravel-admin.org/forms/form-4
I just need the above url Form4 code. Can u help me someone to get the code in laravel admin.
Thanks in advance.

@wuwx  @jonphipps  @Fisiu  @vlados  @hayeah

**Comment by vlados** [comment]
https://github.com/z-song/demo.laravel-admin.org/blob/master/app/Admin/Controllers/FormController.php#L105

**Comment by MuhaiminS** [comment]
Thanks @vlados
