### ISSUE TITLE
Filter and paginate issues  with multiple grids on one page

### ISSUE THREAD

**Issue by jonphipps** [z-song/laravel-admin#517]
You can set a unique sortname for a grid using ```$grid->model()->setSortName('v')``` and a unique perpage name using ```$grid->model()->setPerPageName('vp')```,.

Is there a way to set a unique pagination name, like ```&v[page]=2``` instead of just ```&page=2```?

Is there a way to set a unique prefix or name for the filters, like ```&v[name]=Joe``` instead of ```&name=Joe```, on each grid?

Right now, those query elements affect all of the grids on the page.

**Comment by z-song** [comment]
Not supported by now, multiple grids on one page makes it much more complicated, I have no solution about this yet.

**Comment by jonphipps** [comment]
Ok. 

I just wanted to make sure that I didn't miss something. This pushed me to find a better solution anyway. 

This is a very feature-rich and well-done project. 

Thanks!

**Comment by sepehr09** [comment]
i have same problem. any idea ?

**Comment by HeroSony** [comment]
@jonphipps Did you find solution about this issue?

**Comment by Tamaditi** [comment]
Did you find solution about this issue?

**Comment by iljalukin** [comment]
How do you add multiple grids to one page?
