### ISSUE TITLE
How to change the action icon?

### ISSUE THREAD

**Issue by xuanchau99** [z-song/laravel-admin#5170]
- Laravel Version: 5.5.50
- PHP Version: 7.4.7
- Laravel-admin: 1.8.11

### Description:
How to chang the action icon (version 1.8)
![image](https://user-images.githubusercontent.com/56724036/102174347-d35a6080-3ecf-11eb-92f1-ca7fc611920a.png)

To
![image](https://user-images.githubusercontent.com/56724036/102174400-f1c05c00-3ecf-11eb-9e9c-9e2d1a51702b.png)

Thanks.

**Comment by matondojoao** [comment]
i want to know
