### ISSUE TITLE
Selectable belongsToMany filters issuse

### ISSUE THREAD

**Issue by minhtamwebmaster** [z-song/laravel-admin#5172]
- Laravel Version: 8.0
- PHP Version: 7.3
- Laravel-admin: 1.8

### Description:

- Filter select, filter radio, filter checkbox not load jquery. Ex: iCheck, select2
- Filter Cascading select not working

My code
- Form
![image](https://user-images.githubusercontent.com/8031837/102292525-e88aca00-3f77-11eb-8777-47b1ed76b797.png)
- Selectable
![image](https://user-images.githubusercontent.com/8031837/102292557-f6d8e600-3f77-11eb-8fb8-ce13ddd891e0.png)
- UI
![image](https://user-images.githubusercontent.com/8031837/102292594-0d7f3d00-3f78-11eb-93f7-f53a33716ba4.png)

@z-song please check. Thanks

**Comment by wamilomarov** [comment]
@minhtamwebmaster what is the issue exactly? Just to note that you put the same title for both select options (2)

**Comment by wibin86** [comment]
@minhtamwebmaster select([1 => 2, 2 => 2])....the options should be select([1=>1,2=>2])
