### ISSUE TITLE
从1.8.9开始export-seed是不是只兼容laravel8了啊

### ISSUE THREAD

**Issue by wannabing** [z-song/laravel-admin#5173]
- Laravel Version: 6.18
- PHP Version:7.3
- Laravel-admin: 1.8.10

### Description:
运行 `php artisan admin:export-seed` 程序报错。文件夹seeders不存在

ErrorException  : file_put_contents(/home/vagrant/Code/xxxxx/database/seeders/AdminTablesSeeder.php): failed to open stream: No such file or directory

发现laravel6和laravel7 在datebase里面是seeds文件夹，在laravel8里面是seeders文件夹。
laravel-admin 从1.8.9开始admin:export-seed命令就改成了在seeders里面创建seeder文件，导致laravel6和7版本会报错

**Comment by TonyHappyStyle** [comment]
我也遇到了这个问题，等待解决方案！

**Comment by TonyHappyStyle** [comment]
我暂时靠修改vendor\encore\laravel-admin\src\Console\ExportSeedCommand.php里面的代码解决这个问题，将seeders改为了seeds，先将就用着，希望作者能维护这个问题
![1](https://user-images.githubusercontent.com/25560961/105046709-645ec180-5aa4-11eb-98ca-2cd225e3681c.png)
![微信截图_20210119222216](https://user-images.githubusercontent.com/25560961/105046716-66288500-5aa4-11eb-9f27-ac48bfcb1ec2.png)
