### ISSUE TITLE
v2 版本发布之后 v1 版本的维护计划

### ISSUE THREAD

**Issue by rust17** [z-song/laravel-admin#5174]
这不是一个 issue，只是我的一些疑惑，希望作者看到了可以解答一下：

1. 我从[这篇文章](https://learnku.com/articles/48845)了解到，v2 版本发布之后，不支持 v1 版本直接升级，那会不会给现有使用 v1 的用户提供迁移指导？
2. 以后是否继续维护两个版本，还是打算过一段时间（可能一年？）就放弃维护 v1 了？
3. 现在 v2 处于 beta 版本，如果现在想要提 pr 的话，是往 v1 提还是往 v2 提？

**Comment by sunmingyang** [comment]
第三个问题我可以回答，PR到v2
