### ISSUE TITLE
form表单生成mysql语句问题

### ISSUE THREAD

**Issue by guihouchang** [z-song/laravel-admin#5175]
生成的sql 字符串字段都没有带上引号？
SQLSTATE[HY000]: General error: 1364 Field 'media' doesn't have a default value (SQL: insert into `usr_media_info` (`title`, `theme_id`, `type`, `sort`, `duration`, `update_time`, `create_time`) values (测试测试测试, 1, 1, 2, 3, 2020-12-18 07:03:48, 2020-12-18 07:03:48))

**Comment by SlaraMk** [comment]
I have the same problem
