### ISSUE TITLE
How do I rewrite url website.com/admin?

### ISSUE THREAD

**Issue by panpic** [z-song/laravel-admin#5176]
- Laravel Version: 6.5
- PHP Version: 7.3
- Laravel-admin: 

### Description:
How do I rewrite url admin website.com/admin = website.com/myadmin ?

**Comment by vivozi** [comment]
please add `ADMIN_ROUTE_PREFIX="myadmin"` in your .env file
you'll find more information at https://laravel-admin.org/docs/en/configuration
