### ISSUE TITLE
Data type error while sorting multipleImage

### ISSUE THREAD

**Issue by alexvexone** [z-song/laravel-admin#5177]
- Laravel Version: 8.12
- PHP Version: 7.4
- Laravel-admin: 1.8.11

### Description:
Sorting multipleImage doesn't work. Error:
Argument 1 passed to Encore\Admin\Form\Field\MultipleFile::hydrateFiles() must be of the type array, string given, called in PATH\vendor\encore\laravel-admin\src\Form\Field\MultipleFile.php on line 78

### Steps To Reproduce:
1. Create a pictures field of json type
2. Make a mutator for this field (casts = ['pictures' => 'json'] or via get / set PicturesAttibute)
3. Add multipleImage, sortable, etc. for this.
4. Add some pictures and save
5. Try to sort the pictures you get the error 'must be of the type array, string given'

**Comment by shanmugarajah25** [comment]
I have the same issue. 
Sorting multipleImage doesn't work. Error:

**Comment by alexvexone** [comment]
@z-song help us, plz

**Comment by profaller** [comment]
Faced with same issue.

**Comment by wisp-x** [comment]
same issue.

**Comment by default-089** [comment]
similar problem.

**Comment by hh0210** [comment]
i tried to modify this, seem can work.

at Encore\Admin\Form\Field\MultipleFile Class, on getValidator() method, add in this

        if (request()->has(static::FILE_SORT_FLAG)) {
            return false;
        }

$form->submitted(function (Form $form) {            
            $request = request();            
            $img_sort = explode(",",$request->input('_file_sort_')['img']);
            $imgs = $form->model()->img;
            $new_img = [];
            foreach($img_sort as $index){
                $new_img[] = $imgs[$index];
            }
            //dd('submitted',request()->all(),$form->model()->img,$img_sort,$new_img);            
        });
