### ISSUE TITLE
1.4.x-dev not letting me remove the text field content?

### ISSUE THREAD

**Issue by smuzammilali** [z-song/laravel-admin#518]
Text field content is not letting me empty the field?

Which is nullable and with no rules working fine on 1.3.x-dev but not working on 1.4.*
Screencast video: https://www.screencast.com/t/nnN2IfxV

Also when multiple image upload coming on 1.4.*? as it's currently working on:
http://120.26.143.106/admin/demo/multiple-images/56/edit

**Comment by z-song** [comment]
This [commit](https://github.com/laravel/laravel/commit/54c5e1585a4b99acb749e3c6ab73043270768e7c) add a middleware `ConvertEmptyStringsToNull` to convert empty request data to `null`, but `laravel-admin` filtered out data with value `null`，try to remove that middleware will fix this

multiple image upload is available in 1.4.x-dev now,  and see doc here http://z-song.github.io/laravel-admin/#/en/model-form-fields.md?id=multiple-imagefile-upload
