### ISSUE TITLE
form text BUG

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#5182]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
$form->text('phone', trans('手机'))->attribute('maxlength',11);
这样写可以生效；

$form->text('phone', trans('手机'))->style('maxlength',11);
这样写不生效；

**Comment by pucoder** [comment]
请问maxlength是属性，还是css 样式？？？搞清楚再来提问题

**Comment by acclea** [comment]
> 请问maxlength是属性，还是css 样式？？？搞清楚再来提问题

是我技术太菜，不好意思。
