### ISSUE TITLE
Auth guard [admin] is not defined.

### ISSUE THREAD

**Issue by songlen** [z-song/laravel-admin#5183]
- Laravel Version: 6.18.13
- PHP Version: 7.3
- Laravel-admin: 1.8.10

### Description:
升级到 1.8.10 版本后，报错：Auth guard [admin] is not defined.
经排查发现：vendor/encore/laravel-admin/src/Middleware/Authenticate.php 
``` php
public function handle($request, Closure $next)
    {
        \config(['auth.defaults.guard' => 'admin']);

        $redirectTo = admin_base_path(config('admin.auth.redirect_to', 'auth/login'));

        if (Admin::guard()->guest() && !$this->shouldPassThrough($request)) {
            return redirect()->to($redirectTo);
        }

        return $next($request);
    }
```
```
\config(['auth.defaults.guard' => 'admin']); 
```
是这行导致的，对比了一下老版本发现，这行代码是新增的，配置里默认是 `web`

**Comment by vlados** [comment]
I think it should be `Auth::guard("admin")`

**Comment by songlen** [comment]
> I think it should be `Auth::guard("admin")`

config/auth.php 配置文件里没有 admin 的配置项，默认是 web
