### ISSUE TITLE
admin登录后出现500 internal server error

### ISSUE THREAD

**Issue by evanyeung92** [z-song/laravel-admin#519]
目前我从vendor里复制laravel-admin/views到resources/views里面，自定义了视图。
但是出现一个问题就是用其他的role登录都没问题，用admin登录的话整个页面就是空白的， 500 internal server error. Routes里面都没有问题

求解答，万分感谢

**Comment by z-song** [comment]
不太清楚你的问题，你需要打开详细异常错误看看具体的异常信息，获取看看laravel.log里面有没有详细的信息

**Comment by z-song** [comment]
没有回复先暂时关掉
