### ISSUE TITLE
sub tab displaying the field twice

### ISSUE THREAD

**Issue by travelcampadmin** [z-song/laravel-admin#5193]
$form->tab('Images',function($images) { 
         $tab = new Tab();
         $tab->add('Exterior Images',$images->multipleImage('Extimages','Exterior Images'));
         $tab->add('Interior Images',$images->multipleImage('IntImages','Interior Images'));
         $images->html($tab->render());
    });

sub tab is displaying the form field twice
how to not display the content of 
`$images->multipleImage('Extimages','Exterior Images')`
to the parent tab?

**Comment by asadkamran** [comment]
How you define
