### ISSUE TITLE
Middleware to protect page

### ISSUE THREAD

**Issue by elraghifary** [z-song/laravel-admin#52]
I've been using Menu to utilize access control for user that has a role. It works smoothly that entry menu didn't show up if user didn't have a role.

Like if user is not administrator, they can't see Users page appear on sidebar. But they still be able to open Users page by manually type http://localhost:8000/admin/auth/users.

How to protect routes like adding 401 unauthorized into laravel-admin?

**Comment by z-song** [comment]
Yes, it's really a big problem，I will update the Authenticate middleware.

**Comment by z-song** [comment]
I add  permission middleware to protect admin routes.

https://github.com/z-song/laravel-admin/blob/1.3/src/Middleware/PermissionMiddleware.php
https://github.com/z-song/laravel-admin/blob/1.3/src/Routing/Router.php#L70

**Comment by git123efasdfoojo** [comment]
Hello how do i create routes with different controllers and roles

In app\admin\routes.php

Route::group([
    'prefix' => config('admin.prefix'),
    'namespace' => Admin::controllerNamespace(),
    'middleware' => ['web', 'admin'],
        ], function (Router $router) {

If (user role is USER) {

     $Router-> group ([], function ($ router) {
         $ Router-> resource ('page', PageUserController :: class);
     });

If (user role is ADMIN) {

     $ Router-> group ([], function ($ router) {
         $ Router-> resource ('page', PageAdminController :: class);
     });

}

});
