### ISSUE TITLE
去 /admin/auth/login 总是 redirect too many times

### ISSUE THREAD

**Issue by JayChew** [z-song/laravel-admin#5203]
- Laravel Version: 5.7.29
- PHP Version: 7.4
- Laravel-admin: 1.8.10+

### Description:
update laravel-admin 1.7.16 去到 1.8.10 然后
为什么 去 /admin/auth/login 总是 redirect too many times，laravel-admin 1.7.16 没有这个问题。我该怎么做？谢谢 @z-song

**Comment by JayChew** [comment]
知道怎么解决了，那就是 在 config/admin.php 里 以下代码就可以了

`        'redirect_to' => 'auth/login',
        // The URIs that should be excluded from authorization.
        'excepts' => [
            'auth/login',
            'auth/logout',
        ],`

**Comment by bthiban** [comment]
`'auth' => [
'excepts' => [ 'auth/login', 'auth/logout', ], 

should be inside the "auth" config
`

**Comment by lljxx1** [comment]
1.7 重新安装也遇到了 diff 看是 `laravel-admin\src\Middleware\Authenticate.php` 有变更
