### ISSUE TITLE
multipleImage无法上传jpg

### ISSUE THREAD

**Issue by health901** [z-song/laravel-admin#5205]
- Laravel Version: 5.8.38
- PHP Version: 7.3.4
- Laravel-admin: 1.8.11

### Description:
multipleImage 上传图片无法上传jpg格式图片,png可以上传,界面一闪而过

### Steps To Reproduce:
` $form->multipleImage('banner', '头图')->uniqueName()->removable()->retainable();`

**Comment by health901** [comment]
laravel的bug,验证有图片出错

**Comment by Justniceone** [comment]
同样遇到这个问题，laravel 5.8.36 + laravel-admin1.7.9就没这问题

**Comment by Call-ship-it** [comment]
are there any solutions for this bug?
