### ISSUE TITLE
在 $form->hasMany 里面用select()，跑不到 options->when()

### ISSUE THREAD

**Issue by JayChew** [z-song/laravel-admin#5212]
- Laravel Version: 5.7.*
- PHP Version: 7.4
- Laravel-admin: 1.8.10

### Description:

`        $form->hasMany('form_fields', function (Form\NestedForm $form) {
            $form->select('type', __('Input type'))
                ->rules('required')
                ->options(config('enum.form_field_type'))
                ->when('checkbox', function (Form $form) {
                    $form->text('label')->rules('required|max:200');
                });
        });`
        
       当我选 checkbox, 然后没有显示 label text field ，form->table() 也是没有显示。请问我该怎么做
       
### Steps To Reproduce:
![Screenshot (111)](https://user-images.githubusercontent.com/22468507/104170379-ff6bf180-543b-11eb-957c-f223fd80ec57.png)
![Screenshot (112)](https://user-images.githubusercontent.com/22468507/104170384-0135b500-543c-11eb-95fd-f2eaa4aa2682.png)

**Comment by sunghangga** [comment]
I have the same issue
