### ISSUE TITLE
$form->hasMany 里面的 $form->table 加row 反应奇怪

### ISSUE THREAD

**Issue by JayChew** [z-song/laravel-admin#5216]
-Laravel Version: 5.7.*
- PHP Version: 7.4
- Laravel-admin: 1.8.10

### Description:
![Screenshot (117)](https://user-images.githubusercontent.com/22468507/104429530-ae393a80-55c0-11eb-9856-abc6f1298514.png)

![Screenshot (118)](https://user-images.githubusercontent.com/22468507/104428864-ef7d1a80-55bf-11eb-9530-1f3ddf27cce4.png)
![Screenshot (119)](https://user-images.githubusercontent.com/22468507/104429094-2eab6b80-55c0-11eb-9bbd-118230f21fe1.png)

https://user-images.githubusercontent.com/22468507/104429223-569acf00-55c0-11eb-9f4e-48e2a1da0ea2.mp4

这个问题我就用视频来解释就好了. 不讲这么多

**Comment by lishuai199502** [comment]
![image](https://user-images.githubusercontent.com/23136422/115176772-57cc2280-a100-11eb-8b72-164c32ab2737.png)
大佬解决了没，我也想这样横排。加table倒是能横，就每次提交都会把原数据再重新插入一遍。
