### ISSUE TITLE
Unable to upload Multiple Images

### ISSUE THREAD

**Issue by shanmugarajah25** [z-song/laravel-admin#5219]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

**Controller**

    protected function form()
    {
        $form = new Form(new Testing());

        $form->text('name', __('Name'));
        $form->multipleImage('pictures','Images');

        return $form;
    }

-----------------------

 protected $table = 'testings';

    public function getPicturesAttribute($pictures)
    {
        if (is_string($pictures)) {
            return json_decode($pictures, true);
        }
        return $pictures;
    }

    public function setPicturesAttribute($pictures)
    {

        if (is_array($pictures)) {
            $this->attributes['pictures'] = json_encode($pictures);
        }
    }
### Steps To Reproduce:
![Capture](https://user-images.githubusercontent.com/28956107/104831028-c8b63100-58aa-11eb-857e-7fc32ca61508.PNG)

**Comment by AnupDPokhrel** [comment]
did you try adding 
`protected $appends = ['pictures'];`
in your model.

**Comment by shanmugarajah25** [comment]
**I Tried the below code**

```
   $form->multipleFile('pictures')
       ->rules('mimes:jpeg,png,jpg');

```
**It's Working fine 😊**
