### ISSUE TITLE
异步加载modal，参数要怎么传递啊

### ISSUE THREAD

**Issue by fanhengyuan** [z-song/laravel-admin#5220]
PHP version | PHP/7.4.14
Laravel version | 6.20.12
- Laravel-admin:  1.8.11
### Description:

参考
https://laravel-admin.org/docs/zh/1.x/model-grid-column-display#%E5%BC%82%E6%AD%A5%E5%8A%A0%E8%BD%BD

```php
$grid->expand('user', '标题')->modal(ShowUser::class);
```

异步加载怎么获取到 当前行参数
同步加载是可以的

```php
use Illuminate\Contracts\Support\Renderable;

class ShowUser implements Renderable
{
    public function render($key = null)
    {
        dump(User::find($key)->toArray());
    }
}
```

**Comment by fanhengyuan** [comment]
```bash
admin/_handle_renderable_?renderable=App_Admin_Actions_SurgicalPatient_SurgeryCost&key=
```
我看 浏览器network中 key=  要怎么赋值

**Comment by sunmingyang** [comment]
根据当前model的主键自动进行传参处理

**Comment by Huangjunlin** [comment]
> 根据当前model的主键自动进行传参处理

你好，可以大概讲一下是怎么写的吗，试了好久，谢谢了

**Comment by Huangjunlin** [comment]
> PHP version | PHP/7.4.14
> Laravel version | 6.20.12
> 
> * Laravel-admin:  1.8.11
> 
> ### Description:
> 参考
> https://laravel-admin.org/docs/zh/1.x/model-grid-column-display#%E5%BC%82%E6%AD%A5%E5%8A%A0%E8%BD%BD
> 
> ```
> $grid->expand('user', '标题')->modal(ShowUser::class);
> ```
> 
> 异步加载怎么获取到 当前行参数
> 同步加载是可以的
> 
> ```
> use Illuminate\Contracts\Support\Renderable;
> 
> class ShowUser implements Renderable
> {
>     public function render($key = null)
>     {
>         dump(User::find($key)->toArray());
>     }
> }
> ```
> 
> ### Steps To Reproduce:

你的问题解决了吗

**Comment by Huangjunlin** [comment]
`

namespace App\Admin\Renderable;

use Dcat\Admin\Support\LazyRenderable;

class GoodTable extends LazyRenderable
{

    public function render()
    {
        dd($this->payload['key']);
    }
}`
原来这样就可以获得当前行的主键id，弄了半天

**Comment by fanhengyuan** [comment]
> `
> 
> namespace App\Admin\Renderable;
> 
> use Dcat\Admin\Support\LazyRenderable;
> 
> class GoodTable extends LazyRenderable
> {
> 
> ```
> public function render()
> {
>     dd($this->payload['key']);
> }
> ```
> 
> }`
> 原来这样就可以获得当前行的主键id，弄了半天

我的这个key是空的，应该是要指定主键。
