### ISSUE TITLE
router 默认为管理后台了

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#523]
在模板中使用router方法时，默认相对于admin了，该怎么改回来啊
`router('tree')`生成了 localhost/admin/tree了

**Comment by z-song** [comment]
我没有找到`router()`方法,  你的laravel 版本？

**Comment by iianpan** [comment]
打错了，是route方法。
发现原来是直接找后台的`resource('tree')`去了，打扰了，不好意思
