### ISSUE TITLE
Undefined variable: strAllowClear

### ISSUE THREAD

**Issue by vonsogt** [z-song/laravel-admin#5237]
- Laravel Version: 8.12
- PHP Version: 7.4.11
- Laravel-admin: 2.0.0 Beta 5

### Error Messages:
` Undefined variable: strAllowClear (View: D:\...\vendor\encore\laravel-admin\resources\views\form\select.blade.php)`

### Description:
When using `->load()` on select depends, it will returns this error `Undefined variable: strAllowClear (line: 44)`, after fix that another variable `$idField` then `$textField` too.

and the closing of function was missing too at `@isset($load)`:
```
$(this).off('change').on('change', function () {
    var target = $(this).closest('.fields-group').find(".{{ $load['class'] }}");
    $.get("{{ $load['sourceUrl'] }}",{q : this.value}, function (data) {
         ...
    });
}); // this line was missing
```

I tried to figure out the solution for this problem, soon I will do pull request

**Comment by sajjad606** [comment]
hi, if you are in iran you can pay any forign payments via our web site.
سایت EPAY 724 | خدمات ارزی بین الملل (https://bit.ly/3uieWwW) (سایت EPAY 724 | خدمات ارزی بین الملل (https://epay724.com))
online payments for application fees, buying gift cards, international exams fees are easier than ever ….

**Comment by jiangtao6888** [comment]
```
$form->select('brand_id', __('Brand'))->options(ProductBrand::getName())->load('type_id', 'list/types');
$form->select('type_id', __('Type'))->options(function ($id) {
    return ProductType::getName($id);
});

```
ViewException In 8962c60f5af1fd89f223e0e7afde37c74f871071.php line 44 :
[  Undefined variable $strAllowClear (View: /Users/jiangtao/Code/php/baby-service/vendor/encore/laravel-admin/resources/views/form/select.blade.php) (View: /Users/jiangtao/Code/php/baby-service/vendor/encore/laravel-admin/resources/views/form/select.blade.php)]()

我应该如何解决这个问题

**Comment by rooma1989** [comment]
> ```
> $form->select('brand_id', __('Brand'))->options(ProductBrand::getName())->load('type_id', 'list/types');
> $form->select('type_id', __('Type'))->options(function ($id) {
>     return ProductType::getName($id);
> });
> ```
> 
> ViewException In 8962c60f5af1fd89f223e0e7afde37c74f871071.php line 44 : Undefined variable $strAllowClear (View: /Users/jiangtao/Code/php/baby-service/vendor/encore/laravel-admin/resources/views/form/select.blade.php) (View: /Users/jiangtao/Code/php/baby-service/vendor/encore/laravel-admin/resources/views/form/select.blade.php)
> 
> 我应该如何解决这个问题

请看我上面这段代码，变量错了，应该加上load和loads
