### ISSUE TITLE
大佬好，单表100万+的内容，打开卡死，请教下怎么把翻页改成上下页模式

### ISSUE THREAD

**Issue by ieliwb** [z-song/laravel-admin#5239]
每次打开会 select count(*) as aggregate 导致卡死几十秒，请问怎么改掉这个啊

**Comment by xiaomlove** [comment]
什么上下翻页的模式，语句什么样的？这里渲染的分页都需要总数的。

**Comment by ieliwb** [comment]
@xiaomlove 大佬好，laravel 的 simplePaginate 模式，上下翻页，好像不需要总数
现在需要总数的太卡了，100万+数据特别是带上条件查询，基本要等很久

**Comment by xiaomlove** [comment]
@ieliwb 整个项目搜索都没有 `simplePaginate`，看来没有支持。

**Comment by never615** [comment]
一千四百万数据没有因为 select count(*) as aggregate卡死。你是加了其他查询条件没有加索引吧？
