### ISSUE TITLE
Filter where

### ISSUE THREAD

**Issue by andervilo02** [z-song/laravel-admin#524]
Hi, I'd like a example  code how to use filter->where() in grid component. I search in your doc site but I find only one example using between. 

Thanks

**Comment by z-song** [comment]
Use `$filter->where()` you can use original eloquent syntax to achieve data filtering, mainly used to achieve some of the more complex data filtering.

[Here](http://z-song.github.io/laravel-admin/#/en/model-grid.md?id=add-query-filters) has three examples to show you how to use it.

**Comment by andervilo02** [comment]
Thank you. I was so near to the example And I can't see this. This help me a lor
