### ISSUE TITLE
在edit時替換文件名

### ISSUE THREAD

**Issue by Haogood** [z-song/laravel-admin#525]
請問在edit時有方法在顯示的時候替換原始的文件名嗎?
例如上傳時隨機產生的文件名，在edit的時候將文件名替換成其他的內容
(只替換顯示的內容，實際文件名仍保持uniqueName)
![3](https://cloud.githubusercontent.com/assets/22260295/23603311/90fa6ef4-028f-11e7-851d-9e7a5d1f8bf7.png)

**Comment by z-song** [comment]
在model中定义accessor
比如字段名为`picture`
```php
public function getPictureAttribute($picture)
{
    return '你想显示的文件名';
}
```

**Comment by Haogood** [comment]
已經在model中定義accessor，文件名還是沒法代換，文件也不顯示了

```php
class Upload extends Model
{

    ...

    protected $fillable = ['FL_vcrFileKey'];

    public function getFileNameAttribute($value) {
        return 'abc';
    }
}
```


```php
class UploadController extends Controller
{

    ...

    protected function form()
    {
        return Admin::form(Upload::class, function (Form $form) {
            $form->file('file_name', '文件名');
        }
    }
}
```

對應數據庫的column字段為FL_vcrFileKey，內容為file/719449e9444995998e3aaf3b994d7ba0.jpeg
想代換為abc.jpeg呈現於edit頁面

**Comment by z-song** [comment]
暂不能实现
