### ISSUE TITLE
建议数据库从env取值

### ISSUE THREAD

**Issue by wingofsky** [z-song/laravel-admin#526]
发到线上时数据库各种连接报错，发现是写死在了admin里，建议还是env()取值吧。我自己已经改过来了。

**Comment by edwinhuish** [comment]
貌似都是env取值的啊？

**Comment by wingofsky** [comment]
啊，我说的是：https://github.com/z-song/laravel-admin/blob/1.4/config/admin.php

**Comment by edwinhuish** [comment]
这个也是一个配置文件，本来就是根据需要修改的。

如果你指的是下面这个配置：
```
        // Database connection for following tables.
        'connection'  => '',
```

这个仅仅是database.php 里面的 'connections' 的配置的主键的string，数据库配置我一直用env，没有任何问题。

你出问题的话，最好还是从你自身的环境检查一下

**Comment by wingofsky** [comment]
嗯，刚才试了一下，原来为空就是直接从env里取的值
