### ISSUE TITLE
如何迁移菜单？

### ISSUE THREAD

**Issue by williamtse** [z-song/laravel-admin#5266]
- Laravel Version: 1.8
- PHP Version: 7.2
- Laravel-admin: #.#.#

### Description:
本地开发创建的菜单，部署项目到服务器，菜单又得手动创建很麻烦哦，能把菜单迁移的功能做上去吗？还有权限等数据的迁移

**Comment by miaotaizi** [comment]
可以看下 Encore\Admin\Extension::import() 逻辑

**Comment by lihe6666** [comment]
这个有必要搞一下！
