### ISSUE TITLE
「BUG」From  儅一個頁面表單超過出一定數量時，驗證消息不顯示，直接重置頁面，重現見錄屏

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#5267]
- Laravel Version: 8.x
- PHP Version: 7.4
- Laravel-admin: 1.8.1

### Description:
1. 儅表單數量為 13 則時，表單驗證錯誤提示正常顯示
2. 儅表單數量為 14 則時，表單驗證錯誤提不顯示，頁面自动刷新
3. 貌似與表單字段類型無關
2. 類似的情況我應該如何阻止頁面刷新，捕獲並抛出異常？

### Steps To Reproduce:

https://user-images.githubusercontent.com/8817046/111035046-5c435280-8453-11eb-9158-dbe434efdda1.mp4

**Comment by miaotaizi** [comment]
会不会跟 Session 的驱动有关, 我之前使用文件驱动的Session时 会有一些比较奇怪的问题, 猜测是文件读写性能导致. 可以试试 Redis 驱动

**Comment by Xuan-Goldenf** [comment]
```
看一下 env 的 CACHE_DRIVER=file 的配置
```
