### ISSUE TITLE
关于https的问题

### ISSUE THREAD

**Issue by 503580622** [z-song/laravel-admin#5268]
- Laravel Version: #.#.#
- PHP Version: 7.4.14
- Laravel-admin: 1.8.11

### Steps To Reproduce: 配置证书
![image](https://user-images.githubusercontent.com/19412082/111035320-df18dd00-8454-11eb-8a8f-9ccfea203cec.png)

不明白这里为啥要把null转成bool，给个null让他自适应不行吗，非要在.env中配置ADMIN_HTTPS才行

**Comment by mRamadan0101** [comment]
add ADMIN_HTTPS=true in .env

**Comment by 503580622** [comment]
我知道加这个配置，不能自动适应吗，每次加了证书还要去配置一下
