### ISSUE TITLE
请问如何禁用删除？以及如何使用软删除？

### ISSUE THREAD

**Issue by fasthold** [z-song/laravel-admin#527]
发现 $grid->disableBatchDeletion() 已经 deprecated 了，现在只要一点删除就是物理删除，也没找到文档里有写如何利用 laravel 的软删除

谢谢！

**Comment by fasthold** [comment]
已找到如何去掉“删除”

“软删除”是否需要自己写接口？

**Comment by zxy198717** [comment]
@fasthold 软删除是laravel默认支持的。
https://laravel.com/docs/5.4/eloquent#soft-deleting

**Comment by z-song** [comment]
http://120.26.143.106/admin/demo/posts   这个demo就是软删除，模型，表结构都有

**Comment by leung0826** [comment]
@z-song 这个地址访问不了哦

**Comment by mountainguan** [comment]
代码地址应该是这里https://github.com/z-song/laravel-admin.org/blob/master/app/Admin/Controllers/PostController.php
但是我没发现怎么软删除，只看见对被软删除的数据进行检索。然后我也在demo的网站上试了一下，根本删不掉
