### ISSUE TITLE
问题改善反馈，关于 $.admin

### ISSUE THREAD

**Issue by sunpluto2004** [z-song/laravel-admin#5271]
- Laravel Version: 8
- PHP Version: 8
- Laravel-admin: 2.0

先感谢一下项目，很不错的学习标的，赞

### Description:

在 Home 页面中，因 js 异步加载的原因，直接刷新页面会报 $.admin 对象无法找到

### Steps To Reproduce:

提供一个解决方案，partials/toastr.blade.php 中 在 $(function () { 外再加一个函数，像如下这样

<script>
        require(['jquery', 'admin'], function (){
            $(function () {
                $.admin.toastr.{{$type}}('{!!  $message  !!}', {!! $options !!});
            });
        });
        {{--$.admin.toastr.{{$type}}('{!!  $message  !!}', {!! $options !!});--}}
</script>

因为脚本是异步加载的，所以需要等脚本加载完毕，对象生成后，才能进行调用

**Comment by Caisen1988** [comment]
@sunpluto2004  请问如何解决这个问题呢

**Comment by sunpluto2004** [comment]
@Caisen1988 我是把 admin 的 toastr.blade 模板复制出来，然后再修改  $(function () {，改为 require(['jquery', 'admin'], function (){  的，这样当 admin 对象有效时，才会执行脚本
