### ISSUE TITLE
How to add custom html or blade code to footer

### ISSUE THREAD

**Issue by schel4ok** [z-song/laravel-admin#5273]
- Laravel Version: 8.26.1
- PHP Version: 8.0.2
- Laravel-admin: 1.8.11

How to add custom html or blade code to footer?
I need to add my pack of SVG icons, which I use in frontend like that `<x-svgpack/>`

**Comment by bashman** [comment]
1. Put this code in Admin/bootstrap.php
 `app('view')->prependNamespace('admin', resource_path('views/admin'));`
2. Copy entire folder vendor/encore/laravel-admin/resources/views/* to resources/views/admin

Enjoy

**Comment by attentive20** [comment]
> 1. Put this code in Admin/bootstrap.php
>    `app('view')->prependNamespace('admin', resource_path('views/admin'));`
> 2. Copy entire folder vendor/encore/laravel-admin/resources/views/* to resources/views/admin
> 
> Enjoy

Another way is to apply js to override footer content

**Comment by schel4ok** [comment]
what do you mean to override footer using js?

**Comment by attentive20** [comment]
For example. Original footer
![footer1](https://user-images.githubusercontent.com/71190913/113701715-2fe0c600-96e1-11eb-94c3-209c942cda54.jpg)
In Admin/bootstrap.php, include your js file `Admin::js('/js/custom.js');`
Custom.js file:
`$(document).on('ready pjax:end', function () {
    $(function(){
            $('.main-footer').html('Hello World')
   });
})
`
Our footer now looks like this:
![footer2](https://user-images.githubusercontent.com/71190913/113702792-a92ce880-96e2-11eb-8da1-76c8f0f4c099.jpg)

Another way is to edit the sources.
