### ISSUE TITLE
how to format the data before edit form is rendered?

### ISSUE THREAD

**Issue by jayblendit** [z-song/laravel-admin#5274]
- Laravel Version: 8.12.0
- PHP Version: 7.4.14
- Laravel-admin: 1.8.0

### Description:
I'm using this package: https://github.com/spatie/laravel-translatable to make model fields translatable.

Creating entry is working. Translation is saved. 

See here: https://prnt.sc/10tgp3b

As you can see field "title" & "text" has array as value.

But when I go to edit, following error happens:

https://prnt.sc/10tgtp0

On create view, here is the form:

https://prnt.sc/10tgv6e

I know that the reason the edit form is not working is because of the array value of the column after save (because of the package).

I have tried setting the form field default value but still has error.

My question is, how to format the data before edit form is rendered?

Thank you in advance.

**Comment by loicgeek** [comment]
@jayblendit  any update on this?
