### ISSUE TITLE
不建议使用 cdn 方式引入 css，js 文件

### ISSUE THREAD

**Issue by miaotiao** [z-song/laravel-admin#5275]
- Laravel Version: 8.30.1
- PHP Version:7.4
- Laravel-admin: 1.8.11

### Description:
不太明白 flatpickr 为什么会使用 cdn 的方式部署
建议使用静态文件方式部署。

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/28383349/112416675-15156580-8d61-11eb-9994-971352a00443.png)

**Comment by pucoder** [comment]
https://github.com/pucoder/laravel-admin 看看这个包，满足要求
