### ISSUE TITLE
conflicts with Laravel 8.x and require doctrine/dbal ? 

### ISSUE THREAD

**Issue by swansun95** [z-song/laravel-admin#5278]
- Laravel Version: 8.1.2
- PHP Version: 7.3.11
- Laravel-admin: #.#.#

### Description:
Can not install laravel-admin 1.x or 2.x on Laravel 8.1.2

Problem 1
    - encore/laravel-admin[v1.1.6, ..., 1.1.x-dev] require laravel/framework 5.1.* -> found laravel/framework[v5.1.0, ..., 5.1.x-dev] but it conflicts with your root composer.json require (^8.12).
    - encore/laravel-admin[v1.2.6, ..., 1.2.x-dev] require laravel/framework 5.2.* -> found laravel/framework[v5.2.0-beta1, ..., 5.2.x-dev] but it conflicts with your root composer.json require (^8.12).
    - encore/laravel-admin[v1.3.3, ..., 1.3.x-dev] require laravel/framework 5.3.* -> found laravel/framework[v5.3.0-RC1, ..., 5.3.x-dev] but it conflicts with your root composer.json require (^8.12).
    - encore/laravel-admin 1.4.x-dev requires laravel/framework 5.4.* -> found laravel/framework[v5.4.0, ..., 5.4.x-dev] but it conflicts with your root composer.json require (^8.12).
    - encore/laravel-admin 1.5.x-dev requires laravel/framework ~5.5 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev] but it conflicts with your root composer.json require (^8.12).
    - encore/laravel-admin[v1.4.1, ..., v1.4.6] require symfony/dom-crawler 3.1.* -> found symfony/dom-crawler[v3.1.0-BETA1, ..., 3.1.x-dev] but it conflicts with your root composer.json require (^5.2).
    - encore/laravel-admin[v1.5.5, ..., v1.5.19] require symfony/dom-crawler ~3.1 -> found symfony/dom-crawler[v3.1.0-BETA1, ..., 3.4.x-dev] but it conflicts with your root composer.json require (^5.2).
    - encore/laravel-admin[v1.6.0, ..., v1.7.8] require symfony/dom-crawler ~3.1|~4.0 -> found symfony/dom-crawler[v3.1.0-BETA1, ..., 3.4.x-dev, v4.0.0-BETA1, ..., 4.4.x-dev] but it conflicts with your root composer.json require (^5.2).
    - encore/laravel-admin v1.7.9 requires laravel/framework ~5.5|~6.0 -> found laravel/framework[v5.5.0, ..., 5.8.x-dev, v6.0.0, ..., 6.x-dev] but it conflicts with your root composer.json require (^8.12).
    - encore/laravel-admin[v1.7.11, ..., v1.8.11] require doctrine/dbal 2.* -> found doctrine/dbal[2.1.5, ..., 2.13.x-dev] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires encore/laravel-admin 1.* -> satisfiable by encore/laravel-admin[v1.1.6, ..., v1.8.11].

### Steps To Reproduce:

composer require encore/laravel-admin:1.*

can Laravel-admin support Laravel 8.x ?
thanks

**Comment by attentive20** [comment]
Recently I updated Laravel from 7.x to 8.x. At the same time, laravel-admin from 1.8.6 to 1.8.11. Not a single problem has arisen yet.

**Comment by olezhkafp** [comment]
I have the same error with laravel 8

Problem 1
    - encore/laravel-admin[v1.8.0, ..., v1.8.12] require doctrine/dbal 2.* -> found doctrine/dbal[2.1.5, ..., 2.13.x-dev] but it conflicts with your root composer.json require (^3.0).
    - Root composer.json requires encore/laravel-admin ^1.8 -> satisfiable by encore/laravel-admin[v1.8.0, ..., v1.8.12].
