### ISSUE TITLE
grid 显示扩展的问题

### ISSUE THREAD

**Issue by Makingss** [z-song/laravel-admin#528]
Model:
![image](https://cloud.githubusercontent.com/assets/23512926/23613612/2317beb0-02bb-11e7-999a-45055a679fc4.png)
![image](https://cloud.githubusercontent.com/assets/23512926/23613622/2e5ac2ea-02bb-11e7-8ae7-227e1a544954.png)

grid:

报错：
![image](https://cloud.githubusercontent.com/assets/23512926/23613653/52a54c42-02bb-11e7-92f5-d907ae73dc79.png)

grid修改成：
![image](https://cloud.githubusercontent.com/assets/23512926/23613699/78ebce1c-02bb-11e7-88cd-a97b0d9ad153.png)

报错：
![image](https://cloud.githubusercontent.com/assets/23512926/23613713/8712b8b6-02bb-11e7-8b9d-ae8208433cea.png)

求解！！！！

**Comment by z-song** [comment]
`$grid->column('electric')` 还是 `$grid->column('electrics')` ??

**Comment by Makingss** [comment]
$grid->column('electrics')->electric(function () use ($getElectricColumns)

**Comment by z-song** [comment]
没有这样的用法   只有display方法，另外报错已经很清楚了，你打印下74行的$this 就知道怎么取值了
