### ISSUE TITLE
pjax 扩展冲突

### ISSUE THREAD

**Issue by 761042678** [z-song/laravel-admin#5282]
- Laravel Version: 5.6
- PHP Version:7.2
- Laravel-admin: 1.6

### Description:
本人基于 laravel 5.6 框架开发的网站，前台部分页面加载也是使用的 pjax 局部刷新技术，pjax 是基于 spatie/laravel-pjax 扩展开发的，这个扩展需要在 app/Http/Kernel.php 的 $middleware 数组中引入一个 pjax 类才能使用；

但是引入这个类之后，laravel-admin 后台就出问题了，所有页面F5刷新全量加载的时候没问题能正常展示，但是页面内的 pjax 加载会报错，未知错误，经查看源码确认是前台的这个 pjax 扩展中间件过滤的问题；明显是 laravel-admin 后台的 pjax 加载和我前台自己安装的 pjax 扩展冲突了；

这个问题目前自己没有找到比较好的解决办法；我只能在使用 laravel-admin 后台时注释掉这个 pjax 类（在 app/Http/Kernel.php 的 $middleware 数组中）的引入，使用完后台后再还原

**Comment by pucoder** [comment]
你的pjax中间件不要放到web中间件的组里面，在前台路由中单独使用即可解决问题

**Comment by 761042678** [comment]
> 你的pjax中间件不要放到web中间件的组里面，在前台路由中单独使用即可解决问题

好的，我试试看；谢谢大侠
