### ISSUE TITLE
Would you please update the bootstrap and jQuery versions?

### ISSUE THREAD

**Issue by TakanashiAsuka** [z-song/laravel-admin#5295]
- Laravel-admin: 1.8

### Description:
When I was diagnosing with OWASP ZAP, I got an alert called "Vulnerable JS Library".
After checking the details, it seems that the versions of "laravel-admin/AdminLTE/bootstrap/js/bootstrap.min.js" and "laravel-admin/AdminLTE/plugins/jQuery/jQuery-2.1.4.min.js" are old.

I don't know how dangerous it is because I don't have much security knowledge, but if there is a danger, I would appreciate it if you could fix it.

**Comment by Endy-c** [comment]
I think you could update that two files by yourself, the easiest way is directly copy and replace content from new version without changing file names. So you don't need to edit any reference of these two files.
After doing replacement and test, you may change the filename to real, update all references and create a PR for the project if it works fine with new version.
