### ISSUE TITLE
不选择图片无法更新?

### ISSUE THREAD

**Issue by qq447665722** [z-song/laravel-admin#53]
![image](https://cloud.githubusercontent.com/assets/14967427/19377447/0c6f8db8-9219-11e6-8587-b5ad23dc80c5.png)
这是你的demo页面,保存已经存在的表单,如果不选择图片会报错,是哪里可以设置?

**Comment by z-song** [comment]
在laravel5.3里面确实有这个问题，已经修复

谢谢反馈！
