### ISSUE TITLE
关于Slider 取范围的问题

### ISSUE THREAD

**Issue by Makingss** [z-song/laravel-admin#532]
![image](https://cloud.githubusercontent.com/assets/23512926/23692747/7913a5d0-040b-11e7-8b8a-804f229b26c6.png)
怎么样像下面效果取范围
![image](https://cloud.githubusercontent.com/assets/23512926/23692772/9919ea60-040b-11e7-907c-e7b5ecd2f7f2.png)

**Comment by z-song** [comment]
`$form->slider('xxx')->options([]);`

options参考https://github.com/IonDen/ion.rangeSlider#settings

**Comment by Makingss** [comment]
谢谢提供的文档，问题已解决！
