### ISSUE TITLE
multipleSelect click clear all option and choose againt this was add in list empty first option

### ISSUE THREAD

**Issue by vuongutc** [z-song/laravel-admin#5321]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Steps To Reproduce:

![3](https://user-images.githubusercontent.com/59592052/118248897-029cea00-b4cf-11eb-9f94-d4072cb721e2.png)

**Comment by jxlwqq** [comment]
show me the code, please. is is a grid filter?

**Comment by vuongutc** [comment]
![Screen Shot 2021-05-14 at 22 06 54](https://user-images.githubusercontent.com/59592052/118290532-bd91ab80-b500-11eb-9fa6-86b74f48162f.png)
Thank for comment. it's my code

**Comment by jxlwqq** [comment]
https://github.com/select2/select2/issues/4742

**Comment by jxlwqq** [comment]
I think, it is a bug of select2. no solution yet.

**Comment by vuongutc** [comment]
The first thank bro. this is my issues.
