### ISSUE TITLE
Not showing validation errors 

### ISSUE THREAD

**Issue by trikey** [z-song/laravel-admin#5322]
- Laravel Version: 8.40.0
- PHP Version: 7.4.16
- Laravel-admin: 1.8.11

### Description:
Validation works, but there are no visible errors. After form submitted it redirects back without updating model.

### Steps To Reproduce:

$form->number('max_answers', __('fields.max_answers'))
            ->default(1)
            ->min(1)
            ->max(100)
            ->rules('exclude_if:is_multiple,off|numeric|min:2')
        ;

**Comment by abdulPike** [comment]
@trikey did you solved this problem. kindly share the answer.
