### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by fadoi-nhaila** [z-song/laravel-admin#5323]

**Comment by jxlwqq** [comment]
Please show me the code of `Commande.php` and `Client.php`.

**Comment by fadoi-nhaila** [comment]
ok the code look like this:


class Client extends Model
{
    use HasFactory;

    public function commandes()
    {
        return $this->hasMany(Commande::class,'id_client');
    }
}


class Commande extends Model
{
    use HasFactory;

    public function client()
    {
        return $this->belongsTo(Client::class,'id_client');   
    }

}
