### ISSUE TITLE
[Bug] Model-tree form component does not work with a MSSQLSERVER database

### ISSUE THREAD

**Issue by a157147899** [z-song/laravel-admin#5324]
- Laravel Version: 8.41.0
- PHP Version:PHP/7.3.5
- Laravel-admin: 1.*

### Description:
It will throw a SQL syntax exception when using a model-tree component in a controller and the table of the model is from an MSSQLSERVER database. It seems the select query only cater for MySQL database but not MSSQLSERVER. I double-checked the column names and ensured they are correct.

### Steps To Reproduce:
Exception:
![image](https://user-images.githubusercontent.com/1812136/118795553-cd3d3580-b8ee-11eb-80ff-19cc6a7132dd.png)

Model Definition:
```php
<?php

namespace App\Models;

use Encore\Admin\Traits\ModelTree;
use Illuminate\Database\Eloquent\Model;

class tCategory extends Model
{
    use ModelTree;

    protected $connection = 'sqlsrv';

    protected $table = 'tCategory';

    protected $primaryKey = 'ID';

    public $timestamps = false;

    public function __construct(array $attributes = [])
    {
        parent::__construct($attributes);

        $this->setParentColumn('ParentID');
        $this->setOrderColumn('OrderIndex');
        $this->setTitleColumn('Title');
    }
}
```
Controller definition:
```php
<?php

namespace App\Admin\Controllers;

use App\Http\Controllers\Controller;
use App\Models\tCategory;
use Encore\Admin\Tree;
use Encore\Admin\Layout\Content;

class CategoriesController extends Controller
{
    public function index(Content $content)
    {
        $tree = new Tree(new tCategory());

        return $content
            ->header('Tree testing')
            ->body($tree);
    }
}

```

Table definition:
![image](https://user-images.githubusercontent.com/1812136/118796372-a9c6ba80-b8ef-11eb-9602-8122cacc00b3.png)

**Comment by wamilomarov** [comment]
hi @a157147899 did you find a solution for tihis?
