### ISSUE TITLE
problen in export

### ISSUE THREAD

**Issue by mcsham** [z-song/laravel-admin#5329]
- Laravel Version: #.#.# 8.32.1
- PHP Version:8.0.5
- Laravel-admin: #.#.# last

### Description:
I have a formatted page, I need to export to csv
![image](https://user-images.githubusercontent.com/40900923/119545429-79719700-bd9b-11eb-8365-ce67f159621f.png)
in the end I get a document with html tags
![image](https://user-images.githubusercontent.com/40900923/119545501-8ee6c100-bd9b-11eb-9ea2-17a87347e0e0.png)
How can I fix this so that there is only data without html, despite the fact that I have dependencies and dynamic conversion of a number (for example, status) to a string?

**Comment by mori-apptime** [comment]
Hi
try this .
`$grid->export(function ($export) {

    $export->filename('Filename.csv');

    $export->except(['column1', 'column2' ...]);

    $export->only(['column3', 'column4' ...]);
    //↓this
    $export->originalValue(['column1', 'column2' ...]);

    $export->column('column_5', function ($value, $original) {
        return $value;
    )};
});`

**Comment by mcsham** [comment]
> Hi
> try this .
> `
> $grid->export(function ($export) {
> 
> ```
> $export->filename("Filename.csv");
> 
> $export->except(["column1", "column2" ...]);
> 
> $export->only(["column3", "column4" ...]);
> //↓this
> $export->originalValue(["column1", "column2" ...]);
> 
> $export->column("column_5", function ($value, $original) {
>     return $value;
> )};
> ```
> 
> });
> `
I tried it, it works crookedly for me.
