### ISSUE TITLE
[HELP] New page doesn't show, why?

### ISSUE THREAD

**Issue by sweggggg** [z-song/laravel-admin#533]
I am still new to laravel, and i need an option like "Orderable Grid" in this demo page admin/demo/articles. I did everything it did in code, schema and model tab.

so i put this code as ArticleController.php in app/Admin/Controllers/

> <?php

namespace App\Admin\Controllers\Demo;

use App\Http\Controllers\Controller;
use App\Models\Article;
use Encore\Admin\Form;
use Encore\Admin\Grid;
use Encore\Admin\Facades\Admin;
use Encore\Admin\Layout\Content;
use Encore\Admin\Controllers\ModelForm;
use Encore\Admin\Widgets\Tab;

class ArticleController extends Controller
{
    use ModelForm;
    ...

    protected function grid()
    {
        return Admin::grid(Article::class, function (Grid $grid) {

            $grid->model()->ordered();

            $grid->id('ID')->sortable();

            $grid->title()->editable();
            $grid->content()->editable();
            $grid->picture()->image();

            $grid->order()->orderable();

            $grid->created_at();
            $grid->updated_at();
        });
    }

    protected function form()
    {
        return Admin::form(Article::class, function (Form $form) {

            $form->display('id', 'ID');

            $form->text('title')->rules('required');
            $form->textarea('content')->rules('required');
            $form->image('picture');

            $form->display('created_at', 'Created At');
            $form->display('updated_at', 'Updated At');
        });
    }

    ...
}

Article.php in app/Models/

> <?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Spatie\EloquentSortable\Sortable;
use Spatie\EloquentSortable\SortableTrait;

class Article extends Model implements Sortable
{
    use SortableTrait;

    protected $table = 'demo_articles';

    public $sortable = [
        'order_column_name' => 'order',
        'sort_when_creating' => true,
    ];
}

**Comment by z-song** [comment]
Any exceptions?

**Comment by sweggggg** [comment]
exceptions means? what should i do?

**Comment by sweggggg** [comment]
![capture](https://cloud.githubusercontent.com/assets/26056229/23693922/ff612760-0411-11e7-908b-fe6371a362ea.PNG)

**Comment by z-song** [comment]
You need to define a route to point to this controller.

I suggest you go first to learn about laravel's routing definitions

**Comment by sweggggg** [comment]
can you post the solution just for this problem please?

**Comment by sweggggg** [comment]
So, i just a new line of codes in routes.php
![capture](https://cloud.githubusercontent.com/assets/26056229/23695008/1073200c-0418-11e7-926c-fdfd3dc14f24.PNG)

And a new error appear
![capture1](https://cloud.githubusercontent.com/assets/26056229/23695019/1b0bfa16-0418-11e7-9f9d-c240ab3f5ff1.PNG)

**Comment by zxy198717** [comment]
seems your controller in `App\Admin\Controllers\Demo;`
Try to change `ArticleController@index` to `Demo\ArticleController@index`

**Comment by sweggggg** [comment]
I have done what you suggested, now got another error
![capture](https://cloud.githubusercontent.com/assets/26056229/23696550/1a0ac21c-041f-11e7-8dec-0ff5d62bbb3f.PNG)

**Comment by zxy198717** [comment]
Please confirm whether has method `index` in class `ArticleController` and try to use this route:
```
$router->resource('articles', Demo\ArticleController::class);
```
refer this:
http://z-song.github.io/laravel-admin/#/en/quick-start.md

**Comment by sweggggg** [comment]
i think theres none, only grid() and form(), how do i do that?

![capture](https://cloud.githubusercontent.com/assets/26056229/23696798/2e48b350-0420-11e7-845a-53ae4c429828.PNG)

**Comment by zxy198717** [comment]
You can add the following code in `ArticleController ` to do test:
```
public function index()
    {
        return Admin::content(function (Content $content) {

            $content->header('header');
            $content->description('description');

            $content->body($this->grid());
        });
    }
```

If you want to use the full features. you'd better to generate your controller by `artisan`.
I suggest you to write one test case base on `document` step by step.
refer: http://z-song.github.io/laravel-admin/#/en/quick-start.md

**Comment by sweggggg** [comment]
Added the codes, now another error

![capture](https://cloud.githubusercontent.com/assets/26056229/23697226/ef7deeea-0421-11e7-815d-7ca10f303568.PNG)


![capture1](https://cloud.githubusercontent.com/assets/26056229/23697243/003154c0-0422-11e7-8847-ea5cf70d7a92.PNG)

**Comment by zxy198717** [comment]
Try:
```
composer require spatie/eloquent-sortable
```

**Comment by sweggggg** [comment]
Oh my, it works, thank you so much for the help.

Btw, how do i +rep you? Or theres no option for that haha
