### ISSUE TITLE
How to add condition on grid listing based on relationship model?

### ISSUE THREAD

**Issue by eine91** [z-song/laravel-admin#5331]
- Laravel Version: 8.8
- PHP Version: 7.4
- Laravel-admin: 1.8.6

### Description:
Hi, how can I add condition on grid listing based on relationhship?

Currently documented:

$grid->model()->orderBy('id', 'desc');

I want to order list based on relationship table column.

I tried below but not working:

$grid->model()->orderBy('relationship_table.id', 'desc');

**Comment by respectall** [comment]
You can try this way:

```
$grid->model()->join('relation_table as rt', 'rt.id', '=', 'model.rt_id')->orderBy('rt.column', 'desc')
```
