### ISSUE TITLE
Grid error: htmlspecialchars(): Argument #1 ($string) must be of type string, array given

### ISSUE THREAD

**Issue by mendizalea** [z-song/laravel-admin#5338]
- Laravel Version: 8.45.1
- PHP Version: PHP/8.0.6
- Laravel-admin: 1.8.12

I can't add one of the fields to the grid, the moment I add it, it gives me the following error:

```
ViewException In helpers.php line 118 :
  htmlspecialchars(): Argument #1 ($string) must be of type string, array given (View: /home/test/vendor/encore/laravel-admin/resources/views/grid/inline-edit/comm.blade.php)
  
```
I have 2 tables, one is the event table and I have several fields and one of them is 'season_id' and the relationship with the other table is like this:
```
public function season()
    {
        return $this->belongsTo(Season::class);
    }
```
	
And then in the seasons table I have the following relationship:
```
public function events()
    {
        return $this->hasMany(Event::class);
    }
```
	
I do not understand the reason why it is returning an array to me, the grid I have like this:
`$grid->season()->year(__('Season'))->sortable();`

Thank for all!

**Comment by taha-moghaddam** [comment]
> * Laravel Version: 8.45.1
> * PHP Version: PHP/8.0.6
> * Laravel-admin: 1.8.12
> 
> I can't add one of the fields to the grid, the moment I add it, it gives me the following error:
> 
> ```
> ViewException In helpers.php line 118 :
>   htmlspecialchars(): Argument #1 ($string) must be of type string, array given (View: /home/test/vendor/encore/laravel-admin/resources/views/grid/inline-edit/comm.blade.php)
>   
> ```
> 
> I have 2 tables, one is the event table and I have several fields and one of them is 'season_id' and the relationship with the other table is like this:
> 
> ```
> public function season()
>     {
>         return $this->belongsTo(Season::class);
>     }
> ```
> 
> And then in the seasons table I have the following relationship:
> 
> ```
> public function events()
>     {
>         return $this->hasMany(Event::class);
>     }
> ```
> 
> I do not understand the reason why it is returning an array to me, the grid I have like this: `$grid->season()->year(__('Season'))->sortable();`
> 
> Thank for all!

I have same issue
