### ISSUE TITLE
禁用掉“删除”后，批量删除里并没有禁用

### ISSUE THREAD

**Issue by fasthold** [z-song/laravel-admin#535]
如图：

![image](https://cloud.githubusercontent.com/assets/174880/23695485/60d66f52-041a-11e7-985f-a3f4f5f9030c.png)

**Comment by Haogood** [comment]
[https://github.com/z-song/laravel-admin/issues/437](url)

**Comment by jelsonsong** [comment]
disableBacthActions 才行
