### ISSUE TITLE
Custom editable inline

### ISSUE THREAD

**Issue by vuongutc** [z-song/laravel-admin#5354]
- Laravel Version: 8.0
- PHP 7.3:
- Laravel-admin: 1.8

### Description:
Hi bro, i have problem. i want to add paramater to editdable inline.
i need detect table in form method follow by request()->get('type'), how can i add param type to from method.

### Steps To Reproduce:
![2-issue](https://user-images.githubusercontent.com/59592052/123789122-0235a280-d907-11eb-9e19-0c6cda98b52b.png)
![1-issue](https://user-images.githubusercontent.com/59592052/123789126-0366cf80-d907-11eb-8a3a-2ed876e658d0.png)

**Comment by ShuiPingYang** [comment]
editdable inline releate to the method update,if you want to get params in form method ,you need to add it in the url

**Comment by vuongutc** [comment]
But i don't no to add params to url. i nedd something like this(the custom action method)
![Uploading 1-delete.png…]()
