### ISSUE TITLE
SwitchField 里的 on/off 应该是 $this->states['on']['value']/$this->states['off']['value']  ?

### ISSUE THREAD

**Issue by feistiny** [z-song/laravel-admin#5355]
https://github.com/z-song/laravel-admin/blob/2c4834cf2d3160b31714292eece6df58e78c177f/src/Form/Field/SwitchField.php#L72

**Comment by feistiny** [comment]
不然存到数据库的是 on/off, 应该是自定义的 value，现在开关是无法切换的

**Comment by felixwann** [comment]
你好，我最近也遇到了行内编辑switch不生效的问题，可能跟你说的这个有关[issue5369](https://github.com/z-song/laravel-admin/issues/5369#issue-954735536)
