### ISSUE TITLE
有关上传文件的问题

### ISSUE THREAD

**Issue by Elfantasmal** [z-song/laravel-admin#536]
我想加一个上传视屏的功能可是发现报了一个文件太大的错误，这个框架的上传没有用分片吗？不适用大文件上传吗，还是说我需要自己写一个lavaral自带的文件上传的功能。。。望大神解答

**Comment by zxy198717** [comment]
1. 文件太大需要修改php配置:post_max_size、upload_max_filesize、memory_limit。如果用nginx的话，还需要修改client_max_body_size。这是任何php程序都会遇到的问题。
2. 一般的服务器不适合直接上传大文件，大文件建议直接上传到云存储里。例如 七牛等，都有js的sdk。

**Comment by Elfantasmal** [comment]
谢谢大神的解答，但我觉得框架如果有分片上传就更好了，感谢

**Comment by z-song** [comment]
找一个支持分片上传的插件扩展一下试试看

**Comment by chenlixin93** [comment]
文件太大我都是选择第三方的上传了，比如像视频这种媒体资源
