### ISSUE TITLE
install无报错 访问 /admin  404

### ISSUE THREAD

**Issue by zxt3310** [z-song/laravel-admin#5365]
- Laravel Version: v8.41.0
- PHP Version: v7.4.19
- Laravel-admin: v1.8.10

### Description:
xxx.com:8080 可以访问laravel 
xxx.com:8080/admin  404
php artisan route:list  没发现 admin的路由
php artisan package:discover  之后 依然404

**Comment by 8108905** [comment]
检查下 是否下载完全？install  执行 artisan，不报错，说明不了什么

**Comment by zxt3310** [comment]
下载都全，没啥问题。  路由里没有admin是为何呢？  我用的nginx
