### ISSUE TITLE
Data From API 模块中返回 id 数值类型的问题

### ISSUE THREAD

**Issue by jxlwqq** [z-song/laravel-admin#537]
我们知道，这里 API 返回的数据中，必须要有 id 字段，如果没有则需要自己修改数组，将 id 这个字段添加进入。以微信接口为例，微信返回的数据中有 openid 或者 media_id 这些字段，但是这些字段的数据类型是字符串，如果我将字符串类型的 openid 赋值给 id 这个字段，会有问题，都会强制转换为数值类型。

`

        $wechat = new Application(config('wechat'));
        $list = $wechat->user->lists();
        $list = json_decode($list, true);
        $openid_list = $list['data']['openid']; // 微信最大为 10000
        $openid_list = array_slice($openid_list, $offset, $length);
        $data = $wechat->user->batchGet($openid_list);
        $data = json_decode($data, true);
        $user_info_list = $data['user_info_list'];
        foreach ($user_info_list as $key => &$val) {
            $val['id'] = $val['openid'];
        }
        $user_info_list = static::hydrate($user_info_list);
`

**Comment by z-song** [comment]
在模型中加入属性：
```php
protected $primaryKey = 'openid';

protected $keyType = 'string';
```
不用将openid 赋值给 id，也不用强转类型

**Comment by jxlwqq** [comment]
非常谢谢，已解决。
