### ISSUE TITLE
Password hash, ID is not showing

### ISSUE THREAD

**Issue by mantax559** [z-song/laravel-admin#5373]
- Laravel Version: 8.50.0
- PHP Version: 7.3.2
- Laravel-admin: 1.8.13

Hello,

1. When I enter a new password and press "Submit", in database, password column I see the text I entered instead of hashed password;
2. In country, confession, diocese, deanery and parish rows there should be ID's from other tables, but now these fields are empty. ![image](https://user-images.githubusercontent.com/45240543/128069362-975434ba-dc81-43b0-9fee-2aef59e2addf.png) and I can only see ID's in show page ![image](https://user-images.githubusercontent.com/45240543/128069869-35c35fb5-1bdb-4225-86b3-219c06067246.png)
3. How can I join data from 2 different tables in one and edit them?

**Comment by mRamadan0101** [comment]
>     1. When I enter a new password and press "Submit", in database, password column I see the text I entered instead of hashed password;
> 
in saving callback

```
        $form->saving(function (Form $form) {
            if ($form->password && $form->model()->password != $form->password) {
                $form->password = bcrypt($form->password);
            }
        });
```
>     2. In country, confession, diocese, deanery and parish rows there should be ID's from other tables, but now these fields are empty. !
> 
use select form type not number.
`
$form->select('country_id', 'Country')->options(Country::pluck('name', 'id'));
`
>     3. How can I join data from 2 different tables in one and edit them?

explain more please with more details

**Comment by jianhui99** [comment]
1. When I enter a new password and press "Submit", in database, password column I see the text I entered instead of hashed password;

Can try add  password in the protected $fillable in your models
