### ISSUE TITLE
Form\NestedForm 中使用 when 的情况

### ISSUE THREAD

**Issue by kwdassk** [z-song/laravel-admin#5375]
// 直接添加一对多的关联模型
        $form->hasMany('skus', 'SKU 列表', function (Form\NestedForm $form) {
            $form->text('title', 'SKU 名称')->rules('required');
            $form->text('description', 'SKU 描述')->rules('required');
            $form->text('price', '单价')->rules('required|numeric|min:0.01');
            $form->radio('activity_type', '活动类型')->options([0 => '无活动', 1 => '折扣固定金额', 2 => '多件整体打折'])->default(0)
            ->when(1, function ($form) {
                $form->text('activity_price', '活动价格')->rules('required|numeric|min:0.01');
            });
            $form->text('stock', '剩余库存')->rules('required|integer|min:0');
        });

想这样使用，当活动类型仅为1的时候活动价格必填，其他类型为null

**Comment by Godmail** [comment]
类似情况，hasMany下无法使用when

**Comment by mRamadan0101** [comment]
try this if i understand correctly 
```
        $form->saving(function (Form $form) {
            $validator = Validator::make(request()->all(), [
                'skus.*.activity_price' => 'required_if:'.$form->activity_type.',1',
            ]);
       });
```

**Comment by MarsTify** [comment]
可以曲线救国
`
        $form->saving(function (Form $form) {
            if ($sku = collect($form->input('skus'))->where('activity_type', 1)->first()) {
                $validator = Validator::make($sku, [
                    'activity_price' => 'required|numeric|min:0.01',
                ]);

                if ($validator->fails()) {
                    $error = new MessageBag([
                        'title'   => 'Error',
                        'message' => $validator->errors()->first('activity_price'),
                    ]);
                    
                    return back()->with(compact('error'));
                }
            }
        });
`
