### ISSUE TITLE
这是一个靠颜值和理想撑起的项目啊

### ISSUE THREAD

**Issue by vlongen** [z-song/laravel-admin#538]
刚刚试了试,耽误了一夜的时间,好在我最终没用项目里,文档写的太次了!

请告诉我, Tree 的保存回调呢?没有保存回调我怎么处理保存到数据库之后的逻辑和之前的逻辑呢?

**Comment by z-song** [comment]
既然不用了 就没必要告诉你了

ps 换了是我，一个工具不适合我，就去换一个，半句话都不会多说。

**Comment by vlongen** [comment]
非常抱歉话说过了啊

**Comment by edwinhuish** [comment]
支持 @z-song

**Comment by RobinVSRose** [comment]
支持@z-song
