### ISSUE TITLE
$form->table 二维数组编辑二维数组数据丢失

### ISSUE THREAD

**Issue by Feng-YunFei** [z-song/laravel-admin#5380]
- Laravel Version: 6.2
- PHP Version: 7.4
- Laravel-admin: 1.8.1

### Description:
$form->table二维数组编辑的时候，前端页面动态追加的元素会覆盖之前已存在元素的值，原因就是后面追加的input的name值是从new_1开始的，导致之前的new_1数据被覆盖，这个怎么解决呢
![laravel-admin](https://user-images.githubusercontent.com/15756940/129841082-e8838303-2c75-43d0-a0c5-fd5ad08a7dc4.png)

**Comment by imnpc** [comment]
https://github.com/z-song/laravel-admin/issues/4745#issuecomment-755184481

参见这条修复
