### ISSUE TITLE
如何重新构建删除

### ISSUE THREAD

**Issue by a478005966** [z-song/laravel-admin#5397]
- Laravel Version:8.4
- PHP Version:7.4
- Laravel-admin: 1.8.13

### Description:
我想在删除操作时，做其他逻辑，并不是真的要删除数据，该如何重新构建删除

**Comment by jxlwqq** [comment]
试试这个？
https://laravel-admin.org/docs/zh/1.x/model-grid-custom-actions

**Comment by a478005966** [comment]
> 试试这个？
> https://laravel-admin.org/docs/zh/1.x/model-grid-custom-actions

这个我也考虑过，不能像修改或者创建那样直接复写吗

**Comment by jxlwqq** [comment]
在 controller 里面，复写一下 destroy 方法

**Comment by jxlwqq** [comment]
在你的xxxController里，复写这个方法：
```php
 public function destroy($id)
    {
        // do what you want
        // return $this->form()->destroy($id);
    }
```
