### ISSUE TITLE
I want to disable delete button if user use globally assigned pat name

### ISSUE THREAD

**Issue by evoama** [z-song/laravel-admin#5398]
- Laravel Version: ^7.0
- PHP Version: 7.3
- Laravel-admin: 1.8.*

### Description:
I try to disable the delete for some rows which have pat name mekky.
But I'm unable to do it.
please help me for this.

### Steps To Reproduce:
```
$pat_name = 'mekky';
$grid->actions(function (Grid\Displayers\Actions $actions) use($pat_name) {
      $actions->disableView();
      $actions->disableDelete()->where('pat_name', $pat_name);
    });
```

**Comment by respectall** [comment]
Try this:

```
$pat_name = 'mekky';
$grid->actions(function (Grid\Displayers\Actions $actions) use ($pat_name) {
    if ($pat_name === $actions->row->pat_name) {
        $actions->disableDelete();
    }
    $actions->disableView();
})
```

**Comment by Rabinhoodwho** [comment]
> * Laravel Version: ^7.0
> * PHP Version: 7.3
> * Laravel-admin: 1.8.*
> 
> ### Description:
> I try to disable the delete for some rows which have pat name mekky.
> But I'm unable to do it.
> please help me for this.
> 
> ### Steps To Reproduce:
> ```
> $pat_name = 'mekky';
> $grid->actions(function (Grid\Displayers\Actions $actions) use($pat_name) {
>       $actions->disableView();
>       $actions->disableDelete()->where('pat_name', $pat_name);
>     });
> ```
