### ISSUE TITLE
更新版本后无法打开登录首页

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#54]
重新安装项目的情况下（laravel5.2）

**Comment by z-song** [comment]
@windpursuer 请问有什么报错信息吗？

**Comment by windpursuer** [comment]
无法找到网页。我排查了一下，应该不是项目的问题，是我本地环境的问题。phpstudy开启apache下是没问题的，但nginx下会报错，请问有解决方法吗？

**Comment by z-song** [comment]
检查一下nginx配置吧，看看路径是不是有问题，另外检查下php-fpm

**Comment by windpursuer** [comment]
好的，我再尝试一下，感谢回答！可以关闭这个issue了

**Comment by z-song** [comment]
谢谢反馈！
