### ISSUE TITLE
禁用批量操作后（$tools->disableBatchActions()），多选框还在

### ISSUE THREAD

**Issue by fasthold** [z-song/laravel-admin#540]
使用 `$tools->disableBatchActions();` 去掉批量操作，一般来说最左列的多选框就没用了

![image](https://cloud.githubusercontent.com/assets/174880/23734248/d19a6646-04b8-11e7-9298-e35608558ce4.png)

**Comment by z-song** [comment]
用`$grid->disableRowSelector();`来把多选框和批量删除一起去掉。

**Comment by fasthold** [comment]
搞定！ Thanks you!
