### ISSUE TITLE
关于从别的数据服务器取数据

### ISSUE THREAD

**Issue by hangxingfu** [z-song/laravel-admin#5400]
请教一个问题，
有好几个mysql服，表结构相同，数据不同，根据条件从全部服或者其中几个中查询数据，
protected function grid()
{
    $grid = new Grid(new User());

    $grid->column('id', __('Id'));
    $grid->column('name', __('Name'));
    $grid->column('email', __('Email'));
    $grid->column('password', __('Password'));
    $grid->column('created_at', __('Created at'));
    $grid->column('updated_at', __('Updated at'));

    return $grid;
}
这样展示是一个表的数据，我想在一个页面展示所有的查询数据

**Comment by keller31** [comment]
参考此文：
自己实现一个Model 并对数据进行聚合
https://laravel-admin.org/docs/zh/1.x/model-grid-data#%E6%95%B0%E6%8D%AE%E6%9D%A5%E8%87%AA%E5%A4%96%E9%83%A8API
