### ISSUE TITLE
WangEditor 内容出现在编辑器之外

### ISSUE THREAD

**Issue by faydanube** [z-song/laravel-admin#5405]
- Laravel Version: 8.58.0
- Laravel-admin: 1.8.14

### Steps To Reproduce:
1. 根据 <https://github.com/laravel-admin-extensions/wangEditor> 配置 1.x 版本
![image](https://user-images.githubusercontent.com/8817046/132207199-138cce19-769b-48d0-bd14-e1a178f02c83.png)

2. 进数据库对比发现，可能和 p 标签有关，不知道如何能够修复此问题，没有 p 标签的内容都会显示在编辑器之外。
![image](https://user-images.githubusercontent.com/8817046/132207501-841ae909-e9dd-494f-b088-6e0f771a531f.png)

![image](https://user-images.githubusercontent.com/8817046/132207540-103ec513-de7d-4894-8737-e9fd5c4bedcd.png)

@z-song

**Comment by angyangyang** [comment]
将内容转义，可用htmlspecialchars_decode()函数
