### ISSUE TITLE
Version 2 is abandoned?

### ISSUE THREAD

**Issue by igorhaf** [z-song/laravel-admin#5407]
- Laravel Version: 6 LTS and 9 LTS (future)
- PHP Version: 8
- Laravel-admin: 2

### Description:

is there still the intention to go with version 2.0 or has it been abandoned?
in case you intend to collaborate only with v2, testing possible bugs and implementing what has already been done in version 1

**Comment by mhenselin** [comment]
Hey folks,
I would recommend that starting with V2.0 we switch to semantic versioning :-)
Personally I ran into some interesting issues lately
