### ISSUE TITLE
1.4.*-dev 下　$filter->between('created_at') 空数据搜索异常

### ISSUE THREAD

**Issue by smartymoon** [z-song/laravel-admin#541]
![_20170309112506](https://cloud.githubusercontent.com/assets/12489528/23734644/57256c6e-04bb-11e7-820e-bdd2e82b903f.png)
![_20170309112518](https://cloud.githubusercontent.com/assets/12489528/23734645/597b58c0-04bb-11e7-8ba9-67aa264ae60c.png)

1.4.*-dev 填入时间搜索正常，若为空会报错．
１.3.*-dev下没有这个问题

**Comment by z-song** [comment]
我这边没有这个问题，你pull一下代码试试看

**Comment by smartymoon** [comment]
调试了好久，终于发现问题了．在laravel5.4下空input返回的是null，而在laravel5.3下空input返回的是＂＂，
Filter.php 可以过滤5.3的 "　" ,却不能过滤5.4的 null.
![_20170309152752](https://cloud.githubusercontent.com/assets/12489528/23740216/968005d2-04dd-11e7-850e-9a86d3121fe4.png)
![_20170309152921](https://cloud.githubusercontent.com/assets/12489528/23740222/99309b66-04dd-11e7-8d5c-a6d5a0a4206c.png)

**Comment by z-song** [comment]
我更新到Laravel 5.4.15 input的值是`""`，你的Laravel版本是多少？

**Comment by smartymoon** [comment]
也是5.4.15
![_20170309160044](https://cloud.githubusercontent.com/assets/12489528/23741064/9a7d06ae-04e1-11e7-91c9-fd84c9f0a24c.png)

**Comment by z-song** [comment]
原来是这样的，难怪怎么更新Laravel都没用，中间件是在`app/Http/Kernel.php`引入的
