### ISSUE TITLE
Form > Switch > values parameter is not working

### ISSUE THREAD

**Issue by skyhip0811** [z-song/laravel-admin#5412]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

The form field switch cannot custom the on/off value sent 

### Steps To Reproduce:

         $states = [
                'on'  => ['value' => 1, 'text' => 'enable', 'color' => 'success'],
                'off' => ['value' => 0, 'text' => 'disable', 'color' => 'danger'],
            ];
            
        $form->switch('approved', __('Approved'))->states($states);

The value sending in the switch field in the form is still string value on/off but not integer value 1/0

**Comment by carlospinhod** [comment]
@skyhip0811 
Laravel Version: 9.31.0
PHP Version: 8.1.8
Laravel-admin: 1.8.17

Hey, i'm running in the same problem, have you find a way to solve it? 
thanks anyway

**Comment by alexoleynik0** [comment]
@carlospinhod It actually does that, but not when/where you're expecting, I guess.
I believe you're trying to check the switch value somewhere in the `$form->saving` callback, and there it's still "on/off". 

For that I can only suggest you to save your $switchField and to call `$field->prepare($value)` from anywhere you need to get the $states["on/off"]["value"] itself. Like that: 

```php
$states = [
    'on'  => ['value' => 1, 'text' => 'enable', 'color' => 'success'],
    'off' => ['value' => 0, 'text' => 'disable', 'color' => 'danger'],
];
$switchField = $form->switch('approved', __('Approved'))->states($states);

$form->saving(function (Form $form) use ($switchField) {
    $approvedValue = $switchField->prepare($form->input('approved')); // this is now `1 / 0`
});
```
