### ISSUE TITLE
Unable to update or change La profile picture for admin

### ISSUE THREAD

**Issue by anishre** [z-song/laravel-admin#5428]
- Laravel Version: 8.61.0
- PHP Version: 8.0.9
- Laravel-admin: 1.8.14

### Description:
Attempting to change admin profile picture on the laravel admin panel leaves a blank canvas. Tried with multiple images of varying resolutions, original image included.

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/39543074/135160698-c5e28145-41d7-4e5b-88d7-f30072691bbd.png)

**Comment by lotustea** [comment]
I have the same problem here!

**Comment by oneWaveAdrian** [comment]
Happens to me as well when `HTTPS` is used.
I noticed that LaravelAdmin somehow changes the saved image location to `httpis://...` the `i` is what breaks it imho.
Can't find the right location in code to fix it though...
