### ISSUE TITLE
I want to store multiple images in images column in a product table -> Array to string conversion

### ISSUE THREAD

**Issue by zeynepkadi** [z-song/laravel-admin#5434]
- Laravel Version: 6
- PHP Version:
- Laravel-admin: #.#.#

### Steps To Reproduce:
ProductController Form():
$form->multipleImage('image', __('ımage'))->removable()->rules('mimes:png,jpeg,jpg');

Product Model:
public function setPicturesAttribute($pictures)
    {
        if (is_array($pictures)) {
            $this->attributes['image'] = json_encode($pictures);
        }
    }

    public function getPicturesAttribute($pictures)
    {
        return json_decode($pictures, true);
    }

the error i got
Array to string conversion

**Comment by Alex4Shch** [comment]
in model:
```
protected $casts = [
        'image' => AsArrayObject::class,
 ];
```
https://docs.rularavel.com/docs/8.x/eloquent-mutators#array-object-and-collection-casting

**Comment by mRamadan0101** [comment]
```
    public function setImagesAttribute($images)
    {
        if (is_array($images)) {
            $this->attributes['images'] = json_encode($images);
        }
    }

    public function getImagesAttribute($images)
    {
        if (null != $images) {
            return json_decode($images, true);
        } else {
            return json_decode('[]', true);
        }
    }
```
