### ISSUE TITLE
sortable排序不好用

### ISSUE THREAD

**Issue by jackqth** [z-song/laravel-admin#544]
![image](https://cloud.githubusercontent.com/assets/16730906/23747572/292c0db4-04fb-11e7-8ff0-9347357b8665.png)
纯数字排序不好使，感觉有点不对

**Comment by z-song** [comment]
如果这个字段类型为varchar的话，改成int试试看

**Comment by yangtongbing** [comment]
我用本表字段进行排序的时候发现502了，因为线上的原因，不能打开报错，我本地的是没有问题，该怎么找问题？

**Comment by z-song** [comment]
线上报错没有log吗？
