### ISSUE TITLE
These credentials do not match our records.

### ISSUE THREAD

**Issue by anishre** [z-song/laravel-admin#5445]
Laravel v8.61.0 
PHP v8.0.9
Laravel-admin: 1.8.14

### Description:
Getting error  - These credentials do not match our records after Laravel admin installation. Using default credentials.

### Steps To Reproduce:
Follow instructions and install laravel admin. Log in with default credentials

@z-song

**Comment by mRamadan0101** [comment]
try 
`php artisan admin:install `
and make sure database seed in your database
