### ISSUE TITLE
Model求帮助

### ISSUE THREAD

**Issue by sheldon5** [z-song/laravel-admin#545]
创建了Model之后，关联到了Controller上，执行了之后出现问题 ModelNotFoundException In Builder.php line 324 :
No query results for model [App\Models\Game] index，
App\Models\Game.php的代码这样：
```php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Game extends Model
{
    //
    protected $table = 'games';
}
```

请问您那边可以公开使用的demo网站源码吗？

**Comment by edwinhuish** [comment]
出现这个错误是没有找到对应数据库的值。

**Comment by xinhaonaner** [comment]
加上这个
**
public function update($id)
{
      return $this->form($id)->update($id);
 }
**
