### ISSUE TITLE
多选表单联动异常

### ISSUE THREAD

**Issue by latrell** [z-song/laravel-admin#5464]
- Laravel Version: 8.69.0
- PHP Version: 8.0.11
- Laravel-admin: 1.8.16

### Description:
在多选组件中使用表单联动，出现 `addslashes(): Argument #1 ($string) must be of type string, array given` 异常。

### Steps To Reproduce:
```
$form->multipleSelect('test', 'Test')
        ->options(['aaa' => 1, 'bbb' => 2])
        ->when('has', 1, function (Form $form) {
        });
```

**Comment by DamichiXL** [comment]
Same with checkboxCard
