### ISSUE TITLE
Duplicate entries when saving $form->table

### ISSUE THREAD

**Issue by oligirling** [z-song/laravel-admin#5468]
- Laravel Version: 7.30.4
- PHP Version: 7.4.22
- Laravel-admin: v1.8.11

### Description:
I have a table of comments that are editable. However, when I click`submit` it saves a duplicate amount of entries. There are no modifications on the submit button.

<img width="1038" alt="Screenshot 2021-11-12 at 16 42 59" src="https://user-images.githubusercontent.com/42932986/141502984-71eee4f5-6ffe-4dd5-a629-6b7db1d552ee.png">

### Steps To Reproduce:

```
$form = new Form(new User());
$form->column(12, function (Form $form) {
    $form->divider();
    $form->html('<h3 style="text-align: center">Comments</h3>');

    $form->table('comments', '', function(Form\NestedForm $form) {
        $form->datetime('created_at');
        $form->text('author');
        $form->text('type');
        $form->text('comment');
     })->setWidth(12, 0);
});
```

Worth noting comments is a relationship of User:
```
    public function comments()
    {
        return $this->hasMany(Comments::class);
    }
```

**Comment by mRamadan0101** [comment]
are you try 
`$form = new Form(new User());
$form->column(12, function (Form $form) {
    $form->divider();
    $form->html('<h3 style="text-align: center">Comments</h3>');

    $form->hasMany('comments', '', function(Form\NestedForm $form) {
        $form->datetime('created_at');
        $form->text('author');
        $form->text('type');
        $form->text('comment');
     })->setWidth(12, 0);
});`
