### ISSUE TITLE
关于权限管理问题

### ISSUE THREAD

**Issue by acclea** [z-song/laravel-admin#5477]
目前权限管理，只有两种方式，要不是具体的路由，要不是带 *

但是现在这个有个缺陷，情况如下：
案例一：A 用户只给查看 ID 为 1000-5000 的数据，B 用户需要查看 ID 为 6000-8000 的数据
案列二：A用户可以查看全部的数据，但是不可以进入到编辑页面
在这样的情况下，该系统目前无法实现

建议：可以把目前管理路由的文本框，修改为 【键值对象】
第一个值用来 设置【是否为正则】，第二个值填写路由的内容

**Comment by wengheng** [comment]
目前权限验证路由是用的laravel辅助方法Str::is();来判断的,如果你想要改,建议你自己改个RBAC,作者大概率不会因少数人需求去改这个的.

**Comment by keller31** [comment]
这种属于特殊的业务数据权限需求，自己在业务代码中也是很容易实现的，框架层面基本上不会考虑这些的。
