### ISSUE TITLE
Please correct website instruction to create new controller using `admin:controller` command

### ISSUE THREAD

**Issue by taha-moghaddam** [z-song/laravel-admin#5484]
At this [link](https://laravel-admin.org/docs/en/quick-start#Add%20controller) command to create new controller is incorrect.
This `php artisan admin:controller --model=App\User`
Should be `php artisan admin:controller App\User`

**Comment by Tamaditi** [comment]
php artisan admin:make UserController --model=App\Models\User

**Comment by axsweet** [comment]
may need extra slash linux someone once said 3 in windows

php artisan admin:make Website\\Balls --model=App\\Models\\Website\\Balls
