### ISSUE TITLE
flatpickr的CDN失效了

### ISSUE THREAD

**Issue by wannabing** [z-song/laravel-admin#5505]
- Laravel Version: 8
- PHP Version:7.3
- Laravel-admin: 1.8.14

### Description:
DateMultiple组件的代码里引入了外部资源，在cdn失效的时候影响到了本地项目运行。
`
        'https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css',
        'https://cdn.jsdelivr.net/npm/shortcut-buttons-flatpickr@0.3.0/dist/themes/light.min.css',
        'https://cdn.jsdelivr.net/npm/flatpickr',
        'https://cdn.jsdelivr.net/npm/shortcut-buttons-flatpickr@0.1.0/dist/shortcut-buttons-flatpickr.min.js',
        'https://npmcdn.com/flatpickr@4.6.6/dist/l10n/zh.js',
`

**Comment by fasthold** [comment]
确实是，需要将 flatpickr 的js和css文件弄到本地啊

**Comment by junsonw** [comment]
如果把他们一定本地 不改composer的情况下

**Comment by terranc** [comment]
重写DateMultiple 
```php
// bootstop.php
Encore\Admin\Form::extend('DateMultiple', Custom/DateMultiple::class);
```
AND:
```php
// Custom/DateMultiple.php
namespace Custom;

class DateMultiple extends \Encore\Admin\Form\Field\DateMultiple
{
    protected static $css = [
        'https://unpkg.com/flatpickr@4.6.13/dist/flatpickr.min.css',
        'https://unpkg.com/shortcut-buttons-flatpickr@0.3.0/dist/themes/light.min.css',

    ];

    protected static $js = [
        'https://unpkg.com/flatpickr',
        'https://unpkg.com/shortcut-buttons-flatpickr@0.1.0/dist/shortcut-buttons-flatpickr.min.js',
        'https://unpkg.com/flatpickr@4.6.6/dist/l10n/zh.js',
    ];
}
```

**Comment by whycomeing** [comment]
添加了代码还是请求“https://cdn.jsdelivr.net”的资源啊

**Comment by whycomeing** [comment]
添加了代码还是请求“https://cdn.jsdelivr.net”的资源啊

**Comment by whycomeing** [comment]
如果压缩了js和css文件的，记得“php artisan admin:minify --clear”清除后再“php artisan admin:minify”重新压缩

**Comment by jxlwqq** [comment]
fixed.

**Comment by jxlwqq** [comment]
fixed.
