### ISSUE TITLE
admin/_handle_action_  seems to bypass the permissions

### ISSUE THREAD

**Issue by atlasan** [z-song/laravel-admin#5509]
- Laravel Version: 5.7.29
- PHP Version:
- Laravel-admin: 1.18.14

### Description:
admin/_handle_action_  seems bypassing the permissions
Having a fresh scaffolded Controller with view and grid, a profile with only GET permission, all actions were blocked except GET, but clicking on delete produced the unexpected result

**Comment by shahruslan** [comment]
I have the same problem. There is no way to check the permissions for the Delete action.

**Comment by atlasan** [comment]
It should be checked the Delete permisision inside the handle_action for the current user for the entity in use. I took a quick look and it seems to me that some checks are made, but not the same used for the "common" permission.
I'm new to laravel_admin, sorry I'm saying something wrong.

**Comment by atlasan** [comment]
The code comment says: // 下面的路由不验证登陆
Translated: The following route does not verify the login
