### ISSUE TITLE
What to set to increase number of rows in the grid?

### ISSUE THREAD

**Issue by herol-gl** [z-song/laravel-admin#5511]
Let say I want to show 100k of rows per page. What do I need to set in Laravel config file or php.ini etc? Or to change the server spec?

**Comment by agusputra** [comment]
How if you try this:

```
        $grid->paginate(100);
        $grid->perPages([100, 200, 300]);
```

**Comment by herol-gl** [comment]
I try but it takes forever to load so I wonder what setting should I set in Laravel or the server (ubuntu nginx) or database to make it possible to show lots of data.

$grid->perPages([5000, 10000, 50000]);
