### ISSUE TITLE
How can I display Customer model data into Booking model Grid

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#5531]
- Laravel Version: 5.8.38
- PHP Version: PHP/7.3.28
- Laravel-admin: 1.8.14

### Description:
I have something like this Customer hasMany Booking.
![image](https://user-images.githubusercontent.com/7189244/156493172-d93a1370-f1ae-4b77-aa32-996058e88cf9.png)
and
![image](https://user-images.githubusercontent.com/7189244/156493201-5f4cd264-64f3-450b-9efe-d20584382a46.png)

Now, I want to display Bookings on a grid and I want to display all Customers info. 
![image](https://user-images.githubusercontent.com/7189244/156493239-b1f161f9-6514-4dd8-9e73-b8c598fe5957.png)

### Steps To Reproduce:
So, below is my code in BookingController Grid

```
        $grid = new Grid(new Booking());
        $grid->column('booking_event_id', 'Booking ID');
        $grid->column('customer_id', __('Customer Name'))->display(function () {
            $customer = Customer::find($this->customer_id);
            return $customer->name;
        });

        $grid->column('phone', __('Phone'))->display(function () {
            $customer = Customer::find($this->customer_id);
            return $customer->phone;
        });
```
So problem is, I don't want a repetition of using ```Customer::find()``` again and again for each column data
Are there any other more efficient solutions?

**Comment by dev** [comment]
```php
$grid->column('customer.name', __('Customer Name'));
$grid->column('customer.phone', __('Phone'));
```

**Comment by amun1303** [comment]
> ```
> $grid->column('customer.name', __('Customer Name'));
> $grid->column('customer.phone', __('Phone'));
> ```
> 
> [Documentation](https://laravel-admin.org/docs/en/model-grid)

![image](https://user-images.githubusercontent.com/7189244/156537576-2de0535e-3dca-473a-975a-c31413dee729.png)

**Comment by dev** [comment]
> > ```
> > $grid->column('customer.name', __('Customer Name'));
> > $grid->column('customer.phone', __('Phone'));
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > [Documentation](https://laravel-admin.org/docs/en/model-grid)
> 
> ![image](https://user-images.githubusercontent.com/7189244/156537576-2de0535e-3dca-473a-975a-c31413dee729.png)

You'll need to have a customer relationship in your Booking model. The error message is pretty clear here:
```php
public function customer() 
{
    return $this->belongsTo(Customer::class);
}
```

**Comment by amun1303** [comment]
> > > ```
> > > $grid->column('customer.name', __('Customer Name'));
> > > $grid->column('customer.phone', __('Phone'));
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > [Documentation](https://laravel-admin.org/docs/en/model-grid)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/7189244/156537576-2de0535e-3dca-473a-975a-c31413dee729.png)
> 
> You'll need to have a customer relationship in your Booking model. The error message is pretty clear here:
> 
> ```
> public function customer() 
> {
>     return $this->belongsTo(Customer::class);
> }
> ```
> 
> [Laravel Docs](https://laravel.com/docs/9.x/eloquent-relationships#one-to-many-inverse)

Great! It's work. That's simple solution. Thanks @dev  so much
