### ISSUE TITLE
Why isn't there a separate Models folder for admin?

### ISSUE THREAD

**Issue by hoangnamitc** [z-song/laravel-admin#5581]
Hi,

I'm familiar with Laravel-admin, I see there is a Controller section inside the Admin folder which is separate from the original Laravel Controller, but about Models, it doesn't do that, but uses the same Laravel root.
So why not separate both processes for "Admin" vs "Site"

Thanks !

**Comment by sinmusystems** [comment]
there is not need for the model layer separation as far as auth/admin controller is concerned.  However I do suggest Laravel-Admin to cite example for using SelectRAW from model class for custom query in their documentation
