### ISSUE TITLE
静态资源被屏蔽了

### ISSUE THREAD

**Issue by xieruidong521** [z-song/laravel-admin#5593]
- Laravel Version: 8
- PHP Version:7.4
- Laravel-admin: 1.8.17

### Description:
静态资源被屏蔽了

### Steps To Reproduce:
![image](https://user-images.githubusercontent.com/28883857/169652393-309e7893-8af4-49c6-99b6-dd4b0bd54da0.png)
![image](https://user-images.githubusercontent.com/28883857/169652413-b0896413-31c0-4e0d-b0db-763a53890cc4.png)
![image](https://user-images.githubusercontent.com/28883857/169652432-f648ab33-fe30-49c9-84f4-3b34eb6e07a7.png)
![image](https://user-images.githubusercontent.com/28883857/169652438-757c237c-c718-45a4-84fe-921a66e1f914.png)

**Comment by jxlwqq** [comment]
fixed.
