### ISSUE TITLE
Flatpickr is not available

### ISSUE THREAD

**Issue by kkkreset** [z-song/laravel-admin#5599]
- Laravel Version: 9.0
- PHP Version:8.0
- Laravel-admin: 1.8

### Description:
vendor/encore/laravel-admin/src/Form/Field/DateMultiple.php
The javascipt and css library cannot be used.

CSS replace:
https://cdn.jsdelivr.net/npm/flatpickr/dist/flatpickr.min.css
https://cdn.jsdelivr.net/npm/shortcut-buttons-flatpickr@0.3.0/dist/themes/light.min.css
TO:
https://unpkg.com/flatpickr@4.6.13/dist/flatpickr.min.css
https://unpkg.com/shortcut-buttons-flatpickr@0.3.0/dist/themes/light.min.css

JS replace:
https://cdn.jsdelivr.net/npm/flatpickr
https://cdn.jsdelivr.net/npm/shortcut-buttons-flatpickr@0.1.0/dist/shortcut-buttons-flatpickr.min.js
TO:
https://unpkg.com/flatpickr@4.6.13/dist/flatpickr.js
https://unpkg.com/shortcut-buttons-flatpickr@0.1.0/dist/shortcut-buttons-flatpickr.min.js
https://npmcdn.com/flatpickr@4.6.6/dist/l10n/zh.js

**Comment by jxlwqq** [comment]
please try this version: [v1.8.19](https://github.com/z-song/laravel-admin/releases/tag/v1.8.19)

**Comment by kkkreset** [comment]
> 请试试这个版本：[v1.8.19](https://github.com/z-song/laravel-admin/releases/tag/v1.8.19)

get ，Thx

**Comment by terranc** [comment]
有的地方unpkg.com一样的被和谐了
