### ISSUE TITLE
menu错误

### ISSUE THREAD

**Issue by jackqth** [z-song/laravel-admin#56]
![image](https://cloud.githubusercontent.com/assets/16730906/19432856/ea02f54c-9490-11e6-964b-f74b49c52a2f.png)
没有发现有menu的文件？我的是1.3版本。

**Comment by z-song** [comment]
现在的menu管理在后台界面上操作
![qq20161017-0](https://cloud.githubusercontent.com/assets/1479100/19433786/ba8c1060-9494-11e6-8923-fe19ef8f34b3.png)
