### ISSUE TITLE
form组件中password加密

### ISSUE THREAD

**Issue by vampirebitter** [z-song/laravel-admin#560]
看了很久手册，只看到`$form->password()`来定义password文本框，但是提交之后并不是bcrypt()加密，请问应该怎么实现加密？

**Comment by vampirebitter** [comment]
**抱歉**，没看到saving这个方法，感谢贡献

**Comment by akazhuk** [comment]
@vampirebitter 大兄弟，form表单里password如何使用bcrypt()加密方法？
