### ISSUE TITLE
如何在grid里面传递参数使得index只显示特定的records

### ISSUE THREAD

**Issue by yatong2008** [z-song/laravel-admin#561]
如题比如我有id为1,2,3的三篇blog，每一篇中有若干comments，我想在CommentController中的传递一个blog_id，使得/admin/comments/[blog_id] 这样的话只显示外键是blog_id的comment records，请问如何操作？

**Comment by yang5664** [comment]
這樣如何
```
$grid->model()->whereIn('blog_id', [1,2,3]);
```

**Comment by z-song** [comment]
你应该定义一个comments的resource路由
```php
$router->resource('blogs/{id}/comments', PostCommentController::class);
```

**Comment by yatong2008** [comment]
@yang5664 谢谢您的回复，尝试了你的这个call没有filter出来需要的comments。

@z-song 也谢谢您的tip
我使用了这一段'blogs/{id}/comments' 但是在grid之中还是显示了所有的comments

    protected function grid()
    {
        return Admin::grid(Comment::class, function (Grid $grid) {
            $grid->id('ID')->sortable();
            $grid->text('comment_text');
            $grid->created_at();
            $grid->updated_at();
        });
    }
请问这里该如何使用传递进去{id} ？

**Comment by yatong2008** [comment]
@yang5664 之前是写错了array，其实是有效的，谢谢您的提示。
不过我还是没有成功传入{id}来实现通过url来过滤

**Comment by z-song** [comment]
```php
public function index($Id)
{
    ...
    $this->grid($id);
    ...
}

protected function grid($id)
{

}
```
这样不就传进去了吗

**Comment by yang5664** [comment]
假如你要透過URL 傳遞如
![screen shot 2017-03-13 at 10 43 32 pm](https://cloud.githubusercontent.com/assets/5953010/23859463/a63df4b6-083e-11e7-8835-a9e635f4a210.png)
這樣也不錯
```
$grid->model()->where(['id'=>request()->get('id')])
```
