### ISSUE TITLE
How to add criteria to Selectable

### ISSUE THREAD

**Issue by technilogics** [z-song/laravel-admin#5624]
- Laravel Version: 9
- PHP Version: 8
- Laravel-admin: 1.8

### Description:
I used selectable to allow users selection, but  some users status is inactive, how i can show only Active user in selectable.

`namespace App\Admin\Selectable;

use App\Models\User;
use App\Models\UserType;
use Encore\Admin\Grid\Filter;
use Encore\Admin\Grid\Selectable;

class Users extends Selectable
{
    public $model = User::class;

    public function make()
    {
        $this->column('id');
        $this->column('name');
        $this->column('user_type_id','User Type')->display(function($id) {
        return ($id ? UserType::find($id)->title_en : null);
        });
        $this->column('email');
        $this->column('avatar','Avatar')->image();
        $this->column('created_at');

        $this->filter(function (Filter $filter) {
            $filter->like('name');
          $filter->equal('user_type_id')->select(UserType::where('status',1)->pluck('title_en', 'id'));
        });
    }
}
`
i tried as changing

`public $model = User::class;`

to 

`public $model = User::where('status',1);`

but it failed, as in grid/selectable

protected function initGrid() method

`$model = new $this->model();
$this->grid = new Grid(new $model());`

is conflicting with my change.

Any help is appreciated, without changing core admin files.

**Comment by k0hel** [comment]
idk your table, idk I'm right.
If it's the same usage as the grid, this should work.
`$this->model()->where('status', 1);`

**Comment by technilogics** [comment]
Thanks, this works in make() method
$this->model()->where('status', 1);
