### ISSUE TITLE
Bug: 修改时，如果改为空，则无效

### ISSUE THREAD

**Issue by fasthold** [z-song/laravel-admin#563]
编辑时，如果原来有值，改为空，则并没有生效，还是保留着先前的值

**Comment by z-song** [comment]
这是在Laravel 5.4.15加入了新的middleware引起的问题，参考https://github.com/z-song/laravel-admin/issues/541#issuecomment-285281562

你可以先暂时去掉这个middleware解决下问题

**Comment by z-song** [comment]
这个问题已经在dev版本里面修复 thx
