### ISSUE TITLE
Issues with Adblock extension

### ISSUE THREAD

**Issue by hoangnamitc** [z-song/laravel-admin#5630]
- Laravel Version: 8.x
- PHP Version: 7.4
- Laravel-admin: v1.8

### Description:
Use browser has install extension Adblock Plus when delete action, edit action not working.
But disable extension Adblock Plus is working !

**Comment by Heinirich** [comment]
Also faced the issue and didnt quite understand why

**Comment by kuchienkz** [comment]
I used Ublock Origin (kind of adblocker), never have this issue, perhaps it's the extension itself.
