### ISSUE TITLE
列表页面未显示导出按钮

### ISSUE THREAD

**Issue by zys60233** [z-song/laravel-admin#5632]
- Laravel Version: 5.6
- PHP Version: 7.4.30
- Laravel-admin: 1.8.17

### Description:
![image](https://user-images.githubusercontent.com/25996631/182841166-b75372ec-9851-4276-a9d8-08b22db0355a.png)

按照这种方式配置完成，列表页不显示导出按钮

**Comment by Xuan-Goldenf** [comment]
```
        //
        $grid->disableExport(false);
        $grid->exporter(new UserExporter());
```

**Comment by zys60233** [comment]
> ```
>         //
>         $grid->disableExport(false);
>         $grid->exporter(new UserExporter());
> ```

这不在文档中注明，有点难发现啊
