### ISSUE TITLE
how to rename the grid filter id 

### ISSUE THREAD

**Issue by Sivan4562** [z-song/laravel-admin#5638]
- Laravel Version: 5.6.39
- PHP Version: 73
- Laravel-admin: 1.6

### Description:
I want to rename the grid filter id name eg: the default name show ID but I want to rename it to Driver Id. it is possible in laravel admin??

**Comment by Xuan-Goldenf** [comment]
```
        $grid->filter(function($filter){
            $filter->disableIdFilter();
            ....
           // create new one.
```

**Comment by Sivan4562** [comment]
I can use the  **$filter->disableIdFilter();** function and add the new one like **$filter->like('id','Sum ID');** but it does not show in the filter box but i remove the **disableIdFilter()** it can show two fields for id and SumID. what can do for this scenario??

**Comment by Xuan-Goldenf** [comment]
<img width="763" alt="image" src="https://user-images.githubusercontent.com/40749214/187614695-b0a6146e-aa0e-4494-8a47-10648055b777.png">

**Comment by Sivan4562** [comment]
Thanks @Xuan-Goldenf  Now it working fine.
