### ISSUE TITLE
Is this dead project

### ISSUE THREAD

**Issue by mcfaith9** [z-song/laravel-admin#5674]

**Comment by LouisGac** [comment]
I'm currently hesitating between BackPack and laravel admin. So I'd be interested too on the status of the project

**Comment by mcfaith9** [comment]
> I'm currently hesitating between BackPack and laravel admin. So I'd be interested too on the status of the project

me too, but I am still interested on this project. I hope this will be updated as I prefer this Laravel Admin over BackPack or Voyager

**Comment by mcfaith9** [comment]
_I don't think this is already in a road map, I was eager to update and maintain it._
