### ISSUE TITLE
Cannot export to pdf with rowaction

### ISSUE THREAD

**Issue by RikiSptraaa** [z-song/laravel-admin#5694]
- Laravel Version: 9.19
- PHP Version:
- Laravel-admin: 1.8.9

### Description:
Custom RowAction return a corupt file pdf with dompdf while clicked. is there any solution?

![image](https://user-images.githubusercontent.com/80390490/205655486-6f7ce7d9-4ac0-4f59-a65a-55e8dab5392a.png)

**Comment by RikiSptraaa** [comment]
i still cannot solve it with download() method
 
`   public function print($id)
    {

        $borongan = GroupOrder::find($id);
        $carbon = new Carbon();
        $pdf = pdf::loadHTML(view('pdf.borongan', compact('borongan', 'carbon')));
        $pdf->render();
        return $pdf->download('invoice.pdf', array("Attachment" => 0));
    }`

`class Cetak extends RowAction

{
    public $name = 'Cetak';

    public function href()
    {
        return '/borongan/cetak/' . $this->row->getKey();
    }


}
`

the code still return the corupted files except i refresh the browser

**Comment by alexoleynik0** [comment]
RowAction `href` method isn't good for that as previously mentioned. Try `render` with something like:
```php
public function render() {
    return "<a href=$linkToPdf target=_blank>Get PDF</a>";
}
```
This will prevent **pjax** from loading your pdf into page's container, what causes your issue.

Or (sometimes) even better: 
```php
public function handle($model) {
    return $this->response()->open($model->getLinkToPdf());
}
```
The last will suit for some relation-greedy links that you don't need in your display Grid initially.
