### ISSUE TITLE
请教行内编辑如何展示确认框？

### ISSUE THREAD

**Issue by liunian-zy** [z-song/laravel-admin#5695]
rt，想在switch点击后弹出确认框，不知该如何配置。

**Comment by alexoleynik0** [comment]
Where exactly is that switch you want to add confirmation pop-up to? Form? Grid? Custom layout?

Anyway, I feel like the closest way to achieve this will be to use JS somewhere neer it. 

LA uses bootstrap-switch, and it natively doesn't support [this](https://github.com/Bttstrp/bootstrap-switch/issues/340) I'm afraid.
