### ISSUE TITLE
How to display pivot table's field ?

### ISSUE THREAD

**Issue by r-shaygan** [z-song/laravel-admin#5727]
there is a many-to-many relationship between coverage and proposal model.

on the proposal model , i have : 

```
public function coverages()
    {
        return $this->belongsToMany(InsuranceCoverage::class,'health_coverage_proposal',
            'proposal_id','coverage_id')->withPivot('cost');
    }

```

i want to access 'cost' column on ProposalController:

```
protected function detail($id)
    {
        $show = new Show(HealthProposal::findOrFail($id));

        $show->coverages(__('Insurance coverages'), function ($coverages) {
            $coverages->resource('/'.config('admin.route.prefix').'/insurances/coverages');
            $coverages->id();
            $coverages->title(__('Insurance coverages title'));
            $coverages->cost();// it doesnt work

        });
}
```

**Comment by alexoleynik0** [comment]
Have you tried something like `$coverages->column('pivot.cost');` ?

**Comment by r-shaygan** [comment]
> Have you tried something like `$coverages->column('pivot.cost');` ?

it returns this error: Call to undefined relationship [pivot] on model [Modules\Insurance\Entities\InsuranceCoverage]

**Comment by alexoleynik0** [comment]
Hmm.. can't test right now. Does your model's relationship has `->withPivot
('cost')` ?

**Comment by r-shaygan** [comment]
> Hmm.. can't test right now. Does your model's relationship has `->withPivot ('cost')` ?

yes..


```
public function coverages()
    {
        return $this->belongsToMany(InsuranceCoverage::class,'health_coverage_proposal',
            'proposal_id','coverage_id')->withPivot('cost');
    }

```

and i don't know how to insert this pivot field either

**Comment by alexoleynik0** [comment]
You're right, sorry, confused relation columns with nested ones. Grid treats column names as relations if there's a dot between names like in `pivot.cost`, but pivot is not a relation - hence an error. 
You should treat it like JSON field / array / object on the Grid's model. 
`$coverages->column('pivot->cost');` -- your way to go.

**Comment by r-shaygan** [comment]
> You're right, sorry, confused relation columns with nested ones. Grid treats column names as relations if there's a dot between names like in `pivot.cost`, but pivot is not a relation - hence an error. You should treat it like JSON field / array / object on the Grid's model. `$coverages->column('pivot->cost');` -- your way to go.

it worked.. thank you..
can you help me, with how to get pivot value from a form?

`$form->multipleSelect('roles','Role')->options(Role::all()->pluck('name','id'));`

in the code above we can just get the related model value.. what if it has pivot field?
