### ISSUE TITLE
Is there any way to customize the Encore\Admin\Show element's actions?

### ISSUE THREAD

**Issue by r-shaygan** [z-song/laravel-admin#5730]
how to change the 'list', 'edit', and 'delete' URL in the Encore\Admin\Show  element?
I know by setResource method, can set resource but I need to link them separately

**Comment by alexoleynik0** [comment]
Yes, you can -- [it's called panel there](https://laravel-admin.org/docs/en/model-show#Panel%20tool%20settings). 
So disabling defaults and adding your own should do the trick.

You can also use this in `app/Admin/bootstrap.php` to modify all Show views/panels. 
```php
Show::init(function (Show $show) {
    $show->panel()->tools(function (Show\Tools $tools) {
        $tools->append('<a href="#" class="btn btn-sm btn-default">Some button</a>');
    });
});
```
