### ISSUE TITLE
Form Validation double value verification

### ISSUE THREAD

**Issue by carlospinhod** [z-song/laravel-admin#5733]
- Laravel Version: 9.31.0
- PHP Version: 8.1.8
- Laravel-admin: 1.8.17

### Description:

Hi, i need to validate if a value is unique but i have to filter the "unique search" with other field for example:
if the username is unique for this club_id.
hope you can help me!
ps: the ideia is to validate before submiting, and the club id is a variable i get from php

### Steps To Reproduce:
table example: (user_id, username, club_id)

$form->text('username')->updateRules(['required', "unique:user_table,username,{{id}}"]);

**Comment by alexoleynik0** [comment]
This should help - [link to SO](https://stackoverflow.com/a/19377725). 

Basically `'unique:user_table,username,NULL,id,clud_id,' . $form->model()->club_id` or something similar. 

Or use more verbose OOP-based approach as described in this section of [Laravel docs](https://laravel.com/docs/10.x/validation#rule-unique) (last example).

`'username' => [Rule::unique('user_table')->where(fn (Builder $query) => $query->where('club_id', $club_id))]`

**Comment by carlospinhod** [comment]
@alexoleynik0 thank you for your hints, i have solved my problem using something like this

$form->number('id','ID')->rules(['required' => Rule::unique('user_table')->where(fn(Builder $query) => $query->where('id', '!=', $form->model()->id)->where('club_id', $club_id))])->required();
