### ISSUE TITLE
Add new custom css skin to adminLTE

### ISSUE THREAD

**Issue by gomes2191** [z-song/laravel-admin#5742]
- Laravel Version: 10
- PHP Version: 7.4
- Laravel-admin: 1.8.19

### Description: 
How to add custom css skin to adminLTE?

**Comment by alexoleynik0** [comment]
I've commented my approach to something similar in this [issue](https://github.com/z-song/laravel-admin/issues/1011#issuecomment-1451574711) . You can put your css file after the defaults or replace any of them entirely using it.
