### ISSUE TITLE
Side-by-side inputs.

### ISSUE THREAD

**Issue by gomes2191** [z-song/laravel-admin#5748]
Laravel Version: 10
PHP Version: 7.4
Laravel-admin: 1.8.19
Description:
Is there any way to put the field side by side and with a label above?
![image](https://user-images.githubusercontent.com/4576117/230097363-cac4152c-fffb-4688-94c1-22d660291584.png)
Similar to this, but with the above label.

**Comment by komarove** [comment]
Try to do like this: `$form->text('text', __('Text'))->setWidth('12', 'xs-12')`
Or you can add you own classes: `$form->text('text', __('Text'))->setWidth('8 my_class_for_input', '2 my_class_for_label')`

**Comment by gomes2191** [comment]
> Try to do like this: `$form->text('text', __('Text'))->setWidth('12', 'xs-12')`
> Or you can add you own classes: `$form->text('text', __('Text'))->setWidth('8 my_class_for_input', '2 my_class_for_label')`

I will check if it solves the problem.

**Comment by gomes2191** [comment]
I solved it as follows.
```
$form->column(6, function ($setForm) {
            $setForm->text('duration', 'Duração')->setWidth(12, 12)->placeholder('---')->icon('fa fa-clock-o fa-fw')->autofocus();
});

 $form->column(6, function ($setForm) {
            $setForm->text('duration', 'Duração')->setWidth(12, 12)->placeholder('---')->icon('fa fa-clock-o fa-fw')->autofocus();
});
```

In the css I did this to prevent the label text from going to the right.

`.control-label {
    text-align: unset !important;
}
`

The result was this:

![image](https://user-images.githubusercontent.com/4576117/231009108-505393fd-0351-4854-b6fd-a2284db536cf.png)
