### ISSUE TITLE
建议集成SimpleSoftwareIO\QrCode\Facades\QrCode

### ISSUE THREAD

**Issue by xiaalngf** [z-song/laravel-admin#575]
//controller中生成二维码
    public function generateQrCode()
    {
        return QrCode::format('png')->size(150)->margin(1)->generate(Input::get('q'));
    }
然后修改
class UrlWrapper extends AbstractDisplayer｛
......
 ` $qrcode = "<img src='https://somedomain.com/admin/api/generateQrCode?q={$this->value}' style='height:150px;width:150px;'/>";`
......
｝

这样就不用担心` https://api.qrserver.com/v1/create-qr-code`有时用不了了。

**Comment by z-song** [comment]
谢谢建议

不过demo那个功能只是演示作用，不是必要功能，就不集成进去了
