### ISSUE TITLE
saved and saving how to detect the mode

### ISSUE THREAD

**Issue by avifatal** [z-song/laravel-admin#576]
Hi,
There are supposed to be 4 mods in saved and saving.
pre create, pre update, post create and post update.

how do you diffrenciate between there situations? 
how can I know inside saved if this is post create and post update?
thanks

**Comment by yang5664** [comment]
```
            $form->saving(function($form){
                \Log::info(request()->getMethod());  <== Update(PUT)、Create(POST)
            });
```

**Comment by avifatal** [comment]
I think it should be seperated in to 4 different methods 
In the context of each you should provide $form and $model (with the data).
its odd to access the  $form to read the model data...

**Comment by z-song** [comment]
Thanks for your suggestion, I'll add a mode attribute for $form.

Use `$form->model()` to get the data model.

**Comment by avifatal** [comment]
@z-song , I still don't get it.
Have a look at the image bellow.
In the bottom, you can see the debugger evaluation.
As oppose to what you have saied,  `$form->model()` does not have the data, but `$form` .

Please help me understands that. thanks

![image](https://cloud.githubusercontent.com/assets/12430740/24032058/bc356922-0aee-11e7-8515-a3d5e885d78d.png)
