### ISSUE TITLE
How can I do drag and drop order sorting column and save to db using laravel-admin?

### ISSUE THREAD

**Issue by TuyenNguyenDinh** [z-song/laravel-admin#5778]
- Laravel Version: 7.4
- PHP Version:8.1
- Laravel-admin: 1.8.9

### Description:

As a title, I want to drag and drop column on grid table, how can I handle this, Pls help me, thank you

**Comment by capetrel** [comment]
You can try this : https://github.com/laravel-admin-extensions/grid-sortable
