### ISSUE TITLE
Form里面的multiSelect对应数据库里面varchar字段的时候，保存的时候出错

### ISSUE THREAD

**Issue by aquariuscool** [z-song/laravel-admin#578]
错误信息是：Array to string conversion。看了下之前的版本，之前在store和update里面setAttribute的时候有用formatValueBeforeSave把array转成用逗号隔开的字符串。

**Comment by z-song** [comment]
之前用逗号隔开的方式写死了存储格式，所以去掉了这种方式，以后需要自己在model中指定存储格式，比如字段名为options， 用逗号隔开的方式存储的话:

```php
public function setOptionsAttribute($options)
{
    if (is_array($options)) {
        $this->attributes['options'] = implode(',', $options);
    }
}

public function getOptionsAttribute($options)
{
    return explode(',', $options);
}
```

**Comment by aquariuscool** [comment]
谢谢！

**Comment by fasthold** [comment]
由于此前用了太多的逗号分隔，所以升级到 1.4.2 后有了太多的报错，有没有办法快速的兼容逗号的情形？

**Comment by aquariuscool** [comment]
@fasthold 在model里面加getXXXAttribute和setXXXAttribute也还挺方便吧？

**Comment by oiuv** [comment]
已解决，不过，这个在文档中要更新说明啊，要不都不知道。

**Comment by LeptonHuo** [comment]
@oiuv @z-song 我刚刚用你们提到的方法解决了checkbox 表单提交后不能将Array写入mysql的varchat字段。方法很方便！如果需要整理文档的话，我可以帮忙！

#preg_replace(): Parameter mismatch, pattern is a string while replacement is an array#
