### ISSUE TITLE
How to add recaptcha to login page 

### ISSUE THREAD

**Issue by hieulvt** [z-song/laravel-admin#5784]
- Laravel Version: 8.83.27
- PHP Version: 8.1.18
- Laravel-admin: 1.8.17

### Description:
Could you please help me on how to add the recaptcha to the default login page?
Thanks

**Comment by mRamadan0101** [comment]
follow google steps and u can all admin views in resource path copy all files into resource folder
then
add in bootstrap.php file this line
`app('view')->prependNamespace('admin', resource_path('views/admin'));`
then 
follow google steps
