### ISSUE TITLE
An arbitrary file upload vulnerability in laravel-admin v1.8.19 allows attackers to execute arbitrary code via a crafted PHP file.

### ISSUE THREAD

**Issue by Hel5ing** [z-song/laravel-admin#5793]
- Laravel Version: 9.0.x
- PHP Version: 8.1.13
- Laravel-admin: 1.8.19

### Description:
我的企业Github发现框架存在以下风险,导致项目无法通过安全审核, 请问该如何修复?

<img width="1310" alt="截屏2023-06-30 下午1 18 21" src="https://github.com/z-song/laravel-admin/assets/23660753/d21642e8-1914-4211-bf06-83bd65dafb25">

**Comment by Mte90** [comment]
a link instead of a screen to investigate it further?

**Comment by alexoleynik0** [comment]
#5726 Has a workaround for this issue.
