### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by avifatal** [z-song/laravel-admin#580]
I have customer model that has many assignments.
I in edit customer form, I put a grid with the related assignments.
the grid buttons acts very odd.
have a look at the attachments. 

![image](https://cloud.githubusercontent.com/assets/12430740/23871089/a8e1fca6-0831-11e7-9dbe-3609f21d9b9d.png)

same for the row edit

![image](https://cloud.githubusercontent.com/assets/12430740/23871131/d5381506-0831-11e7-91ca-f0968cfbfdb2.png)

Thanks!

**Comment by z-song** [comment]
Try to use ` $grid->resource($resource);` to set the resource path of the grid.

**Comment by NickCoolii** [comment]
@avifatal how do you handled this situation?
