### ISSUE TITLE
create方法添加新数据的确认画面

### ISSUE THREAD

**Issue by sheldon5** [z-song/laravel-admin#583]
在调用create之后出现了添加页面，点击submit按钮之后直接提交了数据。可以设计为点击按钮之后出现一个确认页面，将自己填写的信息列出来，然后下面有一个submit按钮，点击之后再提交吗

**Comment by never615** [comment]
感觉暂时没有这方面的计划...

**Comment by z-song** [comment]
感觉这个需求出现的不多，如果有需要可以用`Admin::script();`添加js代码来控制
