### ISSUE TITLE
how to add messagebox icon in to the header?

### ISSUE THREAD

**Issue by jesnagifto** [z-song/laravel-admin#5832]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:

like this image
![WhatsApp Image 2023-10-18 at 17 16 30_bd878c7b](https://github.com/z-song/laravel-admin/assets/123555177/3cafba16-5155-4df0-be56-354e4a89c3c4)

**Comment by fits-fujiura-st** [comment]
@jesnagifto 

Header template(header.blate.php) is in vendor directory.
So, you need to copy laravel-admin templates to your application direcotry first.
This post will help you.
https://github.com/z-song/laravel-admin/issues/943

And specific way to add icon is in this post.
https://blog.fits-inc.jp/2023/10/18/laravel-admin-add-header-icon/

**Comment by jesnagifto** [comment]
thank u for ur infomartion
