### ISSUE TITLE
In update form: Radio buttons and select inputs are not being selected in case of enums (string keys of options)

### ISSUE THREAD

**Issue by amismailz** [z-song/laravel-admin#5833]
- Laravel Version: 8.83.26
- PHP Version: 7.4
- Laravel-admin: 1.8.19

### Description:
While using dropdowns / radio buttons in the update form, saved values are not being selected if options have string keys but works with integer ones.  

#### Not working (No inputs are selected)
```
// $form->model()->gender = 'male'
$form->radio('gender', __('Gender'))->options(['male' => 'male', 'female' => 'female']);`
$form->select('gender', __('Gender'))->options(['male' => 'male', 'female' => 'female']);`
```
#### Works (Male is selected)
```
// $form->model()->gender = 1
$form->radio('gender', __('Gender'))->options([1 => 'male', 2 => 'female']);`
$form->select('gender', __('Gender'))->options([1 => 'male', 2 => 'female']);`
```

**Comment by fits-fujiura-st** [comment]
@amismailz 

Hi, following code works in my environment.

```
    protected function form()
    {
        $form = new Form(new User());

        $form->text('name', __('Name'));
        $form->email('email', __('Email'));

        $form->radio('sex1', 'Sex(number)')->options([0=>'male', 1=>'female', 2=>'other'])->default(0);
        $form->radio('sex2', 'Sex(string)')->options(['male'=>'male', 'female'=>'female', 'other'=>'other'])->default('male');
 
        $form->datetime('email_verified_at', __('Email verified at'))->default(date('Y-m-d H:i:s'));
        $form->password('password', __('Password'));
        $form->text('remember_token', __('Remember token'));

        return $form;
    }
```

Snapshot of DB
<img width="835" alt="image" src="https://github.com/z-song/laravel-admin/assets/47600545/6bcb2fe0-fc6d-4452-a0af-366b890173b0">

Snapshot of editing user id=1
![image](https://github.com/z-song/laravel-admin/assets/47600545/19523936-cc52-47d3-92c3-d3cf6e03e806)

Snapshot of editing user id=3
![image](https://github.com/z-song/laravel-admin/assets/47600545/0e2af5ba-c3ef-44e7-9bea-206ffd0c7a8e)

Is it possible to check the actual DB values?

**Comment by amismailz** [comment]
@fits-fujiura-st What is the field data type you use? did you use enum?

**Comment by fits-fujiura-st** [comment]
@amismailz 

I used int for number and varchar for string.

<img width="706" alt="image" src="https://github.com/z-song/laravel-admin/assets/47600545/4f427695-d90a-461d-96a8-5a97108fa0b1">

**Comment by amismailz** [comment]
@fits-fujiura-st I just got the cause of this issue, this was because I make some getter functions (attribute accessors) like this:

```
public function getGenderAttribute($value)
    {
        return __(ucfirst($value));
    }
```

I'll try another way to handle this.

Thank you so much, I really appreciate your great support :+1:
