### ISSUE TITLE
value are saving in the DB and show the grid But value not show in edit page? how to solve this?

### ISSUE THREAD

**Issue by jesnagifto** [z-song/laravel-admin#5842]
- Laravel Version: #.#.#
- PHP Version:
- Laravel-admin: #.#.#

### Description:
![Screenshot 2023-11-29 144150](https://github.com/z-song/laravel-admin/assets/123555177/babe0bec-d7aa-4271-ab7b-14f93ecd9653)
![Screenshot 2023-11-29 144213](https://github.com/z-song/laravel-admin/assets/123555177/51893e67-eef6-47ca-a89e-577f608ca8b8)

**Comment by jesnagifto** [comment]
cast is not show in the edit page .... how to solve this plase help me.

**Comment by xxl4** [comment]
Maybe you can use text form to display the value , or the right options for it.
