### ISSUE TITLE
image中设置的默认的rules会导致删除失败

### ISSUE THREAD

**Issue by never615** [z-song/laravel-admin#587]
![screen shot 2017-03-14 at 6 45 52 pm](https://cloud.githubusercontent.com/assets/9959927/23897018/96fd07fa-08e6-11e7-9b8f-c662ea91c50d.png)
在点击删除按钮后,
![screen shot 2017-03-14 at 6 47 50 pm](https://cloud.githubusercontent.com/assets/9959927/23897097/ce4a0f82-08e6-11e7-9315-4b31d50ed3a9.png)
下列Form中的代码会执行然后返回错误信息->导致报错
```
        // Handle validation errors.
        if ($validationMessages = $this->validationMessages($data)) {
            return back()->withInput()->withErrors($validationMessages);
        }
```

顺便提一句,这个注释会导致编辑器提示出现问题:
```
 /* @var Model $this->model */
```
![screen shot 2017-03-14 at 6 15 50 pm](https://cloud.githubusercontent.com/assets/9959927/23897186/13a5492a-08e7-11e7-9504-193da6b113a2.png)

**Comment by z-song** [comment]
具体是什么报错呢？

**Comment by never615** [comment]
删除之后,验证就通不过,提示不是图片.
但这个提示是不会到前端的,前端看到的是这样的效果.
![screen shot 2017-03-14 at 6 55 32 pm](https://cloud.githubusercontent.com/assets/9959927/23897376/e1f504aa-08e7-11e7-8c3c-6568500105de.png)

**Comment by z-song** [comment]
这个不是验证错误，你可以具体看一下异常日志

我之前遇到这个问题，是因为数据库的这个字段设置为not null,  把字段设置为允许为空就好了。

**Comment by never615** [comment]
我一步一步跟踪代码了,就是验证这几句.
这个我validation写的
 'image' => ':attribute 必须是图片。',
验证结果返回的是:
	{"logo":["Logo \u5fc5\u987b\u662f\u56fe\u7247\u3002"]}
后面那一串就是 必须是图片。

**Comment by never615** [comment]
我把rules中的image删除了就可以通过执行了.而且我的字段是允许为空的.

**Comment by never615** [comment]
我知道了,是1.4新加的中间件导致的.

**Comment by z-song** [comment]
新增的哪个中间件？

**Comment by never615** [comment]
```
\Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull::class,
```
图片中上面那条是开启这个中间件后的结果.
![screen shot 2017-03-14 at 7 21 32 pm](https://cloud.githubusercontent.com/assets/9959927/23898282/80a48b86-08eb-11e7-813d-8aab68d4b0a9.png)

**Comment by never615** [comment]
还有一个问题是,图片为空的时候,显示这样.

![screen shot 2017-03-14 at 7 13 25 pm](https://cloud.githubusercontent.com/assets/9959927/23898508/3d9ee4d4-08ec-11e7-8d64-be19903d0e45.png)

这个我还没仔细看,扫了一眼应该是这段代码:
```
    /**
     * Get file visit url.
     *
     * @param $path
     *
     * @return string
     */
    public function objectUrl($path)
    {
        if (URL::isValidUrl($path)) {
            return $path;
        }

        return rtrim(config('admin.upload.host'), '/') . '/' . trim($path, '/');
    }
```

在使用了文件系统(filesystem)配置的时候,感觉这样用更好一点:
```
Storage::disk("admin")->url($path)
```
filesystem配置:
```
        'admin' => [
            'driver' => 'local',
            'root' => storage_path('app/public'),
            'url' => env('APP_ URL').'/storage',
            'visibility' => 'public',
        ],
```
七牛里面也加上url参数,一个文件系统有自己存储位置和url.不用单独配置upload的host了

**Comment by z-song** [comment]
谢谢提醒

**Comment by never615** [comment]
@z-song 
您好,看到了您关闭了这个issue,提交了这个修改...不知道这个提交是不是解决这个issue的
https://github.com/z-song/laravel-admin/commit/1392739ee8c5a7276b8242c3b3c219c093c50c9e
但是这个提交并没有解决这个问题,出问题的代码会在您修改的代码之前运行.
<img width="678" alt="screen shot 2017-03-15 at 1 10 23 am" src="https://cloud.githubusercontent.com/assets/9959927/23912947/631332c6-091c-11e7-87bc-0d9b65903a7f.png">
出问题的是验证,走到验证就会return,您修改的是prepare中会执行的代码,是在验证之后执行的.

```
	array (
'key' => '0',
  'logo' => NULL,
  '__del__' => NULL,
  '_token' => 'c2Daiov6xxVsg70kCjRbqsAD67U6LvtW1qrWRIPn',
  '_method' => 'PUT',
)
```
  'logo' => NULL, 这个通不过rules是image的验证....
```
  if ($validationMessages = $this->validationMessages($data)) {
            Log::info($validationMessages);
            return back()->withInput()->withErrors($validationMessages);
        }
```
validationMessages打印:
	{"logo":["Logo \u5fc5\u987b\u662f\u56fe\u7247\u3002"]}  (Logo 不是图片)

  $form->image("logo");

**Comment by z-song** [comment]
发现Laravel的验证一个很奇怪的地方
```php
Validator::make(['logo' => ''], ['logo' => 'image']);

Validator::make(['logo' => null], ['logo' => 'image'])
```
上面能通过，下面不能通过，所以我要把它强转一下

**Comment by z-song** [comment]
已经提交了修复

**Comment by never615** [comment]
@z-song 

`isset — Determine if a variable is set and is not NULL`

你新加的这段代码条件进不去...
```
        /**
         * Make input data validatable if the column data is `null`.
         */
        if (isset($input[$this->column]) && is_null($input[$this->column])) {
            $input[$this->column] = '';
        }
```

不过image是null就说不是图片,null应该是require判断的规则...应该是laravel的bug..

**Comment by z-song** [comment]
疏忽了，已修改
