### ISSUE TITLE
Available fields for many-to-many relationship

### ISSUE THREAD

**Issue by IDEPTA** [z-song/laravel-admin#5872]
- Laravel Version: 11.19.0
- PHP Version: 8.3.9
- Laravel-admin: 1.8.19

### Description:

Hello everyone, did I understand correctly that for many-to-many relationships you can only use multipleSelect and checkbox?
And other types of fields, such as radio and select, do not work with such relationships?

**Comment by Ladel** [comment]
Привет.
Ты также можешь использовать `belongsToMany`

**Comment by Ladel** [comment]
<details>
<summary>В качестве примера</summary>
  <img src="https://github.com/user-attachments/assets/cd522617-b24e-45cf-b3cd-137b725ac4dd">
</details>

**Comment by IDEPTA** [comment]
Спасибо!
