### ISSUE TITLE
How to disable the export button for a table?

### ISSUE THREAD

**Issue by IDEPTA** [z-song/laravel-admin#5873]
- Laravel Version: 11.19.0
- PHP Version: 8.3.9
- Laravel-admin: 1.8.19

### Description:
Hello everyone, I need to add a button to export records from a table to csv and excel files. Such a button already exists in some of my tables, but I don't understand how to enable it.

![image](https://github.com/user-attachments/assets/0a2591bd-ccad-4cfa-926d-2f5ab9497481)
![image](https://github.com/user-attachments/assets/ffa9c8f9-e087-4507-b2c0-5bb6fe4554d7)

**Comment by Ladel** [comment]
That should help

```php

$grid->disableExport(false);
```

**Comment by IDEPTA** [comment]
> Это должно помочь.
> 
> ```
> $grid->disableExport(false);
> ```

This really helped, thank you so much!
