### ISSUE TITLE
为什么本地测试/admin 是正常的，放服务器上 会出现 Class App\Admin\Controllers\HomeController does not exist

### ISSUE THREAD

**Issue by 734918601** [z-song/laravel-admin#596]
![default](https://cloud.githubusercontent.com/assets/14305518/23936419/10a8e226-098d-11e7-9aaf-363b785a458a.png)

**Comment by z-song** [comment]
运行一下`composer dump-autoload`看看

**Comment by 734918601** [comment]
这个是为什么，  谢谢啊。

**Comment by daikirokuyama** [comment]
<img width="981" alt="2018-06-15 22 41 51" src="https://user-images.githubusercontent.com/29940203/41471098-9a075db8-70ed-11e8-8876-40e5ec2ec068.png">

I deployed my app with Heroku.
The image is showing up on the screen.
I tried these command below, but doesn't solve.
- `composer dump-autoload`
- `heroku run composer dump-autoload`

Please help me out!!!
※It is not happened in my local environment ; (
thanks!
