### ISSUE TITLE
Multi language support

### ISSUE THREAD

**Issue by SpinyMan** [z-song/laravel-admin#602]
Is it possible?

**Comment by rizaergun** [comment]
i am looking for the answer to this question

**Comment by SpinyMan** [comment]
How about this:
1) https://laravel-news.com/how-to-add-multilingual-support-to-eloquent
2) https://github.com/dimsav/laravel-translatable

**Comment by z-song** [comment]
`laravel-admin` does not have built-in multilingual support, but you can integrate these packages into `laravel-admin`

**Comment by SpinyMan** [comment]
Could you pls give me an example? How using tabs of languages and relations create multilingual content? Would be great if u help me!
