### ISSUE TITLE
How to install it in subfolder

### ISSUE THREAD

**Issue by newbie2005** [z-song/laravel-admin#603]
How to install laravel-admin in subfolder e.g. laravel-admin,
user access http://ip address//laravel-admin

**Comment by z-song** [comment]
open `config/admin.php` and change `prefix` to `laravel-admin`

**Comment by my101du** [comment]
looks like Laravel-Admin can not generate url/routes correctly when running laravel in sub directory.

eg:  I have a laravel site, running in a sub directory like this:

www.sample.org/laravel-app

in /routes/web.php file, I create a route define as below

```php
Route::get('/test', 'HomeController@test')->name('home.test');
```
in the blade, render it

```html
<a href="{{route('home.test')}}">test</a>
```

that will generate the link  correctly  as expect (with /sub directory prefix):

www.sample.org/laravel-app/test


but the laravel-admin's routes always start at   www.sample.org/, for example:

www.sample.org/admin/auth/login

did not generate the correct

www.sample.org/laravel-app/admin/auth/login

 

I have modify the /config/admin.php , the "prefix" from "admin" to "laravel-app/admin", but the system return a "404" error.

**Comment by my101du** [comment]
I just found the solution.

modify the file `vendor/encore/larvel-admin/src/helpers.php`

```php
function admin_base_path($path = '')
    {
        // replace the '/' with the '/sub-directory/' name
        $prefix = '/laravel-app/'.trim(config('admin.route.prefix'), '/');
```

**Comment by SimZal** [comment]
I can confirm that this is still broken and @my101du fix doesn't seem to work. There are 2 pull requests with a promised solution.

**Comment by yucolabjames** [comment]
Can we re-open this issue? tried solutions posted by @z-song and @my101du but doesn't seem to work. And there are over 80 pull requests...
