### ISSUE TITLE
如何插入一对一数据模型？

### ISSUE THREAD

**Issue by spc324** [z-song/laravel-admin#606]
如何插入一对一数据模型？

**Comment by edwinhuish** [comment]
参考这个: [关联模型](https://github.com/z-song/laravel-admin/blob/master/docs/zh/model-grid.md#关联模型)

**Comment by z-song** [comment]
模型里面定义一对一关系
```php
public function profile ()
{
    return $this->hasOne(Profile::class);
}
```
在model-form中使用
```php
$form->text('profile.mobile');
```

**Comment by spc324** [comment]
我试了这样是可以 但是在edit方法里 Form 表单里取不到profile.mobile的值

**Comment by kelvenchi** [comment]
对， 我也遇到这个问题， 我再form表单里面也拿不到profile.mobile 的值

**Comment by luoandy** [comment]
同样  laravel5.4    laravel-admin1.4
