### ISSUE TITLE
Please help me in images

### ISSUE THREAD

**Issue by aliakel** [z-song/laravel-admin#610]
#Encoding format (tmp) is not supported.
This appear when i use intervention methode as crop. ($form->image('image', 'Image')->crop(100,100);
and i can't use imageMultiple function to uploade multiple images
and when i wirte ($form->image('image', 'Image')->multiple(); ) i receive this error 
(Type error: Argument 1 passed to Encore\Admin\Form\Field\File::hydrateFiles() must be of the type array, object given)

**Comment by edwinhuish** [comment]
you can see this. #484 

```
public function setPicturesAttribute($pictures)
{
    if (is_array($pictures)) {
        $this->attributes['pictures'] = json_encode($pictures);
    }
}

public function getPicturesAttribute($pictures)
{
    return json_decode($pictures, true);
}
```

**Comment by aliakel** [comment]
i tried it, and the same error.
and what is about crop function probleme?

**Comment by edwinhuish** [comment]
what vesion of laravel-admin are you using?

**Comment by aliakel** [comment]
1.4.*

**Comment by aliakel** [comment]
$form->image('image', 'Image')->multiple(); 
work now
but crop() the same probleme (Encoding format (tmp) is not supported.)

**Comment by z-song** [comment]
This error is thrown by intervention.

**Comment by aliakel** [comment]
My question: How it works in your demo (when you call flip('v') in images demo) ?
I tried to use intervention 2.3.0 and 2.3.11 and the sme error.
intervention doesn't accept tmp extension accouring to them documentation
I develope laravel application in windows platform, using laravel 5.4, laravel-admin 1.4.*.
Please answer me.
Thanx a lot z-song.

**Comment by rizaergun** [comment]
the problem persists in version 1.4.x-dev

"Encoding format (tmp) is not supported."
