### ISSUE TITLE
Controlling the redirect after save

### ISSUE THREAD

**Issue by avifatal** [z-song/laravel-admin#612]
Hi,
I want to controll the redirect after the save.
I want the user to stay on the same form he is editing.

I have done it as the following, but then I loose the "update success" green message.
```
            $form->saved(function(Form $form){
                return redirect('/admin/assignments/'.$form->model()->id.'/edit');
            });
```
What is the correct way to redirect after submit.
Thanks

**Comment by z-song** [comment]
update `laravel-admin` and use:
```php
admin_toastr('update success');
return redirect('/admin/assignments/'.$form->model()->id.'/edit');
```

**Comment by Naskalin** [comment]
with localization admin_toastr(__('admin.save_succeeded'));
