### ISSUE TITLE
使用多级联动组件后js会重复执行

### ISSUE THREAD

**Issue by a648132694** [z-song/laravel-admin#619]
我用的是1.4版本的,在使用地区选择的多级联动组件后,重复提交后js会重复执行,比如我submit 4次,在第5次下拉栏的时候,js的change事件也会重复5次,无论是放在自己的项目还是官方的示例中都有这种情况出现
![image](https://cloud.githubusercontent.com/assets/13271701/24043596/539611e6-0b52-11e7-94c8-8a277024677a.png)

**Comment by ajiader** [comment]
我也好像有这个问题

**Comment by a648132694** [comment]
我这边改了下js代码,在每次change事件之前加入off方法取消了绑定
`$(document).off('change', "{$this->getElementClassSelector()}");`
不知道这是bug还是我的用法有问题

**Comment by akazhuk** [comment]
我也有这个问题，选项一直跳

**Comment by wonhsi** [comment]
执行submit 操作，是 pajax 局部刷新，将请求获取的内容里有对应 js 方法，被重复写在页面上了。

你在框架里，判断 是否是pajax， 来决定 是否输出js 方法

**Comment by edwinhuish** [comment]
这个是一个BUG，只要 @z-song 将 select field 的 load() 函数里 JS 改一下即可。注意有 ``` .off('change', "{$this->getElementClassSelector()}")```

```
        $script = <<<EOT

$(document).off('change', "{$this->getElementClassSelector()}").on('change', "{$this->getElementClassSelector()}", function () {
    var target = $(this).closest('.fields-group').find(".$class");
    $.get("$sourceUrl?q="+this.value, function (data) {
        target.find("option").remove();
        $(target).select2({
            data: $.map(data, function (d) {
                d.id = d.$idField;
                d.text = d.$textField;
                return d;
            })
        }).trigger('change');
    });
});
EOT;
```

原因是每次 ``` pjax:end ``` 之后，都会重新执行``` "script[data-exec-on-popstate]" ``` 里面的代码，导致同样的 ```Event``` 事件挂载多次。
```
    $(document).on("pjax:popstate", function() {
        $(document).one("pjax:end", function(event) {
            $(event.target).find("script[data-exec-on-popstate]").each(function() {
                $.globalEval(this.text || this.textContent || this.innerHTML || '');
            });
        });
    });
```
