### ISSUE TITLE
请问项目的数据库迁移文件在哪呢？

### ISSUE THREAD

**Issue by mornone** [z-song/laravel-admin#62]
安装完成之后运行报没有数据库表的错，admin_users和menu都没有呢？谢谢

**Comment by z-song** [comment]
@mornone `vendor/encore/laravel-admin/migrations/2016_01_04_173148_create_admin_tables.php`

**Comment by mornone** [comment]
谢谢，我也找到了，大神回复好快啊！

**Comment by z-song** [comment]
可以加README下面的留下的QQ群交流 😁
