### ISSUE TITLE
form表单中的这种文本框可以叠加使用吗

### ISSUE THREAD

**Issue by moore0903** [z-song/laravel-admin#622]
form表单中的这种文本框可以叠加使用吗
就是一行显示两个文本框,前面一个输入文本款,后面接着一个下拉选择框
就比如输入一个数量后面再选择计量单位(克,斤)
这种,不知道我表达能不能明白

**Comment by edwinhuish** [comment]
暂时不行。按照 Laravel-admin 现在的模式，一行是一个field，其他需要参考dateRange，hasMany 写

**Comment by moore0903** [comment]
好的,谢谢
