### ISSUE TITLE
security issue

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#625]
In Operation log passwords are in plain text!!! It's big security issue i think...
![zaznaczenie_325](https://cloud.githubusercontent.com/assets/358993/24073470/4008b7ea-0bf8-11e7-9867-a03d5250771e.png)

**Comment by edwinhuish** [comment]
You can change permission for just administrator...

**Comment by qcol** [comment]
Passwords in plain text should not see even the admin, it is not safe.

**Comment by avifatal** [comment]
Its a bug issue. should be stared or be blank
