### ISSUE TITLE
菜单添加错误

### ISSUE THREAD

**Issue by hongxchen** [z-song/laravel-admin#628]
按照文档配置成功后，添加新菜单，parent设置为Root，报错
SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uri' cannot be null (SQL: insert into `admin_menu` (`parent_id`, `title`, `icon`, `uri`, `updated_at`, `created_at`) values (0, Course, fa-bars, , 2017-03-20 02:53:30, 2017-03-20 02:53:30))

**Comment by Unull** [comment]
之前有遇到过，我是设置url为/

**Comment by edwinhuish** [comment]
提示很明显了～
