### ISSUE TITLE
提示我csrf，七牛云上传视频

### ISSUE THREAD

**Issue by jackqth** [z-song/laravel-admin#629]
![image](https://cloud.githubusercontent.com/assets/16730906/24089916/a38d4432-0d76-11e7-924e-7cf23e4c01d3.png)

**Comment by jackqth** [comment]
不止是七牛有问题，本地上传也有问题

**Comment by Unull** [comment]
文件上传要加csrf_token

**Comment by jackqth** [comment]
但是我传图片是可以的，而且我把csrf屏蔽了也不行

**Comment by Unull** [comment]
我的版本是1.4.＊，刚刚试了，是可以的。你不屏蔽csrf，看会报什么错

**Comment by jackqth** [comment]
我的是1.3.*，不屏蔽csrf就报我最上面的错，屏蔽csrf就会报sql的错，而且我用file传图片都没问题，只要视频就会有报错。
![image](https://cloud.githubusercontent.com/assets/16730906/24093239/d4a2cf8a-0d8d-11e7-8383-de1e79507e31.png)
哥们你做过视频上传，方便的话给我个邮箱，我请教一下

**Comment by Unull** [comment]
Nnull#live.com
