### ISSUE TITLE
tab组件只有第一个组件内容正常显示，后面的组件内容显示异常。

### ISSUE THREAD

**Issue by oiuv** [z-song/laravel-admin#634]
$tab->add('用户类型分布', $pie1);
                    $tab->add('用户类型分布', $pie2);

只有第一个pie内容能显示，第二个pie内容不显示。

**Comment by MissMyCat** [comment]
诶，这个问题我也遇到了……
```
$tab->add("销量", $bar));
```

同时，在collapse组件也存在这样的问题。
@z-song 有空的话看一下吧，看是用法不对还是怎么说？

**Comment by ChengwenY** [comment]
同样遇到这个问题，js报错
`Uncaught DOMException: Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-0.5) is negative.
`

**Comment by gm8300130** [comment]
一樣的問題
只有第一列是正確的,
之後的不是顯示不出來
就是點下去會控制到其他列的開合

**Comment by ericliu000** [comment]
找到问题了，是因为echarts活着chartjs的id重复了。

`<div id="main" style="width: 600px;height:400px;margin: auto"></div>
`
改为这个
`<div id="main<?php echo $rand?>" style="width: 600px;height:400px;margin: auto"></div>
`
就好了
