### ISSUE TITLE
form编辑时，数据库的值如何修改后再放到表单中？

### ISSUE THREAD

**Issue by Alex-Leung** [z-song/laravel-admin#636]
如题：数据库中有个价格字段(price)是以分为单位保存，但是显示的时候想以2位小数点显示
假如数据库的值是100，显示的时候就显示：1.00

在grid中显示没有问题，只要加上
$grid->price('价格')->display(function ($price) {
        return number_format($price/100, 2, '.', '');
});

我想问的是，在编辑记录时如何也显示为：1.00 ???
$form->currency('price', '价格')->symbol('￥');  //这样每次都显示100.00

**Comment by edwinhuish** [comment]
既然grid 需要改，form也需要改，还不如直接改sql. 

个人意见，不知你实际需要。

**Comment by edwinhuish** [comment]
$form->currency('price', '价格')->symbol('￥')->value(function ($price){

     return $price/100;

}); 

$form->saving(function (){

//...........

});

**Comment by z-song** [comment]
参考laravel 模型的访问器和修改器 https://laravel.com/docs/5.4/eloquent-mutators#accessors-and-mutators
