### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages

### ISSUE THREAD

**Issue by includeleec** [z-song/laravel-admin#64]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - intervention/image 2.3.8 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.7 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.6 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.5 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.4 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.3 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.2 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.1 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - intervention/image 2.3.0 requires ext-fileinfo * -> the requested PHP exte                                                                   nsion fileinfo is missing from your system.
    - encore/laravel-admin dev-master requires intervention/image ~2.3 -> satisf                                                                   iable by intervention/image[2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3                                                                   .7, 2.3.8].
    - Installation request for encore/laravel-admin dev-master -> satisfiable by                                                                    encore/laravel-admin[dev-master].

  To enable extensions, verify that they are enabled in those .ini files:
    - D:\AppServ\php5\php.ini
  You can also run `php --ini` inside terminal to see which files are used by PH                                                                   P in CLI mode.

**Comment by z-song** [comment]
you need to install fileinfo extension for php.
