### ISSUE TITLE
prism问题，初次加载样式文件已经加载，但无法显示行号；手动刷新后才显示，请问如何处理？

### ISSUE THREAD

**Issue by guilinli001** [z-song/laravel-admin#640]
**prism问题，初次加载样式文件已经加载，但无法显示行号；手动刷新后才显示，请问如何处理？**
我的配置如下：
**bootstrap.php中**
Admin::css('/packages/prism/prism.css');
Admin::js('/packages/prism/prism.js');
**我发现**
你的页面
![image](https://cloud.githubusercontent.com/assets/13914042/24180255/db5fba1a-0eee-11e7-9850-4b631f3c51dc.png)
我的页面
![image](https://cloud.githubusercontent.com/assets/13914042/24180493/2c816c6c-0ef0-11e7-97ec-c34efd24aee3.png)
![image](https://cloud.githubusercontent.com/assets/13914042/24180567/84046520-0ef0-11e7-9c12-30e315ecc9f2.png)

我的页面有4个prism,而你的是5个prism

**Comment by z-song** [comment]
在需要高亮的页面加上`Admin::script('Prism.highlightAll();');`
