### ISSUE TITLE
多级联动，第一次的时候不显示子选项

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#642]
需要选择一下其他选项，子选项才会有选项显示出来 
![default](https://cloud.githubusercontent.com/assets/9032762/24183197/deccc84c-0f01-11e7-8b03-cc70c7c60562.png)

**Comment by never615** [comment]
子级需要通过option在设置一遍默认值;
我提了一种不需要设置默认值或者选项的方案.
https://github.com/z-song/laravel-admin/pull/609
目前还没有回应.

**Comment by a648132694** [comment]
请问下你们在使用这个的时候会不会出现js重复执行的情况?比如触发了多次change事件,然后重复多次请求

**Comment by yugihuang** [comment]
@a648132694 我也发现这个问题，以demo里的多级联动页面为例，不使用浏览器刷新页面，打开一次会注册一次change事件，到指触发多次，应该是pjax机制的问题，或许注册change之前先用off处理一下

**Comment by lukang287** [comment]
亲测这个可以解决，http://www.cc430.cn/index.php/archives/523/
