### ISSUE TITLE
可否禁用 pjax ？

### ISSUE THREAD

**Issue by fasthold** [z-song/laravel-admin#643]
部分二次嵌入js代码不会被执行，非得刷新一下
硬伤啊

**Comment by edwinhuish** [comment]
二次嵌入的js可以用jquery的html() 插入，如此会自动运行新插入的js代码

**Comment by z-song** [comment]
嵌入的js文件里面封装方法，在外面用`Admin::script()`调用

**Comment by HustGuoHeng** [comment]
我看提供的管理界面上使用pajax存在数据修改之后部分接口页面缓存未刷新的问题，看起来好难受额。

**Comment by dynamohuang** [comment]
可以的  pjax
不求哪些特性 稳定就好
public/vendor/laravel-admin/jquer-pjax/query.pjax.js  
添加一行 $.pjax.disable()
bingo~~~~

**Comment by zhpefe** [comment]
pjax 打开的情况下，在页面有自定义工具时，会出现
VM386:80 Uncaught SyntaxError: Invalid or unexpected token
或者
VM1844:25 Uncaught SyntaxError: Unexpected end of input
错误，都是由于自定义工具的 JS 加载不完全导致的。
这个真是头疼。楼上  $.pjax.disable() 不起作用，会导致表单提交无法保存。

**Comment by xiaohuilam** [comment]
now you can put `Admin::disablePjax()` into your `App\Providers\AppServiceProvider`
```php
namespace App\Providers;

use Encore\Admin\Facades\Admin;
use Illuminate\Support\ServiceProvider;

class AppServiceProvider extends ServiceProvider
{
    public function boot()
    {
        Admin::disablePjax();
    }
}
```

**Comment by zacksleo** [comment]
header('X-PJAX: false');

**Comment by D0ggy** [comment]
>"encore/laravel-admin": "^1.8",

- 1、确实，我自定义页面的时候，如下使用的时候，**禁止pjax后，表单没法提交了**


```php
use Encore\Admin\Widgets\Form;

$form = new Form([ 
    'start_time' => $start_time,
    'end_time'   => $end_time,
]);

$form->dateRange('start_time', 'end_time', '时间范围')->required();
$form->disablePjax();
```

- 2、**但是貌似使用这个表单就没啥问题** : `\Encore\Admin\Form form($model, \Closure $callable)` :
```php
$form = Admin::form(Model::class, function (Form $form) {
    $form->html('直接提交导出');
});
    $script = <<<SCRIPT
    $('.content form').removeAttr('pjax-container');
SCRIPT;
    Admin::script($script);
```

**总结**，尝试使用第 2 种情况的 form，第 1 种情况应该是个 🐛🐛

**Comment by zmy2002** [comment]
最烂的框架没有之一，那个pjax 的加载能把你的 html全部刷烂。
