### ISSUE TITLE
编辑时图片不显示

### ISSUE THREAD

**Issue by Unull** [z-song/laravel-admin#644]
![image](https://cloud.githubusercontent.com/assets/15064387/24185378/d2495dea-0f0d-11e7-9dd2-a7650c6cee86.png)
版本：1.4.2

**Comment by fasthold** [comment]
同样存在这个问题

**Comment by edwinhuish** [comment]
源码没有设置fileinput 文件的type 或者 filetype

**Comment by Unull** [comment]
我用1.4.1的时候不用设置的文件类型的呀

**Comment by never615** [comment]
你重新发布资源了吗?

**Comment by Unull** [comment]
重新发布了
![image](https://cloud.githubusercontent.com/assets/15064387/24201477/1716b192-0f4b-11e7-9a6a-11d35b818320.png)

**Comment by never615** [comment]
然后清理一下,view缓存

**Comment by Unull** [comment]
依旧不行✋

**Comment by akazhuk** [comment]
我也遇到這個問題

**Comment by z-song** [comment]
清理浏览器缓存

**Comment by Unull** [comment]
清理缓存，卸载包重新安装发布，都试过了，还是会存在。
我的开发环境是Laravel Homestead ，是不是有php扩展未安装？
@z-song

**Comment by wanghuanyi** [comment]
我这个问题依旧不能解决 我是 1.4.3-dev

**Comment by xiaobailc** [comment]
#687
