### ISSUE TITLE
请问是否能够分享一下demo的源码

### ISSUE THREAD

**Issue by yoshi315** [z-song/laravel-admin#646]
如题，请问是否能够分享一下demo的源码，谢谢作者带来这么好的admin框架

**Comment by edwinhuish** [comment]
已经很多人问过了，松一直回复由于源码有其他项目资料，不方便公开。

**Comment by yoshi315** [comment]
只是把controller里面的代码公开一下也好啊

**Comment by edwinhuish** [comment]
controller 里主要就是 grid() 和 form()，都已经公开了，你看一下tab 页就知道了。

做程序猿眼神要好一点，不然怎么发现BUG呢？ :rofl:

**Comment by yoshi315** [comment]
好的，谢谢，我现在已经在读源代码了，读源代码比文档更加细节化。

**Comment by edwinhuish** [comment]
嗯，优质的代码比任何文档好
