### ISSUE TITLE
How could I customize the "add button" URI in grid?

### ISSUE THREAD

**Issue by chianhsieh** [z-song/laravel-admin#660]
Hello,

The add button URI of the grid is defined by the currently URL.
For example,
Current URL: xxx.com/admin/articles
URI of add button: /admin/articles/create

If I want to change the URI of add button to something like /admin/comments/create, how should I do?

I have this idea because I put 2 grid with different model in the same page. Each of them need their own URI path of the add button.

Thank you.

**Comment by z-song** [comment]
You can't customize the add button.

But you can remove the button by using `$grid->disableCreation();`, and add a custom tool for grid like following:
```php
$grid->tools(function ($tools) {
    $tools->append("<a href='your-create-URI' class='btn btn-default'>Create</a>");
});
```

**Comment by LanKing** [comment]
Hello, what about creating buttons near "Create button" (on the right side), not on the left side of grid top?

**Comment by mcsham** [comment]
![image](https://user-images.githubusercontent.com/40900923/123474901-52f58480-d603-11eb-9056-453cac28e1a7.png)
therefore, it is not created where the create button should be

**Comment by leandroeidi** [comment]
This is an old issue, but I couldn't find another place with this problem, so I'll write here how I did it.
Basically, I created another button with the same classes and style of the default create button.

```
$grid->disableCreation();
$grid->tools(function ($tools) {
	$tools->append('<div class="btn-group pull-right" style="margin-right: 10px"><a href="/my-custom-create-url" class="btn btn-sm btn-success"><i class="fa fa-save"></i><span class="hidden-xs">&nbsp;&nbsp;新規</span></a></div>');
});
```
My new custom button exactly in the place and design of the normal button.
![laravel-admin-create-button](https://github.com/user-attachments/assets/351cf60a-fea3-4fba-b27d-a65f5bae6417)
