### ISSUE TITLE
ubuntu apache访问根目录正常，却无法访问/admin??

### ISSUE THREAD

**Issue by guilinli001** [z-song/laravel-admin#664]
配置如下：
ServerAlias www.laravel.local
DocumentRoot /var/www/laravel/public
http://laravel.local 访问正常；http://laravel.local/admin 无法访问
------------
Not Found

The requested URL /admin was not found on this server.

Apache/2.4.12 (Ubuntu) Server at laravel.local Port 80

**Comment by z-song** [comment]
apache配置问题，你得去找laravel在apache下的配置文档
