### ISSUE TITLE
Command (multiple) is not available for driver (Gd).

### ISSUE THREAD

**Issue by iapexli** [z-song/laravel-admin#665]
[Command](url) (multiple) is not available for driver (Gd).

php 5.6.30
"encore/laravel-admin": "1.4.x-dev",
 "intervention/image": "^2.3",

**Comment by iapexli** [comment]
升级后 使用方式不对

已解决

**Comment by lukaskris** [comment]
???

**Comment by igo9go** [comment]
怎么解决的 ` $form->image('pictures')->multiple();`
