### ISSUE TITLE
1.4.x-dev null value as edit not working to all fields

### ISSUE THREAD

**Issue by rizaergun** [z-song/laravel-admin#666]
this problem available for all fields. 1.3.x-dev does not have this problem.

**Comment by z-song** [comment]
Currently  try to remove `ConvertEmptyStringsToNull` middleware in `app/Http/Kernel.php` to fix this.

**Comment by rizaergun** [comment]
Thanks @z-song, it is working.

**Comment by qcol** [comment]
yes, it works now, thanks

**Comment by connected-company** [comment]
@z-song this solve the problem for me.

It's possible to fix in v1.4* branch ? **Or** add a note in the install documentation  ?
