### ISSUE TITLE
grid actions()方法取消？

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#67]
![image](https://cloud.githubusercontent.com/assets/7192860/19515023/5ce7b9e2-9628-11e6-9c3f-5845e1f22f5d.png)
master上这个方法被删除了？为什么？是正在开发中吗

**Comment by z-song** [comment]
@xyz8772232 应该是早期版本的功能，可以用下面的方法代替

```
$grid->rows(function($row){
    $row->action('edit');
}
```

用这种方式会更加灵活

**Comment by xyz8772232** [comment]
thanks very much. this project is helpful!
