### ISSUE TITLE
Filter查询刷新问题

### ISSUE THREAD

**Issue by tbefree** [z-song/laravel-admin#672]
grid组建里没有介绍到怎么重置filter的方法，你的DEMO的User里面有filter重置的功能，但是代码里面没有体现，我从文档里面没有找到关于filter的重置方法，能教我一下吗？

**Comment by z-song** [comment]
重置功能默认都有的啊

**Comment by tbefree** [comment]
我这里没有，那请问filter有方法调用重置吗？

**Comment by z-song** [comment]
![qq20170327-0 2x](https://cloud.githubusercontent.com/assets/1479100/24359149/0bad2658-1336-11e7-9fb6-1ef6e370fcad.png)
你说的是这个吗？

**Comment by tbefree** [comment]
是的

**Comment by z-song** [comment]
你使用的版本呢？

**Comment by tbefree** [comment]
不是很清楚，因为是别人给我的一个模板—。——，看起来应该是1.3？下面是readme里面的一些语句

Laravel 5.2
composer require encore/laravel-admin "dev-master"

Laravel 5.3
composer require encore/laravel-admin "1.3.x-dev"

Laravel 5.1
composer require encore/laravel-admin "1.1.x-dev"
```

**Comment by z-song** [comment]
你的laravel什么版本？

**Comment by tbefree** [comment]
5.3.30的

**Comment by tbefree** [comment]
还有为什么我重新按照文档composer require encore/laravel-admin "1.3.*" 说找不到文档？难道晚上会关闭下载？

**Comment by z-song** [comment]
`composer update encore/laravel-admin`试试看

**Comment by tbefree** [comment]
我重新创建了个工程，然后按文档那个做了，出现了。
