### ISSUE TITLE
关于多图上传的问题

### ISSUE THREAD

**Issue by iianpan** [z-song/laravel-admin#675]
```
    protected $casts = [
        'pics' => 'array',
    ];
```
我在表中为该字段设置自动转换，没有使用你文档中的json转换。然后在上传修改页面中就不显示图片了，应该是被判断为字符串了吧，

**Comment by z-song** [comment]
你检查一下数据库的存储格式

再去看一下cast设置成array的原理，应该能找到答案

**Comment by iianpan** [comment]
真的是很奇怪啊！
问题一：多图模式下，删除照片，同时再上传一张，就会出现有些图片没有删除的问题，而删除后直接保存，不再上传就没有问题。
问题二：是多图上传无法预览吗？为什么单图的时候可以预览，多图不能预览，我字段类型是`text`啊

**Comment by z-song** [comment]
多图可以预览，前提是这个字段的查询结果必须是一个数组，比如你的text字段就要定义一个访问器，来把存储的字符串格式化成数组输出

**Comment by Sydney710** [comment]
请教一下你说的文档是在哪? `没有使用你文档中的json转换`
个人没找到有关多文件上传的说明呢?

**Comment by z-song** [comment]
http://z-song.github.io/laravel-admin/#/zh/model-form-fields?id=%e5%a4%9a%e5%9b%be%e6%96%87%e4%bb%b6%e4%b8%8a%e4%bc%a0

**Comment by Sydney710** [comment]
3Q, 原来有个详细的文档，刚开始用laravel-admin
多图上传已经解决! 谢谢
