### ISSUE TITLE
Config

### ISSUE THREAD

**Issue by tbefree** [z-song/laravel-admin#676]
当我创建新的管理元时，出现了这个error，我该怎么处理？

Disk [admin] not configured, please add a disk config in `config/filesystems.php`.

**Comment by z-song** [comment]
使用上传需要配置，文档上都有写
http://z-song.github.io/laravel-admin/#/zh/model-form-fields?id=%e5%9b%be%e7%89%87%e4%b8%8a%e4%bc%a0
