### ISSUE TITLE
如何禁止特定刪除按鈕

### ISSUE THREAD

**Issue by Haogood** [z-song/laravel-admin#677]
請問在grid中，如何禁止特定刪除按鈕?
想呈現如圖的效果
![asking01](https://cloud.githubusercontent.com/assets/22260295/24399842/c79448e2-13e0-11e7-93e7-79edaa276382.png)

**Comment by z-song** [comment]
```php
$grid->actions(function ($actions) {
    if ($actions->getKey() % 2 == 0) {
        $actions->disableDelete();
    }
});
```
这样？

**Comment by Haogood** [comment]
感謝！

**Comment by RobinHoo1973** [comment]
@z-song 
如果重定义了actions列,好像就不可以了
