### ISSUE TITLE
使用grid时如何禁用表格顶部的新建（new）按钮？

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#68]
翻了一下源码，好像也没发现有这个方法，请问是写在哪里了？（另外发现版本更新后部分文档未更新，大神有空的话麻烦更新一下使用文档，感谢分享了这么好用的后台）

**Comment by z-song** [comment]
@windpursuer 确实没有这个方法，稍后会把这个方法加进去  谢谢反馈！

**Comment by z-song** [comment]
@windpursuer 已经支持禁用创建按钮 -> [禁用创建按钮](https://github.com/z-song/laravel-admin/blob/master/docs/zh/model-grid.md#禁用创建按钮)

谢谢支持！
