### ISSUE TITLE
form表单提交字段不在数据库中，但还要用到

### ISSUE THREAD

**Issue by jialingfei** [z-song/laravel-admin#681]
![1](https://cloud.githubusercontent.com/assets/16495170/24435543/7ab2d43e-1468-11e7-9d08-bda423be24ba.png)

**Comment by z-song** [comment]
不保存数据库：
```php
$form->ignore(['width', 'height']);
```
在saved里面可以通过request()方法获取：
```php
dd(request('width'), request('height'));
```

**Comment by jialingfei** [comment]
好的，谢谢

**Comment by panyanyany** [comment]
这个方法感觉还是很实用的，建议更新到文档中。 @z-song
