### ISSUE TITLE
编辑时候，图片img标签没有展示出来

### ISSUE THREAD

**Issue by phpfangting** [z-song/laravel-admin#687]
@z-song 
编辑信息的时候图片没有显示出来,只有url地址,发现img标签也没有

 这是我图片的设置，请大神@z-song 帮我看看
 $form->image('picture','picture');

**Comment by z-song** [comment]
http://z-song.github.io/laravel-admin/#/zh/qa?id=%e6%9b%b4%e6%96%b0%e9%9d%99%e6%80%81%e8%b5%84%e6%ba%90  看最先面

**Comment by phpfangting** [comment]
@z-song 真的解决不了，好多人都出现我这种问题，都私下问我

**Comment by z-song** [comment]
检查一下你引用的fileinput.min.js文件是什么版本

**Comment by phpfangting** [comment]
@z-song  '/packages/admin/bootstrap-fileinput/js/fileinput.min.js?v=4.3.7 应该不低吧

**Comment by z-song** [comment]
浏览器里面打开这个文件看。。。

**Comment by phpfangting** [comment]
@z-song 
这是我打开的文件
/*!
 * @copyright Copyright &copy; Kartik Visweswaran, Krajee.com, 2014 - 2015
 * @version 4.3.2
 *
 * File input styled for Bootstrap 3.0 that utilizes HTML5 File Input's advanced features including the FileReader API.
 *
 * The plugin drastically enhances the HTML file input to preview multiple files on the client before upload. In
 * addition it provides the ability to preview content of images, text, videos, audio, html, flash and other objects.
 * It also offers the ability to upload and delete files using AJAX, and add files in batches (i.e. preview, append,
 * or remove before upload).
 *
 * Author: Kartik Visweswaran
 * Copyright: 2015, Kartik Visweswaran, Krajee.com
 * For more JQuery plugins visit http://plugins.krajee.com
 * For more Yii related demos visit http://demos.krajee.com

**Comment by z-song** [comment]
问题不是找到了么， 参考我第一个回复

**Comment by phpfangting** [comment]
@z-song 谢谢你，问题已经解决

**Comment by song2013** [comment]
http://z-song.github.io/laravel-admin/#/zh/qa?id=%e6%9b%b4%e6%96%b0%e9%9d%99%e6%80%81%e8%b5%84%e6%ba%90 链接打不开了
