### ISSUE TITLE
可以在tree组件那里根据条件隐藏删除按钮吗

### ISSUE THREAD

**Issue by a648132694** [z-song/laravel-admin#688]
就是现在使用数据模型树,有个需求是有特定条件的项目不能删除,请问下怎样才能根据条件隐藏删除按钮呢

**Comment by qq175023117** [comment]
@z-song 可以在tree组件那里根据条件隐藏修改或者删除按钮吗

**Comment by Harrypoters** [comment]
同问，有人解决了吗

**Comment by fplun** [comment]
> 同问，有人解决了吗

没有找到怎么隐藏,我是直接加的判断

在控制器里写一个destory方法,就是删除按钮指向的方法

**Comment by sunxiyuan** [comment]
我也遇到这个问题，有时候模型树上的产品不希望被删除，因为删除的话会影响到已开通的产品。

**Comment by wangjingyu** [comment]
vendor模板里可以隐藏（路径vendor/encore/laravel-admin/resources/views/tree/branch.blade.php），建议继承tree类，将他的模板到自己项目中进行重写
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/8317296/206084125-2e5c996d-0bbe-4df6-bb21-0c767bc8c878.png">
