### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#689]
Hi

Is it possible to attach multiple files to any data record? Just like with pictures but pdf and other not-image files. Like this http://120.26.143.106/admin/demo/multiple-images

**Comment by z-song** [comment]
Please ref to  http://z-song.github.io/laravel-admin/#/en/model-form-fields?id=multiple-imagefile-upload

**Comment by qcol** [comment]
OK, but still have some problems :(

in Grid view I see only array, not thumbs. I can't delete pictures in form too...

![zaznaczenie_020](https://cloud.githubusercontent.com/assets/358993/24547602/fb2e97ac-1610-11e7-8221-32029773abd7.jpg)

My controller:
```
$grid->pictures()->image();
$grid->files();
```

Mutators in Model:
```
public function setPicturesAttribute($pictures)
    {
        if (is_array($pictures)) {
            $this->attributes['pictures'] = json_encode($pictures);
        }
    }

    public function getPicturesAttribute($pictures)
    {
       
        return json_decode($pictures, true);
    }```

**Comment by qcol** [comment]
OK, updated from 1.4.x-dev to 1.4.* and Griv View is OK now

**Comment by Antonelka** [comment]
Hi, 
I've got the same issue on 1.5.x-dev :(
