### ISSUE TITLE
安装问题

### ISSUE THREAD

**Issue by Cybs** [z-song/laravel-admin#693]
请问用Homestead安装laravel后安装admin，出现这个错误怎么处理？
![image](https://cloud.githubusercontent.com/assets/2275676/24534895/51f5d860-1603-11e7-8ada-eb9af5233d8a.png)

**Comment by z-song** [comment]
这个错误与laravel-admin无关

**Comment by Cybs** [comment]
是我安装的问题，重新安装解决了
