### ISSUE TITLE
图片地址的问题

### ISSUE THREAD

**Issue by nobodylikeyou** [z-song/laravel-admin#694]
$server = $server ?: config('admin.upload.host');
 $src = trim($server, '/').'/'.trim($path, '/');
会把admin.upload.host右边的斜杠过滤造成图片无法显示。或者我这么问，是不是我配置的admin.upload.host有问题
我的admin.upload.host配置的是’/upload/‘

**Comment by z-song** [comment]
应该是左边的去掉了吧，你把host设置成完整的url试试看
