### ISSUE TITLE
vendor/encore/laravel-admin/src/Tree.php  cann`t  return false

### ISSUE THREAD

**Issue by chenkaizong** [z-song/laravel-admin#696]
if(confirm("{$confirm}")) {
                $.post('/{$this->path}/' + id, {_method:'delete','_token':LA.token}, function(data){
                    $.pjax.reload('#pjax-container');
                    toastr.success('{$deleteSucceeded}');
                });
            }
only can success,   but I want  toastr.error().....

**Comment by shenglin-php** [comment]
I want too
