### ISSUE TITLE
我想找某一个页面的视图文件 

### ISSUE THREAD

**Issue by purrck** [z-song/laravel-admin#702]

**Comment by purrck** [comment]
![image](https://cloud.githubusercontent.com/assets/24643608/24575002/00a1c7e6-16ce-11e7-8b5b-15c30bb4c77a.png)
我就想在这页面加些标注

**Comment by z-song** [comment]
laravel-admin自带的图表组件将会移除，请不要再使用

可以参考这里实现自己的图表 https://gist.github.com/z-song/15078827726bfae34dcda5935b02697a

**Comment by purrck** [comment]
进不去·······
