### ISSUE TITLE
图片上传时  过渡动画太不明显，不知道我该怎么可以修改它，或者改变上传时候Input的高度使效果明显些

### ISSUE THREAD

**Issue by purrck** [z-song/laravel-admin#704]
![image](https://cloud.githubusercontent.com/assets/24643608/24577590/2f9c0f22-1703-11e7-997f-fde18c2da583.png)

**Comment by yugihuang** [comment]
这个是bootstrap-fileinput控件里定义的，相关的样式
.file-thumb-loading {
    background: url(../img/loading.gif)center center no-repeat content-box!important;
}
最简单的方法是替换掉这个gif图(public/packages/bootstrap-fileinput/img/loading.gif)，
或者覆盖这个css类的样式
