### ISSUE TITLE
图片上传的问题

### ISSUE THREAD

**Issue by tbefree** [z-song/laravel-admin#705]
我把这个程序放到阿里云上测试的时候，发现图片上传不了，以下是出现的error，请问该怎么解决？

 ErrorException In /var/www/carclub/vendor/league/flysystem/src/Adapter/Local.php line 129 :

file_put_contents(/var/www/carclub/public/upload/image/2017-03-28 22-14-56屏幕截图.png): failed to open stream: Permission denied

**Comment by yangzuwei** [comment]
Permission denied  权限不足啊
