### ISSUE TITLE
global label name

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#706]
Hi

First of all: I love this tool, it is amazing - very good job! :1st_place_medal: 

Question: Is it possible to set any global translation column_name -> label_name? 

Many column names repeats, so everytime you need to set for example:
`$form->display('updated_at', 'Updated At');`

maybe any settings file to set it global? "update_at" = "Updated At"?

**Comment by edwinhuish** [comment]
```$form->display('updated_at', trans('updated_at'));```

**Comment by qcol** [comment]
OK, but I mean You can write just:
`$form->display('updated_at');`
and proper label will be automagically added

**Comment by yugihuang** [comment]
Try to modify Encore\Admin\Form\Field\Display and rewrite that method formatLabel()
