### ISSUE TITLE
数据从API中获取，请问搜索这块该怎么做呢？谢谢

### ISSUE THREAD

**Issue by phpfangting** [z-song/laravel-admin#707]
我们的model层是调用的Java接口，根据您的demo都能做出来，但是查询的时候，不知道该怎么做了，请大神
@z-song 指点

**Comment by edwinhuish** [comment]
我觉得你可以参考这个： http://120.26.143.106/admin/movies/in-theaters

**Comment by phpfangting** [comment]
@edwinhuish 
就是参考那个，但是没有搜索功能

**Comment by edwinhuish** [comment]
无非就是修改model，这方面看laravel文档吧，我也没有做过。

**Comment by z-song** [comment]
思路都是一样的 在model里面写方法覆盖掉Eloquent的方法，比如接受查询条件就覆盖where方法，更新就覆盖update方法，插入就覆盖insert方法，具体的情况你要会举一反三
