### ISSUE TITLE
File delete doesn't work

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#709]
I can't delete uploaded files. I have uploaded file: 
![zaznaczenie_021](https://cloud.githubusercontent.com/assets/358993/24586044/a2b31678-1798-11e7-95fa-23ba648f6d4d.jpg) (doesn't work pdf preview but that's another topic)

When click trash icon, file disappears (looks correct), then save form and see message (updated succesfully). But when back to form editing - everything is back in place. 

Doesn't work neither multipleFile nor one file form type.

"encore/laravel-admin": "1.4.x-dev"

**Comment by rizaergun** [comment]
look here #666

**Comment by qcol** [comment]
It works! Thanks!
