### ISSUE TITLE
删除如何回调

### ISSUE THREAD

**Issue by felixjing** [z-song/laravel-admin#713]
删除某个记录后，还需要其他操作该如何搞。 有没有类似表单saving和saved回调的方法

**Comment by windyson2008** [comment]
两种解决方案：
1，比较麻烦，模拟 `Encore\Admin\Form.php` 的 saving 一些列方法，扩展添加注册 destory 回调。
2，比较简单，拷贝 `Encore\Admin\Controllers\ModelForm.php` 到你工程目录下，然后修改：
```
...
    public function destroy($id)
    {
        if ($this->form()->destroy($id)) {
            ↓↓↓
            debug(‘something here’)
            ↑↑↑
            return response()->json([
                'status'  => true,
                'message' => trans('admin::lang.delete_succeeded'),
            ]);
        } else {
            ↓↓↓
            debug(‘something here’)
            ↑↑↑
            return response()->json([
                'status'  => false,
                'message' => trans('admin::lang.delete_failed'),
            ]);
        }
    }
...
```
然后，在你的 `Controllers` 中用上面修改好的 `ModelForm` 性状来覆盖原有的。

**Comment by z-song** [comment]
在模型里面设置删除回调，模型添加方法：
```php
    public static function boot()
    {
        parent::boot();

        static::deleted(function ($model) {
            // 在这里添加其他逻辑
        });
    }
```

**Comment by amun1303** [comment]
The latest version this solution doesn't work. I don't know why
``php
public static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
        static:: deleted(function ($model) {
            **dd($model);
            exit();**
            $speaker = Speaker::find($model->speaker_id);
            $speaker->total_track = Track::where('speaker_id', '=', $model->id)->count();
            $speaker->save();
        });
    }
``
