### ISSUE TITLE
How could I set width of column in grid?

### ISSUE THREAD

**Issue by chianhsieh** [z-song/laravel-admin#715]
We can use $grid->xxx() or 

$gid->actions( function($actions) { 
  // blahblah 
});

to set up a column in grid.
If I want to assign the fixed width to the column, what should I do?

Thank you.

**Comment by windyson2008** [comment]
Please try to read the link below. You can find the solution. GOOD LUCK:
@[Extend the column](http://z-song.github.io/laravel-admin/#/en/model-grid-column?id=extend-the-column)

**Comment by qcol** [comment]
with **extending column** you can change only content of column (inside <td></td>), but what to change column width? I have similiar question...

**Comment by git123efasdfoojo** [comment]
what is wrong? (file App/Admin/Routes.php)

The last route is always executed (2 route in the example)

I want to show specific drivers for each function

someone can help me?

I use version 1.4

**Comment by windyson2008** [comment]
@qcol 
Because AdminLTE has no css for grid. You have to define it by yourself.

Here is a simply sample:
> Step1: add a $width property into Admin\Grid\Column.php and generate a getter\setter for it.
```
protected $width = '1em';

    /**
     * @return string
     */
    public function getWidth()
    {
        return $this -> width;
    }

    /**
     * @param string $width
     */
    public function setWidth($width)
    {
        $this -> width = $width;
        return $this;
    }
``` 

> Step2: add a funtion into Admin\Grid.php for getting a use-width-feature flg 
```
    public function renderColumnGroupOrNot()
    {
        return $this->option('useWidth');
    }
```
> Step3: in your contorller
```
    protected function grid()
    {
        ...
        $grid -> option('useWidth', true);
        $grid -> id('id')->setWidth('10em') -> sortable();
        ...
    }
```

> Step4: in your table.blade.php
```
 <table class="table table-hover">
           ↓↓↓ render colgroup start
            @if($grid->renderColumnGroupOrNot())
                @foreach($grid->columns() as $column)
                    <colgroup style="width: {{$column->getWidth()}}"></colgroup>
                @endforeach
            @endif
           ↑↑↑ render colgroup end
            <tr>
                @foreach($grid->columns() as $column)
                <th>{{$column->getLabel()}}{!! $column->sorter() !!}</th>
                @endforeach
            </tr>

            @foreach($grid->rows() as $row)
            <tr {!! $row->getHtmlAttributes() !!}>
                @foreach($grid->columnNames as $name)
                <td>{!! $row->column($name) !!}</td>
                @endforeach
            </tr>
            @endforeach
        </table>
```

**Comment by z-song** [comment]
In lastest dev version:
```php
$grid->created_at()->setAttributes(['width' => ' 300px']);
```

**Comment by chianhsieh** [comment]
Hi @z-song , 

May I know which version support this function?
Could you give me version number?

Thank you

**Comment by augustinex80** [comment]
1.4.2这些方法setAttributes，style不在Column.php中。可如下解决：

`$grid->user('用户')->name()->display(function ($val) {
                    return '<div style="width: 200px;">' . $val . '</div>';
                });`
生成的html略显丑陋。
还有个方法叫value。功能是一样的。
