### ISSUE TITLE
Allow nav links outside of admin urls

### ISSUE THREAD

**Issue by bryce13950** [z-song/laravel-admin#717]
I am trying to add some links to the navigation that would take the user to a page outside of the admin into a new tab. Is there any chance that the navigation could be revised a bit to allow more options, such as target, and urls outside of the admin prefix?

**Comment by Fisiu** [comment]
You could create a new model which inherits from `Encore\Admin\Auth\Database\Menu`, then create proper db table for it and finally update `config/admin.php` regarding:
```php
// Menu table and model.
'menu_table'  => 'admin_menu',
'menu_model'  => Encore\Admin\Auth\Database\Menu::class,
```
