### ISSUE TITLE
HasMany 表单中有图片字段时，会出现所有图片变成一样的bug。效果，原因如下

### ISSUE THREAD

**Issue by smartymoon** [z-song/laravel-admin#719]
出问题的效果：
![_20170405105655](https://cloud.githubusercontent.com/assets/12489528/24687942/399cd80a-19ef-11e7-917f-1c4c5fa4ff03.png)

原因是File.php中，Jquery 选择器没有对多张图片做区分
![_20170405105733](https://cloud.githubusercontent.com/assets/12489528/24687926/2008fd74-19ef-11e7-92f1-33933ccbad0a.png)
![_20170405105535](https://cloud.githubusercontent.com/assets/12489528/24687931/246ef54e-19ef-11e7-8d54-7429f7959e06.png)

**Comment by jonny77** [comment]
虽然没有用过这个框架 不过 我觉得 可以改下代码  $("input{$this->getElementClassSelector()}") to  
$("input{$this->getElementClassSelector()}[]")

**Comment by edwinhuish** [comment]
@jonny77 不是这个原因。

确实有这个问题，@smartymoon 提个PR给 @z-song 吧。

**Comment by liushaoxing110** [comment]
您好，你的QQ是多少，关于商品规格和商品属性有一些问题咨询一下，谢谢

**Comment by HuangZhanBo** [comment]
你好 请问 如何解决这个问题呢？

**Comment by HuangZhanBo** [comment]
刚接触这个框架，对代码还不是非常的了解 只能用一个很傻瓜纯js的办法解决这个问题 
改成下面这个样子
$this->script = <<<EOT
        
        //修改HasMany 表单中有图片字段时，会出现所有图片变成一样的bug
        $("input{$this->getElementClassSelector()}").each(function(){
           var name = $(this).attr('name'); 
           var removeClassName =("{$this->getElementClassSelector()}".split('.'))[1];
           $("input{$this->getElementClassSelector()}[name='"+name+"']").fileinput({$options});
           $(this).removeClass(removeClassName);
           return false;
        });

EOT;

**Comment by z-song** [comment]
已修复 请更新
