### ISSUE TITLE
saved里面再次修改数据库

### ISSUE THREAD

**Issue by jialingfei** [z-song/laravel-admin#724]
$form->saved(function(Form $form){
    //在这个里面重新对数据库的某个字段进行修改

});

**Comment by windyson2008** [comment]
想问啥呀~？

**Comment by jialingfei** [comment]
就是在saved的里面怎么再次修改数据库里值，

**Comment by yugihuang** [comment]
我的方法是有点蠢
            $form->saving(function (Form $form) {
                $media = $form->model();
                if (Input::hasFile('store_path')) {
                    $image = Input::file('store_path');
                    $media->mime = $image->getClientMimeType();
                    $media->file_name = $image->getClientOriginalName();
                    $media->size = $image->getClientSize();
                }
            });

**Comment by edwinhuish** [comment]
方法不错，就是这样做的。 @yugihuang

**Comment by git123efasdfoojo** [comment]
hi!
can help?

https://github.com/z-song/laravel-admin/issues/723
