### ISSUE TITLE
Contributing to the framework

### ISSUE THREAD

**Issue by avifatal** [z-song/laravel-admin#725]
Hi,
I would like to add some feature to the framework.
The development is stuck , can you please explain how to do it?
Thanks

**Comment by windyson2008** [comment]
simply to say:
Step 1: fork this project
Step 2: make a feature branch
Step 3: coding
Step 4: commit & push to your own forked project
Step 5: do "New pull request"
detail information: see @[Learn Git # Making a pull request](https://www.atlassian.com/git/tutorials/making-a-pull-request)

**Comment by avifatal** [comment]
@windyson2008 , I know how to contribute, but I dont know how to contibute from my app.
Im using composer obviously, and the source code of laravel-admin is under vendor folder.
How can I aim that this folder vendor/laravel-admin will be from my forked repo.
Thanks

**Comment by edwinhuish** [comment]
Google
