### ISSUE TITLE
提个建议

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#735]
能否实现form表单填表时，选择不同的数据类型能够动态展示不同的数据表格？

**Comment by edwinhuish** [comment]
不同的数据类型？对于html来说所有数据类型都是string

**Comment by yugihuang** [comment]
@windpursuer 能否举个例子

**Comment by windpursuer** [comment]
不好意思，表达不清晰。就是说有一个新增用户信息的form，但选择男性时出现指定的文本框进行填写，选择女性时则出现不同的文本框进行填写。 @edwinhuish @yugihuang @z-song

**Comment by edwinhuish** [comment]
完全可以自定义扩展，写js触发男性/女性表单的显示和隐藏即可。

**Comment by z-song** [comment]
这属于自定义的需求，自己实现比较好，扩展field或者嵌入js实现吧
