### ISSUE TITLE
如何通过curl认证访问admin路由组中的路由

### ISSUE THREAD

**Issue by wonderful60** [z-song/laravel-admin#738]
![qq20170410-171916](https://cloud.githubusercontent.com/assets/2291007/24854961/b11af0f2-1e12-11e7-8626-1e3390550177.png)
参照https://laravel.io/forum/02-18-2015-l-5-how-to-autehnticate-user-on-curl 的方法无效，效果如上图

**Comment by z-song** [comment]
看下面的评论，在使用basic auth的认证路由上才可以使用curl --user的方式，laravel-admin并不是使用basic auth作为认证中间件

**Comment by wonderful60** [comment]
好的，谢谢
