### ISSUE TITLE
覆盖同名具名方法

### ISSUE THREAD

**Issue by miyazawatomoka** [z-song/laravel-admin#744]
如果定义了route
`Route::resource('users', 'UserController')`

 再按文档中
> Add a route in app/Admin/routes.php  

定义`$router->resource('users', UserController::class);`
会覆盖掉具名方法，如`users.index`,`users.show`...

**Comment by z-song** [comment]
不太明白你的意思  两个定义的效果不是一样的吗，为什么要定义两遍

**Comment by yugihuang** [comment]
可以看一下有关资源路由的文档，按你项目的需要命名资源路由或者只使用部分
http://d.laravel-china.org/docs/5.4/controllers#resource-controllers

**Comment by z-song** [comment]
还是不明白你的意思，为什么定义了`Route::resource('users', 'UserController')`之后，再按文档定义`$router->resource('users', UserController::class);`,不是重复了吗

**Comment by miyazawatomoka** [comment]
Laravel并不会通过namespace生成如`admin.users.index`这样的路由.
通过重新命名解决了问题.
感谢!
