### ISSUE TITLE
form表单图片删除js报错

### ISSUE THREAD

**Issue by 18811409790** [z-song/laravel-admin#747]
laravel-admin 编辑的时候的form表单里的图片删除时js报错，laravel.log里面没有错误日志，我用的是laravel5.3 admin是1.3.x-dev编辑的时候换图片时原来的图片也不会替换掉，而是增加了一张图片

**Comment by z-song** [comment]
具体的错误信息呢？

**Comment by 18811409790** [comment]
![image](https://cloud.githubusercontent.com/assets/16815562/24939467/147fa936-1f70-11e7-8a48-23b2811356bc.png)

**Comment by 18811409790** [comment]
还有用了wangeditor了，然后按照文档在bootstrap.php里面加了extend('editor',...)。在删除图片的时候会先弹出一个alert说不能重复加载wangeditor.js但是我去掉那个的话编辑器长得就不好看了，所以这差不多算两个问题吧但都是编辑时点击删除图片的时候

**Comment by z-song** [comment]
点删除的时候看看浏览器network   看下请求返回的内容是什么

**Comment by 18811409790** [comment]
network里面有一堆js但是edit返回的事

**Comment by 18811409790** [comment]
![Uploading image.png…]()

**Comment by 18811409790** [comment]
![image](https://cloud.githubusercontent.com/assets/16815562/24940877/9dd3a734-1f78-11e7-8b1d-92aa722e1fcd.png)

**Comment by z-song** [comment]
第一张截图的network点开看一下错误

**Comment by 18811409790** [comment]
没看到控制台哪里有错误
![image](https://cloud.githubusercontent.com/assets/16815562/24947145/47078964-1f98-11e7-9749-83859b2468c6.png)

**Comment by wanghuanyi** [comment]
这个问题解决了吗， 我还是报这个错误

**Comment by akazhuk** [comment]
我也是这个报错。。
