### ISSUE TITLE
用户设置页面 删除头像错误

### ISSUE THREAD

**Issue by zanjs** [z-song/laravel-admin#749]
/admin/auth/setting

指向的 url  是  /admin/1

**Comment by xinuxZ** [comment]
遇到同样的问题，超级管理员登录后，可以删除其他普通管理员的头像。普通管理员登录后，点击删除头像的按钮出错，但是可以再添加一张，进行覆盖

**Comment by yugihuang** [comment]
这个问题我发现是通过点击右上角头像里的设置之后才会出现，
因为该设置的url为admin/auth/setting，而在左边菜单里进入用户设置里的url为admin/auth/users/1/edit。
通过Encore\Admin\Form\Field\UploadField这个trait发现$defaultOptions['deleteUrl'] = $this->form->resource().'/'.$this->form->model()->getKey();里是使用Encore\Admin\Form里的resource方法，因为url的层数不一样，所以前者的deleteUrl就会是admin/1，而后者则是admin/auth/users/1

**Comment by libybai** [comment]
兄弟们，这个问题解决了吗

**Comment by libybai** [comment]
@z-song 兄弟，这个问题怎么解决？

**Comment by sessionliang** [comment]
这个问题解决了吗？怎么现在还有
