### ISSUE TITLE
建议权限分配操作改用勾选的方式

### ISSUE THREAD

**Issue by windpursuer** [z-song/laravel-admin#75]
之前在tp的一个项目看到类似的方式，感觉会比较直观好用，大神可考虑下一版本改用此方式

**Comment by z-song** [comment]
@windpursuer  之前考虑过这个方式，但是发现使用checkbox来显示选项的时候，由于选项内容长短不一，看上去会不整齐，并且考虑到这种操作不会太频繁，所以就没有使用这种方式。
