### ISSUE TITLE
上传mp3文件再次编辑的时候显示为图片

### ISSUE THREAD

**Issue by draguo** [z-song/laravel-admin#750]
form 中
```
$form->file('music','music');
```
新建选择时是正确的
![](http://i1.piimg.com/567571/730f09462bd2c4ed.png)
二次编辑时就会变成
![](http://i2.muimg.com/567571/46ac7d06a14e74c1.png)
请问是需要做什么设置吗？

**Comment by z-song** [comment]
fileinput组件不会自动检测文件类型，要手动指定预览类型
```php
$form->file('music','music')->options(['initialPreviewFileType' => 'audio']);
```

`initialPreviewFileType`配置的可选值参考http://plugins.krajee.com/file-input#option-previewsettings
