### ISSUE TITLE
model-grid model-form

### ISSUE THREAD

**Issue by kingofzihua** [z-song/laravel-admin#751]
起初用这个感觉 ***model-grid*** ***model-form*** 太好用了，但是随着用，感觉这个项目有点太大了，各方面有点冗余，很多是我所不需要的，不知老大是否考虑一下将 ***model-grid*** ***model-form*** 单独拿出来做维护。

**Comment by edwinhuish** [comment]
貌似最主要就是这两个了吧?还有其他什么多余的?
