### ISSUE TITLE
form 元件 select 選擇後，按“X”，無法刪除，解法，必須設定 “placeholder”

### ISSUE THREAD

**Issue by yang5664** [z-song/laravel-admin#752]
![screen shot 2017-04-14 at 3 19 44 pm](https://cloud.githubusercontent.com/assets/5953010/25036424/53a9cb98-2126-11e7-8950-4043959d36c2.png)
```
allowClear

This option only works when the placeholder is specified.
```
![screen shot 2017-04-14 at 3 24 58 pm](https://cloud.githubusercontent.com/assets/5953010/25036462/9bc1994c-2126-11e7-91eb-b3337a001848.png)

**Comment by yugihuang** [comment]
这个issue我觉得应该发给select2，请见https://select2.github.io/options.html#allowClear
