### ISSUE TITLE
编辑表单时，图片怎么删除

### ISSUE THREAD

**Issue by Decent-Dexter** [z-song/laravel-admin#753]
删除了提交是没有效果的，原因是仅仅删除了预览图？
实际提交的东西是空

**Comment by Decent-Dexter** [comment]
@z-song It works!感谢你的回复，这个是什么原因呢？我之前看过Form.php里面update的代码，以及点击删除按钮和点击提交按钮的请求数据，却找不到删除的实现，最后只能自己改写控制器里面的update方法来单独处理删除的操作，现在这样就方便多了

**Comment by z-song** [comment]
中间件`ConvertEmptyStringsToNull`是在Laravel 5.4.12新加入的，对输入的空数据格式化成了null，不兼容laravel-admin的删除图片逻辑，所以只好先注释掉来解决这个问题。

**Comment by Decent-Dexter** [comment]
@z-song 我看到了，是不是可以考虑把 MultipleFile 里面 prepare 的 has 换成 exists，这个函数只判断键值

**Comment by imageslr** [comment]
@ba6yface 你好，我现在image删除图片的时候也遇到了这个问题。Laravel版本5.6，我已经注释了那个中间件，但是后端就根本收不到`image`字段的参数值，请问你是怎么解决的？

**Comment by ba6yface** [comment]
@imageslr 我当时应该是5.4版本，package版本是1.4.2，就是注释中间件就可以了

**Comment by imageslr** [comment]
@ba6yface 我注释中间件以后也不行，主要是后端我打印`request`以后，就收不到那个文件名的表单参数。如果我选择一个文件的话，是可以收到一个`UploadedFile`类型的对象的。

我现在是设置该Field为`removable`，这样删除图片的时候就直接和后端通信、设置该字段了。
