### ISSUE TITLE
请问1对1关联如何删除?谢谢大家

### ISSUE THREAD

**Issue by jiayouzl** [z-song/laravel-admin#757]
1对对的显示,修改都没问题,但现在删除的时候只会删除主表的信息,关联表不会删除,谢谢大家~

**Comment by edwinhuish** [comment]
在mysql里设置外键约束。

**Comment by jiayouzl** [comment]
恩感谢,我以为代码就能实现,谢谢~

**Comment by z-song** [comment]
可以通过监听模型的删除事件来实现级联删除。

ref https://laravel.com/docs/5.4/eloquent#events
