### ISSUE TITLE
jQuery 版本与fullcalendar冲突

### ISSUE THREAD

**Issue by yatong2008** [z-song/laravel-admin#759]
在项目中引入了https://github.com/maddhatter/laravel-fullcalendar/ 之后，
发现冲突，第一次进入含有fullcalendar的页面无法载入calendar，后来发现是jQuery问题，更新了index.blade.php中的jQuery到3.2后calendar显示正常，但是其他页面中的jQuery有些地方无法正常显示，例如multiselect的一些地方无法正常的显示下拉菜单。

之后试过其他方法例如恢复成默认jQuery2.1.4，调整fullcalendar js和 jQuery载入顺序之类不过依然没法解决，期间还试过添加jQuery migrate，添加之后dropdown可以实现，但是造成了新的问题，在edit页面里面submit的时候会有422 unprocessed entity，并且页面不跳转。
请问z-song是否有办法jQuery升级到3以后的版本能使项目正常运行？谢谢

**Comment by z-song** [comment]
框架内置的jQuery集成自AdminLTE，参考这个页面 https://almsaeedstudio.com/themes/AdminLTE/pages/calendar.html

这个页面的jQuery版本是2.2.3，fullcalendar的版本是v2.2.5，功能表现正常

**Comment by yatong2008** [comment]
@z-song 谢谢您的回答，我尝试了几天以后还是兼容性不好，我准备像LTE一样的导入fullcalendar，但是发现在vendor\encore\laravel-admin\assets\plugins里面好像没有导入fullcalendar库，我还不是太熟悉配置文件这些，请问我该如何导入可以像AdminLTE实现那样的效果呢？

**Comment by z-song** [comment]
在`app/Admin/bootstrap.php`里面导入静态资源
