### ISSUE TITLE
如果数据库id类型是char类型怎么办？

### ISSUE THREAD

**Issue by gaofei123123** [z-song/laravel-admin#76]
我们的项目数据id用的都是uniqueid作为数据id，结果导致生成的内容被强制转整了

**Comment by gaofei123123** [comment]
我现在的做法是在模型当中声明了 getIdAttribute 方法，然后返回原值来规避这个问题

**Comment by z-song** [comment]
@gaofei123123 请问是在grid中还是form中？

**Comment by gaofei123123** [comment]
grid里面

**Comment by gaofei123123** [comment]
提交报错后报错信息内显示的默认首页title页面，然后刷新页面的时候就只显示一个顶部的title信息，console.log的显示是加载资源错误，network显示的500报错，除了这些就没有任何报错信息了，感觉好崩溃

**Comment by z-song** [comment]
请问有没有更详细的信息，或者截图？

**Comment by gaofei123123** [comment]
我重装了一遍后一切正常，后来重复了一遍之前的操作：
1. 通过 `admin/auth/menu`添加了一个中文title的导航，比如是 `用户` ，url为 `members`
2. 再新建一个导航，父级选择 `用户列表` ,url为 `members/list` 提交的时候就会出 warning，但是warning里显示的是页面的一部分，当这个时候就不能再修改点什么都没反应了
3. 最后再刷新页面的时候就只能显示出默认模版样式的顶部蓝条那块
4. 我现在的结局办法是直接命令行输入  `php artisan admin:install` 重置了一下，但是这样的话之前成功添加的 `用户列表` 那一条就没有了 回归到初始状态
5. 现在还发现的问题是通过$grid添加的filter进行条件筛选的时候点击搜索会出现`warning:undifined`但是地址栏的参数变了，刷新一下才能正常显示出要搜索的结果
6. 我现在用的版本是 5.3的那版

**Comment by z-song** [comment]
重复了一下你的操作，没有重现问题，可以看一下异常log，把信息贴出来看看

**Comment by z-song** [comment]
close issue
