### ISSUE TITLE
How could Grid get the grandparent's content?

### ISSUE THREAD

**Issue by chianhsieh** [z-song/laravel-admin#760]
Hello,

if I have 3 Eloquent models which are
```
// it has a column called "title"
class Board extends Model {
}
```
```
class Article extends Model {
  public function board() {
    return $this->belongsTo(Board::class);
  }
}
```
```
class Comment extends Model {
  public function article() {
    return $this->belongsTo(Article::class);
  }
}
```

In Comment grid, how could I display the Board's "title"  ?

For example, here is what I want ( but it can't work actually ) 
```
Admin::grid(Comment::class, function (Grid $grid) {
  // How could I make it work? => display the "title" in Board class
  $grid->article()->board()->title();

  // How could I make it work? => display the "id" and "title" in board using display function
  $grid->article()->board()->display(function ($board) {
    echo $board['id'] . " and " . $board['title'];
  });
}
```

Many thanks.
Eric

**Comment by edwinhuish** [comment]
$grid->model()->with('article.board')

**Comment by chianhsieh** [comment]
Hello @edwinhuish ,

The code you provided works well but there is no any output.

If I want to output the column "title" in board, what should I do?
It looks like 

$grid->model()->with('article.board')->title()

cannot work.

Thank you.

**Comment by edwinhuish** [comment]
Try

```
Admin::grid(Comment::class, function (Grid $grid) {
    $grid->model()->with('article.board');

  // How could I make it work? => display the "title" in Board class
  $grid->column('article.board.title');
..........
}
```

**Comment by isometriq** [comment]
I have the same kind of structure.
The call `$grid->model()->with('country.countryRegion')` works indeed, i can prove relations are loaded with this:
```
$grid->model()->collection(function($collection){
    dump($collection);
    return $collection;
});
```
However, data is not available in the column, by using this
`$grid->column('country.countryRegion.name', 'Region');`
..it stays blank

**Comment by isometriq** [comment]
Oh, I see now, camel case is converted to underscored probably by laravel array transformer. Can prove with this:
```
$grid->column('country.countryRegion.name', 'Region')->display(function($value) {
    dump($this);
    return '...';
});
```
So I would have to use it like this:
```
$grid->column('country.country_region.name', 'Region');
```
But this outputs an array dump (the content of `country.country_region`)
So I have no choice to use this:
```
$grid->column('country.country_region.name', 'Region')->display(function($value) {
    return $value['name'];
});
```
Now it works

NOTE: I had other issues with camel case, see issue #946
