### ISSUE TITLE
pjax reload后JS无法一起reload，造成部分功能出现问题

### ISSUE THREAD

**Issue by kevin1018** [z-song/laravel-admin#761]
这个问题针对laravel-admin 1.4版本；
一个页面上有一个Grid，有多个select filter，select filter会用ajax动态加载数据。这里会监听这个filter的change事件。这里会加载Grid\Filter\Field\Select中的一段JS代码。

从这个页面，可以跳转到修改页面，修改页面也包括多个select filter，这个请求是通过pjax完成的，执行reload后，会加载Form\Field\Select中的一段JS代码。此时上次在Grid页面注册的change事件不会被清除。

新加载的页面上的select element的class id与老页面上的相同，因为对应的是model中的同一个字段。于是造成这个element现在会有两个change事件。很显然其中一个是不应该出现的。

我目前没有想到很好的解决办法，临时在script.blade.php内增加了
```
$(document).off('change');
```
临时解决。

是否有好的方法能够解决这个问题，谢谢

**Comment by hare2011** [comment]
我觉的应该是新加载的页面select change事件绑定到老页面上。

**Comment by ChitaGideon** [comment]
我也遇到pjax 的问题。

自己定义的一些组件 首次进去没法用，
必须得手动刷新下页面才能正常使用，

怎么才能全局禁掉pjax，把laravel-admin.js 从全局模板里删掉
