### ISSUE TITLE
Use multipleSelect to save an array into a json column.

### ISSUE THREAD

**Issue by peacemoon** [z-song/laravel-admin#762]
I'm trying to use a multipleSelect to add/edit an array into a json column. For showing, I have no problem using the following code

````
$form->multipleSelect('features')->ajax('/'.config('admin.prefix').'/api/features');
````

But when I click on `Submit`,  I have an `Array to string conversion`error because the `MultipleSelect` field returns an array and my `json` column requires a `String` value.

Anyone has any suggestion?

**Comment by edwinhuish** [comment]
getXxxxAttribute and  setXxxxAttribute

**Comment by peacemoon** [comment]
@edwinhuish what do you mean? Can you give me more detail?

**Comment by peacemoon** [comment]
Ok, I think you mean this https://laravel.com/docs/5.4/eloquent-mutators, will have a look.
