### ISSUE TITLE
列表无法设置每一列的宽度

### ISSUE THREAD

**Issue by leyix** [z-song/laravel-admin#766]
表单可以设置表单的宽度，但是列表无法设置每一列的宽度，希望增加这个功能

**Comment by z-song** [comment]
`$grid->column('username')->setAttributes(['style' => 'width:200px;']);`
or
`$grid->column('username')->style('width:200px;');`

**Comment by chenzi2015** [comment]
好像还是不行, 提示"Method setAttributes does not exist."
