### ISSUE TITLE
可以自己命名路由吗

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#77]
$router->post('comments/block/{$id}', 'CommentController@block')->name('admin.comments.block');

这样会报错：
![image](https://cloud.githubusercontent.com/assets/7192860/19754786/3becead4-9c43-11e6-9d4c-eca8ea0b913f.png)

**Comment by z-song** [comment]
`app('admin.router')`是对laravel路由的包装，不能直接使用，如果需要使用系统路由的话，可以从包装里面拆出来使用：

在`app/Admin/routes.php`添加

```php
Route::group([
    'prefix'        => config('admin.prefix'),
    'namespace'     => Admin::controllerNamespace(),
    'middleware'    => ['web', 'admin.auth', 'admin.pjax'],
], function ($router) {

    $router->post('comments/block/{$id}', 'CommentController@block')->name('admin.comments.block');

});
```

**Comment by xyz8772232** [comment]
好的，多谢
