### ISSUE TITLE
我的操作日志突然都无法显示了  数据库也没有记录

### ISSUE THREAD

**Issue by purrck** [z-song/laravel-admin#773]
![image](https://cloud.githubusercontent.com/assets/24643608/25159628/9cf39c50-24e3-11e7-865f-6d3f0beb4a0e.png)

**Comment by z-song** [comment]
`config/admin.php`里面加一项配置，参考 https://github.com/z-song/laravel-admin/blob/1.4/config/admin.php#L94

**Comment by purrck** [comment]
好了  谢谢
