### ISSUE TITLE
本地项目迁移到服务器时

### ISSUE THREAD

**Issue by hzysoft** [z-song/laravel-admin#774]
本地项目是基于假域名的虚拟站点，laravel-admin运行正常

但迁移到一个服务器，Admin:url不正常，情况如下：
服务器上：整个laravel项目根目录是在其他站点的子目录下面的，
Admin:url() 生成的url都是相对目录，而且url字符串头带“/”
所以admin的一些view里面的url，都指错到了根站点
而实际想要的效果是在站点域名的子目录里。

我尝试修改了Admin:url() 返回时加上 url('/') 。但造成打开登录页面反复重定向，浏览器打开失败。

请问作者大神，如何解决这个问题？

急！盼复！

**Comment by z-song** [comment]
你是想把这个项目挂载在已有域名的子目录下？

把它设置成独立站点，然后在主域名的服务器添加配置，代理这个目录的访问到前面配置的独立站点。

**Comment by hzysoft** [comment]
感谢您的回复，看来只有设置成独立站点才能比较好的解决问题。
