### ISSUE TITLE
From 表单的结构有办法控制吗？

### ISSUE THREAD

**Issue by ZeiyThink** [z-song/laravel-admin#776]
form表单想在一行显示多个字段，有办法实现吗？

**Comment by ZeiyThink** [comment]
http://z-song.github.io/laravel-admin/#/zh/model-form-field-management
通过自定义组件，把整个表单写到一个view里，调整view里的html代码，然后当成一个字段输出，来达到自己调整表单布局的目的，笨办法

**Comment by edwinhuish** [comment]
@ZeiyThink  现在无论是form还是grid，页面元素都是以行构建的，你可以继承Field，然后自己构建自己想要的分布方式，具体可以参考range input。
