### ISSUE TITLE
为新增页面和编辑页面增加js代码遇到的问题。

### ISSUE THREAD

**Issue by hare2011** [z-song/laravel-admin#779]
从源码和文档来看  admin::script  or admin::js 增加的代码会放到 pjax-container 容器的外面。是否提供一个方法可以直接把js或者css代码放肉pjax-container容器。
我要实现在创建和编辑页面里面，点击选择动态类型时，下面的视频和图片可以切换显示。

**Comment by zzDylan** [comment]
我也遇到这个问题。。。。现在是直接手动在视图中加<script>标签
