### ISSUE TITLE
请问支持mongodb吗

### ISSUE THREAD

**Issue by wl496928838** [z-song/laravel-admin#781]
请问支持mongodb吗

**Comment by z-song** [comment]
支持，需先安装https://github.com/jenssegers/laravel-mongodb

**Comment by wl496928838** [comment]
[Symfony\Component\Debug\Exception\FatalThrowableError]  
  Call to a member function compileTruncate() on null

**Comment by wl496928838** [comment]
php artisan admin:install 执行后报错

laravel 5.4

已安装您说的 "jenssegers/mongodb": "^3.2",

**Comment by z-song** [comment]
安装过程会创建几张系统表，因为有联表操作只能使用mysql，后续的其它功能模块支持mongodb

**Comment by qingdi** [comment]
确定支持吗？

**Comment by qingdi** [comment]
> 支持，需先安装https://github.com/jenssegers/laravel-mongodb

我测试了下，报错了啊？安装后需要做什么操作呢？
