### ISSUE TITLE
mongodb报错

### ISSUE THREAD

**Issue by wl496928838** [z-song/laravel-admin#782]
php artisan admin:install 执行后报错

[Symfony\Component\Debug\Exception\FatalThrowableError]
Call to a member function compileTruncate() on null

laravel 5.4

已安装 "jenssegers/mongodb": "^3.2",

**Comment by jiayouzl** [comment]
碰到同样的问题

**Comment by wl496928838** [comment]
BUG啊~修复下嘛

**Comment by z-song** [comment]
bug已经在1.3.x-dev修复了，更新到1.3.x-dev

**Comment by jiayouzl** [comment]
我用的是5.4啊~

**Comment by z-song** [comment]
@jiayouzl 那就用1.4.x-dev

**Comment by jiayouzl** [comment]
@z-song 谢谢明天醒来试下

**Comment by Adger01** [comment]
1.5 报这个错，怎么解决

**Comment by lizhenggan** [comment]
1.5 报这个错，怎么解决
