### ISSUE TITLE
multipleImage编辑时的BUG

### ISSUE THREAD

**Issue by y451309839** [z-song/laravel-admin#785]
multipleImage控件在编辑时，如果没有改动图片（编辑其它内容），导致 MultipleImage::prepareForeach 方法的$image传入null，而里面 getStoreName 时并没有处理 $image为null的情况，导致报错！ 对了，5.2版本。

**Comment by smm229** [comment]
碰到了相同的问题，此错误不是一直出现，而是偶尔出现的
![image](https://user-images.githubusercontent.com/23715207/34931517-30387c1e-fa0a-11e7-8ff0-99f4e2e47712.png)

**Comment by smm229** [comment]
求解决方案
