### ISSUE TITLE
#719 那个问题,修改了file和uploadFile,但是没有改MultipleFile,预览没了

### ISSUE THREAD

**Issue by never615** [z-song/laravel-admin#789]
https://github.com/z-song/laravel-admin/commit/277d074f2fb06cea20adac2db0ee00fab1288c11

顺便问一下:多图上传,我点浏览选一张,然后再点浏览,再选一张就会覆盖刚选的那张,(只能点浏览,一次选多张),是这样吗?还是只有我是?

**Comment by libybai** [comment]
上面的兄弟，多图上传的问题你解决了吗？我也遇到了这个问题，多图上传，再选择就会覆盖上一个

**Comment by libybai** [comment]
@never615

**Comment by never615** [comment]
没有,现在只能一次选择多张
