### ISSUE TITLE
登录记住我功能不起效果

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#79]
![image](https://cloud.githubusercontent.com/assets/7192860/19793169/44862712-9cfe-11e6-952a-051e0cd1926b.png)
勾选remeber me字段，但是session失效后（120分钟），没用自动登录。

![image](https://cloud.githubusercontent.com/assets/7192860/19793186/6e58baf0-9cfe-11e6-9e52-abe69aad6f85.png)
看登录逻辑中没有对remember字段的处理。
请问这个是功能还没有实现还是我哪里没有配置好？

**Comment by z-song** [comment]
@xyz8772232 为了后台管理的安全性，我之前决定去掉了自动登录功能，估计是前端忘记去掉这个checkbox

谢谢提醒
