### ISSUE TITLE
Permissions有什么用呢？

### ISSUE THREAD

**Issue by 775397252** [z-song/laravel-admin#792]
后台菜单和role绑定，那Permissions不是显得多余？本人小白想问下为何不讲菜单和Permissions绑定？

**Comment by xs47968224** [comment]
菜单的role只是判断是否显示，哪些角色能看见菜单，难保不会有用户直接链接访问，Permissions怎么会多余呢，不同的方法都可以控制……有的角色可以创建数据，有的只能看列表，不同的方法都可以细节控制，怎么会多余，你这问题太不走心了
