### ISSUE TITLE
自定义组件怎么获取当条需要修改的值的id

### ISSUE THREAD

**Issue by purrck** [z-song/laravel-admin#794]
我现在是自己弄了个组件   把权限列成多项选择的形式  在新增的时候没问题 在修改某角色的权限的时候发现传不了ID 然后没法默认选中
![image](https://cloud.githubusercontent.com/assets/24643608/25373999/6cd350ac-29ce-11e7-8577-98419422cd41.png)
我这是通过URL 参数获取到ID  但是这样的话 URL参数第一次传过来是在列表页面也就是gird那个页面的URL 参数  不对 就算给个判断然后刷新 还是有问题的

**Comment by z-song** [comment]
得先知道你的自定义组件是怎么写的
