### ISSUE TITLE
switch列扩展组件的值设置无效  都是 on或者off

### ISSUE THREAD

**Issue by leyix** [z-song/laravel-admin#803]
switch列扩展组件的值设置无效  都是 on或者off

**Comment by MiloZheng** [comment]
遇到同样的问题

**Comment by MiloZheng** [comment]
个人感觉应该修改SwitchField.php中的代码
$('{$this->getElementClassSelector()}').val(state ? '{$this->states['on']['value']}' : '{$this->states['off']['value']}');

**Comment by juoiy** [comment]
我數據庫裏設置的值是“on”和“off” 在根據文檔就改了value的值，在頁面中能夠正常顯示，但不能夠跟新數據庫。
` $states = [
                'on'  => ['value' => 'on', 'text' => '打開', 'color' => 'primary'],
                'off' => ['value' => 'off', 'text' => '關閉', 'color' => 'default'],
            ];
  $grid->status('狀態')->switch($states);`
然後在作者Dome中找使用switch的code，還真發現原因了，作者更新數據庫是有ajax發送執行，
[http://120.26.143.106/admin/demo/posts?&trashed=0](url)
第一次寫這個，希望能幫到你們！！！ @leyix @MiloZheng
