### ISSUE TITLE
scaffold helper error - file_put_contents(/Users/jackiehopwood/projects/laravel-admin/app/Models/.php): failed to open stream: No such file or directory

### ISSUE THREAD

**Issue by densonclan** [z-song/laravel-admin#805]
getting error when attempting to create a scaffold using the admin helper:

`file_put_contents(/Users/jackiehopwood/projects/laravel-admin/app/Models/.php): failed to open stream: No such file or directory`

this is from the operation log:

`	3	Administrator	POST	admin/helpers/scaffold	127.0.0.1	{ "table_name": "properties", "model_name": "App\\Models\\", "controller_name": "App\\Admin\\Controllers\\", "create": [ "migration", "model", "controller", "migrate" ], "fields": [ { "name": "id", "type": "integer", "key": "index", "default": null, "comment": null }, { "name": "add1", "type": "string", "key": null, "default": null, "comment": null }, { "name": "add2", "type": "string", "key": null, "default": null, "comment": null }, { "name": "add3", "type": "string", "key": null, "default": null, "comment": null }, { "name": "add4", "type": "string", "key": null, "default": null, "comment": null }, { "name": "add5", "type": "string", "key": null, "default": null, "comment": null }, { "name": "postcode", "type": "string", "key": null, "default": null, "comment": null }, { "name": "tenant_id", "type": "integer", "key": null, "default": null, "comment": null }, { "name": "owner_id", "type": "integer", "key": null, "default": null, "comment": null }, { "name": "purchase_price", "type": "decimal", "key": null, "default": null, "comment": null } ], "timestamps": "on", "soft_deletes": "on", "primary_key": "id", "_token": "CYcyjRnhwb9Va9Ri0bcWkjiYvS3Zuj12SFCFzGje" }`

**Comment by geekstek** [comment]
you need to input the model name and controller at the scaffold screen

**Comment by introin** [comment]
I have created folder 'Models' under app and it resolved!
