### ISSUE TITLE
grid列不能设置宽度

### ISSUE THREAD

**Issue by chenzi2015** [z-song/laravel-admin#808]
使用grid创建表格, 怎么才能设置列的宽度,  我看了其他人也提过这个问题, 我尝试了一下. 但是没有成功  地址是: **https://github.com/z-song/laravel-admin/issues/766**

  protected function grid()
    {
        return Admin::grid(GameRoleRegister::class, function (Grid $grid) {
	        $grid->id('ID')->sortable();
	        $grid->column('queue_data')->style('width:200px;');
        });
    }

**Comment by Tairy** [comment]
我是自定义了一个css 给列加了 max-width。

**Comment by chenzi2015** [comment]
@Tairy 请问一下怎么给grid自定义css?

**Comment by Tairy** [comment]
在 bootstrap.php 里面加上

```
Admin::css('/your/css/path');
```

**Comment by king52311** [comment]
我是把encore\laravel-admin\src\Grid\Row.php 里面的三个方法放到encore\laravel-admin\src\Grid\Column.php 里面，然后在
`  $grid->name('位置名称')->style('width:150px');`
在表格的<th>标签里面就有这个属性了

**Comment by purrck** [comment]
@Tairy 能把你的代码 发出来看一下嘛  尝试过你的方法 加完CSS 后不知道怎么用哦

**Comment by akazhuk** [comment]
@king52311  這個方法好使

**Comment by byte16** [comment]
上面的问题是：按照style这种方法有人可以实现，但并不是所有人都可以实现，issue这样就关了吗

**Comment by gq1078849197** [comment]
我
