### ISSUE TITLE
关于Grid列引用其它列的问题

### ISSUE THREAD

**Issue by gochiel** [z-song/laravel-admin#811]
$grid->id('ID')->sortable();

$grid->column('type');
$gird->column('type_value')->value(function($value){
     // 需要根据type的值进行不同的展示
     // #code here
    return ($column['type'] == 1 ? '类型1：' : '其它类型') . $value;
});

上面的这种情况怎么弄？

**Comment by edwinhuish** [comment]
用display，具体用法请看文档。
