### ISSUE TITLE
如何在表单中对同一个字段的添加和修改设置不同的属性值

### ISSUE THREAD

**Issue by gochiel** [z-song/laravel-admin#812]
$form->text('title');

在添加的时候我允许设置title
修改的时候不允许修改title
我要如果设计表单呢？

应用场景应该是比较多的，数据中对于某一个属性，在添加完之后就不允许再修改

**Comment by z-song** [comment]
你可以判断当前页面是添加页面还是修改页面，然后给修改页面设置`$form->text('title')->readOnly();`

**Comment by kelvenchi** [comment]
@z-song 怎么判断是添加页面还是修改页面？

**Comment by z-song** [comment]
@kelvenchi 修改页面进入edit方法会传入修改id，可以用这个判断
