### ISSUE TITLE
Method Encore\Admin\Grid::__toString() must not throw an exception,

### ISSUE THREAD

**Issue by aliakel** [z-song/laravel-admin#815]
FatalErrorException in Column.php line 0: Method Encore\Admin\Grid::__toString() must not throw an exception, caught ErrorException: Call to undefined method Encore\Admin\Grid\Row::getRowAttributes() (View: E:\xampp\htdocs\namaa\resources\views\vendor\admin\grid\table.blade.php)

**Comment by z-song** [comment]
参考这个comment https://github.com/z-song/laravel-admin/pull/807#issuecomment-298569856
