### ISSUE TITLE
Grid组件的actions怎么获取行数据?

### ISSUE THREAD

**Issue by chenzi2015** [z-song/laravel-admin#816]
我想在操作里面增加一个按钮, 按钮里面增加一个url带有这行数据的主键ID. 
但是我不知道怎么才能获取到, 请问应该如何获取到ID?

**Comment by z-song** [comment]
要看下你的按钮是怎么写的

**Comment by chenzi2015** [comment]
已经解决了, $actions对象里面有row对象.

**Comment by akazhuk** [comment]
@chenzi2015 大兄弟，如何在Action裏增加按鈕？

**Comment by zeen828** [comment]
//範例
            $grid->actions(function ($actions) {
                $id = $actions->row->id;
                $actions->append('<a href="/admin/' . $id . '/add/user/create" class="fa fa-user-plus"></a>');
            });
