### ISSUE TITLE
RBAC数据表用的 timestamp 作字段类型 [Y2K38]

### ISSUE THREAD

**Issue by fbens** [z-song/laravel-admin#825]
使用RBAC所有创建的create_at 和 update_at 都是 `timestamp` 类型，如果到了2038之后，这样岂不无法使用了 。

```
#vendor/encore/laravel-admin/migrations/2016_01_04_173148_create_admin_tables.php
$table->timestamps();?
```

**Comment by springjk** [comment]
<https://laravel-china.org/topics/2473/mysql-timestamp-timestamp-field-is-said-to-be-only-in-2037-why-laravel-also-default-to-use-this-field-as-a-new-time-update-time>
