### ISSUE TITLE
我想在列表多输出一行统计怎么实现

### ISSUE THREAD

**Issue by lxb5291689** [z-song/laravel-admin#829]

**Comment by colyii** [comment]
我也想知道，如果找到了麻烦分享一下。

**Comment by colyii** [comment]
可以通过传入的$actions参数来获取当前行的数据：

 $grid->actions(function ($actions) {

    // 当前行的数据数组
    $actions->row;

    // 获取当前行主键值
    $actions->getKey();
});

**Comment by colyii** [comment]
原谅我复制粘贴，但是你可以先看一下文档吗？
