### ISSUE TITLE
使用在自己的Model时,出现1366的错误,查看SQL发现中文都没有引号

### ISSUE THREAD

**Issue by xiaocode** [z-song/laravel-admin#83]
RT...使用的版本是1.3.x-dev
输入中文时会出现这样的错误,输入英文不会报错
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xE8\xB6\x85\xE7\xBA\xA7...' for column 'name' at row 1 (SQL: insert into `applications` (`name`, `icon`, `description`, `status`, `updated_at`, `created_at`) values (测试, http://7xonmh.com1.z0.glb.clouddn.com/FsBnaHplrQlmxTM3nNlUr_vgn8Sz, 测试, 1, 2016-10-28 17:18:29, 2016-10-28 17:18:29))
不知道BUG在哪里

**Comment by z-song** [comment]
检查一下你的表字段字符编码定义
