### ISSUE TITLE
[BUG]? Can't preview files

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#831]
Preview files in multiple upload was disabled. Now we can't  preview and delete it. 

/encore/laravel-admin/src/Form/Field/UploadField.php
```
protected function setupPreviewOptions()
    {
        $this->options([

            //'initialPreview'        => $this->preview(),  //<-- it should be uncommented?
            'initialPreviewConfig'  => $this->initialPreviewConfig(),
        ]);
    }
```

**Comment by taimaiduc** [comment]
@z-song any help talent?

**Comment by xiaobailc** [comment]
#687  Update static resources, you can copy `vendor/encore/laravel-admin/assets`  to `public/packages`
