### ISSUE TITLE
发现两处bug.

### ISSUE THREAD

**Issue by mrjnamei** [z-song/laravel-admin#837]
* 1
`
\Encore\Admin\Admin 
line : 106 method controllerNamespace ;
当我代码部署目录为/app/project时，app/这个路劲会被替换为空，建议不替换该路劲
`
* 2
`
 \Encore\Admin\Admin 
line : 106 method getModel ;
// 如果我没有看错的话，这里应该是一处死循环代码。
    public function getModel($model)
    {
        if ($model instanceof EloquentModel) {
            return $model;
        }
        if (is_string($model) && class_exists($model)) {
              // bugs here model 如果不是继承EloquentModel的话会死循环。
             return $this->getModel(new $model());
        }

        throw new InvalidArgumentException("$model is not a valid model");
    }
`

**Comment by z-song** [comment]
如果不是继承EloquentModel的话, 再次调用getModel的时候传进去的是参数是实例化的对象，不是string, 就会走到下面抛异常
