### ISSUE TITLE
求助：Disk [admin] not configured, please add a disk config in `config/filesystems.php`.

### ISSUE THREAD

**Issue by y7ut** [z-song/laravel-admin#839]
## 我使用了这个包，但是发现在涉及到文件上传的页面，会弹出标题显示的这个异常，而我在磁盘文件设置是local，为何会出现这个error,查看代码发现，是变量disk不在配置文件中，才会抛出这个错误，可是我需要在哪里设置这个disk，或者说，我应该如何修改我的**config/filesystems,php**这个配置文件。

**Comment by houlijie** [comment]
config/admin下配置即可

**Comment by houlijie** [comment]
/*
     * Laravel-admin upload setting.
     */
    'upload' => [

        // 'disk' => 'admin', 
        'disk' => 'local',

        'directory' => [
            'image' => 'images',
            'file'  => 'files',
        ],
    ],
