### ISSUE TITLE
可以将外部js或css引入pjax更新中吗

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#84]
比如，我自定义一个模板继承admin::index模板。然后在里面写自定义的样式和脚本文件
![image](https://cloud.githubusercontent.com/assets/7192860/19851055/ee98cda0-9f96-11e6-8c5f-3682448c856b.png)
![image](https://cloud.githubusercontent.com/assets/7192860/19851060/f574c034-9f96-11e6-96cb-b85658403a8f.png)
怎样才能让pjax请求中这些资源起作用

**Comment by z-song** [comment]
关于这个问题，我也没有找到比较好的解决办法

**Comment by xyz8772232** [comment]
是的，pjax已经一年没更新了。
