### ISSUE TITLE
1.4.x-dev multipleImage not working after composer update

### ISSUE THREAD

**Issue by rizaergun** [z-song/laravel-admin#842]
the preview image not view after composer update.

![multipleimage](https://cloud.githubusercontent.com/assets/5610980/26104015/bdc1050a-3a44-11e7-998c-51e4cb3ba4b2.PNG)

**Comment by qcol** [comment]
I reported it some days ago, workaround here: #831

**Comment by xiaobailc** [comment]
@rizaergun    you can Update static resources by copy `vendor/encore/laravel-admin/assets` to `public/packages`
