### ISSUE TITLE
Image not show in edit mode 

### ISSUE THREAD

**Issue by taimaiduc** [z-song/laravel-admin#849]
Image not show in edit mode just show link.
![screenshot-job dev-2017-05-18-00-41-19](https://cloud.githubusercontent.com/assets/10907980/26168004/d709ca82-3b62-11e7-89c0-c31edc50aed7.png)

**Comment by qcol** [comment]
See #831

**Comment by xiaobailc** [comment]
@taimaiduc  see #687
