### ISSUE TITLE
WangEditor upload image 403  Forbidden

### ISSUE THREAD

**Issue by Bouqute** [z-song/laravel-admin#850]
It is good when there is no picture of the content，
but if  you upload a picture it's report 403 Forbidden 
I have not modified the code，A few days ago it's work
![qq 20170518152901](https://cloud.githubusercontent.com/assets/19699836/26191036/dbc2609e-3bde-11e7-9d79-b8d64f053180.jpg)

**Comment by z-song** [comment]
Should be the issue of upload directory permissions
