### ISSUE TITLE
Changing login screen

### ISSUE THREAD

**Issue by avifatal** [z-song/laravel-admin#856]
Hi,
1. Is it possible to to add "remember be" checkbox
2. Is it possible to call my own css in the login screen.
Thanks

**Comment by gavande** [comment]
1. Copy all views from package to inside your resource folder. 
like:
`resources/admin/`

2. Add following line to your `AppServiceProvider` Class
```
$this->loadViewsFrom(resource_path('views/core'), 'admin');
```

Now you can customise your login view but all your views.

**Comment by avifatal** [comment]
Isnt that overkill to inject css?
I understand that to change HTML ill need to do that, so I give up.
But for CSS its an overkill. ill loose changes when the laravel admin will
be updated.
Thanks

**Comment by z-song** [comment]
You can override the login route by add following code in app/Admin/routes.php
```php
$router->get('/auth/login', function () {
    return view("Your-login-view");
});
```
