### ISSUE TITLE
pjax刷新页面图片路径问题

### ISSUE THREAD

**Issue by qq447665722** [z-song/laravel-admin#86]
get刷新数据截图
![image](https://cloud.githubusercontent.com/assets/14967427/19886294/8cf83cee-a05d-11e6-8346-81e7f4318114.png)
pjax刷新数据截图
![image](https://cloud.githubusercontent.com/assets/14967427/19886317/a04c1d74-a05d-11e6-81a9-87747ec07a5b.png)
图片的路径的"/"被转义了,是不是要设置什么?还是有bug?

**Comment by z-song** [comment]
没有发现这个问题，http://120.26.143.106/admin/carousel 这里有例子和代码

或者贴一下你的代码看看

**Comment by qq447665722** [comment]
什么都没改,今天又好了.....thank you
