### ISSUE TITLE
multipleImage 不能删除图片

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#865]
点删除按钮后，数据库里没有改变

**Comment by ezhilec** [comment]
And sorting is also not working

**Comment by CooperJin** [comment]
遇到同样问题 1.4.x-dev

**Comment by ajiader** [comment]
我也遇到 是1.3的版本  删除貌似有bug

**Comment by ajiader** [comment]
补充一下：我是使用了一对一 出现不能删除的问题，代码如下
`$form->multipleImage('data.images', '多图上传')->move('images/beadhouse/'.date('Y/m/d'))->uniqueName();`

**Comment by akazhuk** [comment]
@ajiader  你试试去掉app/Http/Kernel.php的ConvertEmptyStringsToNull中间件，我這樣改後可以刪除圖片，查看數據庫也是空的

**Comment by ajiader** [comment]
@akazhuk 貌似只有laravel5.4才有这个ConvertEmptyStringsToNull中间件，我用的是laravel5.3

**Comment by CooperJin** [comment]
为啥我注释了ConvertEmptyStringsToNull 这个中间件也不好用 ...

**Comment by imageslr** [comment]
@z-song image也无法删除图片。我原来有一个图片，点击删除以后提交，在开发者工具中可以看到`file_url`是空字符串`""`，但是后端获取不到这个参数。但是如果另一个`textarea`字段修改为空的话，后端就可以获取到这个空字符串。我已经注释了`ConvertEmptyStringsToNull`这个中间件。

删除图片后提交，网络请求中有文件内容，但是后端无法获取到请求：
![image](https://user-images.githubusercontent.com/17822028/44615174-19560b00-a866-11e8-8036-805393c32592.png)

![image](https://user-images.githubusercontent.com/17822028/44615173-10653980-a866-11e8-9eb0-61a144855902.png)
