### ISSUE TITLE
请问下怎么拿到添加数据后的自增id?

### ISSUE THREAD

**Issue by zhangya4548** [z-song/laravel-admin#866]
请问下在这个回调方法中怎么拿到添加数据后的自增id?

//保存后回调
$form->saved(function (Form $form) {
    //...
});

**Comment by RingoBool** [comment]
同问

**Comment by RingoBool** [comment]
$form->model()->id

**Comment by colyii** [comment]
真的吗？我现在就试试。

**Comment by colyii** [comment]
确实可以 $form->model()
