### ISSUE TITLE
select default NULL

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#867]
Hi... 

I have some columns as type select, but it should be as option. So, default value should be **none**.  Unfortunately by default the first position is chosen. I try to use prepend but can;t use empty data (option don't show). I can use only **0** but then require validation doesn't work as expected...  
How to deal with it?

```
$contracts =   Contracts::all()->pluck('number', 'id');
//                $contracts->prepend('- none -', "");  // << -- it doesn't work
                $contracts->prepend('- none -', 0);  // << -- it works but rules required doesn't work correctly because 0 is valid

                $form->select('contract_id', 'Contract')->options($contracts)->rules('required');
```

**Comment by zho** [comment]
this issue already cleared by this commit https://github.com/z-song/laravel-admin/pull/1264 have u update to the latest version?

**Comment by NickCoolii** [comment]
@qcol do you have this problem now?
