### ISSUE TITLE
filter的bug

### ISSUE THREAD

**Issue by JackyZhan** [z-song/laravel-admin#868]
如果先在grid里设定了条件比如代码如下。
$grid->model()->where('status', 1)->orWhere('status', 3)->orderBy('id', 'desc');

再设定filter就会无效。比如
$filter->like('username', 'name');

filter就会无效。

**Comment by JackyZhan** [comment]
是我自己eloquent里orWhere的写法问题。

**Comment by nicholas1009** [comment]
遇到了同样的问题 请教一下是什么写法问题
