### ISSUE TITLE
Form inline

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#872]
Is it possible to set the input fields next to each other (inline)? 
It's a waste of space to put short inputs one under the other

I found that I can use setWidth (not documented?), but what about form-group to set two inputs in one row?

**Comment by colyii** [comment]
model-form-tab
如果表单元素太多,会导致form页面太长, 这种情况下可以使用tab来分隔form:

**Comment by qcol** [comment]
Tab is not a solution for me. 

Sometimes I prefer this arrangement of fields: (it's more logical and handy) 

```
item 1: [input_width]   [input_length]   [input_height]   
item 2: [input_width]   [input_length]   [input_height]   
item 3: [input_width]   [input_length]   [input_height]   
```
Instead of such:

```
item1:
width:  [input_width]
length: [input_length]
height: [input_height]

item2:
width:  [input_width]
length: [input_length]
height: [input_height]

item3:
width:  [input_width]
length: [input_length]
height: [input_height]
```

**Comment by qcol** [comment]
I know that inputs one under another is OK for mobile devices. But my web apps are used 95% on PC / 5% on mobiles. So, it's big waste of screen space with wide HD screens.

**Comment by isometriq** [comment]
I would like to see that, in the same way the content pages are created. Here is an example:
```
$form->row(function ($row) {
    $row->column(4, function($column()){
        $column->text('first_name');
        $column->text('last_name');
        // etc...
    });
    $row->column(8, function($column()){
        $column->image('avatar');
        $column->textarea('notes');
        // etc...
    });
});
```

**Comment by isometriq** [comment]
@qcol One thing you could do is either:
- Create a custom field so that you can arrange the fields the best you can
- Override the view `vendor/encore/laravel-admin/views/form.blade.php` and use either the View Composer or override Encore\Admin\Form\Builder::render

I have such a requirement, but with nested forms (hasMany http://z-song.github.io/laravel-admin/#/en/model-form-fields?id=hasmany)

**Comment by isometriq** [comment]
I think for my specific case, I ended up creating a custom form field

**Comment by isometriq** [comment]
By the way, my comment above with code was only an example of how it could be implement.

**Comment by sistemasjg** [comment]
Hi, I'm just testing. This is working for me

```
 $form->row(function ($row) use ($id, $form) 
            { 
                $row->width(2)->text('fiscal_id', 'Id Fiscal')->rules('required|unique:empl_master,fiscal_id,'.$id);
                $row->width(4)->text('nombre', 'Nombre')->rules('required');
                $row->width(2)->date('fecha_nacimiento', 'F. de Nac.')->format('DD/MM/YYYY')->rules('required');
                
            },  $form);  
```

**Comment by llxx-lord-xxll** [comment]
@sistemasjg  But this solution makes the form full width and already added columns does not work as well :(

**Comment by t9221823420** [comment]
use $form->hasMany( ... )->mode('table');

**Comment by themightysapien** [comment]
I solved this in following steps.
1. Created Custom Form class which extends the main Form class.
2.  New Form class holds child form objects which gets saved during main form object is saved. Only draw back is Each child form class will run individual insert and update query.
3. Created custom field which cha load dynamic views and change layouts on the views accordingly.


`class Form extends AdminForm
{
    public $childForms = [];

    public function registerForm($form)
    {
        $this->childForms[] = $form;
    }

    public function partial($callback)
    {
        if (is_callable($callback)) {
            $form = new AdminForm($this->model());
            call_user_func($callback, $form);
            $this->childForms[] = $form;
            //dd($form->fields()->values());

            return $form->fields();
        }
        return null;
    }

    public function store()
    {

        foreach ($this->childForms as $form) {
            $form->store();
        }
        return parent::store();
    }

    public function edit($id): self
    {
        foreach ($this->childForms as $form) {
            $form->edit($id);
        }

        return parent::edit($id);
        //return $this;
    }

    public function update($id, $data = null)
    {
        foreach ($this->childForms as $form) {
            $form->update($id, $data);
        }

        return parent::update($id, $data);
    }
}`

And here is the Custom field class

`class Custom extends Field
{
    protected $view = 'core::fields.';
    protected $gridClass = ['col-md-2'];
    protected $fields = [];
    protected $partial = 'inline';

    public function __construct($label, $fields)
    {
        $this->label = $label;
        $this->fields = $fields[0];
    }

    public function plain()
    {
        $this->plain = true;
        return $this;
    }

    public function addScript()
    {
        return $this;
    }

    public function gridClass($gridClass)
    {
        $this->gridClass = $gridClass;
        return $this;
    }

    public function useView($partial){
        $this->partial = $partial;
        return $this;
    }

    public function render()
    {
        $this->view = $this->view . $this->partial;
        $this->addScript();
        $this->addVariables([
            'inputs' => $this->fields,
            'gridClass' => $this->gridClass
        ]);

        return parent::render();
    }
}`

This is what i used to render the attached form
`$form->custom('Vehicle', $form->partial(function ($f) {
            $f->setWidth(12, 1);
            $f->text('vehicle_no', 'Vehicle No')->placeholder('Plate Number');
            $f->text('vehicle_lot', 'Lot')->placeholder("Lot Number");
        }))->gridClass(['col-md-3', 'col-md-2']);
`

![Screenshot from 2020-10-11 16-09-45](https://user-images.githubusercontent.com/732813/95676214-35e76580-0bdc-11eb-8a97-d5f416b40ee5.png)

**Comment by themightysapien** [comment]
Now i need to figure out how to  append child form fields to parent fields during store and update so everything works in single query each time.
