### ISSUE TITLE
Multiple equal queries

### ISSUE THREAD

**Issue by SpinyMan** [z-song/laravel-admin#876]
This function (in Encore\Admin\Auth\Database\AdminPermission trait)

```
public function inRoles($roles = [])
{
    return $this->roles()->whereIn('slug', (array) $roles)->exists();
}
```

called as many times as called function visible 
`Admin::user()->visible($item['roles'])`

Could you insert there temporary memory cache to prevent it? Here is my example:

```
public function inRoles($roles = [])
{
	static $cache;

	$hashRoles = md5(implode('', $roles));
	if(!isset($cache[$hashRoles]))
	{
		$cache[$hashRoles] = $this->roles()->whereIn('slug', (array)$roles)->exists();
	}
	return $cache[$hashRoles];
}
```

**Comment by edwinhuish** [comment]
I think you'd better make a PR for @z-song

**Comment by SpinyMan** [comment]
@edwinhuish, could u pls do it for me and for @z-song ? :) 
Thx)

**Comment by langeuh** [comment]
created a PR #893 and used the built-in caching way for relations

**Comment by langeuh** [comment]
@SpinyMan @z-song This can be closed in my opinion. Works fine and reduces a lot of queries if you have many roles/permissions/menu items

**Comment by z-song** [comment]
Thanks
