### ISSUE TITLE
能自定义视图到content的布局组件吗？

### ISSUE THREAD

**Issue by chenlixin93** [z-song/laravel-admin#879]
![image](https://cloud.githubusercontent.com/assets/22536294/26785310/451c9a7e-4a34-11e7-983c-57776191025d.png)
比如想把自定义的上传视频的页面放到这个面板中

**Comment by chenlixin93** [comment]
我自己的做法是直接把 html 代码丢进box，双引号要用反斜杠转义，
如果在form表单，可以直接使用$form->html($tpl)的方式。
![image](https://cloud.githubusercontent.com/assets/22536294/26811319/a014b6a4-4aa3-11e7-87d2-674100ec77d8.png)

**Comment by z-song** [comment]
可以不放在box里面，新建一个视图文件写入你的html，比如video.blade.php， 然后：
```php
return Admin::content(function ($content) {
    ...
    $content->body(view('video'));
});
```
这样就可以了

**Comment by uu6744** [comment]
在哪个目录下写view

**Comment by z-song** [comment]
`resource/views`下

**Comment by uu6744** [comment]
laravel_admin下面，还是项目下面的resources/views

**Comment by reasonpun** [comment]
@uu6744 你可以参照下WangEditor调用视图的写法
class WangEditor extends Field
{
    ## **_protected $view = 'admin.wang-editor'; // 视图文件_**

    protected static $css = [
        '/vendor/wangEditor-3.0.9/release/wangEditor.min.css',
    ];
...
}
读取的模版是项目目录下
resources/views/admin/wang-editor.blade.php
文件
你的自定义视图也可以放到类似目录下。

**Comment by derboys** [comment]
``$form->html

**Comment by huyouheng** [comment]
如何引用其他的库，将其放入到该框架中, 比如 route('log-viewer'),  放这样的需要怎么用，使它在content 中显示，而不是整个页面全部覆盖呢？
