### ISSUE TITLE
Menu链接访问权限问题

### ISSUE THREAD

**Issue by hankji** [z-song/laravel-admin#891]
menu.blade.php中
@if(Admin::user()->visible($item['roles']))
开头这一句每次都是去数据库检查权限, 像我们现在如果有很多菜单的时候, 每个页面单菜单权限控制就要访问60多次数据库查询..
这个有什么方法修改吗?

**Comment by xs47968224** [comment]
可以编缉菜单时直接把角色字段留空，留空默认所有人可见，设置了角色就只有指定角色用户可见，如果已经全部设置了，你可以试着直接修改数据库中`admin_role_menu`表，（修改前请自行备份）
