### ISSUE TITLE
NestedForm and multipleFile, multipleImage problems

### ISSUE THREAD

**Issue by qcol** [z-song/laravel-admin#892]
When I use multipleFile in NestedForm, I can't remove files. No errors, just files appears again when back to edit mode. 

When I use  multipleImage in NestedForm, I can't upload any picture (png,jpg). Always get validation error "photo_fileld must be an image".  Why? 

By the way... multipleImage doesn't work in demo too:
http://120.26.143.106/admin/demo/multiple-images

**Comment by markxxv** [comment]
I had the same issue The products.17.photos must be an image. In my NestedForm

**Comment by DaoChinh1202** [comment]
Does anyone have a solution?
