### ISSUE TITLE
wangEditor 3.0 有集成成功的吗？

### ISSUE THREAD

**Issue by chenlixin93** [z-song/laravel-admin#898]
wangEditor 3.0 有集成成功的吗？我按照文档集成不成功。。。

**Comment by chenlixin93** [comment]
原来是各种路径加载搞错了，新版的路径跟文档不太一致，需要注意一下

**Comment by Tairy** [comment]
路径改了也没成功

**Comment by chenlixin93** [comment]
我用的v2的，v3搞不定

2017年7月26日 12:41，"Gengrui Guo" <notifications@github.com>写道：

**Comment by Tairy** [comment]
换成 simditor 了
