### ISSUE TITLE
Password example does not work

### ISSUE THREAD

**Issue by axyr** [z-song/laravel-admin#9]
On subsequent save the password gets bcrypted again with this example : 
```php
 $form->saving(function($form) {
        $form->password = bcrypt($form->password);
    });
```
I think there are several ways to solve this, but this depends where you want to go with this:

- keep all logic in the model and use a mutator in Administrator: 
```php
public function setPasswordAttribute($password)
    {
        if($password && $password != $this->password) {
            $this->attributes['password'] = bcrypt($password);
        }
    }
```
- move the logic to the password field.

there is already a prepare method that returns the changed value, but we need access to the Form object in the FormFields. This can be handy for other formfields as well : 

```php
public function pushField(Field $field)
    {
        $field->setForm($this);

        $this->builder->fields()->push($field);

        return $this;
    }
```

**Comment by z-song** [comment]
It's just a example to show what saving() method can do.

**Comment by axyr** [comment]
I understand that.
But its a bit confusing as the example does not work and it is used in [AdministratorController](https://github.com/z-song/laravel-admin/blob/master/src/Commands/stubs/AdministratorController.stub#L43-L45) as well.

If my PR #13 is accepted, I should change the example and the stub to this : 

```php
    $form->saving(function(Form $form) {
        if($form->password && $form->model()->password != $form->password)
        {
            $form->password = bcrypt($form->password);
        }
    });
```

And maybe the value of password should not be populated from the database?

**Comment by z-song** [comment]
You are right ! I will update the readme.md and stub later.
