### ISSUE TITLE
多图上传在编辑的时候图片不能删除的bug

### ISSUE THREAD

**Issue by ajiader** [z-song/laravel-admin#903]
版本：1.3
bug描述：在使用多图上传的功能，编辑的时候不能删除，模型关联是1对1
`$form->multipleImage('data.images', '多图上传')->move('images/beadhouse/'.date('Y/m/d'))->uniqueName();`
期望：在使用关联关系的时候多图上传功能，可以删除图片。

**Comment by lduhejian** [comment]
我也遇到同样的问题

**Comment by lduhejian** [comment]
我知道了原因了。需要添加 removable() 方法
```
$form->multipleImage('images', '样品图片')
          ->removable();
```
