### ISSUE TITLE
[HELP]一对多嵌套表格生成字段赋值

### ISSUE THREAD

**Issue by JefferyWong** [z-song/laravel-admin#905]
对于数据表单的嵌套表单（hasMany）主键并不是AUTO INCREMENT而是程序生成，在创建保存的时候主表可以用类似
`$form->saving(function (Form $form) {
                if (!$form->id) {
                    $form->id = uniqid();
                }
            });`
来生成，而对于嵌套表使用
`$form->hasMany('borrower_contact', '借款人联系人', function (Form\NestedForm $form) {
                if (!$form->id) {
                    $form->id = uniqid();
                }
}`
不管用。
请问可以用什么方式为表borrower_contact的生成字段赋值？

**Comment by yuriyoung** [comment]
这个不是前端的事情。在PHP里做，在Model里的的boot里实现creating函数来实现id的自定义。
