### ISSUE TITLE
多对多关系时grid搜索能否支持一下自定义sql

### ISSUE THREAD

**Issue by imlida** [z-song/laravel-admin#91]
部分多对多关联的搜索场景需要where子句里带入附表的某些条件，能够支持下，如果可以自定义搜索sql就强大了，laravel-admin很不错，会一直关注。

**Comment by z-song** [comment]
确实搜索功能这块还不够灵活，接下来会把这个功能加上。

谢谢关注！

**Comment by imlida** [comment]
期待

**Comment by z-song** [comment]
@imlida 目前已经实现了使用`eloquent`的查询做过滤
```php
$grid->filter(function ($filter) {

    $filter->where(function ($query) {

        $input = $this->input;

        $query->whereHas('tags', function ($query) use ($input) {

            $query->where('name', $input);

        })->orWhere('title', 'like', "%$input%");

    }, 'Has tag');
});

```

上面是个多对多关系组合查询的例子

如果需要使用自定义sql，可以使用`$query->whereRaw()`来实现

谢谢你的建议！

**Comment by imlida** [comment]
赞，等会测试一下，非常棒的开源项目，节省了很多搭建后台的时间，希望越做越好

**Comment by imlida** [comment]
还有就是搜索字段可以加一个select的类型，部分过滤条件是bool类型的

**Comment by z-song** [comment]
@imlida  http://120.26.143.106/admin/china-area/city  你说的是`Province`这种select选择查询吗?

**Comment by imlida** [comment]
恩对的，看到了，谢谢
