### ISSUE TITLE
请问可以拿到 $filter->where()的 url 参数名么

### ISSUE THREAD

**Issue by lyyhd** [z-song/laravel-admin#910]
_想在filter 外获取 filter->where()   用户输入的参数,
 url 上显示 eb89ad29d1bc1a89c27e845af4c06668=2
查看了下代码_
       ` return md5($reflection->getFileName().$reflection->getStartLine().$reflection->getEndLine())`
请问怎么可以在搜索时获取到这个key呢？

**Comment by z-song** [comment]
现在提供第三个参数自定义key
```php
$filter->where(function () {
    //...
}, '用户名', 'username')
```
