### ISSUE TITLE
selectOptions可以设置成model tree那种可以收缩展开的样式吗？

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#912]
这是selectOptions的样式
![default](https://user-images.githubusercontent.com/9032762/27374324-ed58320a-569d-11e7-882f-c46b98a0c2da.png)

想修改成model tree的这种可以收起和展开
![default](https://user-images.githubusercontent.com/9032762/27374363-0eaa4182-569e-11e7-9693-9eba3e6df4a5.png)

**Comment by juoiy** [comment]
@akazhuk 大兄弟 能贴一下你使用selectOptions的代码吗？我不会使用，万分感谢！！！

**Comment by akazhuk** [comment]
@juoiy 
$form->select('book','书本')->options(Book::selectOptions())

**Comment by juoiy** [comment]
@akazhuk 谢谢大兄弟，已解决！

**Comment by akazhuk** [comment]
最後用JS自定義
