### ISSUE TITLE
multipleSelect 逗号分割的字段

### ISSUE THREAD

**Issue by hzysoft** [z-song/laravel-admin#915]
大神您好，
按文档，多选框支持：选项值以逗号,隔开，存储在字符串字段里

但文档没有写怎么使用，请问如何使用？

我现在处理的方式是，在$form->saving回调中，把提交的数组组合成了逗号分隔的字符串，保存到数据库正常。

但是！下次打开form的编辑页面，不能正常显示已保存的值。

请求大神帮助！

**Comment by edwinhuish** [comment]
请查看laravel的文档： [Eloquent: 修改器](http://d.laravel-china.org/docs/5.4/eloquent-mutators)

**Comment by hzysoft** [comment]
@edwinhuish 
这个问题其实不是修改器能解决的，你实际开发就知道了。
这个情况，保存值到数据库是正常的了，只不过读取值不正常，我的格式是0-1-0-1-1-1-0-0这样的字符串，
即使增加了模型的“访问器”也不能解决该需求。
最终我还是修改了MultipleSelect的fill()方法

无论如何，还是感谢你热心帮忙。

**Comment by edwinhuish** [comment]
Laravel-admin底层有很多地方都有点问题，只是修改起来太麻烦。。。。

我跟你说的Eloquent的修改器确实可以达到你需要的效果。

读取的时候将String转为Array，保存的时候将Array转为String

**Comment by hzysoft** [comment]
@edwinhuish 你试一下就知道，它的MultipleSelect组件，读取model值时，没有经过访问器的，估计是用DB或者什么方式读取的，所以只能直接修改MultipleSelect
