### ISSUE TITLE
datetimepicker报错

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#916]
![default](https://user-images.githubusercontent.com/9032762/27464986-26078bee-5803-11e7-9170-2d3853ee5b58.png)

**Comment by hzysoft** [comment]
好像datetimepicker一直不好使

**Comment by myyeshang** [comment]
locale改成 `zh_CN-cn` 试试

**Comment by akazhuk** [comment]
@myyeshang 是語言問題，自己更改了datetimepicker裏的語言設置，直接設置為en
