### ISSUE TITLE
安装后，分页、搜索，导出等功能无法正常使用

### ISSUE THREAD

**Issue by north9527** [z-song/laravel-admin#919]
如题，查不出原因。已经多次重复安装，并新建项目

**Comment by z-song** [comment]
什么表现？

**Comment by north9527** [comment]
点击页码后，page一直在变化，但是数据还是停留在第一页，
例如点击8后，url 为 `http://jwt.dev:7888/admin/users?per_page=8`  但是数据还是第一页的

![1852daa0-f7ed-4b79-9c0f-c5e52f25fbf6](https://user-images.githubusercontent.com/9986214/27472118-c92e53ec-582c-11e7-9a8d-88eba71f5c9d.png)
