### ISSUE TITLE
限制输入的问题

### ISSUE THREAD

**Issue by 14718011108** [z-song/laravel-admin#921]
为什么 $form->text('name', '姓名')->rules('required|max:12');
            // $form->image('avatar', trans('admin::lang.avatar'));
           $form->password('password', trans('admin::lang.password'))->rules('required|max:12');
            $form->password('password_confirmation', trans('admin::lang.password_confirmation'))
                ->default(function ($form) {
                    return $form->model()->password;
                });    上面姓名的限制有用  下面密码的就没用****

**Comment by aen516954023** [comment]
同问  有个比例输入 如何限制输入比例的大小
