### ISSUE TITLE
Sql 重复查询问题

### ISSUE THREAD

**Issue by leung0826** [z-song/laravel-admin#922]
有一处 sql 重复查询问题，`laravel-debugbar`工具查看到的
![image](https://user-images.githubusercontent.com/19591674/27531950-0523cc68-5a91-11e7-9fa8-0411a0d449b0.png)
`/vendor/encore/laravel-admin/src/Auth/Database/AdminPermission.php:122`
`/vendor/encore/laravel-admin/src/Auth/Database/AdminPermission.php:140`

**Comment by z-song** [comment]
已修复
