### ISSUE TITLE
External JS

### ISSUE THREAD

**Issue by naingwin** [z-song/laravel-admin#926]
Load external js using Admin::js('something.js') in boostrap.php. But not load those js file when I go to create view from list view. I need to refresh once for my external js work. I anyone has this issue?

**Comment by chenqixuan** [comment]
me too  :(  我也遇到同样的问题，请问怎么解决 ?

**Comment by z-song** [comment]
Because of pjax, the js files are loaded only once when page opens, so you should define js functions in js file, and use `Admin::script()` to call the functions you defined

In you js file:
```js
function message() {
    alert('xxxx');
}
```

and call this function in your action `Admin::script('message()');`

**Comment by naingwin** [comment]
Let me please re-open this issue, I am using vue js for some custom process. So my js code will be like this        
        ` new Vue({     
	     el: '#app',     
        });`
how can I call those script via `Admin::script();`. I am just new in JS. Thanks in advance

**Comment by banstola** [comment]
Did you actually solve this issue? I have exact same problem. I have to include custom js script . 200 lines but the JS is not included unless I refresh

**Comment by miurabo** [comment]
@banstola Isn't it possible to call it with Admin::script () after converting it into a function?

**Comment by azinkey** [comment]
when i am calling Admin::script() in my form(){ action it will produce an error
 FatalThrowableError In SpecializationsController.php line 74 :
Class 'App\Admin\Controllers\Admin' not found

**Comment by banstola** [comment]
> when i am calling Admin::script() in my form(){ action it will produce an error
> FatalThrowableError In SpecializationsController.php line 74 :
> Class 'App\Admin\Controllers\Admin' not found

I have a news for you. Admin class does not exist in that namespace. Are you importing correct class?

**Comment by backend-doctor** [comment]
you can use this code to reload the page

```
    if(!localStorage.getItem('reload')){
            localStorage.setItem('reload', 1)
            window.location.reload()
    }
    setTimeout(()=>{
        localStorage.removeItem('reload')
    }, 9000)
```

**Comment by alexoleynik0** [comment]
Don't know what I'm doing here, but besides the good example that z-song provided (and in most cases I will recommend it too), there's also pjax events you can use.
For example 
```js
$(document).on('pjax:complete', function() {
    // this will be run on every pjax request complete 
});
```

**Comment by backend-doctor** [comment]
a more reliable option with js underloading is to disable pajax, this will reload page on every open

```protected function form()
{

(new \Encore\Admin\Admin)->disablePjax();

$form = new Form(new Post());```

//or

protected function grid()
{
    (new \Encore\Admin\Admin)->disablePjax();
    $grid = new Form(new Post());
