### ISSUE TITLE
How to add new plugin 

### ISSUE THREAD

**Issue by hassan848** [z-song/laravel-admin#928]
i want to implements nprogress plugin to add loading bar whenever there is request,
but i did not figure out how to add it.

and suggestions where to include the js and css files and the script to run it globally.   

thinks you in advance :)

**Comment by king52311** [comment]
try do it
http://120.26.143.106/admin/demo/users
`Admin/Extensions/Column/UrlWrapper.php`

**Comment by z-song** [comment]
In app/Admin/bootstrap.php add:
```php

Admin::css('path/to/nprogress.css');
Admin::js('path/to/nprogress.js');

$script = <<<SCRIPT

$(document).on('pjax:start', function() { NProgress.start(); });
$(document).on('pjax:end',   function() { NProgress.done();  });

SCRIPT;

Admin::script($script);
```
