### ISSUE TITLE
submit form 的时候想在后台多添加进字段，然后在save怎么办？

### ISSUE THREAD

**Issue by king52311** [z-song/laravel-admin#934]
//保存前回调
            $form->saving(function (Form $form) {
                $form->model()->url='http://www.baidu.com';

            });
用了这个方法不管用，也没看到其他地方能额外给字段赋值的

**Comment by z-song** [comment]
可以在模型里面设置事件回调来处理，在模型里面添加下面的方法：
```php
public static function boot()
{
    parent::boot();

    static::saving(function ($model) {

        $model->url='http://www.baidu.com';

    });
}
```

**Comment by king52311** [comment]
$form->saving(function (Form $form) {
                $form->url='http://www.baidu.com';
            });

这样解决啦，多谢

**Comment by chenzi2015** [comment]
public static function boot()
{
    parent::boot();

    static::saving(function ($model) {

        $model->url = 'http://www.baidu.com';

    });
}

如果这样解决的话， 其他逻辑岂不是都会这样了？ 感觉逻辑处理还是交给控制器比较好。

**Comment by chenzi2015** [comment]
@king52311 我按照你的方法好像不得行哦！  store的时候还是找不到添加的字段。

**Comment by never615** [comment]
我也不行,我想从表单中提交一些,表中不存在的字段,在saved中使用.但是到不到这,就会报数据库中不存在该列的错误.
