### ISSUE TITLE
WangEditor上傳圖片報錯，看demo也是報錯

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#935]
應該如何配置？
![default](https://user-images.githubusercontent.com/9032762/27670472-bbbbc2a2-5cbf-11e7-8173-377490e5f460.png)

**Comment by edwinhuish** [comment]
明显是路由没有配置。

**Comment by akazhuk** [comment]
@edwinhuish  大兄弟，路由應該怎麼配置？

**Comment by edwinhuish** [comment]
我擦～ laravel的路由都不会？基础中的基础啊，大哥。。。

去看看文档吧

**Comment by akazhuk** [comment]
@edwinhuish 這裡是需要配置上傳圖片的路由配置吧？demo裏也沒給出

**Comment by akazhuk** [comment]
自己寫了一個上傳圖片的方法解決了
