### ISSUE TITLE
使用自动生成表格是如何保留超链接

### ISSUE THREAD

**Issue by xyz8772232** [z-song/laravel-admin#94]
![image](https://cloud.githubusercontent.com/assets/7192860/20052364/b2f115be-a50e-11e6-8c0f-eb70104d9d30.png)
直接
    $row[['<a href="http://yun.app/admin/articles/channel/4">纽澳新闻</a>']];
会被转义：
![image](https://cloud.githubusercontent.com/assets/7192860/20052452/0d001082-a50f-11e6-90c6-012411e6113e.png)

**Comment by z-song** [comment]
你可以先改一下 文件`vendor/encore/laravel-admin/views/widgets/table.blade.php` 13行
```php

<td>{!! $item !!}</td>

```

我稍后把这个修改提交

**Comment by xyz8772232** [comment]
好的，多谢
