### ISSUE TITLE
Helper Idea: Backup Manager

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#940]
An interface for system backup would be useful. Generating a zip containing a dump of the database, and uploads (images and files)

Pushing it further, possibility of scheduling the backups, locally or to an S3 storage (filesystems.php)

**Comment by z-song** [comment]
In next version for Laravel-v5.5, I'll build a backup interface as a extension based on [laravel-backup](https://github.com/spatie/laravel-backup).

**Comment by isometriq** [comment]
yes!
