### ISSUE TITLE
Helper Idea: Recycle bin

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#941]
Laravel features a way to allow trashing data instead of deleting it. A recycle bin to bring back the trash would be interesting. However, model relationships may complicate things up...

**Comment by z-song** [comment]
This [demo](http://120.26.143.106/admin/demo/posts) implements a recycle bin.

Click the `Trashed` button at the head of table and you can see it.

**Comment by isometriq** [comment]
Ok, thanks

I understand now, since the feature depends on the models specific to an app, it would not be possible to make it generic without using conventions. Yet it could be interesting to use the config to tell which models can be trashed and a section to recover, review or wipe them.

If I do something interesting, I'll create a pull request.
