### ISSUE TITLE
Render alert manually

### ISSUE THREAD

**Issue by ltomana** [z-song/laravel-admin#944]
I'd like to render a default green alert in a form view, but can't find the clue in documentation.
The alert should appear in the wake of activation js event.
What should I use in my Js?

**Comment by z-song** [comment]
You can import js files by using `Admin::js('path/to/your/js');` in `app/Admin/bootstrap.php`

Or add js scripts globally by using `Admin::script('alert("hello");');`

**Comment by ltomana** [comment]
Oh, this is not exactly what I was thinking about but actually found a solution. Thanks!
