### ISSUE TITLE
The layout "layout-top-nav" is not displaying correctly

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#948]
If I use AdminLTE demo as a reference
https://adminlte.io/themes/AdminLTE/pages/layout/top-nav.html

The layout `layout-top-nav` in `config/admin.php` does not seem to display correctly. It still shows a collapsible left menu when it would have to appear on the top bar.

**Comment by 2670207** [comment]
https://github.com/z-song/laravel-admin/issues/755
