### ISSUE TITLE
mp3文件上传后被自动转了格式？？？

### ISSUE THREAD

**Issue by chenlixin93** [z-song/laravel-admin#951]
![image](https://user-images.githubusercontent.com/22536294/27767914-8e493860-5f38-11e7-86b9-ea66036806fa.png)
@z-song 肿么解决？？？

**Comment by chenlixin93** [comment]
版本是 1.4*的

**Comment by CooperJin** [comment]
这块重命名判断后缀的有点问题，原来传apk都给改成zip了

只能自己实现重命名的功能
