### ISSUE TITLE
Logged admin user profile form "List" button links to non-existing url

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#952]
This is when the form is opened using the top right profile dropdown and pressing the Settings button.

The List button then tries to go at `/admin/auth` which does not exists.

Suggesting to either hide the button in that case, redirect to the users list or the homepage.
I think 1st option (hide button) would be best and leave back button which works ok...

**Comment by langeuh** [comment]
@z-song  #1284 fixed this
