### ISSUE TITLE
Request: Grid callback for delete similar to Form save

### ISSUE THREAD

**Issue by isometriq** [z-song/laravel-admin#953]
`$form->saving()` and `$form->saved()` is useful for additional logic when saving the form.

I would like to see something like `$grid->deleted()` for extra logic when deleting a row (or a batch) from the grid context.

**Comment by example3** [comment]
Rewrite function boot in model (see #713)
`public static function boot()
    {
         parent::boot();
        static::deleted(function ($model) {
            //do something after deleting...
        });
    }`
