### ISSUE TITLE
如何调用自带的toast提示？

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#959]
![default](https://user-images.githubusercontent.com/9032762/27821242-2d3d4dfc-60d4-11e7-9687-e8456c79f17d.png)

**Comment by chenlixin93** [comment]
尝试下   `\Encore\Admin\Admin::script("toastr.success('缓存清了');");`

**Comment by z-song** [comment]
`admin_toastr('xxx');`
