### ISSUE TITLE
上传到指定磁盘

### ISSUE THREAD

**Issue by MasterShu** [z-song/laravel-admin#961]
> <h3>文件上传的磁盘是admin配置的磁盘</h3>
> 虽然有可以move() 到新路径,可是限制还是蛮大的!
** 但是个人觉得如果可以修改的像laravel那样,</b>指定到上传的磁盘</b>最好!! 
> 这样就可以想上传到那个磁盘就上传到哪个磁盘!
> 不然前台提交的和后台提交的不在一起!管理起来好麻烦!!
> 望采纳

@z-song

**Comment by z-song** [comment]
指定磁盘 `$form->image('xxx')->disk('your-disk');`

**Comment by MasterShu** [comment]
<h2>ok!</h2>
文档上没看到,^_^
