### ISSUE TITLE
How to validate exists with multiple connections

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#964]
I've got 2 connections mysql and mysql2. I need to validate Name of Category on mysql2 connection.
This is my code on $form:

`$form->text('name', 'Category')->rules('required|exists:mysql2.databsename.category.name');`

This is error:
> QueryException In Connection.php line 647 :

> SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '.`name` where `name` = ?' at line 1 (SQL: select count(*) as aggregate from `databasename`.`category`.`name` where `name` = Romance)

**Comment by z-song** [comment]
Try `rules('exists:connection.table,column');`

**Comment by amun1303** [comment]
Thanks z-song, It's worked
