### ISSUE TITLE
当使用select进行选择时，我如何及时知道用户的选择内容是什么，进而主动的根据用户选择更新其他项的内容？

### ISSUE THREAD

**Issue by h17600104847** [z-song/laravel-admin#968]

**Comment by king52311** [comment]
可以考虑多级联动，每次都异步AJAX请求下一层数据
http://120.26.143.106/admin/china-area/nested
`$form->select('province')->options(

                ChinaArea::province()->pluck('name', 'id')

            )->load('city', '/admin/api/china-area/city');

            // second level
            $form->select('city')->options(function ($id) {

                return ChinaArea::options($id);

            })->load('district', '/admin/api/china-area/district');

            // third level
            $form->select('district')->options(function ($id) {

                return ChinaArea::options($id);

            });

            $content->body(new Box('多级联动', $form));`

**Comment by mygrows** [comment]
请教一个问题，需求：在一个表单中，根据用户选择的内容，显示不同的图片
还有就是多级联动只能是使用 select 控件来接收 ajax 请求返回的数据吗？用其他控件接收返回结果是否可以？例如图片控件

**Comment by king52311** [comment]
其他的效果可以自己添加onclick 然后自己扩展js应用，他这个只是常规性质常用的一些控件
http://120.26.143.106/admin/demo/users
中的 Admin/Extensions/Column/UrlWrapper.php 就是自定义的效果，可以仿制一个

**Comment by xiangxihenli** [comment]
官网也发现了这个错误。
![avatar](https://s1.ax1x.com/2018/12/03/FMdQ1J.md.png)
