### ISSUE TITLE
网站域名使用的是 https 协议，使用laravel-admin 登录请求确是 http， 能否将扩展的请求链接协议也修改为https？

### ISSUE THREAD

**Issue by mygrows** [z-song/laravel-admin#972]
自定义的一个扩展，ajax 请求被 canceled，导致请求无法完成，经排查， 发送的 ajax 请求使用的是 https协议，可是同时发送的登录验证使用的却是 http 协议， 协议降权了，可是我设置了 <meta name="referrer" content="no-referrer">  还是没管用，这该如何处理？ 有一点疑惑，我网站语言已经配置了 https 协议，可是 laravel-admin 扩展使用的确是 http 协议？ 盼望解答，谢谢 :)
@springjk 你好
1、 我在  .env  文件配置的 url 使用的是 https  如图

![1499837577 1](https://user-images.githubusercontent.com/23335187/28103164-fa1c1c8a-6706-11e7-95df-0426ab7d13e8.jpg)

2、我web服务器使用的是 apache 
3、自定义的 小扩展方法发送的 ajax 请求协议是 https，可是回有一个 login 却是 http 协议发出的 错误休息如下图

![qq 20170712133420](https://user-images.githubusercontent.com/23335187/28103312-990fb914-6707-11e7-99d1-e53c632bb64e.png)

4、而编辑操作是是可以的

**Comment by springjk** [comment]
1. 检查 `config/app.php` 中的 url 是否设置为 `http`
2. 检查是否采用的为 nginx proxy 模式，如是请开启 request 的 信任代理 IP 列表

你这个问题也没有描述清楚，建议附上截图，没有发现过你这样的问题，https 一直工作正常。

**Comment by elinxer** [comment]
https://m.xxxx.com/admin
样式请求却是http
配置的APP_URL和mo'r默认都配置了相同的，是https

**Comment by ibegyourpardon** [comment]
config/admin.php 中 secure 设置为 true 就可以了

**Comment by liangshuocj** [comment]
config/admin.php：'https' => env('ADMIN_HTTPS', true),
