### ISSUE TITLE
能否在上传图片的组件里预先做裁剪的？

### ISSUE THREAD

**Issue by chenlixin93** [z-song/laravel-admin#973]
能否在上传图片的组件里预先做裁剪的？比如自定义自己想要的比例，尺寸？

**Comment by z-song** [comment]
`$form->image()->crop(100, 100, 25, 25);`

`crop`方法的使用参考 http://image.intervention.io/api/crop

**Comment by leung0826** [comment]
admin使用了 image 的类库吗？怎么没有搜到呢？

**Comment by imageslr** [comment]
使用了intervention/image
