### ISSUE TITLE
外挂自己的js文件问题

### ISSUE THREAD

**Issue by chenqixuan** [z-song/laravel-admin#974]
使用Admin::js('/packages/prettydocs/js/main.js')，这种方式加载自己的JS文件，每次页面一打开不生效，要刷新下才能执行这个JS

**Comment by tiandaye** [comment]
我也想在某个页面有自己的js，请问解决了吗？

**Comment by z-song** [comment]
封装成方法放在引入的js文件里面:
```
//main.js
function foo() {
    alert('hello');
};
```

在页面里用`Admin::script('foo();')`调用。

**Comment by tiandaye** [comment]
@z-song 请教下我页面里用 `Admin::script('foo();')` 调用。是不是就是当次执行下，不会对其他页面造成影响吗? 还有就是如果我在函数里面写了绑定事件，如果多次访问这个页面不会多次绑定事件吧。

**Comment by z-song** [comment]
我也不太清楚pjax的机制，目前没有遇到多次绑定事件产生的问题

**Comment by tiandaye** [comment]
谢谢回复! 我之前想在blade里写的每段js, 现在都封装成函数, 然后用 `Admin::script('foo();') ` 这种方式调用。

**Comment by BI7PRK** [comment]
后台引用JS是个痛点。不能直接用Admin::js 引入。载入失败。
Admin::script() 模板中定义了 $(function(){; }); 但有时候有些组件不能在里面初始化。

**Comment by tjlai17** [comment]
> 使用Admin::js('/packages/prettydocs/js/main.js')，这种方式加载自己的JS文件，每次页面一打开不生效，要刷新下才能执行这个JS

页面开始打开是pjax加载，所以不生效；我这边找到解决方案是把要调用的方法放到$(document).on('pjax:end', function() { //要加载调用的js方法 });

**Comment by summerblue** [comment]
https://learnku.com/articles/42041

**Comment by medmin** [comment]
@tjlai17 

这个方案OK，谢谢

**Comment by gavin1420** [comment]
> > 使用Admin::js('/packages/prettydocs/js/main.js')，这种方式加载自己的JS文件，每次页面一打开不生效，要刷新下才能执行这个JS
> 
> 页面开始打开是pjax加载，所以不生效；我这边找到解决方案是把要调用的方法放到$(document).on('pjax:end', function() { //要加载调用的js方法 });

用你的方法成功了
感謝
