### ISSUE TITLE
switch 不能使用

### ISSUE THREAD

**Issue by ScorpioRen** [z-song/laravel-admin#977]
当我使用hasOne调用另一个对象,的一个状态 
$grid->column('order.is_del', '是否启用')->switch();时 它不工作了,变成了一个checkbox

**Comment by chenlixin93** [comment]
现在switch不应该是这样写吗？
```
$states = [
          'on'  => ['value' => 1, 'text' => '通过', 'color' => 'success'],
          'off' => ['value' => 0, 'text' => '待审核', 'color' => 'danger'],
];
$form->switch('status','审核状态')->states($states);
```

**Comment by EddyAnn** [comment]
我也这样写了，但是后台数据库数据没有改变

**Comment by z-song** [comment]
form里面要有一个同样的switch组件， 因为grid里面的switch修改是依赖form里面的switch实现的

**Comment by zhao0229** [comment]
> form里面要有一个同样的switch组件， 因为grid里面的switch修改是依赖form里面的switch实现的

`$grid->column('status', __('状态'))->switch();
$form->switch('status', __('状态'));
`
列表不行，点击开关后提示
![image](https://user-images.githubusercontent.com/35862443/105938275-3c69f200-6092-11eb-88a5-d97e2df4203a.png)
请求状态
![image](https://user-images.githubusercontent.com/35862443/105938344-60c5ce80-6092-11eb-9d53-9c3a35dc8b85.png)
请求地址：xxx.xxx.com/admin/xxxx/4
这是怎么回事
