### ISSUE TITLE
[HELP] In demo widget forms

### ISSUE THREAD

**Issue by orazz** [z-song/laravel-admin#978]
In demo admin panel widgets forms form2:
 ```$form = new Form();```
 ```$form->action('example');```
```...```
Can i see example action how to proccess how to get "get, post" methods?

**Comment by z-song** [comment]
For example, if you set the form action to `/admin/update-something`, then you need to register a route for this in `app/Admin/routes.php`:
```
$router->post('update-something', 'Controller@action');
```
At last process the input data from request in your action.

**Comment by orazz** [comment]
Thanks!
