### ISSUE TITLE
Can not select option when load data by using ajax

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#980]
I want to select a Book -> book_id to a Chapter. I don"t want to use below solution because there are many books up to thousand books in my system and this combo box always choose an option as default, I don't want it, look below:

`$form->select("book_id", "Choose a book")->options(BookInfo::all()->pluck("title", "book_id"));`

So, I choose to load data by using ajax. Following with document, my code show after:

**ChapterInfoController**
```
protected function form() {
        return Admin::form(ChapterInfo::class, function (Form $form) {
            ......

            $form->select("book_id", "Choose a book")->options(function ($book_id) {
                $book = BookInfo::find($book_id);

                if ($book) {
                    return [$book->book_id => $book->title];
                }
            })->ajax("/admin/api/books");

            ......
        });
    }
```

**routes.php**
`$router->get("api/books", "BooksApiController@books");`

**BooksApiController**
```
class BooksApiController extends Controller{
    public function books(Request $request){
        $q = $request->get("q");
        return BookInfo::where("title", "like", "%".$q."%")->paginate(null, ["book_id", "title as text"]);
    }
}
```

Every thing looks fine, when I type any character, server response a list of Books below the input text
BUT, I CAN NOT SELECT AN OPTION --> please help me. 
++++++++++++++++++++++++++++++++++++++++++++++++
In the other hand, I can using the solution below and HOW TO SET BLANK VALUE FOR DEFAULT WITH RULES METHOD
`$form->select('book_id', 'Choose a book')->rules('required')->options(BookInfo::all()->pluck('title', 'book_id'));`

**Comment by z-song** [comment]
That's weird,  any errors in browser console?

**Comment by amun1303** [comment]
There is no error on browser console

![image](https://user-images.githubusercontent.com/7189244/28195205-1ced75ca-6873-11e7-86db-80556f8cd965.png)

**Comment by z-song** [comment]
Can you show me the response contents of /admin/api/books?

**Comment by amun1303** [comment]
Here you are, thanks
![image](https://user-images.githubusercontent.com/7189244/28195548-1ba3d5c2-6875-11e7-8da2-ffcb8111bcf2.png)

**Comment by z-song** [comment]
Try:
`return BookInfo::where("title", "like", "%".$q."%")->paginate(null, ["book_id as id", "title as text"]);`

The option format of response should be like `{id: xxx, text : xxx}`.

**Comment by amun1303** [comment]
It's worked, thanks z-song so much
