### ISSUE TITLE
如何修改WangEditor的高度？

### ISSUE THREAD

**Issue by akazhuk** [z-song/laravel-admin#981]
![default](https://user-images.githubusercontent.com/9032762/28152077-1bad089e-67d1-11e7-8ed3-070d70b25cd5.png)
我这里的明显太矮了。。

**Comment by z-song** [comment]
```php
$form->editor(...)->rows(100);
```

**Comment by akazhuk** [comment]
@z-song zsong大大，rows是不是要自己写的？我这里设置后没有效果

**Comment by z-song** [comment]
Try:
```
$form->editor(...)->attribute('rows', 100);
```

**Comment by akazhuk** [comment]
@z-song 这个方法可以，谢谢z-song大神

**Comment by tmxd09887** [comment]
$form->editor('content','内容')->attribute('rows', 300);

修改高度无效啊
