### ISSUE TITLE
如何在grid里面查询mongodb的数据？

### ISSUE THREAD

**Issue by wonderful60** [z-song/laravel-admin#982]
### model
``` php
<?php

namespace App\Models;

use Jenssegers\Mongodb\Eloquent\Model;

class Qcloudapi extends Model
{	
	protected $connection = 'mongodb';
	protected $collection = 'qcloud_instances';
}
```
model是这样配置吗？

**Comment by z-song** [comment]
是的  有什么问题吗？

**Comment by wonderful60** [comment]
![qq20170713-182042](https://user-images.githubusercontent.com/2291007/28161949-0b482052-67f8-11e7-9547-80123180d909.png)

**Comment by wonderful60** [comment]
@z-song "encore/laravel-admin": "1.3.*"版本，麻烦了

**Comment by wonderful60** [comment]
更新到1.3.x-dev版本问题得到解决，非常感谢！(因为修改了静态资源，所以还需要处理一下这个问题https://github.com/z-song/laravel-admin/pull/807)
