### ISSUE TITLE
请问如何在添加word文件预览和编辑扩展，

### ISSUE THREAD

**Issue by Witype** [z-song/laravel-admin#984]
请问如何在添加word文件预览和编辑扩展，
谢谢

**Comment by z-song** [comment]
我也没有找到可用的word编辑器

**Comment by Witype** [comment]
刚才找了一下，然后找到了这个，https://github.com/PHPOffice/PHPWord#installation，

**Comment by z-song** [comment]
这个只是编程API，不是可视化编辑器，就不能在线预览和编辑了

**Comment by Witype** [comment]
继续找咯，找到了分享出来。
