### ISSUE TITLE
How to redirect to / after save the form?

### ISSUE THREAD

**Issue by amun1303** [z-song/laravel-admin#985]
As picture below, the Blue Lines is the normal direction. 
Form Home page, click to view the List Page. Choose one to Edit or Create new one. After click Submit, redirect to List page again.
![image](https://user-images.githubusercontent.com/7189244/28197131-0a8d69f6-687f-11e7-9bc2-65f2eadffcc2.png)

**So, how to redirect to Home page instead the List page after Save the form (the RED line)?**

**Comment by z-song** [comment]
Try:
```php
$form->saved(function () {
    return redirect('/admin/');
});
```

**Comment by amun1303** [comment]
Thank you so much

**Comment by 2670207** [comment]
Don't work  `return redirect('/admin/');` why?
