### ISSUE TITLE
建议laravel-admin还添加一个预置的管理设置功能

### ISSUE THREAD

**Issue by kalvincn** [z-song/laravel-admin#987]
建议laravel-admin还添加一个预置的管理设置功能,就是可以在后台添加字段储存设置选项

**Comment by z-song** [comment]
能描述得详细一些吗？

**Comment by myyeshang** [comment]
我理解的是，在Scaffold自动生成数据库和控制器的地方，可以预置一些常用字段，比如name，remark等，这样在反复生成不同的表的时候，不用每次都要重写一遍

**Comment by kalvincn** [comment]
@z-song 一般来说，使用laravel-admin建立的项目，比如说建立一个CMS的功能，他需要灵活配置一些字段用于前台调用，比如说TP的一些后台框架就做得比较好，像http://demo.dolphinphp.com/admin.php/admin

里面的系统》》配置管理，系统》》系统设置，在配置管理可以灵活的添加字段，用于在系统设置里面使用

**Comment by z-song** [comment]
关于后台系统设置，我觉得其实改动比较少，配置项也不多，所有就直接放在`config/admin.php`里面了

关于配置管理，有一个[参考](https://github.com/laravel-backpack/settings), 由于不是后台的必备功能，以后可以参考这个以package的方式来开发。

**Comment by kalvincn** [comment]
嗯，的确不多，但是这样配置起来会方便很多，个人意见，可以参考参考：）
赞一个，laravel-admin非常不错，使用起来很方便
