### ISSUE TITLE
Method hasGetMutator does not exist

### ISSUE THREAD

**Issue by aliakel** [z-song/laravel-admin#991]
Method Encore\Admin\Grid::__toString() must not throw an exception, caught ErrorException: Method hasGetMutator does not exist. (View: E:\xampp\htdocs\alkamal\resources\views\vendor\admin\grid\table.blade.php)

**Comment by linnenn** [comment]
这是什么原因，能说明一下吗

**Comment by jackwang1993** [comment]
"encore/laravel-admin": "1.6.10" 遇到同样的问题

**Comment by khukhrianskiy** [comment]
Try to remove from your grid/table.blade.php layout @if ( $grid->allowTools() ) condition. It worked for me

**Comment by charlesmu2014** [comment]
remove  $grid->showTools()，    It worked for me

**Comment by z-song** [comment]
Try to run `artisan view:clear`

**Comment by lizhufei** [comment]
我也出现这个问题，请问有谁解决没有

**Comment by z-song** [comment]
@lizhufei 运行一下`artisan view:clear`，  如果无效，检查一下你是否自定义过视图，内置视图每个版本都有可能会更新，对比一下出现问题的视图文件

**Comment by wgqi1126** [comment]
我也遇到了同样的问题，提示如下：
```
BadMethodCallException
Method Illuminate\Database\Eloquent\Collection::hasGetMutator does not exist.
```
debug了好久发现是上一个grid字段定义冲突导致的
`$grid->build('Build');`这个字段在Grid类里面已经定义了，用于build Grid，但是我的模型字段里面也出现了 build，所以就导致后面的一个字段在操作的时候 里面的 model 参数变化了，因为已经 build 过了。

当我将 `$grid->build('Build');` 改成 `$grid->column('build');` 报错就解决了。

所以这里有个坑的地方，建议在 controller 的 grid 里的内容的时候判断下 方法是否存在，存在的话换成 column 的方式。
