### ISSUE TITLE
Js bug in hasMany upload image

### ISSUE THREAD

**Issue by echeveria** [z-song/laravel-admin#995]
Hi.
If upload some images (no multipal upload) and save it. After this all image previw of images replafced from first image.
Problem may be is on $("input{$this->getElementClassSelector()}").fileinput({$options}); in File.php

**Comment by echeveria** [comment]
![screenshot from 2017-07-17 18-35-52](https://user-images.githubusercontent.com/1324586/28276031-6bd4154c-6b1e-11e7-994e-6e4e15fff37c.png)

**Comment by SpinyMan** [comment]
Take a look at https://github.com/z-song/laravel-admin/issues/613#issuecomment-314069847

**Comment by echeveria** [comment]
10x
