### ISSUE TITLE
关于helper权限问题

### ISSUE THREAD

**Issue by myyeshang** [z-song/laravel-admin#996]
我是新手，查看了文档和issues，想请教一个问题，常规的权限可以通过路由和方法里的权限检测来管理，helpers里面的那些方法scaffold和terminal如果用权限控制访问，因为我新加一个用户，虽然看不到菜单，但实际它是有访问权限的。如有看到请帮忙解答一下，谢谢

**Comment by z-song** [comment]
在app/Admin/routes.php里面修改：
```php
$middleware = ['middleware' => ['admin', 'web', 'admin.permission:allow,administrator']];
Admin::registerHelpersRoutes($middleware);
```
增加了一个中间件`admin.permission:allow,administrator`,表示只允许角色`administrator`访问helpers

**Comment by myyeshang** [comment]
@z-song 感谢回复，不过我试了一下，访问的时候不论是不是管理员，全被重定向到localhost:8000/admin路径去了，不知是什么原因

**Comment by z-song** [comment]
```php
$attributes = ['middleware' => ['web', 'admin', 'admin.permission:allow,administrator']];

Admin::registerHelpersRoutes($attributes);
```
`web`放在`admin`前面可行。

**Comment by myyeshang** [comment]
感谢，成功了
