### ISSUE TITLE
[help] once installed, but not found url

### ISSUE THREAD

**Issue by ngocnveva** [z-song/laravel-admin#997]
please check help me, i test on google cloud
http://104.154.200.45/laravel3
but when access link:
http://104.154.200.45/laravel3/admin => not found exception

**Comment by z-song** [comment]
In `config/admin.php`, change `prefix` to `laravel3/admin`

**Comment by ngocnveva** [comment]
thanks for reply, but i changed, it still not working. i had configured .htaccess from root folder as follow
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]

and change server.php in root folder to index.php

**Comment by ngocnveva** [comment]
in app/Admin/routes.php, i use default config, is correct?
Route::group([
    'prefix'        => config('admin.prefix'),
    'namespace'     => Admin::controllerNamespace(),
    'middleware'    => ['web', 'admin'],
], function (Router $router) {

    $router->get('/', 'HomeController@index');
});
