### ISSUE TITLE
form embeds 能不能实现保存数组？

### ISSUE THREAD

**Issue by Tairy** [z-song/laravel-admin#998]
比如下面格式的 json:

```
[{"key":"value"}, {"key":"value"},...]
```
找了好久，只想到了把表单的 name 强制用 attribute 方法改成数组的形式，这样 create 的时候是可以实现数据的提交，但是 edit 的时候没法填充数据，也没法保存，请问有更好的办法么？

**Comment by Tairy** [comment]
在模型层用 get 和 set 的方法对数据做了额外处理，不知道以后能不能加上特性。

**Comment by z-song** [comment]
因为每个人的需求不一样，所以推荐自己在模型里面用访问器和修改器来实现。

**Comment by xtzeng** [comment]
> 因为每个人的需求不一样，所以推荐自己在模型里面用访问器和修改器来实现。

有具体的例子参考下吗，$form->embeds('column_name',xx,function($form){
    $form->table('reward', __('xx), function ($table) {
                        $table->text('playerers', __('xx'));
                        $table->text('bonus', __('xx'));
} )  @casts column => json 获取不到数据
